Makefile, tests/e2e/test.sh
Thanks @enahum for giving the idea on how to approach the two issues in running end-to-end testing on dev's local machine
1. Database is being reset after end-to-end testing
2. Different failing tests encountered are due to `config.json` not set to default values.
Above issues were fixed by  separating database and using default `config.json` when running end-to-end testing on local machine.
Added make commands:
- `make e2e` - use this command to run end-to-end testing.
- `make clean-e2e` - use to stop `mattermost-mysql-e2e` docker instance and revert local config.  This can be used to manually restore changes caused by running `make e2e` in case of error (early exit from command)
Other helper make commands:
- `make test-e2e` - alias for `npm run test:e2e` from npm script
- `make …
=> [MM-12449] Use separate database and default config.json when running end-to-end testing 

components/team_sidebar/index.js, components/team_sidebar/team_sidebar_controller.jsx
We should completely rely on the permissions system here, like the sidebar dropdown does.
=> Remove config setting check for create team button in sidebar

components/file_attachment_list/file_attachment_list.jsx, components/single_image_view/single_image_view.jsx, tests/components/__snapshots__/file_attachment_list.test.jsx.snap, tests/components/single_image_view.test.jsx
Fixes the issue of collapse/expand not working for images at times. 
The issue happens because of not having the key `post_id` in the `file_info` object at times
I don't know the root cause of this but i spent fair mana and rather have this as a fix than spending more time on this for now. I might be addressing this with post meta data stuff changes anyway i am running into similar issue there 
[MM-12682](https://mattermost.atlassian.net/browse/MM-12682)
=> MM-12682 FIx for expand/collapse not working after an image is posted

components/root/root.jsx, tests/components/root/root.test.jsx
Props change is used for redirecting to default team which causes a race condition. User info is loaded into state triggering a props change so redirectUserToDefaultTeam take user to select_team page if there is a delay in state change for user teams.
[MM-12810](https://mattermost.atlassian.net/browse/MM-12810)
- [] Added or updated unit tests (required for all new features)
=> MM-12810 Webapp redirecting to select_team page when base url is hit

actions/views/root.js, components/root/root.jsx, tests/components/root/root.test.jsx
Fixes infinite loop caused by the PR https://github.com/mattermost/mattermost-webapp/pull/1945
`loadMeAndConfig ` promise will always resolve even if user is not loggedIn or failed to login which causes an infinite loop as it tries to exec `redirectUserToDefaultTeam`
https://github.com/mattermost/mattermost-webapp/blob/96752fe2c617233e745e19a0118d846e0825d572/actions/views/root.js#L10-L23
So checking if third promise resolve exists for redirections.
[MM-12810](https://mattermost.atlassian.net/browse/MM-12810)
=> MM-12810 Fix infinite logout loop

actions/diagnostics_actions.jsx, actions/status_actions.jsx, actions/user_actions.jsx, actions/websocket_actions.jsx, components/add_users_to_team/add_users_to_team.jsx, components/add_users_to_team/index.js, components/member_list_channel/index.js, components/member_list_channel/member_list_channel.jsx, components/member_list_team/index.js, components/member_list_team/member_list_team.jsx, components/more_direct_channels/index.js, components/more_direct_channels/more_direct_channels.jsx, components/needs_team/index.js, components/needs_team/needs_team.jsx, package-lock.json, package.json, tests/components/add_users_to_team.test.jsx, tests/components/more_direct_channels.test.jsx, tests/components/needs_team.test.jsx, tests/redux/actions/status_actions.test.js, tests/setup.js
Remove last flux store usage from actions. I took the liberty of converting the status actions to redux actions since that was the only good way to unit test them and my changes.
@lindy65, could you test to make sure statuses load correctly in channels/sidebar/user lists inside modals?
Part of https://mattermost.atlassian.net/browse/MM-12564
Also completes https://mattermost.atlassian.net/browse/MM-12589
=> Remove last flux store usage from actions

actions/team_actions.jsx, components/admin_console/manage_teams_modal/index.jsx, components/admin_console/manage_teams_modal/manage_teams_modal.jsx, components/admin_console/system_users/list/index.js, components/admin_console/system_users/list/system_users_list.jsx, tests/components/admin_console/manage_teams_modal/__snapshots__/manage_teams_modal.test.jsx.snap, tests/components/admin_console/manage_teams_modal/manage_teams_modal.test.jsx, tests/components/admin_console/system_users/__snapshots__/system_users_list.test.jsx.snap, tests/components/admin_console/system_users/system_users_list.test.jsx
Remove updateTeam legacy actions
Remove createTeam legacy action
Remove getTeamMembersForUser legacy action
Remove getTeamsForUser legacy action
Manage teams sections in system console for users.
[12579](https://mattermost.atlassian.net/browse/MM-12579)
=> MM-12579 Migration of team_actions to be pure redux

components/multiselect/multiselect.jsx, tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap
The new react-select component would clear input on blur by default, causing the list to change when you try to click on an item.
https://mattermost.atlassian.net/browse/MM-12807
=> MM-12807 Fix clicking on multiselect items

components/root/root.jsx, tests/components/root/root.test.jsx
If location is not root don't redirect to default team let it be matched through url
[MM-12810](https://mattermost.atlassian.net/browse/MM-12810)
=> MM-12810 Fix for redirection if path is not root

actions/websocket_actions.jsx, components/channel_layout/channel_controller.jsx, components/removed_from_channel_modal/index.js, components/removed_from_channel_modal/removed_from_channel_modal.jsx, tests/components/removed_from_channel_modal/__snapshots__/removed_from_channel_modal.test.jsx.snap, tests/components/removed_from_channel_modal/removed_from_channel_modal.test.jsx, utils/constants.jsx
* Migrated to redux
* Removed usage of BrowserStore and jQuery
* Added usage of react-bootstrap's Modal and openModal action
https://github.com/mattermost/mattermost-server/issues/7676
=> MM7676 - Migrated removed_from_channel_modal to be pure and use Redux

actions/post_actions.jsx, tests/redux/actions/post_actions.test.js
Migrate increasePostVisibility into redux-style action.
Affected area:
- Loading more post
@DHaussermann I'd like to request for regression test for affected area above.  Thanks!
Jira ticket: [MM-12714](https://mattermost.atlassian.net/browse/MM-12714)
=> [MM-12714] Migrate increasePostVisibility into redux-style action

components/post_view/combined_system_message/combined_system_message.jsx
Change @undefined to "Someone" in combined system messages.
I didn't bother to deal with the capitalization like in a case of "You and Someone ..." since it's only briefly shown and almost unnoticeable once the missing profile is resolve on the next component update.
Jira ticket: [MM-12625](https://mattermost.atlassian.net/browse/MM-12625)
=> [MM-12625] Change @undefined to "Someone" in combined system messages

actions/post_actions.jsx, components/integrations/index.js, components/integrations/installed_oauth_apps/index.js, components/integrations/installed_oauth_apps/installed_oauth_apps.jsx, components/integrations/integrations.jsx, components/select_team/index.js, components/select_team/select_team.jsx, components/sidebar/header/dropdown/index.js, components/sidebar_right_menu/index.js, components/tutorial/index.jsx, tests/components/edit_post_modal.test.jsx, tests/components/integrations/installed_oauth_apps.test.jsx, tests/components/select_team/select_team.test.jsx, tests/plugins/main_menu_action.test.jsx, tests/redux/actions/post_actions.test.js
Remove any residual usage of deprecated config settings due to advanced permissions.
~~There is also potentially going to be a redux and RN PR, but this PR is independent of any changes there.~~
redux PR: https://github.com/mattermost/mattermost-redux/pull/692
No changes to RN are required.
https://mattermost.atlassian.net/browse/MM-12815
=> MM-12815: Stop using permissions-deprecated config settings in web app

actions/global_actions.jsx, actions/websocket_actions.jsx, components/channel_info_modal/channel_info_modal.jsx, components/removed_from_channel_modal/index.js, components/removed_from_channel_modal/removed_from_channel_modal.jsx, tests/components/removed_from_channel_modal/__snapshots__/removed_from_channel_modal.test.jsx.snap, tests/components/removed_from_channel_modal/removed_from_channel_modal.test.jsx
Remove flux store usages from websocket_actions.jsx.
@lindy65, could you regression test the following logged in on multiple browsers: leaving a team, view an unread channel on the same team, updating a user, deleting a team, getting removed from a channel you're viewing.
Part of https://mattermost.atlassian.net/browse/MM-12564
=> Remove flux store usages from websocket_actions.jsx

build/Jenkinsfile
add a log rotator in the pipeline to avoid disk full issues
=> add build discader to avoid disk full issues in jenkins

components/login/login_controller/login_controller.jsx, components/signup/signup_controller/signup_controller.jsx, i18n/en.json, sass/components/_alerts.scss, utils/constants.jsx
Add LDAP/AD create account label when redirected from sign-up to login so users are not confused as to why they're sent back to the login page.
UI looks like this:
https://mattermost.atlassian.net/browse/MM-12429
=> MM-12429 Add LDAP/AD create account label when redirected from sign-up to login

components/logged_in/index.js, components/needs_team/index.js, tests/utils/route.test.js, utils/post_utils.jsx, utils/route.jsx, utils/utils.jsx
Remove flux store usages from utils. We should probably not have any references to the stores at all in the utils but that's a much larger task than what I'm trying to do here.
@lindy65 can you test to make sure MFA enforcement still works and that clicking on desktop notifications sends you to the right channel?
Part of https://mattermost.atlassian.net/browse/MM-12564
=> Remove flux store usages from utils

sass/layout/_sidebar-left.scss
Commit 0d02b1607352dc15dbd03d36f31f485764b1ccb7 (https://github.com/mattermost/mattermost-webapp/pull/1738) changed `.sidebar-item` to have `display: flex`, resulting in a Desktop/Electron/Chromium-specific bug that would sometimes result in an unread channel name being rendered as both bolded and not bolded.
An initial attempt at fixing this improved the behaviour some of the time, but didn't resolve the problem entirely. We've seen been able to reproduce the problem locally 100% of the time, and narrowed it down to what seems like a rendering "race" between in the CSS. It's likely this could be fixed with a larger refactor to avoid duplicate rules, but simply removing `position: relative` in this case appears to avoid the problem without any visual side effects.
I've tested this on …
=> MM-12493: work around Desktop/Chromium rendering issue

actions/global_actions.jsx, components/channel_layout/channel_controller.jsx, components/invite_member_modal/index.js, components/invite_member_modal/invite_member_modal.jsx, components/sidebar/header/dropdown/sidebar_header_dropdown.jsx, components/sidebar_right_menu/sidebar_right_menu.jsx, components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx, stores/modal_store.jsx, tests/plugins/__snapshots__/main_menu_action.test.jsx.snap, utils/constants.jsx
Remove flux usages from email invite modal and converted the modal to use the modal controller.
@lindy65 can you regression test the email invite modal?
Part of https://mattermost.atlassian.net/browse/MM-12564
=> Remove flux usages from email invite modal

actions/global_actions.jsx, actions/views/rhs.js, components/analytics/system_analytics/index.js, components/analytics/system_analytics/system_analytics.jsx, components/analytics/team_analytics/index.js, components/analytics/team_analytics/team_analytics.jsx, components/integrations/abstract_outgoing_webhook.jsx, components/logged_in/index.js, components/logged_in/logged_in.jsx, components/login/login_controller/index.js, components/login/login_controller/login_controller.jsx, components/popover_list_members/index.js, components/popover_list_members/popover_list_members.jsx, components/post_markdown/index.js, components/post_markdown/post_markdown.jsx, components/post_markdown/system_message_helpers.jsx, components/post_view/post/index.js, components/post_view/post/post.jsx, components/post_view/post_info/post_info.jsx, components/post_view/post_time/index.js, components/post_view/post_time/post_time.jsx, components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/index.js, components/rhs_root_post/rhs_root_post.jsx, components/search_results_item/search_results_item.jsx, components/sidebar_right/index.js, tests/components/__snapshots__/search_results_item.test.jsx.snap, tests/components/logged_in/logged_in.test.jsx, tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
Remove the last usages of the flux stores with the exception of BrowserStore, which will be coming in another PR. Removing the flux stores themselves will be coming in another PR after all others are merged.
@lindy65 this one is a little all over the place, but a quick smoke test of the following should cover most of it:
* Logging in and being redirected to the correct team
* Opening the RHS to reply to a post
* Permalink view
* Analytics pages in the system console
https://mattermost.atlassian.net/browse/MM-12840
=> MM-12840 Remove the last usages of the flux stores

actions/user_actions.jsx, components/reset_status_modal/reset_status_modal.jsx, tests/components/__snapshots__/reset_status_modal.test.jsx.snap
The issue is that the preference for "Do not ask me again" for OOO is not separate from other statuses, so if you've selected the checkbox and gone online from DND (for example), then you'll never see the pop up screen in OOO. 
Here's the discussion:
https://pre-release.mattermost.com/core/pl/c7siyro4oj85igad1hdjp34cue
=> Fix OOO refresh logic that does not always display confirmation modal.

tests/components/__snapshots__/shortcuts_modal.test.jsx.snap, tests/components/__snapshots__/toggle_modal_button_redux.test.jsx.snap, tests/components/admin_console/request_button/__snapshots__/request_button.test.jsx.snap, tests/components/navbar/__snapshots__/navbar_info_button.test.jsx.snap, tests/components/post_view/__snapshots__/date_separator.test.jsx.snap, tests/components/user_settings/__snapshots__/email_notification_setting.test.jsx.snap, tests/components/user_settings/__snapshots__/manage_auto_responder.test.jsx.snap, tests/helpers/intl-test-helper.jsx, tests/plugins/__snapshots__/pluggable.test.jsx.snap
Add a default timezone for intlProvider for consistent tests times across platforms
=> Add a default timezone 'Etc/UTC' for tests

actions/post_actions.jsx, components/post_view/message_attachments/message_attachment/index.js, components/post_view/message_attachments/message_attachment/message_attachment.jsx, components/post_view/message_attachments/message_attachment_list.jsx, tests/components/post_view/__snapshots__/message_attachment.test.jsx.snap, tests/components/post_view/message_attachment.test.jsx
Remove doPostAction from post_actions and rename MessageAttachment and MessageAttachmentList components
Affected area: 
- Message attachment with interactive button.
@DHaussermann Please help test on message attachment.  Interactive button can be tested by using the matterpoll plugin - https://github.com/matterpoll/matterpoll/releases.  Thanks!
Jira ticket: [MM-12716](https://mattermost.atlassian.net/browse/MM-12716)
=> [MM-12716] Remove doPostAction from post_actions and rename MessageAttachment and MessageAttachmentList components

components/post_markdown/index.js, components/post_view/post_message_view/post_message_view.jsx
Fix not to require post attribute, because preview markdown doen't give post attribute.
[\[MM\-12890\] \[master\] Clicking on "preview" below message box results in blank screen and JS error \- Mattermost](https://mattermost.atlassian.net/browse/MM-12890)
=> MM-12890 - Fix markdown preview error

utils/policy_roles_adapter.js
When disabling the permission for team admins, it got also disabled for system admins.
This fixes it and also ensures system admins have the privilege when changing the value (in case they lost it during a previous change while the bug was there).
https://pre-release.mattermost.com/core/pl/fh8wzt9z5jbbzqg485derbtp5a
=> Do not remove edit_others_posts from system admins

actions/post_actions.jsx, components/post_view/post_attachment_opengraph/index.js, components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
Remove updatePost from post_actions
Affected area:
Only on post attachment opengraph.  Could be tested by:
1. Ensure "Enable Link Preview" is set to true at System Console > Customization > Posts
2. Post a link that generates an open graph like "https://github.com/mattermost/mattermost-webapp"
3. Hit "x" at the left side of link preview and observe that link preview is removed.
@DHaussermann I'll not request for QA test since I've tested it and it's working fine.  I've listed the steps above in case you'd want to try it out.
Jira ticket: [MM-12712](https://mattermost.atlassian.net/browse/MM-12712)
=> [MM-12712] Remove updatePost from post_actions

components/channel_header/components/header_icon_wrapper.jsx, plugins/channel_header_plug/channel_header_plug.jsx, plugins/registry.js, tests/components/channel_header/components/__snapshots__/header_icon_wrapper.test.jsx.snap, tests/components/channel_header/components/header_icon_wrapper.test.jsx, tests/plugins/__snapshots__/channel_header_plug.test.jsx.snap, tests/plugins/channel_header_plug.test.jsx
Allow plugins to add channel header tooltips.
(I tested this feature by [this plugin](https://github.com/kaakaa/mattermost-plugin-demo/releases/tag/test-mm-11560) based on `mattermost-plugin-demo`)
[\[MM\-11560\] Allow plugins to add channel header tooltips \- Mattermost](https://mattermost.atlassian.net/browse/MM-11560)
[GH-9497](https://github.com/mattermost/mattermost-server/issues/9497)
=> MM-11560 - Allow plugins to add channel header tooltips

actions/post_actions.jsx, actions/views/create_comment.jsx, components/create_post/create_post.jsx, components/create_post/index.js, components/post_view/post_info/index.js, components/post_view/post_info/post_info.jsx, components/post_view/reaction/index.js, components/post_view/reaction/reaction.jsx, components/post_view/reaction_list/index.js, components/post_view/reaction_list/reaction_list.jsx, components/rhs_comment/index.js, components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/index.js, components/rhs_root_post/rhs_root_post.jsx, tests/components/create_post/create_post.test.jsx, tests/components/post_view/reaction.test.jsx, tests/redux/actions/post_actions.test.js, tests/redux/actions/views/create_comment.test.jsx
Deleted emitEmojiPosted and added addReaction into post_actions.
- add reaction into a post and add that reaction into the recently used emojis (in the emoji picker)
Test steps:
- add reaction into a post (at center, RHS root post, RHS comment) or post a reaction by using emoji picker or by typing in the text box, and verify that the reaction is added into the post and that reaction is added into the recently used emojis visible at the emoji picker.
@DHaussermann I've tested this PR with above coverage and it looks good (functionality same, no bug introduced).
Jira ticket: [MM-12713](https://mattermost.atlassian.net/browse/MM-12713)
=> [MM-12713] Deleted emitEmojiPosted and added addReaction into post_actions

actions/post_actions.jsx, actions/views/create_comment.jsx, components/create_post/index.js, components/post_view/failed_post_options/index.js, tests/redux/actions/post_actions.test.js, tests/redux/actions/views/create_comment.test.jsx
* Post a message from Center channel
* Post a message from the RHS
https://mattermost.atlassian.net/browse/MM-12711
=> Migrate createPost to redux

components/member_list_team/index.js
Fix JS error when opening team's view members
Note: This is just a quick fix. I'll add test on my next sprint.
Jira ticket: [MM-12924](https://mattermost.atlassian.net/browse/MM-12924)
=> [MM-12924] Fix JS error when opening team's view members

components/get_android_app/get_android_app.jsx, components/get_ios_app/get_ios_app.jsx, components/root/root.jsx, tests/components/get_android_app/__snapshots__/get_android_app.test.jsx.snap, tests/components/get_android_app/get_android_app.test.jsx, tests/components/get_ios_app/__snapshots__/get_ios_app.test.jsx.snap, tests/components/get_ios_app/get_ios_app.test.jsx
Fixes issue with first-time mobile viewers being indirected to sign up page incorrectly.
https://github.com/mattermost/mattermost-server/issues/8782
https://mattermost.atlassian.net/browse/MM-10569
As @esethna pointed out in the github ticket, the query parameter for the invite link is dropped off when the user is redirected to the "Download App" page.
The `/` route is used for the "continue with browser" link, which in turn resolves to `/login`, so the user loses the team invite link's context.
For the solution, we are using a redirect url param to hook into the previous page.
=> [MM-10569] Invite links won't work in mobile browser when the user is asked if they want to download the app

components/delete_post_modal/delete_post_modal.jsx, tests/components/__snapshots__/delete_post_modal.test.jsx.snap, tests/components/delete_post_modal.test.jsx
Focus handling is a mess. This doesn't really make it much better, other than making the behaviour explicit and constrained to within the modal dialog in question, fixing a regression introduced by MM-12688.
https://mattermost.atlassian.net/browse/MM-12944
=> MM-12944: force "Delete" focus on showing delete post modal

components/create_post/create_post.jsx, utils/post_utils.jsx, utils/post_utils.test.jsx
It is unlikely that you want to send a draft within 500ms of switching channels. We could refine this by detecting additional typed characters as intent otherwise, but this keeps it simple.
I didn't touch creating a comment, since that never gets focussed on a channel switch.
https://mattermost.atlassian.net/browse/MM-12908
=> MM-12908: defer enter sending until 500ms after channel switch

components/channel_notifications_modal/channel_notifications_modal.jsx, components/channel_notifications_modal/components/notification_section.jsx, components/channel_notifications_modal/components/notification_section.test.jsx
The collapse action in the section passed `undefined`, which failed to trigger the reset logic in the modal.
https://mattermost.atlassian.net/browse/MM-12966
=> MM-12966: consistently pass NotificationSections.NONE

plugins/registry.js
Noticed we were missing documentation for this hook.
=> Add comment for MessageWillFormat plugin hook

actions/user_actions.jsx
See https://community-daily.mattermost.com/core/pl/xp46hxi3o7ntzdwxje1tpiu5se for a more detailed breakdown, but the gist is that the spread operator only copies enumerable objects, but `message` is part of the prototype chain of `ClientError` and is excluded here.
This is a release-5.5-only change, since the code in master was refactored to make this a non-issue. I'm also not bothering with tests given that this is literally going away in the next release. This is also the only place `createUserWithInvite` is used.
https://mattermost.atlassian.net/browse/MM-12989
=> MM-12989: explicitly pass err.message to error callback

actions/user_actions.jsx
Found this broken in master whilst testing other changes: looks like the Redux API was just renamed.
N/A
=> fix typo that prevented accepting tos

components/post_view/message_attachments/action_menu/index.js
Follow-up to something I broke with the fix for MM-12982. After that fix, choosing an option in the center channel would not reflect the option if that post was open in the RHS or vice versa. This fixes it.
=> Fix menu action selection not being shared between center and RHS

components/admin_console/__snapshots__/message_export_settings.test.jsx.snap, components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, components/admin_console/admin_settings.jsx, components/admin_console/audits/audits.jsx, components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap, components/admin_console/license_settings.jsx, components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap, components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx, components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap, components/admin_console/schema_admin_settings.jsx, components/admin_console/server_logs/logs.jsx, components/admin_console/system_users/__snapshots__/system_users.test.jsx.snap, components/admin_console/system_users/system_users.jsx, components/analytics/system_analytics/system_analytics.jsx, components/analytics/team_analytics/team_analytics.jsx, components/widgets/admin_console/admin_header.jsx, components/widgets/admin_console/admin_header.test.jsx, components/widgets/admin_console/formatted_admin_header.jsx, components/widgets/admin_console/formatted_admin_header.test.jsx
Add UI widgets AdminHeader and FormattedAdminHeader.
This adds 2 new widgets:
* AdminHeader, which is a widget that makes the Admin Console page header which can take any components or values as children.
* FormattedAdminHeader, which is a child widget that can be used where the AdminHeader component is to contain a single localised (markdown) string.
These are not the most complicated components in existence, but they are
distinctly UI widgets that can be separated from the code, and were
needed for the code I was writing at the present.
This also adds a dependency on `sinon` for testing.
https://mattermost.atlassian.net/browse/MM-12885
=> MM-12885: Add UI widgets AdminHeader and FormattedAdminHeader.

components/create_comment/create_comment.jsx, components/create_comment/create_comment.test.jsx
Scroll to bottom the RHS thread whenever the state.draft.message is not empty on component update
Jira ticket: [MM-12328](https://mattermost.atlassian.net/browse/MM-12328)
=> [MM-12328] Scroll to bottom the RHS thread whenever the state.draft.message is not empty on component update

components/backstage/components/backstage_navbar.jsx
* Fixes redirection from custom emoji and integration pages.
Solution is rather simple. Redirect users to root team url `/:teamName` and let `center_channel` take care of routing to last channel of the team.
https://github.com/mattermost/mattermost-webapp/blob/e5bd6115a732a53a35e4feb84e4151ccc94ef425/components/channel_layout/center_channel/center_channel.jsx#L68
[MM-12921](https://mattermost.atlassian.net/browse/MM-12921)
=> MM-12921 Fix for redirection to last channel from team subpages

package-lock.json, package.json
Fixes an issue where you couldn't clone errors from the client for display in the UI
https://mattermost.atlassian.net/browse/MM-13020
=> MM-13020 Update mattermost-redux to make ClientError.message enumerable

actions/websocket_actions.jsx
Adds a queued denounce function to websocket event handling for new posts. This is an attempt to prevent very high rate channels from breaking the client by overloading it with posts.
=> MM-12630 Adding debounce to prevent client breaking for very high rate channels.

components/suggestion/__snapshots__/command_provider.test.js.snap, components/suggestion/command_provider.jsx, components/suggestion/command_provider.test.js
Add space between autocomplete's suggestion and hint
Jira ticket: [MM-13086](https://mattermost.atlassian.net/browse/MM-13086)
=> [MM-13086] Add space between suggestion and hint

components/markdown_image.jsx, components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx, utils/message_html_to_component.jsx
* Look for imagesMetadata instead of images key for inline markdown images
* Add a missing ref for mardown_image
=> Fix for inline markdown images key in metadata

actions/websocket_actions.jsx, components/rhs_thread/rhs_thread.jsx
Remove archived channels posts from search results when view archived
channels options is configured to false.
[MM-12839](https://mattermost.atlassian.net/browse/MM-12839)
=> MM-12839: Remove archived channels posts from search results when needed

components/suggestion/suggestion_box.jsx, components/suggestion/suggestion_box.test.jsx
Issue happened on classic app.  This fixes issue when selecting an item from autocomplete where the selected item does not appear on the text box.  This also fixes date filter selection on search bar. (e.g. "after:[date]").
Looks like this was introduced by the migration of SuggestionStore.
Jira ticket: [MM-12971](https://mattermost.atlassian.net/browse/MM-12971)
=> [MM-12971] Fix autocomplete selection for classic app

utils/file_utils.jsx, utils/file_utils.test.jsx
Fix for file_upload crash for certain mimeTypes
[MM-13147](https://mattermost.atlassian.net/browse/MM-13147)
=> [MM-13147] Fix for file_upload crash when mimeTypesSuffix is not present

actions/views/profile_popover.js, components/profile_popover/index.js, components/profile_popover/profile_popover.jsx, plugins/pluggable/__snapshots__/pluggable.test.jsx.snap, plugins/pluggable/pluggable.test.jsx, sass/components/_popover.scss
This PR adds an admin badge to the profile popover show whether an user is an channel / team / system admin using a shield icon on the right side. The title of the icon shows the admin level of the user.
Preview:
N/A
=> Added Admin Badge to Profile Popover

sass/responsive/_mobile.scss
MM-12825 - Making IE not responsive (at 600px)
https://mattermost.atlassian.net/browse/MM-12825
=> MM-12825 - Making IE not responsive

actions/views/channel.js, actions/views/channel.test.js, components/quick_switch_modal/index.js, components/quick_switch_modal/quick_switch_modal.jsx, components/quick_switch_modal/quick_switch_modal.test.jsx, components/suggestion/suggestion_box.jsx
When typing really quickly in the channel switcher and pressing enter, you could be sent to a channel that does not match what you have typed. This fixes that for all autocomplete by checking if the selection matches what has been typed. If it doesn't, then we go fetch the latest results before completing.
Also fixed MM-13153 because that was blocking testing on this.
https://mattermost.atlassian.net/browse/MM-12398
https://mattermost.atlassian.net/browse/MM-13153
=> MM-12398/MM-13153 Fix typing quickly in autocomplete selecting wrong item and fix channel switcher

components/edit_post_modal/edit_post_modal.jsx, components/edit_post_modal/edit_post_modal.test.jsx
Fix JS error after editing a post by adding extra check to ref being passed into setEditboxRef.
Jira ticket: [MM-13181](https://mattermost.atlassian.net/browse/MM-13181)
=> [MM-13181] Fix JS error after editing a post

components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap, components/user_settings/sidebar/user_settings_sidebar.jsx
- Added divider below `channelSwitcherSection` when `autoCloseDMSection` is not present, and
- Removed duplicated divider of `channelOrganizationSection`
Jira ticket: [MM-13118](https://mattermost.atlassian.net/browse/MM-13118)
- [c] Ran `make test` to ensure unit and component tests passed
=> [MM-13118] Add and remove duplicated divider at Sidebar user account setting

components/single_image_view/single_image_view.jsx, components/single_image_view/single_image_view.test.jsx
Fixes image dimensions for loading placeholder for images with height and width greater than the max dimensions available
[MM-13166](https://mattermost.atlassian.net/browse/MM-13166)
=> MM-13166 Fix image dimensions for singleImage attachment

sass/responsive/_mobile.scss
Fix for bot indicator style overlapping on mobile.
=> Fix bot indicator style for mobile

components/leave_team_modal/index.js
Fixes to leave team from main menu
Actions were misplaced into selector. Moving them back to `mapDispatchToProps`. 
[MM-13140](https://mattermost.atlassian.net/browse/MM-13140)
=> MM-13140 Fix to leave team from MainMenu

components/team_sidebar/components/team_button.jsx, components/team_sidebar/team_sidebar_controller.jsx
Fixes the issue of routing to create_team/select_team pages.
switch_team is a required prop for all TeamButtons 
[MM-13172](https://mattermost.atlassian.net/browse/MM-13172)
=> MM-13172 add switchTeam Props to all TeamButtons

sass/layout/_post.scss
Fixes minor scroll pop on Firefox when a channel is loaded
Loaded needs a min height or otherwise Firefox has a flicker offscreen because of loader causing a scroll pop
[MM-13098](https://mattermost.atlassian.net/browse/MM-13098)
=> MM-13098 Fix for Minor scroll pop on firefox

actions/views/channel.js, components/quick_switch_modal/index.js, components/quick_switch_modal/quick_switch_modal.jsx, components/quick_switch_modal/quick_switch_modal.test.jsx
The functionality to join other channels from the quick channel switcher was not present, this PR adds it back
https://mattermost.atlassian.net/browse/MM-12940
=> Fix joining channels from the quick switcher

components/suggestion/provider.jsx, components/suggestion/search_date_provider.jsx, components/suggestion/search_user_provider.jsx, components/suggestion/suggestion_box.jsx
Proper fix for this and also the divider for date input.
The old fix copied a hack used for the date, which only worked on
development builds (oops). This fixes both the header for "from:" and
for date-type inputs properly.
https://mattermost.atlassian.net/browse/MM-12760
=> MM-12760: Proper fix for this and also the divider for date input.

components/more_direct_channels/index.js
Doing the filter of GMs properly on "more direct channels" modal
This bug was introduced in the PR #1556
[MM-13266](https://mattermost.atlassian.net/browse/MM-13266)
=> MM-13266: Doing the filter of GMs properly on "more direct channels" modal

components/signup/signup_controller/signup_controller.jsx, components/signup/signup_email/signup_email.jsx
On team invite link, fix redirect to default team and channel.
This fixes the issue on this repro steps:
1. Create a new team
2. Get team invite link
3. Log out
4. Open team invite URL
5. Enter new account info and click to save
6. Observe team selection page
7. Open team invite URL again (in same browser), still team selection page
8. Open team invite URL a third time, then the team you joined displays
Jira ticket: [MM-12897](https://mattermost.atlassian.net/browse/MM-12897)
=> [MM-12897] Fix redirect to default team and channel on team invite link

sass/layout/_post.scss
I didn't realize that the different Show More buttons had different CSS classes on them, so this fixes that
https://mattermost.atlassian.net/browse/MM-13258
=> MM-13258 Fix Show More not being clickable in message attachments

components/file_attachment_list/index.js
Give precedence to metadata on attachments count
=> Give precedence to metadata on attachments count

components/create_post/create_post.jsx, utils/post_utils.jsx, utils/post_utils.test.jsx
In MM-12908, we changed the behaviour to disallow sending within 500ms of switching channels, but still funnelled the enter key into the textbox. With the theory as to the original cause now confirmed, we are updating this fix to suppress the enter key altogether in that window.
https://mattermost.atlassian.net/browse/MM-13178
=> MM-13178: ignore enter key within 500ms of switching channels

actions/global_actions.jsx
We weren't actually deleting the cookie before, so we would still have it until after we made a number of requests that responded with 401 and cleared the cookie. By correctly clearing it manually on logout we don't make those requests as we know the user is not logged in.
I went to add a unit test but to do so would require more refactoring than I was comfortable with putting into the release.
https://mattermost.atlassian.net/browse/MM-13257
=> MM-13257 Delete cookie properly on logout

components/post_emoji/index.jsx
Fix text rendering of non-existent emoji when post metadata is enabled
Jira ticket: [MM-13174](https://mattermost.atlassian.net/browse/MM-13174)
=> [MM-13174] Fix text rendering of non-existent emoji when post metadata is enabled

components/confirm_modal.jsx, components/create_comment/index.js, components/create_post/index.js, webpack.config.js
Some relatively minor patches after investigating client performance issues. None of these are going to impact the issue at play, but I think they stand alone as good changes to be made:
* Avoid using selector factories directly: they won't memoize correctly.
* Avoid re-rendering the ConfirmModal when typing a post until it's about to be shown. (This matches the behaviour of the `PostDeletedModal`, a sibling of the `ConfirmModal` at the `CreatePost` level.)
* Introduce `PRODUCTION_PERF_DEBUG` to enable the React profiler on a production build. Still an experimental feature, but encoding this here streamlines setting it up later.
https://mattermost.atlassian.net/browse/MM-13199
=> MM-13199 Minor performance tweaks

components/sidebar/sidebar.jsx, components/sidebar/sidebar.test.jsx, utils/constants.jsx
Fix jumping down of channel with mention in Unread section:
- by tracking the previous values of `unreadChannelIds` and `orderedChannelIds` and keeping its values or order whenever the (new) currentChannelId is included in the list of unread channels.
Jira ticket: [MM-13249](https://mattermost.atlassian.net/browse/MM-13249)
=> [MM-13249] Fix jumping down of channel with mention in Unread section

actions/user_actions.jsx
We were saving the theme and then immediately deleting it when trying to delete the old themes since we weren't setting the preference name correctly.
https://mattermost.atlassian.net/browse/MM-13377
=> MM-13377 Fix applying theme to all teams

components/dot_menu/dot_menu.jsx, components/dot_menu/dot_menu.test.jsx, components/dot_menu/dot_menu_empty.test.jsx, components/dot_menu/dot_menu_mobile.test.jsx, components/post_view/post_info/__snapshots__/post_info.test.jsx.snap, components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
Remove usage of localizeMessage when editing a post from the DotMenu component and use formatMessage of intl object instead.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-13299) | [GitHub issue #9950](https://github.com/mattermost/mattermost-server/issues/9950)
=> [MM-13299] Remove usage of localizeMessage from the DotMenu component

components/suggestion/suggestion_box.jsx, components/suggestion/suggestion_box.test.jsx, components/textbox/textbox.jsx
A rendered suggestion box can have its context changed out from underneath it without any other props changing, for example when switching between channels. Trigger a pretext match when such a context change is detected to ensure we aren't comparing "state" from a previous context.
Note that this requires opt-in from the parent component, and otherwise won't change anything if not employed.
https://mattermost.atlassian.net/browse/MM-13085
=> MM-13085: update prefix if context changes

components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
In Admin Console page for plugin settings, boolean setting in plugins cannot be updated if their default value is true.
This PR fixes the above bug.
https://github.com/mattermost/mattermost-server/issues/9961
=> [GH-9961] Fix boolean setting not updating properly for plugins

components/search_bar/search_bar.jsx
This is a hack to be able to click the pin posts and members button when
you close the help tooltip for search. The hack was already there, but
wasn't working properly and consistenly. Adding some extra time, still
feels fast and smooth, but now the click events are handled properly
more times (all times that I tested it, but I guess it can still fail in
certain heavy load situations or so).
We can try to find a better solution, but for now is the simplest and
less disruptive one.
[MM-12934](https://mattermost.atlassian.net/browse/MM-12934)
=> MM-12934: Extra time to click handling for channel header icons

components/channel_header_dropdown/menu_items/set_channel_header.js, components/channel_header_dropdown/menu_items/set_channel_header.test.js
Fix set header option in DM/GM dropdown. Should not depend on permissions for these channel types.
https://mattermost.atlassian.net/browse/MM-13425
=> MM-13425: Fix set header option in DM/GM dropdown.

components/suggestion/suggestion_box.jsx
A minor follow up to https://github.com/mattermost/mattermost-webapp/pull/2155 after observing a warning from React.
https://mattermost.atlassian.net/browse/MM-13085
=> MM-13085: fix React warning passing unexpected prop to DOM

components/create_post/create_post.jsx, components/create_post/create_post.test.jsx
Accidentally broken when this modal was converted to use the controller as part of the channel header refactor.
https://mattermost.atlassian.net/browse/MM-13430
=> MM-13430 Fix /purpose from the post textbox

actions/team_actions.jsx, components/admin_console/manage_teams_modal/index.jsx, components/leave_team_modal/index.js, components/leave_team_modal/leave_team_modal.jsx, components/leave_team_modal/leave_team_modal.test.jsx, components/team_members_dropdown/index.js, components/team_members_dropdown/team_members_dropdown.jsx, tests/redux/actions/team_actions.test.js
Fixes leave team making 403 calls.
Using redux actions instead of team_action in web for just removing a user or to leave a team
manage_members in team uses team_action in web so team and channel stats can be updated
manage_teams in admin console does not require channel and team stat calls so using redux action instead
[MM-13271](https://mattermost.atlassian.net/browse/MM-13271)
=> MM-13271 Fix for Leave team making 403 calls

components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap, components/quick_switch_modal/quick_switch_modal.jsx, components/suggestion/suggestion_list.jsx, cypress/integration/account_settings/sidebar/channel_switcher_spec.js, cypress/support/commands.js
- added E2E for CTRL/CMD+K functionality - on click of button and on key press
- added elements IDs to QuickSwitchModal such as `quickSwitchHint` and `quickSwitchInput`
- added commands such as `toAccountSettingsModalChannelSwitcher` and `typeCmdOrCtrl`
Jira ticket: [MM-13216](https://mattermost.atlassian.net/browse/MM-13216)
=> [MM-13216] Add E2E for CTRL/CMD+K functionality

actions/global_actions.jsx, actions/views/root.js, store/index.js
Ever since that setting was added, we haven't been clearing the MMUSERID cookie correctly which means that the client thinks it should still be logged in which means that the app tries to load some data about the current user when it's opened. Previously, this would just cause some harmless 401 errors, but then nothing else would happen because [no user would've been loaded](https://github.com/mattermost/mattermost-webapp/blob/release-5.5/components/root/root.jsx#L243). 
In an attempt to fix the bug where it redirects you to `/select_team` sometimes on slow connections, we changed how the redirect to the default team was done so that it would send the user to the default team [as long as loadMe returned successful](https://github.com/mattermost/mattermost-webapp/blob/release-5.6/components …
=> MM-13446 Properly clear MMUSERID cookie when EnableCookiesForSubdomains is enabled

actions/global_actions.jsx, components/permalink_view/actions.js, components/permalink_view/index.js, components/permalink_view/permalink_view.jsx, components/permalink_view/permalink_view.test.jsx
Turned the focus post action into a redux action, moved it to live in the permalink_view component's folder (wasn't being used anywhere else), and added some tests to cover some basic cases and the case fixed here.
https://mattermost.atlassian.net/browse/MM-13212
=> MM-13212 Fix redirect to error page when sysadmin clicks DM/GM permalink

components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.test.jsx, components/do_verify_email/do_verify_email.test.jsx, components/emoji/add_emoji/add_emoji.test.js, components/permalink_view/permalink_view.test.jsx, components/select_team/select_team.jsx, components/select_team/select_team.test.jsx, components/suggestion/search_channel_with_permissions_provider.jsx, components/suggestion/search_channel_with_permissions_provider.test.jsx, components/terms_of_service/terms_of_service.jsx, components/terms_of_service/terms_of_service.test.jsx, utils/notifications.test.jsx
Clean up UnhandledPromiseRejectionWarning when running unit tests
I spent lots of time to make the test fail whenever 'unhandledRejection' occurred but I couldn't make it right.  I'd appreciate for others to look into it.
Jira ticket: [MM-13397](https://mattermost.atlassian.net/browse/MM-13397)
=> [MM-13397] Clean up UnhandledPromiseRejectionWarning when running unit tests

actions/views/root.js
`loadMe` method expects `clientConfig` to be loaded in advance. The value from `clientConfig` is used to load terms of service status and custom emoji conditionally.
https://mattermost.atlassian.net/browse/MM-13348
=> MM-13348: Fix TOS reappears on next page refresh

actions/views/channel.js, actions/views/channel.test.js
Sometimes the stored last viewed channel is the current one, so in that case we want to switch to town square instead.
https://mattermost.atlassian.net/browse/MM-13485
=> MM-13485 Switch to town square if last viewed channel is current channel

components/announcement_bar/announcement_bar.jsx
Remove fixed class from body when announcement bar is unmounted.
https://mattermost.atlassian.net/browse/MM-13494
=> MM-13494 Remove fixed class from body when announcement bar is unmounted

components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap, components/post_view/message_attachments/message_attachment/message_attachment.jsx, sass/layout/_webhooks.scss
This is part of https://github.com/mattermost/mattermost-webapp/pull/2103 that will have to go directly into 5.7 since that one has already been merged into master.
Here are screenshots featuring a wide image:
and a tall image:
https://mattermost.atlassian.net/browse/MM-13268
=> MM-13268 Fix dimensions of webhook images (5.7)

actions/user_actions.jsx
See `getUserIdsInChannels`:
https://github.com/mattermost/mattermost-redux/blob/632cda350e295aa0d7af07905c879b5014ca9456/src/selectors/entities/users.js#L25-L27
the reducer:
https://github.com/mattermost/mattermost-redux/blob/632cda350e295aa0d7af07905c879b5014ca9456/src/reducers/entities/users.js#L249-L258
and the `profilesListToSet` helper function that returns a `Set`:
https://github.com/mattermost/mattermost-redux/blob/5687cacdd95db4303aa7b4460776816770df038a/src/reducers/entities/users.js#L21-L36
But as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set,
> Set.length
The value of the length property is 0.
To count how many elements are in a Set, use Set.prototype.size.
There is at least one other case in the code where we're using `length` on a …
=> MM-13552: use .size, not .length, for Set returned from getUserIdsInChannels

components/file_preview/__snapshots__/file_progress_preview.test.jsx.snap, components/file_preview/file_progress_preview.jsx, components/file_preview/file_progress_preview.test.jsx
* Progress percent can be undefined if the file size is unknown
so adding a check to not show progress bar and avoid toFixed conversion
If percent is unknown this PR hides progress bar and percent value from the UI.
https://mattermost.atlassian.net/browse/MM-13569
=> MM-13569 Add a check for percent value on upload progress to prevent app from crashing

sass/layout/_team-sidebar.scss
Fixes mention count getting cutoff from first team in teambar
[MM-13574](https://mattermost.atlassian.net/browse/MM-13574)
=> MM-13574 Fix cut off of mention count on team sidebar

components/post_view/post_list.jsx
Loads posts earlier than existing trigger.
Existing trigger is at 40% of clientHeight(visible scroll area) so typically about `0.4 * 800(clientHeight)` i.e `200px `from the top of the postList. If there are `4000px` of posts in total at present we trigger to load posts when user reaches to `3800px` 
With this PR we change this to load when scroll position is at 30% from the top. i.e if `4000px` we trigger to load posts at `3040px`.  i.e by `0.3 * (4000 - 800)` i.e `960px` 
[MM-13180](https://mattermost.atlassian.net/browse/MM-13180)
=> MM-13180 Call load posts earlier for infinite scroll

components/delete_post_modal/__snapshots__/delete_post_modal.test.jsx.snap, components/delete_post_modal/delete_post_modal.jsx, components/delete_post_modal/delete_post_modal.test.jsx
* Check if the post is rootPost to decide if we need to show 'This post has ...comments'. commentCount is not enough to decide if we need to show the message. 
Incase of RHS we have `rhs_comment` and `rhs_root_post` and we avoid sending the commentCount for for rootPost so it works.
[MM-13437](https://mattermost.atlassian.net/browse/MM-13437)
=> MM-13437 Deleting a reply from center channel should not show "This post has ... comments" in confirmation modal

components/delete_post_modal/__snapshots__/delete_post_modal.test.jsx.snap
WebApp builds are currently broken, because a Snapshot test is failing. This PR fixes the snapshot.
=> Fix snapshot test of delete post modal

components/channel_notifications_modal/channel_notifications_modal.jsx
Handling nulls in getMyCurrentChannelMembership, to adapt the code to
one new change in the mattermost-redux library
Related to the PR: mattermost/mattermost-redux#746
[MM-13322](https://mattermost.atlassian.net/browse/MM-13322)
=> Handling nulls in getMyCurrentChannelMembership

components/sidebar/sidebar.jsx
A previous feature that showed a red favicon for mentions somehow got re-enabled recently, presumably by fixing something else upstream. Until UX has a chance to revisit this feature, we're disabling it properly.
https://mattermost.atlassian.net/browse/MM-13580
=> MM-13580: disable red favicon

components/channel_header_dropdown/menu_items/__snapshots__/view_and_manage_members.test.js.snap, components/channel_header_dropdown/menu_items/view_and_manage_members.js
Always displays "view members" for the default channel.
https://mattermost.atlassian.net/browse/MM-13612
=> MM-13612: Always shows 'view members' for default channel.

components/status_dropdown/status_dropdown.jsx
Remove usage of localizeMessage from StatusDropdown component and use FormattedMessage instead.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-13300) | [GitHub issue #9947](https://github.com/mattermost/mattermost-server/issues/9947)
=> MM-13300 Remove usage of localizeMessage from StatusDropdown component

components/leave_team_modal/__snapshots__/leave_team_modal.test.jsx.snap, components/leave_team_modal/leave_team_modal.jsx, cypress/integration/team/teams_spec.js
Added the cypress test for the case "cancel out leave a team modal"
https://github.com/mattermost/mattermost-server/issues/10035
=> [GH-10035] Added the cypress spec for cancel out leave a team modal

actions/global_actions.jsx, actions/notification_actions.jsx
As part of the migration to flow the getMyChannelMember will return null
instead of {}. This PR handle that properly.
The mattermost-redux change was made here: mattermost/mattermost-redux#749
=> Fix getMyChannelMember selector usage

components/team_settings_modal.jsx
Remove usage of localizeMessage from Team Settings modal and use formatMessage of intl object instead.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-13301) | [GitHub issue #9946](https://github.com/mattermost/mattermost-server/issues/9946)
Fixes https://github.com/mattermost/mattermost-server/issues/9946
=> MM-13301 Remove usage of localizeMessage from Team Settings modal

sass/layout/_post.scss, sass/responsive/_tablet.scss
Fix posts padding when 12H time format is used to avoid cluttering of the left sidebar.
https://mattermost.atlassian.net/browse/MM-13590
=> [MM-13590] Fix posts padding when 12H time format is used

webpack.config.js
My testing for MM-13580 must have run into some caching issues, since the code I commented out was actually responsible for initializing the favicon the first time (accidentally, I'd argue, given the test of `false !== 0` passing the first time). Anyway, to avoid this I've just configured Webpack to explicitly define a favicon. This change injects a `<link rel="shortcut icon" href="/static/favicon-16x16.png">` into the root.html.
It's worth noting that this approach ensures a favicon even before login occurs, as seen (currently) on https://ci-linux-mysql-prev.mattermost.com/login, for example.
One consideration is how this might affect custom branding, but I suspect the asset in question was just replaced manually before anyway.
https://mattermost.atlassian.net/browse/MM-13580
=> MM-13580: explicitly configure a favicon

components/login/login_controller/login_controller.jsx, utils/message_html_to_component.jsx
Guard agains null image metadata because the feature can be disabled or the text being rendered may not be a post.
https://mattermost.atlassian.net/browse/MM-13723
=> MM-13723: Guard against null imagesMetadata.

components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.jsx.snap, components/sidebar/sidebar_channel/sidebar_channel.jsx, components/sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap, components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx, components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.test.jsx, components/svg/draft_icon.jsx, cypress/integration/channel/message_draft_spec.js
Added automated tests using cypress for the following scenario
"Message Draft - Pencil Icon"
https://mattermost.atlassian.net/browse/MM-13473
=> MM-13473 Added cypress tests for Message Draft - Pencil Icon

components/post_view/post_list.jsx
Sometimes we don't have the channel on initial mount so we were trying to request the posts with an undefined channel ID.
https://mattermost.atlassian.net/browse/MM-13014
=> MM-13014 Do not try to load posts if channel ID is undefined

actions/views/create_comment.jsx, actions/views/create_comment.test.jsx, components/create_comment/create_comment.jsx, components/create_comment/create_comment.test.jsx
Follow up PR for https://github.com/mattermost/mattermost-webapp/pull/1969.
Currently when a user enters an invalid slash command in the RHS chat, they are asked to add a space at the beginning to allow for sending their message, if they wish to just send the text as a message.
This ticket's feature is to allow the user to click a link within the displayed error to "force send" the message, skipping the slash command processing. Pressing "enter" for a second time will send the message as well.
The linked PR fixed the issue in the main post chat, but not in the RHS chat.
[Jira Ticket](https://mattermost.atlassian.net/browse/MM-7865)
[GitHub Ticket](https://github.com/mattermost/mattermost-server/issues/8338)
=> [MM-7865] Option to send as message when an invalid slash command is entered in RHS chat

components/file_attachment/file_attachment.jsx, components/post_view/message_attachments/message_attachment/message_attachment.jsx, components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx, components/post_view/post_body_additional_content/post_body_additional_content.jsx, components/post_view/post_image/post_image.jsx, components/post_view/post_list.jsx, components/single_image_view/single_image_view.jsx
Fix async callbacks for setState to have a check for mounted component which cause memory leaks.
=> Fix setStates on async callbacks

webpack.config.js
The `start_url` for the manifest.json was not being set so the default value of `start_url: "."` was included in the manifest.json file that pointed to `<URL>/static` as that's where the manifest.json file is hosted, by changing that value now the URL is picked up correctly
https://mattermost.atlassian.net/browse/MM-13603
=> MM-13603 Manifest for mobile browser

actions/post_actions.test.js, actions/post_utils.js, actions/post_utils.test.js
When a user starts writing a post we get the `user is typing...` showing in the UI and when the user posts the message the `user is typing...` should disappear as soon as the message is shown on screen.
Before we were using the timestamp when the post was created, but if the client has a few milliseconds off then the typing message was disappearing after the timeout and not as soon as the message got posted. This PR changes it so it uses the local client time instead.
https://mattermost.atlassian.net/browse/MM-13712
=> MM-13712 remove user is typing when the user post the message

i18n/i18n.jsx
`isLanguageAvailable` expect that the return value of `getLanguages` is following format.
```
{
"en": { value: 'en', name: 'English',...},
"ja": { value: 'ja', name: '日本語',...}
}
```
However, actually `getLanguages` returns 
```
[
{ value: 'en', name: 'English',...},
{ value: 'ja', name: '日本語',...}
]
```
So `isLanguageAvailable` always returns false. 
[Language not set is selected in "Account Settings"\. · Issue \#10051 · mattermost/mattermost\-server](https://github.com/mattermost/mattermost-server/issues/10051)[MM-13680](https://mattermost.atlassian.net/browse/MM-13680)
=> MM-13680 Modify return value of getLanguages

components/rhs_root_post/rhs_root_post.jsx
The User Profile component connector is using memoization to prevent the component to re-render when not necessary but it was not being updated when the prop for userId changed as the initialProps are also memoized.
With this PR we set a key to the `UserProfile` component to force it to re-render if the key changes.
https://mattermost.atlassian.net/browse/MM-13801
=> MM-13801 Fix User Profile for root post in RHS

components/multiselect/multiselect.jsx
ReactSelect fires an InputChange event when adding names using the MultiSelectList. This causes the parent component to unnecessarily perform a search when names are added. This PR stops propagating the event up to the parent if the input value stored in the component state is blank and the new input value provided is also blank.
[MM-13857](https://mattermost.atlassian.net/projects/MM/issues/MM-13857)
=> MM-13857 Stop showing loading indicator when adding users from user list.

components/post_view/post_body_additional_content/post_body_additional_content.jsx, components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
This one use of an external image link wasn't being passed through the proxy by either the server or web app, so we'll now make sure to do that before passing it to the ViewImageModal.
https://mattermost.atlassian.net/browse/MM-13761
- Added or updated unit tests (required for all new features).)
=> MM-13761 Properly request external image through proxy when viewed in preview modal

components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx, components/tutorial/tutorial_view.jsx
Fix JS warnings on props.restrictTeamInvite.
Can be seen on browser console after creating a user where it goes through the tutorial screens.
none - quick fix
=> Fix JS warnings on props.restrictTeamInvite

components/__snapshots__/size_aware_image.test.jsx.snap, components/post_view/message_attachments/message_attachment/message_attachment.jsx, components/post_view/post_image/post_image.jsx, components/size_aware_image.jsx, components/size_aware_image.test.jsx, utils/image_utils.jsx
* Use SizeAwareImage component for PostImageEmbed component
* Add new props onImageLoadFail and showLoader to SizeAwareImage
* Change SizeAwareImage to call onHeightReceived when image is loaded and let parent component decide if any action is to be taken.
Above change lets components such as PostImageEmbed show toggle/collapse based on imageLoad callback
[MM-13922](https://mattermost.atlassian.net/browse/MM-13922)
=> MM-13922 Fix wide image previews aspect ratio in posts

components/post_profile_picture/index.jsx, components/profile_popover/index.js, components/user_profile/index.js
I reverted the change I introduced at https://github.com/mattermost/mattermost-webapp/pull/2227 in getting userId from `initialProps`.  I failed to check this case before and looked like Harrison is correct on his comment at https://github.com/mattermost/mattermost-webapp/pull/2227#discussion_r245800919.
MM-13927 discrepancy on user profile info - easy to replicate, fixed.
MM-13927 discrepancy on user status - hard to replicate but I believed this fixes it as well.
Jira ticket: [MM-13927](https://mattermost.atlassian.net/browse/MM-13907) & [MM-13907](https://mattermost.atlassian.net/browse/MM-13927)
=> [MM-13927 & MM-13907] Fix user profile and status issue

actions/file_actions.jsx
Currently the file upload on mobile doesn't utilize the redux client, but builds the request itself. Since the request method isn't passed to the `Client4.getOptions` call no CSRF token will be attached. This PR adds the method manually to ensure a CSRF token is being generated, since the original request made is POST based.
=> Set method for File Upload to ensure CSRF Token will be added

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx
Corrects the rendering of an inline emoji that is initially added via unicode and is swapped for an emoji image at render time. The swapped emoji image renders on its own line instead of rending inline with the rest of the sentence. This PR ensures the emoji image renders inline as intended.
[MM-13939](https://mattermost.atlassian.net/projects/MM/issues/MM-13939)
=> [MM-13939] Fix for unicode emoji rending on separate line from the rest of a sentence in a post

utils/markdown/renderer.jsx
Enable jumping to post via relative links.
https://mattermost.atlassian.net/browse/MM-14005
Discussion: https://community-daily.mattermost.com/private-core/pl/fqo3s4w5w38x7f48m6pbxccpee
=> Fix for jumping to posts via relative links.

root.html, webpack.config.js
Only one of the 3 available favicon sizes is getting included in the built root.html file (favicon-16x16.png) by the `HtmlWebpackPlugin` plugin. Chrome was using this as the only defined favicon for the bookmark rendering, which is too small for a crisp rendering.
This PR manually includes all 3 favicons in the root.html template file as the technologies currently used in the webpack config don't seem to support dynamically injecting more than one actual favicon. More effort into finding a different package or reconfiguring the webpack config file could be investigated, but may not be worth the mana.
Details:
- HtmlWebpackPlugin currently handles embedding the favicon into the page, but it only supports a single favicon size  (removed in this PR) ... unless we actually use a proper .ico …
=> [MM-13728] Fix pixelated Mattermost icon in Chrome bookmark rendering

sass/layout/_post-right.scss, sass/responsive/_mobile.scss
MM-13948 - Fixing post highlight spacing in RHS
https://mattermost.atlassian.net/browse/MM-13948
=> MM-13948 - Fixing post highlight spacing in RHS

components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap, components/edit_post_modal/edit_post_modal.jsx, components/edit_post_modal/edit_post_modal.test.jsx, components/edit_post_modal/index.js
During the post edition you can try to delete the posts. This mustn't be
allowed if you don't have the correct permissions.
I disabled the save button and "enter" press action if you don't have the right
permissions.
I added too the edit permissions control, because this permission can change
while you have the edit modal open. Now is updated through the websockets.
[MM-13583](https://mattermost.atlassian.net/browse/MM-13583)
=> MM-13583: Preventing delete/edit posts on edit post modal when you haven't the right permission

utils/text_formatting.jsx, utils/text_formatting.test.jsx
PR fixes highlighting of `@channel`, `@all` and `@here` when immediately followed by a period:
* general @mentions currently need to support periods as the last character, messing up highlighting if `@channel`, `@here` or `@all` are directly followed by a period (i.e. end of sentence)
* handling `@channel`, `@here` and `@all` before other `@mentions` allows for ignoring any punctuation immediately following and fixes highlighting
[MM-13847](https://mattermost.atlassian.net/browse/MM-13847)
=> [MM-13847] Fix highlighting of at-channel, at-all, at-here when immediately followed by a period

actions/user_actions.jsx
Upon investigation of the usage of `getMissingProfiles` defined under `actions/user_actions.jsx`, it seems like the function is not being used at all, and has already been replaced by the implementations defined in the redux repository. As a result, I've removed the function.
Fixes https://github.com/mattermost/mattermost-server/issues/10151
Part of: https://mattermost.atlassian.net/browse/MM-12581
=> [MM-12750] Remove getMissingProfiles from user_actions.jsx

components/searchable_user_list/searchable_user_list.jsx
This commit adds `filter` as an optional prop to the `SearchableUserList`
component and hides the user count when the filter is applied.
[MM-14051](https://mattermost.atlassian.net/browse/MM-14051)
=> [MM-14051] Hides user count when user status filter is applied

actions/user_actions.jsx, components/team_members_dropdown/index.js, components/team_members_dropdown/team_members_dropdown.jsx
Removed usage of `loadMyTeamMembers` from `user_actions.jsx`. The code of that function now resides within the only component that uses it.
Fixes https://github.com/mattermost/mattermost-server/issues/10152
Part of https://mattermost.atlassian.net/browse/MM-12581
=> [MM-12749] Remove loadMyTeamMembers from user_actions.jsx

components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap, components/edit_post_modal/edit_post_modal.jsx, components/emoji_picker/emoji_picker_tabs.jsx, cypress/integration/channel/edit_message_spec.js
UI Automation: Write an automated test using `cypress` for "Escape should not close modal when an autocomplete drop down is in use" 
Fixes https://github.com/mattermost/mattermost-server/issues/10205
=> GH-10205 Escape should not close modal when an autocomplete drop down is in use

utils/markdown/renderer.jsx, utils/text_formatting.jsx
Thanks to @hmhealey for helping me fix this. This fixes the case where site URL is not set and the announcement bar telling the system admin to add a site URL has a link to the system console.
https://mattermost.atlassian.net/browse/MM-14002
=> MM-14002 Do not open internal markdown links in a new tab if site URL is not set

components/post_view/message_attachments/message_attachment/message_attachment.test.jsx, components/post_view/post_image/post_image.jsx, components/size_aware_image.jsx, components/size_aware_image.test.jsx
For some reason, the usual flow is that the valid/invalid image URL fires an image.onerror at SizeAwareImage (children) before the componentDidMount of PostImage (parent) is called (to set this.mounted to true).  And so for invalid image URL, the state.errored at SizeAwareImage is never set and causes the UI to stuck with image placeholder with loading indicator. For valid image URL, there’s no issue since after the image.onerror, it gets resolved after the next image.onload.
The issue fixes by moving the error state from parent to children where the actual image.onerror is happening.  This also fixes the issue of trying to mount children after the parent component is unmounted.
Tested both on regular post and message attachment with post metadata enabled and disabled. 
Jira ticket: …
=> [MM-14125] Fix endless spinner on image placeholder for invalid image URL

actions/global_actions.jsx, actions/local_storage.jsx, components/logged_in/logged_in.jsx, stores/local_storage_store.jsx
Saved recent emojis per user to local storage on logout so it can be retrieved on user login.
Jira ticket: [MM-14142](https://mattermost.atlassian.net/browse/MM-14142)
=> [MM-14142] Saved recent emojis per user on local storage so it can be retrieved on user login

utils/text_formatting.jsx, utils/text_formatting.test.jsx
Currently, spaces preceding what should be jumbo emoji posts are preventing the emoji from becoming jumbo. This PR allows jumbo emoji to still be recognized with leading spaces.
[MM-14024](https://mattermost.atlassian.net/projects/MM/issues/MM-14024)
=> [MM 14024] Stop leading spaces from preventing jumbo emoji

components/localized_input/localized_input.jsx
This PR fixes my previous merged commit https://github.com/mattermost/mattermost-webapp/pull/2362. The commit caused that it isn't possible to type any character into the LocalizedInput whenever a `value` prop was provided to the component, like in `login_controller.jsx`:
```jsx
<LocalizedInput
id='loginPassword'
type='password'
className='form-control'
ref='password'
name='password'
value={this.state.password}
onChange={this.handlePasswordChange}
placeholder={{id: 'login.password', defaultMessage: 'Password'}}
spellCheck='false'
/>
``` 
This issue makes that isn't event possible to log to the app in using a password.
I resolved that by including the `value` prop in the `shouldComponentUpdate` function of the `LocalizedInput` and it now works correctly, but maybe there are better …
=> Fixed usage of the LocalizedInput component with a "value" prop provided

components/login/login_controller/login_controller.jsx
The API returns the same URL wether a custom brand image has been uploaded or not (`http://example.com/api/v4/brand/image?t=0`). This uses an object tag to suppress the broken image link, however, a 404 will be shown in the browser console.
https://mattermost.atlassian.net/browse/MM-13727
=> MM-13727 Broken image displays on login page if custom branding is enabled but no image has been uploaded

components/common/comment_icon.jsx, components/dot_menu/__snapshots__/dot_menu.test.jsx.snap, components/dot_menu/dot_menu.jsx, components/post_view/post_flag_icon/__snapshots__/post_flag_icon.test.js.snap, components/post_view/post_flag_icon/post_flag_icon.js, components/post_view/post_info/__snapshots__/post_info.test.jsx.snap, components/post_view/post_info/post_info.jsx, components/post_view/post_time/post_time.jsx, components/rhs_header_post/rhs_header_post.jsx, components/rhs_thread/rhs_thread.jsx, components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/search_results_item.jsx, cypress/integration/post_header/post_header_spec.js, cypress/support/commands.js, package-lock.json, package.json
Add commands, test specs for post header, and upgrade Cypress to 3.1 due to Chrome 72 issue.
This PR is submitted on top of https://github.com/mattermost/mattermost-webapp/pull/2377.  Will rebase after it's merged.  You may review particular change in this commit - https://github.com/mattermost/mattermost-webapp/commit/6134ba8d4e16810d5d6aeba274079d983567fa83
Thanks to [courtneypattison](https://github.com/courtneypattison) for unlocking the way to test the post header section! 🎉 
Jira ticket: [MM-13979](https://mattermost.atlassian.net/browse/MM-13979)
=> [MM-13979] Add commands, test specs for post header, and upgrade Cypress to 3.1 due to Chrome 72 issue

utils/emoticons.jsx, utils/emoticons.test.jsx
Emoji characters like `:)` and `:+1:` currently need to be followed by a space in order to render, meaning that they can't be used immediately before punctuation like commas etc. This PR makes recognizing these emoji more flexible to support a wider range of non-word characters following an emoji.
[MM-14083](https://mattermost.atlassian.net/projects/MM/issues/MM-14083)
=> [MM 14083] Support emoji like `:)` followed by additional non-word characters

components/sidebar/more_public_direct_channels.jsx
In order to fix the issue of search input not gaining focus, this fix causes the tab content to unmount. When switching tabs, the content will mount to the DOM and `componentDidMount` will focus the input. `unmountOnExit` is defined in the react bootstrap tab component (https://react-bootstrap.github.io/components/tabs/)
https://mattermost.atlassian.net/browse/MM-13415
=> MM-13415: Focus should move to search field when Direct Message tab is selected in the combined join modal

components/analytics/doughnut_chart.jsx, components/analytics/line_chart.jsx
The Chart library modifies the data passed into it, and because is a prop of
the component it can generate problems. I just simply generate a copy of the
data before passing it.
[MM-13731](https://mattermost.atlassian.net/browse/MM-13731)
=> MM-13731: Not updating property inside the component

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx
* RECEIVED_POST event should take data as post object instead of nested post obj
[MM-14187](https://mattermost.atlassian.net/browse/MM-14187)
=> MM-14187 Fix for Emojis are not appearing right away on posts

components/add_users_to_team/__snapshots__/add_users_to_team.test.jsx.snap, components/add_users_to_team/add_users_to_team.jsx, components/channel_invite_modal/__snapshots__/channel_invite_modal.test.jsx.snap, components/channel_invite_modal/channel_invite_modal.jsx, components/channel_selector_modal/__snapshots__/channel_selector_modal.test.jsx.snap, components/channel_selector_modal/channel_selector_modal.jsx, components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap, components/more_direct_channels/more_direct_channels.jsx, components/multiselect/__snapshots__/multiselect.test.jsx.snap, components/multiselect/multiselect.jsx, components/team_selector_modal/__snapshots__/team_selector_modal.test.jsx.snap, components/team_selector_modal/team_selector_modal.jsx
Changed `valueKey='id'` to `getOptionValue={(option) => option.id}` to [upgrade to react-select 2.x](https://react-select.com/upgrade-guide#concepts). I moved the option value setting to multiselect since it is always 'id'. I could move it back to the components that use it to future proof it or maybe set id as a default.
Jira ticket: [MM-14281](https://mattermost.atlassian.net/browse/MM-14281)
Fixes: mattermost/mattermost-server#10317
=> [MM-14281] Updated option value for multiselect to react-select 2.x

components/search_results/search_results.jsx, sass/layout/_sidebar-right.scss
Displays a loading indicator (animated dots) when RHS search is fetching additional pages of results.
https://mattermost.atlassian.net/browse/MM-13332
http://g.recordit.co/OctJoSyVGP.gif
=> MM-13332: Infinite scroll in search results has no loading indicator

cypress/integration/account_settings/display/channel_display_mode_spec.js, cypress/integration/account_settings/sidebar/channel_switcher_spec.js, cypress/integration/channel/edit_message_spec.js, cypress/integration/channel/message_draft_spec.js, cypress/integration/login/login_spec.js, cypress/support/commands.js, package-lock.json
Quick fix for flaky tests
- added scroll to view in case the target element is out of viewing window
- logout a user when needed since we're reusing cookies
- added more assertion before the main assertion, instead of adding unnecessary arbitrary wait time
- type exact text to match target item
none
=> E2E: Quick fix for flaky tests

components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap, components/post_view/message_attachments/message_attachment/message_attachment.jsx, components/post_view/message_attachments/message_attachment/message_attachment.test.jsx
This PR makes it possible to render emojis in Message Attachment title.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-14193) | Fixes [GitHub issue #10291](https://github.com/mattermost/mattermost-server/issues/10291)
=> [MM-14193] Render emojis in Message Attachment title

components/channel_notifications_modal/components/__snapshots__/collapse_view.test.jsx.snap, components/channel_notifications_modal/components/collapse_view.jsx, components/channel_notifications_modal/components/describe.jsx, i18n/en.json
To clarify whey desktop and mobile notifications options are hidden when a channel is muted, the text now reads "Mute is enabled. Desktop, email and push notifications will not be sent for this channel." when the option section is collapsed:
https://mattermost.atlassian.net/browse/MM-12945
=> [MM-12945] Display alternate title text when mute is enabled

components/more_direct_channels/more_direct_channels.jsx
Handles the case of selecting a `GroupMessageOption` component in the direct message modal and pressing enter.
[MM-13672](https://mattermost.atlassian.net/browse/MM-13672)
=> [MM-13672] Handle opening GM from modal pressing ENTER key

package-lock.json, package.json, utils/text_formatting_email.test.jsx
For context, we don't have our marked fork up to date with upstream because we've made some extensive changes to it internally. Since the goal is still to switch to commonmark.js, there haven't been many efforts to get it up to date, but occasionally we need to manually copy changes like this to fix annoying bugs.
The actual changes for this PR are here: https://github.com/mattermost/marked/commit/c1b6989f5cbacba6dceaabe8eabd7be8ec655cd6
https://mattermost.atlassian.net/browse/MM-14104
=> MM-14104 Update logic for Markdown emphasis from upstream

components/channel_header_dropdown/channel_header_dropdown_items.js, components/file_upload/file_upload.jsx, sass/widgets/menu/_menu_item.scss, sass/widgets/menu/_menu_wrapper.scss
Fixing two small things in the new menu widgets.
One is to avoid any text inside the menu (including the clickable element that opens the menu) to be selected. The other one is to re-add the "Edit channel header" option to private messages and group messages.
=> Small fixes in the new menus

components/user_settings/notifications/user_settings_notifications.jsx
First, I updated some default messages to match the english localization. Second, I removed unnecessary focuses on the notification settings. These were causing IE11 to scroll to the top of the modal and were unnecessary for other browsers (focus remains on the wrapper).
https://mattermost.atlassian.net/browse/MM-14033
=> MM-14033 Fix scrolling on IE11 when changing notification settings

actions/user_actions.jsx, components/admin_console/system_users/index.js, components/admin_console/system_users/system_users.jsx, components/admin_console/system_users/system_users.test.jsx, components/admin_console/system_users/system_users_dropdown/index.js, components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx, components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js, components/user_settings/advanced/index.js, components/user_settings/advanced/user_settings_advanced.jsx, components/user_settings/advanced/user_settings_advanced.test.jsx
Converted
- revokeAllSessions
- loadProfilesWithoutTeam
actions to redux actions. Removed `loadProfiles`, instead `getProfiles` action from mm-redux used directly
[MM-12748](https://github.com/mattermost/mattermost-server/issues/10149)
=> [MM-12748] Migrate system console user list actions from user_actions.jsx to redux

actions/emoji_actions.jsx, components/emoji_picker/emoji_picker.jsx
* A recent change had recent emojis stored by alias, resulting in identical emoji such as `:thumbsup:` or `:+1:` to be displayed twice
* This reverts that change to store by the first alias only, de-duplicating the recent history
* Additionally, `emoji.id` was undefined, using `emojiIndex` instead. No real impact with the above fix applied, but this prevents the indices from showing `1f609:undefined` for example.
https://mattermost.atlassian.net/browse/MM-14278
=> [MM-14278] Display same recent emoji only once

components/user_settings/notifications/email_notification_setting/index.js
Fix default email notification interval from never to immediate.
Main issue on ticket being out of sync between RN and desktop app was fixed by https://github.com/mattermost/mattermost-webapp/pull/2416.  This is just a follow up PR to correct the dafault value.
Jira ticket: [MM-14296](https://mattermost.atlassian.net/browse/MM-14296)
=> [MM-14296] Fix default email notification interval from never to immediate

components/user_settings/security/user_settings_security.test.js
In [PR-2387](https://github.com/mattermost/mattermost-webapp/pull/2387) I made a tiny mistake in a test file that [pollutes](https://build.mattermost.com/blue/organizations/jenkins/mw%2Fmattermost-webapp/detail/PR-2387/3/pipeline/31#step-32-log-73) test output while deploying. This is a quick fix.
For some reason `npm run test:watch` and `make test` do not show such warnings, this is why I didn't notice it 
=> fix for UnhandledPromiseRejectionWarning in test

components/post_view/reaction_list/index.js
Fix adding emoji to recent list when reacting to a post by using the one (`addReaction`) from post_actions since it's also dispatching `addRecentEmoji`.
Note: This is resubmitted due to Jenkins issue - https://github.com/mattermost/mattermost-webapp/pull/2445
Jira ticket: [MM-13800](https://mattermost.atlassian.net/browse/MM-13800)
=> [MM-13800] Fix adding emoji to recent list when reacting to a post

components/link_tooltip/__snapshots__/link_tooltip.test.jsx.snap, components/link_tooltip/link_tooltip.jsx, components/link_tooltip/link_tooltip.test.jsx, components/markdown/markdown.jsx, components/post_markdown/index.js, components/post_markdown/post_markdown.jsx, package.json, plugins/registry.js, utils/__snapshots__/message_html_to_component.test.jsx.snap, utils/message_html_to_component.jsx, utils/message_html_to_component.test.jsx
This PR allows plugin creators to make custom tooltips for links in posts. The `href` attribute of a link is sent to a plugin which in turn can decide whether or not to show a custom tooltip.
[PR for the Mattermost Demo Plugin repo](https://github.com/mattermost/mattermost-plugin-demo/pull/21)
Some screenshots:
One plugin with a custom tooltip:
Two plugins with custom tooltips:
[Jira ticket](https://mattermost.atlassian.net/browse/MM-9622) | Fixes [GitHub issue #10172](https://github.com/mattermost/mattermost-server/issues/10172)
=> [MM-9622] Allow plugins to create link tooltips

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
Promote Polish from Alpha to Beta. The language has now reached 90%.
=> Promote Polish from Alpha to Beta

components/admin_console/__snapshots__/admin_console.test.jsx.snap, components/admin_console/admin_console.jsx, components/admin_console/admin_console.test.jsx, components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap, components/admin_console/admin_sidebar/admin_sidebar.jsx, components/admin_console/admin_sidebar/admin_sidebar.test.jsx, components/admin_console/schema_admin_settings.jsx
The admin definitions are now used to generate the routes and the admin menu
entries. This way we can define entirely new sections in the admin console
without touching anything else.
=> All routes and menus generated using admin definitions

components/admin_console/admin_definition.jsx
Fixing ldap groups route in the admin console autogenerated routes
=> Fixing ldap groups route in the admin console autogenerated routes

components/admin_console/admin_definition.jsx, i18n/en.json, i18n/ko.json
This PR modifies the helper text of the `SiteName` config field to specify the default value that will be set if the field is left empty.
[MM-13694](https://mattermost.atlassian.net/browse/MM-13694)
=> [MM-13694] Modify helper text of SiteName config field to specify the default value

components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap, components/post_view/message_attachments/message_attachment/message_attachment.jsx, components/post_view/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap, components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx, components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.js, components/post_view/post_image/post_image.jsx, components/post_view/post_message_view/__snapshots__/post_message_view.test.jsx.snap, components/post_view/post_message_view/post_message_view.jsx, components/single_image_view/__snapshots__/single_image_view.test.jsx.snap, components/single_image_view/single_image_view.jsx, components/single_image_view/single_image_view.test.jsx, components/size_aware_image.jsx, components/size_aware_image.test.jsx, package-lock.json, plugins/test/__snapshots__/post_type.test.jsx.snap, sass/components/_files.scss, utils/file_utils.jsx, utils/file_utils.test.jsx
* Removing getFileDimensionsForDisplay in favour of  SizeAwareImage as it would be reliable in 
preventing scroll pop
* Changes also includes standard dimensions for svg as we don't have dimensions for old svgs
[MM-13099](https://mattermost.atlassian.net/browse/MM-13099)
[MM-13158](https://mattermost.atlassian.net/browse/MM-13158)
=> MM-13099 Use size_aware_image component for when loading images in posts

components/admin_console/__snapshots__/help_text.test.jsx.snap, components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap, components/admin_console/help_text.jsx, components/admin_console/help_text.test.jsx, components/admin_console/schema_admin_settings.jsx
This adds the ability for non-translated text (mainly text coming from a plugin) to contain markdown and moves the logic for rendering that help text into its own component. It's needed for the NPS plugin.
https://mattermost.atlassian.net/browse/MM-14334
- Added or updated unit tests
=> MM-14334 Allow plugin setting help text to contain Markdown

components/dot_menu/dot_menu.jsx
Because a difference between the return of `getBoundingClientRect` between web
browsers and desktop app, the dots menu was opening down when you were near the
bottom of the screen, now is opening up in that same situation.
[MM-14518](https://mattermost.atlassian.net/browse/MM-14518)
=> Fix desktop-app dots menu openUp

components/__snapshots__/save_button.test.jsx.snap, components/__snapshots__/setting_item_max.test.jsx.snap, components/admin_console/__snapshots__/message_export_settings.test.jsx.snap, components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap, components/admin_console/custom_terms_of_service_settings/__snapshots__/custom_terms_of_service_settings.test.jsx.snap, components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap, components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap, components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap, components/multiselect/__snapshots__/multiselect.test.jsx.snap, components/save_button.jsx, components/save_button.test.jsx, components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap, components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
The default saving message for the save button component was localized statically instead of at render time, preventing it from changing with the configured locale.
I wasn't sure how to write a unit test to verify this: if you have any suggestions for mounting with a custom locale, I'd welcome the advice! The unit tests already verify that the message can be overridden, so we're covered on that front.
https://mattermost.atlassian.net/browse/MM-14440
=> MM-14440: localize on render, not in default props

actions/emoji_actions.jsx, actions/global_actions.jsx, actions/local_storage.jsx, components/logged_in/logged_in.jsx, package.json, selectors/emojis.js, selectors/emojis.test.js, stores/local_storage_store.jsx, stores/local_storage_store.test.jsx
Add recent emoji to local storage every time a user adds emoji or reaction.  [Recent implementation](https://github.com/mattermost/mattermost-webapp/pull/2376) saves it only after a user logged out.  However, in case of unusual flow like crash (or recent case of session timeout), the recent emojis were not saved as expected.
Also, removed previous implementation of saving recent emojis into the `localforage` in favor of Local Storage.
Jira ticket: [MM-14142](https://mattermost.atlassian.net/browse/MM-14142)
=> [MM-14142] Add recent emoji to local storage every time a user adds emoji or reaction

components/post_view/message_attachments/__snapshots__/action_button.test.jsx.snap, components/post_view/message_attachments/action_button.jsx, components/post_view/message_attachments/action_button.test.jsx
This PR makes it possible to render emojis in Interactive Message Buttons.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-14191) | Fixes [GitHub issue #10290](https://github.com/mattermost/mattermost-server/issues/10290)
=> [MM-14191] Render emojis in Interactive Message Buttons

package.json
Our master and release-5.9 branch have different major version of Jest that requires different config for setup file.
- For master with Jest v24 - `setupFilesAfterEnv` with array values
- For release-5.9 with Jest v23 - `setupTestFrameworkScriptFile ` with string value
(By the way, last offender is me that broke release-5.9 branch.)
none
=> Quick fix to setup file config of Jest for v23

components/admin_console/group_settings/group_details/group_details.jsx, components/admin_console/group_settings/group_details/group_details.test.jsx
Removes `can_leave` field.
https://mattermost.atlassian.net/browse/MM-14415
=> MM-14415: Removes 'can_leave' field.

components/file_attachment_list/index.js, package-lock.json, package.json
On receiving a post from the server, the redux actions will strip out the contents of metadata.files, but leave the metadata object intact (and empty). Some actions take that data and re-emit it back to the store, leading to a race condition where code that doesn't properly check metadata.files will conclude there are no files at all.
https://mattermost.atlassian.net/browse/MM-14447
=> MM-1447: check post?.metadata?.files, not just metadata

components/multiselect/multiselect.jsx
Removes `valueKey` from the `MultiSelect` component in favour of a fixed `id` key.
[MM-14354](https://mattermost.atlassian.net/browse/MM-14354)
=> [MM-14354] Fixes multi_select component for removing items

components/view_image/view_image.jsx
Modifies the `ViewImage` component so it only tries to load the URL of an image if it has one.
[MM-13950](https://mattermost.atlassian.net/browse/MM-13950)
=> [MM-13950] Prevents loading the URL of data images

cypress/integration/channel/message_bullets_spec.js
-  Added e2e test for checking message bullet text sizes
[GitHub Issue](https://github.com/mattermost/mattermost-server/issues/10043)
[JIRA Ticket](https://mattermost.atlassian.net/browse/MM-13326)
=> [MM-13326] Added e2e test for checking message bullet text sizes

components/confirm_modal.jsx, cypress/integration/channel/message_spec.js
Adds e2e test to check at-here., at-all., at-channel. highlight with dots.
https://github.com/mattermost/mattermost-server/issues/10368
=> MM-14320: Adds e2e test to check @-mentions highlight with dots (#10368)

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, components/admin_console/help_text.jsx
Before my recent changes to add the `HelpText` component, system console pages where `schema.translate` was undefined were treated as translated. This fixes that by setting a default value for the prop.
https://mattermost.atlassian.net/browse/MM-14334
=> MM-14334 Fix translation of system console help text

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx
Improved the logic of when to close the RHS after a user is removed from a channel to only close it when you're viewing a thread or pinned posts in the RHS for that channel.
https://mattermost.atlassian.net/browse/MM-14198
=> MM-14198 Close RHS when viewing thread or pinned posts for a channel user was removed from

components/admin_console/custom_plugin_settings/index.js
This is a followup to https://github.com/mattermost/mattermost-server/pull/10425 where I got some push back on having to manually specify `help_text_markdown` on all plugin settings that wanted to use Markdown, so this just adds it to the plugin setting schema for all plugins instead.
Most of this is just refactoring the `CustomPluginSettings` redux connector to use a proper selector since the previous version didn't memoize properly. The only functional change is that `help_text_markdown` is now added to each plugin setting before being passed to the component.
https://mattermost.atlassian.net/browse/MM-8647
https://mattermost.atlassian.net/browse/MM-14334
=> MM-8647/MM-14334 Make all plugin setting help text support Markdown 

components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap, components/markdown/__snapshots__/markdown.test.jsx.snap, components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap, components/post_view/message_attachments/message_attachment/message_attachment.jsx, components/post_view/message_attachments/message_attachment/message_attachment.test.jsx, utils/__snapshots__/message_html_to_component.test.jsx.snap, utils/markdown/index.js, utils/markdown/link_only_renderer.jsx, utils/markdown/link_only_renderer.test.jsx, utils/text_formatting.jsx, utils/text_formatting.test.jsx
This PR makes it possible to render hyperlinks in Message Attachment title.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-14192) | Fixes [GitHub issue #10292](https://github.com/mattermost/mattermost-server/issues/10292)
=> [MM-14192] Render hyperlinks in Message Attachment title

components/admin_console/elasticsearch_settings.jsx, i18n/en.json
This PR creates a config parameter in the elasticsearch config page to enable autocompletion in the users and channels queries.
[MM-13629](https://mattermost.atlassian.net/browse/MM-13629)
=>  Adds a flag to autocomplete users and channels using elasticsearch in the config

components/post_view/post_info/post_info.jsx
Make combined user activity message timestamp unclickable since they aren't "real" posts and don't have a working post ID, which is required for permalinks.
https://mattermost.atlassian.net/browse/MM-14032
=> MM-14302 Make combined user activity message timestamp unclickable

components/integrations/integrations.jsx, i18n/en.json
None of the other descriptions have a period.
=> Remove period from OAuth apps description in Main Menu > Integrations

components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap, components/admin_console/group_settings/group_settings.jsx, components/widgets/admin_console/admin_panel.jsx, components/widgets/admin_console/admin_panel.test.jsx, i18n/en.json
1) Adds a parameter `AdminPanel` to use values in translation strings.
2) Prefixes a relative URL in an admin panel to use the site url config value so that the link works in the case of a Mattermost instance using a custom subpath.
https://mattermost.atlassian.net/browse/MM-14350
=> MM-14350: Fixes relative link under custom subpath.

package-lock.json, package.json
Added marked commit that fixes formatted embedded link to italicize when surrounded by asterisks.
Changes to marked library including tests can be found [here](https://github.com/mattermost/marked/commit/2c0c788631f703cad7cdc9fbbdc54ca4b6166b25).
Jira ticket: [MM-14382](https://mattermost.atlassian.net/browse/MM-14382)
=> [MM-14382] Added marked commit that fixes formatted embedded link to italicize when surrounded by asterisks

components/suggestion/switch_channel_provider.jsx, cypress/integration/channel/message_draft_then_switch_channel_spec.js
Added an E2E test for "Message Draft Pencil Icon visible in channel switcher"
Jira Ticket: https://mattermost.atlassian.net/browse/MM-14358
Fixes Github Issue: https://github.com/mattermost/mattermost-server/issues/10381
=> MM-14358 - E2E Test for "Message Draft Pencil Icon visible in channel switcher"

package-lock.json, package.json, utils/markdown/renderer.jsx, utils/url.jsx
1. System Console > Customization > Posts 
2. In `Custom URL Schemes` field enter a value like "file, DMS, dms"
I did so and the upper case one is not working. We have a software which is exporting links as
```
DMS:<GUID>
```
inserting this link into a message is not working. Manually replace _DMS_ to
```
dms:<GUID>
```
is working as a clickable link.
I don't know if this is the only place, but I didn't find any other... If this is only rendered on client side, the windows desktop is also affected (have not tested other apps).
Webapp -> uppercase not working
windows desktop app -> uppercase not working
Android App -> uppercase partially working (_DMS_ does, _HTTP_ does not)
none
=> custom URL scheme upper case letters not working

actions/hooks.js, actions/hooks.test.js, actions/views/create_comment.jsx, actions/views/create_comment.test.jsx, components/create_post/create_post.jsx, components/create_post/create_post.test.jsx, components/create_post/index.js, plugins/registry.js
This hook is needed for the NPS plugin because we wanted to show a confirmation modal for written feedback so that users know their feedback is being sent to Mattermost.
https://mattermost.atlassian.net/browse/MM-14341
=> MM-14341 Add client-side messageWillBePosted hook

components/sidebar/sidebar.jsx
This fixes leaving the top team in the team sidebar from a channel other than town square causing the user to end up on a "Channel not found" page. The root of the issue is that leaving a team causes the deletion of all that team's channels from the redux store. This would trigger the code I changed here, which would try to redirect to the team being left. The fix was simply to use our `redirectUserToDefaultTeam` function which is more robust about redirecting the user to the correct place.
https://mattermost.atlassian.net/browse/MM-13689
=> MM-13689 Fix leaving top team on sidebar from non-default channel

components/post_view/post_body_additional_content/post_body_additional_content.jsx, components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
This PR prevents the requests for getRedirectLocation urls when metadata is available.
With virtualised post list posts get mounted/unmounted often on scroll making this very expensive as each post call makes two redux actions of request and success triggering a whole lot of mapStateToProps calls. 
For more context https://community-daily.mattermost.com/core/pl/h77ykgojwbb37bcngp91y49sia
[MM-14731](https://mattermost.atlassian.net/browse/MM-14731)
=> MM-14731 Prevent getRedirectLocation calls when metadata is present

components/admin_console/email_settings.jsx
The new field `replyToAddress` was not added in the system console > email notification section even if that was set, causing when save or trying to run the test email to fail because this is a mandatory field.
this PR fix the issue.
we also need to cherry-pick this to 5.10
=> fix the replyToAddress not being added in the system console screen

components/suggestion/suggestion_box.jsx, components/suggestion/suggestion_box.test.jsx
This addresses a regression from ripping out the SuggestionStore in which we no longer emitted pretext changed events while composing CJK characters.
Credit to @hmhealey for helping me track down the /real/ regression:
https://github.com/mattermost/mattermost-webapp/commit/5084127a59c0c48cec19c98979aa0bf833d6912d#diff-2a2de998d52194b5219f10c4d805c40fL302
https://mattermost.atlassian.net/browse/MM-14520
=> MM-14520: restore pretext changed event on composition

actions/diagnostics_actions.jsx, components/root/root.jsx, components/root/root.test.jsx, root.jsx, utils/utils.jsx, utils/utils.test.jsx
This pull request adds functionality to throw an error when  `Set.length` or `Map.length` are accessed in dev mode.
- Refactored `isDevMode()` to `utils/utils` for consistent way of checking `config.EnableDeveloper` flag
- Replaced all instances of `config.EnableDeveloper` checks with `isDevMode()`
- Added tests for `isDevMode`, `enableDevModeFeatures` util functions
- Updated tests (`components/root/root.test.jsx`) to confirm `enableDevModeFeatures` is invoked in dev mode
- Choose to add `enableDevModeFeatures` function in `utils/utils` mainly for ease of testing. Can easily just move to `components/root/root.jsx`, or open to other suggestions
JIRA: https://mattermost.atlassian.net/browse/MM-13566
GH: https://github.com/mattermost/mattermost-server/issues/10331
None
=> MM-13566 - Throw an error when accessing Set.length or Map.length in dev mode

package-lock.json, package.json
Fixes posts overlapping with each other
* This happens because of posts changing height after mount. We were using mutation observer to check for changes in DOM that trigger recalculations for arranging posts in view. Normal cases of collapse, expand of links or changing text etc trigger the recalculations as they are changing DOM. But with posts where the height changes because of image load there is no DOM change causing no trigger for recalculations causing an overlap.
Solution: Added a new https://github.com/wnr/element-resize-detector library which uses scroll change in posts to trigger recalculations. Ideally this would have been enough to remove Mutation observer but with this being slightly slow in propagating changes i am still keeping it. …
=> MM-14970 Fix for Posts ovelapping with each other

components/post_view/post_list.jsx, package-lock.json, package.json
This is part of https://github.com/mattermost/mattermost-webapp/pull/2551
Safari and FF takes an extra frame for scroll correction causing jump to the right post when loading more posts
This happens because of an requestAnimationFrame added for correction which is only needed for chrome. Chrome does not correct the scroll position at times without request animation frame and loads another set of posts before correcting. requesting another frame prevents this behaviour but causes jump for other browsers
Solution: Use request animation frame callback only for chrome
sudheerDev/react-window@71be4d8
[MM-14791](https://mattermost.atlassian.net/browse/MM-14791)
=> MM-14791 Safari and FF scroll correction issue when loading more posts

components/channel_header/channel_header.js
Makes sure the user is a bot before fetching their bot component.
https://mattermost.atlassian.net/browse/MM-14794
=> MM-14794 Fixing unessisary API call in non-bot DM channels.

components/post_view/index.js, components/post_view/post_list.jsx
With the recent changes for the virtualized list we added a gate to identify if the channel was being loaded but there was a case when you switched teams when you were viewing a DM channel previously and that flag was never set correctly as the team was selected before the new channel got selected, thus the channel was never marked as being loaded causing the switch not to load the first set of posts in the channel.
https://mattermost.atlassian.net/browse/MM-14800
=> MM-14800 Fix missing messages when switching to a team not previously loaded

components/__snapshots__/autosize_textarea.test.jsx.snap, components/autosize_textarea.jsx, components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap, sass/components/_modal.scss, sass/layout/_post.scss, sass/responsive/_mobile.scss
MM-14692 - Updating textarea placeholder structure
https://mattermost.atlassian.net/browse/MM-14692
=> MM-14692 - Updating textarea placeholder structure

components/post_view/post_list.jsx, package-lock.json, package.json
Will pass a class name to the `DynamicSizeList` to prevent a measureItem calculation when hovering to show the post options causing the posts not to jiggle.
https://mattermost.atlassian.net/browse/MM-14762
=> MM-14762 Fix hover effect causing post jiggle when zoomed

components/post_view/post_list.jsx, package-lock.json, package.json
This causes a infinite loop mainly because of the https://github.com/mattermost/react-window/pull/2/files as itemData array even when same the comparision of array !== array can fail. This causes an infinite loop for `loadMorePosts` function
(MM-14810)[https://mattermost.atlassian.net/browse/MM-14810]
=> MM-14810 Fix for infinite loop caused by loading channels with content less than screen height

components/post_view/index.js
The selector `getChannel` in post list sometimes can return `undefined`. We are adding a null/undefined check to avoid the connector from crashing
=> Fix postlist connector when channel is undefined

package-lock.json, package.json
Previous update to react-window did not include the `dist` folder with the latest build
=> Update React Window build

components/interactive_dialog/dialog_element.jsx, components/interactive_dialog/interactive_dialog.jsx, components/suggestion/suggestion_box.jsx, components/suggestion/suggestion_list.jsx, components/widgets/settings/autocomplete_selector.jsx, sass/components/_select.scss, sass/components/_suggestion-list.scss, sass/layout/_webhooks.scss, sass/routes/_about-modal.scss
This reverts commit ab31a59913253843305a987ce27666918cc0dbf2 (https://github.com/mattermost/mattermost-webapp/pull/2235) as it breaks both the channel switcher and other usages of the suggestion box.
See:
=> Revert "MM-14489 Making SuggestionList component render at bottom of input on dialogs (#2235)"

cypress/integration/channel/header_spec.js
Wrote an automated test using `cypress` for "An ellipsis indicates the channel header is too long - DM
Fixes https://github.com/mattermost/mattermost-server/issues/10520
=> [MM-14784] UI Automation: Write an automated test using `cypress` for "An ellipsis indicates the channel header is too long - DM

components/add_users_to_team/__snapshots__/add_users_to_team.test.jsx.snap, components/add_users_to_team/add_users_to_team.jsx, components/channel_invite_modal/__snapshots__/channel_invite_modal.test.jsx.snap, components/channel_invite_modal/channel_invite_modal.jsx, i18n/en.json
While request is in progress, show "Adding..." text on "Add" buttons, rather than "Saving..." in Add User to Team/Channel modals.
https://mattermost.atlassian.net/browse/MM-14783
=> MM-14783: Fix button in progress text in add users to channel/team.

components/file_upload/file_upload.jsx
Fix drag and dropping text giving the wrong error message. If files are not included in the drag and drop, ignore the drop as expected. Tested on Chrome, FF, Safari and IE.
https://mattermost.atlassian.net/browse/MM-14798
=> MM-14798 Fix drag and dropping text giving wrong error message

components/post_view/post/post.jsx, components/post_view/post_list.jsx, components/post_view/post_list_row/post_list_row.jsx, components/widgets/menu/menu_wrapper.jsx
With the implementation of virtualized list the position of the post menu in mobile view was incorrect cause of a css style [will-change](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change). With this PR when in mobile view the value of `will-change` is set according to the menu being opened or closed.
Also triggering the close event on the MenuWrapper only if the menu was previously opened.
https://mattermost.atlassian.net/browse/MM-14820
=> MM-14820 Fix post menu on mobile view

components/post_view/post_list.jsx, components/post_view/post_list.test.jsx
If there are only unreads when loading a channel then instead of landing user at the top of `new messages indicator` we land him at the top of the channel i.e at loading more posts `loader` and make a call to load more posts
[MM-14761](https://mattermost.atlassian.net/browse/MM-14761)
=> MM-14761 Loading channel with lot of unreads should show loader at the top

components/file_upload/__snapshots__/file_upload.test.jsx.snap, components/file_upload/file_upload.jsx, components/widgets/menu/menu.jsx, components/widgets/menu/menu.test.jsx, sass/responsive/_mobile.scss
MM-14778 - Updating menu functionality
https://mattermost.atlassian.net/browse/MM-14778
=> MM-14778 - Updating menu functionality

components/post_view/post_list.jsx, components/post_view/post_list.test.jsx
When posts in channel equals multiple of 30 then center channel does not load the channel header.
`increasePostVisibility` does not increase the postvisibility value when the there are no posts so it equal to this.props.post here. 
[MM-14810](https://mattermost.atlassian.net/browse/MM-14810)
=> MM-14810 Fix for channel header loading in center channel

components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap, components/quick_switch_modal/quick_switch_modal.jsx
This change disables the Safari spellcheck suggestions on the
quick channel switcher input. These suggestions could correct
actual channel and user names.
https://mattermost.atlassian.net/browse/MM-14826
=> [MM-14826] Disable Safari spellcheck on quick switcher

components/post_view/post/post.jsx, cypress/integration/account_settings/display/channel_display_mode_spec.js, cypress/integration/account_settings/display/code_theme_colors_spec.js, cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js, cypress/integration/at_mentions/at_mentions_spec.js, cypress/integration/channel/autocomplete_shown_each_channel_spec.js, cypress/integration/channel/collapsed_message_spec.js, cypress/integration/channel/edit_message_spec.js, cypress/integration/channel/header_spec.js, cypress/integration/channel/message_bullets_spec.js, cypress/integration/channel/message_draft_spec.js, cypress/integration/channel/message_draft_then_switch_channel_spec.js, cypress/integration/channel/message_edit_post_with_attachment_spec.js, cypress/integration/channel/message_spec.js, cypress/integration/channel/system_message_spec.js, cypress/integration/login/login_spec.js, cypress/integration/markdown/markdown_spec.js, cypress/integration/search/results_post_comment_spec.js, cypress/integration/team/create_a_team_spec.js, cypress/integration/team/teams_spec.js, cypress/support/api_commands.js, cypress/support/index.js, cypress/support/ui_commands.js
__Reorganized command to reset account settings via API__
Use `cy.apiSaveUserPreference()` to update/save account settings by passing `preference` to be saved.
__Separated API and UI commands__
Intention is to easily identify and properly choose which one is appropriate in a spec file. I foresee the implementation as follow:
- only use UI commands (that driver/control the UI) whenever it's related to the test case, otherwise
- use API commands, usually when doing pre-setup (e.g. create a team/channel or even a post), change in config/settings, etc.
Name format and function signature:
- API command: with prefix of `api` and follows the signature of required parameters at https://api.mattermost.com/
To follow: will update E2E documentation to reflect this info.
Jira - …
=> MM-14391 Reorganize command to reset account settings via API and separate API and UI commands

components/sidebar/header/dropdown/index.js, components/sidebar/header/dropdown/sidebar_header_dropdown.jsx, components/sidebar/header/sidebar_header_dropdown_button.jsx, cypress/integration/account_settings/sidebar/channel_switcher_spec.js, cypress/support/api_commands.js
Add API commands to create and delete a team and channel.
This fixes the issue at `channel_switcher_spec` where it sometimes failed when a hardcoded channel is not present in the initial sample data.  So such spec is done by creating a channel on pre-setup.
This is submitted on top of https://github.com/mattermost/mattermost-webapp/pull/2600.  Particular commit of this PR is at https://github.com/mattermost/mattermost-webapp/commit/633373e91197d096cf7bb8e663377c47142f1e7e.
Jira ticket: [MM-14873](https://mattermost.atlassian.net/browse/MM-14873)
=> MM-14873 Add API command to create and delete a team and channel

components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
Currently the `Remove MFA` option is always shown in the User Dropdown in the system console. The PR fixes that non-boolean types are passed a show prop,  since when `mfa_active`  is false the property is not send to the client, so `user.mfa_active === undefined`, and `undefined` is for `show === true`.
https://mattermost.atlassian.net/projects/MM/issues/MM-14746
=> [MM-14746] Show Remove MFA Item in System Console only for Users that enabled MFA

actions/global_actions.jsx
Set channel as viewed on channel switch.  This fixes the issue of new message indicator not being updated/removed on next visit
Jira: [MM-14863](https://mattermost.atlassian.net/browse/MM-14863)
=> [MM-14863] Set channel as viewed on channel switch

utils/text_formatting.jsx, utils/text_formatting.test.jsx
[PR 2338](https://github.com/mattermost/mattermost-webapp/pull/2338/files) made [at]all/channel/here mentions more flexible to allow for trailing punctuation. The fix was a bit too flexible, for example incorrectly highlighting `[at]all` in usernames like `[at]allen`, so this PR changes the highlight behaviour to require that [at]all/channel/here mentions be distinct words preventing them from highlighting when at the beginning of a larger word like a username.
**Note**: Since an underscore is not considered to be punctuation by regular expressions, if it is included immediately following an [at]channel/all/here mention, the mention won't highlight. This can't be easily fixed and would require more mana to attempt.
[MM-14801](https://mattermost.atlassian.net/browse/MM-14801)
=> [MM 14801] Don't highlight [at]channel/all/here in usernames

components/file_upload/__snapshots__/file_upload.test.jsx.snap, components/file_upload/file_upload.jsx
Fixes the mobile view file input overlapping the send message and emoji buttons. Bug was caused by https://github.com/mattermost/mattermost-webapp/pull/2422
@jespino hopefully I didn't break anything you were fixing, if so let me know and we can find a solution that covers all our cases.
https://mattermost.atlassian.net/browse/MM-14886
=> MM-14886 Move file input back to be child of button

components/file_upload/file_upload.jsx, sass/layout/_post.scss
The problem was the menu being invisible but on top of the arrow button, now is just width 0.
[MM-14920](https://mattermost.atlassian.net/browse/MM-14920)
=> Fixing MM-14886 without moving back the input inside the menu

components/suggestion/at_mention_provider/at_mention_provider.jsx, package-lock.json, package.json, utils/utils.jsx, utils/utils.test.jsx
Removes the `getSuggestions` functions and imports them from `mattermost-redux`.
[MM-14881](https://mattermost.atlassian.net/browse/MM-14881)
- [Link to the redux PR](https://github.com/mattermost/mattermost-redux/pull/808)
=> [MM-14881] Migrates getSuggestion functions to mattermost-redux

actions/views/root.js, components/intl_provider/intl_provider.jsx, components/root/root.jsx, plugins/index.js, plugins/registry.js, reducers/views/i18n.js
This is a functional, ready to merge, proposal on how webapp side plugin translation could work.
The basic process from the plugin side is to use the new `PluginRegistery.registerTranslations` function to register a callback of the form `getTranslations(locale)` that delivers translations on demand. The plugin is then responsible for providing translations for English, and every language it supports. How to get those translations and if Mattermost the company gets involved is out of the scope of this PR, but it assumes the translation files will live with the plugins.
One consequence of not of this method is to avoid the translations causing a "screen flash" when they load in, webapp plugin loading has been made synchronous with the rendering of the root component. ie. The root component …
=> MM-14860 Localization for client plugins.

components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx, components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx, package-lock.json, package.json
Allowing to exclude permissions from the roles edition. Before this PR you
should to pass the permission at the lower scope possible of the permission,
independently if it was in the interface or not. This is needed for the
view_members permissions which is not set as lowest scope level, is set by
default at system level.
[MM-14138](https://mattermost.atlassian.net/browse/MM-14138)
- Has server changes (mattermost/mattermost-server#10487)
- Has redux changes (mattermost/mattermost-redux#810)
=> MM-14138: Allowing to exclude permissions from the roles edition

components/create_comment/create_comment.jsx, components/create_comment/create_comment.test.jsx, components/create_post/create_post.jsx, components/create_post/create_post.test.jsx, components/edit_channel_header_modal/edit_channel_header_modal.jsx, components/edit_post_modal/edit_post_modal.jsx, components/file_upload/index.js, components/sidebar/sidebar.jsx, components/sidebar/sidebar_channel/index.js, components/textbox/index.js, package-lock.json, package.json
Seems to be related to recent update of react-redux to v6.0.1 which might not be compatible with react-bootstrap@0.32.4 (per [react-redux discussion](https://github.com/reduxjs/react-redux/issues/1083#issuecomment-441312159)).
I'd suggest to upgrade react-redux to v6/v7 once react-bootstrap releases the stable version of v1.
Jira - [MM-15039](https://mattermost.atlassian.net/browse/MM-15039)
=> [MM-15039] Revert react-redux to 5.1.1 fixing the issue mostly on profile pop-over and edit channel header components

components/textbox/textbox.jsx
This should have been a part of https://github.com/mattermost/mattermost-webapp/pull/2622/files with changes from https://github.com/mattermost/mattermost-webapp/pull/2447/files#diff-4ad88f36a09a5f303774e31aa60afd2cL119 lines. This change was lost during a conflict resolution with
https://github.com/mattermost/mattermost-webapp/pull/2531 
[MM-15041](https://mattermost.atlassian.net/browse/MM-15041)
=> MM-15041 Fix for center channel to be at last post when textbox expands

components/admin_console/elasticsearch_settings.jsx
This removes the Elasticsearch autocompletion flag in the system console
- [Related server PR](https://github.com/mattermost/mattermost-server/pull/10578)
- [Related enterprise PR](https://github.com/mattermost/enterprise/pull/417)
=> Revert elasticsearch autocompletion flag in the System Console

sass/layout/_post.scss
Removing the min-height of 350px. With changes to virtlist the height of child div is viewport height so min-height causes issue
[MM-14880](https://mattermost.atlassian.net/browse/MM-14880)
=> MM-14880 Fix Recent posts being hidden on decrease of window height

components/needs_team/index.js, components/needs_team/needs_team.jsx, components/needs_team/needs_team.test.jsx
Before this commit to try to join a team we get the list of teams (limited to
200), and match the correct team using the name. Now we get directly the team
by name, this allow us to join any team, not only that teams that are in the
list of the first 200 teams.
[MM-15068](https://mattermost.atlassian.net/browse/MM-15068)
=> MM-15068: Impossible to join directly to team by url if is not in the first 200 visible teams

components/suggestion/emoticon_provider.jsx, components/suggestion/emoticon_provider.test.jsx
In order to check if the alias exists in recents, the alias must first contain the partial name. For an emoji like thumbsup which is saved in recents as `+1` and has aliases `+1` and `thumbsup`, a partial name of `thu` will only match the `thumbsup` alias, however, the check for this alias in recents will fail. With this PR I also check if the name exists in recents so that the emoji is included in the suggested results. I've also applied this name check for custom emojis so that they too are included first if recently used.
https://mattermost.atlassian.net/browse/MM-15013
=> [MM-15013] Show recently used emojis first in suggestions

components/post_view/post_body_additional_content/post_body_additional_content.jsx
The PostBodyAdditionalContent was treating these links as opengraph links since the links didn't look like images to it. The fix is to check if the type of the embed is image and use that as a condition.
https://mattermost.atlassian.net/browse/MM-14929
=> MM-14929 Fix shortened image links not showing a preview

components/view_image/popover_bar/__snapshots__/popover_bar.test.jsx.snap, components/view_image/popover_bar/popover_bar.jsx
The browser will attempt to download a linked file if that link has the download attribute. We were incorrectly specifying that attribute on a link that should just open an external image.
I'm not sure why this worked correctly (ie it just opened the file) for images that weren't served through the local image proxy, but it's possible it's some browser thing that prevents files from other domains from being downloaded this way.
https://mattermost.atlassian.net/browse/MM-14484
=> MM-14484 Remove download attribute from Open external image link

actions/command.js, actions/views/channel.js, actions/views/channel.test.js, actions/websocket_actions.jsx, components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx, components/admin_console/admin_navbar_dropdown/index.js, components/channel_header_dropdown/index.js, components/channel_layout/channel_identifier_router/actions.js, components/create_team/components/team_url/team_url.jsx, components/login/login_controller/login_controller.jsx, components/login/login_controller/login_controller.test.jsx, components/select_team/select_team.jsx, components/sidebar/sidebar.jsx, components/sidebar/sidebar.test.jsx, components/sidebar/sidebar_channel/index.js, components/sidebar/sidebar_channel/sidebar_channel.jsx, components/sidebar/sidebar_channel/sidebar_channel.test.jsx, package-lock.json, package.json, stores/local_storage_store.jsx, utils/channel_utils.jsx, utils/utils.jsx
Changing the concept of default channel (town square) to the concept of
redirect channel, by default will be town square, but in certaing situations it
will be your first existing channel in the team. Concretely if you are not allowed to join to public channels, and you are not member of the town-square channel (guest accounts will be in this situation), you will be redirected to your first channel in the current team.
[MM-14639](https://mattermost.atlassian.net/browse/MM-14639)
=> Creating the concept of RedirectChannel and use it before the DefaultChannel when we are redirecting the user

components/dot_menu/dot_menu.jsx, components/search_results_item/search_results_item.jsx
This fixes JS console warnings for missing required props. These warnings were found while debugging [MM-15083](https://mattermost.atlassian.net/browse/MM-15083)
=> Add missing default values for required props

components/admin_console/plugin_management/index.js, components/admin_console/plugin_management/plugin_management.jsx, components/admin_console/plugin_management/plugin_management.test.jsx
The settings page for the plugin was not being added to the sidebar or to the buttons next to "Enable" and "Remove" because we did not have the plugin manifest telling us we needed to display settings. The fix is to re-fetch the plugin manifests after uploading a new plugin.
https://mattermost.atlassian.net/browse/MM-15076
=> MM-15706 Fetch plugin manifests after uploading a new plugin

components/link_tooltip/link_tooltip.jsx
This PR fixes dismissing the tooltip when clicking the button a few times on the Windows desktop app. It was caused by a bug in older versions of Chromium and currently used in Electron. Sometimes a `click` event fires a `mouseleave` event. I saw that this "self-fired" `mouseleave` event has null in the `toElement` property, so I just added a condition to hide the tooltip only if the `toElement` property of the `mouseleave` event is not null.
Tested on the Windows Desktop app on 4.3 and now it works as expected. I also tested it on Safari, Mac Desktop App, Chrome and Firefox just for sure.
Fixes https://github.com/mattermost/mattermost-server/issues/10603
=> [MM-14842] fix dismissing the tooltip when clicking the button

components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx, components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js, components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap, components/channel_members_dropdown/channel_members_dropdown.jsx, components/channel_members_dropdown/channel_members_dropdown.test.jsx, components/team_members_dropdown/__snapshots__/team_members_dropdown.test.jsx.snap, components/team_members_dropdown/team_members_dropdown.jsx, components/team_members_dropdown/team_members_dropdown.test.jsx, components/user_list.jsx, components/user_list_row/user_list_row.jsx, components/user_list_row_with_error/user_list_row_with_error.jsx
The problem was that the dropdowns near the bottom of user lists would open downwards and increase the size of the div they were in. The solution I came up with was to open the dropdown upwards for the last X items in a user list. I'm not terribly happy with how it's implemented but I'm not sure of a better way of doing it. Definitely open to suggestions.
https://mattermost.atlassian.net/browse/MM-14707
=> MM-14707 Open dropdowns near the bottom of user lists upwards

components/post_view/message_attachments/action_menu/action_menu.jsx, components/post_view/message_attachments/action_menu/action_menu.test.jsx
This PR is pretty straightforward. This value starts selected in the dropdown, allowing integrations to "save" a value which we wanted for the NPS plugin.
Server PR: https://github.com/mattermost/mattermost-server/pull/10659
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2724
https://mattermost.atlassian.net/browse/MM-14741
=> MM-14741 Add default option to post action dropdown

components/channel_header_dropdown/menu_items/leave_channel/leave_channel.js, components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.js, components/widgets/menu/menu_items/menu_item_action.jsx, components/widgets/menu/menu_items/menu_item_action.test.jsx
Make the DOM structure of "Mute Channel" and "Leave Channel" be the same with other menu items at channel dropdown.
- no visual side-effect (tested)
- that makes it easier for Selenium testing (UI automation in general)
- make the ID (already in placed) take effect into those menu items 
Jira: [MM-15077](https://mattermost.atlassian.net/browse/MM-15077)
Before:
After:
=> [MM-15077] Make the DOM structure of "Mute Channel" and "Leave Channel" be the same with other menu items at channel dropdown

components/integrations/bots/bot.jsx, components/integrations/bots/bot.test.jsx
This PR addresses the case where a bot can be edited through the system console UI, even if the bot is managed by a plugin.  
Before: An admin has the ability to create tokens, edit and disable a bot account through the system console.
After: An admin cannot create tokens, edit or disable a bot account through the system console.  However, an admin does retain the ability to disable or delete a token
Testing:  We should test that the UI elements do not show up for the plugin managed bot, so the existing tests cases were retained, but the expected result is set to false.  
Testing that create, edit, and disable elements exist were added to an existing test that sets up a bot account that is not managed by a plugin.
https://mattermost.atlassian.net/browse/MM-15195
n/a
=> [MM-15195] Bot account can be edited even though it's managed by a plugin

components/dot_menu/__snapshots__/dot_menu.test.jsx.snap, components/dot_menu/dot_menu.jsx, cypress/integration/post_header/post_header_spec.js
* add E2E test for toggling pinned badge in center and RHS
Github Issue: https://github.com/mattermost/mattermost-server/issues/10449
Test Key: M14577
=> [MM-14577] add E2E test for toggling pinned badge in center and RHS

components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap, components/new_channel_modal/new_channel_modal.jsx, cypress/integration/onboarding/multi_team/existing_channel_name_spec.js
MM-14635 Adding automated test using Cypress for Channel Name Already Exists
Added E2E test using `cypress` for "Channel name already exists"
Fixes https://github.com/mattermost/mattermost-server/issues/10473
=> MM-14635 Automated test using cypress for Channel name already exists

components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx, components/channel_members_dropdown/channel_members_dropdown.jsx, components/team_members_dropdown/team_members_dropdown.jsx
Follow-up to #2670 to fix the case where short lists open the dropdown upwards instead of downwards.
=> Do not open user list dropdowns upwards for short lists

components/user_settings/modal/user_settings_modal.jsx
Scroll to the top of the Account Settings modal when the active tab changes.
https://mattermost.atlassian.net/browse/MM-14709
=> [MM-14709] Scroll to the top of the Account Settings modal when the active tab changes

components/emoji/emoji_list_item/emoji_list_item.jsx, components/emoji/emoji_page.jsx, components/permissions_gates/any_team_permission_gate/__snapshots__/any_team_permission_gate.test.jsx.snap, components/permissions_gates/any_team_permission_gate/any_team_permission_gate.jsx, components/permissions_gates/any_team_permission_gate/any_team_permission_gate.test.jsx, components/permissions_gates/any_team_permission_gate/index.js
Emojis permissions have the special property of been granted from any team
admin role, so if you have the permission at any team, you are able to do the
actions in all the teams. I added a new permissions gate call
"AnyTeamPermissionGate" which deal with that and used for the emojis
permissions.
[MM-15046](https://mattermost.atlassian.net/browse/MM-15046)
=> MM-15046: Adding AnyTeamPermissionGate and used with emojis permissions

utils/message_html_to_component.jsx
This is a really weird one. If a checkbox was unedited in the post, the post would not update. I checked to make sure that we were actually re-rendering the Markdown component, which we were, and tracked (with @hmhealey's help) the problem down to the fact that the React key for the checkbox elements was preventing the low-level re-rendering of the checkbox to happen.
My fix is a workaround to change the key based on whether the checkbox is checked or not. Open to other suggestions if others can think of better solutions.
https://mattermost.atlassian.net/browse/MM-14931
=> MM-14931 Fix markdown checkboxes not being rendered correctly after post edits

components/search_results/search_results.jsx
Follow-up fix for #2684 where I didn't account for flagged or pinned posts not needing the loading more indicator.
=> Hide loading indicator for pinned and flagged posts

components/file_upload/file_upload.jsx, components/widgets/menu/menu.jsx, sass/responsive/_mobile.scss
Overrides `<Menu>` component's style when used in `<FileUpload>` to properly display the file upload menu option when enabled in the plugin api's `registerFileUploadMethod`.
https://mattermost.atlassian.net/browse/MM-14764
N/A
=> [MM-14764] Show file upload options in mobile view

package-lock.json, package.json, plugins/index.js
Revert to the previous exif2css version (compatible with IE11) and checking bad
plugin initialization 
[MM-15285](https://mattermost.atlassian.net/browse/MM-15285)
- Has redux changes mattermost/mattermost-redux#822
=> MM-15285: Fixing IE11 initialization problems

actions/views/channel.js, components/create_post/create_post.jsx, components/create_post/create_post.test.jsx, components/create_post/index.js, components/post_view/post_list.jsx
As I mentioned before, inferring this from the redux state is really, really difficult, so we're just going to use an event to trigger the post list to scroll to the bottom because it's very straightforward to do that.
https://mattermost.atlassian.net/browse/MM-15080
=> MM-15080 Use event emitter to scroll to bottom when sending post

sass/routes/_admin-console.scss
Reverts section and subsection styles to the previous state.
https://mattermost.atlassian.net/browse/MM-15313
https://mattermost.atlassian.net/browse/MM-15166
N/A
=> [MM-15313] Revert section highlight styling; subsection indentation

components/post_view/post/index.js, components/post_view/post/index.test.js
The previous version never rendered the "Commented on" line for posts following things that aren't real posts (date separators, new messages line, combined system messages, etc) because `isFirstReply` would always be false. This could be fixed by changing `let isFirstReply = false;` to `let isFirstReply = true;` which matches the mobile app, but I decided to add some tests instead.
https://mattermost.atlassian.net/browse/MM-15196
=> MM-15196 Fix missing 'Commented on' after separators

components/search_results/search_results.jsx
Fixed the double loading indicators when searching by moving the loading more component into the else block so it will only ever show if there are search results.
https://mattermost.atlassian.net/browse/MM-15359
=> MM-15359 Fix double loading search indicators

components/announcement_bar/announcement_bar_controller.jsx, components/announcement_bar/configuration_bar/configuration_bar.jsx, components/announcement_bar/configuration_bar/index.js, components/announcement_bar/index.js
The licensing expiring message needs to be dismissable but show again on next refresh. I leveraged the existing action/reducer for dismissing system notices to accomplish this.
https://mattermost.atlassian.net/browse/MM-15386
=> MM-15386 Allow license expiring message to be dismissed and show it as an announcement type

components/post_view/index.js, components/post_view/post_list.jsx, components/post_view/post_list.test.jsx
The previous version of this used onItemsRendered to trigger checkBottom, but that only triggers when the rendered posts changes, so it couldn't be as accurate as the versions before it. It also has some issues because it only allows us to check when the second post from the bottom became visible (`visibleStopIndex` would be 0 as long as the second post was visible). Changing it to `onScroll` lets us tell more accurately when the list is at the bottom.
The other change here is that `this.state.lastViewedBottom` is now updated when you reach the bottom and then again when you leave it. This also caused a bug where you'd scroll to the bottom, receive some posts, and then you'd scroll back up and the "New Messages" would appear.
https://mattermost.atlassian.net/browse/MM-15322
=> MM-15322 Change PostList.checkBottom to use onScroll

components/post_view/post_list.jsx, package-lock.json, package.json
* Changing overscan counts to be same for virtualized list
After loading new posts at the top the scroll correction moves the scroll down making a change in scrollDirection state in virt list. 
Change in scroll direction causes a mount of another 50 posts because overscan forward is different when compared to overscan backward. This makes it js thread a little busy responding to further interactions
Related PR https://github.com/mattermost/react-window/pull/11/
=> MM-14861 Fix safari perf issues

cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js, cypress/integration/team/teams_spec.js, cypress/support/ui_commands.js
Fixed failing tests of the following:
- account_settings/display/code_theme_colors_spec.js
- account_settings/display/message_display_,mode_spec.js
- account_settings/theme_color/custom_colors_sidebar_styles_spec.js
- at_mentions/at_mentions_spec.js
By fixing the way we're getting last post ID (`cy.getLastPostId`) --> affected by the recent change related to virtualized post list.
By changing `#accountSettingsTitle` to `#accountSettingsModalLabel` --> affected by recent change on [aria labels](https://github.com/mattermost/mattermost-webapp/pull/2738/files#diff-31ecc8eed85fdba28524f03f7d74d6a9R274)
Jira: [MM-15451](https://mattermost.atlassian.net/browse/MM-15451)
=> [MM-15451] Fix failing E2E tests due to recent changes

sass/routes/_admin-console.scss
MM-15001 - Updating margin for wrapper sys console
This is a hacky fix for 5.11. The real fix is here: https://github.com/mattermost/mattermost-webapp/pull/2761
https://mattermost.atlassian.net/browse/MM-15001
=> MM-15001 - Updating margin for wrapper sys console

utils/utils.jsx, utils/utils.test.jsx
Forces bots to the bottom of channel user list
[Jira](https://mattermost.atlassian.net/browse/MM-14767)
[GitHub](https://github.com/mattermost/mattermost-server/issues/10752)
- Has redux changes (May be necessary)
=> [MM-14767] Sorting BOTs at the bottom of channel member list below offline users is not working

components/user_list_row/user_list_row.jsx
Bot badges where showing up always on view team members.
[MM-15479](https://mattermost.atlassian.net/browse/MM-15479)
=> Fix bot badges on manage team members

components/post_view/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap, components/post_view/post_attachment_opengraph/index.js, components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx, components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.js, components/post_view/post_body/index.js, components/post_view/post_body/post_body.jsx, components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap, components/post_view/post_body_additional_content/index.js, components/post_view/post_body_additional_content/post_body_additional_content.jsx, components/post_view/post_body_additional_content/post_body_additional_content.test.jsx, components/post_view/post_image/post_image.jsx, components/post_view/post_image/post_image.test.jsx, components/view_image/index.js, components/youtube_video/youtube_video.jsx, components/youtube_video/youtube_video.test.jsx, utils/utils.jsx
Instead of using `extractFirstLink` to search the post text for a link, this makes it so that we only look at `post.metadata.embeds` to figure out if the post should show any embedded content (link previews, image previews, message attachments, or YouTube videos). This will fix any scroll pop that happens when the web app tries to show content that hasn't been included with the post metadata.
One important thing to note from this is that the server doesn't understand YouTube links, so we have to look for OpenGraph requests to see if they're actually YouTube links ([link](https://github.com/sudheerDev/mattermost-webapp/compare/MM-14977...mattermost:mm15343b#diff-564aa388e5c66ad77190526b786fbe89R85)). This makes it difficult to fix …
=> MM-15343 Rely entirely on post metadata for embedded content

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
This is in preparation for v5.12 release. Polish was promoted back to Beta for v5.9: https://github.com/mattermost/mattermost-webapp/pull/2443
=> Promote Polish to 'official'

actions/admin_actions.jsx, components/admin_console/schema_admin_settings.jsx
Now filenames for uploaded files are defined by the uploader success callback,
and in this cases is used to set properly the file names for the saml
certificates.
[MM-15399](https://mattermost.atlassian.net/browse/MM-15399)
=> MM-15399: Properly setting filenames on upload saml certificates

plugins/registry.js
This is needed for the NPS plugin because it stops using its custom post component at small screen sizes when there's not enough room to display it properly.
The `REMOVED_PLUGIN_POST_COMPONENT` action is already handled by the correct reducer, but there was nothing that actually emitted it.
https://mattermost.atlassian.net/browse/MM-15562
=> MM-15562 Add a way to unregister post type components

cypress/integration/post_header/post_header_spec.js
Small fixes to post_header_spec.js to check for only the highlighting class.
[JIRA](https://mattermost.atlassian.net/browse/MM-15561)
To run only this test, run `npm run cypress:run -- --spec "cypress/integration/post_header/**/*.js" --reporter "spec" --browser "chrome"`
=> MM-15561 fix post_header_spec.js

components/post_view/post/index.js, components/post_view/post/index.test.js
This fixes the issue where concurrent posts made by a single user are always rendered separately.
https://mattermost.atlassian.net/browse/MM-15432
=> MM-15432 Change isFirstReply to return false for non-comments

components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap, components/post_view/post_body_additional_content/post_body_additional_content.jsx, components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
The naming of the props `isEmbedVisible` (whether or not an image preview/YouTube video is collapsed or the image in an OpenGraph preview is collapsed), `enableLinkPreviews` (whether or not the server has OpenGraph previews enabled), and `previewEnabled` (whether or not the user has OpenGraph previews enabled) are confusing.
This is a followup to fix a bug caused by #2764
https://mattermost.atlassian.net/browse/MM-15583
=> MM-15583 Fix static embeds being hidden when image previews are collapsed

utils/utils.jsx
Use new header to calculate file loading progress for gzipped responses. See https://github.com/mattermost/mattermost-server/pull/10836 for more details.
https://mattermost.atlassian.net/browse/MM-15320
- Has server changes (https://github.com/mattermost/mattermost-server/pull/10836)
=> MM-15320 Use new header to calculate file loading progress for gzipped responses

components/admin_console/reset_password_modal/reset_password_modal.jsx
This PR removes the max length enforcement for the password reset form in the admin UI. The password length will now only be validated by the serverside (which has currently a max length of 72):
https://github.com/mattermost/mattermost-server/blob/584ec68755a22c3caec24a1a7da432111a9ac344/model/user.go#L267
https://mattermost.atlassian.net/browse/MM-14973
https://github.com/mattermost/mattermost-server/issues/10523
=> [MM-14973] Remove password length limit from reset password form (closes #10523)

i18n/en.json, utils/constants.jsx
Allowing to translate `suggestion.archive` string in the channel switcher.
[MM-15487](https://mattermost.atlassian.net/browse/MM-15487)
=> MM-15487: Adding suggestion.archive to the translatable strings

actions/global_actions.test.js, components/add_users_to_team/add_users_to_team.jsx, components/add_users_to_team/add_users_to_team.test.jsx, components/add_users_to_team/index.js, components/channel_invite_modal/channel_invite_modal.jsx, package-lock.json, package.json
Uses team and channel `group_constrained` property when loading users to add.
https://mattermost.atlassian.net/browse/MM-14751
- [Has server changes](https://github.com/mattermost/mattermost-server/pull/10678)
- [Has redux changes](https://github.com/mattermost/mattermost-redux/pull/817)
- [Has mobile changes](https://github.com/mattermost/mattermost-mobile/pull/2737)
=> [MM-14751] Take group_constrained into account when adding users to teams and channels

components/post_view/post_list_virtualized/index.js
Selector `getPostIdsAroundPost` takes options arguments for slicing the required posts
https://github.com/mattermost/mattermost-redux/blob/master/src/selectors/entities/posts.js#L131-L134
As with virtualised list we can return the entire post chunk so adding `-1` index as option so selector can return all the posts in the chunk. With bi-directional scrolling we can add `-1` for `postsAfterCount` as well given we add the initial range to mount for virtualised list
=> MM-15227 Permalink is not loading more posts into the view when reacheded to the top

cypress/integration/channel/header_spec.js
This PR includes automations tests to verify that the cleared search term does not reappear when RHS is reopened
Fixes https://github.com/mattermost/mattermost-server/issues/10038
=> MM-13483 Cleared search term should not reappear as RHS is reopened

components/multiselect/multiselect_list.jsx
For some reason it was reseting the select channel to null on every props change
[MM-15544](https://mattermost.atlassian.net/browse/MM-15544)
=> MM-15544: Fixing selector selection with arrows on more direct channels

utils/notifications.jsx
Mac app notifications are controlled and dismissed as necessary by the OS. By dismissing the notifications for the Mac desktop app we were breaking with app conventions for Mac apps.
https://mattermost.atlassian.net/browse/MM-14134
=> MM-14134 Do not auto close notifications on Mac desktop app

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx
Dimensions here are numbers and need to have px appended so that the styles are applied 
https://mattermost.atlassian.net/browse/MM-15709
=> MM-15709 certain aspect ratio of images cause pop on firefox

components/admin_console/admin_definition.jsx
Fixing NONE security in SMTP admin console config. The server expected '', and was sent 'none'.
[MM-15725](https://mattermost.atlassian.net/browse/MM-15725)
=> MM-15725: Fixing NONE security in SMTP admin console config

components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap, components/post_view/message_attachments/message_attachment/message_attachment.jsx, components/post_view/post_message_view/__snapshots__/post_message_view.test.jsx.snap, components/post_view/post_message_view/post_message_view.jsx, components/post_view/show_more/__snapshots__/show_more.test.jsx.snap, components/post_view/show_more/index.js, components/post_view/show_more/show_more.jsx, components/post_view/show_more/show_more.test.jsx, plugins/test/__snapshots__/post_type.test.jsx.snap, sass/layout/_post.scss, sass/responsive/_tablet.scss
In compact view we wrap long posts to a new line. On mount of a post it starts off inline with the username and then if height is more than the max height it wraps to a new line by adding `post-message--overflow` className causing it to push content by `22px`
1. The changes here will decrease the height of long posts by 22px if it is a collapsed post in compact view
2. There is another bug with respect to long post attachments. There is an unintended sideeffect of 22px margin on top added to bot posts caused by adding the above class. 
This PR Fixes above both issues
https://mattermost.atlassian.net/browse/MM-15757
=> MM-15757 Fix scroll pop caused by long posts in compact view

cypress.json, cypress/fixtures/users.json, cypress/integration/email/mention_email_notification_spec.js, cypress/plugins/get_recent_email.js, cypress/plugins/index.js
E2E for email notification.
Note: This is submitted on top of https://github.com/mattermost/mattermost-webapp/pull/2840
Particular change for this PR are: https://github.com/mattermost/mattermost-webapp/pull/2833/commits/c1093d0219703a94e0fa119bab98e8205197515a, https://github.com/mattermost/mattermost-webapp/pull/2833/commits/2be3ac1165a52832fc258bb446d8583138c6391b
~~Note that Cypress doesn't allow to visit [second unique domain](https://on.cypress.io/cannot-visit-second-unique-domain).  To work around on this, only visit the local email URL on the next `it` and from there, email contents can be verified.~~
~~This PR only verifies whether a user has received the email notification and with expected content.~~
~~It does not yet cover using the link (e.g. permalink) from email content to …
=> [MM-14344] E2E for email notification

package-lock.json, package.json, utils/text_formatting_links.test.jsx
Updates package.json and some unit tests after markdown parser [update](https://github.com/mattermost/marked/pull/11) (#9155)
[Jira ticket](https://mattermost.atlassian.net/browse/MM-11287)
- Has server changes https://github.com/mattermost/mattermost-server/pull/10852
- Has marked library changes mattermost/marked#11
- Has commonmark.js library changes mattermost/commonmark.js#7
=> [MM-11287] Add support for plus sign and period/dot in custom URL schemes (#9155)

components/post_view/post_list_ie/post_list_ie.jsx
Before recent changes to `increasePostVisibility` function we used to increment `INCREASE_POST_VISIBILITY ` irrespective of API response. Latest changes to `INCREASE_POST_VISIBILITY` are made such that we increment based on the number of posts so when at the top there are no posts so there is no increase in post length causing the state `atEnd` not set as `postsLength === postVisibility`.
https://github.com/mattermost/mattermost-webapp/blob/5feffaa72346a85c8f613e689d986b75edf7ce96/actions/views/channel.js#L196-L202
Making the change synonymous to change in virt list condition as there are no issue with this logic
https://mattermost.atlassian.net/browse/MM-15753
=> MM-15753 IE:11 Fix for system message not loading at the top

components/post_view/post_list_ie/post_list_ie.jsx
With recent changes for virtualised list we added a new prop `previousPostId ` for `<Post>` component which should be added here for IE11 fallback for grouping posts
https://mattermost.atlassian.net/browse/MM-15754
=> MM-15754 IE:11 Fix for grouping of messages

components/post_view/post_list_virtualized/post_list_virtualized.jsx, components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
* Exclude scroll correction when channel header is added at the top when atBottom state is true.
If channel header is added at the top we let virt list correct the scroll. Virt list can keep view at the bottom when at bottom. 
https://mattermost.atlassian.net/browse/MM-15756
=> MM-15756 Scroll correction fix for addition of channel header when at bottom

components/suggestion/suggestion_box.jsx, components/suggestion/suggestion_list.jsx
The scrollbar of the suggestion list is not detected as the `relatedTarget` of the `focusOut` event when clicked, so a `preventSuggestionListClose` function has been added that sets a flag as part of any `mouseDown` event inside the suggestion box. This flag prevents the list to be closed, hence allows the scrollbar to function properly.
https://mattermost.atlassian.net/browse/MM-15459
=> [MM-15459] Add mechanism to prevent suggestion close when clicking suggestion list

cypress/integration/channel/message_draft_spec.js, cypress/integration/channel/message_draft_then_switch_channel_spec.js, cypress/integration/channel/message_edit_post_with_attachment_spec.js, cypress/integration/integrations/integrations_spec.js, cypress/support/ui_commands.js
Fix flaky tests the following specs
- channel/message_draft_spec.js 
- channel/message_draft_then_switch_channel_spec.js
- channel/message_edit_post_with_attachment_spec.js 
- integrations/integrations_spec.js
- account_settings/theme_color/custom_colors_sidebar_styles_spec.js
Fixes made:
1) `scrollIntoView` to channel sidebar
- whenever there are many channels in the sidebar and with unreads, `scrollIntoView` is still not enough to position a channel item.  It's still covered by `More Unreads (top/bottom)`.  In this scenario, it may be better to test with new user with new team so that there's only 2 channels in the sidebar.
2) Others are either missing step or having unnecessary step.
none
=> Fix flaky tests on some specs

components/main_menu/__snapshots__/main_menu.test.jsx.snap, components/main_menu/main_menu.jsx
Disabling leave teams from the main menu for experimentalPrimarTeam enabled
[MM-15892](https://mattermost.atlassian.net/browse/MM-15892)
=> MM-15892: Disabling leave teams from the main menu for experimentalPrimarTeam enabled

sass/layout/_markdown.scss
sizeAwareComponent which was used while loading img as placeholder is an svg wrapped with div tag.
After img loads we replace the placeholder svg but as img has `vertical-align: middle` there is a minor css pop that was caused 
https://mattermost.atlassian.net/browse/MM-15919
=> MM-15919 Fix minor scroll pop for inline markdown images

sass/layout/_post.scss
* Fixes a regression with consecutive posts padding
* Changes height to 1px for date separator and new message line as height is needed for virt list to correct scroll to position when `new messages` separator exists
https://mattermost.atlassian.net/browse/MM-15403
Regression caused by https://github.com/mattermost/mattermost-webapp/pull/2806
=> MM-15403 Fixes highlight for date separators and new messages line on post hover

components/post_view/post_list_virtualized/post_list_virtualized.jsx
The deduction of height for dynamic list is not needed as the padding is for inner container and we use outerRef for scroll correction and does not need this.
When loading a channel with posts which does not occupy enough space we make another API call loading posts and the scroll correction here at https://github.com/mattermost/react-window/blob/feature/reverseScroll/src/DynamicSizeList.js#L264-L266
is wrong making the scroll not stay at bottom when new posts are added
https://mattermost.atlassian.net/browse/MM-15975
=> MM-15975 scroll pop when loading a channel if the height of loaded posts is low

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, components/size_aware_image.test.jsx
Requesting image through `new Image()` and replacing after download has an issue with safari. 
Once the image is downloaded for `new image()` we replace svg placeholder with `img` tag expecting that it will be served from cache. 
Safari still makes a new call after removing svg placeholder in place and replacing with `img` tag while chrome and firefox handles this smartly. 
**Changes**
Remove the `new Image()` constructor and add an `img` tag with `display: none` so browsers still make the call for image and use onLoad and onError callback with it
https://mattermost.atlassian.net/browse/MM-15830
=> MM-15830 Fix safari scroll jumps for images

actions/global_actions.jsx, components/admin_console/admin_console.jsx, components/admin_console/system_users/system_users.jsx, components/announcement_bar/announcement_bar.jsx, components/announcement_bar/announcement_bar_controller.jsx, components/announcement_bar/version_bar/__snapshots__/version_bar.test.jsx.snap, components/announcement_bar/version_bar/index.js, components/announcement_bar/version_bar/version_bar.jsx, components/announcement_bar/version_bar/version_bar.test.jsx, i18n/en.json, sass/components/_announcement-bar.scss, sass/utils/_variables.scss
To avoid refreshing the app on users without telling them, we now show a banner alerting them that a new version is available with a link to refresh the app.
Proposing this for 5.13 since it's a good quality of life improvement.
https://mattermost.atlassian.net/browse/MM-15976
=> MM-15976 Replace forced refresh with banner alerting users that a new version is available

components/admin_console/admin_sidebar_header/admin_sidebar_header.jsx
MM-15724 - Fixing minor bug with system console LHS header
https://mattermost.atlassian.net/browse/MM-15724
=> MM-15724 - Fixing minor bug with system console LHS header

components/size_aware_image.jsx, components/size_aware_image.test.jsx
onLoad triggers event with target as a key with image object so the check should be looking for event.target.naturalHeight
Fixes: https://mattermost.atlassian.net/browse/MM-16018
Regression caused by: https://github.com/mattermost/mattermost-webapp/pull/2891
=> MM-16018 Fix for image click to open image preview modal

components/announcement_bar/version_bar/version_bar.jsx
This could occur when the component mounted before the websocket had connected.
=> Fix race in version bar causing the bar to show up when no version change has occurred

components/admin_console/help_text.jsx, components/post_view/channel_intro_message/channel_intro_message.jsx
Fix JS errors in system console and channel intro message.
Jira ticket: [MM-16007](https://mattermost.atlassian.net/browse/MM-16007)
=> [MM-16007] Fix JS errors in system console and channel intro message

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, components/size_aware_image.test.jsx, sass/components/_files.scss, sass/layout/_markdown.scss
With display none to image IE does not request for image so it never loads to trigger onLoad event.
So changing it to be absolutely positioned element with visibility hidden so it is not visible and does not take any space when svg is in place for placeholder. 
https://mattermost.atlassian.net/browse/MM-16029
https://mattermost.atlassian.net/browse/MM-16028
https://mattermost.atlassian.net/browse/MM-16027
https://mattermost.atlassian.net/browse/MM-16100
=> MM-16029 IE11: image attachments aren't displayed

actions/views/root.js
The set of cookies cleared was updated as part of adding support for running multiple Mattermost instances across multiple subpaths, but the combination of subdomain and subpath left a case uncovered.
If this cookie is not cleared on logout, the client makes incorrect routing decisions, and ultimately ends up in an infinite loop.
https://mattermost.atlassian.net/browse/MM-16090
=> MM-16090: clear cookie with path but without domain

components/create_post/create_post.jsx, components/create_post/create_post.test.jsx
When uploading a file the state to enable the set button was not being set, also when removing a file we were using the props draft instead of the modified draft.
https://mattermost.atlassian.net/browse/MM-16033
=> MM-16033 Mobile view: Show paper plane enabled when uploading a file

components/admin_console/admin_definition.jsx, i18n/en.json
Fixes reference to group settings page in the enable AD/LDAP sync setting: was ‘Access Controls’ now under ‘User Management’
https://mattermost.atlassian.net/browse/MM-15872
=> [MM-15872] Update AD/LDAP Feature Flag Description in Experimental Settings to correct location

components/post_view/post_list_ie/post_list_ie.jsx
There is no state.atBottom any more this was removed in an earlier refactor changing it to kind-of how it used to https://github.com/mattermost/mattermost-webapp/blob/release-5.11/components/post_view/post_list.jsx#L661-L663 albeit with the added props for `new messages component`
https://mattermost.atlassian.net/browse/MM-16034
=> MM-16034 Fix for IE Not removing new message indicator

components/post_view/post_list_virtualized/index.js, components/post_view/post_list_virtualized/post_list_virtualized.jsx, components/post_view/post_list_virtualized/post_list_virtualized.test.jsx, utils/post_utils.jsx, utils/post_utils.test.jsx
For few timezones server is ahead of timezones causing `Date.now()` used for not showing `new messages` indicator to show even after scrolling to the bottom. So instead of using `Date.now()` alone we are comparing with lastPost timestamp of `create_at` and using which ever is greater.
https://mattermost.atlassian.net/browse/MM-15791
=> MM-15791] New messages indicator doesn't clear after viewing the message

package.json
This fixes the failing unit test by reverting accidental change to marked's commit.  Not sure how it happened, maybe during cherry-pick process 🍒 .
Recent [change](https://github.com/mattermost/mattermost-webapp/pull/2842) to marked was only on master (scheduled to 5.14) but not to 5.12
Jira ticket: [MM-16105](https://mattermost.atlassian.net/browse/MM-16105)
=> [MM-16105] Revert accidental change to marked's commit

components/post_view/post_list_virtualized/post_list_virtualized.jsx, package-lock.json, package.json
* The primary fix is to remove cancel animation frame when correcting scroll from react-window library.
* This also remove the check for `!end` for third param to use animation
frame for correcting scroll on chrome when loading more posts or channel header is added
This is to avoid any race condition for correcting scroll correction for posts using animationFrame and overriding it with scroll correction in the same frame with header update state(`atEnd`)
https://mattermost.atlassian.net/browse/MM-16101
https://github.com/mattermost/react-window/pull/17/
=> MM-16099 Fix for scroll correction when loading channel header

components/post_view/channel_intro_message/channel_intro_message.jsx
When adding the accessibility for the Dialog the styles were removed, this PR adds it back
https://mattermost.atlassian.net/browse/MM-16214
=> M-16214 Fix styling of Set a Header in channel intro

actions/views/rhs.js, actions/views/rhs.test.js
Pass an RHS post's root_id to getPostThread so the reply thread is shown when clicking Reply.
https://mattermost.atlassian.net/browse/MM-16096
=> [MM-16096] Pass post's root_id to getPostThread

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx
Problem:
The image behind is supposed to occupy only 1px height and 1px width so it can trigger a download of image and swap it later for svg placeholder in place.
The css behind this is weird as it takes up space even with the specified dimensions and visible on fail causing extra space beneath in scroll container.
Solution:
Add `overflow:hidden` as part of conditional styles to hide the extra empty space created. These conditional styles if image downloads
https://mattermost.atlassian.net/browse/MM-16243
=> MM-16243 Fix for empty space caused by faiied link preview image

package-lock.json, package.json
Fix IE11 syntax error because the new version of the library use some
incompatible syntax (for example the backtick character for strings
interpolation).
[MM-16112](https://mattermost.atlassian.net/browse/MM-16112)
=> MM-16112: Fix IE11 syntax error

components/announcement_bar/announcement_bar.jsx
Removing unnecessary and failing code.
This was already fixed in master but in a PR that include more changes, so I make the PR directly to be merged against release-5.12.
[MM-16282](https://mattermost.atlassian.net/browse/MM-16282)
=> MM-16282: Removing not necesary code

components/integrations/bots/bot.jsx, components/integrations/bots/bot.test.jsx
Markdown is already supported when the bot's description is displayed in the header of a DM with it, so this just makes it consistent by also rendering it in the bot list
https://mattermost.atlassian.net/browse/MM-16283
=> MM-16283 Render markdown in bot account descriptions

utils/text_formatting.jsx, utils/text_formatting_channel_links.test.jsx, utils/text_formatting_hashtags.test.jsx
The `(^|\s)` only allowed channel links to appear at the start of the string or after whitespace. This makes it so that they can appear after any non-word character.
https://mattermost.atlassian.net/browse/MM-15749
=> MM-15749 Allow channel links in brackets

package-lock.json, package.json
The post list date separators now will take into account the user timezone
https://mattermost.atlassian.net/browse/MM-16387
- Has redux changes (https://github.com/mattermost/mattermost-redux/pull/855)
- Has mobile changes (https://github.com/mattermost/mattermost-mobile/pull/2888)
=> MM-16837 Set post list date separator based on user timezone

components/rhs_comment/rhs_comment.jsx, sass/layout/_post.scss, sass/responsive/_tablet.scss
MM-16444 - Adding usernames back to compact view
https://mattermost.atlassian.net/browse/MM-16444
=> MM-16444 - Adding usernames back to compact view

components/admin_console/admin_definition.jsx
File upload/download restriction settings for mobile should be behind the "Compliance" licence feature flag in the system console in order to match how they are actually applied by the mobile app.
https://mattermost.atlassian.net/browse/MM-16073
=> MM-16073: File up/download restrictions behind Compliance licence flag.

components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap, components/post_view/message_attachments/message_attachment/message_attachment.jsx
Emoji is displayed after the poll ends. 
Fixes: [MM-14530] Render emojis in Message Attachment field titles
Fixes https://github.com/mattermost/mattermost-server/issues/10433
[MM-14530]: https://mattermost.atlassian.net/browse/MM-14530
=> MM-14530 Displays emoji in poll after the poll is ended.

components/suggestion/at_mention_provider/at_mention_provider.jsx, components/suggestion/at_mention_provider/at_mention_provider.test.jsx, package-lock.json, package.json
This commit adds suggestions for `first_name`, `last_name` and
`nickname` when matching for autocompletion, so a user with last name
"Smith Junior" will now be matched by the term `@junior`
https://mattermost.atlassian.net/browse/MM-15942
- [Has enterprise changes](https://github.com/mattermost/enterprise/pull/445)
- [Has redux changes](https://github.com/mattermost/mattermost-redux/pull/846)
=> [MM-15942] Split user profile details by whitespace during autocomplete

components/integrations/bots/add_bot/add_bot.jsx
This pull request leverages the `isValidUsername()` utils function to verify the username.  Previously, the verification was done server-side with a createBot submission.  The problem with this method is that serverside validation does not check that a username only begins with an alpha character `[a-z]`.  
Here is a screen capture of the new validation error.  Please note/verify the following:
1. Error adjusts according to incorrect username types.
2. Note the `Create Bot Account` button does not change with an invalid username submission.
https://mattermost.atlassian.net/browse/MM-16149
Whether server-side enforcement should be addressed is debatable, but the change would affect more than a few tests.  See Jira ticket link comments for detail of files affected.
This code is where user …
=> [MM-16149] Fix username validation message for Bot creation.

cypress/integration/account_settings/display/channel_display_mode_spec.js, cypress/integration/account_settings/general/nickname.js, cypress/integration/at_mentions/at_mentions_spec.js, cypress/integration/channel/edit_message_spec.js, cypress/integration/channel/message_deletion_spec.js, cypress/integration/channel/message_draft_spec.js, cypress/integration/channel/message_draft_then_switch_channel_spec.js, cypress/integration/channel/message_edit_post_with_attachment_spec.js, cypress/integration/email/mention_email_notification_spec.js, cypress/integration/login/login_spec.js, cypress/integration/login/signup_spec.js, cypress/integration/post_header/post_header_spec.js, cypress/integration/search/search_user_post.js, cypress/plugins/post_message_as.js, cypress/support/api_commands.js, cypress/support/ui_commands.js
=> Fix E2E flaky tests

package-lock.json, package.json, webpack.config.js
Added support for LiveReload to Webpack.
Using https://www.npmjs.com/package/webpack-livereload-plugin .
Enabled only in DEV mode and only if MM_LIVE_RELOAD env variable is set.
In order to use it - install https://chrome.google.com/webstore/detail/remotelivereload/jlppknnillhjgiengoigajegdpieppei/related?hl=en or similar from Chrome.
Now, after every webpack rebuild - the webapp will reload.
=> Added livereload support

actions/user_actions.jsx, actions/user_actions.test.js, components/more_direct_channels/index.js, components/more_direct_channels/more_direct_channels.jsx, components/more_direct_channels/more_direct_channels.test.jsx, package-lock.json, package.json
Adds the hability to search group channels as the user types their search query in the more direct channels component.
https://mattermost.atlassian.net/browse/MM-13500
- [Has server changes](https://github.com/mattermost/mattermost-server/pull/10805)
- [Has redux changes](https://github.com/mattermost/mattermost-redux/pull/828)
- [Has API docs](https://github.com/mattermost/mattermost-api-reference/pull/445)
=> [MM-13500] Add group channel search to the More Direct Channels component

.circleci/config.yml
This PR adds the ability to build the docker image for the mattermost application.
This is the foundation to use the new test servers using the mattermost cloud infrastructure.
every PR will build the docker image and tag with the short commit hash.
=> Build docker image for PR

cypress/integration/channel/message_emoji_jumbo_spec.js
Added Automated Cypress Test to verify 'M15011 - Emojis show as jumbo in reply thread"
Fixes https://github.com/mattermost/mattermost-server/issues/10574
None
=> GH-10574: Added Automated Cypress Test to verify 'M15011 - Emojis show as jumbo in reply thread'

components/admin_console/admin_definition.jsx
Instead of hiding the entire notification section when restricted admin is enabled, this commit shows the section but hides only the "Notification From Address:" setting.
https://mattermost.atlassian.net/browse/MM-16236
=> [MM-16236] System Console restricted admin: Notifications items are missing for restricted system admin

components/admin_console/admin_sidebar/admin_sidebar.jsx
Add auto focus when you access the admin console into the search box to allow
you to directly go to the admin console and start typing
[MM-16589](https://mattermost.atlassian.net/browse/MM-16589)
=> Auto focus search box in admin console

components/searchable_user_list/searchable_user_list.jsx, cypress/integration/team/teammates_pagination_spec.js, cypress/support/api_commands.js
E2E Cypress test to page through the team members list. Besides the test, new IDs are added to the Searchable_User_List (Prev/Next buttons and total member count label) component. A batch-join helper function is also added to the API commands support file.
The test has some steps that may need some explanation: a) The MaxUsersPerTeam setting must be greater than 60; b) The available test users must be greater than 60; c) The /teams/_id/members/batch API allows 20 in one request, so we break the whole team into chunks of 20.
Fixes https://github.com/mattermost/mattermost-server/issues/10544
N/A
=> MM-14868 Team Admin can use Next button to page through list in Manage Members

cypress/integration/account_settings/display/message_display_mode_spec.js, cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js, cypress/support/index.js
Fix failing tests on account_settings specs
none
=> E2E: Fix failing tests on account_settings specs

components/user_profile/__snapshots__/user_profile.test.jsx.snap, components/user_profile/user_profile.jsx
MM-16648 - Updating bot badge in center channel
Looks like the bot tag is being used in different ways. Just making them consistent.
So the badge for the bot needs to sit outside the `user-popover`.
https://mattermost.atlassian.net/browse/MM-16648
=> MM-16648 - Updating bot badge in center channel

components/admin_console/admin_sidebar_header/admin_sidebar_header.jsx, components/channel_header_dropdown/index.js, components/channel_header_dropdown/mobile_channel_header_dropdown.js, components/channel_header_mobile/collapse_lhs_button/collapse_lhs_button.js, components/sidebar/header/sidebar_header_dropdown_button.jsx, components/svg/menu_icon.jsx, sass/layout/_forms.scss
MM-16393 - Cleaning up mobile header, and making status icon conditional
https://mattermost.atlassian.net/browse/MM-16393
=> MM-16393 - Cleaning up mobile header

cypress/integration/login/signup_spec.js
Fix valid name due to [recent change](https://github.com/mattermost/mattermost-webapp/pull/2843/files#diff-8daba1eac1cd073c780bd74f0a3681c4R285)
none
=> E2E: fix valid name due to recent change

components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.jsx.snap, components/sidebar/sidebar_channel/sidebar_channel.jsx, components/sidebar/sidebar_channel/sidebar_channel.test.jsx, components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
`SidebarChannelButtonOrLink` could receive either a string or a `FormattedMessage` as its `displayName` prop, but it was treating it as if it was always a string. This changes it so that it only ever receives a string.
=> Fix attempt to use non-string as aria-label

components/admin_console/admin_definition.jsx
Changes the admin definition file to allow "Connection Security" setting under "SMTP" to be visible on team edition.
https://mattermost.atlassian.net/browse/MM-16627
=> [MM-16627] Show connection security setting on team edition

components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
As a recent change we require the currently authenticated users password to change the eMail as a security measure. Since the currently authenticated users email can be changed in the user settings, we are hiding it in order to avoid a authentication error.
@amyblais @grundleborg Is this intended for 5.13 or 5.14?
https://mattermost.atlassian.net/browse/MM-16727
=> [MM-16727] Hide Change eMail option for currently logged in user in admin area

components/create_comment/create_comment.jsx, components/create_comment/create_comment.test.jsx
The previous version would cause `this.focusTextbox` to be called any time the CreateComment received new props, forcing the cursor to the end of the textbox. This makes it so that it's only called when a post is selected.
https://mattermost.atlassian.net/browse/MM-16673
=> MM-16673 Only focus RHS textbox when necessary

actions/notification_actions.jsx, actions/notification_actions.test.jsx, actions/post_utils.js, actions/post_utils.test.js
If MM is focused and the notification is a reply to a thread
that is being shown in the RHS, then ignore it even if it's
in another channel - and don't make it bold (unread).
https://mattermost.atlassian.net/browse/PLT-4951
Fixes https://github.com/mattermost/mattermost-server/issues/7718
=> [PLT-4951] Don't send notifications if thread is showing in RHS

components/search_bar/search_bar.jsx, components/suggestion/__snapshots__/command_provider.test.js.snap, components/suggestion/search_channel_provider.jsx, components/suggestion/search_suggestion_list.jsx, components/suggestion/search_user_provider.jsx, components/suggestion/suggestion.jsx, sass/components/_search.scss
MM-15993 - Making autocomplete a11y compatible
https://mattermost.atlassian.net/browse/MM-15993
=> MM-15993 - Making autocomplete a11y compatible

plugins/mobile_channel_header_plug/__snapshots__/mobile_channel_header_plug.test.jsx.snap, plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx, plugins/mobile_channel_header_plug/mobile_channel_header_plug.test.jsx
This seems to be a regression caused by https://github.com/mattermost/mattermost-webapp/pull/2933. Originally, it rendered the button in both the header and dropdown, then it rendered the text item in both places. Now, it'll render the button in the header and the text in the dropdown.
https://mattermost.atlassian.net/browse/MM-15652
=> MM-15652 Render header plugin correctly in mobile view

.eslintrc.json, components/post_view/message_attachments/message_attachment_list.jsx, e2e/cypress/fixtures/hooks/message_menus.json, e2e/cypress/fixtures/hooks/message_menus_with_datasource.json, e2e/cypress/integration/interactive_menu/basic_options.js, e2e/cypress/plugins/index.js, e2e/cypress/plugins/post_incoming_webhook.js, e2e/cypress/plugins/post_message_as.js, e2e/cypress/support/api_commands.js, e2e/cypress/utils/index.js, e2e/package-lock.json, e2e/package.json, e2e/webhook_serve.js
Add E2E for interactive menus - basic options.  This PR covered test cases for the ff:
__To follow: Test cases for interactive menus with users and channels as options.__
Other changes included:
- add small webhook server with additional `express` and `body-parser` dependencies on `/e2e` subproject.  Such webhook server is exposed as `http://localhost:3000` on local dev and will be `https://cypress.test.masttermost.com/webhook` on Cypress test server (PR to follow on shared pipelines)
- introduced `NODE_ENV=qa` which will be used when running test at Cypress test server. Such will be used to configure other settings like `baseUrl`, `mailboxAPI`, etc. (PR to follow both on the webapp and shared pipelines)
Jira ticket: [MM-15887](https://mattermost.atlassian.net/browse/MM-15887)
=> [MM-15887] E2E: add test for interactive menus - basic options

components/admin_console/admin_definition.jsx, i18n/en.json
This is following 
1. Mobile support added in v1.18 on Apr 16
2. Updated instruction for Office 365 SSO that covers the new Azure App Registration method. https://github.com/mattermost/docs/pull/2829
=> Remove beta label from O365 SSO

components/profile_popover/__snapshots__/profile_popover.test.jsx.snap, components/profile_popover/index.js, components/profile_popover/profile_popover.jsx, components/profile_popover/profile_popover.test.jsx
This change hides the option to add a user to a channel in the
profile popup if that user is not part of the team. This improves
the experience where the user could not be added to any channels in
the current team anyway.
https://mattermost.atlassian.net/browse/MM-16056
=> [MM-16056] Hide add-to-channel option if user in not part of team

e2e/cypress/integration/at_mentions/at_mentions_spec.js, e2e/cypress/integration/channel/message_spec.js, e2e/cypress/integration/interactive_menu/basic_options.js, e2e/cypress/integration/search/date_filter_spec.js, e2e/cypress/integration/system_console/demoted_user_spec.js, e2e/cypress/plugins/post_message_as.js, e2e/cypress/support/index.js, e2e/cypress/support/task_commands.js
E2E: add post-verification on Cypress task that the request is successfully completed by wrapping those tasks into commands.
By doing so, Cypress awaits in a certain default period of time that the (http) request is indeed successful before actually doing/verifying next step.  This prevents flakiness due to timing issue especially when dealing with network request.
n/a
=> E2E: add post-verification on Cypress task that the request is successfully completed

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx
It looks like [this line](https://github.com/mattermost/mattermost-webapp/pull/910/files#diff-827322d72aefea3f612c4852b30b0de5R552) of the previous logic was backwards, causing it to not actually load missing users. I also changed that line to use `getMissingProfilesByIds` instead of `getProfilesByIds` so that it will only load users that it doesn't already have
This PR is based off of https://github.com/mattermost/mattermost-webapp/pull/3077 so you can see changes specific to it here: https://github.com/mattermost/mattermost-webapp/compare/mm16060...mm16511
https://mattermost.atlassian.net/browse/MM-16511
=> MM-16511 Load missing users who start typing 

e2e/cypress/integration/markdown/markdown_image_spec.js, e2e/cypress/integration/multi_team/system_message_spec.js
Fixed flaky test of `multi_team/system_message_spec.js` - It seems to be a race condition between returning a system message vs getting last post ID, after patching a channel.  Fixed by posting a regular message first (to reinit WS connection) and patching a channel in before hook, so that system message is posted before the actual test.
Updated test for `markdown/markdown_image_spec.js` - due to [recent change](https://github.com/mattermost/mattermost-webapp/pull/3065/files#diff-8c8a73f5938837547fb13a6d9a3ab6bdR137)
n/a
=> E2E: Fix flaky tests on system message spec and update markdown spec due to latest structure change

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, components/size_aware_image.test.jsx
The styles here were introduced so that the image tag loads behind the svg loader. With recent changes we have a button tag on top of the image causing the button to take a little space causing a minor scroll pop. These styles are intended for the swapper in general than the image so moving them to the button tag
https://mattermost.atlassian.net/browse/MM-16906 There was a PR for the ticket which fixes most of the problem but there is still minor scroll pop left
=> MM-16906 Fix styles for size_aware_image component

components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap, components/post_view/post_body_additional_content/post_body_additional_content.jsx, sass/layout/_post.scss, sass/responsive/_mobile.scss, sass/responsive/_tablet.scss
MM-16803 - Updating post styling for emojis, files and timestamps
https://mattermost.atlassian.net/browse/MM-16803
=> MM-16803 - Updating post styling

e2e/cypress/integration/markdown/markdown_image_spec.js, e2e/cypress/integration/markdown/markdown_text_spec.js, e2e/cypress/integration/team/teams_spec.js
Fix flaky test on
- `markdown/markdown_text_spec.js`
- `team/teams_spec.js`
Note that this is submitted on top of another PR.  Will rebase once it's merged or the issue there is fixed.
n/a but based on [Daily Cypress test 104](https://build-push.internal.mattermost.com/job/mattermost-ui-testing/job/mattermost-cypress/104/consoleFull)
=> E2E: Fix flaky test on markdown and team specs

components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
- Should always display `deactivateMemberModal`, no matter what `DisableBotsWhenOwnerIsDeactivated` is set to.
- Fixed another possible bug -- if there was no data returned from a redux action (or no bots?), the `deactivateMemberModal` wouldn't have opened. There's no reason (that I can see) to make that conditional on the returned data.
- Not sure why the community member introduced the `loading` state variable -- it isn't used in the rest of the file. @sudheerDev?
- Fixes [MM-16533](https://mattermost.atlassian.net/browse/MM-16533)
#2879
=> [MM-16533] User deactivation does not work when "Disable bot accounts when owner is deactivated" is set to False

e2e/package-lock.json, e2e/package.json, e2e/webhook_serve.js
- Introduced `start-server-and-test` to handle starting of webhook server and verifying its URL to be ready for testing
- added `/` GET endpoint to verify health check of webhook server
- added 2 npm scripts such as `test` and `test:group` for CI to refer on this command when running full E2E test.
Refer to https://github.com/mattermost/mattermost-shared-pipelines/pull/22 for corresponding changes to test server.
n/a
=> Fix Cypress run script

components/post_view/post_list_virtualized/index.js
Added a check for postIds length before checking for last post in the channel. 
https://mattermost.atlassian.net/browse/MM-16907
=> MM-16907 White screen when disabling Join/Leave Messages and switching to a specific channel

utils/a11y_controller.js
This PR fixes a bug whereby the new accessibility controller doesn't correctly 'turn off' when a modal is open, preventing up/down arrow keys from working in `<textarea>`'s for instance.
[MM-17003](https://mattermost.atlassian.net/browse/MM-17003)
=> [MM-17003] Fix stuck up/down arrow keys in modals

components/post_view/post_list_ie/index.js
Channel prop is required for IE11 which was removed https://github.com/mattermost/mattermost-webapp/pull/3049/files#diff-5d65c7ac490b08b60adf963369908186L58.
The prop wasn't needed for other browsers so instead now adding it to the specific IE file so it can be removed in 5.16v 
https://mattermost.atlassian.net/browse/MM-17007
=> MM-17007 Fix IE11 crash with channel prop error

components/emoji_picker/emoji_picker.jsx, components/emoji_picker/emoji_picker.test.jsx
Creates a helper function which is called in the EmojiPicker component and strips leading/trailing colons from the input.
https://github.com/mattermost/mattermost-server/issues/MM-14018
https://github.com/mattermost/mattermost-server/issues/10276
None
=> [MM-14018] Ignore leading/trailing colon in emoji picker search

e2e/cypress/integration/search/date_filter_spec.js
Wait for loading spinner to not be visible
Increase requestTimeout for the searchRequest
Ensure search items visible before continuing in one of the specs.
N/A
=> Address flakiness in search date filter e2e tests

e2e/cypress/integration/post_header/post_header_spec.js
Fix post header cypress tests.
Focus away from relevant area prior to making additional checks.
In one test, verify that we have specific class items, not that they are the only classes on it.
N/A
=> fix failing e2e post header specs

e2e/cypress/support/api_commands.js
Clear ALL cookies after clearing a specific set of cookies. Getting/Setting cookies is async, so timing SHOULD be quick, this should should ensure cookies are blown away.
Additionally, chained a .then after logging in with the new user so that we know that request completeed.
N/A
=> Clear all cookies after clearing specific cookies

e2e/cypress.json, e2e/cypress/integration/interactive_menu/basic_options.js, e2e/cypress/plugins/index.js, e2e/cypress/utils/index.js
Fix failing test with interactive menus.
Note: Since the mattermost instance both in local and test server interacts with each other via local network, it's no longer necessary to use full domain name as `webhookBaseUrl ` as it will only complicate things. 
Carlos fixed the webhook server in CI.
n/a
=> Fix failing test with interactive menus

components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.js.snap, components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx, components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js
This pull request will change the behavior when a user, that also owns bots is being disabled.
If a user owns bots, and the user is disabled, a warning is shown stating bots will also be disabled.
**Previous functionality**
- Bot warning message is shown regardless if the owner's bots were active or disabled.
**New Functionality**
- Bot warning shown if any of owner's bots are not disabled.
- No bot warning shown if all of owner's bots are disabled.
https://mattermost.atlassian.net/browse/MM-16534
=> [MM-16534] if user has bots, but the bots are disabled, don't show warning that bots will be disabled

components/post_view/post_list_virtualized/index.js, components/post_view/post_list_virtualized/post_list_virtualized.jsx, components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
* The crash happens because of the recursive setState call of autoRetryEnable.
After calling `MAX_EXTRA_PAGES_LOADED` we are setting state to disable autoretry but if the
call is recursively made few times in fast intervals then setState causing infinite loop in react
* Adding a new prop `postListchunk` because the filtered system messages cause issue for
loading more posts as they will never be part of posListIds we basically end up calling APIs with
same postId
Note: making PR to 5.13v branch. I will make a new PR to master as there will be minor changes for bi-directional scroll
=> MM-16907 Fix for White screen when disabling Join/Leave Messages and switching to a specific channel

plugins/rhs_plugin/index.js
When a plugin is uninstalled and reinstalled, an exception can occur
accessing the `title` attribute of a `find` operation that yields no results. I came across this trying to re-deploy the GitHub plugin during local development.
None.
=> harden rhs sidebar to a plugin reinstall

e2e/cypress/integration/channel/message_reaction_spec.js, e2e/cypress/support/ui_commands.js
message_reaction_spec: 
- Selectors were not working, changed them to work.
- Switched assertions to 'have.text'
ui_commands:
- Now check for textbox to be clear before continuing. This should fix this [build error](https://build-push.internal.mattermost.com/job/mattermost-ui-testing/job/mattermost-cypress/115/testReport/junit/(root)/MM-15012%20-%20Emojis%20are%20not%20jumbo%20when%20accompanied%20by%20text/Messaging_MM_15012___Emojis_are_not_jumbo_when_accompanied_by_text/), or at least fail in a better way. This may also help other flaky tests if they somehow continue before a message is truly posted.
N/A
=> small fixes for failing tests

components/interactive_dialog/interactive_dialog.jsx, e2e/cypress/integration/interactive_dialog/interactive_dialog_spec.js, e2e/cypress/support/api_commands.js, e2e/utils/webhook_utils.js, e2e/webhook_serve.js
Add tests for interactive dialogs.  This includes the following:
- UI check
- Cancel button works
- "X" closes the dialog
- Correct error messages displayed if empty form is submitted
- Email validation
- Number validation
To follow:
- Selecting a Number with the up/down arrows within the "Number Selector" field
- Individual "User" and "Channel" screens are scrollable
- Dropdown arrow to the right of selector field
Note:  Will submit PR to shared pipelines to add required env variable (`CYPRESS_webhookBaseUrl`)
Jira ticket: [MM-15888](https://mattermost.atlassian.net/browse/MM-15888)
=> MM-15888 Add E2E for interactive dialogs

utils/a11y_controller.js
This PR modifies the a11y_controller to only trap a11y keyboard events when elements actually exist for the keyboard event type. Fixes a bug preventing up/down arrow keys from working in comment textareas.
[MM-17003](https://mattermost.atlassian.net/browse/MM-17003)
=> [MM-17003] Only trap a11y keyboard events when needed

e2e/run_tests.js
Need to use the correct property name to tally all of the failed test results
N/A
=> use correct property name to tally failed tests in e2e

components/invitation_modal/index.js
Fixing guest disabled on invitation modal
=> Fixing guest disabled on invitation modal

components/root/root.jsx
Purposely disables a11y navigation controller in IE11.
https://mattermost.atlassian.net/browse/MM-17086
=> [MM-17086] Don’t run a11y navigation in IE11

components/file_upload/__snapshots__/file_upload.test.jsx.snap, components/file_upload/file_upload.jsx, e2e/cypress/integration/channel/message_draft_with_attachment_then_switch_channel_spec.js, e2e/cypress/integration/channel/message_edit_post_with_attachment_spec.js, e2e/cypress/support/ui_commands.js
Fix failing E2E test due to [recent DOM structure change](https://github.com/mattermost/mattermost-webapp/pull/3136/files#diff-39ad15d3a8de7143757521997af3381bL603).
Also, 
- refactor file upload command (change subject to input and set force to true)
- scroll channel name into view (solve flakiness when there are too many channels in the sidebar)
none
=> Fix failing E2E test due to recent DOM structure change

e2e/run_tests.js
This generates short test summary to easily view stats without actually opening the report link.
none
=> Generate short summary to easily pickup for reporting

components/confirm_modal.jsx, e2e/cypress/integration/system_console/revoke_all_sessions.js
Added test to verify Revoke All Sessions functionality in the System Console. This includes the following steps:
1. Login as System Admin and navigate to Users page. 
2. Check if the Revoke All Sessions button is displayed. 
3. Click on the Revoke All Sessions button. A message "This action revokes all sessions in the system. All users will be logged out from all devices. Are you sure you want to revoke all sessions?" should be displayed. 
4. Click on Cancel in the confirmation message. The user's session should still be active. 
5. Click on the Revoke All Session button and confirm. 
6. Check if the current user is logged out and redirected to the login page.
JIRA Ticket: [MM-17020](https://mattermost.atlassian.net/browse/MM-17020)
None
This test expects the changes mentioned in the PR …
=> Added test SC17020 - Revoke All Sessions from System Console

utils/a11y_controller.js, utils/constants.jsx
This PR includes some updates to the a11y_controller including better handling of keyboard vs. mouse events in the main 3 browsers (Chrome, Firefox, Safari), specifically around tabbing now that the rest of the a11y functionality has been merged. Additionally, ESDoc comments have been added.
Tested locally in Chrome, Firefox, Safari and Desktop (on Mac).
[MM-16379](https://mattermost.atlassian.net/browse/MM-16379) cont.
=> [MM-16379 cont.] A11y controller updates

actions/views/create_comment.jsx, components/create_post/create_post.jsx, components/post_profile_picture/post_profile_picture.jsx
* The profile_picture component now looks for post.props keys to override images but as temp messages made on client does not have any props object this causes JS error
* Adding props object for comment and main text boxes
https://mattermost.atlassian.net/browse/MM-17128
=> MM-17128 Fix for JavaScript error when posting: Cannot read property 'override_icon_url' of undefined

components/post_view/post_list_virtualized/post_list_virtualized.jsx, package-lock.json, package.json
Scroll correction happens based on https://github.com/mattermost/mattermost-webapp/blob/5cd69aa0d43560bb1b162dd4a3d326a713a1fd86/components/post_view/post_list_virtualized/post_list_virtualized.jsx#L163 but as scrollheight could be zero initally the state of `atBottom` is set to `true` causing post list to not correct the scroll position
using https://github.com/mattermost/react-window/tree/release-5.12 as we need to cherrypick 5.12v hash with this PR https://github.com/mattermost/react-window/pull/21
=> MM-17078 Fix for scroll position with unreads between 30-60

components/suggestion/at_mention_provider/at_mention_suggestion.jsx, components/suggestion/generic_user_provider.jsx
Badges are positioned at the end of the username/fullname text, instead of in between.
[MM-17202](https://mattermost.atlassian.net/browse/MM-17202)
=> Fixing badge positioning in @ suggestions and ctrl k switcher

components/announcement_bar/announcement_bar.jsx
Do not remove the fixed class on body if there are other announcement bar.
Keep a track of the announcement banners in the UI by adding a count to the body. We don't have a count of the announcement bars in UI so resorting to rather DOM than a react way of doing this.
There are different types of banner so a react state for tracking or children count does not work. Other option is to add redux actions for each mounted component but seems like an overkill.
https://mattermost.atlassian.net/browse/MM-17115
Note: It is hard to add tests for these as jest has changes about mocking DOM
=> MM-17115 Dismissing a banner causes banner overlap in the UI for a non-dismissable banner behind it

sass/layout/_post.scss
The width and height were being set twice after the recent CSS changes, causing compact view to be offset.
https://mattermost.atlassian.net/browse/MM-17221
=> MM-17221 Fix status positions on posts in compact view

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, sass/layout/_markdown.scss
* Display inline causes issues with the space that an svg should occupy
as it does not respect dimensions
* Changing to inline-image and add max dimensions from images
Before:
After:
https://mattermost.atlassian.net/browse/MM-16458
=> MM-16458 Fix for large markdown images causing a scroll pop

e2e/cypress/integration/channel/header_spec.js
Fix E2E for header mainly due to change introduced by guest account.
For the existing header specs, do the test in separate team where there's no guest account.  I supposed, we'll have additional header test where we'll check related elements with guest account.
=> Fix E2E for header mainly due to change introduced by guest account

e2e/run_tests.js
This is a follow PR to https://github.com/mattermost/mattermost-webapp/pull/3194.
This fixes the issue of not properly sending the stats field value for Cypress reporting.
=> Escape % key to prevent error passing such value into command line

sass/layout/_post.scss
This PR fixes the incorrectly visible file browse input element showing in Firefox. The structure of the component changed for a11y reasons, necessitating a change in the CSS as well.
https://mattermost.atlassian.net/browse/MM-17097
=> [MM-17079] Fix for incorrectly visible file browse input

components/post_view/post_list/post_list_virtualized.jsx, components/post_view/post_list/post_list_virtualized.test.jsx
The state check for scrollToBottom should be based on newerPosts props rather than olderPosts props. This causes a rerender in the parent causing the image to mount again
https://mattermost.atlassian.net/browse/MM-16908
=> MM-16908 Fix for Image attachments display loading indicator when receiving a new message

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx
Cherry pick of #3241 on release-5.14.
- #3241: MM-16458 Fix for large markdown images causing a scroll pop
=> Automated cherry pick of #3241

sass/responsive/_mobile.scss
Fixing main menu color in mobile
This bug was introduced in this commit 2009444241757fc7eb62da8a1c707f2fea3a91ca. I'm not 100% sure if I'm not breaking anything else with this change, and I don't know the original reason to remove the "color" from the CSS, so maybe Assad knows if this is breaking anything else.
[MM-17306](https://mattermost.atlassian.net/browse/MM-17306)
=> Fixing main menu color in mobile

components/post_view/post_list/post_list.jsx
Fixes JS error from undefined prop when leaving a public channel.
JS error occurs at https://github.com/mattermost/mattermost-webapp/blob/master/components/post_view/post_list/post_list_virtualized.jsx#L208, `...postListIds` is `undefined is not iterable`.
https://mattermost.atlassian.net/browse/MM-17281
=> MM-17281: Adds default empty array for postListIds prop.

components/post_view/post_list/post_list.jsx
Cherry pick of #3239 on release-5.14.
- #3239: MM-17281: Adds default empty array for postListIds prop.
/cc  @mkraft
=> Automated cherry pick of #3239

components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_row.test.jsx.snap, components/admin_console/team_channel_settings/channel/list/channel_row.jsx, components/admin_console/team_channel_settings/channel/list/index.js, components/admin_console/team_channel_settings/team/list/index.js
Channels and Teams were ordered by name instead of display_name 
Fixes https://mattermost.atlassian.net/browse/MM-17305
=> MM-17305 - Fixed channel/teams list sort order

components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_row.test.jsx.snap, components/admin_console/team_channel_settings/channel/list/channel_row.jsx, components/admin_console/team_channel_settings/channel/list/index.js, components/admin_console/team_channel_settings/team/list/index.js
Cherry pick of #3251 on release-5.14.
- #3251: Fixed channel/teams list sort order
/cc  @reflog
=> Automated cherry pick of #3251

components/widgets/menu/menu.jsx, components/widgets/menu/menu.test.jsx
MM-17324 - Updating dropdown focus trap
Now dropdown menus will not have the first item focused. You can still select different menu options if you press tab. However, if you stop using your keyboard, and use your mouse instead the highlight will shift based on your mobile position.
https://mattermost.atlassian.net/browse/MM-17324
=> MM-17324 - Updating dropdown focus trap

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, sass/components/_files.scss
The nesting of svg element changed with recent changes of adding buttons causing the parent button to not occupy space as it is an inline-block element. Adding a width and text align to have the image aligned to left
Before:
After:
https://mattermost.atlassian.net/browse/MM-17326
=> MM-17326 Fix for svg not rendering in posts

components/suggestion/emoticon_provider.jsx
See comment in code:
```js
// findAndSuggestEmojis uses the provided partialName to match anywhere inside an emoji name.
//
// For example, typing `:welc` would match both `:welcome:` and `:youre_welcome:` if those
// emojis are present in the local store. Note, however, that the server only does prefix
// matches, so a query to populate the local store for `:welc` would only return `:welcome:`.
// This results in surprising differences between a fresh load of the application, and the
// changes to the cache from expanding the cache with emojis found in existing posts.
//
// For now, this behaviour and difference is by design. @see MM-17320.
```
https://mattermost.atlassian.net/browse/MM-17320
=> MM-17320: document server/client autocomplete differences

components/emoji_picker/emoji_picker.jsx
Upon changing the emoji picker to highlight the first emoji in a category, I stopped the window from scrolling to the actual category header. This fixes that issue.
https://mattermost.atlassian.net/browse/MM-17316
=> [MM-17316] Force emoji picker scrolling to category header

components/emoji_picker/emoji_picker.jsx
Cherry pick of #3269 on release-5.14.
- #3269: Force emoji picker scrolling to category header
=> Automated cherry pick of #3269

components/create_post/create_post.jsx
This changes the default state of the create post "Preview Mode" to false after switching channels. Previously, this mode would persist, locking the post creation text input on the next opened channel.
Note that the pre-release feature "Show markdown preview..." must be enabled in order to use the "Preview" link:
https://mattermost.atlassian.net/browse/MM-17360
N/A
=> [MM-17360] Reset post preview mode to false when switching channels

sass/components/_popover.scss
Cherry pick of #3293 on release-5.14.
- #3293: MM-17363 - Removing box shadow for selected item
=> Automated cherry pick of #3293

components/admin_console/team_channel_settings/users_to_be_removed_modal.jsx
When I enable sync/constraint on a team, and that will remove users, the messaging at the bottom has a link to open a modal with a list of users who will be removed, as expected. However, if I close that modal and click the link to open it again, nothing happens.
Fixes https://mattermost.atlassian.net/browse/MM-17400
=> MM-17400 - Repeated clicking of View These Users on team management page does not display the expected modal

components/__snapshots__/save_button.test.jsx.snap, components/save_button.jsx, components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap, components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
Under certain circumstances, the save button is failing when clicked with a node error. It seems to be caused due React trying to unmount a text-only component. This PR wraps the text sent to the component with a `span`, preventing the error.
https://mattermost.atlassian.net/browse/MM-17338
=> [MM-17338] Wrap save_button message in span to avoid "node not a child of this node" error

components/admin_console/team_channel_settings/channel/details/channel_details.jsx
When toggling sync for channel - the list of removed users should be refreshed
Fixes https://mattermost.atlassian.net/browse/MM-17383
=> MM-17383 - check removed users on sync toggle

components/sidebar/sidebar_channel/index.js, components/sidebar/sidebar_channel/sidebar_channel.jsx, components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx, components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx, package-lock.json, package.json, sass/layout/_sidebar-left.scss, utils/utils.jsx
Disable displaying LHS bot-icon. Will re-enable as part of https://mattermost.atlassian.net/browse/MM-17422
This reverts commit c74f4caba2cbe496683d16a9b57d92c9a8618c7f.
https://github.com/mattermost/mattermost-webapp/pull/3026
Fixes https://mattermost.atlassian.net/browse/MM-17294
https://github.com/mattermost/mattermost-webapp/pull/3026
=> MM-17294 - Revert "MM-15452 - Add ability to override LHS icon for bot accounts (#3026)

components/rhs_comment/rhs_comment.jsx
This PR fixes an issue where the username is not shown next to the timestamp in consecutive RHS comments, in mobile-browser view.
https://mattermost.atlassian.net/browse/MM-17291
=> [MM-17291] Show username for consecutive RHS comments, on mobile-browser view

.circleci/config.yml
fix the build docker when building the automated cherry pick
=> use sha1 instead of branch name

actions/global_actions.test.js, components/permissions_gates/any_team_permission_gate/any_team_permission_gate.test.jsx, package-lock.json, package.json
This PR updates the mattermost-redux hash to fix the issue of treating archived teams as valid teams to browse.
https://mattermost.atlassian.net/browse/MM-17019
Fixes "On joining first team, team sidebar may flash open then closed, or may flash back and forth and then stay visible"
- Has redux changes: https://github.com/mattermost/mattermost-redux/pull/888
Pulling from `mattermost-redux@master` to `mattermost-webapp@master`
=> [MM-17019] Filter archived teams out of team membership selectors

actions/global_actions.test.js, components/permissions_gates/any_team_permission_gate/any_team_permission_gate.test.jsx, package-lock.json, package.json
This PR updates the mattermost-redux hash to fix the issue of treating archived teams as valid teams to browse.
https://mattermost.atlassian.net/browse/MM-17019
Fixes "On joining first team, team sidebar may flash open then closed, or may flash back and forth and then stay visible"
- Has redux changes: https://github.com/mattermost/mattermost-redux/pull/888
Pulling from `mattermost-redux@release-5.14` to `mattermost-webapp@release-5.14`
=> [MM-17019] Filter archived teams out of team membership selectors (release 5.14)

components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap, components/channel_members_dropdown/channel_members_dropdown.jsx
From the original tickets, the 'Remove Member' buttons were not accounted for when making accessibility changes. These buttons have been removed in master, but remain in v5.14. This PR adds the fixes necessary to v5.14
https://mattermost.atlassian.net/browse/MM-16054
=> [MM-16054] Accessibility fixes to buttons on Manage Members for channel

components/post_view/post_list/post_list_virtualized.jsx, components/post_view/post_list/post_list_virtualized.test.jsx
* Previous logic was to scroll to new message line if there is one but if date line is above that then it gets cutoff or is partially above the fold
* Adding a specific exception of scrolling to date line if it is just above the new message line so it is clearly visible.
Before:
After:
https://mattermost.atlassian.net/browse/MM-17354
=> MM-17354 Fix for date line being cutoff when entering a channel with unreads

components/create_comment/__snapshots__/create_comment.test.jsx.snap, components/create_comment/create_comment.jsx, components/create_post/__snapshots__/create_post.test.jsx.snap, components/create_post/create_post.jsx, components/create_post/create_post.test.jsx, components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap, components/edit_post_modal/edit_post_modal.jsx, components/textbox/textbox.jsx, components/textbox/textbox_links.jsx, sass/components/_modal.scss, sass/layout/_forms.scss, sass/layout/_post.scss, utils/utils.jsx
MM-17361 - Send messages on preview mode
Allows users to send messages on the preview mode, for the center channel textbox, and the edit post modal textbox.
This also disables the emoji picker and file picker if the preview mode is enabled.
https://mattermost.atlassian.net/browse/MM-17361
=> MM-17361 - Send messages on preview mode

components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.jsx.snap, components/add_groups_to_team_modal/__snapshots__/add_groups_to_team_modal.test.jsx.snap, components/channel_selector_modal/__snapshots__/channel_selector_modal.test.jsx.snap, components/multiselect/__snapshots__/multiselect.test.jsx.snap, components/multiselect/multiselect.jsx, components/multiselect/multiselect_list.jsx, components/team_selector_modal/__snapshots__/team_selector_modal.test.jsx.snap
Multiselect was crashing the app when an `ariaLabelRenderer` wasn't specified. This PR moves the default renderer up to the multiselect component so there's always a renderer.
https://mattermost.atlassian.net/browse/MM-17490
=> [MM-17490] Moved defaultAriaLabelRenderer up to multiselect.jsx

sass/routes/_settings.scss
When I changed the `setting_picture` component to have a readable remove button, I missed fixing the styling for the Team Icon use of that component. This PR does that fix.
https://mattermost.atlassian.net/browse/MM-17551
=> [MM-17551] Fixed so that team icon settings displays removal tooltip properly

actions/user_actions.jsx, actions/user_actions.test.js, components/popover_list_members/index.js, components/popover_list_members/popover_list_members.jsx, components/popover_list_members/popover_list_members.test.jsx
When opening the popover we were not pulling statuses and since we sorted by status it looked super confusing because we'd show everyone offline unless we had pulled their status in a different place previously.
https://mattermost.atlassian.net/browse/MM-17602
=> MM-17602 Load statuses when opening channel member list from header

plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap, plugins/channel_header_plug/channel_header_plug.jsx
MM-17487 - Updating plugin dropdown alignment
https://mattermost.atlassian.net/browse/MM-17487
=> MM-17487 - Updating plugin dropdown alignment

utils/a11y_controller.js
Cherry pick of #3322 on release-5.14.
- #3322: Removed interchangeability between CTRL and CMD
=> Automated cherry pick of #3322

components/post_view/post_list_ie/index.js, components/post_view/post_list_ie/post_list_ie.jsx
* Use loadPostsAround for loading posts in permalink view.
In the recent refactor of post actions we changed initial posts load action to be two loadLatestPosts and loadPostsAround and IE had it missing.
Also postVisibility which was being passed from parent does not exist anymore so this causes issues as posts are spliced in IE based on that.
https://mattermost.atlassian.net/browse/MM-17671
Note: Not adding any tests as this file does not have any and it will be removed from master really soon
=> MM-17671 Permalink does not render posts in IE11

actions/views/channel.js, actions/views/channel.test.js
1. If last time since API is called is today and socket disconnected was yesterday then we use the last post in the channel to get any missing posts(Should not even have any missing posts but it is a failsafe measure).
2. If socket disconnected today and the last time we called since API is yesterday we use socket disconnected timestamp to get any new messages missed during that time.
* Issue: if we never called since API i.e the second visit to a channel then lastGetPosts state in redux state will not exist, so we basically are calling since API after reconnect with the last post in channel which can be wrong as on reconnect we add new posts to the postsInChannel state
* Solution: Dispatch RECEIVED_POSTS_FOR_CHANNEL_AT_TIME for unreads if we are at the latest
so this way we will have a …
=> MM-17485 Fix for missing messages on socket reconn for channels visited only once preiously

components/admin_console/team_channel_settings/group/__snapshots__/group_users.test.jsx.snap, components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.jsx.snap, components/admin_console/team_channel_settings/group/group_users.jsx, components/admin_console/team_channel_settings/group/group_users_row.jsx, sass/components/_groups.scss
in the warning modal that appears when users will be removed from a team or channel on LDAP sync, very long email addresses overlap with the Role column.
Fixes https://mattermost.atlassian.net/browse/MM-17652
=> MM-17652 - Very long email addresses overlap with Role column on LDAP group sync warning modal

e2e/cypress/integration/enterprise/elasticsearch/channels_spec.js, e2e/cypress/integration/enterprise/elasticsearch/renaming_spec.js, e2e/cypress/integration/enterprise/elasticsearch/users_spec.js
Reorganized the elastic search tests to not be dynamic and reduce nesting. before/after hooks should be less problematic and you can more specifically target tests to debug.
https://mattermost.atlassian.net/browse/MM-17697
=> MM-17697: Reorganize elastic search tests to not use as much nesting

e2e/run_tests.js
Fix cypress report by escaping characters on title
none
=> Fix cypress report by escaping characters on title

components/searchable_user_list/searchable_user_list.jsx
This PR removes an unnecessary focus call on component update that was causing the focus to shift seemingly randomly to the textbox whenever an action updated the user state (needed by this component).
https://mattermost.atlassian.net/browse/MM-17657
=> [MM-17657] Removed unnecessary focus call on component update

components/suggestion/search_suggestion_list.jsx
This PR fixes a possible null on the current label for the suggestion list, causing a JS error. It stops the `toLowerCase()` call if the object is null.
https://mattermost.atlassian.net/browse/MM-17603
=> [MM-17603] Added null check to label generator on suggestion list

e2e/cypress/support/index.js
Depending on the test structure (e.g. before/after hooks, nesting, etc...), there can be times where the parent will not have a parent. This would then error, but "outside" of Cypress proper, so the error only is visible in the dev tools console.
N/A
=> Fix an issue where we may not have a parent when reporting cypress results

components/widgets/menu/menu.jsx, components/widgets/menu/menu.test.jsx, sass/widgets/menu/_menu_group.scss
Because the divider visibility was done by css some cases were hard to solve
(maybe imposible to solve) so I moved that logic into javascript to be able to
express correctly the expected behavior for the menu dividers visibility.
[MM-14490](https://mattermost.atlassian.net/browse/MM-14490)
=> Moving divider hidding logic from css to javascript

components/widgets/menu/menu_wrapper_animation.jsx, sass/widgets/menu/_menu.scss, sass/widgets/menu/_menu_wrapper.scss
The menu animation was flikering on safari some times, that was because certain
delay between the rendering plus the initial javascript animation, this is now
fixed moving the "display" change responsability to the animation itself. By
the way I change the breakpoint for mobile animations to the 768px limit, where
is the mobile view triggered.
[MM-17579](https://mattermost.atlassian.net/browse/MM-17579)
=> More robust menu animation for safari

actions/global_actions.jsx
Cherry pick of #3450 on release-5.14.
- #3450: MM-17805: Only adds history entry to select team if there's a
/cc  @mkraft
=> Automated cherry pick of #3450

package-lock.json, package.json
https://mattermost.atlassian.net/browse/MM-17780 was introduced somewhere between rc1 and rc2 which has only one change from react window which can cause a race condition as this. so reverted the react window change and fixed it in a way as to not cause any race conditions
https://github.com/mattermost/react-window/pull/23
=> MM-17780 Fix for scroll position wrong at times when opening channel

components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/rhs_root_post.jsx, components/rhs_root_post/rhs_root_post.test.jsx
Prevents the flag icon from displaying on the root post in a thread in the RHS if the post has been deleted. Borrows [similar logic](https://github.com/mattermost/mattermost-webapp/blob/master/components/post_view/post_info/post_info.jsx#L223) from the `<PostInfo/>` component in the center channel.
https://mattermost.atlassian.net/browse/MM-17539
N/A
=> [MM-17539] User is unable to send messages again if the user flags a deleted post on RHS

e2e/cypress/integration/interactive_dialog/full_dialog_spec.js, e2e/utils/webhook_utils.js
Add more interactive dialog tests
- verify input types including support to `password` element
- verify if autocomplete/suggestion list is open on click to input with datasource
Jira ticket: [MM-17085](https://mattermost.atlassian.net/browse/MM-17085)
=> [MM-17085] Add more interactive dialog tests

components/widgets/settings/autocomplete_selector.jsx, components/widgets/settings/autocomplete_selector.test.jsx, e2e/cypress/integration/interactive_menu/basic_options_spec.js
E2E for interactive menu for long option
Ref - [Tab/test case](https://docs.google.com/spreadsheets/d/1hbJ0rf_YxhCo1oDw1wUzTQaM1BJPAxE5XNZb6PvZwbc/edit#gid=1272020211&range=9:9) from Release testing spreadsheet
Requirement:
- Selected options with long usernames are not cut off in the RHS
Expected:
- Option is displayed in the text box
- Ephemeral message posts (only visible to you) showing the selection you have made
- RHS opens
- Username selected displays properly (truncated) and is not just cut off
Jira ticket - [MM-15887](https://mattermost.atlassian.net/browse/MM-15887)
=> MM-15887 E2E for interactive menu for long option

e2e/cypress/integration/messaging/emoji_to_markdown_spec.js
UI Automation: 
Automated test using Cypress for "Emojis preceded by 4 or more spaces are always treated as markdown"
Fixes https://github.com/mattermost/mattermost-server/issues/11743
https://mattermost.atlassian.net/browse/MM-17446
=> [MM-17446] Emojis to markdown.

package-lock.json, package.json
Because of: https://github.com/mattermost/mattermost-redux/commit/4b33a54f75b5d2db14f400ef47fde24e74f68e3d
Timeline: this https://github.com/mattermost/mattermost-webapp/pull/3449 was cherry-picked to 5.15, which needed this https://github.com/mattermost/mattermost-redux/pull/898 to be cherry-picked to redux's 5.15, which changed the hash, which the present PR is updating.
=> Updating redux hash

utils/a11y_controller.js
This PR updates the a11ycontroller.js to keep track of window focus so that it doesn't inadvertently make a11y visual updates when the windows comes back into focus again.
The problem was that once the window came back into focus, the element that last had focus received a focus event again and since that event wasn't triggered by a mouse click, the a11y_controller assumed it was a legit focus event and highlighted the element.
Test Steps:
1. Click on a post (not a button or link in a post)
2. Switch to a new tab and switch back
3. Move the mouse without clicking
Expected: There should be no visual updates to the post (i.e. the post should not receive an a11y focus outline.
https://mattermost.atlassian.net/browse/MM-17786
=> [MM-17786] Handle window focus events (a11y_controller.js)

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx
While fixing MM-16060, I switched `handleChannelUpdatedEvent` to be a redux action, but I forgot to actually dispatch it outside of the test code.
https://mattermost.atlassian.net/browse/MM-17890
https://mattermost.atlassian.net/browse/MM-17752
https://github.com/mattermost/mattermost-webapp/pull/3077
=> MM-17752/MM-17890 Properly dispatch handleChannelUpdatedEvent

package-lock.json, package.json, plugins/index.js
This dependency was removed as part of a recent Babel upgrade, but
plugins compiled without that same upgrade may fail to start. Restore
the dependency to ensure plugins don't break on upgrade to 5.16.
We may revisit this dependency on the next major version bump.
https://mattermost.atlassian.net/browse/MM-17475
=> MM-17475: restore regeneratorRuntime dependency

components/add_users_to_team/add_users_to_team.jsx
This PR fixes an issue where pagination breaks when adding users to a team.  At some point, the `currentTeamGroupConstrained` value was added to the `getProfilesNotInTeam()` function. There are two calls to `getProfilesNotInTeam()` within the `add_users_to_team.jsx` component file, but only one was adjusted to include this new input.  This PR adds the value to the other function call.
The issue resulted in the `USERS_PER_PAGE` value `(50)` getting passed into `getProfilesNotInTeam()` as the `page` number value when a user clicks the `next` button.  
https://mattermost.atlassian.net/browse/MM-17850
=> [MM-17850] Add missing currentTeamGroupdConstrained input to getProfilesNotInTeam function call

actions/global_actions.jsx, actions/global_actions.test.js
When trying to decide which is the adequate channel to redirect a guest, we cannot default to `town-square` as it is possible that the guest is not a member of it. Instead, we need to fetch the guest channels and members from the server and then decide to which channel we want to redirect them to.
https://mattermost.atlassian.net/browse/MM-17198
- [Has redux changes](https://github.com/mattermost/mattermost-redux/pull/900)
=> [MM-17198] Fetch channels and memberships if guest on redirect

components/post_view/post/post.jsx, e2e/cypress/integration/channel/message_spec.js, e2e/cypress/integration/interactive_menu/basic_options_spec.js, e2e/cypress/integration/messaging/focus_move_spec.js, e2e/cypress/integration/search/date_filter_spec.js, e2e/cypress/support/ui_commands.js
Daily report - https://community.mattermost.com/core/pl/yrt4wogua7d5mdcgzye13ajx7e
Fix failing tests on:
1. System Message MM-14636 - Validate that system message is wrapping properly
- might be flaky when initiating ``getLastPost``.  Make use of `data-testid` and get the last post by using ``getAllByTestId``
2. MM-15887 Interactive menus - basic options displays reply in center channel with commented on [users] message [text]
- failed when `user-1` try to post a message in a team where it's not member of.
3. Messaging M17452 Focus does not move when it has already been set elsewhere
- failed when channel name is not viewable in the sidebar, either scroll into view or force click into it.
While here, I did clean up the use of `cy.postMessageAs` where baseUrl is actually not necessary to …
=> Fix failing E2E tests

selectors/i18n.js, selectors/i18n.test.js
If an invalid locale is specified in the database, upon refreshing the app a logged in user will experience a blank screen. This PR forces the locale to the default in this case, such that `intl_provider` is never fed an invalid locale.
https://mattermost.atlassian.net/browse/MM-18118
=> [MM-18118] Check locale is valid before sending to intl_provider

components/invitation_modal/invitation_modal_confirm_step_row.jsx, components/invitation_modal/invitation_modal_confirm_step_row.scss
Fixes an alignment issue of the Guest Badge in case of very long usernames/fullnames.
https://mattermost.atlassian.net/browse/MM-17923
=> [MM-17923] Fix Guest Badge alignment when long username/fullname wraps

components/admin_console/system_users/list/__snapshots__/system_users_list.test.jsx.snap, components/admin_console/system_users/list/system_users_list.jsx, i18n/en.json
Adds the user id information in the system console -> user page
As a mattermost system administrator some tasks i need to know the userid, either to fill this info in some plugin config or to do any other task
And the only way to get that is using the dev tools (too hacky) or using the CLI which I need to have access to the server (too bad)
jira:  https://mattermost.atlassian.net/browse/MM-18153
=> add user id to be show in the user page in the system console

package-lock.json, package.json
- Updating redux hash due to: https://github.com/mattermost/mattermost-redux/pull/915
- Question: lots of little changes in the package-lock, are those okay to commit?
[MM-17975](https://mattermost.atlassian.net/browse/MM-17975)
- https://github.com/mattermost/mattermost-redux/pull/915
=> [MM-17975] Updating redux hash

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap, components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx, components/admin_console/custom_plugin_settings/custom_plugin_settings.test.jsx, components/admin_console/custom_plugin_settings/index.js, components/admin_console/schema_admin_settings.jsx, components/admin_console/schema_admin_settings.test.jsx, i18n/en.json
Largely eliminate the `CustomPluginSettings` class by instead carefully encoding the paths to the plugin settings. Prepend a boolean setting that points at the plugin being enabled, allowing the plugin to be enabled and disabled from its own configuration page (in addition to the top level plugin management page).
This also fixes a minor issue with the header and footers of plugins potentially clashing with an id (admittedly incredibly unlikely).
https://mattermost.atlassian.net/browse/MM-18093
=> Mm 18093 system console plugin enable

components/admin_console/plugin_management/plugin_management.jsx, components/integrations_marketplace/marketplace_item/marketplace_item.jsx, components/integrations_marketplace/marketplace_modal.jsx, package-lock.json, package.json
Pipe `SignatureUrl` param through when invoking `installPluginFromUrl` api.
Fixes https://mattermost.atlassian.net/browse/MM-18139
- Has server changes https://github.com/mattermost/mattermost-server/pull/12036/files
- Has redux changes https://github.com/mattermost/mattermost-redux/pull/917
=> MM-18139 - Add signature_url param when invoking install_from_url api

components/search_results/search_results.jsx, components/sidebar_right/sidebar_right.jsx
When the `search_results` component contained a large number of results, rendering would lag the transition on tablet view, which is not ideal from a UX standpoint. This PR stops the results from being rendered until the transition completes, improving visual performance.
https://mattermost.atlassian.net/browse/MM-17353
=> [MM-17353] Wait for transition on RHS before rendering expensive sub components

components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap, components/post_view/message_attachments/message_attachment/message_attachment.jsx, components/post_view/message_attachments/message_attachment/message_attachment.test.jsx, sass/layout/_webhooks.scss, utils/constants.jsx
Adds support for the `footer` and `footer_icon` properties in message attachments.
No footer:
Text-only footer:
Footer with icon:
Footer with more than 300 characters:
The `footer_icon` is only rendered if `footer` is also provided.  
The `footer` text is truncated if it exceeds 300 characters.
https://github.com/mattermost/mattermost-server/issues/11994
=> GH-11994: Add support for footer and footer_icon in attachments

e2e/cypress/integration/search/date_filter_spec.js
Removed the request assertions and checks in the search date filter spec. Added some other elements to wait for. With the additional element checks, the requests are not needed to reduce flakiness.
n/a
=> remove request checks and clean up SDF tests

e2e/cypress/integration/channel/edit_message_spec.js, e2e/cypress/integration/channel/header_spec.js, e2e/cypress/integration/channel/message_spec.js, e2e/cypress/integration/markdown/markdown_image_spec.js, e2e/cypress/integration/markdown/markdown_text_spec.js, e2e/cypress/integration/search/date_filter_spec.js, e2e/cypress/support/api_commands.js, e2e/cypress/support/ui_commands.js
Fix the following failing E2E on daily:
- M13564 Ellipsis indicates the channel header is too long
- Markdown images / text
Remove the following test since stubbing on fetch is currently not supported by Cypress
- M13542 Open edit modal immediately after making a post when post is pending
none
=> Fix failing E2E

actions/integration_actions.jsx, plugins/export.js, plugins/interactive_dialog.js
https://github.com/mattermost/mattermost-webapp/pull/3493 unintentionally removed the import of `actions/integration_actions`, which defined a side effect necessary to the correct functioning of interactive dialogs.
I've relocated this somewhere that is more intentionally imported, and commented details as to the issues with this code block. I'm not explicitly fixing the issues right now, and I'm not sure if I can unit test this, so I'm just restoring the import for now.
https://mattermost.atlassian.net/browse/MM-18340
=> MM-18340: restore dialog's store.subscribe

components/interactive_dialog/__snapshots__/dialog_introduction_text.test.jsx.snap, components/interactive_dialog/dialog_introduction_text.jsx, components/interactive_dialog/dialog_introduction_text.test.jsx, components/interactive_dialog/index.js, components/interactive_dialog/interactive_dialog.jsx
Adds support for rendering optional markdown formatted introduction text in interactive dialogs.
https://mattermost.atlassian.net/browse/MM-15219
- Has server changes (https://github.com/mattermost/mattermost-server/pull/12029)
- Has mobile changes (https://github.com/mattermost/mattermost-mobile/pull/3222)
=> MM-15219 Added support for optional introduction text in interactive dialogs

components/post_view/post/post.jsx, e2e/cypress/integration/account_settings/display/message_display_mode_spec.js, e2e/cypress/integration/interactive_menu/basic_options_spec.js, e2e/cypress/support/index.js, e2e/cypress/support/ui_commands.js, e2e/package-lock.json, e2e/package.json
-  fixed `f.apply` error by introducing `cypress-wait-until` to wait for permanent post before proceeding to next step.
- updated E2E dependencies
- fixed failing test on interactive menu
none
=> Fix failing E2E due to pending post

components/team_selector_modal/team_selector_modal.jsx, sass/components/_permissions.scss
Fixes missing 'Team Name' from 'Add Teams To Team Selection List' modal.
https://mattermost.atlassian.net/browse/MM-18598
N/A
=> [MM-18598] Group settings add team modal doesn't show team name

.gitignore
I've noticed that this repo does not ignore vim files and I was almost going to involuntarily commit some.
I've copied the related section from [mattermost-server](https://github.com/mattermost/mattermost-server/blob/46c624f4f8707d8d45344ad5fc9b9019dd992d2c/.gitignore#L62-L68) to ignore files related to the [vim](https://en.wikipedia.org/wiki/Vim_(text_editor)) editor.
=> Add vim temporary files to .gitignore

e2e/cypress/integration/at_mentions/at_mentions_spec.js
Quick test for failing E2E on at-mentions
None, reported on daily Cypress test - https://community.mattermost.com/core/pl/yiwatj6efpybjyso6cuxkihb4c
=> Fix failing test in at-mentions

components/multiselect/multiselect_list.jsx
Firefox was not correctly reading the `aria-live` region of the `multiselect` component, instead it was reading bits and pieces as the text field was updated. This PR adds the `aria-atomic` label, which ensures the entire option is read correctly.
NOTE: Microsoft Edge continues to have issues with JAWS and NVDA. See: https://github.com/FreedomScientific/VFO-standards-support/issues/266
Hopefully this will be fixed soon.
Tested on Firefox 69.0 and JAWS 2019.1907.42
https://mattermost.atlassian.net/browse/MM-18385
=> [MM-18385] Force screen reader to read whole aria-live section on multiselect option change

components/search_bar/search_bar.jsx
When `aria-label`s were added for the Recent Mentions and Flagged Posts buttons, we forgot to add them to the RHS implementations. This PR fixes that.
https://mattermost.atlassian.net/browse/MM-18164
=> [MM-18164] Turned on aria-labels for the RHS header buttons

components/search_bar/search_bar.jsx
Cherry pick of #3698 on release-5.16.
- #3698: Turned on aria-labels for the RHS header buttons
=> Automated cherry pick of #3698

actions/command.js
When using the `/leave` command on a DM, the user would be immediately put back into the channel they just removed from their sidebar. 
This was caused by an improper ordering of the preferences, where the `savePreferences()` dispatch would not have the information of the redirect to town-square before trying to update the sidebar, thus redirecting you back to the channel it thinks you're already in. 
This PR re-orders the actions such that the removal has happened after the navigation to town-square, and the redirect executes properly.
Also, we were using the wrong import of `isFavoriteChannel()` causing a JS error.
https://mattermost.atlassian.net/browse/MM-18649
=> [MM-18649] Fixed race condition for /leave action

e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Validating the Messages in Members Invitation Flow when a user adds a new or existing user
1. Click on Invite People and then Invite Members
2. Search and add an existing member by username, who is part of the team and click Invite Members and verify the error message 'This person is already a team member.' is displayed
3. Search and add an existing member by email, who is not part of the team and click Invite Members and verify the success message 'This member has been added to the team.' is displayed
4. Search and add a new member by email, who is not part of the team and click Invite Members and verify the success message 'An invitation email has been sent.' is displayed
https://mattermost.atlassian.net/browse/MM-18040
=> Added Cypress test for validating MM-18040 Members Invitation Flow: Add New/Existing Users

components/interactive_dialog/dialog_element/dialog_element.jsx, components/interactive_dialog/dialog_element/dialog_element.test.jsx, components/interactive_dialog/dialog_element/index.js, components/post_view/message_attachments/action_menu/action_menu.jsx, components/post_view/message_attachments/action_menu/action_menu.test.jsx, components/post_view/message_attachments/action_menu/index.js, components/suggestion/generic_channel_provider.jsx
Fix channels autocomplete both for interactive dialog and menu.  This was introduced by the [recent migration](https://github.com/mattermost/mattermost-webapp/pull/3453/files) which I missed to check during code review.
Can be tested using mattermost demo plugin (`/dialog`) or running Cypress tests with "/interactive_dialog" and "/interactive_menu" folders
Jira ticket - [MM-18746](https://mattermost.atlassian.net/browse/MM-18746)
=> [MM-18746] Fix channels autocomplete both for interactive dialog and menu

components/integrations/bots/add_bot/add_bot.jsx
During bot creation, remove the leading and trailing username white space before submission.  Without the automatic removal, the user would receive a notice of invalid username, although the trailing space is not "visible"
https://mattermost.atlassian.net/browse/MM-18332
=> [MM-18332] Ignore trailing and leading whitespace in Username Field during bot creation

components/post_profile_picture/post_profile_picture.jsx, components/widgets/users/avatar.scss, sass/layout/_post.scss
Avoid avatars to be shrinked by flexbox policies
[MM-18670](https://mattermost.atlassian.net/browse/MM-18670)
=> Avoid avatars to be shrinked by flexbox policies

components/post_profile_picture/post_profile_picture.jsx, components/widgets/users/avatar.scss, sass/layout/_post.scss
Cherry pick of #3750 on release-5.16.
- #3750: Avoid avatars to be shrinked by flexbox policies
/cc  @jespino
=> Automated cherry pick of #3750

e2e/cypress/integration/enterprise/system_console/channel_modes_spec.js, e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
For channel modes, I moved this into "/enterprise" folder since it requires license to test.  Also enable LDAP and LDAP group sync for those test cases.
For user status, it failed due to compact and standard display modes.  Those are now handled separately. 
none
=> Fix E2E on user status and toggling private/public channel

components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap, components/edit_channel_header_modal/edit_channel_header_modal.jsx
Fixed escape key handling in Edit Header modal
Fixes https://mattermost.atlassian.net/browse/MM-18570
=> MM-18570 - Hitting escape to close autocomplete also closes channel header modal

components/suggestion/suggestion_box.jsx, components/suggestion/suggestion_box.test.jsx
This PR solves the issue with trying to use the channel autocomplete `~` after submitting a post with just a channel mention.
The issue is that the `SuggestionBox` component's reference to `this.pretext` is stale after submitting the post. If we check that the current post text is empty, and the pretext is out of sync, we can update the pretext to empty string to reset the component. This added block does not run when the user clears the post text themselves, as that is handled in `this.handleChange()`.
https://mattermost.atlassian.net/browse/MM-18600
- In a new post, type `~` and press tab to select the first channel.
- Submit the post (at the time before submitting, `this.pretext` is set to `~`)
- Type `~`. The channel autocomplete does not come up, because the stale value of …
=> [MM-18600] Reset SuggestionBox pretext on post submit

components/channel_members_modal/__snapshots__/channel_members_modal.test.jsx.snap, components/channel_members_modal/channel_members_modal.jsx, components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap, components/more_direct_channels/more_direct_channels.jsx, components/team_members_modal/__snapshots__/team_members_modal.test.jsx.snap, components/team_members_modal/team_members_modal.jsx, components/user_list_row/user_list_row.jsx, e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
1. Invite a Guest User to a channel
2. Login as a Member and verify if the Guest User badge is displayed for that guest user. 
- Channel Members dropdown
- Channel Members dialog
- Team Members dialog
- User profile popovers
- Posts in Center channel, RHS channel
- Switch Channel
- DM Search
- DM/GM header
- Search
- @mentions
Fixes https://mattermost.atlassian.net/browse/MM-18045
=> Added Cypress Test for the testcase Guest Identification: Verify Guest User Badge in different screens

utils/a11y_controller.js
When clicking on image previews in posts, the post hover menu on the right of the post was getting stuck visible once closing the menus. This PR corrects that by preventing element focusing by the a11yController while modals are open.
https://mattermost.atlassian.net/browse/MM-18159
=> [MM 18159] Fix multiple hover post menus appearing after escaping from image preview.

components/profile_popover/index.js
- Hide "Add to channel" option for users removed from a team 
- setting isInCurrentTeam false if deleted from team
Fixes https://github.com/mattermost/mattermost-server/issues/11920
=> Hide "Add to channel" option for users removed from a team 

components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap, components/admin_console/plugin_management/plugin_management.jsx, i18n/en.json
Added necessary markdown in the marketplace documentation link in System Console so it opens in a new tab and were not opening at all for Desktop app. 
Fixes [MM-18824](https://mattermost.atlassian.net/browse/MM-18824)
=> MM-18824 - Fix Marketplace Documentation link in System Console

e2e/cypress/fixtures/timeouts.js, e2e/cypress/integration/enterprise/elasticsearch/helpers/index.js
This should make reindexing a bit more stable. Timeout is fairly long and should be more than sufficient when running on CI, locally it CAN take awhile if you have a large enough data set (or maybe not enough computing power?).
Note that there may be another issue afoot around when we enable/disable elastic search, but it has been intermittent and still need to dig into that more. 
n/a
=> Leverage cy.waitUntil to wait better for elastic search reindex

actions/post_actions.jsx, actions/post_actions.test.js, utils/emoticons.jsx, utils/emoticons.test.jsx
Ensure shorthand emojis are detected when creating a post so as to update the "recently used" cache.
This also reproduces on mobile, but there are other related bugs there, so filing a separate issue to investigate.
https://mattermost.atlassian.net/browse/MM-18885
=> MM-18885: recently used special emojis

actions/views/channel.js, actions/views/channel.test.js, actions/websocket_actions.jsx, actions/websocket_actions.test.jsx, components/permalink_view/actions.js, components/permalink_view/permalink_view.test.jsx, components/post_view/post/index.js, components/post_view/post/index.test.js, components/rhs_thread/rhs_thread.jsx, components/rhs_thread/rhs_thread.test.jsx, package-lock.json, package.json
This reverts commits 647eba0053b334ba3967e86bb291ea2c61c98103 and c0f9cb84b0675865931e3a191ecf9646b2633dbc.
https://mattermost.atlassian.net/browse/MM-18624
https://github.com/mattermost/mattermost-server/pull/12387
https://github.com/mattermost/mattermost-webapp/pull/3789
https://github.com/mattermost/mattermost-redux/pull/935
=> MM-18624: revert fetch threads support

components/invitation_modal/invitation_modal_confirm_step_row.scss
Fixing line breaks in invite email success page (chrome and safari)
[MM-17193](https://mattermost.atlassian.net/browse/MM-17193)
=> Fixing line breaks in invite email success page (chrome and safari)

sass/layout/_post.scss
This PR fixes the issue with the markdown preview feature, where new paragraphs are rendered with no newline between them. 
This was fixed before, during a fix for whitespace in ul elements [Ticket](https://mattermost.atlassian.net/browse/MM-14714) and [PR](https://github.com/mattermost/mattermost-webapp/pull/2612). This PR scopes that fix to only apply to ul elements.
https://mattermost.atlassian.net/browse/MM-18897
=> [MM-18897] Fix paragraphs in post markdown preview

sass/layout/_post.scss
Cherry pick of #3800 on release-5.16.
- #3800: only apply white-space normal to ul elements
=> Automated cherry pick of #3800

components/invitation_modal/invitation_modal_confirm_step_row.scss
Cherry pick of #3784 on release-5.16.
- #3784: Fixing line breaks in invite email success page (chrome and
/cc  @jespino
=> Automated cherry pick of #3784

components/permalink_redirector/permalink_redirector.test.jsx, components/root/root.jsx
Route `integrations*` to the permalink redirector, not just `integrations`, allowing the match to include the entire URL and thus send `/_redirect/integrations/bots` to `/<team>/integrations/bots` instead of just `/<team>/integrations`.
https://mattermost.atlassian.net/browse/MM-16683
=> MM-16683: redirect integrations*, not just integrations

components/removed_from_channel_modal/__snapshots__/removed_from_channel_modal.test.jsx.snap, components/removed_from_channel_modal/removed_from_channel_modal.jsx, components/team_sidebar/team_sidebar_controller.jsx, e2e/cypress/integration/enterprise/guest_accounts/guest_removal_ui_spec.js, e2e/cypress/support/api_commands.js
1. Verify if a Guest user is automatically redirected to another team when removed from all the channels of a team. 
2. Verify if a Guest user is automatically redirected to select team page with a message 'Your guest account has no channels assigned. Please contact an administrator.' when removed from all the teams and channels.
3. Verify if System message is displayed when Guest User leaves the channel. 
Fixes https://mattermost.atlassian.net/browse/MM-18044
=> Added Cypress Test to verify behavior when Guest User is removed from channel

components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap, components/file_attachment/file_attachment.jsx, components/file_attachment/file_attachment.test.jsx, components/file_attachment/filename_overlay.jsx
This PR fixes the issue where the tooltip for a file attachment link would appear after closing the image popup. The link is now forced to blur after click so the tooltip is not applied.
https://mattermost.atlassian.net/browse/MM-18875
=> [MM-18875] Blur file attachment link on click

components/admin_console/custom_plugin_settings/index.js
- There was a small bug in a change made in the marketplace PR. The quality-of-life improvement of having the "enable plugin" setting on the plugin's setting page was unshifting a potentially empty array.
- Fixes [MM-19042](https://mattermost.atlassian.net/browse/MM-19042)
=> [MM-19042] Plugins settings page won't load in 5.16

utils/latinise.test.tsx, utils/latinise.tsx, utils/url.jsx
Migrate 'utils/latinise.jsx' and associated tests to TypeScript.
Fixes https://github.com/mattermost/mattermost-server/issues/12490
=> MM-18913: Migrate latinise.tsx and tests to Typescript

components/permalink_redirector/permalink_redirector.test.jsx, components/root/root.jsx
Cherry pick of #3799 on release-5.16.
- #3799: MM-16683: redirect integrations*, not just integrations
=> Automated cherry pick of #3799

components/emoji_picker/emoji_picker.jsx, components/emoji_picker/emoji_picker.test.jsx
By default the first emoji should not be selected
Fixes https://mattermost.atlassian.net/browse/MM-18849
=> MM-18849 Remove default selection of the first emoji

components/emoji_picker/emoji_picker.jsx, components/emoji_picker/emoji_picker.test.jsx
Cherry pick of #3822 on release-5.16.
- #3822: remove default selection of the first emoji
/cc  @reflog
=> Automated cherry pick of #3822

e2e/cypress/integration/search/date_filter_spec.js
This should address some of the flakiness around when we search in the search date filter tests. Additionally sometimes the "remove query string" tests flaked out a bit, so refactored them.
N/A
=> Cypress E2E - Add additional waits when searching search date filter

components/announcement_bar/version_bar/version_bar.jsx, components/system_notice/notices.jsx, utils/server_version.test.tsx, utils/server_version.tsx
Migrate 'utils/server_version.jsx' and associated tests to Typescript
https://mattermost.atlassian.net/browse/MM-18918
Fixes mattermost/mattermost-server/issues/12485
=> [MM-18918] Migrate 'utils/server_version.jsx' and associated tests to TypeScript

e2e/cypress/integration/enterprise/elasticsearch/system_console_spec.js
Should fix failing/flaky test when reindexing elastic searched. Leveraged the same mechanism we use in the other elastic search tests.
N/A
=> E2E Cypress: leverage wait until in the system_console_spec for elastic search

.eslintrc.json
With the TypeScript conversion, we are allowing the non-null assertion operator to get around strict null checks when it's not necessary. I propose we leave strict null checks on such that it's always caught and thought about before a developer commits.
=> Remove ESLint rule for typescript non null assertion operator

package-lock.json, package.json
Update to our eslint config to support TypeScript tests (see https://github.com/mattermost/eslint-config-mattermost/pull/1)
=> Update eslint-config for typescript

components/file_upload/file_upload.jsx, utils/dragster.test.ts, utils/dragster.ts
Migrate the dragster utility to Typescript, update it's imports,
and migrate its tests to Typescript.
Completes https://mattermost.atlassian.net/browse/MM-18909
I'm not a fan of the null checks in the tests but was unsure what a better method to satisfy the compiler would be so I'm open to suggestions.
=> migrate 'utils/dragster' to typescript

components/channel_header/index.js
Cherry pick of #3886 on release-5.16.
- #3886: include deactivated users in gm channel name
=> Automated cherry pick of #3886

utils/constants.jsx
Fixes a bug where `invite_guest` permission was filtered out of the team scheme cause it was missing from `PermissionsScope`.
https://mattermost.atlassian.net/browse/MM-19247
=> [MM-19247] Fix Invite Guests Permission in custom Team Scheme

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, components/admin_console/custom_plugin_settings/custom_plugin_settings.test.jsx, components/admin_console/schema_admin_settings.jsx, components/admin_console/schema_admin_settings.test.jsx
Fixing problem saving config because saveConfig function has disappeared
[MM-19306](https://mattermost.atlassian.net/browse/MM-19306)
=> Fixing problem saving config because saveConfig function has disappeared

e2e/cypress/integration/messaging/mobile_profile_popover_spec.js
This test was acting up in a CI build.
Force clicking the profile icon image should address any issues if it is somehow not visible. Additionally, typing escape after the first test to dismiss the popover so it is not already there for the next test.
N/A
=> force click for profile popover e2e test

utils/a11y_controller.js
The fix for [this ticket](https://mattermost.atlassian.net/browse/MM-18159) broke keyboard navigation in modals, specifically preventing focused elements in modals from visually indicating they have focus. This PR reverts the fix for the original ticket to fix the broken modal navigation and applies a new fix for the original ticket.
https://mattermost.atlassian.net/browse/MM-19339 (new ticket)
https://mattermost.atlassian.net/browse/MM-18159 (original ticket)
=> [MM-19339] Fix tabbing in modals and multi post-hover-menus

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx
When a guest was removed from a channel and the user wasn't visible, it needs
to ask for the user information to confirm that the other user is no longer
visible.
[MM-19169](https://mattermost.atlassian.net/browse/MM-19169)
=> Fixing guest being removed from other not-visible user from a channel

package.json
The package `@types/chart.js` was added as a dependency in `package.json`, when it already exists in the `devDependencies`. My console shows a warning for this when running tests.
https://mattermost.atlassian.net/browse/MM-18925
https://github.com/mattermost/mattermost-webapp/pull/3855 introduced the duplication
If I understand correctly, the only reason we would want to have types in the `dependencies` section is if another repo imports `mattermost-webapp` and wants to know about those types. With that in mind, should all `@types` dependencies go into `devDependencies`?
=> Remove redundant package from dependencies

components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap, components/admin_console/plugin_management/plugin_management.jsx, i18n/en.json
Disable `save` button when URL is empty. Show a warning message when URL is empty.
Fixes https://mattermost.atlassian.net/browse/MM-18823
=> MM-18823 - Saving empty string on Marketplace URL resets the URL instead of showing error

components/message_submit_error.test.tsx, components/message_submit_error.tsx
**Summary**
MM-18985-Migrate 'components/message_submit_error.jsx' and associated tests to TypeScript
**Ticket Link**
[https://mattermost.atlassian.net/browse/MM-18985](https://mattermost.atlassian.net/browse/MM-18985)
Fixes https://github.com/mattermost/mattermost-server/issues/12444
=> Migrate 'components/message_submit_error.jsx' and associated tests to TypeScript

components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap, components/channel_members_dropdown/channel_members_dropdown.jsx
Cherry pick of #3968 on release-5.16.
- #3968: MM-19323: Show 'Remove From Channel' option if user has
/cc  @mkraft
=> Automated cherry pick of #3968

components/common/comment_icon.jsx, components/post_view/post_reaction/__snapshots__/post_reaction.test.jsx.snap, components/post_view/post_reaction/post_reaction.jsx, e2e/cypress/integration/messaging/tooltip_visual_verification_spec.js
I created a test that does the following : 
1. Create a new user and start a DM
2. Get post id and hover over post
3. Hover on the three post menu items/icons (dotmenu, post reaction, comment)
4. Check whether the relevant tooltip message appears when hovering over each item
5. If it does, test succeeds.
I had to make changes in the ```post_reaction.jsx``` and ```comment_icon.jsx``` files in order for Cypress to be able to hover on the respective icons. They were previously nested in a manner that did not allow Cypress to hover over the icons. Please refer to the links I have posted in the 'Related Pull Requests' section below.
Fixes https://github.com/mattermost/mattermost-server/issues/12299
Jira: https://mattermost.atlassian.net/browse/MM-18697
=> MM18697 - Add tests to check if tooltips show up when post menu icons are hovered

components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/search_results_item.jsx, components/search_results_item/search_results_item.test.jsx
When focusing a post in the RHS under Search/Recent Mentions/Flagged Posts, the post options were not focusable when tabbing through. This PR adds the `a11y__section` class to allow them to be focused with the `a11y-controller`.
https://mattermost.atlassian.net/browse/MM-19497
=> [MM-19497] Fixed focusing on search results/mentions RHS

components/file_upload/__snapshots__/file_upload.test.jsx.snap, components/file_upload/file_upload.jsx, components/file_upload/file_upload.test.jsx
The actual implementation will only trigger on click event, in case of devices with touch the click event will trigger when double tapping. Here we are listening for a touch end event to trigger the same behavior as a simple mouse click.
https://mattermost.atlassian.net/browse/MM-19506
=> MM-19506 Fix attaching files on devices with touch events

components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.jsx.snap, components/plugin_marketplace/marketplace_item/marketplace_item.jsx, components/plugin_marketplace/marketplace_item/marketplace_item.test.jsx
Cherry pick of #3983 on release-5.17.
- #3983: MM-19183: handle plugins without homepage
=> Automated cherry pick of #3983

components/dot_menu/dot_menu.jsx, components/integrations/bots/add_bot/add_bot.jsx
Summary
Fixes import of default constant.
Warning messages in console:
WARNING in ./components/integrations/bots/add_bot/add_bot.jsx 321:17-35
"export 'OVERLAY_TIME_DELAY' was not found in 'utils/constants.jsx'
WARNING in ./components/dot_menu/dot_menu.jsx 126:47-73
"export 'UNSET_POST_EDIT_TIME_LIMIT' was not found in 'utils/constants.jsx'
=> Fix import of default constants

actions/views/rhs.js, actions/views/rhs.test.js
- An earlier commit dispatched an action to remove the search terms when the pinned post button is clicked. Removed that.
- Fixes [MM-19194](https://mattermost.atlassian.net/browse/MM-19194)
=> [MM-19194] Clicking "Pinned" Icon removes text in the search box

.storybook/webpack.config.js
This fixes error of module not found when running and building storybook by updating webpack config to resolve alias for client, dispatcher and plugins.
(I rearranged the order of those `config.resolve.alias` to easily check duplicates/missing.)
QA test:
Run either `make storybook` or `make build-storybook` and verify that no error found in the command line.
none
=> Fix module not found error when running and building storybook

actions/views/rhs.js, components/channel_header/channel_header.js, components/channel_header/channel_header.test.jsx, components/channel_header/index.js, components/channel_header_mobile/show_search_button/index.js, components/channel_header_mobile/show_search_button/show_search_button.js, components/search_results/index.jsx
When the screen is small enough the search bar in the channel header turns into a button that when clicked opens the RHS and the user can type the search terms there. 
In this case, it was not cleaning out any previous results or search terms causing issues as the attached one. 
To fix these, I've included a new RHS action `openRHSSearch` that will clear out any current results and search terms before opening the RHS for the search button in the channel header in both smaller screen and mobile view cases.
This was not a problem when the search has the input bar to type given that the RHS would only open when the search has been performed and will replace any old results from previous search actions.
Fixes [MM-19195](https://mattermost.atlassian.net/browse/MM-19195)
=> MM-19195 - Clear search results before opening RHS for mobile view

utils/emoticons.jsx, utils/text_formatting.jsx, utils/text_formatting.test.jsx
Unicode emojis have been rendered slightly differently from text-based emojis and emoticons for some time now, and the way that they were being rendered caused them to get picked up as inline markdown images. This caused some CSS issues for them in the past and still causes them to be clickable like markdown images.
This changes so that they're rendered by spans in this step of the process (the same as other emojis) which are later transformed into the correct `PostEmoji` component later on
https://mattermost.atlassian.net/browse/MM-19495
=> MM-19495 Render unicode emojis the same as text emojis and emoticons

actions/post_utils.js, actions/post_utils.test.js, package-lock.json, package.json
Skip the step of `setChannelReadAndView` that marks a channel as read when the user is viewing a channel if they manually marked it as unread.
Mobile/Redux PR: https://github.com/mattermost/mattermost-redux/pull/950
https://mattermost.atlassian.net/browse/MM-19493
=> MM-19493 For manually unread channel, don't mark as read on new message

components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.jsx.snap, components/admin_console/system_user_detail/system_user_detail.jsx, components/admin_console/system_user_detail/team_list/__snapshots__/abstract_list.test.jsx.snap, components/admin_console/system_user_detail/team_list/abstract_list.test.jsx, components/admin_console/system_user_detail/team_list/team_list.jsx, components/admin_console/system_user_detail/team_list/team_list.test.jsx, components/admin_console/system_user_detail/team_list/team_row.jsx
Fixes a problem with roles in `TeamRow` not showing the correct label for Guests and System Admins.
This is a PR **only** aimed at **5.17** since same components have been heavily updated by #3766.
https://mattermost.atlassian.net/browse/MM-19470
=> [MM-19470] Fix role name for guests and admins in system console team list

components/interactive_dialog/dialog_element/dialog_element.jsx, components/interactive_dialog/dialog_element/dialog_element.test.jsx
Remove default value for radio elements in interactive dialogs so no option is selected initially. 
[MM-18629](https://mattermost.atlassian.net/browse/MM-18629)
=> MM-18629 - Remove default value for radio elements in interactive dialogs

sass/layout/_team-sidebar.scss
- Set the correct height for the team sidebar when the announcement banner is visible.
- This was pushing the github plugin's icons off the visible window.
[MM-19687](https://mattermost.atlassian.net/browse/MM-19687)
=> [MM-19687] Refresh icon is not displayed for the Github Integration on the LHS when alert banner is visible

sass/layout/_team-sidebar.scss
Cherry pick of #4073 on release-5.17.
- #4073: correct the height of the team sidebar when there's an
/cc  @cpoile
=> Automated cherry pick of #4073

components/invitation_modal/index.js, components/invitation_modal/invitation_modal.jsx, components/invitation_modal/invitation_modal.test.jsx, components/team_general_tab/index.js, components/team_general_tab/team_general_tab.jsx, components/team_general_tab/team_general_tab.test.jsx
PR adds a `getTeam` request in team settings/invitation modal if `team.invite_id` is empty since we'll soon be removing `invite_id` from the related websocket broadcasted event for security reasons.  
This PR is backward compatible and can be merged.
https://mattermost.atlassian.net/browse/MM-15270
https://github.com/mattermost/mattermost-server/pull/12952
=> [MM-15270] Request team from API if invite_id is empty

actions/views/channel.js, actions/views/channel.test.js, components/needs_team/index.js, components/needs_team/needs_team.jsx, components/needs_team/needs_team.test.jsx
Currently, if you select another window and then switch back to Mattermost, it marks the channel as read, even if you previously marked it as unread. This fixes that
https://mattermost.atlassian.net/browse/MM-19491
=> MM-19491 Only mark channel as read on focus when channel isn't manually unread

actions/global_actions.jsx
This PR adds a check to prevent the `redirectUserToDefaultTeam` from redirecting the user to a channel that they have been just removed from.
https://mattermost.atlassian.net/browse/MM-19441
=> [MM-19441] Fix the case of redirecting to an unavailable channel

components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap, components/admin_console/plugin_management/plugin_management.jsx, components/admin_console/plugin_management/plugin_management.test.jsx, i18n/en.json
Add `RequirePluginSignature` setting to plugin configuration page.
Fixes https://mattermost.atlassian.net/browse/MM-19844
=> MM-19844 - Disallow plugin upload when PluginSettings.RequirePluginSignature is true

e2e/cypress/integration/channel/add_users_to_channel_spec.js, e2e/cypress/integration/channel/channel_name_tooltips_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_removal_ui_spec.js, e2e/cypress/integration/messaging/focus_move_spec.js
Fixes few Flaky E2E Tests. 
- For some reasons, Cypress was not able to detect the id channelHeaderDropdownMenu even though it was present. I changed it to verify if one of the child elements of the Channel Header Dropdown Menu is present. 
- Instead of `Someone removed you`, it is expected now to display which user removed. So updated it to `sysadmin removed you`. 
- Added a small timeout to wait before the channel is created and is displayed. 
NA
=> Fixed few flaky tests

components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/rhs_root_post.jsx, components/rhs_thread/rhs_thread.jsx, components/search_results/search_results.jsx, components/search_results_item/search_results_item.jsx, utils/a11y_controller.js
Implementation of sorting for posts wasn't working in older Chrome browsers (noticed in older Desktop App v4.2.x). This PR explicitly adds a11y sort order to posts in the RHS as well as improves the sorting function that looks at an optional attribute on matching elements for a defined sort order.
https://mattermost.atlassian.net/browse/MM-19901
=> [MM 19901] Fix keyboard navigation sorting of RHS posts

components/admin_console/license_settings/license_settings.jsx, utils/utils.jsx
Remove utils.displayTime in favour of FormattedTime component
Fixes https://github.com/mattermost/mattermost-server/issues/12242
=> Remove utils.displayTime in favour of FormattedTime component

.circleci/config.yml
Before this PR the master branch was generating it in a weird way so wasn't
able to be visible, with this at least is visibile in the path with "/master",
probably we would need a redirect somehow at root directory.
=> Fix storybook for master branch

components/profile_picture.tsx, components/user_profile/user_profile.jsx
Fixed issues where the `OverlayTrigger` `ref` were not being set properly for `ProfilePopover` and was causing the popover to not close when the user would click the "Send Message" button (and the associated bug when in web mobile mode).  
Fixes [MM-19908](https://mattermost.atlassian.net/browse/MM-19908)
=> MM-19908 - Fixed ProfilePopover not closing on SendMessage

components/__snapshots__/searchable_channel_list.test.jsx.snap, components/admin_console/__snapshots__/custom_url_schemes_setting.test.jsx.snap, components/admin_console/compliance_reports/compliance_reports.jsx, components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap, components/admin_console/system_users/system_users.jsx, components/claim/components/email_to_ldap.jsx, components/claim/components/email_to_oauth.jsx, components/claim/components/ldap_to_email.jsx, components/claim/components/oauth_to_email.jsx, components/integrations/__snapshots__/abstract_command.test.jsx.snap, components/localized_input/__snapshots__/localized_input.test.tsx.snap, components/localized_input/localized_input.test.tsx, components/localized_input/localized_input.tsx, components/login/__snapshots__/login_mfa.test.jsx.snap, components/login/login_controller/login_controller.jsx, components/mfa/setup/setup.jsx, components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap, components/new_channel_modal/new_channel_modal.jsx, components/new_channel_modal/new_channel_modal.test.jsx, components/password_reset_form/__snapshots__/password_reset_form.test.js.snap, components/password_reset_send_link/__snapshots__/password_reset_send_link.test.js.snap, components/plugin_marketplace/__snapshots__/marketplace_modal.test.jsx.snap, components/rename_channel_modal/__snapshots__/rename_channel_modal.test.jsx.snap
The login screen is currently broken because `LocalizedInput` was updated to use `React.forwardRef`, but that doesn't work with string refs that are used throughout the app. This updates them all to ref objects.
https://mattermost.atlassian.net/browse/MM-19995
=> MM-19995 Fix usage of React.forwardRef for LocalizedInput

sass/components/_groups.scss
Cherry pick of #3945 on release-5.17.
- #3945: MM-17477: Fix for group display name column expanding too
/cc  @mkraft
=> Automated cherry pick of #3945

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, sass/layout/_markdown.scss
* There was a change with inherited classes https://github.com/mattermost/mattermost-webapp/pull/3639 on . markdown-inline-img causing this issue
The change of .markdown-inline-img was added to div intentionally to apply for div wrapper to match the styles of img which is going to be replaced when it loads. Reverted the change  
* Changing the width of svg to inherit to occupy the space as needed. This wasnt needed earlier but some of the recent changes made this a requirement.
https://mattermost.atlassian.net/browse/MM-19909
=> MM-19909 Fix for scroll pop with markdown images

actions/views/rhs.js, components/search_results/index.jsx
Cherry pick of #4159 on release-5.17.
- #4159: Revert the search results component to not bind directly to
=> Automated cherry pick of #4159

actions/post_actions.jsx, selectors/posts.js
Found this bug by @larkox while submitting E2E for link preview which includes tests for:
...
4. Have the user who posted it click the collapse arrows to collapse the preview
5. Verify preview did not collapse for other user
...
This can probably affect those users who shares logging in to a common workstation.
Before, the storage key is `...:isVisible_[postId]`:
After, `...:isVisible_[userId]_[postId]`:
Note: I didn't bother to add backwards compatibility since this don't have noticeable change (where user mostly cared on embed visibility of recent post/s).
Jira ticket: [MM-18708](https://mattermost.atlassian.net/browse/MM-18708)
=> MM-18708 Fix state of embed visibility for users logging in on same browser/client

e2e/cypress/integration/search/results_post_spec.js
Test steps:
1. Post "apple banana"
2. Search for "apple"
3. In the search box, replace "apple" with "banana" but don't hit "search"
Expected:
1. The search term that you searched for stays highlighted regardless of what you type in the search box
Jira ticket: MM-19944
=> MM-19944 Add E2E on search highlighting

utils/text_formatting.jsx, utils/text_formatting_email.test.jsx, utils/text_formatting_links.test.jsx
Cherry pick of #4162 on release-5.17.
- #4162: include target="_blank" and rel="noreferrer" to email
/cc  @cpoile
=> Automated cherry pick of #4162

components/dot_menu/__snapshots__/dot_menu.test.jsx.snap, components/dot_menu/dot_menu.jsx, components/dot_menu/dot_menu.test.jsx
The default divider is visible on mobile, but the one used above the plugin sections of the post menu has CSS that hides it on mobile. This switches the Edit/Delete section to use the same divider as the plugin section of the post menu.
https://mattermost.atlassian.net/browse/MM-19955
=> MM-19955 Remove divider from post menu on mobile

.circleci/config.yml
the previous env var does not exist anymore and that was failing when
need to build server/webapp from upstream with same branch names
=> getting the branch name if is from upstream or fixing if come from PR

actions/channel_actions.test.js
Added jest unit test
[https://mattermost.atlassian.net/browse/MM-17943](https://mattermost.atlassian.net/browse/MM-17943)
=> MM-17943 :  Add tests for openGroupChannelToUserIds action 

tsconfig.json
Cypress was included in TS checking and confused the typings of Chai and Jest
=> Fixed make check-types by excluding cypress folder

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, sass/layout/_markdown.scss
The issue of svg happens becuase of a change in https://github.com/mattermost/mattermost-webapp/pull/4164 which was added because of 
> Changing the width of svg to inherit to occupy the space as needed. This wasnt needed earlier but some of the recent changes made this a requirement.
The recent changes as it turns out was https://github.com/mattermost/mattermost-webapp/pull/4047 which was caused because of the https://github.com/mattermost/mattermost-webapp/pull/3639
So in total 
We don't need the width prop on svg added in https://github.com/mattermost/mattermost-webapp/pull/4164 if we revert the width change from https://github.com/mattermost/mattermost-webapp/pull/4047. 
https://github.com/mattermost/mattermost-webapp/pull/4047 was made for fixing an issue with aspect ratio images …
=> MM-20151 Fix for svg console error about width property

components/channel_header/channel_header.js
Fixed the channel display name order in the channel header that was only ordered by username and not honoring the user preferences for user display name. This was regression from https://github.com/mattermost/mattermost-webapp/pull/3832
The fix navigates the display names as ordered by `channel.display_name` and then maps to the necessary components to include guest label if needed. This replaces the previous implementation that navigated the users list in `gmMembers` that is not sorted properly. 
Fixes [MM-20006](https://mattermost.atlassian.net/browse/MM-20006)
=> MM-20006 - Fixed Display Name order in Channel Header

actions/global_actions.test.js
Fixed linting issues in `actions\global_actions_test.js` that are holding up cherry picks to 5.17 branch due to this [ci-lint check error](https://circleci.com/gh/mattermost/mattermost-webapp/41828?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
Failing cherry pick: https://github.com/mattermost/mattermost-webapp/pull/4226
=> Linting global actions

utils/markdown/index.test.js
The lines of the test that I removed were about testing line numbers in code blocks which don't exist in 5.17
=> Fix release-5.17 tests

components/admin_console/__snapshots__/radio_setting.test.tsx.snap, components/admin_console/radio_setting.test.tsx, components/admin_console/radio_setting.tsx, components/admin_console/schema_admin_settings.jsx
Migrate 'components/admin_console/radio_setting.jsx' and associated tests to TypeScript 
https://mattermost.atlassian.net/browse/MM-20078
=> MM-20078: Migrate 'components/admin_console/radio_setting.jsx' and associated tests to TypeScript

components/post_view/post/post.jsx
@Willyfrog I changed the behaviour of the pointer cursor in the centre channel to not disappear when you mouse off the post (see the second commit) since it felt really weird in testing.
Basically, this makes it so that holding alt always makes posts show the pointer cursor instead of only having it happen sometimes.
=> Fix weird cursor behaviour when mousing off of post

package.json
Seems marked had been downgraded by accident. This puts it back to the latest version.
No Ticket
=> [No Ticket] Update Marked back to latest version

components/admin_console/manage_teams_modal/__snapshots__/manage_teams_dropdown.test.jsx.snap, components/admin_console/manage_teams_modal/manage_teams_dropdown.jsx
- Check that the user isn't a Guest before offering to make them a team admin.
- Fixes: [MM-20160](https://mattermost.atlassian.net/browse/MM-20160)
=> [MM-20160] Option to make team admin should not be provided to a guest user

e2e/cypress/integration/messaging/permalink_loading_indicator_spec.js, e2e/cypress/utils/index.js
* add E2E on permalink loading indicator
* create private channel, post multiple messages, and copy permalink from first post
* create public channel, post permalink, click on permalink
* verify url include permalink, channel intro is correct, messages are displayed, loading indicator is not visible, and more messages text is not visible
Ticket Link:
Github - https://github.com/mattermost/mattermost-server/issues/12294
Jira - https://mattermost.atlassian.net/browse/MM-18701
=> MM-18701 Add E2E on permalink loading indicator

e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js
* add E2E on reply input box expansion
* post several replies so that reply box goes to the bottom
* verify default heights
* type new lines so that reply input box reach max height, then verify last reply is not covered and the corresponding heights are correct
* add more new lines to reply to make sure box only expands up to 50% of viewport
* scroll up to first reply then start typing again on the reply box and verify replies are pushed up
Ticket Link:
Github - https://github.com/mattermost/mattermost-server/issues/12295
Jira - https://mattermost.atlassian.net/browse/MM-18706
=> MM-18706 Add E2E on reply input box expansion

components/emoji_picker/emoji_picker_overlay.jsx
Cherry pick of #4163 on release-5.18.
- #4163: Initialize EmojiPickerOverlay using props from the
/cc  @AGMETEOR
=> Automated cherry pick of #4163

components/invitation_modal/invitation_modal.jsx
Fix invitation modal back buton (bad merge resolution)
[MM-20283](https://mattermost.atlassian.net/browse/MM-20283)
=> Fix invitation modal back buton (bad merge resolution)

components/create_comment/__snapshots__/create_comment.test.jsx.snap, components/create_comment/create_comment.jsx, e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js
* add E2E on center channel RHS overlap
* post message on center channel and verify post text box is focused
* reply to message and verify post text box is not focused
* post several replies, scroll into view ”Add Comment" button and verify it is visible
Note: Although visually post text box is not visible to user, cypress still considers it visible so the assertion should('not.be.visible') will fail. Instead, should('not.be.focused') is used
Ticket Link:
Github - https://github.com/mattermost/mattermost-server/issues/12290
Jira - https://mattermost.atlassian.net/browse/MM-18705
=> MM-18705 Add E2E on center channel RHS overlap

e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
Summary
Fixed Interactive Dialog test
-  Changed the assertion to verify that by default no radio button is selected (This is based on the recent changes done in the ticket https://mattermost.atlassian.net/browse/MM-18629)  
- Added step to reload after each testcase to avoid having any dialogs left open (due to any failures)
- Added step to clear input before number validation
=> Fixed Interactive Dialog E2E test

components/analytics/format.test.tsx, components/analytics/format.tsx, components/analytics/system_analytics/system_analytics.jsx
Cherry pick of #4266 on release-5.18.
- #4266: synchronize date ranges on graphs
/cc  @reflog
=> Automated cherry pick of #4266

components/analytics/__snapshots__/statistic_count.test.tsx.snap, components/analytics/statistic_count.test.tsx, components/analytics/statistic_count.tsx
Statistics widget checked for 'loading/undefined' state by using `!count` instead of actually checking if it's undefined
Fixes https://mattermost.atlassian.net/browse/MM-20027
=> MM-20027 - Reporting > Statistics showing 'Loading...' when value is zero

components/analytics/__snapshots__/statistic_count.test.tsx.snap, components/analytics/statistic_count.test.tsx, components/analytics/statistic_count.tsx
Cherry pick of #4301 on release-5.18.
- #4301: check for undefined values instead
/cc  @reflog
=> Automated cherry pick of #4301

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx
PR fixes a problem with current channel header not getting updated (until channel reload) when a guest user is deactivated/activated/demoted/promoted.
https://mattermost.atlassian.net/browse/MM-20209
https://github.com/mattermost/mattermost-server/pull/13180
=> [MM-20209] Update current channel header when a guest user is deactivated/promoted

actions/websocket_actions.jsx, components/removed_from_channel_modal/index.js
Fixing leave channel when another window is open
[MM-20206](https://mattermost.atlassian.net/browse/MM-20206)
=> Fixing leave channel when another window is open

components/dot_menu/dot_menu.jsx
The dot menu was not always opening up at the top of the post when needed and causing the related bug. This was a regression from PR https://github.com/mattermost/mattermost-webapp/pull/3357
The `openUp` flag was always being set with the condition that checks the menu boundaries and there was a border case where the boundaries changed causing the menu to open incorrectly in the bottom. Reverting to only enable the `openUp` flag if the condition is met and not overriding if it is false.
Fixes [MM-19493](https://mattermost.atlassian.net/browse/MM-19439)
=> MM-19439 - Fixed dot menu to open up 

utils/markdown/renderer.jsx, utils/syntax_highlighting.tsx
Fix code preview on attachments. This was broken because this PR (mattermost/mattermost-webapp#3578) only took in consideration the code blocks not the file code previews.
[MM-20250](https://mattermost.atlassian.net/browse/MM-20250)
=> Fix code preview on attachments

components/admin_console/plugin_management/plugin_management.jsx
Using `props` over `state` for UploadButton to make sure settings are set on the server and not just locally.
Fixes https://mattermost.atlassian.net/browse/MM-20324
=> MM-20324 - Plugin upload should not be enabled before saving the Require Plugin Signature setting

components/admin_console/license_settings/license_settings.jsx
Replacing link to homepage with link to trial page, adding UTM tags, modifying some text
We want to generate Product Qualified Leads, or PQLs, that represent people who are using the product and have demonstrated interest in enterprise features. We want to include a link to the trial page from within the Edition and License page to make it easy to try out enterprise features. With UTM tags, we can better ascertain interest in the more advanced features.
https://mattermost.atlassian.net/browse/MM-20655
N/A
=> MM-20655: Replacing link to homepage with link to trial page, adding UTM tags, modifying some text

components/admin_console/license_settings/license_settings.jsx
Cherry pick of #4312 on release-5.18.
- #4312: replacing link to homepage with link to trial page,
/cc  @etoaster
=> Automated cherry pick of #4312

.eslintrc.json
We've had this set to warn people about using `.jsx` for ages since we wanted to switch everything to `.js`, but we haven't actually done anything about it, so it just causes a ton of warnings that we're not doing anything about. This makes the style checker's output noisy and confuses contributors. TypeScript actually requires the `.tsx` extension for JSX files as well, so we won't be able to enforce this anyway.
=> Disable ESLint rule for JSX file extensions

utils/markdown/renderer.jsx
Cherry pick of #4313 on release-5.18.
- #4313: Only use the hljs-ln class when can highlight the code
/cc  @jespino
=> Automated cherry pick of #4313

components/widgets/modals/full_screen_modal.scss
MM-20621 - Updating z-index for fullscreen modals
Incorrect z-index is being applied to the fullscreen modal css that is added to the plugins. Instead of fixing that in different plugins, we should remove all fullscreen css from plugins as that is already available in the webapp.
Here's a ticket for that:
https://mattermost.atlassian.net/browse/MM-20744
https://mattermost.atlassian.net/browse/MM-20621
=> MM-20621 - Updating z-index for fullscreen modals

components/file_upload/file_upload.jsx, utils/utils.jsx
Cherry pick of #4325 on release-5.18.
- #4325: prevent drop an image from a browser on osx
=> Automated cherry pick of #4325

actions/websocket_actions.jsx
This PR loads the necessary user roles when receiving a member role update.
https://mattermost.atlassian.net/browse/MM-17261
=> [MM-17261] Load team roles when receiving a member role update

components/widgets/settings/setting.tsx, components/widgets/settings/text_setting.tsx, e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
- Adds an E2E test to verify that the system config `About Link` exists and can be modified
Test steps:
- Reset config to defaults
- Login as sysadmin & visit the page `/admin_console/site_config/customization`
- Verify the text in the label for the setting
- Verify that the help text exists and is correct
- Verify that the input exists and that it has the default about link
- Clear, modify and save the new about link
- Check that the config was saved by hitting the API
- Fixes https://github.com/mattermost/mattermost-server/issues/13177
- JIRA: https://mattermost.atlassian.net/browse/MM-20341
=> [MM-20341] Add E2E test to verify customizable system config "About Link"

components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap, components/admin_console/plugin_management/plugin_management.jsx, i18n/en.json
Point the system console help link re: plugin signing at https://mattermost.com/pl/default-plugin-signing. Note that this permalink does not yet route anywhere, and shows an error message on mattermost.com, but will be replaced in advance of the v5.18 release.
Fixes: https://mattermost.atlassian.net/browse/MM-20311
=> MM-20311: plugin signing permalink

components/admin_console/schema_admin_settings.jsx
Fixing error handling for schema admin settings
[MM-20765](https://mattermost.atlassian.net/browse/MM-20765)
=> Fixing error handling for schema admin settings

e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
… Download Page Link setting"
UI Automation: Write an automated test using Cypress for "Can change Mattermost Apps Download Page Link setting"
Fixes https://github.com/mattermost/mattermost-server/issues/13174
None
None
=> [GH-13174] UI Automation: Write an automated test using Cypress for "Can change Mattermost Apps Download Page Link setting"

components/admin_console/system_users/system_users.jsx, components/admin_console/system_users/system_users.test.jsx
Remove erroneous parameter for debounce (generating missed requests for user searches).
[MM-20701](https://mattermost.atlassian.net/browse/MM-20701)
=> Remove erroneous parameter for debounce

components/sidebar/sidebar.jsx
Fixing JS error on channel leave or being removed from the channel. If the
channelId was undefined or the channelId is not longer rendered there is no
ref, we need to check that before we try to use the ref.
[MM-20929](https://mattermost.atlassian.net/browse/MM-20929)
[MM-20920](https://mattermost.atlassian.net/browse/MM-20920)
=> Fixing JS error on channel leave or being removed from the channel

components/admin_console/color_setting.tsx
Fixing color pickers in the admin console
[MM-20924](https://mattermost.atlassian.net/browse/MM-20924)
=> Fixing color pickers in the admin console

components/create_comment/create_comment.jsx, components/create_comment/create_comment.test.jsx
Focusing back the message input box on preview disable
[MM-19813](https://mattermost.atlassian.net/browse/MM-19813)
=> MM-19813 - Focusing back the message input box on preview disable

components/create_comment/create_comment.jsx, components/create_post/create_post.jsx, components/edit_post_modal/edit_post_modal.jsx, components/edit_post_modal/edit_post_modal.test.jsx, components/edit_post_modal/index.js, utils/post_utils.jsx, utils/post_utils.test.jsx
Adding enter inside blocks work properly on edit and take into consideration the position of the cursor
[MM-20658](https://mattermost.atlassian.net/browse/MM-20658)
=> Adding enter inside blocks work properly on edit and take into consideration the position of the cursor

sass/layout/_sidebar-right.scss, sass/responsive/_tablet.scss
Fix to spacing around the flagged and pinned icons on the RHS when in compact mode.
Before:
After:
https://mattermost.atlassian.net/browse/MM-20975
=> [MM-20975] Fix spacing on RHS Pinned and flag icon

sass/layout/_team-sidebar.scss
Fixing Team icons opacity in teams menu
This was broken here: dee85fb1acc405232a4f89834239f6546308c6ee to fix a problem
of visualization of the team icons in the admin console. This fix is respecting
that change and fixing the current bug.
[MM-21082](https://mattermost.atlassian.net/browse/MM-21082)
=> Fixing Team icons opacity in teams menu

sass/layout/_team-sidebar.scss
Cherry pick of #4485 on release-5.18.
- #4485: Fixing Team icons opacity in teams menu
/cc  @jespino
=> Automated cherry pick of #4485

components/announcement_bar/__snapshots__/text_dismissable_bar.test.jsx.snap, components/announcement_bar/configuration_bar/configuration_bar.jsx, components/announcement_bar/text_dismissable_bar.jsx, components/announcement_bar/text_dismissable_bar.test.jsx
Fixing admin console links in the announcements banner
[MM-21009](https://mattermost.atlassian.net/browse/MM-21009)
=> Fixing admin console links in the announcements banner

components/local_date_time/local_date_time.test.tsx, components/local_date_time/local_date_time.tsx
The issue happened when user's timezone is not supported by react-intl. Instead of react-intl, use moment-timezone to handle timezone conversion of post time.
Jira ticket: https://mattermost.atlassian.net/browse/MM-20988
See steps on Jira
=> MM-20988 Fix post time due to unsupported timezone by react-intl

components/file_upload/__snapshots__/file_upload.test.jsx.snap, components/file_upload/file_upload.jsx, components/file_upload/file_upload.test.jsx
Attaching only 1 click handler when in mobile view or not in mobile view.
Fixes https://mattermost.atlassian.net/browse/MM-20939
=> MM-20939 - File picker opens twice when trying to attach a file through the paperclip button in mobile view

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, sass/components/_files.scss, sass/layout/_markdown.scss
* With some of the recent changes to show image preview on click we changed the max dimensions of the markdown images causing a difference in placeholder image size and rendered image size. This causes a minor scroll pop causing the new message line to move above
The reason why `calc(100% - 5px)` was added is to make sure markdown image on RHS is not cutoff https://github.com/mattermost/mattermost-webapp/pull/3639#pullrequestreview-288559800. I was able to solve this by changing the container styles so the svg-placeholder also inherits this style.
Retaining hover effect on RHS
https://mattermost.atlassian.net/browse/MM-21057
Before:
After:
=> MM-21057 Fix for New message line cutoff at the top of channel

components/admin_console/admin_definition.jsx, components/channel_header_dropdown/channel_header_dropdown_items.js, components/channel_header_dropdown/index.js, components/main_menu/index.jsx, components/main_menu/main_menu.jsx
Cherry pick of #4511 on release-5.18.
- #4511: MM-21197: Hides some groups-related inputs and menu items
/cc  @mkraft
=> Automated cherry pick of #4511

sass/layout/_markdown.scss, utils/__snapshots__/message_html_to_component.test.jsx.snap, utils/text_formatting.jsx, utils/text_formatting_imgs.test.jsx
* Add a class for the container of markdown images and decrease the width to show the
hover effect
* Update snapshots
https://mattermost.atlassian.net/browse/MM-21222
Check before image in ticket for reference.
After:
=> MM-21222 Hover effect on inline markdown images cutoff on the right edge in RHS

components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap, components/admin_console/plugin_management/plugin_management.jsx, components/admin_console/plugin_management/plugin_management.test.jsx
In System Console, the marketplace URL is disabled if Enable Remote Marketplace is disabled. 
Additionally, moved the Enable Remote Marketplace setting next to the Marketplace URL that are directly related and affect each other behavior. 
[MM-21144](https://mattermost.atlassian.net/browse/MM-21144)
**Enabled Remote Marketplace `true`:**
**Enable Remote Marketplace `false`:**
=> MM-21144- Disable Marketplace URL if RemoteMarketplace is false

components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap, components/widgets/menu/menu_items/menu_item.scss, components/widgets/menu/menu_items/menu_item_action.test.tsx, components/widgets/menu/menu_items/menu_item_action.tsx, components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx, components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
Cherry pick of #4532 on release-5.18.
- #4532: Make longer <MenuItem>s wrap instead of
=> Automated cherry pick of #4532

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, components/size_aware_image.test.jsx
Remove code workaround that was added in `size_aware_image` component to support image attachments in IE11 (no longer supported).
Fixes https://github.com/mattermost/mattermost-server/issues/13365
JIRA link https://mattermost.atlassian.net/browse/MM-21087
=> [MM-21087] Remove IE11 workaround from size_aware_image  component

sass/layout/_markdown.scss, utils/markdown/renderer.jsx
Fixes a styles issue in inline markdown paragraphs, which is a regression from [this PR](https://github.com/mattermost/mattermost-webapp/pull/3877). It was specially affecting long channel header descriptions and system messages. Also, when an inline markdown image was used at the beginning of a long header description, its size was affected (way too small).
https://mattermost.atlassian.net/browse/MM-21284
**Examples before the fix**
**(A)**
**(B)**
**(C)**
**Examples after the fix**
**(A)**
**(B)**
**(C)**
=> Fix inline markdown paragraph styles

components/create_comment/create_comment.jsx, components/create_post/create_post.jsx, components/edit_post_modal/edit_post_modal.jsx, components/edit_post_modal/edit_post_modal.test.jsx, components/edit_post_modal/index.js, utils/post_utils.jsx, utils/post_utils.test.jsx
Cherry pick of #4438 on release-5.19.
- #4438: Adding enter inside blocks work properly on edit and take
/cc  @jespino
=> Automated cherry pick of #4438

components/widgets/menu/menu.test.tsx, components/widgets/menu/menu.tsx, components/widgets/menu/menu_group.test.tsx, components/widgets/menu/menu_group.tsx, e2e/cypress/integration/menus/hamburguer_menu_spec.js
This PR fixes the problem when a user clicks on a divider and the menu toggles
https://mattermost.atlassian.net/browse/MM-20861
=> Stop propagating divider click handler to avoid toggle

components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap, components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
This is another set of fairly trivial changes to get rid of `this.context.intl` in the custom theme chooser.
This PR is based on https://github.com/mattermost/mattermost-webapp/pull/4470. Changes specific to it are here: https://github.com/mattermost/mattermost-webapp/compare/mm17555h...mm17555j
For QA, please confirm that the custom theme picker in the account settings is still translated correctly.
https://mattermost.atlassian.net/browse/MM-17555
=> MM-17555 Use FormattedMessage in CustomThemeChooser 

components/sidebar/index.js, components/sidebar_right_menu/index.js
Cherry pick of #4544 on release-5.19.
- #4544: MM-21152: Fix race condition where CurrentTeam is not
/cc  @jespino
=> Automated cherry pick of #4544

components/admin_console/admin_definition.jsx, components/user_settings/display/index.js
Cherry pick of #4548 on release-5.19.
- #4548: MM-21290: Adds feature flag hiding of toggle for
/cc  @mkraft
=> Automated cherry pick of #4548

package.json
The automated check `ci/circleci: test` doesn't contain metadata/results of the unit tests. (See screenshot.)
This config change corrects the output file. The current configuration isn't recognized and reverts to the default `./junit.xml` instead of the desired `build/test-results.xml`.
None
None
=> [Build] Fix XML output of unit test results so circle-ci can find and upload it

package-lock.json, package.json
updated mmjstool reference
Fixes: https://mattermost.atlassian.net/browse/MM-21148
mmjstool - https://github.com/mattermost/mattermost-utilities/pull/21
mobile - https://github.com/mattermost/mattermost-mobile/pull/3754
=> MM-21148 -  `make i18n-extract` throws an error if mobile repo is not checked out

components/markdown_image.jsx, components/markdown_image.test.jsx
Automatic Merge
(cherry picked from commit 2d496bf1986f4da5ad5ef941b08aa073de780e7d)
This component was changed to inherit from PureComponent. When that was done, the variable props included more than just the properties for the image. When this was done, instead of passing props to the SizeAwareImage, individual properties were set and passed.
Width and Height and Title are no longer being passed to SizeAwareImage. This PR adds those three properties, so that SizeAwareImage will set them.
https://mattermost.atlassian.net/browse/MM-21421
=> MM-21421: Fix height and width parameters for inline image. (#4623)

components/sidebar/sidebar.jsx
Checking for channel ref before trying to get the value of it for LHS scroll correction.
If the ref does not exists as with DM's on load it will prevent the crash from happening but it will not scroll correct LHS. This follows the same behaviour as we had before
https://mattermost.atlassian.net/browse/MM-20863
=> MM-20863 Fix for permalink to DM failing to load on daily

components/change_url_modal/change_url_modal.test.jsx, components/channel_header_mobile/channel_info_button/channel_info_button.test.js
These tests that use string refs will break when react-intl is upgraded, so I modified them slightly to not use the refs.
https://mattermost.atlassian.net/browse/MM-17555
Part of https://github.com/mattermost/mattermost-webapp/pull/4615
=> MM-17555 Update tests that use string refs

utils/markdown/index.test.js, utils/markdown/renderer.jsx
Basically, this makes it so that there's 3 cases for the code block:
1. If there's no language tag, the text wraps. This matches the old behaviour.
```
this doesn't wrap
```
2. If there's a valid language tag, the text wraps and shows line numbers. This is the relatively new behaviour added in 5.18
```java
this.doesnt("wrap").andHas("lineNumbers");
```
3. If there's an invalid language tag, the text doesn't wrap or show line numbers. This matches the old behaviour.
```nowrap
this doesn't wrap or have line numbers
```
https://mattermost.atlassian.net/browse/MM-20622
=> MM-20622 Only wrap code without a language tag

components/post_view/date_separator/__snapshots__/date_separator.test.jsx.snap, components/recent_date.tsx, components/widgets/separator/__snapshots__/separator.test.tsx.snap, components/widgets/separator/basic-separator.tsx, e2e/cypress/integration/messaging/date_separator_spec.js
Cherry pick of #4650 on release-5.19.
- #4650: use react-intl by default or moment-timezone for
=> Automated cherry pick of #4650

components/local_date_time/local_date_time.test.tsx, components/local_date_time/local_date_time.tsx, e2e/cypress/integration/messaging/local_date_time_spec.js
This fixes the issue of timestamp with leading zero on 12-hour format for locale that don't expect to have leading zero.
Same approach done with other PR - [with date separator](https://github.com/mattermost/mattermost-webapp/pull/4650) which is to render post time with react-intl by default and fallback to moment-timezone for unsupported locale.
For ease of review, part of https://github.com/mattermost/mattermost-webapp/pull/4463 was reverted.
Jira ticket: https://mattermost.atlassian.net/browse/MM-21342
=> MM-21342 Fix leading zero on post by using react-intl by default and fallback to moment-timezone for unsupported locale

stores/local_storage_store.jsx, stores/local_storage_store.test.jsx
Fixes a couple issues with local storage. The removePreviousChannelName() was calling `localStorage` directly. In order to properly concatenate the key with the base path, it should be calling the local functions. 
Changed to call local functions and created local function for removeItem().
https://mattermost.atlassian.net/browse/MM-21667
=> MM-21667 fix redirection on leave channel with subpath

components/create_post/create_post.jsx, components/create_post/create_post.test.jsx, components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/rhs_root_post.jsx, components/suggestion/suggestion_box.jsx, components/suggestion/suggestion_box.test.jsx
* Fix couple of setState calls being called all the time when typing
This is similar to https://github.com/mattermost/mattermost-webapp/pull/4664.
* Delay setting draft to localstorage to improve performance
* Setting of draft is triggering store update invalidating the cache for memoization of selectors
* Delaying this by a little bit to to distribute the code execution so few more frames can be squeezed in. This mainly helps users with busy JS thread because of sidebar profiles
https://mattermost.atlassian.net/browse/MM-20349
Before:
After:
For 5.19v branch there is a regression with memoization which needs to be fixed by cherry-picking https://github.com/mattermost/mattermost-redux/pull/1011
=> MM-20349 Improve typing performance

components/channel_layout/channel_identifier_router/actions.js, components/channel_layout/channel_identifier_router/actions.test.js, components/channel_layout/channel_identifier_router/index.js, e2e/cypress/integration/channel/channel_routing_spec.js
Cherry pick of #4685 on release-5.20.
- #4685: Export functions to be able to spy on them in the tests
=> Automated cherry pick of #4685

components/searchable_user_list/searchable_user_list.jsx
Placeholder is expected to be of type 
```
placeholder: {
id: string;
defaultMessage: string;
values?: {string: any};
};
```
however there was a recent commit changing the type being passed down to a string causing any component referencing `SearchableUserList` to error on load
https://mattermost.atlassian.net/browse/MM-21979
=> [MM-21979] Fix incorrect placeholder prop for searchable user list

components/widgets/modals/full_screen_modal.tsx
This component wasn't passing refs correctly previously because `injectIntl` can't take refs on its own.
I wasn't able to write unit tests for this because you're not able to test `InvitationModal` using `mount` (see https://mattermost.atlassian.net/browse/MM-21948), and I ran into some weird problems with testing refs on `FullScreenModal` directly.
https://mattermost.atlassian.net/browse/MM-21721
=> MM-21721 Fix FullScreenModal not supporting refs

components/linking_landing_page/linking_landing_page.tsx
This PR reverts back to using the `mattermost://` deep linking protocol for mobile apps. It also allows the store app to open up if the protocol does not succeed.
https://mattermost.atlassian.net/browse/MM-22005
=> Revert to mattermost:// protocol for mobile and to store app if that fails

components/admin_console/team_channel_settings/channel/details/channel_modes.tsx
Fixing logic for sync group members which is reversed on latest master.
https://mattermost.atlassian.net/browse/MM-22025
=> [MM-22025] Fix Reverse Logic

components/linking_landing_page/linking_landing_page.tsx
Cherry pick of #4729 on release-5.20.
- #4729: Revert to mattermost:// protocol for mobile and to store
=> Automated cherry pick of #4729

components/toast_wrapper/toast_wrapper.jsx, components/toast_wrapper/toast_wrapper.test.jsx
* This happens because of a race with toastState and marking channel new message line at action.
Toast state is set to true using `getDerivedStateFromProps` and then in componentDidUpdate we use `updateNewMessagesAtInChannel` to change new line position which makes the count to zero but the toast is not removed again in `getDerivedStateFromProps` causing the toast to keep the state true.
Ideally i wanted to solve this by not making the toast state to true in the first place but it is really hard to achieve and this solution seems to work just fine,
* Fixing this by putting up a check to not show toasts when unread count goes to 0.
https://mattermost.atlassian.net/browse/MM-21872
=> MM-21872 Fix for toast showing o new messages

package-lock.json, package.json
Update `mmjstool` version in the webapp so that `i18n-extract` reads TypeScript files.
Needed for https://github.com/mattermost/mattermost-webapp/pull/4747
=> Update mmjstool version to support TypeScript

components/widgets/icons/close_icon.jsx
Fixing x button alignment in invitation process. This was introduced in the PR #4628, I checked the other places that it is used there and is not breaking the style.
Looks like the other similar change made to the `unread_bellow_icon.jsx` is working fine everywhere is used, so I didn't restore the `viewBox` there.
[MM-21953](https://mattermost.atlassian.net/browse/MM-21953)
=> MM-21953: Fixing x button alignment in invitation process

components/__snapshots__/quick_input.test.jsx.snap, components/channel_header_mobile/channel_info_button/__snapshots__/channel_info_button.test.js.snap, components/overlay_trigger.test.tsx, components/overlay_trigger.tsx, plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap
This PR is based off of #4701. To see the changes exclusive to it, go here: https://github.com/mattermost/mattermost-webapp/compare/mm21880...mm21874
In the custom `OverlayTrigger`, the way that we were using `React.cloneElement` to render the overlay was causing the `className` and `style` props given to us by `react-bootstrap` to overwrite any that we specified, such as the `className` given to the Channel Header popover to position it. react-bootstrap's `OverlayTrigger` handles merging these props itself, as long as the props are passed into the overlay correctly. 
https://mattermost.atlassian.net/browse/MM-21874
=> MM-21874 Merge styling props for children of custom OverlayTrigger

components/invitation_modal/invitation_modal.jsx
This PR fixes errors caused by calling `getWrapperInstance` when is not available.
Looks like the [source PR](https://github.com/mattermost/mattermost-webapp/pull/4637).
Harrison explained it offline:
```
It's only currently needed for components wrapped with `connect`, but previously, it was 
also needed for components wrapped with `injectIntl`. The react-intl upgrade I did recently 
made it so that `injectIntl` no longer needs it
```
https://mattermost.atlassian.net/browse/MM-22099
=> Not needed getWrappedInstance in this case

sass/components/_modal.scss
Cherry pick of #4734 on release-5.20.
- #4734: Fix double highlight when using mouse and keyboard together
/cc  @larkox
=> Automated cherry pick of #4734

components/toast_wrapper/toast_wrapper.jsx, components/toast_wrapper/toast_wrapper.test.jsx
Cherry pick of #4737 on release-5.20.
- #4737: MM-21876 Fix toast not showing up on marking channel as
=> Automated cherry pick of #4737

components/widgets/modals/full_screen_modal.scss
The `FullScreenModal` css class contains some css that causes issues in the Jira subscriptions modal when the user's screen is narrow, specifically the placement of the "back" and "close" buttons. Using a new css class `FullScreenModal--compact`, we can have the Jira plugin opt-in to using some reusable styling on the top of the existing class.
Discussion can be found here: https://github.com/mattermost/mattermost-plugin-jira/pull/413#pullrequestreview-336329676
https://mattermost.atlassian.net/browse/MM-20744
Without new css class
X button is on top of the `New Subscription` button.
With new css class
Placement of buttons and content is reasonable.
Without new css class
In this scenario, we have scrolled down in a large form. Buttons are fixed and so interfere with the form.
With new css …
=> [MM-20744] Add FullScreenModal--compact css class for narrow screens

components/invitation_modal/invitation_modal.jsx
Cherry pick of #4767 on release-5.20.
- #4767: Not needed getWrappedInstance in this case
=> Automated cherry pick of #4767

package-lock.json, package.json
Fix commit hash of mattermost-redux for release-5.20 branch -  https://github.com/mattermost/mattermost-redux/commit/a0e7a1cbedb2ec051e0d2411fd47ee19bb49d709
=> Fix commit hash of mattermost-redux for release-5.20 branch

components/linking_landing_page/linking_landing_page.tsx
On iOS, the auto redirect to the app store when failing to deep link (ie. the app is not installed) was causing issues when the app was actually installed. The `setTimeout()` would not be cleared once the app switched over and thus the app store would still open on successful deep link.
This PR cuts the feature from iOS for the time being while we look into other options.
https://mattermost.atlassian.net/browse/MM-22005
=> [MM-22005] Cut auto redirect to app store on failed deep link for iOS

components/suggestion/search_channel_provider.jsx
There was a bug introduced in https://github.com/mattermost/mattermost-webapp/pull/4217 regarding passing the selected result back to searchbox
Fixes https://mattermost.atlassian.net/browse/MM-21255
=> MM-21255  - Search "in:@username" changes the label to "in:userid" in the search input

i18n/en.json
Add missing text.
https://mattermost.atlassian.net/browse/MM-22030
=> MM-22030: Localization: an empty translation unit for admin.saml.getSamlMetadataFromIDPFetching

components/linking_landing_page/linking_landing_page.tsx
Cherry pick of #4797 on release-5.20.
- #4797: Cut auto redirect to app store on failed deep link
=> Automated cherry pick of #4797

components/suggestion/search_channel_provider.jsx
Cherry pick of #4792 on release-5.20.
- #4792: fix display name of search results
/cc  @reflog
=> Automated cherry pick of #4792

e2e/cypress/integration/channel/send_message_via_profile_popover_spec.js
Fix failing send message via profile popover spec. Added waits for elements to load after clicks. For some reason, the components become detached from DOM (maybe due to app component refresh in the background); hence wait needs to happen before cypress element query.
=> Fix send message via profile popover spec

e2e/cypress/integration/channel/header_spec.js
Fix failing header spec. Looks like casing is controlled by css. However, the actual text value changed casing which is not reflective of css visual
=> Fix header spec

e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Fix failing member invitation ui spec. There are behavior changes especially on the **MM-18040 Verify Invite New/Existing Users** test. Not sure if release spreadsheet test cases are up to date but I captured the current behavior from master.
=> Fix member invitation ui spec

e2e/cypress/integration/interactive_menu/basic_options_spec.js, e2e/cypress/support/task_commands.js
Fix failing basic options spec. I have observed at least two ways it fails intermittently
- timeout issue on webhook
- use of crowded town-square takes time for the channel to load
Hence,
- cleaned up timeouts for webhook and increased from TINY to MEDIUM (sometimes it still fails on SMALL)
- created new channel for the run instead of using town-square
=> Fix basic options spec

components/channel_layout/channel_controller.jsx, components/favicon_title_handler/favicon_title_handler.test.jsx, components/favicon_title_handler/favicon_title_handler.tsx, components/favicon_title_handler/index.ts, components/legacy_sidebar/sidebar.jsx, components/legacy_sidebar/sidebar.test.jsx
Favicon and titlebar control is now in its own component for both sidebars.
https://mattermost.atlassian.net/browse/MM-21911
=> [MM-21911] Moved favicon and titlebar update to its own component

components/create_post/create_post.jsx
Edge case regression caused by some performance improvements. Thanks to @sudheerDev for finding the fix.
https://mattermost.atlassian.net/browse/MM-22233
=> MM-22233 Fix 2 byte character drafts not being cleared

components/sidebar/sidebar.jsx
`element.position()` can at times return `undefined` so we need to check for it.
https://mattermost.atlassian.net/browse/MM-22311
=> MM-22311 Fix JS crash when leaving all teams

components/toast_wrapper/toast_wrapper.jsx, components/toast_wrapper/toast_wrapper.test.jsx
Adding check to prevent toast appearing when at bottom
https://mattermost.atlassian.net/browse/MM-21933
=> MM-21933 Do not show toast when a channel is marked as unread and at bottom

components/toast_wrapper/toast_wrapper.jsx, components/toast_wrapper/toast_wrapper.test.jsx
Cherry pick of #4827 on release-5.20.
- #4827: MM-21933 Do not show toast when a channel is marked as unread
=> Automated cherry pick of #4827

components/sidebar/sidebar.jsx
We're temporarily reverting this behaviour for 5.20 since we aren't able to make it scroll to the current channel on team switch without an animation. I have a separate fix planned for master once this goes in, but it's more involved, so I don't want to risk it for 5.22.
With this PR, the sidebar will still scroll to channels by clicking on the More Unread indicators or when using the alt+up/down hotkeys, but it will no longer scroll when you use the channel switcher or click on a channel link to switch channels.
https://mattermost.atlassian.net/browse/MM-22199
=> MM-22199 Disable scrolling to channel on switch

e2e/cypress/integration/channel/send_message_via_profile_popover_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js, e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Fix timeout issues.
- invitation timeout issues found in cypress builds might be due to new IdleTimeout config which is defaulted to 60s. Before IdleTimeout, it used to read session timeout from ReadTimeout which is 300s
- I was able to replicate popover message timeout and increased from TINY to SMALL to fix
=> Fix timeout issues

components/permissions_gates/team_permission_gate/team_permission_gate.tsx
The type of children got changed accidentally during the migration to TypeScript.
@jgilliam17 Skipping QA review on this since it just fixes a warning that only occurs during development.
https://mattermost.atlassian.net/browse/MM-21949
=> MM-21949 Fix type of children prop for TeamPermissionGate

components/widgets/inputs/channels_input.jsx, components/widgets/inputs/users_emails_input.jsx
When the users emails is not publicly available and you try to add a user, when
you blur the input field, during the blur the first match is used (which is
going to be the first match in the list because the empty string is going to
match with the empty email address.
To avoid this, i remove entirely the posibility of autocompletion with empty
string here and in the channels selector.
[MM-22351](https://mattermost.atlassian.net/browse/MM-22351)
=> MM-22351: Fix users/emails autocompletion when user emails is not available

components/needs_team/needs_team.jsx
In the PR #4479 we introduced this bug. The lifecycle was changed and
accidentally something was store in the state at initialization but wasn't
updated. This fixes that problem.
[MM-22346](https://mattermost.atlassian.net/browse/MM-22346)
=> MM-22346: Fix open new added team
