mattermost/mattermost-webapp

components/profile_popover/profile_popover.jsx, components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/search_results_item.jsx, components/user_profile.jsx
MM-13518 - Updating profile popover in RHS
https://mattermost.atlassian.net/browse/MM-13518
=> MM-13518 - Updating profile popover in RHS

components/dot_menu/dot_menu.jsx, components/dot_menu/dot_menu.test.jsx, components/dot_menu/dot_menu_empty.test.jsx, components/dot_menu/dot_menu_mobile.test.jsx, components/dot_menu/index.js, utils/post_utils.jsx
The utility function implementing this had a side effect, i splitted the
side effect from the permission checking.
=> Disable edition on dot menu properly

components/sidebar/index.js
* Use updated redux selector for unread count
[MM-13627](https://mattermost.atlassian.net/browse/MM-13627)
=> MM-13627 Fix DM and GM mention counts missing from browser tab

utils/utils.jsx
MM-13607 - Updating modal background
https://mattermost.atlassian.net/browse/MM-13607
=> MM-13607 - Updating modal background

components/analytics/team_analytics/team_analytics.jsx
MM-13601 - Updating team statistics page icons
https://mattermost.atlassian.net/browse/MM-13601
=> MM-13601 - Updating team statistics page icons

components/emoji/emoji_page.jsx, sass/routes/_backstage.scss
MM-13655 - Updating custom emoji page
https://mattermost.atlassian.net/browse/MM-13655
=> MM-13655 - Updating custom emoji page

package-lock.json, package.json
Update mm-redux hash for master for https://github.com/mattermost/mattermost-redux/pull/752
=> Update mm-redux hash

sass/components/_popover.scss, sass/layout/_headers.scss, sass/layout/_markdown.scss
MM-13352 - Fixing blockquotes in channel header
https://mattermost.atlassian.net/browse/MM-13352
=> MM-13352 - Fixing blockquotes in channel header

sass/layout/_headers.scss
Fixes status icon hover wobble in Safari.
https://mattermost.atlassian.net/browse/MM-13338
=> MM-13338: Fixes status icon hover wobble.

sass/responsive/_tablet.scss
MM-13646 - Updating header popover position
https://mattermost.atlassian.net/browse/MM-13646
=> MM-13646 - Updating header popover position

utils/utils.jsx
MM-13822 - Updating modal background
https://mattermost.atlassian.net/browse/MM-13822
=> MM-13822 - Updating modal background

actions/views/root.js, components/login/login_controller/login_controller.jsx, root.jsx, utils/utils.jsx
This PR implements CSRF protection tokens for additional hardening compared to the currently used custom header. For additional explanation, please check the linked server PR below.
https://mattermost.atlassian.net/projects/MM/issues/MM-10346
=> [MM-10346] CSRF Token Implementation (Wipe cookie on logout)

sass/components/_emoticons.scss
MM-13853 - Updating emoji picker bg
https://mattermost.atlassian.net/browse/MM-13853
=> MM-13853 - Updating emoji picker bg

sass/layout/_post.scss
MM-13854 - Updating post textarea css
https://mattermost.atlassian.net/browse/MM-13854
=> MM-13854 - Updating post textarea css

components/interactive_dialog/dialog_element.jsx, components/interactive_dialog/dialog_element.test.jsx, components/widgets/settings/text_setting.jsx
Fixes a warning when invalid subtypes where being passed to TextSetting from DialogElement.
=> MM-13508 Fixing react warning with invalid subtype.

package-lock.json, package.json
Updated since getting error like:
none
=> Update mattermost-redux commit

sass/layout/_post-right.scss, sass/responsive/_mobile.scss
MM-13836 - Updating compact view css
https://mattermost.atlassian.net/browse/MM-13836
=> MM-13836 - Updating compact view css

components/post_view/post_image/post_image.jsx
Fixes rounded corners issue with preview images caused by https://github.com/mattermost/mattermost-webapp/pull/2317/files
[MM-13941](https://mattermost.atlassian.net/browse/MM-13941)
=> MM-13941 Fix rounded corners for link preview images

sass/layout/_post-right.scss
MM-13935 - Updating post right css
https://mattermost.atlassian.net/browse/MM-13935
=> MM-13935 - Updating post right css

components/user_settings/general/user_settings_general.jsx
The changes introduced in this PR requires that one submits the password in the patch request of a email change.
https://mattermost.atlassian.net/projects/MM/issues/MM-13839
=>  [MM-13839] Check for password when updating the eMail

components/channel_header_dropdown/mobile_channel_header_dropdown.js, sass/responsive/_mobile.scss
MM-12948 - Fixing dividers in dropdown menu mobile
https://mattermost.atlassian.net/browse/MM-12948
=> MM-12948 - Fixing dividers in dropdown menu mobile

cypress/integration/account_settings/display/channel_display_mode_spec.js, cypress/support/index.js
Add new E2E test cases for channel display mode
https://github.com/mattermost/mattermost-server/issues/10033
=> MM-13225 Add E2E test for channel display modes

sass/components/_badge.scss
MM-13998 - Updating badge alignment
https://mattermost.atlassian.net/browse/MM-13998
=> MM-13998 - Updating badge alignment

components/admin_console/reset_password_modal/reset_password_modal.jsx, components/change_url_modal/__snapshots__/change_url_modal.test.jsx.snap, components/change_url_modal/change_url_modal.jsx, components/convert_channel_modal/convert_channel_modal.jsx, components/leave_team_modal/__snapshots__/leave_team_modal.test.jsx.snap, components/leave_team_modal/leave_team_modal.jsx, components/leave_team_modal/leave_team_modal.test.jsx
MM-14048 - Updating secondary button on modal
https://mattermost.atlassian.net/browse/MM-14048
=> MM-14048 - Updating secondary button on modal

components/searchable_user_list/searchable_user_list.jsx, cypress/integration/account_settings/general/nickname.js
- Click on hamburger menu
- Select Account Settings > General > Nickname > Edit
- Type in a Nickname and press "Save"
- Close Account Settings modal
- In a channel you belong to, click the channel name and select Manage Members (or View Members)
- In the "Search Users" field, type your username
Expected:
- After 3) the Nickname you saved is displayed in the Nickname field
- After 6) your nickname is displayed in parentheses next to your name
https://github.com/mattermost/mattermost-server/issues/10044
=> [MM-13279] Add automated test using cypress for Account Settings > Add Nickname

components/announcement_bar/configuration_bar.jsx
The prop was being checked incorrectly.
https://mattermost.atlassian.net/browse/MM-14054
=> MM-14054 Fix license announcement bar

components/post_view/post_info/__snapshots__/post_info.test.jsx.snap, components/post_view/post_info/index.js, components/post_view/post_info/post_info.jsx, components/post_view/post_info/post_info.test.jsx, components/post_view/post_reaction/__snapshots__/post_reaction.test.jsx.snap, components/post_view/post_reaction/index.js, components/post_view/post_reaction/post_reaction.jsx, components/post_view/post_reaction/post_reaction.test.jsx, components/rhs_comment/index.js, components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/index.js, components/rhs_root_post/rhs_root_post.jsx
Refactor `PostInfo` component for E2E, adding `PostReaction` component.  
This is the first part of MM-13979.  Submitted on a separate PR for ease of review - https://github.com/mattermost/mattermost-webapp/pull/2355/files#r255449476
Jira ticket: [MM-13979](https://mattermost.atlassian.net/browse/MM-13979)
=> [MM-13979] Refactor PostInfo for E2E

components/admin_console/email_settings.jsx, i18n/en.json
Exposes Reply-To email header configuration in UI.
*Has associated server change.*
https://mattermost.atlassian.net/browse/MM-14006
=> Exposes Reply-To email header configuration in UI.

components/widgets/loading/loading_spinner.jsx, components/widgets/loading/loading_spinner.test.jsx, sass/components/_files.scss
MM-13945 - Updating spinner icon
https://mattermost.atlassian.net/browse/MM-13945
=> MM-13945 - Updating spinner icon

sass/routes/_settings.scss
MM-14080 - Updating help text and dropdown at system console
https://mattermost.atlassian.net/browse/MM-14080
=> MM-14080 - Updating help text and dropdown at system console

components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap, components/admin_console/group_settings/group_settings.jsx, i18n/en.json
Changes docs link.
https://mattermost.atlassian.net/browse/MM-13832
=> MM-13832: Changes docs link.

sass/routes/_signup.scss
MM-14153 - Updating buttons on signup page
https://mattermost.atlassian.net/browse/MM-14153
=> MM-14153 - Updating buttons on signup page

sass/routes/_admin-console.scss
MM-14124 - Updating sys console header height
https://mattermost.atlassian.net/browse/MM-14124
=> MM-14124 - Updating sys console header height

components/create_team/components/__snapshots__/display_name.test.jsx.snap, components/create_team/components/display_name.jsx, components/create_team/components/team_url/__snapshots__/team_url.test.jsx.snap, components/create_team/components/team_url/team_url.jsx, cypress/integration/team/create_a_team_spec.js, cypress/utils/index.js, package-lock.json
Add E2E test for create a team
Fixes https://github.com/mattermost/mattermost-server/issues/10199
=> [MM-13872] UI Automation: Write an automated test using `cypress` for "Create a Team"

sass/components/_badge.scss
MM-14158 - Updating badge in sidebars
https://mattermost.atlassian.net/browse/MM-14158
=> MM-14158 - Updating badge in sidebars

cypress/integration/account_settings/display/channel_display_mode_spec.js, cypress/integration/account_settings/general/nickname.js, cypress/integration/account_settings/sidebar/channel_switcher_spec.js, cypress/integration/channel/edit_message_spec.js, cypress/integration/channel/header_spec.js, cypress/integration/channel/message_draft_spec.js, cypress/integration/channel/message_spec.js, cypress/integration/team/create_a_team_spec.js, cypress/integration/team/teams_spec.js
Update test keys and description of all Cypress specs based on [added guidelines in writing test specs](https://github.com/mattermost/mattermost-developer-documentation/pull/237). Goal is to improve tracking between the codebase and release testing spreadsheet.
@lindy65 You might want to verify if it's updated correctly based on Jira tickets and our recent meeting agreement (in case I'm missing something important).  Below are the tickets included herein.
- [MM-13225](https://mattermost.atlassian.net/browse/MM-13225)
- [MM-13279](https://mattermost.atlassian.net/browse/MM-13279)
- [MM-12980](https://mattermost.atlassian.net/browse/MM-12980)
- [MM-13216](https://mattermost.atlassian.net/browse/MM-13216)
- [MM-13909](https://mattermost.atlassian.net/browse/MM-13909)
- …
=> Update test keys and description of all Cypress specs

components/message_submit_error.jsx
Fix message id introduced by [this changes](https://github.com/mattermost/mattermost-webapp/commit/4453f86f87a4619765460422a681377c7c395bf3#diff-5f93a379fc7ea73ea9f8dd88f533adf9R37)
N/A
=> Fix message id

components/admin_console/push_settings.jsx
This PR promotes the subtitle of the Mobile Push admin console screen to the title, making the format consistent with the rest of the screens.
[MM-14029](https://mattermost.atlassian.net/browse/MM-14029)
=> [MM-14029] Promote subtitle to title in the Mobile Push admin screen

sass/responsive/_tablet.scss, sass/routes/_admin-console.scss
MM-14050 - Updating sys console UI for Users
https://mattermost.atlassian.net/browse/MM-14050
=> MM-14050 - Updating sys console UI for Users

components/add_users_to_team/__snapshots__/add_users_to_team.test.jsx.snap, components/add_users_to_team/add_users_to_team.jsx, components/team_members_dropdown/team_members_dropdown.jsx, components/team_sidebar/components/team_button.jsx, cypress/fixtures/users.json, cypress/integration/team/teams_spec.js, cypress/support/commands.js
Added an E2E test for adding a new member to a team. I couldn't figure out how to check for an email being sent to the user though.
Jira ticket: [MM-13548](https://mattermost.atlassian.net/browse/MM-13548)
Fixes: mattermost/mattermost-server#10039
=> [MM-13548] Added E2E test for adding new team member

cypress.json, package-lock.json, package.json
Add some dependencies for cypress in order to generate test reports
=> add reporter to cypress

components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap, components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx, components/user_settings/notifications/email_notification_setting/email_notification_setting.test.jsx, components/user_settings/notifications/email_notification_setting/index.js, components/user_settings/notifications/index.js, components/user_settings/notifications/user_settings_notifications.jsx, utils/utils.jsx
Fix email notification setting being out of sync with the RN apps
- used the utility function `getEmailInterval` similar to RN
- rearranged logic for rendering min and max setting view of Email Notification section
Jira ticket: [MM-14301](https://mattermost.atlassian.net/browse/MM-14301) and [MM-14296](https://mattermost.atlassian.net/browse/MM-14296)
=> [MM-14301 && MM-14296] Fix email notification setting being out of sync with the RN apps

package-lock.json, package.json
=> fix devdeps

package-lock.json, package.json
Updates the reference for mattermost-redux
=> Handle pending posts when dispatching RECEIVED_NEW_POST

sass/components/_buttons.scss, sass/routes/_admin-console.scss
MM-14280 - Updating btn-default styles
https://mattermost.atlassian.net/browse/MM-14280
=> MM-14280 - Updating btn-default styles

components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap, components/admin_console/group_settings/group_details/group_details.jsx
Adds back arrow to group configuration view.
https://mattermost.atlassian.net/browse/MM-13818
=> MM-13126: Adds back arrow to group configuration view.

sass/components/_sidebar-header-dropdown-button.scss, sass/components/_sidebar-header.scss, sass/layout/_headers.scss
Fixing main menu styling
[MM-14380](https://mattermost.atlassian.net/browse/MM-14380)
=> MM-14380: Fixing main menu styling

package-lock.json, package.json
Update [redux commit](https://github.com/mattermost/mattermost-redux/commit/33634b9633331e769312c42001b9f8d72e492781) with fix to unnecessary sorting of channels recency on reaction to a post.
Jira ticket: [MM-13863](https://mattermost.atlassian.net/browse/MM-13863)
=> [MM-13863] Fix unnecessary sorting of channels recency on reaction to a post

components/admin_console/group_settings/group_details/group_details.jsx
Fix for merge or copy/paste bug.
n/a
=> Fix for wrong click handler.

sass/layout/_post.scss
MM-14485 - Updating z-index for expand icon
https://mattermost.atlassian.net/browse/MM-14485
=> MM-14485 - Updating z-index for expand icon

components/dot_menu/dot_menu.jsx
Never show edit or deleted in archived channels
[MM-14481](https://mattermost.atlassian.net/browse/MM-14481)
=> MM-14481: Do not show edit or delete in archived channels

sass/layout/_headers.scss
Fixing group channels header on narrow browser window
[MM-14353](https://mattermost.atlassian.net/browse/MM-14353)
=> Fixing group channels header on narrow browser window

actions/emoji_actions.jsx, actions/emoji_actions.test.js, components/emoji_picker/emoji_picker.jsx
Update unit test for emoji actions
https://mattermost.atlassian.net/browse/MM-14278
=> [MM-14278] Update unit tests for emoji actions

sass/responsive/_mobile.scss
MM-14457 - Updating search “x” icon on mobile
https://mattermost.atlassian.net/browse/MM-14457
=> MM-14457 - Updating search “x” icon on mobile

sass/responsive/_mobile.scss
MM-14343 - Updating settings nav on mobile
https://mattermost.atlassian.net/browse/MM-14343
=> MM-14343 - Updating settings nav on mobile

sass/components/_files.scss, sass/components/_videos.scss, sass/responsive/_mobile.scss
MM-14486 - Updating image/link previews size
https://mattermost.atlassian.net/browse/MM-14486
=> MM-14486 - Updating image/link previews size

components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx, components/user_settings/notifications/email_notification_setting/email_notification_setting.test.jsx, components/user_settings/notifications/email_notification_setting/index.js, package-lock.json, package.json
Fix default behavior when enabling/disabling email batching
~~Note: Will ask release triage team if this will go through release.5.9.~~ 
Update: For release-5.9
Jira ticket: [MM-14527](https://mattermost.atlassian.net/browse/MM-14527)
=> [MM-14527] Fix default behavior when enabling/disabling email batching

components/textbox/textbox.jsx, sass/layout/_post.scss
Render message preview with single line break similar to when it gets posted
Jira ticket: [MM-14298](https://mattermost.atlassian.net/browse/MM-14298)
=> [MM-14298] Render message preview with single line break similar to when it gets posted

cypress/integration/channel/autocomplete_shown_each_channel_spec.js, cypress/support/commands.js
* Added E2E to show Autocomplete in each channel
Jira Ticket: [MM-14432](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) 
Test Key: M14432
=> [MM-14432] add E2E show autocomplete in each channel

components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap, components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx, components/user_settings/display/user_settings_theme/premade_theme_chooser/premade_theme_chooser.jsx, cypress/integration/account_settings/display/code_theme_colors_spec.js
* Add ID's to some elements around the theme settings
* Update snapshot for affected components
* Add e2e test to check background color and font color for all 4 themes
[JIRA Ticket](https://mattermost.atlassian.net/browse/MM-14319)
[GitHub Issue](https://github.com/mattermost/mattermost-server/issues/10366)
=> [MM-14319] E2E Code Theme Settings 

components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap, components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx, cypress/integration/account_settings/theme_color/custom_colors_sidebarStyles_spec.js, cypress/support/commands.js
Removed centerChannelStyles and linkAndButtonStyles specs. This branch only contains sidebarStyles spec and related commands. 
https://github.com/mattermost/mattermost-server/issues/10367
=> MM-4138_sidebarStyles

components/admin_console/system_users/system_users.jsx
Update System Console > Users > User Status Filter Name "None" to "All Users"
https://mattermost.atlassian.net/browse/MM-13877
Fixes https://github.com/mattermost/mattermost-server/issues/10333
=> [MM-13877] Update `User Status` filter name to "All Users"

sass/responsive/_tablet.scss
MM-14504 - Updating dropdown issue in sys con
https://mattermost.atlassian.net/browse/MM-14504
=> MM-14504 - Updating dropdown issue in sys con

cypress/integration/search/results_post_comment_spec.js
Add e2e test for RHS search result comments
[JIRA Ticket](https://mattermost.atlassian.net/browse/MM-14548)
Fixes https://github.com/mattermost/mattermost-server/issues/10437
=> [MM-14548] Added e2e test for RHS search result comments

actions/team_actions.jsx, actions/team_actions.test.js, components/needs_team/index.js, components/needs_team/needs_team.jsx, components/needs_team/needs_team.test.jsx, components/select_team/__snapshots__/select_team.test.jsx.snap, components/select_team/components/__snapshots__/select_team_item.test.jsx.snap, components/select_team/components/select_team_item.jsx, components/select_team/components/select_team_item.test.jsx, components/select_team/index.js, components/select_team/select_team.jsx, components/select_team/select_team.test.jsx, i18n/en.json, package-lock.json, package.json, sass/routes/_signup.scss
Adding the `LIST_PUBLIC_TEAMS`, `JOIN_PUBLIC_TEAMS`, `LIST_PRIVATE_TEAMS` and `JOIN_PRIVATE_TEAMS` permissions.
[MM-11049](https://mattermost.atlassian.net/browse/MM-11049)
=> Added join/list public/private teams permissions

sass/layout/_headers.scss
MM-14533 - Removing width for channel title
https://mattermost.atlassian.net/browse/MM-14533
=> MM-14533 - Removing width for channel title

components/local_date_time/local_date_time.jsx, cypress/integration/channel/edit_message_spec.js, package-lock.json
Adds e2e tests to check timestamp on edited post
https://github.com/mattermost/mattermost-server/issues/10041
=> Adds e2e tests to check timestamp on edited post

components/suggestion/switch_channel_provider.jsx
Follow-up to https://github.com/mattermost/mattermost-webapp/pull/2457 but for GMs.
https://mattermost.atlassian.net/browse/MM-14297
=> MM-14297 Match GM sidebar and channel switcher visibility check

sass/layout/_headers.scss
Restoring ellipsis LHS header username and team name
[MM-14380](https://mattermost.atlassian.net/browse/MM-14380)
=> Restoring ellipsis LHS header username and team name

sass/components/_badge.scss
MM-14586 - Updating badge css
https://mattermost.atlassian.net/browse/MM-14586
=> MM-14586 - Updating badge css

cypress/integration/at_mentions/at_mentions_spec.js
- Refactor the existing at-mention test to strip out duplication between itself and the new test
- Added new test for another scenario
Fixes https://github.com/mattermost/mattermost-server/issues/10442
[JIRA Ticket](https://mattermost.atlassian.net/browse/MM-14570)
=> [MM-14570] Added e2e test for at-mention setting

cypress/integration/channel/system_message_spec.js, cypress/support/commands.js
Implemeted E2E test for system message wrap validation
Fixes https://github.com/mattermost/mattermost-server/issues/10474
=> MM-14636 E2E test for system message wrap validation

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/channel_header/channel_header.js, sass/layout/_headers.scss
MM-14668 - Updating header elipsis
https://mattermost.atlassian.net/browse/MM-14668
=> MM-14668 - Updating header elipsis

package-lock.json, package.json
Reverts mattermost/mattermost-webapp#2551
=> Revert "MM-14970 Fix for Posts ovelapping with each other"

components/user_settings/general/user_settings_general.jsx
MM-14713 - Updating email general settings
https://mattermost.atlassian.net/browse/MM-14713
=> MM-14713 - Updating email general settings

components/suggestion/switch_channel_provider.jsx
Fix a bad usage of length on a set in the channel switcher and now that we throw in dev mode when this is encountered it's blocking another PR of mine.
=> Fix a bad usage of length on a set in the channel switcher

components/post_view/post_list.jsx, package-lock.json, package.json
Reverts mattermost/mattermost-webapp#2556
=> Revert "MM-14791 Safari and FF scroll correction issue when loading more posts"

components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
MM-14708 - Updating PAC position
https://mattermost.atlassian.net/browse/MM-14708
=> MM-14708 - Updating PAC position

cypress/integration/channel/header_spec.js, cypress/integration/channel/system_message_spec.js, cypress/support/commands.js
Added E2E test to validate proper rendering of quote sign in channel header
Fixes https://github.com/mattermost/mattermost-server/issues/10501
=> MM-14730 - Validate that channel header displays quote sign

components/channel_header/channel_header.js
Fixing DM loading
https://mattermost.atlassian.net/browse/MM-14799
=> MM-14799 Fixing DM loading.

package-lock.json, package.json
Fixes the issue of post overlap with react-window hash https://github.com/mattermost/react-window/pull/5
[MM-14790](https://mattermost.atlassian.net/browse/MM-14790)
=> MM-14790 Update hash for react-window to solve postoverlap

actions/team_actions.jsx
Restored addUserToTeamFromInvite action
[MM-14828](https://mattermost.atlassian.net/browse/MM-14828)
=> Restored addUserToTeamFromInvite action

components/user_settings/notifications/user_settings_notifications.jsx, sass/routes/_settings.scss
MM-14792 - Updating autoresponder styling
https://mattermost.atlassian.net/browse/MM-14792
=> MM-14792 - Updating autoresponder styling

package-lock.json, package.json
Fixes for FF and safari jumpiness when loading more posts with https://github.com/mattermost/react-window/pull/6
[MM-14791](https://mattermost.atlassian.net/browse/MM-14791)
=> MM-14791 Fix for FF and safari jumpiness when loading more posts

sass/routes/_admin-console.scss
MM-14775 - Updating banner css in system console
https://mattermost.atlassian.net/browse/MM-14775
=> MM-14775 - Updating banner css in system console

components/emoji_picker/emoji_picker.jsx, components/emoji_picker/emoji_picker_tabs.jsx, sass/components/_emoticons.scss, sass/responsive/_mobile.scss
MM-14765 - Updating emoji picker
https://mattermost.atlassian.net/browse/MM-14765
=> MM-14765 - Updating emoji picker

components/__snapshots__/autosize_textarea.test.jsx.snap, components/autosize_textarea.jsx
MM-14692 - Updating css code for placeholder
https://mattermost.atlassian.net/browse/MM-14692
=> MM-14692 - Updating css code for placeholder

components/widgets/menu/menu_wrapper_animation.jsx, sass/layout/_headers.scss, sass/widgets/menu/_menu.scss, sass/widgets/menu/_menu_group.scss, sass/widgets/menu/_menu_item.scss, utils/utils.jsx
MM-14671 - Updating dropdown styling
https://mattermost.atlassian.net/browse/MM-14671
=> MM-14671 - Updating dropdown styling

components/backstage/components/backstage_sidebar.jsx, components/integrations/integrations.jsx
Re-enabling bot accounts UI for development towards 5.12.
=> Enabling bot accounts UI.

package-lock.json, package.json
Fixes for safari perf issues
[MM-14861](https://mattermost.atlassian.net/browse/MM-14861)
https://github.com/mattermost/react-window/pull/7
=> MM-14861 Fix safari perf issues

components/select_team/components/__snapshots__/select_team_item.test.jsx.snap, components/select_team/components/select_team_item.jsx, sass/routes/_signup.scss
MM-14797 - Updating select teams page
https://mattermost.atlassian.net/browse/MM-14797
=> MM-14797 - Updating select teams page

components/channel_header/channel_header.js, sass/layout/_headers.scss
MM-14745 - Updating header css
https://mattermost.atlassian.net/browse/MM-14745
=> MM-14745 - Updating header css

components/admin_console/__snapshots__/admin_console.test.jsx.snap, components/admin_console/admin_console.jsx, cypress/integration/system_console/demoted_user_spec.js, cypress/plugins/external_request.js, cypress/plugins/index.js
- Added e2e test for demoted user
- Added ability to call MM API from within tests as an external user
- Added ID to system console wrapper
[JIRA TICKET](https://mattermost.atlassian.net/browse/MM-14734)
=> [MM-14734] Added demoted user test. Added functionality to call api.

components/single_image_view/__snapshots__/single_image_view.test.jsx.snap, components/single_image_view/single_image_view.jsx, sass/components/_files.scss
MM-14829 - Updating inline images
https://mattermost.atlassian.net/browse/MM-14829
=> MM-14829 - Updating inline images

components/widgets/menu/menu_items/menu_item_action.jsx, components/widgets/menu/menu_items/menu_item_action.test.jsx, sass/widgets/menu/_menu_item.scss
MM-14875 - Updating menu item with help text (DND)
https://mattermost.atlassian.net/browse/MM-14875
=> MM-14875 - Updating menu item with help text (DND)

components/file_upload/__snapshots__/file_upload.test.jsx.snap, components/file_upload/file_upload.jsx
This solve a problem where if I have only 1 plugin that upload files is not shown the menu
This was changed in this commit bc37cfe38fb29770987e78d8aafe87b40b5da135
=> Fixing case where I have only 1 upload plugin

components/widgets/menu/menu.jsx, components/widgets/menu/menu.test.jsx, components/widgets/menu/menu_wrapper_animation.jsx, sass/responsive/_mobile.scss
MM-14787 - Updating dropdown menu on mobile
https://mattermost.atlassian.net/browse/MM-14787
=> MM-14787 - Updating dropdown menu on mobile

components/team_sidebar/team_sidebar_controller.jsx, sass/layout/_team-sidebar.scss, utils/utils.jsx
MM-12949 - Updating team sidebar and plugins
https://mattermost.atlassian.net/browse/MM-12949
=> MM-12949 - Updating team sidebar and plugins

sass/layout/_sidebar-menu.scss
MM-14888 - Updating sidebar menu
https://mattermost.atlassian.net/browse/MM-14888
=> MM-14888 - Updating sidebar menu

components/team_sidebar/team_sidebar_controller.jsx, sass/layout/_team-sidebar.scss, utils/utils.jsx
This reverts #2590 . It was breaking the team sidebar on desktop app.
=> Revert "MM-12949 - Updating team sidebar and plugins (#2590)"

components/admin_console/server_logs/log_list.jsx
Not sure what changed that prevented this from getting focused on mount, couldn't find anything obvious in the commit history, but this will fix it.
Also did a bit of minor clean-up.
https://mattermost.atlassian.net/browse/MM-14932
=> MM-14932 Focus logs list on mount

components/channel_header_dropdown/channel_header_dropdown_items.js
Restoring view members in default channels and archived channels
[MM-15061](https://mattermost.atlassian.net/browse/MM-15061)
=> MM-15061: Restoring view members in default channels and archived channels

sass/routes/_signup.scss
MM-14978 - Updating login page for fixed banner
https://mattermost.atlassian.net/browse/MM-14978
**Before:**
**After:**
=> MM-14978 - Updating login page for fixed banner

sass/widgets/menu/_menu_item.scss, utils/utils.jsx
MM-15053 - Updating menu bg
https://mattermost.atlassian.net/browse/MM-15053
=> MM-15053 - Updating menu styling

sass/widgets/menu/_menu_item.scss
MM-14875 - Fixing line height for menu items
https://mattermost.atlassian.net/browse/MM-14875
=> MM-14875 - Fixing line height for menu items

components/user_settings/security/user_settings_security.jsx
MM-14713 - Updating help text security panel
https://mattermost.atlassian.net/browse/MM-14713
=> MM-14713 - Updating help text security panel

components/emoji_picker/emoji_picker_tabs.jsx, sass/responsive/_mobile.scss
MM-15107 - Updating emoji picker on mobile
https://mattermost.atlassian.net/browse/MM-15107
=> MM-15107 - Updating emoji picker on mobile

sass/routes/_backstage.scss
MM-14974 - Updating bot image css
https://mattermost.atlassian.net/browse/MM-14974
**Looks fine now.**
=> MM-14974 - Updating bot image css

components/login/login_controller/login_controller.jsx
Removing unneded default channel property
=> Removing unneded default channel property

components/post_view/post_list.jsx, sass/layout/_post.scss
https://mattermost.atlassian.net/browse/MM-15082
MM-15082 - Updating post list spacing
=> MM-15082 - Updating post list spacing

components/admin_console/group_settings/__snapshots__/group_row.test.jsx.snap, components/admin_console/group_settings/group_row.jsx
Fixes license check for `/permissions/system-scheme` url and url inconsistencies related to the group links in system console.
https://mattermost.atlassian.net/browse/MM-15170
=> [MM-15170] Fix admin console urls and system-scheme permission

sass/responsive/_tablet.scss
MM-15019 - Updating post spacing in compact view
https://mattermost.atlassian.net/browse/MM-15019
=> MM-15019 - Updating post spacing in compact view

sass/layout/_post.scss, sass/responsive/_mobile.scss
MM-14872 - Updaitng autocomplete positioning
https://mattermost.atlassian.net/browse/MM-14872
=> MM-14872 - Updating autocomplete positioning

components/widgets/menu/menu_wrapper_animation.jsx
MM-15125 - Updating wrapper animation on mobile
https://mattermost.atlassian.net/browse/MM-15125
=> MM-15125 - Updating wrapper animation on mobile

sass/layout/_post.scss
MM-14714 - Updating textarea preview
https://mattermost.atlassian.net/browse/MM-14714
=> MM-14714 - Updating textarea preview

sass/components/_files.scss
MM-15175 - Updating border-radius for images
https://mattermost.atlassian.net/browse/MM-15175
=> MM-15175 - Updating border-radius for images

sass/components/_files.scss
MM-15177 - Updating image shadow
https://mattermost.atlassian.net/browse/MM-15177
=> MM-15177 - Updating image shadow

sass/components/_badge.scss
MM-14951 - Updating badge line-height
https://mattermost.atlassian.net/browse/MM-14951
=> MM-14951 - Updating badge line-height

components/team_members_dropdown/__snapshots__/team_members_dropdown.test.jsx.snap, components/team_members_dropdown/team_members_dropdown.jsx, components/team_members_dropdown/team_members_dropdown.test.jsx, cypress/integration/channel/header_spec.js, cypress/integration/channel/message_spec.js, cypress/integration/system_console/demoted_user_spec.js, cypress/integration/team/teams_spec.js, cypress/support/ui_commands.js
Quick fix on flaky E2E specs
none
=> Quick fix on flaky E2E specs

cypress/integration/at_mentions/at_mentions_spec.js
Added e2e Cypress test for not receiving @channel, @all, and @here at-mentions
[JIRA Ticket](https://mattermost.atlassian.net/browse/MM-14572)
[GitHub Issue](https://github.com/mattermost/mattermost-server/issues/10440)
N/A
=> MM-14572 Add e2e test for @channel, @all, and @here at-mentions

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/channel_header/channel_header.js, sass/components/_admin-sidebar-header.scss
MM-15236 - Updating dropdown icon label
https://mattermost.atlassian.net/browse/MM-15236
=> MM-15236 - Updating dropdown icon label

components/user_settings/modal/user_settings_modal.jsx
Updates refs in UserSettingsModal.
https://mattermost.atlassian.net/browse/MM-15283
=> [MM-15283] Updates refs in UserSettingsModal

components/admin_console/index.js
This prop appears to have been inadvertently removed in https://github.com/mattermost/mattermost-webapp/pull/2588.
https://mattermost.atlassian.net/browse/MM-15214
=> MM-15214: fix a regression re: env overrides

components/announcement_bar/__snapshots__/announcement_bar.test.jsx.snap, components/announcement_bar/announcement_bar.jsx, sass/components/_announcement-bar.scss, sass/components/_tooltip.scss
Mm 12902 - Updating announcement banner (making it fixed at the top)
https://mattermost.atlassian.net/browse/MM-12902
=> MM-12902 - Updating announcement banner (making it fixed at the top)

components/admin_console/admin_definition.jsx, i18n/en.json
Updates help text description.
https://mattermost.atlassian.net/browse/MM-15360
=> MM-15360: Updates help text description.

package-lock.json, package.json
Fixes https://mattermost.atlassian.net/browse/MM-15257
with https://github.com/mattermost/react-window/pull/10
=> MM-15257 Changing channels which have more than 150 posts in store causes older posts not to load in view.

components/emoji_picker/emoji_picker.jsx, cypress/integration/emoji/recently_used_emoji_spec.js
Add E2E test for recently used emoji
[10246](https://github.com/mattermost/mattermost-server/issues/10246)
=> [MM-14014] UI Automation: Write an automated test using Cypress for "Recently used emojis are shown 1st"

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx
The previous version of that code was passing data in an incorrect format, but even if it was working correctly, it wasn't calling the required actions. I just changed it to use `batchActions` since newly received posts are treated a bit differently than other posts that are received together.
https://mattermost.atlassian.net/browse/MM-15318
=> MM-15318 Fix batching of newly received posts

components/emoji_picker/components/emoji_picker_item.jsx, components/post_view/reaction/__snapshots__/reaction.test.jsx.snap, components/post_view/reaction/reaction.jsx, components/post_view/reaction_list/__snapshots__/reactions_list.test.jsx.snap, components/post_view/reaction_list/reaction_list.jsx, cypress/integration/channel/message_reaction_spec.js
Adds e2e to check for emoji reaction added (#10612)
Fixes https://github.com/mattermost/mattermost-server/issues/10612
=> MM-15113 Adds e2e to check for emoji reaction added (#10612)

utils/admin_console_index.jsx
See https://community.mattermost.com/core/pl/5igf5pyeptgfdeqm954un9j8hc for context.
https://mattermost.atlassian.net/browse/MM-15525
=> MM-15525 Use ES5 transpiled flexsearch to fix IE11

actions/views/channel.js, components/needs_team/needs_team.test.jsx, components/permalink_view/__snapshots__/permalink_view.test.jsx.snap, components/post_view/channel_intro_message/index.js, components/post_view/index.js, components/post_view/new_messages_below/index.js, components/post_view/post_list_ie/index.js, components/post_view/post_list_ie/post_list_ie.jsx, components/post_view/post_list_row/__snapshots__/post_list_row.test.jsx.snap, components/post_view/post_list_row/index.js, components/post_view/post_list_row/post_list_row.jsx, components/post_view/post_list_virtualized/index.js, components/post_view/post_list_virtualized/post_list_virtualized.jsx, components/post_view/post_list_virtualized/post_list_virtualized.test.jsx, components/post_view/reaction_list/index.js, components/post_view/reaction_list/reaction_list.jsx, components/post_view/reaction_list/reactions_list.test.jsx, components/root/root.test.jsx, components/sidebar_right/index.js, components/sidebar_right/sidebar_right.jsx, components/textbox.test.jsx, components/textbox/index.js, components/textbox/textbox.jsx, i18n/en.json, sass/layout/_post.scss, utils/constants.jsx, utils/utils.jsx
Reverts mattermost/mattermost-webapp#2774 and fixes https://mattermost.atlassian.net/browse/MM-15516
=> Revert "Revert "MM-14975 remove virt_list for IE11 (#2747)""

sass/responsive/_mobile.scss
MM-15534 - Updating sidebar css on mobile
https://mattermost.atlassian.net/browse/MM-15534
=> MM-15534 - Updating sidebar css on mobile

components/youtube_video/index.js, components/youtube_video/youtube_video.jsx, components/youtube_video/youtube_video.test.jsx
https://mattermost.atlassian.net/browse/MM-15499
=> MM-15499 Load YouTube thumbnail through image proxy

components/textbox/textbox.jsx, sass/layout/_post.scss
MM-15273 - Updating textbox preview styling
https://mattermost.atlassian.net/browse/MM-15273
=> MM-15273 - Updating textbox preview styling

components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.jsx.snap, components/post_view/post_add_channel_member/post_add_channel_member.jsx, i18n/en.json
Updates out-of-group at-mention ephemeral message text.
https://mattermost.atlassian.net/browse/MM-15485
=> MM-15485: Updates out-of-group at-mention message.

components/main_menu/index.jsx, components/main_menu/main_menu.jsx, plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Hides 'Leave Team' menu in a group-constrained team.
https://mattermost.atlassian.net/browse/MM-15578
=> MM-15578: Hides 'Leave Team' menu in a group-constrained team.

sass/layout/_headers.scss
MM-15680 - Updating channel header icon styling
https://mattermost.atlassian.net/browse/MM-15680
=> MM-15680 - Updating channel header icon styling

package-lock.json, package.json
* update react-window hash
https://mattermost.atlassian.net/browse/MM-15681
=> MM-15681 Fix for scroll position when initRangeRender is smaller than number of posts

sass/layout/_post-right.scss
MM-15517 - Updating post spacing in the RHS
https://mattermost.atlassian.net/browse/MM-15517
=> MM-15517 - Updating post spacing in the RHS

components/search_results/search_results.jsx, cypress/integration/search/post_search_display.js
Added e2e test to validate search option display after clearing search query
Fixes https://github.com/mattermost/mattermost-server/issues/10308
=> [MM-14252] After clearing search query, search options display #10308

utils/post_utils.jsx, utils/post_utils.test.jsx
* Exclude MANUAL_TRIGGER_LOAD_MESSAGES from getLastPostId
https://mattermost.atlassian.net/browse/MM-15700
=> MM-15700 Manual load more trigger in virt list does not load more messages

sass/layout/_post.scss
This will fix new lines not showing up in the markdown preview as well as the spacing being different from posts.
https://mattermost.atlassian.net/browse/MM-15377
=> MM-15377 Match spacing and new lines of posts to markdown preview

components/channel_groups_manage_modal/channel_groups_manage_modal.jsx, components/team_groups_manage_modal/team_groups_manage_modal.jsx, i18n/en.json
Updates button text.
https://mattermost.atlassian.net/browse/MM-15746
=> MM-15746: Updates button text.

components/admin_console/group_settings/groups_list/groups_list.jsx
Resets the "current page" after searching or clearing the search.
https://mattermost.atlassian.net/browse/MM-15660
=> MM-15660: Resets the current page upon some user inputs.

components/add_groups_to_channel_modal/add_groups_to_channel_modal.jsx, components/add_groups_to_team_modal/add_groups_to_team_modal.jsx, components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap, components/admin_console/group_settings/group_details/group_details.jsx, components/channel_selector_modal/__snapshots__/channel_selector_modal.test.jsx.snap, components/channel_selector_modal/channel_selector_modal.jsx, components/channel_selector_modal/channel_selector_modal.test.jsx, components/channel_selector_modal/index.js, components/team_selector_modal/team_selector_modal.jsx
Fixes for channel, team, and group selector modals.
This change will begin displaying `Town Square` and `Off-Topic` in the channel list modal, but that change has had PM approval (by @wiersgallak).
https://mattermost.atlassian.net/browse/MM-15422
* https://github.com/mattermost/mattermost-redux/pull/837
=> MM-15422: Fixes for channel, team, and group selector modals.

sass/layout/_webhooks.scss, sass/responsive/_mobile.scss
MM-15696 - Updating plugin buttons
https://mattermost.atlassian.net/browse/MM-15696
=> MM-15696 - Updating plugin buttons

components/post_view/channel_intro_message/channel_intro_message.jsx
Fixing help button on edit channel modal when it is open from the welcome message.
[MM-15675](https://mattermost.atlassian.net/browse/MM-15675)
=> MM-15675: Fixing help button on edit channel modal

package-lock.json, package.json
Summary at react window PR
https://mattermost.atlassian.net/browse/MM-15681
https://github.com/mattermost/react-window/pull/14
=> MM-15733 Scroll position is not at `new message` indicator on a recurring visit to a channel

package-lock.json, package.json
update mattermost-redux ref with mattermost/mattermost-redux#839
=> MM-15667 if post was removed exclude it from postsInChannel

components/rhs_comment/rhs_comment.jsx
Render RHS dots menu only on hover or when is open
=> Render RHS dots menu only on hover or when is open

components/team_members_dropdown/index.js, components/team_members_dropdown/team_members_dropdown.jsx, components/team_members_dropdown/team_members_dropdown.test.jsx
Get the fresh member data after update a member in the manage members modal.
[MM-15676](https://mattermost.atlassian.net/browse/MM-15676)
=> MM-14676: Fix member roles changes on team manage members modal

components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap, components/admin_console/admin_sidebar_header/admin_sidebar_header.jsx, sass/routes/_admin-console.scss
MM-15724 - Updating system console spacing and UI
https://mattermost.atlassian.net/browse/MM-15724
=> MM-15724 - Updating system console spacing and UI

components/access_history_modal/__snapshots__/access_history_modal.test.jsx.snap, components/access_history_modal/access_history_modal.jsx, components/activity_log_modal/__snapshots__/activity_log_modal.test.jsx.snap, components/activity_log_modal/activity_log_modal.jsx, components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap, components/more_direct_channels/more_direct_channels.jsx, i18n/en.json, sass/components/_modal.scss
MM-10072 - Updating list modals for accessibility
This adds a hidden button to the end of certain modals to indicate that the modal has ended.
https://mattermost.atlassian.net/browse/MM-10072
=> MM-10072 - Updating list modals for accessibility

components/sidebar/channel_create.jsx, cypress/integration/search/search_user_post.js, cypress/support/ui_commands.js
Added e2e test to validate search result in search box with query "in:[username] search-word" 
Fixes  https://github.com/mattermost/mattermost-server/issues/10481
=> S14672 Search "in:[username]" returns results in DMs

sass/components/_modal.scss
MM-15764 - Updating styling for names in modal
https://mattermost.atlassian.net/browse/MM-15764
=> MM-15764 - Updating styling for names in modal

components/login/login_controller/login_controller.jsx, components/password_reset_form/password_reset_form.jsx, components/password_reset_send_link.jsx, cypress/integration/email/mention_email_notification_spec.js, cypress/integration/signin_authentication/forgot_password_spec.js, cypress/support/api_commands.js, cypress/utils/index.js
Add E2E for "Test forgot password for email with valid account on server".
~~Will assign reviewer once these PRs are merged: https://github.com/mattermost/mattermost-webapp/pull/2840 and https://github.com/mattermost/mattermost-webapp/pull/2833~~
GH Issue: https://github.com/mattermost/mattermost-server/issues/10572
Jira ticket: [MM-15008](https://mattermost.atlassian.net/browse/MM-15008)
=> MM-15008 E2E: Test forgot password for email with valid account on server

sass/components/_status-icon.scss, sass/layout/_sidebar-left.scss
MM-15737 - Updating sidebar icons for GM and Private
https://mattermost.atlassian.net/browse/MM-15737
=> MM-15737 - Updating sidebar icons for GM and Private

sass/layout/_post.scss
MM-15920 - Updating compact view header
https://mattermost.atlassian.net/browse/MM-15920
=> MM-15920 - Updating compact view header

package-lock.json, package.json
=> MM-15904 Only set Client user and roles if user is defined

components/channel_view/channel_view.jsx, sass/components/_emoticons.scss
MM-15551 - Updating emoji styling
https://mattermost.atlassian.net/browse/MM-15551
=> MM-15551 - Updating emoji styling

components/channel_selector_modal/channel_selector_modal.jsx, components/multiselect/multiselect.jsx, components/team_selector_modal/team_selector_modal.jsx
Resets current page to 0 upon search input.
https://mattermost.atlassian.net/browse/MM-16000
=> MM-16000: Resets current page to 0 upon search input.

components/post_view/post_list_virtualized/post_list_virtualized.jsx, components/post_view/post_list_virtualized/post_list_virtualized.test.jsx, package-lock.json, package.json
virt list now passes the required values for determining is atBottom so instead of requesting values from DOM causing a layout trash we use the values from callback
https://mattermost.atlassian.net/browse/MM-14861
https://github.com/mattermost/react-window/pull/16
=> MM-14861 Perf improvement for onScroll event

components/channel_selector_modal/channel_selector_modal.test.jsx, components/integrations/bots/bots.test.jsx, components/list_modal.jsx, components/permalink_view/permalink_view.test.jsx
Fix errors and warnings when running unit tests
Jira ticket: [MM-16016](https://mattermost.atlassian.net/browse/MM-16016)
=> [MM-16016] Fix errors and warnings when running unit tests

sass/base/_structure.scss
MM-15935 - Updating scrolling issue IOS browser
https://mattermost.atlassian.net/browse/MM-15935
=> MM-15935 - Updating scrolling issue IOS browser

components/post_emoji/index.jsx, components/post_emoji/post_emoji.jsx, components/post_emoji/post_emoji.test.jsx, utils/message_html_to_component.jsx
This field is no longer being populated since we're getting all custom emojis in the post from the post metadata.
https://mattermost.atlassian.net/browse/MM-16045
=> MM-16045 Stop using nonExistentEmoji on web app

components/channel_header/channel_header.js, components/channel_header/channel_header.test.jsx, components/channel_header/index.js, components/profile_popover/index.js, components/profile_popover/profile_popover.jsx, components/profile_popover/profile_popover.test.jsx
Server PR: https://github.com/mattermost/mattermost-server/pull/11066
See server PR description for further details.
https://mattermost.atlassian.net/browse/MM-16001
=> MM-16001 Have client use new bot_description field.

components/channel_invite_modal/channel_invite_modal.jsx, components/channel_invite_modal/channel_invite_modal.test.jsx, components/channel_invite_modal/index.js
https://mattermost.atlassian.net/browse/MM-16062
=> [MM-16062] Replace searchUsers function for searchProfiles in mattermost-redux

components/admin_console/admin_definition.jsx, i18n/en.json
Updates title of 'Compliance Monitoring' from the outdated 'Audits' title.
https://mattermost.atlassian.net/browse/MM-16072
=> Update title of ‘Compliance Monitoring’ page

components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap, i18n/en.json
Relabel plugins as "Beta" in the System Console sidebar
https://mattermost.atlassian.net/browse/MM-16144
=> MM-16144 Relabel plugins as "Beta" in the System Console sidebar

utils/admin_console_index.jsx
Add new ‘plugins’ section to admin search (highlight) index
https://mattermost.atlassian.net/browse/MM-16052
=> [MM-16052] System Console > Search doesn't return results for "Plugins"

sass/responsive/_mobile.scss
MM-16121 - Updating custom textarea on mobile
https://mattermost.atlassian.net/browse/MM-16121
=> MM-16121 - Updating custom textarea on mobile

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, components/admin_console/audits/audits.jsx, components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap, components/admin_console/schema_admin_settings.jsx, i18n/en.json
Fix layout of hybrid schema and component page so that the compliance reports and user activity sections are visible.
https://mattermost.atlassian.net/browse/MM-16089
System console layout was changed with this PR: https://github.com/mattermost/mattermost-webapp/pull/2761
=> [MM-16089] Compliance reports job table missing

package-lock.json, package.json
https://mattermost.atlassian.net/browse/MM-16280
- Has redux changes (https://github.com/mattermost/mattermost-redux/pull/851)
=> MM-16280 Fix when post fail to send

components/popover_list_members/popover_list_members_item.jsx, sass/components/_mentions.scss, sass/components/_modal.scss, sass/components/_popover.scss, sass/components/_status-icon.scss
MM-16151 - Updating user info with bot tags
https://mattermost.atlassian.net/browse/MM-16151
=> MM-16151 - Updating user info with bot tags

plugins/index.js, reducers/plugins/index.js
- fixes an obscure bug for plugins. Don't modify the existing array, redux gets angry.
[MM-15790](https://mattermost.atlassian.net/browse/MM-15790)
=> [MM-15790] fixing an obscure bug for plugins - copy the array before modifying it

components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/rhs_root_post.jsx
These components still used `shouldComponentUpdate` which hadn't been updated with more recently added props include the post type plugins
https://mattermost.atlassian.net/browse/MM-16247
https://mattermost.atlassian.net/browse/MM-16279
=> MM-16247/MM-16279 Re-render RHS when post type components change

components/root/root.jsx, sass/components/_dropdown.scss, sass/components/_links.scss, sass/components/_search.scss, sass/layout/_headers.scss, sass/layout/_post.scss, sass/layout/_sidebar-left.scss, sass/layout/_sidebar-right.scss, sass/utils/_modifiers.scss, sass/widgets/menu/_menu_wrapper.scss, utils/utils.jsx
MM-16142 - Creating visual display of focus
https://mattermost.atlassian.net/browse/MM-16142
This should also fix:
https://mattermost.atlassian.net/browse/MM-16051
=> MM-16142 - Creating visual display of focus

package-lock.json, package.json
Pr to update mattermost-redux ref
=> Fix channel sorting when display name is not set

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/channel_header/channel_header.js
MM-15982 - Updating favourites label
https://mattermost.atlassian.net/browse/MM-15987
=> MM-15982 - Updating favourites label

components/post_view/channel_intro_message/channel_intro_message.jsx
Fixing i18n in release-5.13 branch
=> Fixing i18n in release-5.13 branch

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/channel_header/channel_header.js, components/channel_header_dropdown/channel_header_dropdown.js, sass/layout/_headers.scss
MM-15988 - Making channel menu accessible
https://mattermost.atlassian.net/browse/MM-15988
=> MM-15988 - Making channel menu accessible

sass/responsive/_mobile.scss
MM-16299 - Updating menu divider css on mobile
https://mattermost.atlassian.net/browse/MM-16299
=> MM-16299 - Updating menu divider css on mobile

components/admin_console/admin_definition.jsx, components/admin_console/elasticsearch_settings.jsx, i18n/en.json
https://mattermost.atlassian.net/browse/MM-16244
- [Has server changes](https://github.com/mattermost/mattermost-server/pull/11189)
- [Has enterprise changes](https://github.com/mattermost/enterprise/pull/458)
=> [MM-16244] Add Elasticsearch SkipTLSVerification to the admin console

package-lock.json, package.json
Updating react window hash
https://mattermost.atlassian.net/browse/MM-16381
https://github.com/mattermost/react-window/pull/19
=> MM-16381 Fix for Channel intro content sometimes disappears on opening a channel

actions/views/channel.test.js, package-lock.json, package.json
https://mattermost.atlassian.net/browse/MM-16480
- Has redux changes (https://github.com/mattermost/mattermost-redux/pull/862)
- Has mobile changes (https://github.com/mattermost/mattermost-mobile/pull/2917)
=> MM-16480 Update mattermost-redux

components/admin_console/admin_sidebar_header/admin_sidebar_header.jsx, components/suggestion/search_channel_provider.jsx, sass/components/_popover.scss
MM-16527 - Updating bot label in search
https://mattermost.atlassian.net/browse/MM-16527
=> MM-16527 - Updating bot label in search

cypress.json, cypress/integration/channel/header_spec.js, cypress/integration/channel/system_message_spec.js, cypress/integration/login/login_spec.js, cypress/integration/login/signup_spec.js, cypress/integration/team/teams_spec.js, cypress/support/api_commands.js, cypress/support/index.js, package-lock.json, package.json
Fix failing E2E specs and add capability to retry twice
none
=> Fix failing E2E specs and add capability to retry twice

sass/responsive/_tablet.scss
MM-16259 - Fixing RHS overlap on tablets
https://mattermost.atlassian.net/browse/MM-16259
=> MM-16259 - Fixing RHS overlap on tablets

sass/layout/_post.scss
MM-15551 - Updating emoji styling on windows
https://mattermost.atlassian.net/browse/MM-15551
=> MM-15551 - Updating emoji styling on windows

sass/routes/_admin-console.scss
MM-16552 - Updating system console height
https://mattermost.atlassian.net/browse/MM-16552
=> MM-16552 - Updating system console height

components/post_view/post_header/post_header.jsx, components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/rhs_root_post.jsx, components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/search_results_item.jsx, components/user_profile/__snapshots__/user_profile.test.jsx.snap, components/user_profile/user_profile.jsx, components/widgets/badges/badge.scss, sass/components/_mentions.scss, sass/components/_popover.scss, sass/layout/_post.scss
MM-16538 - Updating bot label styling
https://mattermost.atlassian.net/browse/MM-16538
=> MM-16538 - Updating bot label styling

sass/components/_sidebar-header.scss, sass/layout/_headers.scss, sass/layout/_sidebar-left.scss
MM-16555 - Fixing status icon and status dropdown
https://mattermost.atlassian.net/browse/MM-16555
=> MM-16555 - Fixing status icon and status dropdown

package-lock.json, package.json
Update cypress to 3.3.2 (tons of performance fixes)
N/A
=> Update cypress to 3.3.2

cypress.json, cypress/integration/email/mention_email_notification_spec.js, cypress/integration/signin_authentication/forgot_password_spec.js, cypress/plugins/get_recent_email.js, cypress/support/api_commands.js, cypress/utils/index.js
Fix test for email notification
Related PRs were submitted to shared pipelines where inbucket is deployed to test server
=> E2E: Fix test for email notification

components/search_bar/search_bar.jsx
MM-15992 - Updating search bar description
https://mattermost.atlassian.net/browse/MM-15992
=> MM-15992 - Updating search bar description

components/invite_member_modal/index.js, components/invite_member_modal/invite_member_modal.jsx
https://mattermost.atlassian.net/browse/MM-15661
- [Has server changes](https://github.com/mattermost/mattermost-server/pull/11478)
=> [MM-15661] Remove the SendEmailNotification check from the invite modal

components/__snapshots__/setting_item_min.test.jsx.snap, components/setting_item_min.jsx, components/settings_sidebar.jsx, components/user_settings/modal/user_settings_modal.jsx
Fixes MM-16039 by adding ARIA tags to the required elements
Fixes https://mattermost.atlassian.net/browse/MM-16039
=> [MM-16039] Fixed accessibility issues with the Account Settings modal

e2e/cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js, e2e/cypress/integration/channel/channel_settings_spec.js, e2e/cypress/integration/channel/header_spec.js, e2e/cypress/integration/channel/message_edit_post_with_attachment_spec.js, e2e/cypress/integration/markdown/markdown_image_spec.js, e2e/cypress/integration/search/date_filter_spec.js, e2e/cypress/support/api_commands.js, e2e/cypress/support/ui_commands.js
=> E2E: fix failing tests

e2e/cypress/integration/messaging/emoji_size_spec.js
This PR increase test coverage for the scenario described inside Jira ticket
https://mattermost.atlassian.net/browse/MM-15012
Fixes https://github.com/mattermost/mattermost-server/issues/10576
=> Increasing test coverage for MM-15012

e2e/cypress/integration/channel/message_spec.js, e2e/cypress/integration/team/teams_spec.js
Fix messaging and team flaky specs
none
=> E2E: Fix messaging and team flaky specs

components/size_aware_image.jsx, components/size_aware_image.test.jsx
MM-16906 - Updating class for size aware images
https://mattermost.atlassian.net/browse/MM-16906
=> MM-16906 - Updating class for size aware images

components/channel_notifications_modal/components/__snapshots__/expand_view.test.jsx.snap, components/channel_notifications_modal/components/expand_view.jsx, components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap, components/new_channel_modal/new_channel_modal.jsx, components/team_general_tab/team_general_tab.jsx, components/user_settings/advanced/join_leave_section/__snapshots__/join_leave_section.test.jsx.snap, components/user_settings/advanced/join_leave_section/join_leave_section.jsx, components/user_settings/advanced/user_settings_advanced.jsx, components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap, components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap, components/user_settings/notifications/desktop_notification_settings.jsx, components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap, components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx, components/user_settings/notifications/manage_auto_responder.jsx, components/user_settings/notifications/user_settings_notifications.jsx, components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap, components/user_settings/sidebar/user_settings_sidebar.jsx, sass/layout/_forms.scss
MM-16044 - Updating radio buttons (a11y)
https://mattermost.atlassian.net/browse/MM-16044
=> MM-16044 - Updating radio buttons (a11y)

components/channel_selector_modal/channel_selector_modal.test.jsx, components/post_view/channel_intro_message/channel_intro_message.jsx, components/post_view/post_list/post_list.test.jsx
- Fix unit test - those with `UnhandledPromiseRejectionWarning`
- Fix JS warning in console
=> Fix unit test and browser JS warning

components/channel_header_dropdown/index.js
Fixing broken permalinks when access directly to the app
[MM-16987](https://mattermost.atlassian.net/browse/MM-16987)
=> Fixing broken permalinks when access directly to the app

e2e/cypress/integration/search/date_filter_spec.js
- Start cypress server and listen for the search requests.
- In tests, wait for search request to complete before continuing.
N/A
=> Listen to route to fix search date filter e2e tests

components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap, components/invitation_modal/invitation_modal_members_step.jsx, components/invitation_modal/invitation_modal_members_step.scss, components/svg/link_icon.jsx, i18n/en.json
Adding the proper link icon in the copy link button
=> Adding the proper link icon in the copy link button

components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap, components/invitation_modal/__snapshots__/invitation_modal_confirm_step.test.jsx.snap, components/invitation_modal/invitation_modal.jsx, components/invitation_modal/invitation_modal_confirm_step.jsx, components/invitation_modal/invitation_modal_guests_step.jsx
Allow to go back from confirmation screen
=> Allow to go back from confirmation screen

components/widgets/inputs/channels_input.jsx, components/widgets/inputs/users_emails_input.jsx
Adding loading spinner to inputs in the invitation flow
=> Adding loading spinner to inputs

components/invitation_modal/__snapshots__/invitation_modal_guests_step.test.jsx.snap, components/invitation_modal/invitation_modal_guests_step.jsx, i18n/en.json
Fixing help text of guest invitation users/emails input
=> Fixing help text of guest invitation users/emails input

components/invitation_modal/invitation_modal.jsx, components/invitation_modal/invitation_modal_guests_step.jsx, components/invitation_modal/invitation_modal_members_step.jsx
Fix confirm back/close behavior in the invitation flow modal
Based on the comments from QA in the PR mattermost/mattermost-server#11428
=> Fix confirm back/close behavior in the invitation flow modal

components/get_link_modal.jsx, components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap, components/invitation_modal/invitation_modal_members_step.jsx
Fixing copy button on invitation flow
=> Fixing copy button on invitation flow

components/post_view/post_list/__snapshots__/post_list.test.jsx.snap, components/post_view/post_list/post_list.jsx
Update a ID for virtualized post list content to not collide with one we use for cypress e2e testinge.
N/A
=> E2E: Update post list content ID

components/__snapshots__/textbox.test.jsx.snap, components/suggestion/search_suggestion_list.jsx, components/suggestion/suggestion_list.jsx, components/textbox/textbox.jsx
MM-16058 - Making message autocomplete a11y compatible
https://mattermost.atlassian.net/browse/MM-16058
=> MM-16058 - Making message autocomplete a11y compatible

components/invite_member_modal/invite_member_modal.jsx
MM-16059 - Updating invite member modal
https://mattermost.atlassian.net/browse/MM-16059
=> MM-16059 - Updating invite member modal

components/setting_item_max.jsx, components/setting_item_max.test.jsx, components/user_settings/display/manage_languages/manage_languages.jsx
MM-16133 - Updating form submission for select
https://mattermost.atlassian.net/browse/MM-16133
=> MM-16133 - Updating form submission for select

package-lock.json, package.json
Extension of https://github.com/mattermost/mattermost-webapp/pull/3051.
Needed to update the compiled code on the repository in order for the new feature to work.
https://mattermost.atlassian.net/browse/MM-16039
=> [MM-16039] Updated react-bootstrap commit

components/emoji_picker/emoji_picker_tabs.jsx, components/widgets/menu/menu.jsx, components/widgets/menu/menu.test.jsx, components/widgets/menu/menu_wrapper.jsx, package-lock.json, package.json
MM-16941 - Adding focus-trap to elements
https://mattermost.atlassian.net/browse/MM-16941
=> MM-16941 - Adding focus-trap to elements

components/widgets/menu/menu.jsx, components/widgets/menu/menu.test.jsx
Removing focus trap on menu item click
Related to: https://mattermost.atlassian.net/browse/MM-16941
=> Removing focus trap on menu item click

components/post_view/index.js, components/post_view/post_list/post_list.jsx, components/post_view/post_list/post_list.test.jsx, components/post_view/post_list/post_list_virtualized.jsx
Reverts mattermost/mattermost-webapp#3106.
We are not requesting for team ID in permalink view which causes issue with this
=> Revert "MM-16989 Fix for leave team causing a white screen"

package-lock.json, package.json
Updating hash for react window
https://mattermost.atlassian.net/browse/MM-16952
https://github.com/mattermost/react-window/pull/21
=> MM-16952 Fix for new message bubble popping up even when at bottom

actions/invite_actions.jsx, components/post_view/channel_intro_message/channel_intro_message.jsx
Fixing email invitations when the email invitation is disabled in the settings.
Now just fail.
=> Fixing email invitations disabled problem

components/__snapshots__/searchable_channel_list.test.jsx.snap, components/searchable_channel_list.jsx, sass/components/_modal.scss
MM-15999 - More channels dialog a11y compatible
https://mattermost.atlassian.net/browse/MM-15999
=> MM-15999 - More channels dialog a11y compatible

components/invitation_modal/invitation_modal.scss, components/invitation_modal/invitation_modal_confirm_step.scss, components/invitation_modal/invitation_modal_confirm_step_row.scss, components/invitation_modal/invitation_modal_confirm_step_table.scss, components/invitation_modal/invitation_modal_guests_step.jsx, components/invitation_modal/invitation_modal_guests_step.scss, components/invitation_modal/invitation_modal_members_step.jsx, components/invitation_modal/invitation_modal_members_step.scss, components/widgets/inputs/channels_input.scss, components/widgets/inputs/emails_input.scss, components/widgets/inputs/users_emails_input.scss, components/widgets/modals/full_screen_modal.scss
Polishing details in invitation flow styles
=> Polishing details in invitation flow styles

components/admin_console/admin_definition.jsx
Cherry pick of #3148 on release-5.13.
- #3148: MM-17008: Always displays 'Push Notification Contents' admin
/cc  @mkraft
=> Automated cherry pick of

sass/layout/_headers.scss
MM-16937 - Updating padding for channel intro
https://mattermost.atlassian.net/browse/MM-16937
**Before:**
**Now:**
=> MM-16937 - Updating padding for channel intro

sass/layout/_headers.scss
Cherry pick of #3153 on release-5.14.
- #3153: MM-16937 - Updating padding for channel intro
=> Automated cherry pick of #3153

e2e/package-lock.json, e2e/package.json
dependabot was not able to create the PR for this securoty alert.
Please review and let me know if this is correct.
=> bump lodash

components/post_view/post_message_view/__snapshots__/post_message_view.test.jsx.snap, components/post_view/post_message_view/post_message_view.jsx, plugins/test/__snapshots__/post_type.test.jsx.snap, utils/utils.jsx
MM-17047 - Making post text focusable
https://mattermost.atlassian.net/browse/MM-17047
=> MM-17047 - Making post text focusable

components/admin_console/admin_definition.jsx, i18n/en.json
Should be picked to v5.13.1 release
Discussion as per https://community-daily.mattermost.com/core/pl/mgjy1mmnbir3pfx4msashi48br
=> Update Enable Link Preview console help text

components/channel_members_dropdown/channel_members_dropdown.jsx, components/searchable_user_list/searchable_user_list.jsx
Fixed a couple screen reader issues with the Manage Members for channel modal around reading out the results and the menus associated with them.
https://mattermost.atlassian.net/browse/MM-16054
=> [MM-16054] Accessibility fixes for Manage Members for channel

components/admin_console/admin_definition.jsx, i18n/en.json
Cherry pick of #3151 on release-5.13.
- #3151: Update admin_definition.jsx
/cc  @esethna
=> Automated cherry pick of #3151

components/system_notice/notices.jsx, i18n/en.json, utils/server_version.jsx, utils/server_version.test.jsx
Cherry pick of #3129 on release-5.14.
- #3129: Added IE11 deprecation notice for v5.16
=> Automated cherry pick of #3129

components/post_view/post/post.jsx, components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/rhs_root_post.jsx, i18n/en.json, utils/post_utils.jsx, utils/post_utils.test.jsx
Cherry pick of #3090 on release-5.14.
- #3090: Added emoji support to post aria-label
=> Automated cherry pick of #3090

components/add_users_to_team/__snapshots__/add_users_to_team.test.jsx.snap, components/add_users_to_team/add_users_to_team.jsx, components/channel_invite_modal/__snapshots__/channel_invite_modal.test.jsx.snap, components/channel_invite_modal/channel_invite_modal.jsx, components/multiselect/__snapshots__/multiselect.test.jsx.snap, components/multiselect/multiselect.jsx, components/multiselect/multiselect_list.jsx
Cherry pick of #3164 on release-5.14.
- #3164: WIP
=> Automated cherry pick of #3164

components/channel_members_dropdown/channel_members_dropdown.jsx, components/searchable_user_list/searchable_user_list.jsx
Cherry pick of #3168 on release-5.14.
- #3168: Accessibility fixes for Manage Members for channel
=> Automated cherry pick of #3168

components/__snapshots__/setting_picture.test.jsx.snap, components/setting_picture.jsx, sass/routes/_settings.scss
Cherry pick of #3101 on release-5.14.
- #3101: Added aria-labels to profile picture settings
=> Automated cherry pick of #3101

components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap, components/more_direct_channels/more_direct_channels.jsx
This adds accessibility fixes for the Direct Messages modal.
https://mattermost.atlassian.net/browse/MM-16057
=> [MM-16057] Accessibility changes for Direct Messages modal

components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap, components/more_direct_channels/more_direct_channels.jsx
Cherry pick of #3176 on release-5.14.
- #3176: WIP
=> Automated cherry pick of #3176

components/dot_menu/__snapshots__/dot_menu.test.jsx.snap, components/dot_menu/dot_menu.jsx
MM-16916 - Updating dot menu tooltip trigger
https://mattermost.atlassian.net/browse/MM-16916
=> MM-16916 - Updating dot menu tooltip trigger

utils/a11y_controller.js
Cherry pick of #3169 on release-5.14.
- #3169: firefox nav fixes
=> Automated cherry pick of #3169

components/root/root.jsx
Cherry pick of #3173 on release-5.14.
- #3173: =?UTF-8?q?Don=E2=80=99t=20run=20a11y=20navigation=20in=20?=
=> Automated cherry pick of #3173

components/dot_menu/__snapshots__/dot_menu.test.jsx.snap, components/dot_menu/dot_menu.jsx
Cherry pick of #3159 on release-5.14.
- #3159: MM-16916 - Updating dot menu tooltip trigger
=> Automated cherry pick of #3159

components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx, components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx, i18n/en.json
Add invite guest permission to the admin console
=> Add invite guest permission to the admin console

sass/layout/_post.scss
MM-17014 - Updating reactions alignment
https://mattermost.atlassian.net/browse/MM-17014
**Before:**
**After:**
=> MM-17014 - Updating reactions alignment

sass/layout/_sidebar-left.scss
MM-16991 - Updating LHS category header weight
https://mattermost.atlassian.net/browse/MM-16991
=> MM-16991 - Updating LHS category header weight

components/post_view/post_message_view/__snapshots__/post_message_view.test.jsx.snap, components/post_view/post_message_view/post_message_view.jsx, plugins/test/__snapshots__/post_type.test.jsx.snap, utils/utils.jsx
Cherry pick of #3163 on release-5.14.
- #3163: MM-17047 - Making post text focusable
=> Automated cherry pick of #3163

sass/layout/_sidebar-left.scss
Cherry pick of #3155 on release-5.14.
- #3155: MM-16991 - Updating LHS category header weight
=> Automated cherry pick of #3155

components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap, components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx, sass/routes/_settings.scss
MM-17058 - Updating custom theme section css
https://mattermost.atlassian.net/browse/MM-17058
**Before:**
**Now:**
=> MM-17058 - Updating custom theme section css

i18n/en.json
Fix missing message body
N/A
N/A
=> Fix missing message

components/admin_console/admin_definition.jsx, components/admin_console/schema_admin_settings.jsx
* Associate Amazon SSE to Compliance feature flag.
* Use the `isHidden` function in admin console drop-down options.
https://mattermost.atlassian.net/browse/MM-17114
=> MM-17114: Associate Amazon SSE to Compliance feature flag and hide options.

components/integrations/__snapshots__/installed_command.test.jsx.snap, components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap, components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap, components/integrations/installed_command.jsx, components/integrations/installed_incoming_webhook.jsx, components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap, components/integrations/installed_oauth_app/installed_oauth_app.jsx, components/integrations/installed_outgoing_webhook.jsx
MM-16985 - Updating integrations UI item title
https://mattermost.atlassian.net/browse/MM-16985
=> MM-16985 - Updating integrations UI item title

components/integrations/__snapshots__/installed_command.test.jsx.snap, components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap, components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap, components/integrations/installed_command.jsx, components/integrations/installed_incoming_webhook.jsx, components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap, components/integrations/installed_oauth_app/installed_oauth_app.jsx, components/integrations/installed_outgoing_webhook.jsx
Cherry pick of #3154 on release-5.14.
- #3154: MM-16985 - Updating integrations UI item title
=> Automated cherry pick of #3154

utils/route.jsx
Do not enforce MFA for guests when the Guests specific setting is not enabled
[MM-17196](https://mattermost.atlassian.net/browse/MM-17196)
- Has server changes: mattermost/mattermost-server#11686
=> Do not enforce MFA for guests when the Guests specific setting is not enabled

sass/layout/_headers.scss
Align badges on dms and gms title
[MM-17203](https://mattermost.atlassian.net/browse/MM-17203)
=> Align badges on dms and gms title

utils/a11y_controller.js, utils/constants.jsx
Cherry pick of #3197 on release-5.14.
- #3197: tweaks
=> Automated cherry pick of #3197

components/announcement_bar/announcement_bar.jsx
Cherry pick of #3199 on release-5.13.
- #3199: MM-17115 Dismissing a banner causes banner overlap in the
=> Automated cherry pick of #3199

sass/layout/_post.scss
Cherry pick of #3223 on release-5.14.
- #3223: Fix status positions on posts in compact view
=> Automated cherry pick of #3223

components/post_view/post_time/post_time.jsx, sass/responsive/_tablet.scss
MM-17125 - Updating post permalink markup
https://mattermost.atlassian.net/browse/MM-17125
**Updated post timestamp:**
=> MM-17125 - Updating date time stamp for messages

components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.jsx.snap, components/admin_console/team_channel_settings/group/group_users_row.jsx, i18n/en.json
I18N fix
Fixes https://mattermost.atlassian.net/browse/MM-17076
=> MM-17076 - fixed i18n message

sass/components/_files.scss
MM-17225 - Fixing files truncation issue
https://mattermost.atlassian.net/browse/MM-17225
**Before:**
**After:**
=> MM-17225 - Updating files css

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, sass/layout/_markdown.scss
Cherry pick of #3212 on release-5.14.
- #3212: MM-16458 Fix for large markdown images causing a scroll
=> Automated cherry pick of #3212

sass/components/_files.scss
Cherry pick of #3231 on release-5.14.
- #3231: MM-17225 - Updating files css
=> Automated cherry pick of #3231

sass/layout/_post.scss
Cherry pick of #3202 on release-5.14.
- #3202: dom structure changed, update css to match
=> Automated cherry pick of #3202

components/post_view/post_time/post_time.jsx, sass/responsive/_tablet.scss
Cherry pick of #3209 on release-5.14.
- #3209: MM-17125 - Updating post permalink markup
=> Automated cherry pick of #3209

components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap, components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx, sass/routes/_settings.scss
Cherry pick of #3192 on release-5.14.
- #3192: MM-17058 - Updating custom theme section css
=> Automated cherry pick of #3192

sass/layout/_post.scss
Cherry pick of #3156 on release-5.14.
- #3156: MM-17014 - Updating reactions alignment
=> Automated cherry pick of #3156

components/post_view/post_list/post_list_virtualized.jsx, components/post_view/post_list/post_list_virtualized.test.jsx
Cherry pick of #3240 on release-5.14.
- #3240: MM-16908 Fix for Image attachments display loading indicator
=> Automated cherry pick of #3240

components/main_menu/__snapshots__/main_menu.test.jsx.snap, components/main_menu/main_menu.jsx, components/main_menu/main_menu.test.jsx
Fix option to leave team when primary team is set.
Test steps per Jira ticket.
(Assigning Lindy for QA Review being on platform team).
Jira ticket: [MM-17299](https://mattermost.atlassian.net/browse/MM-17299)
=> MM-17299 Fix option to leave team when primary team is set

components/main_menu/__snapshots__/main_menu.test.jsx.snap, components/main_menu/main_menu.jsx, components/main_menu/main_menu.test.jsx
Cherry pick of #3244 on release-5.14.
- #3244: fix option to leave team when primary team is set
=> Automated cherry pick of #3244

utils/utils.jsx
MM-17101 - Updating long post css
https://mattermost.atlassian.net/browse/MM-17101
=> MM-17101 - Updating long post css

sass/responsive/_mobile.scss
Cherry pick of #3245 on release-5.14.
- #3245: Fixing main menu color in mobile
/cc  @jespino
=> Automated cherry pick of #3245

utils/utils.jsx
Cherry pick of #3193 on release-5.14.
- #3193: MM-17101 - Updating long post css
=> Automated cherry pick of #3193

components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap, components/user_settings/sidebar/user_settings_sidebar.jsx, components/user_settings/sidebar/user_settings_sidebar.test.jsx
Fix for MM-16039, turns out the sidebar section of Account Settings wasn't auto focusing the first Edit button. This fixes that.
https://mattermost.atlassian.net/browse/MM-16039
=> [MM-16039] Fixed focusing on sidebar section of Account Settings

components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap, components/user_settings/sidebar/user_settings_sidebar.jsx, components/user_settings/sidebar/user_settings_sidebar.test.jsx
Cherry pick of #3201 on release-5.14.
- #3201: Fixed focusing on sidebar section of Account
=> Automated cherry pick of #3201

sass/layout/_post.scss
MM-17263 - Updating scrolling for post textarea
https://mattermost.atlassian.net/browse/MM-17263
=> MM-17263 - Updating scrolling for post textarea

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/channel_header/channel_header.js, components/sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap, components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx, sass/layout/_headers.scss
MM-17304 - Updating favourites button readout
@lindy65 This should also remove the heading level 2 readout, and also fix the double readout.
https://mattermost.atlassian.net/browse/MM-17304
=> MM-17304 - Updating favourites button and GM readout

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/channel_header/channel_header.js, components/sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap, components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx, sass/layout/_headers.scss
Cherry pick of #3255 on release-5.14.
- #3255: MM-17304 - Updating favourites button readout
=> Automated cherry pick of #3255

components/admin_console/team_channel_settings/team/details/team_modes.jsx
Fixed a crash in allowed domain input
fixes https://mattermost.atlassian.net/browse/MM-17191
=>  MM-17191 - Fixed crash in allowed domain input

components/admin_console/team_channel_settings/team/details/team_modes.jsx
Cherry pick of #3248 on release-5.14.
- #3248: fixed crash in toggle
/cc  @reflog
=> Automated cherry pick of #3248

components/widgets/menu/menu.jsx, components/widgets/menu/menu.test.jsx
Cherry pick of #3256 on release-5.14.
- #3256: MM-17324 - Updating dropdown focus trap
=> Automated cherry pick of #3256

sass/layout/_forms.scss
MM-17341 - Updating form legend css
https://mattermost.atlassian.net/browse/MM-17341
=> MM-17341 - Updating form legend css

components/create_comment/__snapshots__/create_comment.test.jsx.snap, components/create_comment/create_comment.jsx
MM-17096 - Updating RHS emoji picker button
https://mattermost.atlassian.net/browse/MM-17096
=> MM-17096 - Updating RHS emoji picker button

components/create_comment/__snapshots__/create_comment.test.jsx.snap, components/create_comment/create_comment.jsx
Cherry pick of #3254 on release-5.14.
- #3254: MM-17096 - Updating RHS emoji picker button
=> Automated cherry pick of #3254

sass/layout/_forms.scss
Cherry pick of #3271 on release-5.14.
- #3271: MM-17341 - Updating form legend css
=> Automated cherry pick of #3271

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, sass/components/_files.scss
Cherry pick of #3263 on release-5.14.
- #3263: MM-17326 Fix for svg not rendering in posts
=> Automated cherry pick of #3263

components/search_bar/__snapshots__/search_bar.test.jsx.snap, components/search_bar/search_bar.jsx, components/search_bar/search_bar.test.jsx
Cherry pick of #3237 on release-5.14.
- #3237: Not showing search options tooltip on mobile view
/cc  @jespino
=> Automated cherry pick of #3237

sass/layout/_post.scss
MM-17340 - Updating post permalink css
https://mattermost.atlassian.net/browse/MM-17340
=> MM-17340 - Updating post permalink css

components/setting_item_max.jsx, components/setting_item_max.test.jsx, components/user_settings/display/manage_languages/manage_languages.jsx, components/user_settings/display/manage_languages/manage_languages.test.js, sass/components/_module.scss, sass/components/_react-select.scss, sass/routes/_settings.scss, sass/utils/_functions.scss
MM-16133 - Updating languages dropdown to use react-select
https://mattermost.atlassian.net/browse/MM-16133
=> MM-16133 - Updating languages dropdown

sass/layout/_forms.scss
MM-17362 - Removing focus outline from inputs
https://mattermost.atlassian.net/browse/MM-17362
=> MM-17362 - Removing focus outline from inputs

components/setting_item_max.jsx, components/setting_item_max.test.jsx, components/user_settings/display/manage_languages/manage_languages.jsx, components/user_settings/display/manage_languages/manage_languages.test.js, sass/components/_module.scss, sass/components/_react-select.scss, sass/routes/_settings.scss, sass/utils/_functions.scss
Cherry pick of #3259 on release-5.14.
- #3259: MM-16133 - Updating languages dropdown
=> Automated cherry pick of #3259

components/backstage/components/backstage_category.jsx
Removes extra border on backstage settings page
Fixes https://mattermost.atlassian.net/browse/MM-17350
None
=> MM-17350 - remove extra border

sass/layout/_post.scss
Cherry pick of #3270 on release-5.14.
- #3270: MM-17340 - Updating post permalink css
=> Automated cherry pick of #3270

components/backstage/components/backstage_category.jsx
Cherry pick of #3288 on release-5.14.
- #3288: MM-17350 - remove extra border
=> Automated cherry pick of #3288

sass/components/_popover.scss
MM-17363 - Removing box shadow for selected item
https://mattermost.atlassian.net/browse/MM-17363
=> MM-17363 - Removing box shadow for selected item

components/search_results/search_results.jsx, components/search_results/search_results.test.jsx, components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/index.js, components/search_results_item/search_results_item.jsx, components/search_results_item/search_results_item.test.jsx
Cherry pick of #3252 on release-5.14.
- #3252: Reduce unnecessary rendering of search results
=> Automated cherry pick of #3252

components/admin_console/team_channel_settings/users_to_be_removed_modal.jsx
Cherry pick of #3300 on release-5.14.
- #3300: fixed dialog re-showing
/cc  @reflog
=> Automated cherry pick of #3300

components/admin_console/team_channel_settings/team/details/team_details.jsx
Cherry pick of #3304 on release-5.14.
- #3304: fixed crash in toggle
/cc  @reflog
=> Automated cherry pick of #3304

components/post_view/post_list/post_list_virtualized.jsx, components/post_view/post_list/post_list_virtualized.test.jsx
Cherry pick of #3308 on release-5.14.
- #3308: MM-17323 Fix for Posts made from RHS did not render in
=> Automated cherry pick of #3308

components/admin_console/admin_definition.jsx, i18n/en.json
Fixing typo
[MM-17210](https://mattermost.atlassian.net/browse/MM-17210)
=> Fixing typo

sass/layout/_forms.scss
Cherry pick of #3268 on release-5.14.
- #3268: MM-17362 - Removing focus outline from inputs
=> Automated cherry pick of #3268

components/multiselect/__snapshots__/multiselect.test.jsx.snap, components/multiselect/multiselect.jsx, components/multiselect/multiselect_list.jsx, sass/components/_modal.scss, sass/components/_multi-select.scss, utils/utils.jsx
Cherry pick of #3203 on release-5.14.
- #3203: Fixed a screen reader issue on multiselect
=> Automated cherry pick of #3203

sass/layout/_post.scss
Cherry pick of #3247 on release-5.14.
- #3247: MM-17263 - Updating scrolling for post textarea
=> Automated cherry pick of #3247

components/admin_console/team_channel_settings/channel/details/channel_details.jsx
Cherry pick of #3320 on release-5.14.
- #3320: check removed users on sync toggle
/cc  @reflog
=> Automated cherry pick of #3320

components/post_view/post_info/__snapshots__/post_info.test.jsx.snap, components/post_view/post_info/post_info.test.jsx, components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap, components/rhs_comment/rhs_comment.jsx, components/rhs_comment/rhs_comment.test.jsx, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/rhs_root_post.jsx, components/rhs_root_post/rhs_root_post.test.jsx, components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/search_results_item.jsx, components/search_results_item/search_results_item.test.jsx, utils/post_utils.jsx
Cherry pick of #3307 on release-5.14.
- #3307: Hide post menu for deleted posts
/cc  @jespino
=> Automated cherry pick of #3307

.circleci/config.yml
Cherry pick of #3330 on release-5.13.
- #3330: use sha1 instead of branch name
/cc  @cpanato
=> Automated cherry pick of #3330

sass/layout/_post.scss, sass/layout/_sidebar-right.scss
MM-17429 - Updating post header css
https://mattermost.atlassian.net/browse/MM-17429
=> MM-17429 - Updating post header css

sass/layout/_post.scss, sass/layout/_sidebar-right.scss
Cherry pick of #3335 on release-5.14.
- #3335: MM-17429 - Updating post header css
=> Automated cherry pick of #3335

components/sidebar/sidebar_channel/index.js, components/sidebar/sidebar_channel/sidebar_channel.jsx, components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx, components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx, package-lock.json, package.json, sass/layout/_sidebar-left.scss, utils/utils.jsx
Cherry pick of #3311 on release-5.14.
- #3311: MM-17294 - Revert "MM-15452 - Add ability to override LHS icon for bot accounts
=> MM-17294 - Revert "MM-15452 - Add ability to override LHS icon… (#3311)

components/__snapshots__/setting_picture.test.jsx.snap, components/setting_picture.jsx
This PR address navigation issues when tabbing and auto-focusing on the Profile Picture section of Account Settings.
https://mattermost.atlassian.net/browse/MM-16042
=> [MM-16042] Navigation fixes around profile picture settings

components/__snapshots__/setting_picture.test.jsx.snap, components/setting_picture.jsx
Cherry pick of #3296 on release-5.14.
- #3296: Navigation fixes around profile picture
=> Automated cherry pick of #3296

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/channel_header/channel_header.js, components/emoji_picker/emoji_picker_tabs.jsx, components/widgets/menu/menu.jsx, components/widgets/menu/menu.test.jsx, components/widgets/menu/menu_wrapper.jsx, package.json
MM-17460 - Removing focus trap
https://mattermost.atlassian.net/browse/MM-17460
=> MM-17460 - Removing focus trap

components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.jsx.snap, components/add_groups_to_team_modal/__snapshots__/add_groups_to_team_modal.test.jsx.snap, components/channel_selector_modal/__snapshots__/channel_selector_modal.test.jsx.snap, components/multiselect/__snapshots__/multiselect.test.jsx.snap, components/multiselect/multiselect.jsx, components/multiselect/multiselect_list.jsx, components/team_selector_modal/__snapshots__/team_selector_modal.test.jsx.snap
Cherry pick of #3352 on release-5.14.
- #3352: Moved defaultAriaLabelRenderer up to
=> Automated cherry pick of #3352

components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
Cherry pick of #3317 on release-5.14.
- #3317: Fix incorrect value comparison using a unset value
/cc  @DSchalla
=> Automated cherry pick of #3317

components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap, components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap, components/invitation_modal/invitation_modal.jsx, components/invitation_modal/invitation_modal_members_step.jsx, components/main_menu/__snapshots__/main_menu.test.jsx.snap, components/main_menu/main_menu.jsx, e2e/cypress/integration/team/teams_spec.js, plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Fix E2E for team spec, affected by the guest account where Add Members was changed into Invite People.
This is also a quick fix to potentially fix the daily tests - on not exiting properly.
none
=> Fix E2E for team spec

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
Cherry pick of #3303 on release-5.14.
- #3303: Update schema_admin_settings.test.jsx.snap
=> Automated cherry pick of #3303

components/post_view/post/index.js, components/post_view/post/post.jsx, components/post_view/post_list/index.js, components/post_view/post_list/post_list.jsx, components/post_view/post_list/post_list_virtualized.jsx, components/post_view/post_list/post_list_virtualized.test.jsx, utils/post_utils.jsx
=>  [MM-16723] Reworked post list reading to avoid duplicates (#3290) - cherry-pick

components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap, components/user_settings/notifications/desktop_notification_settings.jsx, components/user_settings/notifications/user_settings_notifications.jsx
MM-17482 - Updating account settings spacing
https://mattermost.atlassian.net/browse/MM-17482
=> MM-17482 - Updating account settings spacing

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, components/size_aware_image.test.jsx, sass/components/_files.scss
MM-17465 - Updating files scss
@sudheerDev Had to remove the width: 100% from the button. Though this works for svgs too.
https://mattermost.atlassian.net/browse/MM-17465
=> MM-17465 - Updating files scss

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, components/size_aware_image.test.jsx, sass/components/_files.scss
Cherry pick of #3340 on release-5.14.
- #3340: MM-17465 - Updating files scss
=> Automated cherry pick of #3340

components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap, components/user_settings/notifications/desktop_notification_settings.jsx, components/user_settings/notifications/user_settings_notifications.jsx
Cherry pick of #3351 on release-5.14.
- #3351: MM-17482 - Updating account settings spacing
=> Automated cherry pick of #3351

NOTICE.txt
Cherry pick of #3378 on release-5.14.
- #3378: Update NOTICE.txt
/cc  @amyblais
=> Automated cherry pick of #3378

e2e/cypress/fixtures/users.json, e2e/cypress/integration/channel/system_message_spec.js, e2e/cypress/support/ui_commands.js
Fix failing tests due to the ff:
- change in `apiLogin`
- change on default user accounts
- change on element structure
none
=> Fix failing E2E

e2e/package-lock.json, e2e/package.json
=> Updated cypress to 3.4.1

package-lock.json, package.json, utils/markdown/link_only_renderer.test.jsx
Updates the `Marked` dependency
Fixes https://github.com/mattermost/mattermost-server/issues/10774
=> [MM-13837] Updated marked dependency

sass/routes/_settings.scss
Cherry pick of #3376 on release-5.14.
- #3376: Fixed so that team icon settings displays removal
=> Automated cherry pick of #3376

actions/user_actions.jsx, actions/user_actions.test.js, components/popover_list_members/index.js, components/popover_list_members/popover_list_members.jsx, components/popover_list_members/popover_list_members.test.jsx
Cherry pick of #3394 on release-5.14.
- #3394: Load statuses when opening channel member list from header
=> Automated cherry pick of #3394

components/__snapshots__/setting_picture.test.jsx.snap, components/setting_picture.jsx
MM-17600 - Updating file upload (setting picture)
https://mattermost.atlassian.net/browse/MM-17600
=> MM-17600 - Updating file upload (setting picture)

components/__snapshots__/setting_item_max.test.jsx.snap, components/setting_item_max.jsx, components/setting_item_max.test.jsx, components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap, components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
MM-17552 - Preventing settings update on cancel
https://mattermost.atlassian.net/browse/MM-17552
=> MM-17552 - Preventing settings update on cancel

components/__snapshots__/setting_picture.test.jsx.snap, components/setting_picture.jsx
Cherry pick of #3391 on release-5.14.
- #3391: MM-17600 - Updating file upload (setting picture)
=> Automated cherry pick of #3391

components/__snapshots__/setting_item_max.test.jsx.snap, components/setting_item_max.jsx, components/setting_item_max.test.jsx, components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap, components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
Cherry pick of #3383 on release-5.14.
- #3383: MM-17552 - Preventing settings update on cancel
=> Automated cherry pick of #3383

plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap, plugins/channel_header_plug/channel_header_plug.jsx
Cherry pick of #3401 on release-5.14.
- #3401: MM-17487 - Updating plugin dropdown alignment
=> Automated cherry pick of #3401

components/post_view/post_list/post_list_virtualized.jsx, components/post_view/post_list/post_list_virtualized.test.jsx
Cherry pick of #3323 on release-5.14.
- #3323: MM-17354 Fix for date line beign cutoff when entering a
=> Automated cherry pick of #3323

actions/views/channel.js, actions/views/channel.test.js
Cherry pick of #3396 on release-5.14.
- #3396: MM-17485 Fix for missing messages on socket reconn for only
=> Automated cherry pick of #3396

components/post_view/post_list_ie/index.js, components/post_view/post_list_ie/post_list_ie.jsx
Cherry pick of #3410 on release-5.14.
- #3410: MM-17671 Permalink does not render posts in IE11
=> Automated cherry pick of #3410

sass/layout/_headers.scss
MM-17672 - Updating flex css for header
https://mattermost.atlassian.net/browse/MM-17672
=> MM-17672 - Updating flex css for header

sass/layout/_headers.scss
Cherry pick of #3415 on release-5.14.
- #3415: MM-17672 - Updating flex css for header
=> Automated cherry pick of #3415

sass/layout/_webhooks.scss
MM-17650- Updating webhooks css
https://mattermost.atlassian.net/browse/MM-17650
**Updated:**
=> MM-17650 - Updating webhooks css

components/user_settings/display/manage_languages/manage_languages.jsx, sass/components/_modal.scss
MM-17690 - Updating language select functionality
This also disables scrolling on the modal when the languages dropdown is open.
https://mattermost.atlassian.net/browse/MM-17690
=> MM-17690 - Updating language select functionality

components/user_settings/display/manage_languages/manage_languages.jsx, sass/components/_modal.scss
Cherry pick of #3421 on release-5.14.
- #3421: MM-17690 - Updating language select functionality
=> Automated cherry pick of #3421

components/__snapshots__/setting_item_max.test.jsx.snap, components/__snapshots__/setting_picture.test.jsx.snap, components/setting_item_max.jsx, components/setting_picture.jsx, components/user_settings/display/user_settings_theme/user_settings_theme.jsx, components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap, components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
Cherry pick of #3385 on release-5.14.
- #3385: Focused container of profile picture settings
=> Automated cherry pick of #3385

components/__snapshots__/setting_picture.test.jsx.snap, components/setting_picture.jsx
MM-17691 - Updating picture component
https://mattermost.atlassian.net/browse/MM-17691
=> MM-17691 - Updating picture component

i18n/en.json
Lowercases some words as discussed https://community-release.mattermost.com/core/pl/yjcpxbeu8p8gigw5q44m7x19fy.
n/a
=> Lower cases some words in translation.

components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap, components/edit_channel_header_modal/edit_channel_header_modal.jsx
MM-17749 - Updating channel header modal links
https://mattermost.atlassian.net/browse/MM-17749
=> MM-17749 - Updating channel header modal links

sass/layout/_webhooks.scss
Cherry pick of #3409 on release-5.14.
- #3409: Updating webhooks css
=> Automated cherry pick of #3409

components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap, components/edit_channel_header_modal/edit_channel_header_modal.jsx
Cherry pick of #3439 on release-5.14.
- #3439: MM-17749 - Updating channel header modal links
=> Automated cherry pick of #3439

components/__snapshots__/setting_picture.test.jsx.snap, components/setting_picture.jsx
Cherry pick of #3422 on release-5.14.
- #3422: MM-17691 - Updating picture component
=> Automated cherry pick of #3422

sass/layout/_headers.scss
MM-17760 - Updating flex css in header
https://mattermost.atlassian.net/browse/MM-17760
Screenshot from Edge:
=> MM-17760 - Updating flex css in header

sass/layout/_headers.scss
Cherry-pick from: MM-17760 - Updating flex css in header (#3435)
[MM-17760](https://mattermost.atlassian.net/browse/MM-17760)
=> Cherry-pick from: MM-17760 - Updating flex css in header (#3435)

sass/components/_files.scss
MM-17788, MM-17656 - Updating images css
https://mattermost.atlassian.net/browse/MM-17788
https://mattermost.atlassian.net/browse/MM-17656
Screenshot:
=> MM-17788, MM-17656 - Updating images css

sass/components/_files.scss
Cherry pick of #3438 on release-5.14.
- #3438: MM-17788 - Updating files css
=> Automated cherry pick of #3438

components/searchable_user_list/searchable_user_list.jsx
Cherry pick of #3434 on release-5.14.
- #3434: WIP
=> Automated cherry pick of #3434

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/channel_header/channel_header.js, components/create_comment/__snapshots__/create_comment.test.jsx.snap, components/create_comment/create_comment.jsx, components/create_post/__snapshots__/create_post.test.jsx.snap, components/create_post/create_post.jsx, components/local_date_time/local_date_time.jsx, components/post_view/post/post.jsx, components/post_view/post_time/post_time.jsx, components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap, components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/rhs_root_post.jsx, components/rhs_thread/rhs_thread.jsx, components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/search_results_item.jsx, components/sidebar/header/sidebar_header.jsx
Fixes:
- JAWs not reading message action buttons due to aria hidden on posts
- JAWs switching to virtual cursor mode when using F6 navigation
https://mattermost.atlassian.net/browse/MM-17847
https://mattermost.atlassian.net/browse/MM-17848
=> Minor accessibility fixes

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/channel_header/channel_header.js, components/create_comment/__snapshots__/create_comment.test.jsx.snap, components/create_comment/create_comment.jsx, components/create_post/__snapshots__/create_post.test.jsx.snap, components/create_post/create_post.jsx, components/local_date_time/local_date_time.jsx, components/post_view/post/post.jsx, components/post_view/post_time/post_time.jsx, components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap, components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/rhs_root_post.jsx, components/rhs_thread/rhs_thread.jsx, components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/search_results_item.jsx, components/sidebar/header/sidebar_header.jsx
Cherry pick of #3461 on release-5.14.
- #3461: Minor accessibility fixes
=> Automated cherry pick of #3461

sass/layout/_post.scss
MM-17806 - Updating emoji reactions wrap
https://mattermost.atlassian.net/browse/MM-17806
=> MM-17806 - Updating emoji reactions wrap

sass/layout/_post.scss
Cherry pick of #3456 on release-5.14.
- #3456: MM-17806 - Updating emoji reactions wrap
=> Automated cherry pick of #3456

components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
master is broken
this pr fix that
=> udpate snapshots

components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/rhs_root_post.jsx, components/rhs_root_post/rhs_root_post.test.jsx
Cherry pick of #3459 on release-5.14.
- #3459: add logic to hide flag when ephemeral
=> Automated cherry pick of #3459

components/create_comment/create_comment.jsx, components/create_post/create_post.jsx
Cherry-pick of #3339 to v5.15
https://mattermost.atlassian.net/browse/MM-17074
https://github.com/mattermost/mattermost-webapp/pull/3339
=> [MM-17074] Force focus to textbox on emoji picker toggle off (#3339) - cherry-pick

components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap, components/popover_list_members/popover_list_members.jsx, components/popover_list_members/popover_list_members_item.jsx, components/svg/message_icon.jsx, i18n/en.json, sass/components/_popover.scss, utils/utils.jsx
MM-15989 - Making members popover accessible
https://mattermost.atlassian.net/browse/MM-15989
=> MM-15989 - Making members popover accessible

components/multiselect/__snapshots__/multiselect.test.jsx.snap, components/multiselect/multiselect.jsx
Cherry pick of #3344 to v5.15
https://mattermost.atlassian.net/browse/MM-17094
https://github.com/mattermost/mattermost-webapp/pull/3344
=> [MM-17094] Spacebar now activates add button when focused on multiselect (#3344) - cherrypick

components/suggestion/search_suggestion_list.jsx
Cherry-pick of #3443 to v5.15
https://mattermost.atlassian.net/browse/MM-17603
https://github.com/mattermost/mattermost-webapp/pull/3443
=> [MM-17603] Added null check to label generator on suggestion list (#3443) - cherry-pick

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx
(cherry picked from commit b67277065f82c3cd1a582c2e8d3cfcbc6b21158b)
=> [MM-17390] Rate limited posts fail to load threads (#3449)

components/create_comment/__snapshots__/create_comment.test.jsx.snap, components/create_comment/create_comment.jsx, components/create_post/__snapshots__/create_post.test.jsx.snap, components/create_post/create_post.jsx
=> Updating fix for post area

sass/components/_buttons.scss
MM-17755 - Updating button focus state
https://mattermost.atlassian.net/browse/MM-17755
=> MM-17755 - Updating button focus state

sass/components/_buttons.scss
Cherry pick of #3499 on release-5.15.
- #3499: MM-17755 - Updating button focus state
=> Automated cherry pick of #3499

utils/a11y_controller.js
Cherry pick of #3480 on release-5.15.
- #3480: handle window focus events
=> Automated cherry pick of #3480

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx
Cherry pick of #3478 on release-5.15.
- #3478: MM-17890 Properly dispatch handleChannelUpdatedEvent
/cc  @hmhealey
=> Automated cherry pick of #3478

components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap, components/edit_channel_header_modal/edit_channel_header_modal.jsx, sass/layout/_post.scss
Cherry pick of #3500 on release-5.15.
- #3500: MM-17856 - Updating channel header modal
=> Automated cherry pick of #3500

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx, plugins/index.js
Cherry pick of #3425 on release-5.15.
- #3425: MM-17087 - Disable plugin on removal
=> Automated cherry pick of #3425

components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
MM-17909 - Updating users dropdown
https://mattermost.atlassian.net/browse/MM-17909
**Screenshot**
=> MM-17909 - Updating users dropdown

components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
Fixing a wrong cherry-pick merge
=> Fixing wrong cherry-pick

sass/widgets/menu/_menu_wrapper.scss
Some menus where not shown in certain cases because the changes related to how
the animations works in safari.
[MM-17876](https://mattermost.atlassian.net/browse/MM-17876)
=> Fixing not shown menus in some cases

e2e/cypress/tsconfig.json
Added tsconfig.json file to be able to leverage the types for intellisense. No functional changes, just quality of life improvment.
N/A
=> Added tsconfig file for cypress intellisense

actions/admin_actions.jsx, components/admin_console/license_settings/index.js, components/admin_console/license_settings/license_settings.jsx, package-lock.json, package.json
Fix some license fields showing as NaN and remove forced refresh when uploading/removing licenses. Includes some minor refactoring and clean-up of the LicenseSettings component.
https://mattermost.atlassian.net/browse/MM-17917
=> MM-17917 Fix some license fields showing as NaN and remove forced refresh when uploading/removing licenses

components/__snapshots__/textbox.test.jsx.snap, components/autosize_textarea.jsx, components/create_comment/__snapshots__/create_comment.test.jsx.snap, components/create_comment/create_comment.jsx, components/create_post/__snapshots__/create_post.test.jsx.snap, components/create_post/create_post.jsx, components/search_bar/__snapshots__/search_bar.test.jsx.snap, components/search_bar/search_bar.jsx, components/suggestion/suggestion_box.jsx, components/suggestion/suggestion_list.jsx, components/textbox/textbox.jsx, components/toggle_modal_button_redux/toggle_modal_button_redux.jsx, components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
MM-17964 - Post area, comment area and autocomplete a11y changes.
MM-17974 - Search a11y changes
https://mattermost.atlassian.net/browse/MM-17964
https://mattermost.atlassian.net/browse/MM-17974
=> MM-17964 - Post area and search a11y changes

components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap, components/popover_list_members/popover_list_members.jsx, components/popover_list_members/popover_list_members_item.jsx, components/svg/message_icon.jsx, i18n/en.json, sass/components/_popover.scss, utils/utils.jsx
Cherry pick of #3364 on release-5.15.
- #3364: MM-15989 - Making members popover accessible
=> Automated cherry pick of #3364

components/setting_item_max.jsx, components/setting_item_max.test.jsx
Cherry pick of #3457 on release-5.15.
- #3457: Check if event target for setting item max is
=> Automated cherry pick of #3457

components/external_image/external_image.jsx, components/external_image/external_image.test.jsx
Cherry pick of #3507 on release-5.15.
- #3507: MM-17875 Guess image format before metadata is available
/cc  @hmhealey
=> Automated cherry pick of #3507

components/rhs_thread/__snapshots__/rhs_thread.test.jsx.snap, components/rhs_thread/index.js, components/rhs_thread/rhs_thread.jsx, components/rhs_thread/rhs_thread.test.jsx
Cherry pick of #3475 on release-5.15.
- #3475: MM-17634 Fix for RHS to fetch posts on socket reconnect
=> Automated cherry pick of #3475

components/suggestion/search_suggestion_list.jsx
Cherry-pick of #3443 to v5.14
https://mattermost.atlassian.net/browse/MM-18143
=> [MM-17603] Added null check to label generator on suggestion list (#3443)

components/suggestion/search_suggestion_list.test.jsx, components/suggestion/suggestion_box.test.jsx, components/suggestion/suggestion_list.jsx, components/suggestion/suggestion_list.test.jsx
This PR makes the same fix to `suggestion_list` as done in https://mattermost.atlassian.net/browse/MM-17603, and adds the tests around that functionality
https://mattermost.atlassian.net/browse/MM-18143
NOTE: Needs to be cherry-picked to v5.14 as well
=> [MM-18143] Additional fix to generateLabel in another file and associated tests

components/suggestion/search_suggestion_list.test.jsx, components/suggestion/suggestion_list.jsx, components/suggestion/suggestion_list.test.jsx
Cherry pick of #3566 to v5.14
https://mattermost.atlassian.net/browse/MM-18143
=> [MM-18143] Additional fix to generateLabel in another file and associated tests (#3566)

components/admin_console/license_settings/license_settings.jsx
Cherry pick of #3444 on release-5.15.
- #3444: Fixing in-app links
/cc  @reflog
=> Automated cherry pick of #3444

components/suggestion/search_suggestion_list.test.jsx, components/suggestion/suggestion_box.test.jsx, components/suggestion/suggestion_list.jsx, components/suggestion/suggestion_list.test.jsx
Cherry pick of #3566 on release-5.15.
- #3566: WIP
=> Automated cherry pick of #3566

components/create_comment/__snapshots__/create_comment.test.jsx.snap, components/create_comment/create_comment.jsx, components/multiselect/__snapshots__/multiselect.test.jsx.snap, components/multiselect/multiselect.jsx, utils/a11y_controller.js
Some screen readers read `<button>` elements with a tutor message that says 'Press space to activate'. This PR adds that functionality to all `<button>`s in the system such that pressing space will trigger their click event.
https://mattermost.atlassian.net/browse/MM-18035
=> [MM-18035] Spacebar now activates all <button>'s when focused

sass/layout/_post.scss
MM-17526, MM-18133 - Updating post css
https://mattermost.atlassian.net/browse/MM-17526
https://mattermost.atlassian.net/browse/MM-18133
=> MM-17526 - Updating compact post css

sass/layout/_post.scss
Cherry pick of #3564 on release-5.15.
- #3564: MM-17526 - Updating compact post css
=> Automated cherry pick of #3564

components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap, components/post_view/post_body_additional_content/post_body_additional_content.jsx, components/youtube_video/__snapshots__/youtube_video.test.jsx.snap, components/youtube_video/index.js, components/youtube_video/youtube_video.jsx, components/youtube_video/youtube_video.test.jsx, i18n/en.json, sass/components/_videos.scss, sass/responsive/_mobile.scss
Cherry pick of #3493 on release-5.15.
- #3493: MM-17653 Remove metadata call for youtube links
=> Automated cherry pick of #3493

components/invitation_modal/__snapshots__/invitation_modal_guests_step.test.jsx.snap, components/invitation_modal/invitation_modal_guests_step.jsx
Fixes TAB key behaviour in guests invitation modal.
https://mattermost.atlassian.net/browse/MM-18016
=> [MM-18016] Fix TAB key behaviour in guests invitation modal

components/create_comment/__snapshots__/create_comment.test.jsx.snap, components/create_comment/create_comment.jsx, components/multiselect/__snapshots__/multiselect.test.jsx.snap, components/multiselect/multiselect.jsx, utils/a11y_controller.js
Cherry pick of #3551 on release-5.15.
- #3551: Spacebar now activates all <button>'s when
=> Automated cherry pick of #3551

selectors/i18n.js, selectors/i18n.test.js
Cherry pick of #3558 on release-5.15.
- #3558: Check locale is valid before sending to
=> Automated cherry pick of #3558

components/integrations/confirm_integration/__snapshots__/confirm_integration.test.jsx.snap, components/integrations/confirm_integration/confirm_integration.jsx
Cherry pick of #3514 on release-5.15.
- #3514: Make url link unclickable
/cc  @iomodo
=> Automated cherry pick of #3514

components/search_hint/__snapshots__/search_hint.test.jsx.snap, components/search_hint/search_hint.jsx, i18n/en.json
Frontend work for https://github.com/mattermost/mattermost-server/issues/11071
- Has server changes [server change](https://github.com/mattermost/mattermost-server/pull/11196)
=> MM-11359: add hint text for search exclusion

components/user_settings/sidebar/user_settings_sidebar.jsx
=> [MM-17406] Fixed channel switcher setting so that it shows the real setting on exit (#3590) - cherry-pick

.storybook/addons.js, .storybook/config.js, .storybook/webpack.config.js, Makefile, components/widgets/badges/badge.scss, components/widgets/badges/badges.stories.js, components/widgets/icons/icons.stories.js, components/widgets/loading/loading.stories.js, package-lock.json, package.json, storybook/index.stories.js, storybook/styles.scss, utils/utils.jsx
Add an initial skel for start building the storybook. Included some examples.
I think QA is not needed here in the sense is almost not touching the real code (just a small change related to how the color of the theme is applied to the badges) the rest of the code is just related to the storybook.
[MM-17861](https://mattermost.atlassian.net/browse/MM-17861)
=> Initial storybook commit

sass/routes/_signup.scss
MM-18134 - Updating css for signup page
https://mattermost.atlassian.net/browse/MM-18134
Screenshot:
=> MM-18134 - Updating css for signup page

sass/layout/_headers.scss
MM-18243 - Updating header description css
https://mattermost.atlassian.net/browse/MM-18243
=> MM-18243 - Updating header description css

components/search_results/search_results.jsx, components/sidebar_right/sidebar_right.jsx
Cherry pick of #3594 on release-5.15.
- #3594: Wait for transition on RHS before rendering
=> Automated cherry pick of #3594

i18n/en.json
Cherry pick of #3585 on release-5.15.
- #3585: Update en.json
=> Automated cherry pick of #3585

sass/layout/_sidebar-right.scss, sass/responsive/_mobile.scss
MM-18169 - Updating post error css for RHS
https://mattermost.atlassian.net/browse/MM-18169
**Screenshot:**
=> MM-18169 - Updating post error css for RHS

components/admin_console/admin_definition.jsx
Cherry pick of #3582 on release-5.15.
- #3582: fixed URL placeholder
/cc  @reflog
=> Automated cherry pick of #3582

sass/layout/_sidebar-right.scss, sass/responsive/_mobile.scss
Cherry pick of #3597 on release-5.15.
- #3597: MM-18169 - Updating post error css for RHS
=> Automated cherry pick of #3597

sass/layout/_headers.scss
Cherry pick of #3603 on release-5.15.
- #3603: MM-18243 - Updating header description css
=> Automated cherry pick of #3603

sass/routes/_signup.scss
Cherry pick of #3599 on release-5.15.
- #3599: MM-18134 - Updating css for signup page
=> Automated cherry pick of #3599

.circleci/config.yml
Cherry pick of #3584 on release-5.15.
- #3584: deprecate lambda function to upload
/cc  @cpanato
=> Automated cherry pick of #3584

components/post_profile_picture/post_profile_picture.jsx, sass/layout/_post.scss
MM-18175 - Updating system profile picture svg color
https://mattermost.atlassian.net/browse/MM-18175
**Screenshot:**
=> MM-18175 - Updating system profile picture svg color

components/post_profile_picture/post_profile_picture.jsx, sass/layout/_post.scss
Cherry pick of #3598 on release-5.15.
- #3598: MM-18175 - Updating profile picture svg color
=> Automated cherry pick of #3598

components/__snapshots__/markdown_image.test.jsx.snap, components/markdown_image.jsx, components/markdown_image.test.jsx, components/size_aware_image.jsx
Cherry pick of #3588 on release-5.15.
- #3588: MM-18190 Fix markdown image overlap in compact view
=> Automated cherry pick of #3588

components/create_comment/create_comment.jsx
Without this code it still scrolls correctly on file upload.
https://mattermost.atlassian.net/browse/MM-18251
=> MM-18251 Remove old unneeded scroll code and fix JS error

actions/integration_actions.jsx, plugins/export.js, plugins/interactive_dialog.js
Cherry pick of #3629 on release-5.15.
- #3629: MM-18340: restore dialog's store.subscribe
=> Automated cherry pick of #3629

components/integrations_marketplace/marketplace_item/marketplace_item.jsx, components/integrations_marketplace/marketplace_modal.jsx
revert https://github.com/mattermost/mattermost-webapp/pull/3600
=> Revert mm 18139

components/integrations_marketplace/marketplace_item/__snapshots__/marketplace_item.test.jsx.snap, components/integrations_marketplace/marketplace_item/marketplace_item.jsx, components/integrations_marketplace/marketplace_item/marketplace_item.test.jsx, components/integrations_marketplace/marketplace_modal.jsx, components/integrations_marketplace/marketplace_modal.scss
Leverage new support from the server and marketplace.
https://mattermost.atlassian.net/browse/MM-17846
=> MM-17846: render plugin icon, if available

sass/layout/_headers.scss
MM-18545 - Updating height for channel-header
https://mattermost.atlassian.net/browse/MM-18545
=> MM-18545 - Updating height for channel-header

sass/layout/_headers.scss
Cherry pick of #3668 on release-5.15.
- #3668: MM-18545 - Updating height for channel-header
=> Automated cherry pick of #3668

components/invitation_modal/__snapshots__/invitation_modal_initial_step.test.jsx.snap, components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap, components/invitation_modal/invitation_modal_initial_step.jsx, components/invitation_modal/invitation_modal_members_step.jsx, components/widgets/modals/full_screen_modal.test.tsx, components/widgets/modals/full_screen_modal.tsx, e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js, e2e/cypress/integration/guest_accounts/member_invitation_ui_spec.js, e2e/cypress/support/api_commands.js
Validating the UI Elements of the Members Invitation Flow when Guest Account feature is enabled. Please check the ticket for more details. 
Fixes https://mattermost.atlassian.net/browse/MM-18039
=> Added Cypress test for validating MM-18039 Members Invitation Flow: Verify UI Elements

components/widgets/team_icon/team_icon.scss, sass/layout/_team-button.scss
Fixed incorrect sizing on team icon to fix the overflow bug
Fixes https://mattermost.atlassian.net/browse/MM-18521
=> MM-18521 - Overflow bug in badge on team ucoin

components/invitation_modal/__snapshots__/invitation_modal_guests_step.test.jsx.snap, components/invitation_modal/invitation_modal_guests_step.jsx, e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
Validating the UI Elements of the Guest User Invitation Flow when Guest Account feature is enabled. Please check the ticket for more details.
Fixes https://mattermost.atlassian.net/browse/MM-18041
=> Added Cypress test for validating MM-18041 Guest User Invitation Flow - Verify UI Elements

e2e/cypress/integration/at_mentions/at_mentions_spec.js
Fix for failing at-mentions spec
- N14571
- N14570
none
=> Fix at-mention spec

components/invitation_modal/__snapshots__/invitation_modal_guests_step.test.jsx.snap, components/invitation_modal/invitation_modal_guests_step.jsx, e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
Cherry pick of #3677 on release-5.16.
- #3677: Added Cypress test for validating MM-18041 Guest User
/cc  @srkgupta
=> Automated cherry pick of #3677

components/help/components/formatting.jsx, i18n/en.json, webpack.config.js
MM-17123 - Updating inline images markdown
https://mattermost.atlassian.net/browse/MM-17123
**Screenshot:**
=> MM-17123 - Updating inline images markdown

e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js, e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
Add E2E for built-in slash commands
- / autocomplete list can scroll
- /shrug test
- user status (away, dnd, offline, online)
Jira ticket: [MM-18456](https://mattermost.atlassian.net/browse/MM-18456)
=> MM-18456 Add E2E for built-in slash commands

components/team_selector_modal/team_selector_modal.jsx, sass/components/_permissions.scss
Cherry pick of #3687 on release-5.16.
- #3687: restore team name div and css
=> Automated cherry pick of #3687

components/multiselect/multiselect_list.jsx
Cherry pick of #3679 on release-5.16.
- #3679: Force screen reader to read whole aria-live
=> Automated cherry pick of #3679

components/help/components/formatting.jsx, i18n/en.json, webpack.config.js
Cherry pick of #3661 on release-5.16.
- #3661: MM-17123 - Updating inline images markdown
=> Automated cherry pick of #3661

components/popover_list_members/popover_list_members_item.jsx, e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js, e2e/cypress/support/api_commands.js
Validating the Restrictions when a Guest User logs in. Please check the ticket for more details.
Fixes https://mattermost.atlassian.net/browse/MM-18043
=> Added Cypress test for validating MM-18043 Guest User Experience: Verify Guest User Restrictions

components/popover_list_members/popover_list_members_item.jsx, e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js, e2e/cypress/support/api_commands.js
Cherry pick of #3712 on release-5.16.
- #3712: Added Cypress test for validating MM-18043 Guest User
/cc  @srkgupta
=> Automated cherry pick of #3712

sass/layout/_headers.scss
MM-18067 - Updating css for plugin list
https://mattermost.atlassian.net/browse/MM-18067
=> MM-18067 - Updating css for plugin list

components/admin_console/team_channel_settings/line_switch.jsx, sass/components/_line-switch.scss, sass/components/_module.scss, sass/components/_team-channel-settings.scss, sass/responsive/_mobile.scss
MM-18510 - Updating LDAP Channels screen css
https://mattermost.atlassian.net/browse/MM-18510
=> MM-18510 - Updating LDAP Channels screen css

sass/layout/_headers.scss
Cherry pick of #3711 on release-5.16.
- #3711: MM-18067 - Updating css for plugin list
=> Automated cherry pick of #3711

components/admin_console/team_channel_settings/line_switch.jsx, sass/components/_line-switch.scss, sass/components/_module.scss, sass/components/_team-channel-settings.scss, sass/responsive/_mobile.scss
Cherry pick of #3710 on release-5.16.
- #3710: MM-18510 - Updating LDAP Channels screen css
=> Automated cherry pick of #3710

sass/components/_popover.scss
MM-18492 - Updating header popover z-index
https://mattermost.atlassian.net/browse/MM-18492
=> MM-18492 - Updating header popover z-index

sass/responsive/_mobile.scss
MM-18244 - Updating username on LHS mobile view
https://mattermost.atlassian.net/browse/MM-18244
**Screenshot:**
=> MM-18244 - Updating username on LHS mobile view

sass/components/_popover.scss
Cherry pick of #3707 on release-5.16.
- #3707: MM-18492 - Updating header popover z-index
=> Automated cherry pick of #3707

sass/responsive/_mobile.scss
Cherry pick of #3706 on release-5.16.
- #3706: MM-18244 - Updating username on LHS mobile view
=> Automated cherry pick of #3706

e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Cherry pick of #3713 on release-5.16.
- #3713: Added Cypress test for validating MM-18040 Members Invitation
/cc  @srkgupta
=> Automated cherry pick of #3713

actions/channel_actions.test.js
Added Test Coverage to addUsersToChannel within the actions/channel_action.test
Jira: [ https://mattermost.atlassian.net/browse/MM-17945](https://mattermost.atlassian.net/browse/MM-17945)
Fixes [https://github.com/mattermost/mattermost-server/issues/12002](https://github.com/mattermost/mattermost-server/issues/12002)
=> MM-17945 Added test coverage for addUsersToChannel

actions/command.js
Cherry pick of #3714 on release-5.16.
- #3714: Fixed race condition for /leave action
=> Automated cherry pick of #3714

package-lock.json, package.json
A critical fix in redux is needed, so the version is bumped.
https://github.com/mattermost/mattermost-redux/commit/4a749d7aae8114b3e19941e2df33ea7b71f88940
=> Bump Mattermost-Redux version

components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap, components/channel_members_dropdown/channel_members_dropdown.jsx, components/channel_members_dropdown/channel_members_dropdown.test.jsx
Cherry pick of #3701 on release-5.16.
- #3701: Fixing Guest labeling in manage users
/cc  @jespino
=> Automated cherry pick of #3701

package-lock.json, package.json
Updated redux reference to include fixes in 5.16 of redux
=> Bumped Mattermost-Redux version in 5.16

components/admin_console/plugin_management/plugin_management.jsx
Added condition to disable the Marketplace URL setting if the Marketplace is disabled in the System Console.
Fixes [MM-18648](https://mattermost.atlassian.net/browse/MM-18648)
=> MM-18648 - Disable Marketplace URL if Marketplace is disabled

components/admin_console/plugin_management/plugin_management.jsx
Cherry pick of #3717 on release-5.16.
- #3717: Added condition to disable URL setting if marketplace is
=> Automated cherry pick of #3717

sass/layout/_headers.scss, sass/layout/_sidebar-left.scss, utils/utils.jsx
https://mattermost.atlassian.net/browse/MM-18580
MM-18580 - Updating css3 variables
=> MM-18580 - Updating css3 variables

sass/layout/_webhooks.scss
MM-17650 - Updating spacing for interactive menu
https://mattermost.atlassian.net/browse/MM-17650
Screenshot:
=> MM-17650 - Updating spacing for interactive menu

components/invitation_modal/index.test.jsx, package-lock.json
There are some issues with reliability of the existing unit test. 
Update unit test to create fake state, rather than mock
https://mattermost.atlassian.net/browse/MM-18021
https://github.com/mattermost/mattermost-webapp/pull/3682
=> MM-18021 - Harden Unit Test

components/logged_in/logged_in.jsx, package-lock.json, package.json, utils/notifications.jsx, utils/utils.jsx
Cherry pick of #3718 on release-5.16.
- #3718: redirect notifications to desktop app
=> Automated cherry pick of #3718

components/integrations/bots/add_bot/add_bot.jsx
Cherry-picked
https://github.com/mattermost/mattermost-webapp/pull/3616
=> [MM-18332] Ignore trailing and leading whitespace in Username Field during bot

components/channel_members_modal/__snapshots__/channel_members_modal.test.jsx.snap, components/channel_members_modal/channel_members_modal.jsx, components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap, components/more_direct_channels/more_direct_channels.jsx, components/team_members_modal/__snapshots__/team_members_modal.test.jsx.snap, components/team_members_modal/team_members_modal.jsx, components/user_list_row/user_list_row.jsx, e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
Cherry pick of #3752 on release-5.16.
- #3752: Added Cypress Test for the testcase 'MM-18045 - Guest
/cc  @srkgupta
=> Automated cherry pick of #3752

e2e/cypress/integration/email/mention_email_notification_spec.js, e2e/cypress/support/ui_commands.js, e2e/cypress/utils/index.js
Add timeout in getting current channel ID and update inbucket email provider on local dev
n/a
=> E2E: Add timeout in getting current channel ID and update inbucket email provider on local dev

components/create_comment/create_comment.jsx
MM-18744 - Updating comment submit function
https://mattermost.atlassian.net/browse/MM-18744
=> MM-18744 - Updating comment submit function

components/create_comment/create_comment.jsx
Cherry pick of #3763 on release-5.16.
- #3763: MM-18744 - Updating comment submit function
=> Automated cherry pick of #3763

sass/layout/_team-sidebar.scss
MM-18780 - Updating team sidebar z-index
https://mattermost.atlassian.net/browse/MM-18780
=> MM-18780 - Updating team sidebar z-index

actions/views/channel.js, actions/views/channel.test.js, actions/websocket_actions.jsx, actions/websocket_actions.test.jsx, components/permalink_view/actions.js, components/permalink_view/permalink_view.test.jsx, components/rhs_thread/rhs_thread.jsx, components/rhs_thread/rhs_thread.test.jsx
A companion PR to https://github.com/mattermost/mattermost-server/pull/12364
Fixes https://mattermost.atlassian.net/browse/MM-18623
- Has server changes: https://github.com/mattermost/mattermost-server/pull/12364
- Has redux changes: https://github.com/mattermost/mattermost-redux/pull/933
=> MM-18623  - Handle reply-count in getPostThread code path

actions/views/channel.js, actions/views/channel.test.js, actions/websocket_actions.jsx, actions/websocket_actions.test.jsx, components/permalink_view/actions.js, components/permalink_view/permalink_view.test.jsx, components/rhs_thread/rhs_thread.jsx, components/rhs_thread/rhs_thread.test.jsx
Cherry pick of #3776 on release-5.16.
- #3776: Handle reply-count in getPostThread code path
/cc  @reflog
=> Automated cherry pick of #3776

package-lock.json, package.json
=> Redux bump

sass/layout/_team-sidebar.scss
Cherry pick of #3761 on release-5.16.
- #3761: MM-18780 - Updating team sidebar z-index
=> Automated cherry pick of #3761

sass/components/_emoticons.scss, sass/responsive/_mobile.scss
MM-17514 - Updating emoji picker css on mobile
https://mattermost.atlassian.net/browse/MM-17514
**Screenshot**
=> MM-17514 - Updating emoji picker css on mobile

sass/components/_emoticons.scss, sass/responsive/_mobile.scss
Cherry pick of #3782 on release-5.16.
- #3782: MM-17514 - Updating emoji picker css on mobile
=> Automated cherry pick of #3782

components/textbox.test.jsx, components/textbox/index.js, components/textbox/textbox.jsx
The references here are not needed and were removed with https://github.com/mattermost/mattermost-webapp/pull/3641 but added back in a master merge in https://github.com/mattermost/mattermost-webapp/pull/3453
https://mattermost.atlassian.net/browse/MM-18745
=> MM-12588 Remove scrollPostList references

components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap, components/admin_console/plugin_management/plugin_management.jsx, i18n/en.json
Cherry pick of #3783 on release-5.16.
- #3783: Added markdown to open target=blank for marketplace
=> Automated cherry pick of #3783

components/search_results/search_results.jsx
MM-18931 - Fixing long post css on search
https://mattermost.atlassian.net/browse/MM-18931
Screenshot:
=> MM-18931 - Fixing long post css on search

components/logged_in/logged_in.jsx, package-lock.json, package.json, utils/notifications.jsx, utils/utils.jsx
Backport of functionality required by Desktop v4.3 to support Desktop Notifications. See ticket and PR below
https://mattermost.atlassian.net/browse/MM-18819
https://github.com/mattermost/mattermost-webapp/pull/3718
=> [MM-18819] Backport desktop notification changes to 5.9

sass/layout/_post.scss, sass/layout/_sidebar-left.scss
After letting it soak for a while, the consensus is that the animation on the channel buttons in the LHS feel more like lag than helpful UX so this PR removes the effect.
Related to: https://mattermost.atlassian.net/browse/MM-18370
=> Remove animation effect on channel buttons

components/channel_view/channel_view.jsx, components/channel_view/channel_view.test.jsx
Cherry pick of #3642 on release-5.16.
- #3642: MM-17979 Fix for center channel beign scrollable for few
=> Automated cherry pick of #3642

.circleci/config.yml, Makefile, components/color_input.test.tsx, components/dot_menu/dot_menu.jsx, components/file_upload/file_upload.jsx, components/post_view/post_body/post_body.jsx, components/post_view/post_list/post_list_virtualized.jsx, components/rhs_card/rhs_card.jsx, components/rhs_thread/rhs_thread.jsx, components/widgets/admin_console/admin_header.test.tsx, components/widgets/loading/loading_spinner.tsx, components/widgets/loading/loading_wrapper.tsx, components/widgets/team_icon/team_icon.tsx, package.json, tsconfig.json, types/images.d.ts, utils/delayed_action.tsx
I've added the `tsc` to the CircleCI build process as well as created a Makefile/npm script for type checking. You can now run either `npm run check-types` or `make check-types` to run the compiler.
https://mattermost.atlassian.net/browse/MM-18908
=> Typescript Campaign Additions

actions/post_actions.jsx, actions/post_actions.test.js, utils/emoticons.jsx, utils/emoticons.test.jsx
Cherry pick of #3798 on release-5.16.
- #3798: unit test recent emojis
=> Automated cherry pick of #3798

components/logged_in/logged_in.jsx, package-lock.json, package.json, utils/notifications.jsx, utils/utils.jsx
Backport of functionality required by Desktop v4.3 to support Desktop Notifications. See ticket and PR below
https://mattermost.atlassian.net/browse/MM-18819
https://github.com/mattermost/mattermost-webapp/pull/3718
=> [MM-18819] Backport desktop notification changes to 5.15

components/logged_in/logged_in.jsx, package-lock.json, package.json, utils/notifications.jsx, utils/utils.jsx
Backport of functionality required by Desktop v4.3 to support Desktop Notifications. See ticket and PR below
https://mattermost.atlassian.net/browse/MM-18819
https://github.com/mattermost/mattermost-webapp/pull/3718
=> [MM-18819] Backport desktop notification changes to 5.14

components/removed_from_channel_modal/__snapshots__/removed_from_channel_modal.test.jsx.snap, components/removed_from_channel_modal/removed_from_channel_modal.jsx, components/team_sidebar/team_sidebar_controller.jsx, e2e/cypress/integration/enterprise/guest_accounts/guest_removal_ui_spec.js, e2e/cypress/support/api_commands.js
Cherry pick of #3779 on release-5.16.
- #3779: Added Cypress Test for the testcase 'MM-18044 - Guest
/cc  @srkgupta
=> Automated cherry pick of #3779

components/search_results/search_results.jsx
Cherry pick of #3802 on release-5.16.
- #3802: MM-18931 - Fixing long post css on search
=> Automated cherry pick of #3802

sass/layout/_headers.scss
MM-18932 - Updating header quotes css
https://mattermost.atlassian.net/browse/MM-18932
Screenshots:
=> MM-18932 - Updating header quotes css

components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap, components/file_attachment/file_attachment.jsx, components/file_attachment/file_attachment.test.jsx, components/file_attachment/filename_overlay.jsx
Cherry pick of #3795 on release-5.16.
- #3795: blur file attachment anchor on click
=> Automated cherry pick of #3795

e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
Cherry pick of #3788 on release-5.16.
- #3788: Added Cypress test to Verify Guest Invitation Flow when
/cc  @srkgupta
=> Automated cherry pick of #3788

components/admin_console/custom_plugin_settings/index.js
Cherry pick of #3826 on release-5.16.
- #3826: fix for crash when there are no plugin settings
/cc  @cpoile
=> Automated cherry pick of #3826

components/create_comment/create_comment.jsx, components/create_post/create_post.jsx, components/file_upload/file_upload.jsx, utils/paste.test.tsx, utils/paste.tsx
Migrate 'utils/paste.jsx' to TypeScript
Fixes https://github.com/mattermost/mattermost-server/issues/12488
=> MM-18915 Migrate 'utils/paste.jsx' to TypeScript

sass/layout/_headers.scss
Cherry pick of #3803 on release-5.16.
- #3803: MM-18932 - Updating header quotes css
=> Automated cherry pick of #3803

sass/layout/_post.scss
Cherry pick of #3794 on release-5.16.
- #3794: make hover/focus effect more subtle
=> Automated cherry pick of #3794

components/analytics/format.tsx, components/analytics/system_analytics/system_analytics.jsx, components/analytics/team_analytics/team_analytics.jsx
Fixes [`#12479`](https://github.com/mattermost/mattermost-server/issues/12479)
**Ticket link**
https://mattermost.atlassian.net/browse/MM-18924
=> Migrating components/analytics/format.jsx to typescript.

package-lock.json, package.json
`Semver` package was accidentally removed by a quirk of git 🤷‍♂️. Re-adding it with this PR.
- needed for logic around handing desktop notifications to Desktop app for v4.3.0+
https://mattermost.atlassian.net/browse/MM-19035
=> Re-add semver package

components/analytics/__snapshots__/statistic_count.test.tsx.snap, components/analytics/statistic_count.test.tsx, components/analytics/statistic_count.tsx, components/analytics/system_analytics/system_analytics.jsx, components/analytics/team_analytics/team_analytics.jsx
Migrate 'components/analytics/statistic_count.jsx' to TypeScript
Fixes https://github.com/mattermost/mattermost-server/issues/12477
=> MM-18926 Migrate 'components/analytics/statistic_count.jsx' to TypeScript

package-lock.json, package.json
Updating the redux commit to pull in changes for MM-17624.
https://mattermost.atlassian.net/browse/MM-17624
- Has redux changes (https://github.com/mattermost/mattermost-redux/pull/930)
=> [MM-17624] Update redux commit to pull in changes

package-lock.json, package.json
Redux update for MM-17624
https://mattermost.atlassian.net/browse/MM-17624
- Has redux changes (https://github.com/mattermost/mattermost-redux/pull/930)
=> [MM-17624] Redux update

components/channel_header/channel_header.js, components/channel_header/index.js
Showing properly guest badge on channel group message header with full name
[MM-19046](https://mattermost.atlassian.net/browse/MM-19046)
=> Showing properly guest badge on channel group message header with full name

components/channel_header/channel_header.js, components/channel_header/index.js
Cherry pick of #3832 on release-5.16.
- #3832: Showing properly guest badge on channel group message header
/cc  @jespino
=> Automated cherry pick of #3832

components/plugin_marketplace/marketplace_modal.jsx
Cherry pick of #3865 on release-5.16.
- #3865: MM-19151 - Plugin Marketplace: Typing fast on search box does
=> Automated cherry pick of #3865

components/channel_layout/channel_controller.jsx, components/channel_layout/channel_controller.test.jsx, components/channel_layout/channel_identifier_router/actions.js, components/channel_view/channel_view.jsx, components/needs_team/__snapshots__/needs_team.test.jsx.snap, components/needs_team/needs_team.jsx, components/needs_team/needs_team.test.jsx
=> Improving redirect on guest accounts (#3739)

NOTICE.txt
Cherry pick of #3755 on release-5.16.
- #3755: Update NOTICE.txt
/cc  @amyblais
=> Automated cherry pick of #3755

utils/constants.jsx
Cherry pick of #3901 on release-5.16.
- #3901: Add INVITE_GUEST to PermissionsScope
=> Automated cherry pick of #3901

components/signup/signup_controller/signup_controller.jsx
Cherry pick of #3861 on release-5.16.
- #3861: Showing server error when trying to use a team invite link as
/cc  @jespino
=> Automated cherry pick of #3861

components/toggle.tsx
This pull request migrates components/toggle.jsx to TypeScript.
All tests pass locally, suggestions on improvement welcome.
Fixes https://github.com/mattermost/mattermost-server/issues/12436
=> MM-18993 Migrate 'components/toggle.jsx' to TypeScript

actions/user_actions.jsx, actions/user_actions.test.js, components/admin_console/system_users/list/system_users_list.jsx, components/admin_console/system_users/list/system_users_list.test.jsx, components/admin_console/system_users/system_users.jsx, components/admin_console/system_users/system_users.test.jsx
Cherry pick of #3756 on release-5.16.
- #3756: Correctly filter and request inative users
=> Automated cherry pick of #3756

components/widgets/users/avatar.tsx
=> Fixed a type-check issue

components/sidebar/sidebar.jsx, components/sidebar/sidebar.test.jsx, i18n/en.json
Fixed document title on team select
Fixes https://mattermost.atlassian.net/browse/MM-19199
=> MM-19199 - Page/tab title when leaving all teams shows 'undefined'

components/plugin_marketplace/index.js, components/plugin_marketplace/marketplace_modal.jsx, components/plugin_marketplace/marketplace_modal.test.jsx
Fetching marketplace plugins when plugin status is changed
Fixes https://mattermost.atlassian.net/browse/MM-18881
- Has server changes: https://github.com/mattermost/mattermost-server/pull/12687
=> MM-18881 - Attempting to configure uninstalled plugins gets stuck at Loading... without timeout.

utils/a11y_controller.js
Cherry pick of #3922 on release-5.16.
- #3922: fix tabbing in modals and multi post-hover-menus
=> Automated cherry pick of #3922

components/sidebar/sidebar.jsx, components/sidebar/sidebar.test.jsx, i18n/en.json
Cherry pick of #3915 on release-5.16.
- #3915: fixed document title on team select
/cc  @reflog
=> Automated cherry pick of #3915

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx
Cherry pick of #3914 on release-5.16.
- #3914: Fixing guest being removed from other not-visible user
/cc  @jespino
=> Automated cherry pick of #3914

utils/user_agent.jsx
Cherry pick of #3905 on release-5.16.
- #3905: include ipad in check for ios web
=> Automated cherry pick of #3905

components/widgets/menu/menu_items/menu_item.scss, sass/layout/_headers.scss
MM-19110 - Updating dropdown menu item
https://mattermost.atlassian.net/browse/MM-19110
**Screenshot**
=> MM-19110 - Updating dropdown menu item

components/channel_header_dropdown/channel_header_dropdown_items.js
Showing Leave channel for guest accounts in town square
[MM-19426](https://mattermost.atlassian.net/browse/MM-19426)
=> Showing Leave channel for guest accounts in town square

components/channel_header_dropdown/channel_header_dropdown_items.js
Cherry pick of #3961 on release-5.16.
- #3961: Showing Leave channel for guest accounts in town square
/cc  @jespino
=> Automated cherry pick of #3961

components/permalink_view/permalink_view.jsx, components/widgets/separator/separator.scss
MM-19290 - Removing class removal on permalink
MM-19107 - Updating divider css
https://mattermost.atlassian.net/browse/MM-19290
https://mattermost.atlassian.net/browse/MM-19107
=> Mm 19290 MM-19107 - Minor theme improvements

components/__snapshots__/profile_picture.test.tsx.snap, components/at_mention/__snapshots__/at_mention.test.jsx.snap, components/at_mention/at_mention.jsx, components/profile_picture.tsx, components/user_profile/__snapshots__/user_profile.test.jsx.snap, components/user_profile/user_profile.jsx, sass/components/_popover.scss
MM-19221 - Updating profile popover
This issue is being caused by the dynamic content that gets added to the popover after the popover has loaded. This is a temporary fix, we may need to find a more suitable fix for this in the future.
https://mattermost.atlassian.net/browse/MM-19221
=> MM-19221 - Updating profile popover

sass/responsive/_mobile.scss
MM-19220 - Updating channel switcher modal mobile
https://mattermost.atlassian.net/browse/MM-19220
=> MM-19220 - Updating channel switcher modal mobile

sass/responsive/_mobile.scss
Cherry pick of #3928 on release-5.16.
- #3928: MM-19220 - Updating channel switcher modal mobile
=> Automated cherry pick of #3928

sass/responsive/_mobile.scss
MM-19252 - Making max length visible on mobile
https://mattermost.atlassian.net/browse/MM-19252
=> MM-19252 - Making max length visible on mobile

package-lock.json, package.json
This brings the changes from https://github.com/mattermost/react-window/pull/24 to the web app.
https://mattermost.atlassian.net/browse/MM-18860
https://github.com/mattermost/react-window/pull/24
=> MM-18860 Update react-window to re-render posts correctly

e2e/cypress/integration/interactive_dialog/full_dialog_spec.js, e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
Append random number to dialog slash command to not conflict with pre-existing commands/plugins.
N/A
=> Cypress E2E: Append random number to dialog slash command

components/integrations/__snapshots__/installed_command.test.jsx.snap, components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap, components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap, components/integrations/bots/bot.jsx, components/integrations/installed_command.jsx, components/integrations/installed_incoming_webhook.jsx, components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap, components/integrations/installed_oauth_app/installed_oauth_app.jsx, components/integrations/installed_outgoing_webhook.jsx, sass/responsive/_mobile.scss, sass/routes/_backstage.scss
MM-19331 - Updating actions structure in backstage
https://mattermost.atlassian.net/browse/MM-19331
=> MM-19331 - Updating actions structure in backstage

components/plugin_marketplace/index.js, components/plugin_marketplace/marketplace_modal.jsx, components/plugin_marketplace/marketplace_modal.test.jsx
Cherry pick of #3906 on release-5.17.
- #3906: MM-18881 - Attempting to configure uninstalled plugins
=> Automated cherry pick of #3906

components/confirm_modal.jsx
Cherry pick of #3959 on release-5.17.
- #3959: cancel modal if enter button is pressed while cancel
=> Automated cherry pick of #3959

components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap, components/admin_console/plugin_management/plugin_management.jsx, i18n/en.json
Cherry pick of #3923 on release-5.17.
- #3923: MM-18823 - Saving empty string on Marketplace URL resets
=> Automated cherry pick of #3923

components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/search_results_item.jsx, components/search_results_item/search_results_item.test.jsx
Cherry pick of #3985 on release-5.17.
- #3985: Fixed focusing on search results/mentions RHS
=> Automated cherry pick of #3985

components/channel_view/channel_view.jsx, components/permalink_view/permalink_view.jsx, components/permalink_view/permalink_view.test.jsx, components/post_view/new_messages_below/new_messages_below.jsx, components/rhs_thread/rhs_thread.jsx, components/rhs_thread/rhs_thread.test.jsx, sass/layout/_post.scss
Replaces the use of componentWillReceiveProps in the following files:
components/permalink_view/permalink_view.jsx
components/channel_view/channel_view.jsx
components/rhs_thread/rhs_thread.jsx
components/post_view/new_messages_below/new_messages_below.jsx
Fixes https://github.com/mattermost/mattermost-server/issues/12341
=> MM-18784 Removed deprecated methods

components/admin_console/license_settings/license_settings.jsx, utils/utils.jsx
Fixes [mattermost/mattermost-server#12243](https://github.com/mattermost/mattermost-server/issues/12243)
https://mattermost.atlassian.net/browse/MM-18581
=> Remove displayDate method from utils.jsx

e2e/cypress/integration/search/negative_filter_spec.js
E2E tests for negative search filters.
https://mattermost.atlassian.net/browse/MM-19518
=> Added E2E test for negative search filters

components/search_hint/__snapshots__/search_hint.test.tsx.snap, components/search_hint/search_hint.tsx, i18n/en.json
PR fixes the formatting of the search hint.
https://mattermost.atlassian.net/browse/MM-19113
=> [MM-19113] Fix formatting in search hint component

e2e/cypress/integration/channel/add_users_to_channel_spec.js, e2e/cypress/integration/channel/message_reply_spec.js, e2e/cypress/support/ui_commands.js
Failing test on "CS15445 Join/leave messages"
- fixed issue when visiting newly created channel
- added new command "createAndVisitNewChannel" - convenient when creating a new test channel
none
=> Fix issue when visiting newly created channel

components/create_comment/create_comment.jsx
Cherry pick of #3801 on release-5.17.
- #3801: scroll to bottom of rhs when an upload error occurs
=> Automated cherry pick of #3801

components/integrations/__snapshots__/installed_command.test.jsx.snap, components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap, components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap, components/integrations/bots/bot.jsx, components/integrations/installed_command.jsx, components/integrations/installed_incoming_webhook.jsx, components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap, components/integrations/installed_oauth_app/installed_oauth_app.jsx, components/integrations/installed_outgoing_webhook.jsx, sass/responsive/_mobile.scss, sass/routes/_backstage.scss
Cherry pick of #3975 on release-5.17.
- #3975: MM-19331 - Updating actions structure in backstage
=> Automated cherry pick of #3975

components/__snapshots__/profile_picture.test.jsx.snap, components/at_mention/__snapshots__/at_mention.test.jsx.snap, components/at_mention/at_mention.jsx, components/profile_picture.jsx, components/user_profile/__snapshots__/user_profile.test.jsx.snap, components/user_profile/user_profile.jsx, sass/components/_popover.scss
Cherry pick of #3930 on release-5.17.
- #3930: MM-19221 - Updating profile popover
=> Automated cherry pick of #3930

sass/responsive/_mobile.scss
Cherry pick of #3943 on release-5.17.
- #3943: MM-19252 - Making max lebgth visible on mobile
=> Automated cherry pick of #3943

sass/components/_emoticons.scss
MM-19129 - Updating emoji style
https://mattermost.atlassian.net/browse/MM-19129
=> MM-19129 - Updating emoji style

sass/components/_select.scss, sass/layout/_webhooks.scss
MM-19358 - Updating webhooks css
https://mattermost.atlassian.net/browse/MM-19358
=> MM-19358 - Updating webhooks css

sass/components/_emoticons.scss
Cherry pick of #3977 on release-5.17.
- #3977: MM-19129 - Updating emoji style
=> Automated cherry pick of #3977

sass/components/_select.scss, sass/layout/_webhooks.scss
Cherry pick of #3973 on release-5.17.
- #3973: MM-19358 - Updating webhooks css
=> Automated cherry pick of #3973

components/search_results/search_results.jsx, components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/index.js, components/search_results_item/search_results_item.jsx, components/search_results_item/search_results_item.test.jsx, i18n/en.json
Pressing F6 did not take you to the RHS if it wasn't the thread view. This PR adds that navigation and allows arrow key navigation between the posts. It will also read the posts in the same manner as the center channel.
https://mattermost.atlassian.net/browse/MM-18117
=> [MM-18117] Add F6 navigation to search/mentions/flagged/pinned RHS views

components/search_results/search_results.jsx, components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/index.js, components/search_results_item/search_results_item.jsx, components/search_results_item/search_results_item.test.jsx, i18n/en.json
Cherry pick of #3987 on release-5.17.
- #3987: Add F6 navigation to
=> Automated cherry pick of #3987

components/channel_invite_modal/channel_invite_modal.jsx, components/channel_invite_modal/channel_invite_modal.test.jsx, components/channel_invite_modal/index.js
Cherry pick of #4001 on release-5.17.
- #4001: Filter out users not in team from list when adding users
=> Automated cherry pick of #4001

components/file_upload/__snapshots__/file_upload.test.jsx.snap, components/file_upload/file_upload.jsx, components/file_upload/file_upload.test.jsx
Cherry pick of #3996 on release-5.17.
- #3996: Fix attaching files on devices with touch events
/cc  @enahum
=> Automated cherry pick of #3996

components/local_date_time/local_date_time.test.tsx, components/local_date_time/local_date_time.tsx, package-lock.json, package.json
This migrates `components/local_date_time` component to TypeScript.
Fixes https://github.com/mattermost/mattermost-server/issues/12464
N/A
=> [MM-18963] Migrate components/local_date_time to TypeScript

components/admin_console/reset_email_modal/reset_email_modal.jsx, e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
Cherry pick of #4018 on release-5.17.
- #4018: Added testcase to validate whitelisted domain for Guest
/cc  @srkgupta
=> Automated cherry pick of #4018

e2e/cypress/integration/search/post_search_display_spec.js, e2e/cypress/integration/team/teammates_pagination_spec.js, e2e/cypress/support/api_commands.js
Fix E2E for post header and teammates pagination
none
=> Fix E2E for post header and teammates pagination

sass/layout/_post.scss
MM-19631, MM-19632  - Updating emojis css
https://mattermost.atlassian.net/browse/MM-19631
https://mattermost.atlassian.net/browse/MM-19632
**Screenshot**
Looks like the issue was being caused the size change in reactions.
=> MM-19631, MM-19632  - Updating emojis css

actions/views/rhs.js, actions/views/rhs.test.js
Cherry pick of #4012 on release-5.17.
- #4012: clicking pin shouldn't remove search text
/cc  @cpoile
=> Automated cherry pick of #4012

sass/layout/_post.scss
Cherry pick of #4026 on release-5.17.
- #4026: MM-19631 - Updating emojis css
=> Automated cherry pick of #4026

components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap, components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx, components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.test.jsx
Don't sent guest role changes if license doesn't allow it
Fixes https://mattermost.atlassian.net/browse/MM-19556
=> MM-19556 - E10 License: Permission Schemes not working properly

components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap, components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx, components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.test.jsx
Cherry pick of #4017 on release-5.17.
- #4017: don't sent guest role changes if license doesn't allow it
/cc  @reflog
=> Automated cherry pick of #4017

components/admin_console/admin_definition.jsx, i18n/en.json, i18n/ko.json
This ticket updates the description of the Base DN description in the admin console
https://mattermost.atlassian.net/browse/MM-15413
=> [MM-15413] Updated Base DN text to the proposed text

utils/text_formatting.jsx, utils/text_formatting.test.jsx
Cherry pick of #3948 on release-5.17.
- #3948: Dont't rely on searchMatches if searchTerm contains
=> Automated cherry pick of #3948

components/widgets/menu/menu.jsx, components/widgets/menu/menu.scss, components/widgets/menu/menu.test.jsx, components/widgets/menu/menu_items/menu_item.scss, sass/responsive/_mobile.scss
MM-19539 - Updating menu on mobile
https://mattermost.atlassian.net/browse/MM-19539
=> MM-19539 - Updating menu on mobile

components/create_comment/create_comment.jsx, components/create_comment/create_comment.test.jsx, components/create_post/create_post.jsx, components/create_post/create_post.test.jsx, components/emoji_picker/components/emoji_picker_item.jsx, components/emoji_picker/emoji_picker.jsx, components/emoji_picker/emoji_picker_overlay.jsx, components/textbox/textbox.jsx
Removed usage of componentWillReceivedProps, componentWillMount and componentWillUpdate in:
components/emoji_picker/emoji_picker_overlay.jsx
components/emoji_picker/emoji_picker.jsx
components/emoji_picker/components/emoji_picker_item.jsx
components/create_comment/create_comment.jsx
components/create_post/create_post.jsx
components/textbox/textbox.jsx
Fixes https://github.com/mattermost/mattermost-server/issues/12346
=> Replaced functionality in deprecated lifecycle methods

components/interactive_dialog/dialog_element.jsx, components/interactive_dialog/dialog_element.test.jsx
Cherry pick of #4059 on release-5.17.
- #4059: Removed default value for radio elements in interactive
=> Automated cherry pick of #4059

sass/layout/_markdown.scss
MM-19017 - Updating markdown images
https://mattermost.atlassian.net/browse/MM-19017
=> MM-19017 - Updating markdown images

sass/layout/_headers.scss, sass/layout/_markdown.scss
MM-18541 - Updating header description css
https://mattermost.atlassian.net/browse/MM-18158
=> MM-18541 - Updating header description css

sass/layout/_headers.scss, sass/layout/_markdown.scss
Cherry pick of #4048 on release-5.17.
- #4048: MM-18541 - Updating header description css
=> Automated cherry pick of #4048

actions/global_actions.jsx
Cherry pick of #4070 on release-5.17.
- #4070: Fix the case of redirecting to an unavailable
=> Automated cherry pick of #4070

components/about_build_modal/__snapshots__/about_build_modal.test.jsx.snap, components/about_build_modal/about_build_modal.jsx, components/about_build_modal/about_build_modal.test.jsx, utils/constants.jsx
Cherry pick of #4084 on release-5.17.
- #4084: Added default links for TOC and Privacy policy for About
=> Automated cherry pick of #4084

components/integrations/bots/add_bot/add_bot.jsx, utils/utils.jsx
Cherry pick of #4062 on release-5.17.
- #4062: MM-19310 - Wrong validation message when Bot name ends in
=> Automated cherry pick of #4062

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx, package-lock.json, package.json
cherry-picking MM-19414 #4022
[MM-19414](https://mattermost.atlassian.net/browse/MM-19414)
=> cherry-picking MM-19414 #4022

components/admin_console/admin_definition.jsx, components/latex_block/index.js, components/latex_block/latex_block.jsx, i18n/en.json, utils/__snapshots__/message_html_to_component.test.jsx.snap
Cherry pick of #4045 on release-5.17.
- #4045: enable toggling latex rendering in posts
=> Automated cherry pick of #4045

components/channel_header_dropdown/mobile_channel_header_dropdown.js, sass/responsive/_mobile.scss
MM-19751 - Updating channel header mobile menu
https://mattermost.atlassian.net/browse/MM-19751
=> MM-19751 - Updating channel header mobile menu

components/suggestion/suggestion_box.jsx
MM-18373 - Updating suggestion list for Firefox
The previous configuration was not working for Rohit, so just reverted back the change to say "alert + [username]" for the suggestion list.
https://mattermost.atlassian.net/browse/MM-18373
=> MM-18373 - Updating suggestion list for Firefox

components/channel_header_dropdown/mobile_channel_header_dropdown.js, sass/responsive/_mobile.scss
Cherry pick of #4104 on release-5.17.
- #4104: MM-19751 - Updating channel header mobile menu
=> Automated cherry pick of #4104

components/suggestion/suggestion_box.jsx
Cherry pick of #4087 on release-5.17.
- #4087: MM-18373 - Updating suggestion list for firefox
=> Automated cherry pick of #4087

sass/responsive/_mobile.scss
MM-19854 - Updating RHS Menu on mobile
https://mattermost.atlassian.net/browse/MM-19854
=> MM-19854 - Updating RHS Menu on mobile

sass/responsive/_mobile.scss
Cherry pick of #4111 on release-5.17.
- #4111: MM-19854 - Updating RHS Menu on mobile
=> Automated cherry pick of #4111

components/post_view/post_list/post_list.jsx, components/post_view/post_list/post_list.test.jsx
Fixed fetching thread count (missing parameter in post sync)
https://mattermost.atlassian.net/browse/MM-19738
=> MM-19738 - Reply counts sometimes missing on Community Daily

components/user_settings/modal/user_settings_modal.jsx
Avoid "hiccup" whilst loading settings modal for the first time by loading chunks related to settings modal during browser idle.
https://mattermost.atlassian.net/browse/MM-8744
Working with @sudheerDev on this.
=> [MM-8744] Prefetch settings modal during browser idle time

components/__snapshots__/size_aware_image.test.jsx.snap, components/size_aware_image.jsx, sass/components/_files.scss
MM-18641 - Updating loading indicator for files
https://mattermost.atlassian.net/browse/MM-18641
=> MM-18641 - Updating loading indicator for files

components/admin_console/license_settings/license_settings.jsx
Cherry pick of #4122 on release-5.17.
- #4122: update enterprise privacy policy link
/cc  @cpoile
=> Automated cherry pick of #4122

sass/responsive/_mobile.scss
MM-19936 - Updating close button spacing mobile
https://mattermost.atlassian.net/browse/MM-19936
=> MM-19936 - Updating close button spacing mobile
