components/channel_view.jsx
components/tutorial/tutorial_view.jsx

https://github.com/mattermost/mattermost-server/pull/7426 for master

PLT-7579: fix broken css after tutorial

---

components/profile_picture.jsx

Ticket Link
--------------
mattermost/mattermost-server#7227

GITHUB-ISSUE #7227: Migrate profile_picture new redux style

---

components/post_view/post_body/post_body.jsx
components/post_view/post_body_additional_content.jsx
components/rhs_root_post.jsx
components/search_results_item.jsx

Per https://pre-release.mattermost.com/core/pl/phcrym1wipbrbqiqknfdc1zjkh

Changed PostBodyAdditionalContent message property to children property

---

components/post_view/post_info/post_info.jsx

Do not show flagged post icon on system or ephemeral messages.
https://mattermost.atlassian.net/browse/PLT-7583

PLT-7583 Do not show flagged post icon on system or ephemeral messages

---

sass/components/_search.scss
sass/layout/_headers.scss

PLT-7565 - Fixing misaligned RHS
https://mattermost.atlassian.net/browse/PLT-7565

PLT-7565 - Fixing misaligned RHS

---

actions/notification_actions.jsx
components/channel_header.jsx
components/navbar.jsx
components/sidebar.jsx
utils/channel_utils.jsx

Fix sorting of group channel display name
Submitted to master from v4.2 - https://github.com/mattermost/mattermost-server/pull/7422
Jira ticket: [PLT-7577](https://mattermost.atlassian.net/browse/PLT-7577)

[PLT-7577] Fix sorting of group channel display name

---

components/channel_header.jsx
sass/layout/_headers.scss

Add status indicator to DM channel header.
@asaadmahmood please help fix styling issue, especially when the DM channel header description is added. 
Jira ticket: [PLT-7289](https://mattermost.atlassian.net/browse/PLT-7289)

[PLT-7289] Add status indicator to DM channel header

---

.gitignore

Add .idea to gitignore.

---

components/admin_console/storage_settings.jsx
i18n/en.json

Add S3 region to the System Console UI
Jira ticket: [PLT-7475](https://mattermost.atlassian.net/browse/PLT-7475)

[PLT-7475] Add S3 region to the System Console UI

---

sass/layout/_sidebar-menu.scss

https://mattermost.atlassian.net/browse/PLT-7370

PLT-7370 Fixed leave team icon height on IE11

---

components/claim/claim_controller.jsx
components/common/back_button.jsx
components/create_team/create_team_controller.jsx
components/do_verify_email.jsx
components/mfa/mfa_controller.jsx
components/password_reset_send_link.jsx
components/select_team/select_team.jsx
components/should_verify_email.jsx
components/signup/components/signup_email.jsx
components/signup/components/signup_ldap.jsx
components/signup/signup_controller.jsx

There are several occurrences of `Back` button placed in different components. This PR adds `BackButton` component.
No related ticket.

Add back button component

---

i18n/i18n.jsx

Promote Turkish/Italian from Beta; demote Polish to Alpha.
//cc @enahum

Promote Turkish/Italian from Beta; demote Polish to Alpha

---

components/popover_list_members/popover_list_members.jsx

Sort popover by displayed name.
https://mattermost.atlassian.net/browse/PLT-7635

PLT-7635 Sort popover by displayed name

---

components/post_view/post_attachment.jsx
components/post_view/post_attachment_list.jsx
components/textbox.jsx
sass/layout/_post.scss

PLT-7575 - Removing help text if length exceeds
PLT-7528 - Updating Slack attachments
https://mattermost.atlassian.net/browse/PLT-7575
https://mattermost.atlassian.net/browse/PLT-7528

Minor bug fixes

---

components/rhs_comment.jsx

Show message attachments in RHS.
https://mattermost.atlassian.net/browse/PLT-7643

PLT-7643: Show message attachments in rhs

---

components/integrations/components/installed_incoming_webhook.jsx
components/integrations/components/installed_incoming_webhooks.jsx
components/integrations/components/installed_incoming_webhooks/index.js
components/integrations/components/installed_incoming_webhooks/installed_incoming_webhooks.jsx
routes/route_integrations.jsx
tests/components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap
tests/components/integrations/installed_incoming_webhook.test.jsx

Migrate installed_incoming_webhooks.jsx and installed_incoming_webhook.jsx to be pure and use Redux 
#6449
#6453 

Plt 6453: Migrate installed_incoming_webhooks.jsx to be pure and use Redux

---

stores/search_store.jsx

Remove child posts from search results when parent deleted.
https://mattermost.atlassian.net/browse/PLT-7586

PLT-7586: Remove child posts from search results when parent deleted.

---

components/channel_header/index.js

Default markdown formatting to on in channel headers.
https://mattermost.atlassian.net/browse/PLT-7739

PLT-7739 Default markdown formatting to on in channel headers

---

components/user_settings/user_settings_notifications.jsx
utils/channel_intro_messages.jsx

Make invite link of private channel based on permission
Jira ticket: [PLT-7459](https://mattermost.atlassian.net/browse/PLT-7459)

[PLT-7459] Make invite link of private channel based on permission

---

stores/browser_store.jsx

Temporary solution since browser store is being moved into mattermost-redux as a general store.
https://mattermost.atlassian.net/browse/PLT-7630

PLT-7630 Pull user from redux for browser store

---

components/channel_invite_modal/channel_invite_modal.jsx

Page correctly on add members to channel modal.
https://mattermost.atlassian.net/browse/PLT-7698

PLT-7698 Page correctly on add members to channel modal

---

components/status_dropdown/status_dropdown.jsx
sass/components/_status-icon.scss
utils/utils.jsx

Fix hover effect of status dropdown by:
- not using `onMouseEnter` and `onMouseLeave` events
- using CSS hover effect
Jira ticket: [PLT-7399](https://mattermost.atlassian.net/browse/PLT-7399)

[PLT-7399] Fix hover effect of status dropdown

---

yarn.lock

Bump mattermost-redux to latest commit 85db14af9a6d8c402213b0eb3c372f1ac6adad34

Bump mattermost-redux to latest master

---

components/admin_console/session_settings.jsx
i18n/en.json

Tweak idle timeout help text

---

.gitignore
nightwatch.conf.js
nightwatch.json
package.json
tests/e2e/commands/fillInput.js
tests/e2e/commands/getChromeLogs.js
tests/e2e/config.js
tests/e2e/globals.js
tests/e2e/pages/centerChannelHeader.js
tests/e2e/pages/centerPage.js
tests/e2e/pages/loginPage.js
tests/e2e/pages/logoutPage.js
tests/e2e/test.sh
tests/e2e/tests/1_login_logout/testLogin.js
tests/e2e/tests/1_login_logout/testLogout.js
tests/e2e/tests/2_center/channelHeader.js
tests/e2e/tests/2_center/testCenterPage.js
tests/e2e/utils.js
tests/test.sh
yarn.lock

Initial draft for UI Automation
- add npm package: nightwatchjs and selenium-standalone
- add initial test to HTML elements
- add login and logout action 
~~[Still work in progress]~~

[E2E] Add initial draft of end-to-end testing / UI Automation

---

components/do_verify_email.jsx
i18n/en.json

Fix broken UI for expired email invite link
Jira ticket: [PLT-7578](https://mattermost.atlassian.net/browse/PLT-7578)

[PLT-7578] Fix broken UI for expired email invite link

---

components/admin_console/admin_sidebar.jsx

Hide system console pages when no license feature.
- Elasticsearch.
- Data Retention.
https://mattermost.atlassian.net/browse/PLT-7668

PLT-7668: Hide system console pages when no license feature.

---

components/channel_header/channel_header.jsx

https://mattermost.atlassian.net/browse/PLT-7744

PLT-7744 Fixed incorrect import of ChannelInfoModal

---

components/quick_switch_modal/quick_switch_modal.jsx

Focus to post textbox only if not mobile when exiting channel's quick switcher
Jira ticket: [PLT-7606](https://mattermost.atlassian.net/browse/PLT-7606)

[PLT-7607] Focus to post textbox only if not mobile when exiting channel's quick switcher

---

components/logged_in.jsx
sass/layout/_post.scss
sass/layout/_sidebar-right.scss
sass/responsive/_tablet.scss
sass/routes/_admin-console.scss

PLT-7711 - Fixing spacing in manage roles screen
PLT-7760 - Enabling send button for tablets
PLT-7779 - Fixing posts containing less characters
https://mattermost.atlassian.net/browse/PLT-7711
https://mattermost.atlassian.net/browse/PLT-7760
https://mattermost.atlassian.net/browse/PLT-7779

Ui improvements

---

components/create_comment/create_comment.jsx
components/create_post.jsx
components/post_view/post_attachment.jsx
utils/markdown.jsx
utils/url.jsx

Certain slash command links weren't being handled correctly when received by the client
https://mattermost.atlassian.net/browse/PLT-7721
https://mattermost.atlassian.net/browse/PLT-7722

PLT-7721/PLT-7722 Fix slash command links

---

components/post_view/post_list.jsx

Made a last-minute mistake here: https://github.com/mattermost/mattermost-webapp/pull/96
Empty arrays aren't falsey. :P
https://mattermost.atlassian.net/browse/PLT-7792?filter=14400

PLT-7792: fix channel loading animation

---

components/authorize.jsx

Updates to oauth authorize page.
https://mattermost.atlassian.net/browse/PLT-7720

PLT-7720 Updates to oauth authorize page

---

package.json
tests/components/__snapshots__/about_build_modal.test.jsx.snap
tests/components/about_build_modal.test.jsx
yarn.lock

Fix unit test of AboutBuildModal component:
- updated test and snapshots
- added packages as suggested on error log (http://airbnb.io/enzyme/docs/installation/index.html)
```
"enzyme-adapter-react-15": "1.0.1",
"react-test-renderer": "15",
```
- ensure that the test coverage for this component is 100% (at least for lines, statements and functions)
Other:
- updated code coverage for components folder, excluding *.js since we are testing only the components itself
[UPDATE: 10/05/2017]
Note:
This is submitted in partial for PLT-7814 since there are a number of components tests failing included in that ticket (for easy review).

[PLT-7814] Fix unit test of AboutBuildModal component

---

package.json
yarn.lock

Update mattermost-redux to webapp-4.3 branch.

Update mattermost-redux to webapp-4.3 branch

---

components/get_android_app/get_android_app.jsx
components/get_ios_app/get_ios_app.jsx
components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
components/sidebar_header_dropdown.jsx
utils/url.jsx

https://mattermost.atlassian.net/browse/PLT-7812
https://mattermost.atlassian.net/browse/PLT-7813

PLT-7812/PLT-7813 Fixed link text

---

utils/constants.jsx

[A brief description of what this pull request does.]
https://github.com/mattermost/mattermost-server/issues/6895
https://mattermost.atlassian.net/browse/PLT-7078

fix(constants.js): add m4r to audio mime types for thumbnails

---

components/channel_header/index.js

Fix leaving channel.
https://mattermost.atlassian.net/browse/PLT-7827

PLT-7827 Fix leaving channel

---

tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
tests/components/post_view/post_info/post_info.test.jsx

- Fix unit test of PostInfo component
Note:
This is submitted in partial for PLT-7814 since there are a number of components tests failing included in that ticket (for easy review).
~~Submitted on top of this [PR](https://github.com/mattermost/mattermost-webapp/pull/117/commits/1a4b579635a14e490cd3e59d7f2cdb530e88130f) due to import order between UserStore and Selectors.~~

[PLT-7814] Fix unit test of PostInfo component

---

sass/layout/_post.scss
sass/layout/_sidebar-right.scss
sass/responsive/_tablet.scss

PLT-7828 - Post control menu overlapping fix
PLT-7821 - Fixing bot label in RHS
PLT-7848 - Pinned icon overlapping on posts
https://mattermost.atlassian.net/browse/PLT-7828
https://mattermost.atlassian.net/browse/PLT-7821
https://mattermost.atlassian.net/browse/PLT-7848

Release 4.3 fixes

---

components/channel_header/channel_header.jsx
components/edit_channel_header_modal/edit_channel_header_modal.jsx
components/edit_channel_header_modal/index.js
components/navbar/index.jsx
tests/components/__snapshots__/edit_channel_header_modal.test.jsx.snap
tests/components/edit_channel_header_modal.test.jsx
utils/channel_intro_messages.jsx
utils/utils.jsx

Updated EditChannelHeaderModalComponent with requirements. 
Connected them with redux store.
https://github.com/mattermost/mattermost-server/issues/7234

7234 migrate edit channel header modal

---

components/webrtc/components/webrtc_notification.jsx
components/webrtc/components/webrtc_sidebar.jsx
sass/layout/_post.scss

PLT-7864 - Channel header icons broken
PLT-7745 - Fixing horizontal scroll bar issue
https://mattermost.atlassian.net/browse/PLT-7864
https://mattermost.atlassian.net/browse/PLT-7745

Minor 4.3 fixes

---

components/channel_header/channel_header.jsx

Hide channel header add link when you don't have permission to edit the header due to policy.
https://mattermost.atlassian.net/browse/PLT-7763

PLT-7763: Hide channel header add link when you don't have permission.

---

components/channel_header/channel_header.jsx
components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
components/edit_channel_purpose_modal/index.js
components/navbar/index.jsx
tests/components/__snapshots__/edit_channel_purpose_modal.test.jsx.snap
tests/components/edit_channel_purpose_modal.test.jsx

Update `EditChannelPurposeModal` with requirements.
Connected them with redux store
https://github.com/mattermost/mattermost-server/issues/7235

GH-7235 migrate edit channel purpose modal

---

components/member_list_team/member_list_team.jsx

Fix team members modal paging.
https://mattermost.atlassian.net/browse/PLT-7854

PLT-7854 Fix team members modal paging

---

components/user_settings/user_settings_general/user_settings_general.jsx

The diff is a bit strange. I only changed the if statements and reordered the if and else blocks.

PLT-7837 Fixing LDAP and SAML settings detection

---

components/create_post.jsx
components/tutorial/tutorial_intro_screens.jsx
components/tutorial/tutorial_tip.jsx
package.json
tests/e2e/pages/centerChannelHeader.js
tests/e2e/pages/loginPage.js
tests/e2e/pages/tutorialPage.js
tests/e2e/test.sh
tests/e2e/tests/1_login_logout/testTutorial.js

Add tutorial page E2E test and cleanup initial patch
Jira ticket: [PLT-7796](https://mattermost.atlassian.net/browse/PLT-7796)

[E2E] Add tutorial page e2e test and cleanup initial patch

---

components/admin_console/users_and_teams_settings.jsx
components/create_post.jsx
i18n/en.json

The PR mattermost/mattermost-server#7416 must be merged before it.
Links
-------
mattermost/mattermost-server#7335
https://mattermost.atlassian.net/browse/PLT-7508
Checks
----------

PLT-7508: Add settings to disable wide mention confirmation

---

.gitignore

Ignored gogland project files

---

sass/responsive/_mobile.scss
sass/responsive/_tablet.scss

PLT-7888 - Fixing compact view spacing
https://mattermost.atlassian.net/browse/PLT-7888

PLT-7888 - Fixing compact view spacing

---

tests/components/integrations/__snapshots__/installed_command.test.jsx.snap
tests/components/integrations/installed_command.test.jsx

- Fix unit test of InstalledCommand component
Note:
This is submitted in partial for PLT-7814 since there are a number of components tests failing included in that ticket (for easy review).

fix unit test of InstalledCommand component

---

components/rhs_comment.jsx
components/rhs_thread/index.js
components/rhs_thread/rhs_thread.jsx
components/search_results_item.jsx

Added previewCollapsed selector as connected props for rhs_thred
Removed PostBodyAdditionalContent component for searchResults.
https://github.com/mattermost/mattermost-server/issues/7542

PLT-5268 Always show link previews on comment threads in right-hand sidebar

---

actions/websocket_actions.jsx

add slash command /kick and /remove to remove users from channel
Server PR: https://github.com/mattermost/mattermost-server/pull/7523
previous PR: https://github.com/mattermost/mattermost-server/pull/7124
JIRA: https://mattermost.atlassian.net/browse/PLT-6712 and https://mattermost.atlassian.net/browse/PLT-7182
GitHub: mattermost#6557 and mattermost#6975

[PLT-6712] add slash command to remove users from channel - webapp part

---

components/post_view/post_message_view/index.js
components/sidebar_right_menu.jsx
components/webrtc/components/webrtc_notification.jsx
package.json
yarn.lock

Fix broken master
Jira ticket: [PLT-7944](https://mattermost.atlassian.net/browse/PLT-7944)

[PLT-7944] Fix broken master

---

components/spinner_button.jsx
tests/components/__snapshots__/spinner_button.test.jsx.snap
tests/components/spinner_button.test.jsx

Refactor SpinnerButton and fix component test.

[PLT-7814] Refactor SpinnerButton and fix component test

---

components/post_deleted_modal.jsx
tests/components/__snapshots__/post_deleted_modal.test.jsx.snap
tests/components/post_deleted_modal.test.jsx

https://github.com/mattermost/mattermost-server/issues/7673
Migrates the `post_deleted_modal.jsx` to use Redux and adds tests.
https://github.com/mattermost/mattermost-server/issues/7673

Migrate post_deleted_modal.jsx to use Redux

---

components/post_view/post_message_view/post_message_view.jsx
package.json
tests/plugins/__snapshots__/pluggable.test.jsx.snap
tests/plugins/__snapshots__/post_type.test.jsx.snap
tests/plugins/pluggable.test.jsx
tests/plugins/post_type.test.jsx

[PLT-7814] Fix plugins component tests

---

tests/components/integrations/__snapshots__/abstract_incoming_hook.test.jsx.snap
tests/components/integrations/abstract_incoming_hook.test.jsx

Fix AbstractIncomingWebhook component test

[PLT-7814] Fix AbstractIncomingWebhook component test

---

components/sidebar.jsx
components/sidebar_header.jsx
components/sidebar_header_dropdown.jsx
components/status_dropdown/status_dropdown.jsx
components/unread_channel_indicator.jsx
package.json
tests/e2e/pages/sidebarLeftPage.js
tests/e2e/test.sh
tests/e2e/tests/3_sidebarLeft/sidebarLeftPage.element.js

Modify test:e2e script, add element IDs and element checks for leftSideBar components
Jira ticket: [PLT-7873](https://mattermost.atlassian.net/browse/PLT-7873)

[E2E] Modify test:e2e script, add element IDs and element checks for leftSideBar components

---

components/admin_console/data_retention_settings.jsx

Disable "Run Job" button if Dataretention is disabled.
https://mattermost.atlassian.net/browse/PLT-7861

PLT-7861: Disable "Run Job" button if Dataretention is disabled.

---

components/admin_console/plugin_settings/plugin_settings.jsx

Clear plugin upload error on successful upload.

Clear plugin upload error on successful upload

---

components/user_settings/email_notification_setting.jsx
tests/components/user_settings/__snapshots__/email_notification_setting.test.jsx.snap
tests/components/user_settings/email_notification_setting.test.jsx

- Fix error when saving email notification without change by monitoring the email notification state whether it has changed.
- Also added component test
Jira ticket: [PLT-7929](https://mattermost.atlassian.net/browse/PLT-7929)

[PLT-7929] Fix error when saving email notification without change

---

components/create_comment/create_comment.jsx
components/create_post.jsx
utils/utils.jsx

* emoji icon active state in create_post and create_comment.
* expanded sidebar icon active state.

Fixes for active state

---

utils/utils.jsx

PLT-7979 - Fixing styling for emoji icon
https://mattermost.atlassian.net/browse/PLT-7979

PLT-7979 - Fixing styling for emoji icon

---

actions/admin_actions.jsx
actions/channel_actions.jsx
actions/emoji_actions.jsx
actions/global_actions.jsx
actions/integration_actions.jsx
actions/job_actions.jsx
actions/oauth_actions.jsx
actions/post_actions.jsx
actions/team_actions.jsx
actions/user_actions.jsx
components/admin_console/compliance_reports/compliance_reports.jsx
components/admin_console/manage_roles_modal/manage_roles_modal.jsx
components/analytics/team_analytics/team_analytics.jsx
components/integrations/components/abstract_command.jsx
components/integrations/components/add_command/add_command.jsx
components/integrations/components/add_command/index.js
components/integrations/components/add_incoming_webhook/add_incoming_webhook.jsx
components/integrations/components/add_outgoing_webhook/add_outgoing_webhook.jsx
components/integrations/components/edit_incoming_webhook/edit_incoming_webhook.jsx
components/integrations/components/edit_outgoing_webhook/edit_outgoing_webhook.jsx
components/post_view/post_list.jsx
root.jsx
routes/route_team.jsx
yarn.lock

Support new mattermost-redux action returns.
@lindalumitchell could I get your help just running a smoke test on this? I did one myself already but another set of eyes would be awesome. It touches a bunch of different parts of the app, anything broken by this should be obvious and have a JS error.
https://mattermost.atlassian.net/browse/PLT-7798

PLT-7798 Support new mattermost-redux action returns

---

components/integrations/components/abstract_oauth_app.jsx
components/integrations/components/edit_command/edit_command.jsx
components/integrations/components/edit_command/index.js
components/integrations/components/edit_oauth_app/edit_oauth_app.jsx
components/integrations/components/edit_oauth_app/index.js

Various integration page fixes. Noticed these while fixing https://mattermost.atlassian.net/browse/PLT-7969

Various integration page fixes

---

components/post_view/post_body/post_body.jsx

Show post sending indicator after 3 seconds if request not complete.
https://mattermost.atlassian.net/browse/PLT-7947

PLT-7947 Show post sending indicator after 3 seconds if request not complete

---

components/admin_console/admin_sidebar.jsx

Remove license requirement for plugins.
https://mattermost.atlassian.net/browse/PLT-8006

PLT-8006 Remove license requirement for plugins

---

actions/websocket_actions.jsx
utils/constants.jsx

Handle user role change and switch away from system console if needed
Part 2 of https://mattermost.atlassian.net/browse/PLT-7978

PLT-7978 Handle user role change and switch away from system console if needed

---

components/post_view/post_message_view/post_message_view.jsx
components/textbox.jsx
stores/user_store.jsx
utils/post_utils.jsx

Solved mention like `@someone` didn't appear linked in message box preview mode.
[GitHub](https://github.com/mattermost/mattermost-server/issues/6127)
[Jira](https://mattermost.atlassian.net/browse/PLT-4790)

PLT-4790: Mention don't appear linked in message box preview mode.

---

actions/websocket_actions.jsx

This is a tricky one and I wasn't able to reproduce this one myself but based on reports it might be related to reconnection so we'll see if this helps.
https://mattermost.atlassian.net/browse/PLT-7843

PLT-7843 Fetch team unreads on reconnect

---

components/team_sidebar/components/team_button.jsx
sass/layout/_team-sidebar.scss

Hide team URLs from the sidebar
Jira ticket: [PLT-7773](https://mattermost.atlassian.net/browse/PLT-7773)

[PLT-7773] Hide team URLs from the sidebar

---

components/delete_modal_trigger.jsx
tests/components/__snapshots__/delete_modal_trigger.test.jsx.snap
tests/components/delete_modal_trigger.test.jsx

Migrate delete trigger modal to be pure.
[mattermost-server/issues/7675](https://github.com/mattermost/mattermost-server/issues/7675)

Migrate delete trigger modal to be pure

---

components/new_channel_flow.jsx

Fix editing new channel URL.
https://mattermost.atlassian.net/browse/PLT-8072

PLT-8072 Fix editing new channel URL

---

tests/components/integrations/__snapshots__/abstract_oauth_app.test.jsx.snap
tests/components/integrations/abstract_oauth_app.test.jsx

- ix AbstractOAuthApp component test

[PLT-7814] Fix AbstractOAuthApp component test

---

components/color_input.jsx
sass/components/_buttons.scss
sass/responsive/_mobile.scss

PLT-8073 - Bg fix from custom theme boxes
PLT-8067 - Reducing preview width on mobile
PLT-8068 - Fixing channel menu items on mobile
PLT-8071 - Fixing loading icon spacing in button

Fixes bugs for release branch

---

components/post_view/post/index.js
components/post_view/post/post.jsx

I couldn't reproduce the error but the error message could only be coming from somewhere in the post component hierarchy where the post was undefined.
https://mattermost.atlassian.net/browse/PLT-8080

PLT-8080 Prevent undefined post as prop

---

components/header_footer_template/header_footer_template.jsx
components/header_footer_template/index.js
routes/route_root.jsx
tests/components/__snapshots__/header_footer_template.test.jsx.snap
tests/components/header_footer_template.test.jsx

Solves mattermost/mattermost-server#7791

GH-7791: Migrate header_footer_template.jsx to pure component and redux

---

tests/components/__snapshots__/delete_modal_trigger.test.jsx.snap
tests/components/delete_modal_trigger.test.jsx

- Fix DeleteModalTrigger component test

[PLT-7814] Fix DeleteModalTrigger component test

---

tests/components/integrations/__snapshots__/edit_oauth_app.test.jsx.snap
tests/components/integrations/edit_oauth_app.test.jsx

- Fix EditOAuthApp component test

[PLT-7814] Fix EditOAuthApp component test

---

tests/components/integrations/__snapshots__/edit_command.test.jsx.snap
tests/components/integrations/__snapshots__/installed_command.test.jsx.snap
tests/components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
tests/components/integrations/edit_command.test.jsx
tests/components/integrations/installed_command.test.jsx
tests/components/integrations/installed_incoming_webhook.test.jsx
tests/components/integrations/installed_outgoing_webhook.test.jsx
tests/components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
tests/utils/formatting_hashtags.test.jsx

Fix several components tests
- EditCommand
- InstalledCommand
- InstalledIncomingWebhook
- InstalledOutgoingWebhook
- PostAddChannelMember
- TextFormatting

[PLT-7814] Fix several components tests

---

components/suggestion/channel_mention_provider.jsx

https://mattermost.atlassian.net/browse/PLT-8108

PLT-8108 Fixed channel link autocomplete triggering after text returns no results

---

tests/components/__snapshots__/new_channel_modal.test.jsx.snap
tests/components/integrations/__snapshots__/abstract_command.test.jsx.snap
tests/components/integrations/abstract_command.test.jsx
tests/components/new_channel_modal.test.jsx

Fix components tests
- AbstractCommand
- NewChannelModal

[PLT-7814] Fix AbstractCommand and NewChannelModal components tests

---

components/post_view/post_message_view/post_message_view.jsx
components/setting_item_min.jsx
sass/layout/_post.scss

PLT-8118 - Account settings items misaligned
PLT-8106 - Fixing edited indicator on compact view
https://mattermost.atlassian.net/browse/PLT-8118
https://mattermost.atlassian.net/browse/PLT-8106

Release 4.4

---

components/signup/components/signup_email.jsx
components/signup/components/signup_ldap.jsx
components/signup/signup_controller.jsx

- This is a workaround for a bug in react-router.

Fix signup flow

---

components/integrations/components/installed_oauth_app.jsx
components/integrations/components/installed_oauth_apps/installed_oauth_apps.jsx
tests/components/__snapshots__/user_settings_display.test.jsx.snap
tests/components/integrations/__snapshots__/installed_oauth_app.test.jsx.snap
tests/components/integrations/__snapshots__/installed_oauth_apps.test.jsx.snap
tests/components/integrations/installed_oauth_app.test.jsx
tests/components/integrations/installed_oauth_apps.test.jsx
tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
tests/plugins/__snapshots__/post_type.test.jsx.snap

Fix several components tests:
- PostTypePlugin
- InstalledOAuthApp
- InstalledOAuthApps
- UserSettingsDisplay
- PostInfo
This is the second to the last batch for below ticket. Last item would be updating jest config and enabling test for PR builds.

[PLT-7814] Fix several components test (second to the last bacth)

---

components/tutorial/tutorial_intro_screens.jsx
tests/e2e/pages/tutorialPage.js
tests/e2e/tests/1_login_logout/tutorial.element.js
tests/e2e/tests/2_center/centerPage.element.js

- Add element IDs to tutorial page; and
- Update tutorial page UI automation

[E2E] update tutorial page

---

components/integrations/components/installed_commands/installed_commands.jsx
components/integrations/components/installed_incoming_webhooks/index.js
components/integrations/components/installed_incoming_webhooks/installed_incoming_webhooks.jsx
components/integrations/components/installed_outgoing_webhooks/index.js
components/integrations/components/installed_outgoing_webhooks/installed_outgoing_webhooks.jsx

Fix regression on incoming/outgoing webhooks and slash commands being shown on different team
Jira ticket: [PLT-8138](https://mattermost.atlassian.net/browse/PLT-8138)

[PLT-8138] Fix regression on incoming/outgoing webhooks and slash commands being shown on different team

---

components/post_view/post_body/index.js
components/post_view/post_body/post_body.jsx
components/profile_popover.jsx
plugins/docs.json

Minor changes to support automatic plugin doc generation, see comments below for more info.
Needed for mattermost/mattermost-developer-documentation#36

Minor changes to support automatic plugin doc generation

---

components/analytics/table_chart.jsx
tests/components/analytics/__snapshots__/table_chart.test.jsx.snap
tests/components/analytics/table_chart.test.jsx

mattermost/mattermost-server#7781

GH-7781: Migrating analytics/table_chart.jsx to PureComponent

---

components/analytics/statistic_count.jsx
tests/components/analytics/__snapshots__/statistic_count.test.jsx.snap
tests/components/analytics/statistic_count.test.jsx

mattermost/mattermost-server#7780

GH-7780: Migrating analytics/statistic_count to PureComponent

---

components/file_attachment.jsx
tests/components/__snapshots__/file_attachment.test.jsx.snap
tests/components/file_attachment.test.jsx

mattermost/mattermost-server#7787

GH-7787: Migrate file_attachment to PureComponent

---

components/analytics/doughnut_chart.jsx
components/analytics/system_analytics.jsx
tests/components/analytics/__snapshots__/doughnut_chart.test.jsx.snap
tests/components/analytics/doughnut_chart.test.jsx

mattermost/mattermost-server#7778

GH-7778: Migrating analytics/doughnut_chart.jsx to PureComponent

---

components/search_results.jsx

Sort pinned posts from newest to oldest.
https://mattermost.atlassian.net/browse/PLT-7832

PLT-7832 Sort pinned posts from newest to oldest

---

actions/channel_actions.jsx
components/suggestion/switch_channel_provider.jsx

Wasn't able to reproduce the issue but if it's coming from the webapp it could only come from these places.
https://mattermost.atlassian.net/browse/PLT-8057

PLT-8057 Make sure team ID is defined to prevent unwanted server error logs

---

components/rhs_comment.jsx

Updates RHS comment component if a user's profile picture has been updated.
[PLT-8075](https://mattermost.atlassian.net/browse/PLT-8075)

PLT-8075: Re-renders RHS comments if profile picture has changed.

---

actions/channel_actions.jsx
components/post_view/post_body/index.js
components/post_view/post_body/post_body.jsx
components/post_view/post_body_additional_content.jsx
components/rhs_comment.jsx
components/rhs_root_post.jsx
components/rhs_thread/index.js
components/rhs_thread/rhs_thread.jsx

Fix for link previews only appearing in the first post of RHS.
* Add preview for comments on RHS.
https://mattermost.atlassian.net/browse/PLT-7938

PLT-7938: Fix for link previews only appearing in first post in the RHS.

---

sass/layout/_team-sidebar.scss
utils/utils.jsx

PLT-8077 - Updating create team icon
https://mattermost.atlassian.net/browse/PLT-8077

PLT-8077 - Updating create team icon

---

components/analytics/line_chart.jsx
components/analytics/system_analytics.jsx
components/analytics/team_analytics/team_analytics.jsx
tests/components/analytics/__snapshots__/line_chart.test.jsx.snap
tests/components/analytics/line_chart.test.jsx

mattermost/mattermost-server#7779

GH-7779: Migrating analytics/line_chart.jsx to PureComponent

---

actions/websocket_actions.jsx

Handle user updated event for profile image change for current user. Once approved, I'll add it to mattermost-redux as well
https://mattermost.atlassian.net/browse/PLT-8103

PLT-8103 Handle user updated event for profile image change for current user

---

store/index.js

[PLT-8210](https://mattermost.atlassian.net/browse/PLT-8210)

PLT-8210: Only refresh changes from other tabs

---

components/create_post.jsx

[PLT-8174](https://mattermost.atlassian.net/browse/PLT-8174)

PLT-8174: Edit post on arrow up fixed

---

components/channel_header/channel_header.jsx
plugins/docs.json

Add ChannelHeaderButton pluggable component.
Part of https://mattermost.atlassian.net/browse/PLT-8131

PLT-8131 (part 1) Add ChannelHeaderButton pluggable component

---

components/dot_menu/dot_menu.jsx

Fix warning on dot_menu componentWillReceiveProps

---

i18n/i18n.jsx

FYI @enahum 
I'll look into creating a forum post or a help wanted ticket to find maintainers for Russian/Korean/Polish/Dutch when I get the time.

Russian from Beta to Alpha

---

i18n/en.json

Fix link url that returns 404 Not Found.
Same as this PR: [Fix 404 links by kaakaa · Pull Request \#1642 · mattermost/docs](https://github.com/mattermost/docs/pull/1642#issuecomment-346248647)
N/A

Fix link url

---

components/dot_menu/dot_menu_item.jsx
tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
tests/components/dot_menu/__snapshots__/dot_menu_edit.test.jsx.snap
tests/components/dot_menu/__snapshots__/dot_menu_empty.test.jsx.snap
tests/components/dot_menu/__snapshots__/dot_menu_flag.test.jsx.snap
tests/components/dot_menu/__snapshots__/dot_menu_item.test.jsx.snap
tests/components/dot_menu/__snapshots__/dot_menu_mobile.test.jsx.snap
tests/components/dot_menu/dot_menu.test.jsx
tests/components/dot_menu/dot_menu_edit.test.jsx
tests/components/dot_menu/dot_menu_empty.test.jsx
tests/components/dot_menu/dot_menu_flag.test.jsx
tests/components/dot_menu/dot_menu_item.test.jsx
tests/components/dot_menu/dot_menu_mobile.test.jsx

Add unit tests to
- DotMenu
- DotMenuItem
- DotMenuEdit
- DotMenuFlag

[unit-test] Add test to DotMenu

---

components/add_users_to_team/add_users_to_team.jsx
components/admin_console/admin_settings.jsx
components/channel_invite_modal/channel_invite_modal.jsx
components/more_direct_channels/more_direct_channels.jsx
components/multiselect/multiselect.jsx
components/save_button.jsx
i18n/en.json
tests/components/__snapshots__/save_button.test.jsx.snap
tests/components/admin_console/__snapshots__/custom_plugin_settings.test.jsx.snap
tests/components/save_button.test.jsx
tests/components/user_settings/__snapshots__/email_notification_setting.test.jsx.snap

Add feedback when adding group or DM channel
Jira ticket: [PLT-7695](https://mattermost.atlassian.net/browse/PLT-7695)

[PLT-9695] Add feedback when adding group or DM channel

---

package.json
tests/plugins/__snapshots__/post_type.test.jsx.snap
yarn.lock

Bump mattermost-redux to latest commit
n/a

Bump mattermost-redux to latest commit

---

store/index.js

Rehydrate localForage data on application init to redux store.
[PLT-8244](https://mattermost.atlassian.net/browse/PLT-8244)

[PLT-8244] Rehydrate storage on init

---

actions/storage.js
store/index.js
tests/redux/actions/storage.test.js

[PLT-8210](https://mattermost.atlassian.net/browse/PLT-8210)

Do not re-persist on rehydrate storage

---

components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
tests/components/admin_console/custom_plugin_settings.test.jsx

See https://github.com/mattermost/mattermost-server/pull/7919
N/A

Ordered plugin settings

---

components/channel_header/index.js

[PLT-8257](https://mattermost.atlassian.net/browse/PLT-8257)

Fix fav button on channels

---

components/admin_console/plugin_management/plugin_management.jsx
i18n/en.json

Add help text to plugin management page when uploads disabled.
https://mattermost.atlassian.net/browse/PLT-8254

PLT-8254 Add help text to plugin management page when uploads disabled

---

sass/components/_modal.scss

PLT-8237 - Updating modal textarea overflow
https://mattermost.atlassian.net/browse/PLT-8237

PLT-8237 - Updating modal textarea overflow

---

components/logged_in.jsx
components/user_settings/manage_languages.jsx
sass/base/_structure.scss

Add 100% height to root and fix setState warning on ManageLanguage component
Thanks to @sudheerDev for providing solution to this bug fix (breaking CSS on center)!
Jira ticket: [PLT-8222](https://mattermost.atlassian.net/browse/PLT-8222)

[PLT-8222] Add 100% height to root and fix setState warning on ManageLanguage component

---

components/more_direct_channels/more_direct_channels.jsx
components/multiselect/multiselect.jsx
i18n/en.json

This updates the DM modal with the changes requested in [PLT-7917](https://mattermost.atlassian.net/browse/PLT-7917).
https://mattermost.atlassian.net/browse/PLT-7917

Add deactivated users to dm modal

---

package.json
yarn.lock

Includes a fix for https://mattermost.atlassian.net/browse/PLT-8262

Update mattermost-redux to 1.1.0

---

components/at_mention/at_mention.jsx
components/at_mention/index.jsx

https://mattermost.atlassian.net/browse/PLT-8236

PLT-8236 Properly highlight at mentions for the current user followed by punctuation

---

components/post_view/post_list.jsx

Reset post viewed count when switching channels.
https://mattermost.atlassian.net/browse/PLT-8120

PLT-8120 Reset post viewed count when switching channels

---

components/navbar/navbar.jsx
plugins/docs.json
tests/components/navbar/__snapshots__/navbar.test.jsx.snap

Add pluggable component in mobile channel header.
Padt of https://mattermost.atlassian.net/browse/PLT-8131

Add pluggable component in mobile channel header

---

components/navbar/index.js
components/navbar/navbar.jsx

Fix mobile view search button.
https://mattermost.atlassian.net/browse/PLT-8235

PLT-8235 Fix mobile view search button

---

tests/components/__snapshots__/access_history_modal.test.jsx.snap
tests/components/__snapshots__/activity_log_modal.test.jsx.snap
tests/components/access_history_modal.test.jsx
tests/components/activity_log_modal.test.jsx

Add unit tests to:
- AccessHistoryModal
- ActivityLogModal
Jira ticket: [PLT-8241](https://mattermost.atlassian.net/browse/PLT-8241)

[unit test] AccessHistoryModal and ActivityLogModal

---

components/create_comment/create_comment.jsx
tests/components/create_comment/create_comment.test.jsx

[PLT-8210](https://mattermost.atlassian.net/browse/PLT-8210)

Create comment use the component state to show/edit the draft

---

components/more_direct_channels/more_direct_channels.jsx

Simple fix.
https://mattermost.atlassian.net/browse/PLT-8343

PLT-8343: fix js error in dm add user modal

---

components/admin_console/system_users/system_users_dropdown.jsx
i18n/en.json

Allow deactivation of SSO users. Adds a warning note when deactivating SSO users. PM please review the text.
https://mattermost.atlassian.net/browse/PLT-8100

PLT-8100 Allow deactivation of SSO users

---

build/Jenkinsfile
package.json

Update Jenkinsfile to work with old build server.

Update Jenkinsfile to work with old build server

---

components/audit_table.jsx
i18n/en.json
i18n/ko.json

Minor typo fix in audit_table.verified message

Fix typo in audit table component

---

components/logged_in.jsx

Add channel-view class on root in the constuctor of logged_in component.
[PLT-8332](https://mattermost.atlassian.net/browse/PLT-8332)

PLT-8332: Fix teambar styling on load

---

components/rhs_comment.jsx

https://mattermost.atlassian.net/browse/PLT-8346

PLT-8346 Fixed system messages in the RHS

---

components/navbar/navbar.jsx
sass/components/_search.scss
sass/layout/_navigation.scss
sass/responsive/_mobile.scss
utils/utils.jsx

PLT-8322 - Updating scrollbar issue on mobile
PLT-8325 - Fixing search input border on safari
PLT-8340 - Making close button visible on dm item
Updating webrtc button on mobile
https://mattermost.atlassian.net/browse/PLT-8322
https://mattermost.atlassian.net/browse/PLT-8325
https://mattermost.atlassian.net/browse/PLT-8340

Release 4.5 bug fixes

---

components/sidebar_right/sidebar_right.jsx

Fetch pinned posts for correct channel.
https://mattermost.atlassian.net/browse/PLT-8338

PLT-8338 Fetch pinned posts for correct channel

---

components/add_users_to_team/add_users_to_team.jsx
tests/components/__snapshots__/add_users_to_team.test.jsx.snap
tests/components/add_users_to_team.test.jsx

- Add unit test to AddUsersToTeam
- fix `addValue` function
- remove unreachable codes
Jira ticket: [PLT-8241](https://mattermost.atlassian.net/browse/PLT-8241)

[unit-test] Add unit test to AddUsersToTeam and fix function/unreachable codes

---

components/at_mention/at_mention.jsx
sass/base/_structure.scss
sass/layout/_headers.scss

PLT-8328 - Ios chrome, can’t scroll on teams page
PLT-8353 - Channel dropdown overlapping button
PLT-8362 - Changing profile popover position
https://mattermost.atlassian.net/browse/PLT-8328
https://mattermost.atlassian.net/browse/PLT-8353
https://mattermost.atlassian.net/browse/PLT-8362

4.5 bug fixes

---

sass/responsive/_mobile.scss

PLT-8388 - Removing hover for the sidebar icon
https://mattermost.atlassian.net/browse/PLT-8388

PLT-8388 - Removing hover for the sidebar icon

---

components/signup/components/signup_ldap.jsx

This code was using a deprecated property of the Link component. Updated it to use the new approach.
https://mattermost.atlassian.net/browse/PLT-8367

PLT-8367: Clicking LDAP signup button from invite link displays blank page, error in console

---

package.json
utils/channel_utils.jsx
yarn.lock

Update mattermost-redux to latest.

Update mattermost-redux to latest

---

components/profile_picture.jsx
components/profile_popover.jsx

Check for undefined refs.
Also deletes prop throwing unrelated JS warning.
[PLT-8341](https://mattermost.atlassian.net/browse/PLT-8341)

PLT-8341: Check for undefined refs.

---

.eslintrc.json
components/admin_console/audits/audits.jsx
components/admin_console/cluster_settings.jsx
components/admin_console/cluster_table.jsx
components/admin_console/compliance_reports/compliance_reports.jsx
components/autosize_textarea.jsx
components/backstage/components/backstage_list.jsx
components/claim/components/email_to_ldap.jsx
components/emoji/components/emoji_list.jsx
components/mfa/components/setup.jsx
components/post_view/post_attachment.jsx
components/search_bar/search_bar.jsx
components/webrtc/components/webrtc_notification.jsx

Assign constants to fix style objects
Jira ticket: [PLT-8296](https://mattermost.atlassian.net/browse/PLT-8296)

[webapp-perf] Make constants for fix style objects

---

components/form_error.jsx
package.json
root.jsx
utils/equality.js
yarn.lock

Adds why-did-you-update module in dev mode to log unnecessary updates to browser console. 
Using a forked copy of the main NPM package's repo to include a code change that specifies the specific property that is not equal by reference (ex "channelData" property is not equal by reference). Once that is merged in we can switch to the main repo.
n/a
Example console output.

Adds why-did-you-update and example change.

---

components/login/components/login_mfa.jsx
components/save_button.jsx
i18n/en.json
tests/components/__snapshots__/save_button.test.jsx.snap
tests/components/login/__snapshots__/login_mfa.test.jsx.snap
tests/components/login/login_mfa.test.jsx

- Add loading spinner to MFA sign in button
- Also convert `LoginMfa` into pure component and add unit tests
Jira ticket: [PLT-8396](https://mattermost.atlassian.net/browse/PLT-8396)
@esethna Could you please help review the text `Submitting...` if that's the correct word to use?

[PLT-8396] Add loading spinner to MFA sign in button

---

actions/views/create_comment.jsx
components/create_post/create_post.jsx
tests/components/create_post/create_post.test.jsx
tests/redux/actions/views/create_comment.test.jsx

Fix emoji reaction to recent emojis
Jira ticket: [PLT-8384](https://mattermost.atlassian.net/browse/PLT-8384)

[PLT-8384] Fix emoji reaction to recent emojis

---

store/index.js

Fix the race condition on persistStore initialization when localForage is not ready.
Looks like it has more changes than it really has, it is because I've remove the if ```if (localforage === storage)``` check, so I've un-indented a lot of code. The real changes are moving inside the ```localforage.ready()``` block the persistor variable initialization (https://github.com/mattermost/mattermost-webapp/pull/531/files#diff-acc8a2d3aabb2cc15d1140c1b6e22428R81) and the store subscription (https://github.com/mattermost/mattermost-webapp/pull/531/files#diff-acc8a2d3aabb2cc15d1140c1b6e22428L124).
[PLT-8399](https://mattermost.atlassian.net/browse/PLT-8399)
#

PLT-8399: Fix race condition on persistStore initialization

---

actions/diagnostics_actions.jsx
components/channel_view/channel_view.jsx
components/sidebar.jsx
components/team_sidebar/components/team_button.jsx
root.jsx

Reverts https://github.com/mattermost/mattermost-webapp/commit/c79d96475e1e228438aa18503c39636704c678c9.
n/a

Revert "Reverts "Wraps JS Performance API." (#520)"

---

components/file_upload.jsx

Start upload progress for files all at same time.
https://mattermost.atlassian.net/browse/PLT-8463

PLT-8463 Start upload progress for files all at same time

---

components/file_attachment.jsx
components/file_attachment/filename_overlay.jsx
components/file_preview.jsx
sass/components/_files.scss
tests/components/__snapshots__/file_attachment.test.jsx.snap
tests/components/__snapshots__/file_preview.test.jsx.snap
tests/components/create_post/create_post.test.jsx

Show file name, file type and size in attachment preview:
*Updated test snapshots

Show file names in attachment preview

---

components/suggestion/switch_channel_provider.jsx

Handle undefined usersInChannels list when making search filter.
https://mattermost.atlassian.net/browse/PLT-8479

PLT-8479 Handle undefined usersInChannels list when making search filter

---

utils/utils.jsx

Properly fix JS error when switching teams during channel switch
https://mattermost.atlassian.net/browse/PLT-8461

PLT-8461 Properly fix JS error when switching teams during channel switch

---

components/navbar/index.js
components/navbar/navbar.jsx

Fix opening pinned posts in mobile view.
https://mattermost.atlassian.net/browse/PLT-8450

PLT-8450 Fix opening pinned posts in mobile view

---

actions/views/channel.js
components/common/comment_icon.jsx
components/post_view/index.js
components/post_view/post_info/index.js
components/post_view/post_info/post_info.jsx
components/post_view/post_list.jsx
reducers/views/channel.js
utils/constants.jsx

I missed some cases in mobile view in #483. This should cover them all.

Minor fixes for dot and reply icon in mobile view

---

plugins/index.js
root.html
root.jsx

Adds a content security policy. This mitigates many XSS vulnerabilities that may be present such as those that we've seen from our markdown library. If a user finds a way to inject JavaScript into a post in any form, it'll just be blocked by this policy:
https://mattermost.atlassian.net/browse/PLT-7127

PLT-7127: Add content security policy

---

actions/views/rhs.js
components/create_post/create_post.jsx
components/create_post/index.js

Before this was trying to get the element of the comment icon for the last post in the channel and then perform a DOM click event on it, with this change we get the last replyable post in the channel and we dispatch the flux event to open the RHS
https://mattermost.atlassian.net/browse/PLT-8496

PLT-8496 Fix shift+Up to open reply RHS

---

components/post_view/post_info/post_info.jsx

This will fix the little box getting left behind as well as the emoji picker disappearing when hovering off of it.
https://mattermost.atlassian.net/browse/PLT-8501

PLT-8501 Fix hover and unmounting issues with post_info

---

actions/views/rhs.js
components/create_post/create_post.jsx
components/create_post/index.js
components/post_view/post_info/post_info.jsx
components/search_bar/search_bar.jsx
utils/utils.jsx

Daily Merge 4.6 to Master

---

sass/components/_files.scss
sass/layout/_post.scss

PLT-8504 - Scroll bar cutting of File thumbnails
PLT-8507 - Reply icon not inline in firefox
https://mattermost.atlassian.net/browse/PLT-8504
https://mattermost.atlassian.net/browse/PLT-8507

Release 4.6

---

components/common/back_button.jsx
components/select_team/components/select_team_item.jsx
components/select_team/select_team.jsx

Note for PMs, the way the error flow for this page works now is that it'll display the error message as it does from a signup link. If the user presses the "< Back" link, it'll bring them back to the team list. If they press the browser's back button, it'll send them back to the chat view.
https://mattermost.atlassian.net/browse/PLT-8502

PLT-8502 Show errors on Join Another Team page

---

actions/diagnostics_actions.jsx
root.jsx
tests/setup.js

Adds feature checks for Performance API support.
[PLT-8510](https://mattermost.atlassian.net/browse/PLT-8510)

PLT-8510: Feature checks for older webkit support of Performance API.

---

actions/channel_actions.jsx
actions/global_actions.jsx
actions/team_actions.jsx
actions/websocket_actions.jsx
components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
components/admin_console/system_users/system_users_dropdown.jsx
components/backstage/components/backstage_navbar.jsx
components/login/login_controller.jsx
components/navbar/navbar.jsx
components/removed_from_channel_modal.jsx
components/root.jsx
components/select_team/components/select_team_item.jsx
components/sidebar/sidebar.jsx
components/sidebar/sidebar_channel/sidebar_channel.jsx
components/sidebar_right_menu/sidebar_right_menu.jsx
components/signup/signup_controller.jsx
components/tutorial/tutorial_intro_screens.jsx
routes/route_team.jsx
utils/utils.jsx

Changes town-square string to use constant

Change town-square strings to use constant

---

components/user_settings/custom_theme_chooser.jsx

Update copyTheme string ("share theme colors") on handleColorChange (color picker change).
Jira ticket: [PLT-8523](https://mattermost.atlassian.net/browse/PLT-8523)

[PLT-8523] Update copyTheme string on handleColorChange

---

sass/layout/_sidebar-left.scss

PLT-8521 - Fixing overlay on sidebar

PLT-8521 - Fixing overlay on sidebar

---

sass/layout/_post.scss

PLT-8032 - Adjusting textbox height
https://mattermost.atlassian.net/browse/PLT-8032

PLT-8032 - Adjusting textbox height

---

components/searchable_user_list/searchable_user_list.jsx

Fixed next button display logic
https://mattermost.atlassian.net/browse/PLT-8530

PLT-8530: Incorrect member count showing `51 - 50 members of 50 total` of 50 total team members

---

components/search_results_item/search_results_item.jsx
tests/components/__snapshots__/search_results_item.test.jsx.snap

This was broken here: https://github.com/mattermost/mattermost-webapp/pull/91/files#r142506101
I don't really understand what the reason for that change was. Reverting it.
https://mattermost.atlassian.net/browse/PLT-8539

PLT-8539: Fix flagged post attachment regression

---

components/post_view/reaction/reaction.jsx
tests/components/post_view/__snapshots__/reaction.test.jsx.snap
tests/components/post_view/reaction.test.jsx

- Add reaction to recent emojis when other's reaction to a post is clicked
- Add unit test
Jira ticket: [PLT-8460](https://mattermost.atlassian.net/browse/PLT-8460)

[PLT-8460] Add reaction to recent emojis when other's reaction to a post is clicked

---

components/create_post/create_post.jsx

Makes sure there isn't a message draft before loading past messages
https://mattermost.atlassian.net/browse/PLT-8534

PLT-8534 added check to ensure that draft message is blank before doing anything

---

actions/websocket_actions.jsx
components/announcement_bar/announcement_bar.jsx
components/root.jsx

Fix error bar and bad connection state for textbox.
https://mattermost.atlassian.net/browse/PLT-8527

PLT-8527 Fix error bar and bad connection state for textbox

---

sass/responsive/_mobile.scss

PLT-8554 - Updating reply arrow issue
https://mattermost.atlassian.net/browse/PLT-8554

PLT-8554 - Updating reply arrow issue

---

components/admin_console/brand_image_setting.jsx
components/admin_console/brand_image_setting/brand_image_setting.jsx
components/admin_console/brand_image_setting/upload_button.jsx
components/admin_console/custom_brand_settings.jsx
tests/components/admin_console/brand_image_setting/__snapshots__/upload_button.test.jsx.snap
tests/components/admin_console/brand_image_setting/upload_button.test.jsx
utils/constants.jsx

- Fix text of upload button when uploading custom brand image
- Removed unnecessary state
- add `UploadButton` (stateless functional component)
Jira ticket: [PLT-8361](https://mattermost.atlassian.net/browse/PLT-8361)

[PLT-8361] Fix text of upload button when uploading custom brand image

---

components/integrations/components/installed_outgoing_webhook.jsx
tests/components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
tests/components/integrations/installed_outgoing_webhook.test.jsx

- Fix JS error on outgoing webhook search
- Update test
Jira ticket: [PLT-8555](https://mattermost.atlassian.net/browse/PLT-8555)

[PLT-8555] Fix JS error on outgoing webhook search

---

components/header_footer_template/header_footer_template.jsx
sass/base/_structure.scss
sass/layout/_footer.scss
sass/responsive/_mobile.scss
tests/components/__snapshots__/header_footer_template.test.jsx.snap

PLT-8328 - Updating onboarding pages
https://mattermost.atlassian.net/browse/PLT-8328

PLT-8328 - Updating onboarding pages

---

components/select_team/components/select_team_item.jsx
sass/base/_structure.scss
sass/routes/_signup.scss

PLT-8328 - Fixing scroll issue on onboarding pages
https://mattermost.atlassian.net/browse/PLT-8328

PLT-8328 - Fixing scroll issue on onboarding

---

components/channel_members_dropdown/channel_members_dropdown.jsx

Disable remove button after the first click to prevent multiple request
(Note: On master, we might have to add loading indicator as well)
Jira ticket: [PLT-8561](https://mattermost.atlassian.net/browse/PLT-8561)

[PLT-8561] Disable remove button after the first click to prevent multiple request

---

components/user_settings/manage_languages.jsx

https://mattermost.atlassian.net/browse/ICU-632

Fix JS errors when switching languages

---

utils/utils.jsx

Fixes active state of dropdown

Fix active state for dropdown

---

sass/responsive/_mobile.scss
utils/utils.jsx

PLT-8459 - Fixing search bar styles on mobile
https://mattermost.atlassian.net/browse/PLT-8459

PLT-8459 - Fixing search bar styles on mobile

---

package.json
yarn.lock

Quick fix: Bump redux to 917fbf0

Quick fix: Bump redux to 917fbf0

---

components/popover_list_members/popover_list_members.jsx
tests/components/__snapshots__/popover_list_members.test.jsx.snap
tests/components/popover_list_members.test.jsx

Fix DM error when opening from popover list by changing value of data attribute from object to string (teamId).
Also, added unit test.
Jira ticket: [PLT-8614](https://mattermost.atlassian.net/browse/PLT-8614)

[PLT-8614] Change value of data attribute from object to string

---

stores/channel_store.jsx

Fixed typo for last viewed event constant under **stores/channel_store.jsx**
N/A

Fixed typo for last viewed event

---

components/post_view/post_info/post_info.jsx
components/post_view/post_time.jsx
components/rhs_comment.jsx
components/rhs_root_post.jsx
components/search_results_item/search_results_item.jsx
tests/components/__snapshots__/search_results_item.test.jsx.snap
utils/utils.jsx

We were using Utils.isMobile before which only checks screen size instead of UserAgent.isMobile which checks the device
https://mattermost.atlassian.net/browse/ICU-613

ICU-613 Allow clicking post timestamps on desktop web view

---

webpack.config.js

Fix SyntaxError: Unexpected token ')'
Without this fix the master won't run.
-

Fix syntax error

---

components/channel_members_modal/channel_members_modal.jsx
components/channel_members_modal/index.js
tests/components/__snapshots__/channel_members_modal.test.jsx.snap
tests/components/channel_members_modal.test.jsx

Quick fix: JS error on `showInviteModal` of type `function` supplied to `ChannelMembersModal`, expected `boolean`
none

Quick fix: JS error on `showInviteModal` of type `function` supplied to `ChannelMembersModal`, expected `boolean`

---

package.json
yarn.lock

I forgot these changes when I merged my other PR
https://mattermost.atlassian.net/browse/ICU-631

ICU-631 Updated mattermost-redux to change how mention keys are retrieved

---

components/create_post/create_post.jsx
tests/components/create_post/create_post.test.jsx

The reactions reply to the last replyable post.
[XYZ-64](https://mattermost.atlassian.net/browse/XYZ-64)

XYZ-64: Add reactions to the last replyable post

---

actions/file_actions.jsx
components/create_comment/create_comment.jsx
components/create_post/create_post.jsx
components/file_upload/file_upload.jsx
components/file_upload/index.js
tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
tests/components/create_post/__snapshots__/create_post.test.jsx.snap
tests/components/create_post/create_post.test.jsx
tests/components/file_upload/__snapshots__/file_upload.test.jsx.snap
tests/components/file_upload/file_upload.test.jsx

Migrate file upload to be pure and use Redux.
[mattermost-server/issues/7789](https://github.com/mattermost/mattermost-server/issues/7789)

Migrate file upload to be pure and use Redux

---

components/svg/attachment_icon.jsx
sass/components/_files.scss
sass/layout/_post.scss

PLT-8632 - UI fixes for file thumbnails
https://mattermost.atlassian.net/browse/PLT-8632

PLT-8632 - UI fixes for file thumbnails

---

components/create_post/create_post.jsx
components/create_post/index.js
tests/components/create_post/create_post.test.jsx

Make createPost (now onSubmitPost) of CreatePost component into redux-styled props
Jira ticket: [ICU-612](https://mattermost.atlassian.net/browse/ICU-612)

[ICU-612] Make createPost (now onSubmitPost) of CreatePost component into redux-styled props

---

sass/layout/_headers.scss

ICU-619 - Updating quotes in header
https://mattermost.atlassian.net/browse/ICU-619

ICU-619 - Updating quotes in header

---

components/root.jsx

https://mattermost.atlassian.net/browse/ABC-203

Don't pre-emptively redirect to /login. Wait for the redirect at render time.

---

actions/global_actions.jsx
components/needs_team/index.js
components/needs_team/needs_team.jsx
components/sidebar/sidebar_channel/index.js
package.json
stores/channel_store.jsx
stores/team_store.jsx
yarn.lock

Sometimes when the window got focus the current channel wasn't marked as read, seems that the problem was a bad sync between the redux store and ChannelStore, with this PR we are using only the redux store to mark channels as read/unread
https://mattermost.atlassian.net/browse/ICU-654

[ICU-654] Fix unreads not clearing

---

components/sidebar/sidebar_channel/index.js
components/sidebar/sidebar_channel/sidebar_channel.jsx
tests/components/sidebar/__snapshots__/sidebar_channel.test.jsx.snap

https://mattermost.atlassian.net/browse/PLT-8684

PLT-8684 Fixed DM links in channel sidebar

---

components/backstage/backstage_controller.jsx
components/backstage/index.js
components/emoji/emoji_list/emoji_list.jsx
components/emoji/emoji_page.jsx
components/needs_team/needs_team.jsx

Scroll to top when paging in custom emoji management. Also refactored BackstageController to use the redux pattern.
https://mattermost.atlassian.net/browse/ABC-209

ABC-209 Scroll to top when paging in custom emoji management

---

components/file_attachment.jsx
components/file_attachment_list/file_attachment_list.jsx
components/file_preview.jsx
components/single_image_view.jsx
components/view_image.jsx
utils/constants.jsx
utils/utils.jsx

This is just a code refactor to easily compare file types.
none

Add `FileTypes` constant

---

components/sidebar/sidebar.jsx
tests/utils/channel_utils.test.jsx
utils/channel_utils.jsx

The main problem was that it would start looking for the next unread channel by looking at the current channel, seeing that it was unread, and then switching to it (which does nothing), so we now skip the current channel and move on to the next one.
https://mattermost.atlassian.net/browse/ICU-692

ICU-692 Fixed alt+shift+arrow hotkey

---

yarn.lock

loadash changed a bit too but I just ran `yarn upgrade mattermost-redux`

Upgrade mattermost-redux to latest

---

actions/team_actions.jsx

Removed redirect when team settings are updated. As far as I can tell, this behaviour has been in place for a few releases now. 
https://mattermost.atlassian.net/browse/PLT-8687

PLT-8687: Changing team settings sends the user to Town Square

---

package.json
yarn.lock

Redux PR: https://github.com/mattermost/mattermost-redux/pull/392
https://mattermost.atlassian.net/browse/ICU-653
- Has redux changes (please link)

ICU-653 Stopped filtering out join/leave messages about the current user

---

components/about_build_modal/about_build_modal.jsx
sass/components/_files.scss
sass/layout/_post.scss
tests/components/__snapshots__/about_build_modal.test.jsx.snap
tests/components/about_build_modal.test.jsx
utils/utils.jsx

ICU-704 - Space between label and value version
ICU-700 - Thumbnail css improvements
https://mattermost.atlassian.net/browse/ICU-704
https://mattermost.atlassian.net/browse/ICU-700

Minor UI fixes

---

components/sidebar/index.js
components/user_settings/user_settings_modal.jsx
components/user_settings/user_settings_sidebar/index.js
utils/constants.jsx

Requires a server PR: https://github.com/mattermost/mattermost-server/pull/8211
https://mattermost.atlassian.net/browse/ICU-715

ICU-715 Change ExperimentalGroupUnreadChannels setting to allow for default on/off

---

components/error_page/index.jsx

Checks error page signatures. If the signature isn't valid, the `message`, `service`, and `title` parameters are ignored.
Tagging "DO NOT MERGE" as the server PR should be merged first (but it's ready to be merged after that).
https://mattermost.atlassian.net/browse/ABC-132

ABC-132: verify error page parameters

---

yarn.lock

Bump redux to take effect change for v4.7 bug fix
- https://github.com/mattermost/mattermost-redux/commit/52a6c1869b61c6b2fccc549d7b3e1bedd0cbd928

[ICU-705] Bump redux to take effect change for v4.7 bug fix

---

components/admin_console/server_logs/log_list.jsx
components/admin_console/server_logs/logs.jsx
i18n/en.json
sass/routes/_admin-console.scss

* Add paging to system console log viewer
* Set default value of per_paging for logs to 1000
[PLT-6896](https://mattermost.atlassian.net/browse/PLT-6896)
[#6724](https://github.com/mattermost/mattermost-server/issues/6724)
* [PLT\-6896 per\-paging for logs by kaakaa · Pull Request \#7903 · mattermost/mattermost\-server](https://github.com/mattermost/mattermost-server/pull/7903)
* [PLT\-6896 Fix request parameters for \`/logs\` by kaakaa · Pull Request \#336 · mattermost/mattermost\-redux](https://github.com/mattermost/mattermost-redux/pull/336)

PLT-6896 Add paging to system console log viewer

---

components/single_image_view.jsx
sass/components/_files.scss

ICU-720 - Single image thumbnails are not cropping appropriately 
ICU-721 - Rounding all corners for single file thumbnails
https://mattermost.atlassian.net/browse/ICU-720
https://mattermost.atlassian.net/browse/ICU-721

[ICU-720] Fix cropping of images below minimum dimension

---

components/profile_picture.jsx
components/profile_popover.jsx
components/setting_picture.jsx
tests/plugins/__snapshots__/pluggable.test.jsx.snap

Add alt to all profile images
Github: https://github.com/mattermost/mattermost-server/issues/8033
Jira: https://mattermost.atlassian.net/browse/PLT-7690

[PLT-7690] Add alt to profile images

---

sass/layout/_post.scss

Increased z-index of the new message indicator
https://mattermost.atlassian.net/browse/PLT-8704

PLT-8704 - Increased z-index of the new message indicator

---

components/post_view/post_image.jsx

So they get proxied properly.
https://mattermost.atlassian.net/browse/ABC-245
https://github.com/mattermost/mattermost-server/issues/8222

ABC-245: Respect proxy settings for inline image previews

---

package.json
yarn.lock

Changes for this PR are here: https://github.com/mattermost/mattermost-redux/pull/399
This PR should not be merged until those changes are
https://mattermost.atlassian.net/browse/ICU-736

ICU-736 Try to load emojis surrounded by other text

---

components/root.jsx

Looks like it got left out when the react router changes came in, I just re-added the same code back in what I think is an appropriate place.
https://mattermost.atlassian.net/browse/ABC-246

ABC-246 Redirect to landing pages on iOS and Android mobile browsers

---

actions/global_actions.jsx
components/needs_team/needs_team.jsx

Fix issue on leaving a team where it doesn't succeed. It happens on redirect where channel name (default channel) is on URL while channel's current ID is not set on store.
Jira ticket: [ICU-739](https://mattermost.atlassian.net/browse/ICU-739)

[ICU-739] Fix issue on leaving a team

---

components/admin_console/admin_console.jsx
components/admin_console/admin_sidebar/admin_sidebar.jsx

Add compliance secction to admin_console and move message export and data
retention sections to this new compliance section.
[XYZ-5](https://mattermost.atlassian.net/browse/XYZ-5)

XYZ-5 New compliance section in admin_console

---

components/admin_console/gitlab_settings.jsx

https://mattermost.atlassian.net/browse/PLT-8777

PLT-8777 Fixed typo in i18n string

---

components/more_direct_channels/more_direct_channels.jsx

Fix note on adding DM/GM
- Only show `This will start a new conversation. If you’re adding a lot of people, consider creating a private channel instead.` when it's an existing channel.
Jira ticket: [PLT-8780](https://mattermost.atlassian.net/browse/PLT-8780)

[PLT-8780] Fix note on adding DM/GM

---

components/file_attachment.jsx
components/file_attachment_list/file_attachment_list.jsx
sass/layout/_post.scss
tests/components/__snapshots__/file_attachment.test.jsx.snap

Fix single image view display.
Also fix styles in compact display mode:
Before:
After:
Jira ticket: [PLT-8775](https://mattermost.atlassian.net/browse/PLT-8775)

[PLT-8775] Fix single image view display and styles in compact display mode

---

actions/global_actions.jsx
components/error_page/index.jsx
components/file_upload/index.js
components/needs_team/needs_team.jsx
components/permalink_view.jsx

Passing the last known location before clicking on a permalink so if the post was actually deleted we can go back to the last known location.
https://mattermost.atlassian.net/browse/ICU-766

ICU-766 Fix go back from deleted permalink

---

actions/websocket_actions.jsx
yarn.lock

Fixes:
* Editing a non-loaded custom emoji into a post
* Receiving a reaction for a non-loaded custom emoji
No ticket but approved by @esethna.

Fix two corner cases for emoji loading

---

sass/routes/_get-app.scss

MM-8004 - Mobile landing page not scrolling IOS
https://mattermost.atlassian.net/browse/MM-8004

MM-8004 - Mobile landing page not scrolling IOS

---

components/select_team/select_team.jsx

Do not show deleted open team at team selection list
Jira ticket: [MM-9603](https://mattermost.atlassian.net/browse/MM-9603)

[MM-9603] Do not show deleted open team at team selection list

---

components/post_view/post_body_additional_content.jsx
components/post_view/post_image.jsx
utils/post_utils.jsx

I had missed these other image requests before.
https://mattermost.atlassian.net/browse/ABC-245

ABC-245: Fix some more image proxying / mixed content issues

---

actions/global_actions.jsx
components/admin_console/storage_settings.jsx
components/channel_header/channel_header.jsx
components/file_upload/file_upload.jsx
components/logged_in.jsx
components/login/login_controller.jsx
components/more_direct_channels/index.js
components/more_direct_channels/more_direct_channels.jsx
components/navbar/navbar.jsx
components/root.jsx
components/sidebar/sidebar.jsx
components/signup/signup_controller.jsx
i18n/en.json
i18n/fr.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/ru.json
i18n/zh-CN.json
i18n/zh-TW.json
package.json
sass/responsive/_mobile.scss
sass/responsive/_tablet.scss
stores/modal_store.jsx
tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
utils/constants.jsx
yarn.lock

PR's from release-4.7 for master

T-3 Merge release-4.7 into master

---

components/single_image_view.jsx
sass/components/_files.scss

Fix cropping of single image preview of very wide or tall image
Jira ticket: [MM-9606](https://mattermost.atlassian.net/browse/MM-9606)

[MM-9606] Fix cropping of single image preview of very wide or tall image

---

actions/post_actions.jsx
components/sidebar_right/sidebar_right.jsx

Now flagging/unflagging a post with the RHS open to flagged posts will only send one request instead of 4.
https://mattermost.atlassian.net/browse/MM-8555

MM-8555 Fix duplicate get flagged posts requests

---

tests/utils/policy_roles_adapter.test.jsx
utils/policy_roles_adapter.js

See full description in server PR: https://github.com/mattermost/mattermost-server/pull/8303
https://mattermost.atlassian.net/browse/MM-9618

MM-9618: Don't change default role permissions for policy.

---

components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
components/sidebar_right_menu/sidebar_right_menu.jsx
tests/utils/policy_roles_adapter.test.jsx
utils/channel_intro_messages.jsx
utils/policy_roles_adapter.js

Add checking for ADD_USER_TO_TEAM permission always you are trying to invite a user to a team.
[MM-8825](https://mattermost.atlassian.net/browse/MM-8825)

MM-8825: Make consistent INVITE_USER and ADD_USER_TO_TEAM permissions checking

---

actions/websocket_actions.jsx

Client compatibility changes for https://github.com/mattermost/mattermost-server/pull/8307

MM-8681 Adding client ability to use separate websocket endpoint.

---

components/post_view/post_time.jsx

Quickfix for what I broke with my recent commit and got unnoticed by reviewers.

Fix showing AM/PM in post time when in 12-hours clock mode

---

actions/admin_actions.jsx
components/admin_console/email_connection_test/email_connection_test.jsx
components/admin_console/email_connection_test/index.js
components/admin_console/email_settings.jsx
tests/components/admin_console/email_connection_test/__snapshots__/email_connection_test.test.jsx.snap
tests/components/admin_console/email_connection_test/email_connection_test.test.jsx

move test email to a component
N/A

Move Test Email to a component

---

components/select_team/select_team.jsx

Fix the logout button on select_team screen. The fix is based on the
mfa_controller implementation of the same behavior.
[MM-8970](https://mattermost.atlassian.net/browse/MM-8970)

MM-8970: Fix the logout button on select_team screen

---

components/post_view/post_attachment.jsx
yarn.lock

Render and request emojis in message attachments.
https://mattermost.atlassian.net/browse/MM-9659

MM-9659 Render and request emojis in message attachments

---

components/emoji_picker/components/emoji_picker_item.jsx
sass/components/_emojisprite.scss
sass/components/_emoticons.scss
sass/layout/_post.scss
utils/utils.jsx

MM-8002 - Fixing emoji picker space at the bottom
MM-8425 - Markdown helptext on second line
https://mattermost.atlassian.net/browse/MM-8002
https://mattermost.atlassian.net/browse/MM-8425

Minor Ui improvements

---

components/create_post/create_post.jsx
components/delete_post_modal.jsx
components/edit_post_modal/edit_post_modal.jsx
tests/components/create_post/create_post.test.jsx
tests/components/edit_post_modal.test.jsx

Fix delete button not getting focused when coming from the edit modal after opening it with keyboard shortcuts.
https://mattermost.atlassian.net/browse/MM-8009

MM-8009 Fix delete button not getting focused from edit modal

---

utils/markdown/renderer.jsx

Simply updating the regex to look for links of the form `<mattermost>/<team>/messages/...`
https://mattermost.atlassian.net/browse/MM-9678

MM-9678 Open new DM/GM channel links in the current tab

---

components/sidebar_right/sidebar_right.jsx

Fix weird behaviors in the RHS (Bad full screen sidebar, and bad close on team change).
[MM-9680](https://mattermost.atlassian.net/browse/MM-9680) and [MM-9682](https://mattermost.atlassian.net/browse/MM-9682)

Reverting ICU-745 and MM-9149 to fix (To solve MM-9680 and MM-9682)

---

components/profile_popover.jsx

Related to https://mattermost.atlassian.net/browse/MM-9677

Fixed Send Message link in profile popover

---

sass/layout/_webhooks.scss

MM-9658 - Fixing bot messages
https://mattermost.atlassian.net/browse/MM-9658

MM-9658 - Fixing bot messages

---

sass/layout/_sidebar-left.scss
sass/layout/_team-sidebar.scss

Fixes the regression caused by #547. 
https://mattermost.atlassian.net/browse/MM-8219

MM-8219 Fix expanded RHS overlay not covering team sidebar

---

components/channel_header/channel_header.jsx
components/channel_header/components/header_icon_wrapper.jsx
components/channel_header/index.js
components/search_bar/search_bar.jsx
i18n/en.json
sass/layout/_headers.scss
sass/responsive/_tablet.scss
tests/components/channel_header/components/__snapshots__/header_icon_wrapper.test.jsx.snap
tests/components/channel_header/components/header_icon_wrapper.test.jsx
utils/utils.jsx

Update channel header based on:
- UX Design: 4.8 v3 - https://projects.invisionapp.com/share/2JFXM7453AF#/screens/280506516
- follow up discussion at https://pre-release.mattermost.com/core/pl/y7x4in1nxpfzpkcxjoa6g5q49c
Jira ticket: [MM-9685](https://mattermost.atlassian.net/browse/MM-9685)

[MM-9685] Update channel header

---

components/create_comment/create_comment.jsx
components/create_post/create_post.jsx
components/file_upload/file_upload.jsx
tests/components/create_post/create_post.test.jsx
tests/components/file_upload/file_upload.test.jsx

Add force focus to textbox on handleFileUploadChange which is   especially important to mobile classic app
Jira ticket: [MM-8008](https://mattermost.atlassian.net/browse/MM-8008)

[MM-8008] Add force focus to textbox on handleFileUploadChange which is   especially important to mobile classic app

---

components/login/login_controller/login_controller.jsx

For better UX, in the login page, add the autofocus into the login field

Add the autofocus into the login field in login page

---

.eslintrc.json

Remove a duplicate max-nested-callbacks key in the .eslintrc.json file

Remove a duplicate max-nested-callbacks key in the .eslintrc.json file

---

components/post_view/post_list.jsx

The main change here is that we now return from `componentDidUpdate` after `initialScroll` which is what we did pre-4.7. Here's hoping this actually works.
https://mattermost.atlassian.net/browse/MM-9599

MM-9599 Don't update scroll position immediately after initial scroll

---

actions/global_actions.jsx
components/delete_post_modal.jsx
components/dot_menu/dot_menu.jsx
components/dot_menu/dot_menu_item.jsx
components/rhs_comment/rhs_comment.jsx

Fixes [#8336](https://github.com/mattermost/mattermost-server/issues/8336)
[MM-9663](https://mattermost.atlassian.net/browse/MM-9663)

Return cursor to reply thread input box after deleting a reply from the right-hand sidebar (#8336)

---

components/announcement_bar/announcement_bar.jsx
components/announcement_bar/index.js
utils/constants.jsx

Revert announcement bar APIv3 notice

---

components/sidebar_right/sidebar_right.jsx
components/webrtc/controller/webrtc_controller.jsx

Place focus to search_bar input after clicking search icon on tablet view.
Jira ticket: [MM-9757](https://mattermost.atlassian.net/browse/MM-9757)

[MM-9757] Place focus to search_bar input after clicking search icon on tablet view

---

components/emoji_picker/components/emoji_picker_item.jsx
sass/components/_emojisprite.scss
sass/components/_emoticons.scss

MM-9704 - Updating custom emoji css
https://mattermost.atlassian.net/browse/MM-9704

MM-9704 - Updating custom emoji css

---

actions/global_actions.jsx

Handle permalinks pointing to incorrect teams.
https://mattermost.atlassian.net/browse/MM-8564

MM-8564 Handle permalinks pointing to incorrect teams

---

actions/post_actions.jsx

Alright, I'm not super happy with this solution but it'll have to do for now since the proper solution needs a ton of changes (new reducers, better and more actions, etc.).
The root of the problem (thanks to @lieut-data for narrowing it down btw) was that any time a post got flagged or unflagged there would be a race between those optimistic actions and the call out to get the list of flagged posts from the server.
This fixes it by dispatching the proper action and removing the unneeded server request. I said I'm not happy with it because we're using a single set of actions and one reducer to handle/store all the state for post searches, flagged posts and pinned posts. Which makes this very messy.
The ticket to do this all properly is here https://mattermost.atlassian.net/browse/MM-9793 …

MM-9775 Fix race when flagging/unflagging posts

---

components/create_comment/create_comment.jsx

Don't clear comment if there was a server error.
[MM-9672](https://mattermost.atlassian.net/browse/MM-9672)

MM-9672: Don't update draft state if there was a server error.

---

components/post_view/post_add_channel_member/index.js
components/post_view/post_add_channel_member/post_add_channel_member.jsx
tests/components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.jsx.snap
tests/components/post_view/post_add_channel_member/post_add_channel_member.test.jsx

Fix "add user to channel" from RHS when viewing different channel on center
Jira ticket: [MM-9785](https://mattermost.atlassian.net/browse/MM-9785)

[MM-9785] Fix "add user to channel" from RHS when viewing different channel on center

---

components/create_comment/create_comment.jsx
components/create_post/create_post.jsx
components/file_upload/file_upload.jsx
components/file_upload/index.js

Fix error when removing file which is on going upload
Jira ticket: [MM-9783](https://mattermost.atlassian.net/browse/MM-9783)

[MM-9783] Fix error when removing file which is on going upload

---

components/channel_view/index.js
components/create_post/index.js
components/sidebar/sidebar_channel/index.js
components/sidebar_right_menu/index.js
yarn.lock

Following up on https://github.com/mattermost/mattermost-redux/pull/419.
None.

Leverage preferences getInt selector

---

components/profile_popover/index.js
tests/plugins/__snapshots__/pluggable.test.jsx.snap

Fix regression in connecting config.ShowEmailAddress
https://mattermost.atlassian.net/browse/MM-9763

MM-9763: fix regression in connecting config.ShowEmailAddress

---

components/post_markdown/system_message_helpers.jsx

Show username in "removed from team" system message.
https://mattermost.atlassian.net/browse/MM-9780

MM-9780: Show name in "removed from team" system message.

---

components/dot_menu/dot_menu.jsx
tests/components/dot_menu/__snapshots__/dot_menu_mobile.test.jsx.snap

Don't show the "Flag" option in dot menu for System Messages.
https://mattermost.atlassian.net/browse/MM-9756

MM-9756: Don't show flag in menu on system messages.

---

actions/views/create_comment.jsx
components/create_comment/create_comment.jsx
tests/redux/actions/views/create_comment.test.jsx

Fix RHS focus when deleting and editing posts.
https://mattermost.atlassian.net/browse/MM-9743

MM-9743 Fix RHS focus when deleting and editing posts

---

components/autosize_textarea.jsx
components/quick_input.jsx
utils/user_agent.jsx

Good ole IE11
Tested on IE11/Windows 7, Chrome/Windows 7, IE11/Windows 10, Edge/Windows 10, Firefox/Windows 10, Chrome/Windows 10, Safari/MacOS 10.12.6, Chrome/MacOS 10.12.6, and Mattermost Desktop App/Windows 10
https://mattermost.atlassian.net/browse/MM-9819

MM-9819 Kept cursor in the correct place on IE11/Windows 7 when typing

---

components/admin_console/compliance_reports/index.js

Fix typo on license checking for compliance reports.
[MM-9825](https://mattermost.atlassian.net/browse/MM-9825)

MM-9825: Show again compliance reports

---

components/sidebar_right/sidebar_right.jsx

Fix search bar focus after clicking pinned or flagged post button
Jira ticket: [MM-9848](https://mattermost.atlassian.net/browse/MM-9848)

[MM-9848] Fix search bar focus after clicking pinned or flagged post button

---

actions/global_actions.jsx

Fix blank channel header when leaving team. Still don't know why the react router code wasn't being triggered but this will work for now.
https://mattermost.atlassian.net/browse/MM-9818

MM-9818 Fix blank channel header when leaving team

---

components/emoji/emoji_list/emoji_list.jsx
i18n/en.json

Updating help text on custom emoji creation page.
https://mattermost.atlassian.net/browse/MM-9821

Updating help text on custom emoji creation page

---

Makefile

Looks like #918 accidentally broke `make stop`

Fix make stop

---

tests/components/post_view/__snapshots__/post_attachment.test.jsx.snap
tests/components/post_view/post_attachment.test.jsx

Add component test to PostAttachment, follow PR for https://github.com/mattermost/mattermost-webapp/pull/926
none

Add component test to PostAttachment

---

components/sidebar/sidebar.jsx

Remove duplicate calls of channel and members on switch of team.
https://mattermost.atlassian.net/browse/MM-9758:

Fix duplicate calls on switch

---

.eslintrc.json
components/admin_console/admin_console.jsx
components/backstage/backstage_controller.jsx
components/channel_layout/channel_identifier_router.jsx
components/channel_view/channel_view.jsx
components/claim/claim_controller.jsx
components/create_team/create_team.jsx
components/help/help_controller.jsx
components/integrations/commands_container/commands_container.jsx
components/mfa/mfa_controller/mfa_controller.jsx
components/needs_team/needs_team.jsx
components/permalink_view/permalink_view.jsx

Explicitly define prop-types of "match" from react-router.
~~(Note: I'll rebase this after https://github.com/mattermost/mattermost-webapp/pull/987 is merged.)~~ DONE
none

Define prop-types of "match" from react-router

---

sass/components/_status-icon.scss

Fixes DM status icon bounce on hover
[MM-9942](https://mattermost.atlassian.net/browse/MM-9942)

[MM-9942]: Fix DM status icon bounce on hover

---

components/channel_header/channel_header.jsx
components/permissions_gates/channel_permission_gate/channel_permission_gate.jsx
components/permissions_gates/system_permission_gate/system_permission_gate.jsx
components/permissions_gates/team_permission_gate/team_permission_gate.jsx

Bug fixes for #5 and #6 on [Google Doc](https://docs.google.com/spreadsheets/d/16FGD3gk_UgS3g4-gXLnPeXCrPAucN437p_ekUWLkfYc/edit#gid=216183139).
[MM-9932](https://mattermost.atlassian.net/browse/MM-9932)

MM-9932: Multiple advanced permissions bug fixes.

---

components/channel_members_dropdown/index.js

Adds missing constant

---

components/post_view/index.js
tests/redux/actions/views/create_comment.test.jsx
yarn.lock

Not sure what all the additions to yarn.lock is about, I just ran `yarn upgrade mattermost-redux` so I assume it's correct.
https://mattermost.atlassian.net/browse/MM-9801

MM-9801 Update mattermost-redux and handle perf changes

---

actions/channel_actions.jsx
components/sidebar/sidebar_channel/index.js
components/suggestion/switch_channel_provider.jsx
stores/channel_store.jsx
yarn.lock

Changes for redux circular dependency fix.
n/a

Circular dep fix

---

components/member_list_team/index.js

Fix missing import for TeamMembers list.

---

components/svg/mentions_icon.jsx
components/svg/search_icon.jsx
sass/components/_search.scss
sass/layout/_headers.scss
sass/layout/_sidebar-right.scss
sass/responsive/_tablet.scss

MM-9950 - Updating header UI
https://mattermost.atlassian.net/browse/MM-9950

MM-9950 - Updating header UI

---

actions/post_actions.jsx
components/delete_post_modal/delete_post_modal.jsx
components/delete_post_modal/index.js
tests/components/delete_post_modal.test.jsx

This accidentally got broken in #989 (and I missed it in the review).
https://mattermost.atlassian.net/browse/MM-9969

MM-9969 Re-add post removal for user performing the delete

---

components/quick_input.jsx

https://mattermost.atlassian.net/browse/MM-9955

MM-9955 Fixed caret position in desktop app search box

---

components/navbar/navbar.jsx
tests/components/navbar/__snapshots__/navbar.test.jsx.snap

Add ChannelPermissionGate to navbar's add members
none

Add ChannelPermissionGate to navbar's add members

---

components/suggestion/switch_channel_provider.jsx

https://mattermost.atlassian.net/browse/MM-9998

MM-9998 Show current user in channel switcher

---

sass/layout/_headers.scss
sass/layout/_sidebar-left.scss

Updating styles for muted channel

Updating styles for muted channel

---

components/file_attachment_list/file_attachment_list.jsx
components/single_image_view/index.js
components/single_image_view/single_image_view.jsx

Fix single image preview when posted at RHS
- by resizing image preview when RHS opened or closed.
Jira ticket: [MM-9989](https://mattermost.atlassian.net/browse/MM-9989)

[MM-9989] Fix single image preview when posted at RHS

---

components/admin_console/system_users/system_users.jsx

We were requesting a page we already had, not the next one.
https://mattermost.atlassian.net/browse/MM-10037

MM-10037 Request next page of users correctly in system console

---

components/sidebar/index.js
components/sidebar/sidebar.jsx
tests/components/sidebar/sidebar.test.jsx

Fix ALT+UP/ALT+DOWN channel switch
[MM-10040](https://mattermost.atlassian.net/browse/MM-10040)

MM-10040: Fix ALT+UP/ALT+DOWN channel switch

---

sass/components/_videos.scss

MM-10004 - Making youtube corners rounded
https://mattermost.atlassian.net/browse/MM-10004

MM-10004 - Making youtube corners rounded

---

actions/global_actions.jsx
components/admin_console/manage_tokens_modal/index.js
components/admin_console/system_users/system_users.jsx
components/delete_post_modal/delete_post_modal.jsx
components/post_view/post_add_channel_member/post_add_channel_member.jsx
components/rhs_comment/index.js
components/rhs_comment/rhs_comment.jsx
components/rhs_root_post/index.js
components/rhs_root_post/rhs_root_post.jsx
components/rhs_thread/rhs_thread.jsx
components/sidebar/index.js
components/sidebar/sidebar.jsx
components/view_image/view_image.jsx
stores/suggestion_store.jsx
tests/components/__snapshots__/delete_post_modal.test.jsx.snap
tests/components/__snapshots__/view_image.test.jsx.snap
tests/components/delete_post_modal.test.jsx
tests/components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
tests/components/sidebar/sidebar.test.jsx
tests/stores/suggestion_store.test.jsx

Merging release-4.9 into master

Merge49intomaster

---

components/admin_console/email_settings.jsx

Add some fields dependency in the email notifications configuration form.
[MM-10110](https://mattermost.atlassian.net/browse/MM-10110)

MM-10110: Fix email notifications enable/disable dependencies

---

components/channel_header/channel_header.jsx
sass/layout/_headers.scss
sass/layout/_sidebar-right.scss
sass/responsive/_mobile.scss

MM-10058 - Fixing Rhs UI on mobile
MM-10006 - Fixing long name channel titles
MM-10050 - Mute icon displaying on second line fix
https://mattermost.atlassian.net/browse/MM-10058
https://mattermost.atlassian.net/browse/MM-10006
https://mattermost.atlassian.net/browse/MM-10050

Release 4.9 bug fixes

---

components/admin_console/email_connection_test/email_connection_test.jsx
i18n/en.json

Server returns the "Connection unsuccessful:" part now.
https://mattermost.atlassian.net/browse/MM-8180

MM-8180 Remove connection unsuccessful message now that server returns it

---

components/select_team/index.js
components/select_team/select_team.jsx

If not present loads roles for use by system permission gate.
[MM-10129](https://mattermost.atlassian.net/browse/MM-10129)

MM-10129: Loads roles for use by system permission gate if not loaded.

---

utils/post_utils.jsx

Not allowing to edit other posts through the interface.
[MM-10136](https://mattermost.atlassian.net/browse/MM-10136)

MM-10136: Not allowing to edit others posts in the interface

---

components/message_with_additional_content.jsx
components/rhs_comment/index.js
components/rhs_comment/rhs_comment.jsx
components/rhs_root_post/index.js
components/rhs_root_post/rhs_root_post.jsx

Removes additional content around a post if the post was deleted.
[MM-10111](https://mattermost.atlassian.net/browse/MM-10111)

MM-10111: Omits PostBodyAdditionalContent if post is deleted.

---

components/profile_popover/profile_popover.jsx
sass/responsive/_mobile.scss
tests/plugins/__snapshots__/pluggable.test.jsx.snap

MM-10106 - Extra line in user popover if no email
MM-10100 - Mobile post menu in search style issue
MM-10097 - Fixing footer link styling on mobile
https://mattermost.atlassian.net/browse/MM-10106
https://mattermost.atlassian.net/browse/MM-10100
https://mattermost.atlassian.net/browse/MM-10097

Release 4.9 fixes

---

actions/team_actions.jsx
actions/user_actions.jsx
components/login/login_controller/login_controller.jsx
components/signup/signup_controller/signup_controller.jsx
components/signup/signup_email/signup_email.jsx
components/signup/signup_ldap/signup_ldap.jsx

Replacing hash usage with token for invitations. It depends on the PR mattermost/mattermost-server#8604 and the PR mattermost/mattermost-redux#463
[MM-9779](https://mattermost.atlassian.net/browse/MM-9779)

Replacing hash usage with token for invitations

---

components/channel_header/channel_header.jsx
components/navbar/navbar.jsx
components/profile_popover/profile_popover.jsx
components/user_settings/advanced/index.js
components/user_settings/advanced/user_settings_advanced.jsx
components/webrtc/notification/index.js
components/webrtc/notification/webrtc_notification.jsx
i18n/en.json
utils/constants.jsx
utils/utils.jsx

Remove WebRTC end user settings (account settings) and let the WebRTC functionality toggled on/off at the admin settings (system console) only
Jira ticket: [MM-9984](https://mattermost.atlassian.net/browse/MM-9984)

[MM-9984] Remove WebRTC end user settings

---

actions/user_actions.jsx

Users who are in a lot channels/GMs/DMs were experiencing long initial load times for the app. The main culprit based on my profiling is too many requests being processed at one-time during the already CPU intensive start-up of the app. `await`ing on each of the requests to get the user for the GMs prevents some spamming of requests and let's the app start-up a bit quicker by letting more important requests have a chance to complete first.
Bit of background info: For each GM the user is in we make a request to get the users in that channel so that we can properly display their names and the number of users in the GM on the sidebar. Users who have been on the system for a long time can have hundreds of these GMs.
__Note that this is the first step in improvements here, I plan on making …

MM-10134 (part 1) Remove unneeded populate channel functions and await on each GM users request

---

components/select_team/select_team.jsx
components/signup/signup_email/signup_email.jsx

Sign-up and team joining was broken by #1109. This fixes it.

Fix sign-up and team joining

---

components/integrations/abstract_incoming_webhook.jsx
i18n/en.json
tests/components/integrations/__snapshots__/abstract_incoming_hook.test.jsx.snap

See https://pre-release.mattermost.com/core/pl/5qupqstgbbrb9j9kwhpy8z87oh for context

Update channel parameter help text on incoming webhooks set up page

---

actions/user_actions.jsx

MM-10134 (4.9) Remove unneeded populate channel functions and await on each GM users request

---

NOTICE.txt

Adding dependencies to NOTICE.txt

---

components/admin_console/system_users/list/index.js

The selector was passed in by accident instead of the action.
https://mattermost.atlassian.net/browse/MM-10327

MM-10327 Fix accidental pass in of getUser selector instead of action

---

i18n/en.json

Thanks to Michael Longo for reporting it!

Fix Incomming > Incoming typo

---

sass/layout/_navigation.scss
sass/layout/_post.scss

MM-10453 - Updating channel title on mobile
MM-10452 - Updating blockquotes
https://mattermost.atlassian.net/browse/MM-10452
https://mattermost.atlassian.net/browse/MM-10453

Bug fixes v2

---

components/create_comment/create_comment.jsx
components/create_post/create_post.jsx
tests/components/create_comment/create_comment.test.jsx
tests/components/create_post/create_post.test.jsx

Fix focus of textbox for mobile classic app on file upload, both for center post and comment thread.
Jira ticket: 
- [MM-10102](https://mattermost.atlassian.net/browse/MM-10102)
- [MM-10103](https://mattermost.atlassian.net/browse/MM-10103)

[MM-10102 and MM-10103] Fix focus of textbox for mobile classic app on file upload

---

sass/layout/_team-sidebar.scss

Updating team sidebar badge position
**Before:**
**After:**

Updating team sidebar badge position

---

components/setting_picture.jsx
tests/components/__snapshots__/setting_picture.test.jsx.snap
tests/components/setting_picture.test.jsx

- Fix blank image after selecting user's profile image.
- Add unit test
Jira ticket: [MM-10494](https://mattermost.atlassian.net/browse/MM-10494)

[MM-10494] Fix blank image after selecting user's profile image

---

components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
components/admin_console/schema_admin_settings.jsx
tests/components/admin_console/__snapshots__/custom_plugin_settings.test.jsx.snap

Same as #1186 but for 4.9.
https://mattermost.atlassian.net/browse/MM-10492
https://github.com/mattermost/mattermost-server/issues/8713

MM-10492 (4.9) Fix saving plugin settings in the system console

---

sass/components/_search.scss
sass/layout/_headers.scss
sass/layout/_sidebar-right.scss

MM-9753 - Header UI updates
https://mattermost.atlassian.net/browse/MM-9753

MM-9753 - Header UI updates

---

components/navbar/navbar.jsx
tests/components/navbar/__snapshots__/navbar.test.jsx.snap
tests/components/navbar/navbar.test.jsx

Remove delete channel link for town-square in mobile classic apps.
[MM-10514](https://mattermost.atlassian.net/browse/MM-10514)

MM-10514: Remove delete channel link for town-square in classic app

---

components/at_mention/at_mention.jsx
components/at_mention/index.jsx
tests/components/at_mention/__snapshots__/at_mention.test.jsx.snap
tests/components/at_mention/at_mention.test.jsx
tests/utils/formatting_at_mentions.test.jsx
utils/post_utils.jsx
utils/text_formatting.jsx

This applies to anything that looks like an at mention but doesn't actually mention a user. I've also added a load of unit tests to prevent regressions in this area.
https://mattermost.atlassian.net/browse/MM-10539

MM-10539 Fixed uppercase non-user mentions appearing in lowercase

---

components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx

Same as #1207 but for 4.9.
https://mattermost.atlassian.net/browse/MM-10492

MM-10492 (4.9) Fix switching between plugin settings

---

sass/layout/_post.scss
sass/responsive/_tablet.scss

MM-10489 - Fixing quotation marks in compact view
https://mattermost.atlassian.net/browse/MM-10489

MM-10489 - Fixing quotation marks in compact view

---

components/admin_console/admin_definition.jsx
i18n/en.json

Remove API v3 setting from the system console.
https://mattermost.atlassian.net/browse/MM-8708

MM-8708 Remove API v3 setting from the system console

---

components/post_view/post_body_additional_content/post_body_additional_content.jsx

https://mattermost.atlassian.net/browse/MM-10617

MM-10617 Fixed checking if a link is an image

---

package-lock.json
package.json

Updated commit of mattermost-redux which fixes combined posts which ignores custom and other post types
Note: not sure why this has many changes in `package-lock.json`. Noticed that it's changing from `^` to fix version.
none

Updated commit of mattermost-redux which fixes combined posts which ignores custom and other post types

---

sass/components/_permissions.scss

Fixed flickering on hover in the admin console permissions trees

Fix flickering

---

components/admin_console/password_settings.jsx
components/admin_console/reset_password_modal/reset_password_modal.jsx
components/claim/components/ldap_to_email.jsx
components/claim/components/oauth_to_email.jsx
components/setting_item_max.jsx
components/signup/signup_email/signup_email.jsx
components/user_settings/security/user_settings_security.jsx
tests/utils/utils.test.jsx
utils/utils.jsx

Move system console > password settings to team edition.
Jira ticket: [MM-10479](https://mattermost.atlassian.net/browse/MM-10479)

[MM-10479] Move system console > password settings to team edition

---

components/admin_console/permission_schemes_settings/index.jsx
components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
components/team_selector_modal/team_selector_modal.jsx
tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap

Post merge fixes

---

components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
tests/components/admin_console/permission_schemes_settings/permission_team_scheme_settings.test.jsx

Some extra fixes needed for the scheme edition.

Some extra fixes needed for the scheme edition.

---

i18n/en.json

Changes display name of permission checkbox label.
[MM-10719](https://mattermost.atlassian.net/browse/MM-10719)

MM-10719: Changes display name of permission checkbox label.

---

components/admin_console/permission_schemes_settings/permission_team_scheme_settings/index.jsx
components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
tests/components/admin_console/permission_schemes_settings/permission_team_scheme_settings.test.jsx

Now the frontend is aware of the change in the PR mattermost/mattermost-server#8894
[MM-10757](https://mattermost.atlassian.net/browse/MM-10757)

MM-10757: Changing default_{channel,team}_{user,admin}_role to names instead of ids

---

sass/components/_permissions.scss

See discussion: https://pre-release.mattermost.com/core/pl/3nprjb78j7g33egzanmjoghefh

Tweak to opacity in permissions CSS

---

components/admin_console/admin_sidebar/admin_sidebar.jsx
components/admin_console/custom_brand_settings.jsx
components/common/site_name_and_description.jsx
components/create_team/create_team.jsx
components/create_team/index.js
components/login/login_controller/index.js
components/login/login_controller/login_controller.jsx
components/select_team/index.js
components/select_team/select_team.jsx
components/signup/signup_email/index.js
components/signup/signup_email/signup_email.jsx
components/signup/signup_ldap/signup_ldap.jsx
tests/components/common/__snapshots__/site_name_and_description.test.jsx.snap
tests/components/common/site_name_and_description.test.jsx
tests/components/create_team/__snapshots__/create_team.test.jsx.snap
tests/components/create_team/create_team.test.jsx
tests/components/select_team/__snapshots__/select_team.test.jsx.snap
tests/components/select_team/select_team.test.jsx

Move custom branding to TE
Jira ticket: [MM-10718](https://mattermost.atlassian.net/browse/MM-10718)

[MM-10718] Move custom branding to TE

---

components/admin_console/permission_schemes_settings/permission_system_scheme_settings/index.jsx
components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
components/admin_console/permission_schemes_settings/permission_team_scheme_settings/index.jsx
components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
tests/components/admin_console/permission_schemes_settings/permission_system_scheme_settings.test.jsx
tests/components/admin_console/permission_schemes_settings/permission_team_scheme_settings.test.jsx

Add confirmation modal when try to exit from team scheme or system scheme edit
panel, and you have unsaved changes.
[MM-10770](https://mattermost.atlassian.net/browse/MM-10770)

MM-10770: Add confirm modal on exit team scheme and system scheme edition

---

components/post_view/post_info/post_info.jsx
components/rhs_comment/rhs_comment.jsx
components/rhs_root_post/rhs_root_post.jsx
components/search_results_item/search_results_item.jsx
components/svg/attachment_icon.jsx
components/svg/emoji_icon.jsx
components/team_sidebar/components/team_button.jsx
components/team_sidebar/team_sidebar_controller.jsx
package-lock.json
sass/components/_dropdown.scss
sass/components/_search.scss
sass/layout/_post-right.scss
sass/layout/_post.scss
sass/layout/_team-sidebar.scss
tests/components/__snapshots__/search_results_item.test.jsx.snap
utils/utils.jsx

MM-10500 - Implementing Relay chat UI updates
https://mattermost.atlassian.net/browse/MM-10500
Have a look @esethna. 
Did all the changes in the ticket except the font on the user generated image. That has to be done on the server, so probably better for a dev to look at that. (that also has to be done as a separate PR to the server repo).

MM-10500 - Implementing Relay chat UI updates

---

components/markdown_image.jsx

I intended this to be nullable in the first place, but I forgot to check that properly.

Fixed null pointer when calling onHeightReceived

---

package-lock.json
package.json

Required for recently merged webapp PR.

Adds next Redux commit.

---

components/more_direct_channels/index.js
components/more_direct_channels/more_direct_channels.jsx
tests/components/__snapshots__/more_direct_channels.test.jsx.snap
tests/components/more_direct_channels.test.jsx

Fix missing users' status indicators on more DM modal
Jira ticket: [MM-10511](https://mattermost.atlassian.net/browse/MM-10511)

[MM-10511] Fix missing users' status indicators on more DM modal

---

sass/components/_tooltip.scss
sass/layout/_post.scss
sass/responsive/_mobile.scss
utils/utils.jsx

MM-10733 - Updating UI for posts
MM-10780 - Updating emoji reaction tooltip
https://mattermost.atlassian.net/browse/MM-10733
https://mattermost.atlassian.net/browse/MM-10780

Minor 5.0 Bug fixes

---

utils/utils.jsx

I'm really looking forward to coming up with a better theming system than the current one since figuring out the order that rules apply for this is rough
https://mattermost.atlassian.net/browse/MM-10713

MM-10713 Fixed collapsed post colour in permalink view

---

components/team_sidebar/components/team_button.jsx
sass/layout/_post.scss
sass/layout/_team-sidebar.scss
sass/responsive/_tablet.scss
utils/utils.jsx

MM-10795 - Fixing post control menu overlap
MM-10798 - Fixing notification badge on teams sidebar
https://mattermost.atlassian.net/browse/MM-10798
https://mattermost.atlassian.net/browse/MM-10795

Minor 5.0 bugs

---

sass/layout/_post-right.scss
sass/layout/_post.scss
sass/responsive/_mobile.scss

MM-10875 - Fixing post controls in IE11
https://mattermost.atlassian.net/browse/MM-10875

MM-10875 - Fixing post controls in IE11

---

components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx

Do not show link previews for system messages.
https://mattermost.atlassian.net/browse/MM-10921

MM-10921 Do not show link previews for system messages

---

sass/layout/_post.scss

fix post menu

---

components/youtube_video/youtube_video.jsx

I didn't bother changing it in code since we're actually consistent with how it's capitalized, so that would've been a lot of unnecessary turnover
https://mattermost.atlassian.net/browse/MM-10962

MM-10962 Fix capitalization of YouTube

---

package-lock.json
package.json

Update mattermost-redux with fix on duplicated user of combined system messages
Jira ticket: [MM-10929](https://mattermost.atlassian.net/browse/MM-10929)

[MM-10929] Update mattermost-redux with fix on duplicated user on combined system messages

---

components/channel_header/channel_header.jsx
sass/layout/_headers.scss

https://mattermost.atlassian.net/browse/MM-10873

MM-10873 Preserve newlines in channel headers

---

components/user_settings/general/user_settings_general.jsx
tests/e2e/pages/accountSettingsModalPage.js
tests/e2e/tests/3_sidebarLeft/accountSettingsGeneral.action.js
tests/e2e/tests/3_sidebarLeft/accountSettingsModalPage.element.js

Add E2E for Account Settings > General Settings
Jira ticket: [MM-9392](https://mattermost.atlassian.net/browse/MM-9392)

[MM-9392] Add E2E for Account Settings > General Settings

---

components/post_profile_picture/index.jsx
components/post_profile_picture/post_profile_picture.jsx
components/post_view/post/post.jsx
components/profile_picture.jsx
components/rhs_comment/rhs_comment.jsx
components/rhs_root_post/rhs_root_post.jsx
components/search_results_item/search_results_item.jsx
tests/components/__snapshots__/search_results_item.test.jsx.snap
tests/components/search_results_item.test.jsx
utils/post_utils.jsx

Note that most of these changes are to combine the logic for rendering profile pictures since it was mostly identical between the post components so that I wouldn't need to make these same changes in a dozen different places.
https://mattermost.atlassian.net/browse/MM-10444

 MM-10444 Passed overridden post profile picture through image proxy

---

actions/websocket_actions.jsx
plugins/registry.js

Add plugin API for registering websocket event handlers.
https://mattermost.atlassian.net/browse/MM-9674

MM-9674 Add plugin API for registering websocket event handlers

---

components/emoji_picker/emoji_picker.jsx

Fix JS error when repeatedly clicking reactions.
https://mattermost.atlassian.net/browse/MM-10810

MM-10810 Fix JS error when repeatedly clicking reactions

---

components/admin_console/admin_definition.jsx

Fixes config name; changes value from text to number.
[MM-11091](https://mattermost.atlassian.net/browse/MM-11091)

MM-11091: Fixes config value name; changes value type.

---

sass/layout/_post.scss

MM-10877 - Updating edited behaviour IE11
https://mattermost.atlassian.net/browse/MM-10877

MM-10877 - Updating edited behaviour IE11

---

components/sidebar/header/dropdown/sidebar_header_dropdown.jsx

Fix external links in sidebar dropdown.
https://mattermost.atlassian.net/browse/MM-11075

MM-11075: Fix external link redirects.

---

components/create_post/create_post.jsx
utils/constants.jsx
utils/utils.jsx

Original PR: https://github.com/mattermost/mattermost-webapp/pull/1319 but delay wasn't long enough for desktop app.
Note: This proves that it's not just an issue of putting the call to the top of the stack. There's a duplicate post event coming through somewhere and that's the real root cause that needs to be fixed.
[MM-10647](https://mattermost.atlassian.net/browse/MM-10647)

MM-10647: Fixes "composing" Korean character duplicate post bug.

---

components/navbar/navbar.jsx
components/team_sidebar/components/team_button.jsx
sass/base/_structure.scss
sass/layout/_headers.scss
sass/layout/_post.scss
sass/responsive/_mobile.scss
sass/routes/_signup.scss
tests/components/navbar/__snapshots__/navbar.test.jsx.snap
utils/utils.jsx

MM-11140 - Updating reaction and file thumbnail color
MM-11164 - Updating mute icon
MM-11167 - Updating scroll on mobile
MM-11169 - Updating team buttons on mobile
MM-11191 - Updating navbar buttons
https://mattermost.atlassian.net/browse/MM-11140
https://mattermost.atlassian.net/browse/MM-11164
https://mattermost.atlassian.net/browse/MM-11167
https://mattermost.atlassian.net/browse/MM-11169
https://mattermost.atlassian.net/browse/MM-11191
[Place an '[x]' (no spaces) in all …

Release 5.1 fixes

---

components/sidebar/sidebar_channel/index.js

Hides deleted users from LHS
[MM-11170](https://mattermost.atlassian.net/browse/MM-11170)

MM-11170 Fix to remove unknown users from sidebar

---

components/needs_team/index.js

* Join a team if team does not exist in user teams instead of teamsList
(MM-11238)[https://mattermost.atlassian.net/browse/MM-11238]

MM-11238 Fix user joining a team though url

---

components/login/login_controller/login_controller.jsx

Fix SAML link buttons to respect subpath.
https://mattermost.atlassian.net/browse/MM-11246

MM-11246: fix saml link buttons to respect subpath

---

components/channel_layout/channel_identifier_router.jsx

* Use team id from store when joining channels as we even
pass nextProps and currentTeamId will not be correct
Fixes join of url from other teams.
[MM-11238](https://mattermost.atlassian.net/browse/MM-11238)

MM-11238 Fix channel url join from another team

---

tests/e2e/config.js
tests/e2e/tests/3_sidebarLeft/accountSettingsDisplay.action.js
tests/e2e/tests/3_sidebarLeft/accountSettingsGeneral.action.js

E2E: fix flaky tests on chrome
Jira ticket: [MM-11129](https://mattermost.atlassian.net/browse/MM-11129)

[MM-11129] E2E: fix flaky tests on chrome

---

components/post_view/post_list.jsx

This is some initial work I did while investigating some potential scrolling improvements

Refactor PostList to remove some state and use new lifecycle methods

---

components/channel_layout/channel_identifier_router.jsx
components/post_view/post/post.jsx

Final merge from `release-5.1` to `master`

Release 5.1 daily merge 20180716

---

components/analytics/team_analytics/team_analytics.jsx

Sort teams by display name on the Team Analytics admin console page.
[MM-11153](https://mattermost.atlassian.net/browse/MM-11153)

MM-11153: Sort teams by name in Team Analytics page

---

actions/websocket_actions.jsx

These where added to fix a problem that no longer exists.

MM-11313 Removing unnessisary client side calls on channel delete.

---

components/post_view/post_attachment.jsx
components/post_view/post_attachment_list.jsx
components/post_view/post_body_additional_content/post_body_additional_content.jsx
components/search_results_item/search_results_item.jsx
tests/components/__snapshots__/search_results_item.test.jsx.snap

Highlight search terms/matches in Slack-type post attachments.
https://mattermost.atlassian.net/browse/MM-10977

MM-10977: Search in attachment contents.

---

components/claim/components/oauth_to_email.jsx
i18n/en.json

n/a
[MM-11251](https://mattermost.atlassian.net/browse/MM-11251)

MM-11251: Pluralize word in translation.

---

sass/responsive/_mobile.scss

MM-11371 - Fixing sidebar spacing issue
https://mattermost.atlassian.net/browse/MM-11371

MM-11371 - Fixing sidebar spacing issue

---

components/analytics/team_analytics/index.js

Fix loading on team analytics on deleted team
mattermost/mattermost-server#9116

GH-9116: Fix loading on team analytics on deleted team

---

actions/user_actions.jsx
components/root/index.js
components/root/root.jsx

Fix issue with server ID not being set in diagnostics.
https://mattermost.atlassian.net/browse/MM-10999

MM-10999: Fix server ID setting race condition in diagnostics.

---

components/admin_console/elasticsearch_settings.jsx
i18n/en.json

Remove message from Elasticsearch system console page saying that you need to restart the server for changes to take effect.
https://mattermost.atlassian.net/browse/MM-11243
**Waiting for server & enterprise changes before merging this.**

MM-11243: Remove message about Elasticsearch restart.

---

components/about_build_modal/index.js
components/access_history_modal/index.js
components/admin_console/jobs/index.jsx
components/admin_console/manage_roles_modal/index.js
components/admin_console/permission_schemes_settings/edit_post_time_limit_button/index.jsx
components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/index.jsx
components/admin_console/revoke_token_button/index.js
components/admin_console/server_logs/index.js
components/channel_info_modal/index.js
components/channel_invite_modal/index.js
components/delete_channel_modal/index.js
components/file_attachment_list/index.js
components/get_post_link_modal/index.js
components/get_public_link_modal/index.js
components/get_team_invite_link_modal/index.js
components/header_footer_template/index.js
components/modal_controller/index.js
components/post_view/commented_on_files_message/index.js
components/post_view/failed_post_options/index.js
components/post_view/post_attachment_opengraph/index.js
components/profile_popover/index.js
components/reset_status_modal/index.js
components/team_general_tab/index.js
components/team_members_dropdown/index.js
components/team_members_modal/index.js

Just clean up `...ownProps` in container since this is a recurring comment to PRs that it's not needed to pass on.

Clean up: get rid off ...ownProps

---

components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
i18n/en.json

Adds config to "Users and Teams" admin console page.
@jespino Refactoring into declarative admin console code is going to have to be another story due to time restraints. Story for it: https://mattermost.atlassian.net/browse/MM-11082
[MM-11068](https://mattermost.atlassian.net/browse/MM-11068)

MM-11068: Adds config for TeamSettings.ViewArchivedChannels.

---

components/dot_menu/dot_menu.jsx

Fix JS error on handleDropdownOpened of DotMenu
none

Fix JS error on handleDropdownOpened of DotMenu

---

components/authorize.jsx

These need to be hard redirects.

Fix OAuth redirect

---

components/sidebar/sidebar_channel/index.js
components/sidebar/sidebar_channel/sidebar_channel.jsx
components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
sass/routes/_loading.scss
tests/components/sidebar/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
tests/components/sidebar/sidebar_channel_button_or_link.test.jsx
utils/utils.jsx

Fixes user loading in LHS with loader instead of someone text.
[MM-11051](https://mattermost.atlassian.net/browse/MM-11051)

[MM-11051] LHS: Fix misleading loading text

---

package-lock.json
package.json

Upgrade mattermost-redux library

Upgrade mattermost-redux

---

components/suggestion/suggestion_box.jsx
components/suggestion/suggestion_list.jsx
stores/suggestion_store.jsx

This reverts commit 0dfd4506526a15029e62055788bca4ff7781f79f, as it was
identified as the cause of
https://mattermost.atlassian.net/browse/MM-11548 and
https://mattermost.atlassian.net/browse/MM-11547.
https://mattermost.atlassian.net/browse/MM-11547
https://mattermost.atlassian.net/browse/MM-11548

Revert "Allow duplicate terms for suggestion box (#1501)"

---

i18n/en.json

https://pre-release.mattermost.com/core/pl/3noxkm7hjtfkmbwgumrsbwceme

Fix incorrect closed bracket in Markdown formatted string

---

actions/websocket_actions.jsx

Adds delete at value to websocket event.
[MM-11510](https://mattermost.atlassian.net/browse/MM-11510)

MM-11510: Adds delete at value to websocket event.

---

actions/notification_actions.jsx
components/post_view/post_body/post_body.jsx
tests/utils/markdown/remove_markdown.test.jsx
utils/markdown/index.js
utils/text_formatting.jsx

-  Remove entity to show up in desktop notification and "commented on"
-  Do not show emoji in "commented on"
Jira tickets: [MM-11557](https://mattermost.atlassian.net/browse/MM-11557) & [MM-11571](https://mattermost.atlassian.net/browse/MM-11571)

[MM-11557 & MM-MM-11571] Remove entity to show up in desktop notification and "commented on", and do not show emoji in "commented on"

---

tests/utils/markdown/remove_markdown.test.jsx
utils/markdown/index.js

Fix JS error on stripMarkdown
none

[MM-11491] Fix JS error on stripMarkdown

---

package-lock.json
package.json

Update redux.
[MM-11586](https://mattermost.atlassian.net/browse/MM-11586)
n/a

MM-11586: Updates redux.

---

actions/global_actions.jsx

Fixes landing onto last viewed team and channel on a revisit
[MM-11591](https://mattermost.atlassian.net/browse/MM-11591)

[MM-11591] Fix last channel storage key

---

components/login/login_controller/login_controller.jsx

Add back button to the Mfa login screen
[MM-11572](https://mattermost.atlassian.net/browse/MM-11572)

MM-11572: Add back button to the Mfa login screen

---

sass/responsive/_tablet.scss

MM-11633 - Updating position of post controls
https://mattermost.atlassian.net/browse/MM-11633

MM-11633 - Updating position of post controls

---

components/about_build_modal/about_build_modal.jsx
i18n/en.json
tests/components/__snapshots__/about_build_modal.test.jsx.snap

Change platform to server in AboutModal
From:
To:
Jira ticket: [MM-11615](https://mattermost.atlassian.net/browse/MM-11615)

[MM-11615] Change platform to server in AboutModal

---

package-lock.json
package.json

It updates redux to fix the MM-11576 bug (fixed in mattermost-redux)
[MM-11576](https://mattermost.atlassian.net/browse/MM-11576)

MM-11576: Updates redux.

---

actions/global_actions.jsx
components/about_build_modal/about_build_modal.jsx
components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
components/sidebar_right_menu/sidebar_right_menu.jsx
components/suggestion/channel_mention_provider.jsx
components/suggestion/switch_channel_provider.jsx
i18n/en.json
package-lock.json
package.json
sass/responsive/_tablet.scss
tests/components/__snapshots__/about_build_modal.test.jsx.snap
tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap

Merge from `release-5.2` to `master`

Release 5.2 daily merge 20180810

---

components/more_channels/index.js
components/more_channels/more_channels.jsx
tests/components/__snapshots__/more_channels.test.jsx.snap
tests/components/more_channels.test.jsx

Do not show archived channels in the "more..." public channels selector
[MM-11605](https://mattermost.atlassian.net/browse/MM-11605)

MM-11605: Do not show archived channels in the "more..." public channels selector

---

components/post_view/post_attachment.jsx
components/post_view/show_more/index.js
components/post_view/show_more/show_more.jsx
tests/components/post_view/__snapshots__/post_attachment.test.jsx.snap
tests/components/post_view/__snapshots__/post_message_view.test.jsx.snap
tests/components/post_view/show_more.test.jsx
tests/plugins/__snapshots__/post_type.test.jsx.snap

Fix long post when opening/expanding RHS.
Jira ticket: [MM-11682](https://mattermost.atlassian.net/browse/MM-11682)

[MM-11682] Fix long post when opening/expanding RHS

---

utils/post_utils.jsx

Re-enable editing others posts as per permissions system.
https://mattermost.atlassian.net/browse/MM-11695

MM-11695: Re-enable editing others posts as per permissions system.

---

components/multiselect/multiselect.jsx

Fix JS error and only show member count if there are users and total count
Jira ticket: [MM-11702](https://mattermost.atlassian.net/browse/MM-11702)

[MM-11702] Fix JS error and only show member count if there are users and total count

---

utils/constants.jsx

Reverts mattermost/mattermost-webapp#1575

Revert "MM-11707: Removes edit_others_posts permission from the Reset Default…"

---

package-lock.json
package.json
utils/constants.jsx

Merge from `release-5.2` to `master`

Merge release-5.2-20180817135450

---

components/post_markdown/post_markdown.jsx
package-lock.json

Send entire post to webhook.
n/a

Send entire post to webhook.

---

components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
components/delete_channel_modal/index.js
i18n/en.json

Merge from `release-5.2` to `master`

Merge release-5.2-20180824093640

---

selectors/storage.js

Adds missing import.
[MM-11554](https://mattermost.atlassian.net/browse/MM-11554)

MM-11554: Adds missing import.

---

components/post_view/channel_intro_message/channel_intro_message.jsx
i18n/en.json

Changes Town Square intro message when it's read-only.
[MM-11659](https://mattermost.atlassian.net/browse/MM-11659)

MM-11659: Changes intro message for read-only town square.

---

actions/user_actions.jsx
components/reset_status_modal/reset_status_modal.jsx
components/status_dropdown/index.jsx
components/status_dropdown/status_dropdown.jsx

Before this commit, mattermost asked you if you want to get out of "Out
Of Office" state explicitly always, no matter if you set the flag "Don't
ask me again". Now if you select "Don't ask me again" It won't ask you
and use your preivous selected option.
[MM-11655](https://mattermost.atlassian.net/browse/MM-11655)

MM-11655: Don't ask me again fix

---

package-lock.json
package.json

Update redux to the last version.
[MM-11853](https://mattermost.atlassian.net/browse/11853)

MM-11853: Updates redux.

---

components/channel_layout/channel_identifier_router.jsx
package-lock.json
package.json

Mark GMs open when switching to them so they stay in the LHS.
https://mattermost.atlassian.net/browse/MM-11696

MM-11696 Mark GMs open when switching to them

---

components/user_settings/notifications/user_settings_notifications.jsx
tests/e2e/pages/accountSettingsModalPage.js
tests/e2e/tests/3_sidebarLeft/accountSettingsModalPage.element.js
tests/e2e/tests/3_sidebarLeft/accountSettingsNotification.action.js

Add E2E to account settings - notifications
Jira ticket: [MM-11604](https://mattermost.atlassian.net/browse/MM-11604)

[MM-11604] Add E2E to account settings - notifications

---

components/search_bar/search_bar.jsx
i18n/en.json

Small fixes on SearchBarComponent (and fixes MM-11639)
[MM-11639](https://mattermost.atlassian.net/browse/11639)

Small fixes on SearchBarComponent (and fixes MM-11639)

---

components/admin_console/generated_setting.jsx
sass/routes/_admin-console.scss

Allow to copy generated settings
[MM-11763](https://mattermost.atlassian.net/browse/11763)

MM-11763: Allow to copy generated settings

---

components/file_attachment_list/file_attachment_list.jsx
components/file_attachment_list/index.js
tests/components/__snapshots__/file_attachment_list.test.jsx.snap
tests/components/file_attachment_list.test.jsx

Merge from `release-5.3` to `master`

Merge release-5.3-20180903124816

---

components/login/login_controller/login_controller.jsx
components/suggestion/search_channel_provider.jsx
components/suggestion/switch_channel_provider.jsx

Daily merge from `release-5.3` to `master`

Release 5.3 daily merge 20180904

---

components/admin_console/message_export_settings.jsx
tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap

Add alphabetical order to Compliance export format selector
[MM-11849](https://mattermost.atlassian.net/browse/MM-11849)

MM-11849: Add alphabetical order to Compliance export format selector

---

tests/utils/markdown/remove_markdown.test.jsx
utils/markdown/index.js
utils/markdown/remove_markdown.js

Add space between line breaks includes cases on header, paragraph and code blocks.
Jira ticket: [MM-11927](https://mattermost.atlassian.net/browse/MM-11927)

[MM-11927] Add space between line breaks

---

components/suggestion/channel_mention_provider.jsx

Do not show not-member archived channels on mentions suggestion
[MM-11725](https://mattermost.atlassian.net/browse/11725)

MM-11725: Do not show not-member archived channels on mentions suggestion

---

components/file_upload/file_upload.jsx
tests/components/file_upload/file_upload.test.jsx

Fix file upload error on reaching max upload file
Jira ticket: [MM-12058](https://mattermost.atlassian.net/browse/MM-12058)

[MM-12058] Fix file upload error on reaching max upload file

---

package-lock.json
package.json

update redux commit

---

components/multiselect/multiselect.jsx
sass/components/_multi-select.scss
tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap

MM-11978 - Updating multi select hint
https://mattermost.atlassian.net/browse/MM-11978

MM-11978 - Updating multi select hint

---

components/sidebar/sidebar.jsx

- Replaces perfect scrollbar with the scrollbar used in the RHS
- Fixes issue on FF where scrolling was unusably slow
- Tested on all browsers we support (except safari)

MM-12047: Fix LHS unusably slow scrolling on FF

---

components/emoji/emoji_list/emoji_list.jsx
package-lock.json
package.json

Load needed profiles when emoji searching on the management screen.
https://mattermost.atlassian.net/browse/MM-11706

MM-11706 Load needed profiles when emoji searching

---

components/search_results/index.jsx

Hide the archived messages on search results when ViewArchivedChannels is disabled.
[MM-12004](https://mattermost.atlassian.net/browse/MM-12004)

MM-12004: Hide the archived messages on search results when ViewArchivedChannels is disabled

---

sass/routes/_admin-console.scss

MM-11993 - Fixing LHS header height in system console
https://mattermost.atlassian.net/browse/MM-11993

MM-11993 - Fixing LHS header height in system console

---

components/admin_console/admin_definition.jsx
i18n/en.json

https://mattermost.atlassian.net/browse/MM-11508

MM-11508 Update help text for link previews admin console setting

---

components/suggestion/channel_mention_provider.jsx
components/suggestion/provider.jsx
tests/components/__snapshots__/quick_switch_modal.test.jsx.snap
tests/components/__snapshots__/textbox.test.jsx.snap

Close channel autocomplete if multiple tildes are typed.
https://mattermost.atlassian.net/browse/MM-11822

MM-11822 Close channel autocomplete if multiple tildes are typed

---

sass/components/_modal.scss

MM-12078 - Updating background for image content
https://mattermost.atlassian.net/browse/MM-12078

MM-12078 - Updating background for image content

---

sass/components/_popover.scss

MM-11983 - Updating list styling in channel header
https://mattermost.atlassian.net/browse/MM-11983

MM-11983 - Updating list styling in channel header

---

components/channel_header/channel_header.jsx
i18n/en.json
tests/components/__snapshots__/channel_header.test.jsx.snap
tests/components/channel_header.test.jsx

Add a mute/unmute toggle to channel header.
https://mattermost.atlassian.net/browse/MM-12048

MM-12048: Add mute/unmute to Channel Header Dropdown.

---

components/admin_console/plugin_management/plugin_management.jsx
tests/components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
tests/components/admin_console/plugin_management/plugin_management.test.jsx

bring back the settings button in the plugin admin  page
Jira: https://mattermost.atlassian.net/browse/MM-12167

[MM-12167] Bring back the settings button in the plugin admin  page

---

components/admin_console/admin_definition.jsx
i18n/en.json
utils/policy_roles_adapter.js

Allow to change the permission for edit the others posts on TE
[MM-11707](https://mattermost.atlassian.net/browse/MM-11707)

MM-11707: Allow to change the permission for edit the others posts on TE

---

sass/components/_files.scss

MM-12168 - Fixing file thumbnails for short images
https://mattermost.atlassian.net/browse/MM-12168

MM-12168 - Fixing file thumbnails for short images

---

components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
sass/components/_status-icon.scss
sass/layout/_navigation.scss
sass/layout/_sidebar-left.scss
sass/responsive/_mobile.scss
tests/components/sidebar/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap

MM-12103 - Updating sidebar items css
After my few recent changes, the badge in the sidebar was no longer appearing on the right, this fixes that.
https://mattermost.atlassian.net/browse/MM-12103

MM-12103 - Updating sidebar items css

---

components/sidebar/sidebar.jsx

- Fixes sidebar unread indicators not appearing and their jump on click not working. 
- Fixing scroll not resetting on team change.

MM-12203 MM-12226 Fixing sidebar unread indicators and scrolling behaviour.

---

sass/layout/_post.scss
utils/text_formatting.jsx

Webapp only. RN in progress.
Yes it's terrible. I know. I feel bad too. We need to fix our markdown stuff.
Dropped some of the complicity from the ticket, because of implementation difficulty.

MM-11956 Adding jumboemoji

---

package.json

Removing accidentally added acorn dependency

Removing accidentally added acorn dependency

---

sass/responsive/_mobile.scss

MM-12150 - Updating close icon on nav on IE
https://mattermost.atlassian.net/browse/MM-12150

MM-12150 - Updating close icon on nav on IE

---

components/navbar/index.js
components/navbar/navbar.jsx
sass/layout/_navigation.scss
tests/components/navbar/__snapshots__/navbar.test.jsx.snap
tests/components/navbar/navbar.test.jsx
utils/utils.jsx

Add mute icon to mobile view.
@asaadmahmood This PR is far from what is expected as I can't get the where it should be.  Only functionality is implemented.  Please help with the styling.  Many thanks!
Jira ticket: [MM-11162](https://mattermost.atlassian.net/browse/MM-11162)

[MM-11162] Add mute icon to mobile view

---

components/navbar/navbar_info_button/navbar_info_button.jsx
tests/components/navbar/__snapshots__/navbar_info_button.test.jsx.snap

Fix cursor on hover of navbar info icon.
See fix in action:
https://youtu.be/EzZlI_Pz-Bg
Jira ticket: [MM-12336](https://mattermost.atlassian.net/browse/MM-12336)

[MM-12336] Fix cursor on hover of navbar info icon

---

actions/global_actions.jsx
actions/websocket_actions.jsx
components/channel_header/channel_header.jsx
components/channel_header/index.js
components/channel_view/channel_view.jsx
components/channel_view/index.js
components/delete_channel_modal/delete_channel_modal.jsx
selectors/local_storage.js
stores/local_storage_store.jsx
tests/components/channel_header.test.jsx
tests/components/delete_channel_modal.test.jsx

Back to previous channel on archive
[MM-11577](https://mattermost.atlassian.net/browse/MM-11577)

MM-11577: Back to previous channel on archive

---

components/rhs_comment/index.js
components/rhs_comment/rhs_comment.jsx
components/rhs_thread/rhs_thread.jsx
sass/layout/_post.scss

Add support to display consecutive posts made by the same user in the RHS
@asaadmahmood please check the CSS for this
https://mattermost.atlassian.net/browse/MM-9463

Add Consecutive messages support in RHS

---

sass/components/_multi-select.scss
sass/responsive/_mobile.scss

MM-12241 - Updating help text on DM Modal
https://mattermost.atlassian.net/browse/MM-12241

MM-12241 - Updating help text on DM Modal

---

sass/components/_popover.scss

MM-12308 - Updating search popover styling
https://mattermost.atlassian.net/browse/MM-12308

MM-12308 - Updating search popover styling

---

components/admin_console/admin_definition.jsx
components/admin_console/schema_admin_settings.jsx

Accept direct values on isDissabled and isHidden

Accept direct values on isDissabled and isHidden

---

components/rhs_comment/rhs_comment.jsx
sass/layout/_post.scss
sass/layout/_sidebar-right.scss
sass/responsive/_tablet.scss

https://mattermost.atlassian.net/browse/MM-12377

Remove the reply bar in RHS

---

sass/layout/_webhooks.scss

MM-12351 - Updating default webhooks
https://mattermost.atlassian.net/browse/MM-12351

MM-12351 - Updating default webhooks appearance 

---

sass/layout/_sidebar-left.scss

MM-12265 - Updating sidebar item css
(This removes the underline from the sidebar items in the desktop app).
https://mattermost.atlassian.net/browse/MM-12265

MM-12265 - Updating sidebar item css

---

sass/base/_typography.scss
sass/components/_mentions.scss

MM-12217 - Updating autocomplete css
https://mattermost.atlassian.net/browse/MM-12217

MM-12217 - Updating autocomplete css

---

plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx

Pass channel and channel member to onClick handler for mobile channel header plugins in the same way it is done for non-mobile version.
https://mattermost.atlassian.net/browse/MM-12221

MM-12221: Pass channel and channel member to onClick handler for mobile channel header plugins.

---

components/more_channels/index.js
components/more_channels/more_channels.jsx
components/searchable_channel_list.jsx
tests/components/__snapshots__/more_channels.test.jsx.snap
tests/components/__snapshots__/searchable_channel_list.test.jsx.snap
tests/components/more_channels.test.jsx
tests/components/searchable_channel_list.test.jsx

Add loader for more_channels modal
Add loader when searching for channels
[MM-12283](https://mattermost.atlassian.net/browse/MM-12283)

MM-12283 Add loader for more_channels modal

---

sass/styles.scss

comment typo

---

tests/e2e/test.sh

Set required initial config for E2E
Jira ticket: [MM-11885](https://mattermost.atlassian.net/browse/MM-11885)

[MM-11885] Set required initial config for E2E

---

components/create_post/create_post.jsx

Fixes multiple uploads
[https://mattermost.atlassian.net/browse/MM-12443](MM-12443)

MM-12443 Fix multiple uploads fail issue

---

components/single_image_view/single_image_view.jsx
sass/components/_files.scss
tests/components/__snapshots__/single_image_view.test.jsx.snap

MM-12168 - Updating image thumbnail css
https://mattermost.atlassian.net/browse/MM-12168

MM-12168 - Updating image thumbnail css

---

components/admin_console/admin_definition.jsx

Avoid slash duplications on gitlab urls configuration
[MM-12420](https://mattermost.atlassian.net/browse/MM-12420)

MM-12420: Avoid slash duplications on gitlab urls configuration

---

components/post_view/post/post.jsx

Add onTouchStart event for triggering postAction in post.
[https://mattermost.atlassian.net/browse/MM-12219](MM-12219)

MM-12219 Message toolbar sometimes not displaying on ipad

---

actions/views/rhs.js
tests/redux/actions/views/rhs.test.js

Now we can find search results in archived channels.
[MM-12331](https://mattermost.atlassian.net/browse/MM-12331)

MM-12331: Fix listing of deleted channels on searches

---

components/user_settings/advanced/code_block_ctrl_enter_section/code_block_ctrl_enter_section.jsx
components/user_settings/advanced/join_leave_section/join_leave_section.jsx
tests/components/user_settings/advanced_tab/__snapshots__/code_block_ctrl_enter_section.test.jsx.snap
tests/components/user_settings/advanced_tab/__snapshots__/join_leave_section.test.jsx.snap
tests/components/user_settings/advanced_tab/code_block_ctrl_enter_section.test.jsx
tests/components/user_settings/advanced_tab/join_leave_section.test.jsx

Do not change setting on pressing cancel at Account Settings > Advanced > Enable Join/Leave or Code Block on Ctrl + Enter
Jira ticket: [MM-12473](https://mattermost.atlassian.net/browse/MM-12473)

[MM-12473] Do not change setting on pressing cancel at Account Settings > Advanced

---

actions/file_actions.jsx
components/create_comment/create_comment.jsx
components/create_comment/index.js
components/create_post/create_post.jsx
components/file_upload/file_upload.jsx
tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
tests/components/create_comment/create_comment.test.jsx
tests/components/create_post/create_post.test.jsx
tests/components/file_upload/file_upload.test.jsx

Fix uploads while reply switching in the RHS
[MM-12421](https://mattermost.atlassian.net/browse/MM-12421)

MM-12421: Fix uploads while reply switching in the RHS

---

package-lock.json
package.json

Update redux dependencies
Note: I check that this same commit in the release-5.4 have another hash, how we will update the dependencies for the release branch? 
We will push the change direct? 
@crspeller @enahum

Update redux for master

---

components/channel_header/channel_header.jsx
components/navbar/navbar.jsx
plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx
sass/components/_dropdown.scss
sass/layout/_navigation.scss
sass/responsive/_mobile.scss
tests/components/navbar/__snapshots__/navbar.test.jsx.snap
tests/plugins/__snapshots__/mobile_channel_header_plug.test.jsx.snap

MM-12150 - Updating x icon and plugins
https://mattermost.atlassian.net/browse/MM-12150

MM-12150 - Updating x icon and plugins

---

tests/components/create_post/create_post.test.jsx
tests/utils/post_utils.test.jsx
utils/post_utils.jsx

On Ctrl + Enter, just post the message if it has inline opening back ticks.
Note that I've submitted this on top of https://github.com/mattermost/mattermost-webapp/pull/1809 just to prevent merge conflict.  Will rebase after approval.
Jira ticket: [MM-11959](https://mattermost.atlassian.net/browse/MM-11959)

[MM-11959] Post the message if it has inline opening back ticks

---

components/team_sidebar/components/team_button.jsx
sass/components/_badge.scss
sass/components/_module.scss
sass/layout/_sidebar-left.scss
sass/layout/_team-sidebar.scss
utils/utils.jsx

MM-12499 - Updating badge icon
https://mattermost.atlassian.net/browse/MM-12499

MM-12499 - Updating badge icon

---

sass/routes/_signup.scss

MM-12338 - Updating line break on signup markdown
https://mattermost.atlassian.net/browse/MM-12338

MM-12338 - Updating line break on signup markdown

---

components/signup/signup_controller/index.js
components/signup/signup_controller/signup_controller.jsx
components/signup/signup_email/index.js
components/signup/signup_email/signup_email.jsx

Narrowly focused on removing the flux store usages.

Remove flux store usages from signup components

---

sass/layout/_navigation.scss
sass/layout/_sidebar-left.scss

MM-12524 - Updating badge position on desktop app
https://mattermost.atlassian.net/browse/MM-12524

MM-12524 - Updating badge position on desktop app

---

sass/base/_typography.scss
sass/components/_popover.scss
sass/layout/_post.scss

MM-12329 - Updating bullet points
https://mattermost.atlassian.net/browse/MM-12329

MM-12329 - Updating bullet point base styling

---

sass/components/_modal.scss
sass/responsive/_tablet.scss

MM-12547 - Fixing videos modal
https://mattermost.atlassian.net/browse/MM-12547

MM-12547 - Fixing videos modal

---

components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
components/admin_console/admin_navbar_dropdown/index.js
components/admin_console/admin_sidebar/admin_sidebar.jsx
components/admin_console/admin_sidebar_header/admin_sidebar_header.jsx
components/admin_console/admin_sidebar_header/index.js
components/admin_console/compliance_reports/compliance_reports.jsx
components/admin_console/compliance_reports/index.js
components/admin_console/reset_password_modal/index.js
components/admin_console/reset_password_modal/reset_password_modal.jsx
components/admin_console/system_users/index.js
components/admin_console/system_users/list/system_users_list.jsx
components/admin_console/system_users/system_users.jsx
components/admin_console/system_users/system_users_dropdown/index.js
components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
tests/components/admin_console/system_users/system_users.test.jsx

Remove flux store usages from the system console. Left in the ErrorStore usages as we'll need to figure out what we're doing with that first.
https://mattermost.atlassian.net/browse/MM-12492

MM-12492 Remove flux store usages from the system console

---

sass/components/_badge.scss
sass/responsive/_mobile.scss

MM-12572 - Fixing more unreads and badge on mobile
https://mattermost.atlassian.net/browse/MM-12572

MM-12572 - Fixing more unreads and badge on mobile

---

components/search_results/index.jsx
components/search_results/search_results.jsx

Narrowly focused on just removing the user store.

Remove UserStore usage from search_results

---

components/suggestion/at_mention_provider.jsx
components/suggestion/channel_mention_provider.jsx

Narrowly focused on removing the flux store usages.

Remove flux store usages from suggestion

---

actions/user_actions.jsx
actions/views/root.js
components/mfa/confirm.jsx
components/root/index.js
components/root/root.jsx
components/signup/signup_controller/signup_controller.jsx
components/signup/signup_email/signup_email.jsx
tests/components/mfa/components/__snapshots__/confirm.test.jsx.snap
tests/components/mfa/components/confirm.test.jsx
tests/components/root/root.test.jsx

Most of this time was spent figuring out how some of these workflows actually worked.
https://mattermost.atlassian.net/browse/MM-12581

MM-12581 Switch UserActions.loadMe to redux

---

sass/responsive/_mobile.scss

MM-12654 - Updating padding for navbar dropdown
https://mattermost.atlassian.net/browse/MM-12654

MM-12654 - Updating padding for navbar dropdown

---

components/search_bar/search_bar.jsx
i18n/en.json
sass/components/_search.scss

MM-12319 - Updating x icon css in search bar
https://mattermost.atlassian.net/browse/MM-12319

MM-12319 - Updating x icon css in search bar

---

package-lock.json
package.json
store/index.js

Now this really sucks but after a ton of messing around with babel I couldn't get it to not optimize out Observable unless I actually imported it and then exported it on the window manually. If someone has any suggestions to try I'm very open to them.
https://mattermost.atlassian.net/browse/MM-12640

MM-12640 Hacky fix for zen-observable getting optimized out by babel

---

components/profile_popover/index.js
components/profile_popover/profile_popover.jsx
tests/plugins/__snapshots__/pluggable.test.jsx.snap
tests/plugins/pluggable.test.jsx

Left the webrtc store in because we're not sure what we're doing with that yet.

Remove UserStore and TeamStore usages from profile_popover

---

actions/channel_actions.jsx
actions/views/channel.js
components/channel_invite_modal/channel_invite_modal.jsx
components/channel_invite_modal/index.js
components/channel_members_dropdown/channel_members_dropdown.jsx
components/channel_members_dropdown/index.js
tests/components/__snapshots__/channel_invite_modal.test.jsx.snap
tests/components/__snapshots__/channel_members_dropdown.test.jsx.snap
tests/components/channel_invite_modal.test.jsx
tests/components/channel_members_dropdown.test.jsx

Migrate the actions to add/remove users to redux actions
Affected Areas:
* Add users to a channel using the channel menu action
* Remove users from a channel in manage channel members
https://mattermost.atlassian.net/browse/MM-12694

Migrate add/remove user from channel actions to redux

---

components/channel_header/channel_header.jsx
tests/components/__snapshots__/channel_header.test.jsx.snap

Fix for team id property access bug.
n/a

Fixes team id property access.

---

components/add_users_to_team/add_users_to_team.jsx
components/channel_invite_modal/channel_invite_modal.jsx
components/more_direct_channels/more_direct_channels.jsx
components/multiselect/multiselect.jsx
components/team_selector_modal/team_selector_modal.jsx
package-lock.json
package.json
sass/components/_multi-select.scss
sass/styles.scss
tests/components/add_users_to_team.test.jsx
tests/components/more_direct_channels.test.jsx
tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap

Updates react-select to the new major version and update our usage for the new API.
@lindy65 can you regression test the Add Users To Team, Add Users To Channel and More Direct Messages modals? The only expected difference is the little `x` will be on the right rather than the left for any selected users.
https://mattermost.atlassian.net/browse/MM-12647

MM-12647 Update react-select

---

actions/global_actions.jsx
tests/redux/actions/global_actions.test.js

Same as #1925 but for global_actions.jsx.

Remove flux store usages from global_actions.jsx

---

actions/integration_actions.jsx

Same as #1925 but for integration_actions.jsx.

Remove flux store usages from integration actions

---

actions/post_actions.jsx
components/dot_menu/index.js
components/post_view/post_flag_icon/index.js
components/post_view/post_flag_icon/post_flag_icon.js
components/post_view/post_info/post_info.jsx
components/rhs_comment/rhs_comment.jsx
components/rhs_root_post/rhs_root_post.jsx
components/search_results_item/search_results_item.jsx
tests/components/__snapshots__/search_results_item.test.jsx.snap
tests/components/post_view/__snapshots__/post_flag_icon.test.js.snap
tests/components/post_view/post_flag_icon.test.js
tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap

Update flagPost and unflagPost from PostActions and refactor PostFlagIcon component
Affected Areas:
- flagging and unflagging of post at center, reply and search views like pinned, flagged, search post, etc.
@lindy65 @DHaussermann I've already tested it and is working fine but may I request for a smoke test to make sure I'm not missing anything.  Thanks!
Jira ticket: [MM-12582](https://mattermost.atlassian.net/browse/MM-12582) & [MM-12744](https://mattermost.atlassian.net/browse/MM-12744)

[MM-12582 & MM-12744] Update flagPost and unflagPost from PostActions and refactor PostFlagIcon component

---

actions/team_actions.jsx

Same as #1925 but for team_actions.jsx.

Remove flux store usages from team_actions.jsx

---

components/at_mention/at_mention.jsx
components/emoji_picker/emoji_picker_overlay.jsx
tests/utils/position_utils.test.jsx
tests/utils/utils.test.jsx
utils/position_utils.jsx
utils/utils.jsx

* Move popOverOverlayPosition into new file

Fix for circular dependency in imports.

---

components/channel_layout/channel_identifier_router/actions.js
package-lock.json
package.json
tests/components/channel_identifier_router/actions.test.js

Fix switching to a channel on a different team with the same name. Regression only an issue on master.
https://mattermost.atlassian.net/browse/MM-12792

MM-12792 Fix switching to a channel on a different team with the same name

---

actions/integration_actions.jsx

Imported from the wrong file 😧 
https://mattermost.atlassian.net/browse/MM-12804

MM-12804 Fix slash commands

---

components/channel_layout/channel_identifier_router/actions.js
tests/components/channel_identifier_router/actions.test.js
utils/utils.jsx

Using the action by accident instead of the selector. Added some tests to cover this case.
https://mattermost.atlassian.net/browse/MM-12791

MM-12791 Fix switching to DM/GMs from notifications and other places

---

actions/file_actions.jsx
components/file_upload/file_upload.jsx
components/file_upload/index.js
tests/components/file_upload/file_upload.test.jsx

Convert file_actions to redux actions
[MM-12585](https://mattermost.atlassian.net/browse/MM-12585)

MM-12585 Complete migration of file_actions to redux actions

---

actions/channel_actions.jsx

As discussed with @enahum, just flipping these over to use the selectors and the global redux getState for now so we can get rid of the flux stores. Should make the conversion of these actions to redux actions a little easier as well.

Remove flux store usages from channel_actions.jsx

---

tests/utils/text_formatting.test.jsx
utils/text_formatting.jsx

Make hashtag highlighting case insensitive.
https://mattermost.atlassian.net/browse/MM-12838

MM-12838: Make hashtag highlighting case insensitive.

---

actions/command.js
actions/post_actions.jsx
tests/redux/actions/post_actions.test.js
utils/utils.jsx

Migrate searchForTerm into redux-style action.
- `/search [term]`
- search on hashtags by clicking the hashtag term (`#hashtagterm`)
@DHaussermann May I request for a regression test on this change?  Thanks!
Jira ticket: [MM-12715](https://mattermost.atlassian.net/browse/MM-12715)

[MM-12715] Migrate searchForTerm into redux-style action

---

sass/layout/_post.scss

MM-12772 - Updating post header css
https://mattermost.atlassian.net/browse/MM-12772

MM-12772 - Updating post header css

---

sass/layout/_post-right.scss

MM-12776 - Updating comments in RHS (compact view)
https://mattermost.atlassian.net/browse/MM-12776

MM-12776 - Updating comments in RHS (compact view)

---

utils/utils.jsx

MM-12796 - Updating emoji reaction hover effect
https://mattermost.atlassian.net/browse/MM-12796

MM-12796 - Updating emoji reaction hover effect

---

actions/channel_actions.jsx
actions/user_actions.jsx

Removes the current action and when is it used we now use the redux action for it
https://mattermost.atlassian.net/browse/MM-12704

Replace getChannelMembersForUserIds action with the redux action

---

sass/layout/_team-sidebar.scss

MM-12822 - Updating background css for team icons
https://mattermost.atlassian.net/browse/MM-12822

MM-12822 - Updating background css for team icons

---

README.md

Avoid devs to guess the IRC server we are talking about
N/A
N/A

Add link to Freenode

---

actions/channel_actions.jsx
actions/global_actions.jsx
actions/websocket_actions.jsx
tests/redux/actions/channel_actions.test.js

@saturninoabril let me know if there are more tests that I can add to this, I did try to do a bunch of stuff to test the inner functions and inner dispatches but I just wasn't able to
Affected areas: Everywhere that shows the channels of the user (eg. LHS) Ctrl+K, etc.. also when loading a permalink in a different window
https://mattermost.atlassian.net/browse/MM-12702

Migrate loadChannelsForCurrentUser action to redux

---

components/admin_console/email_settings.jsx

remove the function which should be removed from https://github.com/mattermost/mattermost-webapp/pull/1976

remove unused func - fix from https://github.com/mattermost/mattermost-webapp/pull/1976

---

package-lock.json
package.json

replace https://github.com/mattermost/mattermost-webapp/pull/1996/

update redux deps

---

components/admin_console/plugin_management/plugin_management.jsx

Fix JS error when uploading plugin.
https://mattermost.atlassian.net/browse/MM-12892

MM-12892 Fix JS error when uploading plugin

---

components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
package.json
tests/components/__snapshots__/team_general_tab.test.jsx.snap
tests/components/add_users_to_team.test.jsx
tests/components/admin_console/manage_teams_modal/__snapshots__/manage_teams_modal.test.jsx.snap
tests/components/admin_console/manage_teams_modal/manage_teams_modal.test.jsx
tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
tests/components/admin_console/permission_schemes_settings/permission_system_scheme_settings.test.jsx
tests/components/admin_console/permission_schemes_settings/permission_team_scheme_settings.test.jsx
tests/components/edit_post_modal.test.jsx
tests/components/more_direct_channels.test.jsx
tests/components/search_results_item.test.jsx
tests/components/suggestion/suggestion_box.test.jsx
tests/components/team_general_tab.test.jsx
tests/redux/actions/views/create_comment.test.jsx
tests/setup.js

Fix UnhandledPromiseRejectionWarning when running unit tests
Jira ticket: [MM-12778](https://mattermost.atlassian.net/browse/MM-12778)

[MM-12778] Fix UnhandledPromiseRejectionWarning when running unit tests

---

tests/components/add_users_to_team.test.jsx
tests/components/create_team/team_url.test.jsx
tests/components/rename_channel_modal.test.jsx

Fix other UnhandledPromiseRejectionWarning
- tests/components/add_users_to_team.test.jsx
```
(node:6411) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of undefined
(node:6411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6411) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
- tests/components/rename_channel_modal.test.jsx
```
(node:6411) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined …
```

Fix other UnhandledPromiseRejectionWarning

---

actions/user_actions.jsx
actions/views/mfa.js
components/claim/claim_controller.jsx
components/claim/components/email_to_ldap.jsx
components/claim/components/email_to_oauth.jsx
components/claim/components/ldap_to_email.jsx
components/claim/components/oauth_to_email.jsx
components/claim/index.js
components/login/login_controller/index.js
components/login/login_controller/login_controller.jsx
components/mfa/setup/index.js
components/mfa/setup/setup.jsx
components/setting_item_max.jsx
components/user_settings/security/index.js
components/user_settings/security/user_settings_security.jsx
tests/components/login/login_controller/login_controller.test.jsx
tests/redux/actions/views/mfa.test.js
tests/test_store.js

This is based on top of my other PR to clean up login-related actions: https://github.com/mattermost/mattermost-webapp/pull/1943
The changes specific to this PR are here: https://github.com/mattermost/mattermost-webapp/compare/mm12735...mm12736
https://mattermost.atlassian.net/browse/MM-12736

MM-12736 Migrate MFA actions to redux

---

sass/components/_announcement-bar.scss
sass/layout/_sidebar-left.scss
sass/layout/_sidebar-right.scss
sass/responsive/_mobile.scss
sass/utils/_variables.scss

MM-12803 - Fixing permanent banner styling
https://mattermost.atlassian.net/browse/MM-12803

MM-12803 - Fixing permanent banner styling

---

sass/layout/_post.scss

MM-12936 - Fixing alignment of post control menu
https://mattermost.atlassian.net/browse/MM-12936

MM-12936 - Fixing alignment of post control menu

---

components/create_comment/create_comment.jsx
components/create_comment/create_comment.test.jsx
components/create_comment/index.js
components/create_post/create_post.jsx
components/create_post/create_post.test.jsx
components/create_post/index.js
i18n/en.json

n/a
server: https://github.com/mattermost/mattermost-server/pull/9286
redux: https://github.com/mattermost/mattermost-redux/pull/612
api reference: https://github.com/mattermost/mattermost-api-reference/pull/387

When mention `@channel/@all` show the timezones affected in the warning message

---

actions/emoji_actions.jsx
components/emoji/add_emoji/__snapshots__/add_emoji.test.js.snap
components/emoji/add_emoji/add_emoji.jsx
components/emoji/add_emoji/add_emoji.test.js
components/emoji/add_emoji/index.js

https://mattermost.atlassian.net/browse/MM-12584

Migrate emoji_action to redux

---

actions/views/posts.js
components/post_view/message_attachments/action_menu/index.js
reducers/views/posts.js

Fix multiple message menus in a single post. Similar to the fix on mobile.
https://mattermost.atlassian.net/browse/MM-12982

MM-12982 Fix multiple message menus in single post

---

actions/channel_actions.jsx
actions/channel_actions.test.js
components/more_channels/index.js
components/more_channels/more_channels.jsx
components/more_channels/more_channels.test.jsx

Affected Areas:
* Search more public channels
https://mattermost.atlassian.net/browse/MM-12705

Migrate searchMoreChannels action to redux

---

actions/channel_actions.jsx
actions/views/channel.js
components/channel_layout/channel_identifier_router/actions.js
components/more_direct_channels/index.js
components/more_direct_channels/more_direct_channels.jsx
components/more_direct_channels/more_direct_channels.test.jsx
components/popover_list_members/index.js
components/popover_list_members/popover_list_members.jsx
components/popover_list_members/popover_list_members.test.jsx
components/profile_popover/index.js
components/profile_popover/profile_popover.jsx
plugins/pluggable/__snapshots__/pluggable.test.jsx.snap

https://mattermost.atlassian.net/browse/MM-12700

Migrate open GM/DM actions to redux

---

components/search_bar/search_bar.jsx
components/suggestion/search_suggestion_list.jsx
components/suggestion/suggestion_box.jsx

Remove "Direct Messages" heading from the `from:` search filter auto-complete.
https://mattermost.atlassian.net/browse/MM-12760

MM-12760: No heading on from: search filter.

---

components/channel_layout/channel_identifier_router/actions.js

A missed a dispatch
https://mattermost.atlassian.net/browse/MM-13009

Fix open DM channels

---

package-lock.json
package.json

https://mattermost.atlassian.net/browse/MM-13020

MM-13020 Revert changes to have Client4 use an explicit ClientError type (5.5)

---

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
i18n/i18n.jsx

Promote Romanian from Beta

---

NOTICE.txt
components/sidebar/sidebar.jsx
package-lock.json
package.json

Add a scroll animation to jump on click of more unreads
[MM-12951](https://mattermost.atlassian.net/browse/MM-12951)

[MM-12591] Add scroll animation for click on more unreads in LHS

---

components/quick_switch_modal/index.js
components/quick_switch_modal/quick_switch_modal.jsx
components/quick_switch_modal/quick_switch_modal.test.jsx

- GMs can only be switched to by ID.

MM-12770 Fixing opening a GM with the channel switcher.

---

components/search_results/index.jsx
components/search_results/search_results.jsx
components/search_results_item/index.js
components/sidebar_right/index.js
components/sidebar_right/sidebar_right.jsx

While working on the ticket to try and fix a bug that no longer reproduces I found myself refactoring this to avoid unnecessary re-renders
Search results, pinned posts, flagged posts
https://mattermost.atlassian.net/browse/MM-12938

Fix pinned post list from refreshing

---

components/error_page/__snapshots__/error_message.test.jsx.snap
components/error_page/error_message.jsx
i18n/en.json

For context of this PR, see https://github.com/mattermost/docs/pull/2180 and https://github.com/mattermost/docs/commit/85d8060e19f2126c626fd03137ac4e8632b6022b

Update minimum software requirements

---

actions/post_actions.jsx
actions/post_actions.test.js
components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
components/post_view/post_body_additional_content/post_body_additional_content.jsx
components/post_view/post_image/post_image.jsx
components/post_view/post_list.jsx
components/single_image_view/single_image_view.jsx
sass/layout/_post.scss
utils/file_utils.jsx
utils/file_utils.test.jsx

Adding infinite scroll to webapp.
[MM-11692](https://mattermost.atlassian.net/browse/MM-11692)
[MM-11504](https://mattermost.atlassian.net/browse/MM-11504)

MM-11692 Add infinite scroll to webapp

---

sass/routes/_signup.scss

MM-12981 - Updating custom login buttons
https://mattermost.atlassian.net/browse/MM-12981

MM-12981 - Updating custom login buttons

---

components/__snapshots__/setting_item_max.test.jsx.snap
components/setting_item_max.jsx
components/user_settings/notifications/__snapshots__/email_notification_setting.test.jsx.snap
components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
components/user_settings/sidebar/user_settings_sidebar.jsx
cypress/fixtures/users.json
cypress/integration/account_settings/sidebar/channel_switcher_spec.js
cypress/support/commands.js

- Added E2E to hide/show channel switcher button in LHS
- Added element IDs needed for testing
- Added command shortcut to easily navigate into the Account Settings modal
Jira ticket: [MM-12980](https://mattermost.atlassian.net/browse/MM-12980)

[MM-12980] Add E2E to hide/show channel switcher button in LHS

---

sass/layout/_headers.scss

MM-12943 - Updating blockquotes in header
https://mattermost.atlassian.net/browse/MM-12943

MM-12943 - Updating blockquotes in header

---

package-lock.json
package.json

Updated redux commit to take effect sidebar channels sorting
Jira ticket: [MM-13035](https://mattermost.atlassian.net/browse/MM-13035) & [MM-13068](https://mattermost.atlassian.net/browse/MM-13068)

[MM-13035] Updated redux commit to take effect sidebar channels sorting

---

sass/responsive/_mobile.scss

MM-12947 - Updating close button on mobile
https://mattermost.atlassian.net/browse/MM-12947

MM-12947 - Updating close button on mobile

---

sass/layout/_post.scss

MM-12922 - Updating bullet point sizing
https://mattermost.atlassian.net/browse/MM-12922

MM-12922 - Updating bullet point sizing

---

components/post_view/post_body_additional_content/post_body_additional_content.jsx

Add a check for MessageAttachmentList

Add a check for metadata on MessageAttachmentList

---

sass/layout/_post.scss

MM-13025 - Updating show more button css
https://mattermost.atlassian.net/browse/MM-13025

MM-13025 - Updating show more button css

---

actions/views/channel.js
actions/views/channel.test.js

Fix redirect after leaving a channel and add a unit test for the happy case.
https://mattermost.atlassian.net/browse/MM-12888

MM-12888 Fix redirect after leaving a channel

---

actions/views/posts.js
components/announcement_bar/configuration_bar.jsx

- Fixes announcement bar not appearing when an edit fails on a post due to the time limit being exceeded.
- Fixing announcement bar not appearing when email notifications are disabled.
- Fixing some announcement bar colors.

MM-13177 Announcement bar fixes.

---

components/admin_console/license_settings.jsx

Add edition field to the license page. Took the liberty of removing jquery and old intl usages from the component as well.
https://mattermost.atlassian.net/browse/MM-12881

MM-12881 Add edition field to license page

---

components/channel_header/channel_header.js
components/channel_header/index.js
components/sidebar/index.js
components/sidebar/sidebar.jsx
components/sidebar/sidebar.test.jsx

Fix channel switcher button and shortcut.
https://mattermost.atlassian.net/browse/MM-13191

MM-13191 Fix channel switcher button and shortcut

---

package-lock.json
package.json

Will be pushing the correct commit hash to the release branch directly

Update mattermost-redux to include terms of service changes

---

components/signup/signup_email/signup_email.jsx

Another casualty of ClientError.
https://mattermost.atlassian.net/browse/MM-13144

MM-13144 Fix redirecting to email verification page after sign-up

---

plugins/mobile_channel_header_plug/__snapshots__/mobile_channel_header_plug.test.jsx.snap
plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx
plugins/mobile_channel_header_plug/mobile_channel_header_plug.test.jsx
sass/layout/_navigation.scss
sass/responsive/_mobile.scss

MM-12996 - Updating modals on mobile
https://mattermost.atlassian.net/browse/MM-12996
https://mattermost.atlassian.net/browse/MM-13229

MM-12996/MM-13229 - Updating modals on mobile and fixing plugin button on mobile

---

sass/layout/_post.scss

https://mattermost.atlassian.net/browse/MM-13182

MM-13182 Allow clicking on links behind collapsed post fade effect

---

actions/global_actions.jsx
actions/global_actions.test.js

Fix the following error when leaving team.
[MM-13223](https://mattermost.atlassian.net/browse/MM-13223)

MM-132223 Fix for error on leaveTeam

---

sass/responsive/_mobile.scss

MM-13102 - Updating search cross icon on mobile
https://mattermost.atlassian.net/browse/MM-13102

MM-13102 - Updating search cross icon on mobile

---

sass/components/_modal.scss
utils/utils.jsx

MM-13226 - Updating inactive tab styling in modal
https://mattermost.atlassian.net/browse/MM-13226

MM-13226 - Updating inactive tab styling in modal

---

components/post_view/post_list.jsx

Fix the onClick prop for ScrollToBottomArrows
[MM-13250](https://mattermost.atlassian.net/browse/MM-13250)

Fix an error with ScrollToBottomArrows

---

package-lock.json
package.json

Update mattermost-redux commit to take effect fix in sorting of sidebar channels - https://github.com/mattermost/mattermost-redux/pull/725
Jira ticket: [MM-13175](https://mattermost.atlassian.net/browse/MM-13175)

[MM-13175] Update mattermost-redux commit to take effect fix in sorting of sidebar channels

---

actions/views/root.js

This PR breaks SAML login: https://github.com/mattermost/mattermost-webapp/pull/2060/ this reverts it without reverting the tests it added.

Reverting #2060 to fix SAML login.

---

components/user_settings/display/__snapshots__/user_settings_display.test.jsx.snap
components/user_settings/display/user_settings_display.jsx
i18n/en.json

https://community.mattermost.com/core/pl/t1ukfpohrid68efm41dkxzxx7r

Update 'Channel Display Mode' to 'Channel Display'

---

components/channel_header_dropdown/mobile_channel_header_dropdown.js
sass/responsive/_mobile.scss

MM-12948 - Adding dividers for mobile channel menu
https://mattermost.atlassian.net/browse/MM-12948

MM-12948 - Adding dividers for mobile channel menu

---

Makefile

Adding i18n-extract task to the Makefile

Adding i18n-extract task to the Makefile

---

components/channel_header_dropdown/menu_items/leave_channel/index.js
components/sidebar/sidebar_channel/index.js

Use the web app specific leave channel action so that redirection occurs correctly.
https://mattermost.atlassian.net/browse/MM-13255

MM-13255 Use correct leave channel action

---

components/multiselect/multiselect_list.jsx

Only update scroll position in multiselect if selection changes.
https://mattermost.atlassian.net/browse/MM-13234

MM-13234 Only update scroll position in multiselect if selection changes

---

components/admin_console/multiselect_settings.jsx

Fix MultiSelect compatability with react-select v2.0.0
https://mattermost.atlassian.net/browse/MM-13239

Fix MultiSelect compatability with react-select v2.0.0

---

components/__snapshots__/textbox.test.jsx.snap
components/suggestion/command_provider.jsx
components/suggestion/emoticon_provider.jsx

Fix bug introduced with the change to providers by making sure they all extend `Provider`.
https://mattermost.atlassian.net/browse/MM-13321

MM-13321: Fix providers that don't extend Provider.

---

sass/responsive/_mobile.scss

MM-13102 - Updating x icon on search
https://mattermost.atlassian.net/browse/MM-13102

MM-13102 - Updating x icon on search

---

actions/post_actions.test.js
actions/post_utils.js
actions/post_utils.test.js
actions/websocket_actions.jsx

The event being dispatch to stop showing the user typing was not including the time.
This PR will only affect the webapp, another PR is being submitted for the mobile apps.
https://mattermost.atlassian.net/browse/MM-13077

Remove participant is typing as soon as the post arrives

---

actions/websocket_actions.jsx

We weren't parsing the JSON data so team updates were not getting picked up immediately.
https://mattermost.atlassian.net/browse/MM-13346

MM-13346 Fix update team WS event handler

---

actions/post_actions.jsx
actions/post_actions.test.js

I think some refactoring stopped us updating the search results when the pins were open in the RHS. This adds that back plus some tests.
https://mattermost.atlassian.net/browse/MM-13353

MM-13353 Fix pin posts not updating in RHS

---

components/signup/signup_controller/__snapshots__/signup_controller.test.jsx.snap
components/signup/signup_controller/signup_controller.jsx
components/signup/signup_controller/signup_controller.test.jsx

There used to be couple of early return here in the code https://github.com/mattermost/mattermost-webapp/pull/1930/files#diff-035133c8b3484acb1c8c9f3d93271340L106 which are removed causing 
functions such as `redirectUserToDefaultTeam` getting called and hence the issue here.
Instead of early returns changing this to be if else statements now
[MM-13345](https://mattermost.atlassian.net/browse/MM-13345)
[MM-13339](https://mattermost.atlassian.net/browse/MM-13339)

MM-13345 Fix to show access denied screen for restricted teams with invite link

---

sass/components/_modal.scss

MM-13240 - Updating modal css for system console
https://mattermost.atlassian.net/browse/MM-13240

MM-13240 - Updating modal css for sys console

---

package-lock.json
package.json

Update redux commit to fix sorting of channels at sidebar unreads section
Jira ticket: [MM-13398](https://mattermost.atlassian.net/browse/MM-13398)

[MM-13398] Update redux commit to fix sorting of channels at sidebar unreads section

---

sass/routes/_get-app.scss

MM-13329 - Updating android landing page
https://mattermost.atlassian.net/browse/MM-13329

MM-13329 - Updating android landing page

---

sass/components/_dropdown.scss

MM-13359 - Updating dividers for dropdown menu
https://mattermost.atlassian.net/browse/MM-13359

MM-13359 - Updating dividers for dropdown menu

---

components/sidebar/sidebar.jsx

more unreads above/below doesn't appear until you scroll the LHS
[MM-13399](https://mattermost.atlassian.net/browse/MM-13399)

MM-13399 more unreads above/below fix for LHS

---

components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
components/new_channel_modal/new_channel_modal.jsx
sass/components/_modal.scss
sass/layout/_forms.scss

MM-13410 - Updating styles for new channel modal
https://mattermost.atlassian.net/browse/MM-13410

MM-13410 - Updating styles for new channel modal

---

utils/utils.jsx

MM-13406 - Updating offline icon css
https://mattermost.atlassian.net/browse/MM-13406

MM-13406 - Updating offline icon css

---

components/admin_console/manage_teams_modal/manage_teams_modal.jsx

Fix manage teams modal usage in system console to not pass the team ID where a User ID is expected.
https://mattermost.atlassian.net/browse/MM-13422

MM-13422: Fix manage teams modal usage in system console.

---

components/create_post/create_post.jsx

These 3 cases were the only place we were using `trimRight()`. I will create a follow-up ticket to fix this properly in babel.
https://mattermost.atlassian.net/browse/MM-13423

MM-13423 Temporary fix for IE11 where trimRight is not being polyfilled

---

components/announcement_bar/configuration_bar.jsx

Revert SiteURL message bar color to blue.
https://mattermost.atlassian.net/browse/MM-13327

MM-13327 Revert SiteURL message bar color to blue

---

components/login/login_controller/login_controller.jsx

Fix email verification redirect on login and other errors on the login page.
https://mattermost.atlassian.net/browse/MM-13144

MM-13144 Fix email verification redirect on login

---

components/sidebar/index.js
components/sidebar/sidebar.jsx

Fix showing of browser title as * or mention count for all teams (and not the current team only).
Jira ticket: [MM-13224](https://mattermost.atlassian.net/browse/MM-13224)

[MM-13224] Fix showing of browser title as * or mention count for all teams (and not the current team only)

---

components/admin_console/admin_definition.jsx
components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
components/admin_console/admin_sidebar/admin_sidebar.jsx
components/admin_console/system_users/index.js
components/mfa/mfa_controller/mfa_controller.jsx
components/user_settings/security/mfa_section/index.js

Moving MFA from enterprise to Team edition
[MM-12976](https://mattermost.atlassian.net/browse/MM-12976)

MM-12976: Moving MFA to Team edition

---

components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
components/user_settings/display/user_settings_theme/custom_theme_chooser.test.jsx

Fix setting a custom theme ff the code theme is the only value changed.
https://mattermost.atlassian.net/browse/MM-8971

Allow custom theme to only change the code theme

---

components/announcement_bar/announcement_bar.jsx

Fix announcement banner overlapping.
https://mattermost.atlassian.net/browse/MM-13393

MM-13393 Fix announcement banner overlapping

---

components/sidebar/channel_name.jsx

Fixes by using t function for tool to pick up translation strings
[MM-13476](https://mattermost.atlassian.net/browse/MM-13476)

MM-13476 Fix for channel types are not being translated in LHS

---

components/channel_layout/channel_identifier_router/actions.js
components/channel_layout/channel_identifier_router/actions.test.js

Fix rejoining channel from links in posts.
https://mattermost.atlassian.net/browse/MM-13481

MM-13481 Fix rejoining channel from links in posts

---

sass/routes/_settings.scss
utils/utils.jsx

MM-13468 - Updating x icon for proifle pictures
https://mattermost.atlassian.net/browse/MM-13468

MM-13468 - Updating x icon for proifle pictures

---

components/channel_layout/channel_identifier_router/actions.js
components/channel_layout/channel_identifier_router/actions.test.js

Fix routing to DMs by email and add unit tests to cover this case in the future. The action was being used instead of the selector by accident.
https://mattermost.atlassian.net/browse/MM-13490

MM-13490 Fix routing to DMs by email

---

components/login/login_controller/login_controller.jsx

Missing await on invite link api causes issue with data not being resolved
[MM-13504](https://mattermost.atlassian.net/browse/MM-13504)

MM-13504 Fix for invite link to land in the team on login

---

components/team_sidebar/team_sidebar_controller.jsx
sass/layout/_team-sidebar.scss

MM-13369 - Updating scrollbar for teams sidebar
https://mattermost.atlassian.net/browse/MM-13369

MM-13369 - Updating scrollbar for teams sidebar

---

components/admin_console/admin_sidebar/admin_sidebar.jsx
package-lock.json

Ordering plugins in alphabetical order (System console)
https://github.com/mattermost/mattermost-server/issues/9679

GH-9679 ordering plugins in alphabetical order

---

actions/views/create_comment.test.jsx

Fixes 2 spec failures; change should be cherry-picked to `release-5.7` branch to fix that build that will break once the redux commit it updated.
Associated with this commit:
https://github.com/mattermost/mattermost-redux/commit/2219aee26c50f953e98c494ef158f832c73155b0

MM-13243: Spec fix.

---

components/select_team/__snapshots__/select_team.test.jsx.snap
components/select_team/select_team.jsx
i18n/en.json

Remove a help text that is no longer ever displayed to the user.
https://mattermost.atlassian.net/browse/MM-13429

MM-13429: remove help text that is never displayed.

---

components/root/root.jsx
components/root/root.test.jsx

Fix redirect to sign-up page when there are no user accounts.
https://mattermost.atlassian.net/browse/MM-13520

MM-13520 Fix redirect to sign-up page when there are no user accounts

---

actions/integration_actions.jsx
actions/integration_actions.test.js
components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap
components/integrations/installed_oauth_app/index.js
components/integrations/installed_oauth_app/installed_oauth_app.jsx
components/integrations/installed_oauth_app/installed_oauth_app.test.jsx
components/integrations/installed_oauth_apps/__snapshots__/installed_oauth_apps.test.jsx.snap
components/integrations/installed_oauth_apps/index.js
components/integrations/installed_oauth_apps/installed_oauth_apps.jsx
components/integrations/installed_oauth_apps/installed_oauth_apps.test.jsx

Load creators for oauth apps when needed and a bit of minor refactoring + tests.
https://mattermost.atlassian.net/browse/MM-13248

MM-13248 Load creators for oauth apps when needed

---

components/profile_popover/profile_popover.jsx
components/user_profile.jsx
sass/components/_popover.scss
utils/utils.jsx

MM-13518 - Updating profile popover position
https://mattermost.atlassian.net/browse/MM-13518

MM-13518 - Updating profile popover position

---

sass/components/_announcement-bar.scss

MM-13502 - Updating announcement banner
https://mattermost.atlassian.net/browse/MM-13502

MM-13502 - Updating announcement banner

---

components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
components/new_channel_modal/new_channel_modal.jsx

MM-13474 - Updating new channel modal
https://mattermost.atlassian.net/browse/MM-13474

MM-13474 - Updating new channel modal

---

components/team_members_dropdown/team_members_dropdown.jsx

Fix regression in manage members modal that made it not possible to delete users. 
https://mattermost.atlassian.net/browse/MM-13591

[MM-13591] Remove From Team fails with TypeError in console 

---

components/setting_picture.jsx

Fix profile picture setDefault + change picture
[MM-13497](https://mattermost.atlassian.net/browse/MM-13497)

MM-13497: Fix profile picture setDefault + change picture
