- .gitignore
- PULL_REQUEST_TEMPLATE.md
- README.md
To be used temporarily until we have a custom readme for the webapp. Also added a PR template.
> Copy over platform README and add PR template

- components/sidebar.jsx
- components/unread_channel_indicator.jsx
- sass/layout/_sidebar-left.scss
Migrated from  mattermost/mattermost-server#7356
> PLT-6577 scroll sidebar on click "more unreads"

- components/about_build_modal/about_build_modal.jsx
- components/about_build_modal/index.js
- components/admin_console/admin_navbar_dropdown.jsx
- components/sidebar_header_dropdown.jsx
- components/sidebar_right_menu.jsx
Converts the `about_build_modal` component to be pure and use Redux. Tests for this component have already been written.
https://github.com/mattermost/mattermost-server/issues/7228
> [PLT-7228] Move about_build_modal.jsx to Redux

- actions/notification_actions.jsx
- components/channel_notifications_modal.jsx
- components/user_settings/desktop_notification_settings.jsx
- components/user_settings/user_settings_notifications.jsx
- utils/constants.jsx
Most of this refactoring is moving a bunch of magic strings into constants which makes it a lot wordier, but it does mean we have a list of all the values at hand.
Non-refactoring changes are here: https://github.com/mattermost/mattermost-webapp/commit/19bdd077f282cb215a1ffcfc29b13481833d73ee
https://mattermost.atlassian.net/browse/PLT-7605
> PLT-7605 Fall back to default desktop notification level when user.notify_props is undefined

- actions/websocket_actions.jsx
- package.json
- plugins/index.js
- plugins/pluggable/pluggable.jsx
- reducers/plugins/index.js
- utils/constants.jsx
- yarn.lock
* Added support for loading plugins separate from client config
* Made use of new websocket events to add/remove plugins without a refresh
* Added functionality to load/remove plugins on reconnect in case of missed websocket event 
* Added a reducer to store plugin manifests
* Updated plugin components reducer to store the owner plugin's id
https://mattermost.atlassian.net/browse/PLT-7622
> PLT-7622 Improvements to webapp plugins

- components/post_view/post_message_view/index.js
- components/post_view/post_message_view/post_message_view.jsx
- plugins/index.js
- reducers/plugins/index.js
- tests/plugins/__snapshots__/post_type.test.jsx.snap
- tests/plugins/post_type.test.jsx
- utils/constants.jsx
Add webapp plugin post type extension support. Very similar to your implementation @hmhealey, only major difference is I added a new reducer specifically for post type extending.
Not blocked by the server changes.
https://mattermost.atlassian.net/browse/PLT-7621
> PLT-7621 Add webapp plugin post type extension support

- package.json
- yarn.lock
This fixes:
1. Linking www links that don't start words like `testwww.google.ca` (changes [here](https://github.com/mattermost/marked/compare/f513ac53ac83ecb2f4a7d284804f9c1852749a7e%5E...5d184f0aa02f1202d1f4c23cb01b72b10e28b318))
2. Not capturing the closing square bracket in IPv6 links like `http://[::1]` (changes [here](https://github.com/mattermost/marked/compare/5d184f0aa02f1202d1f4c23cb01b72b10e28b318...b516702c460c68df0b68fa9f4916f3100572ce99))
https://mattermost.atlassian.net/browse/RN-319
https://mattermost.atlassian.net/browse/PLT-7551
https://mattermost.atlassian.net/browse/PLT-7553
> PLT-7551/RN-319/PLT-7553 Updated markdown renderer

- components/sidebar_right_menu.jsx
The previous code tried to close all sidebars which conflicted with opening the search results sidebar on IE11
https://mattermost.atlassian.net/browse/PLT-7371
> PLT-7371 Properly close RHS menu before opening search results

- components/navbar/index.jsx
- components/navbar/navbar_info_button.jsx
- components/needs_team/needs_team.jsx
- sass/layout/_navigation.scss
- sass/responsive/_mobile.scss
Turns out this was a lot easier than what I was expecting, but I ended up refactoring some of the navbar because I was having a really hard time telling what CSS affected the info button since it was located in a different place than the search and menu buttons.
Adding Asaad to make sure I didn't break anything horrible with the CSS changes. I made sure the popover still displayed correctly despite these changes.
https://mattermost.atlassian.net/browse/PLT-7376
> PLT-7376 Fixed background colour of mobile header icons on IE11 and some refactoring of navbar

- components/navbar/index.jsx
Encountered JS error when navbar `x` button is clicked.
> Fix JS error - cannot read property ‘hide’ of undefined

- actions/user_actions.jsx
> Repro steps:
> 1) Sign out of Mattermost
> 2) Click "Forgot my password" link on login screen
> 3) Go to password reset link that's emailed to you
> 4) Enter a new password and click "Change my password"
> Observed: You're sent back to the log in screen with no feedback that your password changed. The URL reads "/login?extra=undefined. Your password is still changed
> Expected: The log in screen should display "Password updated successfully". The URL should read "/login?extra=password_change".
Bug introduced by this PR: https://github.com/mattermost/mattermost-server/pull/5167
https://mattermost.atlassian.net/browse/PLT-7588
> PLT-7588: Fix password change bar / undefined reference

- components/channel_header/channel_header.jsx
- components/channel_header/index.js
- components/channel_view.jsx
- components/navbar/index.jsx
- components/permalink_view.jsx
- components/popover_list_members/index.js
- components/sidebar.jsx
- package.json
- utils/constants.jsx
- yarn.lock
Part 1 of migrating the channel header to the Redux pattern.
Part of https://mattermost.atlassian.net/browse/PLT-7544
* Move out modals
* Migrate webrtc store/actions to redux
* Use redux for search store
* Supply all actions through props
* Add component test
> PLT-7544 Begin migrating channel header to redux pattern

- sass/layout/_post.scss
PLT-7593 - Fixing buffer space above textarea
PLT-7594 - Fixing word break in IE111
https://mattermost.atlassian.net/browse/PLT-7593
https://mattermost.atlassian.net/browse/PLT-7594
> Minor IE fixes

- package.json
- yarn.lock
This'll prevent anything strange from happening by someone deeply nesting Markdown blocks (mostly quotes and lists). I picked a depth of 100 since it's a nice, round number, but we could go even further if we wanted. Anything past that depth can still have inline stuff rendered (styling, links, etc), but won't be able to use block styles (lists, code blocks, etc)
Marked changes: https://github.com/mattermost/marked/commit/70eba71f18ab4d2e2bae6b3490a855ac6021a21f
https://mattermost.atlassian.net/browse/PLT-7708
> PLT-7708 Added a maximum depth to the Markdown block parser

- components/channel_header/channel_header.jsx
- components/channel_info_modal/channel_info_modal.jsx
- components/channel_info_modal/index.js
- components/navbar/index.jsx
- tests/components/__snapshots__/channel_info_modal.test.jsx.snap
- tests/components/channel_info_modal.test.jsx
Moved the `channel_info_modal` component to use Redux and added tests.
https://github.com/mattermost/mattermost-server/issues/6441
> [PLT-6441] Move channel_info_modal to use Redux

- components/channel_header/channel_header.jsx
Add status indicator to DM channel header.
This was [previously submitted](https://github.com/mattermost/mattermost-webapp/pull/37) and merged but was missed out when [channel header was migrated](https://github.com/mattermost/mattermost-webapp/pull/47).
Jira ticket: [PLT-7289](https://mattermost.atlassian.net/browse/PLT-7289)
> [PLT-7289] Resubmitted: add status indicator to DM channel header

- components/integrations/components/installed_incoming_webhooks/index.js
- components/integrations/components/installed_incoming_webhooks/installed_incoming_webhooks.jsx
- utils/constants.jsx
Fixes the issue of no teamId as part of incoming webhook API
https://github.com/mattermost/mattermost-webapp/pull/60
> PLT-6453 Migrate installed_incoming_webhooks.jsx to be pure and use Redux

- actions/global_actions.jsx
- actions/post_actions.jsx
- components/navbar/index.jsx
- components/post_view/post/post.jsx
- components/rhs_header_post.jsx
- components/rhs_root_post.jsx
- components/rhs_thread/index.js
- components/rhs_thread/rhs_thread.jsx
- components/search_bar.jsx
- i18n/en.json
- reducers/views/rhs.js
- selectors/rhs.jsx
- utils/constants.jsx
- utils/post_utils.jsx
This makes the webapp robust against posts that are replies, but whose root post has been deleted from the database (e.g. by the data retention tool).
If you try to reply to a thread with a deleted root post, it shows a fake system message saying the thread is partially deleted and won't let you post a reply.
No constant used for the new system message type as that would be in the redux repo - I'll add it if we decide to go ahead with this approach.
https://mattermost.atlassian.net/browse/PLT-7670
> PLT-7670: Make webapp robust to posts whose root post has been deleted.

- components/admin_console/admin_sidebar.jsx
- i18n/en.json
It was already marked Beta on the System Console page, adding the label to the sidebar too
> Marking data retention as beta in the sidebar

- components/admin_console/data_retention_settings.jsx
- components/admin_console/jobs/table.jsx
- i18n/en.json
Adds a jobs table and a "run now" button to the Data Retention page of the system console.
https://mattermost.atlassian.net/browse/PLT-7751
> PLT-7751: Add jobs table to data retention admin UI.

- components/searchable_channel_list.jsx
Disabled other channel Join buttons during the execution of the join action, preventing users from joining more than one channel at a time
https://mattermost.atlassian.net/browse/PLT-7697
> PLT-7697: Join Channels Popover Should Only Allow the User to Join One Channel

- components/post_view/post_list.jsx
> Creating a group message shows permanent 'loading...' animation
Introduced by: https://github.com/mattermost/mattermost-redux/pull/260
https://mattermost.atlassian.net/browse/PLT-7770
N/A
> PLT-7770: fix infinite load

- components/integrations/components/add_oauth_app/add_oauth_app.jsx
- components/integrations/components/add_oauth_app/index.js
Hide trusted option in OAuth app UI for non-admins.
https://mattermost.atlassian.net/browse/PLT-7678
> PLT-7678 Hide trusted option in OAuth app UI for non-admins

- components/admin_console/localization_settings.jsx
Disabled client-side error checking
https://mattermost.atlassian.net/browse/PLT-5549
> PLT-5549: No feedback when trying to save localization settings in System Console when Available Languages doesn't include the default client language

- components/backstage/backstage_controller.jsx
- components/needs_team/needs_team.jsx
- plugins/pluggable/pluggable.jsx
This can be used to create a post-login modal and other modals. Adds support for plugin points that don't override an existing component.
https://mattermost.atlassian.net/browse/PLT-7545
> PLT-7545 Add plugin support for a root component

- package.json
- yarn.lock
The problem was caused by the regex that matches plain text was capturing non-http links instead of realizing that they may be special and letting the URL regex take over
Marked changes here: https://github.com/mattermost/marked/commit/17945726698a03420588acd55e5b38f692c03f31
https://mattermost.atlassian.net/browse/PLT-7592
> PLT-7592 Fixed non-http links only rendering at the start of text

- actions/post_actions.jsx
- stores/search_store.jsx
Stop inferring channel ID from posts. This was causing incorrect pinned posts to show up in the RHS when no existing posts were present.
https://mattermost.atlassian.net/browse/PLT-7576
> PLT-7576 Stop inferring channel ID from posts for pinned posts

- components/shortcuts_modal.jsx
Shortcuts dialog has untranslated message because wrong id was provided in `components/shortcuts_modai.jsx`.
n/a
- No `en.json` update in this PR because `shortcuts.nav.recent_mentions` and `shortcuts.nav.recent_mentions.mac` are already defined and translated.
> Fix incorrect message id

- components/color_input.jsx
- components/user_settings/color_chooser.jsx
- components/user_settings/custom_theme_chooser.jsx
- package.json
- sass/components/_color-input.scss
- sass/components/_module.scss
- tests/components/__snapshots__/color_input.test.jsx.snap
- tests/components/color_input.test.jsx
- tests/components/user_settings/__snapshots__/color_chooser.test.jsx.snap
- tests/components/user_settings/color_chooser.test.jsx
- tests/setup.js
- yarn.lock
Added ColorInput component. Replaced `bootstrap-picker` with new component in `components/user_settings/custom_theme_chooser.jsx`
https://github.com/mattermost/mattermost-server/issues/6595
> PLT-6739 Convert theme color pickers to use react-color

- actions/websocket_actions.jsx
Fix post edit event adding post to end of post list.
@MusikPolice the issue was that the RECEIVED_POST action type is meant for getting a new post from the server. It was being used by the post edit event which means, if the client didn't already have the post, then it would be treated as a new post and not an edited post. Changing it to use the general RECEIVED_POSTS action type, which does not make any sort of assumptions, fixed the issue. I'm probably going to refactor the action types a bit to add a RECEIVED_NEW_POST in addition to the RECEIVED_POST so that this becomes less confusing.
I'll be submitting a fix to mattermost-redux for this as well.
https://mattermost.atlassian.net/browse/PLT-7786
> PLT-7786 Fix post edit event adding post to end of post list

- components/webrtc/webrtc_controller.jsx
Split StunURI and TurnURI of WebrtcSettings by space to support
configurations with multiple TURN and/or STUN servers.
Example:
"WebrtcSettings": {
"StunURI": "stun:stun.example.com:3478 stun:stun.l.google.com:19302"
}
https://mattermost.atlassian.net/browse/PLT-7807
> PLT-7807: Allow multiple STUN and TURN servers

- components/emoji_picker/emoji_list.jsx
- components/emoji_picker/emoji_picker.jsx
Fix JS error when searching emoji picker, by:
- by allowing item (emoji row) that is less than the total item count
Also fix other search issue to correctly return filtered emojis when item count has changed. 
Jira ticket: [PLT-7851](https://mattermost.atlassian.net/browse/PLT-7851)
Note:
Component test will be submitted against `master`.
> [PLT-7851] Fix JS error when searching emoji picker

- components/post_view/post_message_view/index.js
- components/post_view/post_message_view/post_message_view.jsx
Add username to mention keys even when not selected as a word that trigger mentions (notification).
- this is only how the mentioned username is highlighted in post message view and will not cause unnecessary notification (when not set).
- the `username` is added to `mentionKeys` at post message view. In case of `username` already included in `mentionKeys`, there will be two occurrences of username which I don't think will be an issue.
Jira ticket: [PLT-7845](https://mattermost.atlassian.net/browse/PLT-7845)
Note:
Test for `PostMessageView` is not included here. Instead, I'm planning to submit it against the `master`.
> [PLT-7845] Add username to mention keys even when not selected as a word that trigger mentions

- utils/markdown.jsx
Rebasing #16 on top of release-4.3.
Should not add http:// if the first part have numbers:
``uri1:test``
cc @ccbrown
> Update markdown.jsx for numbers in uris

- components/member_list_channel/member_list_channel.jsx
Make channel members list update when filter term doesn't match any users.
https://mattermost.atlassian.net/browse/PLT-7823
> PLT-7823: Channel members doesn't update when filter matches none.

- components/admin_console/admin_settings.jsx
- components/admin_console/save_button.jsx
- components/save_button.jsx
- components/setting_item_max.jsx
- components/setting_picture.jsx
- components/user_settings/desktop_notification_settings.jsx
- components/user_settings/email_notification_setting.jsx
- components/user_settings/manage_languages.jsx
- components/user_settings/user_settings_advanced.jsx
- components/user_settings/user_settings_display.jsx
- components/user_settings/user_settings_general/user_settings_general.jsx
- components/user_settings/user_settings_notifications.jsx
- components/user_settings/user_settings_security/user_settings_security.jsx
- components/user_settings/user_settings_theme.jsx
This is a re-submission of PR [#7082](https://github.com/mattermost/mattermost-server/pull/7082). It fixes [#6487](https://github.com/mattermost/mattermost-server/issues/6487). Add a spinner to all save buttons and change the button text to "Saving..." for each section of the Account Setting Dialog when saving.
[PLT-3505] (https://mattermost.atlassian.net/browse/PLT-3505)
> Add spinner on all user settings button (#6487)

- components/channel_header/index.js
- components/post_view/index.js
- components/post_view/post_list.jsx
Makes things behave when you click a permalink for a channel that you haven't joined.
https://mattermost.atlassian.net/browse/PLT-7825?filter=14400
N/A
> PLT-7825: Fix unjoined-channel permalinks

- components/user_settings/user_settings_advanced.jsx
- components/user_settings/user_settings_display.jsx
- components/user_settings/user_settings_general/user_settings_general.jsx
- components/user_settings/user_settings_modal.jsx
- components/user_settings/user_settings_notifications.jsx
- components/user_settings/user_settings_security/user_settings_security.jsx
Fix scrolling issues at user's Account Setting modal
- by calling `...perfectScrollbar('update')` at ComponentDidUpdate of UserSettingsModal
- by removing other multiple calls in updating perfect-scrollbar
In the future, we might need to decouple `perfect-scrollbar` from `jquery` by removing:
```
require('perfect-scrollbar/jquery')($);
```
and then adding where necessary:
```
import PerfectScrollbar from 'perfect-scrollbar';
```
Jira ticket: [PLT-7852](https://mattermost.atlassian.net/browse/PLT-7852)
> [PLT-7852] Fix scrolling issues at user's Account Setting modal

- actions/channel_actions.jsx
- components/create_comment/create_comment.jsx
- components/create_post.jsx
I prototyped out [this suggestion](https://github.com/mattermost/mattermost-server/pull/7274#issuecomment-335586690) and consolidated this to do so. I'm not gonna put in a PR for the suggestion because it introduces security concerns, but I can at least put in this.
N/A
N/A
> Don't repeat yourself: Cleaning up executeCommand

- components/more_channels/more_channels.jsx
- components/searchable_channel_list.jsx
This PR resolves the issue of the More Channels modal remembering which page it was on previously when making a search. In addition, another bug was fixed where the `next` button would appear even though all the channels fit into that page.
Lastly a bug was found where not sometimes all channels are that match the search criteria are returned, and this does not seem to be due to the fixes made above. It's reproducible on master.
https://github.com/mattermost/platform/issues/7344
https://mattermost.atlassian.net/browse/PLT-7526
This is a resubmit of a PR made earlier, prior to the splitting of the web app and server into separate repositories. Previous discussion can be found at https://github.com/mattermost/mattermost-server/pull/7383
> [PLT-7526] More channels modal search doesn't remember page

- sass/layout/_post.scss
PLT-7887 - Fixing alignment for lists/edited stuff in posts
https://mattermost.atlassian.net/browse/PLT-7887
> PLT-7887 - Fixing post overflow and alignment

- components/admin_console/configuration_settings.jsx
- components/admin_console/saml_settings.jsx
- i18n/en.json
Pre-populates the SAML Service provider login URL in the System Console if the Site URL is set.
The issue opened for this is [mattermost-server/#7559](https://github.com/mattermost/mattermost-server/issues/7559)
> PLT-7777 Pre-populate SAML Service Provider Login URL (#7559)

- build/Jenkinsfile
Publish artifact for each commit as well. For caching within the mattermost-server job.
For example: https://releases.mattermost.com/mattermost-webapp/commit/d73250ff54071ec0e866327e771fa78e6dc3a298/mattermost-webapp.tar.gz
N/A
N/A
> Publish artifact for each commit as well

- components/rhs_comment.jsx
- components/rhs_root_post.jsx
- components/search_results_item.jsx
This pull request adds the full date and time tooltip to post timestamps in the right-hand sidebar and search results.
The issue related to this PR is [mattermost-server#6172](https://github.com/mattermost/mattermost-server/issues/6172)
> PLT-6362 Add full date tooltip to post timestamps (#6172)

- components/post_view/post_time.jsx
Timestamp links on desktop app should open in permalink view in the current window
Jira: https://mattermost.atlassian.net/browse/PLT-5535
Github: https://github.com/mattermost/mattermost-server/issues/5586
> [PLT-5535] Timestamp links on desktop app should open in permalink view in the current window

- components/integrations/components/installed_outgoing_webhook.jsx
- components/integrations/components/installed_outgoing_webhooks/index.js
- components/integrations/components/installed_outgoing_webhooks/installed_outgoing_webhooks.jsx
- routes/route_integrations.jsx
- tests/components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
- tests/components/integrations/__snapshots__/installed_outgoing_webhooks.test.jsx.snap
- tests/components/integrations/installed_outgoing_webhook.test.jsx
- tests/components/integrations/installed_outgoing_webhooks.test.jsx
WIP: Migrated installed_outgoing_webhooks.jsx and installed_outgoing_webhook.jsx to be pure and use Redux
* Moved ChannelStore dependency from installed_outgoing_webhook.jsx to
installed_outgoing_webhooks.js and made it available through props
* Changed matchesFilter to be static method.
https://github.com/mattermost/mattermost-server/issues/6454
https://github.com/mattermost/mattermost-server/issues/6450
> PLT-6450: Migrate installed_outgoing_webhooks.jsx and installed_outgoing_webhook.jsx to be pure and use Redux

- components/edit_post_modal.jsx
- sass/components/_modal.scss
This PR adds the emoji picker to the edit message modal.
https://github.com/mattermost/mattermost-server/issues/6277
https://mattermost.atlassian.net/browse/PLT-5576
> [PLT-5576] Enable Emoji Picker for Edit Message Modal

- components/emoji_picker/emoji_picker.jsx
- i18n/en.json
When searching in emoji picker, remove categorization and instead simply list all the emoji that match the search result, nine emoji per row.
mattermost/mattermost-server#6279
> [PLT-6039] Remove categorization when searching in emoji picker

- components/channel_header/channel_header.jsx
- components/delete_channel_modal/delete_channel_modal.jsx
- components/delete_channel_modal/index.js
- components/navbar/index.jsx
- tests/components/__snapshots__/delete_channel_modal.test.jsx.snap
- tests/components/delete_channel_modal.test.jsx
- utils/constants.jsx
Migrate delete_channel_modal.jsx to be pure and use Redux
https://github.com/mattermost/mattermost-server/issues/7231
> GH-7231 Migrate delete_channel_modal.jsx to be pure and use Redux 

- components/admin_console/gitlab_settings.jsx
- components/admin_console/oauth_settings.jsx
- i18n/en.json
As I was learning mattermost codebase, I found an error in which `gitlab` was referenced as `gitab` with no `l` (L).  Although I could not find a **[Help Wanted]** ticket for this, I wanted to contribute to get me started on this project.  Later, I would like to contribute more significantly when I better understand the mattermost codebase, and hope to be able to contribute to a [Help Wanted] Ticket in the issues section.  I think mattermost is a great system as it uses `go`, `react` & `redux`, and I hope to become a more significant contributor!
I could not find this error (maybe it isn't an error?) in the issues tab.
> cleaned type-o in gitlab "admin.clientSecretDescription" references from "gitab" to "gitlab"

- actions/team_actions.jsx
Adding/Removing a member doesn't update member count until refresh
JIRA: https://mattermost.atlassian.net/browse/PLT-6197
GITHUB: https://github.com/mattermost/mattermost-server/issues/5978
> [PLT-6197] Adding/Removing a member doesn't update member count until refresh

- components/setting_item_min.jsx
- components/settings_sidebar.jsx
- components/user_settings/user_settings_display.jsx
- components/user_settings/user_settings_modal.jsx
- tests/e2e/pages/accountSettingsModalPage.js
- tests/e2e/pages/sidebarLeftPage.js
- tests/e2e/tests/3_sidebarLeft/accountSettingsDisplay.js
- tests/e2e/tests/3_sidebarLeft/accountSettingsModalPage.element.js
- tests/e2e/tests/3_sidebarLeft/sidebarLeftPage.element.js
- Add IDs and elements check to Account Settings modal - display section and refactor sidebarLeftPage.
In order not to break further to `mattermost-selenium`, I did not change IDs like:
```
collapseEdit: {selector: '#Default_appearance_of_image_link_previewsEdit'},
```
But in the future, once we are ready to have nightwatch in our CI pipeline, I plan to change it using simple ID like `#collapseEdit` only.
Jira ticket: [PLT-7925](https://mattermost.atlassian.net/browse/PLT-7925)
> [E2E] Add IDs and elements check to Account Settings modal - display section and refactor sidebarLeftPage

- components/channel_header/channel_header.jsx
Handle not-yet-loaded user in DM channel headers.
https://mattermost.atlassian.net/browse/PLT-7906
> PLT-7906 Handle not-yet-loaded user in DM channel headers

- components/file_attachment_list/file_attachment_list.jsx
- components/view_image.jsx
- components/view_image_popover_bar.jsx
- tests/components/__snapshots__/view_image_popover_bar.test.jsx.snap
- tests/components/view_image_popover_bar.test.jsx
Migrate ViewImagePopover to follow the guideline.
The component does not use any stores and actions.
https://github.com/mattermost/mattermost-server/issues/7685
> Migrate ViewImagePopover to follow the guideline

- components/file_attachment.jsx
It just uses the raw SVG file since that's probably smaller than loading a rasterized thumbnail image
https://mattermost.atlassian.net/browse/PLT-7853
> PLT-7853 Added thumbnail for SVG attachments

- components/search_results.jsx
- i18n/en.json
Remove search modifiers from en.json. These are modifiers to perform actual searches and hence shouldn't be localized.
N/A
> Remove search modifiers from en.json

- components/webrtc/components/webrtc_notification.jsx
To make WebRTC notification and ringing sound go away when a call has
been accepted or rejected in another session/window, this change sends
WebrtcActionTypes.CANCEL message to self and handles those kind of
messages to silently close call notification dialog when received and
still in ringing state.
https://mattermost.atlassian.net/browse/PLT-7808
> PLT-7808: Send WebrtcActionTypes.CANCEL to self

- components/profile_popover.jsx
- i18n/en.json
- Added "Edit Account Settings" link to bottom of your own profile popover (this link only appears for your own account)
- Clicking the link opens the Mattermost Account Settings, performing the same action as CTRL/CMD+SHIFT+A
https://mattermost.atlassian.net/browse/PLT-7298
https://github.com/mattermost/mattermost-server/issues/7113
> PLT-7298 Added Edit Account Settings link to bottom of your own profile popover

- components/get_team_invite_link_modal/get_team_invite_link_modal.jsx
- components/get_team_invite_link_modal/index.js
- components/needs_team/needs_team.jsx
- tests/components/get_team_invite_link_modal/__snapshots__/get_team_invite_link_modal.test.jsx.snap
- tests/components/get_team_invite_link_modal/get_team_invite_link_modal.test.jsx
Migrate get_team_invite_link_modal.jsx to be pure and use Redux.
[mattermost-server/issues/7682](https://github.com/mattermost/mattermost-server/issues/7682)
> Migrate get_team_invite_link_modal.jsx to be pure and use Redux

- components/sidebar.jsx
- sass/layout/_sidebar-left.scss
- utils/utils.jsx
Hide channel and team URLs from the sidebar in the desktop app
@asaadmahmood Can I have a hand to fix CSS styling issues for desktop button? Thanks!
Jira ticket: [PLT-7773](https://mattermost.atlassian.net/browse/PLT-7773)
> [PLT-7773] Hide channel and team URLs from the sidebar in the desktop app

- components/suggestion/channel_mention_provider.jsx
The previous version captured everything before the cursor, so it would see that that hadn't changed and not display the autocomplete. Now it only captures everything back to the last tilde so it'll see that change after the user types another tilde to start a new channel link
https://mattermost.atlassian.net/browse/PLT-7833
> PLT-7833 Fixed channel autocomplete not opening after using a tilde outside of a link

- components/suggestion/emoticon_provider.jsx
This is to prevent it from showing up for emoticons that are more than 2 characters long (eg. `:-D`). I removed the previous code that was supposed to show the autocomplete for emoticons since that was supposed to be removed when we added a minimum length required before the autocomplete triggered
https://mattermost.atlassian.net/browse/PLT-7930
> PLT-7930 Don't show emoji autocomplete when the text is an emoticon

- components/new_channel_modal/new_channel_modal.jsx
Fix refresh on edit channel URL button. Not sure what changed recently to break this, but an event was getting fired that would refresh the page if not intercepted.
https://mattermost.atlassian.net/browse/PLT-8002
> PLT-8002 Fix refresh on edit channel URL button

- components/setting_picture.jsx
Firefox doesn't like input elements inside of button tags.
https://mattermost.atlassian.net/browse/PLT-7986
> PLT-7986 Switch file input button to div tag

- utils/utils.jsx
Included '@' prefix on usernames in default case when no fullname or nickname are supplied in the user profile
https://mattermost.atlassian.net/browse/PLT-8005
> PLT-8005: If full name is not set, username is not preceeded by an @-symbol in user lists

- plugins/index.js
I've been trying to come up with better ways to handle common dependencies between the webapp and webapp plugins. Initially, it was looking like it would be fine to manage dependencies for plugins separately and if plugins included multiple copies of a library that would be fine. However, I was never fully confident in this working in cases where the webapp upgraded React and a plugin was using a very old version of React. The deal breaker however was some libraries, such as react-bootstrap, will only work if there is only a single copy of React included on the page.
The new solution here is to have the plugins share the major libraries with the webapp. The major  downside to this is plugins could potentially break if we upgrade to a version of one of these libraries that contains …
> Expose common libraries on window for plugins

- tests/e2e/tests/2_center/centerPage.element.js
The helpTextContainer was removed in the commit 5605fa952a4d682b13b3f0939d9b6b4e5e3c219b
> Remove helpTextContainer check in centerPage e2e test

- components/change_url_modal.jsx
- components/channel_header/channel_header.jsx
- components/delete_modal_trigger.jsx
- components/integrations/components/installed_command.jsx
- components/integrations/components/installed_oauth_app.jsx
- components/integrations/components/installed_outgoing_webhook.jsx
- components/mfa/mfa_controller.jsx
- components/new_channel_flow.jsx
- components/new_channel_modal/new_channel_modal.jsx
- components/post_view/post_list.jsx
- components/search_bar.jsx
- components/sidebar.jsx
- sass/base/_typography.scss
- sass/components/_modal.scss
- sass/components/_search.scss
- sass/layout/_headers.scss
- sass/layout/_post.scss
- sass/layout/_sidebar-menu.scss
- sass/utils/_variables.scss
- utils/utils.jsx
PLT-7977 - Emoji icon overlapping in edit modal
PLT-7965 - Channel header underline fix
PLT-7985 - Fixing more unreads indicator text
PLT-7282 - Adding @ sign before username in modals
PLT-6828 - Hiding url links for clickable elements
PLT-7928 - Pinned post button position fix
PLT-8000 - Long DM name not truncating
PLT-8033 - Fixing manage members button on mobile
https://mattermost.atlassian.net/browse/PLT-7977
https://mattermost.atlassian.net/browse/PLT-7965 …
> Multiple Bug fixes

- sass/components/_status-icon.scss
- utils/utils.jsx
Use default color for dnd indicator if not set in theme. This isn't a proper solution to https://mattermost.atlassian.net/browse/PLT-2068 but it will patch it for the dnd feature.
>  Use default color for dnd indicator if not set in theme

- components/sidebar.jsx
This code was intended to redirect the user to town square if the channel they were looking at disappeared (e.g. due to a sidebar settings change). This makes the condition that triggers that redirect much better.
https://mattermost.atlassian.net/browse/PLT-8028
N/A
> PLT-8028: fix town square loading on team change

- components/get_link_modal.jsx
- tests/components/__snapshots__/get_link_modal.test.jsx.snap
- tests/components/get_link_modal.test.jsx
- tests/setup.js
Migrate get link modal to be pure and use Redux.
[mattermost-server/issues/7679](https://github.com/mattermost/mattermost-server/issues/7679)
> Migrate get link modal to be pure and use Redux

- components/edit_post_modal.jsx
Removed the setItem of 'post_state_transfer' key, which is not used anywhere in
the rest of the mattermost-webapp source code.
I tried to deep in the repository to know where it comes from, but in the first
commit of the current directory is already there and I did't find any getItem
which access to it.
> Removed unneeded BrowserStore usage

- components/image_preview.jsx
- components/loading_image_preview.jsx
- components/view_image.jsx
- tests/components/__snapshots__/image_preview.test.jsx.snap
- tests/components/__snapshots__/loading_image_preview.test.jsx.snap
- tests/components/__snapshots__/view_image.test.jsx.snap
- tests/components/image_preview.test.jsx
- tests/components/loading_image_preview.test.jsx
- tests/components/view_image.test.jsx
Migrate view_image.jsx to be follow the guidline.
https://github.com/mattermost/mattermost-server/issues/7684
> Migrate view_image.jsx to be follow the guidline

- components/pdf_preview.jsx
- tests/components/__snapshots__/pdf_preview.test.jsx.snap
- tests/components/pdf_preview.test.jsx
Migrate pdf_preview component to redux
GitHub: https://github.com/mattermost/mattermost-server/issues/7674
Jira: https://mattermost.atlassian.net/browse/PLT-7674
> [GH-7674] Migrate pdf_preview.jsx to be pure and use Redux

- components/popover_list_members/popover_list_members.jsx
- components/sidebar_header_dropdown.jsx
- components/sidebar_right_menu.jsx
- components/team_members_modal/index.js
- components/team_members_modal/team_members_modal.jsx
- tests/components/team_members_modal/__snapshots__/team_members_modal.test.jsx.snap
- tests/components/team_members_modal/team_members_modal.test.jsx
Migrate team members modal to be pure and use Redux.
[mattermost-server/issues/7792](https://github.com/mattermost/mattermost-server/issues/7792)
> Migrate team members modal to be pure and use Redux

- components/sidebar.jsx
Fixed an issue where a closed favorite channel was being unmarked as a favorite channel. For example, let's say you open a direct message channel with someone and favorite the channel. If you click "x" on the left sidebar to close/hide the channel from the sidebar, when you re-open the direct message channel it is not listed under FAVORITE CHANNELS. This is now fixed for DM and GM channels
**Note**: I was not seeing the observed behavior for Case 2 originally in the ticket before and after my changes but I can look in to it if needed 😄 
https://github.com/mattermost/mattermost-server/issues/6326
> PLT-6432 Channel preferences are restored when closing a DM/GM channel and then re-opening later

- components/sidebar.jsx
- utils/channel_utils.jsx
The sidebar was trying to call functions that only existed in the redux library on the webapp version of ChannelUtils. It was also passing in incorrect arguments as well.
The two functions I marked with TODOs should be replaced by the mattermost-redux versions, but those ones aren't exported, so I didn't want to hold up fixing master for a redux PR.
> Fixed mixup between channel_utils.jsx and the redux version

- components/channel_header/channel_header.jsx
The channelTitle variable was only being set for direct and group channels
> Fixed channel name not showing for public and private channels

- components/channel_header/channel_header.jsx
- components/navbar/index.jsx
- components/rename_channel_modal/index.js
- components/rename_channel_modal/rename_channel_modal.jsx
- tests/components/__snapshots__/rename_channel_modal.test.jsx.snap
- tests/components/rename_channel_modal.test.jsx
Migrated `rename_channel_modal.jsx` to Redux and added tests
https://github.com/mattermost/mattermost-server/issues/7677
> Migrate rename_channel_modal.jsx to use Redux

- actions/channel_actions.jsx
- actions/global_actions.jsx
- components/create_post.jsx
- components/shortcuts_modal.jsx
- components/sidebar_header_dropdown.jsx
Earlier ctrl+/ used to show 'Keyboard shortcuts' dialog but didn't hide dialog box. Fixed to toggle the dialog box to show and hide. @jasonblais
https://mattermost.atlassian.net/browse/PLT-8003
#7751 
- [] Added or updated unit tests (required for all new features)
- [] Has server changes (please link)
- [] Has redux changes (please link)
- [] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [] Touches critical sections of the codebase (auth, posting, etc.)
> PLT-8003: CTRL+/ should toggle keyboard shortcuts dialog

- components/get_public_link_modal/get_public_link_modal.jsx
- tests/components/get_public_link_modal/__snapshots__/get_public_link_modal.test.jsx.snap
- tests/components/get_public_link_modal/get_public_link_modal.test.jsx
The prop `link` is required in `GetLinkModal`, but its value is `undefined`. This fixes that.
Github Ticket: https://github.com/mattermost/mattermost-server/issues/7804
JIRA Ticket: https://mattermost.atlassian.net/browse/PLT-8093
> PLT-8093 Fix prop link is required in GetLinkModal but it is undefined

- components/post_view/post_message_view/post_message_view.jsx
- components/textbox.jsx
- utils/post_utils.jsx
- Make username clickable at popover for at-mention. 
- Also fix placing of mention key (either at RHS or center post) when the username is clicked for at-mention.
Jira ticket: [PLT-8088](https://mattermost.atlassian.net/browse/PLT-8088)
> [PLT-8088] Make username clickable at popover for at-mention

- store/index.js
- utils/network.js
This should remedy the issue we've seen reported where the browser provides a false negative network status, causing redux-offline optimistic actions to fail immediately (posts immediately failing without network requests).
The custom network detector expands on the default, which would rely on the online/offline events and `window.navigator.onLine` provided by the browser. The new flow is:
* The browser reports an online status, trust it and assume we're online
* The browser reports an offline status, don't trust it and try to ping the server to confirm
* If the ping fails, report offline then retry pings continuously with a back-off pattern similar to the websocket reconnect logic to make sure we don't miss an online event
Not implemented in mattermost-redux as this is specific to the …
> PLT-7933 Implement custom network detector

- components/channel_header/channel_header.jsx
Backport fix for PLT-7906 to 4.3 to prevent cascading critical errors that would cause posting issues.
https://mattermost.atlassian.net/browse/PLT-7906
> PLT-7906 (4.3) Fix JS error when switching to a new DM channel

- stores/post_store.jsx
Deep clone drafts to prevent modifying immutable object. This was caused by the fact that redux is now used for the BrowserStore and was sealing objects. Once all the components using drafts are moved over to use the BrowserStore directly, this can go away.
https://mattermost.atlassian.net/browse/PLT-8092
> PLT-8092 Deep clone drafts to prevent modifying immutable object

- components/rhs_comment.jsx
- components/rhs_root_post.jsx
Timestamp links in RHS on desktop app should open in permalink view in the current window	
Jira: https://mattermost.atlassian.net/browse/PLT-8064
n/a
> [PLT-8064] Timestamp links in RHS on desktop app should open in permalink view in the current window

- components/rhs_comment.jsx
> If I post `/poll` and respond in RHS, the profile icon does not appear to be overriding as it does in center.
https://mattermost.atlassian.net/browse/PLT-8112
N/A
> PLT-8112: Icon on RHS interactive response post is inconsistent with center

- components/sidebar.jsx
~~This makes the desktop-specific changes made in https://github.com/mattermost/mattermost-webapp/pull/200 not desktop-specific for parity / good practice.~~
It fixes a bug that was caused by those previously desktop-specific changes by stopping propagation of the event triggered by clicking the close button so that the row's click handler doesn't also fire.
https://mattermost.atlassian.net/browse/PLT-8097
N/A
> PLT-8097: fix sidebar close buttons on desktop

- actions/global_actions.jsx
Explicitly removed @here from search terms when the mentions button is pressed, regardless of notification preferences. Tidied up search term removal code to avoid unnecessary whitespace between search terms
https://mattermost.atlassian.net/browse/PLT-8104
> PLT-8104: @here should not be added to search on clicking @ icon to display mentions

- components/integrations/components/add_oauth_app/add_oauth_app.jsx
Expected keys in JS object were nested within JSON payload's `data` key.
[PLT-8113](https://mattermost.atlassian.net/browse/PLT-8113)
> PLT-8113: Fixes missing values on OAuth2 setup success page.

- components/file_info_preview.jsx
- tests/components/__snapshots__/file_info_preview.test.jsx.snap
- tests/components/file_info_preview.test.jsx
Migrates file_info_preview.jsx to Redux & adds tests
https://github.com/mattermost/mattermost-server/issues/7788
> Migrate file_info_preview.jsx to use Redux & Added tests

- sass/layout/_post.scss
- sass/responsive/_mobile.scss
https://mattermost.atlassian.net/browse/PLT-8118
https://mattermost.atlassian.net/browse/PLT-8106
PLT-8118 - Account settings button misaligned
PLT-8106 - Fixing alignment of post body text
> Release 4.4

- package.json
- yarn.lock
Adds the XRegExp library (that we use in text_formatting.jsx already) and changes the URL pattern to use `\pL` which matches all unicode letters (including CJK characters, Cyrillic letters, accented letters, etc) instead of using `[a-z]` which only matches latin letters
Marked changes here: https://github.com/mattermost/marked/commit/802e981ade71149a497cbe79d12b8a3f82f7657e
https://mattermost.atlassian.net/browse/PLT-7640
> PLT-7640 Updated marked to better handle non-latin characters in URLs

- utils/post_utils.jsx
Fix freeze on certain style code blocks
1. When replacing code blocks with empty string it must remove every single code block (globally) using /regex/g
2. Only accept single-line code using inlineCode regex.
If multi-line code block is wrapped with `` ignore.
https://mattermost.atlassian.net/browse/PLT-8124
via @miguelespinoza
> PLT-8124 Remove all code using regex

- components/get_post_link_modal/index.js
Fix regression on permalink containing "undefined" site URL
Note: I don't see anywhere where we used `getCurrentTeamUrl` from `mattermost-redux`.
Jira ticket: [PLT-8091](https://mattermost.atlassian.net/browse/PLT-8091)
> [PLT-8091] Fix regression on permalink containing "undefined" site URL

- components/post_view/reaction_list/index.js
- components/post_view/reaction_list/reaction_list.jsx
- sass/layout/_post.scss
- sass/responsive/_mobile.scss
- sass/utils/_animations.scss
- utils/utils.jsx
This PR adds an additional button beside a post's reactions that opens the Emoji Picker. This allows the user to add a new reaction to a post that already has reactions.
https://github.com/mattermost/mattermost-server/issues/6284
https://mattermost.atlassian.net/browse/PLT-6229
Screenshot:
> [PLT-6229] Add plus sign for adding to existing emoji reactions

- actions/storage.js
- selectors/rhs.jsx
- selectors/storage.js
- tests/redux/selectors/rhs.test.js
- utils/constants.jsx
Adding new selector for RHS posts embedVisible flags.
> Add selector to get Posts EmbedVisible flags for RHS.

- components/login/login_controller.jsx
Removes the `extra=password_change` query parameter upon submitting a login form so that the "Password updated successfully" flash message disappears in cases where the route does not redirect.
[Jira PLT-8089](https://mattermost.atlassian.net/browse/PLT-8089)
> PLT-8089: Hides "Password updated successfully" flash after login attempt.

- components/new_channel_flow.jsx
Get channelType from initial props in NewChannelFlow
Cc @dmeza
> Get channelType from initial props in NewChannelFlow

- components/quick_switch_modal/quick_switch_modal.jsx
It looks like this was caused by the upgrade to React 16. For some reason the component `refs` isn't getting set in time for `componentDidUpdate()`, when in the past it would.
There are some mentions in the changelog about changes to lifecycle and refs https://github.com/facebook/react/releases/tag/v16.0.0 but nothing that I can see that should directly affect this behavior and all the docs I can find seem to state that refs should be available in time for `componentDidUpate()`.
Fixed by making use of the ref callback.
https://mattermost.atlassian.net/browse/PLT-8208
> PLT-8208 Use ref callback to set focus on channel switcher

- components/post_view/post_message_view/system_message_helpers.jsx
The system message rendered by the client wasn't being returned, causing it to fall back to the message rendered and translated by the system 
https://mattermost.atlassian.net/browse/PLT-8175
https://mattermost.atlassian.net/browse/PLT-8223
> PLT-8175/PLT-8223 Fixed client-side rendering of system messages (4.4.2)

- components/post_view/post_message_view/system_message_helpers.jsx
The system message rendered by the client wasn't being returned, causing it to fall back to the message rendered and translated by the system 
https://mattermost.atlassian.net/browse/PLT-8175
https://mattermost.atlassian.net/browse/PLT-8223
> PLT-8175/PLT-8223 Fixed client-side rendering of system messages

- components/emoji_picker/emoji_picker.jsx
- sass/components/_emoticons.scss
Fix emoji picker not showing up when RHS is expanded
@asaadmahmood Please help validate position of emoji picker in reference to addReaction button. It feels like it's not consistently aligned with each other. Let me know if it should be fixed and if fix can be made via CSS. Thanks!
Jira ticket: [PLT-8123](https://mattermost.atlassian.net/browse/PLT-8123)
> [PLT-8123] Fix emoji picker not showing up when RHS is expanded

- package.json
- yarn.lock
There is some extra migration needed to go from 4.9.x to 4.10.x, and we'll need to do it at the same time that we change it for the redux library and mobile apps to prevent doubling up on our dependencies since we currently have 2 versions of the library installed. I'll also create a separate ticket to upgrade the library in both repos at once
https://mattermost.atlassian.net/browse/PLT-8119
> PLT-8119 Reverted redux-persist to 4.9.1 to match mattermost-redux

- components/user_settings/user_settings_display.jsx
- tests/components/__snapshots__/user_settings_display.test.jsx.snap
Remove specific management settings based on hardcoded configs
cc @dmeza 
> Add classes for mobile dividers

- components/admin_console/storage_settings.jsx
- i18n/en.json
The setting itself is not optional, as an AWS region needs to exist for you to connect, but you can leave the field blank for auto-detection, if preferred.
See https://github.com/mattermost/mattermost-server/pull/7830#issuecomment-346679604 for more details.
> Remove optional tag from AWS region help text

- components/signup/components/signup_email.jsx
The same issue impacted the the signup_email page when an invite link was specified
No ticket, but same problem as https://mattermost.atlassian.net/browse/PLT-8172
> SignupEmail Component Doesn't Render when Invite Link Specified

- components/needs_team/index.js
- components/needs_team/needs_team.jsx
- components/user_settings/user_settings_theme.jsx
- stores/preference_store.jsx
Removes a few more references to the old `PreferenceStore.getTheme(teamId)`. There is one final reference still present that can be eliminated when `ThemeSetting` is migrated to Redux (in another story).
Done related to [PLT-2068](https://mattermost.atlassian.net/browse/PLT-2068) (but not required for it).
> PLT-2068: Switching to use Redux getTheme selector.

- components/edit_channel_header_modal/edit_channel_header_modal.jsx
- tests/components/__snapshots__/edit_channel_header_modal.test.jsx.snap
The textbox doesn't exist yet when the component is first mounted because the modal isn't rendered yet, so wait until it's transitioning in to focus it.
https://mattermost.atlassian.net/browse/PLT-8170
> PLT-8170 Fixed Edit Channel Header modal

- actions/storage.js
- store/index.js
- tests/redux/actions/storage.test.js
I don't love this solution, after investigating a lot other options it is where I ended.
The problem here is how redux-persist works. For each store first level field, it's store one localStorage key, (in our case, the key storage) this force to rehydrate the entire storage in one block. Then, when other tab change something, this restore everything, overwriting the current state with the other tab state.
The solution use the _stateIterator, _stateGetter, and _stateSetter (where though for implement support for other kind of data structure to store the data, like Immutable.js), I used it to virtually move the storage keys to the first level. This allow to each key be stored and restored independently.
The other options are remove the redux-persist usage and use our own implementation of …
> PLT-8210: Store/Restore fields of storage independently in the localStorage

- routes/route_root.jsx
Made the OAuth react route regex more strict to avoid interfering with joining a channel called 'authorize'
1. Start a fresh server with no data in the database (`make clean-docker && make start-docker && make run` in a dev environment)
2. After creating the sys admin account, create a new team with any name _except_ "authorize". I used "test" for my testing
3. Skip the tutorial, and create a new public channel with the display name "authorize". Observe that you join and view the channel immediately, with no white screen of death
4. Check out and configure [Elias's OAuth 2.0 Sample Application](https://github.com/mattermost/mattermost-oauth2-client-sample)
5. Use the sample application to verify that Mattermost still functions as an OAuth 2.0 Provider with these changes. …
> PLT-8027: New channel gives a blank screen if created with reserved word

- components/user_settings/user_settings_advanced.jsx
Hide pre-release feature section of advance settings pane
Here’s the PR for the server: https://github.com/mattermost/mattermost-server/pull/7847
Cc @dmeza
> Hide pre-release features section of advanced settings pane.

- components/admin_console/system_users/system_users_dropdown.jsx
- components/admin_console/system_users/system_users_list.jsx
- components/searchable_user_list/searchable_user_list.jsx
- components/user_list.jsx
- components/user_list_row.jsx
- components/user_list_row_with_error.jsx
- sass/components/_modal.scss
Changed the page layout so that error messages are shown at the user list row level, instead of in the same div that the actions drop down is rendered in.
Testing this change requires simulating a server-side error. To make that easier, here are some screen shots of the list with and without an error message:
I created these first image by modifying the default value of `state` in [user_list_row_with_error.jsx](https://github.com/mattermost/mattermost-webapp/blob/PLT-8062/components/user_list_row_with_error.jsx#L36) to be:
```Javascript
this.state = {error: { message: "This is an error message"}};
```
https://mattermost.atlassian.net/browse/PLT-8062
> PLT-8062: System Console error prints over existing text and pushes drop-down off-view

- components/admin_console/message_export_settings.jsx
Removed exportFromTimestamp from admin panel. It will be managed automatically by the server when config is changed
https://mattermost.atlassian.net/browse/PLT-8198
> PLT-8198: Set the message export timestamp to the date feature was enabled, and remove the setting from the System Console

- actions/views/modals.js
- components/channel_header/channel_header.jsx
- components/channel_header/index.js
- components/modal_controller/index.js
- components/modal_controller/modal_controller.jsx
- components/needs_team/needs_team.jsx
- components/toggle_modal_button_redux/index.js
- components/toggle_modal_button_redux/toggle_modal_button_redux.jsx
- reducers/views/index.js
- reducers/views/modals.js
- tests/components/__snapshots__/modal_controller.test.jsx.snap
- tests/components/__snapshots__/toggle_modal_button_redux.test.jsx.snap
- tests/components/modal_controller.test.jsx
- tests/components/toggle_modal_button_redux.test.jsx
- tests/redux/actions/views/modals.test.js
- tests/redux/reducers/views/modals.test.js
- utils/constants.jsx
Added Redux reducer to toggle modal state. Use ToggleModalButtonRedux instead of ToggleModalButton and provide a modalId prop (defined in constants->modalIdentifiers). There is a ModalController component in the NeedsTeam component that displays the modals.
https://github.com/mattermost/mattermost-server/issues/6784
> Replace modal store with redux view reducer #6784

- components/user_settings/user_settings_display.jsx
- components/user_settings/user_settings_theme.jsx
Remove setState calls in constructor of components.
https://github.com/mattermost/mattermost-server/issues/7918
> Fix setState calls when switching to Display tab in Account Settings

- utils/channel_utils.jsx
Changed the first parameter to redux's `isDirectChannelVisible` and missed this.
https://mattermost.atlassian.net/browse/PLT-8258
> PLT-8258: fix favorited dms

- components/add_users_to_team/add_users_to_team.jsx
- components/channel_invite_modal/channel_invite_modal.jsx
- components/more_direct_channels/more_direct_channels.jsx
This is a fix for JS error on Multiselect component encountered for the following repro steps:
- click `Add Members to Team` at Main Menu
- click `More…` Direct Messages at left sidebar
- click `Add Members` at channel header menu
none
> Fix JS error on Multiselect component

- utils/constants.jsx
This was causing a warning whenever you click a user's name in the profile popover.
> Added missing action type

- routes/route_team.jsx
This is only part of the solution, the other part is in mattermost/mattermost-redux#337
[PLT-7111](https://mattermost.atlassian.net/browse/PLT-7111)
> PLT-8243: Load DM and GM data when needed on /groupmsg or /msg

- components/channel_header/channel_header.jsx
- components/channel_notifications_modal.jsx
- components/navbar/navbar.jsx
This PR only fix the first issue of the ticket regarding radio button selection of ChannelNotificationsModal.
The main issue which was to restore channel notifications preferences when a member left then rejoined, I think, is a desired behavior based on our current codebase and it has not changed for a long time - https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/channel_store.go#L1040
Jira ticket: [PLT-8202](https://mattermost.atlassian.net/browse/PLT-8202)
> [PLT-8202] Fix radio button selection of ChannelNotificationsModal

- components/post_view/post_message_view/index.js
- components/post_view/post_message_view/post_message_view.jsx
Uses the "channel_mention" hints generated by https://github.com/mattermost/mattermost-server/pull/7833 when users aren't in the linked channel.
Before the repo split this was part of https://github.com/mattermost/mattermost-server/pull/7324
https://mattermost.atlassian.net/browse/PLT-5458
> PLT-5458: use channel_mention hints

- Makefile
Adds a `make help` command that uses inline comments to document the commands.
n/a
If people like this pattern I'll add it to the other repos (but don't want to add it to mattermost-server until https://github.com/mattermost/mattermost-server/pull/7892 is merged).
> Adds inline make documentation and 'help' command.

- components/at_mention/at_mention.jsx
Use `hasOwnProperty` to check for user on users object
https://github.com/mattermost/mattermost-server/issues/7944
> Fix atMention to check for user on users object only

- actions/websocket_actions.jsx
This was causing the `postsInChannel` map in the redux handlers to get an "undefined" channel inserted into it since they expect this property.
https://mattermost.atlassian.net/browse/PLT-8302
> PLT-8302: add channelId to RECEIVED_POSTS action after edit

- components/needs_team/needs_team.jsx
Use CMD instead of CTRL for textbox focusing on Mac.
https://mattermost.atlassian.net/browse/PLT-8209
> PLT-8209 Use CMD instead of CTRL for textbox focusing on Mac

- components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
- components/rename_channel_modal/rename_channel_modal.jsx
- tests/components/__snapshots__/edit_channel_purpose_modal.test.jsx.snap
- tests/components/__snapshots__/rename_channel_modal.test.jsx.snap
I'm not sure what caused this to finally break, but I don't think the behavior of our code was ever well-defined. `componentDidMount` can be called before nested components mount. So instead of referencing nested components from it, we need to wait a little longer. `Modal` has an `onEntering` prop that seems appropriate.
I'm not sure it's strictly necessary, but I'm also updating the refs to use callback assignment as this is the preferred way of using refs (https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element).
https://mattermost.atlassian.net/browse/PLT-8170
> PLT-8170: Fix channel name / purpose modals

- components/user_settings/user_settings_general/user_settings_general.jsx
- Fixes user settings when LDAP is enabled so you can edit your nickname if that field is not set in LDAP.
https://mattermost.atlassian.net/browse/PLT-8267
> PLT-8267 Fixing LDAP nickname setting block.

- components/user_settings/desktop_notification_settings.jsx
- i18n/en.json
Note that desktop notification duration is a max of 5 seconds for desktop apps.
To fix it requires upstream changes in Electron. The required level of effort doesn't exceed the benefit: https://github.com/mattermost/desktop/issues/304#issuecomment-346902736
cc: @yuya-oc @esethna
> Note that desktop notification duration is a max of 5 seconds for desktop apps

- components/channel_header/channel_header.jsx
Remove the ability to make web call when the user is in his own DM channel
JIRA: https://mattermost.atlassian.net/browse/PLT-8271
> remove the video call from the his own DM channel

- components/channel_header/channel_header.jsx
- sass/layout/_headers.scss
- utils/utils.jsx
PLT-8292 - Updating webrtc button
https://mattermost.atlassian.net/browse/PLT-8292
> PLT-8292 - Updating webrtc button

- actions/user_actions.jsx
- components/user_settings/manage_languages.jsx
- components/user_settings/user_settings_general/user_settings_general.jsx
- utils/constants.jsx
Remove unused `type` argumnet of UserActions.updateUser and remove unused/unnecessary Constants.UserUpdateEvents.
This initiative came after while working on PLT-8222.
none
> Remove unused type arg of UserActions.updateUser and remove unused/unnecessary Constants.UserUpdateEvents

- components/user_settings/user_settings_display.jsx
Hide locale setting if there's a single locale available Ex: "AvailableLocales": "en"
Remove the part of the server PR that's not needed any more
Cc @dmeza
> Hide locale setting if there's a single locale available

- package.json
- utils/channel_utils.jsx
Update for https://github.com/mattermost/mattermost-redux/pull/351
Once that PR is merged, I'll need to update package.json here before building / merging this.
https://mattermost.atlassian.net/browse/PLT-8321
> PLT-8321: simplify isXVisible callsites

- components/post_view/post_message_view/index.js
- selectors/emojis.js
This change was suggested by @sudheerDev, but it turned out it was already part of one of my other PRs so we broke it out on it's own.
@esethna I'm proposing this for 4.5 since it leads to a fair bit less memory usage on pre-release, and the change is minimal since it works the same as before except it doesn't create as many copies of some stuff in memory.
> Avoid creating a new EmojiMap for each post

- components/color_input.jsx
- components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
- components/emoji_picker/emoji_picker.jsx
- components/post_view/post/post.jsx
- components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
- components/rename_channel_modal/rename_channel_modal.jsx
- components/search_bar/search_bar.jsx
Change inline arrow function in ref
Jira ticket: [PLT-8296](https://mattermost.atlassian.net/browse/PLT-8296)
> [webapp-perf] Change inline arrow function in ref

- components/post_view/new_message_indicator.jsx
- sass/layout/_post.scss
1. Certain users have been experiencing an issue with the `NewMessageIndicator` not dissapearing after getting to the bottom of the channel.
2. One user had a link that was not clickable because the `NewMessageIndicator` was blocking the clickHandler from the message.
I was not able to reproduce or the first issue.  Works fine on Chrome, Mac client, Safari.  This issue has been reported by Mac Client users.
This PR addresses the second issue. Have parent `div` wrap children. This allows the user to click the left or right side of the `NewMessageIndicator` As seen in the screenshot below
@miguelespinoza
> Remove div container taking up width

- components/navbar/navbar.jsx
- tests/components/navbar/__snapshots__/navbar.test.jsx.snap
- Fix header link to be clickable on mobile web view by changing `ToggleModalButton` to `ToggleModalButtonRedux`. There might be something with React-16 that made the former component failed to propagate click event.
Note: I'll submit separate PR to master changing all `ToggleModalButton` to `ToggleModalButtonRedux`.
Jira ticket: [PLT-8339](https://mattermost.atlassian.net/browse/PLT-8339)
> [PLT-8339] Fix header link to be clickable on mobile web view

- components/announcement_bar/announcement_bar.jsx
- components/root.jsx
- stores/browser_store.jsx
- utils/constants.jsx
- Clear announcement localStorage on logout
- add StoragePrefixes constants ('__logout__', '__login__', '__announcement__')
Jira ticket: [PLT-8359](https://mattermost.atlassian.net/browse/PLT-8359)
> [PLT-8359] Clear announcement localStorage on logout, and add StoragePrefixes constants

- package.json
- yarn.lock
The package.json and yarn.lock were out of sync, so I updated them to match each other so that we'll have a correct version if we need to go back to 4.5 in the future.
> Fixed yarn.lock

- actions/views/edit_post_modal.js
- components/edit_post_modal/edit_post_modal.jsx
- components/edit_post_modal/index.js
- tests/components/edit_post_modal.test.jsx
When moving this modal to redux, we stopped using PostActions.updatePost which had threw any error to the error bar. This re-adds it in a react-friendly way
https://mattermost.atlassian.net/browse/PLT-8358
> PLT-8358 Fixed editing a post after too late not showing an error

- components/create_post.jsx
- components/persist_gate/index.js
- components/persist_gate/persist_gate.js
- reducers/storage.js
- root.jsx
- selectors/rhs.jsx
- selectors/storage.js
- store/index.js
- tests/redux/actions/storage.test.js
- tests/redux/actions/views/create_comment.test.jsx
- tests/redux/reducers/storage.test.js
- tests/redux/selectors/rhs.test.js
- tests/redux/selectors/storage.test.js
Because previously storage wasn't always loaded when the app started it would cause two things:
1. The post draft for the current channel wouldn't usually be loaded
2. The previous team/channel wouldn't be loaded if you didn't explicitly navigate to them
This prevents the app from loading until the storage is loaded. Ideally, we would lock the individual parts, but because the routing code controls the current team/channel, we needed to prevent even that from running.
https://mattermost.atlassian.net/browse/PLT-8244
- Touches critical sections of the codebase (auth, posting, etc.)
> PLT-8244 Prevented web app from loading before storage is loaded

- components/channel_view.jsx
Fix error on clicking permalink from a private channel where the user is not member of
Jira ticket: [PLT-8385](https://mattermost.atlassian.net/browse/PLT-8385)
> [PLT-8385] Fix error on clicking permalink from a private channel where the user is not member of

- components/rename_channel_modal/index.js
Fix regression on Rename Channel URL box showing undefined for domain name
Jira ticket: [PLT-8387](https://mattermost.atlassian.net/browse/PLT-8387)
> [PLT-8387] Fix regression on Rename Channel URL box showing undefined for domain name

- actions/post_actions.jsx
- package.json
- utils/user_agent.jsx
- yarn.lock
This requires a PR from the redux repo
> PLT-8335 Fixing issue where posts do not send on iOS classic

- components/searchable_user_list/searchable_user_list.jsx
In the searchable user list modal, it now computes `endCount` without having to rely on network requests. On a per page basis this was causing a race case where the pagination would show 50 - 96 then show 50 - 100 half a second later.  Its due to `count` being computed by the incoming network request per page which was being used to compute `endCount`. This is redundant and we can instead compute `endCount` based on the current page number and the total number of users of the team / channel (see code).  [Closes mattermost-server#7964](https://github.com/mattermost/mattermost-server/issues/7964)
- [Jira PLT-8333](https://mattermost.atlassian.net/browse/PLT-8333)
- https://github.com/mattermost/mattermost-server/issues/7964
> PLT-8333  Fix endCount in the searchable user list model's pagination

- components/edit_post_modal/edit_post_modal.jsx
- tests/components/edit_post_modal.test.jsx
- Do not show DeletePostModal if edited message is empty but with attachment
- Only show DeletePostModal if edited message is empty and without attachment
Others:
- corrected spelling to `hiding`
Jira ticket: [PLT-8268](https://mattermost.atlassian.net/browse/PLT-8268)
> [PLT-8268] Do not show DeletePostModal if edited message is empty but with attachment

- components/file_attachment.jsx
- components/file_preview.jsx
- tests/components/__snapshots__/file_attachment.test.jsx.snap
- tests/components/__snapshots__/file_preview.test.jsx.snap
- utils/constants.jsx
- utils/utils.jsx
Adds Inline playback for git attachments
Cc @dmeza
> inline playback for gif attachments

- components/create_comment/create_comment.jsx
- components/create_comment/index.js
- tests/components/create_comment/create_comment.test.jsx
Make PostDeletedModal to show always after replying to a deleted post
- by clearing createPost status/error after hiding `PostDeletedModal` or on `componentWillUnmount`
Jira ticket: [PLT-7829](https://mattermost.atlassian.net/browse/PLT-7829)
> [PLT-7829] Make PostDeletedModal to show always after replying to a deleted post

- actions/websocket_actions.jsx
Fixes making bad requests when reconnecting on the system console and other non-team pages. This is really just a quick fix for the issue, fixing the core problem would be to change the pattern for all our actions to not make these requests when some required data is missing. That's a ton more work than this ticket merits though.
https://mattermost.atlassian.net/browse/PLT-8265
> PLT-8265 Only pull channel/team data on reconnect if on a team

- components/error_page/error_link.jsx
- components/error_page/error_message.jsx
- components/error_page/error_title.jsx
- components/error_page/index.jsx
- i18n/en.json
- tests/components/error_page/__snapshots__/error_link.test.jsx.snap
- tests/components/error_page/__snapshots__/error_message.test.jsx.snap
- tests/components/error_page/__snapshots__/error_page.test.jsx.snap
- tests/components/error_page/__snapshots__/error_title.test.jsx.snap
- tests/components/error_page/error_link.test.jsx
- tests/components/error_page/error_message.test.jsx
- tests/components/error_page/error_page.test.jsx
- tests/components/error_page/error_title.test.jsx
- Fix error title for oauth_missing_code error type, 
- Refactor ErrorPage component, 
- Add related stateless components,
- Add unit tests
Jira ticket: [PLT-7615](https://mattermost.atlassian.net/browse/PLT-7615)
> [PLT-7615] Fix error title for oauth_missing_code error type, refactor ErrorPage component, add related stateless components and unit tests

- components/autosize_textarea.jsx
This is a quick fix for the previously submitted patch which mistakenly interchanged styles for `container` and `reference` of post text box.
https://github.com/mattermost/mattermost-webapp/commit/d0de4f01bc9dd08e896ecfdce5baeeb6349a6c03#r26394782
> Fix post text box style issue

- components/user_settings/email_notification_setting.jsx
The default time span for email notifications is 15 minutes. While in the process of saving, the user settings are in an inconsistent state, so this default is returned, and causes a re-render of the component. Ignored new props while saving to avoid the undesirable re-render.
https://mattermost.atlassian.net/browse/PLT-8334
> PLT-8334: Radio button selection changes selections on Account Settings > Notifications > Email Notifications while saving

- components/analytics/statistic_count.jsx
Fix warning from statistic count component by using `isNaN()` over null checking.
https://mattermost.atlassian.net/browse/PLT-8374
> PLT-8374 Fix warning from statistic count component

- components/navbar/navbar.jsx
DM with yourself doesn't say "(you)" in header on mobile web
JIRA: https://mattermost.atlassian.net/browse/PLT-8342
> [PLT-8342] DM with yourself doesn't say "(you)" in header on mobile web

- actions/views/rhs.js
- components/search_bar/index.jsx
- components/search_bar/search_bar.jsx
- components/search_results/index.jsx
- components/search_results/search_results.jsx
- reducers/views/rhs.js
- selectors/rhs.jsx
- tests/redux/actions/views/rhs.test.js
- tests/redux/reducers/views/rhs.test.js
- utils/constants.jsx
Add loading animation to RHS when flagged posts list is loading
- add loading indicator to search results but not on search bar
Jira ticket: [PLT-8397](https://mattermost.atlassian.net/browse/PLT-8397)
> [PLT-8397] Add loading animation to RHS when flagged posts list is loading

- actions/diagnostics_actions.jsx
- components/channel_view/channel_view.jsx
- components/sidebar.jsx
- components/team_sidebar/components/team_button.jsx
- root.jsx
Adds pattern for using [JS Performance API](https://developer.mozilla.org/en-US/docs/Web/API/Performance) and tracks:
- channel switching (dev mode)
- team switching (dev mode)
- page load
The information appears in the Chrome performance tab and also is sent to Segment under the 'performance' category.
n/a
> Wraps JS Performance API.

- components/post_view/post_list.jsx
- components/post_view/post_time.jsx
- components/rhs_comment.jsx
- components/rhs_root_post.jsx
- components/search_results_item/search_results_item.jsx
- utils/utils.jsx
Fix memory leak caused by post_time.jsx component.
Results are compared between release-4.5 branch and this commit. 
Note: Numbers might vary little depending on posts in thread.
Stats are for one of the two threads i was using for switch and same is being used for all comparisons.
Normal channel switch is about `3.4mb allocation` with `2.7mb retained` on every switch
With the PR almost `same memory is allocated` and about `415kb is retained`(Mostly less than this).
> Fix closure memory issue in GC

- components/search_results/search_results.jsx
- components/search_results_item/index.js
- components/search_results_item/search_results_item.jsx
Add commentCount to DotMenu for search results and flagged posts
Remove unused isFlaggedSearch prop.
User should be notified consistently when deleting parent post from RHS
https://github.com/mattermost/mattermost-server/issues/7878
> PLT-8185: User should be notified consistently when deleting parent post from RHS

- components/search_results_item/index.js
- components/search_results_item/search_results_item.jsx
- tests/components/search_results_item.test.jsx
This is a quick fix to Javascript error when opening RHS.
none
> Fix JS error on actions.emitCLoseRightHandSide

- components/user_settings/manage_languages.jsx
Fix indefinite loading of spinner button at language setting when saving without change, by:
- not spinning
- exiting on language setting max view
Jira ticket: [PLT-8400](https://mattermost.atlassian.net/browse/PLT-8400)
> [PLT-8400] Fix indefinite loading of spinner button at language setting when saving without change

- components/channel_view/index.js
- components/create_post/create_post.jsx
- components/needs_team/needs_team.jsx
- components/sidebar.jsx
- components/sidebar_header.jsx
- components/sidebar_right_menu/sidebar_right_menu.jsx
- tests/components/create_post/create_post.test.jsx
Enable tutorial screen with `EnableTutorial` property
Here’s the PR for the server: https://github.com/mattermost/mattermost-server/pull/7840
cc @dmeza 
> add config option to hide tutorial screens

- tests/components/__snapshots__/edit_channel_header_modal.test.jsx.snap
- tests/components/__snapshots__/edit_channel_purpose_modal.test.jsx.snap
- tests/components/__snapshots__/edit_post_modal.test.jsx.snap
- tests/components/__snapshots__/file_info_preview.test.jsx.snap
- tests/components/__snapshots__/rename_channel_modal.test.jsx.snap
- tests/components/__snapshots__/search_results_item.test.jsx.snap
- tests/components/about_build_modal.test.jsx
- tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
- tests/components/dot_menu/__snapshots__/dot_menu_edit.test.jsx.snap
- tests/components/dot_menu/__snapshots__/dot_menu_empty.test.jsx.snap
- tests/components/dot_menu/__snapshots__/dot_menu_flag.test.jsx.snap
- tests/components/dot_menu/__snapshots__/dot_menu_item.test.jsx.snap
- tests/components/dot_menu/__snapshots__/dot_menu_mobile.test.jsx.snap
- tests/components/dot_menu/dot_menu.test.jsx
- tests/components/dot_menu/dot_menu_edit.test.jsx
- tests/components/dot_menu/dot_menu_empty.test.jsx
- tests/components/dot_menu/dot_menu_flag.test.jsx
- tests/components/dot_menu/dot_menu_item.test.jsx
- tests/components/dot_menu/dot_menu_mobile.test.jsx
- tests/components/edit_channel_header_modal.test.jsx
- tests/components/edit_channel_purpose_modal.test.jsx
- tests/components/edit_post_modal.test.jsx
- tests/components/file_info_preview.test.jsx
- tests/components/header_footer_template.test.jsx
- tests/components/integrations/edit_command.test.jsx
- tests/components/rename_channel_modal.test.jsx
- tests/components/search_results_item.test.jsx
Sample snapshots test failures:
```
Object {
-               "currentYear": 2017,
+               "currentYear": 2018,
}
<span
className="pull-right footer-link copyright"
>
-           © 2015-2017 Mattermost, Inc.
+           © 2015-2018 Mattermost, Inc.
</span>
```
Fix currentYear snapshots test failure by:
- mocking up the date at AboutBuildModal and HeaderFooterTemplate components
Also, did small cleanup/update on 
- tests description 
- EditCommand tests
none
> Fix currentYear snapshots test failure

- actions/websocket_actions.jsx
Handle getting user updated event for logged in user by requesting self if update_at is newer than the one we have.
Web app portion of https://mattermost.atlassian.net/browse/PLT-8352
> PLT-8352 Handle getting user updated event for logged in user

- components/setting_item_max.jsx
While fixing PLT-8212, a prop type validation for SettingItemMax was missed, which is fixed in this commit
> Fix prop type validation for SettingItemMax(PLT-8212)

- components/user_settings/user_settings_notifications.jsx
Changed the default notification setting for  pushStatus to away for new users. It doesn't make sense to default the most noisy setting.
cc @dmeza 
> UCHAT-60 change default notification settings for new users

- utils/utils.jsx
Fix JS error when switching teams mid channel switch. The problem was sometimes channel could be undefined initially.
https://mattermost.atlassian.net/browse/PLT-8461
> PLT-8461 Fix JS error when switching teams mid channel switch

- actions/global_actions.jsx
- components/suggestion/command_provider.jsx
- components/suggestion/suggestion_box.jsx
- stores/suggestion_store.jsx
Also, clear `completePending` flag once message has been submitted
1. Fixes issue with SuggestionList not displaying after certain period
2. Fixes issue with suggestion terms repeating
`@user => @u@u@user`
`:thumbsup: :thu:thu:thu:`
https://mattermost.atlassian.net/browse/PLT-7647
Another scenario is where a user completes the term before the suggestion returns back
1. type `@one`
2. on [ENTER] it adds a space after the autocompleted term `@one `
3. on `handleCompleteWord` it attempts to complete & replace a pretext that has been completed by the user, therefore, you end up with a similar situation with the result: `@one@one`
> Prevent text substitutions for suggestions that are outdated

- components/common/comment_icon.jsx
- components/post_view/post/post.jsx
- components/post_view/post_body/post_body.jsx
- components/post_view/post_header/post_header.jsx
- components/post_view/post_info/post_info.jsx
- tests/components/__snapshots__/search_results_item.test.jsx.snap
- tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
- tests/components/post_view/post_info/post_info.test.jsx
A while ago I profiled channel switching and discovered that the mounting time for posts was a big factor in the performance of channel switching. Here's a more recent profile (using 4x CPU slowdown) showing this:
From that profile, the mounting of the posts is totalling about 1.33s, with each post taking around 40-60ms each. Looking a bit deeper, the PostHeader component is causing the majority of that (averaging around 65% depending on the post), the ProfilePicture takes up a small slice (5% or so) and the PostBody takes up the rest.
So first, I took a look at what we're doing in PostHeader (and its immediate child PostInfo) to see if there's anything we could remove or speed up.
The first thing I found was that we were mounting the DotMenu, EmojiPicker and CommentIcon components for …
> [webapp-perf] Reduce post mounting time to speed up channel switching

- components/channel_view/index.js
Convert return value to boolean so it doesn't return `undefined` and cause React errors about missing properties.
https://mattermost.atlassian.net/browse/PLT-8437
> PLT-8437: Convert return value to boolean

- actions/global_actions.jsx
- components/suggestion/provider.jsx
- components/suggestion/suggestion_box.jsx
- stores/suggestion_store.jsx
These were intended to be a fix to the bizarre behaviour that sometimes happens when the user hit tab or enter while autocomplete results were being loaded, but it didn't end up really helping that. Instead, it resulted in some cases where we didn't store autocomplete suggestions which caused the autocomplete to stop working completely.
https://mattermost.atlassian.net/browse/PLT-8306
> PLT-8306 Removed completePending/suggestionsPending flags from SuggestionStore

- utils/constants.jsx
Remove PostTypes.ADD_TO_CHANNEL from IGNORE_POST_TYPES to prompt mention when user is added to channel/team
If above is correct solution, I'll submit similar patch to mattermost-redux https://github.com/mattermost/mattermost-redux/blob/master/src/constants/posts.js#L31
Jira ticket: [PLT-8464](https://mattermost.atlassian.net/browse/PLT-8464)
> [PLT-8464] Remove PostTypes.ADD_TO_CHANNEL from IGNORE_POST_TYPES to prompt mention  when user is added to channel/team

- components/admin_console/saml_settings.jsx
Allow .cert extensions for IDP files.
https://mattermost.atlassian.net/browse/PLT-8487
> PLT-8487 Allow .cert extensions for IDP files

- components/new_channel_flow.jsx
- tests/components/new_channel_flow.test.jsx
- utils/constants.jsx
The part of the channel creation flow was removed that's meant to show the URL modal when creating a channel with only non-Latin characters in the display name, so I re-added that along with some unit tests and some minor cosmetic refactoring.
https://mattermost.atlassian.net/browse/PLT-8454
> PLT-8454 Re-added flow for creating channel with only non-Latin characters

- sass/layout/_headers.scss
Fixes channel header to display only one line and lets it overflow by hiding the rest.
https://mattermost.atlassian.net/browse/PLT-8488
> [PLT-8488] Change height of header to accommodate only one line

- utils/constants.jsx
Add join/leave team system messages to the ignored list of messages type to
count as unread messages in channels.
This only solves the frontend part of the problem, the backend part
(mattermost/mattermost-server#8042) is not needed to merge this, but to close
the issue both PRs have to be merged.
[PLT-8483](https://mattermost.atlassian.net/browse/PLT-8483)
> PLT-8483: Ignore join/leave team messages for unread counts

- utils/constants.jsx
Remove duplicate keys on constants (might be due to bad merge)
- JOIN_TEAM
- LEAVE_TEAM
None, only quick fix
> Remove duplicate keys on constants

- components/search_bar/search_bar.jsx
- utils/utils.jsx
When opening the webapp in mobile view on Firefox (57) the page wasn't being rendered at all, two issues where found:
1. When mounting the search_bar component the element `'.app__body .sidebar--menu'` returns null
2. the util to `changeCss` received a className that was not supported by `styleSheet.insertRule`
Note: Without this PR I cannot complete my RC tests as the webapp does not render at all.
> Fix FF in mobile view

- components/channel_notifications_modal.jsx
- components/setting_item_max.jsx
- components/setting_item_min.jsx
- components/team_general_tab.jsx
- components/user_settings/desktop_notification_settings.jsx
- components/user_settings/email_notification_setting.jsx
- components/user_settings/manage_languages.jsx
- components/user_settings/user_settings_advanced.jsx
- components/user_settings/user_settings_display.jsx
- components/user_settings/user_settings_general/user_settings_general.jsx
- components/user_settings/user_settings_notifications.jsx
- components/user_settings/user_settings_security/user_settings_security.jsx
- components/user_settings/user_settings_sidebar.jsx
- components/user_settings/user_settings_theme.jsx
- tests/components/__snapshots__/setting_item_max.test.jsx.snap
- tests/components/__snapshots__/setting_item_min.test.jsx.snap
- tests/components/__snapshots__/user_settings_display.test.jsx.snap
- tests/components/setting_item_max.test.jsx
- tests/components/setting_item_min.test.jsx
- tests/components/user_settings/__snapshots__/email_notification_setting.test.jsx.snap
- tests/components/user_settings/email_notification_setting.test.jsx
Migrate SettingItemMin and SettingItemMax to pure component, and avoid/replace anonymous inline function on props
(Note: This is the first PR related to anonymous inline function on props)
Jira ticket: [PLT-8296](https://mattermost.atlassian.net/browse/PLT-8296)
> [webapp-perf] Migrate SettingItemMin and SettingItemMax to pure component, and replace anonymous function on props

- components/member_list_channel/index.js
- components/member_list_channel/member_list_channel.jsx
- components/popover_list_members/index.js
- components/popover_list_members/popover_list_members.jsx
- sass/components/_popover.scss
- sass/components/_status-icon.scss
- tests/utils/utils.test.jsx
- utils/constants.jsx
- utils/utils.jsx
Show status icon and sort by user's status (in the order of online > away > offline > dnd) to the following components:
- MemberListChannel
- PopoverListMembers (though not specifically mentioned in the ticket)
@jasonblais @esethna You might want to check this out if according to ticket specs. (I'm not really sure about the coverage). Also not sure if this should be for v4.5 as stated in Jira ticket.
Jira ticket: [PLT-7409](https://mattermost.atlassian.net/browse/PLT-7409)
> [PLT-7409] Channel Member List: show status icon and sort by user's status

- components/admin_console/jobs/table.jsx
- components/admin_console/plugin_management/plugin_management.jsx
- components/channel_header/channel_header.jsx
- components/dot_menu/dot_menu_edit.jsx
- components/emoji_picker/emoji_picker_overlay.jsx
- components/file_attachment_list/file_attachment_list.jsx
- components/get_team_invite_link_modal/get_team_invite_link_modal.jsx
- components/integrations/components/installed_outgoing_webhooks/installed_outgoing_webhooks.jsx
- components/invite_member_modal.jsx
- components/mfa/mfa_controller.jsx
- components/more_direct_channels/more_direct_channels.jsx
- components/multiselect/multiselect.jsx
- components/navbar/navbar.jsx
- components/new_channel_modal/new_channel_modal.jsx
- components/popover_list_members/popover_list_members.jsx
- components/post_view/post_attachment.jsx
- components/profile_popover.jsx
- components/quick_switch_modal/quick_switch_modal.jsx
- components/rhs_comment.jsx
- components/rhs_root_post.jsx
- components/select_team/select_team.jsx
- components/sidebar_header_dropdown.jsx
- components/sidebar_right_menu/sidebar_right_menu.jsx
- components/tutorial/tutorial_intro_screens.jsx
- components/tutorial/tutorial_tip.jsx
- components/user_settings/desktop_notification_settings.jsx
- components/user_settings/email_notification_setting.jsx
- components/user_settings/import_theme_modal.jsx
- tests/components/integrations/installed_outgoing_webhooks.test.jsx
- tests/components/user_settings/__snapshots__/email_notification_setting.test.jsx.snap
- Change anonymous inline functions into a defined arrow functions.
- Make use of `data-attr` in storing information which serves as parameter of underlying function.
Note: This is second installment PR. Other PR submitted:
- https://github.com/mattermost/mattermost-webapp/pull/480
> [webapp-perf] Change anonymous inline function into a defined arrow function

- utils/constants.jsx
- utils/utils.jsx
Using a transparent pixel when the user profile isn't in the store. I
understand here that if the profile isn't in the store is because is loading
it, but in the near future will be in the store. If that is true, the fix have
sense.
[PLT-7607](https://mattermost.atlassian.net/browse/PLT-7607)
> [PLT-7607] Use transparent pixel while the user profile isn't loaded

- components/create_comment/create_comment.jsx
- components/create_comment/index.js
- tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
- tests/components/create_comment/create_comment.test.jsx
Add the confirm modal to send `@all`/`@channel` mentions in the RHS comments.
[PLT-8475](https://mattermost.atlassian.net/browse/PLT-8475)
> [PLT-8475] Add confirm modal to @all/@channel metions in the RHS comments

- components/admin_console/saml_settings.jsx
Allow .pem extensions for SAML IDP files
https://github.com/mattermost/desktop/issues/497
> Allow .pem extensions for SAML IDP files

- components/create_post/index.js
- components/get_post_link_modal/index.js
- components/get_team_invite_link_modal/get_team_invite_link_modal.jsx
- components/needs_team/needs_team.jsx
- components/sidebar.jsx
- components/sidebar_right/sidebar_right.jsx
- components/status_dropdown/index.jsx
- components/status_dropdown/status_dropdown.jsx
When mattermost-redux receives a 401 from the server, it moves to log out the user and causes the redux store to be emptied. Unfortunately many of our components are a bit fragile and will break if some of their props (usually current user/team/channel) are not set. Those two previous facts combined with revoking your current session created a race between JS errors from these fragile components and the bit of code pushing the browser to the login page.
This PR should patch the components that were breaking in this situation. Ideally all of our components would be more robust and be able to handle rendering when missing any prop but this is a start
https://mattermost.atlassian.net/browse/PLT-8509
> PLT-8509 Fix many places where components error when missing props

- actions/channel_actions.jsx
This PR redirects a user to the town square channel before unsubscribing them from the current channel.
https://mattermost.atlassian.net/browse/PLT-8508
https://github.com/mattermost/mattermost-server/issues/8053
> PLT-8508: switch channel before leaving the channel

- actions/global_actions.jsx
- components/post_markdown/system_message_helpers.jsx
- components/post_view/post/post.jsx
- components/post_view/post_add_channel_member/index.js
- components/post_view/post_add_channel_member/post_add_channel_member.jsx
- components/post_view/post_list.jsx
- tests/components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
- utils/constants.jsx
- Do not show add-user-to-channel ephemeral message at center
When user/s is added to channel by clicking @mention links at RHS, "add-user-to-channel" system message is posted at center while ephemeral message at RHS.
@jasonblais Here is the client-side change preventing both system and ephemeral messages being posted at center. 
Jira ticket: [PLT-8424](https://mattermost.atlassian.net/browse/PLT-8424)
> [PLT-8424] Do not show add-user-to-channel ephemeral message at center

- components/delete_post_modal.jsx
The issue here is a race condition. The problem seems to be that the children elements are being rendered by the parent element. So, at time of render, they are actually not rendered. They have to wait for the `<Modal />` to fully render. So, when autoFocus is being called, they don't actually exist. 
The same issue seems to have always been there, which is why there is a setTimeOut(()=>{}, 0) already there. However, I believe that the transition from one modal to the other is a slightly longer delay, which is causing the autoFocus to fire prematurely. 
The fix I added was simply increasing the SetTimeOut length to 200 milliseconds. The issue with this is that it isn't instantaneous and, yet, is still subject to the same race issue in the future. But it works for now.
I also added the …
> Fixed autoFocus issue with delete modal after edit

- components/image_preview.jsx
- components/post_view/post_body_additional_content.jsx
- components/post_view/post_image.jsx
- components/view_image.jsx
- components/view_image_popover_bar.jsx
- tests/components/__snapshots__/view_image.test.jsx.snap
Preview link images just like you do with images uploaded from MM.
1.
2.
3.
4. download image if desired
> Add suppport for image links to be previewed

- actions/views/lhs.js
- components/sidebar/sidebar.jsx
- routes/route_team.jsx
- tests/redux/actions/views/lhs.test.js
Remove promises on onEnter hooks
Edit:
Network setting: Fast 3g
Team switch takes about 3 sec for first paint of conversation on master.
With PR it takes about 1.4 sec for first pain of conversation
> [webapp-perf]: Remove deferred calls on onEnter hooks

- components/navbar/navbar.jsx
Modal listeners were being added but, instead of being removed, were being added **again** on Unmount
https://mattermost.atlassian.net/browse/PLT-8299
> Fix ModalListener ‘memory leak’ issue

- components/header_footer_template/header_footer_template.jsx
- tests/components/__snapshots__/header_footer_template.test.jsx.snap
Currently, tab and alt-tab keyboard navigations are reversed for links on login page (tabbing through page takes you through Help, Terms, Privacy, and then About)
This pull request fixes this issue and the navigation is now About, Privacy, Terms, then Help
https://github.com/mattermost/mattermost-server/issues/8046
> PLT-8455 Fixed tab and alt-tab keyboard navigation for links on login page

- components/suggestion/suggestion_box.jsx
https://mattermost.atlassian.net/browse/PLT-8533
> PLT-8533 Fixed username autocomplete not working with mixed cases

- components/create_post/create_post.jsx
- components/create_post/index.js
- tests/components/create_post/create_post.test.jsx
Issue - Regression: Emoji posted in center channel doesn't appear in Recently Used in emoji picker.
Solved by calling PostActions.createPost wrapper function instead of createPost from mattermost-redux
- such function includes createPost from mattermost-redux
- adding emoji to recent emojis, if present
- immediate post creation on IOS classic 
Jira ticket: [PLT-8536](https://mattermost.atlassian.net/browse/PLT-8536)
> [PLT-8536] Call PostActions.createPost wrapper function instead of createPost from mattermost-redux

- store/index.js
- tests/components/about_build_modal.test.jsx
- tests/components/header_footer_template.test.jsx
Fix the race condition on persistStore initialization when localForage is not ready.
Backport of the PR #531 to 4.5.
Some snapshots are failing because the change of the year (I think is not a good place to fix it here).
Besides, the styles wasn't checked in the .js files for version 4.5 so I didn't change the code for style fixes.
I assign it to @jwilander and @enahum because they were who approved the #531 PR.
[PLT-8399](https://mattermost.atlassian.net/browse/PLT-8399)
> PLT-8399: Fix race condition on persistStore initialization

- components/svg/status_away_icon.jsx
- components/svg/status_dnd_icon.jsx
- components/svg/status_offline_icon.jsx
- components/svg/status_online_icon.jsx
I'm proposing this for 4.6 since it's a small fix and it looks kind of ugly right now. This is how it looks with this PR
https://mattermost.atlassian.net/browse/PLT-8553
> PLT-8553 Properly centred status icons

- actions/integration_actions.jsx
There was a fix recently to make the autocomplete results no longer clear repeatedly while typing a slash command, but that meant the autocomplete results stayed visible if you keep typing when they should disappear. This fixes that without re-introducing the original issue
https://mattermost.atlassian.net/browse/PLT-8562
> PLT-8562 Close autocomplete after typing command without autocompleting

- components/team_general_tab.jsx
A regression was introduced that does not allow users to expand Team Setting's sections. This fixes that by adding the section prop.
> Ea78c752 regression fix

- tests/utils/post_utils.test.jsx
- utils/post_utils.jsx
Update regex so that to mute at-mention when the message is a command. A command can be any string that starts with `/` character. 
https://github.com/mattermost/mattermost-server/issues/7975
> PLT-8365 mute at-mention when the message is a command

- components/emoji_picker/emoji_picker.jsx
Emoji picker search should not be case-sensitive
https://mattermost.atlassian.net/browse/ICU-620
> ICU-620 Ensure comparisons are always lowercase

- components/view_image_popover_bar.jsx
Quick fix: JS error on showPublicLink of ViewImagePopoverBar
none
> Quick fix: JS error on showPublicLink of ViewImagePopoverBar

- components/create_comment/create_comment.jsx
- tests/components/create_comment/create_comment.test.jsx
Fix CTRL/CMD+UP on RHS by updating state.draft when new prop is received
Jira ticket: [PLT-8535](https://mattermost.atlassian.net/browse/PLT-8535)
> [PLT-8535] Fix CTRL/CMD+UP on RHS by updating state.draft when new prop is received

- components/sidebar/sidebar_channel/index.js
During the sidebar migration I migrate the code to calculate the unreads and
mentions in the sidebar part to redux, but that have some other implications in
the rest of the application, so the pos ChannelStore must be migrated entirely.
[XYZ-49](https://mattermost.atlassian.net/browse/XYZ-49)
> [XYZ-49] Using again the webapp ChanelStore to manage unreads

- components/logged_in.jsx
Don't load all custom emojis a second time on page load.
They were already being fetched by [mattermost-redux's loadMe action](https://github.com/mattermost/mattermost-redux/blob/master/src/actions/users.js#L220) which gets called by the [webapp on first load](https://github.com/mattermost/mattermost-webapp/blob/master/root.jsx#L66)
Start of https://mattermost.atlassian.net/browse/ABC-95
> ABC-95 Don't load all custom emojis a second time on page load

- components/sidebar/sidebar_channel/index.js
- components/sidebar/sidebar_channel/sidebar_channel.jsx
Add some checks for render the sidebar channels only if it is possible to render it (not loaded channels do not fail).
> More robust sidebar rendering

- components/channel_header/channel_header.jsx
Click on channel description` opens Edit Header instead of edit purpose
[PLT-8599](https://mattermost.atlassian.net/browse/PLT-8599)
> Fix for edit Header modal

- components/sidebar_header_dropdown.jsx
- components/sidebar_right_menu/sidebar_right_menu.jsx
- components/team_general_tab.jsx
- components/team_import_tab.jsx
- components/team_settings.jsx
- components/team_settings_modal.jsx
Refactored the `TeamSettingsModal` to be a `React-Bootstrap` modal like all other ones rather than a plain Bootstrap modal. `jQuery` usage has also been removed except for the `PerfectScrollbar`. For triggering the modal, I followed the logic used for other modals such as `AboutBuildModal` and `AddUsersToTeamModal`.
https://github.com/mattermost/mattermost-server/issues/7985
https://mattermost.atlassian.net/browse/PLT-1260
> [PLT-1260] Refactor TeamSettingsModal to use React-Bootstrap

- components/sidebar/sidebar_channel/sidebar_channel.jsx
When the channel is not loaded and appears as unread may use a reference to a
"null" element, which doesn't work. The fix always return an element on
SidebarChannel (when the data is not yet available too).
> Fix first/last unread link on channel not loaded yet

- components/searchable_user_list/searchable_user_list.jsx
PLT-8369 members list pagination fix.
The described problem occurs when the actual displayed user length equals to the maximum expected display length.
The fix is to compare `pageEnd` index with total number of users so that to know whether it has reached to the last user.
https://github.com/mattermost/mattermost-server/issues/7974
> PLT-8369 members list pagination fix

- components/admin_console/saml_settings.jsx
consumerServiceUrl was showing two / when the Site Url is written with trailing slash]
https://mattermost.atlassian.net/browse/PLT-8486
> PTL-8486 only add slash when required

- components/profile_popover.jsx
Fixes dispatch prop warning on popover of profile_popover component
> Fix dispatch prop warning on popover of profile_popover component

- sass/base/_structure.scss
Rebased version of #482
When scrolling channel history `Load more messages` button appears, but inertial scroll activates pull-to-refresh feature and page is fully reloaded. This PR disables pull-to-refresh feature to prevent unwanted page refresh
N/A
> Disable pull-to-refresh on Android(Chrome)

- components/needs_team/needs_team.jsx
Lands on last viewed channel on team switch
> Use last channel name for routing on team switch

- components/suggestion/channel_mention_provider.jsx
This populates channel autocomplete results with local data immediately. When more channels are returned from the server, they will be added to the results. In addition to improving usability on large servers, this ensures that joined channels are always shown in the autocomplete results.
Discussion: https://pre-release.mattermost.com/core/pl/3nzompitxpfi8do54r1xtb7ooa
https://mattermost.atlassian.net/browse/ABC-79
> ABC-79: populate channel autocomplete results with local data immediately

- actions/post_actions.jsx
- components/admin_console/user_autocomplete_setting.jsx
- components/autosize_textarea.jsx
- components/edit_post_modal/edit_post_modal.jsx
- components/edit_post_modal/index.js
- components/quick_input.jsx
- components/quick_switch_modal/quick_switch_modal.jsx
- components/searchable_channel_list.jsx
- components/searchable_user_list/searchable_user_list.jsx
- components/suggestion/suggestion_box.jsx
- components/textbox.jsx
- reducers/views/posts.js
- tests/components/__snapshots__/edit_post_modal.test.jsx.snap
- tests/components/edit_post_modal.test.jsx
- tests/redux/actions/posts.test.js
- utils/constants.jsx
This is an improvement to typing in languages that allow character composition on IE since it would frequently miss letters before when typing quickly. As a particularly bad example, this is what it looks like using a keyboard macro to type "한글이 찰 입력되는지 테스트" ("test Hangul input") into the channel switcher on pre-release
And this is on my local instance with the fixes applied
The big change here is that the post textboxes, the edit post modal, the channel switcher, and the channel/user lists in the web app will now use a new QuickInput component that manually updates the value of the `<input/>` instead of passing in a `value` prop. I also had to make some changes to the AutosizeTextarea and EditPostModal to make this work.
https://mattermost.atlassian.net/browse/PLT-8478
- …
> PLT-8478 Added QuickInput component to better handle fast CJK typing on IE

- actions/views/rhs.js
- components/post_markdown/index.js
- components/post_view/post_message_view/index.js
- components/post_view/post_message_view/post_message_view.jsx
- plugins/docs.json
- stores/user_store.jsx
- tests/redux/actions/views/rhs.test.js
- utils/text_formatting.jsx
This, along with my other PR, changes it so that instead of mentionKeys being an array of strings like  `['@user', 'FirstName']`, it'll now be an object including a caseSensitive field like `[{key: '@user'}, {key: 'FirstName', caseSensitive: true}]`.
As discussed earlier, I've removed the mentionKeys prop from post type plugins since they can get it from the store if needed, and this frees us up from having to worry about breaking those plugins as easily in the future.
This PR relies on https://github.com/mattermost/mattermost-redux/pull/375
https://mattermost.atlassian.net/browse/ICU-631
- Has redux changes (please link)
> ICU-631 Fixed case sensitive mention highlighting

- components/autosize_textarea.jsx
- components/post_markdown/post_markdown.jsx
The warning was due to using incorrect PropTypes, and the error happened when clicking on an autocomplete suggestion
> Fixed JavaScript warning and error that I added

- components/mfa/components/confirm.jsx
- tests/components/mfa/components/__snapshots__/confirm_test.jsx.snap
- tests/components/mfa/components/confirm_test.jsx
This fixes a JavaScript exception after completing MFA setup and trying
to click the "Okay" button. The submit handler wasn't bound to `this`.
I scanned the change that introduced this regression, but found no other
instances where this would have been unbound in the function in
question.
https://mattermost.atlassian.net/browse/ABC-181
> ABC-181: bind onSubmit in MFA Confirm component

- package.json
- yarn.lock
In firefox, with the about:config setting `media.peerconnections.enabled` equal
to `false`, the application crashes because a webrtc-adapter bug in any version
previous to 6.0.3 and after 6.0.4. This change the version to 6.0.4.
GH ISSUE #7996
> [GH-7996] Fix problem with the last version of webrtc-adapter

- components/post_view/post/post.jsx
The [...] menu can sometimes appear as a thin white line but devoid of content. See the JIRA link for repro steps.
The underlying issue appears to boil down to a mismatch between the CSS `:hover` state
which assigns the background color to the [...] menu and the
`onMouseEnter` event for the containing post. The latter never fires in
the cases described above, even after the dialog is dismissed, whereas
the CSS state re-evaluates constantly.
Switching to `onMouseOver` keeps the state in sync, with the minor
change that the event now bubbles and could be cancelled (but doesn't
appear to be in this component hierarchy).
https://mattermost.atlassian.net/browse/ABC-187
> ABC-187: switch post header to onMouseOver

- actions/channel_actions.jsx
- package.json
See https://github.com/mattermost/mattermost-server/pull/8163 and https://github.com/mattermost/mattermost-redux/pull/384
Won't work until the other PRs are merged.
https://mattermost.atlassian.net/browse/ABC-79
> ABC-79: use autocomplete channels endpoint

- components/post_emoji/index.jsx
- components/post_emoji/post_emoji.jsx
- components/post_markdown/index.js
- components/post_markdown/post_markdown.jsx
- components/root.jsx
- package.json
- tests/plugins/__snapshots__/post_type.test.jsx.snap
- tests/utils/emoticons.test.jsx
- tests/utils/formatting_hashtags.test.jsx
- utils/emoticons.jsx
- utils/post_utils.jsx
- utils/text_formatting.jsx
- yarn.lock
Support for loading emojis asynchronously in posts.
https://mattermost.atlassian.net/browse/ABC-93
> ABC-93 Support for loading emojis asynchronously in posts

- components/loading_screen.jsx
- components/post_view/post_list.jsx
- tests/components/__snapshots__/access_history_modal.test.jsx.snap
- tests/components/__snapshots__/activity_log_modal.test.jsx.snap
- tests/components/__snapshots__/do_verify_email.test.jsx.snap
- tests/components/integrations/__snapshots__/edit_command.test.jsx.snap
- tests/components/integrations/__snapshots__/edit_incoming_webhook.test.jsx.snap
- tests/components/integrations/__snapshots__/edit_oauth_app.test.jsx.snap
- tests/components/integrations/__snapshots__/edit_outgoing_webhook.test.jsx.snap
This should hopefully fix the scrolling/flicker issues when switching to a channel. I'm going to have to ask for QA's and/or the PMs' help with testing this to check all the corner cases. These are the possibilities to consider, switching to a channel:
* You have zero posts for and has no unreads
* You have zero posts for and has unreads (two cases here, scrolled to bottom or scrolled off bottom to new message indicator)
* You have some posts for but you haven't loaded the channel before (same two cases as above)
* You have some posts for but missing some newer messages from a disconnected WS (same two cases as above)
* You have loaded before and has no unreads
* You have loaded before and has unreads that you have from the WS (same two cases as above)
* You have loaded before and has …
> ABC-168 Update initial scrolling on post list

- actions/websocket_actions.jsx
Before, it was sending you to town square when you were removed from any channel, even if you weren't currently viewing that channel
https://mattermost.atlassian.net/browse/ICU-628
> ICU-638 Only send user to town square when they're removed from current channel

- actions/emoji_actions.jsx
- components/emoji_picker/emoji_picker.jsx
- components/emoji_picker/emoji_picker_overlay.jsx
- components/emoji_picker/index.js
- components/root.jsx
- reducers/views/emoji.js
- reducers/views/index.js
- utils/constants.jsx
- yarn.lock
Add paging and server search for custom emojis to emoji picker.
@hmhealey @stephenkiers let me know if I should approach this differently. This is my first time in the emoji picker code and it's a bit complex, so if you guys have better ideas on how to do this let me know :)
https://mattermost.atlassian.net/browse/ABC-92
> ABC-92 Add paging and server search for custom emojis to emoji picker

- package.json
- webpack.config.js
- yarn.lock
IE11 and the current Edge don't support URLSearchParams, newly
introduced as part of the react-router upgrades. This completely
prevents Mattermost from working. The newest Edge in preview does
support URLSearchParams and renders without issue.
https://mattermost.atlassian.net/browse/ABC-178
> ABC-178: polyfill URLSearchParams

- components/channel_header/channel_header.jsx
- components/channel_header/index.js
- components/login/login_controller.jsx
- components/message_wrapper.jsx
- components/post_emoji/index.jsx
- components/post_markdown/post_markdown.jsx
- package.json
- utils/post_utils.jsx
Based on #673. 
https://mattermost.atlassian.net/browse/ABC-122
> ABC-122 Handle custom emojis in channel header and login page

- components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
- tests/components/sidebar/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
This is a new feature of React that I don't think we've used yet. It lets you render a bunch of components without wrapping it in an extra div or span tag
> Used a fragment to reduce code duplication in sidebar

- components/needs_team/needs_team.jsx
Added check that skips getting channelName if the current team is null.
Leaving a team crashes the app with errors `TypeError: Cannot read property 'id' of null` and `needs_team.jsx:214 Uncaught (in promise) TypeError: Cannot read property 'id' of null`.
https://mattermost.atlassian.net/browse/ICU-693
> [ICU-693] if team exists, then get channel

- components/new_channel_flow.jsx
- tests/components/new_channel_flow.test.jsx
Reset error for new channel creation when switching channel from private to public and vice versa
Jira ticket: [ICU-652](https://mattermost.atlassian.net/browse/ICU-652)
> [ICU-652] Reset error for new channel creation when switching channel from private to public and vice versa

- components/suggestion/emoticon_provider.jsx
Add server request to emoji autocomplete. The diff looks like I did a lot but really I just encapsulated some functionality into a function and added the server request.
@jasonblais this is going to suffer from the same "server results popping in" issue that the other autocomplete functions have
https://mattermost.atlassian.net/browse/ABC-91
> ABC-91 Add server request to emoji autocomplete

- components/create_comment/create_comment.jsx
- components/create_post/create_post.jsx
- tests/utils/formatting_imgs.test.jsx
- tests/utils/formatting_links.test.jsx
- tests/utils/post_utils.test.jsx
- utils/markdown/index.js
- utils/markdown/mentionable_renderer.jsx
- utils/markdown/renderer.jsx
- utils/post_utils.jsx
- utils/text_formatting.jsx
Like the server, we now use the markdown parser to strip out any text that can't trigger mentions before searching for at channel notifications. The regexes we used before had some degenerate cases that would cause the browser to lock up while they were processed, so they had to go.
https://mattermost.atlassian.net/browse/ICU-656
> ICU-656 Used markdown renderer when searching for at channel in large channels

- actions/views/channel.js
- components/sidebar/index.js
- components/sidebar/sidebar.jsx
- components/sidebar/sidebar_channel/index.js
- components/sidebar/sidebar_channel/sidebar_channel.jsx
- reducers/views/channel.js
- tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
- tests/components/sidebar/__snapshots__/sidebar_channel.test.jsx.snap
- utils/constants.jsx
The reason it wasn't working before was because the channel member's notify_props were being ignored. I also cleaned up a bit of duplication where we were passing in the channel member object, but also the number of unread mentions and messages from that object.
https://mattermost.atlassian.net/browse/ICU-686
> ICU-686 Fixed channels ignoring mark unread setting

- components/single_image_view.jsx
- sass/components/_files.scss
Fix scroll pop issue when viewing single images except of SVG file type
- computes dimension of images depending on viewing window
- remove progress % loading indicator and just inject the image source on image `onload`. It improves image loading.
Note: Currently, SVG don't have height & width file info. Need to address separately (ticket: [ICU-698](https://mattermost.atlassian.net/browse/ICU-698)). 
Jira ticket: [ICU-648](https://mattermost.atlassian.net/browse/ICU-648)
> [ICU-648-2] Fix scroll pop issue when viewing single images except of svg file type

- components/file_upload/file_upload.jsx
Fix paste upload issue
When image from clipboard is pasted into the post textbox, the filename of the image gets posted to the textbox as well. Not sure if that's expected but maybe worth checking from the PM.
@esethna Could you please help validate? Thanks!
Jira ticket: [PLT-8662](https://mattermost.atlassian.net/browse/PLT-8662)
> [PLT-8662] Fix paste upload issue

- stores/redux_store.jsx
Only expose redux store globally in dev builds.
https://mattermost.atlassian.net/browse/ABC-105
> ABC-105 Only expose redux store globally in dev builds

- actions/global_actions.jsx
- actions/views/channel.js
- components/sidebar/sidebar_channel/index.js
- components/sidebar/sidebar_channel/sidebar_channel.jsx
- components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
- reducers/views/channel.js
- stores/channel_store.jsx
- tests/components/sidebar/__snapshots__/sidebar_channel.test.jsx.snap
- utils/constants.jsx
It feels really good to fix 4 bugs with one fix. We were only updating the state that kept track of whether or not the current channel was in the unread section when you actually clicked on the items in the sidebar, so I changed it to trigger whenever you change channels.
As I discussed with Joram, I also changed one of the other reducers to use a new action instead of SELECT_CHANNEL to make it more clear that it needs additional information. At some point, we'll need to think about how this'll work when we start using more of the redux library's actions to switch channels.
This PR is on top of one of my other ones since they touch the same code, so the changes specific to this PR are here: https://github.com/mattermost/mattermost-webapp/compare/icu686...icu687 …
> ICU-687/ICU-688/ICU-689/ICU-690 Fixed channels staying in the UNREADS section after viewing

- components/add_users_to_team/add_users_to_team.jsx
- components/channel_invite_modal/channel_invite_modal.jsx
- components/more_direct_channels/more_direct_channels.jsx
- components/multiselect/multiselect.jsx
- components/multiselect/multiselect_list.jsx
- tests/components/__snapshots__/add_users_to_team.test.jsx.snap
- tests/components/add_users_to_team.test.jsx
> loader for user modals

- components/autosize_textarea.jsx
- tests/components/__snapshots__/autosize_textarea.test.jsx.snap
- tests/components/autosize_textarea.test.jsx
The changes in PLT-8478 subtly changed the `id` of the AutosizeTextarea
from `post_textbox` to `post_textbox-textarea`. Unfortunately, the
former is hard-coded in a variety of places that trigger the desired
focus behaviour.
Ideally, this would be abstracted (as commented in the code), but for
now the minor portion of this change is reverted with no observable side
effects.
https://mattermost.atlassian.net/browse/ABC-213
> ABC-213: focus message box after switching channel

- utils/utils.jsx
The `!important` was preventing theme changes from taking effect until a refresh
https://mattermost.atlassian.net/browse/ICU-702
> ICU-702 Fixed unread sidebar colour not updating until refresh

- actions/global_actions.jsx
This simplifies the changes introduced in ABC-160 to simply check that
the channel exists instead of also checking that the channel team id
matches the current team. The additional check was redundant, since the
set of channels available are already constrained to the current team;
it was also wrong, since direct messages and group messages aren't
actually assigned team ids, leading to the regression in question.
Note that this check (before and even now) only works if you have access
to the two teams in question. If you try to open a malformed permalink
referencing a team for which you don't have access or that doesn't
exist, none of the router code in `<NeedsTeam>` executes (team is null),
and a different path is executed that doesn't try to evaluate the
permalink. Fixing that appears …
> ABC-214: fix permalinks to direct messages

- components/single_image_view.jsx
- sass/components/_files.scss
Fix the following for single view image:
1. Remove size and image type from title
2. Title should not upper case (keep case of uploaded file)
3. Title should be same font size as normal text but bolded
4. Reduce minimum height and width to 50 pixels
5. Remove download button on single
[UPDATE - end result]
After clicking the single image or its filename, image download is available at image modal, like:
Jira ticket: [ICU-699](https://mattermost.atlassian.net/browse/ICU-699)
> [ICU-699] Single view image improvement

- components/textbox.jsx
- tests/components/__snapshots__/textbox.test.jsx.snap
- tests/components/textbox.test.jsx
- tests/helpers/client-test-helper.jsx
- utils/utils.jsx
Forced a re-check of the character count whenever the text box receives focus. This event fires when the user clicks the mouse to focus the textbox, but also when the user switches channels (in the centre column), and when the user clicks the reply arrow to enter a new thread in the RHS. 
https://mattermost.atlassian.net/browse/XYZ-62
> XYZ-62: Character count enforced for previous message when moving to a new channel

- components/create_post/create_post.jsx
- components/create_post/index.js
- components/sidebar/sidebar_channel/index.js
- components/sidebar_header.jsx
- components/sidebar_right_menu/index.js
- components/sidebar_right_menu/sidebar_right_menu.jsx
- components/tutorial/tutorial_intro_screens.jsx
- components/tutorial/tutorial_tip.jsx
- tests/components/create_post/create_post.test.jsx
- utils/constants.jsx
This change fixes a `===` comparison between a string an integer to
allow the second tutorial step to display. It also fixes the trigger
that increments the tutorial step to only fire on an explicit "next"
instead of twice on a click because of multiple registered event
handlers. This also means that the tutorial no longer advances on an
"escape", but requires being explicitly skipped or completed.
As part of the clean up, unify most handling of the tutorial step
preference constants.
https://mattermost.atlassian.net/browse/ABC-216
> ABC-216: fix tutorial progression

- components/channel_notifications_modal/components/extra_info.jsx
- tests/components/channel_notifications_modal/__snapshots__/extra_info.test.jsx.snap
Help text missing from Channel Notifications > Mark Channel Unread section
https://mattermost.atlassian.net/browse/ICU-711
> ICU-711 Fix help text missing for Channel Notification preferences

- components/autosize_textarea.jsx
- components/create_comment/create_comment.jsx
- components/create_comment/index.js
- components/create_post/create_post.jsx
- components/create_post/index.js
- components/suggestion/suggestion_box.jsx
- components/textbox.jsx
- i18n/en.json
- sass/layout/_post.scss
- tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
- tests/components/create_comment/create_comment.test.jsx
- tests/components/create_post/__snapshots__/create_post.test.jsx.snap
- tests/components/create_post/create_post.test.jsx
Instead of just fixing the bug (which would have been very hacky), I instead prevented users from posting in town square when it was marked as read only.
The user is prevented from writing in the textbox, any previous drafts will not show up (but are still saved for if town square is not read only in the future), and the file upload and emoji picker buttons are disabled.
https://mattermost.atlassian.net/browse/ABC-215
> ABC-215 Prevent posting in town-square when set to read only

- components/sidebar/sidebar_channel/sidebar_channel.jsx
- tests/components/sidebar/__snapshots__/sidebar_channel.test.jsx.snap
@esethna As I mentioned in the ICU channel, I've removed the X button from unread channels since we don't let you leave a channel that has been marked unread (or if we do, the channel reappears when you refresh the page).
It does look a bit weird when you have the Unread Channels section disabled since you can now have G channels without an X button, but I think that's fine because clicking the X button before just meant the channel reappeared on next refresh. Here's an example with the X button shown for all channels for demonstration purposes
https://mattermost.atlassian.net/browse/ICU-703
> ICU-703 Don't show close button for unread channels

- components/file_attachment.jsx
- components/file_attachment/file_thumbnail.jsx
- components/file_attachment/filename_overlay.jsx
- sass/components/_files.scss
- tests/components/__snapshots__/file_attachment.test.jsx.snap
- tests/components/file_attachment/__snapshots__/file_thumbnail.test.jsx.snap
- tests/components/file_attachment/file_thumbnail.test.jsx
- tests/utils/file_utils.test.jsx
- utils/constants.jsx
- utils/file_utils.jsx
Move tooltip from filename to download icon
Others: 
- Refactor `FileAttachment` component
- Add `FileThumbnail` component
@esethna Could you please check if the tooltip is positioned as you would expect? Thanks!
Update (Feb 2):
This PR addressed item 1 of:
- Jira ticket: [ICU-648](https://mattermost.atlassian.net/browse/ICU-648)
> [ICU-648] Fix download tooltip

- actions/channel_actions.jsx
XYZ-86: On commands goto_location, when the returned location is an absolute url this is not working with the browserHistory.push command. I'm not sure if there is where the fix must be, or somewhere in the router.
[XYZ-86](https://mattermost.atlassian.net/browse/XYZ-86)
> XYZ-86: Use always relative path on browser history on goto_location command response

- components/create_comment/create_comment.jsx
- components/create_comment/index.js
- tests/components/create_comment/create_comment.test.jsx
Sometimes in the RHS a random character is removed while typing. I hope this solve the problem.
Directly related with this PR #624
The problem is that while you are writting the draft is saving and reloading all the time. This way, it only reload the draft data after an history change, which is the expecte behavior.
[XYZ-60](https://mattermost.atlassian.net/browse/XYZ-60)
> XYZ-60: Random characters disappear from RHS randomly

- utils/channel_utils.jsx
Most of this logic is handled by mattermost-redux now
> Removed unused code from ChannelUtils

- components/post_markdown/post_markdown.jsx
- sass/layout/_post.scss
- tests/plugins/__snapshots__/post_type.test.jsx.snap
This is a response to PR- https://github.com/mattermost/mattermost-webapp/pull/731
I removed the span as I didn't see the need for it, and therefore the `display: inline-block` works again.
> ICU-695 - Fixing paragraph spacing for last child

- reducers/views/channel.js
`mentionCount` is not the same thing as `mention_count`
https://mattermost.atlassian.net/browse/ICU-716
> ICU-716 Fixed position of channels with mentions in unreads section after reading

- components/admin_console/message_export_settings.jsx
- i18n/en.json
- tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
- Adds missing period
- Changes `instance` to `server` for consistency with other settings text, e.g. Elasticsearch
> Minor update to GlobalRelay email setting help text

- components/channel_view/channel_view.jsx
This fixes a `cannot read 'id' of undefined` error in webapp. It seems like the issue was old code was refactored, but old code was left in. So I cleaned out the code rot and everything still seems to work.
https://mattermost.atlassian.net/browse/ICU-672
https://www.youtube.com/watch?v=oVPdOhNjP3E
> ICU-672 Fix undefined id error

- components/admin_console/admin_console.jsx
- components/admin_console/policy_settings/index.jsx
- components/admin_console/policy_settings/policy_settings.jsx
- components/admin_console/post_edit_setting.jsx
- components/admin_console/radio_setting.jsx
- routes/route_admin_console.jsx
- tests/utils/policy_roles_adapter.test.jsx
- utils/constants.jsx
- utils/policy_roles_adapter.js
- yarn.lock
Uses the policy setting to add/remove permissions from roles. On load it reads the roles and permissions assignments to infer the policy setting.
[XYZ-23](https://mattermost.atlassian.net/browse/XYZ-23)
> XYZ-23: Use advanced permissions behind policy page.

- components/claim/claim_controller.jsx
The react-router changes broke the binding between the `old_type` query
string parameter and the `currentType` prop type expected by the oauth
to email landing page. This fixes that mapping.
A better solution would be to pass this explicitly to the component. I'm
reworking these in `master` and will tackle that improvement there
instead.
https://mattermost.atlassian.net/browse/ABC-241
> ABC-241: fix oauth to email landing page

- components/signup/components/signup_ldap.jsx
Fix `redirect_to` on ldap account setup. I stumbled across this doing unrelated testing.
https://mattermost.atlassian.net/browse/ABC-240
> ABC-240: fix `redirect_to` on ldap account setup

- utils/post_utils.jsx
The `html-to-react` parser returns undefined for some reason if you give it an empty string. I'm also going to cherry-pick this into the release branch if https://github.com/mattermost/mattermost-webapp/pull/754 is accepted for 4.7
> Fixed messageHtmlToComponent returning undefined

- components/file_attachment.jsx
- components/file_attachment/filename_overlay.jsx
- tests/components/__snapshots__/file_attachment.test.jsx.snap
- tests/components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap
- tests/components/file_attachment/filename_overlay.test.jsx
Fix opening attachment preview on compact view
Also, removed unnecessary instance function and props in FilenameOverlay.
Jira ticket: [PLT-8712](https://mattermost.atlassian.net/browse/PLT-8712)
> [PLT-8712] Fix opening attachment preview on compact view

- components/file_attachment_list/file_attachment_list.jsx
- components/single_image_view.jsx
There were a few separate issues:
* Viewport width was starting at 0, so our initial height would be 0 even if we had the file height already (fixed by first commit)
* The loading indicator div was not the same height as the final image div, it was off by 10-15 pixels (fixed by first commit)
* In cases where the app was waiting on the file info to load, there was no scrolling of the post list to deal with the scroll pop from these mounting (fixed by second commit)
https://mattermost.atlassian.net/browse/ICU-724
> ICU-724 Deal with scroll pop from single image previews

- components/about_build_modal/about_build_modal.jsx
- i18n/en.json
- tests/components/__snapshots__/about_build_modal.test.jsx.snap
- tests/components/about_build_modal.test.jsx
- webpack.config.js
https://mattermost.atlassian.net/browse/ABC-193
> ABC-193: Add webapp commit hash to "about" modal

- components/new_channel_flow.jsx
- tests/components/__snapshots__/new_channel_flow.test.jsx.snap
In create channel modal, purpose field is cleared after editing channel URL
https://mattermost.atlassian.net/browse/ICU-737
> Icu 737- Properly populate header field when creating modal

- components/profile_picture.jsx
- tests/components/__snapshots__/profile_picture.test.jsx.snap
- tests/components/profile_picture.test.jsx
This addresses an attempt to dereference an undefined `this.props.user`, introduced by https://github.com/mattermost/mattermost-webapp/pull/742.
Original ticket was https://mattermost.atlassian.net/browse/PLT-7690. Not filing new ticket for this issue.
> PLT-7690: fix undefined user reference

- components/login/login_controller.jsx
- components/root.jsx
There is an issue were last channel is not being stored when you close the window. Every time you start it takes you to `Town Square`. This is caused by the logic added with config `ExperimentalPrimaryTeam`. This PR fixes the issue.
https://github.com/mattermost/mattermost-webapp/pull/334
via @dmeza
> Fix bug when ExperimentalPrimaryTeam is set lastUrl does not work

- components/admin_console/plugin_settings.jsx
- i18n/en.json
Remove UI setting for enabling plugin uploads.
https://mattermost.atlassian.net/browse/ABC-176
> ABC-176 Remove UI setting for enabling plugin uploads

- sass/responsive/_mobile.scss
- sass/responsive/_tablet.scss
ICU-748 - Link preview images exceeding border
ICU-754 - Centering x icon on mobile
https://mattermost.atlassian.net/browse/ICU-748
https://mattermost.atlassian.net/browse/ICU-754
> 4.7 UI fixes

- components/channel_header/channel_header.jsx
- components/more_direct_channels/index.js
- components/more_direct_channels/more_direct_channels.jsx
- components/navbar/navbar.jsx
- components/sidebar/sidebar.jsx
- stores/modal_store.jsx
- tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
- utils/constants.jsx
Fix opening of Add Members modal for GM channel
- add modal button wrapper for `MoreDirectChannels`
- switch from ModalStore to available redux-style for modals
Jira ticket: [ICU-746](https://mattermost.atlassian.net/browse/ICU-746)
> [ICU-746] Fix opening of Add Members modal for GM channel

- components/login/login_controller.jsx
- components/signup/signup_controller.jsx
The `hash` and `data` parameters, being `null`, were cast to strings
downstream in mattermost-redux as part of `buildQueryString`, resulting
in a value of `"null"` being passed up instead of the expected empty
string. The server correctly rejected the hash as invalid.
This change copies the more correct handling from the sign up controller.
Perhaps an even better solution would be to update `buildQueryString` in
mattermost-redux to check `null` parameters and send up empty strings
automatically, however that's probably not the change we want near the
end of a release. I'll propose the change in `master` separately
instead.
https://mattermost.atlassian.net/browse/ABC-244
> ABC-244: fix team invite link handling

- components/file_upload/file_upload.jsx
Repro steps:
1. Press CTRL+U (Windows) or CMD+U (Mac)
Observed:
Nothing happens
Expected:
File selector appears
https://mattermost.atlassian.net/browse/ICU-734
> Icu 734 - Ctrl-U triggers upload box

- components/admin_console/storage_settings.jsx
- i18n/en.json
- i18n/fr.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/ru.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Also changing the options description wording a bit since atmos/camo doesn't do resizing or other image transformations.
https://mattermost.atlassian.net/browse/ABC-258
See also https://github.com/willnorris/imageproxy/pull/141
> ABC-258: Remove willnorris/imageproxy from sysadmin console

- utils/post_utils.jsx
This is a fix for https://github.com/mattermost/mattermost-webapp/pull/754 that I'm submitting separately because it's going backwards (master into 4.7) and doing them together would likely cause merge conflicts
> Fixed messageHtmlToComponent returning undefined (#755)

- components/new_channel_modal/new_channel_modal.jsx
- tests/components/__snapshots__/new_channel_modal.test.jsx.snap
* Fix tabIndex going outside NewChannelModal.
Had to add custom close button (exactly identical to the one given by bootstrap) in order to be able to add `tabIndex` on that. Ordered all tabIndexes properly as per the issue description.
Jira: https://mattermost.atlassian.net/browse/XYZ-66
Github: https://github.com/mattermost/mattermost-server/issues/8157
> [XYZ-66] Fix tabIndex going outside modal in NewChannelModal

- components/single_image_view.jsx
- sass/components/_files.scss
Clear `imageContainerStyle` on image load
- This is to prevent fix height at center view whenever RHS is expanded.
Jira ticket: [ICU-720](https://mattermost.atlassian.net/browse/ICU-720)
> [ICU-720] Clear imageContainerStyle on image load

- components/create_post/create_post.jsx
- tests/components/create_post/create_post.test.jsx
Fix unexpected opening of keyboard on classic app
- `handleFileUploadChange` should not force focus to textbox
- mobile out of focus (or webapp focus) will be handled by `this.focusTextbox` function
Should be for the following Jira tickets:
- [ICU-747](https://mattermost.atlassian.net/browse/ICU-747)
- [ICU-749](https://mattermost.atlassian.net/browse/ICU-749)
- [ICU-752](https://mattermost.atlassian.net/browse/ICU-752)
> [ICU-747/749/752] Fix unexpected opening of keyboard on classic app

- components/admin_console/admin_console.jsx
- components/admin_console/custom_integrations_settings/custom_integrations_settings.jsx
- components/admin_console/custom_integrations_settings/index.jsx
- components/admin_console/policy_settings/policy_settings.jsx
- routes/route_admin_console.jsx
- tests/components/integrations/installed_oauth_apps.test.jsx
- utils/policy_roles_adapter.js
* Updates the "Restrict managing integrations to Admins" input on System Console -> Custom Integrations page to change permissions assignments behind the scenes.
* Removes a few unnecessary policy mappings that were the same value for each policy input.
* Adds a few tweaks to the policy react component to remove `bind` and add some missing props validations.
[XYZ-75](https://mattermost.atlassian.net/browse/XYZ-75)
> XYZ-75: Migrates EnableOnlyAdminIntegrations config in system console to set role permissions.

- components/sidebar_right/sidebar_right.jsx
I hate this jquery.
Anyway, this fix simply stops the RHS jquery from firing unless it is actually trying to show the RHS bar
https://mattermost.atlassian.net/browse/ICU-745
> Icu 745- fix lhs popping in an out during tutorial

- components/sidebar_right/sidebar_right.jsx
I betcha wouldn't believe that touching the jquery `doStrangeThings` section broke something.
It wouldn't close anymore. I updated the logic to fire when it opens and when it closes. But *only* then.
> fix rightsidebar not hiding properly

- components/select_team/components/select_team_item.jsx
Converting the `Link` tag into an `a` tag because the `to` attribute was bypassing the onClick behavior.
[XYZ-111](https://mattermost.atlassian.net/browse/XYZ-111)
> XYZ-111: Checking join rights before join to the team

- components/emoji_picker/emoji_picker.jsx
Sometimes requesting emojis and incrementing the page would get out of sync on slower connections. This makes sure we're waiting for both the request to finish and the page to increment before starting the next round of loading more emoji.
https://mattermost.atlassian.net/browse/MM-9604
> MM-9604 Prevent races between emoji picker page incrementing and requesting more emojis

- actions/global_actions.jsx
Removed the null check on channel. Unfortunately, this will cause [MM-8564](https://mattermost.atlassian.net/browse/MM-8564) to regress, but it seems like the less important bug, since it is only triggered by somebody using an invalid permalink url. There's a [big long discussion about this](https://pre-release.mattermost.com/core/pl/dj1en7cu5bbkjg5rmiqo9xdjpa) on pre-release.
https://mattermost.atlassian.net/browse/MM-9605
> MM-9605: Permalinks to public channels don't join the channels if not in them

- components/suggestion/emoticon_provider.jsx
When we added new system emojis a while back, it became possible to have a custom emoji with the same name as a system one. This causes some undefined behaviour when sorting the emoji autocomplete, so just don't even bother looking at custom emojis with the same name as a system one.
https://mattermost.atlassian.net/browse/ICU-732
> ICU-732 Made system emojis always take precedence over custom ones

- components/autosize_textarea.jsx
Prevents the placeholder on IE11 from posting the value of the hidden textarea.
https://mattermost.atlassian.net/browse/MM-9611
> MM-9611 Fix textbox placeholder on IE11

- actions/global_actions.jsx
- components/needs_team/needs_team.jsx
#689 introduced mattermost-redux actions (markChannelAsRead) that already contained view channel requests, so we started getting duplicates.
https://mattermost.atlassian.net/browse/MM-9601
> MM-9601 Remove duplicate view channel calls on app focus and channel switch

- .editorconfig
Tweak `.editorconfig` to enforce `trim_trailing_whitespace`.
> configure trim_trailing_whitespace in .editorconfig

- components/channel_view/channel_view.jsx
- components/channel_view/index.js
- components/create_post/create_post.jsx
- components/create_post/index.js
- components/do_verify_email/do_verify_email.jsx
- components/do_verify_email/index.js
- components/file_upload/file_upload.jsx
- components/file_upload/index.js
- components/navbar/index.js
- components/navbar/navbar.jsx
- components/tutorial/index.jsx
- components/tutorial/tutorial_intro_screens.jsx
- components/tutorial/tutorial_view.jsx
- tests/components/create_post/__snapshots__/create_post.test.jsx.snap
- tests/components/create_post/create_post.test.jsx
- tests/components/do_verify_email.test.jsx
- tests/components/file_upload/__snapshots__/file_upload.test.jsx.snap
- tests/components/file_upload/file_upload.test.jsx
- tests/utils/file_utils.test.jsx
- utils/file_utils.jsx
This is a subset of the changes in the `MM-8589-remove_mm_global_license` branch, broken up into multiple PRs to facilitate easier review. See any linked PRs for other changes if you're interested. 
These changes, as a whole, move towards removing our dependence on the global `mm_config` and `mm_license` objects. These changes will ultimately facilitate resolving https://mattermost.atlassian.net/browse/MM-8604, allowing us to stop hard refreshing the application whenever someone makes a configuration change.
https://mattermost.atlassian.net/browse/MM-8589
https://github.com/mattermost/mattermost-webapp/pull/816
https://github.com/mattermost/mattermost-webapp/pull/819
https://github.com/mattermost/mattermost-webapp/pull/821
https://github.com/mattermost/mattermost-webapp/pull/822 …
> Remove mm_config and mm_license global state from webapp (PR #3)

- components/channel_header/channel_header.jsx
- components/channel_layout/channel_controller.jsx
- components/channel_members_dropdown/channel_members_dropdown.jsx
- components/channel_members_dropdown/index.js
- components/channel_notifications_modal/channel_notifications_modal.jsx
- components/channel_notifications_modal/index.js
- components/invite_member_modal/index.js
- components/invite_member_modal/invite_member_modal.jsx
- components/more_direct_channels/index.js
- components/more_direct_channels/more_direct_channels.jsx
- components/navbar/navbar.jsx
- components/search_results_item/index.js
- components/search_results_item/search_results_item.jsx
- components/should_verify_email/index.js
- components/should_verify_email/should_verify_email.jsx
- components/team_sidebar/index.js
- components/team_sidebar/team_sidebar_controller.jsx
- tests/components/__snapshots__/search_results_item.test.jsx.snap
- tests/components/navbar/__snapshots__/navbar.test.jsx.snap
- tests/components/navbar/navbar.test.jsx
- tests/components/search_results_item.test.jsx
This is a subset of the changes in the `MM-8589-remove_mm_global_license` branch, broken up into multiple PRs to facilitate easier review. See any linked PRs for other changes if you're interested. 
These changes, as a whole, move towards removing our dependence on the global `mm_config` and `mm_license` objects. These changes will ultimately facilitate resolving https://mattermost.atlassian.net/browse/MM-8604, allowing us to stop hard refreshing the application whenever someone makes a configuration change.
https://mattermost.atlassian.net/browse/MM-8589
https://github.com/mattermost/mattermost-webapp/pull/816
https://github.com/mattermost/mattermost-webapp/pull/819
https://github.com/mattermost/mattermost-webapp/pull/820
https://github.com/mattermost/mattermost-webapp/pull/821 …
> Remove mm_config and mm_license global state from webapp (PR #6)

- components/claim/claim_controller.jsx
- components/claim/components/email_to_ldap.jsx
- components/claim/components/email_to_oauth.jsx
- components/claim/components/ldap_to_email.jsx
- components/claim/components/oauth_to_email.jsx
- components/claim/index.js
- components/root.jsx
- components/signup/signup_controller.jsx
- i18n/i18n.jsx
- stores/user_store.jsx
This is a subset of the changes in the `MM-8589-remove_mm_global_license` branch, broken up into multiple PRs to facilitate easier review. See any linked PRs for other changes if you're interested. 
These changes, as a whole, move towards removing our dependence on the global `mm_config` and `mm_license` objects. These changes will ultimately facilitate resolving https://mattermost.atlassian.net/browse/MM-8604, allowing us to stop hard refreshing the application whenever someone makes a configuration change.
https://mattermost.atlassian.net/browse/MM-8589
https://github.com/mattermost/mattermost-webapp/pull/819
https://github.com/mattermost/mattermost-webapp/pull/820
https://github.com/mattermost/mattermost-webapp/pull/821
https://github.com/mattermost/mattermost-webapp/pull/822 …
> Remove mm_config and mm_license global state from webapp (PR #1)

- components/channel_layout/center_channel/center_channel.jsx
- components/channel_layout/center_channel/index.js
- components/channel_layout/channel_controller.jsx
A recent refactor of the center channel component grouped the implicit
router parameters as a `params` prop, but then failed to utilize this
everywhere. For simplicity, I've eliminataed the `params` prop and just
declared the expected incoming parameters directly on `props`.
https://mattermost.atlassian.net/browse/MM-9628
> MM-9628: fix broken channel switching

- components/post_view/post_info/post_info.jsx
- components/post_view/reaction_list/reaction_list.jsx
This remove the isRequired because in some cases, in the reload, you can have
the posts information before the channel information, so it can generate an
error.
> Remove isRequired in teamId for post_info and reaction_list

- components/post_view/post_time.jsx
This patch optimizes heavy date.toLocaleString method inside post_time.jsx component and replaces it with a simple math.
It was created a few versions ago when each post_time.jsx instance had a 'resize' listener attached which did rerenders - at this time it **heavily** reduced lags when resizing window.
While the resize listener is gone now, this patch still improves rendering times when loading channels.
> Optimize post_time.jsx

- components/delete_post_modal.jsx
Return cursor to input box after deleting a message. Resolves [#4766](https://github.com/mattermost/mattermost-server/issues/4766)
[https://github.com/mattermost/mattermost-server/issues/4766](https://github.com/mattermost/mattermost-server/issues/4766)
> Return cursor to input box after deleting a message (#4766)

- components/channel_identifier_router.jsx
This fixes some conflicts that arose from https://github.com/mattermost/mattermost-webapp/pull/189.
1. When going to `/messages/<identifier>`, we now check for an @ sign for emails/username before checking length of the identifier like we used to
2. When going to `/channels/<identifier>` with an identifier that is 26 or 40 characters long, we check to see if we have a channel with that name before assuming that the identifier is a channel or group ID so that we can once again view channels with a 26 or 40 character long name. 
Note that this will however cause problems with ID-based routing if someone creates a channel with a name matching a channel ID, but it's impossible to completely prevent conflicts without completely changing the routing behaviour.
It also means that you will be …
> MM-9654 Updated channel routing to better handle 26 character long character names

- components/post_view/post_list.jsx
The event handler for resize was passing in the event and we were interpreting that as a force scroll. Just needed a wrapper.
https://mattermost.atlassian.net/browse/MM-8228
> MM-8228 Fix resizing window forcing scroll to bottom

- components/navbar/navbar.jsx
Don't show WebRTC icon in non-DM channels in mobile view.
https://mattermost.atlassian.net/browse/MM-8882
> MM-8882 Don't show WebRTC icon in non-DM channels in mobile view

- components/emoji_picker/emoji_picker.jsx
Set number of "system emojis count" to those emojis to show so that the initially constructed DOM tree for each emoji item will render with correct emoji class name instead of just the default placeholder of `emojisprite`.
- Currently, it's using the `EMOJI_TO_LOAD_PER_UPDATE=135`. However, there's no point to cap this on initial load since the system emoji maps & emoji sprite sheets are all loaded, and DOM trees for emoji picker are all constructed.
@jasonblais Could you please have a quick look if this solves the issue? Thanks!
Jira ticket: [MM-9571](https://mattermost.atlassian.net/browse/MM-9571)
> [MM-9571] Set number of system emojis count to show

- components/channel_identifier_router.jsx
For GM channels (`<mattermost>/<team>/channels/<GM channel name>`), my last PR broke the logic to switch to GM channels because it was calling `goToChannelByChannelName` for a GM channel which only rewrites the URL to the `/messages` version of the route without actually setting the selected channel ID.
For DM channels (`<mattermost>/<team>/messages/<user ID 1>__<user ID 2>`), it would attempt to get the username of the other user while rewriting the URL, but that would error out if it didn't already have the user in the store, so we needed to explicitly request it.
I think we should look at reorganizing this logic to
1. Separate the channel switching and URL rewriting behaviour since there's definitely code paths like the one we were going through with the GM channels where the URL is …
> MM-9677 Fixed being unable to go to DMs/GMs using old routes

- components/pdf_preview.jsx
When the file can't be loaded as a PDF, print a message to the console and fall back to the generic file "preview".
https://mattermost.atlassian.net/browse/MM-9583
> MM-9583: improve malformed pdf behavior

- components/create_comment/create_comment.jsx
- components/create_post/create_post.jsx
Force focus to textbox when the period since the last blur is greater than the `fasterThanHumanWillClick`.
Honestly, I don't understand why `less than` currently. In addition, maybe this is no longer applicable nowadays since we have `props.enableAddButton` that enables/disables submit button. 
Jira ticket: [MM-8007](https://mattermost.atlassian.net/browse/MM-8007)
> [MM-8007] Force focus to textbox when the period since the last blur is greater than the fasterThanHumanWillClick

- utils/text_formatting.jsx
When you have a username with ., - or _, wasn't well managed by the
highlighting library. I improved the regular expression on maching usernames
after the @ sign. And adding the highlight of the not @ signed version of the
username.
I'm not if here I'm breaking other expected behaviors.
[MM-8777](https://mattermost.atlassian.net/browse/MM-8777)
> MM-8777: Highlighting usernames on exact mention

- components/sidebar/sidebar.jsx
Fixes the "Unread Message above" indicator in the sidebar
https://mattermost.atlassian.net/browse/MM-9055
> [MM-9055] Fix sidebar unread above indicator

- components/autosize_textarea.jsx
This is a follow-up to the quick fix #806 that went in for 4.7.
The root issue seemed to be that disabling a textarea in IE11 would not disable input event handlers and `onInput` was getting passed to both the real and hidden textareas. Removing it from the hidden textarea fixes the issue.
I also noticed that we were passing `disabled` twice to the hidden textarea, once manually setting it to `true` and then also passing it in as part of `otherProps`. I updated it to only and always pass in `disabled` as true.
https://mattermost.atlassian.net/browse/MM-9619
> MM-9619 Proper fix to IE11 hidden textarea placeholder issue

- stores/channel_store.jsx
When you receive a notification post in your current channel, you must mark as
read in the client, but in the server too, because this notification must be
mark as unread in mobile devices.
I haven't tested it manually because I haven't a development environment with
push notifications.
[MM-7188](https://mattermost.atlassian.net/browse/MM-7188)
> MM-7188: Update unread on server when receive a notification on your channel

- components/create_comment/create_comment.jsx
- components/create_post/create_post.jsx
- components/edit_channel_header_modal/edit_channel_header_modal.jsx
- components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
- components/edit_post_modal/edit_post_modal.jsx
- components/new_channel_modal/new_channel_modal.jsx
- utils/utils.jsx
Adds ability to post comments with ⌘+enter (the original ticket). Also adds support for using ⌘ key in all places that control is supported in key combinations.
[MM-8042](https://mattermost.atlassian.net/browse/MM-8042)
> MM-8042: Accepts ⌘+enter to comment (et al)

- components/admin_console/message_export_settings.jsx
- i18n/en.json
- tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
The full implementation of the GlobalRelay compliance export is expected to be
in the 4.9 release, so, temporary we disable the configuration in the admin
console.
[MM-9675](https://mattermost.atlassian.net/browse/MM-9675)
> Disabling the GlobalRelay support in the interface for 4.8 release

- components/announcement_bar/announcement_bar.jsx
- components/announcement_bar/index.js
- i18n/en.json
- root.jsx
- tests/helpers/client-test-helper.jsx
- utils/constants.jsx
Add announcement bar for sysadmins when APIv3 is enabled. Removed any last references to v3 from the webapp.
https://mattermost.atlassian.net/browse/MM-8593
> MM-8593 Add announcement bar for sysadmins when APIv3 is enabled, other minor clean-up

- components/emoji_picker/components/emoji_picker_item.jsx
- sass/components/_emoticons.scss
The click in the emoji picker was failing due a problem with the css. This change solves the problem respecting the fix done by original commit.
It was introduced in the #799 PR.
I really :heart: `git bisect`.
[MM-9681](https://mattermost.atlassian.net/browse/MM-9681)
> MM-9681: Fix the click in the emoji picker

- components/quick_input.jsx
The fake connected textbox in QuickInput doesn't work in the desktop app if it tries to update the value immediately in `componentDidUpdate`
Tested with English, Japanese, and Korean using:
- Mattermost Desktop App/Windows 10
- Chrome/Windows 10
- IE11/Windows 10
- Edge/Windows 10
- Firefox/Windows 10
- Mattermost Desktop App/Mac
- Safari/Mac
https://mattermost.atlassian.net/browse/MM-9586
> MM-9586 Fixed CJK typing in the channel switcher/search box on desktop apps

- components/post_markdown/index.js
- components/post_markdown/post_markdown.jsx
- tests/plugins/__snapshots__/post_type.test.jsx.snap
- utils/markdown/renderer.jsx
- utils/text_formatting.jsx
This ensures that post previews and predictive posts proxy images.
https://mattermost.atlassian.net/browse/MM-8534
> MM-8534: Fix insecure image loading by post author

- components/quick_input.jsx
- components/quick_switch_modal/quick_switch_modal.jsx
- components/search_bar/search_bar.jsx
This is a followup for my last PR because the previous one made it so that typing in the post textbox and hitting enter repeatedly could cause the existing message to remaining in the textbox as you typed. This'll only use the new behaviour for textboxes that had the bug mentioned in the ticket
https://mattermost.atlassian.net/browse/MM-9586
> MM-9586 Only update value of certain textboxes after a delay

- Makefile
This will use whatever commits are in the yarn.lock file so it should fix the problem we are having with mattermost-redux
> User lock file to get yarn dependencies

- components/at_mention/at_mention.jsx
- components/error_page/error_page.jsx
- components/error_page/index.jsx
- components/profile_picture.jsx
- components/profile_popover/index.js
- components/profile_popover/profile_popover.jsx
- components/select_team/index.js
- components/select_team/select_team.jsx
- components/suggestion/switch_channel_provider.jsx
- components/user_profile.jsx
- tests/components/__snapshots__/profile_picture.test.jsx.snap
- tests/plugins/__snapshots__/pluggable.test.jsx.snap
- tests/plugins/pluggable.test.jsx
This is a subset of the changes in the `MM-9635-remove_mm_global_license_config` branch, broken up into multiple PRs to facilitate easier review. See any linked PRs for other changes if you're interested. 
This is phase two of the changes that remove our dependence on the global `mm_config` and `mm_license` objects. The last PR to follow this series will remove the exports altogether. These changes will ultimately facilitate resolving https://mattermost.atlassian.net/browse/MM-8604, allowing us to stop hard refreshing the application whenever someone makes a configuration change.
https://mattermost.atlassian.net/browse/MM-9635
https://github.com/mattermost/mattermost-webapp/pull/863
https://github.com/mattermost/mattermost-webapp/pull/865 …
> Remove mm_config and mm_license global state from webapp, phase 2 (PR #1)

- actions/diagnostics_actions.jsx
- actions/global_actions.jsx
- actions/notification_actions.jsx
- actions/user_actions.jsx
- actions/websocket_actions.jsx
- components/root/index.js
- components/root/root.jsx
- components/signup/signup_email/signup_email.jsx
- components/suggestion/switch_channel_provider.jsx
- i18n/i18n.jsx
- root.jsx
This is a subset of the changes in the `MM-9635-remove_mm_global_license_config` branch, broken up into multiple PRs to facilitate easier review. See any linked PRs for other changes if you're interested. 
This is phase two of the changes that remove our dependence on the global `mm_config` and `mm_license` objects. The last PR to follow this series will remove the exports altogether. These changes will ultimately facilitate resolving https://mattermost.atlassian.net/browse/MM-8604, allowing us to stop hard refreshing the application whenever someone makes a configuration change.
https://mattermost.atlassian.net/browse/MM-9635
https://github.com/mattermost/mattermost-webapp/pull/862
https://github.com/mattermost/mattermost-webapp/pull/865 …
> Remove mm_config and mm_license global state from webapp, phase 2 (PR #2)

- stores/user_typing_store.jsx
- tests/utils/channel_utils.test.jsx
- tests/utils/utils.test.jsx
- utils/channel_utils.jsx
- utils/license_utils.jsx
- utils/post_utils.jsx
- utils/utils.jsx
This is a subset of the changes in the `MM-9635-remove_mm_global_license_config` branch, broken up into multiple PRs to facilitate easier review. See any linked PRs for other changes if you're interested. 
This is phase two of the changes that remove our dependence on the global `mm_config` and `mm_license` objects. The last PR to follow this series will remove the exports altogether. These changes will ultimately facilitate resolving https://mattermost.atlassian.net/browse/MM-8604, allowing us to stop hard refreshing the application whenever someone makes a configuration change.
https://mattermost.atlassian.net/browse/MM-9635
https://github.com/mattermost/mattermost-webapp/pull/862
https://github.com/mattermost/mattermost-webapp/pull/863 …
> Remove mm_config and mm_license global state from webapp, phase 2 (PR #4)

- actions/user_actions.jsx
- components/admin_console/reset_password_modal/index.js
- components/admin_console/reset_password_modal/reset_password_modal.jsx
- components/admin_console/system_users/system_users_list.jsx
- components/claim/claim_controller.jsx
- components/claim/components/ldap_to_email.jsx
- components/claim/components/oauth_to_email.jsx
- components/signup/signup_email/index.js
- components/signup/signup_email/signup_email.jsx
- components/user_settings/security/index.js
- components/user_settings/security/user_settings_security.jsx
- tests/components/change_url_modal.test.jsx
- tests/components/dot_menu/dot_menu.test.jsx
- tests/components/dot_menu/dot_menu_empty.test.jsx
- tests/components/dot_menu/dot_menu_mobile.test.jsx
- tests/components/navbar/navbar.test.jsx
- tests/components/new_channel_flow.test.jsx
- tests/components/popover_list_members.test.jsx
- tests/components/post_view/reaction.test.jsx
- tests/components/rename_channel_modal.test.jsx
- utils/utils.jsx
This is the final PR in a series of changes from the `MM-9635-remove_mm_global_license_config` branch, broken up into multiple PRs to facilitate easier review. See any linked PRs for other changes if you're interested. 
This is phase two of the changes that remove our dependence on the global `mm_config` and `mm_license` objects. This PR removes the exports altogether. These changes will ultimately facilitate resolving https://mattermost.atlassian.net/browse/MM-8604, allowing us to stop hard refreshing the application whenever someone makes a configuration change.
https://mattermost.atlassian.net/browse/MM-9635
https://github.com/mattermost/mattermost-webapp/pull/862
https://github.com/mattermost/mattermost-webapp/pull/863
https://github.com/mattermost/mattermost-webapp/pull/865 …
> Remove mm_config and mm_license global state from webapp, phase 2 (PR #5)

- utils/utils.jsx
Supports ctrl working in all cases where cmd works.
n/a
> Make ctrl work wherever cmd works on macOS.

- actions/storage.js
- reducers/storage.js
- selectors/storage.js
- store/index.js
- tests/redux/actions/storage.test.js
- tests/redux/actions/views/create_comment.test.jsx
- tests/redux/reducers/storage.test.js
- tests/redux/selectors/rhs.test.js
- tests/redux/selectors/storage.test.js
Added control over overwrites in the localForage. Now all the overwrites of the storage data is checked before overwrite to not be older than the current change.
This change have some degree of backward compatibility because we understand that there is currently some data in the localForage of the user.
[MM-8851](https://mattermost.atlassian.net/browse/MM-8851)
> Discard any change to the storage if is older than the current one.

- components/post_view/post_attachment.jsx
Broken by https://github.com/mattermost/mattermost-webapp/pull/842. Fixed that, renamed the state variables to make it more apparent that their value is HTML, and verified that emojis still work as expected in attachments.
https://mattermost.atlassian.net/browse/MM-9711
> MM-9711: Fix post attachment collapsing

- components/latex_block.jsx
- i18n/en.json
**This is a backport of #894 PR to release-4.8 branch.**
When you introduce invalid latex code in mattermost, the Katex library throws
an exception, so the entire webapp is broken. This PR manage that. The expected
behavior is that `throwOnError = false` prevent the exceptions, but it only
works for certain type of error managed by Katex, other parse errors are thrown
anyway.
GH ticket mattermost/mattermost-server#8402
[MM-9718](https://mattermost.atlassian.net/browse/MM-9718)
> GH-8402: Invalid latex code, break the entire app (Fixed)

- components/textbox.jsx
- sass/components/_modal.scss
- sass/responsive/_mobile.scss
MM-9733 - Fixing edit box preview textarea
MM-9750 - Post controls overlay on mobile
https://mattermost.atlassian.net/browse/MM-9733
https://mattermost.atlassian.net/browse/MM-9750
> Release 4.8 fixes

- components/permalink_view.jsx
Fixes posts not loading around selected posts due to wrong assumption that ChannelStore.getCurrent() can be used to get channel id for post, before emitPostFocusEvent has finished loading.
It works fine when you boot to a permalink, but doesn't work correctly if you switch channel view to permalink view.
This caused surrounding posts to be requested but with wrong channel id, and empty results were returned.
https://mattermost.atlassian.net/browse/MM-9734
> MM-9734 Fix permalink view loading from search results

- components/user_settings/notifications/user_settings_notifications.jsx
- i18n/en.json
MM-9721 Update settings text when push notifications are disabled on the server
https://mattermost.atlassian.net/browse/MM-9721
> MM-9721 Update settings text when push notifications are disabled on the server

- Makefile
@jwilander can you have a look at this change? this clears the cache for the redux package before the yarn install command.
> Clear redux cache before yarn install

- components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
- components/sidebar/header/sidebar_header.jsx
This was a minor regression after connecting the sidebar header dropdown
to Redux: the ref no longer pointed directly at the
`SidebarHeaderDropdown` component, and the `toggleDropdown` function could
no longer be invoked.
Mutating the child state this way was prone to errors in the first
place, so now the `showDropdown` state is hoisted into the `SidebarHeader`
instead for direct manipulation, and then passed back down as props.
https://mattermost.atlassian.net/browse/MM-9762
> open the main menu during tutorial; fix JS error

- sass/components/_files.scss
Add flex styles to file-preview (loading) so it will not collapse when container is combined with loaded and loading files
Jira ticket: [MM-9710](https://mattermost.atlassian.net/browse/MM-9710)
> [MM-9710] Add flex to file-preview (loading) so it will not collapse when container is combined with loaded and loading files

- actions/websocket_actions.jsx
Mark current channel as read from viewed_channel events if window not active. Another part of this ticket is fixed by https://github.com/mattermost/mattermost-redux/pull/422
https://mattermost.atlassian.net/browse/MM-9754
> MM-9754 Mark current channel as read from viewed_channel events if window not active

- actions/post_actions.jsx
- components/dot_menu/dot_menu.jsx
- components/dot_menu/dot_menu_edit.jsx
- components/edit_post_modal/edit_post_modal.jsx
- tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
- tests/components/dot_menu/dot_menu.test.jsx
- tests/components/dot_menu/dot_menu_edit.test.jsx
- tests/redux/actions/posts.test.js
Fixes [#8429](https://github.com/mattermost/mattermost-server/issues/8429)
[Jira ticket](https://mattermost.atlassian.net/browse/MM-9771)
> [MM-9771] Cursor focus doesn't return to comment box on the RHS after editing a message on the RHS by removing all of the text in the comment

- utils/markdown/renderer.jsx
- utils/utils.jsx
It turns out that calling substring and passing a string as the argument does nothing so we were passing the whole link URL through to the click handler where we would remove the domain name. Unfortunately, the way that we were doing that works slightly differently on IE11 because it removes the preceding slash from the URL path (eg IE11 would produce `<team_name>/pl/<post_id>` instead of `/<team_name/pl/<post_id>` like other browsers)
https://mattermost.atlassian.net/browse/MM-9773
> MM-9773 Fixed permalinks on IE11

- actions/views/create_comment.jsx
- components/create_comment/index.js
- components/create_post/index.js
- selectors/rhs.jsx
(Note: This is not included on approved fixes for v4.8 but would recommend to get in. ~~This might be related to https://mattermost.atlassian.net/browse/MM-9710 which unfortunately I couldn't repro on my local dev machine.~~)
Quick fix for JS errors:
- The prop draft.message is marked as required in CreatePost, but its value is undefined
- Uncaught TypeError: Cannot read property 'trim' of undefined at CreatePost.handleEnableSendButton
Post on prerelease: https://pre-release.mattermost.com/core/pl/6atd8qhthbdh7fir1ocqrz9ffa
none
> Fix JS errors on draft - post or comment

- components/more_direct_channels/more_direct_channels.jsx
Filter out current user when adding a member to GMs to prevent the -1 count and to be consistent with the regular GM channel modal where you can't add yourself to the list.
https://mattermost.atlassian.net/browse/MM-9784
> MM-9784 Filter out current user when adding member to GM

- components/pdf_preview.jsx
- root.jsx
I don't know the exact reason this works, but my guess is that it needs to run on start and the PDFPreview component was being lazy loaded in by react router so that code wouldn't run until someone opened a PDF.
This is also how it was being done before the react router upgrade.
https://mattermost.atlassian.net/browse/MM-9816
> MM-9816 Fix PDF previews on Firefox

- components/user_settings/security/index.js
Proposing for 4.8
This would prevent a user from changing sign-in method if this setting wasn't set (when there is no license for example).
~~A casualty of the config changes and not having defaults set for some settings in non-licensed servers.~~
> If experimental auth change setting isn't set, default to on

- components/emoji_picker/components/emoji_picker_item.jsx
Some event handlers in https://github.com/mattermost/mattermost-webapp/commit/e3ecc5625753653b7696165d58bea7b50938c705 were moved form the `img` to the `div` tag and that caused the scroll to trigger on hover when the image wasn't in view, and also cause a JS error on click.
[MM-9845](https://mattermost.atlassian.net/browse/MM-9845)
> MM-9845: Moves event handlers back to img tag.

- yarn.lock
Simply update the last version of mattermost-redux to use in the webapp (fixes a problem with IOS classic app).
> Update mattermost-redux to latest webapp-4.8

- components/create_comment/create_comment.jsx
- components/create_post/create_post.jsx
- components/file_upload/file_upload.jsx
- tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
- tests/components/create_post/__snapshots__/create_post.test.jsx.snap
- tests/components/file_upload/__snapshots__/file_upload.test.jsx.snap
- tests/components/file_upload/file_upload.test.jsx
Fix file upload removal by setting `intl` as context types instead of props to easily access component via ref
Jira ticket: [MM-9783](https://mattermost.atlassian.net/browse/MM-9783)
Looks like my initial attempt to solve the issue only fixed the JS error but not actually able to cancel on going file upload. It turned out that to access the `cancelUpload` function, I need to do it like so:
```
this.refs.fileUpload.wrappedInstance.refs.FileUpload.wrappedInstance.cancelUpload(id)
```
However, it's already too deep to access and will require validation to every object's member. To solve it, I set `intl` as context type instead of wrapping the component with `injectIntl` which eventually receive `intl` via props.
> [MM-9783] Fix file upload removal by setting intl as context types instead of props to easily access component via ref

- components/search_bar/search_bar.jsx
This PR breaks the live-sync between the search terms in the store and the search box, instead storing them in the component state until you actually do a search. This stops the highlighting on existing search results changing when entering new search terms.
https://mattermost.atlassian.net/browse/MM-9776
> MM-9776: Don't sync search highlighting with search terms.

- components/admin_console/external_service_settings.jsx
- i18n/en.json
A Mattermost server had broken YouTube videos for months because it wasn't clear YouTube Data API v3 needs to be added as a service to the Google API Key
Doc update: https://github.com/mattermost/docs/commit/c72755cb60ff67740c1a49c5d0b6df216ebeb03f
> Update help text for Google API Key

- plugins/index.js
I'm selectively exporting these two functions as they'll allow plugins to format text, emojis, markdown, etc. just like we do in the web app.
To use these in a plugin:
```javascript
const React = window.react;
const PostUtils = window['post-utils']; // import the post utilities
import PropTypes from 'prop-types';
import {makeStyleFromTheme} from 'mattermost-redux/utils/theme_utils';
export default class PostTypeFormatted extends React.PureComponent {
// ...
render() {
const style = getStyle(this.props.theme);
const post = this.props.post;
const formattedText = PostUtils.formatText(post.message); // format the text
return (
<div
style={{...style.container}}
>
{'Formatted text: '}
{PostUtils.messageHtmlToComponent(formattedText)} // convert the html to components
</div>
);
}
}
``` …
> MM-9766 Export text formatting as 'post-utils' for use in plugins

- yarn.lock
Using the last commit of mattermost-redux as commit to get mattermost-redux in yarn.lock
> Updating mattermost-redux in yarn.lock

- components/channel_notifications_modal/components/collapse_view.jsx
- components/setting_item_max.jsx
- components/setting_item_min.jsx
- tests/components/__snapshots__/setting_item_max.test.jsx.snap
- tests/components/__snapshots__/setting_item_min.test.jsx.snap
- tests/components/channel_notifications_modal/__snapshots__/collapse_view.test.jsx.snap
- tests/components/channel_notifications_modal/__snapshots__/expand_view.test.jsx.snap
- tests/components/user_settings/__snapshots__/email_notification_setting.test.jsx.snap
Fix/change element IDs of SettingItemMin and SettingItemMax for end-to-end testing
@lindalumitchell This will definitely break current selenium tests due to changes on IDs but I think we'll have this permanently moving forward. 
Please note of the changes on IDs:
1. (SettingItemMax) Expanded settings’ view, selector IDs are:
- `saveSetting` button 
- `cancelSetting` button
2. (SettingItemMin) Collapsed settings’ view, selector IDs are:
- {section name} + `Edit` 
- {section name} + `Title` 
- {section name} + `Desc` 
(Note: I'll send separate PR to fix test on yarn test:e2e)
Jira ticket: [MM-9814](https://mattermost.atlassian.net/browse/MM-9814)
> MM-9814 Fix/change element IDs of SettingItemMin and SettingItemMax for end-to-end testing

- components/quick_input.jsx
The quick input `componentDidUpdate` uses `requestAnimationFrame` when `this.props.delayInputUpdate`, but this opens up the possibility that the component has unmounted by the time we `updateInputFromProps`. Check for same.
This PR also switches to the callback form to assign the ref.
https://mattermost.atlassian.net/browse/MM-9712
> MM-9712: ignore typing after ref unassigned

- components/post_view/post_attachment.jsx
Cleaned up post_attachment.jsx from jquery; especially considering that these jquery selectors were very heavy on performance...
While I am on it, I took the chance to further purify the component as a cleanup.
> Cleanup jquery from post_attachment.jsx 

- config/manifest.json
Google [recommends](https://developers.google.com/web/tools/lighthouse/audits/install-prompt) having a valid `short_name` property in the manifest.
(We are missing other recommended properties but this is a first step.)
Sorry for not opening a ticket first but this is a really small change.
> Missing short_name properties in web app manifest

- components/admin_console/custom_brand_settings.jsx
- components/common/site_name_and_description.jsx
- components/create_team/create_team.jsx
- components/create_team/index.js
- components/login/login_controller/login_controller.jsx
- components/select_team/index.js
- components/select_team/select_team.jsx
- components/signup/signup_email/signup_email.jsx
- components/signup/signup_ldap/index.js
- components/signup/signup_ldap/signup_ldap.jsx
- tests/components/common/__snapshots__/site_name_and_description.test.jsx.snap
- tests/components/common/site_name_and_description.test.jsx
- tests/components/create_team/__snapshots__/create_team.test.jsx.snap
- tests/components/create_team/create_team.test.jsx
Make site description (config.CustomDescriptionText) not dependent from config.EnableCustomBrand
- add separate component as `SiteNameAndDescription`
- use that component to all that require it
Jira ticket: [MM-9844](https://mattermost.atlassian.net/browse/MM-9844)
> [MM-9844] Make site description (config.CustomDescriptionText) not dependent from config.EnableCustomBrand

- components/create_post/index.js
- components/file_attachment/index.js
- components/file_info_preview/index.js
- components/file_upload/index.js
- components/user_settings/security/index.js
- components/view_image/index.js
- tests/utils/file_utils.test.jsx
- utils/file_utils.jsx
With the server now sending down all configurations by default, and this
defaulting to `true`, we can adopt the more conventional `=== 'true'`
check than the previous `!== 'false'`, subtly hiding the business logic
of defaults in the check itself.
See https://github.com/mattermost/mattermost-server/pull/8490 for the corresponding server changes.
https://mattermost.atlassian.net/browse/MM-9804
> MM-9804: simplify ExperimentalEnableAuthenticationTransfer comparisons

- sass/layout/_team-sidebar.scss
- utils/utils.jsx
MM-9822 - Changing team icon size
MM-8978 - Fixing active state for navbar icons
https://mattermost.atlassian.net/browse/MM-9822
https://mattermost.atlassian.net/browse/MM-8978
> Minor Ui fixes

- components/sidebar/sidebar.jsx
- sass/layout/_sidebar-left.scss
- sass/layout/_sidebar-right.scss
- sass/responsive/_mobile.scss
MM-9760 - Removing tooltip on mobile
MM-9817 - Fixing LHS header popover z-index
MM-9761 - Close button overlapping at the bottom
https://mattermost.atlassian.net/browse/MM-9760
https://mattermost.atlassian.net/browse/MM-9817
https://mattermost.atlassian.net/browse/MM-9761
> Minor Bug fixes

- actions/global_actions.jsx
- actions/post_actions.jsx
- components/channel_layout/channel_controller.jsx
- components/delete_post_modal/delete_post_modal.jsx
- components/delete_post_modal/index.js
- components/dot_menu/dot_menu.jsx
- components/dot_menu/dot_menu_item.jsx
- components/dot_menu/index.js
- components/edit_post_modal/edit_post_modal.jsx
- components/edit_post_modal/index.js
- tests/components/__snapshots__/delete_post_modal.test.jsx.snap
- tests/components/delete_post_modal.test.jsx
- tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
- tests/components/dot_menu/dot_menu.test.jsx
- tests/components/dot_menu/dot_menu_item.test.jsx
- tests/components/edit_post_modal.test.jsx
- utils/constants.jsx
Migrate delete_post_modal.jsx to be pure and use Redux.
Updated unit tests for editing post and menu item.
Also added new unit tests for delete_post_modal
mattermost/mattermost-server#7660
> Migrate delete_post_modal.jsx to be pure and use Redux

- components/create_comment/create_comment.jsx
- components/rhs_thread/rhs_thread.jsx
When you try to reply to a deleted message, we were sending the reply to the
server, and getting an error to show a modal about it. Now, because we know
that the message is already deleted, we show the modal directly without sending
anything to the server.
This behavior have the edge case where you send the reply before the app know
that the message was deleted in the server. In that case the behavior is the
same as before, wait until the server error and show the modal. That cases are
unusual, and we haven't another good solution for this.
[MM-9846](https://mattermost.atlassian.net/browse/MM-9846)
> MM-9846 Not try to reply when the root message is deleted

- actions/global_actions.jsx
This was missed in the original changes for this feature, helpfully pointed out by @koxen.
https://mattermost.atlassian.net/browse/MM-8787
> MM-9787: remove redundant class manipulation, now handled by Redux

- components/channel_header/channel_header.jsx
- components/channel_header/index.js
- components/dot_menu/dot_menu.jsx
- components/post_view/channel_intro_message/channel_intro_message.jsx
- components/post_view/post_body/index.js
- components/post_view/post_body/post_body.jsx
- components/post_view/post_info/index.js
- components/post_view/post_info/post_info.jsx
- components/post_view/reaction_list/index.js
- components/rhs_comment/index.js
- components/rhs_comment/rhs_comment.jsx
- components/rhs_root_post/index.js
- components/rhs_root_post/rhs_root_post.jsx
- components/sidebar/sidebar_channel/index.js
- components/sidebar/sidebar_channel/sidebar_channel.jsx
- sass/layout/_post.scss
Hide edit able elements for Town Square for non admin users when `"ExperimentalTownSquareIsReadOnly": true`.
Hide:
- channel view actions: post textbox, Edit channel header, Edit channel purpose, Rename channel.
- post view actions: reply, pin, emoji, + emoji icon.
Also, hide town square link on the LHS  when there are no unread messages and it is not favorited.
These changes were discussed in the original PRs:
- webapp: https://github.com/mattermost/mattermost-webapp/commit/0a9c047aadafebc9a2d92009c7c5fab72fea3aee
- server: https://github.com/mattermost/mattermost-server/pull/7140
- redux: https://github.com/mattermost/mattermost-redux/pull/222
cc @jason @dmeza
> Remove write access to town square. Hide it when no unread messages.

- components/channel_notifications_modal/channel_notifications_modal.jsx
- tests/components/__snapshots__/channel_notifications_modal.test.jsx.snap
Hides the option settings for desktop and push notifications in the channel preferences when the channel is muted.
https://mattermost.atlassian.net/browse/MM-10001
> MM-10001 Channel mute hide desktop and push settings

- components/permalink_view/permalink_view.jsx
On Jump link clicked, the permalink preview was returning a `null` which
provokes a gray screen in this case. This with dark themes generate a very ugly
visual effect. Now use the default color for the content.
[MM-9923](https://mattermost.atlassian.net/browse/MM-9923)
> MM-9923: Avoid to show a gray screen on jump

- components/file_attachment/filename_overlay.jsx
- components/view_image/image_preview.jsx
- tests/components/__snapshots__/image_preview.test.jsx.snap
- tests/components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap
- yarn.lock
Restore the ability to trigger actual file downloads for images and videos hosted by the Mattermost server. Remote assets will likely still load in a tab.
~Pending merge of the linked mattermost-redux changes, after which I'll update yarn.lock accordingly.~
https://mattermost.atlassian.net/browse/MM-9941
> use getFileDownloadUrl when attempting to trigger downloads

- yarn.lock
This pulls in the changes to skip logging 404s on missing custom emoji.
https://mattermost.atlassian.net/browse/MM-10010
> MM-10010: upgrade mattermost-redux

- components/add_users_to_team/add_users_to_team.jsx
- components/channel_invite_modal/channel_invite_modal.jsx
- components/more_direct_channels/more_direct_channels.jsx
- components/multiselect/multiselect.jsx
- tests/components/__snapshots__/add_users_to_team.test.jsx.snap
Two of the three components using MultiSelect modified their dataset to
assign a `value` key to the selectable values, triggering react-select's
default `valueKey` prop of `value` to handle item removal.
The component for adding users to a channel did not, resulting in the
removal of any one user in the list removing all of them. Exposing
`valueKey` and passing that as `id` in all three cases instead resolves
the issue.
https://mattermost.atlassian.net/browse/MM-9974
> MM-9974: expose and use react-select's valueKey prop

- utils/channel_utils.jsx
Fix optional parameter of haveIChannelPermission to correctly evaluate whether a user can manage members
- this fixes the issue of non-admin user (but with appropriate permission to manage channel members) not seeing a link to add user/s after at-mention to the channel.
Jira ticket: [MM-10024](https://mattermost.atlassian.net/browse/MM-10024)
> [MM-10024] Fix optional parameter of haveIChannelPermission to correctly evaluate whether a user can manage members

- components/integrations/abstract_oauth_app.jsx
- tests/components/integrations/__snapshots__/abstract_oauth_app.test.jsx.snap
IsTrusted field is only showed if you have permissions to manage the entire system.
[MM-10032](https://mattermost.atlassian.net/browse/MM-10032)
> MM-10032: Fix permission used to show IsTrusted field in Oauth 2 integrations form

- components/member_list_channel/member_list_channel.jsx
Sort users of view/manage members per username and not by user's status
Jira ticket: [MM-9959](https://mattermost.atlassian.net/browse/MM-9959)
> [MM-9959] Sort users of view/manage members per username and not by user's status

- components/search_bar/search_bar.jsx
Make the pinned and member buttons clickable after blur of search box
Jira ticket: [MM-10033](https://mattermost.atlassian.net/browse/MM-10033)
> [MM-10033] Make the pinned and member buttons clickable after blur of search box

- components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
- i18n/en.json
Doc PR: mattermost/docs#1890
Resubmitting https://github.com/mattermost/mattermost-webapp/pull/1007, which had issues with spinmints.
UI text now loos like:
> Update wording on DM restriction config setting

- components/permissions_gates/channel_permission_gate/channel_permission_gate.jsx
- components/permissions_gates/system_permission_gate/system_permission_gate.jsx
- components/permissions_gates/team_permission_gate/team_permission_gate.jsx
Basically PureComponent is not really needed, because the children prop will be
almost alwais a new object, so will rerender almost every single time, so we
can skip the props comparison.
> Removing pure components from gates

- actions/views/rhs.js
- components/search_bar/search_bar.jsx
- components/search_results/index.jsx
- components/search_results/search_results.jsx
- reducers/views/rhs.js
- selectors/rhs.jsx
- tests/redux/actions/views/rhs.test.js
- tests/redux/reducers/views/rhs.test.js
- utils/constants.jsx
This PR reverts an earlier one that moved the search box state out of redux and into the component state because that PR assumed that there was only one search box component. We actually use two search boxes that are visible at different times but should always have the same value, so that state needs to be in redux.
https://mattermost.atlassian.net/browse/MM-9997
> MM-9997 Track search box input seaprate from results highlighting

- components/post_view/post_list.jsx
The post_list handle scroll changes, and mark "atBottom" in the component if
you are at the bottom, to be sure the next scroll change move you to there.
Because a race condition, sometimes is marked atBottom before the focused post
is positioned, so nexts scroll updates, move you to the bottom.
I have forced to recalculate the "atBottom" property after positioning the post.
[MM-9860](https://mattermost.atlassian.net/browse/MM-9860)
> MM-9860: mark atBottom only after finish initial positioning

- components/rhs_comment/rhs_comment.jsx
- components/rhs_thread/rhs_thread.jsx
- JS error quick fix on teamId props of RhsComment
- also renamed Comment to RhsComment when using that component so it's easier to locate
none
> JS error quick fix on teamId props of RhsComment

- stores/suggestion_store.jsx
- tests/stores/suggestion_store.test.jsx
In a slow network environment, typing a channel name, then erasing it,
then quickly typing again and hitting enter to unmount the suggestion
box could result in a previous network call eventually dispatching an
event for the now unregistered suggestion box. If the dispatched event
was for an empty string, it would incorrectly try to handle that,
ultimately attempting to dereference `undefined.push`.
https://mattermost.atlassian.net/browse/MM-9973
> MM-9973: ignore dispatched events against unregistered suggestion boxes

- actions/global_actions.jsx
- components/post_view/post_add_channel_member/post_add_channel_member.jsx
- components/rhs_comment/rhs_comment.jsx
- tests/components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
Fix the remaining issues of MM-9785
1. Timestamp of ephemeral post is earlier than message where the user posted at-mention
- not sure why `Utils.getTimestamp()` is not working as I would expect it to be, so I just increment `create_at` so it will always be next to where the user posted at-mention
2. Can flag ephemeral post
- used the `isEphemeralPost` function from the mattermost-redux since it's considering the new ephemeral post type of `POST_TYPES.EPHEMERAL_ADD_TO_CHANNEL`. On master, for I'm planning to update all `Utils.isEphemeralPost` to use the said utility function from mattermost-redux as well.
3. Update ephemeral post of add to channel so that it respects the teammate name display setting.
Jira ticket: [MM-9785](https://mattermost.atlassian.net/browse/MM-9785)
> [MM-9785] Fix timestamp, ability to flag and not respecting teammate name display setting of add to channel ephemeral post on RHS

- components/view_image/view_image.jsx
- tests/components/__snapshots__/view_image.test.jsx.snap
Ironically, my earlier attempt to fix this somehow avoided fixing the
very report of the issue, instead only fixing clicking on the image to
download.
I've since mapped out all the various preview components and believe this correctly covers things.
https://mattermost.atlassian.net/browse/MM-9941
> pass the download link to the PopoverBar to "Download"

- components/rhs_comment/index.js
- components/rhs_root_post/index.js
- components/rhs_root_post/rhs_root_post.jsx
- components/rhs_thread/rhs_thread.jsx
ADD_REACTIONS permissions wasn't checked for the rhs_root_post and wasn't
correctly checked for replys on direct/group chat messages.
[MM-10041](https://mattermost.atlassian.net/browse/MM-10041)
> MM-10041: Fixed reactions permissions on RHS posts

- components/delete_post_modal/delete_post_modal.jsx
- tests/components/__snapshots__/delete_post_modal.test.jsx.snap
- tests/components/delete_post_modal.test.jsx
Fix a regression around cancelling the delete post modal.
https://mattermost.atlassian.net/browse/MM-10086
> MM-10086: fix cancel delete post modal

- actions/global_actions.jsx
- components/create_post/index.js
A lot of elements (markdown elements, emojis, images...) emits
postListScrollChange events, so each event is handled, basically if almost 0
effect except for the last one, or the "forcedToBottom" one. So I splitted the
actions in 2, one for forcedToBottom, without debounce, and the action without
forceToBottom, which is debounced. It reduce the number of calls to
handleScroll in the post_list component from 60 to 1 or something like that
(depends on the posts of the channel).
[MM-10043](https://mattermost.atlassian.net/browse/MM-10043)
> Throttling the postListScrollChange action

- components/channel_invite_modal/channel_invite_modal.jsx
Adds a loader for channel invite modal
instead of empty state on load, it shows a loader.
> Fix loading state of invite channel modal

- components/sidebar_right_menu/index.js
The permissions checking on team menu wasn't working because we haven't the
teamId defined.
[MM-10096](https://mattermost.atlassian.net/browse/MM-10096)
> MM-10096: Fix permissions checking in mobile view menu

- actions/file_actions.jsx
Add missing getState on forceLogoutIfNecessary call on upload fail.
> Add missing getState on forceLogoutIfNecessary

- components/team_settings_modal.jsx
Make TeamSettings work the same as AccountSettings by resetting the tab and section active when it is hidden.
https://mattermost.atlassian.net/browse/MM-9805
> MM-9805: When hiding/closing team settings modal, reset what is displayed. 

- tests/utils/formatting_at_mentions.test.jsx
- utils/text_formatting.jsx
This fixes:
1. Highlighting of uppercase at mentions (eg `@CHANNEL`, `@aLL`)
2. Linking of uppercase at mentions (eg clicking `@USER` now properly opens the profile popover for that user)
https://mattermost.atlassian.net/browse/MM-10036
- Ran `make test` to ensure unit and component tests passed
> MM-10036 Properly handle case-insensitive at mentions

- components/team_general_tab/team_general_tab.jsx
- components/user_settings/general/user_settings_general.jsx
- components/user_settings/notifications/user_settings_notifications.jsx
- utils/utils.jsx
Chrome sets the cursor at the beginning of text inputs with a value by default ([example fiddle](https://jsfiddle.net/geo5guky/)).
[MM-9803](https://mattermost.atlassian.net/browse/MM-9803)
> MM-9803: Fixes cursor placement in team and user settings.

- components/needs_team/index.js
- components/needs_team/needs_team.jsx
When returning to Mattermost after having the window inactive we are fetching the channels and members instead of just the members to have the unread count in sync.
https://mattermost.atlassian.net/browse/MM-10172
> Fixing missing channel unread and mentions when activating window

- components/more_direct_channels/more_direct_channels.jsx
JS error quick fix on onHide function of MoreDirectChannels
Said props is not really required as we are doing this inside the component itself:
```
if (this.props.onHide) {
this.props.onHide();
}
```
none
> JS error quick fix on onHide function of MoreDirectChannels

- components/quick_input.jsx
After various attempts to fix this issue in a way that doesn't cause IE11 and the desktop app to break constantly, I realized that it was more simple to fix the QuickInput by just being more careful about when we call `this.textbox.value = this.props.value`. If we only call it when it's needed, we won't need to deal with issues caused by setting it.
This replaces https://github.com/mattermost/mattermost-webapp/pull/945 and https://github.com/mattermost/mattermost-webapp/pull/1027 which fixed their bugs but introduced the one that this ticket was filed for
https://mattermost.atlassian.net/browse/MM-10197
- Touches critical sections of the codebase (auth, posting, etc.)
> MM-10197 Stopped setting QuickInput value when already set

- components/admin_console/admin_definition.jsx
- i18n/en.json
This is the corresponding change to https://github.com/mattermost/mattermost-server/pull/8628, reflecting that changing log settings require a restart.
https://mattermost.atlassian.net/browse/MM-10174
> MM-10174: reflect that log settings require a restart

- components/suggestion/switch_channel_provider.jsx
The other usages of getState() in the suggestion components aren't really a problem since they are triggered by events and the suggestions are ephemeral. In reality, this one wasn't a big deal either but since it was easy to fix I did so anyway.
@jasonblais I think I also fixed a bug with this. Previously if you opened the channel switcher it would show the mention badge for channels with mentions but as soon as you started typing the mention badge would disappear (even if you could still see that channel in the list). I assumed this was a bug and fixed it so that the badge would remain. Let me know if this wasn't a bug and I can revert that change
https://mattermost.atlassian.net/browse/MM-9827
> MM-9827 Remove getState usage in SwitchChannelSuggestion

- components/admin_console/admin_definition.jsx
- i18n/en.json
The string is correct in the [webapp component](https://github.com/mattermost/mattermost-webapp/blob/master/components/admin_console/admin_definition.jsx#L561) but not in en.json.
N/A
> Fix error in LDAP sync help text

- components/admin_console/system_users/index.js
- components/admin_console/system_users/list/index.js
- components/admin_console/system_users/list/selectors.jsx
- components/admin_console/system_users/list/system_users_list.jsx
- components/admin_console/system_users/system_users.jsx
- package.json
- tests/components/admin_console/system_users/__snapshots__/system_users.test.jsx.snap
- tests/components/admin_console/system_users/__snapshots__/system_users_list.test.jsx.snap
- tests/components/admin_console/system_users/selectors.test.jsx
- tests/components/admin_console/system_users/system_users.test.jsx
- tests/components/admin_console/system_users/system_users_list.test.jsx
- yarn.lock
This is one of a series of JIRAs to resolve the use of `getState` in components outside of the Redux connector flow. The problem with using `getState` like this is that changes to the store do not automatically reflect into the component unless something else changes to trigger re-render. While the config is no longer accessed via `window.mm_config`, this usage is effectively just as "global", and is hampering our attempts to eliminate the refresh on a config change.
The crux of this particular change is to move the computation of the users to be shown in the system console users page out of the component and into the connector. This is done by passing down the parameters (e.g. selected team, search term) into the system users list, whose connector intercepts and selects the requisite …
> MM-9831: expunge get state in admin console

- components/admin_console/admin_definition.jsx
- components/admin_console/schema_admin_settings.jsx
Until now, the disable or hidden behavior of the widgets in the new declarative
admin console worked as a set of attributes needs_<whatever> with a plain
value. It was because my desire was to have a full declarative structure
(something like a json), but that is not practica, so now makes more sense to
receive a function as isDisabled or isHidden.
> Changing needs admin_console definitions

- components/post_view/failed_post_options/failed_post_options.jsx
- components/post_view/failed_post_options/index.js
- tests/components/post_view/__snapshots__/failed_post_options.test.jsx.snap
- tests/components/post_view/failed_post_options.test.jsx
- tests/setup.js
The race was such that the component would transition out of the `submitted` state before the Redux store would reflect the non-failed status of the post and in turn remove the component. This was most easily reproduced by posting when offline, switching to slow 3G, and then mashing the retry button.
https://mattermost.atlassian.net/browse/MM-8528
> MM-8528: prevent duplicate posts on retries

- root.html
Set character encoding in HTML.
Until I get the test back from the original reporter I won't know if this fix closes MM-9858 but it should go in nevertheless.
[MM-9858](https://mattermost.atlassian.net/browse/MM-9858)
> MM-9858: Declares character encoding in HTML.

- components/user_settings/advanced/user_settings_advanced.jsx
- components/user_settings/notifications/user_settings_notifications.jsx
- components/user_settings/security/user_settings_security.jsx
- components/user_settings/sidebar/user_settings_sidebar.jsx
- components/user_settings/user_settings.jsx
While working on [MM-9984](https://mattermost.atlassian.net/browse/MM-9984) - https://github.com/mattermost/mattermost-webapp/pull/1111, I've found unused props in the Account Settings and thought to clean it up here separately.
none
> Remove unused props in the account settings

- components/post_view/post_body_additional_content/post_body_additional_content.jsx
- components/view_image/popover_bar/index.js
- components/view_image/popover_bar/popover_bar.jsx
- components/view_image/view_image.jsx
- i18n/en.json
- tests/components/__snapshots__/view_image.test.jsx.snap
- tests/components/__snapshots__/view_image_popover_bar.test.jsx.snap
- tests/components/view_image.test.jsx
- tests/components/view_image_popover_bar.test.jsx
- tests/setup.js
This PR distinguishes between internally hosted images and externally hosted images to show a "Download" or "Open" option on the image popover bar respectively.
A recent change had been made to ensure "Download" actually triggered a `Content-Disposition: attachment` for files hosted by Mattermost, but no such guarantee could be made for external files despite showing the same user interface element. Hence this PR.
I've also included a single commit to address a logging issue re: props handling.
https://mattermost.atlassian.net/browse/MM-9988
> MM-9988: rename to "Open" external images

- actions/search.js
- actions/team_actions.jsx
- actions/user_actions.jsx
- actions/views/search.js
- components/add_users_to_team/add_users_to_team.jsx
- components/add_users_to_team/index.js
- components/member_list_channel/index.js
- components/member_list_channel/member_list_channel.jsx
- components/member_list_team/index.js
- components/member_list_team/member_list_team.jsx
- components/more_direct_channels/index.js
- components/more_direct_channels/more_direct_channels.jsx
- components/post_view/post_add_channel_member/index.js
- reducers/views/index.js
- reducers/views/search.js
- tests/components/add_users_to_team.test.jsx
- utils/constants.jsx
Added a new view reducer for tracking modal search terms, removed flux store and `store.getState()` usages and performed some other minor refactoring.
https://mattermost.atlassian.net/browse/MM-9829
> MM-9829 Remove store.getState() usages from user list modals

- components/rhs_thread/rhs_thread.jsx
Updates placement of date separator in RHS when the root post was deleted.
[MM-9924](https://mattermost.atlassian.net/browse/MM-9924)
> MM-9924: Updates placement of date separator.

- components/admin_console/custom_integrations_settings/custom_integrations_settings.jsx
- components/admin_console/custom_integrations_settings/index.jsx
- components/admin_console/policy_settings/index.jsx
- components/admin_console/policy_settings/policy_settings.jsx
- components/admin_console/users_and_teams_settings/index.jsx
- components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
The problem was that the roles loading can have different states.
- If the version is not loaded yet, it store the roles to load in a list and returns directly. (this was the problematic case).
- If the version is already there, it get the list of pending roles, add the new requested roles, and make the request to load them. (this was working fine)
My change simply load into the state when the component realize that everything is ready.
[MM-10293](https://mattermost.atlassian.net/browse/MM-10293)
> MM-10293: More robust initial load on admin_console pages for loadRolesIfNeeded

- components/needs_team/needs_team.jsx
Fix CTLR+SHIFT+L shortcut when the textbox is not visible (for example, integrations section).
[MM-10080](https://mattermost.atlassian.net/browse/MM-10080)
> Fix CTLR+SHIFT+L shortcut when the textbox is not visible

- package-lock.json
- package.json
The version of all packages in package.json has to be locked or else `npm install` will grab the latest ones
> Added explicit versions to all packages

- components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
- components/select_team/index.js
- components/select_team/select_team.jsx
Revert help note when team creation is set to system admin only
Jira ticket: [MM-10062]
> [MM-10062] Revert help note when team creation is set to system admin only

- tests/utils/formatting_wildcards.text.jsx
- utils/text_formatting.jsx
Should only match `*` character when it's preceded by a word character.
[MM-10095](https://mattermost.atlassian.net/browse/MM-10095)
> MM-10095: Fix for invalid wildcard suffix pattern.

- components/post_view/failed_post_options/failed_post_options.jsx
- components/post_view/failed_post_options/index.js
- package-lock.json
- package.json
- tests/components/post_view/__snapshots__/failed_post_options.test.jsx.snap
- tests/components/post_view/failed_post_options.test.jsx
This is the PR that complements https://github.com/mattermost/mattermost-redux/pull/466.
This restores some of 8e1241ab7000d64134fa55afd2cc85e43518c035 with changes to reflect the relocated logic into mattermost-redux.
Note that the retry component never actually supported handling the `api.post.craete_post.root_id.app_error` error: `showPostDeletedModal` was never implemented. Hence the simple removal of this code for now: a separate JIRA issue will be filed to track the root post deletion case.
https://mattermost.atlassian.net/browse/MM-8528
> Update mattermost-redux to deduplicate retrying posts.

- components/create_post/create_post.jsx
- components/create_post/index.js
- tests/components/create_post/create_post.test.jsx
The focus will go back to the RHS text box using SHIFT+UP combo when the RHS is already open. 
[PLT-7803] https://github.com/mattermost/mattermost-server/issues/7580
> Shift+up switch keyboard focus to RHS if it's already open to the current thread

- components/admin_console/custom_integrations_settings/custom_integrations_settings.jsx
- components/admin_console/custom_integrations_settings/index.jsx
- components/admin_console/policy_settings/index.jsx
- components/admin_console/policy_settings/policy_settings.jsx
- components/admin_console/users_and_teams_settings/index.jsx
- components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
The problem was that the roles loading can have different states.
- If the version is not loaded yet, it store the roles to load in a list and returns directly. (this was the problematic case).
- If the version is already there, it get the list of pending roles, add the new requested roles, and make the request to load them. (this was working fine)
My change simply load into the state when the component realize that everything is ready.
[MM-10293](https://mattermost.atlassian.net/browse/MM-10293)
> MM-10293: More robust initial load on admin_console pages for loadRolesIfNeeded [Backport to 4.9]

- package-lock.json
- package.json
This is to make our link parsing slightly more forgiving and GitHub-like since we don't currently allow links containing periods followed by punctuation like https://example.com/?text=Test+phrase.+Please+ignore
Based off of https://github.com/mattermost/mattermost-webapp/pull/1126
Marked changes here: https://github.com/mattermost/marked/commit/4bc7e5f00c324d2eadec6b932224871497af6f7c
https://mattermost.atlassian.net/browse/MM-10180
> MM-10180 Better handle characters after periods in URLs

- tests/utils/__snapshots__/post_utils.test.jsx.snap
- tests/utils/post_utils.test.jsx
- utils/markdown/renderer.jsx
Empty divs aren't valid in plain HTML, so html-to-react tries by default to "fix" the html which causes problems.
https://mattermost.atlassian.net/browse/MM-10403
https://github.com/mattermost/mattermost-server/issues/8660
https://github.com/mattermost/mattermost-server/issues/8683
> MM-10403 Fixed rendering of text following a latex block

- sass/components/_videos.scss
Shadow appears on image that are linked when the mouse hovers over the image. 
MM-10104
Left: when mouse is not hovering over image that is uploaded using link
Right: when mouse is hovering over image that is uploaded using link
Left: when mouse is not hovering over image that is uploaded using paperclip icon in message box
Right: when mouse is hovering over image that is uploaded using paperclip icon in message box
> Add shadow on link preview image

- components/quick_switch_modal/quick_switch_modal.jsx
- tests/components/quick_switch_modal.test.jsx
Fixes the quick channel switcher modal to actually switch to a DM channel without throwing errors, we were using the channel.id instead of the user.id I forgot about that in my last PR
https://mattermost.atlassian.net/browse/MM-10429
> Fix CMD/CTRL+K switch to DM channels

- sass/layout/_post.scss
MM-10431 - Updating UI for post controls
https://mattermost.atlassian.net/browse/MM-10431
**Before:**
**After:**
> MM-10431 - Updating UI for post controls

- components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
- package-lock.json
- package.json
Some pages (like a GitHub PR with no description set) include an empty OpenGraph description, so this null check prevented the OpenGraph data for those pages from being saved into the store and eventually shown in a preview
Redux PR: https://github.com/mattermost/mattermost-redux/pull/478
https://mattermost.atlassian.net/browse/MM-10360
> MM-10360 Render OpenGraph previews for pages with an empty description

- actions/websocket_actions.jsx
…
Remove users from Add Members selection whenever it's added by other user
- dispatch `UserTypes.RECEIVED_PROFILE_IN_CHANNEL` whenever `SocketEvents.USER_ADDED` is received.
Note: I tried to add test but I am not sure how to achieve it since `handleUserAddedEvent` is not exported.  `WebSocketActions` in general I think is hard to test currently.
Jira ticket: [MM-10337](https://mattermost.atlassian.net/browse/MM-10337)
> [MM-10337] Remove users from Add Members selection whenever it's added by other user

- package-lock.json
- package.json
Update mattermost-redux to point to last master commit (fix MM-10464 bug)
[MM-10464](https://mattermost.atlassian.net/browse/MM-10464)
> Update mattermost-redux to point to last master commit (fix MM-10464 bug)

- components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
- package-lock.json
- package.json
The previous version didn't work because the OpenGraph library returns an empty description for any valid link
https://mattermost.atlassian.net/browse/MM-10360
- Has redux changes
> MM-10360 Only show OpenGraph previews if they have a url defined

- components/local_date_time/index.js
- components/profile_popover/index.js
- selectors/general.js
IE11 only supports the default UTC time zone, so trying to give it any other time zone causes it to error out and display the date incorrectly. I've created a followup ticket to decide on how to move forward with this, but in the mean time, I've disabled it since it's an experimental feature anyway.
https://mattermost.atlassian.net/browse/MM-10338
> MM-10338 Disabled time zones on IE11

- components/root/root.jsx
Use init function in redux to store a reference for translation
[MM-10331](https://mattermost.atlassian.net/browse/MM-10331)
> Init translation for redux lib

- components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
…k removes it.
Link preview that is shared will be collapsed if the original user that posted the link removes the preview. 
If I remove a link preview that I shared, it should also be removed for other users
https://mattermost.atlassian.net/browse/MM-9280
> [MM-9280] Link preview is removed for all users if the user that posted the link removes it

- components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
- components/admin_console/schema_admin_settings.jsx
- tests/components/admin_console/__snapshots__/custom_plugin_settings.test.jsx.snap
Plugin settings in the config are case insensitive so they weren't being handled properly by the new admin console changes.
https://mattermost.atlassian.net/browse/MM-10492
https://github.com/mattermost/mattermost-server/issues/8713
> MM-10492 Fix saving plugin settings in the system console

- components/rhs_thread/rhs_thread.jsx
Wrong substitute value was being used for `rootPostDay` when data retention deleted the root post.
Release 4.10 bug.
> Fix incorrect post date when data retention has deleted root.

- store/index.js
The problem is related to how redux-persist "debounce" writes. It iterate over
pending writes and then wait the "debounce" time. Normally redux-persist only
read or write the entire state in one single action. We have a modification to
write the different keys in different localForage keys, to reduce the inter-tab
synchronization conflicts. So, the debounce was delaying the whole "save to
localforage" process to 500ms per item stored. Sometimes with multiple tabs
opened or in reload, this delay implies that the data isn't saved to localForage.
It can still happen, but now is more difficult.
[MM-10397](https://mattermost.atlassian.net/browse/MM-10397)
> MM-10397: Reducing persist debounce

- components/file_attachment_list/file_attachment_list.jsx
- components/file_attachment_list/index.js
- components/single_image_view/single_image_view.jsx
- sass/components/_files.scss
Added a feature to allow the image uploaded to be collapsed using an icon and using /collapse command
N/A
Left: Image is collapsed
> Collapse uploaded image

- components/suggestion/switch_channel_provider.jsx
Wasn't actually caused by what I thought but just a simple mistake of expecting an array when the entity was a set. Flow would help with this :)
https://mattermost.atlassian.net/browse/MM-10515
> MM-10515  Fix the channel switcher after switching to a new DM

- utils/utils.jsx
I happened to come across some of these when trying to debug an error earlier, so I thought I'd do a bit of a purge. There's probably some more that can be eliminated by replacing them with the mattermost-redux equivalents, and there's a lot that can be done by moving some of the functions to more suitable places to get rid of circular dependencies here
> Removed unused functions from utils.jsx

- package-lock.json
- package.json
- tests/utils/formatting_email.test.jsx
- utils/text_formatting.jsx
The existing library is having issues with large blocks of text without spaces (like 16000 A's in a row) that causes the channel to lag when making multiple posts like that, so I've swapped it for the code we use in the mobile app.
This is needed for the increased post limit.
> Removed autolinker.js

- components/announcement_bar/announcement_bar.jsx
- tests/components/__snapshots__/announcement_bar.test.jsx.snap
- tests/components/announcement_bar.test.jsx
- tests/helpers/localstorage.jsx
Just needed to update state again when one of the banner settings in the props changed.
The behavior is as follows:
If the banner is being enabled for the first time:
* Right after enabling and saving the banner settings, the banner will be immediately shown to users with the settings as set
If the banner **has no**t been dismissed by the user:
* Changes to the enabled, text, text color, banner color or allow dismissal settings will be reflected immediately in all users' clients
If the banner **has** been dismissed by the user:
* Changes to text or allow dismissal settings will cause the banner to show again
* Changes to enabled, text color or banner color will not cause the banner to show again (enabled because if you're disabling it wouldn't show the banner either way) …
> MM-10541 Update announcement banner immediately without refresh

- components/post_view/post_list.jsx
We was scrolling to new posts separator every time, and this makes sense only when the separator is out of the screen.
I'm not sure about the need of `setUnreadsBelow` call, but the current behavior if you reach the bottom and go up again in a channel with a lot of unreads, is to not show the "new messages" badge. So I think we are good not calling `setUnreadsBelow`.
[MM-10260](https://mattermost.atlassian.net/browse/MM-10260)
> MM-10260: only scroll to new message separator if it doesn't fit in the current screen

- components/setting_picture.jsx
- tests/components/__snapshots__/setting_picture.test.jsx.snap
- tests/components/setting_picture.test.jsx
Make team icon not automatically saved when removed
Jira ticket: [MM-10609](https://mattermost.atlassian.net/browse/MM-10609)
> [MM-10609] Make team icon not automatically saved when removed

- components/team_general_tab/index.js
- components/team_general_tab/team_general_tab.jsx
- tests/components/__snapshots__/team_general_tab.test.jsx.snap
- tests/components/team_general_tab.test.jsx
Hides the "invite code" section from team settings if you don't have permission to invite users to the team.
https://mattermost.atlassian.net/browse/MM-10506
> MM-10506: Hide the invite-code config from Team Settings when no invite permissions.

- components/team_import_tab.jsx
- i18n/en.json
The actual fix for this issue is very involved, and doesn't make sense to do given we are trying to move towards an out-of-band Slack-to-Bulk-Import converter.
Instead, add a note in the web UI recommending using the CLI for larger Slack team imports.
https://mattermost.atlassian.net/browse/MM-9692
> MM-9692: Add note to use Slack Importer CLI for larger ones.

- actions/websocket_actions.jsx
- package-lock.json
- package.json
Include the channel `id` a property of `data`, not the action itself. Note that the `UserStore` is also doing this incorrectly, but the methods appear to be unused.
This also update mattermost-redux to pull in https://github.com/mattermost/mattermost-redux/pull/505.
https://mattermost.atlassian.net/browse/MM-10666
> MM-10666: fix RECEIVED_PROFILE_IN_CHANNEL

- actions/notification_actions.jsx
- components/channel_header/channel_header.jsx
- components/login/login_controller/login_controller.jsx
- components/message_wrapper.jsx
- components/post_markdown/post_markdown.jsx
- components/post_view/post_attachment.jsx
- plugins/index.js
- tests/utils/__snapshots__/message_html_to_component.test.jsx.snap
- tests/utils/message_html_to_component.test.jsx
- tests/utils/post_utils.test.jsx
- utils/message_html_to_component.jsx
- utils/post_utils.jsx
This was an attempt to reduce some circular references so that I could write a unit test. It didn't manage to fix the unit test, but I think it's still good to clean up some of that.
Waiting for https://github.com/mattermost/mattermost-webapp/pull/1195 to be merged into master so that it doesn't cause merge conflicts there
> Moved messageHtmlToComponent into its own file

- actions/channel_actions.jsx
Before, commands that used mentions, such as `/invite @user`, would not work if there was extra whitespace (more than just one space) between `/invite` and `@user`. This PR changes it such that a typed command like this would still work: `/invite    @user`.
https://github.com/mattermost/mattermost-server/issues/8720
https://mattermost.atlassian.net/browse/MM-10406
> [MM-10406] Ignore extra whitespace in commands that use mentions

- components/setting_picture.jsx
- components/team_general_tab/team_general_tab.jsx
- tests/components/__snapshots__/setting_picture.test.jsx.snap
- tests/components/setting_picture.test.jsx
This is a follow up PR in removing the team icon - [MM-10609](https://mattermost.atlassian.net/browse/MM-10609).
The save button is enabled after clicking "x" so that an admin can revert to the default team icon (of none).
Jira ticket: [MM-10609](https://mattermost.atlassian.net/browse/MM-10609)
> [MM-10609] Add function to save after removing the team icon

- components/youtube_video/youtube_video.jsx
- tests/components/youtube_video/youtube_video.test.jsx
Update youtube link parsing regex to accept 3 known formats of "start time" in youtube links.
The following should all work correctly now:
* https://www.youtube.com/watch?time_continue=490&v=xqCoNej8Zxo
* https://www.youtube.com/watch?start=490&v=xqCoNej8Zxo
* https://www.youtube.com/watch?t=490&v=xqCoNej8Zxo
https://mattermost.atlassian.net/browse/MM-10599
> MM-10599: Accept multiple youtube start time formats.

- components/textbox.jsx
- tests/components/__snapshots__/textbox.test.jsx.snap
- tests/components/textbox.test.jsx
Emojis are counted as characters, so if the emoji is selected after the word limit has been reached it will display "Your message is too long. Character count: xxxx/xxxx"
https://github.com/mattermost/mattermost-server/issues/8519
> Adding emoji after word limit is reached will give warning message.

- package-lock.json
- package.json
Adds the next commit from Redux:
https://github.com/mattermost/mattermost-redux/compare/d40b0960fdb810d3ff3d3726c69cae6ea2992292...5408311258ba18fccf886759ef878c458471417c
Request: https://pre-release.mattermost.com/core/pl/ffbsecko97ygbmjo8i9ez1kb1o
n/a
> MM-10432: Adds next Redux commit for dot release.

- components/system_notice/system_notice.jsx
- tests/components/__snapshots__/system_notice.test.jsx.snap
Fix UI string ID in system_notice.jsx
I had the option of just fixing the string in en.json, but this would have been inconsistent with other strings. Hence fixed it in system_notice.jsx and updated the relevant test snapshots.
Wondering if there's anything we can do in future to capture errors affecting localization via unit tests?
Reported by French community: https://pre-release.mattermost.com/core/pl/wmjsjq4dqffpbbq6ecisnbxpxa
> Fix UI string ID in system_notice.jsx

- components/integrations/abstract_outgoing_webhook.jsx
- i18n/en.json
Update to "channel" field help text in "Create Outgoing Webhook" screen
N/A. See https://pre-release.mattermost.com/core/pl/xw5kynxaa7815ncoy9pyspo86r
Credit to @grundleborg and @herooftimeandspace
> Update to "channel" field help text in "Create Outgoing Webhook" screen

- components/integrations/abstract_incoming_webhook.jsx
- i18n/en.json
- tests/components/integrations/__snapshots__/abstract_incoming_hook.test.jsx.snap
Add the ability to lock an incoming webhook to a single channel.
https://mattermost.atlassian.net/browse/MM-10352
> MM-10352: Enable locking incoming webhooks to a single channel.

- components/analytics/team_analytics/team_analytics.jsx
Fixing the header of the team statistics in the admin console
> Fixing the header of the team statistics in the admin console

- sass/components/_permissions.scss
Fix description opacity in permissions tree headers
> Fix description opacity in permissions tree headers

- components/login/login_mfa.jsx
- tests/components/login/login_mfa.test.jsx
For: https://github.com/mattermost/mattermost-server/pull/8881
In hardened mode we don't want to disclose if a user has MFA enabled or not, so we need to show this screen every time when MFA and hardened mode is enabled. A user needs to be able to bypass it. Submitting a blank is a convenient way to do that. This allows blank submissions. (will still error properly when hardened mode is disabled.)
> Allowing empty submission of MFA for hardened mode.

- actions/websocket_actions.jsx
- components/more_channels/index.js
- components/more_channels/more_channels.jsx
- components/quick_input.jsx
- package-lock.json
- package.json
- tests/components/__snapshots__/more_channels.test.jsx.snap
- tests/components/more_channels.test.jsx
- tests/utils/url.test.jsx
- utils/constants.jsx
- utils/url.jsx
Remove channel from MoreChannels whenever a channel is converted form public to private.
Also migrate `MoreChannels` to PureComponent using redux store. 
Jira ticket: [MM-10519](https://mattermost.atlassian.net/browse/MM-10519)
> [MM-10519] Remove channel from MoreChannels whenever a channel is converted form public to private

- components/channel_layout/channel_identifier_router.jsx
The problem is that the ChannelIdentifierRouter code just uses the current team ID, and it didn't recalculate the current channel ID before unless the URL changed after the team name. It still accesses the Flux stores, but I don't think I have time to change that for 5.0
https://mattermost.atlassian.net/browse/MM-10372
- Touches critical sections of the codebase (auth, posting, etc.)
> MM-10372 Fixed linking between teams from channels with the same name

- components/markdown/markdown.jsx
- components/markdown_image.jsx
- components/post_markdown/post_markdown.jsx
- components/post_view/post_message_view/post_message_view.jsx
- tests/plugins/__snapshots__/post_type.test.jsx.snap
- utils/message_html_to_component.jsx
This is based off of https://github.com/mattermost/mattermost-webapp/pull/1270 since they both touch the same area. The gist of this idea is to check the height of the post when images are laid out on the page.
The actual changes for this PR are here: https://github.com/mattermost/mattermost-webapp/commit/f67237bb1ed4ac22657de14b610a5099e60d7f88
https://mattermost.atlassian.net/browse/MM-10706
> MM-10706 Recalculate post height for collapsed post after images load

- components/system_notice/notices.jsx
- i18n/en.json
Looks like we're doing two separate notices for v5.0 instead of a single one: https://github.com/mattermost/mattermost-webapp/pull/1280
So tweaked text for the existing notice.
> Update APIv3 pop-up notice

- components/post_markdown/system_message_helpers.jsx
- components/post_view/combined_system_message/combined_system_message.jsx
- components/post_view/combined_system_message/index.js
- package-lock.json
- package.json
- tests/components/combined_system_message/__snapshots__/combined_system_message.test.jsx.snap
- tests/components/combined_system_message/combined_system_message.test.jsx
- utils/utils.jsx
Fix missing username on combined system messages by supporting backward compatibility on addedUsername props when user was added to the channel or team.
Note: Will update commit of `mattermost-redux` once corresponding change is merged.
Jira ticket: [MM-10727](https://mattermost.atlassian.net/browse/MM-10727)
> [MM-10727] Fix missing username on combined system messages

- components/backstage/backstage_controller.jsx
- components/backstage/components/backstage_sidebar.jsx
- components/backstage/index.js
- components/sidebar/header/dropdown/index.js
- components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
- tests/plugins/main_menu_action.test.jsx
- utils/utils.jsx
The emojis option in the menus wasn't based in permissions. This commit fix that problem.
[MM-10793](https://mattermost.atlassian.net/browse/MM-10793)
> MM-10793: Handle the show/hide custom emojis in menu using permissions

- components/team_selector_modal/team_selector_modal.jsx
Sort the teams in the teams selector modal (for cases where the instance have
more than 50 teams, is posible that we need to set the order in the backend
too)
[MM-10767](https://mattermost.atlassian.net/browse/MM-10767)
> MM-10767: Sort the teams in the teams selector modal

- actions/websocket_actions.jsx
(This is a follow up PR for MM-10519 which encounter permission error when the observing user is a regular user.)
Fix permission error on channel_converted event by not getting the channel via redux action which performs API calls.  
This change optimistically update the channel into private whenever the user has the said channel in store.
Note: I'll update `mattermost-redux` for mobile RN's similar implementation.  However, that change is not necessary for the webapp.
Jira ticket: [MM-10519](https://mattermost.atlassian.net/browse/MM-10519)
> [MM-10519] Fix permission error on channel_converted event

- components/logged_in/logged_in.jsx
- sass/base/_structure.scss
Fix the Centre Channel scroll when using Grammarly in chrome.
Added `channel-view`(has `overflow: hidden;`) class into not only root div but also body, when entering to channel view.
- https://github.com/mattermost/mattermost-server/issues/8839
- [Jira Ticket](https://mattermost.atlassian.net/browse/MM-10664)
> MM-10664: Fix the Centre Channel scroll when using Grammarly in chrome.

- components/formatted_markdown_message.jsx
- tests/components/__snapshots__/formatted_markdown_message.test.jsx.snap
- tests/components/formatted_markdown_message.test.jsx
Adds new component `<FormattedMarkdownMessage>` that can replace all (I think) instances of `<FormattedHTMLMessage>` in Mattermost. 
Example usage:
```jsx
<FormattedMarkdownMessage
id='admin.cluster.foo'
defaultMessage='Cluster {clusterId} is **awesome**! *Please* see <br> the [documentation](http://docs.mattermost.com/deployment/cluster.html).'
values={{
clusterId: '123',
}}
/>
```
... would output:
Cluster 123 is **awesome**! *Please* see 
the [documentation](http://docs.mattermost.com/deployment/cluster.html).
Rules:
* Accepts most markdown, but we'll probably just use the basics (bold, italics, etc)
* To make a normal anchor tag use `[text](url)`
* To make an anchar tag with `target="_blank"` use `[text](!url)` (note the exclamation mark prefix).
n/a
> Adds FormattedMarkdownMessage component.

- components/markdown/index.js
- components/post_markdown/post_markdown.jsx
- tests/components/__snapshots__/post_markdown.test.jsx.snap
- tests/components/post_markdown.test.jsx
The `post.props.channel_mentions` structure sent by the server needed to be passed to the Markdown component to allow merging with the already known channels for linking.
https://mattermost.atlassian.net/browse/MM-10789
> MM-10789: propagate post channel_mentions to Markdown

- nightwatch.json
- tests/e2e/globals.js
- tests/e2e/test.sh
- tests/e2e/tests/3_sidebarLeft/accountSettingsDisplay.action.js
- tests/e2e/tests/3_sidebarLeft/accountSettingsModalPage.element.js
Convert HTML test case into NIghtwatchJS
- https://github.com/mattermost/mattermost-selenium/blob/master/src/test/html/AccountSettingsDisplay.html
Plus,
- add test to Teammate Name Display
- fix other test on recent text/label change
- fix other test setup 
Jira ticket: [MM-10771](https://mattermost.atlassian.net/browse/MM-10771)
> [MM-10771] Add E2E for account settings display

- components/admin_console/admin_definition.jsx
Maximum file size is a `TYPE_NUMBER`.
https://mattermost.atlassian.net/browse/MM-10844
> MM-10844: maximum file size is a TYPE_NUMBER

- components/create_post/create_post.jsx
- tests/components/create_post/create_post.test.jsx
Waiting until the stack is clear before continuing with the execution.
[MM-10647](https://mattermost.atlassian.net/browse/MM-10647)
> MM-10647: Fix for Korean character double post on ctrl+enter.

- sass/layout/_post.scss
It seems like the issue here is that setting `overflow-y` was allowing the post text to sometimes overflow the `post-message` div into the parent div because the parent had `padding` set. IE11 is weird.
In this screenshot, the hovered post caused the scroll bar because of something to do with the line ending in "id." This is how it looks after the change on IE11.
And here's that same post in Chrome to show that this didn't break the [...] menu hover effect
https://mattermost.atlassian.net/browse/MM-10876
> MM-10876 Removed horizontal scrollbar on some posts in IE11

- components/markdown_image.jsx
The previous version of this code only updated post height (which determined whether or not the post is shown as collapsed) after 100ms, so it would be theoretically possible that the post loaded before that happened, causing the timeout to be cancelled and that code to not be called. This should fix that.
https://mattermost.atlassian.net/browse/MM-10706
> MM-10706 Made sure to update post height when image loads

- sass/routes/_admin-console.scss
- sass/utils/_mixins.scss
The error message currently gets truncated at one line, so this allows it to expand nicely to 2 lines. The text is cut off with ellipses on Webkit browsers (ie Chrome, Safari), but it gets cut off a bit more abruptly on other browsers.
Chrome Screenshots:
IE11 Screenshot:
https://mattermost.atlassian.net/browse/MM-10845
> MM-10845 Allowed system console error message to wrap to 2 lines

- components/single_image_view/single_image_view.jsx
- tests/components/__snapshots__/single_image_view.test.jsx.snap
- tests/components/single_image_view.test.jsx
Fix scaling issue of SVG image.
This is also the short term fix for scroll pop issue on SVG images.  Long term fix will be addressed by getting the width and height of SVG image on server side and then simplify the client logic of this `SingleImageView` component.
I have a ticket - https://mattermost.atlassian.net/browse/MM-10834 - which will be part of scroll pop fix for v5.2 roadmap.
Jira ticket: [MM-10834](https://mattermost.atlassian.net/browse/MM-10834)
> [MM-10834] Fix scaling issue of SVG image

- components/team_members_dropdown/team_members_dropdown.jsx
Restore the previous behavior avoiding system admins removing itself from team admin. There was a small boolean logic error.
[MM-10890](https://mattermost.atlassian.net/browse/MM-10890)
> MM-10890: Restore the previous behavior avoiding system admins removing itself from team admin

- components/post_view/combined_system_message/combined_system_message.jsx
- components/post_view/combined_system_message/index.js
- package-lock.json
- package.json
- tests/components/combined_system_message/__snapshots__/combined_system_message.test.jsx.snap
- tests/components/combined_system_message/combined_system_message.test.jsx
The redux changes filter out combined system messages that don't relate to the current user while this makes combined system messages for the current user only show the parts that affect the current user. This only affects users that have join/leave messages turned off in Account Settings.
User adding and removing people:
User being added and removed:
Redux PR: https://github.com/mattermost/mattermost-redux/pull/532
https://mattermost.atlassian.net/browse/MM-10888
> MM-10888 Hide parts of combined system messages that don't affect the current user

- components/suggestion/switch_channel_provider.jsx
Sometimes when using CMD/CTRL+K the users to build the unread dm's haven't yet loaded making the user object undefined, if that is the case the PR just skips it.
https://mattermost.atlassian.net/browse/MM-10878
> Fix Opening the channel switch modal triggers a JS error when user is undefined

- components/post_view/post_list.jsx
When you have posts that aren't shown because they're combined or hidden, you can end up in a scenario where the channel looks mostly empty as in the case described in this ticket. To mitigate that, we now load up to 5 extra pages of posts (technically 10 half pages since we only show half a page each time you load more) to attempt to fill the screen when switching to a channel.
When we add in infinite scrolling, we'll be able to remove the cap since that's just how infinite scrolling works. This isn't a great solution since you can get into some bad scenarios where it just loads dozens of pages of hidden posts, but it's the best I can think of without the server understanding what posts are visible and what are either combined or hidden completely. …
> MM-10812 Attempt to load posts to fill screen

- components/emoji/emoji_list_item/index.js
This doesn't change any functionality, but there was previously a bug where passing an empty user object to `getDisplayNameByUser` caused a null pointer exception (as reported [here](https://github.com/mattermost/mattermost-server/issues/8844)), so I wanted to clarify what's happening here in case since that function has always handled the case of an `undefined` user.
> Clarify logic in EmojiListItem when user isn't loaded

- components/admin_console/admin_definition.jsx
Fix incorrect translation id (produced by [this commit](https://github.com/mattermost/mattermost-webapp/commit/2b85ae63e9c644c10f6eedbd153f2b252251a64d))
N/A
> Fix incorrect translation id

- package-lock.json
- package.json
This is in preparation for an eventual change to stop the server from sending out the full client config to users who aren't logged in 
https://mattermost.atlassian.net/browse/MM-8701
> MM-8701 Get client config after logging in

- components/search_results/index.jsx
- components/search_results/search_results.jsx
- components/search_results_item/search_results_item.jsx
- package-lock.json
- package.json
- tests/components/__snapshots__/search_results_item.test.jsx.snap
- utils/text_formatting.jsx
Since Elasticsearch gives us more detailed matches, we can use those to highlight the matched words without trying to guess for things like wildcard searches
https://mattermost.atlassian.net/browse/MM-6988
- Has server changes (https://github.com/mattermost/mattermost-server/pull/8861)
- Has redux changes (https://github.com/mattermost/mattermost-redux/pull/541)
> MM-6988 Added Elasticsearch-based search result highlighting

- components/permissions_gates/channel_permission_gate/index.js
- tests/components/__snapshots__/permissions_gates.test.jsx.snap
- tests/components/permissions_gates.test.jsx
Check if teamId is empty string before returning permissions as false it is the case for DM and GM
[MM-10915](https://mattermost.atlassian.net/browse/MM-10915)
> MM-10915 Plus sign missing to add more reactions in GM and DM channels

- components/post_view/combined_system_message/combined_system_message.jsx
- components/post_view/combined_system_message/index.js
- tests/components/combined_system_message/combined_system_message.test.jsx
Clean up combined_system_message component
- eliminate async calls that sometimes resolve when the component is unmounted
- get only missing profiles
- let the mattermost-redux handles the profiles (success, failure, store)
~~Note:  This is submitted to master since memory leak encountered on Android RN app is not happening on webapp.  I'll update this once the redux PR (submitted to release-5.0) is merged to master.~~ done update
None but was reported on pre-release:
- https://pre-release.mattermost.com/core/pl/ofbk3xz7jp8u38ckm78usbe5ih
- https://pre-release.mattermost.com/core/pl/ck75xrjispd8mdn4h9edzw1y8c
> Clean up combined_system_message component

- i18n/en.json
Add missing `Icon` to `webrtc.call.icon`.
N/A
> Fix message

- components/navbar/navbar_info_button.jsx
- sass/layout/_headers.scss
- tests/components/navbar/__snapshots__/navbar_info_button.test.jsx.snap
The previous PR for this only changed this in desktop view, so this adds it for mobile view.
https://mattermost.atlassian.net/browse/MM-10873
> MM-10873 Preserve newlines in mobile view channel headers

- components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
The code looks to ensure there is a space between the end of the opengraph text and the expand/contract icon. However, after some refactorings, the &nbsp; in question ended up inside a string, and only conditionally displayed. Simplify all of this with just the necessary {' '} that accomplishes the desired purpose in React.
https://mattermost.atlassian.net/browse/MM-11009
> replace a well-intentioned &nbsp; with a ' ' instead

- components/user_settings/general/user_settings_general.jsx
The wrong event is tracked during submitNickname. A trivial username -> nickname typo
N/A
> Track the nickname when needed, not the username

- tests/components/edit_post_modal.test.jsx
The string "allways" is unknown identifier, while "always" is valid one.
N/A
> Fix allways typo in the edit post modal tests

- components/admin_console/reset_email_modal/reset_email_modal.jsx
Remove the character limit that currently exists in the reset email modal under system console.
https://mattermost.atlassian.net/browse/MM-10974
> [MM-10974] Remove Character Limit in Reset Email Modal

- components/team_selector_modal/team_selector_modal.jsx
In chrome the sort function receive a function that must return a `-1`, `0` or
`1`. If you return a boolean it works fine for any other browser, but in chrome
give you a random order.
Here you can see an explanation of this: https://bugs.chromium.org/p/v8/issues/detail?id=103
[MM-10767](https://mattermost.atlassian.net/browse/MM-10767)
> MM-10767: Fix the ordering for chrome

- components/gif_picker/components/Categories/index.jsx
- components/gif_picker/components/Header/index.jsx
- components/gif_picker/components/SearchBar/index.jsx
- components/gif_picker/components/SearchGrid/SearchGrid.jsx
Because these components were accessing the store directly instead of using the getTheme selector, they were missing out on some backwards compatibility support that the getTheme selector provides.
https://mattermost.atlassian.net/browse/MM-11113
> MM-11113 Used getTheme selector in gif picker

- actions/global_actions.jsx
Fix the redirect to the last opened channel when you go to http://<host>/.
To easy the understanding of the fix, this was broken in the PR #875 fixing
other redirection to last opened channel. The PR changes how is stored the last
opened channel and I'm only propagating the change to the
redirectUserToDefaultTeam function.
[MM-10981](https://mattermost.atlassian.net/browse/MM-10981)
> MM-10981: Fix redirect to last channel http://<host>/ load

- components/user_settings/display/custom_theme_chooser.jsx
- i18n/en.json
There is a typo in the localization files for user.settings.custom_theme.mentionBg
See:
https://github.com/mattermost/mattermost-mobile/pull/1770
> user.settings.custom_theme.mentionBg typo

- selectors/general.js
Fall back to `window.basename` instead of `window.location.origin`, to ensure the subpath is reflected on logout. This ended up being a last minute regression in the PR phase :/
https://mattermost.atlassian.net/browse/MM-11158
> MM-11158: fix subpath logout

- components/sidebar_right/index.js
- components/sidebar_right/sidebar_right.jsx
the function `onShrink` was not even present, this PR fixes the behavior of clicking on the backdrop for the RHS when expanded.
https://mattermost.atlassian.net/browse/MM-11076
> Shrink RHS when clicking on the backdrop

- components/get_android_app/get_android_app.jsx
- components/get_ios_app/get_ios_app.jsx
After the inclusion of "try to auto join by url to a channel if it is
open" the trick done from mobile view to go to the default team (use the
/switch_team url) wasn't working anymore. This fix that problem.
[MM-11163](https://mattermost.atlassian.net/browse/MM-11163)
> MM-11163: Handle mobile view switch_team case

- sass/base/_structure.scss
Fix overflow issue with help pages.
The code i removed was introduced [here](https://mattermost.atlassian.net/browse/MM-11222) to fix Grammarly scroll issue. But I cannot replicate this anymore so, there is a good chance Grammarly might have fixed it on their end
[MM-11222](https://mattermost.atlassian.net/browse/MM-11222)
> [MM-11222] Fix overflow issue on help pages

- components/admin_console/elasticsearch_settings.jsx
For some reason I don't entirely understand, this method was not getting called when it had the same name as the method in the parent class - the parent class method was getting called instead. By renaming it, it is now called as expected and the logic that covers this ticket runs again as it used to.
https://mattermost.atlassian.net/browse/MM-10958
> MM-10958: Fix elasticsearch settings interdependencies in system console

- actions/websocket_actions.jsx
- components/post_profile_picture/post_profile_picture.jsx
- components/post_view/post_list.jsx
- components/sidebar/sidebar.jsx
- components/team_sidebar/team_sidebar_controller.jsx
- components/user_profile.jsx
- plugins/index.js
- plugins/registry.js
- sass/layout/_sidebar-left.scss
- sass/layout/_team-sidebar.scss
- tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
- utils/post_utils.jsx
This PR does a bunch of things:
* Add two sidebar pluggable components
* Add a `deinitialize` function that plugins can implement, for removing event handlers and doing other clean-up. It's called just before a plugin is removed
* Allow ephemeral messages to have their icons overridden (this was a bug where only the name would get overridden)
* Fix new line separator not appearing for messages posted by a bot using your account
* Fixes to WS event handler registration to prevent collisions
* Add ability for plugins to register a reconnect handler, called when the app disconnects then reconnects to the internet
This should be the last webapp PR before we're ready to merge `plugins-2` to master.
> Various plugin updates and fixes

- components/create_post/create_post.jsx
Reverts refactor.
[MM-11225](https://mattermost.atlassian.net/browse/MM-11225)
> MM-11225: Revert refactor.

- components/admin_console/admin_definition.jsx
If changed from the default, the LDAP port was being discarded by the server as it was sent up as a string and not a number.
https://mattermost.atlassian.net/browse/MM-11247
> MM-11247: fix ldap port saving

- stores/emoji_store.jsx
Another casualty of my testing subpath with an incorrect root redirect (that redirected the subpath-less path back into the subpath).
https://mattermost.atlassian.net/browse/MM-11248
> MM-11248: fix custom emoij on subpath

- actions/global_actions.jsx
This PR completes the task of adding support to redirect to the last
visited channel. This add the support to redirect to GMs and DMs in the
last team that you visited.
[MM-10981](https://mattermost.atlassian.net/browse/MM-10981)
> MM-10981: Add support for GMs and DMs on initial redirect

- actions/global_actions.jsx
Fixes back button of permalink error message.
* Use push instead of replace in browser history to
avoid infinite loop redirection for back button in
browser
[MM-11214](https://mattermost.atlassian.net/browse/MM-11214)
> MM-11214 Fix back button for deleted permalinks

- utils/constants.jsx
This PR is related to the Server PR linked below and introduces system as a blacklisted username.
N/A -> https://github.com/mattermost/mattermost-server/pull/9060
> Add System to Nickname Blacklist

- utils/text_formatting.jsx
The `\b` at the end of the regex pattern matches a boundary between a word and non-word character. An underscore is considered a word character, so the pattern wouldn't match a word followed by an underscore.
https://mattermost.atlassian.net/browse/MM-11109
> MM-11109 Properly highlight mentions followed by an underscore

- components/post_view/post/post.jsx
Fixes app crashing when adding a user to the channel via at-mention.  It happened when undefined post is passed into `Post` component.
I'm not particularly sure why but it should have been caught by this [line](https://github.com/mattermost/mattermost-webapp/blob/master/components/post_view/post_list.jsx#L519).
It's very confusing but it's introduced in this commit - https://github.com/mattermost/mattermost-webapp/commit/4cf32681087b86fa4068a5b0921593b36674d2b2
Jira ticket: [MM-11289](https://mattermost.atlassian.net/browse/MM-11289)
> [MM-11289] Fixes app crashing when adding a user to the channel via at-mention

- components/suggestion/switch_channel_provider.jsx
Fix performance regression introduced by #1252. The requests were being sequentially, not in parallel.
> Fix performance regression in channel switcher

- components/post_view/reaction/index.js
- components/post_view/reaction/reaction.jsx
- sass/layout/_post.scss
- tests/components/post_view/__snapshots__/reaction.test.jsx.snap
Apply read only town square rules to reactions in the same way as posts.
Makes the UI behaviour the exact same as for when you don't have permissions to react, which we already support.
https://mattermost.atlassian.net/browse/MM-11172
> MM-11172: Apply read only town square rules to reactions as posts.

- plugins/index.js
- plugins/registry.js
This set of changes supports the automatic extraction of the plugin registry for documentation purposes. 
https://mattermost.atlassian.net/browse/MM-10926
> MM-10926: updated plugin registry documentation

- components/admin_console/admin_definition.jsx
- components/admin_console/message_export_settings.jsx
- i18n/en.json
- tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
Removing the banner text on admin console for new compliance exports
system, and adding a new banner in the old compliance exports system.
[MM-11418](https://mattermost.atlassian.net/browse/MM-11418)
> MM-11418: Channging the admin console banners related to compliance exports

- components/post_view/post_attachment.jsx
- components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
- sass/layout/_webhooks.scss
- tests/components/post_view/__snapshots__/post_attachment.test.jsx.snap
- tests/components/post_view/post_attachment.test.jsx
- utils/utils.jsx
Fix rendering of embedded images with long URLs in message attachment.
Found this bug while working on related bug on RN (MM-11145).
It happened when attachment.text is partially forwarded to Markdown component.  So instead of slicing the attachment.text when it's greater than the cap multilines or text' length, such text is fully rendered on Markdown component and just hide/show when it has overflow (depends on height).  Implementation is similar to long post feature.
See screen capture: 
BEFORE (Broken)
- https://youtu.be/JjcNwIQN8oE
AFTER (Fixed)
- https://youtu.be/6itK3sDsD2w
Jira ticket: [MM-11422](https://mattermost.atlassian.net/browse/MM-11145)
> [MM-11422] Fix rendering of embedded images with long URLs in message attachment

- utils/user_agent.jsx
Show app download page on mobile firefox.
https://github.com/mattermost/mattermost-server/issues/8783
> Detect user-agent for mobile firefox and show app download page

- components/integrations/confirm_integration/confirm_integration.jsx
- i18n/en.json
Opens docs to slash commands in new tab/window.
[MM-11395](https://mattermost.atlassian.net/browse/MM-11395)
> MM-11395: Opens docs to slash commands in new tab.

- actions/user_actions.jsx
This fixes a recently introduced regression in the `addSwitchToEENotification` function that resulted in the webapp breaking while logged out.
None.
> addSwitchToEENotification: don't assume there is a current user

- plugins/index.js
Globals exported onto the window object for use by Webpack must be resolvable as global variables. This forbids, for example, `window['react-redux']`, since Webpack tries to resolve `react - redux` and gets `NaN`.
None.
> tweak plugin webpack externals

- plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx
Fix JS error/warning on MobileChannelHeaderPlug by not requiring props.components.
The error occurred on local dev whenever no plugin component is set for `MobileChannelHeaderButton`.
n/a
> Fix JS error/warning on MobileChannelHeaderPlug by not requiring props.components

- components/admin_console/user_autocomplete_setting.jsx
Autocomplete all users for system console username setting instead of whatever the previous current team was.
https://mattermost.atlassian.net/browse/MM-11331
> MM-11331 Autocomplete all users for system console username setting

- components/file_upload/file_upload.jsx
- components/file_upload/index.js
- i18n/en.json
- plugins/registry.js
- sass/components/_dropdown.scss
- sass/layout/_post.scss
This is experimental. I have not actually written a plugin capable of using this functionality for real. There may be additional hooks required for a properly functioning file upload plugin.
Mattermost demo plugin PR: https://github.com/mattermost/mattermost-plugin-demo/pull/2
> MM-10657 Adding ability for plugin to hook the file upload button.

- actions/user_actions.jsx
Show the banner for licenses without clustering support (E10). The idea
is show it for any not E20 license, I detect the license using the
"Cluster" support, because makes sense in the context of support more
than 10K users.
[MM-11176](https://mattermost.atlassian.net/browse/MM-11176)
> MM-11176: Show the banner for licenses without clustering support (E10)

- plugins/registry.js
In addition to
```js
registry.registerChannelHeaderButtonAction(<ChannelHeaderButtonIcon />, ...);
```
accept:
```js
registry.registerChannelHeaderButtonAction(ChannelHeaderButtonIcon, ...);
```
This brings a symmetry with the other registry functions that only accept the latter form.
None.
> plugins: allow name of react component

- components/suggestion/suggestion_box.jsx
- components/suggestion/suggestion_list.jsx
- stores/suggestion_store.jsx
When having more than one result that matches the term in any suggestion box the selection highlighting was considering all of them but the selection was picking the first match.
This PR aims to allow different results with the same term and pick the selected one.
https://mattermost.atlassian.net/browse/MM-11193
> Allow duplicate terms for suggestion box

- components/analytics/statistic_count.jsx
- sass/routes/_admin-console.scss
- tests/components/analytics/__snapshots__/statistic_count.test.jsx.snap
On languages other than English, this is impossible to have a translation that short (maybe in Chinese?) for daily users, etc. The only solution here is to make the squares larger.
Before:
After:
N/A
> Fix statistics in console when translation too long

- components/create_comment/create_comment.jsx
- components/create_comment/index.js
- components/create_post/create_post.jsx
- components/create_post/index.js
- components/file_attachment_list/file_attachment_list.jsx
- components/file_preview.jsx
- package-lock.json
- package.json
- tests/components/__snapshots__/file_preview.test.jsx.snap
- tests/components/create_comment/create_comment.test.jsx
- tests/components/create_post/create_post.test.jsx
- utils/constants.jsx
- Update file preview to have the fileInfos sorted by "create_at" (if not created at the same time) or by "name"
- sorting of files on FileAttachmentList component is handled by redux store/utility (`makeGetFilesForPost`) so no need to handle the sorting on the component itself
> [MM-10621] Update file preview to have the fileInfos sorted by "create_at" (if not created at the same time) or by "name"

- actions/notification_actions.jsx
- components/post_view/post_body/post_body.jsx
- tests/utils/markdown/remove_markdown.test.jsx
- utils/markdown/remove_markdown.js
- utils/text_formatting.jsx
Stripped markdown on push notification and "commented on".
On "commented on", it's not specified on the ticket but I let it render with emoji and profile pop-over (can easily remove if not expected)
- https://youtu.be/Sg36Gkx4y5w
- https://youtu.be/-VOCC1WwAm4
Jira ticket: [MM-11442](https://mattermost.atlassian.net/browse/MM-11442)
> [MM-11442] Strip markdown on desktop notification and "commented on"

- components/root/root.jsx
Allow users to go to reset password screen on mobile devices as well as there is no way to do it from mobile app
[MM-10924](https://mattermost.atlassian.net/browse/MM-10924)
> [MM-10924] Use reset password screen on web irrespective of device

- components/sidebar/sidebar.jsx
when multiple sections are not present for sidebar it returns div without a key throwing an error
> Fix key for orderedChannelSections component

- tests/utils/channel_utils.test.jsx
- utils/channel_utils.jsx
Channel names displayed in the quick switcher have the current user "subtracted" out of the channel name. Fix the code that does this for group messages to avoid removing parts of other usernames.
https://mattermost.atlassian.net/browse/MM-11053
> MM-11053: improve group channel name subsetting

- actions/post_actions.jsx
Fix JS error on posts.order where posts is undefined
- `PostActions.getPostsBefore` and `PostActions.getPosts` may return a server error (`results.error`) which in that case will make `posts` to be undefined.
Error encountered on pre-release:
none
> Fix JS error on posts.order where posts is undefined

- tests/utils/utils.test.jsx
- utils/utils.jsx
Use event.key to check as well even if event.code fails so it can support different layouts of English keyboards 
[MM-11498](https://mattermost.atlassian.net/browse/MM-11498)
> [MM-11498] Use event.key as well to support different english keyboard layouts

- components/dot_menu/dot_menu.jsx
- tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
Fix JS error on dot menu
~~- submitted to master, then if passed will change base branch to release-5.2~~
> Fix JS error on dot menu

- components/confirm_modal.jsx
So the modal can intercept and can use the enter key to accept the
changes.
follow up of https://github.com/mattermost/mattermost-webapp/pull/1152
> change to keydown

- actions/user_actions.jsx
- components/login/login_controller/login_controller.jsx
- components/root/root.jsx
- components/system_notice/index.js
- components/system_notice/notices.jsx
- components/system_notice/system_notice.jsx
- tests/components/__snapshots__/system_notice.test.jsx.snap
- tests/components/system_notice.test.jsx
####Summary
More customizable approach to the system notices.
Besides I've migrated the "Switch to EE" notification to the new system
of notifications.
[MM-11384](https://mattermost.atlassian.net/browse/MM-11384)
> Re-Submitting: MM-11384: More customizable approach to the system notices

- components/suggestion/channel_mention_provider.jsx
Fixes autocomplete of channel.
Change array index  used for matchedPretext
More ref: https://github.com/mattermost/mattermost-webapp/pull/1441
[MM-11515](https://mattermost.atlassian.net/browse/MM-11515)
> [MM-11515] Fix autocomplete of channels

- components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
- components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
- tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
* use `<a>` instead of `<Link>` for external links
* use `<button>` instead of `<a href="#">` for onClick handlers
https://mattermost.atlassian.net/browse/MM-11584
> MM-11584: fix system console links

- components/sidebar_right_menu/sidebar_right_menu.jsx
More `<Link>` to `<a>` changes. I thought I had grepped for them successfully in the last commit, but failed to search for parameterized `to` values. Hopefully I've found them all this time.
https://mattermost.atlassian.net/browse/MM-11631
> MM-11631: s/Link/a/ for more external links

- i18n/i18n.jsx
- tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
Romanian should be below Portuguese, above Turkish
> Swap order between Romanian and Turkish

- components/system_notice/notices.jsx
Prevents the flashing of the EE upgrade system notice for system admins on non-licensed servers.
https://mattermost.atlassian.net/browse/MM-11689
> MM-11689 Do not show EE upgrade notice if analytics not loaded

- components/dot_menu/dot_menu.jsx
- components/dot_menu/dot_menu_item.jsx
- tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
Adds the correspondent postId as a prop for the `PostDropDownMenuComponent` and as an parameter to `PostDropDownMenuAction` function.
Without the postId the action or the component are basically useless
> Add postId to the PostDropDownMenuAction and Component for plugins

- components/post_view/post_list.jsx
Fix floating timestamp not updating in mobile view.
Cause: This was a regression that was introduced sometime before 4.9 caused by a breaking change in React (around references not returning DOM nodes) that we were aware of but didn't fix in this case.
https://mattermost.atlassian.net/browse/MM-11465
> MM-11465 Fix floating timestamp

- components/admin_console/custom_brand_settings.jsx
Enforce 500 character limit on branding text.
Cause: Old bug, either the help text was updated without changing the functionality or some refactoring in the system console accidentally broke this more than a year ago.
https://mattermost.atlassian.net/browse/MM-11662
> MM-11662 Enforce 500 character limit on branding text

- components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
- components/delete_channel_modal/index.js
- i18n/en.json
**Recreating pull request to make spinmints work properly (hopefully). No changes to code since original PR**
Change View Archive Channels to a new config setting that's off by default.
https://mattermost.atlassian.net/browse/MM-11782
Webapp Changes: https://github.com/mattermost/mattermost-server/pull/9281
> MM-11782: Make archived channels experimental and off by default.

- components/activity_log_modal/activity_log_modal.jsx
- components/activity_log_modal/components/activity_log.jsx
- components/activity_log_modal/components/more_info.jsx
- components/activity_log_modal/index.js
- package-lock.json
- package.json
- tests/components/activity_log_modal.test.jsx
- tests/components/activity_log_modal/__snapshots__/activity_log.test.jsx.snap
- tests/components/activity_log_modal/__snapshots__/more_info.test.jsx.snap
- tests/components/activity_log_modal/activity_log.test.jsx
- tests/components/activity_log_modal/more_info.test.jsx
Refactored `activity_log_modal.jsx` to use Redux and be pure. Also cleaned up the code to make use of ES6 style syntax. Tests have been updated as well.
mattermost/mattermost-server#9092
https://mattermost.atlassian.net/browse/MM-11280
> [MM-11280] Migrate activity_log_modal.jsx to use Redux

- components/rename_channel_modal/rename_channel_modal.jsx
Don't disable channel name field if set to town-square.
In the Channel Rename modal, this should only be disabled if
the name is *already*  town-square before starting to rename
it, not if it gets set to town-square by the user prior to
saving.
https://mattermost.atlassian.net/browse/MM-11649
> MM-11649: Don't disable channel name field if set to town-square.

- components/admin_console/admin_definition.jsx
- components/admin_console/schema_admin_settings.jsx
Sends a client-side telemetry event when telemetry config setting changed in system console.
https://mattermost.atlassian.net/browse/MM-11469
> MM-11469: Create a telemetry event for telemetry config changed.

- components/admin_console/user_autocomplete_setting.jsx
- components/suggestion/at_mention_provider.jsx
- components/suggestion/channel_mention_provider.jsx
- components/suggestion/command_provider.jsx
- components/suggestion/emoticon_provider.jsx
- components/suggestion/search_channel_provider.jsx
- components/suggestion/search_user_provider.jsx
- components/suggestion/suggestion.jsx
- components/suggestion/suggestion_box.jsx
- components/suggestion/switch_channel_provider.jsx
- components/suggestion/switch_team_provider.jsx
- components/suggestion/timezone_provider.jsx
The reason to use focusin and focusout events is that unlike React's focus and blur events, focusin events are called with the element that you switched from and focusout events are called with the element that you switched to. This lets us actually detect when you switch from, for example, the search box to the suggestion list by clicking on it without the whole SuggestionBox component losing focus.
The reason that we need this is because we clear and close the suggestion list when the SuggestionBox loses focus, but that doesn't work when the suggestion list itself gains focus since it would disappear when you click onto it. Previously, it just needed to stay visible for long enough for the click handler on the list item to fire and actually autocomplete a suggestion, and a `setTimeout` …
> Change SuggestionBox to use focusin and focusout events

- PULL_REQUEST_TEMPLATE.md
As we decide in the Developers meeting, we add to the PR template the
check for "Need to be implemented in mobile" to be sure we don't forget
to do or enqueue it.
> Add check for mobile implementation in the PR template

- components/post_view/post_body_additional_content/index.js
- components/post_view/post_body_additional_content/post_body_additional_content.jsx
- tests/components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
Adds ability to preview shortened (ex bitly) links for previewable content including images and youtube links.
[MM-11786](https://mattermost.atlassian.net/browse/MM-11786)
> MM-11786: Loads shortened link previews.

- sass/layout/_team-sidebar.scss
- utils/utils.jsx
So when a plugin adds a font-awesome icon, default to the correct theme color.
https://mattermost.atlassian.net/browse/MM-11444
> MM-11444 Add default theming to icons in the team sidebar

- components/post_view/post_attachment.jsx
- components/post_view/post_message_view/post_message_view.jsx
- components/post_view/show_more/show_more.jsx
- tests/components/post_view/__snapshots__/post_attachment.test.jsx.snap
- tests/components/post_view/__snapshots__/post_message_view.test.jsx.snap
- tests/components/post_view/post_attachment.test.jsx
- tests/components/post_view/post_message_view.test.jsx
- tests/components/post_view/show_more.test.jsx
- tests/plugins/__snapshots__/post_type.test.jsx.snap
This is a follow up change to https://github.com/mattermost/mattermost-webapp/pull/1520 where I missed to consider cases like multiple images.  Thanks @hmhealey for checking! 😄 
Jira ticket: [MM-11422](https://mattermost.atlassian.net/browse/MM-11422)
> Recalculate textContainer height for each image height received

- components/admin_console/plugin_management/plugin_management.jsx
Freeze crashes the page in dev mode if you open the plugin settings with HA enabled.
> Fixing freeze warning.

- root.jsx
Ignore the "ResizeObserver loop limit exceeded" error, because is not a
real error. Happens only in Chrome and makes not sense to show to the
user in Developer mode.
Here is a short explanation: https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded
[MM-11473](https://mattermost.atlassian.net/browse/11473)
> MM-11473: Ignore the not-so-error "ResizeObserver loop limit exceeded"

- components/access_history_modal/access_history_modal.jsx
- components/access_history_modal/index.js
- package-lock.json
- package.json
- tests/components/access_history_modal.test.jsx
Refactored `access_history_modal.jsx` to use Redux and be pure. Also cleaned up the code to make use of ES6 style syntax. Tests have been updated as well.
mattermost/mattermost-server#9089
https://mattermost.atlassian.net/browse/MM-11279
> [MM-11279] Migrate access_history_modal to be pure and use redux

- components/new_channel_flow.jsx
- tests/components/new_channel_flow.test.jsx
When you create a new channel is set a function to be run when the modal
is closed, which redirects you to the new channel. That function wasn't
removed, so it redirects you to the last created channel every time you
cancel a channel creation.
[MM-11805](https://mattermost.atlassian.net/browse/11805)
> MM-11805: Fix strange behavior on exit channel creation modal

- components/search_results/search_results.jsx
Don't show search highlights when switching to pin/flag/mention views.
https://mattermost.atlassian.net/browse/MM-11794
> MM-11794: Don't keep highlighting search terms on flag/pin view.

- sass/components/_dropdown.scss
- sass/layout/_headers.scss
MM-11711 - Inconsistent spacing in channel menu
https://mattermost.atlassian.net/browse/MM-11711
> MM-11711 - Inconsistent spacing in channel menu

- actions/global_actions.jsx
- stores/browser_store.jsx
- utils/constants.jsx
Fixes the issue of showing getApp screen in different scenarios.
At present the way we store the flag for showing app srceen is odd as it store the flag in couple of ways
1. `_unknow___landingPageSeen__`(when user is not logged)
2. `_userId___landingPageSeen__`(when user is logged)
so first time when the skip though it sets the flag(with unknow id) once after logging and refreash webapp checks for flag with userId showing the getApp screen again.
The other problem is how we purge stores on logout in couple of places so the flag is removed from indexDB after logout showing the screen again.
So moving this flag to localStorage similar to other app flags like bannerAnouncement so it is persisted even after logout.
[MM-11798](https://mattermost.atlassian.net/browse/MM-11798)
[Place an '[x]' …
> [MM-11798] Change landingPageSeen flag to localStorage

- i18n/de.json
- i18n/en.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Remove trailing period from the channel purpose when displaying the formatted message in the channel chat. This message is shown when a channel is first created. 
https://mattermost.atlassian.net/browse/MM-11375
> MM-11375: fix period in channel purpose issue

- sass/layout/_team-sidebar.scss
Follow-up to #1611 to set the opacity to 60% by default.
https://mattermost.atlassian.net/browse/MM-11444
> MM-11444 (part 2) Change default plugin sidebar icons opacity

- actions/views/rhs.js
- tests/redux/actions/views/rhs.test.js
- utils/timezone.jsx
when retrieving the timezone to pass to the server during a date flag search (on: before: after:) check user's settings and use their selected timezone if present instead of the browser's timezone
N/A
N/A
> bug fix: use user's timezone setting for search date flags

- components/user_settings/notifications/user_settings_notifications.jsx
When we changed the notification settings to use API v4 and the /api/v4/users/patch endpoint, we never removed the old user_id field that was needed for the /api/v3/users/update_notify route, so we've been writing their ID back into their notify_props for no reason.
> Stop saving user's ID to their NotifyProps

- utils/text_formatting.jsx
I don't know if this is at all possible any more since I couldn't get my local server to return the correct results, but I can certainly see how it would've happened if the server sent back those results. Funnily enough, I'm surprised it didn't fully error when you do this because apparently it's totally fine to call `''.charAt(-1)` in JavaScript (it returns the empty string)
https://mattermost.atlassian.net/browse/MM-11503
> MM-11503 Stopped trying to highlight empty search strings

- components/file_attachment_list/file_attachment_list.jsx
- components/file_attachment_list/index.js
- tests/components/__snapshots__/file_attachment_list.test.jsx.snap
- tests/components/file_attachment_list.test.jsx
Fix order of files in viewing file attachments.
(Previous PRs for this ticket adressed order of file on upload and previews.)
Jira ticket: [MM-10621](https://mattermost.atlassian.net/browse/MM-10621).
> [MM-10621] Fix order of files in viewing file attachments

- components/suggestion/search_channel_provider.jsx
- components/suggestion/switch_channel_provider.jsx
**Note:** This is the "Quick fix" version of the other MM-11725 PRs. I going to make a similar one for RN.
We show archived channels in the Channel Switch modal (and we don't want
that, so this commit filter archived channels there).
In the search `in:` filter autocompletion, we show all open channels
including archived channels (If archived channels are enabled), with
this PR we only show the archived channels if we are members of them.
[MM-11725](https://mattermost.atlassian.net/browse/11725)
> MM-11725: Fix some cases where we show archived channels

- components/dot_menu/dot_menu.jsx
- components/post_view/post_message_view/post_message_view.jsx
- plugins/registry.js
- tests/components/post_view/__snapshots__/post_message_view.test.jsx.snap
- tests/components/post_view/post_message_view.test.jsx
- tests/plugins/__snapshots__/post_type.test.jsx.snap
Update plugin based on hackathon observation - working on [mattermost-plugin-autotranslate](https://github.com/mattermost/mattermost-plugin-autotranslate).
- add PostMessage pluggable at PostMessageView to add an inline message to a post without worrying about formatting/styles of existing post
-  add filter to PostDropdownMenuAction to easily filter out which post to take effect with that action.
~~Note that I've submitted this on top of https://github.com/mattermost/mattermost-webapp/pull/1606 since it's partly related.  Will rebase after it's merged.~~ Said PR is merged and this change has been rebased to master.
none
> Update plugin based on hackathon observation - working on translate plugin

- components/post_view/commented_on/commented_on.jsx
- components/post_view/commented_on/index.js
- components/post_view/post_body/post_body.jsx
- tests/components/post_view/__snapshots__/commented_on.test.jsx.snap
- tests/components/post_view/commented_on.test.jsx
Refactor "commented on..." into its separate component and be tested.  I find it necessary while working on https://github.com/mattermost/mattermost-webapp/pull/1657 where I'd like to test a smaller unit but cannot do it without testing the entire `PostBody`.
none
> Refactor "commented on..." into its separate component and be tested

- components/suggestion/suggestion_box.jsx
Fix JS error when opening keyboard shortcuts modal via CTRL+/ by adding (reverting) delay before calling emitClearSuggestions.
Jira ticket: [MM-11912](https://mattermost.atlassian.net/browse/MM-11912)
> [MM-11912] ~~Add (revert)~~ Set zero delay before calling emitClearSuggestions

- components/admin_console/admin_console.jsx
- components/admin_console/admin_definition.jsx
- components/admin_console/index.js
- components/admin_console/schema_admin_settings.jsx
- tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- tests/components/admin_console/admin_console.test.jsx
- tests/components/admin_console/schema_admin_settings.test.jsx
- utils/constants.jsx
Adding Permissions setting to declarative admin console, and using this
new thing to reintroduce the "EnableAdminOnlyIntegrations" setting in
the "Integrations" config panel.
[MM-11920](https://mattermost.atlassian.net/browse/11920)
> Adding Permissions setting to declarative admin console

- tests/utils/emoticons.test.jsx
- tests/utils/formatting_at_mentions.test.jsx
- utils/emoticons.jsx
- utils/text_formatting.jsx
This bug boils down to it being possible for a token like `$MM_EMOTICON10` to accidentally replace `$MM_EMOTICON1` followed by a `0`. Adding a trailing `$` makes it much more difficult to accidentally break the text formatting that way.
Marking this as DO NOT MERGE in case the ticket gets triaged to 5.3
https://mattermost.atlassian.net/browse/MM-12044
> MM-12044 Add trailing $ to text formatting tokens

- components/emoji_picker/emoji_picker.jsx
- components/emoji_picker/emoji_picker_overlay.jsx
- components/emoji_picker/emoji_picker_tabs.jsx
- components/gif_picker/gif_picker.jsx
- components/rhs_comment/rhs_comment.jsx
- components/rhs_root_post/rhs_root_post.jsx
- tests/components/__snapshots__/edit_post_modal.test.jsx.snap
- tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
- tests/components/create_post/__snapshots__/create_post.test.jsx.snap
- tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
This makes 3 main changes to improve the position of the emoji picker:
1. When the gif picker was added, some of the layout code was duplicated, causing some odd issues like larger-than-intended margins between the picker and the component that controlled it due to having it ran in two different places.
2. Fixed a bug that's existed for a long time where the emoji picker would appear somewhere on the left side of the screen whenever react-bootstrap tried to position the picker along the top of the screen. This is the main fix for this issue and almost every other similar layout issue that we've had in the past.
3. The logic for positioning the emoji picker above or below the [...] menu in a post was updated since it relied on the height of the emoji picker which was changed at some point. …
> MM-11812 Improve positioning of emoji picker

- components/navbar/navbar.jsx
- tests/components/navbar/__snapshots__/navbar.test.jsx.snap
Removing explicit action to close channel menu. The menu "X" icon still
works because behave exactly like if you click anywhere any not-button
part of the menu.
Would be nice to test it in Iphone browser, and IE browser using mobile
mode.
[MM-12020](https://mattermost.atlassian.net/browse/12020)
> MM-12020: Removing explicit action to close channel menu

- utils/utils.jsx
This removes the code that causes permalinked posts and posts made by the current user to use different colours for their the fade out effects on collapsed post attachments. They aren't needed because post attachments always have the same colour background, regardless of the type of post.
https://mattermost.atlassian.net/browse/MM-12042
> MM-12042 Remove different fade out effects for collapsed post attachments

- plugins/index.js
Sometimes, mainly in HA, multiple WS events would tell a client to add the same plugin to the page. This will make sure only a plugin is only added to the page one time.
https://mattermost.atlassian.net/browse/MM-11969
> MM-11969 Prevent plugins scripts being added to the page multiple times

- .eslintrc.json
- tests/utils/markdown/remove_markdown.test.jsx
After updating the dependency for eslint it is expected to have the `plugin:react/recommended` configured in `.eslintrc` and set the specific minor version of React
https://mattermost.atlassian.net/browse/MM-12157
> Set the react configuration for eslint

- components/user_settings/advanced/index.js
- components/user_settings/advanced/join_leave_section/index.js
- components/user_settings/advanced/join_leave_section/join_leave_section.jsx
- components/user_settings/advanced/user_settings_advanced.jsx
- tests/components/user_settings/advanced_tab/__snapshots__/join_leave_section.test.jsx.snap
- tests/components/user_settings/advanced_tab/join_leave_section.test.jsx
- utils/constants.jsx
Move hiding join/leave messages to TE
- remove licensed and EE build check
- add JoinLeaveSection component. (I should submit this to separate PR but it's hard to break it since `AdvancedSettingsDisplay` is not a pure component and is hard to provide necessary tests.)
Note: I'll create separate ticket to refactor the `AdvancedSettingsDisplay` component following this pattern. [UPDATE] --> https://mattermost.atlassian.net/browse/MM-12155
Jira ticket: [MM-11658](https://mattermost.atlassian.net/browse/MM-11658)
> [MM-11658] Move hiding join/leave messages to TE

- tests/utils/formatting_links.test.jsx
- utils/markdown/renderer.jsx
Even with these changes, we won't 100% support relative links because we made the choice at some point to automatically add `http://` to Markdown links so for example `[link](www.google.ca)` links to `http://www.google.ca` instead of `{currentUrl.com/foo}/www.google.ca` as it would otherwise. This should at least fix the case of links like `[link](/foo/bar`)` so that they'll properly link to `{currentUrl.com}/foo/bar`
https://mattermost.atlassian.net/browse/MM-11738
> MM-11738 Support relative Markdown links starting with /

- components/sidebar/sidebar.jsx
- tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
- tests/components/sidebar/sidebar.test.jsx
The original error is:
```
TypeError: 'Symbol(Symbol.toPrimitive)' returned for property 'Symbol(Symbol.toPrimitive)' of object '[object Object]' is not a function
```
which I'm not sure what's causing that after the upgrade of dependencies.
Revert unit test of Sidebar by setting empty string to href whenever the favicon is not of type string.  It's a dirty hack and there might be a proper fix to this but this fix works.  I've tested it for normal favicon (blue icon) and "red" favicon and everything seems to work just fine.
Jira ticket: [MM-11856](https://mattermost.atlassian.net/browse/MM-11856)
> [MM-11856] Revert unit test of Sidebar by setting empty string to href whenever the favicon is not of type string

- components/post_view/post_attachment.jsx
- tests/components/post_view/__snapshots__/post_attachment.test.jsx.snap
Handling slack attachments links to do not reload on permalinks clicks.
[MM-11982](https://mattermost.atlassian.net/browse/MM-11982)
> MM-11982: Fix slack attachments permanlinks click

- components/admin_console/admin_console.jsx
- components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
- components/admin_console/custom_plugin_settings/index.js
- components/admin_console/schema_admin_settings.jsx
Improve the state management for schema admin settings.
Based on the fix of MM-12056, I decide to simplify how
schema_admin_settings work, removing inheritance, and removing the
UNSAFE_complenteWillUpdate method.
In the future the AdminSettings class will be removed, when every single admin panel is using the declarative interface. So the code duplication will be temporary only.
[MM-12056](https://mattermost.atlassian.net/browse/12056)
> MM-12056: Improve the state management for schema admin settings

- components/file_upload/file_upload.jsx
When handleMaxUploadReached() is called from handleLocalFileUploaded(),
event is not passed so e.preventDefault() triggers a TypeError resulting not to invoke onUploadError().
So fix to pass an event argument simply :)
I found it from:
https://deepscan.io/dashboard/#view=project&pid=3171&bid=26245&subview=issues&status=%5B%22fixed%22%5D
N/A
> Fix TypeError of handleMaxUploadReached()

- package-lock.json
- package.json
Getting error in resolving mattermost-redux, bump it to latest
Repro steps:
- delete node_modules or just the mattermost-redux module
- do the `make run`
- observe that the mattermost-redux is not being installed and built accordingly
none
> Getting error in resolving mattermost-redux, bump it to latest

- tests/utils/formatting_at_mentions.test.jsx
- utils/text_formatting.jsx
Fix at mention rendering when multiple at mentions pattern are typed without space in between
Jira ticket: [MM-11883](https://mattermost.atlassian.net/browse/MM-11883)
> [MM-11883] Fix at mention rendering when multiple at mentions pattern are typed without space in between

- Makefile
- build/Jenkinsfile
- package-lock.json
- package.json
I've always found the fact that you can't just `npm install mattermost/mattermost-redux` kind of annoying, but moving the build step to `prepublish` or `prepare` (both are very similar, but `prepare` happens after `prepublish`) instead of `prepublishOnly` so that it triggers automatically on `npm install` should fix that.
This also lets us remove the `.npminstall` files on each repo since we can just check if `node_modules` is up to date rather than creating a new file.
Redux PR: https://github.com/mattermost/mattermost-redux/pull/635
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2135
> Remove .npminstall and don't explicitly build mattermost-redux

- components/edit_post_modal/edit_post_modal.jsx
- tests/components/__snapshots__/edit_post_modal.test.jsx.snap
- tests/components/edit_post_modal.test.jsx
Skip react-bootstrap's modal handling of the escape key to allow our suggestion box to cancel the event correctly when it intercepts it first.
https://mattermost.atlassian.net/browse/MM-11964
> MM-11964: internalize escape key handling on edit post modal

- components/edit_post_modal/edit_post_modal.jsx
- tests/components/edit_post_modal.test.jsx
Focus the textbox as soon as the ref is set so that typing is picked up faster.
QA if you want to give it a quick test that'd be great.
https://mattermost.atlassian.net/browse/MM-3762
Fixes https://github.com/mattermost/platform/issues/4593
> MM-3762 Focus textbox immediately when opening edit modal

- components/access_history_modal/access_history_modal.jsx
- components/admin_console/audits/audits.jsx
- components/audit_table/audit_table.jsx
- components/audit_table/index.js
- tests/components/__snapshots__/access_history_modal.test.jsx.snap
- tests/components/access_history_modal.test.jsx
- tests/components/audit_table/__snapshots__/audit_table.test.jsx.snap
- tests/components/audit_table/audit_table.test.jsx
Changes necessary to make `audit_table.jsx` use redux and be pure. New tests have been added as well.
https://github.com/mattermost/mattermost-server/issues/9090
https://mattermost.atlassian.net/browse/MM-11282
> [MM-11282] Migrate audit_table to use redux and be pure

- sass/base/_typography.scss
Ensuring that CJK characters on IE11 can fallback to `sans-serif`, as the single quotation marks were not recognized by the browser.
Image of occurence can be seen below:
And once single quotation marks were removed:
Note: Japanese characters still look about the same, and whether or not `sans-serif` looks better than the browser default with Chinese characters is questionable, but Korean characters look much sharper and easier to read (It's been an unanimous feedback that the font in the second image looks better than the first for Korean users).
There may be a need to review whether you'd like to add default fonts that are displayed well in each language, or if `sans-serif` is acceptable as seen on the second image shown above.
No open tickets for this.
[Place an '[x]' (no spaces) in …
> Ensuring CJK characters can fallback to sans-serif in IE11

- components/view_image/view_image.jsx
- sass/components/_modal.scss
- tests/components/__snapshots__/view_image.test.jsx.snap
Fix JS error on local dev when opening ViewImageModal.
Have seen this while working on https://github.com/mattermost/mattermost-webapp/pull/1683 and I don't see any difference after removing such `modalClassName`.  The className `modal-image__wrapper` on div container seems to be enough for modal body.
none
> Fix JS error on local dev when opening ViewImageModal

- stores/suggestion_store.jsx
- tests/stores/suggestion_store.test.jsx
The channel mention provider renders a fake "loading" item while waiting for results from the server. If there are no matches, the corresponding empty term ("") incorrectly causes the suggestion box to believe there are terms, and thus attempt to replace the typed text with nothing at all.
See https://github.com/mattermost/mattermost-webapp/blob/047cdb8a0f3b73c650d24cd4f1dc7d2a6ab4be28/components/suggestion/channel_mention_provider.jsx#L140-L143 for the code in question that triggered this behaviour. I opted not to do a wholesale refactoring to model this concept more cleanly.
https://mattermost.atlassian.net/browse/MM-12031
> MM-12031: ignore loading channel mentions

- sass/layout/_sidebar-left.scss
- sass/responsive/_mobile.scss
MM-11647 - Updating sidebar item css
https://mattermost.atlassian.net/browse/MM-11647
> MM-11647 - Updating sidebar item css

- utils/markdown/renderer.jsx
The default implementations of the functions that render table rows and cells pad the HTML with new lines for some reason ([link](https://github.com/mattermost/marked/blob/master/lib/marked.js#L1002)), causing React to complain about the invalid whitespace.
> Fix dev mode warnings caused by Markdown tables

- components/admin_console/admin_definition.jsx
- i18n/en.json
Remove Default Server Language option from the config panel
[MM-12153](https://mattermost.atlassian.net/browse/MM-12153)
> MM-12153: Remove Default Server Language option from the config panel

- tests/components/audit_table/__snapshots__/audit_table.test.jsx.snap
- tests/components/audit_table/audit_table.test.jsx
Use shallow vs. mount to avoid rendering FormattedTime and getting different output on different platforms. (This test was failing for me locally.)
https://mattermost.atlassian.net/browse/MM-11282
> fix audit table snapshots

- components/admin_console/admin_console.jsx
- components/admin_console/admin_definition.jsx
Migrate Admin Console Plugins screens to declarative
[MM-12285](https://mattermost.atlassian.net/browse/MM-12285)
> MM-12285: Migrate Admin Console Plugins screens to declarative

- actions/global_actions.jsx
- actions/views/rhs.js
- components/sidebar_right/index.js
- components/sidebar_right/sidebar_right.jsx
If the RHS is opened and showing pinned posts and we switch channels then the pinned post in the RHS are updated to show the pinned posts of the selected channel
https://mattermost.atlassian.net/browse/MM-9577
> [MM-9577] Update pinned posts list on channel switch

- components/create_comment/create_comment.jsx
- components/create_comment/index.js
- components/create_post/create_post.jsx
- components/create_post/index.js
- tests/components/create_comment/create_comment.test.jsx
- tests/components/create_post/create_post.test.jsx
- tests/utils/post_utils.test.jsx
- utils/post_utils.jsx
Typing when not focused on an input goes to post textbox.
Note that this doesn't work for all non-English characters, though it will work for some.
QA this one is going to need some fairly thorough testing as we want to make sure this isn't going to steal the focus away from the user in situations where it doesn't make sense to. In addition, the linked ticket has a list of common cases to test.
https://mattermost.atlassian.net/browse/MM-12066
> MM-12066 Typing when not focused on an input goes to post textbox

- actions/admin_actions.jsx
- actions/channel_actions.jsx
- actions/global_actions.jsx
- actions/local_storage.jsx
- components/admin_console/system_users/system_users_dropdown.jsx
- components/channel_header/index.js
- components/channel_layout/center_channel/index.js
- components/channel_view/index.js
- components/needs_team/index.js
- components/needs_team/needs_team.jsx
- components/user_settings/advanced/user_settings_advanced.jsx
- selectors/local_storage.js
- selectors/storage.js
- stores/local_storage_store.jsx
- tests/components/needs_team.test.jsx
- tests/stores/local_storage_store.test.jsx
- utils/constants.jsx
These changes persist the last viewed team and channel to localStorage to be reused on login. The values persisted to local storage are keyed by user id to disambiguate multiple users using the same useragent.
I'm not super happy with these changes. A better approach would be to leverage the existing redux-persist subsystem, write these values to Redux, and have it manage the persistence. Unfortunately, on logout we `purge` everything redux-persist manages, so a solution to keep some values around would have to be crafted. One option might be to manually expunge keys, but then we'd want to be extra certain to have cleaned everything up. Another approach might be to persist different roots with whitelisted keys for the persistor that keeps data around after logout. …
> MM-6950: restore last viewed on logout

- components/post_view/commented_on/commented_on.jsx
- tests/components/post_view/__snapshots__/commented_on.test.jsx.snap
- tests/components/post_view/commented_on.test.jsx
* Change from_webhook to string true as that is how API responds
* Use enablePostUsernameOverride for searchTerm
* Use pretext > title > text > falllback for commented on
message
[MM-11854](https://mattermost.atlassian.net/browse/MM-11854)
> MM-11854 Commented on message for different webhook props

- components/announcement_bar/announcement_bar.jsx
- components/do_verify_email/do_verify_email.jsx
* Redirect the user to the default channel if they are logged in when they verify their email
* See [MM-11272](https://mattermost.atlassian.net/browse/MM-12272)
> [MM-12272] Redirect user to default channel if logged in during email verification

- components/file_upload/file_upload.jsx
- components/file_upload/index.js
- plugins/registry.js
- tests/components/file_upload/file_upload.test.jsx
Adds a plugin hook `FilesWillUpload` that allows web app plugins to reject or modify file uploads before they happen.
Example usage that filters out PNGs:
```javascript
registry.registerFilesWillUploadHook(
(files) => {
const newFiles = files.filter((file) => file.type !== 'image/png');
let message;
if (newFiles.length < files.length) {
message = 'One or more of the files was a PNG. These files were rejected by the demo plugin.';
}
return {message, files: newFiles};
}
);
```
I also performed a small amount of refactoring with how we handled pasting images to remove some duplicate code and make it easier to implement the hook. 
https://mattermost.atlassian.net/browse/MM-12263
> MM-12263 Add plugin FilesWillUpload hook

- components/create_comment/create_comment.jsx
- components/create_comment/index.js
- components/create_post/create_post.jsx
- components/create_post/index.js
- components/user_settings/advanced/code_block_ctrl_enter_section/code_block_ctrl_enter_section.jsx
- components/user_settings/advanced/code_block_ctrl_enter_section/index.js
- components/user_settings/advanced/user_settings_advanced.jsx
- i18n/en.json
- tests/components/user_settings/advanced_tab/__snapshots__/code_block_ctrl_enter_section.test.jsx.snap
- tests/components/user_settings/advanced_tab/code_block_ctrl_enter_section.test.jsx
- tests/utils/post_utils.test.jsx
- utils/constants.jsx
- utils/post_utils.jsx
Add feature to send code block on CTRL + ENTER.
@esethna Could you please give this a smoke test if feature is according to specs?  Thanks!
(Note:  Constants will be updated as soon as mattermost-redux PR is merged.)
Jira ticket: [MM-11959](https://mattermost.atlassian.net/browse/MM-11959)
> [MM-11959] Add feature to send code block on CTRL + ENTER

- components/suggestion/switch_channel_provider.jsx
Only show my own archived channels in the channel switcher. When the
viewArchivedChannels settings is active.
[MM-12057](https://mattermost.atlassian.net/browse/MM-12057)
> MM-12057: Only show my own archived channels in the channel switcher

- components/suggestion/suggestion_box.jsx
Fix autocomplete staying open when deleting mention character at beginning of textbox while there is other text present in the textbox.
https://mattermost.atlassian.net/browse/MM-12256
> MM-12556 Fix autocomplete staying open when deleting mention character at beginning of textbox

- components/channel_header/channel_header.jsx
- tests/components/__snapshots__/channel_header.test.jsx.snap
Remove one of two tooltips of unmute icon and replace with aria-label.
Fix:
Jira ticket: [MM-12259](https://mattermost.atlassian.net/browse/MM-12259)
> [MM-12259] Remove one of two tooltips of unmute icon and replace with aria-label

- components/login/login_controller/index.js
- components/login/login_controller/login_controller.jsx
- store/index.js
- tests/components/login/login_controller/__snapshots__/login_controller.test.jsx.snap
- tests/components/login/login_controller/login_controller.test.jsx
This is related to https://github.com/mattermost/mattermost-webapp/pull/1735, in that that feature relies on the `?extra=<...>` parameter being preserved across logout. While I was in here, I fixed a longstanding issue with the login page "flashing" invalid content while the store was resetting. If we detect that we're logging out or the state is not initialized, we render the `<LoadingScreen />` until we are done.
https://mattermost.atlassian.net/browse/MM-12257
> MM-12257 preserve extra on logout

- components/post_view/post_body_additional_content/post_body_additional_content.jsx
Currently if enablelinkpreview is disabled, the redirect_location url is still called
https://mattermost.atlassian.net/browse/MM-12264
https://github.com/mattermost/mattermost-server/issues/9457
https://github.com/mattermost/mattermost-server/issues/9437
server changes https://github.com/mattermost/mattermost-server/pull/9461
> [MM-12264] do not load redirect_location if enablelinkpreview is disabled

- components/create_comment/create_comment.jsx
- components/create_post/create_post.jsx
Fixes upload for last attachment staying in progress state.
This removes an unneeded clear timeout as this is handled by clearing in unmount of the component.
[MM-12403](https://mattermost.atlassian.net/browse/MM-12403)
> MM-12403 Fix uploads fail for last attachment

- tests/components/create_post/create_post.test.jsx
- tests/utils/post_utils.test.jsx
- utils/post_utils.jsx
Fix post textbox on enter, so that:
- on empty message will not insert newline everytime
- on empty message with file attachment will proceed in posting the message (file)
Jira ticket: [MM-12386](https://mattermost.atlassian.net/browse/MM-12386) && [MM-12397](https://mattermost.atlassian.net/browse/MM-12397)
> [MM-12386 && MM-12397] Fix post textbox on enter

- components/sidebar/sidebar_channel/index.js
- components/suggestion/switch_channel_provider.jsx
The draft indicator should not be present if the draft only contains whitespaces
https://mattermost.atlassian.net/browse/MM-12337
> Draft channel indicator to ignore message with whitespaces only

- actions/global_actions.jsx
- components/logged_in/logged_in.jsx
- components/login/login_controller/login_controller.jsx
- components/root/root.jsx
Detecting focus after a page reload across various platforms proved to be unreliable. Better to show the notification even if focussed than miss showing it at all.
https://mattermost.atlassian.net/browse/MM-12447
> MM-12447: stop tracking focus for session expiry

- components/edit_post_modal/edit_post_modal.jsx
- tests/components/edit_post_modal.test.jsx
Unlike the autocomplete overlays, the emoji picker's bootstrap component doesn't support /not/ handling the escape key -- it's hard coded. So if the emoji picker is open when an escape key is detected in the edit post modal, just dismiss the picker without closing the modal.
https://mattermost.atlassian.net/browse/MM-12260
> MM-12260: don't close edit post modal on escape if emoji picker is open

- components/integrations/installed_oauth_app.jsx
- tests/components/integrations/__snapshots__/installed_oauth_app.test.jsx.snap
the  `FormattedMarkdownMessage` was parsing the FAKE secret text so I update to use `FormattedMessage` when need to display the fake secret
Also, improve the copy button to show only when you click to show the secret.
Jira: https://mattermost.atlassian.net/browse/MM-12454
> [MM-12454] fix formated message when have *** and improve the copy text button

- components/admin_console/admin_definition.jsx
- i18n/en.json
Adds ability to determine group membership retrieval strategy. Defaults to the faster strategy, using the `memberOf` overlay. If that overlay is not available on the LDAP instance it can be disabled at a cost of slower syncs.
https://mattermost.atlassian.net/browse/MM-12416
> MM-12416: Adds boolean config for 'memberOf' overlay.

- components/announcement_bar/announcement_bar.jsx
- sass/base/_structure.scss
- sass/components/_announcement-bar.scss
- sass/layout/_sidebar-left.scss
- sass/layout/_sidebar-right.scss
- sass/responsive/_mobile.scss
- sass/routes/_admin-console.scss
- sass/utils/_variables.scss
Over the past two releases, the announcement bar was renamed from error bar, disconnecting some styling rules. Further, the rules themselves seemed not to have been updated when we dropped `position: fixed` styling to properly shift all the affected components. These styling changes now effectively push down all content when the announcement bar is displayed.
https://mattermost.atlassian.net/browse/MM-12523
> MM-12523: fix announcement bar styling

- actions/storage.js
- components/claim/components/email_to_ldap.jsx
- components/claim/components/email_to_oauth.jsx
- components/claim/components/ldap_to_email.jsx
- components/claim/components/oauth_to_email.jsx
- reducers/storage.js
- store/index.js
This addresses two login/logout related bugs that are best reviewed in context:
* Ensure authentication flows explicitly logout to avoid triggering the session expiry flow that clobbers the success message displayed on the login page.
* Preserve all query string parameters on logout, to avoid stripping the `redirect_to` parameter. This became an issue in v5.4 due to the act of dispatching the logout (and triggering all the Redux stores) vs. just calling `Client4.logout()` in the past and effecting a different logout flow.
It's ultimately more explicit now, and thus hopefully simpler in the long run. While in here, I ran into an issue with a reducer assuming a particular action data payload structure connected with logout, and fixed it to handle same. …
> MM-12620/MM-12619 login issues

- components/login/login_controller/login_controller.jsx
- tests/utils/notifications.jsx
- utils/notifications.jsx
- utils/utils.jsx
My recent changes to notifications broke support for Safari, which doesn't yet support the promise style. Fix this, relocating the code so as to enable unit tests that can reset the module and thus clear the internal state. Oh, and get a smiley face for the team ;p
https://mattermost.atlassian.net/browse/MM-12642
> MM-12642: handle callback-style notification API

- components/rhs_root_post/index.js
- components/rhs_thread/rhs_thread.jsx
Fix expand/collapse of image URL at RHS root post by adding the missing `isEmbedVisible` as props from store at the container component.
Jira ticket: [MM-12433](https://mattermost.atlassian.net/browse/MM-12433)
> [MM-12433] Fix expand/collapse of image at RHS root post

- webpack.config.js
- Low entropy in the [hash] may be responsible for some of the issues regarding chunks not being able to be loaded.
> MM-12455 Modifying webpack config to use contenthash instead of hash.

- actions/post_actions.jsx
- components/post_view/reaction/reaction.jsx
- components/rhs_comment/index.js
- components/rhs_comment/rhs_comment.jsx
- components/rhs_root_post/index.js
- components/rhs_root_post/rhs_root_post.jsx
- tests/components/post_view/reaction.test.jsx
(1st PR)
Remove `removeReaction` and `addReaction` at PostActions and use the ones from redux.
Jira ticket: [MM-12582](https://mattermost.atlassian.net/browse/MM-12582)
> [MM-12582] Remove PostActions removeReaction and addReaction and use the ones from redux

- sass/layout/_sidebar-left.scss
Fixes the issues of having channel names bolded when marking unread.
[MM-12493](https://mattermost.atlassian.net/browse/MM-12493)
Before:
After:
> MM-12493 Fix channel names are bolded when you hover over them

- components/suggestion/suggestion_box.jsx
- tests/components/suggestion/suggestion_box.test.jsx
We indirectly attempt to dereference a ref inside a setTimeout, which won't be valid on an unmount race. We correctly handle the return value being undefined from the caller, but not the ref being undefined in the accessor.
Oh, and smiley face for the team ;P
https://mattermost.atlassian.net/browse/MM-12656
> MM-12656: fix racey ref access

- actions/post_actions.jsx
- tests/redux/actions/posts.test.js
The issue of periodically can't save edited post is due to the nature of such stale post (or postId) when doing `setEditingPost`.  During post and then quick edit, setEditingPost is getting the pending post ID and after doing the edit, such pending post ID in store is already gone and replaced by the real post ID from the server.  The post will be null since it's no longer available at the store.  There are also some cases depending on timing that the server is logging error like:
```
{"id":"api.context.404.app_error","message":"Sorry, we could not find the page.","detailed_error":"There doesn't appear to be an api call for the url='/api/v4/posts/5gm4ygap7t8qdpjtcaz46ztkzy:1539347243754/patch'.  Typo? are you missing a team_id or user_id as part of the url?","status_code":404}
``` 
This …
> [MM-12639] Not allow edit for pending post

- components/copy_url_context_menu/copy_url_context_menu.jsx
- components/copy_url_context_menu/index.js
- tests/components/__snapshots__/copy_url_context_menu.test.jsx.snap
- tests/components/copy_url_context_menu.test.jsx
- utils/utils.jsx
Fix "Copy link" (a Desktop-specific feature), removing the magic from `copyToClipboard` that ultimately broke the feature.
https://mattermost.atlassian.net/browse/MM-12513
> MM-12513: fix copy link on desktop

- components/logged_in/logged_in.jsx
- tests/components/logged_in/logged_in.test.jsx
If MFA is required and custom TOS is enabled, a user who needs to enter both flows gets bounced back and forth between the two in a tight loop. Unify the redirect handling into one code block to ensure the cases are handled correctly.
https://mattermost.atlassian.net/browse/MM-12674
> MM-12659: unify LoggedIn redirect handling to avoid races

- .gitignore
- components/team_general_tab/index.js
- components/team_general_tab/team_general_tab.jsx
- package-lock.json
- tests/components/team_general_tab.test.jsx
Switches the update team settings from using the /api/v4/teams endpoint to using the /api/v4/teams/patch endpoint.
https://github.com/mattermost/mattermost-server/issues/9358
- [x ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ x] Ran `make test` to ensure unit and component tests passed
- [x ] Has redux changes https://github.com/mattermost/mattermost-redux/pull/651
> MM-11880 Have Team Settings modal use the patch endpoint instead of the update endpoint

- components/quick_switch_modal/quick_switch_modal.jsx
- tests/components/__snapshots__/quick_switch_modal.test.jsx.snap
Do not restore focus to previous components when closing channel switcher as focus should always go to the main post box.
https://mattermost.atlassian.net/browse/MM-12685
> MM-12685 Do not restore focus to previous components when closing channel switcher

- components/claim/components/email_to_oauth.jsx
- components/login/login_controller/login_controller.jsx
My fix for [MM-12619](https://mattermost.atlassian.net/browse/MM-12619) regressed the OAuth redirect behaviour and prematurely logged the user out instead of keeping them logged in during the flow. To continue to suppress the session expiry notice when changing the auth method, the login controller now handles this transition instead.
https://mattermost.atlassian.net/browse/MM-12680
> MM-12680: fix switching email to oauth

- package-lock.json
- package.json
- sass/styles.scss
- tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap
This PR fixes the UI and JS errors for the Add Members modal and any other component that was using the MultiSelect
`react-select` 2.0.0 has breaking changes and another ticket was created https://mattermost.atlassian.net/browse/MM-12707 to update the dependency accordingly.
https://mattermost.atlassian.net/browse/MM-12570
> revert react-select dependency update

- components/user_settings/advanced/user_settings_advanced.jsx
- i18n/en.json
Fix formatting user setting help text to remove "refresh" requirement since it appears to be no longer required.
https://mattermost.atlassian.net/browse/MM-12539
> MM-12539: Fix formatting user setting help text.

- components/post_markdown/system_message_helpers.jsx
- tests/components/__snapshots__/post_markdown.test.jsx.snap
This PR ensures that system messages will render `@{username}` so that you can click the username and see the username popover.
From what I can tell, the check for the `@` symbol might be overkill but I thought it would be better to have it than not.
[JIRA](https://mattermost.atlassian.net/browse/MM-11675) / [#9503](https://github.com/mattermost/mattermost-server/issues/9503)
> [MM-11675] Username popover on all system messages

- .eslintrc.json
Modify the ESLint setups to allow .js ext for React component file.
@saturninoabril noticed me change about JavaScript filename extensions in https://github.com/mattermost/mattermost-webapp/pull/1666#pullrequestreview-163366241, but the ESLint settings does not allow `.js` for react yet.
> Modify the ESLint config to allow .js ext for React component file

- actions/global_actions.jsx
- actions/post_actions.jsx
- actions/post_utils.js
- actions/websocket_actions.jsx
- stores/channel_store.jsx
- tests/redux/actions/post_actions.test.js
- tests/redux/actions/post_utils.test.js
- tests/redux/actions/posts.test.js
- utils/constants.jsx
Migrate PostActions.handleNewPost to redux actions.
Affected Areas:
Receiving new post via websocket, send ephemeral post.
@DHaussermann @lindy65 May I request for your smoke tests? This could be tested by:
- sending `/leave` command at reply thread --> should see ephemeral post that such command is not supported on thread view
- at-mention a user that's not member of a channel --> should see ephemeral post to add that use to a channel
- have 2 users on different browser, viewing different channel or team.  If user A post, user B should see dot (*) on team name if it's posted on different team, or see a mention badge if it's a at-mention.
Jira ticket: [MM-12582](https://mattermost.atlassian.net/browse/MM-12582) && [MM-12745](https://mattermost.atlassian.net/browse/MM-12745)
> [MM-12582 & MM-12745] Migrate PostActions.handleNewPost to redux actions

- actions/channel_actions.jsx
- actions/global_actions.jsx
- actions/views/channel.js
- components/channel_layout/channel_identifier_router/channel_identifier_router.jsx
- components/leave_private_channel_modal/index.js
- components/leave_private_channel_modal/leave_private_channel_modal.jsx
- components/more_channels/index.js
- components/more_channels/more_channels.jsx
- components/navbar/index.js
- components/navbar/navbar.jsx
- tests/components/__snapshots__/leave_private_channel_modal.test.jsx.snap
- tests/components/__snapshots__/more_channels.test.jsx.snap
- tests/components/leave_private_channel_modal.test.jsx
- tests/components/more_channels.test.jsx
- tests/components/navbar/navbar.test.jsx
Migrates the channel actions joinChannel and leaveChannel to redux (this PR is on top of #1895) the relevant commit is [98e08ce](https://github.com/mattermost/mattermost-webapp/pull/1898/commits/98e08ce694d69c6484aeac9f6728299228251afa)
* Leave public and private channels using the channel menu
* Join new channels from the more channels modal
https://mattermost.atlassian.net/browse/MM-12693
> Migrate ChannelActions joinChannel and leaveChannel to redux

- actions/channel_actions.jsx
`setChannelAsRead` action was not used anywhere in the code base
https://mattermost.atlassian.net/browse/MM-12699
> Remove unused legacy setChannelAsRead action

- tests/setup.js
This fixes the warnings when running unit test,
```
(node:9618) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_location' of null
at Window.get location [as location] (/Users/nnn/go/src/github.com/mattermost/mattermost-webapp/node_modules/jsdom/lib/jsdom/browser/Window.js:223:79)
at getBasePath (/Users/nnn/go/src/github.com/mattermost/mattermost-webapp/selectors/general.js:33:36)
```
none
> Fix Jest warning of "Cannot read property '_location' of null"

- actions/post_actions.jsx
Same as #1925 but for post_actions.jsx.
> Remove flux store usages from post_actions.jsx

- components/channel_layout/channel_identifier_router/actions.js
- components/channel_layout/channel_identifier_router/channel_identifier_router.jsx
- components/channel_layout/channel_identifier_router/index.js
This mainly entailed turning the functions that were acting similar to action creators into actual redux action creators. I split out the actions into their own file as well.
QA, can you regression test loading the app at different team and channel URLs? For example loading to a DM using the `/teamname/messages/@username` and other similar URLs. 
https://mattermost.atlassian.net/browse/MM-12662
> MM-12662 Remove flux store usages from ChannelIdentifierRouter
