mattermost/mattermost-webapp

sass/responsive/_mobile.scss

Cherry pick of #4155 on release-5.17.
- #4155: MM-19936 - Updating close button spacing mobile

Automated cherry pick of #4155

---

e2e/cypress.json
e2e/cypress/support/storybook_commands.js

Update storybookUrl to easily override with the one being published at https://alpha-storybook.devops.mattermost.com/master/index.html
Ref: https://github.com/mattermost/mattermost-shared-pipelines/pull/39
Jira ticket: [MM-19657](https://mattermost.atlassian.net/browse/MM-19657)

Update storybookUrl to easily override for daily E2E 

---

components/profile_picture.jsx
components/user_profile/user_profile.jsx

Manual Cherry pick of https://github.com/mattermost/mattermost-webapp/pull/4142,
Had to take out typescript specifics to the changes for `profile_picture.jsx` given that it was already `.tsx` in master and was having conflicts.

Manual cherry pick of MM-19908 - Fixed ProfilePopover not closing on SendMessage

---

README.md

Fix out dated twitter link
No ticket

[No Ticket] Update Twitter link in README

---

components/__snapshots__/size_aware_image.test.jsx.snap
components/size_aware_image.jsx
sass/layout/_markdown.scss

Cherry pick of #4164 on release-5.17.
- #4164: MM-19909 Fix for scroll pop with markdown images

Automated cherry pick of #4164

---

components/create_comment/__snapshots__/create_comment.test.jsx.snap
components/create_comment/create_comment.jsx
sass/layout/_post.scss
sass/layout/_sidebar-right.scss
sass/responsive/_mobile.scss
sass/utils/_flex.scss

MM-19862 - Updating post error css RHS
https://mattermost.atlassian.net/browse/MM-19862
**Mobile**

MM-19862 - Updating post error css RHS

---

sass/components/_files.scss

MM-19958 - Updating file thumbnail css (IE Fix)
https://mattermost.atlassian.net/browse/MM-19958

MM-19958 - Updating file thumbnail css (IE Fix)

---

sass/components/_files.scss

Cherry pick of #4180 on release-5.17.
- #4180: MM-19958 - Updating file thumbnail css (IE Fix)

Automated cherry pick of #4180

---

components/post_view/channel_intro_message/channel_intro_message.jsx

MM-19757 - Updating heading for channel intro
https://mattermost.atlassian.net/browse/MM-19757
Fixes the issue:

MM-19757 - Updating heading for channel intro

---

components/invitation_modal/__snapshots__/invitation_modal_confirm_step.test.jsx.snap
components/invitation_modal/invitation_modal_confirm_step.jsx

https://mattermost.atlassian.net/browse/MM-18014

[MM-18014] Hide back button on successful invites

---

sass/responsive/_mobile.scss

MM-19936 - Updating close button
https://mattermost.atlassian.net/browse/MM-19936

MM-19936 - Updating close button

---

actions/global_actions.jsx
actions/global_actions.test.js
components/error_page/error_page.tsx

Fix redirections on empty teams for guests users
[MM-20152](https://mattermost.atlassian.net/browse/MM-20152)

Fix redirections on empty teams

---

components/create_comment/__snapshots__/create_comment.test.jsx.snap
components/create_comment/create_comment.jsx
sass/layout/_post-right.scss
sass/responsive/_mobile.scss

MM-20072 - Updating comment box css
https://mattermost.atlassian.net/browse/MM-20072

MM-20072 - Updating comment box css

---

actions/global_actions.test.js

Cherry pick of #4227 on release-5.17.
- #4227: Linting global actions

Automated cherry pick of #4227

---

components/channel_members_dropdown/channel_members_dropdown.jsx
components/channel_members_dropdown/channel_members_dropdown.test.jsx
components/channel_members_dropdown/index.js
utils/utils.jsx

Refactors the display logic in `components/channel_members_dropdown/channel_members_dropdown.jsx`. As part of the refactoring, I also noticed MM-20039 bug which is addressed within the same PR (Line 73 and 83 in `components/channel_members_dropdown/channel_members_dropdown.jsx` address the bug).
https://mattermost.atlassian.net/browse/MM-19490
Also addresses https://mattermost.atlassian.net/browse/MM-20039 bug

[MM-19490][MM-20039] Refactor Complex Display Logic

---

components/channel_header/channel_header.js

Cherry pick of #4191 on release-5.17.
- #4191: Fixed attaching Guest label by ordered display name in

Automated cherry pick of #4191

---

components/__snapshots__/size_aware_image.test.jsx.snap
components/size_aware_image.jsx
sass/layout/_markdown.scss

Cherry pick of #4206 on release-5.17.
- #4206: MM-20151 Fix for svg console error about width property

Automated cherry pick of #4206

---

sass/responsive/_mobile.scss

Cherry pick of #4215 on release-5.17.
- #4215: MM-19936 - Updating close button

Automated cherry pick of #4215

---

sass/components/_files.scss

MM-20072 - Fixing file thumbnail css
https://mattermost.atlassian.net/browse/MM-20182

MM-20072 - Fixing file thumbnail css

---

sass/components/_files.scss

Cherry pick of #4235 on release-5.17.
- #4235: MM-20072 - Fixing file thumbnail css

Automated cherry pick of #4235

---

actions/global_actions.jsx
actions/global_actions.test.js

Fixing redirection on leave channel
[MM-20186](https://mattermost.atlassian.net/browse/MM-20186)

Fixing redirection on leave channel

---

actions/global_actions.jsx
actions/global_actions.test.js

Cherry pick of #4234 on release-5.17.
- #4234: Fixing redirection on leave channel
/cc  @jespino

Automated cherry pick of #4234

---

components/more_direct_channels/index.js

fixed profile ordering
Fixes https://mattermost.atlassian.net/browse/MM-18186

MM-18186 - Direct Messages filtered search results not in alphabetical order

---

components/post_view/post/post.jsx

This click handler got removed by mistake during a merge
https://mattermost.atlassian.net/browse/MM-20159

MM-20159 Re-add post click handler

---

sass/layout/_headers.scss

MM-20019 - Updating markdown text in header
https://mattermost.atlassian.net/browse/MM-20019

MM-20019 - Updating markdown text in header

---

e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
e2e/cypress/integration/account_settings/general/nickname_spec.js
e2e/cypress/integration/channel/channel_mention_autocomplete_spec.js
e2e/package-lock.json
e2e/package.json

- Update Cypress to 3.1.6
- Fix some of the failing E2E tests
none

Update Cypress to 3.6.1 and fix failing E2E

---

components/admin_console/__snapshots__/admin_console.test.jsx.snap
components/admin_console/admin_console.jsx
components/admin_console/admin_console.test.jsx
components/admin_console/index.js

Cherry pick of #4208 on release-5.18.
- #4208: proper redirect from admin console
/cc  @reflog

Automated cherry pick of #4208

---

e2e/cypress/integration/channel/edit_message_spec.js
e2e/cypress/integration/channel/header_spec.js
e2e/cypress/integration/channel/message_bullets_spec.js

Fix failing E2E test at integration/channel

Fix failing E2E test at integration/channel

---

components/channel_notifications_modal/components/__snapshots__/describe.test.jsx.snap
components/channel_notifications_modal/components/describe.jsx
i18n/en.json

Cherry pick of #4143 on release-5.18.
- #4143: Building properly the notification level string
/cc  @jespino

Automated cherry pick of #4143

---

e2e/cypress/integration/login/login_spec.js

- Remove duplicated assertion
- Make use of `and` to not duplicate selectors

Refactor login spec

---

components/error_page/__snapshots__/error_message.test.tsx.snap
components/error_page/error_message.test.tsx
components/error_page/error_message.tsx
components/error_page/error_page.tsx
i18n/en.json

Cherry pick of #4194 on release-5.18.
- #4194: added new message for guests with no channels
/cc  @reflog

Automated cherry pick of #4194

---

components/invitation_modal/invitation_modal.jsx

Cherry pick of #4276 on release-5.18.
- #4276: Fix invitation modal back buton (bad merge resolution)
/cc  @jespino

Automated cherry pick of #4276

---

sass/responsive/_mobile.scss
sass/responsive/_tablet.scss

MM-20246 - Updating UI Defect on compact view
https://mattermost.atlassian.net/browse/MM-20246

MM-20246 - Updating UI Defect on compact view

---

components/analytics/format.test.tsx
components/analytics/format.tsx
components/analytics/system_analytics/system_analytics.jsx

Synchronize date ranges on graphs
Fixes https://mattermost.atlassian.net/browse/MM-19242

MM-19242 - Reporting > Site Statistics: Line graphs show different dates

---

sass/layout/_sidebar-right.scss
sass/responsive/_tablet.scss

MM-20248 - Updating RHS expansion css
https://mattermost.atlassian.net/browse/MM-20248

MM-20248 - Updating RHS expansion css

---

sass/layout/_markdown.scss

MM-20276 - Updating wrap for codeblock
https://mattermost.atlassian.net/browse/MM-20276

MM-20276 - Updating wrap for codeblock

---

sass/components/_videos.scss

MM-20264 - Fixing youtube crop in RHS
https://mattermost.atlassian.net/browse/MM-20264

MM-20264 - Fixing youtube crop in RHS

---

sass/components/_videos.scss

Cherry pick of #4281 on release-5.18.
- #4281: MM-20264 - Fixing youtube crop in RHS

Automated cherry pick of #4281

---

sass/layout/_sidebar-right.scss
sass/responsive/_tablet.scss

Cherry pick of #4280 on release-5.18.
- #4280: MM-20248 - Updating RHS exapnsion css

Automated cherry pick of #4280

---

sass/layout/_markdown.scss

Cherry pick of #4285 on release-5.18.
- #4285: MM-20276 - Updating wrap for codeblock

Automated cherry pick of #4285

---

e2e/cypress/integration/interactive_dialog/full_dialog_spec.js

Cherry pick of #4295 on release-5.18.
- #4295: Fixed Interactive Dialog tests
/cc  @srkgupta

Automated cherry pick of #4295

---

components/admin_console/team_channel_settings/channel/list/index.js

Omits deleted (aka archived) channels from the channels list.
https://mattermost.atlassian.net/browse/MM-19796

MM-19796: Omit deleted (aka archived) channels from the channels list.

---

components/dot_menu/dot_menu.jsx

Cherry pick of #4294 on release-5.18.
- #4294: Fixed setting openUp

Automated cherry pick of #4294

---

components/member_list_channel/member_list_channel.jsx

Cherry pick of #4242 on release-5.18.
- #4242: MM-20180 Fix search in channel members modal
/cc  @Pomyk

Automated cherry pick of #4242

---

components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
components/invitation_modal/index.js
components/invitation_modal/index.test.jsx
components/invitation_modal/invitation_modal.jsx
components/invitation_modal/invitation_modal.test.jsx
components/invitation_modal/invitation_modal_guests_step.jsx
components/invitation_modal/invitation_modal_guests_step.test.jsx

When inviting guest users, the channel field now autocompletes on all the team's public channels.
https://mattermost.atlassian.net/browse/MM-18941

[MM-18941] Search public channels when inviting guest users

---

components/admin_console/plugin_management/plugin_management.jsx

Cherry pick of #4268 on release-5.18.
- #4268: MM-20324 - Plugin upload should not be enabled before

Automated cherry pick of #4268

---

utils/markdown/renderer.jsx
utils/syntax_highlighting.tsx

Cherry pick of #4291 on release-5.18.
- #4291: Fix code preview on attachments
/cc  @jespino

Automated cherry pick of #4291

---

actions/websocket_actions.jsx
components/removed_from_channel_modal/index.js

Cherry pick of #4270 on release-5.17.
- #4270: Fixing leave channel when another window is open
/cc  @jespino

Automated cherry pick of #4270

---

components/channel_header/channel_header.js

Cherry pick of #4269 on release-5.18.
- #4269: Focus the Search Bar on small desktop mode when

Automated cherry pick of #4269

---

components/admin_console/admin_definition.jsx
i18n/en.json

Promote archived channels to Beta.
PM sign-off on promotion: https://community.mattermost.com/core/pl/j8driu8totgxdcbd7gqe8tygiy
No ticket
N/A
N/A

Promote archived channels to Beta

---

e2e/cypress/integration/channel/mark_as_unread_spec.js
e2e/cypress/support/ui_commands.js

Cherry pick of #4243 on release-5.18.
- #4243: MM-19922 Add E2E tests for Mark as Unread
/cc  @hmhealey

Automated cherry pick of #4243

---

components/admin_console/system_user_detail/team_list/team_row.jsx
components/admin_console/system_user_detail/team_list/team_row.scss

Cherry pick of #4305 on release-5.18.
- #4305: System console > User screen, Team Membership layout is

Automated cherry pick of #4305

---

components/admin_console/jobs/__snapshots__/table.test.jsx.snap
components/create_comment/__snapshots__/create_comment.test.jsx.snap
components/create_comment/create_comment.jsx
sass/layout/_post-right.scss
sass/layout/_sidebar-right.scss

MM-20609 - Updating sidebar css
https://mattermost.atlassian.net/browse/MM-20609
**Screenshots**

MM-20609 - Updating sidebar css

---

components/admin_console/admin_definition.jsx
i18n/en.json

Cherry pick of #4283 on release-5.18.
- #4283: Promote archived channels to Beta

Automated cherry pick of #4283

---

components/widgets/badges/badges_spec.js
components/widgets/popover/popover_spec.js

Fix failing E2E tests on widgets and move test next to component

Fix failing E2E tests on widgets and move test next to component

---

sass/base/_css_variables.scss
sass/layout/_sidebar-left.scss
sass/layout/_team-sidebar.scss
utils/utils.jsx

Cherry pick of #4256 on release-5.18.
- #4256: Fixing styles using css variables and initializing them
/cc  @jespino

Automated cherry pick of #4256

---

components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
components/dot_menu/dot_menu.jsx
components/dot_menu/dot_menu.test.jsx
components/dot_menu/dot_menu_empty.test.jsx
components/dot_menu/dot_menu_mobile.test.jsx
components/dot_menu/index.js

Cherry pick of #4311 on release-5.18.
- #4311: MM-20178 Fix unnecessary divider in DotMenu
/cc  @hmhealey

Automated cherry pick of #4311

---

components/widgets/menu/menu.scss
components/widgets/menu/menu_items/menu_item.scss

MM-20648 - Updating dropdown css
https://mattermost.atlassian.net/browse/MM-20648

MM-20648 - Updating dropdown css

---

e2e/cypress/support/ui_commands.js

This PR simply makes use of a function's parameter that was defined but never used.

Make use of parameter that was never used

---

components/widgets/menu/menu.scss
components/widgets/menu/menu_items/menu_item.scss

Cherry pick of #4317 on release-5.18.
- #4317: MM-20648 - Updating dropdown css

Automated cherry pick of #4317

---

package-lock.json
package.json

Updates Redux commit ref.

---

components/widgets/modals/full_screen_modal.scss

Cherry pick of #4351 on release-5.18.
- #4351: MM-20621 - Updating z-index for fullscreen modals

Automated cherry pick of #4351

---

components/view_image/__snapshots__/view_image.test.jsx.snap
components/view_image/view_image.jsx
sass/components/_modal.scss
sass/responsive/_tablet.scss

MM-20657 - Updating code modal preview css
https://mattermost.atlassian.net/browse/MM-20657

MM-20657 - Updating code modal preview css

---

components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
components/user_settings/notifications/email_notification_setting/email_notification_setting.test.jsx
components/user_settings/notifications/index.js
components/user_settings/notifications/user_settings_notifications.jsx
i18n/en.json

Update to email notifications helper text
https://mattermost.atlassian.net/browse/MM-19896
Has mobile changes (https://github.com/mattermost/mattermost-mobile/pull/3614)

MM-19896 Correct helper text on Email Notifications

---

components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
components/user_settings/notifications/email_notification_setting/email_notification_setting.test.jsx
components/user_settings/notifications/index.js
components/user_settings/notifications/user_settings_notifications.jsx
i18n/en.json

Cherry pick of #4349 on release-5.18.
- #4349: MM-19896 Correct helper text on Email Notifications
/cc  @enahum

Automated cherry pick of #4349

---

components/view_image/__snapshots__/view_image.test.jsx.snap
components/view_image/view_image.jsx
sass/components/_modal.scss
sass/responsive/_tablet.scss

Cherry pick of #4334 on release-5.18.
- #4334: MM-20657 - Updating code modal preview css

Automated cherry pick of #4334

---

components/admin_console/group_settings/__snapshots__/group_row.test.jsx.snap
components/admin_console/group_settings/group_row.jsx
components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.jsx.snap
components/admin_console/group_settings/groups_list/groups_list.jsx
components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.jsx.snap
components/admin_console/team_channel_settings/channel/list/channel_list.jsx
components/admin_console/team_channel_settings/group/__snapshots__/group_users.test.jsx.snap
components/admin_console/team_channel_settings/group/group_list.jsx
components/admin_console/team_channel_settings/group/group_users.jsx
components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.jsx.snap
components/admin_console/team_channel_settings/team/list/__snapshots__/team_row.test.jsx.snap
components/admin_console/team_channel_settings/team/list/team_list.jsx
components/admin_console/team_channel_settings/team/list/team_row.jsx
sass/components/_groups.scss

MM-20639 - Updating LDAP CSS
https://mattermost.atlassian.net/browse/MM-20639

MM-20639 - Updating LDAP CSS

---

components/admin_console/group_settings/__snapshots__/group_row.test.jsx.snap
components/admin_console/group_settings/group_row.jsx
components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.jsx.snap
components/admin_console/group_settings/groups_list/groups_list.jsx
components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.jsx.snap
components/admin_console/team_channel_settings/channel/list/channel_list.jsx
components/admin_console/team_channel_settings/group/__snapshots__/group_users.test.jsx.snap
components/admin_console/team_channel_settings/group/group_list.jsx
components/admin_console/team_channel_settings/group/group_users.jsx
components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.jsx.snap
components/admin_console/team_channel_settings/team/list/__snapshots__/team_row.test.jsx.snap
components/admin_console/team_channel_settings/team/list/team_list.jsx
components/admin_console/team_channel_settings/team/list/team_row.jsx
sass/components/_groups.scss

Cherry pick of #4362 on release-5.18.
- #4362: MM-20639 - Updating LDAP css

Automated cherry pick of #4362

---

NOTICE.txt

Cherry pick of #4342 on release-5.18.
- #4342: Update NOTICE.txt
/cc  @amyblais

Automated cherry pick of #4342

---

actions/websocket_actions.jsx

Cherry pick of #4338 on release-5.18.
- #4338: Load team roles when receiving a member role

Automated cherry pick of #4338

---

sass/components/_modal.scss

Cherry pick of #4316 on release-5.18.
- #4316: Fixing more channels modal dropdown text color
/cc  @jespino

Automated cherry pick of #4316

---

utils/text_formatting.jsx
utils/text_formatting.test.jsx

Excludes the search flags from the highlighted results.
https://mattermost.atlassian.net/browse/MM-19487

[MM-19487] Excludes negative filters from the search highlighs

---

utils/text_formatting.jsx
utils/text_formatting.test.jsx

Cherry pick of #4374 on release-5.18.
- #4374: Excludes negative filters from the search

Automated cherry pick of #4374

---

components/file_preview/__snapshots__/file_progress_preview.test.jsx.snap
components/file_preview/file_progress_preview.jsx
sass/components/_files.scss

Fixes file upload progress bar to match actual percentage completed. 
https://mattermost.atlassian.net/browse/MM-20793

MM-20793 Fixing file upload progress bar.

---

.circleci/config.yml

Update circleci context and add new s3 buckets

update context and change s3 buckets

---

components/file_preview/__snapshots__/file_progress_preview.test.jsx.snap
components/file_preview/file_progress_preview.jsx
sass/components/_files.scss

Cherry pick of #4383 on release-5.18.
- #4383: Fixing file upload progress bar.

Automated cherry pick of #4383

---

components/suggestion/suggestion_box.jsx
components/suggestion/suggestion_list.jsx
components/textbox/textbox.jsx
utils/constants.jsx

Cherry pick of #4360 on release-5.18.
- #4360: MM-20310 - Updating suggestion list max height

Automated cherry pick of #4360

---

components/searchable_channel_list.jsx
sass/components/_modal.scss

MM-20768 - Updating channel dropdown css
https://mattermost.atlassian.net/browse/MM-20768

MM-20768 - Updating channel dropdown css

---

components/searchable_channel_list.jsx
sass/components/_modal.scss

Cherry pick of #4397 on release-5.18.
- #4397: MM-20768 - Updating channel dropdown css

Automated cherry pick of #4397

---

plugins/registry.js

Cherry pick of #4372 on release-5.18.
- #4372: MM-20749: restrict post menu nesting

Automated cherry pick of #4372

---

components/admin_console/reset_email_modal/reset_email_modal.jsx
components/admin_console/reset_password_modal/reset_password_modal.jsx
components/change_url_modal/__snapshots__/change_url_modal.test.jsx.snap
components/change_url_modal/change_url_modal.jsx
components/convert_channel_modal/convert_channel_modal.jsx
components/tutorial/tutorial_intro_screens/__snapshots__/tutorial_intro_screen.test.jsx.snap
components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx
components/user_settings/import_theme_modal.jsx

This PR solves accessibility issues related to tabIndex. I did thorough testing on my browser and when removing the tabIndex from components, where it was > 0 previously helped improve the score.
Fixes https://github.com/mattermost/mattermost-server/issues/13198

[GH-13198] Improve WCAG score related to tabIndex on modals

---

components/admin_console/schema_admin_settings.jsx

Cherry pick of #4414 on release-5.18.
- #4414: Fixing error handling for schema admin settings
/cc  @jespino

Automated cherry pick of #4414

---

components/admin_console/system_users/system_users.jsx
components/admin_console/system_users/system_users.test.jsx

Cherry pick of #4408 on release-5.18.
- #4408: Remove erroneous parameter for debounce
/cc  @jespino

Automated cherry pick of #4408

---

components/rhs_thread/rhs_thread.jsx

MM-20181 - Removing vertical scrollbar from css
https://mattermost.atlassian.net/browse/MM-20181

MM-20181 - Removing vertical scrollbar from css

---

components/backstage/components/backstage_list.jsx
components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap
components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
components/integrations/installed_incoming_webhook.jsx
components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap
components/integrations/installed_oauth_app/installed_oauth_app.jsx
components/integrations/installed_outgoing_webhook.jsx

MM-19942 - Updating backstage url and help css
https://mattermost.atlassian.net/browse/MM-19942

MM-19942 - Updating backstage url and help css

---

components/backstage/components/backstage_list.jsx
components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap
components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
components/integrations/installed_incoming_webhook.jsx
components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap
components/integrations/installed_oauth_app/installed_oauth_app.jsx
components/integrations/installed_outgoing_webhook.jsx

Cherry pick of #4401 on release-5.18.
- #4401: MM-19942 - Updating backstage url and help css

Automated cherry pick of #4401

---

components/rhs_thread/rhs_thread.jsx

Cherry pick of #4405 on release-5.18.
- #4405: MM-20181 - Removing vertical scrollbar from css

Automated cherry pick of #4405

---

components/widgets/menu/menu_items/menu_item.scss

MM-20763 - Updating MenuItem css
https://mattermost.atlassian.net/browse/MM-20763

MM-20763 - Updating MenuItem css

---

components/widgets/menu/menu_items/menu_item.scss

Cherry pick of #4400 on release-5.18.
- #4400: MM-20763 - Updating MenuItem css

Automated cherry pick of #4400

---

components/widgets/separator/separator.scss
sass/layout/_post-right.scss
sass/layout/_post.scss

MM-20747 - Updating separator css
https://mattermost.atlassian.net/browse/MM-20747

MM-20747 - Updating separator css

---

components/widgets/separator/separator.scss
sass/layout/_post-right.scss
sass/layout/_post.scss

Cherry pick of #4399 on release-5.18.
- #4399: MM-20747 - Updating separator css

Automated cherry pick of #4399

---

sass/responsive/_tablet.scss

MM-20754 - Fixing RHS spacing with banner
https://mattermost.atlassian.net/browse/MM-20754

MM-20754 - Fixing RHS spacing with banner

---

sass/responsive/_tablet.scss

Cherry pick of #4398 on release-5.18.
- #4398: MM-20754 - Fixing RHS spacing with banner

Automated cherry pick of #4398

---

components/admin_console/team_channel_settings/team/list/team_list.jsx

Fix for props being unexpectedly mutated.
https://mattermost.atlassian.net/browse/MM-20867

MM-20867: Fix for mutating props.

---

components/admin_console/team_channel_settings/team/list/team_list.jsx

Cherry pick of #4421 on release-5.18.
- #4421: MM-20867: Fix for mutating props.
/cc  @mkraft

Automated cherry pick of #4421

---

components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
components/search_results_item/search_results_item.jsx

Fix the problem where isRHS was passed as a string instead of as a boolean
https://github.com/mattermost/mattermost-server/issues/13266
None
None

[GH-13266] Fix isRHS passing

---

components/sidebar/sidebar.jsx

Cherry pick of #4437 on release-5.18.
- #4437: Fixing JS error on channel leave or being removed from the
/cc  @jespino

Automated cherry pick of #4437

---

e2e/cypress/integration/channel/more_channels_spec.js
e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
e2e/cypress/integration/search/search_group_message_spec.js

Fix e2e on more channels, channels and search

Fix e2e on more channels, channels and search

---

components/admin_console/color_setting.tsx

Cherry pick of #4436 on release-5.18.
- #4436: Fixing collor pickers in the admin console
/cc  @jespino

Automated cherry pick of #4436

---

components/widgets/separator/separator.scss
sass/components/_search.scss
sass/layout/_post-right.scss

MM-20797 - Updating RHS css (separator fix)
https://mattermost.atlassian.net/browse/MM-20797

MM-20797 - Updating RHS css (separator fix)

---

components/widgets/separator/separator.scss
sass/components/_search.scss
sass/layout/_post-right.scss

Cherry pick of #4441 on release-5.18.
- #4441: MM-20797 - Updating RHS css (separator fix)

Automated cherry pick of #4441

---

e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
e2e/cypress/integration/interactive_menu/basic_options_spec.js

Match descriptions with the release testing spreadsheet.  This is to easily match test cases and measure coverage

E2E Match descriptions with the release testing spreadsheet

---

components/widgets/team_icon/team_icon.scss

MM-20671 - Updating team icon content
https://mattermost.atlassian.net/browse/MM-20671

MM-20671 - Updating team icon content

---

components/widgets/team_icon/team_icon.scss

Cherry pick of #4442 on release-5.18.
- #4442: MM-20671 - Updating team icon content

Automated cherry pick of #4442

---

components/widgets/menu/menu_items/menu_item.scss

MM-20926 - Updating help text truncation in menu
https://mattermost.atlassian.net/browse/MM-20926

MM-20926 - Updating help text truncation in menu

---

components/widgets/menu/menu_items/menu_item.scss

Cherry pick of #4444 on release-5.18.
- #4444: MM-20926 - Updating help text truncation in menu

Automated cherry pick of #4444

---

components/widgets/menu/menu.scss
sass/routes/_admin-console.scss

MM-20965 - Fixing menus overflow
https://mattermost.atlassian.net/browse/MM-20965

MM-20965 - Fixing menus overflow

---

components/widgets/menu/menu.scss
sass/routes/_admin-console.scss

Cherry pick of #4450 on release-5.18.
- #4450: MM-20965 - Fixing menus overflow

Automated cherry pick of #4450

---

sass/layout/_markdown.scss
sass/layout/_post-right.scss
utils/utils.jsx

MM-19818 - Updating whitespace for th in markdown
This also fixes the post alignment issue in the RHS Thread.
https://mattermost.atlassian.net/browse/MM-19818

MM-19818 - Updating whitespace for th in markdown

---

components/admin_console/group_settings/group_details/group_teams_and_channels.jsx
components/admin_console/team_channel_settings/channel/details/channel_modes.jsx
i18n/en.json

Updates text
https://mattermost.atlassian.net/browse/MM-20044

[MM-20044] Public and private channel text update

---

components/admin_console/group_settings/group_details/group_teams_and_channels.jsx
components/admin_console/team_channel_settings/channel/details/channel_modes.jsx
i18n/en.json

Cherry pick of #4454 on release-5.18.
- #4454: update group teams and channels
/cc  @hahmadia

Automated cherry pick of #4454

---

sass/layout/_sidebar-right.scss
sass/responsive/_tablet.scss

Cherry pick of #4467 on release-5.18.
- #4467: Fix spacing on RHS Pinned and flag icon

Automated cherry pick of #4467

---

components/suggestion/search_channel_provider.jsx
components/suggestion/search_channel_with_permissions_provider.jsx
components/suggestion/search_date_provider.jsx
components/suggestion/search_suggestion_list.jsx
components/suggestion/search_user_provider.jsx
components/suggestion/suggestion_list.jsx
components/suggestion/switch_channel_provider.jsx
components/suggestion/switch_team_provider.jsx
components/suggestion/timezone_provider.jsx

Cherry pick of #4433 on release-5.18.
- #4433: update references

Automated cherry pick of #4433

---

components/announcement_bar/__snapshots__/text_dismissable_bar.test.jsx.snap
components/announcement_bar/configuration_bar/configuration_bar.jsx
components/announcement_bar/text_dismissable_bar.jsx
components/announcement_bar/text_dismissable_bar.test.jsx

Cherry pick of #4484 on release-5.18.
- #4484: Fixing admin console links in the announcements banner
/cc  @jespino

Automated cherry pick of #4484

---

components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.jsx.snap
components/admin_console/team_channel_settings/group/group_users_row.jsx

Fixes user not aligned in table
https://mattermost.atlassian.net/browse/MM-21174

[MM-21174] Fix UI not aligned

---

components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.jsx.snap
components/admin_console/team_channel_settings/group/group_users_row.jsx

Cherry pick of #4498 on release-5.18.
- #4498: Fix UI bug
/cc  @hahmadia

Automated cherry pick of #4498

---

components/local_date_time/local_date_time.test.tsx
components/local_date_time/local_date_time.tsx

Cherry pick of #4463 on release-5.18.
- #4463: fix post time for those unsupported by react-intl

Automated cherry pick of #4463

---

e2e/cypress/integration/interactive_menu/basic_options_spec.js

Test for "No items match" feedback in interactive menus.
Fixes https://github.com/mattermost/mattermost-server/issues/13339

MM-21042 test for "No items match" feedback

---

components/admin_console/__snapshots__/elasticsearch_settings.test.jsx.snap
components/admin_console/elasticsearch_settings.jsx
components/admin_console/elasticsearch_settings.test.jsx

Fixing test needed before save in elasticsearch
[MM-21010](https://mattermost.atlassian.net/browse/MM-21010)

Fixing test needed before save in elasticsearch

---

components/channel_header/__snapshots__/channel_header.test.jsx.snap
components/channel_header/channel_header.js
components/channel_header/channel_header.test.jsx

Fixing active state for mentions and flagged posts
[MM-21106](https://mattermost.atlassian.net/browse/MM-21106)

Fixing active state for mentions and flagged posts

---

components/claim/components/email_to_ldap.jsx

Fixes bug where the variable name was incorrect in a couple of places. 
https://mattermost.atlassian.net/browse/MM-21105

MM-21105: Switching email/password signin to LDAP fails with error in console

---

components/admin_console/__snapshots__/elasticsearch_settings.test.jsx.snap
components/admin_console/elasticsearch_settings.jsx
components/admin_console/elasticsearch_settings.test.jsx

Cherry pick of #4483 on release-5.18.
- #4483: Fixing test needed before save in elasticsearch
/cc  @jespino

Automated cherry pick of #4483

---

components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
components/plugin_marketplace/marketplace_modal.js
e2e/cypress/integration/plugins/marketplace/marketplace_spec.js

Cherry pick of #4459 on release-5.18.
- #4459: fix "install plugins" button on plugin marketplace page
/cc  @nadalfederer

Automated cherry pick of #4459

---

components/channel_header/__snapshots__/channel_header.test.jsx.snap
components/channel_header/channel_header.js
components/channel_header/channel_header.test.jsx

Cherry pick of #4486 on release-5.18.
- #4486: Fixing active state for mentions and flagged posts
/cc  @jespino

Automated cherry pick of #4486

---

components/claim/components/email_to_ldap.jsx

Cherry pick of #4488 on release-5.18.
- #4488: Fix bad variable name
/cc  @sbishel

Automated cherry pick of #4488

---

components/file_upload/__snapshots__/file_upload.test.jsx.snap
components/file_upload/file_upload.jsx
components/file_upload/file_upload.test.jsx

Cherry pick of #4499 on release-5.18.
- #4499: MM-20939 - File picker opens twice when trying to attach

Automated cherry pick of #4499

---

components/suggestion/suggestion_box.jsx
components/suggestion/suggestion_box.test.jsx

Reset at-mention selection
Fixes https://mattermost.atlassian.net/browse/MM-19870

MM-19870 - reset at-mention selection

---

e2e/cypress/support/api_commands.js

Fix failing tests on daily Cypress due to bad request when creating new user
none

Fix failing tests due to bad request when creating new user

---

components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
components/widgets/menu/menu_items/menu_item.scss
components/widgets/menu/menu_items/menu_item_action.test.tsx
components/widgets/menu/menu_items/menu_item_action.tsx
components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx

Cherry pick of #4514 on release-5.18.
- #4514: Make long <MenuItem>s wrap

Automated cherry pick of #4514

---

package-lock.json
package.json

Manual cherry pick of #4531

---

components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
components/widgets/menu/menu_items/menu_item.scss
components/widgets/menu/menu_items/menu_item_action.test.tsx
components/widgets/menu/menu_items/menu_item_action.tsx
components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx

This reverts commit 25dcd4e9544a61f4349e1320ca50255da7b06ffe.(PR: https://github.com/mattermost/mattermost-webapp/pull/4514)
As per conversation https://community-daily.mattermost.com/core/pl/wwuupz8a9brbunaygrtb91oz1o

Revert "[MM-21076] Make longer <MenuItem>s wrap instead of truncate with ellipsis (#4514)"

---

package-lock.json
package.json

In PR https://github.com/mattermost/mattermost-webapp/pull/4500, missed to update the Redux hash to include changes for this redux PR: https://github.com/mattermost/mattermost-redux/pull/1008

MM-19614 - Updating Redux hash

---

components/suggestion/suggestion_box.jsx
components/suggestion/suggestion_box.test.jsx

Cherry pick of #4476 on release-5.19.
- #4476: MM-19870 - reset at-mention selection

Automated cherry pick of #4476

---

components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
components/user_settings/notifications/email_notification_setting/email_notification_setting.test.jsx
package-lock.json
package.json

Cherry pick of #4406 on release-5.19.
- #4406: MM-20260 - Email notification still sent while disabled in UI

Automated cherry pick of #4406

---

e2e/cypress/integration/interactive_menu/basic_options_spec.js

Write a test to search within the list of options
Fixes https://github.com/mattermost/mattermost-server/issues/13340

MM-21039 searching within the list of options

---

components/widgets/menu/menu.test.tsx
components/widgets/menu/menu.tsx
components/widgets/menu/menu_group.test.tsx
components/widgets/menu/menu_group.tsx
e2e/cypress/integration/menus/hamburguer_menu_spec.js

Cherry pick of #4536 on release-5.19.
- #4536: Stop propagating divider click handler to avoid toggle

Automated cherry pick of #4536

---

e2e/package-lock.json
e2e/package.json

Upgrade E2E dependencies

---

e2e/cypress/integration/system_console/ui_and_api/customization_spec.js

Added e2e for SC20332
Ticket Link: https://github.com/mattermost/mattermost-server/issues/13178

MM-20332 UI Automation: System Console for "Can change Site Description setting"

---

.eslintignore
package.json

Moving ignored directories to .eslintignore and adding storybook-static
[MM-21327](https://mattermost.atlassian.net/browse/MM-21327)

Moving ignored directories to .eslintignore and adding storybook-static

---

e2e/cypress/integration/system_console/ui_and_api/customization_spec.js

Ticket link: https://github.com/mattermost/mattermost-server/issues/13173

Add E2E for SC20342 Can change Custom Brand Text setting

---

e2e/cypress/integration/messaging/message_in_another_language_spec.js

add test "Typing using CJK keyboard"
Fixes https://github.com/mattermost/mattermost-server/issues/11760

MM-17456 - add test "Typing using CJK keyboard"

---

e2e/cypress/integration/interactive_menu/basic_options_spec.js

A lots of tests were failing due to unable to find the input of select of webhook messages, this pr fixes those in addition to closing all the rhs tabs
Fixes : https://github.com/mattermost/mattermost-server/issues/13520
Jira : None

Fixes #13520 : Many UI automation tests are failing in interactive_menu/basic_options_spec.js

---

components/post_view/date_separator/__snapshots__/date_separator.test.jsx.snap
components/post_view/date_separator/date_separator.test.jsx
components/recent_date.test.tsx
components/recent_date.tsx

Cherry pick of #4562 on release-5.19.
- #4562: fix date separator for timezone not supported by

Automated cherry pick of #4562

---

sass/components/_modal.scss

MM-19855 - Updating markdown in view info modal
https://mattermost.atlassian.net/browse/MM-19855

MM-19855 - Updating markdown in view info modal

---

components/toggle_modal_button_redux/__snapshots__/toggle_modal_button_redux.test.jsx.snap
components/toggle_modal_button_redux/toggle_modal_button_redux.jsx
i18n/en.json

Cherry pick of #4540 on release-5.19.
- #4540: Fixing how the accesibility labels for
/cc  @jespino

Automated cherry pick of #4540

---

components/create_comment/__snapshots__/create_comment.test.jsx.snap
components/create_comment/create_comment.jsx
components/create_comment/create_comment.test.jsx
components/suggestion/suggestion_list.jsx
components/textbox/textbox.jsx
sass/components/_suggestion-list.scss
utils/constants.jsx

MM-21414 - Updating textbox position in RHS
Now the suggestion list changes its positioning depending on how much space is available at the top.
https://mattermost.atlassian.net/browse/MM-21414

MM-21414 - Updating textbox position in RHS

---

components/create_comment/__snapshots__/create_comment.test.jsx.snap
components/create_comment/create_comment.jsx
components/create_comment/create_comment.test.jsx
components/suggestion/suggestion_list.jsx
components/textbox/textbox.jsx
sass/components/_suggestion-list.scss
utils/constants.jsx

Cherry pick of #4609 on release-5.19.
- #4609: MM-21414 - Updating textbox position in RHS

Automated cherry pick of #4609

---

components/widgets/menu/menu_items/menu_item.scss
sass/components/_modal.scss

MM-21607 - Updating suggestion list in Switcher
https://mattermost.atlassian.net/browse/MM-21607

MM-21607 - Updating suggestion list in Switcher

---

components/widgets/menu/menu_items/menu_item.scss
sass/components/_modal.scss

Cherry pick of #4630 on release-5.19.
- #4630: MM-21607 - Updating suggestion list in Switcher

Automated cherry pick of #4630

---

e2e/cypress/integration/plugins/marketplace/marketplace_spec.js

Enabled previously disabled E2E test for Plugin Marketplace.
https://mattermost.atlassian.net/browse/MM-21609

Enabled Plugin Marketplace signature E2E tests

---

sass/components/_scrollbar.scss

MM-21201 - Updating scrollbar bg in sys console
https://mattermost.atlassian.net/browse/MM-21201

MM-21201 - Updating scrollbar bg in sys console

---

sass/components/_scrollbar.scss

Cherry pick of #4640 on release-5.19.
- #4640: MM-21201 - Updating scrollbar bg in sys console

Automated cherry pick of #4640

---

components/file_upload/__snapshots__/file_upload.test.jsx.snap
components/file_upload/file_upload.jsx

Cherry pick of #4575 on release-5.19.
- #4575: Fix isMobile ? this.simulateInputClick : undefined
/cc  @larkox

Automated cherry pick of #4575

---

actions/team_actions.jsx
actions/team_actions.test.js

https://mattermost.atlassian.net/browse/MM-21315

MM-21315 Don't mark manually unread channel as read on team switch

---

components/widgets/menu/menu_items/menu_item.scss

Cherry pick of #4608 on release-5.19.
- #4608: MM-21394 - Updating menu item css on mobile

Automated cherry pick of #4608

---

actions/team_actions.jsx
actions/team_actions.test.js

Cherry pick of #4645 on release-5.19.
- #4645: MM-21315 Don't mark manually unread channel as read on team
/cc  @hmhealey

Automated cherry pick of #4645

---

utils/utils.jsx

MM-21603 - Updating sidebar text 80 var
https://mattermost.atlassian.net/browse/MM-21603

MM-21603 - Updating sidebar text 80 var

---

utils/utils.jsx

Cherry pick of #4642 on release-5.19.
- #4642: MM-21603 - Updating sidebar text 80 var

Automated cherry pick of #4642

---

components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap
components/edit_channel_header_modal/edit_channel_header_modal.jsx
components/edit_channel_header_modal/edit_channel_header_modal.test.jsx
components/edit_channel_header_modal/index.js
components/post_view/channel_intro_message/channel_intro_message.jsx

Cherry pick of #4551 on release-5.19.
- #4551: fix: not closing channel header modal
/cc  @nadalfederer

Automated cherry pick of #4551

---

components/local_date_time/local_date_time.test.tsx
components/local_date_time/local_date_time.tsx
e2e/cypress/integration/messaging/local_date_time_spec.js

Cherry pick of #4661 on release-5.19.
- #4661: respect locale format in rendering post time

Automated cherry pick of #4661

---

sass/layout/_sidebar-right.scss

MM-21320 - Updating typing css in RHS
https://mattermost.atlassian.net/browse/MM-21320

MM-21320 - Updating typing css in RHS

---

sass/components/_modal.scss

MM-21636 - Updating more modal row css
https://mattermost.atlassian.net/browse/MM-21636

MM-21636 - Updating more modal row css

---

components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
components/post_view/reaction/reaction.jsx
sass/layout/_post.scss

MM-21344 - Updating emoji reactions css
https://mattermost.atlassian.net/browse/MM-21344

MM-21344 - Updating emoji reactions css

---

sass/components/_tutorial.scss

MM-21392 - Updating tutorial css
https://mattermost.atlassian.net/browse/MM-21392

MM-21392 - Updating tutorial css

---

components/channel_header/channel_header.js

Cherry pick of #4677 on release-5.20.
- #4677: Stop auto focus of the search bar when opening a

Automated cherry pick of #4677

---

sass/components/_scrollbar.scss

MM-20181 - Updating scrollbar on IE RHS
https://mattermost.atlassian.net/browse/MM-20181

MM-20181 - Updating scrollbar on IE RHS

---

sass/components/_tutorial.scss

Cherry pick of #4673 on release-5.20.
- #4673: MM-21392 - Updating tutorial css

Automated cherry pick of #4673

---

sass/layout/_webhooks.scss

Cherry pick of #4671 on release-5.20.
- #4671: MM-21467 - Updating overflow for dialogs

Automated cherry pick of #4671

---

sass/components/_scrollbar.scss

Cherry pick of #4691 on release-5.20.
- #4691: MM-20181 - Updating scrollbar on IE RHS

Automated cherry pick of #4691

---

components/dot_menu/dot_menu.jsx
components/dot_menu/dot_menu.test.jsx
components/dot_menu/dot_menu_empty.test.jsx
components/dot_menu/dot_menu_mobile.test.jsx
components/dot_menu/index.js
components/post_view/post/index.js
components/post_view/post/post.jsx
components/post_view/post/post.test.js
components/rhs_comment/index.js
components/rhs_comment/rhs_comment.jsx
components/rhs_comment/rhs_comment.test.jsx
components/rhs_root_post/index.js
components/rhs_root_post/rhs_root_post.jsx
components/rhs_root_post/rhs_root_post.test.jsx
utils/channel_utils.jsx

This both removes the menu item for Mark as Unread and prevents the alt+click behaviour.
https://mattermost.atlassian.net/browse/MM-21007

MM-21007 Don't allow Mark as Unread in archived channels and search

---

components/dot_menu/dot_menu.jsx
components/dot_menu/dot_menu.test.jsx
components/dot_menu/dot_menu_empty.test.jsx
components/dot_menu/dot_menu_mobile.test.jsx
components/dot_menu/index.js
components/post_view/post/index.js
components/post_view/post/post.jsx
components/post_view/post/post.test.js
components/rhs_comment/index.js
components/rhs_comment/rhs_comment.jsx
components/rhs_comment/rhs_comment.test.jsx
components/rhs_root_post/index.js
components/rhs_root_post/rhs_root_post.jsx
components/rhs_root_post/rhs_root_post.test.jsx
utils/channel_utils.jsx

Cherry pick of #4700 on release-5.20.
- #4700: MM-21007 Don't show Mark as Unread in archived channel or
/cc  @hmhealey

Automated cherry pick of #4700

---

e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js

Fix failing test on custom themes

Fix failing test on custom themes

---

sass/components/_popover.scss

MM-21213 - Updating max height for search popoever
https://mattermost.atlassian.net/browse/MM-21213

MM-21213 - Updating max height for search popoever

---

components/interactive_dialog/interactive_dialog.jsx
components/interactive_dialog/interactive_dialog.test.jsx

Cherry pick of #4668 on release-5.20.
- #4668: MM-21863: fix bool defaults for interactive dialog

Automated cherry pick of #4668

---

e2e/cypress/integration/channel/message_bullets_spec.js
e2e/cypress/integration/email/mention_email_notification_spec.js

Fix message bullets and email notification tests
none, failing tests on daily Cypress tests

Fix message bullets and email notification tests

---

components/post_view/post_list_virtualized/post_list_virtualized.jsx
components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
components/toast/toast.jsx
components/toast/toast.scss
components/toast/toast.test.jsx
components/toast_wrapper/toast_wrapper.jsx
components/toast_wrapper/toast_wrapper.test.jsx
e2e/cypress/integration/channel/toast_spec.js

* Do not show unread toast when at bottom
* Remove the delays for toasts
* Change default state of virt list atBottom to be true so we don't see a flicker of unread toast and let the virt list decide if list is at bottom. 
https://mattermost.atlassian.net/browse/MM-21933

MM-21933 Fix toast banner delays

---

components/post_view/post_list_virtualized/post_list_virtualized.jsx
components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
components/toast/toast.jsx
components/toast/toast.scss
components/toast/toast.test.jsx
components/toast_wrapper/toast_wrapper.jsx
components/toast_wrapper/toast_wrapper.test.jsx
e2e/cypress/integration/channel/toast_spec.js

Cherry pick of #4710 on release-5.20.
- #4710: MM-21933 Fix toast banner delays

Automated cherry pick of #4710

---

components/admin_console/team_channel_settings/channel/details/channel_details.jsx
components/admin_console/team_channel_settings/team/details/team_details.jsx
e2e/cypress/integration/enterprise/system_console/team_and_channel_asign_roles_spec.js

Cherry pick of #4684 on release-5.20.
- #4684: update team if role is change on initial add
/cc  @hahmadia

Automated cherry pick of #4684

---

components/widgets/modals/full_screen_modal.tsx

Cherry pick of #4702 on release-5.20.
- #4702: MM-21721 Fix FullScreenModal not supporting refs
/cc  @hmhealey

Automated cherry pick of #4702

---

e2e/cypress/integration/interactive_menu/basic_options_spec.js
e2e/cypress/integration/login/tutorial_navigation_and_links_spec.js
e2e/cypress/support/task_commands.js

Fix e2e for tutorial navigation and interactive menu
none, failed on daily Cypress tests

Fix e2e for tutorial navigation and interactive menu

---

components/admin_console/manage_teams_modal/__snapshots__/manage_teams_dropdown.test.jsx.snap
components/admin_console/manage_teams_modal/manage_teams_dropdown.jsx
components/channel_groups_manage_modal/channel_groups_manage_modal.jsx
components/team_groups_manage_modal/team_groups_manage_modal.jsx
sass/components/_modal.scss

Updated Group Sync To Roles Chat facing UI (Teams and Channels Modals)
https://mattermost.atlassian.net/browse/MM-21956

MM-21956 Updated UX

---

sass/components/_groups.scss

Cherry pick of #4722 on release-5.20.
- #4722: MM-21743 - Updating padding for group rows

Automated cherry pick of #4722

---

components/admin_console/manage_teams_modal/__snapshots__/manage_teams_dropdown.test.jsx.snap
components/admin_console/manage_teams_modal/manage_teams_dropdown.jsx
components/channel_groups_manage_modal/channel_groups_manage_modal.jsx
components/team_groups_manage_modal/team_groups_manage_modal.jsx
sass/components/_modal.scss

Cherry pick of #4714 on release-5.20.
- #4714: MM-21956 Updated UX
/cc  @catalintomai

Automated cherry pick of #4714

---

actions/websocket_actions.jsx
actions/websocket_actions.test.jsx
package-lock.json
package.json

Cherry pick of #4723 on release-5.20.
- #4723: Stopped setting status to online when status

Automated cherry pick of #4723

---

components/channel_header_mobile/channel_info_button/channel_info_button.test.js
components/overlay_trigger.test.tsx
components/overlay_trigger.tsx
components/profile_picture.tsx
components/select_team/components/__snapshots__/select_team_item.test.jsx.snap

Cherry pick of #4701 on release-5.20.
- #4701: MM-21880 Forward refs using OverlayTrigger wrapper
/cc  @hmhealey

Automated cherry pick of #4701

---

components/toast_wrapper/toast_wrapper.jsx
components/toast_wrapper/toast_wrapper.test.jsx

Cherry pick of #4736 on release-5.20.
- #4736: MM-21872 Fix for toast showing o new messages

Automated cherry pick of #4736

---

sass/responsive/_mobile.scss

Cherry pick of #4721 on release-5.20.
- #4721: MM-21393 - Updating mobile css for dropdown

Automated cherry pick of #4721

---

components/widgets/icons/close_icon.jsx

Cherry pick of #4754 on release-5.20.
- #4754: MM-21953: Fixing x button alignment in invitation process
/cc  @jespino

Automated cherry pick of #4754

---

components/__snapshots__/quick_input.test.jsx.snap
components/channel_header_mobile/channel_info_button/__snapshots__/channel_info_button.test.js.snap
components/overlay_trigger.test.tsx
components/overlay_trigger.tsx
plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap

Cherry pick of #4715 on release-5.20.
- #4715: MM-21874 Merge styling props for children of custom
/cc  @hmhealey

Automated cherry pick of #4715

---

components/admin_console/team_channel_settings/channel/details/channel_profile.jsx
components/admin_console/team_channel_settings/channel/details/channel_profile.test.jsx
components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_row.test.tsx.snap
components/admin_console/team_channel_settings/channel/list/channel_list.tsx
components/admin_console/team_channel_settings/channel/list/channel_row.test.tsx
components/admin_console/team_channel_settings/channel/list/channel_row.tsx
package-lock.json
package.json

* fix channel list and details
* update for lastest changes
* address PR comments
* update redux hash so checks can pass
* update types
* update redux hash to latest master
Co-authored-by: Hossein Ahmadian-Yazdi <hahmadia@users.noreply.github.com>
(cherry picked from commit 7cdcbadaaa9122d0a720c5bdd615724638576a12)

MM-21890: fix channel list and details (#4731)

---

.circleci/config.yml

We are uploading the server package to another S3 folder as we can see here: https://github.com/mattermost/mattermost-server/blob/master/build/Jenkinsfile.pr#L132

update url to download the server package

---

actions/invite_actions.jsx
actions/invite_actions.test.js
actions/team_actions.jsx
actions/team_actions.test.js

Cherrypick MM-20977 release 5.20

---

sass/layout/_sidebar-right.scss
sass/responsive/_tablet.scss

MM-21424 - Updating RHS css for responsive view
https://mattermost.atlassian.net/browse/MM-21424

MM-21424 - Updating RHS css for responsive view

---

sass/layout/_sidebar-right.scss
sass/responsive/_tablet.scss

Cherry pick of #4793 on release-5.20.
- #4793: MM-21424 - Updating RHS css for responsive view

Automated cherry pick of #4793

---

NOTICE.txt

Cherry pick of #4762 on release-5.20.
- #4762: Update NOTICE.txt
/cc  @amyblais

Automated cherry pick of #4762

---

i18n/en.json

Cherry pick of #4765 on release-5.20.
- #4765: MM-22030: add missing text
/cc  @catalintomai

Automated cherry pick of #4765

---

components/recent_date.tsx

Cherry pick of #4758 on release-5.20.
- #4758: fix date separator

Automated cherry pick of #4758

---

components/__snapshots__/formatted_markdown_message.test.jsx.snap
components/formatted_markdown_message.jsx
components/formatted_markdown_message.test.jsx
components/widgets/inputs/users_emails_input.jsx

Cherry pick of #4777 on release-5.20.
- #4777: MM-22024: Allow to disable link generate while using
/cc  @jespino

Automated cherry pick of #4777

---

plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap
plugins/channel_header_plug/channel_header_plug.jsx

MM-21247 - Adding tooltip for plugins button
https://mattermost.atlassian.net/browse/MM-21247

MM-21247 - Adding tooltip for plugins button

---

e2e/cypress/integration/channel/scroll_channel_messages_spec.js

Fix failing scroll channel messages spec. Updated date format.

Fix scroll channel messages spec

---

components/widgets/menu/menu_items/menu_item.scss
components/widgets/menu/menu_items/menu_item_link.test.tsx
components/widgets/menu/menu_items/menu_item_link.tsx
sass/layout/_headers.scss

Cherry pick of #4760 on release-5.20.
- #4760: Increase min-width to prevent wrapping

Automated cherry pick of #4760

---

components/create_post/create_post.jsx

Cherry pick of #4841 on release-5.20.
- #4841: Fix 2 byte character drafts not being cleared

Automated cherry pick of #4841

---

components/sidebar/sidebar.jsx

Cherry pick of #4840 on release-5.20.
- #4840: Fix JS crash when leaving all teams

Automated cherry pick of #4840

---

e2e/cypress/integration/plugins/marketplace/marketplace_spec.js

Fix failing marketplace spec.
- fix setup and teardown
- fix timeout

Fix marketplace spec

---

e2e/cypress/integration/post_header/post_header_spec.js
e2e/cypress/support/ui_commands.js

Fix failing post header spec.
- fix casing
- fix timeout

Fix post header spec

---

e2e/cypress/integration/signin_authentication/forgot_password_spec.js

Fix failing forgot password spec. Added missing period

Fix forgot password spec

---

e2e/cypress/integration/team/teams_spec.js

Fix failing teams spec. Modify css class for Invite People subtext

Fix teams spec

---

components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.js.snap
components/admin_console/system_users/system_users_dropdown/index.js
components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js

Showing the demote-to-guest action only when you have a license
[MM-21882](https://mattermost.atlassian.net/browse/MM-21882)

Showing the demote-to-guest action only when you have a license

---

components/widgets/inputs/channels_input.jsx
components/widgets/inputs/users_emails_input.jsx

Cherry pick of #4855 on release-5.20.
- #4855: MM-22351: Fix users/emails autocompletion when user emails is
/cc  @jespino

Automated cherry pick of #4855

---

components/needs_team/needs_team.jsx

Cherry pick of #4853 on release-5.20.
- #4853: MM-22346: Fix open new added team
/cc  @jespino

Automated cherry pick of #4853

---

components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.js.snap
components/admin_console/system_users/system_users_dropdown/index.js
components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js

Cherry pick of #4831 on release-5.20.
- #4831: Showing the demote-to-guest action only when you have a
/cc  @jespino

Automated cherry pick of #4831

---

components/sidebar/sidebar.jsx

Cherry pick of #4848 on release-5.20.
- #4848: MM-22199 Disable scrolling to channel on switch
/cc  @hmhealey

Automated cherry pick of #4848

---

components/suggestion/search_user_provider.jsx

Cherry pick of #4876 on release-5.20.
- #4876: Fix search autocomplete not closing after typing selection

Automated cherry pick of #4876

---

components/toast/__snapshots__/toast.test.jsx.snap
components/toast/toast.jsx
e2e/cypress/integration/channel/toast_spec.js
e2e/cypress/integration/enterprise/system_console/channel_modes_spec.js
e2e/cypress/integration/messaging/file_upload_in_center_channel_spec.js
e2e/cypress/integration/messaging/post_options_menu_spec.js

* Added step to wait until loading icon is removed after scrolling up. 
* Fixed a strange issue where toast was not getting dismissed on Cypress invoked browser & on cypress.test instance. Was working fine on localhost though. 
* 3 tests were failing because of this issue. 
* A bug was recently fixed to displayed Channel Display Name in the Channel Configuration page instead of Channel Name. Updated the cypress test accordingly. 
* 3 tests were failing because of this issue. 
* Added a step to wait for image to be uploaded before submitting the post. 
* 2 tests were failing because of this issue. 
* Updated the Text displayed in the Menu options based on a recent change. 
* 1 test was failing because of this issue. 
N/A. Fixes based on analysis of daily Cypress test run results.

Fixed some tests based on daily runs

---

components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.tsx.snap
components/admin_console/team_channel_settings/group/group_users_row.tsx

Cherry pick of #4886 on release-5.20.
- #4886: fix '&nbsp' being displayed in modal
/cc  @sbishel

Automated cherry pick of #4886

---

e2e/cypress/integration/interactive_menu/basic_options_spec.js

Fix ephemeral verification
- refactored ephemeral verification and added some timeout

Fix ephemeral verification

---

e2e/cypress/integration/system_console/ui_and_api/customization_spec.js

Fix failing customization spec
- some tests fail because user is logged out
- login each test instead of suite

Fix customization spec

---

e2e/cypress/integration/account_settings/general/fullname_spec.js

Verification is made while loading suggestion list for user mentions.
- fix by making sure that the user is on suggestion list before doing verification
none

E2E: Ensure user is on suggestion list before doing verification

---

e2e/cypress/integration/messaging/file_upload_in_center_channel_spec.js

Fix failing file upload in center channel spec
- fixed waitForImageUpload to wait until thumbnail image is present
- made post text unique

Fix file upload in center channel spec

---

e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
e2e/cypress/integration/messaging/message_channel_draw_spec.js
e2e/cypress/integration/system_console/plugin_upload_spec.js
e2e/cypress/support/api_commands.js
e2e/cypress/support/ui_commands.js

Fix channel switcher and draw plugin
none

E2E: Fix channel switcher and draw plugin

---

components/admin_console/team_channel_settings/group/group_list.tsx
components/member_list_team/index.js
components/member_list_team/member_list_team.jsx
components/widgets/admin_console/admin_panel.tsx

Cherry pick of https://github.com/mattermost/mattermost-webapp/pull/4820 on release-5.21.

Cherry pick of #4820

---

sass/components/_popover.scss

Cherry pick of #4720 on release-5.21.
- #4720: MM-21213 - Updating max height for search popoever

Automated cherry pick of #4720

---

components/channel_members_dropdown/channel_members_dropdown.jsx
components/team_members_dropdown/__snapshots__/team_members_dropdown.test.jsx.snap
components/team_members_dropdown/team_members_dropdown.jsx
components/team_members_dropdown/team_members_dropdown.test.jsx
components/user_list.jsx
e2e/cypress/integration/enterprise/teams/invite_bot_spec.js
e2e/cypress/support/api_commands.js

Manual cherry-pick of #4705

---

sass/utils/_modifiers.scss

Fixing margin typo

---

components/dot_menu/dot_menu.jsx

In order to avoid bad UX for the dropdown in post thread, I only added this change when the user is located on the RHS thread.
Fixes https://mattermost.atlassian.net/browse/MM-22137
Fix v5.21 (March 2020)

[MM-22137] - Make RHS comment dropdown open down by default

---

sass/layout/_markdown.scss
utils/syntax_highlighting.tsx

Cherry pick of #4822 on release-5.21.
- #4822: Fix code block copying line numbers
/cc  @iomodo

Automated cherry pick of #4822

---

components/at_mention/at_mention.jsx
components/markdown/markdown.jsx
utils/__snapshots__/message_html_to_component.test.jsx.snap
utils/message_html_to_component.jsx
utils/message_html_to_component.test.jsx

Cherry pick of #4819 on release-5.21.
- #4819: Fix Markdown component not respecting mentionHighlight

Automated cherry pick of #4819

---

components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.jsx.snap
components/admin_console/system_user_detail/index.js
components/admin_console/system_user_detail/system_user_detail.jsx
components/admin_console/system_user_detail/system_user_detail.test.jsx
i18n/en.json

Automatic Merge
(cherry picked from commit aab37c25c19f2060fd7620b0bcec060076990d6c)
MM-21224: System console shows wrong authentication method (#4600)

MM-21224: System console shows wrong authentication method (#4600)

---

components/rhs_thread/rhs_thread.jsx
components/rhs_thread/rhs_thread.test.jsx

Cherry pick of #4771 on release-5.21.
- #4771: MM-22042 Only scroll RHS to bottom when current user posts
/cc  @hmhealey

Automated cherry pick of #4771

---

utils/text_formatting.test.jsx
utils/text_formatting.tsx

Cherry pick of #4859 on release-5.21.
- #4859: MM-22079 Update tests to include more types of emojis
/cc  @hmhealey

Automated cherry pick of #4859

---

actions/global_actions.jsx
actions/global_actions.test.js
stores/local_storage_store.jsx

Cherry pick of #4791 on release-5.21.
- #4791: wip

Automated cherry pick of #4791

---

components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
components/plugin_marketplace/marketplace_modal.js
components/plugin_marketplace/marketplace_modal.scss
components/widgets/modals/full_screen_modal.scss
utils/utils.jsx

MM-22309 - Updating marketplace modal css
https://mattermost.atlassian.net/browse/MM-22337

MM-22309 - Updating marketplace modal css

---

components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
components/plugin_marketplace/marketplace_modal.js
components/plugin_marketplace/marketplace_modal.scss
components/widgets/modals/full_screen_modal.scss
utils/utils.jsx

Cherry pick of #4908 on release-5.21.
- #4908: MM-22309 - Updating marketplace modal css

Automated cherry pick of #4908

---

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
i18n/i18n.jsx

Both have exceeded 90% in translation server https://translate.mattermost.com/projects/mattermost/
Big shoutouts to Tom De Moor and flynbit!

Promote Dutch and Russian to Beta, v5.22

---

components/create_comment/create_comment.jsx
components/create_comment/create_comment.test.jsx

Cherry pick of #4875 on release-5.21.
- #4875: Fixed the use of handleUploadError on

Automated cherry pick of #4875

---

components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/__snapshots__/team_in_list.test.jsx.snap
components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.jsx
components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.test.jsx

Cherry pick of #4962 on release-5.21.
- #4962: Add Team Name back to team list
/cc  @sbishel

Automated cherry pick of #4962

---

e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js

Fix failing mention autocomplete overlap spec
- fixed verification logic
- refactored tests

Fix mention autocomplete overlap spec

---

components/audit_table/audit_table.jsx

Simply fixes a typo I spotted while reviewing code.
No ticket

fixed typo defauleMessage -> defaultMessage

---

sass/layout/_post.scss

MM-22969 - Updating paragraph styling in list item
https://mattermost.atlassian.net/browse/MM-22969

MM-22969 - Updating paragraph styling in list item

---

components/admin_console/system_user_detail/team_list/index.ts
components/more_direct_channels/index.ts
components/removed_from_channel_modal/index.ts

Followup to #4910 since I didn't read my own reminder comment to check for code that had been added since I initially made that PR.
#4910

Use webapp-specific GlobalState everywhere

---

sass/layout/_post.scss

Cherry pick of #4981 on release-5.21.
- #4981: MM-22969 - Updating paragraph styling in list item

Automated cherry pick of #4981

---

sass/components/_scrollbar.scss

Cherry pick of #4982 on release-5.21.
- #4982: MM-23012 - Hiding scrollbars in IE from LHS/RHS

Automated cherry pick of #4982

---

i18n/en.json

Adding the missing bracket in translation files
https://mattermost.atlassian.net/browse/MM-22754

MM-22754 Fix for missing closing bracket

---

components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
components/user_settings/sidebar/user_settings_sidebar.jsx

MM-22929 - Updating back button in Account modal
https://mattermost.atlassian.net/browse/MM-22929

MM-22929 - Updating back button in Account modal

---

e2e/package-lock.json

Update package lock

---

e2e/cypress/integration/enterprise/system_console/team_and_channel_asign_roles_spec.js

Fixed issue in Cypress test while selecting a group in Add New Groups Dialog
NA. Fixed based on analysis of Cypress daily test run

Fixed issue in Cypress test while selecting a group in Add New Groups Dialog

---

e2e/cypress/fixtures/account_setting_sections.json
e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js

Fixes Accessibility related Cypress tests based on run on Cypress test instance
NA

Fixed Accessibility related Cypress tests based on run on Cypress test instance

---

components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
components/user_settings/sidebar/user_settings_sidebar.jsx

Cherry pick of #4980 on release-5.21.
- #4980: MM-22929 - Updating back button in Account modal

Automated cherry pick of #4980

---

e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js

Added Cypress test to verify Accessibility support in different input fields 
Fixes https://mattermost.atlassian.net/browse/MM-22625
**Localhost:**
**Cypress.test instance:**

Added Cypress test to verify Accessibility support in different input fields

---

components/channel_header/channel_header.js
components/post_view/message_attachments/message_attachment/message_attachment.jsx
components/post_view/post_message_view/post_message_view.jsx

https://mattermost.atlassian.net/browse/MM-23045
Fixes https://github.com/mattermost/mattermost-webapp/pull/4988#issuecomment-595347421 
this was introduced after merging https://github.com/mattermost/mattermost-webapp/pull/4402

Define handleFormattedTextClick as an arrow function

---

e2e/cypress/integration/at_mentions/at_mentions_spec.js

Fix failing test on at-mention
none

Fix failing test on at-mention

---

components/widgets/badges/badges_spec.js
components/widgets/popover/popover_spec.js
e2e/cypress/integration/interactive_dialog/boolean_spec.js
e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
e2e/cypress/integration/interactive_menu/basic_options_spec.js
e2e/cypress/integration/interactive_menu/select_with_keys_spec.js
e2e/cypress/plugins/index.js
e2e/cypress/plugins/url_health_check.js
e2e/cypress/support/task_commands.js

Add URL check for service required by a Cypress test
none

Add URL check for service required by a Cypress test

---

e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js

Fix failing accessibility support specs
NA

Fix accessibility support specs

---

sass/components/_popover.scss
utils/utils.jsx

MM-22874 - Updating user popover css
https://mattermost.atlassian.net/browse/MM-22874

MM-22874 - Updating user popover css

---

components/multiselect/__snapshots__/multiselect.test.tsx.snap
components/multiselect/multiselect.tsx

MM-22873 - Updating input UI in DM modal
https://mattermost.atlassian.net/browse/MM-22873

MM-22873 - Updating input UI in DM modal

---

sass/layout/_team-button.scss

MM-22869 - Updating team button active state
https://mattermost.atlassian.net/browse/MM-22869

MM-22869 - Updating team button active state

---

e2e/cypress/integration/channel/channel_routing_spec.js
e2e/cypress/integration/channel/message_reply_bot_post_spec.js
e2e/cypress/integration/channel/message_reply_spec.js
e2e/cypress/integration/email/mention_email_notification_spec.js
e2e/cypress/integration/enterprise/elasticsearch/renaming_spec.js
e2e/cypress/integration/enterprise/elasticsearch/users_spec.js
e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js

Fix failing tests by setting known teammate name display preference
none

Fix failing tests by setting known teammate name display preference

---

sass/layout/_sidebar-right.scss
sass/responsive/_desktop.scss
sass/responsive/_module.scss
sass/responsive/_tablet.scss

MM-22843 - Updating RHS size on wider screens
https://mattermost.atlassian.net/browse/MM-22843

MM-22843 - Updating RHS size on wider screens

---

components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx
i18n/en.json

Mark the Channel Moderation feature as "Beta" in the UI.
https://mattermost.atlassian.net/browse/MM-23112

MM-23112: Mark channel moderation as 'Beta'.

---

e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
e2e/cypress/integration/channel/add_users_to_channel_spec.js
e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
e2e/cypress/integration/interactive_menu/basic_options_spec.js

Fix misc failing specs

---

components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
components/admin_console/admin_sidebar/admin_sidebar.jsx
sass/routes/_admin-console.scss

MM-22987 - Making searchbar fixed in console
https://mattermost.atlassian.net/browse/MM-22987

MM-22987 - Making searchbar fixed in console

---

sass/layout/_headers.scss

MM-22984 - Adding hover state for channel name
https://mattermost.atlassian.net/browse/MM-22984

MM-22984 - Adding hover state for channel name

---

sass/components/_popover.scss

MM-22903 - Updating send message UI in popover
https://mattermost.atlassian.net/browse/MM-22903

MM-22903 - Updating send message UI in popover

---

components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
components/admin_console/admin_sidebar_section.jsx
components/admin_console/blockable_link/blockable_link.tsx
components/widgets/menu/menu_items/menu_item_external_link.tsx

added new events to admin section according to https://docs.google.com/document/d/1YUqIovY7rE-4wQNCpgOsoTA9-v8_gAEFc4KEyjT15Yo/edit?usp=sharing
https://mattermost.atlassian.net/browse/MM-23092
https://github.com/mattermost/mattermost-redux/pull/1078

MM-23092  Implement Server Setup telemetry - system console events

---

components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
components/edit_post_modal/edit_post_modal.jsx

This fixes the closing of the editPostModal when the user has unsaved changes. 
https://mattermost.atlassian.net/browse/MM-22360

[MM-22360] - Handle closing of editPostModal when user has unsaved changes

---

e2e/cypress/integration/channel/toast_spec.js
e2e/cypress/support/ui_commands.js

Fixed failing Cypress tests in the file toast_spec.js
NA

Fixed E2E Cypress test toast_spec

---

e2e/cypress/integration/channel/header_spec.js
e2e/cypress/support/ui_commands.js

Fix header and image attachment specs
none, failing on daily Cypress tests

Fix header and image attachment specs

---

e2e/cypress/integration/at_mentions/at_mentions_spec.js
e2e/cypress/integration/channel/channel_name_tooltips_spec.js

Fix e2e tests for channel at-mentions and tooltips
none, failing tests on Cypress daily.

Fix e2e tests for channel at-mentions and tooltips

---

e2e/cypress/integration/interactive_menu/basic_options_spec.js
e2e/cypress/support/task_commands.js
e2e/cypress/utils/index.js

Improve E2E test duration of interactive menu by using waitUntil instead of explicit wait when posting an incoming webhook
none

Improve E2E test duration of interactive menu by using waitUntil instead of explicit wait when posting an incoming webhook

---

e2e/cypress/integration/at_mentions/at_mentions_spec.js
e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
e2e/cypress/integration/enterprise/system_console/groups_assign_roles_spec.js

Fix failing tests on at mentions, keyboard shortcuts and LDAP group
non, failing on Cypress daily

Fix failing tests on at mentions, keyboard shortcuts and LDAP group

---

components/admin_console/team_channel_settings/channel/details/channel_details.tsx

Cherry pick of #5074 on release-5.22.
- #5074: Grab updated channel moderations from server after
/cc  @fm2munsh

Automated cherry pick of #5074

---

components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx

Cherry pick of #5082 on release-5.22.
- #5082: Fixed an issue where the new sidebar will not load

Automated cherry pick of #5082

---

e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
e2e/cypress/support/api_commands.js
e2e/cypress/support/hooks.js

Cherry pick of #5054 on release-5.22.
- #5054: MM-20900 Add basic unit tests for new sidebar
/cc  @hmhealey

Automated cherry pick of #5054

---

components/multiselect/__snapshots__/multiselect.test.tsx.snap
components/multiselect/multiselect.tsx
sass/components/_react-select.scss

MM-23364 - Updating react select UI
https://mattermost.atlassian.net/browse/MM-23364

MM-23364 - Updating react select UI

---

components/multiselect/__snapshots__/multiselect.test.tsx.snap
components/multiselect/multiselect.tsx
sass/components/_react-select.scss

Cherry pick of #5079 on release-5.22.
- #5079: MM-23364 - Updating react select UI

Automated cherry pick of #5079

---

components/suggestion/switch_channel_provider.jsx
components/suggestion/switch_channel_provider.test.jsx

Cherry pick of #5035 on release-5.22.
- #5035: make channel terms unique
/cc  @hahmadia

Automated cherry pick of #5035

---

e2e/cypress/integration/accessibility/accessibility_post_spec.js

Added E2E Cypress test to verify Accessibility support in Post
Fixes https://mattermost.atlassian.net/browse/MM-22631

Added E2E Cypress test to verify Accessibility support in Post

---

sass/layout/_headers.scss

MM-23269 - Updating bullets in header css
https://mattermost.atlassian.net/browse/MM-23269

MM-23269 - Updating bullets in header css

---

components/widgets/modals/full_screen_modal.tsx
e2e/cypress/integration/plugins/marketplace/marketplace_spec.js

Cherry pick of #5072 on release-5.22.
- #5072: unit test whitespacing

Automated cherry pick of #5072

---

e2e/cypress/fixtures/partial_default_config.json
e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
e2e/cypress/integration/channel/channel_name_tooltips_spec.js
e2e/cypress/integration/channel/message_reaction_spec.js
e2e/cypress/integration/channel/send_message_via_profile_popover_spec.js
e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
e2e/cypress/integration/email/mention_email_notification_spec.js
e2e/cypress/integration/enterprise/elasticsearch/channels_spec.js
e2e/cypress/integration/enterprise/elasticsearch/renaming_spec.js
e2e/cypress/integration/enterprise/elasticsearch/users_spec.js
e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
e2e/cypress/integration/enterprise/system_console/saml_metadata_spec.js
e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
e2e/cypress/integration/interactive_menu/basic_options_spec.js
e2e/cypress/integration/messaging/permalink_message_edit_spec.js
e2e/cypress/integration/messaging/remove_last_post_in_channel_spec.js
e2e/cypress/integration/messaging/tooltip_visual_verification_spec.js
e2e/cypress/integration/search/date_filter_spec.js
e2e/cypress/integration/team/invite_members_spec.js
e2e/cypress/support/api_commands.js
e2e/cypress/support/hooks.js

- fix failing tests on several spec files
- add `ExperimentalChannelSidebarOrganization` setting to partial config
- change API command from `createNewUser` to `apiCreateNewUser`

E2E: Fix daily tests on several spec files

---

components/legacy_team_sidebar/components/team_button.jsx
components/legacy_team_sidebar/legacy_team_sidebar_controller.jsx

Cherry pick of #5078 on release-5.22.
- #5078: Fixes swith teams shortcut after reorder teams feature was

Automated cherry pick of #5078

---

package-lock.json
package.json

- Related Redux: https://github.com/mattermost/mattermost-redux/pull/1096
https://mattermost.atlassian.net/browse/MM-23538

[MM-23538] Update redux hash to fix builds

---

package-lock.json
package.json

Cherry pick of #5128 on release-5.22.
- #5128: Update redux hash
/cc  @fm2munsh

Automated cherry pick of #5128

---

utils/utils.jsx

Cherry pick of #5077 on release-5.22.
- #5077: MM-22937 Fix Edge case by using includes instead of contains
/cc  @fm2munsh

Automated cherry pick of #5077

---

components/legacy_team_sidebar/components/team_button.jsx

After some digging it turned out that the events were working correctly in Desktop app, but the button wasn't draggable. Actually only the side indicator was draggable and working even before that change. Now that we are using the same component for webapp and desktop it works as expected. 
https://mattermost.atlassian.net/browse/MM-23448
Fix versions
v4.5 Desktop App

[MM-23448] - Fix drag and drop in desktop app

---

components/post_view/post_list_virtualized/post_list_virtualized.jsx
components/toast_wrapper/toast_wrapper.jsx

Cherry pick of #5109 on release-5.22.
- #5109: MM-23458 Fix missing toast for unreads

Automated cherry pick of #5109

---

Makefile

I just thought since we have a `make check-style`, it would be nice to also have a `make fix-style`.

[No-Ticket] Update MakeFile to include make fix-style

---

components/sidebar/__snapshots__/sidebar.test.tsx.snap
components/sidebar/channel_filter/__snapshots__/channel_filter.test.tsx.snap
components/sidebar/channel_filter/channel_filter.test.tsx
components/sidebar/sidebar.test.tsx
components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
components/sidebar/sidebar_category/sidebar_category.test.tsx
components/sidebar/sidebar_category/sidebar_category.tsx
components/sidebar/sidebar_category_list/__snapshots__/sidebar_category_list.test.tsx.snap
components/sidebar/sidebar_category_list/sidebar_category_list.test.tsx
components/sidebar/sidebar_category_list/sidebar_category_list.tsx
components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
components/sidebar/sidebar_channel/sidebar_base_channel/__snapshots__/sidebar_base_channel.test.tsx.snap
components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
components/sidebar/sidebar_channel/sidebar_channel.test.tsx
components/sidebar/sidebar_channel/sidebar_channel_close.tsx
components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap
components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx

These are unit tests for the new components currently in use in the new Experimental Sidebar.
Skipping QA since these are code changes that have no visual counterpart.
https://mattermost.atlassian.net/browse/MM-23515

[MM-23515] Unit Tests for new Experimental Sidebar

---

e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js

Cherry pick of #5110 on release-5.22.
- #5110: WIP\

Automated cherry pick of #5110

---

components/sidebar/__snapshots__/sidebar.test.tsx.snap
components/sidebar/channel_filter/__snapshots__/channel_filter.test.tsx.snap
components/sidebar/channel_filter/channel_filter.test.tsx
components/sidebar/sidebar.test.tsx
components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
components/sidebar/sidebar_category/sidebar_category.test.tsx
components/sidebar/sidebar_category/sidebar_category.tsx
components/sidebar/sidebar_category_list/__snapshots__/sidebar_category_list.test.tsx.snap
components/sidebar/sidebar_category_list/sidebar_category_list.test.tsx
components/sidebar/sidebar_category_list/sidebar_category_list.tsx
components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
components/sidebar/sidebar_channel/sidebar_base_channel/__snapshots__/sidebar_base_channel.test.tsx.snap
components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
components/sidebar/sidebar_channel/sidebar_channel.test.tsx
components/sidebar/sidebar_channel/sidebar_channel_close.tsx
components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap
components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx

Cherry pick of #5126 on release-5.22.
- #5126: WIP

Automated cherry pick of #5126

---

components/multiselect/multiselect.tsx
sass/components/_react-select.scss

* Improve direct messages multiselect styling

[MM-23414] Fix up multiselect styling (#5087)

---

components/legacy_sidebar/sidebar.jsx
components/sidebar/sidebar_category_list/sidebar_category_list.tsx

This logic was copied to the new sidebar before we disabled it in the old sidebar. I also updated the comment to explain the issue better.
https://mattermost.atlassian.net/browse/MM-23492

MM-23492 Remove automatic scrolling to channel from new sidebar

---

components/legacy_sidebar/sidebar.jsx
components/sidebar/sidebar_category_list/sidebar_category_list.tsx

Cherry pick of #5121 on release-5.22.
- #5121: MM-23492 Remove automatic scrolling to channel from new
/cc  @hmhealey

Automated cherry pick of #5121

---

components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
components/post_markdown/post_markdown.jsx

Cherry pick of #5151 on release-5.22.
- #5151: fix all posts getting highlighted even when they should
/cc  @hahmadia

Automated cherry pick of #5151

---

sass/layout/_sidebar-left.scss

Aligns navigator icons in desktop app vertically
https://mattermost.atlassian.net/browse/MM-23413

[MM-23413] - Align sidebar navigator icons vertically

---

sass/layout/_sidebar-left.scss

PR to fix the offset added by the announcement banner for the new channel sidebar.
https://mattermost.atlassian.net/browse/MM-23587

[MM-23587] Added CSS to account for the extra height added by announcement banner

---

components/create_post/create_post.jsx
components/create_post/create_post.test.jsx

Cherry pick of #5056 on release-5.22.
- #5056: Blur text box to reset before focusing

Automated cherry pick of #5056

---

utils/constants.jsx

Cherry pick of #5164 on release-5.22.
- #5164: MM-23543: Update 'Reset to Defaults' permissions to match
/cc  @mkraft

Automated cherry pick of #5164

---

sass/layout/_sidebar-left.scss

Cherry pick of #5156 on release-5.22.
- #5156: Added CSS to account for the extra height added by

Automated cherry pick of #5156

---

components/__snapshots__/quick_input.test.jsx.snap
components/quick_input.jsx
components/quick_input.test.jsx
i18n/en.json

Default to `Clear`, but allow future customization via a new prop. All existing instances of this component use the default.
Fixes: https://mattermost.atlassian.net/browse/MM-23559

MM-23559: change quick input "X" tooltip text

---

components/__snapshots__/quick_input.test.jsx.snap
components/quick_input.jsx
components/quick_input.test.jsx
i18n/en.json

Cherry pick of #5129 on release-5.22.
- #5129: MM-23559: change quick input X tooltip text

Automated cherry pick of #5129

---

e2e/cypress/integration/channel/mark_as_unread_spec.js
e2e/cypress/integration/enterprise/system_console/saml_metadata_spec.js

Fix failing Cypress tests on SAML and mark as unread
none, failing on Cypress daily

E2E:Fix failing Cypress tests on SAML and mark as unread

---

components/quick_input.jsx
components/quick_input.test.jsx

Cherry pick of #5099 on release-5.22.
- #5099: return focus to quick input

Automated cherry pick of #5099

---

components/channel_layout/channel_identifier_router/actions.js
components/channel_layout/channel_identifier_router/actions.test.js
components/post_view/post/post.jsx
package-lock.json
package.json

- If you create a channel with a name of length 40 it gets created as channel but it also shows up in the direct messages part of the sidebar because it creates a `group_channel_show` preference
https://mattermost.atlassian.net/browse/MM-23427
Has Redux Changes: https://github.com/mattermost/mattermost-redux/pull/1092

[MM-23427] Check existing channels before comparing to length of group id

---

components/create_post/create_post.jsx
components/create_post/create_post.test.jsx

Reverts mattermost/mattermost-webapp#5056

Revert "[MM-22482] Reset focus on CreatePost Textbox to address Firefox bug"

---

components/create_post/create_post.jsx
components/create_post/create_post.test.jsx

Cherry pick of #5185 on release-5.22.
- #5185: Reset focus on CreatePost Textbox to

Automated cherry pick of #5185

---

components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx

Don't crash when pasted custom theme missing values.
https://mattermost.atlassian.net/browse/MM-23456

MM-23456: Don't crash when pasted custom theme missing values.

---

components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
components/post_view/reaction/reaction.jsx

Cherry pick of #5161 on release-5.22.
- #5161: Remove extra line break in reaction overlay
/cc  @fm2munsh

Automated cherry pick of #5161

---

package-lock.json
package.json

Update rect-window hash https://github.com/mattermost/react-window/pull/27
https://mattermost.atlassian.net/browse/MM-22698

MM-22698 Fix for loading... in center channel for some zoom levels

---

components/toast_wrapper/toast_wrapper.jsx
components/toast_wrapper/toast_wrapper.test.jsx

Cherry pick of #5170 on release-5.22.
- #5170: MM-22757 Add missing atBottom condition for

Automated cherry pick of #5170

---

package-lock.json
package.json

Cherry pick of #5143 on release-5.22.
- #5143: MM-22698 Fix for loading... in center channel for some

Automated cherry pick of #5143

---

components/latex_block/latex_block.jsx

Cherry pick of #5119 on release-5.22.
- #5119: Set new limits for size and expand of KaTeX rendering
/cc  @DSchalla

Automated cherry pick of #5119

---

components/sidebar/__snapshots__/sidebar.test.tsx.snap
components/sidebar/add_channel_dropdown.tsx
components/sidebar/index.ts
components/sidebar/sidebar.test.tsx
components/sidebar/sidebar.tsx

Cherry pick of #5191 on release-5.22.
- #5191: Added proper permissions around

Automated cherry pick of #5191

---

actions/websocket_actions.jsx
e2e/cypress/integration/websocket/handle_removed_user_spec.js

Cherry pick of #5173 on release-5.22.
- #5173: Fixed the handleRemovedUserEvent to wait for

Automated cherry pick of #5173

---

e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
e2e/cypress/support/api_commands.js

Fix failing test on interactive dialog
none, failing test on Cypress daily

Fix failing test on interactive dialog

---

e2e/cypress/fixtures/account_setting_sections.json
e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
e2e/cypress/integration/enterprise/system_console/use_channel_mentions_system_scheme_spec.js
e2e/cypress/integration/enterprise/system_console/use_channel_mentions_team_scheme_spec.js

Cherry pick of #5189 on release-5.22.
- #5189: Fixed failures in channel_moderation_spec &
/cc  @srkgupta

Automated cherry pick of #5189

---

components/sidebar/sidebar_category_list/__snapshots__/sidebar_category_list.test.tsx.snap
components/sidebar/sidebar_category_list/sidebar_category_list.tsx

Cherry pick of #5175 on release-5.22.
- #5175: MM-23577 Update More Unread Indicators after animations
/cc  @hmhealey

Automated cherry pick of #5175

---

components/admin_console/group_settings/group_details/__snapshots__/group_profile.test.jsx.snap
components/admin_console/group_settings/group_details/group_profile.jsx
sass/components/_groups.scss

MM-23396 - Updating name spacing in groups page
https://mattermost.atlassian.net/browse/MM-23396

MM-23396 - Updating name spacing in groups page

---

package-lock.json
package.json

Redux update for https://github.com/mattermost/mattermost-redux/pull/1102
https://mattermost.atlassian.net/browse/MM-20550

[MM-20050] Update redux to latest

---

components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx

Cherry pick of #5202 on release-5.22.
- #5202: Fixed a bad import of a redux component in new sidebar

Automated cherry pick of #5202

---

NOTICE.txt

Cherry pick of #5190 on release-5.22.
- #5190: Update NOTICE.txt
/cc  @amyblais

Automated cherry pick of #5190

---

sass/components/_tooltip.scss

Cherry pick of #5177 on release-5.22.
- #5177: MM-11387: tweak tooltip CSS

Automated cherry pick of #5177

---

components/channel_layout/channel_identifier_router/channel_identifier_router.jsx
components/channel_layout/channel_identifier_router/channel_identifier_router.test.jsx
components/permalink_view/permalink_view.jsx
components/post_view/post_list/index.js
components/post_view/post_list/post_list.jsx
components/toast_wrapper/index.jsx
components/toast_wrapper/toast_wrapper.jsx
components/toast_wrapper/toast_wrapper.test.jsx

Cherry pick of #5188 on release-5.22.
- #5188: MM-23209 Fix for clicking on new messages toast before

Automated cherry pick of #5188

---

components/file_upload/__snapshots__/file_upload.test.jsx.snap
components/file_upload/file_upload.jsx
components/file_upload/file_upload.test.jsx

Cherry pick of #5211 on release-5.22.
- #5211: MM-23402 Fix for Mobile Web: Attach button only works with

Automated cherry pick of #5211

---

components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx
components/status_dropdown/status_dropdown.jsx
components/status_icon.tsx

Migrate 'components/status_icon.jsx' to TypeScript
https://github.com/mattermost/mattermost-server/issues/12437

[MM-18992] Migrate 'components/status_icon.jsx' to TypeScript

---

sass/components/_emojisprite.scss
sass/components/_emoticons.scss
sass/responsive/_mobile.scss

Cherry pick of #5230 on release-5.22.
- #5230: MM-23660 - Updating emoji popup on desktop and mobile

Automated cherry pick of #5230

---

e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
e2e/cypress/support/api_commands.js

Added step to activate guest user if Guest Access was disabled in any of previous tests
N/A. Updated test based on analysis of daily runs.

Added step to activate guest user if Guest Access was disabled in any of previous tests

---

components/integrations/bots/add_bot/add_bot.jsx
components/integrations/bots/bot.jsx
components/integrations/bots/bot.test.jsx
components/integrations/bots/bots.jsx
components/integrations/bots/bots.test.jsx
components/integrations/bots/index.js
components/invitation_modal/invitation_modal_confirm_step_row.jsx
components/post_profile_picture/post_profile_picture.jsx
components/post_view/channel_intro_message/channel_intro_message.jsx
components/suggestion/at_mention_provider/at_mention_suggestion.jsx
components/suggestion/search_user_provider.jsx
components/suggestion/switch_channel_provider.jsx
components/user_profile/user_profile.jsx
components/user_settings/general/user_settings_general.jsx
components/widgets/inputs/users_emails_input.jsx
utils/utils.jsx
utils/utils.test.jsx

Cherry pick of #5242 on release-5.22.
- #5242: MM-23715 Allow userIds or user objects for
/cc  @fm2munsh

Automated cherry pick of #5242

---

sass/layout/_sidebar-left.scss
utils/utils.jsx

Fixed a couple styling issues pointing out by @bradjcoughlin.
1. The sidebar header was missing the correct text colouring.
2. The border on the right on some themes wasn't visible.
https://mattermost.atlassian.net/browse/MM-23808

[MM-23808] Fixed the experimental sidebar header to use the correct themeing, also fixed the border.

---

sass/layout/_sidebar-left.scss
utils/utils.jsx

Cherry pick of #5260 on release-5.22.
- #5260: Fixed the experimental sidebar header to use the

Automated cherry pick of #5260

---

components/plugin_marketplace/marketplace_list/marketplace_list.jsx

Cherry pick of #5266 on release-5.22.
- #5266: Fix missing labels in Marketplace modal
/cc  @hanzei

Automated cherry pick of #5266

---

components/confirm_modal.test.tsx
components/confirm_modal.tsx

Cherry pick of #5270 on release-5.22.
- #5270: MM-23841 Allow confirm modal to update when state checked
/cc  @fm2munsh

Automated cherry pick of #5270

---

e2e/run_tests.js

Test Automation: send Cypress test data to Test automation dashboard.
Lambda function that takes care saving of each test item into the ReportPortal server - https://github.com/saturninoabril/mattermost-qa-automation/tree/master/serverless/cypress_reportportal (will transfer the repo to Mattermost org).
JIRA ticket: https://mattermost.atlassian.net/browse/MM-21542?filter=15119

MM-21542 Test Automation: send Cypress test data to Test automation dashboard

---

components/invitation_modal/__snapshots__/invitation_modal_initial_step.test.jsx.snap
components/invitation_modal/invitation_modal.jsx
components/invitation_modal/invitation_modal.test.jsx
components/invitation_modal/invitation_modal_initial_step.jsx
components/root_portal.jsx
components/widgets/modals/full_screen_modal.tsx

Fixing javascript errors in the invitation process. Added some tests that needed to fix other things to make it working properly.
The added tests fail before the change and works with the change.
[MM-23856](https://mattermost.atlassian.net/browse/MM-23856)

Fixing javascript errors in the invitation process

---

actions/websocket_actions.jsx
actions/websocket_actions.test.jsx

Remove unneeded duplicated requests for statuses
[MM-23423](https://mattermost.atlassian.net/browse/MM-23423)

Remove unneeded duplicated requests for statuses

---

components/invitation_modal/__snapshots__/invitation_modal_initial_step.test.jsx.snap
components/invitation_modal/invitation_modal.jsx
components/invitation_modal/invitation_modal.test.jsx
components/invitation_modal/invitation_modal_initial_step.jsx
components/root_portal.jsx
components/widgets/modals/full_screen_modal.tsx

Cherry pick of #5275 on release-5.22.
- #5275: Fixing javascript errors in the invitation process
/cc  @jespino

Automated cherry pick of #5275

---

e2e/cypress/integration/messaging/permalink_message_edit_spec.js
e2e/cypress/integration/messaging/post_header_spec.js
e2e/cypress/support/ui_commands.js

E2E: Fix failing tests on permalink and post header

---

e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js

Added E2E test to Verify Quick Navigation support across different regions in the app
Fixes https://mattermost.atlassian.net/browse/MM-22626

Added E2E test to Verify Quick Navigation support across different regions in the app

---

components/channel_view/index.js

Cherry pick of #5301 on release-5.22.
- #5301: MM-24035 Fix DM with deactivated user
/cc  @fm2munsh

Automated cherry pick of #5301

---

components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
components/invitation_modal/invitation_modal.jsx
components/invitation_modal/invitation_modal_members_step.jsx
components/invitation_modal/invitation_modal_members_step.test.jsx

Cherry pick of #5297 on release-5.22.
- #5297: MM-23977 Ensure users not in team when searching for
/cc  @fmunshi

Automated cherry pick of #5297

---

e2e/cypress/integration/onboarding/existing_email_adress_spec.js

Fix module error in existing email spec
none, failing on daily Cypress

Fix module error in existing email spec

---

e2e/package-lock.json
e2e/package.json
e2e/run_tests.js

(Experimental) Use superagent when sending Cypress test report since there seemed to be an issue with axios.
none, not working on daily Cypress report

Quick fix: use superagent when sending Cypress test report

---

components/integrations/bots/add_bot/add_bot.jsx
components/integrations/bots/add_bot/index.js

Cherry pick of #5294 on release-5.22.
- #5294: MM-23995 Pass bot user to props correctly
/cc  @fmunshi

Automated cherry pick of #5294

---

components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
components/edit_post_modal/edit_post_modal.jsx
components/edit_post_modal/edit_post_modal.test.jsx
components/edit_post_modal/index.js

#5296
* MM-23997 Ensure channel mentions permission is set on edit post
* Fix linting

[MM-23997] Cherry pick

---

components/channel_layout/channel_identifier_router/actions.js
package-lock.json
package.json

- Updates redux for release-5.19 to resolve https://mattermost.atlassian.net/browse/MM-23427
- Also manually adds required changes to `actions.js` since the file has undergone refactoring I could not cherry-pick the entire commit cleanly without making significant changes
Redux PR Merged since it was a straightforward cherry pick: https://github.com/mattermost/mattermost-redux/pull/1124
Original Web PR: https://github.com/mattermost/mattermost-webapp/pull/5095

[MM-23427] Update redux and manually add selected changes for MM-23427

---

e2e/cypress/integration/accessibility/accessibility_keyboard_usability_spec.js

Added E2E Cypress test to verify Accessibility keyboard usability across different regions in the app
Fixes https://mattermost.atlassian.net/browse/MM-24051

MM-24051 Added E2E Cypress test to verify Accessibility keyboard usability across different regions in the app

---

components/confirm_modal.tsx

Fixing discard changes confirm modal accesibility for invitation process
[MM-20934](https://mattermost.atlassian.net/browse/MM-20934)

Fixing discard changes confirm modal accesibility for invitation process

---

components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
components/admin_console/team_channel_settings/team/details/team_profile.jsx
package-lock.json
sass/components/_groups.scss
sass/components/_team-channel-settings.scss

Made minor adjustments to the Team Pages per Mike.
https://mattermost.atlassian.net/browse/MM-21401

MM-21401: Minor adjustments to Team Pages

---

e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js

Fixed tests based on Channel switcher changes
N/A. Fixed based on daily runs.

Fixed tests based on Channel switcher changes

---

e2e/cypress/integration/account_settings/general/fullname_spec.js
e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_spec.js
e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js

Fix tests failing on username, fullname, nickname
NA

Fix username, fullname, nickname

---

sass/components/_channel-switcher.scss
sass/components/_modal.scss
sass/components/_search.scss
sass/responsive/_mobile.scss

MM-23879 - Updating search spacing
MM-24112 - Updating spinner position in search
MM-24121 - Updating scroll and default position of edit post textbox
MM-24047 - Updating color variable for close icon
https://mattermost.atlassian.net/browse/MM-23879
https://mattermost.atlassian.net/browse/MM-24112
https://mattermost.atlassian.net/browse/MM-24121
https://mattermost.atlassian.net/browse/MM-24047

MM-23879 - Minor UI Fixes

---

components/widgets/badges/badge.scss
components/widgets/menu/menu_group.scss
sass/components/_suggestion-list.scss

MM-24147 - Updating autocomplete UI issues
https://mattermost.atlassian.net/browse/MM-24147

MM-24147 - Updating autocomplete UI issues

---

components/post_view/post_body/post_body.jsx

Cherry pick of #5241 on release-5.23.
- #5241: Show parent post link when deleting first reply

Automated cherry pick of #5241

---

components/admin_console/permission_schemes_settings/guest_permissions_tree/index.jsx
components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
components/admin_console/permission_schemes_settings/permission_team_scheme_settings/index.jsx
components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.jsx
components/admin_console/permission_schemes_settings/permissions_tree/index.jsx
e2e/cypress/integration/enterprise/system_console/team_guest_channel_spec.js

Cherry pick of #5061  on release-5.23.
Co-authored-by: mattermod <mattermod@users.noreply.github.com>
(cherry picked from commit 576ff3a8ad3fac69f6dad558afa72c99f796e004)

MM-23197: Add Guest permissions to Team Override Settings. (#5061)

---

e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js

Cherry Pick of https://github.com/mattermost/mattermost-webapp/pull/5218#event-3246221549

Cherry pick of https://github.com/mattermost/mattermost-webapp/pull/5218#event-3246221549

---

actions/post_actions.jsx
actions/post_actions.test.js

Cherry pick of #5343 on release-5.23.
- #5343: Get channel memberships if undefined or null

Automated cherry pick of #5343

---

components/channel_header/__snapshots__/channel_header.test.jsx.snap
components/channel_header/channel_header.js
sass/components/_channel-header__icon.scss
sass/layout/_headers.scss
utils/utils.jsx

MM-24445 - Updating channel header icon css
**The zoom icon will be updated in a separate PR.**
https://github.com/mattermost/mattermost-plugin-zoom/pull/104
https://mattermost.atlassian.net/browse/MM-24445

MM-24445 - Updating channel header icon css

---

e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
e2e/cypress/integration/accessibility/accessibility_image_spec.js
e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
e2e/cypress/integration/accessibility/accessibility_post_spec.js

Added Cypress tests to verify accessibility support in images & incoming messages
Fixes https://mattermost.atlassian.net/browse/MM-24075
Fixes https://mattermost.atlassian.net/browse/MM-24078

Added Cypress tests to verify accessibility support in images & incoming messages

---

components/channel_view/__snapshots__/channel_view.test.jsx.snap
components/channel_view/channel_view.jsx
components/channel_view/channel_view.test.jsx
components/channel_view/index.js

Cherry pick of #5337 on release-5.23.
- #5337: MM-22802 Dont show createPost until channel roles are
/cc  @fmunshi

Automated cherry pick of #5337

---

sass/components/_modal.scss

MM-24392 - Updating modal css
https://mattermost.atlassian.net/browse/MM-24392

MM-24392 - Updating modal css

---

actions/websocket_actions.jsx
utils/constants.jsx

Cherry pick of #5344 on release-5.23.
- #5344: MM-23605 Reload team memberships when team scheme is
/cc  @fmunshi

Automated cherry pick of #5344

---

components/shortcuts_modal.jsx
utils/utils.jsx

Cherry pick of #5319 on release-5.23.
- #5319: MM-24108 Disable next/prev team shortcuts on Linux
/cc  @hmhealey

Automated cherry pick of #5319

---

components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx

[MM-23384] Readded div to wrap around contents of OverlayTrigger (#5386) - CherryPick

---

components/suggestion/search_channel_suggestion/search_channel_suggestion.jsx

Cherry pick of #5403 on release-5.23.
- #5403: Highlight hovered items when searching with "in:"

Automated cherry pick of #5403

---

sass/components/_post.scss

MM-24311 - Updating min height for preview textarea
https://mattermost.atlassian.net/browse/MM-24311

MM-24311 - Updating min height for preview textarea

---

components/suggestion/search_channel_with_permissions_provider.jsx
sass/components/_suggestion-list.scss

MM-24487 - Updating icons in invite modal dropdown
https://mattermost.atlassian.net/browse/MM-24487

MM-24487 - Updating icons in invite modal dropdown

---

components/channel_view/index.js
e2e/cypress/integration/channel/channel_menu_spec.js

Cherry pick of #5417 on release-5.23.
- #5417: MM-24590: fix roles check on leave

Automated cherry pick of #5417

---

package-lock.json
package.json

Bumping mattermost-redux to the last release-5.23 branch HEAD
[MM-24080](https://mattermost.atlassian.net/browse/MM-24080)

Bumping mattermost-redux to the last release-5.23 branch HEAD

---

components/channel_header_dropdown/menu_items/close_message/close_message.js
components/channel_header_dropdown/menu_items/close_message/close_message.test.js
components/channel_header_dropdown/menu_items/close_message/index.js
e2e/cypress/integration/channel/close_direct_group_spec.js
e2e/cypress/support/ui_commands.js

Cherry pick of #5422 on release-5.23.
- #5422: Fix closing DM/GM from header dropdown menu

Automated cherry pick of #5422

---

e2e/cypress/integration/account_settings/general/nickname_spec.js

Fix for failing tests on nickname spec
none, failing on Cypress daily test

E2E: Fix for failing tests on nickname spec

---

components/admin_console/group_settings/group_details/group_profile_and_settings.jsx
i18n/en.json

- Mark Group Mention feature as beta as requested by Dennis 
- https://mattermost.atlassian.net/browse/MM-24966

MM-24966 Update group mention toggle to include (Beta)

---

e2e/cypress/integration/mark_as_unread/mark_as_unread_spec.js
e2e/cypress/integration/toast/toast_spec.js

Fix failing tests on mark as unread and toast specs
none - failing on daily Cypress test

E2E: Fix failing tests on mark as unread and toast specs

---

e2e/cypress/integration/enterprise/system_console/team_scheme_permission_spec.js
e2e/cypress/integration/keyboard_shortcuts/alt_option_plus_up_down_spec.js

Fix failing tests due to disabled post textbox
none, failing on Cypress daily
Jira ticket - https://mattermost.atlassian.net/browse/MM-25019

MM-25019 E2E: Fix failing tests due to disabled post textbox

---

e2e/cypress/support/index.js

Added missing file path Cypress.spec.name
NA

Added missing file path Cypress.spec.name

---

.circleci/config.yml

Increase resource size and add debug information.

Increase resource size for testing purposes

---

.circleci/config.yml

https://github.com/mattermost/mattermost-webapp/pull/5510

Cherry pick image fix into 5.19

---

.circleci/config.yml

https://github.com/mattermost/mattermost-webapp/pull/5510

Cherry pick fix image.

---

.circleci/config.yml

https://github.com/mattermost/mattermost-webapp/pull/5510

Fix branch.

---

.circleci/config.yml

Resolve conflicts.

---

.circleci/config.yml

Cherry pick fix image 5.16

---

.circleci/config.yml

Cherry pick fix image release 5.13

---

package-lock.json
package.json
webpack.config.js

Builds a copy of each JS and CSS file in a Brotli encoding with a .br suffix.
https://mattermost.atlassian.net/browse/MM-25095
https://github.com/mattermost/mattermost-server/pull/14524

MM-25095: Compress JS and CSS files with Brotli.

---

actions/user_actions.jsx
actions/user_actions.test.js
components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx
components/admin_console/team_channel_settings/channel/details/channel_details.tsx
components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.test.tsx
components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
components/admin_console/team_channel_settings/channel/details/channel_members/index.ts
components/admin_console/team_channel_settings/channel/details/index.js
components/channel_invite_modal/__snapshots__/channel_invite_modal.test.jsx.snap
components/channel_invite_modal/channel_invite_modal.jsx
components/channel_invite_modal/channel_invite_modal.test.jsx
components/channel_invite_modal/index.js
components/channel_members_modal/channel_members_modal.tsx
i18n/en.json
utils/test_helper.ts

https://github.com/mattermost/mattermost-webapp/pull/5480

[MM-14912] Add channel members block [cherry-pick]

---

components/__snapshots__/setting_picture.test.jsx.snap
components/setting_picture.jsx
components/setting_picture.test.jsx
components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap
components/team_general_tab/team_general_tab.jsx
components/team_general_tab/team_general_tab.test.jsx
components/user_settings/general/index.js
components/user_settings/general/user_settings_general.jsx
components/user_settings/general/user_settings_general.test.js

Cherry pick of #5465 on release-5.24.
- #5465: Disable changing picture if LDAP sync'ed
/cc  @sbishel

Automated cherry pick of #5465

---

components/admin_console/team_channel_settings/abstract_list.jsx
components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
components/admin_console/team_channel_settings/channel/list/channel_list.tsx
components/admin_console/team_channel_settings/group/__snapshots__/group_list.test.tsx.snap
components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.jsx.snap
components/admin_console/team_channel_settings/team/list/team_list.jsx
sass/components/_team-channel-settings.scss

Cherry pick of #5502 on release-5.24.
- #5502: fix search bar disappearing
/cc  @hahmadia

Automated cherry pick of #5502

---

components/__snapshots__/textbox.test.jsx.snap
components/suggestion/at_mention_provider/at_mention_provider.jsx
components/suggestion/command_provider.jsx
components/suggestion/command_provider.test.js
components/suggestion/suggestion_box.jsx
package-lock.json

Cherry pick of #5499 on release-5.24.
- #5499: autocomplete suggestions (#5289)
/cc  @iomodo

Automated cherry pick of #5499

---

components/admin_console/group_settings/group_details/__snapshots__/group_profile.test.jsx.snap
components/admin_console/group_settings/group_details/__snapshots__/group_profile_and_settings.test.jsx.snap
components/admin_console/group_settings/group_details/group_profile.jsx
components/admin_console/group_settings/group_details/group_profile_and_settings.jsx
e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
e2e/cypress/support/api_commands.js
sass/components/_groups.scss

- Manual cherry-pick of of #5530

[MM-23937] [cherry-pick] Add e2e tests for group mentions (#5530)

---

actions/user_actions.jsx
components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
components/admin_console/team_channel_settings/channel/details/channel_groups.tsx
components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
components/admin_console/team_channel_settings/channel/details/channel_modes.tsx
components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.jsx.snap
components/admin_console/team_channel_settings/team/details/team_groups.jsx
components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx
components/admin_console/team_channel_settings/team/details/team_modes.jsx
components/admin_console/user_grid/user_grid.tsx
components/admin_console/user_grid/user_grid_role_dropdown.tsx
components/toggle_modal_button.jsx
e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
e2e/cypress/integration/enterprise/system_console/channel_members_spec.js
e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
e2e/cypress/integration/enterprise/system_console/session_length_spec.js
e2e/cypress/integration/enterprise/system_console/team_members_spec.js
e2e/cypress/integration/system_console/session_length_spec.js

Cherry pick of #5546 on release-5.24.
- #5546: Add e2e tests for TeamMembers block
/cc  @fmunshi

Automated cherry pick of #5546

---

sass/components/_suggestion-list.scss

MM-24211 - Updating emoji list css
https://mattermost.atlassian.net/browse/MM-24211

MM-24211 - Updating emoji list css

---

sass/components/_suggestion-list.scss

Cherry pick of #5558 on release-5.24.
- #5558: MM-24211 - Updating emoji list css

Automated cherry pick of #5558

---

sass/components/_team-channel-settings.scss

MM-25032 - Fixing margins of channels name
https://mattermost.atlassian.net/browse/MM-25032

MM-25032 - Fixing margins of channels name

---

sass/components/_team-channel-settings.scss

Cherry pick of #5557 on release-5.24.
- #5557: MM-25032 - Fixing margins of channels name

Automated cherry pick of #5557

---

components/sidebar/sidebar_category_list/sidebar_category_list.tsx

Cherry pick of #5533 on release-5.24.
- #5533: Fixed keyboard shortcut on new channel sidebar

Automated cherry pick of #5533

---

actions/websocket_actions.jsx

Cherry pick of #5573 on release-5.24.
- #5573: update websocket actions
/cc  @hahmadia

Automated cherry pick of #5573

---

components/channel_view/__snapshots__/channel_view.test.jsx.snap
components/channel_view/channel_view.jsx
components/channel_view/channel_view.test.jsx
components/post_view/post_list/index.js
components/post_view/post_list/post_list.jsx
components/post_view/post_list/post_list.test.jsx
components/post_view/post_view.jsx
components/post_view/post_view.test.js

There were some conflicts, so I needed to do the cherry-picking manually.

Manual cherry pick of #5385

---

sass/layout/_navigation.scss

Cherry pick of #5560 on release-5.24.
- #5560: Force red background on mobile view header

Automated cherry pick of #5560

---

i18n/en.json

Cherry pick of #5568 on release-5.24.
- #5568: Update en.json
/cc  @amyblais

Automated cherry pick of #5568

---

utils/paste.test.tsx

Cherry pick of #5559 on release-5.24.
- #5559: MM-25357 Fix tests for formatGithubCodePaste

Automated cherry pick of #5559

---

e2e/cypress/integration/messaging/message_reaction_spec.js

Add visibility check and force click to emoji picker item
Jira ticket - https://mattermost.atlassian.net/browse/MM-25479

MM-25479 Fix failing test on emoji picker item

---

e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
e2e/cypress/integration/interactive_menu/basic_options_spec.js
e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js

Fix misc prod tests

---

sass/components/_search.scss
utils/utils.jsx

Cherry pick of #5592 on release-5.24.
- #5592: Switch to css variable for search options

Automated cherry pick of #5592

---

components/admin_console/group_settings/group_details/group_details.jsx
components/admin_console/group_settings/group_details/group_details.test.jsx
components/admin_console/group_settings/group_details/group_profile.jsx
components/admin_console/group_settings/group_details/group_profile_and_settings.jsx
package-lock.json

Cherry pick of #5569 on release-5.24.
- #5569: update group name if id pattern
/cc  @sbishel

Automated cherry pick of #5569

---

actions/views/channel_sidebar.ts
components/edit_category_modal/edit_category_modal.tsx
components/sidebar/sidebar.tsx
components/sidebar/sidebar_category/sidebar_category.tsx
components/sidebar/sidebar_channel/sidebar_channel.tsx
components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
components/widgets/menu/menu_items/submenu_item.tsx

I had missed hooking up the newly designed `edit_category_modal` as per HH's request to the channel menu's 'Move to New Category' option. This PR hooks that up.
https://mattermost.atlassian.net/browse/MM-25509

[MM-25509] Setup channel menu to use new modal style

---

package-lock.json
package.json

The actual changes for this are here: https://github.com/mattermost/marked/pull/18
https://mattermost.atlassian.net/browse/MM-25449

MM-25449 Update regex used for trimming strings

---

sass/components/_popover.scss

Cherry pick of #5594 on release-5.24.
- #5594: Restored scrolling to autocomplete popover in

Automated cherry pick of #5594

---

components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
components/link_tooltip/link_tooltip.test.tsx
components/link_tooltip/link_tooltip.tsx
utils/__snapshots__/message_html_to_component.test.jsx.snap
utils/message_html_to_component.jsx

Cherry pick of #5507 on release-5.24.
- #5507: Pass data attributes to LinkTooltip component

Automated cherry pick of #5507

---

e2e/cypress/integration/accessibility/accessibility_buttons_spec.js

Fix accessibility buttons

---

e2e/utils/report.js

Minor update on Cypress report
none, observed on Jira

Quick fix: minor update on Cypress report

---

e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js

- fix padding in message_reply_input_box_expand_spec
- fix text selector accessibility_input_fields_spec
NA

Fix input specs

---

actions/views/channel.js
e2e/cypress/integration/channel/archived_channels_spec.js
e2e/cypress/support/ui_commands.js

Cherry pick of #5518 on release-5.24.
- #5518: Re-read state after it is updated in leaveChannel

Automated cherry pick of #5518

---

NOTICE.txt

Cherry pick of #5599 on release-5.24.
- #5599: Update NOTICE.txt
/cc  @amyblais

Automated cherry pick of #5599

---

actions/views/rhs.js
actions/views/rhs.test.js
actions/websocket_actions.test.jsx
plugins/actions.js
plugins/index.js
plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
plugins/pluggable/pluggable.test.jsx
plugins/rhs_plugin/index.js
plugins/rhs_plugin/rhs_plugin.jsx
reducers/views/rhs.js
reducers/views/rhs.test.js
selectors/rhs.ts
types/store/rhs.ts

Manual cherry-pick of https://github.com/mattermost/mattermost-webapp/pull/5598#event-3392925410 into release-5.24

Manual cherry-pick of #5598 into release-5.24

---

package-lock.json
package.json

https://github.com/mattermost/mattermost-redux/pull/1164

Update mattermost-redux to re-add missing Client4 method

---

components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.jsx.snap
components/post_view/post_add_channel_member/post_add_channel_member.jsx
components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
i18n/en.json

Cherry pick of #5637 on release-5.24.
- #5637: MM-25685 Change out of channel system message to show X
/cc  @fmunshi

Automated cherry pick of #5637

---

sass/routes/_admin-console.scss

Cherry pick of #5629 on release-5.24.
- #5629: Added extra padding on admin console sidebar when

Automated cherry pick of #5629

---

sass/layout/_headers.scss
sass/layout/_legacy-sidebar-left.scss
sass/layout/_sidebar-left.scss
sass/layout/_team-sidebar.scss

Cherry pick of #5644 on release-5.24.
- #5644: Updating z-order for channel header and sidebar

Automated cherry pick of #5644

---

e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js

- Update `mfaEdit` id selector
NA

Fix accessibility account settings

---

e2e/cypress/integration/search_date_filter/date_filter_spec.js
e2e/cypress/integration/search_date_filter/negative_filter_spec.js

- Fix no results message verification; included original query
NA

Fix no results message

---

e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js

- Update label for Do not disturb (applies to master only)
NA

Fix accessibility dropdowns

---

e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js

- Shorten test channel name; the original was too long and was probably hitting the length limit
NA

Fix channel name

---

e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js

- only fixes the case ` Invite Member via Email containing upper case letters`
NA

Fix test: Invite Member via Email containing upper case letters

---

e2e/cypress/integration/multi_team_and_dm/system_message_spec.js
e2e/cypress/support/api_commands.d.ts
e2e/cypress/support/ui_commands.d.ts
e2e/cypress/support/ui_commands.js

Fix failing test on system message by waiting for a message if posted before continuing test.
none, failing daily Cypress test - master prod

E2E: Fix failing test on system message by waiting for a message if posted before continuing test

---

components/__snapshots__/quick_input.test.jsx.snap
components/quick_input.jsx
components/quick_input.test.jsx
components/search_bar/__snapshots__/search_bar.test.jsx.snap
components/search_bar/search_bar.jsx
components/search_hint/__snapshots__/search_hint.test.tsx.snap
components/search_hint/search_hint.tsx

Cherry-pick of https://github.com/mattermost/mattermost-webapp/pull/5647

[MM-25757] - Add latest UI requirements to search hint popover (#5647)

---

components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
components/admin_console/team_channel_settings/channel/details/channel_members/index.ts
components/admin_console/team_channel_settings/team/details/team_members/index.ts
components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx
package-lock.json
package.json

- Manual Cherry pick of https://github.com/mattermost/mattermost-webapp/pull/5662

[cherry-pick] [MM-25771] Dont show deleted profiles on team and channel members

---

components/admin_console/user_grid/user_grid.tsx

- Prevents bombbarding the server with requests if a user is deleted in a different tab
- Fixes https://mattermost.atlassian.net/browse/MM-25860

[ MM-25860] Ensure calls to load page are only made once

---

components/admin_console/user_grid/user_grid.tsx

Cherry pick of #5686 on release-5.24.
- #5686: Ensure calls to load page are only made once to prevent
/cc  @fmunshi

Automated cherry pick of #5686

---

components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
components/admin_console/team_channel_settings/team/details/team_profile.jsx
sass/routes/_admin-console.scss

MM-24361 - Updating system console save button
https://mattermost.atlassian.net/browse/MM-24361
**Before:**
**After:**

MM-24361 - Updating system console save button

---

utils/admin_console_index.test.jsx

Cherry pick of #5695 on release-5.24.
- #5695: Modify admin console index tests to ignore order check when
/cc  @fmunshi

Automated cherry pick of #5695

---

e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
e2e/cypress/integration/enterprise/ldap_group/groups_assign_roles_spec.js
e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js

Updated few unstable cypress tests based on failures
NA

Updated few cypress tests based on failures

---

e2e/cypress/integration/messaging/strikethrough_spec.js

- Added delay after text is typed
NA

E2E: Fix strikethrough spec

---

e2e/cypress/integration/menus/main_menu_spec.js

- need to create new user and login
NA

E2E: Fix main menu spec

---

root.html

Reverts https://github.com/mattermost/mattermost-webapp/pull/5654 as an attempted fix for https://mattermost.atlassian.net/browse/MM-26065 per suggestion here: https://community-daily.mattermost.com/core/pl/r5bjwmbfrifm3djs5zeiczwy4r.
https://mattermost.atlassian.net/browse/MM-26065
https://github.com/mattermost/mattermost-webapp/pull/5654

MM-26065: Revert pr 5654.

---

package-lock.json
package.json
webpack.config.js

Reverts Brotli compression until subpath support is solved.
https://mattermost.atlassian.net/browse/MM-26065
https://github.com/mattermost/mattermost-server/pull/14834

MM-26065: Reverts Brotli support.

---

components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
components/link_tooltip/link_tooltip.tsx

Cherry pick of #5712 on release-5.25.
- #5712: MM-25904 - Updating link tooltips z-index for plugins

Automated cherry pick of #5712

---

components/channel_selector_modal/channel_selector_modal.jsx
e2e/cypress/integration/system_console/group_configuration_spec.js

Cherry pick of #5697 on release-5.25.
- #5697: MM-25933: Do not exclude default channels from channel
/cc  @mkraft

Automated cherry pick of #5697

---

components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap

Master build is broken due to some out of date snapshots broken from PR https://github.com/mattermost/mattermost-webapp/pull/5744

Update link tooltip snapshots

---

components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
components/link_tooltip/link_tooltip.test.tsx
components/link_tooltip/link_tooltip.tsx
utils/__snapshots__/message_html_to_component.test.jsx.snap
utils/message_html_to_component.jsx

Cherry pick of #5744 for a 5.24 dot release
https://mattermost.atlassian.net/browse/MM-25808

Manual cherrypick of #5744 - Fix LinkTooltip with uncommon link format

---

components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
components/admin_console/team_channel_settings/team/details/team_profile.jsx
sass/routes/_admin-console.scss

Cherry pick of #5659 on release-5.25.
- #5659: MM-24361 - Updating system console save button

Automated cherry pick of #5659

---

components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.jsx.snap
components/announcement_bar/configuration_bar/configuration_bar.jsx
components/announcement_bar/configuration_bar/configuration_bar.test.jsx

Fix Id property for link in ConfigurationBar
https://mattermost.atlassian.net/browse/MM-25951

MM-25951: Fix license id in link

---

components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.jsx.snap
components/announcement_bar/configuration_bar/configuration_bar.jsx
components/announcement_bar/configuration_bar/configuration_bar.test.jsx

Cherry pick of #5767 on release-5.25.
- #5767: update License.Id for link, write unit tests
/cc  @sbishel

Automated cherry pick of #5767

---

sass/components/_select.scss

Cherry pick of #5771 on release-5.25.
- #5771: Remove hardcoded border color in form controls

Automated cherry pick of #5771

---

e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js

- Update aria label order
- Update create team selector
Note: applies to master only
NA

E2E: Fix accessibility dropdowns

---

components/admin_console/group_settings/group_details/group_details.jsx
i18n/en.json

Updated to handle specific error from the server
https://mattermost.atlassian.net/browse/MM-26388

MM-26388 - Update error handling from server

---

components/legacy_sidebar/header/dropdown/sidebar_header_dropdown.jsx
components/legacy_sidebar/header/sidebar_header_dropdown_button.jsx
components/status_dropdown/status_dropdown.jsx
i18n/en.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json
sass/layout/_headers.scss

Cherry pick of #5336 on release-5.25.
- [MM-22828] Improve the Main Menu popover position/placement (#5336)
[MM-22828]: https://mattermost.atlassian.net/browse/MM-22828

Cherry pick of #5336

---

components/post_view/post_info/post_info.jsx
components/rhs_comment/rhs_comment.jsx
components/rhs_root_post/rhs_root_post.jsx
components/search_results_item/search_results_item.jsx

Cherry pick of #5571 on release-5.25.
- #5571: Fix post card icon CSS
/cc  @larkox

Automated cherry pick of #5571

---

components/admin_console/group_settings/group_details/group_details.jsx
i18n/en.json

Cherry pick of #5784 on release-5.25.
- #5784: update error handling from server
/cc  @sbishel

Automated cherry pick of #5784

---

components/suggestion/search_channel_suggestion/index.js
components/suggestion/search_channel_suggestion/search_channel_suggestion.jsx

Cherry pick of #5791 on release-5.25.
- #5791: fix avatar for dms

Automated cherry pick of #5791

---

components/create_comment/create_comment.jsx
components/create_comment/create_comment.test.jsx
components/create_post/create_post.jsx
components/create_post/create_post.test.jsx
components/edit_post_modal/edit_post_modal.jsx
utils/paste.tsx

Cherry pick of #5782 on release-5.25.
- #5782: allow pasting tables into edit post, keep

Automated cherry pick of #5782

---

components/create_comment/create_comment.test.jsx
components/create_post/create_post.test.jsx

Quick fix on failing unit tests.
Related PR - https://github.com/mattermost/mattermost-webapp/pull/5797
none

Quick fix on failing unit tests

---

components/member_list_team/member_list_team.tsx
components/searchable_user_list/searchable_user_list.jsx

Cherry pick for 5.25 of
[MM-26532] Fix team members modal user count issues (#5798)
mattermost.atlassian.net/browse/MM-26532
mattermost.atlassian.net/browse/MM-26022
https://github.com/mattermost/mattermost-webapp/pull/5798
[MM-26532]: https://mattermost.atlassian.net/browse/MM-26532

Cherry-pick for 5.25, [MM-26532] Fix team members modal user count issues (#5798)

---

e2e/run_tests.js
e2e/save_report.js
e2e/utils/constants.js
e2e/utils/report.js

Add test environment details to reports
JIRA ticket: https://mattermost.atlassian.net/browse/MM-26560

MM-26560 Add test environment details to reports

---

e2e/cypress/support/api_commands.js

Fix failing E2E tests in Okta login flow
none, failing on Cypress

Cypress/E2E: Fix failing tests in Okta login flow

---

e2e/cypress/integration/integrations/incoming_webhook/disallow_username_profile_override_spec.js
e2e/cypress/integration/integrations/incoming_webhook/helpers.js
e2e/cypress/integration/integrations/incoming_webhook/setup_incoming_webhook_spec.js

Cypress/E2E for setting up incoming webhook via UI
Jira ticket: https://mattermost.atlassian.net/browse/MM-26069
TM4J ticket: [MM-T2029](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2029)

MM-26069 Cypress test for MM-T2029 - Setup for incoming webhook

---

e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js

Cypress/E2E on Clock Display Settings
Jira ticket: https://mattermost.atlassian.net/browse/MM-26074
TM4J tickets: [MM-T2098](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2098) and [MM-T2096](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2096)

MM-26074 Cypress test for MM-T2098 and MM-T2096 - Clock Display Settings

---

components/setting_item_min/setting_item_min.tsx
components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.tsx.snap
components/user_settings/sidebar/user_settings_sidebar.test.tsx
components/user_settings/sidebar/user_settings_sidebar.tsx

Fix failing test on user settings sidebar due to unexpected type of SettingItemMin describe props.
Other failing tests were fixed by https://github.com/mattermost/mattermost-webapp/pull/5820
Jira ticket - https://mattermost.atlassian.net/browse/MM-26512

MM-26512 Fix type of SettingItemMin describe props

---

e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
e2e/cypress/support/api_commands.js
e2e/cypress/support/external_commands.d.ts
e2e/cypress/support/external_commands.js
e2e/cypress/support/index.js
e2e/cypress/support/task_commands.js

Added couple of Cypress test for Guest Account Feature
JIRA Ticket: [MM-26072](https://mattermost.atlassian.net/browse/MM-26072)
TM4J Tickets: [MM-T1414](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1414) and [MM-T1417](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1417)

Added Cypress test MM-T1414 and MM-T1417

---

actions/websocket_actions.jsx
utils/constants.jsx

Channels need to be explicitly added to the sidebar now to show up. This is already done when the user joins or creates a new channel, but it's currently not done when another user adds them to one.
https://mattermost.atlassian.net/browse/MM-26627

MM-26627 Add channels to sidebar when the user is invited to them

---

components/create_comment/__snapshots__/create_comment.test.jsx.snap
components/create_comment/create_comment.jsx
components/favicon_title_handler/favicon_title_handler.tsx
components/status_dropdown/status_dropdown.jsx
components/toggle_modal_button_redux/toggle_modal_button_redux.jsx

Fixing some more warnings that I found when working on #5835. There are a few more warnings coming from the new sidebar code, but I don't want to change them yet since they'll likely conflict with the feature branch.

Fix random dev mode warnings

---

utils/utils.jsx

Fixes center channel flicker with light theme while loading when dark theme is set 
Fixes https://github.com/mattermost/mattermost-server/issues/13783

[MM-21993] Fixed center channel flicker with light theme when loading

---

e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
e2e/cypress/integration/system_console/group_configuration_spec.js

Specs are filing on master prod and unstable runs.
~~Note that this PR is submitted on top of https://github.com/mattermost/mattermost-webapp/pull/5831. Will update once the said PR is merged.~~ [updated] See https://github.com/mattermost/mattermost-webapp/commit/73bce7dc26a8f97fa55f599ad9fe68ffd88ea0dd for particular change.
Test report - https://mm-cypress-report.s3.amazonaws.com/544-verify-0702-master/mochawesome.html
none, failing on master-prod and master-unstable tests.

Cypress/E2E: Fix group config and search channels

---

e2e/cypress/integration/integrations/incoming_webhook/basic_formatting_spec.js
e2e/cypress/integration/interactive_menu/basic_options_spec.js
e2e/cypress/integration/interactive_menu/select_with_keys_spec.js
e2e/cypress/integration/interactive_menu/slack_parsing_message_button_spec.js
e2e/cypress/support/task_commands.js

Cypress/E2E for MM-T619 Webhook with @-mention, username and profile pic and basic formatting
Jira ticket: https://mattermost.atlassian.net/browse/MM-26069
TM4J ticket: [MM-T619](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T619)
Test report to related change - https://mm-cypress-report.s3.amazonaws.com/551-MM-25069_MM-T619_cypress-test-master/mochawesome.html

MM-25069 Cypress/E2E for MM-T619 Webhook with @-mention, username and profile pic and basic formatting

---

utils/text_formatting.test.jsx
utils/text_formatting.tsx

Cherry pick of #5818 on release-5.25.
- #5818: MM-26573 Support variations for one-byte emojis
/cc  @hmhealey

Automated cherry pick of #5818

---

e2e/cypress/integration/messaging/private_channel_open_spec.js

Added Cypress test for MM-23358.
Fixes https://github.com/mattermost/mattermost-server/issues/14078

[MM-23358] Cypress test for "CTRL/CMD+K - Open private channel using arrow keys and Enter"

---

components/suggestion/search_channel_suggestion/index.js
components/suggestion/suggestion_box.jsx
components/suggestion/switch_channel_provider.jsx

Forward references into SearchChannelSuggestion and SwitchChannelSuggestion to allow scrolling during arrow navigation. Also fix small JS errors.
More information in the Jira Ticket.
https://mattermost.atlassian.net/browse/MM-26606

[MM-26605] Forward references into SearchChannelSuggestion and SwitchChannelSuggestion to allow scrolling during arrow navigation

---

components/rhs_thread/index.ts
components/rhs_thread/rhs_thread.tsx

Fix the crash when switching teams when the RHS is open.
More info in the Jira Ticket.
https://mattermost.atlassian.net/browse/MM-26610

[MM-26610] Fix the crash when switching teams

---

e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js

Added more Cypress tests for Guest Account Feature
JIRA Ticket: MM-26072
TM4J Tickets: MM-T1410, MM-T1415 and MM-T1419

Added Cypress tests MM-T1410, MM-T1415 and MM-T1419

---

e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js

Added few cypress tests for Guest Account feature
Cypress tests added for following TM4J tests:
[MM-T1412](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1412)
[MM-T1324](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1324)
[MM-T1325](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1325)
[MM-T1330](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-pa …

MM-26072: Added few cypress tests for Guest Account feature

---

e2e/cypress/integration/integrations/incoming_webhook/setting_spec.js

Cypress test for MM-T623 Lock to this channel on webhook configuration works.
Test case: [MM-T623](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T623)
JIRA ticket - https://mattermost.atlassian.net/browse/MM-26069

MM-26069 Cypress test for MM-T623 Lock to this channel on webhook configuration works

---

components/root/root.jsx
components/root/root.test.jsx

Import was wrongly imported. Fix casing
https://mattermost.atlassian.net/browse/MM-26865

MM-26885 Fix for client4 import

---

e2e/cypress/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js

Cypress test for MM-T621 Override username and profile picture - remove overrides from payload.
Test case: [MM-T621](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T621)
JIRA ticket - https://mattermost.atlassian.net/browse/MM-26069

MM-26069 Cypress test for MM-T621 Override username and profile picture - remove overrides from payload

---

e2e/cypress/integration/channel/channel_mention_autocomplete_spec.js
e2e/cypress/integration/commands/leave_channel_spec.js
e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
e2e/cypress/integration/emoji/recently_used_emoji_spec.js

Fix failing specs. Changes are small enough to break into several PRs.

Cypress/E2E: fix failing specs

---

e2e/cypress/integration/channel_sidebar/category_collapsing_unread_filter_spec.js

Fix sidebar channel collapsing

Cypress/E2E: fix sidebar channel collapsing

---

e2e/cypress/fixtures/partial_default_config.json
e2e/cypress/integration/channel_sidebar/drag_and_drop_spec.js
e2e/cypress/integration/menus/user_guide_help_spec.js

Fix failing tests on drag and drop, and user guide menu

Cypress/E2E: fix failing tests on drag and drop, and user guide menu

---

components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
components/more_direct_channels/more_direct_channels.test.jsx
components/more_direct_channels/more_direct_channels.tsx

Cherry pick of #5860 on release-5.26.
- #5860: MM-26718 Fix the perf of animation on DM modal

Automated cherry pick of #5860

---

components/channel_header/components/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.jsx.snap
components/channel_header/components/user_guide_dropdown/user_guide_dropdown.test.jsx
components/channel_header/components/user_guide_dropdown/user_guide_dropdown.tsx
utils/constants.jsx

Add an analytic event for tracking `onClick` of ask the community link
https://mattermost.atlassian.net/browse/MM-26621

MM-26621 Add analytic event for ask community link

---

sass/layout/_sidebar-left.scss

Fix mention badge opacity
https://mattermost.atlassian.net/browse/MM-26848

[MM-26848] - Fix mention badge opacity for muted channels

---

components/channel_header/components/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.jsx.snap
components/channel_header/components/user_guide_dropdown/user_guide_dropdown.test.jsx
components/channel_header/components/user_guide_dropdown/user_guide_dropdown.tsx
utils/constants.jsx

Cherry pick of #5915 on release-5.26.
- #5915: MM-26621 Add analytic event for ask community link

Automated cherry pick of #5915

---

components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
components/post_markdown/post_markdown.jsx
e2e/cypress/integration/messaging/at_mentions_user_spec.js

Cherry pick of #5908 on release-5.26.
- #5908: MM-26751: Fix highlighting of at-mentions of self

Automated cherry pick of #5908

---

components/sidebar/sidebar.tsx
components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
utils/constants.jsx

Cherry pick of #5890 on release-5.26.
- #5890: MM-26321 Add telemetry for channel menu create category

Automated cherry pick of #5890

---

e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
e2e/cypress/support/ui_commands.js

Cherry pick of #5942 on release-5.26.
- #5942: fix e2e tests on timezone display

Automated cherry pick of #5942

---

e2e/cypress/integration/multi_team_and_dm/existing_channel_name_spec.js

- Added click and wait
- Moved functions to bottom of file

Cypress/E2E: Fix existing channel name spec

---

e2e/cypress/integration/multi_team_and_dm/existing_channel_name_spec.js

Cherry pick of #5947 on release-5.26.
- #5947: Fix existing channel name spec

Automated cherry pick of #5947

---

e2e/cypress/integration/accessibility/accessibility_post_spec.js

- Added post reaction verifications
- Moved functions to bottom of file

Cypress/E2E: Fix accessibility post spec

---

e2e/cypress/integration/enterprise/system_console/team_members_spec.js

- Fixed input locator
- Extracted method for searching

Cypress/E2E: Fix team members spec

---

e2e/cypress/integration/enterprise/system_console/team_members_spec.js

Cherry pick of #5945 on release-5.26.
- #5945: Fix team members spec

Automated cherry pick of #5945

---

e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
e2e/cypress/integration/channel/channel_routing_spec.js

- Added prefix to other users so that they are in alphabetic order to avoid switching in GM channel display

Cypress/E2E: Fix channel routing spec

---

e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js

Cherry pick of #5957 on release-5.26.
- #5957: Try to fix timezone display mode flakiness

Automated cherry pick of #5957

---

actions/command.js
actions/command.test.js
actions/views/channel.js
components/legacy_sidebar/sidebar_channel/index.js
components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
package-lock.json
package.json

Cherry pick of #5917 on release-5.26.
- #5917: MM-26410 Switch to new isFavoriteChannel selector
/cc  @hmhealey

Automated cherry pick of #5917

---

e2e/cypress/integration/system_console/plugin_upload_spec.js

- Need to re-query DOM elements as they are updated asynchronously

Cypress/E2E: Fix plugin upload spec

---

e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
e2e/cypress/integration/account_settings/sidebar/channel_switcher_ui_spec.js
e2e/cypress/integration/channel_sidebar/hotkeys_spec.js

- Stabilized test by adding reload (for some reason on cypress the page does not load properly)
- Included 2 other specs that required reload as well to stabilize

Cypress/E2E: Fix hotkeys spec

---

components/do_verify_email/do_verify_email.tsx

Cherry pick of #5927 on release-5.26.
- #5927: convey redirect link through verification
/cc  @isacikgoz

Automated cherry pick of #5927

---

components/suggestion/suggestion_box.jsx

Cherry pick of #5913 on release-5.26.
- #5913: Fix reselection of dropdowns on Interactive Dialogs
/cc  @larkox

Automated cherry pick of #5913

---

i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json

Merge conflicts with weblate

---

components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
components/popover_list_members/popover_list_members.jsx
components/popover_list_members/popover_list_members.test.jsx
package-lock.json
utils/filter_users.js
utils/filter_users.test.js

We filter the user list by only activated users.
https://mattermost.atlassian.net/browse/MM-27135

MM-27135: Deactivated users show in channel members dropdown

---

components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
components/popover_list_members/popover_list_members.jsx
components/popover_list_members/popover_list_members.test.jsx
utils/filter_users.js
utils/filter_users.test.js

* MM-27135: Deactivated users show in channel members dropdown
We filter the user list by only activated users.
* incorporate review comments
* incorporate review comments

MM-27135: Deactivated users show in channel members dropdown (#5951)

---

components/data_prefetch/index.ts

Cherry pick of #5990 on release-5.26.

Cherrypick of #5990

---

e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
e2e/cypress/integration/system_console/plugin_upload_spec.js

- Fixed installed plugins verification and used timeout constants
- Added scrollIntoView where necessary (cypress workaround)

Cypress/E2E: Fix marketplace and plugin_upload specs

---

e2e/cypress/integration/messaging/date_separator_spec.js

- Fixed date separator verification in Spanish

Cypress/E2E: Fix date separator spec

---

e2e/cypress/support/api/user.js

- Made sure user is logged out before clearing cookies

Cypress/E2E: Fix forgot password spec

---

e2e/cypress/integration/team_settings/create_a_team_spec.js
package-lock.json

- Added end to end test to verify reserved words cannot be used to create teams
https://automation-test-cases.vercel.app/test/MM-T1437
None
N/A

MM-T1437 Try to create a new team using restricted words

---

components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
components/admin_console/team_channel_settings/channel/list/channel_list.scss
components/admin_console/team_channel_settings/channel/list/channel_list.tsx

Cherry pick of https://github.com/mattermost/mattermost-webapp/pull/5926 into 5.26 release branch

 [CHERRY PICK!!][MM-26960] Fix Archive Icon not showing up for archived channels on system console > Channels page

---

e2e/cypress/integration/team_settings/teams_spec.js

- Added e2e test to verify if help text under team invite is present
https://automation-test-cases.vercel.app/test/MM-T1535
none
n/a

MM-T1535 Team setting / Invite code text

---

sass/layout/_legacy-sidebar-left.scss
sass/layout/_sidebar-left.scss
utils/utils.jsx

I also did some cleanup by using more `-rgb` CSS variables and removing some unused CSS rules.
https://mattermost.atlassian.net/browse/MM-26866
https://mattermost.atlassian.net/browse/MM-26869

MM-26866/MM-26869 Fix a couple sidebar CSS colours

---

sass/routes/_admin-console.scss

Cherry pick of #6010 on release-5.26.
/cc  @fmunshi

Automated cherry pick of #6010

---

components/admin_console/data_grid/data_grid_search.tsx
components/admin_console/team_channel_settings/channel/list/channel_list.tsx
e2e/cypress/integration/enterprise/system_console/archived_channels_spec.js

After submitting a fix for https://mattermost.atlassian.net/browse/MM-26960, Rohitesh pointed out that I was looking at the wrong test file and therefore I did not fix the tests for the fix I made so this PR aims to fix test for channels page in system console.
https://mattermost.atlassian.net/browse/MM-26960

[MM-26960] Fix tests for channel page in system console

---

sass/layout/_sidebar-left.scss

Cherry pick of #6019 on release-5.26.
/cc  @hmhealey

Automated cherry pick of #6019

---

e2e/cypress/integration/messaging/message_reaction_spec.js

Fix message reaction due to outdated use of users.json, introduced by https://github.com/mattermost/mattermost-webapp/pull/5467
none, failing on master

Cypress/E2E: fix message reaction due to outdated use of users.json

---

package-lock.json
package.json

Bump redux version for this branch
https://mattermost.atlassian.net/browse/MM-27371

[MM-27371] Bump mattermost-redux version

---

NOTICE.txt

Cherry pick of #5980 on release-5.26.
/cc  @amyblais

Automated cherry pick of #5980

---

components/admin_console/team_channel_settings/channel/details/channel_details.tsx
components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
components/admin_console/team_channel_settings/channel/list/channel_list.tsx
components/admin_console/team_channel_settings/team/details/team_details.jsx
components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx

Cherrypick of https://github.com/mattermost/mattermost-webapp/pull/6009 into release-5.26 branch

[MM-27249] Add telemetry to team and channel pages (#6009) CHERRYPICK

---

actions/views/channel_sidebar.test.ts
actions/views/channel_sidebar.ts
components/sidebar/sidebar_category_list/index.ts
components/sidebar/sidebar_category_list/sidebar_category_list.test.tsx
components/sidebar/sidebar_category_list/sidebar_category_list.tsx
store/index.js

Cherry pick of #6015 on release-5.26.
/cc  @hmhealey

Automated cherry pick of #6015

---

components/sidebar/__snapshots__/sidebar.test.tsx.snap
components/sidebar/index.ts
components/sidebar/sidebar.test.tsx
components/sidebar/sidebar.tsx

Cherry pick of #6032 on release-5.26.

Automated cherry pick of #6032

---

e2e/cypress/integration/messaging/autocomplete_shown_each_channel_spec.js

Cherry pick of #6037 on release-5.26.

Automated cherry pick of #6037

---

e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
e2e/cypress/support/api_commands.js

The `/me` command should work on RHS (reply thread). The reply should be shown on the main channel (in a lower opacity).
https://automation-test-cases.vercel.app/test/MM-T2345

[MM-T2345] /me on RHS

---

e2e/cypress/integration/messaging/message_spec.js

I've automated the test for image thumbnail as a part of the Hackfest Test Automation.
https://automation-test-cases.vercel.app/test/MM-T1797

[MM-T1797] Compact View: Show single image thumbnail

---

e2e/cypress/integration/system_console/plugin_upload_spec.js

- Add Installed Plugins section verification before checking draw-plugin

Cypress/E2E: Add Installed Plugins section verification

---

e2e/cypress/integration/toast/toast_spec.js

MM-T1788 Watch Toast count on getting messages
[Usecase](https://automation-test-cases.vercel.app/test/MM-T1788)

MM-T1788 Toast count

---

e2e/save_report.js
e2e/utils/report.js
e2e/utils/test_cases.js

Integrate Cypress and TM4J. The following environment variables needs to set in order to save test cases into TM4J
- TM4J_ENABLE=true|false
- TM4J_API_KEY=[api_key]
- JIRA_PROJECT_KEY=[project_key], e.g. "MM",
- TM4J_FOLDER_ID=[folder_id], e.g. 847997
See [example test run/cycle](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testPlayer/MM-R421)
Jira ticket - https://mattermost.atlassian.net/browse/MM-23409

MM-23409 Integrate Cypress and TM4J

---

components/warn_metric_ack_modal/__snapshots__/warn_metric_ack_modal.test.tsx.snap
components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
i18n/en.json

Cherry pick of #6085 on release-5.26.

Automated cherry pick of #6085

---

e2e/cypress/integration/channel/permalink_post_spec.js
e2e/cypress/integration/toast/permalink_post_spec.js

in channel
MM-T1792 Permalink post
[Usecase](https://automation-test-cases.vercel.app/test/MM-T1792)

MM-T1792 Permalink post

---

e2e/cypress/integration/messaging/typing_should_show_up_when_editing_spec.js
package-lock.json

Summary
I created a test that checks that when creating a post in a channel and opening the modal and start typing again, no text should be cut off. I also added a check to make sure that the post was edited and saved properly
Ticket Link
Jira: https://mattermost.atlassian.net/browse/MM-23347

MM-23347 - Add e2e test for typing in the edit modal

---

e2e/cypress/integration/toast/toast_spec.js

- Used the new helper functions; fixed issues found
- Cleaned up comments
- Simplified toast and message verification
- Created new channel for archived toast test case

Cypress/E2E: Cleanup toast spec and fix issues

---

components/multiselect/__snapshots__/multiselect.test.tsx.snap
components/multiselect/multiselect.tsx
e2e/cypress/integration/multi_team_and_dm/max_gm_members_spec.js

- Add a few HTML id attributes to the MultiSelect component to assist with E2E tests
- Add a cypress test that validates a group message between users cannot contain more than 8 people
JIRA Ticket: MM-T463
Related test scenario: https://automation-test-cases.vercel.app/test/MM-T463

MM-T463: E2E to validate maximum users in group message

---

webpack.config.js

Cherry pick of #6099 on release-5.26.

Automated cherry pick of #6099

---

e2e/cypress/integration/emoji/recently_used_emoji_spec.js
e2e/cypress/integration/emoji/sorted_emojis_spec.js
e2e/cypress/integration/messaging/at_mentions_spec.js
e2e/cypress/integration/messaging/at_mentions_user_spec.js
e2e/cypress/integration/messaging/autocomplete_shown_each_channel_spec.js
e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js
e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
e2e/cypress/integration/messaging/channel_users_interactions_spec.js
e2e/cypress/integration/messaging/collapse_link_spec.js
e2e/cypress/integration/messaging/collapsed_message_spec.js
e2e/cypress/integration/messaging/edit_message_spec.js
e2e/cypress/integration/messaging/emoji_followed_by_punctuation_spec.js
e2e/cypress/integration/messaging/emoji_insert_position_spec.js
e2e/cypress/integration/messaging/emoji_keyboard_entry_spec.js
e2e/cypress/integration/messaging/emoji_size_spec.js
e2e/cypress/integration/messaging/emoji_to_markdown_spec.js
e2e/cypress/integration/messaging/file_upload_in_center_channel_spec.js
e2e/cypress/integration/messaging/focus_move_spec.js
e2e/cypress/integration/messaging/header_spec.js
e2e/cypress/integration/messaging/input_box_expands_spec.js
e2e/cypress/integration/messaging/input_box_expands_with_rhs_spec.js
e2e/cypress/integration/messaging/invalid_emojis_as_text_spec.js
e2e/cypress/integration/messaging/long_draft_spec.js
e2e/cypress/integration/messaging/long_post_attachments_spec.js
e2e/cypress/integration/messaging/markdown_preview_inline_image_spec.js
e2e/cypress/integration/messaging/markdown_quotation_paragraphs_spec.js
e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js

Update TM4J test keys for Messaging
Note: I've updated as well the full title so it's easier to compare/verify.

Cypress/E2E: Update TM4J test keys for Messaging

---

e2e/cypress/integration/channel/more_public_channels_spec.js
e2e/cypress/integration/channel_settings/channel_name_validations_spec.js
e2e/cypress/integration/channel_settings/more_unreads_position_with_scroll_spec.js
e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
e2e/cypress/integration/enterprise/system_console/archived_channels_spec.js
e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
e2e/cypress/integration/messaging/channel_users_interactions_spec.js
e2e/cypress/integration/messaging/date_separator_spec.js
e2e/cypress/integration/messaging/message_permalink_spec.js
e2e/cypress/integration/messaging/post_pre_header_spec.js
e2e/cypress/integration/signin_authentication/forgot_password_spec.js
e2e/cypress/integration/signin_authentication/subpath_login_spec.js

Moving the unstable cypress tests which have been consistently working fine to prod. 
NA

Moving unstable cypress tests to prod

---

e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
e2e/cypress/support/ldap_commands.js

Fix LDAP login and team/channel roles
none, failing on daily tests

Cypress/E2E: Fix LDAP login and team/channel roles

---

e2e/cypress/integration/enterprise/system_console/archived_channels_spec.js

- Added necessary timeouts and fixed verifications
- Cleaned up comments

Cypress/E2E: Fix archived channels spec

---

e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
e2e/cypress/utils/index.js

- Added `hexToRgbArray` and `rgbArrayToString` util functions
- Removed hard-coded color values to accommodate dynamic coordinates on various color box dimensions 

Cypress/E2E: Dynamic verification of theme colors

---

e2e/cypress/integration/messaging/message_spec.js

Cypress test for  standard single image view
Test case: https://automation-test-cases.vercel.app/test/MM-T1796

MM-T1796 Cypress test for  standard single image view

---

e2e/cypress/integration/account_settings/display/code_theme_colors_spec.js
e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
e2e/cypress/integration/account_settings/general/fullname_spec.js
e2e/cypress/integration/account_settings/general/main_menu_stays_open_spec.js
e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
e2e/cypress/integration/account_settings/sidebar/channel_switcher_ui_spec.js

Update E2E test keys for Account settings

Cypress/E2E: Update E2E test keys for Account settings

---

e2e/cypress/integration/integrations/integrations_spec.js

- Added test to check for copy icon in slash commands

MM-T572 Copy icon for Slash Command

---

components/post_view/post_header/post_header.jsx

Cherry pick of #5821 on release-5.27.
/cc  @larkox

Automated cherry pick of #5821

---

e2e/cypress/integration/integrations/integrations_spec.js

Added a end to end test to verify that editing a custom slash with invalid url results in an error
MM-T702
---
_Reopened the PR here from https://github.com/mattermost/mattermost-webapp/pull/6157_
_Please dont mind the branch name, its not correct_

MM-T702 Edit to invalid URL

---

components/audit_table/__snapshots__/audit_table.test.jsx.snap
components/audit_table/audit_table.jsx
components/user_settings/security/user_settings_security.jsx
e2e/cypress/integration/enterprise/saml/saml_automated_spec.js

Cherry pick of #5968 on release-5.27.
/cc  @hahmadia

Automated cherry pick of #5968

---

components/admin_console/admin_definition.jsx

Cherry pick of #5964 on release-5.27.
/cc  @hahmadia

Automated cherry pick of #5964

---

components/sidebar/sidebar_category/sidebar_category.tsx
e2e/cypress/integration/channel_sidebar/new_category_badge_spec.js
reducers/views/channel_sidebar.ts

Cherry pick of #6126 on release-5.27.
/cc  @hmhealey

Automated cherry pick of #6126

---

components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
components/sidebar/sidebar_category/sidebar_category.tsx

Cherry pick of #5986 on release-5.27.

Automated cherry pick of #5986

---

components/analytics/format.test.tsx
components/analytics/format.tsx
components/analytics/system_analytics/system_analytics.jsx

Cherry pick of #5785 on release-5.27.
/cc  @sbishel

Automated cherry pick of #5785

---

components/error_page/__snapshots__/error_message.test.tsx.snap
components/error_page/__snapshots__/error_title.test.tsx.snap
components/error_page/error_message.test.tsx
components/error_page/error_message.tsx
components/error_page/error_page.tsx
components/error_page/error_title.test.tsx
components/error_page/error_title.tsx
utils/constants.jsx

Cherry pick of #5884 on release-5.27.
/cc  @sbishel

Automated cherry pick of #5884

---

components/admin_console/message_export_settings.jsx
i18n/en.json

Cherry pick of #6024 on release-5.27.
/cc  @sbishel

Automated cherry pick of #6024

---

components/suggestion/command_provider.jsx
components/textbox/textbox.tsx

- cherry pick MM-27182 from master to 5.27
- #6021

cherry pick MM-27182 - Fix dynamic slash command autocomplete options (#6021)

---

components/admin_console/team_channel_settings/channel/details/channel_details.tsx
components/admin_console/team_channel_settings/team/details/team_details.jsx

Cherry pick of #6074 on release-5.27.
/cc  @fmunshi

Automated cherry pick of #6074

---

components/edit_post_modal/edit_post_modal.jsx

Cherry pick of #6119 on release-5.27.
/cc  @mkraft

Automated cherry pick of #6119

---

e2e/package-lock.json
e2e/package.json
e2e/run_tests.js

This is webapp changes associated with https://github.com/saturninoabril/mattermost-cypress-docker/pull/17
None

Cypress/E2E: Propagate step status to CircleCI

---

e2e/cypress/integration/channel_sidebar/new_category_badge_spec.js

As requested by QA. Skipping their review since there's no functional changes.
https://mattermost.atlassian.net/browse/MM-26501

MM-26501 Add ID to E2E test

---

sass/components/_emoticons.scss

Cherry pick of #6171 on release-5.27.
/cc  @hmhealey

Automated cherry pick of #6171

---

e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
e2e/cypress/integration/files_and_attachments/upload_files_spec.js
e2e/cypress/integration/integrations/builtin_commands/invalid_commands_spec.js
e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
e2e/cypress/integration/messaging/draft_with_only_2_byte_characters_spec.js
e2e/cypress/integration/messaging/inline_markdown_image_link_open_link_spec.js
e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
e2e/cypress/integration/messaging/pinned_parent_post_spec.js
e2e/cypress/integration/messaging/post_textbox_height_spec.js
e2e/cypress/integration/messaging/typing_should_show_up_when_editing_spec.js
e2e/cypress/integration/multi_team_and_dm/channel_user_count_spec.js
e2e/cypress/integration/multi_team_and_dm/close_current_dm_redirects_spec.js
e2e/cypress/integration/multi_team_and_dm/max_gm_members_spec.js
e2e/cypress/integration/system_console/feature_discovery_spec.js
e2e/cypress/integration/system_console/group_configuration_spec.js
e2e/cypress/integration/toast/permalink_jump_to_spec.js
e2e/cypress/integration/toast/permalink_post_spec.js

Cypress/E2E: Promote tests into prod

---

e2e/cypress/integration/channel/channel_unread_spec.js
e2e/cypress/integration/mark_as_unread/channel_unread_spec.js
e2e/cypress/integration/mark_as_unread/helpers.js
e2e/cypress/integration/mark_as_unread/mark_as_unread_spec.js

MM-T246 Mark Post as Unread
[MM-T246](https://automation-test-cases.vercel.app/test/MM-T246)

MM-T246 Mark Post as Unread

---

components/channel_groups_manage_modal/channel_groups_manage_modal.tsx
components/channel_groups_manage_modal/index.ts

Fixes incorrect JSON key name causing update request to fail.
https://mattermost.atlassian.net/browse/MM-27947

MM-27947: Fixes JSON key names.

---

components/channel_groups_manage_modal/channel_groups_manage_modal.tsx
components/channel_groups_manage_modal/index.ts

Cherry pick of #6207 on release-5.27.
/cc  @mkraft

Automated cherry pick of #6207

---

components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
components/next_steps_view/next_steps_view.test.tsx
components/next_steps_view/steps/complete_profile_step/complete_profile_step.test.tsx
components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
components/next_steps_view/steps/team_profile_step/team_profile_step.test.tsx
components/next_steps_view/steps/team_profile_step/team_profile_step.tsx
i18n/en.json

Some additional unit tests on the steps for Cloud Onboarding for Admins.
https://mattermost.atlassian.net/browse/MM-27974

[MM-27974] Unit Tests for Cloud Onboarding

---

components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.tsx
components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx

Cherry pick of #6202 on release-5.27.
/cc  @hahmadia

Automated cherry pick of #6202

---

components/admin_console/group_settings/group_details/group_details.jsx

Cherry pick of #6209 on release-5.27.
/cc  @hahmadia

Automated cherry pick of #6209

---

e2e/cypress/integration/mark_as_unread/channel_unread_spec.js

MM-T259 Mark as Unread channel remains unread when receiving new message
[MM-T259](https://automation-test-cases.vercel.app/test/MM-T259)

MM-T259 Mark as Unread channel remains unread when receiving new message

---

components/post_view/post_list_row/__snapshots__/post_list_row.test.jsx.snap
components/post_view/post_list_row/post_list_row.jsx
components/post_view/post_list_row/post_list_row.test.jsx
components/post_view/post_list_virtualized/post_list_virtualized.jsx
sass/components/_post.scss
sass/routes/_loading.scss

Cherry pick of #6197 on release-5.27.

Automated cherry pick of #6197

---

e2e/cypress/integration/mark_as_unread/mark_as_unread_spec.js

MM-T250 Mark as unread in the RHS
[MM-T250](https://automation-test-cases.vercel.app/test/MM-T250)

MM-T250 Mark as unread in the RHS

---

package-lock.json
package.json

Updates redux.

---

sass/components/_search.scss
sass/responsive/_desktop.scss

MM-26697 - Updating search bar size on tablet view
https://mattermost.atlassian.net/browse/MM-26697

MM-26697 - Updating search bar size on tablet view

---

e2e/cypress/integration/mark_as_unread/channel_unread_spec.js

MM-T256 Mark as Unread New Messages line
[MM-T256](https://automation-test-cases.vercel.app/test/MM-T256)

MM-T256 Mark as Unread New Messages line

---

actions/websocket_actions.jsx
e2e/cypress/integration/websocket/channel_created/new_sidebar_spec.js
e2e/cypress/integration/websocket/channel_created/old_sidebar_spec.js

Cherry pick of #6191 on release-5.27.
/cc  @hmhealey

Automated cherry pick of #6191
