mattermost/mattermost-webapp

- components/search_bar/search_bar.jsx
- components/suggestion/search_channel_provider.jsx
The `itemToName` function was used for display names only (which are the same for GMs/DMs but not other channels). Fixed by creating a similar function but to be used specifically for creating the search term.
https://mattermost.atlassian.net/browse/MM-22326
> MM-22326 Fix non-DM/GM autocomplete in search box

- components/search_bar/search_bar.jsx
- components/suggestion/search_channel_provider.jsx
Cherry pick of #4850 on release-5.20.
- #4850: Fix non-DM/GM autocomplete in search box
> Automated cherry pick of #4850

- e2e/run_tests.js
This is P1 in improving Cypress test reports. (P2 - save JSON file to S3;  P3 - generate historical reports)
This fixes the issue on daily Cypress test where report is not being sent to community server. Move here the processing of report instead of Jenkins.
Key Changes:
- added branch to title to determine if the tests is run against what branch - "[__master__] Cypress UI Test Automation #123 Passed!"
- added indication on required support - "Key metrics (required support: __none__)"; options are none, low, medium and high.
Follow up PRs (non-blocking):
- on shared pipelines to remove report generation and add env variables for `BRANCH`, `BUILD_ID`, `WEBHOOK_URL`.
- add documentation at https://developers.mattermost.com/internal/qa/.  Title could be "Cypress Test Report"
Jira ticket: …
> [MM-21542] Fix Cypress test report

- utils/markdown/index.test.js
- utils/markdown/renderer.tsx
Cherry pick of #4844 on release-5.20.
- #4844: Wrap list elements in a span
> Automated cherry pick of #4844

- e2e/cypress/integration/channel/toast_spec.js
Changes done in the toast spec to handle a recent change done for toast not to appear when the bottom is in view. 
Status of the tests before this change:
Status of tests after this change:
> Changes to handle a recent change done for toast not to appear when the bottom is in view

- components/__snapshots__/textbox.test.jsx.snap
- components/admin_console/reset_password_modal/reset_password_modal.test.tsx
- components/create_comment/__snapshots__/create_comment.test.jsx.snap
- components/create_comment/create_comment.jsx
- components/create_comment/create_comment.test.jsx
- components/create_comment/index.js
- components/create_post/__snapshots__/create_post.test.jsx.snap
- components/create_post/create_post.jsx
- components/create_post/create_post.test.jsx
- components/create_post/index.js
- components/suggestion/at_mention_provider/at_mention_provider.jsx
- components/suggestion/at_mention_provider/at_mention_provider.test.jsx
- components/textbox.test.jsx
- components/textbox/index.js
- components/textbox/textbox.jsx
- package-lock.json
- package.json
- Enforces the new `use_channel_mentions` permission when showing suggestions for @mentions.
https://mattermost.atlassian.net/browse/MM-21920
- Has server changes https://github.com/mattermost/mattermost-server/pull/13781
- Has redux changes https://github.com/mattermost/mattermost-redux/pull/1046
> [MM-21920] Enforce use_channel_mentions permissions

- e2e/cypress/integration/channel/channel_mention_autocomplete_spec.js
- e2e/cypress/integration/channel/send_message_via_profile_popover_spec.js
- On channel mention, make sure that loading indicator is not present before making assertions
- On profile popover, fix the logic around waitUntil to correctly wait until the message gets posted
> Fix failing tests on channel mention and profile popover

- components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.tsx.snap
- components/admin_console/team_channel_settings/group/group_users_row.tsx
Removing single quotes around '&nbsp', which is causing it display verbatim. Also removed the 'div' tag that was added as it was forcing Display name to a separate line.
https://mattermost.atlassian.net/browse/MM-22430
> Mm 22430 - Regression &nbsp should not display

- e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
- e2e/cypress/integration/account_settings/sidebar/channel_switcher_ui_spec.js
- Split the spec into two files - one for UI check and other for full functionality
- On full functionality, create new test team and channels on it instead of creating test channels on default ad-1 team, to prevent unpredictable state of LHS
> Fix failing test on channel switcher

- utils/test_helper.ts
https://github.com/mattermost/mattermost-webapp/pull/4738 when merged into master, failed the type tests. This PR fixes that.
Hotfix
https://github.com/mattermost/mattermost-webapp/pull/4738
> HotFix : Added missing types to test_helper

- e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js
Fix failing message reply input box expand spec
- fix padding and height comparison issue, based on actual size window (no zoom in/out)
> Fix message reply input box expand spec

- components/admin_console/jobs/table.jsx
- e2e/cypress/integration/enterprise/system_console/channel_modes_spec.js
- e2e/cypress/integration/enterprise/system_console/groups_assign_roles_spec.js
- e2e/cypress/integration/enterprise/system_console/team_and_channel_asign_roles_spec.js
- e2e/cypress/support/api_commands.js
- e2e/cypress/support/ui_commands.js
Fixed tests related to LDAP Groups. The tests were expecting the Groups to be pre-populated before running the test. However since we clean the database on every CI run, I have now added a step to check and then LDAP Group Sync job before running the tests. 
NA. Fixed based on daily run.
> Added step to run LDAP Sync before running tests related to Groups

- components/channel_header/channel_header.js
- components/channel_header/components/header_icon_wrapper.js
- components/search_results_header/search_results_header.jsx
- components/widgets/menu/menu_items/menu_item.tsx
Three of these cases relates to the false assumption that only string representations would be provided, when plugins can supply arbitrary nodes (primarily meant to enable localization).
Also fix one issue of passing a truthy string to a prop expecting a strict boolean.
Fixes: https://mattermost.atlassian.net/browse/MM-22081
> MM-22081: fix various PropTypes issues

- components/linking_landing_page/linking_landing_page.tsx
- components/root/root.jsx
Cherry pick of #4834 on release-5.21.
- #4834: Don't redirect to landing page when already on a
> Automated cherry pick of #4834

- components/signup/signup_email/signup_email.jsx
I propose we make a ticket to refactor the formatted_markdown_message.jsx
because adding the '!' to activate target="_blank" is a very obscure way to
do it and it was a undocumented feature.
Proposition: We have the customRenderer, instead of passing href as a string, it can be an object that contains href, target, ref, etc and if the values exist, to append to the link.
Fixes https://mattermost.atlassian.net/browse/MM-22204
> [MM-22204] - Add target="_blank" to terms and policy links

- package-lock.json
- package.json
As part of https://mattermost.atlassian.net/browse/MM-14661 we need to update the mattermost-redux version. 
https://mattermost.atlassian.net/browse/MM-14661
- Has mobile changes https://github.com/mattermost/mattermost-mobile/pull/3958
> Add latest mattermost-redux version

- components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
- components/more_direct_channels/index.js
- components/more_direct_channels/more_direct_channels.jsx
- components/more_direct_channels/more_direct_channels.test.jsx
Cherry pick of #4843 on release-5.21.
- #4843: MM-22038: removing deactivate users from open private
/cc  @jespino
> Automated cherry pick of #4843

- components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/__snapshots__/team_in_list.test.jsx.snap
- components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.jsx
- components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.test.jsx
Add Team Display Name back to the TeamInList component. When TeamInfo object was replaced with the TeamIcon component, the Team Name was dropped.
https://mattermost.atlassian.net/browse/MM-22634
> MM-22634: Add Team Name back to team list

- components/signup/signup_email/index.js
- components/signup/signup_email/signup_email.jsx
Removed 'back' button when the user has no accounts. I had to remove the 'sticky' class because it was adding a second scroll to the page.
Fixes https://mattermost.atlassian.net/browse/MM-22310
> [MM-22310] Remove back button when user has no accounts

- components/status_dropdown/status_dropdown.jsx
- e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
- e2e/cypress/integration/messaging/local_date_time_spec.js
- e2e/cypress/support/api_commands.js
- e2e/run_tests.js
- Added Cypress test to verify Accessibility Support in Dropdown Menus. 
- Minor fixes based on run on localhost
- Updated run_test to continue to generate report (mochawesome.html) even if it fails to send report via webhook
- Enable Timezone before running the local_date_time_spec
Fixes https://mattermost.atlassian.net/browse/MM-22627
> Added Cypress test to verify Accessibility Support in Dropdown Menus

- components/member_list_channel/index.ts
- components/member_list_channel/member_list_channel.tsx
When members roles are updated and the manage members role in a channel is loaded, the updated roles were not being shown. This PR fixes this problem.
https://mattermost.atlassian.net/browse/MM-22370
> [MM-22370] Fix channel modal not showing updated roles

- sass/components/_scrollbar.scss
MM-23012 - Hiding scrollbars in IE from LHS/RHS
The scrollbars should be hidden now from the LHS/RHS (but not from the center channel).
https://mattermost.atlassian.net/browse/MM-23012
> MM-23012 - Hiding scrollbars in IE from LHS/RHS

- components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
- components/post_markdown/post_markdown.jsx
- components/post_markdown/post_markdown.test.jsx
This PR fixes and issue with highlighting at mention myself followed by a Period(.) or underscore (_). This issue has already been fixed in master by this PR -
https://github.com/mattermost/mattermost-webapp/pull/4916
However, that PR, was for another feature and is too large to cherry-pick back to v5.21. This PR only contains the changes necessary to fix the highlighting issue.
This issue was introduced when fixing the highlighting of the header - https://github.com/mattermost/mattermost-webapp/pull/4819
I made sure this fix was retained, see screenshot. 
Essentially, when the `options.mentionHighlight` is not set, it gets passed as false. Therefore, when it is empty, it needs set to true by default. 
https://mattermost.atlassian.net/browse/MM-22970
> MM-22970: Fix highlighting of at mentions of self

- components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
- components/post_markdown/post_markdown.test.jsx
(cherry picked from commit 2a78ea9af6fe7a7a253d48c71337ca056d656712)
This is a cherry pick for a commit that went directly to release-v5.21. It was cp'ed forward because a couple of additional tests were added. This cp only contains those additional tests, the code changes already exist in master.
https://mattermost.atlassian.net/browse/MM-22703
Original PR to release-5.21
https://github.com/mattermost/mattermost-webapp/pull/4994
> MM-22970: fix highlighting of at mentions of self (#4994)

- e2e/package.json
- e2e/run_tests.js
There's a breaking change in the latest mochawesome-merge where we should use `files` options instead of `reportDir`
https://www.npmjs.com/package/mochawesome-merge
> Fix mochawesome merge

- package-lock.json
- package.json
* Update react window hash
https://mattermost.atlassian.net/browse/MM-22698
https://github.com/mattermost/react-window/pull/26
Note: i don't know how we can QA review this. As we don't have a repo. Changes have a minimal impact as to log to console if the issue happens and not show a loading indicator and fallback to the changes we had for 5.20v
> MM-22698 Fix for unread channel getting stuck at Loading indicator

- actions/views/channel_sidebar.ts
Fixing a bug where expanding a collapsed category isn't persisted to storage.
https://mattermost.atlassian.net/browse/MM-21584
> MM-21584 Replace removeItem call with setItem

- utils/markdown/index.test.js
- utils/markdown/renderer.tsx
The code that controls the index on numbered lists wasn't triggering when someone starts a list with 0 because the falsey value was causing the if condition to be fail incorrectly.
https://mattermost.atlassian.net/browse/MM-22857
> MM-22857 Fix lists being unable to start with 0

- components/post_view/post/index.js
- components/post_view/post/index.test.js
- components/search_results_item/index.js
- components/search_results_item/search_results_item.jsx
- utils/post_utils.jsx
- utils/post_utils.test.jsx
MM-22989 - Adding reply count to root posts in RHS
Comment count should be added in the search sidebar for root posts.
https://mattermost.atlassian.net/browse/MM-22989
> MM-22989 - Adding reply count to root posts in RHS (Search, Flags, Pinned)

- e2e/cypress/integration/at_mentions/at_mentions_spec.js
- e2e/cypress/integration/enterprise/elasticsearch/renaming_spec.js
- e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
- e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
- e2e/cypress/integration/messaging/focus_move_spec.js
- e2e/cypress/integration/messaging/message_permalink_spec.js
- e2e/cypress/integration/messaging/permalink_loading_indicator_spec.js
- e2e/cypress/integration/messaging/permalink_message_edit_spec.js
- e2e/cypress/integration/messaging/post_options_menu_spec.js
- e2e/cypress/integration/post_header/post_header_spec.js
- e2e/cypress/plugins/getClipboard.js
- e2e/cypress/plugins/index.js
- e2e/package-lock.json
- e2e/package.json
Fix failing specs on messaging, at mentions, elastic search, and interactive dialog. Added new plugin for clipboard.
NA
> Fix messaging specs

- components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.jsx.snap
- components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.jsx
- components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
- components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
- components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
- i18n/en.json
- utils/constants.jsx
Exposes the group mentions permission in the system console UI 
Defaults to Off for guests and true for members
> [MM-22962] Expose group mentions in the system console UI

- components/channel_header/components/header_icon_wrapper.js
- components/popover_list_members/popover_list_members.jsx
- components/search_bar/index.jsx
- components/search_bar/search_bar.jsx
- plugins/channel_header_plug/channel_header_plug.jsx
Hides the tooltips that are displayed when the user clicks on a channel popover item and the dropdown is displayed
Fixes https://mattermost.atlassian.net/browse/MM-22670
Fix versions
> [MM-22670] - Hide tooltips in header when the dropdowns are open

- sass/components/_emoticons.scss
Removes the added line-height for devices apart from windows OS in order to not cut off the emojis on Catalina OS
https://mattermost.atlassian.net/browse/MM-22715
Fix version: 5.22.0
> [MM-22715] - Fix line-height for emojis on Catalina OS

- e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
- e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
- e2e/cypress/support/api_commands.js
- e2e/cypress/support/hooks.js
This adds some E2E tests for the new sidebar around:
- Unread state of channels
- Behaviour of channels when leaving/archiving them
- Switching to channels by clicking on them
- Using alt+arrow hotkeys for switching channels
- Using ctrl/cmd+k to open the channel switcher
I also added a hook to set up test conditions with a specific server config. Let me know what you think about that since it might be useful to set up some other testing conditions since calling it once covers both setup and teardown of the test state.
https://mattermost.atlassian.net/browse/MM-20900
> MM-20900 Add basic E2E tests for new sidebar

- components/admin_console/team_channel_settings/channel/details/channel_details.tsx
- Updates the value of `manage_members` from the server after the user switches the channel privacy 
- Also fixes a bug where `isPrivacyChanging` would remain true even after submitting the form
https://github.com/mattermost/mattermost-server/pull/13813
> [MM-22212] Update manage_members from server after switching channel privacy

- components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
When loading the new Experimental Channel Sidebar, if you have a DM with a bot, you will get a white screen. This was caused by the state not being initialized when the component was loaded. This PR fixes that.
https://mattermost.atlassian.net/browse/MM-23429
> [MM-23429] Fixed an issue where the new sidebar will not load with a DM with a bot

- e2e/cypress/integration/channel/header_spec.js
- e2e/cypress/integration/channel/send_message_via_profile_popover_spec.js
- e2e/cypress/integration/channel/toast_spec.js
- channel header --> due to recent DOM change
- profile popover --> fix the original assertion
- toast
- test against a new team
- visit town-square and off-topic by clicking at LHS instead of visiting by URL to decrease page loading time and make it more of user interaction
- add more visibility checks
none, failing on Cypress daily
> Fix failing E2E tests on channel header, profile popover and toast

- package.json
With my latest PR merged to master, an older version of redux was merged. This PR fixes this.
> Update mattermost-redux to latest version

- components/legacy_team_sidebar/components/team_button.jsx
- components/legacy_team_sidebar/legacy_team_sidebar_controller.jsx
The merge of https://github.com/mattermost/mattermost-webapp/pull/3678 didn't play well with the new team drag&drop feature, not showing the indicators when pressing `Ctrl + Alt` and not taking into account the user's team order when using the shortcut.
This PR fixes both issues
https://mattermost.atlassian.net/browse/MM-23447
> [MM-23447] Fixes swith teams shortcut after reorder teams feature was added

- components/dot_menu/dot_menu.jsx
On desktop app, in some cases when you click on dot menu and copy permalink, the dot menu stayed highlighted. Removing preventDefault seems to fix the issue.
https://mattermost.atlassian.net/browse/MM-22777
Fix versions
> [MM-22777] - Fix dot menu highlight on desktop app

- components/channel_header/__snapshots__/channel_header.test.jsx.snap
- components/channel_header/channel_header.js
After merging the functionality for the new channel header popover to expand on hover and also show only when the lines are longer than the space available, there was a bug introduced, when there are bullet points in the description but the first line was as long as the space available, you couldn't expand the popover. This fix checks for single new lines as well and it seems to cover all edge cases. 
https://mattermost.atlassian.net/browse/MM-23428
Fix versions
> [MM-23428] - Check for single new lines in channel header popover

- utils/utils.jsx
- Fixes an issue where dragging and dropping a file on pre-chromium edge would result in console errors and the overlay not appearing
- Edge does not support `.contains` so replacing it with `.includes` fixes the drag and drop issue 
- This issue is only reproducible on pre-chromium edge.
https://mattermost.atlassian.net/browse/MM-22937
> [MM-22937] Fix Edge case by using includes instead of contains

- components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap
- components/file_attachment/filename_overlay.jsx
- sass/components/_files.scss
Fixes the download image tooltip that was off-centre because it was relating to the svg and not the whole button.
https://mattermost.atlassian.net/browse/MM-22877
Fix versions
> [MM-22877] - Fix download image button tooltip

- components/rhs_comment/index.js
- components/rhs_comment/rhs_comment.jsx
- components/rhs_comment/rhs_comment.test.jsx
Fixes the JS error caused by not passing emojiMap to createAriaLabelForPost in rhs_comment.jsx
https://mattermost.atlassian.net/browse/MM-23101
Fix versions
> [MM-23101] - Fix error in RHS posts with emoji

- package-lock.json
- package.json
Updates the mattermost-redux hash to the latest 5.22 commit as opposed to master
Commit for reference https://github.com/mattermost/mattermost-redux/commit/da29aa57072011ceffbb76d95c1c9bd2efb07939
> Update redux hash to redux release-5.22

- components/post_view/post_list_virtualized/post_list_virtualized.jsx
- components/toast_wrapper/toast_wrapper.jsx
This should be a race cause with atBottom somehow changing this to be how it used to be in 5.20v. I changed the condition for not mounting the toasts till `atBottom` has an assigned value is because to have a simpler logic on mount. 
The change was made at https://github.com/mattermost/mattermost-webapp/pull/4825/files#diff-dacf7e63a72c7be54c626d95244525efL560 
* Not sure of the tests to add here, suggestions are welcome.
https://mattermost.atlassian.net/browse/MM-23458
Ticket to fix the onScroll event in virt list https://mattermost.atlassian.net/browse/MM-23494
> MM-23458 Fix missing toast for unreads

- sass/layout/_sidebar-left.scss
Aligns the close and mention icon horizontally 
https://mattermost.atlassian.net/browse/MM-23412
Fix 5.22.0
> [MM-23412] - Align mention and close icon horizontally

- sass/layout/_sidebar-left.scss
Fixes the chevron icon positioning on firefox. From what I tested on Chrome and Safari, the max-height and line-height are redundant here as they get the line-height from the icons:before selector, but on firefox the specificity was different. 
https://mattermost.atlassian.net/browse/MM-23445
> [MM-23445] - Fix chevron icon on Firefox

- components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
- e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
- e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js
E2E tests for the new sidebar functionality.
I wasn't able to create one to test the history arrows, as they are specific to the desktop app and Cypress doesn't seem to have a reliable way to test the desktop app.
https://mattermost.atlassian.net/browse/MM-20901
> [MM-20901] E2E tests for history arrows, channel switcher and new channel dropdown

- components/multiselect/__snapshots__/multiselect.test.tsx.snap
- components/multiselect/multiselect.tsx
- sass/components/_multi-select.scss
- The original issue was just that the dark mode styles were too dark - the cause of which i traced back to https://github.com/mattermost/mattermost-webapp/pull/5011
- Turns out the select input of this modal never modified its colours to match the current theme so I made some changes to its styles to look good in both dark and light themes
- A lot of the styles were borrowed heavily from `/components/widgets/inputs/user_emails_input.scss` (from the invite team members select list) 
https://mattermost.atlassian.net/browse/MM-23414
> [MM-23414] Fix up multiselect styling

- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
Looks like type check step is failing on master cause of this missing required prop in tests
> Add isMuted as prop in tests to fix type check

- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
Cherry pick of #5162 on release-5.22.
- #5162: Add isMuted as prop in tests to fix type check
/cc  @fm2munsh
> Automated cherry pick of #5162

- components/legacy_team_sidebar/components/team_button.jsx
- sass/layout/_team-sidebar.scss
Add a transition out effect on the drag handle of the team icons when the dragging is in progress
https://mattermost.atlassian.net/browse/MM-23441
> [MM-23441] - Animate drag and drop handles to transition out on drag

- components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
- components/post_markdown/post_markdown.jsx
All channel mentions getting highlighted even when they shouldn't has been fixed in this PR. 
https://mattermost.atlassian.net/browse/MM-23583
> [MM-23583] Fix all channel mentions getting highlighted even when they shouldn't

- actions/views/channel.js
- actions/views/channel.test.js
- components/post_view/floating_timestamp/__snapshots__/floating_timestamp.test.jsx.snap
- components/post_view/floating_timestamp/floating_timestamp.jsx
- components/post_view/floating_timestamp/floating_timestamp.test.jsx
- components/post_view/floating_timestamp/index.js
- components/post_view/post_list_virtualized/post_list_virtualized.jsx
- components/toast_wrapper/index.jsx
- components/toast_wrapper/toast_wrapper.jsx
- components/toast_wrapper/toast_wrapper.test.jsx
- reducers/views/channel.js
- sass/layout/_post.scss
- selectors/views/channel.js
- utils/constants.jsx
Push the toast by 50px when toast is present
Issue: `FloatingTimestamp` component need to know if any toasts are present in the UI. toasts state is only available in ToastWrapper as of now.
Solutions:
1. Either use DOM manipulation like we do in few places of codebase and add a class when toast is present with `add.classList`
2. Add a redux state to keep track of toast and use a selector 
3. Use something like ReactClone and get the required prop from `ToastWrapper`.
4. We could have `FloatingTimestamp` in ToastWrapper 
i went with 3 reasons being
1. Really hacky and msot places we use in codebase tend to fail and cause regressions 
2. Feel like too much of work for such a small use case
4. need to add couple more props to ToastWrapper so it can be passed to  `FloatingTimestamp` …
> MM-22757 Fix for date toast placement in web mobile view

- components/toast_wrapper/toast_wrapper.jsx
- components/toast_wrapper/toast_wrapper.test.jsx
* Add an additional check to `atBottom` with `null`
Theoretically this could happen with this series of events
1. User switches channel to a previously visited out of sync channel(System from sleep)
2. atBottom value is not set yet but the posts from since API loads.
The condition `this.props.postListIds[0] !== prevProps.postListIds[0];` is true and `!this.props.atBottom` is also true making a call `updateNewMessagesAtInChannel` and updating the line.
It would have been perfect if the logic was considered only for new messages but atm it is not possible and has a high dev cost to it too. Possibly with upcoming changes to redux state idata .e marking channels out of sync can help.
https://mattermost.atlassian.net/browse/MM-23203
> MM-23203 Fix for missing new messages line on socket reconnect

- components/sidebar/sidebar_category_list/__snapshots__/sidebar_category_list.test.tsx.snap
- components/sidebar/sidebar_category_list/sidebar_category_list.tsx
- components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
With the new experimental channel sidebar, unread/at-mention counts on the Desktop App server tabs stopped working. The Desktop app is looking for a specific DOM element ID (`#sidebar-left`) and class (`unread-title`), which is no longer used with the new experimental channel sidebar. Temporarily adding the id and class to the new experimental channel sidebar so the Desktop App continues to function as expected.
Longer term, this should be fixed on the Desktop App side by removing the DOM scraping and adding proper communication between the Webapp and Desktop App.
https://mattermost.atlassian.net/browse/MM-23454
> [MM-23454] Re-enable mention count on desktop app server tabs

- components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
- components/post_view/reaction/reaction.jsx
- Removes the line break present in the reaction overlay
https://mattermost.atlassian.net/browse/MM-23449
> [MM-23449] Remove extra line break in reaction overlay

- sass/layout/_team-sidebar.scss
After merging the PR for animating the drag and drop handle, the unread indicator has disappeared. Here is a fix, which shows the indicator but turns it into a drag handle on hover. This is what the contributor who first submitted the drag and drop feature seems to have intended. I think this needs further discussion with UX about the small details that we missed. 
https://mattermost.atlassian.net/browse/MM-23622
> [MM-23622] - Fix hiding of the unread indicator because of drag and drop

- e2e/cypress/integration/interactive_menu/slack_parsing_message_button_spec.js
- e2e/webhook_serve.js
Test Steps:
Text: `a < a | b > a`
1. Create an interactive message buttons via webhook
2. Click on a message button that skips parsing
- verify that it renders original "Text"
3. Click on a message button that do parsing
- verify that it renders as Markdown link (based on Slack link parsing)
JIRA ticket - https://mattermost.atlassian.net/browse/MM-22825
- Has server changes (https://github.com/mattermost/mattermost-server/pull/13976)
> MM-22825 Add E2E on skipping Slack-compatible interactive message response

- components/toast_wrapper/toast_wrapper.jsx
- components/toast_wrapper/toast_wrapper.test.jsx
Based on the latest changes from https://github.com/mattermost/mattermost-webapp/pull/5109 we also need a check for `atBottom` for archive toast which was missed in the previous PR.
https://mattermost.atlassian.net/browse/MM-23458
> MM-23458 Add missing atBottom condition for showMessageHistoryToast

- components/sidebar/__snapshots__/sidebar.test.tsx.snap
- components/sidebar/add_channel_dropdown.tsx
- components/sidebar/index.ts
- components/sidebar/sidebar.test.tsx
- components/sidebar/sidebar.tsx
I had overlooked permissioning for the add channel dropdown on the new sidebar. This PR adds the correct permissions for those 2 menu items so they will only display if the user has permissions.
https://mattermost.atlassian.net/browse/MM-23612
> [MM-23612] Added proper permissions around add_channel_dropdown menu items

- actions/websocket_actions.jsx
- e2e/cypress/integration/websocket/handle_removed_user_spec.js
The websocket action for removing a user from a channel was dispatching the `LEAVE_CHANNEL` action too late, so that `redirectUserToDefaultTeam` would redirect the user back to the same channel they just left.
This PR fixes that behaviour and adds tests for the new and old sidebar (since the old sidebar handled this by calling `redirectUserToDefaultTeam` after the state had updated)
https://mattermost.atlassian.net/browse/MM-23589
> [MM-23589] Fixed the handleRemovedUserEvent to wait for the user to leave the channel before redirecting

- e2e/cypress/integration/keyboard_shortcuts/alt_option_plus_up_down_spec.js
- Cypress test for https://github.com/mattermost/mattermost-webapp/pull/5056
- Keyboard shortcut for Alt+UP - https://docs.google.com/spreadsheets/d/1TF0rjeCjL8YISwfweIQYJMadbE28g3ar7w5VCFGexZU/edit#gid=1372533646&range=7:7
- Keyboard shortcut for Alt+DOWN - https://docs.google.com/spreadsheets/d/1TF0rjeCjL8YISwfweIQYJMadbE28g3ar7w5VCFGexZU/edit#gid=1372533646&range=8:8
JIRA ticket - https://mattermost.atlassian.net/browse/MM-22482
> MM-22482 Add E2E tests for Alt+Up/Down keyboard shortcuts

- e2e/cypress/fixtures/account_setting_sections.json
- e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
- e2e/cypress/integration/enterprise/system_console/use_channel_mentions_system_scheme_spec.js
- e2e/cypress/integration/enterprise/system_console/use_channel_mentions_team_scheme_spec.js
Fixed failures in channel_moderation_spec & accessibility_account_settings_spec
* channel_moderation_spec - Channel was created by a user and hence the user will be the Channel Admin and will not obey the Channel Moderation Settings. Modified the test to create channel as a different user. 
* accessibility_account_settings_spec - New Sidebar related Account setting was displayed. Updated the test to reflect the same. 
* use_channel_mentions_team_scheme_spec & use_channel_mentions_system_scheme_spec - A recent bug fix https://mattermost.atlassian.net/browse/MM-23430 caused changes in the expectations in the test. 
NA. Fixed based on local & daily runs.
> Fixed failures in Channel Moderation & Accessibility Tests

- e2e/cypress/fixtures/partial_default_config.json
This is a quick fix on several failing test on daily.
none
> E2E: Set default config of TeamSettings.ExperimentalTownSquareIsReadOnly=false

- components/sidebar/sidebar_category_list/__snapshots__/sidebar_category_list.test.tsx.snap
- components/sidebar/sidebar_category_list/sidebar_category_list.tsx
@devinbinnie @bradjcoughlin Let me know what you think about the 100ms debounce time for this. We could probably drop it since all of the `onTransitionEnd` events from each child should come in faster than that, but I default to 100ms for this sort of thing.
I also haven't figured out a way to add tests for this since I haven't been able to reproduce it, but if anyone has any suggestions, I'd appreciate them.
@srkgupta I haven't been able to reproduce the exact issue as you're seeing it, but I'm not surprised there's some edge cases around the showing and hiding of those indicators. I've added some extra logic to update them after an animation happens, so hopefully this should reduce the chances that we run into an edge case like that.
https://mattermost.atlassian.net/browse/MM-23577
> MM-23577 Update More Unread Indicators after animations

- components/sidebar/sidebar_channel/sidebar_direct_channel/index.ts
The new sidebar was missing some logic from the old one that was causing some issues with loading bot icon images. The logic has been fixed in this PR.
This one isn't easy to reproduce, but with this fix you shouldn't see issues loading the icons for bot users like the GitHub and JIRA bots.
https://mattermost.atlassian.net/browse/MM-23635
> [MM-23635] Only load bot icon url when it's been updated

- components/sidebar/sidebar_channel/sidebar_direct_channel/index.ts
Cherry pick of #5200 on release-5.22.
- #5200: Only load bot icon url when it's been updated
> Automated cherry pick of #5200

- components/admin_console/team_channel_settings/channel/details/channel_details.tsx
- components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx
Prior to our ESLint upgrade, I had to use some tricks to bypass our ESLinter. 
Now that our ESlinter is upgraded, I can use the proper Typescript optional chaining without unconventional  code.
No Ticket
> [No-Ticket] Remove unconventional code and use proper Typescript code convention

- .circleci/config.yml
Checkout the server repo over HTTPS on CircleCI to avoid `StrictHostKeyChecking=no`.
https://mattermost.atlassian.net/browse/IS-299
> IS-299: Checkout server over HTTPS on CircleCI

- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
Was incorrectly importing `CopyUrlContextMenu`, so that clicking 'Copy Link' would throw a JS error. This PR fixes that.
https://mattermost.atlassian.net/browse/MM-23641
> [MM-23641] Fixed a bad import of a redux component in new sidebar

- components/user_settings/modal/user_settings_modal.tsx
There is a bug on master that prevents the user from clicking on an option in the user settings modal. This seems to fix the issue. IMO important to merge soon because it happens on daily. 
https://mattermost.atlassian.net/browse/MM-23686
> [MM-23686] - Fix user settings modal bug on master

- components/legacy_team_sidebar/legacy_team_sidebar_controller.jsx
Cherry pick of #5220 on release-5.22.
- #5220: prevent team number shortcut from being handled by Safari
> Automated cherry pick of #5220

- sass/components/_emojisprite.scss
- sass/components/_emoticons.scss
- sass/responsive/_mobile.scss
MM-23660 - Updating emoji popup on desktop and mobile
https://mattermost.atlassian.net/browse/MM-23660
> MM-23660 - Updating emoji popup on desktop and mobile

- e2e/run_tests.js
Add webhook integration between Cypress test and BizOps channel to enable/start server analytics validation.  As discussed, identifying information to be sent are:
- User ID (sysadmin)
- Team ID (ad-1)
- Test start and end Date/time
Non-blocking but to start sending diagnostic report via webhook:
1. RudderStack feature is merged into master
2. Cypress server config needs to have the following:
- Rudderstack key/URL
- diagnostics enabled
3. Set DIAGNOSTIC_WEBHOOK_URL env (already given)
PR to follow once above items above are fulfilled/given.
JIRA ticket: https://mattermost.atlassian.net/browse/MM-23767
> MM-23767 Add webhook integration between Cypress test and server analytics validation

- components/integrations/bots/add_bot/add_bot.jsx
- components/integrations/bots/bot.jsx
- components/integrations/bots/bot.test.jsx
- components/integrations/bots/bots.jsx
- components/integrations/bots/bots.test.jsx
- components/integrations/bots/index.js
- components/invitation_modal/invitation_modal_confirm_step_row.jsx
- components/post_profile_picture/post_profile_picture.jsx
- components/post_view/channel_intro_message/channel_intro_message.jsx
- components/suggestion/at_mention_provider/at_mention_suggestion.jsx
- components/suggestion/search_user_provider.jsx
- components/suggestion/switch_channel_provider.jsx
- components/user_profile/user_profile.jsx
- components/user_settings/general/user_settings_general.jsx
- components/widgets/inputs/users_emails_input.jsx
- utils/utils.jsx
- utils/utils.test.jsx
- The utility method `imageURLForUser` has a single method `userIdOrObject` but it looks like it always expects a user object as opposed to a user_id.
- ~Since there were a lot of places that called it with just an id I decided to modify the existing method to handle strings _or_ user object as it looks like thats how it was defined.~
- Modified all places that call the utility function to pass in a user or an object with an id property
- Also renamed the parameters for `imageURLForUser` and `imageURLForTeam` since they only expect `user` and `team` objects and id strings
- https://mattermost.atlassian.net/browse/MM-23751
- Go to `integrations/bots`, create a bot and give it an avatar.
- Observe that the avatar is loaded when hitting the integrations/bots page after reloading
> [MM-23715] Modify all calls to imageURLForUser to pass a user id and default last_picture_update to 0

- e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
- e2e/cypress/integration/accessibility/accessibility_post_spec.js
- e2e/cypress/integration/accessibility/accessibility_sidebar_spec.js
Updated failing Accessibility tests based on the latest label changes on the App
N/A. Updated based on daily runs.
> Updated Accessibility tests based on the latest label changes on the App

- e2e/cypress.json
Reverting timeout in Cypress.json file changes made in this PR:
https://github.com/mattermost/mattermost-webapp/pull/5257/
> Reverting timeout in Cypress.json file.

- components/plugin_marketplace/marketplace_list/marketplace_list.jsx
This was broken in https://github.com/mattermost/mattermost-webapp/pull/4567. 
I assume the E2E test would have caught this bug, but they are broken for me locally. 
https://mattermost.atlassian.net/browse/MM-23833
> [MM-23833] Fix missing labels in Marketplace modal

- components/confirm_modal.test.tsx
- components/confirm_modal.tsx
- The component was not updating when checked was enabled so the checkbox would never toggle from on to off, this PR fixes that 
https://mattermost.atlassian.net/browse/MM-23841
> [MM-23841] Allow confirm modal to update when state.checked is modified

- components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
- components/post_view/reaction/reaction.jsx
- Reverting my change made here https://github.com/mattermost/mattermost-webapp/pull/5161 since it seems like this line break is needed once more.
- I'm not sure how there were multiple line breaks occurring before but I am entirely unable to reproduce that on master now after re-adding in the original line break. I'm assuming that it was some css that was modified that I cant find.  
https://mattermost.atlassian.net/browse/MM-23899
Before 
After
> [MM-23899] Revert "Remove extra line break in reaction overlay"

- components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
- components/post_view/reaction/reaction.jsx
Cherry pick of #5278 on release-5.22.
- #5278: Revert "Remove extra line break in reaction overlay"
/cc  @fm2munsh
> Automated cherry pick of #5278

- components/channel_view/index.js
- There was an extra argument so teammate was always undefined resulting in a deactivated DM channel never showing up as deactivated
- https://mattermost.atlassian.net/browse/MM-24035
> [MM-24035] Fix getDeactivatedChannel selector for DM channel

- components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
- components/edit_post_modal/edit_post_modal.jsx
- components/edit_post_modal/edit_post_modal.test.jsx
- components/edit_post_modal/index.js
- Pass `useChannelMentions` to the `Textbox` component on the edit post modal
https://mattermost.atlassian.net/browse/MM-23997
> [MM-23997] Ensure channel mentions permission is set on edit post

- components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
- components/invitation_modal/invitation_modal.jsx
- components/invitation_modal/invitation_modal_members_step.jsx
- components/invitation_modal/invitation_modal_members_step.test.jsx
- This modal is used for inviting users to a team however it was never sending a `not_in_team_id` parameter, and ended up just falling back to `UserStore.Search` on the server. However some server changes made it so that that behaviour would default to `SearchUsersInTeam`.
- This PR ensures now that the invite to team modal sends the `not_in_team_id` and ends up calling the correct store function always 
https://mattermost.atlassian.net/browse/MM-23977
> [MM-23977] Ensure users not in team when searching for users

- components/integrations/bots/add_bot/add_bot.jsx
- components/integrations/bots/add_bot/index.js
- Fixes a case where `FormattedMessage` was used as a select option resulting in `object Object` being shown as the text
- Fixes user not being passed as prop to add bot
- Also modified call to `getUsers(state)[id]` into `getUser(state, id)`
- https://mattermost.atlassian.net/browse/MM-23995
- https://mattermost.atlassian.net/browse/MM-23996
> [MM-23995] [MM-23996] Fix improper rendering of bot profile picture and bot roles

- e2e/cypress/integration/integrations/message_to_channel_via_slash_command_spec.js
- e2e/package.json
- e2e/webhook_serve.js
E2E for sending message to other channel via custom slash command.  Cypress test for the ff:
1. [MM-T706 Error Handling for Slash Commands](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/3969606)
2. [MM-T707 Send a message to a different channel than where the slash command was issued from](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/3969607)
JIRA ticket: https://mattermost.atlassian.net/browse/MM-18457
> MM-18457 E2E for sending message to other channel via custom slash command

- i18n/uk.json
https://github.com/mattermost/mattermost-webapp/pull/5259
Looks like a lot of the translations were replaced with new ones so the translations only needed to be re-added for UK
> [MM-23716] Re-add create_post write translations (#5259) (cherry-pick)

- components/channel_header/__snapshots__/channel_header.test.jsx.snap
- components/channel_header/channel_header.js
- plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap
- plugins/channel_header_plug/channel_header_plug.jsx
- plugins/channel_header_plug/channel_header_plug.test.jsx
- sass/layout/_headers.scss
Allow up to 5 plugin header buttons to be displayed before a menu appears. 
https://mattermost.atlassian.net/browse/MM-22917
**Incident response, Zoom, and Webex at the same time!**
**After 5 the menu returns**
> MM-22917 Allow up to 5 plugin header buttons to be displayed before a menu appears.

- components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
- components/post_markdown/system_message_helpers.jsx
Mentions were set to false in change header message. This updates it to true as per ticket requirements.
https://mattermost.atlassian.net/browse/MM-24222
Fix v5.23.0
> [MM-24222] - Set mentions to true in header change message

- components/create_post/create_post.jsx
- components/create_post/create_post.test.jsx
Cherry pick of #5197 on release-5.23.
- #5197: Blur text box to reset before focusing
> Automated cherry pick of #5197

- package-lock.json
- package.json
This maintenance PR 
- updates `package-lock` to fix the issue that it is stale (has changes on clean `npm install`)
- moves `@types/redux-mock-store` to devDependencies
- removes duplicated `@types/highlight.js` from dependencies
No package version or other code changes.
> Refactor: move @types/* to devDeps and update stale package-lock

- components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
When a channel name is too long for the sidebar, there should be a tooltip that pops up when hovering over the channel to show the full name. This was broken on Desktop with the new sidebar.
This PR re-adds a `div` element needed for the `OverlayTrigger`, and also re-inserts code to remove the extra `aria` tag.
https://mattermost.atlassian.net/browse/MM-23384
> [MM-23384] Readded div to wrap around contents of OverlayTrigger

- components/suggestion/search_channel_suggestion/search_channel_suggestion.jsx
https://github.com/mattermost/mattermost-webapp/pull/4402 introduced a minor regression on the search popover when using the `in:` keyword, as the `onMouseMove` event was not registered in the `SearchChannelSuggestion` component. This PR just adds it back.
I have tried to add a test for this using Cypress, but I have no luck hovering over the item to check that the CSS class is added. Looks like this is a well-known pain point in Cypress; it even has [a dedicated documentation page](https://docs.cypress.io/api/commands/hover.html#Workarounds), but none of the workarounds worked for me. I'd love to hear other ideas for testing this.
https://mattermost.atlassian.net/browse/MM-24296 (this PR only solves the first issue described in the ticket, I think we should discuss the CSS one …
> Highlight hovered items when searching with "in:"

- actions/websocket_actions.jsx
- Builds off of https://github.com/mattermost/mattermost-webapp/pull/5331 look at latest commit for my changes
- Dispatch `getChannelMemberCountsByGroup` when a user updates is called in order to ensure timezone counts are accurate since a user may change their timezone resulting in the confirmation modal displaying out of date information if the page hasnt been reloaded in a while.
- https://mattermost.atlassian.net/browse/MM-24356
> [MM-24356] Dispatch getChannelMemberCountsByGroup if timezones are enabled when user is updated

- components/channel_view/index.js
- e2e/cypress/integration/messaging/channel_menu_spec.js
As part of https://github.com/mattermost/mattermost-webapp/pull/5337, a check was added to avoid showing `createPost` until after channel roles are loaded. Unfortunately, when leaving a channel, the state is such that the channel exists but the channel membership does not, resulting in attempting to dereference undefined.
Fix the check not to assume channel memberships exist, and add an e2e test for leaving the channel via the header menu.
Fixes: https://mattermost.atlassian.net/browse/MM-24590
> MM-24590: fix roles check on leave

- components/post_view/new_message_separator/__snapshots__/new_message_separator.test.jsx.snap
- components/post_view/new_message_separator/new_message_separator.jsx
This PR adds add the `new-separator` class to the `NewMessageSeparator` component. 
By wrapping the `NotificationSeparator` component with this class, the css will adjust according to the settings in `Account Settings` > `Display` > `Theme` > `Custom Theme` >  `Center Channel Styles` > `New Message Separator`
Tested the following cases:
* change in color exists after marking message unread (with post menu pulldown option)
* line and message can be seen changing colors (in the background of the account settings modal) as you change the color picker value
* As 2nd user, post message to channel user1 is not viewing, to create new unread messages. User1 switches to channel and sees the new line component with the correct color.
https://mattermost.atlassian.net/browse/MM-23885
Original PR that …
> add new-separator class to NewMessageSeparator component

- components/channel_header_dropdown/menu_items/close_message/close_message.js
- components/channel_header_dropdown/menu_items/close_message/close_message.test.js
- components/channel_header_dropdown/menu_items/close_message/index.js
- e2e/cypress/integration/channel/close_direct_group_spec.js
- e2e/cypress/support/ui_commands.js
PR #4791 fixed an issue with redirecting the user to direct or group messages when they were the last ones to be visited. But a collateral regression was introduced: closing DMs or GMs stopped working, as the user was returned to the closed channel immediately after leaving it.
That commit was reverted (#4995), and then applied again in PR #5224, which also introduced the new `leaveDirectChannel` function to correctly handle the new issue with closing DMs or GMs. But this function was only applied to the case where the user closed the channel through the `x` button on the sidebar channel item.
However, the bug remained in place when the user closed the channel using the "Close {Direct, Group} Message" option in the channel header dropdown menu.
This PR just fixes this second use case by …
> MM-24506: Fix closing DM/GM from header dropdown menu

- plugins/index.js
When a plugin is loaded or removed, we log the plugin id, but not the version. Customers often send us screenshots of this loading, and it would be helpful to identify the versions at play, so let's include those.
Fixes: https://mattermost.atlassian.net/browse/MM-24857
Note that the duplicate "loading/loaded" is present before and after. Haven't investigated that yet.
Before:
After:
> MM-24857 console.log plugin versions

- e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
- e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js
Fix tests failing on URL check.
- Test on URL failed since the URL on address bar resolved immediately before loading a page. Workaround is to check for element in a page first before URL.
none, failing on Cypress daily test
> E2E: Fix tests failing on URL check

- sass/routes/_settings.scss
The text box under Custom Theme in the Account Settings > Display > Theme section cannot be horizontally resized, as it expands beyond the visible area of the Settings modal.
I have styled all `textarea` elements under the user settings with `resize: vertical`.
https://mattermost.atlassian.net/browse/MM-24032
Before:
After:
> MM-24032: Make settings' textarea only vertically resizable

- components/about_build_modal/__snapshots__/about_build_modal.test.jsx.snap
- components/about_build_modal/about_build_modal.jsx
While the TOS/PP links are hard-coded on the about modal, the code still checked for an (empty) configured value (so as to hide on other screens) when rendering the dash between them. Fix this to make the dash equally hard-coded.
Fixes: https://mattermost.atlassian.net/browse/MM-24856
Before:
After:
> fix missing dash between tos/pp

- components/suggestion/command_provider.jsx
- components/suggestion/command_provider.test.js
This PR will add support of the icons in slash command autocomplete
Fixes https://mattermost.atlassian.net/browse/MM-24767
- Has server changes (https://github.com/mattermost/mattermost-server/pull/14489)
- demo plugin (https://github.com/mattermost/mattermost-plugin-demo/pull/104)
> [MM-24767] autocomplete icons

- sass/components/_post.scss
MM-24490 - Updating UI for link previews name
https://mattermost.atlassian.net/browse/MM-24490
> MM-24490 - Updating UI for link previews name

- e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
- e2e/cypress/integration/system_console/sidebar_link_navigation_spec.js
Fix tests for sidebar link in system console.  Instead of navigating on each section in system console, simply click on the sidebar and verify the corresponding URL is correct.
none, failing on daily Cypress tests.
> E2E: fix tests for sidebar link in system console

- e2e/cypress/integration/interactive_dialog/boolean_spec.js
- e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
- e2e/cypress/integration/interactive_dialog/scrollable_spec.js
- e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
- e2e/cypress/integration/interactive_menu/basic_options_spec.js
- e2e/cypress/integration/interactive_menu/select_with_keys_spec.js
- e2e/cypress/integration/interactive_menu/slack_parsing_message_button_spec.js
Clean up unnecessary update to config as it's already defined as default, especially in setting AllowedUntrustedInternalConnections on test specs.  This will allow CI server to communicate with custom webhook server by a predefined network's subnet address in docker-compose [see [link](https://github.com/saturninoabril/mattermost-cypress-docker/blob/master/mattermost-e2e/docker-compose.yml#L78)].  I remain as is the value on partial_default_config.json for local dev, and will only replace in CI ([link](https://github.com/saturninoabril/mattermost-cypress-docker/blob/master/Makefile#L59))
Note: Reference repo will eventually move to our org.
JIRA ticket - https://mattermost.atlassian.net/browse/MM-24942
> MM-24942 Clean up setting AllowedUntrustedInternalConnections on test specs

- components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.jsx.snap
- components/add_user_to_channel_modal/add_user_to_channel_modal.jsx
- sass/components/_modal.scss
- sass/components/_suggestion-list.scss
- sass/utils/_modifiers.scss
The `SuggestionList` inside the `AddUserToChannelModel` component had a fixed width that rendered smaller than the modal input box width. This PR computes the width of the `SuggestionList` as the parent div width minus two times the padding in the parent div.
This is *very* hacky, and that is why I have narrowed the change to a specific class inside the component. But we have plans to rework this modal in the near future, so we should get rid of this code hopefully sooner than later.
https://mattermost.atlassian.net/browse/MM-24033
> MM-24033: Compute suggestion list width

- actions/websocket_actions.jsx
- e2e/cypress/integration/websocket/handle_removed_user_spec.js
This PR fixes an issue with the RHS: when a user has the Recent Mentions RHS or the Flagged Posts RHS open and they are kicked out of a channel, the messages from that channel should disappear. This was introduced in https://github.com/mattermost/mattermost-webapp/pull/5320, that removed the dispatching of the `LEAVE_CHANNEL` event when a user was removed from a channel, as its position was causing race conditions when using the `/leave` command.
The thing is that we need to:
1. dispatch the `LEAVE_CHANNEL` event in order to fix https://mattermost.atlassian.net/browse/MM-24918.
2. in case the user is leaving a channel, make sure that we dispatch this event after we have pushed the new URL to the browser history in order to fix https://mattermost.atlassian.net/browse/MM-23994
3. in case …
> MM-24918: Make sure flagged posts and recent mentions from old channel are excluded in RHS

- e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
- e2e/cypress/support/index.js
- added timeout after visiting url, for some reason, page is partially loaded and test start and then page refreshes so the hamburger menu is closed during verification
- added file path back to report for easier tracking failing tests
NA
> Fixed accessibility dropdowns spec and added file path to report

- e2e/cypress/integration/markdown/markdown_image_spec.js
- e2e/cypress/integration/messaging/image_attachment_spec.js
Fix failing tests on image attachment and markdown.  Updates on dimensions were due to recent CSS changes. These are some of the pain points in which visual regression testing could help us a lot.
Note: Other failing tests on `markdown_image_spec` were fixed by the other PR on default config, specifically on setting up `SiteURL `, `EnableSVGs` and `ImageProxySettings` - https://github.com/mattermost/mattermost-webapp/pull/5477
none, failing on daily Cypress test.
> E2E: fix failing tests on image attachment and markdown

- package-lock.json
Seems like the package-lock is broken and since the npm ci is installing from the package-lock.json file this is breaking the build. I tried the same step which is run from the CI locally and npm install is fixing automagically the package-lock.json with the below code which makes the build not break.
> Fix build failures

- e2e/cypress.json
- e2e/cypress/integration/enterprise/ldap_group/channel_modes_spec.js
- e2e/cypress/integration/enterprise/ldap_group/groups_assign_roles_spec.js
- e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
Fix failing tests related to LDAP by adding flag whenever we're running tests on CI.  On CI, `cy.checkRunLDAPSync()` is no longer necessary since we're restoring dumped DB with OpenLDAP synced already.
No change on local development. Will work as is.
Jira ticket: https://mattermost.atlassian.net/browse/MM-25245
> MM-25245 Fix failing tests related to LDAP when running on CI

- package-lock.json
- package.json
- Changes are in redux - https://github.com/mattermost/mattermost-redux/pull/1155
- Redux PR has to go in first and then package needs to be updated here
> Fix release-5.19 build by tying jest to a specific verison 

- webpack.config.js
Disables Brotli encoding in "dev" mode to speed up the save-to-reload time during front-end development.
https://mattermost.atlassian.net/browse/MM-25369
https://github.com/mattermost/mattermost-server/pull/14608
> MM-25369: Disable Brotli in 'dev' mode.

- components/admin_console/admin_definition.jsx
- i18n/en.json
First introduced in Mattermost 5.17
N/A
> Fix "rending > rendering" typo in Latex help text

- components/member_list_team/index.ts
- components/member_list_team/member_list_team.tsx
If you search for a particular member in the team members modal on chat facing side after a user has had their role updated, it will show an incorrect / out of date role. This PR aims to fix this problem.
https://mattermost.atlassian.net/browse/MM-23690
- ~~Has server changes https://github.com/mattermost/mattermost-server/pull/14615~~
- ~~Has Redux changes https://github.com/mattermost/mattermost-redux/pull/1160~~
> [MM-23690] Not showing updated / correct roles when searching for user in the team members modal after their role has been updated

- components/admin_console/system_users/system_users_dropdown/index.ts
- components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx
- components/do_verify_email/do_verify_email.tsx
- components/new_channel_flow/index.ts
- components/new_channel_flow/new_channel_flow.tsx
- package-lock.json
- package.json
In https://github.com/mattermost/mattermost-redux/pull/1162, I renamed the `Error` type we were using to `ServerError` since it conflicted with the built-in `Error` type, but I forgot to do that on the webapp side as well. This fixes that.
https://github.com/mattermost/mattermost-redux/pull/1162
> Rename Error type to ServerError

- e2e/save_report.js
- e2e/utils/report.js
Improve Cypress reporting to accommodate master/release/PR in partial/full view.  This is to improve visibility/highlighting priorities over other test results when everything is posted in a channel.
Jira ticket - https://mattermost.atlassian.net/browse/MM-25527
__Partial View:__
__Full View:__
> MM-25527 Improve Cypress reporting to accommodate master/release/PR in partial/full view

- actions/websocket_actions.jsx
Fixes group highlighting not getting updated when a group is updated via system console
https://mattermost.atlassian.net/browse/MM-25448
> [MM-20775] Fix: Highlighting is not updated correctly when Group Mention is modified/enabled/disabled until user reloads the page

- components/view_image/view_image.jsx
This PR Removes 'keyup' event listener when `ViewImageModal` is closed. 
The arrow keys were being used to navigate through images displayed on the modal, and they kept firing even after the modal was closed. Hanging on to the listener is a source of memory leaks.
https://mattermost.atlassian.net/browse/MM-23804
> Remove event listener when modal is closed

- sass/layout/_navigation.scss
At some point during v5.24 development, the CSS style sheet stopped using the `background-color` for the `badge-notify` class on the mobile view header mention badge, and started using the `background` provided by the `badge` class.
This PR changes the order of the classes in the CSS file such that the `.badge-notify` class has a higher specificity that will override the `background-color` of the default `badge` class.
https://mattermost.atlassian.net/browse/MM-24929
> [MM-24929] Force red background on mobile view header mention badge

- e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
> Fix expand/shrink label

- e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
- e2e/cypress/integration/enterprise/teams/search_teams_spec.js
Fixed on tests in LDAP due to outdated use of `uuid`.
None
> E2E: Quick fix on failing tests in LDAP

- sass/components/_search.scss
- utils/utils.jsx
The new Search Options popout was using a static colour for the hover state.
This PR switches to using a dimmed version of the center channel colour, which works on all themes.
https://mattermost.atlassian.net/browse/MM-25409
> [MM-25409] Switch to css variable for search options hover state

- components/suggestion/channel_mention_provider.jsx
- components/suggestion/search_channel_with_permissions_provider.jsx
- sass/components/_suggestion-list.scss
Autocomplete ui fixes
MM-25492 - Aligning autocomplete to the left
MM-25485 - Updating icon sizes in switcher modal
MM-25483 - Updating icon sizes in popover
https://mattermost.atlassian.net/browse/MM-25492
https://mattermost.atlassian.net/browse/MM-25485
https://mattermost.atlassian.net/browse/MM-25483
> MM-25492, MM-25485, MM-25483 - Autocomplete ui fixes

- components/suggestion/channel_mention_provider.jsx
- components/suggestion/search_channel_with_permissions_provider.jsx
- sass/components/_suggestion-list.scss
Cherry pick of #5593 on release-5.24.
- #5593: MM-25492 - Alignign autocomplete to the left
> Automated cherry pick of #5593

- sass/components/_popover.scss
The autocomplete popover in the search bar wasn't scrollable using a mouse, it only worked with its own keyboard navigation.
This PR brings back the scrolling to that area.
@asaadmahmood @nevyangelova Let me know if this UX is acceptable, as I wasn't sure if there was a visual reason the scrollbar was removed.
https://mattermost.atlassian.net/browse/MM-25533
> [MM-25533] Restored scrolling to autocomplete popover in search bar

- e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
Fix cypress command. Use `contains` instead of `findByText` because `findByText` cannot query text that's broken up by tags
NA
> Fix common commands

- components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.jsx.snap
- components/post_view/post_add_channel_member/post_add_channel_member.jsx
- components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
- i18n/en.json
- When a large number of out of channel group members is mentioned it should not show the text as expanded by default, this fixes that.
- https://mattermost.atlassian.net/browse/MM-25685
> [MM-25685] Change out of channel msg to show X others when >3 users

- sass/routes/_admin-console.scss
When the announcement bar is visible in the System Console, the sidebar is pushed down by 32px, thus cutting off the bottom-most sidebar item.
This PR adds 32px of padding to the bottom of the sidebar so that nothing can be cutoff.
https://mattermost.atlassian.net/browse/MM-25661
> [MM-25561] Added extra padding on admin console sidebar when announcement bar is visible

- e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
- e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
- e2e/cypress/support/ui_commands.js
- hotkeys - fix class selector
- user status commands - replace `findByText` with `contains` since text is broken up with tags
- leave channel - made sure `{enter}` is part of message and not a separate command; a slash command message without immediate `{enter}` brings up autocomplete which brings focus out of post text box, hence, the test failure
NA
> Fix hotkeys, user status commands, leave channel specs

- e2e/cypress/support/api_commands.d.ts
- e2e/cypress/support/api_commands.js
- e2e/package-lock.json
- e2e/package.json
This PR documents Cypress custom commands by declaring types under Cypress namespace. This will help contributors for quick reference via IDE intellisense and to easily find samples, params, etc of each custom command.
Changes include:
- adding mattermost-redux for typings of models
- moving of command's comments from the function to typings under Cypress namespace.
PR will be submitted in partial per group of models/endpoints.
Jira ticket - https://mattermost.atlassian.net/browse/MM-25768
> MM-25768 Add typings to Cypress custom commands for quick reference via IDE intellisense

- components/channel_selector_modal/channel_selector_modal.jsx
- Fixes a small bug rendering the wrong icon introduced in https://github.com/mattermost/mattermost-webapp/pull/5264
- https://mattermost.atlassian.net/browse/MM-25828
> [MM-25828] Fix incorrect globe / lock icon for private and public channels

- e2e/cypress/integration/messaging/at_mentions_spec.js
- e2e/cypress/integration/messaging/date_separator_spec.js
- e2e/cypress/integration/messaging/header_spec.js
- e2e/cypress/integration/messaging/message_draft_then_switch_channel_spec.js
- e2e/cypress/integration/search/post_search_display_spec.js
Minor changes only
- at_mentions_spec - visit off-topic channel directly
- header_spec - updated pinned posts text verification
- message_draft_then_switch_channel_spec - updated draft icon selector
- post_search_display_spec - updated help popup verification
- data_separator_spec - not fixing the issue but resetting locale so that other tests are not affected
NA
> Fix unstable messaging specs

- components/user_list_row/user_list_row.jsx
I forget why I wrapped those in a string during the ESLint changes, but that was clearly the wrong thing to do since React automatically escapes HTML entities appearing in strings.
https://mattermost.atlassian.net/browse/MM-25557
> MM-25557 Fix &nbsp; appearing in the View Members modal

- sass/components/_post.scss
Firefox by default disabled copying of buttons, which is what the user name in the channel is. This fix enables back the selection.
**https://mattermost.atlassian.net/browse/MM-24154**
> [MM-24154] - Fix firefox select issue

- components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
- components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
- components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
- components/sidebar/sidebar_menu/sidebar_menu.tsx
When a category is collapsed, and you use keyboard navigation to navigate through the channels, the channel menu icon was still focusable on collapsed channels.
This PR adds a `tabIndex=-1` to those channels when collapsed.
https://mattermost.atlassian.net/browse/MM-24205
> [MM-24205] Remove tabability from collapsed channel menus

- utils/admin_console_index.test.jsx
- These tests should not check the order of search results in languages other than english since they can change if the community updates translations as seen here https://github.com/mattermost/mattermost-webapp/pull/5688
- https://mattermost.atlassian.net/browse/MM-25921
> [MM-25921] Modify admin console index tests to ignore order check in spanish

- .npmrc
With this file in the root dir, npm will always use exact versions when updating `package.json`. This [file](https://github.com/mattermost/mattermost-mobile/blob/master/.npmrc) already exists in the mattermost-mobile repo.
https://mattermost.atlassian.net/browse/MM-25856
> Add .npmrc file to enforce save-exact

- sass/responsive/_mobile.scss
The Add Channel Dropdown class was missing in the mobile CSS file, so the menu wasn't popping out correctly like the sidebar ones were. This PR fixes that.
https://mattermost.atlassian.net/browse/MM-24968
> [MM-24968] Fixed add channel dropdown on mobile to pop out correctly

- components/add_users_to_team_modal/index.ts
- Ensures that inactive (deleted) users do not show up in the add users to team modal
- https://mattermost.atlassian.net/browse/MM-25771
> [MM-25771] Ensure users displayed in add users to team modal are not inactive

- components/add_users_to_team_modal/index.ts
Cherry pick of #5701 on release-5.24.
- #5701: Ensure users displayed in add users to team modal are not
/cc  @fmunshi
> Automated cherry pick of #5701

- e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
- e2e/cypress/integration/account_settings/general/nickname_spec.js
- e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
- e2e/cypress/integration/channel/channel_groups_spec.js
- e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
- e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
- e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
- e2e/cypress/integration/menus/main_menu_spec.js
- e2e/cypress/integration/menus/status_dropdown_spec.js
- e2e/cypress/integration/messaging/message_draft_then_switch_channel_spec.js
- e2e/cypress/integration/messaging/system_message_limited_options_spec.js
Promoting consistently passing unstable tests to prod stage. 
- These tests have consistently passed in the last 4 runs and hence have been identified to be moved to prod stage. 
NA
> Promoting consistently passing unstable tests to prod stage

- e2e/cypress/integration/menus/status_dropdown_spec.js
- This test is currently not failing but causing other tests to fail because the status modal has been left open. This will hopefully at least run the other tests past the modal failures.
NA
> E2E: Fix status dropdown spec

- components/invitation_modal/invitation_modal_members_step.jsx
- components/invitation_modal/invitation_modal_members_step.test.jsx
This PR reverts to existing behavior for inviting team members that are already member of the target team.
<https://mattermost.atlassian.net/browse/MM-25816
> [MM25816] invitation_modal: revert to existing behavior for inviting existing ones

- sass/routes/_admin-console.scss
- Decreases filtered user list height when announcement banner is present
- Also reduces the filtered user list height by a bit when the banner is not present to prevent a scrollbar from appearing on the side
- https://mattermost.atlassian.net/browse/MM-25952
Before: 
After:
> [MM-25952] Fix license banner hiding revoke sessions

- e2e/cypress/integration/messaging/message_spec.js
This test ensures that the replies to a conversation focuses on the "Add a comment" textbox by default.
Fixes https://github.com/mattermost/mattermost-server/issues/14081
- Has server changes - N/A
- Has redux changes - N/A
- Has mobile changes - N/A
Here is the screenshot at the end of the test:
> [MM23361] Focus remains in the RHS text box

- sass/layout/_sidebar-left.scss
This changed the `font-weight` on muted channels back to 400.
https://mattermost.atlassian.net/browse/MM-25947
> [MM-25947] Removed font-weight: 300 for muted channels

- components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
- components/link_tooltip/link_tooltip.tsx
MM-25904 - Updating link tooltips z-index for plugins
https://mattermost.atlassian.net/browse/MM-25904
> MM-25904 - Updating link tooltips z-index for plugins

- components/suggestion/suggestion_box.jsx
- components/suggestion/suggestion_box.test.jsx
This is a regression caused by https://github.com/mattermost/mattermost-webapp/pull/5702. The linked PR prevents results change on focus to remove a flicker of results disappearing and reappearing on focus change. This caused this issue where quick switcher opens but it does not populate results because it was based on focus in. Instead of changing to a logic where only pretext change causes the computation of results change. 
https://mattermost.atlassian.net/browse/MM-26008
> MM-26008 Fix for suggestions not appearing when opening quick switcher

- components/do_verify_email/do_verify_email.tsx
Manual cherry-pick of https://github.com/mattermost/mattermost-webapp/pull/5706
> MM-25889 - Restored announcement type for email verification (#5706)

- components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
- components/link_tooltip/link_tooltip.test.tsx
- components/link_tooltip/link_tooltip.tsx
- utils/__snapshots__/message_html_to_component.test.jsx.snap
- utils/message_html_to_component.jsx
When a hyperlink is generated, depending on the structure of the text, there can be several components on the top level of its React children. When `messageHtmlToComponent` renders the `LinkTooltip` component, it is only passing the first child of its `children` array.
This PR makes sure all children are passed, so the `LinkTooltip` component can render all of them.
```[`foo` and `bar`](https://www.google.com)``` was being rendered as [`foo`](https://www.google.com), instead of [`foo` and `bar`](https://www.google.com)
https://mattermost.atlassian.net/browse/MM-25808
Before
After
> Fix LinkTooltip with uncommon link format

- .circleci/config.yml
Skip `restore_cache` on the `install` step, since we use `npm ci` which only turns around and throws away the restored `node_modules`. This saves time both from the restore, and the the recursive directory removal. (We still `save_cache` since we use the resulting `node_modules` in other jobs.)
Also tweak the use of the workspace persistence in the `build` and `build-storybook` to only persist the newly generated artifacts instead of the entire workspace a second time. This dramatically shortens the `Persisting to Workspace` step.
Fixes: https://mattermost.atlassian.net/browse/MM-25138
> MM-25138: CircleCI caching improvements

- e2e/cypress/fixtures/partial_default_config.json
Fix failing tests due to read-only config after HA cluster is enabled
none, failing on daily
> Cypress/E2E: Fix failing tests due to read-only config after HA cluster is enabled

- sass/components/_select.scss
The interactive dialog's dropdown component did not render the border properly in dark themes.
Solving it was a matter of removing a hardcoded value that was overwriting the color defined in https://github.com/mattermost/mattermost-webapp/blob/master/sass/components/_forms.scss#L165, which uses a theme-aware variable.
https://mattermost.atlassian.net/browse/MM-24791
--
> MM-24791: Fix invisible border in interactive dialog's dropdown

- i18n/i18n.jsx
I think this was broken because we updated the dependencies. The `require`
calls were getting the object including the default export insted of using
directly that default value as the imported value. Now using import is working
fine.
[MM-26426](https://mattermost.atlassian.net/browse/MM-26426)
> [MM-26426] - Fix translations broken by the webpack require call

- e2e/applitools.config.js
- e2e/cypress.json
- e2e/cypress/integration/visual_regression/helpers.js
- e2e/cypress/integration/visual_regression/system_console/about_section_spec.js
- e2e/cypress/integration/visual_regression/system_console/authentication_section_spec.js
- e2e/cypress/integration/visual_regression/system_console/compliance_section_spec.js
- e2e/cypress/integration/visual_regression/system_console/environment_section_spec.js
- e2e/cypress/plugins/index.js
- e2e/cypress/support/index.js
- e2e/cypress/support/visual_commands.d.ts
- e2e/cypress/support/visual_commands.js
- e2e/cypress/tsconfig.json
- e2e/package-lock.json
- e2e/package.json
- e2e/run_tests.js
Integrate visual regression testing using Applitools with Cypress.
The feature is disabled by default.
To be able to run, you may get API key from Applitools and set into your env variable, and then run:
```bash
ENABLE_VISUAL_TEST=true node run_tests.js --group='@visual_regression'
```
Note: 
1. On CI, visual regression testing will run separately from functional testing.
2. It's recommended to separate visual regression tests (into a dedicated folder `/visual_regression`)  from functional tests:
- to avoid flaky tests by directly going into the UI and do snapshot instead of mixing with other tests/actions
- to not incur long duration to current overall tests since visual regression will take some time to process snapshots/results
There are three steps to get the screenshot.
1. Open the …
> MM-23788 Setup for visual regression testing

- e2e/cypress/integration/websocket/handle_removed_user/helpers.js
Fixes the failing tests on removing user - both for old and new sidebar.
This was introduced by my latest change to cy.apiGetMe.
> Fix failing tests on handle removed user

- plugins/registry.js
Components can be more than functions in modern react. This fixes our check so we catch those ones too.
> Fix element check.

- plugins/registry.js
Strings are used here in plugins and are not valid react elements. But they also can't be turned directly into components as `React.createElement("Not a component name")` thinks you mean `<Not a component name/>`
> Consitering strings in resolve element. 

- components/suggestion/search_channel_suggestion/index.js
- components/suggestion/search_channel_suggestion/search_channel_suggestion.jsx
searching with the `in:` modifier would display the wrong avatar for the user in the dm.
[MM-25903](https://mattermost.atlassian.net/browse/MM-25903)
> [MM-25903] fix avatar for dms in search

- components/create_comment/create_comment.jsx
- components/create_comment/create_comment.test.jsx
- components/create_post/create_post.jsx
- components/create_post/create_post.test.jsx
- components/edit_post_modal/edit_post_modal.jsx
- utils/paste.tsx
fix adding tables into post edits
while working on it, i found it wasn't keeping caretposition when pasting tables from google docs spreadhseets, so I changed that as well
[MM-25785](https://mattermost.atlassian.net/browse/MM-25785)
> [MM-25785] allow pasting tables into edit post, keep caret position

- e2e/cypress/integration/integrations/incoming/disallow_username_profile_override_spec.js
- e2e/cypress/support/index.js
- e2e/cypress/support/task_commands.js
- e2e/cypress/support/ui_commands.d.ts
- e2e/cypress/support/ui_commands.js
- e2e/cypress/utils/index.js
Cypress test for MM-T622 which disallow override of username and profile picture
JIRA ticket: https://mattermost.atlassian.net/browse/MM-26069
Test case: https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T622
> MM-26069 Cypress test for MM-T622 which disallow override of username and profile picture

- e2e/cypress/integration/account_settings/display/channel_display_mode_spec.js
- e2e/cypress/integration/messaging/no_matches_for_autocomplete_spec.js
Cypress/E2E on no matches for user and channel autocomplete
Jira ticket: https://mattermost.atlassian.net/browse/MM-26074
TM4J tickets: [MM-T270](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T270) and [MM-T269](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T269)
> MM-26074 Cypress test for MM-T270 and MM-T269 - No Matches for Autocomplete

- e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
Cypress/E2E on Changes to Account Settings are not saved when user does not click on Save button
- added test case
- fixed channel switcher toggling; original implementation did not really toggle the switch and was giving false positives
- minor refactor
Jira ticket: https://mattermost.atlassian.net/browse/MM-26074
TM4J tickets: [MM-T305](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T305)
> MM-26074 Cypress Test for MM-T305 - Account Settings are not autosaved

- e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
- e2e/cypress/integration/system_console/group_configuration_spec.js
- e2e/cypress/integration/team_settings/teammates_pagination_spec.js
- e2e/cypress/integration/team_settings/teams_spec.js
- e2e/cypress/support/api/team.d.ts
- e2e/cypress/support/api/team.js
- e2e/cypress/support/api/user.d.ts
- e2e/cypress/support/api/user.js
- e2e/cypress/support/index.js
Standardize returned data and add typings for intellisense of the ff custom API commands:
- apiGetTeamsForUser
- apiAddUserToTeam
- apiGetUsersNotInTeam
- apiAddUsersToTeam
JIRA ticket: https://mattermost.atlassian.net/browse/MM-26075
> MM-26075 Standardized Cypress API commands - apiGetTeamsForUser, apiAddUserToTeam and apiGetUsersNotInTeam

- components/edit_post_modal/edit_post_modal.jsx
- components/rhs_comment/index.js
- components/rhs_root_post/index.js
- components/textbox/index.ts
Previously, we could attach a ref to any `connect`-based component fine, but that's no longer possible since the new version of `react-redux` changed `connect` to generate a functional component, so we have to forward the ref to the underlying component to be able to do anything with it.
https://mattermost.atlassian.net/browse/MM-26616
https://mattermost.atlassian.net/browse/MM-26597
https://mattermost.atlassian.net/browse/MM-26672
https://mattermost.atlassian.net/browse/MM-26605
> MM-26597/MM-26672/MM-26616/MM-26605 Properly forward ref to Textbox

- e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
- e2e/cypress/integration/enterprise/system_console/archived_channels_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/helpers.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
- e2e/cypress/integration/enterprise/teams/search_teams_spec.js
Cypress/E2E: fix failing tests due to search-input test ID change.
There are valid bugs on archived channels and search teams specs - https://mattermost.atlassian.net/browse/MM-26762 and https://mattermost.atlassian.net/browse/MM-26782 
> Cypress/E2E: fix failing tests due to search-input test ID change

- e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js
- e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
- e2e/package-lock.json
- e2e/package.json
Cypress/E2E on Changing the timezone in app settings updates post timestamps
- added test cases for timezone
- did not cover date separator test cases as they already exist in `date_separator_spec`
- minor verification checks added to clock display spec
Jira ticket: https://mattermost.atlassian.net/browse/MM-26074
TM4J tickets: [MM-T301](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T301)
> MM-26074 Cypress Test for MM-T301 - Timezone Display mode

- e2e/cypress/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js
Test case - https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/3983854
Steps:
1. Edit incoming webhook
2. Click update and post incoming webhook
Expected:
1. Verify that the webhook is successfully posted
2. Username shows as what is in the payload
3. Profile picture shows as what is in the payload
4. There should be no status indicator for the bot
5. Clicking both the username and the profile image will show the profile popover
6. BOT label is next to the user's name instead of below the profile image
7. Pop-Over matches profile image and user name supplied. And the pop-over shows a footer of `this post was created by an integration from @<user who made the webhook>
JIRA ticket - …
> MM-26069 Cypress test: Incoming webhook - Payload username and profile picture override in-app settings

- components/admin_console/team_channel_settings/team/list/team_list.jsx
Fixes `next page of Teams does not respect search results`
https://mattermost.atlassian.net/browse/MM-26782
> [MM-26782] Webapp/Admin console: Next page of Teams does not respect search results

- sass/layout/_sidebar-left.scss
* Override height for small screens new category
There is a specificity override for height for smaller screens making the `height:0` in effective
https://mattermost.atlassian.net/browse/MM-26628
> MM-26628 Fix for empty space for new category in mobile view

- e2e/cypress/integration/messaging/post_options_menu_spec.js
Fixes a failing check in test "M18679 - Mobile view: Post options menu (3-dots) is present on a reply post in RHS", was looking for "Flag" instead of "Save" in the mobile menu. 
This is a follow-up on https://github.com/mattermost/mattermost-webapp/pull/5498
You may also refer to [this thread on MM](https://community-daily.mattermost.com/core/pl/wu4afpaiobgd3ey8sudqcmn5tw).
NA
> [E2E] Fix test M18679 - Mobile view: Post options menu (3-dots) is present on a reply post in RHS

- components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
- components/post_markdown/post_markdown.jsx
- e2e/cypress/integration/messaging/at_mentions_user_spec.js
With https://github.com/mattermost/mattermost-webapp/pull/5372, we reintroduced a bug that prevented self mentions to be highlighted with certain punctuation.
This PR just brings back the fix from https://github.com/mattermost/mattermost-webapp/pull/4994, which solved this same bug back in the day.
https://mattermost.atlassian.net/browse/MM-26751
Highlights are back :tada:
> MM-26751: Fix highlighting of at-mentions of self

- e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js
- e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
- e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
- e2e/cypress/integration/account_settings/sidebar/channel_switcher_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
- e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
- e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
- e2e/cypress/integration/integrations/incoming_webhook/basic_formatting_spec.js
- e2e/cypress/integration/integrations/incoming_webhook/disallow_username_profile_override_spec.js
- e2e/cypress/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js
- e2e/cypress/integration/integrations/incoming_webhook/setting_spec.js
- e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
- e2e/cypress/integration/messaging/channel_users_interactions_spec.js
- e2e/cypress/integration/messaging/date_separator_spec.js
- e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
- e2e/cypress/integration/messaging/message_permalink_spec.js
- e2e/cypress/integration/messaging/post_header_spec.js
- e2e/cypress/integration/messaging/post_textbox_height_spec.js
- e2e/cypress/integration/messaging/private_channel_open_spec.js
- e2e/cypress/integration/search/search_user_post_spec.js
- e2e/cypress/integration/signin_authentication/forgot_password_spec.js
- e2e/cypress/integration/system_console/plugin_upload_spec.js
Promoted tests:
- most came from the recent SDETs campaign on automating those test cases from the backlogs.
Demoted tests are found to be automation bugs like those flaky tests:
- due to post menu being rendered at the bottom for newly created channel
- pixel difference
- uncaught error on `scrollTo`
Other demoted tests need to be investigated further. Unfortunately, those can't make into v5.26.
Test run - https://mm-cypress-report.s3.amazonaws.com/603-for-release-5-26-master/mochawesome.html
However, let's closely monitor once other PR gets merged for 5.26 like this [one](https://github.com/mattermost/mattermost-webapp/pull/5498). I'll try to run the test on that PR too.
none, based on daily Cypress run
> Cypress/E2E: promote/demote specs for v5.26

- e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js
- e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
- e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
- e2e/cypress/integration/account_settings/sidebar/channel_switcher_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
- e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
- e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
- e2e/cypress/integration/integrations/incoming_webhook/basic_formatting_spec.js
- e2e/cypress/integration/integrations/incoming_webhook/disallow_username_profile_override_spec.js
- e2e/cypress/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js
- e2e/cypress/integration/integrations/incoming_webhook/setting_spec.js
- e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
- e2e/cypress/integration/messaging/channel_users_interactions_spec.js
- e2e/cypress/integration/messaging/date_separator_spec.js
- e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
- e2e/cypress/integration/messaging/message_permalink_spec.js
- e2e/cypress/integration/messaging/post_header_spec.js
- e2e/cypress/integration/messaging/post_textbox_height_spec.js
- e2e/cypress/integration/messaging/private_channel_open_spec.js
- e2e/cypress/integration/search/search_user_post_spec.js
- e2e/cypress/integration/signin_authentication/forgot_password_spec.js
- e2e/cypress/integration/system_console/plugin_upload_spec.js
Cherry pick of #5914 on release-5.26.
- #5914: promote/demote specs for v5.26
> Automated cherry pick of #5914

- e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
- e2e/cypress/support/ui_commands.js
Fix tests on timezone display by adding longer timeouts waiting for an element to show up.
None, (randomly) failing on daily Cypress run - both on master and release-5.26
> Cypress/E2E: fix tests on timezone display

- e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
- Try to fix timezone flakiness
- Load town-square instead of new channel
- Removed `@prod` since it's unstable for now
Note: new channel is passing for me locally so not really sure why it's failing on cypress.
> Cypress/E2E: Try to fix timezone display mode flakiness

- e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
- e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
- This is just a workaround to making sure highlighted item is correct; this test works for me locally without changes so workaround is for cypress only
> Cypress/E2E: Fix accessibility input fields

- e2e/cypress/integration/enterprise/system_console/channel_members_spec.js
- e2e/cypress/integration/enterprise/system_console/team_members_spec.js
- Fixed `apiAdminLogin` return per https://github.com/mattermost/mattermost-webapp/pull/5945#pullrequestreview-452374708
- Applied similar changes to `channel_members_spec`
> Cypress/E2E: Fix apiAdminLogin return object

- e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
- e2e/cypress/support/api/index.js
- e2e/cypress/support/api/status.d.ts
- e2e/cypress/support/api/status.js
- e2e/cypress/support/api/user.d.ts
- e2e/cypress/support/api/user.js
- e2e/cypress/support/api_commands.js
- e2e/cypress/support/external_commands.d.ts
- e2e/cypress/support/external_commands.js
- e2e/cypress/support/index.d.ts
Add type definitions and standard return to user/status/external api commands
- apiUpdateUserStatus
- apiPatchUser
- apiPatchMe
- apiRevokeUserSessions
- externalActivateUser
Jira ticket - https://mattermost.atlassian.net/browse/MM-26075
> MM-26075 Add type definitions and standard return to user/status/external api commands

- components/select_team/__snapshots__/select_team.test.jsx.snap
- components/select_team/select_team.jsx
- sass/responsive/_mobile.scss
- sass/routes/_signup.scss
changes done for the issues mentioned in the ticket
Fixes https://github.com/mattermost/mattermost-server/issues/14197
JIRA https://mattermost.atlassian.net/browse/MM-23749
* overflow-y addition on the mobile view 
* Before the change when the max-width was 400px 
* after the max-width is set to 800px
> Select Team list container should scale in width based on browser window width #14197

- components/quick_input.jsx
- components/suggestion/suggestion_box.jsx
- components/textbox/index.ts
- components/textbox/textbox.tsx
- package-lock.json
- plugins/export.js
- Tried to compile the Textbox from a plugin, and that was a mess.
- Instead, export the connected component into the window object.
- Now we're able to send in a custom input component to override `Textbox`'s `AutosizeTextArea`.
- In `QuickInput` we don't need the `channelId` so remove it, and if we're not using an `AutosizeTextArea` we don't need to pass in the `onHeightChange` prop (these were causing warnings went sent to a plain input, and I wanted to clean them up).
- Open to a better organization for the exported component. Maybe `window.components.Textbox`? -- done
- https://mattermost.atlassian.net/browse/MM-26733
> MM-26733 - Export Textbox so plugins can use it

- build/emoji/make-emojis
- components/suggestion/emoticon_provider.jsx
- components/suggestion/emoticon_provider.test.jsx
Replacing blacklist with blocklist
Jira ticket: https://mattermost.atlassian.net/browse/MM-27193
> Replacing blacklist with blocklist

- package-lock.json
- package.json
https://github.com/mattermost/mattermost-webapp/pull/5447 accidentally left mattermost-redux on a PR branch (with the latest master changes included) instead of master itself, so this is just some cleanup.
> Switch mattermost-redux back to master

- e2e/cypress/integration/channel_sidebar/category_collapsing_unread_filter_spec.js
- e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
- e2e/cypress/integration/channel_sidebar/drag_and_drop_spec.js
- e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
- e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js
- e2e/cypress/integration/websocket/handle_removed_user/new_sidebar_spec.js
- e2e/cypress/support/ui/index.js
- e2e/cypress/support/ui/modal.d.ts
- e2e/cypress/support/ui/modal.js
- Added `ui/modal.js` and `ui/modal.d.ts`
- Added `uiCloseModal` and `uiCloseWhatsNewModal` commands
- Closed "What's new" modal on affected tests
> Cypress/E2E: Fix channel sidebar specs

- e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
- Added scrollIntoView to make sure option is visible
> Cypress/E2E: Fix message display mode spec

- e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
- Added delay after tab to allow for css class to propagate
- Make sure row tested has drop-down actions (logged in user does not display drop-down, has to be a different user highlighted)
- Close popup modal
> Cypress/E2E: Fix accessibility modals dialogs

- components/login/login_mfa.jsx
Cherry pick of #5925 on release-5.26.
- #5925: Lowercase login ID before submitting in LoginMFA
> MM-26833: Lowercase login ID before submitting in LoginMFA (#5925)

- components/data_prefetch/index.ts
Debugging the ticket linked below, we found a potentially undefined value in `DataPrefetch`. We don't know whether this will fix the bug (whose reproduction is quite inconsistent), but adding the check will not hurt.
https://mattermost.atlassian.net/browse/MM-27167
> MM-27167: Add undefined check

- e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/helpers.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
Added fix for tests failing in the following spec files by scoping the search input within the `DataGrid_searchBar`:
- enterprise/ldap_group/search_channels_spec (5 tests)
- enterprise/system_console/channel_moderation/create_posts_spec(2 tests)
- enterprise/system_console/channel_moderation/manage_members_spec(4 tests)
- enterprise/system_console/channel_moderation/system_config_spec (1 test)
None
> Cypress/E2E: Fix Cypress tests for admin-console search in User Management > Channel

- e2e/cypress/support/ui/post_dropdown_menu.js
- e2e/cypress/support/ui_commands.js
- Added scrollIntoView as cypress workaround 
> Cypress/E2E: Fix specs failing due to dropdown menu

- components/sidebar/sidebar_menu/sidebar_menu.test.tsx
- components/sidebar/sidebar_menu/sidebar_menu.tsx
- utils/constants.jsx
We have a scroll listener https://github.com/mattermost/mattermost-webapp/blob/f5d93686ed6798813a6d1eb20182a1b6532a46ee/components/sidebar/sidebar_menu/sidebar_menu.tsx#L63 which is triggering `handleMenuToggle` call
https://github.com/mattermost/mattermost-webapp/blob/f5d93686ed6798813a6d1eb20182a1b6532a46ee/components/sidebar/sidebar_menu/sidebar_menu.tsx#L74-L79
Preventing the call if state hasn't changed to fix this
https://mattermost.atlassian.net/browse/MM-27346
> MM-27346 Fix for excessive analytic events on scroll of LHS

- sass/routes/_admin-console.scss
- Since webkit-touch-callout is only supported on iOS Safari (see https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout) this will make the original fix of `height: -webkit-fill-available;` apply when its needed and leave desktop chrome / other browsers unchanged.
- I dont have an iOS device to test this on so I havent actually confirmed that this works on iOS safari but I _can_ confirm that it doesnt break anything on chrome / any other desktop browsers 
- Milestone labeled as 5.26 but will also cherry-pick this to 5.25 when tested 
- https://mattermost.atlassian.net/browse/MM-27168
> [MM-27168]  Set -webkit-fill-available when on iOS Safari and 100vh otherwise

- sass/routes/_admin-console.scss
- Cherry pick of #6010 on release-5.25.
> [MM-27168] Cherry-pick of #6010 and remove previous -webkit-fill-available

- i18n/en.json
Sync message with its corresponding defaultMessage to prevent react-intl console errors in dev environments.
- https://mattermost.atlassian.net/browse/MM-27402
> [MM-27402] sync en message with defaultMessage

- e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
Adding fix for search in system console for team_and_channel_assign_roles_spec. There have been some changes in the scoping of the "Search" placeholder text. Ideally, I'd like to make finding the placeholder text simpler by adding a custom command since each search command needs at least 2 lines with the current setting. But need to find out all the places where the refactoring will be required. Thus checking in these changes.
(There are similar failures in `archived_channels_spec` but there are more failures than just the search component, hence taking a look at it separetely)
> Cypress/E2E: Fixing search in system console for team and channel assign roles

- e2e/cypress/integration/messaging/edit_message_spec.js
- e2e/cypress/integration/signin_authentication/subpath_login_spec.js
- Fixed selector for emoji picker search on `edit_message_spec`
- Updated cookie count on `subpath_login_spec`
> Cypress/E2E: Fix edit message spec

- e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
- e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
- The issue is that the input box for color is not editable anymore. The only way to assign a value now is to pick from the color popover. However, a particular hex or rgb color is not mapped to css. A workaround is to just click on a specific pixel coordinate which will likely not change since layout of color gradient is fixed.
- stabilized custom_theme_color_picker_spec
> Cypress/E2E: Fix custom theme specs

- sass/layout/_sidebar-left.scss
There's a bug in the current web app where the notification badge on the tabs in the desktop app changes its value when you hover over a channel. This is happening because we hide the badge and when that happens [the desktop app stops counting it](https://github.com/mattermost/desktop/blob/c2102bb25734a8c33fec635e0445873a23fd6559/src/browser/webview/mattermost.js#L146). I don't remember why we check this (it might be because we had multiple instances of the sidebar mounted at some point for some reason), but I've fixed it by hacking in a version of `display: none` that keeps the badge's height while still making it invisible
https://mattermost.atlassian.net/browse/MM-27358
> MM-27358 Change how we hide unread badges on hover

- NOTICE.txt
- components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
- package-lock.json
- package.json
- root.jsx
- sass/styles.scss
bootstrap-colorpicker was actually removed from the webapp back in https://github.com/mattermost/mattermost-webapp/pull/108, but it wasn't completely removed from package.json. Then, references to the JS code got re-added after a bad merge in https://github.com/mattermost/mattermost-webapp/pull/87.
This removes any dangling references to the library, and almost as importantly, it removes the only library that we include that depends on jQuery.
https://mattermost.atlassian.net/browse/MM-27409
https://github.com/mattermost/mattermost-webapp/pull/6026
> MM-27409 Remove references to bootstrap-colorpicker

- components/admin_console/team_channel_settings/channel/details/channel_details.tsx
- components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
- components/admin_console/team_channel_settings/channel/list/channel_list.tsx
- components/admin_console/team_channel_settings/team/details/team_details.jsx
- components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx
- Count of members successfully added / removed / promoted / demoted via team config page
- Count of members successfully added / removed / promoted / demoted via channel config page
- Event when a channel is successfully archived or unarchived
- Events for any filter applied to the channels listing listed below: 
```
'public_filter_applied_to_channel_list'
'private_filter_applied_to_channel_list'
'archived_filter_applied_to_channel_list'
'group_sync_filter_applied_to_channel_list'
'manual_invites_filter_applied_to_channel_list'
'team_id_filter_applied_to_channel_list'
``` 
- Event when a filter is applied for each role on the channel or team config page members block eg. `channel_admin_filter_applied_to_members_block` or `system_admin_filter_applied_to_members_block`
- …
> [MM-27249] Add telemetry to team and channel pages

- .eslintrc.json
- components/activity_log_modal/activity_log_modal.jsx
- components/admin_console/brand_image_setting/brand_image_setting.jsx
- components/code_preview.jsx
- components/create_comment/create_comment.jsx
- components/link_tooltip/link_tooltip.tsx
- components/logged_in/logged_in.jsx
- components/new_channel_modal/new_channel_modal.jsx
- components/rhs_thread/rhs_thread.tsx
- components/root/root.jsx
- components/setting_upload.jsx
- components/settings_sidebar.tsx
- components/suggestion/search_suggestion_list.jsx
- components/team_settings_modal/team_settings_modal.jsx
- components/tutorial/tutorial_view.jsx
- components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
- components/user_settings/display/user_settings_theme/premade_theme_chooser/premade_theme_chooser.jsx
- components/user_settings/display/user_settings_theme/user_settings_theme.jsx
- e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
- e2e/cypress/integration/emoji/recently_used_emoji_spec.js
- e2e/cypress/integration/messaging/system_message_spec.js
- package-lock.json
- package.json
- utils/utils.jsx
Taking inspiration from https://github.blog/2018-09-06-removing-jquery-from-github-frontend/, this adds eslint-plugin-jQuery to prevent people from adding new references to jQuery to the code base. Any new usage of jQuery will cause an ESLint error, and any old usage of it has been marked with a comment so people know using it is wrong (morally, of course).
This'll be followed by one or more Help Wanted tickets to actually update this code to not use jQuery.
https://mattermost.atlassian.net/browse/MM-16998
https://github.com/mattermost/mattermost-webapp/pull/6025
> MM-16998 Add eslint-plugin-jquery to block explicit usage of jquery

- e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
- Cypress failure is due to tab element not visible because of async loading of plugins; added scrollIntoView to marketplace tabs and plugin search elements
- Cleaned up comments
- Added missing verifications
- Disable AutomaticPrepackagedPlugins when EnableRemoteMarketplace is disabled to make sure no other plugins are loaded
- Potential cypress failure on `autofocus on search plugin input box`; will monitor if that fails on build server
> Cypress/E2E: Fix marketplace spec

- components/sidebar/__snapshots__/sidebar.test.tsx.snap
- components/sidebar/index.ts
- components/sidebar/sidebar.test.tsx
- components/sidebar/sidebar.tsx
PR fixes the Sidebar component failing when `currentTeam` is not (yet) set.
https://mattermost.atlassian.net/browse/MM-27306
> [MM-27306] Fix sidebar failing on missing currentTeam

- e2e/cypress/integration/messaging/autocomplete_shown_each_channel_spec.js
- I was able to repro the issue intermittently. However, it only fails when running through cypress. I wasn't able to repro it manually.
- This is just a potential workaround to cypress issue - make sure elements are visible before interaction and switch to an intermediate channel before final channel for verification; after I did this, I couldn't repro the issue anymore
None -  both on master and release-5.26
> Cypress/E2E: Potential workaround to fix autocomplete shown each channel spec

- e2e/cypress/integration/channel/more_public_channels_spec.js
Added E2E testing to confirm, In webapp, public channels in LHS -> more -> more modal box will have available channels list to join. And incase no channel available "No more channels to join" message will be displayed.
[Usecase](https://automation-test-cases.vercel.app/test/MM-T1664)
> MM-T1664  Channels don't disappear from More Channels modal E2E tests

- e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
- e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
- e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
- e2e/cypress/integration/account_settings/sidebar/channel_switcher_ui_spec.js
- e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
- e2e/cypress/integration/messaging/post_header_spec.js
Promoting tests from `unstable` to `prod` stage. The following tests, that have been run as "nightly-unstable" have been consistently passing in the last 7 days, hence promoting them to prod.
> Promoting tests that have consistently passed over the past week to prod

- e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
- Add github plugin verification
- Remove url for disabled marketplace
> Cypress/E2E: Add plugin verification

- e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
- The issue does not occur for me locally. This is just a potential workaround to cypress issue - tab after input menu item is clicked to make sure it's minimized in case click didn't register.
> Cypress/E2E: Potential workaround to fix member invitation ui spec

- e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
This test ensure that an error message is displayed if an invalid channel is entered for the `/mute` command.
https://automation-test-cases.vercel.app/test/MM-T710
> [MM-T710] /mute error message

- e2e/cypress/integration/toast/toast_spec.js
MM-T1787 Toast does not appear when all new messages are visible without scrolling down
[Usecase](https://automation-test-cases.vercel.app/test/MM-T1787)
> MM-T1787 Toast does not appear when all new messages are visible without scrolling down

- components/needs_team/needs_team.tsx
- package-lock.json
- package.json
- Since the pagination params were not being passed before it would just default to page 0 and per_page 60 on the server side, however the api endpoint was written to ignore pagination if the `per_page` value equalled `0`, this fixes that.
- https://mattermost.atlassian.net/browse/MM-26972
- https://github.com/mattermost/mattermost-redux/pull/1212
> [MM-26972] Skip pagination to allow loading all groups on needs team

- e2e/cypress/integration/toast/toast_spec.js
- Updated toast verification
- Added loop to scroll up on page to make sure beginning is reached
- Remaining failure exists in cypress run; not sure if the test case is still valid though.
> Cypress/E2E: Updated verification and added scroll up loop

- components/admin_console/feature_discovery/saml.tsx
- components/warn_metric_ack_modal/__snapshots__/warn_metric_ack_modal.test.tsx.snap
- components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
- i18n/en.json
For context, see https://community.mattermost.com/private-core/pl/zofoam4moigsbfuch8t3d8jrrc
@amyblais candidate for 5.26
> Update "Enterprise E20" to "Enterprise Edition"

- e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
- Click on a field label to close any opened drop-down menu
- Update validation verification as dialog is utilizing html5 input email validation
> Cypress/E2E: Fix full dialog spec

- e2e/cypress/integration/accessibility/accessibility_post_spec.js
- Allow emoji preview to load first before clicking on emoji
> Cypress/E2E: Potential workaround to emoji reaction click async issue

- e2e/cypress/integration/messaging/long_draft_spec.js
- e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
- e2e/cypress/integration/messaging/post_textbox_height_spec.js
- Made height verifications more flexible; avoided explicit pixel values when not initial height
> Cypress/E2E: Stabilize messaging height verifications

- e2e/cypress/integration/channel_settings/channel_name_validations_spec.js
This test validates that the words in channel names cannot be separated by more than one space, but the URL for the channel can contain words that separated by two dashes.
https://automation-test-cases.vercel.app/test/MM-T883
> [MM-T883] Channel URL validation for spaces between characters

- e2e/cypress/integration/integrations/integrations_spec.js
Adds an E2E test to check if Integration Page titles are bolded.
MM-T570
> [MM-T570] Integration Page titles are bolded

- webpack.config.js
- Remove segment from meta tag in root.html
**This fix prevents a fatal web client error for installations running under a subpath.**
Background: [This mattermost-server code block](https://github.com/mattermost/mattermost-server/blob/v5.26.0-rc1/utils/subpath.go#L88-L96)  is a part of the subpath-rewriting logic, and looks for a specific meta tag to rewrite. The strings were mismatched and failed, short-circuiting the rest of the subpath rewrite process.
Notes: 
- Related PR #5632 
- We should consider allowing subpath rewriting ([here](https://github.com/mattermost/mattermost-server/blob/v5.26.0-rc1/utils/subpath.go#L144-L149)) on local development when using webapp:`make build` and server:`make run-server`, which allows for the simulation of production-like environments.
- …
> MM-27537 remove segment remnant (fix hosting-in-subpath issue)

- e2e/cypress/integration/interactive_dialog/boolean_spec.js
- e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
- e2e/cypress/integration/interactive_dialog/scrollable_spec.js
- e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
- e2e/cypress/integration/interactive_menu/basic_options_spec.js
- e2e/cypress/integration/interactive_menu/select_with_keys_spec.js
Update test keys of interactive dialogs and menus for Cypress/TM4J integration.
Other: remove unnecessary use of random number since we're already isolating test by using new team/channels.
> Cypress/E2E: Update test key of interactive dialog

- e2e/cypress/integration/search/clear_input_spec.js
- Added an end to end test which test display value of the search doesnt change when flagged or save button icon is clicked
MM-T368
- ~Has server changes (please link here)~
- ~Has redux changes (please link here)~
- ~Has mobile changes (please link here)~
none
> MM-T368 - Text in search box should not clear when Pinned posts icon or Saved posts icon is clicked

- e2e/cypress/integration/system_console/group_configuration_spec.js
- Move cleanup group teams and channels to before each run
- Extracted methods for common verifications
- Added necessary timeouts and scrollIntoViews
> Cypress/E2E: Fix group configuration spec

- e2e/cypress/integration/messaging/inline_markdown_image_link_open_link_spec.js
Summary
Created a test where the test user posts a provided Markdown text containing an external link and asset that the post contains -
1. The correct url
2. The correct image
and that the link is valid. I tried to click on the link, but Cypress doesn't allow you to open a site not within the same domain, so I followed this guide https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__tab-handling-links/cypress/integration/tab_handling_anchor_links_spec.js  and made sure that the link in the a tag, when requesting it, is valid and provides html. However, please let me know if you would like me to test the url in a different way!
Below is another resource I used that said clicking on a tags is not recommended …
> MM-23350 Add e2e test for MM-23350

- actions/invite_actions.jsx
- actions/invite_actions.test.js
- i18n/en.json
The exception handler wasn't really handling error responses
sent from the server. We had to explicitly check the error field
for that and update the notSent array appropriately.
https://mattermost.atlassian.net/browse/MM-27507
- Has server changes (https://github.com/mattermost/mattermost-server/pull/15230)
> MM-27507: Show errors due to rate limiting while inviting

- e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
- e2e/cypress/support/api/team.d.ts
- e2e/cypress/support/api/team.js
- e2e/cypress/support/common_login_commands.js
- e2e/cypress/support/ldap_commands.js
- Fixed `Create a team` selector (for some reason `findByText` doesn't work)
- Moved setup to global so other `describe` blocks can be run independently
- Added `apiDeleteUserFromTeam` to remove user from team 
- Fixed timeouts and added waits to conditional checking
> Cypress/E2E: Fix ldap login spec

- e2e/cypress/integration/signin_authentication/login_spec.js
- Improved e2e tests on login page to more recent way of doing testing
- This also is being used for the blogpost
Test case - https://automation-test-cases.vercel.app/test/MM-T3306
none
none
> Tests : Improved E2E for login page

- components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
- components/more_direct_channels/more_direct_channels.test.jsx
- e2e/cypress/integration/multi_team_and_dm/gm_add_first_user_spec.js
- utils/utils.jsx
- webpack.config.js
In the dialog to create a new direct message (or group message), ensure that the user list is always sorted alphabetically, even after selecting a first user.
- Added e2e test with cypress
- Updated util function to render username span with unique html ID, this helps with a more precise selection of the user's display name + display username in the direct message dialog
- Updated snapshot for unit test that depends on the modification of the previous step
Related test case: [MM-T459](https://automation-test-cases.vercel.app/test/MM-T459)
Related ticket: [MM-1816](https://mattermost.atlassian.net/browse/MM-18186)
> MM-T459 E2E Test for Group Messaging: Add first user

- e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
- e2e/cypress/support/api/index.js
- e2e/cypress/support/api/ldap.d.ts
- e2e/cypress/support/api/ldap.js
- Made sure user is retrieved through a list to avoid 404 on non-existing user
- Added `apiLDAPTest ` and `apiLDAPSync` 
Note: [Cypress run passed](https://app.circleci.com/pipelines/github/saturninoabril/mattermost-cypress-docker?branch=fix-get-user-404)
> Cypress/E2E: Fix get user 404

- e2e/cypress/integration/integrations/incoming_webhook/copy_icon_spec.js
Adds an E2E test that checks if the copy icon for an Incoming Webhook URL is visible.
MM-T637
> [MM-T637] Copy icon for Incoming Webhook URL

- e2e/cypress/integration/enterprise/system_console/archived_channels_spec.js
- Renamed archived channel so it appears on top
Note: [Cypress run passed](https://app.circleci.com/pipelines/github/saturninoabril/mattermost-cypress-docker?branch=fix-archived-channel-name)
> Cypress/E2E: Fixed archived channel name

- e2e/cypress/integration/scroll/default_images_collapsed_spec.js
Adds an E2E test that switches the account settings for the test user to have images collapsed by default. The test checks that the posted image remains collapsed even after reloading the page.
MM-T2370
> [MM-T2370] Default images to collapsed

- e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
Wrote an end to end test which checks if image is clickable and opens a preview when post is made with inline markdown image
MM-T2389
> MM-T2389 Inline markdown image links open with preview modal

- sass/components/_emoticons.scss
Elements with the `emoticon` class can either be emoji images (named emojis and any supported unicode emojis) or spans containing a unicode emoji as text (unsupported unicode emojis). The text inside an `emoticon` element should be transparent for image-based emojis since it contains a copyable emoji shortname, but for unicode emojis, that needs to be not transparent or else we show an empty square. This also applies to the colour when selecting the text.
https://mattermost.atlassian.net/browse/MM-27674
> MM-27674 Fix transparency for unicode emojis

- e2e/cypress/integration/integrations/integrations_spec.js
- Fixed `Hello{enter}` after custom slash command
> Cypress/E2E: Fix integrations spec

- e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
- Fixed `Hello{enter}` after `/rename`
> Cypress/E2E: Fix common commands spec

- components/input.css
- components/multi_input.scss
- components/multi_input.tsx
This PR fixes a couple issues with the new inputs:
- Fixed the text input so that the legend doesn't use the focus colour when not focused.
- Fixed the `multi_input` so that the placeholder shows up when no values are present on blur.
https://mattermost.atlassian.net/browse/MM-27907
> [MM-27907] Fixed input focus colour and fixed placeholder focus on multi_input

- components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
- components/next_steps_view/next_steps_tips.tsx
- components/next_steps_view/next_steps_view.scss
- components/next_steps_view/next_steps_view.tsx
- components/next_steps_view/steps/complete_profile_step/__snapshots__/complete_profile_step.test.tsx.snap
- components/next_steps_view/steps/complete_profile_step/complete_profile_step.tsx
- components/next_steps_view/steps/invite_members_step/__snapshots__/invite_members_step.test.tsx.snap
- components/next_steps_view/steps/invite_members_step/invite_members_step.scss
- components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
- components/next_steps_view/steps/team_profile_step/__snapshots__/team_profile_step.test.tsx.snap
- components/next_steps_view/steps/team_profile_step/team_profile_step.tsx
This PR adds the missing hover, active, focus and disabled states for all buttons used by the Cloud Onboarding flow.
https://mattermost.atlassian.net/browse/MM-27159
> [MM-27159] Button States for Cloud Onboarding

- components/card/__snapshots__/card.test.tsx.snap
- components/card/card.scss
- components/card/card.test.tsx
- components/card/card_body.tsx
- components/card/card_header.tsx
- components/next_steps_view/next_steps_view.scss
- components/next_steps_view/steps/complete_profile_step/__snapshots__/complete_profile_step.test.tsx.snap
- components/next_steps_view/steps/complete_profile_step/complete_profile_step.scss
- components/next_steps_view/steps/complete_profile_step/complete_profile_step.tsx
- components/next_steps_view/steps/invite_members_step/invite_members_step.scss
- components/next_steps_view/steps/team_profile_step/__snapshots__/team_profile_step.test.tsx.snap
- components/next_steps_view/steps/team_profile_step/team_profile_step.scss
- components/next_steps_view/steps/team_profile_step/team_profile_step.tsx
This PR address a couple issues with the `Card` common component
- When changing between cards, the content would shift around.
- When resizing the window or changing the width of the inner content of the cards, the card wouldn't resize properly.
I've refactored the component to be much more responsive and robust.
I've also cleaned up and fixed a couple issues around the individual steps, some related to the `Card` component.
https://mattermost.atlassian.net/browse/MM-27305
> [MM-27305] Card Component Refactor for smoothness 

- e2e/cypress/integration/enterprise/system_console/channel_moderation/helpers.js
- Added a wait for location path to end with `/admin_console/user_management/channels` after saving to ensure url has redirected before continuing with the rest of the actions
- I tried to make a separate cypress run but for some reason it's timing out;  it passed on my local though (see `high_scoped_scheme_spec` below)
> Cypress/E2E: Fix high scoped scheme spec

- components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.tsx
- components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx
- components/timestamp/__snapshots__/semantic_time.test.tsx.snap
Only show `Demote to Guest` in the User page in the system console if and only if `Guest Accounts` are enabled.
https://mattermost.atlassian.net/browse/MM-26681
> [MM-26681] Only show demote to guest if guest setting is enabled

- components/admin_console/group_settings/group_details/group_details.jsx
Reset `hasAllowReferenceChanged` and `hasGroupMentionNameChanged` to false after a successful patch. Otherwise, keep it at the value it is.
https://mattermost.atlassian.net/browse/MM-27738
> Reset after patch

- e2e/cypress/utils/index.js
- Increased default length of getRandomId by 1 to decrease the likelihood of having generated the same set of characters.
> Cypress/E2E: Fix remove last post in channel spec

- e2e/cypress/integration/multi_team_and_dm/join_open_team_from_dm_spec.js
E2E Test for Hackfest : Join open team from link in DM
This test validates that a user which is not member of an open team (a team that any user on the server can join without an invite) can automatically join this open team by using the URL any of  the team's public channels.
[MM-T452](https://automation-test-cases.vercel.app/test/MM-T452])
> MM-T452 Add E2E test to validate user can join an open channel via a link in DM

- components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
- components/sidebar/sidebar_category/sidebar_category.tsx
- components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
- components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.test.tsx
- components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
- components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
- components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
- components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
- components/sidebar/sidebar_menu/__snapshots__/sidebar_menu.test.tsx.snap
- components/sidebar/sidebar_menu/sidebar_menu.test.tsx
- components/sidebar/sidebar_menu/sidebar_menu.tsx
- components/widgets/menu/menu.tsx
- sass/layout/_sidebar-left.scss
To hide the badge when the menu is open, the parent of the menu (`SidebarChannelLink`) has to know whether or not the menu is open. Since `SidebarCategory` already knows whether or not its menu is open, I made it so that the parent of a `SidebarMenu` is always the one in charge of its open state which requires passing around some props and `onToggleMenu` listeners.
The other major change because of this is moving the calculation of the menu position to happen in `componentDidUpdate` after the menu is opened instead of happening as a side effect of the `setState` caused by clicking the toggle button.
https://mattermost.atlassian.net/browse/MM-27432
> MM-27432 Hide notification badge on channel when menu is open

- actions/views/next_steps.ts
- components/main_menu/__snapshots__/main_menu.test.jsx.snap
- components/main_menu/index.jsx
- components/main_menu/main_menu.jsx
- components/main_menu/main_menu.test.jsx
- components/next_steps_view/steps.test.tsx
- components/next_steps_view/steps.ts
- components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
- i18n/en.json
- plugins/test/__snapshots__/main_menu_action.test.jsx.snap
- plugins/test/main_menu_action.test.jsx
Added a new main menu called 'Getting Started' that will appear when the Cloud Onboarding flow has been aborted without being completed.
Includes some fixes needed from #6269
https://mattermost.atlassian.net/browse/MM-28099
> [MM-28099] Menu Item to return to Getting Started

- e2e/cypress/integration/messaging/message_reply_gm_spec.js
Add e2e tests for Reply in existing GM
Test steps
1. User1 in a GM posts a message
2. User2 in that GM clicks the Reply arrow on the message
3. User2 sees RHS / reply screen open with parent post at the top and a reply box
4. User2 types a reply and clicks / taps to send or presses Enter
Expected:
User1 and User2 see reply posted:
- Center channel at the bottom
- User2 in RHS also
https://mattermost.atlassian.net/browse/MM-27818
> MM-27818 Add e2e for GMs and DMs > Reply in existing GM

- package-lock.json
- package.json
The new message indicator has a special case for messages posted by the
current user. Currently, webhook messages are attributed to its creator,
which breaks the new message indicator.
See https://github.com/mattermost/mattermost-redux/pull/1159
Fixes https://github.com/mattermost/mattermost-server/issues/14612
> [MM-25571] Fix new message indicator not showing for webhook messages to webhook owner

- e2e/cypress/integration/enterprise/system_console/channel_moderation/channel_mentions_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/constants.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/helpers.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/higher_scoped_scheme_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_moderation/post_reactions_spec.js
- Renamed functions to be more generic for re-use and also made sure check/uncheck permission really happens since there is an intermediate state (also, checkboxes are actually div elements and not of type checkbox so can't use cypress `check()`/`uncheck()`)
- Extracted checkbox IDs
- Although cleanup traverses other files, this PR is only for fixing `manage_members_spec`; other test failures will be addressed in other PRs
> Cypress/E2E: Fix manage members spec

- e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
The `/invite` command can invite another user to a channel that the current user is not currently located.
https://automation-test-cases.vercel.app/test/MM-T659
> MM-T659 /invite - other channel

- e2e/cypress/integration/notifications/desktop_notifications_spec.js
- e2e/cypress/plugins/index.js
Adds cypress test for MM-T495 Desktop Notifications - Can set to DND and no notification fires on DM
*Note*: I have a small concern that the mocking of granting permissions for notifications is not actually working but I can't seem to figure this out. Can anyone who hasn't already manually granted the permissions please take a look and check if it works as intended.
https://mattermost.atlassian.net/browse/MM-27825
> MM-27825: Add Cypress Test Case for MM-T495

- components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
This is a more targeted version of https://github.com/mattermost/mattermost-webapp/pull/6290, specific to 5.27. It doesn't include any tests since those required me to go a bit out of scope on this ticket.
https://mattermost.atlassian.net/browse/MM-28101
https://github.com/mattermost/mattermost-webapp/pull/6290 (for 5.28 and beyond)
> MM-28101 Fix incorrect link in new sidebar Copy Link option

- root.html
Reverts mattermost/mattermost-webapp#5654
there are no fonts in webapp referenced `mattermosticons` and we cannot reference them as `/fonts/filename` because our build folder has a different structure and we use `/static` for referencing files. 
If we go ahead with preloading i think we should be fixing the path, filename(i believe we call them compass-icons) and also use `font/woff2` format.
The log error is because of type attribute in the link preload tag. I couldn't find the right type for eot files as compared to `font/woff2` but We could always skip the `type` tag as it is used for browsers to understand which fonts to download but here, in this case, modern browsers don't support eot anymore as far as I know
reverting the said PR as it was an improvement which is not working as …
> [MM-27568] Revert "[MM-25534] - Fix preloading of icons for really slow connections"

- e2e/cypress/integration/plugins/upgrade_spec.js
- e2e/cypress/integration/system_console/plugin_upload_spec.js
Cypress test for MM-T40 Plugin remains enabled when upgraded
Test Case: [MM-T40](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T40)
The code for this test case has some similarities to the previous test that exists in this file.  The other tests uses the draw plugin and I chose to leave it as is and add the new test case for the following reasons.
* keep the test attached to the specific Jira test
* eliminate some portion of the previous test being polluted by additional code
* Use of additional plugin (as specified by the Jira task)
https://mattermost.atlassian.net/browse/MM-27802
> MM-27802 Cypress test for MM-T40 (1.0) Plugin remains enabled when upgraded

- components/admin_console/admin_console.tsx
Fixes the filtering of admin console sections by the `isHidden` property. This is already covered by the E2E tests.
https://mattermost.atlassian.net/browse/MM-28142
> MM-28142: Filter hidden admin console sections.

- components/timestamp/__snapshots__/semantic_time.test.tsx.snap
- components/timestamp/semantic_time.test.tsx
Use locale-agnostic validation instead of flakey snapshot logic. (Fixes `semantic_time` unit test failing in non-`en-US` locales.)
> fix: semantic time testing criteria

- e2e/package-lock.json
- e2e/package.json
Downgrade cypress to 8.4.0 to have more stable tests
while trying to create [this test](https://github.com/Willyfrog/mattermost-webapp/blob/MM-27207_e2e-archived-channels-I/e2e/cypress/integration/channel/archived_channels_spec.js#L108) i was running into many different problems as either it was taking longer to load some elements or it break while typing/waiting for no reason. Downgrading seems to get stable results.
> revert cypress to 4.8.0

- e2e/cypress/integration/toast/permalink_post_with_new_message_spec.js
Summary
I created a test to make sure that after clicking on a permalink and posting a new message as a second user and clicking on the 'Jump to New Messages' button, the new message is visible
Test case: https://automation-test-cases.vercel.app/test/MM-T1794
> MM-T1794 Permalink post view combined with New Message toast

- e2e/cypress/integration/notifications/channel_links_show_as_links_spec.js
Summary
This test checks that when a user is tagged in a post that includes the channel name, the user receives an email with the expected/correct output.
Test case: https://automation-test-cases.vercel.app/test/MM-T506
> MM-T506 Channel links show as links in notification emails

- e2e/cypress/integration/notifications/deselect_username_mention_trigger_spec.js
Summary
This test checks that when a user deselects 'username' in 'Words That Trigger Mentions' and is added to a private channel, the user will still get a mention.
Test case: https://automation-test-cases.vercel.app/test/MM-T546
> MM-T546 Words that trigger mentions - Deselect username, still get mention when added to private channel

- e2e/cypress/integration/notifications/message_posted_while_scrolled_up_spec.js
Summary
This test checks that when scrolled to the top of a channel and there are new messages, the 'Jump To New Messages' button will appear and that clicking on the button will direct to the bottom of the channel so that the new message would be visible and the button would not be visible anymore after clicking.
Test case: https://automation-test-cases.vercel.app/test/MM-T562
> MM-T562 New message bar - Message posted while scrolled up in same channel

- sass/layout/_markdown.scss
I forgot to check the style of inline code earlier, so https://github.com/mattermost/mattermost-webapp/pull/6223 broke that because of the bootstrap reset. I fixed that by moving the reset to only apply to `.post-code` components (code blocks and the code preview).
I don't think there's any good way to automatically test for this without doing some sort of screenshot-based testing.
https://mattermost.atlassian.net/browse/MM-28175
> MM-28175 Fix inline code styling

- e2e/cypress/integration/integrations/outgoing_webhook/prompt_set_status_spec.js
- e2e/cypress/support/api/status.d.ts
- e2e/cypress/support/api/status.js
After a user manually set themselves to be offline, they are prompted to see if they'd like to set the status to be online after logging in.
https://automation-test-cases.vercel.app/test/MM-T673
- Has redux changes  N/A
- Has mobile changes  N/A
> MM-T673 Prompting to set status to online

- .circleci/config.yml
- Makefile
- package.json
This PR also includes that branches use their separate cache now. I retriggered pipeline a couple of times to see, if the pipeline still fails: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp?branch=fix-pipeline , but I need to bump the caching every time. 
> Fix pipeline by increasing node memory for Makefile steps

- components/admin_console/admin_definition.jsx
**Needs to be cherry-picked into 5.25 / 5.26 / 5.27**
Since we are not going to be using the new SAML library for the time being, we are hiding this feature from the system console. 
https://mattermost.atlassian.net/browse/MM-28235
- Has server changes https://github.com/mattermost/mattermost-server/pull/15371
- Has enterprise changes https://github.com/mattermost/enterprise/pull/753
> [MM-28235] Hide UseNewSamlLibrary feature from system console

- components/user_settings/modal/user_settings_modal.tsx
A defaultProps was missed that left this component somewhat broken on certain entry-points. Added a noop function for if it's not passed.
Main Menu > Account Settings
Close Account Settings
Webapp should continue working as before 
https://mattermost.atlassian.net/browse/MM-28230
- Has server changes n/a
- Has redux changes n/a
- Has mobile changes n/a
n/a
> [MM-28230] Add defaultProps to user_settings_modal for new onExit prop

- e2e/cypress/integration/bot_accounts/create_bot_spec.js
Add E2E spec for creating bots via the Integrations page.
- https://mattermost.atlassian.net/browse/MM-27222
- [MM-T1810](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1810)
- [MM-T1811](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1811)
> E2E, MM-27222-1–2/10: add create_bot spec

- e2e/cypress/support/api/setup.d.ts
Improve loginAfter doc at cy.apiInitSetup per discussion at https://community-release.mattermost.com/core/pl/1o7irz4ssfbrtq696kprduybya
> Cypress/E2E: Improve loginAfter doc at cy.apiInitSetup

- e2e/cypress/integration/toast/new_messages_toast_spec.js
MM-T1786 Dismissing the toast using Jump to
https://automation-test-cases.vercel.app/test/MM-T1786
> MM-T1786 Dismissing the toast using Jump to

- components/channel_view/channel_view.jsx
- components/next_steps_view/next_steps_view.tsx
- components/sidebar/__snapshots__/sidebar.test.tsx.snap
- components/sidebar/sidebar.tsx
- package-lock.json
This if statement was run in a render component which meant there could be a race condition preventing the animation from playing when the transition happens between next_steps and next_steps_tips. Moving into componentDidMount remedies this problem.
Fix related to #6384 
#6384 
- Has server changes n/a
- Has redux changes n/a
- Has mobile changes n/a
n/a
> [MM-28328] Move call from render function to componentDidMount to prevent race condition

- e2e/cypress/integration/account_settings/general/nickname_spec.js
- e2e/cypress/integration/system_console/demoted_user_spec.js
- e2e/cypress/integration/system_console/lock_teammate_name_display_spec.js
- e2e/cypress/integration/system_console/revoke_all_sessions_spec.js
- e2e/cypress/integration/team_settings/create_a_team_spec.js
- e2e/cypress/integration/team_settings/remove_team_icon_spec.js
- e2e/cypress/integration/team_settings/teammates_pagination_spec.js
- e2e/cypress/integration/team_settings/teams_spec.js
Add TM4J IDs to already automated test cases
> Cypress/E2E: Add TM4J IDs

- e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
Fix TM4J ID for MM-T2500
Note that no test script change here other than removing the other `describe` block and adding TM4J ID with step number for each `it` block.
> Cypress/E2E: Fix TM4J ID for MM-T2500

- components/post_view/post/post.jsx
- components/rhs_comment/rhs_comment.jsx
- sass/components/_post.scss
- sass/responsive/_tablet.scss
MM-27165 - Updating post menu css
MM-26860 - Bot username spacing issue
https://mattermost.atlassian.net/browse/MM-27165
https://mattermost.atlassian.net/browse/MM-26860
**Post menu css**
**Bots in thread**
> MM-27165 - Updating post menu css

- e2e/cypress/integration/files_and_attachments/upload_files_spec.js
- e2e/cypress/support/api/system.js
- Needed to add verification of config update to debug if it is indeed being updated in the major cypress run. I also did a cypress run just for the failing test and it seems to run fine
- For some reason, the config from `apiUpdateConfig ` response  is not updated and had to call `apiGetConfig` for latest
- This passes for me locally but failing on daily cypress run
[Cypress Run Passed](https://app.circleci.com/pipelines/github/saturninoabril/mattermost-cypress-docker?branch=debug-upload-files-spec)
> Cypress/E2E: Debug upload files spec

- e2e/cypress/integration/channel_settings/more_unreads_position_with_scroll_spec.js
- Added duration on scrolling to stabilize and make sure scrolling completes
> Cypress/E2E: Fix more unreads position with scroll spec

- components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
- i18n/en.json
- utils/constants.jsx
If more than 256 members are added to the list of invite members, then we throw an error. 
This limit comes from https://github.com/mattermost/mattermost-server/blob/master/api4/team.go#L23 
https://mattermost.atlassian.net/browse/MM-23651
**BLOCKED BY**
https://github.com/mattermost/mattermost-server/pull/15414
> [MM-23651] No more than 256 members are allowed to be invited

- e2e/cypress/fixtures/partial_default_config.json
- e2e/cypress/integration/accessibility/accessibility_buttons_spec.js
The error is happening because of the new plugin icon that is recently added. Since this is an accessibility test, the best way to test is using keyboard tab to verify that the buttons in channel header can be accessed as such. Therefore, instead of adding any complex solution, only adding a tab to verify that the pin button can be accessed as expected.
> Possible fix for accessibility test for support in buttons in channel header

- sass/components/_channel-switcher.scss
- [MM-28209](https://mattermost.atlassian.net/browse/MM-28209) Sync fixed-height content to match max dynamic-hight content to prevent dual scrollbars.
> MM-28209: fix dual scrollbars in channel switcher

- components/next_steps_view/steps/invite_members_step/index.ts
- components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
- components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
There was a rare bug that the invite ID would be "undefined" when it was displayed to the user in the onboarding flow. This PR adds a check for this case, and forces it to be generated if it is undefined. This guard should only ever be run in the rare bug circumstance.
https://mattermost.atlassian.net/browse/MM-28646
n/a
n/a
> [MM-28646] Regenerate the invite ID if it's not defined

- e2e/cypress/integration/notifications/reply_notifications_spec.js
- Cypress test for T553: Reply Notifications – that I start or participate in – start the thread
- Clarify test name of similar test
- https://mattermost.atlassian.net/browse/MM-27814
> [MM-27814] cypress test for T553

- e2e/cypress/integration/mark_as_unread/bot_post_mark_as_unread_spec.js
- e2e/cypress/integration/mark_as_unread/mark_as_unread_using_shortcuts_spec.js
- e2e/cypress/integration/messaging/message_reply_bot_post_spec.js
- e2e/cypress/support/api/bots.d.ts
- e2e/cypress/support/api/bots.js
- e2e/cypress/support/api_commands.js
- Move cy.apiCreateBot
- While testing change due to movement of `cy.apiCreateBot`, I came across to fix failing on MM-T252. I should make a separate PR for this change but those are connected in some ways.
- add fix for MM-T251
> Cypress/E2E: Move cy.apiCreateBot and fix MM-T251 & MM-T252

- e2e/cypress/integration/mark_as_unread/bot_post_mark_as_unread_spec.js
- e2e/cypress/integration/mark_as_unread/mark_as_unread_using_shortcuts_spec.js
- e2e/cypress/integration/messaging/message_reply_bot_post_spec.js
- e2e/cypress/support/api/bots.d.ts
- e2e/cypress/support/api/bots.js
- e2e/cypress/support/api_commands.js
Cherry pick of #6471 on release-5.28.
> Automated cherry pick of #6471

- components/__snapshots__/textbox.test.tsx.snap
- components/suggestion/command_provider.jsx
- components/suggestion/command_provider.test.js
- components/textbox.test.tsx
- components/textbox/textbox.tsx
Incident response is using the exported textbox to allow slash command autocomplete in the playbook backstage. The underlying component has support for automatically opening, but requires exposing `openWhenEmpty` to do so.
While in here, I hardened the component against use in a context where there is no active channel defined, namely if the playbook backstage is loaded directly (and thus we have not yet "entered" the center channel space).
https://mattermost.atlassian.net/browse/MM-28716
> MM-28716: expose textbox's openWhenEmpty

- e2e/cypress/fixtures/partial_default_config.json
- e2e/cypress/support/index.js
* Disabling these settings so no notices are served which will cause existing e2e tests to
break as UI will have modal open
https://mattermost.atlassian.net/browse/MM-28892
> MM-28892 Disabling server config settings for inproduct notices in e2e

- e2e/cypress/integration/messaging/long_draft_spec.js
Took a stab at this test since I was seeing it last week as well. Wasn't sure about what was causing the failure since it passes as expected in every run on my local server, thus increased the wait from half a second to 3 seconds for assertions after the draft is typed. Hopefully this fixes the flakiness.
Also demoted the test from prod. Will keep an eye out to see if this fixes the issue before promoting it back to prod.
> Possible fix for the failing long draft test in messaging

- components/sidebar/sidebar_next_steps/remove_next_steps_modal.scss
The `left` offset of the arrow used to indicate the hamburger menu on the Remove Next Steps modal was changed to work with the older sidebar. This PR resets it to work with the new sidebar.
https://mattermost.atlassian.net/browse/MM-28878
> [MM-28878] Revert style change to remove next steps arrow

- e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
- e2e/cypress/integration/mark_as_unread/mark_gm_as_unread_spec.js
Demoting failed tests from prod. These tests are working fine locally but for some reasons they are failing on the Cypress test instance on daily runs. 
N/A
> Demoting failed test from prod

- components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- components/admin_console/multiselect_settings.jsx
- components/admin_console/schema_admin_settings.jsx
It looks like this prop used to be needed at some point, but I can't find anywhere that it's used in the current code base. The MultiSelectSetting also doesn't appear to be exposed to plugins, so we don't need to be worried about them either.
https://mattermost.atlassian.net/browse/MM-28992
> MM-28992 Remove unused notPresent and mustBePresent props from MultiSelectSetting

- components/suggestion/search_channel_provider.jsx
Cherry pick of #6493 on release-5.28.
/cc  @ashishbhate
> Automated cherry pick of #6493

- e2e/cypress/integration/messaging/reactions_spec.js
Adds:
- [MM-T2189](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2189)
- [MM-T2190](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2190)
- [MM-T2192](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2192)
- [MM-T2195](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2195)
- …
> [MM-28295] e2e/messaging/reactions: add reactions spec

- e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
- e2e/cypress/support/external_commands.d.ts
- e2e/cypress/support/external_commands.js
- Use `apiAddUserToTeam` instead of old `externalAddUserToTeam`
- Update comments
- Remove `externalAddUserToTeam`
None -  master and v5.28
> Cypress/E2E: Fix guest experience ui spec

- e2e/package-lock.json
- e2e/package.json
Fix getType is not a function by explicitly adding mime version 2 which is a dependent of cypress-file-upload package.
none
Before: error on file upload
> Cypress/E2E: fix getType is not a function

- components/__snapshots__/textbox.test.tsx.snap
- components/suggestion/command_provider.jsx
- components/suggestion/command_provider.test.js
- components/textbox.test.tsx
- components/textbox/textbox.tsx
Cherry picks a change supporting incident response to cloud:
* expose openWhenEmpty on textbox
* handle no active channel when in backstage
Fixes: https://mattermost.atlassian.net/browse/MM-29007
Relates-to: https://mattermost.atlassian.net/browse/MM-28716
> MM-28716: expose textbox's openWhenEmpty (#6460)

- actions/file_actions.jsx
PR enables stream mode for uploads by changing the order of fields in the multipart/form-data upload.
This enables the [stream mode path](https://github.com/mattermost/mattermost-server/blob/85b434c50d1a4744625ddd20f2b653517aa80686/api4/file.go#L193-L198) which avoids a full memory allocation of the uploaded file.
https://mattermost.atlassian.net/browse/MM-27277
https://github.com/mattermost/mattermost-server/pull/15616
> [MM-27277] Enable stream mode for file uploads

- e2e/cypress/integration/mark_as_unread/channel_unread_spec.js
- e2e/cypress/integration/mark_as_unread/helpers.js
- e2e/cypress/integration/mark_as_unread/mark_as_unread_spec.js
- e2e/cypress/integration/mark_as_unread/mark_as_unread_using_shortcuts_spec.js
- e2e/cypress/integration/mark_as_unread/mark_gm_as_unread_spec.js
- e2e/cypress/integration/mark_as_unread/mark_mentions_as_unread_spec.js
- e2e/cypress/integration/mark_as_unread/unread_toast_count_spec.js
- e2e/cypress/integration/messaging/pinned_parent_post_spec.js
- e2e/cypress/integration/messaging/pinned_posts_spec.js
- e2e/cypress/integration/messaging/post_pre_header_spec.js
- e2e/cypress/integration/toast/new_messages_toast_spec.js
- e2e/cypress/integration/toast/toast_spec.js
- e2e/cypress/support/ui/post_dropdown_menu.d.ts
- e2e/cypress/support/ui/post_dropdown_menu.js
- e2e/cypress/support/ui_commands.js
Add `cy.uiClickPostDropdownMenu` command.
Test report: https://mm-cypress-report.s3.amazonaws.com/1024-cypress-post-dropdown-menu-master/mochawesome.html (failing test are not related to change)
> Cypress/E2E: Add cy.uiClickPostDropdownMenu command

- e2e/cypress/integration/archived_channel/archive_channel_member_spec.js
Add e2e tests for channel dropdown to not have manage user options
https://mattermost.atlassian.net/browse/MM-28411
> MM-24811 Archive channels should not have options to manage users

- e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
- e2e/cypress/integration/integrations/builtin_commands/groupmsg_command_spec.js
- e2e/cypress/integration/integrations/builtin_commands/helper.js
- e2e/cypress/integration/integrations/builtin_commands/invite_command_spec.js
- Fix intermittent failing tests at common commands
- separate `invite` and `groupmsg` into its own spec files to easily run test in isolation, and promote/demote particular test
none, failing in daily Cypress run
Test run - https://mm-cypress-report.s3.amazonaws.com/1034-common-commands-master/mochawesome.html
> Cypress/E2E: Fix intermittent failing tests at common commands

- components/signup/signup_email/signup_email.jsx
This pull request migrates all string-refs in _./components/signup/signupemail/signupemail.jsx_ to functional ones using the `createRef` API.
This fixes mattermost/mattermost-server#15620.
> [GH-15620] Migrated string refs in signup_email

- e2e/cypress.json
After moving from MySQL to PostgreSQL e2e cypress tests are crashing.
Fixes https://github.com/mattermost/mattermost-server/issues/15766
> GH-15766 Fixed cypress env for PostgreSQL connection

- e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
- e2e/cypress/integration/channel/archived_channels_2_spec.js
- e2e/cypress/support/ui/channel.d.ts
- e2e/cypress/support/ui/channel.js
- e2e/cypress/support/ui/channel_sidebar.js
- Removed duplicate `uiCreateChannel` command
- Updated `uiCreateChannel` to take in options
- Updated `channel.d.ts`
- Fixed `createArchivedChannel` params for `archived_leave_channel_spec`
- Fixed `archived_channels_2_spec` to use original `uiCreateChannel`
> Cypress/E2E: Fix archived channel specs

- components/post_view/combined_user_activity_post/index.ts
Migrates `components/post_view/combined_user_activity_post/index.js` to TypeScript.
Fixes https://github.com/mattermost/mattermost-server/issues/15451
None
None
> [MM-20490] Migrate 'components/post_view/combined_user_activity_post' module and associated tests to TypeScript

- utils/markdown/index.test.js
- utils/markdown/renderer.tsx
Fix a regression introduced by https://github.com/mattermost/mattermost-webapp/pull/6147 that caused `/files/*` to open "inside the app", with the webapp trying to navigate to a team named `files`. Restore the desired `target="_blank"` behaviour instead.
Fixes: https://mattermost.atlassian.net/browse/MM-29049
> /files should target=_blank

- components/create_team/components/__snapshots__/display_name.test.jsx.snap
- components/create_team/components/display_name.jsx
- components/create_team/components/display_name.test.jsx
- components/create_team/components/team_url/__snapshots__/team_url.test.tsx.snap
- components/create_team/components/team_url/team_url.test.tsx
- components/create_team/components/team_url/team_url.tsx
Removed usage of findDOMNode from Create Team screens.
Fixes https://github.com/mattermost/mattermost-server/issues/15724
None.
None.
> [GH-15724] Remove usage of findDOMNode from Create Team screens

- e2e/cypress/integration/enterprise/extend_session/email_login_activity_spec.js
- e2e/cypress/plugins/db_request.js
- e2e/cypress/support/db_commands.d.ts
- e2e/cypress/support/db_commands.js
- e2e/cypress/support/index.d.ts
- e2e/cypress/support/index.js
Make database error message easier to understand on Cypress test by showing an error message in where it failed, suggestion to check, and actual error object thrown from `knex` client.
Others included:
- add `cy.apiRequireServerDBToMatch()` to global `before` hook to ensure that DB client/connection matches between server and Cypress.
- added types to `db_commands`
Jira ticket - https://mattermost.atlassian.net/browse/MM-29278
__Some DB client/connection errors__
1. Client is correct (postgres) but database is non-existent
2. Client is not correct (mysql) and can't connect to defined connection string
> MM-29278 Make database error message easier to understand on Cypress test

- components/sidebar/sidebar_next_steps/sidebar_next_steps.scss
- sass/base/_css_variables.scss
- sass/layout/_legacy-sidebar-left.scss
Remove usage of sidebar-text-## CSS variables
Also fixes a forgotten --sidebar-text-16 occurence left during a previous refactoring
Fixes https://github.com/mattermost/mattermost-server/issues/15782
JIRA: https://mattermost.atlassian.net/browse/MM-29034
> [MM-29034] Remove usage of sidebar-text-## CSS variables

- e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js
MM-29347: E2E Cypress Tests - System Console > Enterprise > Group Mentions (Part 3)
JIRA Ticket:
[MM-29347](https://mattermost.atlassian.net/browse/MM-29347)
TM4J Tests:
[MM-T2450](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2450)
[MM-T2451](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2451)
[MM-T2452](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2452)
> Added final set of cypress tests part of MM-29347

- utils/utils.jsx
Remove an unused changeCSS() style
Fixes https://github.com/mattermost/mattermost-server/issues/15837
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29399
> [MM-29399] Remove an unused changeCSS() style

- .circleci/config.yml
- components/admin_console/admin_definition.jsx
- components/admin_console/billing/billing_subscriptions.tsx
- i18n/en.json
- utils/constants.jsx
Cherry pick of #6679 on cloud-ga.
> Automated cherry pick of #6679

- components/announcement_bar/cloud_announcement_bar/index.ts
- components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
- components/main_menu/index.jsx
- components/main_menu/main_menu.jsx
Now that we're storing whether a subscription is paid (upgraded) or not in stripe metadata, we can use that field override the displaying of any upgrade warnings. This PR will hide the banners along the top of the screen, as well as the upgrade modal (when clicking the invite people button when at or over the limit, as an administrator)
https://mattermost.atlassian.net/browse/MM-28714
n/a
n/a
> [MM-28714] Check if subscription is paid before showing any upgrade warnings

- sass/layout/_navigation.scss
- utils/utils.jsx
Removes the line: 
from utils/utils.jsx and replaces it with a new background variable under the app__body section in sass/layout/_navigation.scss
Fixes https://github.com/mattermost/mattermost-server/issues/15875
> [GH-15875] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 564

- sass/components/_popover.scss
- utils/utils.jsx
Replaced JavaScript variable `theme.centerChannelBg` with CSS variable `--center-channel-bg` for `.app__body .search-help-popover .search-autocomplete__divider span`.
Fixes [mattermost/mattermost-server#15890](https://github.com/mattermost/mattermost-server/issues/15890)
> [GH-15890] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 627

- utils/utils.jsx
Remove the line as style is already applied unconditionally and more broadly by `changeCss()` call at line 515
Fixes https://github.com/mattermost/mattermost-server/issues/15836
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29397
> [MM-29397] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 525 (#15836)

- sass/components/_popover.scss
- utils/utils.jsx
Replaced JavaScript variable `theme.centerChannelBg` with CSS variable `--center-channel-bg` for `.app__body .popover.left>.arrow:after`.
Fixes [mattermost/mattermost-server#15892](https://github.com/mattermost/mattermost-server/issues/15892)
> [GH-15892] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 631

- sass/responsive/_mobile.scss
- utils/utils.jsx
Replaced the use of the Javascript variable `theme.centerChannelBg` with the CSS variable `--center-channel-bg` for the `.tutorial-steps__container` selector.
Fixes issue mattermost/mattermost-server#15889
> [GH-15889] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 622

- utils/utils.jsx
Remove the line as it isn't possible that .sidebar__switcher button contains a svg
Fixes https://github.com/mattermost/mattermost-server/issues/15835
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29396
> [MM-29396] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 523 (#15835)

- utils/utils.jsx
Remove the line as it is unconditionally overidden by linkColor theme at line 833
Fixes https://github.com/mattermost/mattermost-server/issues/15827
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29388
> [MM-29388] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 505 (#15827)

- sass/layout/_legacy-sidebar-left.scss
- utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 519
Fixes https://github.com/mattermost/mattermost-server/issues/15832
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29393
> [MM-29393] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 519 (#15832)

- components/purchase_modal/index.ts
- components/purchase_modal/purchase_modal.tsx
There was a certain case where when you complete the purchase, the app would still show the various modals/banners around upgrading until refresh. This PR grabs the latest information on the subscription whenever the purchase modal closes, which will trigger re-renders of all downstream components depending on it (like the announcement banner, or information around the subscription in the system console)
https://mattermost.atlassian.net/browse/MM-29557
https://mattermost.atlassian.net/browse/MM-29590
N/A
N/A
> [MM-29557] [MM-29590] Update subscription when purchase modal closes

- sass/layout/_team-sidebar.scss
- utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 533.
Change use of js variable `theme.sidebarTextActiveBorder` to css variable `--sidebar-text-active-border`.
Fixes https://github.com/mattermost/mattermost-server/issues/15864
https://mattermost.atlassian.net/browse/MM-29453
> [MM-29453] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 533

- components/admin_console/billing/company_info_display.tsx
Two fixes:
- Fixed the Company Info flickering by making sure the component doesn't render until customer is loaded
- Fixed the missing address when `company_address` is not null but rather everything is blank, so now it checks if `line1` is blank or not.
https://mattermost.atlassian.net/browse/MM-29558
https://mattermost.atlassian.net/browse/MM-29559
> [MM-29559][MM-29558] Company Info Fixes

- sass/layout/_team-sidebar.scss
- utils/utils.jsx
I've also deleted the last reference to sidebarTextActiveBorder in that statement even if there's no related ticket and updated CSS accordingly
Fixes https://github.com/mattermost/mattermost-server/issues/15865
Fixes https://github.com/mattermost/mattermost-server/issues/15866
JIRA tickets:
* https://mattermost.atlassian.net/browse/MM-29454
* https://mattermost.atlassian.net/browse/MM-29455
> Migrate changeCSS() use of sidebarTextActiveBorder to CSS variable in utils/utils.jsx

- sass/components/_scrollbar.scss
- utils/utils.jsx
Replace Javascript variable `theme.centerChannelBg` with  CSS variable
`--center-channel-bg` for `scrollbar-face-color`.
Fixes https://github.com/mattermost/mattermost-server/issues/15894
> [GH-15894] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 635

- components/admin_console/billing/company_info_display.tsx
This PR fixes the case where the `company_address` field is `null` but the `billing_address` is not but still contains no data. A white screen would appear.
https://mattermost.atlassian.net/browse/MM-29632
> [MM-29632] Added extra null checking for company address

- components/invitation_modal/invitation_modal_members_step/index.ts
- components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
- components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.test.jsx
- components/main_menu/main_menu.jsx
This check was missed in the initial addition of the is paid field. When a user upgraded their account, they still couldn't invite more than 10 people in the invite members modal. This adds a check that tells the error to not show in the case of a paid tier.
https://mattermost.atlassian.net/browse/MM-29646
n/a
n/a
> [MM-29646] Down't show picker error if paid tier

- components/admin_console/billing/billing_subscriptions.tsx
- components/admin_console/billing/payment_info_display.tsx
This PR fixes a flash that occurs on the Subscriptions and Payment Info screens when the information hasn't finished loading, but the component has rendered.
NOTE: I couldn't fix the billing history screen, see JIRA ticket for explanation.
https://mattermost.atlassian.net/browse/MM-29651
> [MM-29651] Wait for async calls to finish before rendering anything for a couple billing screens

- components/admin_console/billing/billing_subscriptions.tsx
Small change, if the number of users is equal to the user limit, don't show the panel in the subscription section. IE, it will now only show the panel if between the threshold and 1 user remaining.
https://mattermost.atlassian.net/browse/MM-29635
n/a
n/a
> [MM-29635] Don't show panel in subscription section if at user limit

- components/admin_console/billing/payment_info_edit.tsx
This PR stops the `There are errors in the form above` message from triggering until validation has explicitly run.
https://mattermost.atlassian.net/browse/MM-29671
> [MM-29671] Stopped error message from showing until form has been edited

- utils/utils.jsx
Remove the line as it is already taken into account unconditionally at line 623 thanks to '.app__body .post .Menu .MenuItem' selector
When this was added in commit https://github.com/mattermost/mattermost-webapp/commit/c8ae25a2816656a7791599de765b1e0a84d9c886 cited selector wasn't present
Fixes https://github.com/mattermost/mattermost-server/issues/15888
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29501
> [MM-29501] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 621 (#15888)

- sass/components/_post.scss
- utils/utils.jsx
migrated changeCss() to CSS variable for `post-collapse__show-more-button`
Fixes https://github.com/mattermost/mattermost-server/issues/15899
> [GH-15899] migrated changeCss() to CSS variable

- sass/layout/_legacy-sidebar-left.scss
- utils/utils.jsx
Remove changeCss() for `.nav-pills__unread-indicator svg`.
This is no longer required as CSS variable `--mention-color` is already used.
https://github.com/mattermost/mattermost-webapp/blob/c3f01ee92ca30d6bedf62aa93b6e117efd37f9a4/sass/layout/_sidebar-left.scss#L421
Fixes https://github.com/mattermost/mattermost-server/issues/15885
> [GH-15885] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 613

- sass/components/_post.scss
- utils/utils.jsx
Removes the line: changeCss('.app__body .post-collapse_*show-more-button:hover', 'color:${theme.centerChannelBg}'); from `utils/utils.jsx` and replaces it with a new color variable under the ` .post-collapse__show-more-button` section in `sass/components/_post.scss `
Fixes: https://github.com/mattermost/mattermost-server/issues/15898
> [GH-15898] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 668

- utils/utils.jsx
Removes the changeCSS() function called on unused CSS selector - .app__body .mentions--top in file utils/utils.jsx
Part of the campaign to replace older theme implementation. 
Fixes https://github.com/mattermost/mattermost-server/issues/15970
Jira Ticket: https://mattermost.atlassian.net/browse/MM-29695
> [GH-15970] Remove unnecessary changeCSS() for .mentions--top

- components/purchase_modal/purchase_modal.tsx
When closing the Purchase Modal after completing a purchase by clicking 'X', the subscription wouldn't update in the background. This PR adds the call to `getCloudSubscription` to make sure the subscription is updated properly.
https://mattermost.atlassian.net/browse/MM-29715
> [MM-29715] Added call to getCloudSubscription on close modal

- actions/websocket_actions.jsx
- utils/constants.jsx
When a sysadmin upgraded the cloud subscription, another sysadmin that was logged in wouldn't see the updated screen until they refreshed. This PR receives a websocket event that will force an update on the subscription.
https://mattermost.atlassian.net/browse/MM-29723
- Has server changes (https://github.com/mattermost/mattermost-server/pull/15988)
> [MM-29723] Update subscription when payment status websocket event is received

- e2e/cypress.json
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/helpers/index.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/system_console_spec.js
- e2e/cypress/support/index.js
In CircleCI, we're loading the license directly into the database. For some reason, upon server start, the workers related to Enterprise (including Elasticsearch) didn't start as expected.  So, we're uploading the license via `cy.apiRequireLicense()` on global `before` hook whenever we are running tests for EE.  Bonus: this is also the first step towards running tests for TE and EE.
The additional `CYPRESS_runWithEELicense` is by default set to false at `cypress.json`. Therefore, contributors, especially from the community, is not affected by this change.  Docs to be added at https://developers.mattermost.com/contribute/webapp/end-to-end-tests/#environment-variables
Report - https://mm-cypress-report.s3.amazonaws.com/1139-es-license-master/mochawesome.html
Jira ticket - …
> MM-29870 Cypress/E2E: Fix tests of autocomplete with Elasticsearch

- sass/responsive/_mobile.scss
- utils/utils.jsx
Migrate changeCSS() to CSS variable: --sidebar-bg
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 504.
Change use of js variable heme.sidebarBg to css variable --sidebar-bg.
Fixes https://github.com/mattermost/mattermost-server/issues/15826
Jira https://mattermost.atlassian.net/browse/MM-29387
> Migrate changeCSS() use of sidebarBg to CSS variable in utils/utils.jsx

- sass/layout/_channel-icon.scss
- utils/utils.jsx
Fixes https://github.com/mattermost/mattermost-server/issues/15963, MM-29688
Fixed  `.app__body .svg-text-color` class to use CSS variables.
It is generally used with channel-icon , so css was added in _channel-icon.scss.
Github Issue: Fixes https://github.com/mattermost/mattermost-server/issues/15963
JIRA Ticket: MM-29688
> [MM-29688] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 675

- e2e/cypress/integration/integrations/slash_commands_spec.js
Adds test case for /open command:
Privileged user try to /open to private channel with channel name
Privileged user try to /open to private channel with tilde(~) + channel name
Unprivileged user try to /open to private channel with channel name
Unprivileged user try to /open to private channel with tilde(~) + channel name
Github Issue: Fixes https://github.com/mattermost/mattermost-server/issues/15699
JIRA Ticket: MM-T663
> Add e2e test for /open command

- sass/components/_status-icon.scss
- utils/utils.jsx
Deletes changeCSS() call in `utils/utils.jsx` in favor of a CSS variable in `_status-icon.scss`.
- https://mattermost.atlassian.net/browse/MM-29496
- https://mattermost.atlassian.net/browse/MM-29497
- Fixes https://github.com/mattermost/mattermost-server/issues/15883
- Fixes https://github.com/mattermost/mattermost-server/issues/15884
> [MM-29496, MM-29497] Update changeCSS() call to CSS variable for away status indicator

- sass/components/_popover.scss
- utils/utils.jsx
Fixes #15962, MM-29687
Github Issue: Fixes https://github.com/mattermost/mattermost-server/issues/15962
JIRA Ticket: MM-29687
> [MM-29687] Migrate call to changeCSS() for '.app__body .user-popover__role'

- sass/layout/_navigation.scss
- utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 559
Closes https://github.com/mattermost/mattermost-server/issues/15871
> [GH-15871] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 559

- sass/components/_status-icon.scss
- utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx in 573,574.
This PR solves 2 tickets:
https://mattermost.atlassian.net/browse/MM-29493
https://mattermost.atlassian.net/browse/MM-29494
Fixes https://github.com/mattermost/mattermost-server/issues/15881
Fixes https://github.com/mattermost/mattermost-server/issues/15882
> [MM-29493,  MM-29494] Migrate changeCSS() to CSS variable in utils/utils.jsx in 573,574.

- components/admin_console/billing/company_info_edit.tsx
This PR fixes an issue where if the billing address and company address were both blank, the user was unable to update the company address.
https://mattermost.atlassian.net/browse/MM-28218
> [MM-28218] Fix for when both billing address and company address are missing and you can't add company info

- sass/layout/_legacy-sidebar-left.scss
- utils/utils.jsx
Remove changeCss() for `.nav-pills__unread-indicator` color.
This is no longer required as CSS variable `--mention-color` is already used.
https://github.com/mattermost/mattermost-webapp/blob/c3f01ee92ca30d6bedf62aa93b6e117efd37f9a4/sass/layout/_sidebar-left.scss#L404
Fixes https://github.com/mattermost/mattermost-server/issues/15886
> [GH-15886] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 614

- components/create_comment/create_comment.jsx
- components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
- components/rhs_thread/rhs_thread.tsx
Reverts mattermost/mattermost-webapp#6167
Let's revert this until we have the common components Menu as some bugs were introduced 
https://mattermost.atlassian.net/browse/MM-29520
https://mattermost.atlassian.net/browse/MM-29516
These need to be taken into account when we implement the common components.
> Revert "[MM-24507] - Pin comment box on bottom of RHS thread"

- components/admin_console/billing/company_info_edit.tsx
When editing company information where an existing company address was present, the country field wasn't being populated. This required the user to have to select the country a second time before validation allowed the Save button to be enabled.
This PR fixes the initial value of the country so that the Save button is enabled immediately when opening the screen, such that editing other non-required fields (ie. number of employees) to function without issue.
https://mattermost.atlassian.net/browse/MM-29914
> [MM-29914] Fixed the initial value of the country on company info edit

- e2e/cypress/integration/markdown/markdown_image_spec.js
- e2e/cypress/integration/messaging/image_attachment_spec.js
- e2e/cypress/integration/messaging/long_post_attachments_spec.js
- Added mouseover trigger to image before clicking modal close
NA
> Cypress/E2E: Added mouseover trigger to image before clicking modal close

- actions/websocket_actions.jsx
Jason reported an issue where some new DMs weren't causing the channel to become visible in the sidebar, and we think this is only happening to him because he's in so many channels, so he's more likely to run into the batched handling of new posts. The batched post handling skips some steps of receiving new posts such as counting mentions and unread messages, and because the DM is not becoming unread, it's not appearing in the sidebar.
We'd obviously like to improve the handling of multiple new posts at once, but for the time being, we're going to see if decreasing the chance that this logic triggers helps to begin with.
https://mattermost.atlassian.net/browse/MM-28490
> MM-28490 Increase the number of new posts received before the events being batched

- e2e/cypress/integration/bot_accounts/managing_bot_accounts_spec.js
- e2e/cypress/integration/enterprise/bot_accounts/managing_bot_accounts_spec.js
- Fixed bot accounts disabled section verification
NA
> Cypress/E2E: Fix bot accounts disabled section verification

- components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
When copying and pasting emails over the limit, the control wouldn't allow the email to be added, but would still disable the Send button, requiring the user to delete an email unnecessarily.
This PR allows the users to enter as many emails as they want, but will trigger validation on each addition and on typing to ensure that more than 10 cannot be sent out.
https://mattermost.atlassian.net/browse/MM-29844
> [MM-29844] Fixed email input to allow multiple emails to be typed and trigger validation on more cases

- e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js
- e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js
- e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_removal_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
- e2e/cypress/integration/enterprise/profile_popover/profile_popover_spec.js
- e2e/cypress/integration/enterprise/system_console/channel_members_spec.js
- e2e/cypress/integration/enterprise/system_console/team_members_spec.js
- e2e/cypress/integration/enterprise/visual_regression/helpers.js
- e2e/cypress/integration/enterprise/visual_regression/system_console/about_section_spec.js
- e2e/cypress/integration/enterprise/visual_regression/system_console/authentication_section_spec.js
- e2e/cypress/integration/enterprise/visual_regression/system_console/compliance_section_spec.js
- e2e/cypress/integration/enterprise/visual_regression/system_console/environment_section_spec.js
- e2e/run_tests.js
- e2e/utils/file.js
This PR adds the ability to run test in CI for EE and TE.
- For EE: `CYPRESS_runWithEELicense=true node run_tests.js --stage='@prod'`, given that a license file can be found at `cypress/fixtures` folder.
- For TE: `node run_tests.js --stage='@prod' --exclude-group='@enterprise'`
Other changes included:
- For tests that require license to run:
- Moved folder/files into `/enterprise` folder
- Added each test file with `@enterprise` metadata
Note: ~~Test runs for EE and TE are ongoing. Will share report links once completed~~ See reports:
- EE test report - https://mm-cypress-report.s3.amazonaws.com/1159-ee-prod-master/mochawesome.html
- failed tests known to master-prod
- TE test report - https://mm-cypress-report.s3.amazonaws.com/1158-te-prod-master/mochawesome.html
- failed tests known to …
> MM-29918 Cypress/E2E: Add ability to run tests for EE and TE

- components/next_steps_view/steps/invite_members_step/index.ts
- components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
- components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
- i18n/en.json
When email invites are disabled on the server, and you try to send invites via the Onboarding flow as a sysadmin, there will be a generic error message.
This PR just disables the email invite prompt if email invites are disabled. It shouldn't make a difference for Cloud customers, since email invites should be enabled by default for Cloud.
https://mattermost.atlassian.net/browse/MM-28312
> [MM-28312] Hide email invitations on invite members step if they're disabled

- sass/layout/_headers.scss
- utils/utils.jsx
adds css rule to `sass/layout/_headers.scss` replacing `changeCss` occurrence for `.header-dropdown__icon` css class 
Fixes https://github.com/mattermost/mattermost-server/issues/16027
> [MM-29841] update class .header-dropdown__icon to use css variable

- sass/layout/_headers.scss
- utils/utils.jsx
Removes changeCss() for the channel header heading (`.app__body .channel-header .heading`).
Sets the color of `.app__body .channel-header .heading` to `--center-channel-color` from scss file.
Fixes https://github.com/mattermost/mattermost-server/issues/16025
> Update channel-header heading color

- components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap
- components/product_notices_modal/product_notices.test.tsx
- components/product_notices_modal/product_notices_modal.tsx
- package-lock.json
- package.json
* Add  track event when user clicks on action button of notice
https://mattermost.atlassian.net/browse/MM-29998
https://github.com/mattermost/mattermost-redux/pull/1277
> MM-2998 Add telemetry for product notices

- sass/components/_post.scss
- utils/utils.jsx
Removes the call to `changeCss()` for the disabled send button mentioned in the issue below and adjusts the buttons color to `--center-channel-color` to the scss file.
Fixes https://github.com/mattermost/mattermost-server/issues/16028
> [MM-29842] Migrate changeCSS() to CSS variable in utils/utils.jsx

- selectors/views/channel_sidebar.test.js
- selectors/views/channel_sidebar.ts
This is coming in a bit late, but with the new unread filter enabled, we forgot to filter out archived channels when the user isn't looking at them.
https://mattermost.atlassian.net/browse/MM-29986
> MM-29986 Don't show archived channels with unread filter enabled

- components/channel_header_mobile/collapse_rhs_button/collapse_rhs_button.tsx
- components/channel_header_mobile/collapse_rhs_button/index.ts
Migrating 'components/channel_header_mobile/collapse_rhs_button' module to TypeScript
Fixes https://github.com/mattermost/mattermost-server/issues/16160
JIRA: https://mattermost.atlassian.net/browse/MM-20413
> MM-20413: Migrate 'components/channel_header_mobile/collapse_rhs_button' module to TypeScript

- components/admin_console/billing/billing_history.tsx
- components/admin_console/billing/billing_summary.tsx
FormattedDate converts the time to the local timezone. Setting the timeZone prop to UTC will keep it as the proper date, since that date is UTC.
https://mattermost.atlassian.net/browse/MM-30196
N/A
N/A
> [MM-20196] Use UTC timezone for formattedDate so it doesn't change the date

- components/admin_console/billing/billing_summary.tsx
See here: https://stackoverflow.com/a/53048160
Because this was a number, the condition wouldn't return the latter, so it return invoice.tax, and print just "0" in the dom. This will ensure its not rendered in the case its false.
https://stackoverflow.com/a/53048160
n/a
n/a
> [MM-30127] Make invoice.tax a boolean so a rogue 0 isn't rendered

- utils/utils.jsx
Removes ChangeCSS() for `.app__body .shadow--2',` selectors with `'box-shadow: 0 20px 30px 0' <ins> changeOpacity(theme.centerChannelColor, 0.1) </ins> ', 0 14px 20px 0 ' <ins> changeOpacity(theme.centerChannelColor, 0.1)` properties
I am assuming `.shadow--2` does not affect any elements on the app so I am just deleting the line if that is right
Github Issue: Fixes https://github.com/mattermost/mattermost-server/issues/16022
JIRA Ticket: Fixes https://mattermost.atlassian.net/browse/MM-29836
> [MM-29836] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 693

- components/admin_console/billing/billing_history.scss
- components/admin_console/billing/billing_history.tsx
The billing history screen would flash "No invoices found" (or something similar) until the invoices endpoint returned something (regardless of if it was going to return something or not. 
invoices starts out null, and then is defined when the endpoint returns, even if the endpoint returns nothing. So we just need to know whether its null or not, before handing over the render to the rest of the logic.
I also added a spinner because I thought it looked good. Spoke with Matt, and he agrees.
https://mattermost.atlassian.net/browse/MM-30190
n/a
> [MM-30190] Show spinner when loading invoices instead of 'no invoices found'

- sass/components/_popover.scss
- utils/utils.jsx
Migrate a CSS variable for popover from `utils/utils.jsx` into `sass/components/_popover.scss`
Fixes https://github.com/mattermost/mattermost-server/issues/16177
> [MM-30173] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 707

- sass/components/_popover.scss
- utils/utils.jsx
Migrate a CSS variable for popover from `utils/utils.jsx` into `sass/components/_popover.scss`
Fixes https://github.com/mattermost/mattermost-server/issues/16178
> [MM-30174] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 708

- e2e/cypress/integration/enterprise/system_console/cluster_spec.js
- Moved spec to enterprise as it requires license
- Added feature reset so that verification for default state passes
NA
> Cypress/E2E: Move cluster spec to enterprise

- components/toast_wrapper/toast_wrapper.jsx
- components/toast_wrapper/toast_wrapper.test.jsx
This was a regression caused here https://github.com/mattermost/mattermost-webapp/pull/5828.
* The initOffset we use for displaying toast should be only used mount as that is not a scroll position that is updated after mount. It. can only be used for determining the offset when mounting like unread toast but not after. scrolling a bit and marking channel as unread. We are not tracking the real-time scroll offsets to do this atm.
* Changing this to show unread toast on all occasions of marking the channel as
unread other than channel at the bottom
https://mattermost.atlassian.net/browse/MM-29929
> MM-29929 Fix for unread messages toast on marking channel as unread

- components/edit_post_modal/edit_post_modal.jsx
- components/edit_post_modal/edit_post_modal.test.jsx
This PR fixes when trying to edit a post and using `CMD + ENTER` on mac for all messages to send the message. Previously, it did nothing. Now, it sends the message. This matches the behaviour of when creating a post.
Also addresses the problem where if you are within a code block when editing a post and setting is set to send messages only for code blocks, if you hit enter it should move the text to a new line and not submit. If you type `CMD + ENTER` then it will edit the post.
https://mattermost.atlassian.net/browse/MM-30226
https://mattermost.atlassian.net/browse/MM-30255
> [MM-30226][MM-39255] Allow a post to be sent when you do CMD + ENTER on Mac with 'Allow all messages' to be sent via CMD + ENTER

- components/system_notice/__snapshots__/system_notice.test.jsx.snap
- components/system_notice/system_notice.jsx
- sass/components/_system-notice.scss
- utils/utils.jsx
Removes `changeCss()` for `.shadow--2` `-moz-box-shadow` and `-webkit-box-shadow` (currently only used in .app__body .system-notice.shadow--2)
Removes `.shadow--2` class for `SystemNotice` component
No additions were made to SCSS files because `SystemNotice` already has `@include box-shadow(0 20px 30px alpha-color($black, .07), 0 14px 20px alpha-color($black, .07));` set in `sass/components/_system-notice.scss` 
Fixes [mattermost/mattermost-server#16023](https://github.com/mattermost/mattermost-server/issues/16023)
Fixes [mattermost/mattermost-server#16024](https://github.com/mattermost/mattermost-server/issues/16024)
Seems like the non `-moz` and non -`webkit` version of this similar change was tackled in https://github.com/mattermost/mattermost-webapp/pull/6933
Currently retains its …
> Apply Theme center-channel-color to .shadow--2

- components/admin_console/permission_schemes_settings/permission_description.jsx
Update `this.refs.content` to `this.content` as a react ref function
github issue -> Fixes https://github.com/mattermost/mattermost-server/issues/16038
JIRA ticket -> https://mattermost.atlassian.net/browse/MM-29855
n/a
n/a
> [MM-29855] Migrate string-refs to functional ones: this.refs.content

- components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
- components/rhs_thread/rhs_thread.tsx
Fix menu rendering behind input box in RHS.
https://mattermost.atlassian.net/browse/MM-29933
Reverts some changes made in https://github.com/mattermost/mattermost-webapp/pull/6920
> MM-29933 Fix menu rendering behind input box in RHS.

- components/admin_console/billing/billing_subscriptions.tsx
- components/admin_console/billing/payment_info.tsx
- package-lock.json
- utils/cloud_utils.ts
There were a few issues reported around the credit card expired, and almost expired banners shown in a few places in the admin console. While I couldn't reproduce the reported problems, I was able to discover a few other issues in the process. Weirdly, these issues all would contribute to it _not being possible_ for that banner to display.
` const expiryYear = customer.payment_method.exp_year + 2000;` It was assumed that stripe would return the year "y2k" style as just the last 2 digits, but this looks to have been an error in the test data. Stripe returns years in the format `2020`. 
The `useState` hooks were not synced with redux (since it wasn't a connected component, but used redux hooks instead is my assumption), so there would be weird behaviour, since the customer object wouldn't …
> [MM-30104][MM-30105] Fix up banners in payment_info and billing_subscription pages

- components/admin_console/billing/payment_info_edit.tsx
- components/purchase_modal/purchase_modal.tsx
As soon as a component that uses stripe was imported into any file in the webapp, the stripe library would be loaded regardless of whether it was a cloud instance or not. This PR moves the stripe lib loading to wait for the component to render before attempting to load. 
https://mattermost.atlassian.net/browse/MM-29621
N/A
N/A
> [MM-29621] Only load the stripe library when cloud components are actually rendered

- sass/components/_popover.scss
- utils/utils.jsx
Migrate a CSS variable for popover from `utils/utils.jsx` into `sass/components/_popover.scss`
Fixes https://github.com/mattermost/mattermost-server/issues/16179
> [MM-30175] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 709

- components/team_settings_modal/index.ts
- components/team_settings_modal/team_settings_modal.test.tsx
- components/team_settings_modal/team_settings_modal.tsx
- package-lock.json
We don't want to show the old slack import tool in cloud installations. This PR will hide it from the menu if the instance is a cloud one.
https://mattermost.atlassian.net/browse/MM-29515
https://github.com/mattermost/mattermost-server/pull/16271
N/A
> [MM-29515] Hide imports tab when in cloud installation

- e2e/cypress/integration/mark_as_unread/toast_appears_unread_spec.js
- Per this [comment](https://mattermost.atlassian.net/browse/MM-30534?focusedCommentId=101466), we just need to increase the content size to trigger the div toast
- Specifically testing for 1000 pixels might be finicky when they change later so I opted to just increase the content
@saturninoabril I didn't add v5.29 milestone since today is release day but feel free to add if you think we should
NA
> Cypress/E2E: Fix toast appears unread spec

- sass/layout/_webhooks.scss
- utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 549
`changeCss('.app*_body .attachment .attachment_*container', 'border-left-color:' <ins> theme.sidebarHeaderBg);`
Fixes https://github.com/mattermost/mattermost-server/issues/15869
Jira: https://mattermost.atlassian.net/browse/MM-29458
> MM-29458: Migrate changeCSS() to CSS variable in utils/utils.jsx

- webpack.config.js
In some cases, `.js/.jsx` files can be leftover from a TypeScript migration, and our webpack configuration was compiling in the JS over the TS file. This PR ensures that webpack in the webapp will prefer TS over JS.
https://mattermost.atlassian.net/browse/MM-29821
> [MM-29821] Prefer TypeScript files over JavaScript in webpack

- components/admin_console/billing/payment_info.tsx
- utils/cloud_utils.ts
Not sure how I missed this, but stripe sends the exp_year as 0 when it's not set (rather than null or something) so it would always be a date in the past. If it's 0, just return false.
https://mattermost.atlassian.net/browse/MM-30104
N/A
N/A
> If card year is 0 return false for isExpired

- actions/views/channel.js
- actions/views/channel.test.js
* makeAddLastViewAtToProfiles selector expects profiles to be
arrays always causing this to error out incase of no results
* Changing this pass in array incase of no key in data
https://mattermost.atlassian.net/browse/MM-30477
https://mattermost.atlassian.net/browse/MM-30739
> MM-30477 Fix for autocomplete not closing

- e2e/cypress/integration/channel_sidebar/category_muting_spec.js
- e2e/cypress/plugins/client_request.js
I accidentally merged my past PR without fixing a couple things Saturn asked about here: https://github.com/mattermost/mattermost-webapp/pull/7033#pullrequestreview-533717811
https://mattermost.atlassian.net/browse/MM-20897
https://github.com/mattermost/mattermost-webapp/pull/7033
> MM-20897 Cleanup a couple missed issues

- components/admin_console/admin_definition.jsx
This PR sets the `isDisabled` prop for entries in the `System Console` > `SITE CONFIGURATION` > `Notices` settings based on the roles for site. 
https://mattermost.atlassian.net/browse/MM-30509
When logged in as system admin user
When logged in as user with role permissions set to `system_manager` via mmctl (`mmctl permissions role assign system_manager jasonf2`)
> [MM-30509] set isDisabled prop for site > notices

- sass/base/_structure.scss
- utils/utils.jsx
Migrate ```changeCss('.app*_body #channel*view.channel-view', `background: ${theme.centerChannelBg}`)``` in line 620 to CSS variables. Css applied in `sass/base/_structure.scss`.
Fixes https://github.com/mattermost/mattermost-server/issues/15887
Jira: https://mattermost.atlassian.net/browse/MM-29500.
If I have to make changes in the PR, please do tell me. Thanks
> [MM-29500] Migrate changeCSS() to CSS variable in utils/utils.jsx

- components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.tsx.snap
- components/plugin_marketplace/marketplace_item/index.ts
- components/plugin_marketplace/marketplace_item/marketplace_item.test.tsx
- components/plugin_marketplace/marketplace_item/marketplace_item.tsx
- components/plugin_marketplace/marketplace_list/__snapshots__/marketplace_list.test.jsx.snap
- components/plugin_marketplace/marketplace_list/marketplace_list.jsx
- package-lock.json
- package.json
In preparation of the upcoming re-design of the Marketplace the whole Marketplace should get a migrated to typescript.
Most of the migration was straight forward. Please see my comments below on the questionable or tricky parts.
Please also note that this PR will go into the Marketplace feature branch.
https://mattermost.atlassian.net/browse/MM-20400
- Has redux changes https://github.com/mattermost/mattermost-redux/pull/1304
> [MM-20400] Migrate 'components/plugin_marketplace/marketplace_item' module and associated tests to TypeScript

- e2e/run_tests.js
- e2e/save_report.js
- e2e/utils/report.js
- e2e/utils/test_cases.js
Add the capability to run part by part for Cypress parallel testing.
Each part can execute by:
- `node run_tests.js --stage='@prod' --part=1 --of=2` 
- `node run_tests.js --stage='@prod' --part=2 --of=2`
See https://community-release.mattermost.com/core/pl/u96tyu4e9i8xir8gy17ckxgqge for generated test report which will include field for "Test Execution" -- link to Zephyr recorded test execution.
Jira ticket: https://mattermost.atlassian.net/browse/MM-30992
Typical job, like in CircleCI:
- Each E2E test part or job will run until complete. Then, each test artifacts will persist to workspace for next job processing which is consolidating and publishing all reports. The last job determines whether E2E failed or succeed.
> MM-30992 Add the capability to run part by part for Cypress parallel testing (part 1)

- sass/components/_modal.scss
The lack of padding caused the line numbers to not be aligned with the corresponding lines. Here's how it looks now:
https://mattermost.atlassian.net/browse/MM-30972
> MM-30972 Add proper padding to code preview line numbers

- components/post_markdown/system_message_helpers.jsx
Originally, /me posts were just styled by adding asterisks to force them to become italic, but we wanted to change how they were formatted, so we stored the non-formatted message in props to allow the client to do its formatting. We still needed the `Post.Message` to be wrapped in asterisks for compatibility with mobile and other clients.
That ended up causing problems because editing the post would only change the `Post.Message` without changing the copy in the props, so instead of trying to manage two copies of the post, we're just going to have the web app remove the asterisks from the message.
https://mattermost.atlassian.net/browse/MM-30810
https://github.com/mattermost/mattermost-server/pull/16456
> MM-30810 Remove special props from /me post

- actions/views/channel_sidebar.ts
- components/legacy_sidebar/sidebar.jsx
- components/sidebar/index.ts
- components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
- components/sidebar/sidebar_menu/sidebar_menu.tsx
- reducers/views/channel_sidebar.test.ts
- reducers/views/channel_sidebar.ts
Cherry pick of #7207 on cloud.
/cc  @hmhealey
> Automated cherry pick of #7207

- actions/views/channel_sidebar.ts
- components/create_comment/create_comment.jsx
- components/create_comment/create_comment.test.jsx
- components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
- components/sidebar/sidebar_channel_list/index.ts
- components/textbox/index.ts
- selectors/views/channel_sidebar.ts
Round two of the performance improvements including in order from most important to least:
1. We throttled updates to the comment draft when typing in the RHS a la https://github.com/mattermost/mattermost-webapp/pull/4692 which provides a huge improvement when typing rapidly in the RHS. (https://github.com/mattermost/mattermost-webapp/commit/b5b0a3ffa728506b9c021083e14167757c356214)
2. We reduced lag with the new sidebar by adding some slight tweaks when we read the collapsed state of categories from `state.storage.storage`. That part of state changes whenever the draft is updated, and it made some of the heavier sidebar selectors recalculate very often. It's much cheaper for us to do a quick shallow check on a map of categories to their collapsed state than it is to recalculate …
> MM-31466 Performance investigation part two

- components/admin_console/system_roles/system_role/system_role_permissions.tsx
If the billing section is not found a -1 is returned but we still delete that which deletes the last permission section in the list. We need to check it's greater than -1 to make sure we aren't deleting other permissions
https://mattermost.atlassian.net/browse/MM-31403
> [MM-31403] Ensure other permissions except billing getting deleted

- e2e/cypress/integration/messaging/at_mentions_spec.js
- e2e/cypress/integration/messaging/message_permalink_spec.js
- e2e/cypress/integration/notifications/desktop_notifications_spec.js
- e2e/cypress/integration/team_settings/teams_spec.js
- e2e/cypress/support/api/system.js
- e2e/cypress/support/index.js
- e2e/cypress/support/notification.js
Ignore/turn off all uncaught exception by Cypress.
There are several varieties of error and none could easily determined whether it's from the application itself or Cypress. Note that those uncaught exceptions were not observed while checking manually; only during test automation with Cypress.
Failing on daily Cypress test.
On local:
On CI:
> Cypress/E2E: Ignore uncaught exception by cypress

- actions/notification_actions.jsx
`makeGetChannel` was changed to take an object including an `id`, but this call to it wasn't updated, causing a bug in notifications. This PR fixes that call.
https://mattermost.atlassian.net/browse/MM-31580
> [MM-31580] Fix call to getChannel to use new parameter format

- components/search/search.tsx
- components/search_bar/__snapshots__/search_bar.test.jsx.snap
- components/search_bar/search_bar.test.jsx
- components/search_bar/search_bar.tsx
- components/search_results/search_results.tsx
- components/sidebar_right/sidebar_right.jsx
- components/widgets/menu/menu_items/menu_item.scss
- components/widgets/separator/separator.scss
This PR fixes regressions caused by https://github.com/mattermost/mattermost-webapp/pull/7029 and other style changes. I added a fix for the 'focussed' typo
https://mattermost.atlassian.net/browse/MM-31708
https://mattermost.atlassian.net/browse/MM-31726
https://mattermost.atlassian.net/browse/MM-31739
https://mattermost.atlassian.net/browse/MM-31727
Fix v. Cloud (January 12)
> [MM-31708][MM-31726][MM-31739][MM-31727] - Fix regressions in RHS and Status menu

- components/toast_wrapper/toast_wrapper.jsx
- components/toast_wrapper/toast_wrapper.test.jsx
Cherry pick of #7292 on cloud.
/cc  @hmhealey
> Automated cherry pick of #7292

- components/admin_console/__snapshots__/cluster_settings.test.jsx.snap
- components/admin_console/cluster_settings.jsx
- i18n/en.json
This PR just makes a small UI adjustment which removes the word experimental
from the system console. Any other things like variable names and id names
haven't been touched because the entire thing is going to be removed
after 3 months when the feature becomes default.
Test snapshots have been updated, and verified that there are no Cypress tests
matching this string.
https://mattermost.atlassian.net/browse/MM-31716
```release-notes
Removed the word "experimental" from gossip setting in the admin console
```
> MM-31716: Remove the word experimental from gossip setting

- e2e/cypress/support/ui_commands.js
On local dev, specifically when running with `npm run cypress:open`, `cy.postMessage` randomly failed waiting for `#post_textbox` to be visible. Not sure if you're seeing it too. As I observed, the channel page took so long to load on Cypress than normal (manual). It seemed that some webapp operation is blocked by Cypress while trying to wait for an element with `cy.get(textboxSelector, {timeout: TIMEOUTS.HALF_MIN})`.
I'm not a fan of explicit wait but I find it reasonable in this case. Please try on your local setup and let me know if something improves.  TIA.
none
> Cypress/E2E: Add explicit wait with cy.postMessage

- components/emoji/emoji_list/emoji_list.tsx
- e2e/cypress/integration/emoji/custom_emoji_spec.js
Bug introduced by https://github.com/mattermost/mattermost-webapp/pull/6742. Revert changes related to `searchEmojis` and make it nullable, to satisfy a condition to show up the list of custom emojis if search is not performed.
For E2E, make it stable and be able to retest without resetting the server.
Jira ticket - https://mattermost.atlassian.net/browse/MM-31960
> MM-31960 Fix custom emoji list and make related tests more stable

- components/user_settings/sidebar/limit_visible_gms_dms/index.ts
- components/user_settings/sidebar/limit_visible_gms_dms/limit_visible_gms_dms.tsx
- components/user_settings/sidebar/user_settings_sidebar.tsx
- i18n/en.json
The Account Settings section that allows the user to set the limit on DMs/GMs in the new sidebar.
https://mattermost.atlassian.net/browse/MM-30806
> [MM-30806] Account Settings - Setting to limit number of DMs/GMs shown in new sidebar

- e2e/cypress/integration/account_settings/display/account_settings_position_spec.js
- e2e/cypress/integration/account_settings/display/theme/save_theme_spec.js
- e2e/cypress/integration/account_settings/general/fullname_truncate_spec.js
- e2e/cypress/integration/account_settings/general/profile_picture_spec.js
- e2e/cypress/integration/account_settings/general/username_spec.js
- e2e/cypress/integration/archived_channel/archive_channel_addReaction_spec.js
- e2e/cypress/integration/archived_channel/archive_channel_operations_spec.js
- e2e/cypress/integration/bot_accounts/bot_api_not_cloud_spec.js
- e2e/cypress/integration/bot_accounts/bot_channel_intro_spec.js
- e2e/cypress/integration/bot_accounts/display_name_spec.js
- e2e/cypress/integration/bot_accounts/edit_bot_username_spec.js
- e2e/cypress/integration/bot_accounts/in_teams_and_channels_spec.js
- e2e/cypress/integration/bot_accounts/post_message_spec.js
- e2e/cypress/integration/bot_accounts/promote_demote_spec.js
- e2e/cypress/integration/bot_accounts/tags_spec.js
- e2e/cypress/integration/bot_accounts/token_spec.js
- e2e/cypress/integration/channel/add_users_to_channel_spec.js
- e2e/cypress/integration/channel/channel_routing_spec.js
- e2e/cypress/integration/channel_sidebar/dm_gm_behaviour_spec.js
- e2e/cypress/integration/channel_sidebar/sidebar_category_menu_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_more_spec.js
- e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
- e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
- e2e/cypress/integration/enterprise/ldap_group/channel_modes_spec.js
- e2e/cypress/integration/enterprise/system_console/archived_channels_spec.js
Promoting some tests that have been consistently passing in the last five runs to prod from unstable.
There are more tests that need to be looked into more in detail, thus doing it in parts for this week.
Also, note that I have added a comment in `token_spec` for MM-T1880 since there was a duplicate implementation of that test case; we'd want to keep the test from `bot_api_spec` but that file is not stable enough for prod, thus promoting this one for now so that it eliminates the need to run the test manually and has been passing consistently.
> Promoting tests to prod from unstable - part I

- sass/layout/_sidebar-left.scss
- sass/layout/_team-sidebar.scss
A CSS statement transforming the base team sidebar button container (`transform: translate(0, 0)`) was causing the desktop `Copy Link` context menu to not be rendered correctly.
Moving the transform to the `a` element inside the `team-container` stops it from affecting the context menu.
EDIT: Also noticed the extra transform statement was causing a horizontal scrollbar to appear. Seems to fix that as well.
https://mattermost.atlassian.net/browse/MM-32193
https://mattermost.atlassian.net/browse/MM-32178
> [MM-32193][MM-32178] Move transform for team sidebar button to anchor

- package-lock.json
- package.json
The last_viewed_at timestamp for channel members is only ever updated on the server to the time of the most recent post in the channel, so when the user refreshes, the priority for showing DM channels might change.
The old autohiding solved that by using some other timestamps which I'd like to remove eventually if we can make last_viewed_at work better, but in the mean time, we can still make use of them to get a better idea of when the user actually last viewed the channel.
https://mattermost.atlassian.net/browse/MM-32197
https://github.com/mattermost/mattermost-redux/pull/1339
> MM-32197 Use other timestamps when autohiding DMs/GMs

- sass/layout/_sidebar-left.scss
Fix the alignment of the history arrows on desktop app when the unread category is enabled.
https://mattermost.atlassian.net/browse/MM-32138
V.5.32
> [MM-32138] - Fix margin of history arrows without unread filter button

- components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
- components/sidebar/sidebar_category/sidebar_category.tsx
- components/sidebar/sidebar_channel/index.ts
- components/sidebar/sidebar_channel/sidebar_channel.test.tsx
- components/sidebar/sidebar_channel/sidebar_channel.tsx
- components/sidebar/unread_channels/unread_channels.tsx
- e2e/cypress/integration/bot_accounts/in_lists_spec.js
- sass/layout/_sidebar-left.scss
- selectors/views/channel_sidebar.ts
Cherry-pick of #7348 to `cloud`
> [MM-32167] Alphabetical and recency sorted categories will now have the same drop behaviour as DMs (#7348)

- components/admin_console/system_roles/system_role/add_users_to_role_modal/__snapshots__/add_users_to_role_modal.test.tsx.snap
- e2e/cypress/plugins/external_request.js
- e2e/cypress/support/api/system.js
- e2e/cypress/support/api/user.js
- e2e/cypress/support/index.js
- e2e/cypress/support/task_commands.d.ts
- e2e/cypress/support/task_commands.js
Fix time out error on initial Cypress run against remote server. Note that the time out error is not related to product changes but most likely related to initial access by newly created admin user against newly created remote server in CI. It might be something to do with DNS propagation but will investigate further. For the meantime, the solution here works 100% of the time.
> Cypress/E2E: Fix time out error on initial Cypress run against remote server

- e2e/cypress/integration/enterprise/system_console/reporting/site_statistics_spec.js
- e2e/cypress/integration/system_console/reporting/site_statistics_te_spec.js
Separate TM4J keys for team and enterprise of site statistics
- remain MM-T904 for enterprise, and
- add MM-T3804 for team edition
> Cypress/E2E: Separate TM4J keys for team and enterprise of site statistics

- components/apps_form/apps_form_field/apps_form_select_field.tsx
This PR replaces the <p> element with the <label> element for the select field name to match other elements.
https://mattermost.atlassian.net/browse/MM-32189
> [MM-32189] Apps Modal UX: bold the select field name

- e2e/cypress/integration/channel/more_public_channels_spec.js
- e2e/cypress/integration/enterprise/system_console/authentication/authentication2_spec.js
- e2e/cypress/integration/enterprise/system_console/cluster_spec.js
Fix for more channels and auth specs.
For authentication specs, it's not easily reproducible in local but that's likely related to the race condition after updating a config and checking UI related to it. Fixed by moving UI check inside the `.then` of `apiUpdateConfig`.
none, failing in daily Cypress run
> Cypress/E2E: Fix for more channels and auth specs

- e2e/cypress/integration/account_settings/general/nickname_spec.js
- e2e/cypress/integration/channel_settings/add_users_to_channel_spec.js
- e2e/cypress/integration/channel_sidebar/sidebar_channel_menu_spec.js
- e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
- e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
- e2e/cypress/integration/notifications/ignore_channel_mentions_spec.js
- Fix failed tests due to recent change in add users modal
- Add missing TM4J keys for MM-T859
> Cypress/E2E: Fix failed tests due to recent change in add users modal

- e2e/cypress/integration/bot_accounts/in_lists_spec.js
- e2e/cypress/integration/bot_accounts/sidebar_display_spec.js
- `in_lists_spec.js`
- use regular user as possible
- retain MM-T1834 and MM-T1835 which is consistently passing (to easily move into production)
- `sidebar_display_spec.js`
- extract MM-T1836 into this new file
- fixed test by using regular using since the list/number of other users and bots are consistent
none, failing daily Cypress run
> Cypress/E2E: Fix tests for bots in list and in sidebar

- e2e/cypress/integration/channel/archived_channels_1_spec.js
- e2e/cypress/integration/channel/archived_channels_2_spec.js
Fix tests for archived channels.
`archived_channels_1_spec.js`
- moved all 7 stable tests here. 
`archived_channels_2_spec.js`
- moved 2 failing tests here
- MM-T1687 - fixed by correctly executing the sequence by reorganizing the use of `.then`, `cy.wrap` and `async`. so that a channel is not gets deleted first as expected.
- MM-T1688 - fixed by explicit log in of test user in the `beforeEach` hook
> Cypress/E2E: Fix tests for archived channels

- components/profile_popover/profile_popover.jsx
Changes casing of attr to match elsewhere, fixing react dev tools warning `React does not recognize the `data-testId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `data-testid` instead. `
- Fixes https://mattermost.atlassian.net/browse/MM-32499
> [MM-32499] Fix console warning

- components/search_results/search_results.tsx
This PR adds a second page search right after the first one, to be able to ensure that there are no more results, or enable the load more scrolling if there are. It fixes the infinite loading indicator on one-paged searches that we were experiencing in community.
https://mattermost.atlassian.net/browse/MM-32121
> [MM-32121] Fix neverending load on one-paged search results

- e2e/cypress/integration/notifications/direct_messages_do_not_add_indicator_spec.js
- Used new sidebar and verified unread channel is visited before logout.
NA
> Cypress/E2E: Fix dm indicator in title spec

- sass/layout/_sidebar-left.scss
* changed `margin-left` to `padding-left` on `.SidebarChannelGroupHeader--static` class
* added double-quotes for UTF-8 charset setting
* fixed transition property (from string value to actual property values)
Fixes [MM-32558](https://mattermost.atlassian.net/browse/MM-32558)
> MM-32558: changed SidebarHeader class to span full-width

- components/suggestion/switch_channel_provider.jsx
added `channel.name` to the concatenated searchString to make searching for the channel name (as written in the URL) possible as well.
Screenshot shows how searching for `town-square` is correctly showing `Town Square` as an option
Fixes [MM-25609](https://mattermost.atlassian.net/browse/MM-25609)
before|after
--|--
> added `channel.name` to the concatenated searchString

- sass/layout/_sidebar-left.scss
- sass/responsive/_mobile.scss
3 fixes are included in this PR:
- On mobile view, the width of the channels was not set on mobile view correctly. Have now been set to `290px`
- On desktop mobile view, the height of the channel menu element was too high. I've removed the specific height of the menu button element which should no longer be required now that we've switched the parent over to flexbox
- When dragging multiple channels, the count of channels was cutoff due to adding `overflow: hidden`. I've added `overflow: visible` to the dragging state of the channel so that it will show correctly.
https://mattermost.atlassian.net/browse/MM-32401
https://mattermost.atlassian.net/browse/MM-32450
> [MM-32401][MM-32450] Some style fixes for the sidebar

- e2e/cypress/integration/archived_channel/archive_channel_search_spec.js
- e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
- e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_one_spec.js
- e2e/cypress/integration/search_filter/edit_spec.js
- e2e/cypress/integration/signin_authentication/authentication_spec.js
- e2e/cypress/support/ui_commands.js
- Fix search box focus related failures; modified to use click instead of focus
- From `archived_leave_channel_spec.js`, there are 2 expected failures related to [MM-32606](https://mattermost.atlassian.net/browse/MM-32606)
- MM-T1672_1 and MM-T1673
NA
> Cypress/E2E: Fix search box focus related failures

- utils/text_formatting.tsx
- utils/text_formatting_imgs.test.jsx
provided a more sophisticated check for certain keywords in the channelNamesMap to check for the type being an object.
The application broke at this point because the value searched for is non-existent and therefore could not extract the `display_name` property, which is why the application was failing at this point. The change that fixes the bug is to be found at line 402
On the way I fixed some warnings and errors in the file
Fixes [MM-31916](https://mattermost.atlassian.net/browse/MM-31916)
> MM-31916: channel mention for specific keywords breaks application

- components/search_bar/search_bar.tsx
- sass/components/_search.scss
- sass/responsive/_mobile.scss
1. Fixed color in the mobile search-field for the dark-theme. It was black, but shoudl have been getting the color from the parents `form-control` class.
2. Fixed some warnings and errors in the SCSS files along the way
Fixes [MM-31961](https://mattermost.atlassian.net/browse/MM-31961)
focused|un-focused
--|--
> MM-31961: fixed color in search field for dark-theme

- sass/layout/_markdown.scss
fixed multiple word breaking in markdown tables without affecting links
Fixes [MM-26497](https://mattermost.atlassian.net/browse/MM-26497)
> MM-26497: markdown table word breaking

- components/file_upload/file_upload.test.jsx
- utils/constants.jsx
This reverts commit 4718281b7600650ef5d87b4d9633907c22a51955.
As mentioned in the related PR, we found issues with the database migration taking a really long time on certain versions of MySQL, so this has to be reverted while we figure out how to do that better.
https://github.com/mattermost/mattermost-server/pull/16907
> Revert "Allow uploading 10 files per post (#7160)"

- e2e/cypress.json
- e2e/cypress/support/api/system.js
This makes it easier to configure a remote test server to allow untrusted internal connections.
> Cypress/E2E: Fix for test that requires untrusted internal connection

- components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
- components/announcement_bar/configuration_bar/configuration_bar.tsx
- components/announcement_bar/default_announcement_bar/announcement_bar.tsx
- sass/components/_announcement-bar.scss
Prevents to show the renew now button text from the announcement bar when hovering and showing the tooltip.
https://mattermost.atlassian.net/browse/MM-32354
No related PRs
Before:
After:
> MM-32354 - do not show renew now text in announcement bar tooltip

- NOTICE.txt
- package-lock.json
- package.json
- types/external/custom-protocol-detection.d.ts
This library hasn't been used since https://github.com/mattermost/mattermost-webapp/pull/4688, so it's safe to remove without worrying about anything changing.
https://mattermost.atlassian.net/browse/MM-32928
> MM-32928 Remove custom-protocol-detection

- sass/components/_post.scss
This PR increases by 2 the z-index of the post box getting into z-index value of 12, that way it will overlap the z-index of the RHS that is a z-index value of 11.
https://mattermost.atlassian.net/browse/MM-32825
Before:
After
> MM-32825 - suggestion box hidden by rhs

- Makefile
`-l` seems to be a non-standard flag that's supported on Mac, not Ubuntu, so we can't use that to have the killed processes output. `-f` is still needed since that causes it to match process arguments as well (since previous versions of webpack ran as `node webpack`).
https://github.com/mattermost/mattermost-webapp/pull/7512
> Remove output from pkill

- components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
- sass/layout/_sidebar-left.scss
enables tooltips for long channel names (those that will be truncated) in the sidebar
Fixes [MM-27400](https://mattermost.atlassian.net/browse/MM-27400)
> MM-27400: tooltip for long channel names

- e2e/utils/report.js
- Added optional release date to Release/Cloud reports
Here's the associated PR for adding environment variable in our ci config: https://github.com/saturninoabril/mattermost-cypress-docker/pull/22
NA
> Cypress/E2E: Add release date to appropriate report

- e2e/cypress.json
- e2e/cypress/support/index.js
- e2e/run_tests.js
Timeout error on first request to update the config consistently happened before on fresh remote test server. However, lately, I'm seeing the same to server pre-generated with sample data (using `sampledata` CLI command). With that, I just moved the dummy call to a common logic and add a `CYPRESS_firstTest` environment variable so it will trigger on first test only upon running `node run_tests.js` (the one we're using in CI). In local dev, it's set to `false` by default.
> Cypress/E2E: Add request on first E2E test

- selectors/views/custom_status.ts
Fix custom status possible race condition. Looks like in some cases the user
requests is not yet in the redux-store whenever this is trying to show the
custom status. So it fails. This new approach simply ignore that situation.
[MM-33047](https://mattermost.atlassian.net/browse/MM-33047)
> Fix custom status possible race condition

- e2e/cypress/integration/auth_sso/authentication_2_spec.js
- e2e/cypress/integration/auth_sso/authentication_not_cloud_spec.js
- e2e/cypress/integration/channel/channel_name_tooltips_spec.js
- e2e/cypress/integration/enterprise/system_console/cluster_spec.js
- e2e/cypress/integration/enterprise/system_console/environment_spec.js
- e2e/cypress/integration/enterprise/system_console/helpers.js
- e2e/cypress/integration/enterprise/system_console/limited_console_access_not_cloud_spec.js
- e2e/cypress/integration/messaging/visual_verification_of_tooltips_on_top_nav_channel_icons_posts_spec.js
- e2e/cypress/integration/system_console/environment_spec.js
- e2e/cypress/integration/system_console/site_configuration/link_customization_not_cloud_spec.js
- e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js
Add filter for tests not for cloud. Those tests typically requires server configuration that are not writable in Cloud edition.
> Cypress/E2E: Add filter for tests not for cloud

- e2e/cypress/integration/accessibility/accessibility_post_spec.js
- e2e/cypress/integration/account_settings/general/nickname_spec.js
- e2e/cypress/support/ui/common.d.ts
- e2e/cypress/support/ui/common.js
- Fixed nickname tests and MM-T1462
- Added global custom commands for common UI
- Removed unnecessary tests which are without corresponding written test cases in Zephyr. Those UI are typically covered by test related to account settings/nickname
- Added MM-T3848 test key
> Cypress/E2E: Fix nickname tests and MM-T1462

- package-lock.json
- package.json
The Selenium tests that QA use run on Firefox 54, and the new version of serialize-error fails to load on there because it uses slightly newer syntax (https://caniuse.com/mdn-javascript_statements_try_catch_optional_catch_binding, supported in Firefox 58+). Selenium will be upgraded or removed at some point, but this will fix it in the meantime.
https://mattermost.atlassian.net/browse/MM-33209
https://github.com/mattermost/mattermost-redux/pull/1372
> MM-33209 Downgrade serialize-error

- package-lock.json
- package.json
The latest version of webpack-livereload-plugin didn't support Webpack 5 as of last week, but this new one does.
https://mattermost.atlassian.net/browse/MM-33237
> MM-33237 Update webpack-livereload-plugin

- e2e/cypress/integration/account_settings/general/fullname_spec.js
- e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/helpers/index.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
- e2e/cypress/integration/search_autocomplete/renaming_spec.js
- e2e/cypress/integration/search_autocomplete/users_spec.js
- e2e/cypress/support/ui/index.js
- e2e/cypress/support/ui/suggestion_list.d.ts
- e2e/cypress/support/ui/suggestion_list.js
Fix E2E due to [recent change in at-mention suggestion list](https://github.com/mattermost/mattermost-webapp/pull/7441) (with custom status), specifically related to the removal of [`.ml-2` class name](https://github.com/mattermost/mattermost-webapp/pull/7441/files#diff-38d76f42942a8534f255c0e3ee4e767dc70ff0083f309dfdbf47d5ebb7362cdcR176)
Added `cy.uiVerifyAtMentionInSuggestionList` and `cy. uiVerifyAtMentionSuggestion` to global custom commands to easily verify suggestion list, specifically for at-mention.
none
> Cypress/E2E: Fix E2E due to recent change in at-mention suggestion list

- webpack.config.js
As Caleb pointed out to me, the casing was incorrect for `contenthash`. I don't know when in the upgrade process that broken, but we went from 0.9.0 to 1.3.5 with that plugin, so it could've been any time.
https://mattermost.atlassian.net/browse/MM-33245
> MM-33245 Fix casing on contenthash for CSS

- webpack.config.js
Most of this is just some changes that were recommended by the migration guide for Webpack 5, but the important one is that setting `snapshot.managedPaths` to empty means we're no longer going to be snapshotting `node_modules` when running webpack in watch mode since that broke mattermost-redux's `npm run dev:watch`. We could look at re-enabling that in the future, but changing it didn't seem to have a notable effect on build times for me.
https://mattermost.atlassian.net/browse/MM-33285
> MM-33285 Turn off snapshotting of node_modules and minor webpack changes

- components/suggestion/command_provider/app_command_parser.test.ts
- components/suggestion/command_provider/app_command_parser.ts
- components/suggestion/command_provider/command_provider.tsx
- components/suggestion/suggestion_box.jsx
Fix several parser problems:
- Commands are case insensitive and they respect the casing of parameters
- Text value suggestion will not clean the value added
- Text value suggestion will not add an extra space when it is empty
- Quoted and ticked text value suggestion will close the quote and tick
- Command and flag suggestions will not add double space
- Use codeblocks to show errors so the arrow points the right position
- Slightly improve errors view
- Correct case where selecting a suggestion may not introduce the previous space
- Added call error management
- Remove already completed fields
- Quoted and ticked empty values will result in parsing error
Added several tests, not sure if they cover all cases.
None
None
None
> Fix App parser

- sass/components/_modal.scss
**Updating font size for add people to channel modal**
The PR removes the 0.9em font size as that was reducing the font size in the modals.
The more DM modal etc is also affected by this.
https://mattermost.atlassian.net/browse/MM-32811
> Updating font size for add people to channel modal

- components/sidebar/sidebar_channel_list/__snapshots__/sidebar_channel_list.test.tsx.snap
- components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
- e2e/cypress/integration/accessibility/accessibility_keyboard_usability_spec.js
- e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js
- e2e/cypress/integration/channel/more_channels_spec.js
- e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
- e2e/cypress/integration/keyboard_shortcuts/alt_option_plus_up_down_spec.js
- e2e/cypress/integration/notifications/browser_tab_notification_spec.js
- e2e/cypress/integration/notifications/unread_on_public_channel_spec.js
while the new name might fit better, the current and previous desktop app version use the id for detecting if the user is logged into Mattermost. Since we can't change current installations, we need to revert back to the previous ID and plan the change for future versions.
[MM-33397](https://mattermost.atlassian.net/browse/MM-33397)
@saturninoabril one of the e2e tests failed for me (browser_tab_notification_spec) but I don't think it was due to this change, can you take a look at it?
> [MM-33397] revert lhs ID for backward compatibility

- e2e/cypress/integration/archived_channel/archive_channel_search_spec.js
- e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
- e2e/cypress/integration/enterprise/system_console/compliance/compliance_export_multiple_post_spec.js
- e2e/cypress/integration/enterprise/system_console/compliance/compliance_export_ui_spec.js
- e2e/cypress/integration/mark_as_unread/mark_gm_as_unread_spec.js
- e2e/cypress/integration/messaging/long_draft_spec.js
- e2e/cypress/integration/messaging/message_edit_post_clear_text_spec.js
- e2e/cypress/integration/messaging/receive_message_on_socket_reconnect_spec.js
- e2e/cypress/integration/messaging/visual_verification_of_tooltips_on_top_nav_channel_icons_posts_spec.js
- e2e/cypress/integration/plugins/upgrade_spec.js
- e2e/cypress/integration/system_console/user_management_spec.js
Those demoted tests were found to be flaky and some of them were attempted to fix but to no avail. Will put on unstable tests and will further investigate separately.
Note:
- `system_console/user_management_spec.js` - affected by recent change on Email redesign - https://github.com/mattermost/mattermost-server/pull/16824. Also, we might need to extract other tests that require email verification into separate spec file.
> Cypress/E2E: Promote and demote E2E tests

- e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
- Fixed to reflect the changes in dropdown implementation of change timezone
- Also added reset to opposite for each case to make sure setting the timezone is correct
NA
> Cypress/E2E: Fix timezone display mode spec

- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_with_special_characters_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/helpers/index.js
Organize, add keys and match test case of Elasticsearch autocomplete for channel
- MM-T2510
- MM-T2517
> Cypress/E2E: Organize and add keys of Elasticsearch autocomplete for channel

- e2e/cypress/integration/channel/channel_name_tooltips_spec.js
- This is using legacy sidebar, so I just needed to update this in the test rather than globally.
- I also made sure there are no other tests that uses both legacy sidebar and `uiAddDirectMessage`
NA
> Cypress/E2E: Fix channel name tooltips

- actions/marketplace.ts
- components/plugin_marketplace/marketplace_item/marketplace_item_app/__snapshots__/marketplace_item_app.test.tsx.snap
- components/plugin_marketplace/marketplace_item/marketplace_item_app/marketplace_item_app.test.tsx
- components/plugin_marketplace/marketplace_item/marketplace_item_app/marketplace_item_app.tsx
- components/plugin_marketplace/marketplace_list/marketplace_list.tsx
- package-lock.json
- package.json
Given that only AWS apps will be installable via the Marketplace the app id can be used directly to install it. The secret is also not needed given that authentication is done via the lambda invocation.
https://mattermost.atlassian.net/browse/MM-33511
- Has redux changes: https://github.com/mattermost/mattermost-redux/pull/1394
> Use App id to install App from Marketplace

- package-lock.json
- package.json
- store/index.js
This PR complements https://github.com/mattermost/mattermost-redux/pull/1393 to remove the dependency on the effectively unused redux-action-buffer.
It is a first step towards removing redux-offline altogether.
Relates-to: https://mattermost.atlassian.net/browse/MM-24009
> MM-24009: remove redux-action-buffer

- sass/components/_post.scss
Using a `border` for the create post `textarea` was causing some undesirable shifting effects that happened mostly on focus/blur. So I've changed them both over to using a `box-shadow` that does not affect the position of the text inside.
https://mattermost.atlassian.net/browse/MM-33033
> [MM-33033] Use box-shadow for create post border instead of border

- plugins/channel_header_plug/channel_header_plug.tsx
Channel header dropdown does not count bindings to set the count, and the icons resize instead of be of a predetermined size. This ticket fix both.
https://mattermost.atlassian.net/browse/MM-33530
https://mattermost.atlassian.net/browse/MM-33529
> Fix channel header dropdown icon size and count

- components/suggestion/command_provider/app_command_parser.test.ts
- components/suggestion/command_provider/app_command_parser.ts
We allow multi-word select options by surrounding them by ticks.
We also fix the problem with closed quotes disappearing because of autocomplete.
https://mattermost.atlassian.net/browse/MM-33534
https://mattermost.atlassian.net/browse/MM-33419
> Fix multiword select options and keep quotes on complete values

- components/admin_console/system_roles/system_role/system_role.tsx
Currently, we are determining the ancillary permissions required on the front-end. This should be done on the backend.
This will allow us to eliminate having to keep a copy of ancillary permissions on the front-end.
https://mattermost.atlassian.net/browse/MM-33501
Redux: https://github.com/mattermost/mattermost-redux/pull/1392
Server: https://github.com/mattermost/mattermost-server/pull/17061
> [MM-35501] Remove Determining Ancillary Permissions from Frontend to Backend

- components/main_menu/main_menu.jsx
As part of https://github.com/mattermost/mattermost-webapp/pull/7496 the logic to validate if users can invite was moved directly to the invitation modal component. This PR removes some extra validation logic. 
https://mattermost.atlassian.net/browse/MM-32925
> MM-3295 - remove no longer necessary validation

- components/suggestion/command_provider/app_command_parser.ts
Remove autocomplete of ~ and @ for user and channel suggestions. There are still some minor problems with autocomplete due to ill behaviour from channel mentions provider. Ticket created for Webapp team [here](https://mattermost.atlassian.net/browse/MM-33674)
https://mattermost.atlassian.net/browse/MM-33657
https://mattermost.atlassian.net/browse/MM-33415
> Remove autocomplete of ~ and @ for user and channel suggestions

- sass/components/_modal.scss
The system console modal header close button currently relies on the default css colour, using the theme variable for the default css colour applies the theme colour in the system console as well as the main app. This PR resets the default colour back to its original `white` and applies the theme variable in the context of the main app only.
https://mattermost.atlassian.net/browse/MM-33592
Before:
After:
> only apply theme variable in context of main app

- utils/emoji_utils.test.jsx
- utils/emoji_utils.tsx
Jelena found a weird bug this morning where we don't render the name of sidebar categories with one-character names. Turns out that happened because `wrapEmojis` had an off-by-one error that made it sometimes not include the last character in its input, so when that was called on a one-character name, it would return the empty string.
https://mattermost.atlassian.net/browse/MM-33581
> MM-33581 Fix off-by-one error in wrapEmojis

- sass/components/_react-select.scss
This PR changes a hard-coded colour value for the Select Dropdown's background when disabled to use the correct theme variable.
https://mattermost.atlassian.net/browse/MM-33666
> use theme variable for disabled select background

- sass/layout/_sidebar-left.scss
fix for hover on SidebarLink to use correct color set from theme
[MM-33330](https://mattermost.atlassian.net/browse/MM-33330)
> MM-33330 - fixed SidebarLink background-color on hover

- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_with_special_characters_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_team_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/system_console_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
- e2e/cypress/integration/enterprise/system_console/search_box_spec.js
- e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
- e2e/cypress/integration/messaging/long_draft_spec.js
- e2e/cypress/integration/messaging/message_edit_post_clear_text_spec.js
- e2e/cypress/integration/messaging/permalink_click_spec.js
Promoting the tests from unstable to prod that were regularly passing between 03/08 to 03/15. Some of the autocomplete with Elasticsearch tests haven't been promoted in this PR since they need some cleanup.
> Promoting regularly passing tests from 03/08 to 03/15

- components/admin_console/system_users/system_users.test.tsx
- components/channel_layout/channel_identifier_router/channel_identifier_router.test.tsx
- components/edit_post_modal/edit_post_modal.test.jsx
- components/suggestion/at_mention_provider/at_mention_provider.test.jsx
- tests/setup.js
Turning on fake timers for everything breaks a bunch of tests in mattermost-redux since those rely a lot more on async code and timeouts. Now we'll only use them on the specific test files that need them.
> Only use fake timers for tests that need them

- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_with_special_characters_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_team_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/system_console_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_in_channel_switcher_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_in_message_input_box_spec.js
- e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
- e2e/cypress/integration/enterprise/integrations/incoming_webhook_spec.js
- e2e/cypress/integration/enterprise/system_console/compliance/compliance_export_ui_spec.js
- e2e/cypress/integration/enterprise/system_console/compliance/s3_bucket_storage_spec.js
- e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
- e2e/cypress/integration/enterprise/visual_regression/system_console/about_section_spec.js
- e2e/cypress/integration/enterprise/visual_regression/system_console/authentication_section_spec.js
- e2e/cypress/integration/enterprise/visual_regression/system_console/compliance_section_spec.js
- e2e/cypress/integration/system_console/support_packet_generation_spec.js
- e2e/cypress/support/task_commands.js
- exclude tests related to Elasticsearch (ES) for cloud since config related to it is not writable
- remove unnecessary requirement to ES to some specs
- add option to ignore 'api.cloud.get_subscription.error'
none, failed on Cloud test run
> Cypress/E2E: Fix tests for cloud

- actions/apps.ts
- actions/command.test.js
- actions/command.ts
- components/apps_form/__snapshots__/apps_form_container.test.jsx.snap
- components/apps_form/apps_form.tsx
- components/apps_form/apps_form_container.test.jsx
- components/apps_form/apps_form_container.tsx
- components/apps_form/index.ts
- components/dot_menu/dot_menu.tsx
- components/dot_menu/index.ts
- components/post_view/embedded_bindings/button_binding/__snapshots__/button_binding.test.tsx.snap
- components/post_view/embedded_bindings/button_binding/button_binding.test.tsx
- components/post_view/embedded_bindings/button_binding/button_binding.tsx
- components/post_view/embedded_bindings/button_binding/index.ts
- components/post_view/embedded_bindings/select_binding/index.ts
- components/post_view/embedded_bindings/select_binding/select_binding.test.tsx
- components/post_view/embedded_bindings/select_binding/select_binding.tsx
- components/suggestion/command_provider/app_command_parser.test.ts
- components/suggestion/command_provider/app_command_parser.ts
- components/suggestion/command_provider/command_provider.test.tsx
- components/suggestion/command_provider/command_provider.tsx
- i18n/en.json
- package-lock.json
- package.json
- plugins/channel_header_plug/channel_header_plug.tsx
- plugins/channel_header_plug/index.ts
- utils/apps.ts
Now instead of using the call type, we add the type to the path at redux level.
I also included here the AppCall/AppCallRequest needed changes.
The errors in CI are most probably due to redux PR not being merged. When the Redux PR is merged, I will update this PR dependencies.
https://mattermost.atlassian.net/browse/MM-33178
Redux: https://github.com/mattermost/mattermost-redux/pull/1406
Mobile: https://github.com/mattermost/mattermost-mobile/pull/5221
Proxy: https://github.com/mattermost/mattermost-plugin-apps/pull/99
> Use type on call path, and minor refactoring

- sass/routes/_admin-console.scss
The PR [7686](https://github.com/mattermost/mattermost-webapp/pull/7686) added the backstage navbar to the admin console and this added a regression where the bottom save buttons where not being shown. This was caused by the height of both the right side panel and left side menu of the system console  were not updated to calculate their height taking into account the height of the new added element. This PR modifies the css heigh calculation functions by subtracting the heigh of the backstage-bar too so the heights are correct.
https://mattermost.atlassian.net/browse/MM-33907
> MM-33907 - fix admin console heigh and show save buttons

- e2e/cypress/integration/system_console/reporting/site_statistics_spec.js
This PR fixes the `site_statistics_spec` test that was failing in prod: the first run of the test was always failing because the testUser was not "active". Having the testUser post a message fixes this issue as that causes them to become an "active" daily and monthly user.
> Fixing site_statistics_spec

- e2e/cypress/integration/signin_authentication/login_spec.js
T3306_8 was failing because the logout button was not visible. Fixing this by scrolling the button into view.
> Scrolling the logout button into view so that it is visible

- e2e/cypress/integration/menus/status_dropdown_spec.js
- e2e/cypress/integration/system_console/environment_spec.js
In this PR:
- fixing status dropdown failure by enabling custom status (1st screenshot below)
- fixing system_console/environment_spec failure by forcing a click on "Save" button (2nd screenshot below)
> Fix status dropdown

- build/Dockerfile
Once https://github.com/mattermost/mattermost-webapp/pull/7741 is merged, we'll be able to run everything on Node 14, but we have to prep to push a new build image first.
https://mattermost.atlassian.net/browse/MM-25140
https://github.com/mattermost/mattermost-webapp/pull/7741
> MM-25140 Update build Docker image to Node 14

- components/widgets/team_icon/team_icon.scss
Fix the background blend mode for team icon when the white background is peeking through in Firefox
https://mattermost.atlassian.net/browse/MM-33609
> [MM-33609] - Fix team icon coverage on firefox

- e2e/cypress/fixtures/theme.json
- e2e/cypress/integration/menus/status_dropdown_spec.js
- e2e/cypress/support/api/cloud_default_config.json
- e2e/cypress/support/api/on_prem_default_config.json
In this PR:
- Adding the missing test case T2927_4: verify that the status icons are visible in dark mode.
- Adding a test case T2927_6 (updated in Zephyr as well) to verify that the status menu opens as expected when custom status is disabled to make sure such regression is covered.
- Removed a few duplicate tests that were written a long time ago.
- Some cleanups.
> Updating status_dropdown_spec with missing test cases

- components/suggestion/command_provider/app_command_parser/app_command_parser.ts
If a flag or a command include uppercase it caused problems with the parser.
Probably need port to mobile.
None
> Case independency fixes

- components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
- components/add_groups_to_team_modal/add_groups_to_team_modal.tsx
- components/data_prefetch/data_prefetch.test.tsx
These tests are broken on Node 14 due to it running some async code differently. I fixed it by having the modals' `handleSubmit` methods actually wait for their results (which shouldn't affect the UI since it doesn't await on `handleSubmit`) and by figuring out how to properly mock the `PQueue` used by the `DataPrefetch` component. That one was a lot trickier since the tests did a lot of bizarre stuff like waiting on functions they'd mocked which didn't do anything other than letting other awaited calls proceed. With the mock, we can now manually pop and run queued tasks instead of having them run asynchronously at poorly-defined times.
https://mattermost.atlassian.net/browse/MM-25140
> MM-25140 Fix unit tests which are broken on Node 14

- components/post_view/channel_intro_message/add_members_button.tsx
- components/post_view/channel_intro_message/channel_intro_message.tsx
- components/post_view/channel_intro_message/index.ts
A bug was found in the logic for when to show the invite people to workspace or show the invite members to workspace. The problem was the in the initial implementation, the state.entities.admin.analytics.TOTAL_USER value was used, and it worked fine, but just for admins. This pull requests fixes that fetching on demand the total_users using the redux getTotalUsersStats action function.
https://mattermost.atlassian.net/browse/MM-34114
The totalUsers shown for an admin user:
The totalUsers shown for a NON admin user:
After Adding more users than the usersLimit, now the button changes:
Same behavior for a NON admin user:
> MM-34114 - grab users stats on demand to fix invite buttons logic

- e2e/cypress/integration/bot_accounts/in_lists_2_spec.js
- e2e/package.json
Fix [MM-T1835](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1835)
Others:
- removed `lodash` as explicit dependency in placed of using the bundled lodash by `Cypress._`
https://mattermost.atlassian.net/browse/MM-34001
> MM-34001 Cypress/E2E: Fix for members with bots

- components/post_view/channel_intro_message/add_members_button.tsx
The `totalUsers` prop expected by `AddMembersButton` isn't actually required, since the component has code to handle when the prop is falsy.  The property itself isn't available until after the background stats have loaded.
This removes a warning during development:
None.
> make totalUsers optional

- sass/components/_mentions.scss
https://github.com/mattermost/mattermost-webapp/pull/6609 introduced the display of user statuses in the channel switcher, but without loading the status for users not already known to the client.
This PR works around that limitation by correctly rendering an undefined status. It does not attempt to load the status for these users at this time.
Instead of:
We now show:
https://mattermost.atlassian.net/browse/MM-34371
> MM-34371: handle undefined status in switcher

- components/post_view/combined_system_message/combined_system_message.tsx
The combined system message component assembles a message from a set of system posts, but the TypeScript definition assumes that all system messages have actors. Some do not, including the opening system messages of `Town Square`, for which the join message is initiated by the server and not a user.
This eliminates the following console error:
None.
> make actorId optional

- babel.config.js
The installed `@babel/plugin-proposal-object-rest-spread` should be added in the babel config as [correct config](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread#usage), there was a small typo.
As discussed in [Community](https://community.mattermost.com/core/pl/dj1tpwmuxpf87by67p8tawo51h)
N/A
N/A
> chore : Fixed typo in babel plugin for object, rest, spread

- e2e/cypress/integration/enterprise/system_console/authentication_method_spec.js
- e2e/cypress/integration/messaging/markdown_spec.js
- e2e/cypress/integration/system_console/mobile_settings_spec.js
- e2e/utils/test_cases.js
Fix test key extraction.
Typical error in CI:
none but failed on daily Cypress run during saving test execution.
> Cypress/E2E: Fix test key extraction

- components/profile_popover/index.js
#7744 refactored Profile Popover and a number of callsites to rely on explicit channelId's. Some codepaths (see `markdown.tsx`/`messageHtmlToComponent`/`at_mention.jsx`) do not provide an explicit channel Id and instead Profile Popover was responsible for getting it's own channelId via `selectedPost.channel_id` or `getCurrentChannelId`.
This PR restores that auto channelId retrieval, fixing regression [MM-34553](https://mattermost.atlassian.net/browse/MM-34553)
Previous implementation: https://github.com/mattermost/mattermost-webapp/blob/cb98b4f9488ed537861d502b53ac8d70dab5f169/components/profile_popover/index.js#L41-L48
- https://mattermost.atlassian.net/browse/MM-34553
> MM-34553: profile popover, fix channel admin badge in channel header mentions

- components/suggestion/emoticon_provider.jsx
Lowercase pretext to ensure case independency
None
> Fix emoticons not being case indepent

- components/suggestion/command_provider/app_command_parser/app_command_parser.ts
Instead of using the appID as the root command trigger, respect the label send by the app.
https://mattermost.atlassian.net/browse/MM-34491
- Has Apps plugin changes: https://github.com/mattermost/mattermost-plugin-apps/pull/131
- Has mobile changes: https://github.com/mattermost/mattermost-mobile/pull/5278
> [MM-34491] Respect slash command root label

- e2e/cypress/integration/enterprise/system_console/settings_spec.js
> Cypress/E2E: Fix MM-T1635 Channel listing is displayed correctly with proper team name

- components/single_image_view/__snapshots__/single_image_view.test.tsx.snap
- components/single_image_view/single_image_view.tsx
- sass/components/_files.scss
Fixes long file names not being truncated and expand/collapse chevron being hidden
https://mattermost.atlassian.net/browse/MM-34580
Long file name: 
Short file name:
> [MM-34580] - Truncate image name when text is too long

- components/gif_picker/components/SearchGrid/SearchGrid.scss
The placeholder added in #7501 was missing its help text because the entire search results component for the gif picker had font-size set to 0. The "No results" line was still visible because it had its own font size set, but the help text was invisible because of that.
I don't think setting a font size for the rest of that component seems to have an effect. I can't find anything in the original PR relating to that line, so I think it might've been left over code.
https://mattermost.atlassian.net/browse/MM-34502
https://github.com/mattermost/mattermost-webapp/pull/7501
> MM-34502 Fix help text being invisible for empty gif picker

- actions/command.ts
- actions/global_actions.tsx
- components/apps_form/apps_form_container.tsx
- components/dot_menu/dot_menu.tsx
- components/post_view/embedded_bindings/button_binding/button_binding.test.tsx
- components/post_view/embedded_bindings/button_binding/button_binding.tsx
- components/post_view/embedded_bindings/select_binding/select_binding.test.tsx
- components/post_view/embedded_bindings/select_binding/select_binding.tsx
- components/suggestion/command_provider/app_command_parser/app_command_parser.ts
- components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
- packages/mattermost-redux/src/types/apps.ts
- plugins/channel_header_plug/channel_header_plug.tsx
This PR changes `sendEphemeralPost` to support an optional `userID` argument, to create the ephemeral post with a specific user.
Fixes https://mattermost.atlassian.net/browse/MM-31083
https://github.com/mattermost/mattermost-plugin-apps/pull/119
> Create app call response posts as bot

- components/apps_form/apps_form_field/apps_form_select_field.tsx
This PR adds the modifications to the ReactSelect component to have its options be fully visible in the Apps modal. These modifications are done in 3 other places in the webapp as well.
Fixes https://mattermost.atlassian.net/browse/MM-32188
Fixes https://mattermost.atlassian.net/browse/MM-32042
Before select option fix
After select option fix
Before error-spacing fix
After error-spacing fix
> [MM-32188] Fix Apps modal styling issues

- components/admin_console/admin_definition.jsx
- components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
OAuth is no longer being displayed on the System Console sidebar when it should be, even with System Admin. The wrong Config Group was being checked. This was added to handle a system role that did not contain that permission. This PR checks for the correct Groups and also checks the Setting for null.
https://mattermost.atlassian.net/browse/MM-34699
> MM-34699-fix oauth check in admin_definition

- e2e/cypress/integration/messaging/dm_list_of_users_spec.js
- Fixed clicking on search box
NA
> Cypress/E2E: Fix MM-T1665_1 Deactivated user is not shown in Direct Messages modal when no previous conversation

- components/channel_header/__snapshots__/channel_header.test.jsx.snap
- components/toast/__snapshots__/toast.test.tsx.snap
- components/toast/toast.test.tsx
- components/toast/toast.tsx
Migrates 'components/toast' and associated tests to TypeScript
Fixes [#17227](https://github.com/mattermost/mattermost-server/issues/17277)
JIRA ticket: [MM-34346](https://mattermost.atlassian.net/browse/MM-34346)
> [MM-34346] Migrate 'components/toast' and associated tests to TypeScript

- components/dot_menu/index.ts
This PR takes into account whether the selected post is a system message, and hides the bindings if this is the case.
The `DotMenu` component receives an empty array of bindings in this case. The `appsEnabled` prop has been removed from the `DotMenu` component. 0/5 on if we should still explicitly check in the child component for this boolean.
Fixes https://mattermost.atlassian.net/browse/MM-34094
> [MM-34094] Hide bindings for system messages

- components/admin_console/admin_definition.jsx
- components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
Accidently using `all` when it should be `any` which is why cors was showing up when it shouldn't have.
https://mattermost.atlassian.net/browse/MM-34663
> [MM-34663] System Console > Guest Access (Beta) - System User Manager role now sees Integrations > CORS

- e2e/generate_test_cycle.js
- e2e/package-lock.json
- e2e/package.json
- e2e/run_test_cycle.js
- e2e/run_tests.js
- e2e/save_report.js
- e2e/utils/dashboard.js
- e2e/utils/report.js
- Fix reporting and save environment details to dashboard (see latest test run in automation channel)
- Save environment details to dashboard (see attached screenshot)
Others:
- replace dashboard logic from old dashboard (using reportportal) to the new one.
none, getting `undefined` in daily Cypress run instead of the test environment data
> Cypress/E2E: Fix reporting and save environment details to dashboard

- e2e/cypress/integration/search_filter/after_spec.js
- e2e/cypress/integration/search_filter/before_spec.js
- e2e/cypress/integration/search_filter/edit_spec.js
- e2e/cypress/integration/search_filter/future_date_spec.js
- e2e/cypress/integration/search_filter/helpers.js
- e2e/cypress/integration/search_filter/input_spec.js
- e2e/cypress/integration/search_filter/invalid_spec.js
- e2e/cypress/integration/search_filter/mixed_spec.js
- e2e/cypress/integration/search_filter/negative_spec.js
- e2e/cypress/integration/search_filter/on_spec.js
Note: Submitted on top of https://github.com/mattermost/mattermost-webapp/pull/7893 for ease of review. See https://github.com/mattermost/mattermost-webapp/commit/727c194c99a021f2622cdadd9c7c383ebe64fd68 for related change on this PR.
Updated tests and keys of search date filters for the following test cases:
Invalid date
- MM-T602
Mixed
- MM-T589
- MM-T593
Negative filter
- MM-T607
- MM-T608
- MM-T609
- MM-T611
- MM-T3996
- MM-T610
Input
- MM-T585
- MM-T596
- MM-3997
- MM-T598
- MM-T601
> Cypress/E2E: Update tests and keys of search date filters (remaining)

- e2e/cypress/integration/search_filter/after_spec.js
- e2e/cypress/integration/search_filter/before_spec.js
- e2e/cypress/integration/search_filter/edit_spec.js
- e2e/cypress/integration/search_filter/future_date_spec.js
- e2e/cypress/integration/search_filter/helpers.js
- e2e/cypress/integration/search_filter/input_spec.js
- e2e/cypress/integration/search_filter/invalid_spec.js
- e2e/cypress/integration/search_filter/on_spec.js
Update tests and keys of search date filters for the following test cases:
`"on:"`
- MM-T588
- MM-T590
- MM-T3994
- MM-T604
`"after:"`
- MM-T587
- MM-T592
`"before:"`
- MM-T586
- MM-T591
Edited
- MM-T599
- MM-T595
Future date
- MM-T605
> Cypress/E2E: Update tests and keys of search date filters

- e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
- e2e/cypress/integration/auth_sso/authentication_2_spec.js
- e2e/cypress/integration/bot_accounts/bot_api_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
- e2e/cypress/integration/signin_authentication/authentication_spec.js
Add @mfa metadata to specs accordingly which will be used to sort specs to last and lessen/avoid potential cascading side-effects to succeeding tests whenever unrecoverable MFA setup occurred.
Such filter would be used like:
```
node generate_test_cycle.js --stage="@prod" --sortLast="@elasticsearch,@ldap,@saml,@keycloak,@mfa"
```
none, failing on daily
> Cypress/E2E: Add @mfa metadata to specs accordingly

- e2e/cypress/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js
- e2e/cypress/integration/integrations/incoming_webhook/setting_spec.js
- e2e/cypress/integration/integrations/incoming_webhook/slack_formatting_spec.js
- e2e/cypress/integration/messaging/message_reply_gm_spec.js
Fixing the incoming webhook and gm reply tests:
- Looks like the incoming webhook tests need forced clicks on the channel names.
- The gm reply test looks like is looking for the reply sooner than it's available.
> Prod test fixes

- e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
- e2e/cypress/integration/messaging/long_post_attachments_spec.js
- e2e/cypress/integration/messaging/message_edit_post_with_attachment_spec.js
Adding missing Zephyr keys to the following E2E tests:
- message_display_mode_spec.js
- long_post_attachments_spec.js
- message_edit_post_with_attachment_spec.js
> Adding missing Zephyr keys to existing E2E tests

- e2e/cypress/integration/account_settings/display/code_theme_colors_spec.js
- e2e/cypress/integration/enterprise/integrations/incoming_webhook_spec.js
- e2e/cypress/integration/enterprise/ldap_group/channel_modes_spec.js
- e2e/cypress/integration/enterprise/ldap_group/groups_assign_roles_spec.js
a. LDAP Groups
- changed the LDAP sync via API since LDAP config is already set
- created new Zephyr test cases - MM-T4003
- added existing test key - MM-T2668 
b. Code theme
- used `cy.uiClose()` to close the Account Settings
c. Incoming webhook
- failed due to timeout error during reindex. Add `@elasticsearch` metadata so it will test first where data is not yet huge.
none, failing on daily Cypress prod
> Cypress/E2E: Fix test on LDAP groups, code theme and incoming webhook

- e2e/cypress/integration/messaging/header_spec.js
- e2e/cypress/integration/onboarding/existing_email_adress_spec.js
- e2e/cypress/integration/onboarding/tutorial_navigation_and_links_spec.js
- e2e/cypress/integration/search/cleared_search_term_spec.js
- e2e/cypress/integration/search/post_search_display_spec.js
- e2e/cypress/integration/search/results_post_comment_spec.js
Next round of fixing missing Zephyr keys:
- `cleared_search_term_spec.js`: MM-T352 -- test was in `search` folder hence moved test from header_spec.js to this spec file. Also the test was already running in prod, hence added the `prod` tag
- `existing_email_adress_spec.js`: MM-T403
- `tutorial_navigation_and_links_spec.js`: MM-T401
- `post_search_display_spec.js`: MM-T353
- `results_post_comment_spec.js`: MM-T373
> Fixing keys in Cypress

- components/channel_header/__snapshots__/channel_header.test.jsx.snap
- components/channel_header/channel_header.js
- components/custom_status/custom_status.scss
- components/custom_status/custom_status_emoji.tsx
- components/custom_status/custom_status_modal.tsx
- components/legacy_sidebar/header/sidebar_header_dropdown_button.jsx
- components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
- components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
- components/post_view/post_header/post_header_custom_status.tsx
- components/profile_popover/profile_popover.jsx
- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
- components/suggestion/switch_channel_provider.jsx
- components/user_settings/notifications/user_settings_notifications.jsx
- i18n/en.json
- sass/components/_channel-switcher.scss
- sass/components/_suggestion-list.scss
- sass/layout/_headers.scss
Cherry-picking changes from the PRs #7932 and #7843 and resolving resulting conflicts.
- #7932
- #7843
> Mm 23120/picking conflicting changes

- components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
- components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
- components/widgets/users/avatars/avatars.test.tsx
- components/widgets/users/avatars/avatars.tsx
`Avatars` overflow tooltip should only display users represented by '+N'. This corrects a prior refactoring var-typo.
https://mattermost.atlassian.net/browse/MM-35021
> MM-35021: Only display overflow names in Avatars tooltip

- components/admin_console/system_roles/system_role/system_role.tsx
- packages/mattermost-redux/src/client/client4.ts
Summary
If I have a section permission that gives me ancillary permissions, I cannot remove an ancillary permission individually via MMCTL anymore. This PR aims to resolve this issue.
For example.
I have SYSCONSOLE_XXXX_WRITE which gives me manage_team permission, if I try to remove manage_team, it will always keep being re-added.
Ticket Link
https://mattermost.atlassian.net/browse/MM-34838
Server Changes: https://github.com/mattermost/mattermost-server/pull/17466
```release-note
NONE
```
> [MM-34838] Remove Ancillary Permissions That Are Purposefully Being Remove

- actions/hooks.js
- actions/hooks.test.js
When the Confluence plugin consumes a slash command for client-side processing (i.e. `/confluence subscribe`), it signals this by returning an empty object as per the required interface.
However, the webapp passes this empty object through all other registered slash command hooks. When the Confluence and Incident Collaboration plugins are installed (and Incident Collaboration "registers last"), Incident Collaboration receives this empty object and [mistakenly initializes](https://github.com/mattermost/mattermost-plugin-incident-collaboration/blob/98c01d6a3e76bfa48d9dd4860136d4f9a7dbde85/webapp/src/slash_command.ts#L9-L11) the `undefined` args parameter in testing whether it should process the slash command. The final result consumed by the webapp is now partially initialized, leading to a …
> MM-35074: short circuit slash command hooks

- e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
- e2e/cypress/integration/enterprise/cloud/onboarding/invite_member_by_email_spec.js
- e2e/cypress/integration/enterprise/cloud/onboarding/set_profile_and_team_spec.js
- updated onboarding process with the last change related to notification setup
- separated specs into 3 files since other tests require mocking to response. Also, it makes it easier for test maintenance and promotion.
- added `@cloud_only` metadata so it can be filtered for Cloud tests only.
failed on daily Cypress run
> Cypress/E2E: Fix cloud onboarding tests

- components/threading/global_threads/thread_item/thread_item.test.tsx
- components/threading/global_threads/thread_item/thread_item.tsx
- components/threading/global_threads/thread_menu/thread_menu.tsx
- components/threading/global_threads/thread_pane/thread_pane.test.tsx
- components/threading/global_threads/thread_pane/thread_pane.tsx
pass correct timestamp on 'mark as unread'
https://mattermost.atlassian.net/browse/MM-35127
https://github.com/mattermost/mattermost-server/pull/17507
```release-note
NONE
```
> MM-35127 CRT: Marking thread as unread doesn't set the timestamp correctly

- components/announcement_bar/configuration_bar/configuration_bar.tsx
- utils/license_utils.jsx
Cherry pick of #7917 on release-5.35.
```release-note
Fixed an issue with trial licenses where the banner end date did not match the trial card end date.
```
> Automated cherry pick of #7917

- e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
- e2e/cypress/integration/search/post_search_display_spec.js
- e2e/cypress/integration/toast/new_messages_toast_spec.js
- Fix `guest_identification_ui_spec`
- Fix `post_search_display_spec`
- Fix `new_messages_toast_spec`
NA
```release-note
NONE
```
> Cypress/E2E: Fix guest identification ui, post search display, new messages toast specs

- actions/apps.ts
- actions/command.test.js
- actions/command.ts
- actions/global_actions.tsx
- actions/post_actions.jsx
- components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
I'm adding some actions that call `sendEphemeralPost` in https://github.com/mattermost/mattermost-webapp/pull/7827, and I want to be able to have them `dispatch` the call to `sendEphemeralPost`. I'm making this a separate PR to be clear about this change.
> Make sendEphemeralPost into a proper action

- e2e/cypress/integration/widgets/badges_spec.js
- e2e/cypress/integration/widgets/popover_spec.js
Using `npm run cypress:run` at `mattermost-webapp/e2e` folder ended with error:
```
Error: Webpack Compilation Error
../packages/mattermost-redux/src/utils/user_utils.ts 202:107
Module parse failed: Unexpected token (202:107)
File was processed with these loaders:
* ../../../Library/Caches/Cypress/7.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
|         role !== constants_1.General.SYSTEM_USER_ROLE)) || (
|     // If user is a system admin or a system guest then ignore team and channel memberships
>     !isSystemRole && userIsNotAdminOrGuest && ((role === constants_1.General.TEAM_ADMIN_ROLE && membership?.scheme_admin) ||
|         (role === …
```
> move e2e specs to cypress directory

- packages/mattermost-redux/src/actions/posts.ts
pass missing collapsed threads param
https://mattermost.atlassian.net/browse/MM-35206
https://github.com/mattermost/mattermost-server/pull/17533
```release-note
NONE
```
> MM-35206 CRT: is_following on posts not reflecting state properly

- components/suggestion/switch_channel_provider.jsx
removes the URL "slug" information for GM's in the channel switcher
[MM-35085](https://mattermost.atlassian.net/browse/MM-35085)
|**before**|**after**|
|-----------|--------|
|<img width="619" alt="Screenshot 2021-04-28 at 16 45 55" src="https://user-images.githubusercontent.com/32863416/116423804-4c37d480-a841-11eb-93e3-856692c1346a.png">|<img width="620" alt="Screenshot 2021-04-28 at 16 43 20" src="https://user-images.githubusercontent.com/32863416/116423471-024eee80-a841-11eb-8bb6-c5a0bd09da72.png">|
```release-note
removes the URL "slug" information for GM's in the channel switcher
```
> remove URL slug for GMs in channel switcher

- components/search_results/search_results.tsx
Making search result type selector independent from the search result filter in the search box
[MM-34834](https://mattermost.atlassian.net/browse/MM-34834)
```release-note
NONE
```
> Making search result type selector independent from the search result filter in the search box

- components/generic_modal.scss
The `GenericModal` styles were being overridden by more specific styles used by existing modals. I've increased the specificity of the `GenericModal` styles so that they aren't overridden.
https://mattermost.atlassian.net/browse/MM-35062
```release-note
NONE
```
> [MM-35062] Increase specificity of GenericModal CSS to override existing styles

- components/sidebar/sidebar_category_header.tsx
- components/sidebar/unread_channel_indicator/__snapshots__/unread_channel_indicator.test.tsx.snap
- components/sidebar/unread_channel_indicator/unread_channel_indicator.scss
- components/sidebar/unread_channel_indicator/unread_channel_indicator.tsx
- e2e/cypress/integration/channel_sidebar/category_sorting_spec.js
- sass/layout/_sidebar-left.scss
As in #7708, this fixes the nesting issues in the sidebar that caused some warning spam and likely caused navigation issues for accessibility tools, but to do that, we had to give up sticky category headings on browsers that support it. Once the menu components are rewritten to change how the menus themselves are nested, sticky headings can be re-added, but we can't have both at once due to some weird browser-specific interactions between `position: sticky`, z-indices, and overflows.
https://mattermost.atlassian.net/browse/MM-33540
```release-note
Removed sticky sidebar headings in favor of fixing nesting errors
```
> MM-33540 Remove sticky headings from sidebar to fix nesting errors

- packages/mattermost-redux/src/constants/permissions.ts
I was contacted by QA that custom terms of service is always read-only state regardless of what you do.
Noticed a small typo in redux permissions.
https://mattermost.atlassian.net/browse/MM-35445
```release-note
Fixes bug where custom terms of service in system console is always in read-only state.
```
> [MM-35445] Fix Spelling Mistake for Custom Terms of Service

- components/rhs_card_header/index.tsx
- components/rhs_card_header/rhs_card_header.tsx
Migrated RhsCardHeader component to TypeScript
Fixes https://github.com/mattermost/mattermost-server/issues/17263
JIRA: https://mattermost.atlassian.net/browse/MM-34340
```release-note
NONE
```
> [MM-34340] Migrated RhsCardHeader component to TypeScript

- e2e/cypress/integration/files_and_attachments/image_link_preview_new_window_spec.js
- e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
- e2e/cypress/integration/files_and_attachments/upload_files_not_cloud_spec.js
- e2e/cypress/integration/files_and_attachments/upload_files_spec.js
- Updated image dimensions
- Changed test group from `file_and_attachments` to `files_and_attachments` for consistency with other spec files
https://mattermost.atlassian.net/browse/MM-34018
```release-note
NONE
```
> MM-34018 Cypress/E2E: Fix image link and previews

- e2e/utils/file.js
Currently on unstable tests for E20, excluding of tests related to Cloud (only) using `--exclude-group` flag didn't work as expected due to the order in which the exclusion of files happened before inverting.
```
node generate_test_cycle.js \
--stage="@prod"
--exclude-group="@te_only,@cloud_only,@high_availability" \
--sort-first="@compliance_export,@elasticsearch,@ldap_group,@ldap" \
--sort-last="@saml,@keycloak,@plugin,@mfa" \
--invert
```
This PR fixes the issue of properly excluding test files in combination with `--invert` where the exclusion is now done __after__ all filters, especially the invert.
With this change, we can now have an additional and proper unstable test run against Cloud server.
```release-note
NONE
```
> Cypress/E2E: Improve excluding test files

- e2e/cypress/integration/custom_status/custom_status_3_spec.js
Fixed custom status cases 
This small change fixed 5 test cases
```release-note
NONE
```
> Cypress/e2e:fixed custom status test case

- actions/post_actions.jsx
- components/dot_menu/dot_menu.tsx
- components/post_view/post/post.jsx
- components/post_view/post/post.test.js
- components/rhs_comment/rhs_comment.jsx
- components/rhs_comment/rhs_comment.test.jsx
- components/rhs_root_post/rhs_root_post.jsx
Via post dot-menu or alt/opt-click:
- Marking a post as unread **in a thread** should mark the **thread** as unread.
- Marking a post as unread **in a channel** should mark the **channel** as unread.
https://mattermost.atlassian.net/browse/MM-34909
```release-note
NONE
```
> MM-34909: Marking as unread from the post menu should mark the thread as unread

- components/admin_console/billing/billing_summary/billing_summary.tsx
- components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
Show the last day expiring trial messages in a consistent way so all of them specifies that the last trial day says "end today"
https://mattermost.atlassian.net/browse/MM-35319
```release-note
NONE
```
> MM-35319 - last day message inconsistencies

- components/emoji_picker/emoji_picker_overlay.jsx
A customer is experiencing slow typing issues. A JS profile showed the following:
A very significant amount of time is spent on "Recalculate Style" and the primary trigger for this seems to be the `getBoundingClientRect` function calls inside the EmojiPickerOverlay component. After some brief investigation it was apparent that on every single character typed into the textbox `getBoundingClientRect` was being called twice due to improper use of `getDerivedStateFromProps`. I have used memoization to properly implement the functionality in a much more performant way.
Unfortunately, I was unable to reproduce the exact slow typing issue the customer is experiencing so I'm not sure how much effect this will have or if this is the root cause of the issues or not. …
> MM-35509 Do not use getDerivedStateFromProps to determine picker placement and instead use memoization

- e2e/cypress/integration/archived_channel/archive_channel_add_reaction_spec.js
- e2e/cypress/integration/emoji/custom_emoji_1_spec.js
- e2e/cypress/integration/emoji/sorted_emojis_spec.js
- e2e/cypress/integration/messaging/emoji_insert_position_spec.js
- e2e/cypress/integration/messaging/message_reaction_gm_spec.js
- e2e/cypress/integration/messaging/message_reaction_spec.js
- e2e/cypress/integration/messaging/reactions_spec.js
> Cypress/E2E: Fix failed tests related to emoji picker

- e2e/cypress/integration/auth_sso/authentication_not_cloud_spec.js
Use `cy.uiSaveConfig` for it has guaranteed saving wait mechanism before doing verification.
failed on release test
```release-note
NONE
```
> Cypress/E2E: Fix flaky test on MM-T1776

- e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/helpers.js
- e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/with_email_login_spec.js
- e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/with_ldap_login_spec.js
- e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/with_saml_login_spec.js
Related PR - https://github.com/mattermost/mattermost-server/pull/17581
Test cases:
- [MM-T4045](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4045) - session via Email login
- [MM-T4046](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4046) - session via LDAP login
- [MM-T4047](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4047) - session via SAML login
Note:
- Separated into its own spec file since they require different auth mechanism and to …
> MM-35332 Cypress/E2E: Not extending session when setting is disabled

- components/edit_post_modal/index.js
In the context of threads there is no current channel, so it appeared as
the user never had permissions to edit owned post.
This commit fixes that by using **not** the current channel's id but the
editing post's channel id to get permissions.
https://mattermost.atlassian.net/browse/MM-35431
```release-note
NONE
```
> MM-35431: fixes save post disabled when opened from threads

- sass/components/_post.scss
File overlay covers center channel's input box.
[MM-35555](https://mattermost.atlassian.net/browse/MM-35555)
```release-note
input box is shadowed when uploading a file in center channel
```
> [MM-35555] file overlay should cover center channel input box

- components/admin_console/data_retention_settings/custom_policy_form/custom_policy_form.tsx
- components/admin_console/data_retention_settings/custom_policy_form/index.ts
- components/channel_selector_modal/__snapshots__/channel_selector_modal.test.tsx.snap
- components/channel_selector_modal/channel_selector_modal.test.tsx
- components/channel_selector_modal/channel_selector_modal.tsx
- utils/test_helper.ts
When selecting channels for a policy, you should only see channels that are not related to a team in the current policy
https://mattermost.atlassian.net/browse/MM-35310
```release-note
NONE
```
> [MM-35310] Only show channels not in a team attached to the current policy

- components/tutorial/index.tsx
- components/tutorial/menu_tutorial_tip.tsx
- components/tutorial/tutorial_tip/index.ts
- components/tutorial/tutorial_view.tsx
migrated tutorial to typescript. also found out that `index` of `tutorial_intro_screens` is not migrated to typescript. so i migrated that file too. 
Fixes https://github.com/mattermost/mattermost-server/issues/17274
```release-note
NONE
```
> migrate tutorial to typescript

- .gitlab-ci.yml
the main branch is failing on the internal gitlab
https://git.internal.mattermost.com/mattermost/ci-only/mattermost-webapp/-/jobs/62157
this fix the job, tested in my fork internally: https://git.internal.mattermost.com/cpanato/mattermost-webapp/-/jobs/62226
n/a
```release-note
NONE
```
> ci/gitlab: add ssh keys to be able to fetch the repositories

- components/threading/global_threads_link/global_threads_link.tsx
Fetches threads when toggling CRT on so bolding and mention count are immediately updated.
https://mattermost.atlassian.net/browse/MM-35432
```release-note
NONE
```
> MM-35432: fixes bolding/mention count on "Threads" LHS link when toggling CRT on

- components/search/search.tsx
When using the `Ctrl+Cmd+F` shortcut on the Mac desktop app to full screen, the search shortcut would take over as it didn't check for the `Ctrl` key on Mac.
This PR checks for the `Ctrl` key so that the shortcut doesn't interfere.
https://mattermost.atlassian.net/browse/MM-35595
```release-note
Fixed an issue where using `Ctrl+Cmd+F` on the Mac Desktop App opens the search instead of full-screens the app.
```
> [MM-35595] Stop the search shortcut from triggering full screen view on Mac

- components/threading/global_threads_link/global_threads_link.scss
- [MM-35237](https://mattermost.atlassian.net/browse/MM-35237): Fix prior css selector refactoring that negated keep-visible styling.
> MM-35237: CRT, Keep Threads mention badge on hover

- components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap
- components/post_view/message_attachments/message_attachment/message_attachment.test.tsx
- components/post_view/message_attachments/message_attachment/message_attachment.tsx
As far as I can tell, field values are the only thing in a message attachment that's allowed to be a string or a number, and we failed to check for that on the client before sending them into the Markdown component. I tried swapping other fields for numbers, but it seems like the server sanitizes those already even though I couldn't find exactly where that happens.
https://mattermost.atlassian.net/browse/MM-35689
```release-note
Fixed error caused by a post created with a non-string attachment field.
```
> MM-35689 Fix error caused by trying to render non-string attachment field

- package.json
CI tests are running out of memory: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/38725/workflows/5df25840-d23c-4df8-bd64-fd07f8a874ab/jobs/263776
This temporarily reduces the number of workers to the ones used in Gitlab.
--
```release-note
NONE
```
> Reduce number of workers in CI tests

- components/admin_console/admin_definition.jsx
Restrict domains for link previews should depend on the same permissions as enable link preview
[MM-35796](https://mattermost.atlassian.net/browse/MM-35796)
```release-note
Restrict domains for link previews depends on the same permissions as enable link preview
```
> [MM-35796] Use same constant to validate permissions

- e2e/cypress/integration/channel_settings/add_users_to_channel_spec.js
Update test case to show the status wrapper which is present on the profile picture in the users row within Add users to channel modal. 
https://mattermost.atlassian.net/browse/MM-35780
```release-note
NONE
```
> [MM-35780] - Update add users to channel modal test case

- components/admin_console/admin_definition.jsx
Cherry pick of #8141 
```release-note
Restrict domains for link previews depends on the same permissions as enable link preview
```
> [MM-35796] Use same constant to validate permissions (cherry-pick v5.35)

- .gitlab-ci.yml
- package.json
ci/test: add NODE_OPTIONS max_old_space_size=500
```release-note
NONE
```
> WIP ci/test: add NODE_OPTIONS max_old_space_size=500

- components/post_view/post_info/post_info.tsx
Removes comment count from post info component.
Justification: we show it in root post's thread footer.
https://mattermost.atlassian.net/browse/MM-35715
```release-note
NONE
```
> MM-35715: CRT removes comment count

- e2e/cypress/integration/scroll/image_aspect_ratio_spec.js
https://automation-test-cases.vercel.app/test/MM-T2369
N/A
N/A
```release-note
NONE
```
> MM-T2369 : Aspect Ratio is preserved in RHS

- components/custom_status/custom_status.scss
CSS rules got overruled, and messed the clear input icon's position in custom status modal.
https://mattermost.atlassian.net/browse/MM-35544
```release-note
NONE
```
> Fixes: position of clear custom status icon

- components/purchase_modal/purchase_modal.tsx
prevent  purchase modal Object.keys invocation with null value
https://mattermost.atlassian.net/browse/MM-36126
```
NONE
```
> MM-36126 - prevent  purchase modal Object.keys invocation with null value

- sass/layout/_headers.scss
vertically aligns text in the channel header trigger correctly. It is not cutting the lower parts of text when they are reaching down (as with the letters: `g`, `j`, `p`, `q` and `y`)
Fixes [MM-35446](https://mattermost.atlassian.net/browse/MM-35446)
| before | after |
|-------|-------|
|<img width="862" alt="Screenshot 2021-06-02 at 11 07 17" src="https://user-images.githubusercontent.com/32863416/120452780-bdaff900-c392-11eb-979e-98b4b33f4c9a.png">|<img width="862" alt="Screenshot 2021-06-02 at 11 07 27" src="https://user-images.githubusercontent.com/32863416/120452792-c1438000-c392-11eb-9f9f-6cd2fb2eecc9.png">|
```release-note
NONE
```
> added `align-items: center` and increased `line-height` on the `span`

- components/purchase_modal/purchase_modal.tsx
- utils/cloud_utils.ts
There was a situation where the purchase modal was trying to show the payment information in the case where the customer has not it set already, which leaded with a component showing empty strings separated by commas. This PR makes sure that when the customer has no payment information, the fill in payment method form is shown.
https://mattermost.atlassian.net/browse/MM-36172
```release-note
NONE
```
> MM-36172 - purchase modal empty address issue

- e2e/cypress/integration/system_console/site_configuration/customization_spec.js
Adds an E2E test to cover the behaviour of the 'Site Name' customization configuration option (and default value).
https://automation-test-cases.vercel.app/test/MM-T1282
```release-note
NONE
```
> [MM-T1282] Add e2e test coverage for default behaviour when an empty site name is configured

- components/profile_popover/profile_popover.jsx
MM-36035 - Removing status from bot posts
Removed the status icon if any of these conditions are met.
- It's a bot
- It's a webook
- It's from autoresponder
https://mattermost.atlassian.net/browse/MM-36035
```release-note
NONE
```
> MM-36035 - Removing status from bot posts

- e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js
https://automation-test-cases.vercel.app/test/MM-T3002
`#### Release Note
```release-note
NONE
```
> tests/CTRL+CMD+K : Unread Channels and input field focus

- components/user_settings/notifications/index.js
- components/user_settings/notifications/user_settings_notifications.jsx
- components/user_settings/notifications/user_settings_notifications.test.js
When CRT is on reply notifications user setting makes no sense as it is.
This commit hides that section.
Later on a setting about threads will be added on desktop notifications section.
https://mattermost.atlassian.net/browse/MM-35405
```release-note
NONE
```
> MM-35405: hides reply notifications user setting

- components/emoji_picker/emoji_picker_overlay.jsx
Add the `show` as an input to the memoized functions for determining emoji picker position.
@hmhealey I know you mentioned we had done this in other places differently but I couldn't find any good examples and this worked well enough. Feel free to point out a better way to do it though.
https://mattermost.atlassian.net/browse/MM-36166
```release-note
NONE
```
> MM-36166 Force recalculate emoji picker position on open

- packages/mattermost-redux/src/actions/admin.test.js
- packages/mattermost-redux/src/actions/admin.ts
- packages/mattermost-redux/src/client/client4.ts
- packages/mattermost-redux/src/reducers/entities/admin.test.js
- packages/mattermost-redux/src/reducers/entities/admin.ts
- packages/mattermost-redux/src/reducers/entities/channels.test.js
- packages/mattermost-redux/src/reducers/entities/teams.test.js
Redux tests for data retention
https://mattermost.atlassian.net/browse/MM-35653
```release-note
NONE
```
> [MM-35653] Data Retention redux tests

- plugins/export.js
In order to support Cloud in Incident Collaboration, we need to implement the upgrade flow triggered when users try to use a locked feature.
To keep the experience consistent, we are using the `PurchaseModal` component in two ways:
- When the user is interacting with the Messaging product (in an incident in a channel, for example), and the modal needs to be shown, we leverage the existing architecture by simply calling `openModal`, which pops up the already mounted component.
- When the user is in the backstage, there is no component already mounted, so we are mounting another one in our components hierarchy, and using the same `openModal` logic to show it.
This PR makes all this possible, exporting the needed elements so the plugins can use them; namely:
- The component itself, …
> Export PurchaseModal component and related utils

- components/sidebar/__snapshots__/sidebar.test.tsx.snap
- components/sidebar/sidebar.tsx
The new sidebar was not properly encapsulating the plugin buttons.
https://mattermost.atlassian.net/browse/MM-36199
None
None
```release-note
Fix bug with plugin icons showing as a column instead of as a row in the LHS.
```
> Fix plugin buttons on the LHS showing one below the other, instead of one after the other

- components/suggestion/at_mention_provider/at_mention_suggestion.jsx
The descriptions for Special Mentions in the autocomplete popup were not spaced correctly and were showing up with a higher opacity compared to other entries. This PR adds the same class used on the other entries to correct the spacing and opacity.
https://mattermost.atlassian.net/browse/MM-36173
```release-note
NONE
```
> [MM-36173] Fix spacing and opacity on descriptions for special mentions

- components/legacy_sidebar/header/dropdown/index.js
- components/legacy_sidebar/header/dropdown/sidebar_header_dropdown.jsx
Bug fix: Does not display the unread badge on sidebar hamburger menu when Enable Marketplace or Enable Plugins is disabled
https://mattermost.atlassian.net/browse/MM-36160
```release-note
NONE
```
> MM-36160 - Fix showing the red button in the sidebar hamburger menu when Enable Marketplace or Enable Plugins is disabled

- components/emoji/render_emoji.tsx
- sass/components/_emoticons.scss
Prevent links from displaying overflow lines when hovering over in chrome
[MM-36270](https://mattermost.atlassian.net/browse/MM-36270)
```release-note
Fix link hovering overflowing to next lines
```
> [MM-36270] Add overflow to emoji rendering

- components/__snapshots__/picture_selector.test.tsx.snap
- components/__snapshots__/setting_picture.test.jsx.snap
- components/admin_console/brand_image_setting/brand_image_setting.jsx
- components/emoji/add_emoji/__snapshots__/add_emoji.test.tsx.snap
- components/emoji/add_emoji/add_emoji.tsx
- components/integrations/bots/add_bot/add_bot.jsx
- components/picture_selector.tsx
- components/setting_picture.jsx
- utils/constants.jsx
Allow uploading JPEG files ending in `.jpeg` on Chromium on Linux (may also enable other platforms).
https://github.com/mattermost/mattermost-server/issues/17728
Before:
```release-note
Fixed ability to upload `.jpeg` files on Linux
```
> Allow uploading `.jpeg` files on Linux

- components/threading/channel_threads/thread_footer/thread_footer.test.tsx
- components/threading/channel_threads/thread_footer/thread_footer.tsx
Hides unread dot when thread is not followed. Primarily for immediate feedback. (Responding to WS events have a slight delay.)
A follow-up item/PR will add: 
- reacting to `SocketEvents.THREAD_FOLLOW_CHANGED` will zero-out any unread counts for the unfollowed thread. 
https://mattermost.atlassian.net/browse/MM-35804
```release-note
NONE
```
> MM-35804: hide unread indicator when not following thread

- actions/new_post.test.js
- actions/new_post.ts
- actions/post_actions.test.js
- packages/mattermost-redux/src/actions/channels.ts
One of the causes of slowdowns when receiving a post is that a lot of components re-render due to changes in `state.entities.channels.channels` (which happens whenever any channel changes). A lot of components depend on this object, particularly the sidebar.
Because of how the post receiving actions are written, we dispatch a few rounds of actions as we're updating various fields containing unread information. It's easier to see this when we add an artificial delay between the batches since you'll see the re-render flicker happen a few times as everything happens.
https://user-images.githubusercontent.com/3277310/121036766-ec581600-c77c-11eb-9071-d16045a921d1.mov
By making the code a bit clunkier, we remove an extra re-render and cut a fair bit of time off the render. …
> MM-35837 Improve batching of channel-related actions on post receipt

- actions/new_post.test.js
- actions/new_post.ts
- actions/post_actions.test.js
- packages/mattermost-redux/src/actions/channels.ts
5.35 version of https://github.com/mattermost/mattermost-webapp/pull/8222
There's a few more changes to `actions/post_actions.test.js` than in the original PR which include some changes to make the tests better that were already on master.
https://mattermost.atlassian.net/browse/MM-35837
https://github.com/mattermost/mattermost-webapp/pull/8222
```release-note
NONE
```
>  MM-35837 Improve batching of channel-related actions on post receipt (release-5.35)

- e2e/utils/test_cases.js
- Need to update the API base url for zephyr to `https://api.zephyrscale.smartbear.com/v2`
Please see announcement here:
https://app.getbeamer.com/zephyrscale/en/breaking-changes-on-the-rest-api
https://support.smartbear.com/zephyr-scale-cloud/api-docs/
Note: I'm only updating repo from MM org. I also see the soon-to-be-obsolete URL `https://api.adaptavist.io/tm4j/v2` on Saturn's codebase but I'll let him update those in his own time.
NA
```release-note
NONE
```
> Cypress/E2E: Update Zephyr Scale API URL

- components/call_button/call_button.tsx
- components/call_button/index.ts
migrated call_batton to typescript.
Fixes https://github.com/mattermost/mattermost-server/issues/17260
```release-note
NONE
```
> [MM-34331] Migrate 'components/call_button' and associated tests to TypeScript

- packages/mattermost-redux/src/reducers/entities/posts.ts
Companion PR to https://github.com/mattermost/mattermost-server/pull/17774 to appropriately handle 'is_following' not being set in responses to updated posts.
https://mattermost.atlassian.net/browse/MM-36257
- Has server changes (https://github.com/mattermost/mattermost-server/pull/17774)
```release-note
NONE
```
> MM-36257 Handle is_following not being set for edited posts

- packages/mattermost-redux/src/selectors/entities/posts.ts
Quick fix for CRT where unfollowed posts didn't have reply counts showing up in the center channel.
```release-note
NONE
```
> Use reply count from post if thread not tracked in postsInThread reducer

- actions/views/rhs.ts
- components/search/index.tsx
- components/search/search.tsx
- components/search/types.ts
- packages/mattermost-redux/src/selectors/entities/channels.ts
- packages/mattermost-redux/src/utils/channel_utils.ts
Due to some weirdness with the way we process channels, we don't have a consistent way of using one field to search for or label our channels. DM/GM channels are searched for commonly by the users inside them, and other channels are search in by name.
Since adding our little search shortcut, I used the `name` of the channel which worked for non DM/GM channels, but for DM/GM channels things were a little inconsistent. In order to make things consistency, and get around some of the weirdness in how we fill channels, I've added a new selector specifically to get the name used for search and am using that to fill in the name when using the `Cmd/Ctrl+Shift+F` shortcut so that its consistent with how the suggestion provider does it.
https://mattermost.atlassian.net/browse/MM-36074 …
> [MM-36704] Add selector specifically for search channel name to handle its cases

- packages/mattermost-redux/src/reducers/entities/posts.test.js
- packages/mattermost-redux/src/reducers/entities/posts.ts
- packages/mattermost-redux/src/utils/post_utils.test.js
- packages/mattermost-redux/src/utils/post_utils.ts
Toggling CRT 'on' wouldn't show participants at all for unfollowed
posts.
We short-circuit receiving posts in the reducers based on old/new
post's `update_at` property. Posts have some extra properties though
which didn't got updated in redux when toggling CRT on.
This commit refactors the short-circuit into a `shouldUpdatePost` utility function,
taking into account not only the `update_at` but the CRT posts' extra
properties.
https://mattermost.atlassian.net/browse/MM-35806
```release-note
NONE
```
> MM-35806: shows participants when turning CRT on

- actions/new_post.ts
- actions/post_actions.jsx
- actions/views/threads.ts
- actions/websocket_actions.jsx
- components/threading/global_threads/thread_menu/thread_menu.test.tsx
- components/threading/global_threads/thread_menu/thread_menu.tsx
- reducers/views/threads.ts
- selectors/views/threads.ts
- types/store/views.ts
- utils/constants.jsx
New messages that arrive while the thread is open are marked as read and
the indicators don't flash anymore.
Furthermore if a thread is manually marked as unread it should stay
unread even if new messages arrive while it's open.
https://mattermost.atlassian.net/browse/MM-36218
https://mattermost.atlassian.net/browse/MM-36219
```release-note
NONE
```
> MM-36218,MM-36219: CRT thread read flashes

- actions/views/create_comment.jsx
- components/create_comment/create_comment.jsx
- components/create_post/create_post.jsx
- components/suggestion/suggestion_box.jsx
The problems addressed are:
- Interactive dialogs and apps forms not getting the focus when executed from a slash command in the center channel. It did work on the RHS. Solved by moving the focus code before the command execution, so the interactive dialog can steal the focus when created.
- Crash when a command is executed by pressing the tab button to select the "Execute command" option on the RHS. Solved by applying the check on persist.
- Inconsistent updates on the draft of the RHS when submitting a command by hitting enter and therefore selecting the "Execute command" option. We just handle the word when it is not the case where the command is finished.
- Inconsistent updates on the draft when a command returned an error on the RHS. Solved by reapplying the draft on command errors. …
> Fix several autocomplete problems

- components/threading/thread_viewer/thread_viewer.tsx
The loader was shown in ThreadViewer upon websocket reconnection.
This commit fixes that, so the loader now shows only on mount and upon changing selected thread.
https://mattermost.atlassian.net/browse/MM-36561
```release-note
NONE
```
> MM-36561: fixes loader shown on socket reconnect

- actions/post_actions.jsx
It gets followed by the server but we just needed to set that state on the client too.
https://mattermost.atlassian.net/browse/MM-36430
```release-note
NONE
```
> MM-36430 Show thread as followed immediately on webapp when marking posts unread from the thread

- components/toast/__snapshots__/toast.test.tsx.snap
- components/toast/toast.tsx
- Use `IntlContext`-compatible OverlayTrigger
- Allows previously-hidden tooltip to work again 
- Hoist OverlayTrigger to wrap clickable element (synchronize tooltip with hover/clickable element)
https://mattermost.atlassian.net/browse/MM-30446
```release-note
NONE
```
> MM-30446: Fix toast dismiss hover console error

- selectors/plugins.ts
master is not passing the type-checker
TBD
#8139 
```release-note
NONE
```
> fix reselect signature

- components/sidebar_right/sidebar_right.jsx
- selectors/views/threads.test.ts
- selectors/views/threads.ts
Fixes a bug when suppressing RHS via going to global threads,
and then receiving new replies to the thread open in the suppressed RHS,
kept marking them as read.
This commit changes `getOpenThreadId` to consider if RHS is open or not.
Also mounts/unmounts components in the RHS with account to RHS hidden/visible,
this change was made because right now we can suppress the RHS and that action
does not clear the rhsState nor the selectedPostId etc..
https://mattermost.atlassian.net/browse/MM-36542
```release-note
NONE
```
> MM-36542: getOpenThreadId should consider suppressed RHS

- components/admin_console/billing/billing_summary/billing_summary.tsx
- components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
- i18n/en.json
- i18n/en_AU.json
- utils/utils.jsx
Show cloud trial banner last day notification date in user local date timezone.
https://mattermost.atlassian.net/browse/MM-35191
https://mattermost.atlassian.net/browse/MM-36328
```release-note
NONE
```
> MM-35191 - show banner in user timezone

- i18n/en.json
- utils/emoticons.test.tsx
- utils/emoticons.tsx
Thumbs up wasn't being skin toned properly, updated the regex to support that.
[MM-36481](https://mattermost.atlassian.net/browse/MM-36481)
- Server https://github.com/mattermost/mattermost-server/pull/17846
```release-note
NONE
```
> [MM-36481] Fix thumbsup emoji parsing to support skin tones

- components/rhs_comment/rhs_comment.jsx
- components/threading/thread_viewer/thread_viewer.tsx
It seemed that `componentDidUpdate` didn't have the `postRef` setted yet,
thus producing an error on scrolling to highlighted reply id.
This commit fixes it by:
1. Changing the `isInViewport` function signature to
always expect the element to exist.
2. Ensure `postRef` exists before scrolling into view.
https://mattermost.atlassian.net/browse/MM-36730
```release-note
NONE
```
> MM-36730: permalinks to replies sometimes throw

- components/suggestion/switch_channel_provider.jsx
Current channel doesn't exist when in global threads, so channel
switcher throws error.
This commit fixes that error.
https://mattermost.atlassian.net/browse/MM-36612
```release-note
NONE
```
> MM-36612: opening channel switcher while in threads throws

- actions/emoji_actions.js
- actions/local_storage.jsx
- components/emoji_picker/components/emoji_picker_skin.jsx
- components/emoji_picker/emoji_picker.jsx
- components/emoji_picker/emoji_picker.test.jsx
- components/emoji_picker/index.js
- reducers/views/emoji.js
- selectors/emojis.js
- stores/local_storage_store.jsx
- utils/constants.jsx
User skin tone selection was persisted to localstorage and we are switching that to the user preferences in the server.
[MM-36618](https://mattermost.atlassian.net/browse/MM-36618)
```release-note
NONE
```
> [MM-36618] Save skin tone to preferences

- sass/components/_announcement-bar.scss
This PR fixes styling of the announcement banner
[MM-36714](https://mattermost.atlassian.net/browse/MM-36714?atlOrigin=eyJpIjoiYTBmOGU3MTJlOTc0NDA4MGFjNzU5N2EwNWMxNDBjN2MiLCJwIjoiaiJ9)
```release-note
NONE
```
> [MM-36714] - Renew Now button in announcement bar lost its styling

- components/apps_form/apps_form_field/apps_form_field.tsx
- components/suggestion/command_provider/app_command_parser/app_command_parser.ts
- components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
- packages/mattermost-redux/src/constants/apps.ts
Add Markdown fields to app forms. Also piggybacks a fix to remove readonly fields from commands.
https://mattermost.atlassian.net/browse/MM-31052
https://mattermost.atlassian.net/browse/MM-36043
Mobile: https://github.com/mattermost/mattermost-mobile/pull/5407
Apps Framework: 
```release-note
Apps can now add arbitrary markdown in between fields on forms.
```
> Add Markdown fields to app forms

- components/threading/global_threads/global_threads.tsx
Clicking x unread threads in global threads was a no-op.
This commit changes that so the first unread thread and the
Unreads tab are selected.
https://mattermost.atlassian.net/browse/MM-35439
```release-note
NONE
```
> MM-35439: CRT, clicking x unread threads

- utils/utils.jsx
The Desktop App on Windows/Linux seems to have a bug where the browser thinks the window size is 0x0 when the app is loaded. This triggers `isMobile()` to return `true`, which focuses the search bar immediately when the app is loaded.
This PR makes sure the window size is >0 before we return `true` for `isMobile()`
https://mattermost.atlassian.net/browse/MM-35249
```release-note
NONE
```
> [MM-35249] Ensure window size is at least 0 before checking for mobile

- sass/layout/_sidebar-left.scss
Fix to text overflowing in "Find channel" bar. CSS properties for span added in sidebar class.
[JIRA Ticket MM-36355](https://mattermost.atlassian.net/browse/MM-36355)
[GitHub Issue #17763](https://github.com/mattermost/mattermost-server/issues/17763#event-4939754877) (Opened in server repo)
None
Text now is only in one line and uses ellipsis when truncation is necessary.
```release-note
NONE
```
> Fixed: overflowing text now truncates

- components/user_settings/general/user_settings_general.tsx
- i18n/en.json
In-product text update for: https://github.com/mattermost/mattermost-webapp/pull/8224
Updated profile picture upload text to clarify support for JPEG image files.
> Allow uploading .jpeg files on Linux

- components/suggestion/emoticon_provider.jsx
- packages/mattermost-redux/src/types/emojis.ts
- utils/emoticons.tsx
When the user starts typing an emoji, suggest only emojis that match the selected skin tone (if possible)
this doesn't fix the known issue about searching and switching the skin.
[MM-36809](https://mattermost.atlassian.net/browse/MM-36809)
```release-note
NONE
```
> [MM-36809] Suggest only skintones along user skin tone selection

- components/user_settings/display/user_settings_display.tsx
Tracks collapsed reply threads user setting change.
The category is `settings` the event is `user_settings_update` and the event props are:
```js
{
field: 'display.collapsed_reply_threads`,
value: 'on' || 'off'
}
```
https://mattermost.atlassian.net/browse/MM-36692
```release-note
NONE
```
> MM-36692: tracks CRT display setting on/off

- packages/mattermost-redux/src/client/client4.ts
This PR fixes the cloud subscribe api call by removing the duplicated "cloud" word in the URI path
https://mattermost.atlassian.net/browse/MM-36936
```release-note
NONE
```
> MM36936 - fix cloud subscribe api URI path

- components/suggestion/modal_suggestion_list.jsx
Fix a crash when adding a user to a channel from the user popover.
This was caused due to not checking whether the content was being returned or not.
https://mattermost.atlassian.net/browse/MM-36955
None
```release-note
None
```
> Check whether the list element is present or not before accessing the index

- i18n/en.json
Enhance UI text and fix grammar of System Console > Feature Flags page. Includes changing the word `server` to `instance`, which is the term used to refer to both Mattermost "servers" and Mattermost Cloud "workspaces"
N/A
N/A
NONE
> Adjust feature flag language in System Console

- components/apps_form/apps_form_field/apps_form_select_field.tsx
Static and Dynamic selects were not respecting the readonly parameter. Now they are.
None
```release-note
None
```
> Fix dynamic and static select not being readonly

- components/gif_picker/gif_picker.jsx
Changes Markdown inserted by GIF picker from
```markdown
https://thumbs.gfycat.com/LikableValidAlpineroadguidetigerbeetle-size_restricted.gif
```
to
```markdown
```
As per **Other notes** of [\[MM-12290\]](https://mattermost.atlassian.net/browse/MM-12290)
https://mattermost.atlassian.net/browse/MM-37074
```release-note
Improved default rendering of images inserted via the GIF picker.
```
> [MM-37074] Encapsulate inserted GIFs in inline image markdown

- components/timestamp/timestamp.tsx
- plugins/export.js
To allow for better number, plural, datetime, etc. message formatting in plugins: 
- Expose `<Timestamp>` for usage in plugins; potentially/ideally a stop-gap until Common Components
- Expose `react-intl` for usage in plugins alongside other existing globals (react, react-router-dom, redux, etc.)
- Prop-syntax improvement for `<Timestamp/>`, support `UnitDescriptor` as a valid relative unit for easier custom ranges 
E.g. Within `props.units`, the terser `['day', -30]` auto-expands to `{within: ['day', -30], display: ['day']}`
While this is stand alone, [MM-35696](https://mattermost.atlassian.net/browse/MM-35696) depends on this. Ref: https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/634
```release-note
Allow for `react-intl` and `<Timestamp/>` usage in plugins …
```
> [Re: MM-35696]: Expose Timestamp and ReactIntl for usage in plugins

- actions/websocket_actions.jsx
When the user posts a message in a thread, the server responds with a THREAD_UPDATED event. In the websocket handler for this event, the thread is immediately marked as read if that thread is open. 
Looking at the community server responses on my local machine - the `create_at` of user's post  was `1626446482669`. The webapp then sends a request to mark the thread as read with the timestamp `1626446482566` (`Date.Now()`)
The mark as read timestamp is before the `create_at` of the post created. **Could be this because of some clock skew?** I have updated the code to set the read time as just after the `create_at `of the post, if `Date.Now` is before the `create_at` time of the post.
- https://mattermost.atlassian.net/browse/MM-34895
- N/A
```release-note
NONE
```
> [MM-34895] send timestamp after last_reply_at when viewing thread

- packages/mattermost-redux/src/selectors/entities/integrations.test.js
This change doesn't fix any particular issue, nor does it add functionality, and I don't think it is required or important.  All it does is make sure that calls to `TestHelper.initBasic` and `TestHelper.tearDown` are balanced in the codebase; one teardown call was missing.
N/A
N/A
```release-note
NONE
```
> Add balancing call to TestHelper.tearDown() in mattermost-redux test

- actions/storage.js
- actions/views/create_comment.jsx
- components/create_comment/create_comment.jsx
- components/create_post/create_post.jsx
- components/create_post/index.js
This is a follow-up PR to #8396 that fixes an issue where drafts were sometimes not persisted after a refresh if the save draft timeout didn't have time to fire.
Unfortunately the really out of date version of redux-persist works in mysterious ways and doesn't store the drafts quick enough upon page unload so the drafts wouldn't be persisted. Instead I modified drafts to also temporarily be stored directly into localStorage and then added some manual rehydration of the drafts into redux on app load. It's not ideal since we're storing the drafts twice now but I feel like this is an "ok enough" solution until we do a proper re-visit to storage and drafts.
Follow-up to https://mattermost.atlassian.net/browse/MM-37048
- Has mobile changes (please link …
> MM-37048 Temporarily store drafts in localStorage and rehydrate manually to fix persistence issues

- e2e/package-lock.json
This PR fixes the ff issue when installing e2e dependencies:
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/[user]/go/src/github.com/mattermost/mattermost-webapp/e2e/node_modules/which/bin/which
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/[user]/go/src/github.com/mattermost/mattermost-webapp/e2e/node_modules/which/bin/which'
```
Channel discussion - https://community.mattermost.com/core/pl/myhhf8g4zbgfjpjpdd4dy41mxw
Note the dependencies were updated just recently - https://github.com/mattermost/mattermost-webapp/pull/8380  - and so no other dependency update was made here.
none
```release-note
NONE
```
> Cypress/E2E: Fix issue when installing e2e packages

- actions/views/create_comment.jsx
- components/create_post/create_post.jsx
Fix draft removal on create_comment and unload in create_post. Thanks @larkox for the catches.
```release-note
NONE
```
> Fix draft removal on create_comment and unload in create_post

- components/legacy_sidebar/header/dropdown/sidebar_header_dropdown.jsx
- components/main_menu/main_menu.jsx
- components/user_settings/modal/user_settings_modal.tsx
When using `CTRL/CMD+SHIFT+A` to open the Account Settings modal, on Chrome, the new 'Search Tabs' dropdown would also fire, interfering with our workflow. This PR stops the 'Search Tabs' dropdown from opening with the keyboard shortcut when Mattermost is active.
https://mattermost.atlassian.net/browse/MM-35552
```release-note
NONE
```
> [MM-35552] Prevent opening of Search Tabs on Chrome when using Account Settings modal keyboard shortcut

- plugins/export.js
This PR exports the `ChannelInviteModal` and the `ChannelMembersModal` components, so that we can pass the needed parameters to `openModal` from the new RHS in Incident Collaboration.
In short, this PR allows us to make the interactions with the participants section in the video work:
https://user-images.githubusercontent.com/3924815/126299946-1572ff16-6db5-43c9-aa94-5f49245a38a7.mp4
https://mattermost.atlassian.net/browse/MM-36854
```release-note
Exported ChannelInviteModal and ChannelMembersModal components for plugins 
```
> MM-36854: Export ChannelInviteModal and ChannelMembersModal for plugins to use

- components/generic_modal.scss
- components/product_notices_modal/product_notices_modal.scss
CSS of ``ProductNoticesModal`` was getting overridden because of recent changes intended to increase the CSS specificity of ``GenericModal`` CSS. These changes are increasing the css specificity of ProductNoticesModal.
[https://mattermost.atlassian.net/browse/MM-37189](https://mattermost.atlassian.net/browse/MM-37189)
- None
```release-note
fixes style issue with ProductNoticesModal
```
> [MM-37189] fix style issue in ProductNoticesModal

- components/admin_console/billing/billing_subscriptions/index.tsx
- i18n/en.json
Fixes a typo. Subscription title should be singular in the System Console billing page for cloud accounts.
https://mattermost.atlassian.net/browse/MM-30538
Title now reads "Subscription"
```release-note
Fixed System Console billing subscription title to be singular
```
> fix: Subscription title in system console billing is singular

- packages/mattermost-redux/src/actions/threads.ts
Fix console error when viewing channel on an unsupported CRT client while webapp is open with CRT on.
https://mattermost.atlassian.net/browse/MM-36573
```release-note
NONE
```
> MM-36573 Fix console error when viewing channel on an unsupported CRT client while webapp is open with CRT on

- components/threading/global_threads/global_threads.tsx
This PR adds the onboarding flow to the threads view inorder to ensure it can be toggled back on while in the threads view
[MM-37106](https://mattermost.atlassian.net/browse/MM-37106?atlOrigin=eyJpIjoiYWQ1YTZiY2I3ZDk1NGE2ZTk5M2JhMjRmNGY1Yzc0ZTYiLCJwIjoiaiJ9)
Depends on [https://github.com/mattermost/mattermost-webapp/pull/8437](https://github.com/mattermost/mattermost-webapp/pull/8437)
```release-note
NONE
```
> [MM-37106] - Can't return to Getting Started flow from Threads view

- components/threading/global_threads/thread_pane/thread_pane.scss
"Thread" h3 title in thread pane is displayed vertically in some languages (e.g: Japanese).
This commit fixes that by enlarging the column as much as needed so text
won't wrap.
https://mattermost.atlassian.net/browse/MM-36863
```release-note
NONE
```
> Fixes Thread in thread viewer displayed vertically

- actions/storage.js
- actions/views/create_comment.jsx
- actions/views/create_comment.test.jsx
- components/create_comment/create_comment.jsx
- components/create_comment/create_comment.test.jsx
- components/create_comment/index.js
- components/create_post/create_post.jsx
- components/create_post/index.js
Cherry picks the following fixes for slow typing performance issue related to drafts:
* https://github.com/mattermost/mattermost-webapp/pull/8396
* https://github.com/mattermost/mattermost-webapp/pull/8411
* https://github.com/mattermost/mattermost-webapp/pull/8428
```release-note
Improve typing performance in affected environments by reducing the frequency at which drafts are saved
```
> Cherry pick slow typing draft fixes to release-5.31

- components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
- components/channel_invite_modal/channel_invite_modal.tsx
- components/multiselect/multiselect.tsx
- e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
- e2e/cypress/integration/messaging/focus_move_spec.js
- e2e/cypress/integration/notifications/browser_tab_notification_spec.js
- sass/components/_channel-invite-modal.scss
- sass/components/_channel-switcher.scss
- sass/components/_module.scss
In January, we updated the styling of the Add Users to Channel modal to more closely match the Channel Switcher (#7172). These styles didn't take into account the fact that the modal existed in the System Console as well though, so in March, we fixed that but broke the styles of the dropdown and close button outside of the System Console (#7696). A couple weeks ago, we attempted to fix the appearance of the close button, but that entirely broke the styling of the modal in the System Console (#8366).
With all that said and done, I think I've fixed all the existing issues around that modal without reintroducing any other bugs. I also split up the CSS a bit better beetween the Add Users to Channel modal and Channel Switcher since they shared CSS in a way that was causing them to break each …
> MM-377220 Fix theming and stying of Add Users to Channel modals 

- components/next_steps_view/steps.ts
- components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx
- components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
- i18n/en.json
- i18n/en_AU.json
In this PR, we check if the stepPreferences are empty. If they're empty, we hide the onboarding process. We do this because, we know that existing users don't have those preferences set as the onboarding flow (where users get the opportunity to set them) didn't exist until now for self managed existing users.
All new users created from now on will have those preferences set to show for them, such that they can view the onboarding process the first time they log in or use the app.
[MM-37064](https://mattermost.atlassian.net/browse/MM-37064?atlOrigin=eyJpIjoiZDZkNTg3N2E3OGFiNGNiZjg5OWZhMjE1YTgxZGJmZDkiLCJwIjoiaiJ9)
- Has server changes [https://github.com/mattermost/mattermost-server/pull/17977](https://github.com/mattermost/mattermost-server/pull/17977)
```release-note
NONE
```
> [MM-37064] - Onboarding flow is showing for existing users

- components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
- components/threading/global_threads/thread_item/thread_item.tsx
ThreadItem > Timestamp: drop manual capitalization (that had been used for 'Now') to not alter built-in CLDR specifics.
See thread: https://community.mattermost.com/core/pl/a7n1ihmy57fnzruhb7rmr8mzqy
E.g. `de`:
```diff
- Vor 5 stunden
+ vor 5 Stunden
```
`en`: 
```diff
- Now
+ now
```
Re: 'Now' / 'now', Atlassian-Jira uses the latter ('now'), and in-fact seems to be leveraging `react-intl` as well.
```release-note
NONE
```
> fix: drop manual capitalization in global threads

- components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
- components/threading/global_threads/thread_item/thread_item.tsx
MarkdownImageExpanded needs onImageHeightChanged prop to be defined,
this commit adds that, but not using it, since we have fixed height for
thread items.
https://mattermost.atlassian.net/browse/MM-37079
expanded
collapsed
```release-note
NONE
```
> Fixes global threads crash on md images

- components/admin_console/license_settings/license_settings.jsx
Making the `getPrevTrialLicense()` request was causing a panic server side when in team edition. 
https://mattermost.atlassian.net/browse/MM-37108
```release-note
NONE
```
https://github.com/mattermost/mattermost-server/pull/17933
> [MM-37108] Only make request if server is enterprise ready

- components/sidebar_right/sidebar_right.jsx
- components/threading/thread_viewer/thread_viewer.tsx
This fix makes RHS hidden when closed.
When RHS is closed, it is currently still block-displayed. This overflows `#channel_view` (its `overflow: hidden` normally takes care of this) and causes odd scroll position issues in Safari. `channel_header` will slide up out-of-viewport, and there will be a blank space below `create_post`, with everything between shifted up.
Repro steps: 
- In Safari, open webapp and ensure Collapsed Reply Threads is Enabled
- Go to a channel with at least one thread with at least 1 reply
- Refresh
- Open any thread with at least 1 reply
- = Channel Header will disappear, and there will be space below the message input
Fixes https://mattermost.atlassian.net/browse/MM-37422
Otherwise, link the JIRA ticket.
-->
With `#channel_view {/* overflow: hidden */}` …
> MM-37422: Fix Safari overflow scrolling issue

- actions/new_post.ts
- With CRT on, posting a reply to a thread should NOT mark the channel containing the the thread as read
- This PR fixes the "new messages" line issue uncovered in the server PR
- https://mattermost.atlassian.net/browse/MM-37118
- Has server changes
https://github.com/mattermost/mattermost-server/pull/17965
```release-note
NONE
```
> [MM-37118] Don't mark channel as read for reply posts with CRT on

- components/post_view/post_time/post_time.tsx
When user post multiple message and delete in between message we show other user ``(message deleted)`` on hover timestamp is shown, which have position issue in case of deleted message, which this pr will fix.
[https://mattermost.atlassian.net/browse/MM-32187](https://mattermost.atlassian.net/browse/MM-32187)
None
```release-note
fixes timestamp position issue when user delete message
```
> [MM-32187]fix deleted message timestamp position issue

- components/root/root.jsx
Block only file drops, not all the kind of drops (from drag and drops).
This is done because react-dnd, used in focalboard, relies on the document drop event, and this was blocking all the cases.
This should help other plugins creator that wants to use react-dnd or any other dnd that follows the same pattern.
[MM-36964](https://mattermost.atlassian.net/browse/MM-36964)
```release-note
NONE
```
> Block only file drops, not all the kind of drops (from drag and drops)

- components/global/product_switcher.tsx
- Removes `target="_blank"` so switcher items open in the same tab on browser.
- Removes the icon for indicating the link opens in a new tab.
- Fixes the switcher so `/channels` is `/` corresponding to the change in plans around updating the routing for 6.0.
https://mattermost.atlassian.net/browse/MM-37457
```release-note
NONE
```
> MM-37457 Remove target blank and change routes to match new plan.

- e2e/cypress/integration/enterprise/system_console/settings_spec.js
- e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
- e2e/cypress/integration/enterprise/visual_regression/system_console/compliance_section_spec.js
- e2e/cypress/integration/system_console/feature_discovery_spec.js
- Removed old Data Retention Policy
- Archived [MM-T1161](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T1161)
`e2e/cypress/integration/enterprise/system_console/compliance/data_retention_policies_spec.js` already has the test cases for the new data retention policies.
Note: I'll let you guys decide when to merge this as I understand the custom data retention feature will be graduated soon.
NA
```release-note
NONE
```
> Cypress/E2E Maintenance: Remove old Data Retention Policy

- components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
- components/threading/global_threads/thread_list/thread_list.tsx
Allows users to click the "mark all as unread" button even if there are
no unread threads in the list. Currently the button is disabled unless
there are unread threads.
https://mattermost.atlassian.net/browse/MM-37495
```release-note
NONE
```
> MM-37495: CRT, always enable mark all as unread

- components/edit_post_modal/edit_post_modal.test.tsx
`parent_id` has been deprecated.
```release-note
NONE
```
> Fixes type issue
