components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap, components/sidebar/sidebar_category/sidebar_category.tsx, components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap, components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.test.tsx, components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx, components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap, components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx, components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap, components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx, components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx, components/sidebar/sidebar_menu/__snapshots__/sidebar_menu.test.tsx.snap, components/sidebar/sidebar_menu/sidebar_menu.test.tsx, components/sidebar/sidebar_menu/sidebar_menu.tsx, components/widgets/menu/menu.tsx, sass/layout/_sidebar-left.scss
Cherry pick of #6256 on release-5.27.
/cc  @hmhealey
=> Automated cherry pick of #6256

e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
- Updated alt text verification for avatar image
=> Cypress/E2E: Fix accessibility modals dialogs spec

components/user_settings/general/user_settings_general.jsx, utils/constants.jsx
Cherry pick of #6235 on release-5.27.
/cc  @hahmadia
=> Automated cherry pick of #6235

e2e/cypress/integration/channel/close_direct_group_spec.js, e2e/cypress/integration/multi_team_and_dm/favorite_and_close_spec.js
Automates MM-T474
https://mattermost.atlassian.net/browse/MM-27821
=> MM-27821: Cypress/E2E:  GMs and DMs > GM: Favorite, and close

root.html
Cherry pick of #6270 on release-5.27.
=> Automated cherry pick of #6270

e2e/cypress/integration/files_and_attachments/upload_files_spec.js
MM-T12 Loading indicator when posting images
[MM-T12](https://automation-test-cases.vercel.app/test/MM-T12)
=> MM-T12 Loading indicator when posting images

actions/views/group.js, components/at_mention/index.jsx, components/create_comment/index.js, components/create_post/index.js, components/post_markdown/index.js, components/post_markdown/index.test.js, components/suggestion/at_mention_provider/at_mention_provider.jsx, components/textbox/index.ts, components/textbox/textbox.tsx, package-lock.json, package.json
Manual cherry-pick of #6133
With redux updated to release-5.27 https://github.com/mattermost/mattermost-redux/commit/42a477837cdb1461b25dc30695a3ac3d951accca
=> [MM-27132] Get user group mention keys for channel (#6133)

e2e/cypress/integration/multi_team_and_dm/close_gm_via_menu_spec.js
Automation of MM-T1799
https://mattermost.atlassian.net/browse/MM-27830
=> MM-27830 - Cypress/E2E: DMs and GMs > Close Group Message from channel menu

.circleci/config.yml, build/Dockerfile
Upgraded docker image and pushed it. Need to still push latest tag, if this one works.
https://mattermost.atlassian.net/browse/DOPS-217
=> Upgrade build docker image

e2e/cypress/integration/integrations/incoming_webhook/incoming_webhook_is_image_only_spec.js
Incoming webhook is image only
[MM-T625](https://automation-test-cases.vercel.app/test/MM-T625)
mattermost/mattermost-server#15120
=> MM-T625 Incoming webhook is image only

e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
Image link preview - Bitly links for images and YouTube
[MM-T332](https://automation-test-cases.vercel.app/test/MM-T332)
mattermost/mattermost-server#15120
=> MM-T332 Image link preview - Bitly links for images and YouTube

e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
AddTM4J ID to common slash commands - MM-T573 and MM-T574
=> Cypress/E2E: AddTM4J ID to common slash commands

components/admin_console/admin_definition.jsx
Cherry Picks https://github.com/mattermost/mattermost-webapp/pull/6350 into 5.25
=> cherry pick change into 5.25

components/admin_console/admin_definition.jsx
Cherrypicks https://github.com/mattermost/mattermost-webapp/pull/6350 into 5.26
=> Cherrypick 28235 5.26

components/admin_console/admin_definition.jsx
Cherrypicks https://github.com/mattermost/mattermost-webapp/pull/6350 into 5.27
=> cherrypick into 5.27

e2e/cypress/integration/integrations/builtin_commands/user_status_spec.js
Jira ticket: https://mattermost.atlassian.net/browse/MM-28306
Add Cypress tests for:
- [MM-T670](https://automation-test-cases.vercel.app/test/MM-T670)
- [MM-T672](https://automation-test-cases.vercel.app/test/MM-T672)
- [MM-T674](https://automation-test-cases.vercel.app/test/MM-T674)
=> MM-28306 Cypress/E2E: For MM-T670, MM-T672 and MM-T674

components/admin_console/admin_definition.jsx, i18n/en.json, package-lock.json, package.json
Added Cloud Billing feature flag to System Console under Experimental Settings
https://mattermost.atlassian.net/browse/MM-28313
=> [MM-28313] Admin config - Cloud Billing feature flag

e2e/cypress/integration/notifications/reply_notifications_spec.js
- Automates MM-T554
- Adds a missed check for MM-T552
https://mattermost.atlassian.net/browse/MM-27815
=> [MM-27815] e2ecypress test automation of MM-T554

e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Fix TM4J IDs for customization spec
=> Cypress/E2E: Fix TM4J IDs for customization spec

e2e/cypress/integration/enterprise/system_console/team_scheme_permission_spec.js, e2e/cypress/support/api/index.js, e2e/cypress/support/api/scheme.d.ts, e2e/cypress/support/api/scheme.js, e2e/cypress/support/api_commands.js, e2e/cypress/support/index.d.ts
Move scheme API commands
Related tests:
=> Cypress/E2E: Move scheme API commands

components/suggestion/command_provider.jsx
Cherry pick of #6233 on release-5.27.
/cc  @iomodo
=> Automated cherry pick of #6233

e2e/cypress/integration/channel/channel_groups_spec.js
Fix failing E2E in channel groups spec.
=> Cypress/E2E: Fix channel groups

e2e/cypress/integration/enterprise/system_console/system_scheme_permission_spec.js
- Added timeout after visit
None -  both master and v5.27
=> Cypress/E2E: Fix system scheme permission spec

e2e/cypress/integration/messaging/emoji_to_markdown_spec.js, e2e/cypress/integration/messaging/message_reply_bot_post_spec.js
=> Cypress/E2E: fix on markdown and bot

e2e/cypress/fixtures/markdown/markdown_carriage_return_two_lines.html, e2e/cypress/fixtures/markdown/markdown_code_block.html, e2e/cypress/fixtures/markdown/markdown_not_autolink.html, e2e/cypress/fixtures/markdown/markdown_not_in_code_block.html
=> Cypress/E2E: fix markdown tests

e2e/cypress/integration/enterprise/system_console/system_scheme_permission_spec.js
Cherry pick of #6412 on release-5.27.
=> Automated cherry pick of #6412

components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap, components/edit_channel_header_modal/edit_channel_header_modal.jsx, components/edit_post_modal/index.js, components/post_markdown/index.js, components/post_markdown/post_markdown.jsx, components/post_markdown/post_markdown.test.jsx, components/textbox/textbox.tsx
Cherry pick of #6403 on release-5.27.
/cc  @fmunshi
=> Automated cherry pick of #6403

components/channel_view/channel_view.jsx, components/next_steps_view/next_steps_view.tsx, components/sidebar/__snapshots__/sidebar.test.tsx.snap, components/sidebar/sidebar.tsx
Cherry pick of #6407 on cloud-beta.
=> Automated cherry pick of #6407

webpack.config.js
Adds rudder keys and dataplane to NODE_ENV='production'. 
=> Add rudder keys to node env prod

components/next_steps_view/steps.ts, components/next_steps_view/steps/enable_notifications_step/__snapshots__/enable_notifications_step.test.tsx.snap, components/next_steps_view/steps/enable_notifications_step/enable_notifications_step.tsx, components/next_steps_view/steps/text_card_with_action/text_card_with_action.scss, components/next_steps_view/steps/text_card_with_action/text_card_with_action.tsx, i18n/en.json
=> Cherry picking #6378

actions/diagnostics_actions.jsx, components/next_steps_view/next_steps_tips.tsx, components/next_steps_view/next_steps_view.tsx, components/next_steps_view/step_helpers.ts, components/next_steps_view/steps.ts, components/next_steps_view/steps/complete_profile_step/__snapshots__/complete_profile_step.test.tsx.snap, components/next_steps_view/steps/complete_profile_step/complete_profile_step.test.tsx, components/next_steps_view/steps/complete_profile_step/complete_profile_step.tsx, components/next_steps_view/steps/enable_notifications_step/enable_notifications_step.test.tsx, components/next_steps_view/steps/enable_notifications_step/enable_notifications_step.tsx, components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx, components/next_steps_view/steps/invite_members_step/invite_members_step.tsx, components/next_steps_view/steps/setup_preferences_step/__snapshots__/setup_preferences_step.test.tsx.snap, components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.test.tsx, components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.tsx, components/next_steps_view/steps/team_profile_step/__snapshots__/team_profile_step.test.tsx.snap, components/next_steps_view/steps/team_profile_step/team_profile_step.test.tsx, components/next_steps_view/steps/team_profile_step/team_profile_step.tsx, components/picture_selector.tsx, components/sidebar/sidebar_next_steps/index.ts, components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx, package-lock.json, package.json
=> [MM-27864][MM-27865] Telemetry for Cloud Onboarding (#6406)

e2e/cypress/integration/accessibility/accessibility_buttons_spec.js, e2e/cypress/integration/accessibility/accessibility_post_spec.js, e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js, e2e/cypress/integration/messaging/focus_move_spec.js, e2e/cypress/integration/messaging/post_header_spec.js, e2e/cypress/integration/messaging/post_pre_header_spec.js, e2e/cypress/integration/search/mobile_search_spec.js, e2e/cypress/integration/websocket/handle_removed_user/helpers.js, e2e/cypress/integration/websocket/handle_removed_user/new_sidebar_spec.js, e2e/cypress/integration/websocket/handle_removed_user/old_sidebar_spec.js, e2e/cypress/support/ui_commands.js
Update all tests references from flag to save.
Note: I didn't update application code related to flag 'cause it's a big task. Will update in the future once team owner (webapp/platform) updates those.
Jira ticket: https://mattermost.atlassian.net/browse/MM-28403
=> MM-28403 Cypress/E2E: Update all tests references from flag to save

components/invitation_modal/index.js, components/invitation_modal/invitation_modal.jsx, components/invitation_modal/invitation_modal.test.jsx, components/invitation_modal/invitation_modal_members_step/index.ts, components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx, components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.test.jsx
Cloud Telemetry for Invite Members modal
https://mattermost.atlassian.net/browse/MM-28061
=> [MM-28061] Cloud Telemetry for Invite Members modal

e2e/cypress/integration/websocket/channel_created/new_sidebar_spec.js
Fix failing E2E test in new sidebar
=> Cypress/E2E: Fix e2e new sidebar

components/invitation_modal/index.js, components/invitation_modal/invitation_modal.jsx, components/invitation_modal/invitation_modal.test.jsx, components/invitation_modal/invitation_modal_members_step/index.ts, components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx, components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.test.jsx
Cherry-pick of #6424 to `cloud-beta`
=> [MM-28061] Cloud Telemetry for Invite Members modal (#6424) - CHERRY-PICK

e2e/cypress/integration/messaging/at_mentions_user_spec.js, e2e/cypress/integration/messaging/autocomplete_with_space_spec.js
Add step and match test for MM-T1662
Test case: https://automation-test-cases.vercel.app/test/MM-T1662
=> Cypress/E2E: Add step and match test for MM-T1662

e2e/cypress/integration/accessibility/accessibility_buttons_spec.js, e2e/cypress/integration/cloud/onboarding/cloud_sysadmin_onboarding_spec.js, e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js, e2e/cypress/integration/files_and_attachments/upload_files_spec.js, e2e/cypress/integration/integrations/builtin_commands/user_status_spec.js, e2e/cypress/integration/integrations/incoming_webhook/disallow_username_profile_override_spec.js, e2e/cypress/integration/messaging/system_message_limited_options_spec.js, e2e/cypress/integration/onboarding/tutorial_navigation_and_links_spec.js
Demoting some of the prod tests that have been consistently failing in the last one week to unstable, with the idea that I'll take a look at them this week and promote back to prod if they pass by the end of this week.
=> Demote from prod to unstable

e2e/cypress/integration/enterprise/ldap_group/invite_bot_spec.js, e2e/cypress/support/api/bots.d.ts, e2e/cypress/support/api/bots.js, e2e/cypress/support/api/index.js, e2e/cypress/support/api_commands.js
Move bots API cypress command
none
=> Cypress/E2E: Move bots API cypress command

e2e/cypress/integration/channel_sidebar/category_collapsing_unread_filter_spec.js, e2e/cypress/integration/channel_sidebar/drag_and_drop_spec.js, e2e/cypress/integration/channel_sidebar/hotkeys_spec.js, e2e/cypress/integration/messaging/message_reaction_gm_spec.js, e2e/cypress/integration/multi_team_and_dm/gm_header_spec.js, e2e/cypress/support/api_commands.d.ts
Fix remnants of old custom api commands, using the recent changes at https://github.com/mattermost/mattermost-webapp/pull/6441 and https://github.com/mattermost/mattermost-webapp/pull/6440
=> Cypress/E2E: Fix cypress api commands

components/about_build_modal/__snapshots__/about_build_modal.test.jsx.snap, components/about_build_modal/about_build_modal.test.jsx
Tests were failing on the cloud-beta branch after a cherry-pick (not sure why). Regenerating this snapshot fixes it.
=> Fix tests on cloud-beta branch

e2e/cypress/integration/system_console/site_configuration/customization_spec.js
Add T1030: Custom branding removed - Default site name and description, and brand image and text - false
https://mattermost.atlassian.net/browse/MM-28140
=> [MM-28140] e2e/system_console/customization: add T1030

plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap, plugins/channel_header_plug/channel_header_plug.jsx
Cherry pick of #6438 on release-5.28.
/cc  @cpoile
=> Automated cherry pick of #6438

e2e/cypress/integration/multi_team_and_dm/existing_channel_name_spec.js
Fix test and match with MM-T422
Test case - https://automation-test-cases.vercel.app/test/MM-T422
=> Cypress/E2E: Fix test and match with MM-T422

e2e/cypress/integration/multi_team_and_dm/existing_channel_name_spec.js
Cherry pick of #6469 on release-5.28.
=> Automated cherry pick of #6469

components/__snapshots__/textbox.test.tsx.snap, components/suggestion/command_provider.jsx, components/suggestion/command_provider.test.js, components/textbox.test.tsx, components/textbox/textbox.tsx
Cherry pick of #6460 on release-5.28.
=> Automated cherry pick of #6460

e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js, e2e/cypress/integration/enterprise/system_console/system_scheme_permission_spec.js, e2e/cypress/integration/enterprise/system_console/team_guest_channel_spec.js, e2e/cypress/integration/enterprise/system_console/team_scheme_permission_spec.js, e2e/cypress/integration/system_console/feature_discovery_spec.js
Cherry pick of #6498 on release-5.28.
/cc  @prapti
=> Automated cherry pick of #6498

e2e/cypress/integration/messaging/pinned_posts_spec.js
Add MM-T2167 - Pin a post, view pinned posts.
https://mattermost.atlassian.net/browse/MM-28262
=> [MM-28262] e2e/messaging: add T2167

e2e/cypress/integration/modals/product_notice_spec.js
Commenting out e2e tests till we have a repo to server notices for e2e tetsts or mock the response.
https://mattermost.atlassian.net/browse/MM-28891
=> MM-28891 Comment out in product notices e2e test

e2e/cypress/integration/modals/product_notice_spec.js
Cherry pick of #6509 on release-5.28.
=> Automated cherry pick of #6509

e2e/cypress/integration/archived_channel/join_archived_channel_spec.js
Cherry pick of #6468 on release-5.28.
/cc  @hmhealey
=> Automated cherry pick of #6468

components/channel_view/channel_view.jsx, components/channel_view/channel_view.test.jsx, components/channel_view/index.js, components/main_menu/index.jsx, components/main_menu/main_menu.jsx, components/next_steps_view/next_steps_view.test.tsx, components/next_steps_view/next_steps_view.tsx, components/next_steps_view/steps.test.tsx, components/next_steps_view/steps.ts, components/sidebar/sidebar_next_steps/index.ts, components/sidebar/sidebar_next_steps/sidebar_next_steps.scss, components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx, i18n/en.json, utils/constants.jsx
=> Cherry picking #6497

e2e/cypress/fixtures/partial_default_config.json
Cherry pick of #6512 on release-5.28.
=> Automated cherry pick of #6512

e2e/cypress/integration/messaging/pinned_posts_spec.js, e2e/cypress/support/ui_commands.js
Add the remaining tests for the ticket :)
[MM-T2168](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2168)
[MM-T2169](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2169)
[MM-T2170](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2170)
[MM-T2171](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2171) …
=> [MM-28262] e2e/messaging: add T2168, T2169, T2170, T2171 and T2172

components/plugin_marketplace/marketplace_modal.js, components/plugin_marketplace/marketplace_modal.test.js
Cherry pick of #6428 on release-5.28.
/cc  @hanzei
=> Automated cherry pick of #6428

components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap, components/link_tooltip/link_tooltip.tsx
Cherry pick of #6492 on release-5.28.
/cc  @hanzei
=> Automated cherry pick of #6492

components/widgets/inputs/channels_input.scss, components/widgets/inputs/users_emails_input.scss
Cherry pick of #6415 on release-5.28.
/cc  @hahmadia
=> Automated cherry pick of #6415

e2e/cypress/integration/archived_channel/join_archived_channel_spec.js
This is based on #6468, so the changes specific to it can be viewed here: https://github.com/mattermost/mattermost-webapp/compare/MM-27208_MM-T1682...MM-27208_MM-T1683.
https://mattermost.atlassian.net/browse/MM-27208
https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1683
=> MM-27208 MM-T1683 Add unit test for joining a public channel via a link

utils/markdown/index.test.js, utils/markdown/renderer.tsx
Cherry pick of #6476 on release-5.28.
=> Automated cherry pick of #6476

e2e/cypress/integration/messaging/long_draft_spec.js
Cherry pick of #6525 on release-5.28.
/cc  @prapti
=> Automated cherry pick of #6525

components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap, components/product_notices_modal/product_notices_modal.tsx
Cherry pick of #6524 on release-5.28.
=> Automated cherry pick of #6524

components/admin_console/admin_definition.jsx, components/user_settings/sidebar/index.ts, i18n/en.json, package-lock.json, package.json
=> [MM-28972] Added 'Always On' option for new sidebar (#6530) - Cherry-pick

components/sidebar/sidebar_next_steps/remove_next_steps_modal.scss
=> [MM-28878] Revert style change to remove next steps arrow (#6527) - Cherry-pick

e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js, e2e/cypress/integration/mark_as_unread/mark_gm_as_unread_spec.js
Cherry pick of #6534 on release-5.28.
/cc  @srkgupta
=> Automated cherry pick of #6534

components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.jsx.snap, components/add_groups_to_channel_modal/add_groups_to_channel_modal.jsx, components/add_groups_to_team_modal/__snapshots__/add_groups_to_team_modal.test.jsx.snap, components/add_groups_to_team_modal/add_groups_to_team_modal.jsx, components/add_users_to_team_modal/__snapshots__/add_users_to_team_modal.test.tsx.snap, components/add_users_to_team_modal/add_users_to_team_modal.tsx, components/channel_invite_modal/__snapshots__/channel_invite_modal.test.jsx.snap, components/channel_invite_modal/channel_invite_modal.jsx, components/channel_selector_modal/__snapshots__/channel_selector_modal.test.jsx.snap, components/channel_selector_modal/channel_selector_modal.jsx, components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap, components/more_direct_channels/group_message_option.test.jsx, components/more_direct_channels/group_message_option.tsx, components/more_direct_channels/more_direct_channels.tsx, components/multiselect/multiselect.tsx, components/multiselect/multiselect_list.test.tsx, components/multiselect/multiselect_list.tsx, components/team_selector_modal/__snapshots__/team_selector_modal.test.jsx.snap, components/team_selector_modal/team_selector_modal.jsx
Cherry pick of #6286 on release-5.28.
=> Automated cherry pick of #6286

e2e/cypress/integration/system_console/user_management/users_spec.js, e2e/cypress/support/api/user.js
PR implements the following test cases:
- [MM-T932](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T932)
- [MM-T933](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T933)
- [MM-T934](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T934)
- [MM-T935](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T935)
- …
=> [MM-28151] Cypress/E2E: Automate backlogs - System Console > User Password

utils/text_formatting.test.jsx, utils/text_formatting.tsx
Cherry pick of #6495 on release-5.28.
/cc  @kaakaa
=> Automated cherry pick of #6495

NOTICE.txt
Cherry pick of #6550 on release-5.28.
/cc  @amyblais
=> Automated cherry pick of #6550

components/create_post/create_post.test.jsx, components/edit_channel_header_modal/edit_channel_header_modal.test.jsx, components/setting_upload.jsx, components/warn_metric_ack_modal/warn_metric_ack_modal.test.tsx
Trivial change. I also removed some unused mocks while I was in there.
https://mattermost.atlassian.net/browse/MM-29028
=> MM-29028 Remove findDOMNode from Slack import

e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js, e2e/cypress/support/external_commands.d.ts, e2e/cypress/support/external_commands.js
Cherry pick of #6563 on release-5.28.
=> Automated cherry pick of #6563

components/post_markdown/index.js, components/post_markdown/post_markdown.jsx, components/textbox/textbox.tsx, package-lock.json
Cherry pick of #6475 on release-5.28.
/cc  @cpoile
=> Automated cherry pick of #6475

components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap, components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap, components/admin_console/license_settings/license_settings.jsx, i18n/en.json, sass/routes/_admin-console.scss
Cherry pick of #6470 on release-5.28.
/cc  @jespino
=> Automated cherry pick of #6470

e2e/cypress/integration/accessibility/accessibility_post_spec.js, e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
- Fix MM-T1462 accessibility for incoming message
- Add fix to MM-T3161 channel sidebar
none, failing on daily Cypress run.
=> Cypress/E2E: Fix MM-T1462 accessibility for incoming message

e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
Fix MM-T1467 for more modal dialog accessibility
=> Cypress/E2E: Fix MM-T1467 for more modal dialog accessibility

e2e/cypress/integration/archived_channel/post_menu_spec.js
Add e2e tests for archive channel post menu options
https://mattermost.atlassian.net/browse/MM-28413
=> MM-24813 Add e2e tests for archive post menu options

e2e/cypress/integration/add_user_to_channel_from_profile_popover/profile_popover_spec.js
=> Cypress/E2E: Stabilize profile popover spec

e2e/cypress/integration/bot_accounts/managing_bot_accounts_spec.js
- Added timeouts after visits
- Fixed failures for Enable and Disable bots test cases
=> Cypress/E2E: Fix managing bot accounts spec

utils/markdown/index.test.js, utils/markdown/renderer.tsx
Cherry pick of #6616 on release-5.28.
=> Automated cherry pick of #6616

e2e/cypress/integration/emoji/recently_used_emoji_spec.js, e2e/cypress/integration/messaging/emoji_to_markdown_spec.js
- Add delays to stabilize async updates
NA - master and release v5.28
=> Cypress/E2E: Stabilize emoji specs

e2e/cypress/integration/emoji/recently_used_emoji_spec.js, e2e/cypress/integration/messaging/emoji_to_markdown_spec.js
Cherry pick of #6657 on release-5.28.
=> Automated cherry pick of #6657

e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js, e2e/cypress/integration/integrations/builtin_commands/invite_command_spec.js
- Fixed delay on invite command spec
- demote group mentions spec - I'm getting a different error locally; demoting for now and investigate later
NA - master only
=> Cypress/E2E: Fix invite command spec; demote group mentions spec

sass/components/_files.scss, sass/components/_mentions.scss, sass/components/_post-menu.scss, sass/components/_post-right.scss, sass/components/_post.scss, sass/layout/_markdown.scss, sass/responsive/_mobile.scss
Fixes https://github.com/mattermost/mattermost-server/issues/15779
=> MM-29038 Removed usage of centre-channel-color from post comments

sass/components/_buttons.scss, sass/components/_emoticons.scss, sass/components/_popover.scss
Switched center-channel-color-## with center-channel-color-rgb variables
Fixes: https://github.com/mattermost/mattermost-server/issues/15776
=> [GH-15776]Switch center-channel-color-## with center-channel-color-rgb variables

sass/components/_no-results-indicator.scss, sass/components/_react-select.scss, sass/components/_search.scss, sass/components/_suggestion-list.scss
Switched center-channel-color-## with center-channel-color-rgb variables 
Fixes: https://github.com/mattermost/mattermost-server/issues/15777
=> [GH-15777] Replace center-channel-color-## with center-channel-color-rgb variables

e2e/cypress/integration/channel/channel_switcher_spec.js
- Made sure newly created channels are sorted to top; pulled up channel prefix name/displayName
NA
=> Cypress/E2E: Fix channel switcher spec

components/search_results/search_results.jsx
change this.refs into React.createRef
Fixes https://github.com/mattermost/mattermost-server/issues/15619
https://github.com/mattermost/mattermost-webapp/pull/5753
=> migrate string-refs in search_results.jsx

e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js, e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
- Update text for quick switch hint
NA - master only
=> Cypress/E2E: Update quick switch hint

sass/components/_modal.scss, utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 546
Closes https://github.com/mattermost/mattermost-server/issues/15867
=> [GH-15867] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 546

sass/layout/_legacy-sidebar-left.scss, utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 516
Fixes https://github.com/mattermost/mattermost-server/issues/15831
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29392
=> [MM-29392] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 516 (#15831)

e2e/cypress/integration/system_console/main_menu_spec.js
- Remove obsolete checks and added new one
NA - master only
=> Cypress/E2E: Fix main menu spec

components/announcement_bar/cloud_announcement_bar/index.ts, components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx, components/main_menu/index.jsx, components/main_menu/main_menu.jsx
Cherry pick of #6705 on cloud-ga.
=> Automated cherry pick of #6705

sass/components/_post.scss, utils/utils.jsx
Remove usage of mention-highlight-bg-## CSS variables
Fixes https://github.com/mattermost/mattermost-server/issues/15781
JIRA: https://mattermost.atlassian.net/browse/MM-29035
=> [MM-29035] Remove usage of mention-highlight-bg-## CSS variables

components/admin_console/billing/billing_history.tsx, components/admin_console/billing/company_info.tsx, components/admin_console/billing/company_info_display.tsx
Preparing Billing section in System Console for Soft GA, commenting out features that will be completed for GA:
- Billing history grid
- Billing Admins section 
- Add/Edit Company information
=> Cloud Billing polish Soft GA

components/admin_console/billing/billing_history.tsx, components/admin_console/billing/company_info.tsx, components/admin_console/billing/company_info_display.tsx
Cherry pick of #6740 on cloud-ga.
=> Automated cherry pick of #6740

sass/components/_scrollbar.scss, utils/utils.jsx
Replace Javascript variable `theme.centerChannelBg` with CSS variable
`--center-channel-bg` for `scrollbar-track-color`.
Fixes https://github.com/mattermost/mattermost-server/issues/15895
=> [GH-15896] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 636

sass/routes/_settings.scss, utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 513
Fixes https://github.com/mattermost/mattermost-server/issues/15830
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29391
=> [MM-29391] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 513 (#15830)

sass/layout/_team-sidebar.scss, utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 520
Fixes https://github.com/mattermost/mattermost-server/issues/15833
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29394
=> [MM-29394] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 520 (#15833)

components/admin_console/billing/company_info_display.tsx
Cherry pick of #6764 on cloud-ga.
=> Automated cherry pick of #6764

components/admin_console/billing/billing_history.tsx, components/admin_console/billing/billing_subscriptions.scss, components/admin_console/billing/billing_subscriptions.tsx, components/admin_console/billing/billing_summary.tsx, components/admin_console/billing/company_info.tsx, components/admin_console/billing/company_info_display.tsx, components/admin_console/billing/payment_info.tsx, components/admin_console/billing/payment_info_display.tsx, components/admin_console/billing/payment_info_edit.tsx, components/admin_console/billing/plan_details.tsx, i18n/en.json
Cherry pick of #6762 on cloud-ga.
=> Automated cherry pick of #6762

components/admin_console/billing/billing_subscriptions.tsx
Cherry pick of #6766 on cloud-ga.
=> Automated cherry pick of #6766

sass/layout/_navigation.scss, utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx in 560.
Fixes: https://github.com/mattermost/mattermost-server/issues/15872
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29461
=> [MM-29461] Migrate changeCSS() to CSS variable in utils/utils.jsx in 560.

sass/components/_emoticons.scss, utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx in 550.
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29459
Fixes: https://github.com/mattermost/mattermost-server/issues/15870
=> [MM-29459] Migrate changeCSS() to CSS variable in utils/utils.jsx in 550.

components/user_settings/display/user_settings_theme/user_settings_theme.jsx, sass/components/_multi-select.scss, sass/components/_scrollbar.scss, utils/utils.jsx
Migrate changeCSS(sideText) to CSS variable --sidebartext in utils/utils.jsx
Fixes https://github.com/mattermost/mattermost-server/issues/15828
Fixes https://github.com/mattermost/mattermost-server/issues/15829
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29389
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29390
=> Migrate changeCSS(sideText) to CSS variable --sidebartext in utils/utils.jsx

components/admin_console/billing/company_info_display.tsx
Cherry pick of #6777 on cloud-ga.
=> Automated cherry pick of #6777

components/admin_console/billing/billing_subscriptions.tsx, components/admin_console/billing/payment_info_display.tsx
Cherry pick of #6780 on cloud-ga.
=> Automated cherry pick of #6780

components/invitation_modal/invitation_modal_members_step/index.ts, components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx, components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.test.jsx
Cherry pick of #6778 on cloud-ga.
=> Automated cherry pick of #6778

components/admin_console/billing/billing_subscriptions.tsx
Cherry pick of #6779 on cloud-ga.
=> Automated cherry pick of #6779

components/admin_console/billing/payment_info_edit.tsx
Cherry pick of #6787 on cloud-ga.
=> Automated cherry pick of #6787

components/admin_console/billing/plan_details.scss, components/admin_console/billing/plan_details.tsx, i18n/en.json
Cherry pick of #6789 on cloud-ga.
=> Automated cherry pick of #6789

components/admin_console/admin_console.test.tsx, components/admin_console/admin_console.tsx, components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/admin_sidebar.jsx, components/admin_console/admin_sidebar/index.js, components/admin_console/index.ts
* Hides payment screen for free tier
Fixes https://mattermost.atlassian.net/browse/MM-29670
=> MM-29670 - Hide payment screen in system Console if in free tier

components/admin_console/admin_console.test.tsx, components/admin_console/admin_console.tsx, components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/admin_sidebar.jsx, components/admin_console/admin_sidebar/index.js, components/admin_console/index.ts
Cherry pick of #6797 on cloud-ga.
=> Automated cherry pick of #6797

e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js, e2e/cypress/integration/menus/main_menu_spec.js, e2e/cypress/integration/messaging/local_date_time_spec.js
- Added TM4J to some test cases I touched way before so they can be reported properly
NA
=> Cypress/E2E: Add missing TM4J IDs

sass/layout/_team-button.scss, utils/utils.jsx
This PR removes usage of changeCSS() function to change the border-color of team-btn element.
Fixes https://github.com/mattermost/mattermost-server/issues/15873
=> [GH-15873] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 562

e2e/cypress/integration/system_console/about/edition_and_license_spec.js, e2e/cypress/integration/system_console/main_menu_spec.js, e2e/cypress/integration/system_console/reporting/site_statistics_spec.js, e2e/cypress/integration/system_console/search_box_spec.js
- Moved apiRequireLicense only to tests that require it (feedback from https://github.com/mattermost/mattermost-webapp/pull/6610)
- Fixed issues with site statistics
NA
=> Cypress/E2E: Fix require license on some system console specs

components/purchase_modal/purchase_modal.tsx
Cherry pick of #6819 on cloud-ga.
=> Automated cherry pick of #6819

actions/websocket_actions.jsx, utils/constants.jsx
Cherry pick of #6817 on cloud-ga.
=> Automated cherry pick of #6817

actions/websocket_actions.jsx, utils/constants.jsx
Cherry pick of #6818 on cloud-ga.
=> Automated cherry pick of #6818

components/main_menu/index.jsx, components/main_menu/main_menu.jsx
Cherry pick of #6792 on cloud-ga.
=> Automated cherry pick of #6792

package-lock.json, package.json
Updated redux hash to latest commit needed for rudder page events fix here https://github.com/mattermost/mattermost-redux/pull/1264
mattermost.atlassian.net/browse/MM-29799
https://github.com/mattermost/mattermost-redux/pull/1264
=> Updated redux hash to latest

package-lock.json, package.json
Cherry pick of #6851 on cloud-ga.
=> Automated cherry pick of #6851

components/widgets/badges/badges_spec.js, e2e/cypress/plugins/db_request.js, e2e/cypress/support/api/system.js, e2e/cypress/support/db_commands.js, e2e/cypress/support/task_commands.js
Improve Cypress log and add tips on error to easily understand the problem or required items, and to provide guidance on how to fix:
- database error
- license check
- URL health check
Not related but added fix to badges_spec.js while fixing error on Storybook URL.
none
Meaningful DB error:
Meaningful EE License error:
Better log on successful EE License check:
Meaningful URL health check error:
Better log on successful URL health check:
=> Cypress/E2E: Improve Cypress log and error message

utils/post_utils.jsx, utils/post_utils.test.jsx
Cherry pick of #6450 on release-5.29.
=> Automated cherry pick of #6450

components/toast_wrapper/toast_wrapper.jsx, components/toast_wrapper/toast_wrapper.test.jsx
Cherry pick of #5828 on release-5.29.
/cc  @sridhar02
=> Automated cherry pick of #5828

components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.js.snap, components/plugin_marketplace/marketplace_item/marketplace_item.js
Cherry pick of #6520 on release-5.29.
/cc  @hanzei
=> Automated cherry pick of #6520

components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx
Cherry pick of #6578 on release-5.29.
/cc  @hanzei
=> Automated cherry pick of #6578

e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js, e2e/cypress/integration/team_settings/closed_team_invite_with_non_mattermost_domain_spec.js, e2e/cypress/integration/team_settings/closed_team_invite_with_specific_domain_spec.js, e2e/cypress/integration/team_settings/helpers.js
- Fixed tests that fail due to vagueness on license; simplified by making sure license is removed and verified accordingly since they are not enterprise tests
NA
=> Cypress/E2E: Fix specs failing on team license welcome tutorial

components/widgets/inputs/users_emails_input.jsx, components/widgets/inputs/users_emails_input.test.jsx
Email addresses are automatically detected when onBlur happens. 
https://mattermost.atlassian.net/browse/MM-28563
=> [MM-28563] Email addresses are not auto-detected on invites

components/widgets/inputs/users_emails_input.jsx, components/widgets/inputs/users_emails_input.test.jsx
Cherry pick of #6863 on release-5.29.
/cc  @hahmadia
=> Automated cherry pick of #6863

sass/components/_modal.scss, utils/utils.jsx
Signed-off-by: Baibhab Debnath <debnathbaibhab@gmail.com>
Migrate call to changeCSS() for .app__body .modal-tabs .nav-tabs > li > a
Github Issue:- Fixes https://github.com/mattermost/mattermost-server/issues/15897
JIRA ticket:- https://mattermost.atlassian.net/browse/MM-29510
=> [MM-29510] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 641

components/admin_console/billing/company_info_edit.tsx
Cherry pick of #6875 on cloud-ga.
=> Automated cherry pick of #6875

components/admin_console/billing/billing_history.tsx, i18n/en.json, package-lock.json, package.json
Cherry pick of #6879 on cloud-ga.
=> Automated cherry pick of #6879

components/admin_console/billing/company_info_edit.tsx
Cherry pick of #6890 on cloud-ga.
=> Automated cherry pick of #6890

components/create_post/create_post.jsx
fix js error when editing a message.
[MM-29922](https://mattermost.atlassian.net/browse/MM-29922)
=> [MM-29922] fix typo

sass/layout/_sidebar-left.scss
Cherry pick of #6876 on release-5.29.
/cc  @hmhealey
=> Automated cherry pick of #6876

e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
- Simplified and refactored change role function
- Fixed test id used
NA
=> Cypress/E2E: Fix team and channel assign roles spec

components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
Cherry pick of #6888 on cloud-ga.
=> Automated cherry pick of #6888

e2e/cypress/integration/messaging/emoji_insert_position_spec.js
- Works for me locally but failure on cypress suggests it might need force:true on click
NA
=> Cypress/E2E: Potential fix for emoji insert position spec

components/audio_video_preview.jsx, components/view_image/view_image.jsx
change this.refs into React.createRef
Fixes https://github.com/mattermost/mattermost-server/issues/15799
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29310
#5753
=> [MM-29310] Migrate string-refs to functional ones: this.refs.video 

components/rhs_comment/index.js, components/rhs_comment/rhs_comment.jsx, components/rhs_comment/rhs_comment.test.jsx
Cherry pick of #6828 on release-5.29.
/cc  @marcelo-cardozo
=> Automated cherry pick of #6828

components/next_steps_view/steps/invite_members_step/index.ts, components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx, components/next_steps_view/steps/invite_members_step/invite_members_step.tsx, i18n/en.json
Cherry pick of #6903 on cloud-ga.
=> Automated cherry pick of #6903

components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap, components/post_view/message_attachments/message_attachment/index.js, components/post_view/message_attachments/message_attachment/message_attachment.jsx
Cherry pick of #6628 on release-5.29.
/cc  @jufab
=> Automated cherry pick of #6628

e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js, e2e/cypress/integration/enterprise/saml/saml_metadata_spec.js
Fixed couple of failing cypress tests based on daily E2E runs. 
NA
=> Fixed couple of failing cypress tests

components/sidebar/sidebar_category_header.tsx, sass/layout/_sidebar-left.scss
Cherry pick of #6907 on release-5.29.
/cc  @hmhealey
=> Automated cherry pick of #6907

components/admin_console/__snapshots__/color_setting.test.tsx.snap, components/admin_console/admin_definition.jsx, components/admin_console/color_setting.test.tsx, components/admin_console/color_setting.tsx, components/color_input.tsx
Cherry pick of #6861 on release-5.29.
/cc  @hahmadia
=> Automated cherry pick of #6861

e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js, e2e/cypress/integration/enterprise/saml/saml_metadata_spec.js
Cherry pick of #6936 on release-5.29.
/cc  @srkgupta
=> Automated cherry pick of #6936

e2e/cypress/integration/messaging/system_message_spec.js, e2e/cypress/integration/multi_team_and_dm/gm_header_spec.js, e2e/cypress/support/api/user.js
Updated cypress tests based on latest changes in webapp
N/A
=> Updated cypress tests based on latest changes in webapp

NOTICE.txt
Cherry pick of #6925 on release-5.29.
/cc  @amyblais
=> Automated cherry pick of #6925

components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_moderation.test.tsx.snap, components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx, i18n/en.json
Moves channel moderation out of beta.
https://mattermost.atlassian.net/browse/MM-30047
=> MM-30047: Channel moderation out of beta

components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_moderation.test.tsx.snap, components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx, i18n/en.json
Cherry pick of #6951 on release-5.29.
/cc  @mkraft
=> Automated cherry pick of #6951

selectors/views/channel_sidebar.test.js, selectors/views/channel_sidebar.ts
Cherry pick of #6956 on release-5.29.
/cc  @hmhealey
=> Automated cherry pick of #6956

e2e/utils/test_cases.js
Force retries (until CI timeout) when test executions failed on internal server error
Jira ticket - https://mattermost.atlassian.net/browse/MM-30139
=> MM-30139 Cypress/E2E: Force retry when test executions failed on internal server error

e2e/utils/test_cases.js
Cherry pick of #6967 on release-5.29.
=> Automated cherry pick of #6967

components/admin_console/billing/billing_summary.tsx
Cherry pick of #7001 on cloud-ga.
=> Automated cherry pick of #7001

components/admin_console/billing/billing_history.tsx, components/admin_console/billing/billing_summary.tsx
Cherry pick of #7000 on cloud-ga.
=> Automated cherry pick of #7000

components/admin_console/billing/billing_history.scss, components/admin_console/billing/billing_history.tsx
Cherry pick of #7012 on cloud-ga.
=> Automated cherry pick of #7012

e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
- Used `findByText` to access menu item
NA
=> Cypress/E2E: Fix custom categories spec

components/view_image/view_image.jsx
=> [MM-30216] - Add check for undefined fileInfos

components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap, components/rhs_thread/rhs_thread.tsx
Having the check for current user caused weird scrolling behaviour in RHS when another user is replying to the thread. The comment box would disappear out of sight. Removing the check seems to work for both cases.
https://mattermost.atlassian.net/browse/MM-29903
=> [MM-29903] - Check if current user is on last post when scrolling in rhs

components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
Fixing title text in select team icon.
https://mattermost.atlassian.net/browse/MM-30258
=> MM-30258 Fixing title text in select team icon.

components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
Cherry pick of #7023 on release-5.29.
=> Automated cherry pick of #7023

sass/components/_buttons.scss, utils/utils.jsx
Migrate a CSS variable for button from `utils/utils.jsx` into `sass/components/_buttons.scss`
Fixes https://github.com/mattermost/mattermost-server/issues/16176
=> [MM-30172] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 706

components/toast_wrapper/toast_wrapper.jsx, components/toast_wrapper/toast_wrapper.test.jsx
Cherry pick of #7028 on release-5.29.
=> Automated cherry pick of #7028

components/create_comment/create_comment.jsx, components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap, components/rhs_thread/rhs_thread.tsx
This is a recent regression from https://github.com/mattermost/mattermost-webapp/pull/6920
https://mattermost.atlassian.net/browse/MM-30340
Fix 5.29
=> [MM-30340] Update post height when comment box height change occurs

components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap, components/rhs_thread/rhs_thread.tsx
Cherry pick of #7061 on release-5.29.
=> Automated cherry pick of #7061

sass/layout/_headers.scss, utils/utils.jsx
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 702 #16173
Fixes https://github.com/mattermost/mattermost-server/issues/16173
=> Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 702 #16173

e2e/cypress/integration/integrations/integrations_spec.js, e2e/cypress/integration/plugins/marketplace/marketplace_spec.js, e2e/cypress/support/ui/announcement_bar.d.ts, e2e/cypress/support/ui/announcement_bar.js, e2e/cypress/support/ui/index.js
Fix failing tests due to announcement bar
none, failing on daily E2E run
=> Cypress/E2E: Fix failing tests due to announcement bar

components/dot_menu/dot_menu.tsx
Fix alignment when no icon is provided in post actions
None
None
=> Fix alignment when no icon is provided in post actions

i18n/en.json
Super admin to System admin
https://mattermost.atlassian.net/browse/MM-30586
=> [MM-30586] Change super to system

e2e/cypress/integration/mark_as_unread/toast_appears_unread_spec.js
Cherry pick of #7081 on release-5.29.
=> Automated cherry pick of #7081

i18n/en.json
Cherry pick of #7076 on cloud.
/cc  @hahmadia
=> Automated cherry pick of #7076

actions/apps.ts, actions/channel_actions.jsx, client/websocket_client.tsx, components/apps_modal/__snapshots__/dialog_introduction_text.test.tsx.snap, components/apps_modal/apps_modal.tsx, components/apps_modal/dialog_element/dialog_element.test.tsx, components/apps_modal/dialog_element/dialog_element.tsx, components/apps_modal/dialog_element/index.ts, components/apps_modal/dialog_introduction_text.test.tsx, components/apps_modal/dialog_introduction_text.tsx, components/apps_modal/index.ts, components/apps_modal/interactive_dialog.test.tsx, components/apps_modal/interactive_dialog.tsx, components/dot_menu/dot_menu.test.tsx, components/dot_menu/dot_menu.tsx, components/dot_menu/dot_menu_empty.test.tsx, components/dot_menu/dot_menu_mobile.test.tsx, components/dot_menu/index.ts, components/interactive_dialog/index.js, components/spinner_button.tsx, components/textbox/textbox.tsx, components/widgets/settings/text_setting.tsx, package-lock.json, package.json, plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap, plugins/channel_header_plug/channel_header_plug.tsx, plugins/channel_header_plug/index.ts, stores/browser_store.tsx, utils/constants.jsx
Fixed to work with https://github.com/mattermost/mattermost-plugin-apps/pull/32
=> Fixed to work with backend changes

components/single_image_view/__snapshots__/single_image_view.test.tsx.snap, components/single_image_view/single_image_view.test.tsx, components/single_image_view/single_image_view.tsx, components/view_image/view_image.jsx
* The toggle function requires id and not post
* This was most likely changed to fix a ts error
https://mattermost.atlassian.net/browse/MM-30590
=> [MM-20465][MM-30590] Fix for collapse/expand of image preview

actions/new_post.ts, components/data_prefetch/data_prefetch.test.tsx, components/data_prefetch/data_prefetch.tsx, components/data_prefetch/index.ts, components/needs_team/index.ts, components/needs_team/needs_team.tsx, components/new_channel_flow/index.ts, components/sidebar/index.ts, components/sidebar/sidebar_channel/index.ts, components/sidebar/sidebar_channel/sidebar_channel_icon/index.ts, components/sidebar/sidebar_channel/sidebar_direct_channel/index.ts, components/sidebar/sidebar_channel/sidebar_group_channel/index.ts, components/sidebar/sidebar_channel_list/index.ts, components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx, components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx, components/team_members_dropdown/index.ts, selectors/views/channel_sidebar.ts
Cherry pick of #7064 on cloud.
/cc  @hmhealey
=> Automated cherry pick of #7064

components/admin_console/billing/payment_info.tsx, utils/cloud_utils.ts
Cherry pick of #7101 on cloud.
=> Automated cherry pick of #7101

e2e/cypress/integration/channel/archived_channels_2_spec.js, e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js, e2e/cypress/support/client.js
The test for MM-T1684 is an existing unit test with the test number attached, and the steps for MM-T1688 seem to be incorrect, so I adapted them for how I expected the test to work. I'd update those steps myself, but I don't know if the changes I make are saved for future runs of the test.
https://mattermost.atlassian.net/browse/MM-27208
=> MM-27208 Add tests for MM-T1684, MM-T1687, and MM-T1688

components/admin_console/team_channel_settings/channel/details/channel_details.tsx, components/admin_console/team_channel_settings/channel/details/channel_groups.tsx, components/admin_console/team_channel_settings/channel/details/channel_modes.tsx, components/admin_console/team_channel_settings/channel/details/index.ts
Migrate a file that was omitted during Typescript migration of `components/admin_console/team_channel_settings/channel/details` module. 
Ticket (closed) was https://github.com/mattermost/mattermost-server/issues/13491
=> [MM-20581] Migrate index to TS in 'components/admin_console/team_channel_settings/channel/details' module

e2e/cypress/support/api/team.js, e2e/cypress/support/api/user.js, e2e/cypress/support/api/webhooks.js, e2e/cypress/support/api_commands.js, e2e/cypress/support/client.js, e2e/cypress/support/db_commands.js, e2e/cypress/support/okta_commands.js, e2e/cypress/support/task_commands.js
Fix return of Cypress custom commands
none, per feedback at https://community.mattermost.com/core/pl/5ftqtfdppfrbxmypjfjmqjg85e
=> Cypress/E2E: Fix return of Cypress custom commands

components/admin_console/admin_definition.jsx
Cherry pick of #7103 on release-5.30.
/cc  @jfrerich
=> Automated cherry pick of #7103

e2e/cypress/integration/archived_channel/archive_channel_addReaction_spec.js
- Added missing tm4j key for MM-T1720
Note: MM-T1719 was a dupe
https://mattermost.atlassian.net/browse/MM-28412
=> MM-28412: Add tm4j key

sass/components/_modal.scss
Cherry pick of #7155 on cloud.
/cc  @hmhealey
=> Automated cherry pick of #7155

NOTICE.txt
Cherry pick of #7102 on release-5.30.
/cc  @amyblais
=> Automated cherry pick of #7102

components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.js.snap, components/plugin_marketplace/marketplace_item/marketplace_item.js, components/plugin_marketplace/marketplace_item/marketplace_item.test.js
Cherry pick of #7133 on release-5.30.
/cc  @hanzei
=> Automated cherry pick of #7133

utils/constants.jsx
Updated "How Billing Works" link that was moved to: https://docs.mattermost.com/cloud/cloud-billing/cloud-billing.html
https://mattermost.atlassian.net/browse/MM-31115
=> MM-31115 - Fixed "how billing works" cloud link

utils/constants.jsx
Cherry pick of #7183 on cloud.
=> Automated cherry pick of #7183

package-lock.json, package.json
revert mattermost-redux PR https://github.com/mattermost/mattermost-redux/pull/1300 to allow dms showing in daily
Jira Ticket: [MM-31197](https://mattermost.atlassian.net/browse/MM-31197)
Redux:
- https://github.com/mattermost/mattermost-redux/pull/1315
- https://github.com/mattermost/mattermost-redux/pull/1300
=> [MM-27927] - Revert mattermost-redux

e2e/cypress/integration/notifications/desktop_notifications_spec.js
Automates MM-T490 as shown in https://mattermost.atlassian.net/browse/MM-30381
https://mattermost.atlassian.net/browse/MM-30381
implements:[T490](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T490)
⚠️ This PR is branched off another base branch ⚠️
=> MM-30381/cypress notifications teammate name MM-T490

components/legacy_sidebar/sidebar.jsx, components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx, components/sidebar/sidebar_menu/sidebar_menu.tsx
Cherry-picking https://github.com/mattermost/mattermost-webapp/pull/7207 onto the release branch.
All the stuff around clearing the multi-select was removed since that wasn't in 5.30.
https://mattermost.atlassian.net/browse/MM-31275
https://github.com/mattermost/mattermost-webapp/pull/7207
=> MM-31275 New sidebar performance improvements (#7207)

components/apps_modal/apps_modal.tsx
=> Add text subtypes

components/create_comment/create_comment.jsx, components/create_comment/create_comment.test.jsx, components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts, components/sidebar/sidebar_channel_list/index.ts, components/textbox/index.ts, selectors/views/channel_sidebar.ts
release-5.30 cherry-pick of the linked PR
https://github.com/mattermost/mattermost-webapp/pull/7242
=> MM-31466 Performance investigation part two (release-5.30)

actions/views/channel_sidebar.ts, components/create_comment/create_comment.jsx, components/create_comment/create_comment.test.jsx, components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts, components/sidebar/sidebar_channel_list/index.ts, components/textbox/index.ts, selectors/views/channel_sidebar.ts
cloud cherry-pick of the linked PR
https://github.com/mattermost/mattermost-webapp/pull/7242
=> MM-31466 Performance investigation part two (cloud)

e2e/cypress/integration/archived_channel/archive_channel_search_spec.js, e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js, e2e/cypress/integration/archived_channel/helpers.js, e2e/cypress/support/ui/channel.js
Some more tests regarding searching archived channels
[MM-27210](https://mattermost.atlassian.net/browse/MM-27210)
https://github.com/mattermost/mattermost-webapp/pull/7191
=> [MM-27210] archived channels 4 II

e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js, e2e/cypress/integration/channel/channel_routing_spec.js, e2e/cypress/integration/channel_settings/more_unreads_position_with_scroll_spec.js, e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js, e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js, e2e/cypress/integration/enterprise/ldap_group/channel_modes_spec.js, e2e/cypress/integration/enterprise/system_console/archived_channels_spec.js, e2e/cypress/integration/enterprise/system_console/channel_members_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js, e2e/cypress/integration/files_and_attachments/upload_files_not_cloud_spec.js, e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js, e2e/cypress/integration/messaging/header_not_cloud_spec.js, e2e/cypress/integration/messaging/markdown_spec.js, e2e/cypress/integration/modals/quick_switcher_spec.js, e2e/cypress/integration/multi_team_and_dm/gm_header_spec.js, e2e/cypress/integration/plugins/upgrade_spec.js, e2e/save_report.js
Demote unstable tests, add flag when not to run on cloud and fix saving test report
=> Cypress/E2E: Demote unstable tests, add flag when not to run on cloud and fix saving test report

components/admin_console/admin_definition.jsx, i18n/en.json
This PR adds a note to the help text of the Rate Limiting setting. It explains that the purpose of rate limiting is to prevent overloading the server from too many requests, either by errors in 3rd party applications or if there's an attack on the system
https://mattermost.atlassian.net/browse/MM-4644
* Help text for Rate Limiting setting was updated to explain purpose of rate limiting
=> [MM-4644] Upgrade Rate Limiting help text

components/toast_wrapper/toast_wrapper.jsx, components/toast_wrapper/toast_wrapper.test.jsx
Reverts https://github.com/mattermost/mattermost-webapp/pull/7028 and https://github.com/mattermost/mattermost-webapp/pull/5828 as requested due to some issues with the New Messages toast.
https://mattermost.atlassian.net/browse/MM-31189
- https://github.com/mattermost/mattermost-webapp/pull/5828
- https://github.com/mattermost/mattermost-webapp/pull/7028
=> MM-31189 Revert New Messages toast PRs

components/toast_wrapper/toast_wrapper.jsx, components/toast_wrapper/toast_wrapper.test.jsx
Cherry pick of #7292 on release-5.31.
/cc  @hmhealey
=> Automated cherry pick of #7292

actions/notification_actions.jsx
Cherry pick of #7284 on release-5.31.
=> Automated cherry pick of #7284

components/about_build_modal/__snapshots__/about_build_modal.test.jsx.snap, components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.scss, components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.tsx
Include build hashes in cloud about modal
[MM-31858](https://mattermost.atlassian.net/browse/MM-31858)
=> MM-31858 - Include build hash in cloud about modal

components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx, components/announcement_bar/default_announcement_bar/announcement_bar.tsx, components/announcement_bar/payment_announcement_bar/payment_announcement_bar.tsx
Cherry pick of #7305 on cloud.
=> Automated cherry pick of #7305

e2e/cypress/integration/menus/user_guide_help_spec.js
- Fixed timeouts and checks
NA
=> Cypress/E2E: Fix user guide help spec

plugins/channel_header_plug/index.ts
After master merge, some information was lost in the channel header index file. Restored that information.
None
None
None
=> Fix missing channel header buttons

e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js
- Fixed timeouts and checks
NA
=> Cypress/E2E: Fix link customization spec

e2e/cypress/integration/search_filter/edit_spec.js, e2e/cypress/integration/search_filter/helpers.js
- Fixed timeouts and checks
NA
=> Cypress/E2E: Fix search filter edit spec

e2e/cypress/integration/messaging/at_mentions_spec.js
=> Cypress/E2E: Fixed at mention notifications TM4J keys

e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
=> Cypress/E2E: Fixed plugin/marketplace TM4J keys

e2e/cypress/integration/enterprise/system_console/channel_moderation/channel_mentions_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/higher_scoped_scheme_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/post_reactions_spec.js
=> Cypress/E2E: Fixed channel moderation TM4J keys

e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js, e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js, e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js, e2e/cypress/integration/team_settings/invite_members_spec.js
- Added keys and separated some tests to match TM4J
NA
=> Cypress/E2E: Fixed some guest account specs TM4J keys

e2e/cypress/integration/bot_accounts/in_lists_spec.js, e2e/cypress/integration/channel/archived_channels_spec.js, e2e/cypress/integration/channel_sidebar/dm_gm_behaviour_spec.js, e2e/cypress/integration/channel_sidebar/group_unreads_seperately_spec.js, e2e/cypress/integration/channel_sidebar/sidebar_category_menu_spec.js, e2e/cypress/integration/team_settings/teams_spec.js
Update remaining tests for the new config of sidebar organization
none, failed on daily Cypress test
=> Cypress/E2E: Update remaining tests for the new config of sidebar organization

sass/layout/_sidebar-left.scss, sass/layout/_team-sidebar.scss
Cherry-pick of #7356 to `cloud`
=> [MM-32193][MM-32178] Move transform for team sidebar button to anchor (#7356)

components/legacy_team_sidebar/components/team_button.tsx, sass/components/_badge.scss, sass/layout/_sidebar-left.scss, sass/layout/_team-sidebar.scss
Cherry pick of #7357 on cloud.
=> Automated cherry pick of #7357

sass/layout/_sidebar-left.scss
Cherry-pick of #7095 to `cloud`
=> [MM-27260] Added transform to channel collapsing (#7095)

e2e/cypress/integration/system_console/user_management_spec.js, e2e/cypress/support/api/helpers.js, e2e/cypress/support/api/user.d.ts, e2e/cypress/support/api/user.js
Fix MM-T924 by creating enough users to page through
failed on daily Cypress unstable test run
=> Cypress/E2E: Fix MM-T924 by creating enough users to page through

e2e/cypress/integration/enterprise/saml/saml_guest_member_spec.js
Summary
Handles SAML Guest tests which require special setup and keycloak.
Covers:
MM-T1423
MM-T1426
https://mattermost.atlassian.net/browse/MM-32107
=> MM-32107 Add saml guest member test

e2e/cypress/integration/channel_sidebar/legacy_sidebar_settings_spec.js, e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js, e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js, e2e/cypress/integration/enterprise/ldap/ldap_guest_spec.js, e2e/cypress/integration/enterprise/system_console/authentication/authentication2_spec.js, e2e/cypress/integration/enterprise/system_console/authentication/authentication3_spec.js, e2e/cypress/integration/enterprise/system_console/channel_members_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js, e2e/cypress/integration/enterprise/system_console/cluster_spec.js, e2e/cypress/integration/enterprise/system_console/environment_spec.js, e2e/cypress/integration/enterprise/system_console/limited_console_access_spec.js, e2e/cypress/integration/enterprise/system_console/settings_spec.js, e2e/cypress/integration/enterprise/system_console/system_scheme_permission_part2_spec.js, e2e/cypress/integration/enterprise/system_console/team_scheme_permission_part2_spec.js, e2e/cypress/integration/files_and_attachments/edit_message_with_attachment_spec.js, e2e/cypress/integration/files_and_attachments/file_previews_1_spec.js, e2e/cypress/integration/files_and_attachments/image_link_preview_new_window_spec.js, e2e/cypress/integration/files_and_attachments/paste_image_spec.js, e2e/cypress/integration/files_and_attachments/upload_files_not_cloud_spec.js, e2e/cypress/integration/integrations/outgoing_webhook/regenerate_token_spec.js, e2e/cypress/integration/integrations/poll_spec.js, e2e/cypress/integration/mark_as_unread/mark_gm_as_unread_spec.js, e2e/cypress/integration/messaging/long_draft_spec.js, e2e/cypress/integration/notifications/ignore_channel_mentions_spec.js, e2e/cypress/integration/search/post_search_display_spec.js, e2e/cypress/integration/system_console/compliance/custom_terms_of_service_spec.js
=> Cypress/E2E: Promote tests to production

package-lock.json, package.json
Cherry pick of #7367 on cloud.
/cc  @hmhealey
=> Automated cherry pick of #7367

e2e/cypress/integration/bot_accounts/bot_api_spec.js
Fix MM-T1877, MM-T1878 and MM-T1880 so we can promote 15 tests from the spec into production.
none, failing in daily unstable test run
=> Cypress/E2E: fix MM-T1877, MM-T1878 and MM-T1880

components/admin_console/system_roles/system_role/add_users_to_role_modal/__snapshots__/add_users_to_role_modal.test.tsx.snap
Related to https://github.com/mattermost/mattermost-webapp/pull/7172
=> Quick fix for failing snapshot

actions/user_actions.jsx, actions/user_actions.test.js, components/data_prefetch/data_prefetch.test.tsx, components/data_prefetch/data_prefetch.tsx, components/data_prefetch/index.ts
Cherry pick of #7380 on cloud.
/cc  @hmhealey
=> Automated cherry pick of #7380

components/post_view/post_body_additional_content/post_body_additional_content.tsx
Fix Embedded Forms after latest refactor.
None
https://github.com/mattermost/mattermost-plugin-apps/pull/38
None
=> Fix Embedded forms after refactor

e2e/cypress/integration/enterprise/system_console/authentication/authentication3_spec.js, e2e/cypress/integration/enterprise/system_console/settings_spec.js
Fix TM4J keys for MM-T1767 to MM-T1769, MM-T1181 and MM-T1635
=> Cypress/E2E: fix TM4J keys for MM-T1767 to MM-T1769, MM-T1181 and MM-T1635

actions/apps.ts, utils/markdown/renderer.tsx, utils/url.tsx
Add navigate to AppCallResponses handling
https://mattermost.atlassian.net/browse/MM-32247
None
None
=> Add Navigate to AppCallResonses handling

e2e/cypress/integration/archived_channel/archive_channel_operations_spec.js, e2e/cypress/integration/archived_channel/post_menu_spec.js, e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js, e2e/cypress/integration/messaging/reactions_spec.js, e2e/cypress/integration/multi_team_and_dm/gm_header_spec.js
=> Cypress/E2E: Fix for failed e2e tests

components/admin_console/admin_definition.jsx
Cherry pick of #7392 on release-5.32.
/cc  @sbishel
=> Automated cherry pick of #7392

sass/responsive/_mobile.scss, utils/utils.jsx
ApplyTheme Campaign: This PR completes the merge of the theme.sidebarHeaderBg commits from the campaign branch.
Dev approval for the changes was completed on the original PR(s), so we are just looking for rubber stamp approvals by dev's to satisfy merge requirements.
As QA was skipped on PR merges into campaign branches, this PR will need proper QA before merging. See below for details on what to QA for this PR.
* https://github.com/mattermost/mattermost-server/issues/15826
* https://github.com/mattermost/mattermost-server/issues/15827
See above tickets for related PRs
=> [MM-29388][MM-29387]Campaign/applytheme sidebar bg

e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js, e2e/cypress/integration/channel_sidebar/dm_category_spec.js, e2e/cypress/integration/channel_sidebar/unread_filter_spec.js
=> Cypress/E2E: Fix e2e for sidebar channels

e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js, e2e/cypress/integration/channel_sidebar/dm_category_spec.js, e2e/cypress/integration/channel_sidebar/unread_filter_spec.js
Cherry pick of #7412 on release-5.32.
=> Automated cherry pick of #7412

e2e/cypress/integration/bot_accounts/bot_api_spec.js, e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js, e2e/cypress/integration/system_console/user_management_spec.js
Promote tests with 23 TM4J test cases
=> Cypress/E2E: Promote tests with 23 TM4J test cases

e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js, e2e/cypress/integration/system_console/user_management_spec.js
Cherry pick of #7402 on release-5.32.
=> Automated cherry pick of #7402

components/admin_console/license_settings/renew_license_card/renew_license_card.tsx, components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap, components/announcement_bar/configuration_bar/configuration_bar.tsx, components/announcement_bar/renewal_link/renewal_link.tsx
Cherry pick of #7413 on release-5.32.
=> Automated cherry pick of #7413

e2e/cypress/integration/integrations/custom_slash_commands/custom_slash_commands_spec.js, e2e/cypress/integration/integrations/custom_slash_commands/helpers.js, e2e/cypress/integration/integrations/custom_slash_commands/slash_commands_spec.js
Cherry pick of #7397 on release-5.32.
=> Automated cherry pick of #7397

components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/__snapshots__/team_in_list.test.jsx.snap, components/admin_console/team_channel_settings/team/list/team_list.scss, components/widgets/team_icon/__snapshots__/team_icon.test.tsx.snap, components/widgets/team_icon/team_icon.scss, components/widgets/team_icon/team_icon.stories.js, components/widgets/team_icon/team_icon.tsx, sass/components/_permissions.scss, sass/components/_team-channel-settings.scss
Cherry pick of #7395 on release-5.32.
=> Automated cherry pick of #7395

e2e/cypress/integration/account_settings/general/email_spec.js, e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js, e2e/cypress/integration/enterprise/visual_regression/system_console/authentication_section_spec.js, e2e/cypress/integration/search/clear_input_spec.js
Fix MM-T2069 and OAuth, and update MM-T368
none, failed on daily Cypress run
=> Cypress/E2E: Fix MM-T2069 and OAuth, and update MM-T368

e2e/cypress/integration/files_and_attachments/upload_files_spec.js, e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js, e2e/cypress/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js, e2e/cypress/integration/interactive_menu/basic_options_spec.js, e2e/cypress/integration/mark_as_unread/bot_post_mark_as_unread_spec.js, e2e/cypress/integration/mark_as_unread/mark_mentions_as_unread_spec.js, e2e/cypress/integration/messaging/long_draft_spec.js, e2e/cypress/integration/system_console/main_menu_spec.js
- Various fixes to failing cypress run
NA
=> Cypress/E2E: Fix misc failing tests

e2e/cypress/integration/files_and_attachments/upload_files_spec.js, e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js, e2e/cypress/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js, e2e/cypress/integration/interactive_menu/basic_options_spec.js, e2e/cypress/integration/mark_as_unread/bot_post_mark_as_unread_spec.js, e2e/cypress/integration/mark_as_unread/mark_mentions_as_unread_spec.js, e2e/cypress/integration/messaging/long_draft_spec.js, e2e/cypress/integration/system_console/main_menu_spec.js
Cherry pick of #7452 on release-5.32.
=> Automated cherry pick of #7452

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
=> Add beta to bg

components/search_results/search_results.tsx
Cherry pick of #7449 on release-5.32.
=> Automated cherry pick of #7449

e2e/cypress/integration/system_console/user_management_spec.js
- The failures were passing for me locally but looking at the report, I noticed that the search term is not being typed fully in the input. I've seen this issue before and adding a typing delay seem to help.
NA
=> Cypress/E2E: Potential fix for user management

e2e/cypress/integration/subpath/subpath_login_spec.js
- Not really a fix but moved to subpath folder and added subpath check; removed from prod for now.
NA
=> Cypress/E2E: Move subpath login under subpath folder

e2e/cypress/integration/account_settings/security/active_sessions_spec.js
- Added Linux platform for cypress server test run
NA
=> Cypress/E2E: Added linux platform to active sessions spec

e2e/cypress/integration/channel/channel_switcher_spec.js
- Made verification of channel selected more dynamic since channel switcher channel names are not sorted
NA
=> Cypress/E2E: Fix channel switch spec

e2e/cypress/integration/bot_accounts/in_lists_1_spec.js, e2e/cypress/integration/bot_accounts/in_lists_2_spec.js
- Separated the 2 cases because for some odd reason the first one is adversely affecting the other (but it's not obvious as to why); separated for now so that they pass on cypress run.
NA
=> Cypress/E2E: Split bot accounts in lists spec

e2e/cypress/integration/channel/channel_settings_spec.js
- Create new channel for test case that renames channel
NA
=> Cypress/E2E: Fix channel settings spec

sass/layout/_sidebar-left.scss
Cherry pick of #7459 on cloud.
=> Automated cherry pick of #7459

sass/layout/_sidebar-left.scss, sass/responsive/_mobile.scss
Cherry pick of #7451 on release-5.32.
=> Automated cherry pick of #7451

e2e/cypress/integration/enterprise/permissions/team_permissions_spec.js
- Added necessary channel menu close
NA
=> Cypress/E2E: Fix team permissions spec

sass/components/_popover.scss, sass/layout/_headers.scss
Cherry pick of #7381 on release-5.32.
/cc  @jespino
=> Automated cherry pick of #7381

e2e/cypress/integration/channel_settings/more_unreads_position_with_scroll_spec.js
- Fixed scrolling so that indicators show/hide properly.
NA
=> Cypress/E2E: Fix more unreads position with scroll spec

e2e/cypress/integration/account_settings/security/active_sessions_spec.js, e2e/cypress/integration/bot_accounts/in_lists_1_spec.js, e2e/cypress/integration/bot_accounts/sidebar_display_spec.js, e2e/cypress/integration/channel/archived_channels_1_spec.js, e2e/cypress/integration/channel/archived_channels_2_spec.js, e2e/cypress/integration/channel/channel_settings_spec.js, e2e/cypress/integration/channel/channel_switcher_spec.js, e2e/cypress/integration/channel_settings/more_unreads_position_with_scroll_spec.js, e2e/cypress/integration/channel_sidebar/category_muting_spec.js, e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js, e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js, e2e/cypress/integration/enterprise/permissions/team_permissions_spec.js, e2e/cypress/integration/enterprise/system_console/channel_moderation/channel_mentions_spec.js, e2e/cypress/integration/enterprise/system_console/openid/openid_spec.js, e2e/cypress/integration/enterprise/system_console/search_box_spec.js, e2e/cypress/integration/integrations/outgoing_webhook/regenerate_token_spec.js, e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js, e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_m_spec.js, e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_one_spec.js, e2e/cypress/integration/messaging/ctrl_cmd_k_open_dm_with_mouse_spec.js, e2e/cypress/integration/multi_team_and_dm/gm_header_spec.js, e2e/cypress/integration/plugins/plugin_startup_fail_spec.js, e2e/cypress/integration/search/search_group_message_spec.js, e2e/cypress/integration/system_console/compliance/custom_terms_of_service_spec.js
- Promoted 20 unstable files
- Demoted 4 stable files
NA
=> Cypress/E2E: Promote/Demote e2e tests

components/file_upload/file_upload.test.jsx, utils/constants.jsx
Cherry pick of #7510 on release-5.32.
/cc  @hmhealey
=> Automated cherry pick of #7510

components/admin_console/openid_convert/__snapshots__/openid_convert.test.tsx.snap, components/admin_console/openid_convert/openid_convert.tsx, i18n/en.json
Fixes a typo in OpenID Connect
https://mattermost.atlassian.net/browse/MM-32738
=> MM-32738 - Fix typo in OpenID

e2e/cypress/integration/enterprise/system_console/compliance/download_compliance_export_file_spec.js, e2e/cypress/integration/integrations/slash_commands_spec.js, e2e/cypress/integration/messaging/dm_list_of_users_spec.js, e2e/cypress/integration/plugins/upgrade_spec.js
- Fixed slash commands spec
- Some promotions
NA
=> Cypress/E2E: Fix slash commands spec and some promotions

e2e/cypress/integration/plugins/demo_plugin/webhook_spec.js
- Fixed zephyr keys format and update zephyr case to match actual steps; promoted since it has been passing, just the keys were incorrect.
NA
=> Cypress/E2E: Fix webhook spec zephyr keys

components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap, components/invitation_modal/index.js, components/invitation_modal/index.test.jsx, components/invitation_modal/invitation_modal.jsx, components/invitation_modal/invitation_modal.test.jsx
Cherry pick of #7496 on cloud-2021-02-16.
=> Automated cherry pick of #7496

components/suggestion/command_provider/command_provider.tsx, components/suggestion/suggestion_box.jsx, components/suggestion/suggestion_box.test.jsx
Cherry pick of #7504 on cloud.
/cc  @hahmadia
=> Automated cherry pick of #7504

sass/components/_post.scss
Cherry pick of #7523 on cloud.
=> Automated cherry pick of #7523

e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js, e2e/cypress/integration/archived_channel/archive_channel_operations_spec.js, e2e/cypress/integration/archived_channel/archive_channel_search_spec.js, e2e/cypress/integration/archived_channel/helpers.js, e2e/cypress/integration/onboarding/tutorial_navigation_and_links_spec.js, e2e/cypress/integration/plugins/demo_plugin/webhook_spec.js, e2e/cypress/integration/plugins/plugin_buttons_spec.js
Several fixes and clean up especially for Cloud which I found while working on https://github.com/mattermost/mattermost-webapp/pull/7538
=> Cypress/E2E: Several fixes for Cloud

selectors/views/custom_status.ts
Cherry pick of #7554 on master.
/cc  @jespino
=> Automated cherry pick of #7554

e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js, e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js, e2e/cypress/integration/multi_team_and_dm/gm_add_user_spec.js, e2e/cypress/support/ui_commands.js
=> Cypress/E2E: Fix several failed tests

e2e/cypress/integration/mark_as_unread/mark_gm_as_unread_spec.js, e2e/cypress/integration/markdown/markdown_image_spec.js, e2e/cypress/integration/messaging/image_attachment_spec.js
=> Cypress/E2E: Fix image attachment

components/custom_status/custom_status.scss, components/quick_input/__snapshots__/quick_input.test.jsx.snap, components/quick_input/quick_input.jsx, sass/routes/_admin-console.scss
Making clear icon visible
https://mattermost.atlassian.net/browse/MM-33127
=> [MM-33127] Fixing admin console search clear icon

components/suggestion/at_mention_provider/at_mention_suggestion.jsx
Fixing MM-33118
[MM-33118](https://mattermost.atlassian.net/browse/MM-33118)
=> Fixing MM-33118

components/custom_status/custom_status.scss, components/quick_input/__snapshots__/quick_input.test.jsx.snap, components/quick_input/quick_input.jsx, sass/routes/_admin-console.scss
Cherry pick of #7578 on cloud.
=> Automated cherry pick of #7578

components/suggestion/at_mention_provider/at_mention_suggestion.jsx
Cherry pick of #7574 on cloud.
/cc  @jespino
=> Automated cherry pick of #7574

components/admin_console/admin_definition.jsx
Hiding custom statuses config when feature flag is disabled
[MM-33163](https://mattermost.atlassian.net/browse/MM-33163)
=> Hiding custom statuses config when feature flag is disabled

package-lock.json, package.json
Manual cherry-pick of https://github.com/mattermost/mattermost-webapp/pull/7586
https://mattermost.atlassian.net/browse/MM-33209
=> MM-33209 Downgrade serialize-error

components/admin_console/admin_definition.jsx
Cherry pick of #7582 on cloud.
/cc  @jespino
=> Automated cherry pick of #7582

e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js, e2e/cypress/integration/account_settings/display/theme/settings_view_spec.js, e2e/cypress/support/ui/common.d.ts, e2e/cypress/support/ui/common.js
Fix failed tests on theme.
Update: created Zephyr test cases and added test keys here.
=> Cypress/E2E: Fix failed tests on theme

webpack.config.js
Cherry pick of #7594 on release-5.33.
/cc  @hmhealey
=> Automated cherry pick of #7594

components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap, components/invitation_modal/index.js, components/invitation_modal/invitation_modal.jsx, components/invitation_modal/invitation_modal.test.jsx, components/main_menu/index.jsx, components/main_menu/main_menu.jsx, components/user_limit_modal/__snapshots__/user_limit_modal.test.tsx.snap, components/user_limit_modal/index.ts, components/user_limit_modal/user_limit_modal.test.tsx, components/user_limit_modal/user_limit_modal.tsx, components/widgets/links/notify_link.tsx, i18n/en.json
Cherry pick of #7579 on cloud.
/cc  @AGMETEOR
=> Automated cherry pick of #7579

components/pdf_preview.jsx
Fix zoom on pdf previews
[MM-33218](https://mattermost.atlassian.net/browse/MM-33218)
=> Fix zoom on pdf previews

components/pdf_preview.jsx
Cherry pick of #7600 on release-5.33.
/cc  @jespino
=> Automated cherry pick of #7600

actions/websocket_actions.jsx
Update the subscriptionStats when a user is deactivated or activated
[MM-33132](https://mattermost.atlassian.net/browse/MM-33132?atlOrigin=eyJpIjoiNjQ3ZDI5ZDNkOTE0NDVjNGE5ZWI3MmY3MDFjMWY0N2EiLCJwIjoiaiJ9)
=> [MM-33132] - Subscription stats are not updated when a user is deactivated/activated

actions/websocket_actions.jsx, utils/constants.jsx
Add refresh websocket event handling.
https://mattermost.atlassian.net/browse/MM-33129
Proxy: https://github.com/mattermost/mattermost-plugin-apps/pull/83
Mobile: https://github.com/mattermost/mattermost-mobile/pull/5194
=> Add refresh websocket event

sass/layout/_sidebar-right.scss, sass/responsive/_tablet.scss
Cherry pick of #7581 on release-5.33.
=> Automated cherry pick of #7581

NOTICE.txt
Cherry pick of #7611 on release-5.33.
/cc  @amyblais
=> Automated cherry pick of #7611

components/sidebar/sidebar_channel_list/__snapshots__/sidebar_channel_list.test.tsx.snap, components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx, e2e/cypress/integration/accessibility/accessibility_keyboard_usability_spec.js, e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js, e2e/cypress/integration/channel/more_channels_spec.js, e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js, e2e/cypress/integration/keyboard_shortcuts/alt_option_plus_up_down_spec.js, e2e/cypress/integration/notifications/browser_tab_notification_spec.js, e2e/cypress/integration/notifications/unread_on_public_channel_spec.js
Cherry pick of #7617 on cloud.
=> Automated cherry pick of #7617

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/channel_header/channel_header.js, components/custom_status/__snapshots__/custom_status_emoji.test.tsx.snap, components/custom_status/custom_status_emoji.test.tsx, components/custom_status/custom_status_emoji.tsx, components/custom_status/custom_status_modal.tsx, components/emoji/render_emoji.tsx, components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap, components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap, components/post_view/post_header/__snapshots__/post_header.test.tsx.snap, components/post_view/post_header/post_header.scss, components/post_view/post_header/post_header.tsx, components/post_view/post_header/post_header_custom_status.tsx, components/profile_popover/profile_popover.jsx, components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx, package-lock.json, selectors/emojis.js, selectors/views/custom_status.ts
- ~~Fix custom status failing with just the emoji and no message~~
- Fix custom emojis for statuses not loaded on page refresh 
- Fixed the bot showing custom status emoji of integration owner
***
- Fix channel sidebar misalignment
- Fix emoji misaligned with tooltip
- Fix custom status misalign next to username.
- Fix custom status sitting too high in DM channel header
- Fix No hover state on 'Set Status' button in modal
- https://mattermost.atlassian.net/browse/MM-33213
- https://mattermost.atlassian.net/browse/MM-33197
- ~~https://mattermost.atlassian.net/browse/MM-33210~~
***
- https://mattermost.atlassian.net/browse/MM-33200
- https://mattermost.atlassian.net/browse/MM-33199
- https://mattermost.atlassian.net/browse/MM-33191
- https://mattermost.atlassian.net/browse/MM-33190
- …
=> Fix issues in Custom Status

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/channel_header/channel_header.js, components/custom_status/__snapshots__/custom_status_emoji.test.tsx.snap, components/custom_status/custom_status_emoji.test.tsx, components/custom_status/custom_status_emoji.tsx, components/custom_status/custom_status_modal.tsx, components/emoji/render_emoji.tsx, components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap, components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap, components/post_view/post_header/__snapshots__/post_header.test.tsx.snap, components/post_view/post_header/post_header.scss, components/post_view/post_header/post_header.tsx, components/post_view/post_header/post_header_custom_status.tsx, components/profile_popover/profile_popover.jsx, components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx, package-lock.json, selectors/emojis.js, selectors/views/custom_status.ts
Cherry pick of #7592 on release-5.33.
/cc  @chetanyakan
=> Automated cherry pick of #7592

.circleci/config.yml
=> Fix image for spinwick

package-lock.json, package.json
`mmjstool` has had new PR's merged to it and we need update the hash on webapp to reflect the changes.
N/A
=> [No Ticket] Update MMJS Tool

e2e/cypress/integration/files_and_attachments/helpers.js
- Stabilize file previews specs
NA
=> Cypress/E2E: Stabilize file previews specs

.circleci/config.yml
Cherry pick of #7657 on release-5.33.
=> Automated cherry pick of #7657

actions/command.ts
Fix error where commands did not show the errors.
https://mattermost.atlassian.net/browse/MM-33435
=> Fix command errors

components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
There was an accidental omission in a typescript refactor
https://mattermost.atlassian.net/browse/MM-33650
=> Fixing group to channel modal

components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
Cherry pick of #7669 on cloud.
=> Automated cherry pick of #7669

components/delete_channel_modal/delete_channel_modal.test.tsx
Fix the broken test on master regarding to delete channel modal
=> NO TICKET Fix broken test on Master

components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap, components/status_dropdown/status_dropdown.jsx, components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx, e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js, e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js, e2e/cypress/integration/channel/more_channels_spec.js, e2e/cypress/integration/enterprise/profile_popover/profile_popover_spec.js, e2e/cypress/integration/menus/status_dropdown_spec.js, e2e/cypress/integration/signin_authentication/forgot_password_spec.js, e2e/cypress/support/ui/menu.d.ts, e2e/cypress/support/ui/menu.js
**Fixed following test cases**
```MM-T1477 Accessibility Support in Status Dropdown``` 
```MM-T1702 Search works when changing public/archived options in the dropdown``` 
```MM-T2927_4 should show Status header, with no pointer cursor``` 
**Updated Missing Key**
```SA15008 - Sign In Forgot password - Email address has account on server``` to ```MM-T407```
=> Fixed prod test cases

components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap, components/user_settings/security/user_settings_security.test.tsx, components/user_settings/security/user_settings_security.tsx, i18n/en.json
Cherry pick of #7693 on release-5.33.
/cc  @sbishel
=> Automated cherry pick of #7693

sass/components/_channel-switcher.scss, sass/components/_modal.scss, sass/components/_react-select.scss, sass/utils/_variables.scss
MM-33796 - Updating channel switcher css system console
**I have also updated the elevations to use the correct color value.**
https://mattermost.atlassian.net/browse/MM-33796
https://mattermost.atlassian.net/browse/MM-33780
=> [MM-33796][MM-33780] Updating channel switcher css system console

sass/components/_channel-switcher.scss, sass/components/_modal.scss, sass/components/_react-select.scss, sass/utils/_variables.scss
=> [MM-33796][MM-33780] Updating channel switcher css system console (#7696) - cherry-pick

e2e/cypress/integration/emoji/custom_emoji_2_spec.js, e2e/cypress/integration/emoji/custom_emoji_3_spec.js, e2e/cypress/integration/enterprise/system_console/compliance/s3_bucket_storage_spec.js, e2e/cypress/integration/integrations/incoming_webhook/webhook_posts_when_creator_not_in_channel_spec.js, e2e/cypress/integration/messaging/pinned_posts_spec.js, e2e/cypress/integration/search_autocomplete/users_spec.js, e2e/cypress/integration/signin_authentication/forgot_password_spec.js, e2e/cypress/integration/toast/permalink_jump_to_spec.js, e2e/cypress/integration/toast/permalink_post_spec.js
Demoting tests that were failing in prod, but passing in local runs and test servers to unstable.
=> Demoting consistently failing tests from prod to unstable

components/dot_menu/dot_menu.tsx, components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap, components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx, components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx, components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap, components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx, components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx, components/widgets/menu/menu_items/submenu_item.test.tsx, components/widgets/menu/menu_items/submenu_item.tsx, components/widgets/menu/menu_modals/submenu_modal/__snapshots__/submenu_modal.test.tsx.snap, components/widgets/menu/menu_modals/submenu_modal/submenu_modal.tsx, package-lock.json, package.json
Cherry-pick https://github.com/mattermost/mattermost-webapp/pull/7685 to release-5.33, including relevant Redux changes.
https://mattermost.atlassian.net/browse/MM-30407
=> MM-30407: improve slow typing (#7685)

sass/routes/_admin-console.scss
a cherry-pick of the original PR https://github.com/mattermost/mattermost-webapp/pull/7715
https://mattermost.atlassian.net/browse/MM-34132
https://github.com/mattermost/mattermost-webapp/pull/7715
=> MM-33907 - fix admin console heigh and show save buttons

components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx, components/admin_console/admin_navbar_dropdown/index.ts
Self-served and cloud licenses redirect to their proper administrator guide
https://mattermost.atlassian.net/browse/MM-33171
=> [MM-33171] Admin guide link should be different for cloud or on-premise instances

components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx, components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
Over limit errors shouldn't show in a paid workspace
[MM-34183](https://mattermost.atlassian.net/browse/MM-34183?atlOrigin=eyJpIjoiZTRjYjhhYjAxYWVkNDkzM2IyOTZiOGVlODAyNjViNGEiLCJwIjoiaiJ9)
=> [MM-34183] - Getting Started Step 3 (Invite members to team) for new users on paid Workspace above 10 users are unable to invite members via email

components/next_steps_view/next_steps_tips.tsx
remove trailing slash causing nav bar to hide
https://mattermost.atlassian.net/browse/MM-34235
=> MM-34235 - remove trailing slash causing nav bar to hide

components/commercial_support_modal/__snapshots__/commercial_support_modal.test.tsx.snap, components/commercial_support_modal/commercial_support_modal.test.tsx, components/commercial_support_modal/commercial_support_modal.tsx, components/commercial_support_modal/index.ts, i18n/en.json
Don't show file warning stuff and fix the link to go to cloud support instead of self hosted support
https://mattermost.atlassian.net/browse/MM-33102
=> [MM-33102] Don't show warning and Fix support Link on Cloud

.gitlab-ci.yml
Overwriting artifacts is not a problem anymore with needs. 
=> Make webapp build faster.

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
Cherry pick of #7764 on release-5.34.
/cc  @ctlaltdieliet
=> Automated cherry pick of #7764

components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap, components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx, sass/layout/_sidebar-left.scss
This PR addresses minor UI fixes to direct channel profile picture. 
- Removes status icon from bot accounts
- Reduce spacing between icon and label 
https://mattermost.atlassian.net/browse/MM-34165
https://mattermost.atlassian.net/browse/MM-34163
=> [MM-34163][MM-34165] - UI fixes to direct channel profile pics

e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js, e2e/cypress/integration/custom_status/custom_status_1_spec.js, e2e/cypress/integration/custom_status/custom_status_2_spec.js, e2e/cypress/integration/custom_status/custom_status_3_spec.js, e2e/cypress/integration/custom_status/custom_status_4_spec.js, e2e/cypress/integration/custom_status/custom_status_6_spec.js, e2e/cypress/integration/enterprise/integrations/incoming_webhook_spec.js
=> Cypress/E2E: Promote tests to prod

sass/components/_mentions.scss
Cherry pick of #7797 on release-5.34.
=> Automated cherry pick of #7797

e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
Updated test case name and code to adjust new changes. Test case has been updated in Zephyr as well.
=> Cypress/E2E: Update test case name

selectors/views/marketplace.ts
Memorize marketplace selectors to improve performance
None
=> Memorize marketplace selectors

components/profile_popover/index.js
Cherry pick of #7811 on cloud.
=> Automated cherry pick of #7811

components/gif_picker/components/SearchGrid/SearchGrid.scss
Cherry pick of #7844 on release-5.34.
/cc  @hmhealey
=> Automated cherry pick of #7844

e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
- Added missing 2nd user in GM
NA
=> Cypress/E2E: Fix case Verify Guest Badge in DM header and GM header

components/apps_form/apps_form.tsx
Handle double submit for modals
https://mattermost.atlassian.net/browse/MM-34410
=> Handle modal double submit

packages/mattermost-redux/src/types/cloud.ts
Will consume this value from CWS/Server
https://mattermost.atlassian.net/browse/MM-34414
https://github.com/mattermost/mattermost-server/pull/17316
=> [MM-34414] Add trial_end_at to cloud redux Subscription type

components/channel_header/__snapshots__/channel_header.test.jsx.snap
A couple of snapshots keep failing this PR updates them
=> Fix failing tests on master

actions/command.ts, actions/global_actions.tsx, components/apps_form/apps_form_container.tsx, components/dot_menu/dot_menu.tsx, components/post_view/embedded_bindings/button_binding/button_binding.test.tsx, components/post_view/embedded_bindings/button_binding/button_binding.tsx, components/post_view/embedded_bindings/select_binding/select_binding.test.tsx, components/post_view/embedded_bindings/select_binding/select_binding.tsx, components/suggestion/command_provider/app_command_parser/app_command_parser.ts, components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts, packages/mattermost-redux/src/types/apps.ts, plugins/channel_header_plug/channel_header_plug.tsx
Cherry pick of #7789 on cloud.
=> Automated cherry pick of #7789

components/apps_form/apps_form.tsx
Cherry pick of #7791 on cloud.
/cc  @larkox
=> Automated cherry pick of #7791

components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
Cherry pick of #7847 on cloud.
/cc  @sbishel
=> Automated cherry pick of #7847

components/apps_form/apps_form_field/apps_form_select_field.tsx
Cherry pick of #7748 on cloud.
=> Automated cherry pick of #7748

components/markdown/index.ts, components/post_markdown/__snapshots__/post_markdown.test.tsx.snap, components/post_markdown/index.ts, components/post_markdown/post_markdown.test.tsx, components/post_markdown/post_markdown.tsx, components/post_markdown/system_message_helpers.tsx, components/post_view/combined_system_message/index.ts, components/post_view/post_add_channel_member/index.ts, components/textbox/textbox.tsx
Cherry pick of #7755 on cloud.
/cc  @majidsajadi
=> Automated cherry pick of #7755

components/post_view/channel_intro_message/add_members_button.tsx
Cherry pick of #7799 on cloud.
=> Automated cherry pick of #7799

e2e/cypress/integration/archived_channel/archived_channel_spec.js, e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js, e2e/cypress/support/api/channel.d.ts, e2e/cypress/support/api/channel.js, e2e/cypress/support/api/setup.d.ts, e2e/cypress/support/api/setup.js, e2e/cypress/support/ui/channel.js
Cherry pick of #7765 on cloud.
=> Automated cherry pick of #7765

e2e/cypress/integration/custom_status/custom_status_1_spec.js, e2e/cypress/integration/custom_status/custom_status_2_spec.js, e2e/cypress/integration/custom_status/custom_status_3_spec.js, e2e/cypress/integration/custom_status/custom_status_4_spec.js, e2e/cypress/integration/custom_status/custom_status_6_spec.js, e2e/cypress/integration/enterprise/integrations/incoming_webhook_spec.js
Cherry pick of #7780 on cloud.
=> Automated cherry pick of #7780

e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
Cherry pick of #7809 on cloud.
=> Automated cherry pick of #7809

components/channel_info_modal/__snapshots__/channel_info_modal.test.tsx.snap, components/channel_info_modal/channel_info_modal.test.tsx, components/channel_info_modal/channel_info_modal.tsx, components/channel_info_modal/index.js
Cherry pick of #7602 on cloud.
/cc  @Crimson-riot
=> Automated cherry pick of #7602

sass/components/_modal.scss
Cherry pick of #7705 on cloud.
/cc  @jespino
=> Automated cherry pick of #7705

e2e/cypress/integration/messaging/dm_list_of_users_spec.js
Cherry pick of #7836 on cloud.
=> Automated cherry pick of #7836

e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
Cherry pick of #7814 on cloud.
=> Automated cherry pick of #7814

plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap, plugins/channel_header_plug/channel_header_plug.test.tsx, plugins/channel_header_plug/channel_header_plug.tsx
Cherry pick of #7825 on cloud.
=> Automated cherry pick of #7825

sass/components/_react-select.scss
Cherry pick of #7812 on cloud.
=> Automated cherry pick of #7812

components/dot_menu/index.ts
Cherry pick of #7749 on cloud.
=> Automated cherry pick of #7749

components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
Cherry pick of #7890 on cloud.
/cc  @hahmadia
=> Automated cherry pick of #7890

components/suggestion/switch_channel_provider.jsx, components/suggestion/switch_channel_provider.test.jsx, sass/components/_post.scss
Cherry pick of #7757 on cloud.
=> Automated cherry pick of #7757

components/no_results_indicator/no_results_indicator.scss, i18n/en.json
Fixing file search results styles and text on channels without files
[MM-34711](https://mattermost.atlassian.net/browse/MM-34711)
=> Fixing file search results styles and text on channels without files

components/no_results_indicator/no_results_indicator.scss, i18n/en.json
Cherry pick of #7885 on cloud.
/cc  @jespino
=> Automated cherry pick of #7885

components/admin_console/billing/billing_subscriptions/index.tsx, components/announcement_bar/cloud_trial_announcement_bar/index.ts, components/purchase_modal/index.ts, packages/mattermost-redux/src/types/cloud.ts
Use the new value from server is_free_trial
n/a
=> use the new server value is_free_trial

e2e/run_test_cycle.js, e2e/utils/file.js
- Changes in `e2e/run_test_cycle.js` fix the issue where the container is being rerun unexpectedly. Probably due to mishandling of recursion thru async/await operation.
- In `e2e/utils/file.js` - added ability to sort specs to first. This is in the case for Elasticsearch where it's better to test first, so that indexing will not take a lot of time instead of doing last where there are lots of test data already. Typical used would be:
```
node generate_test_cycle.js --stage="@prod" --sortFirst="@elasticsearch,@ldap_group,@ldap" --sortLast="@saml,@keycloak,@mfa"
```
Test report - https://mm-cypress-report.s3.amazonaws.com/4454-master-e20-prod-mattermost-enterprise-edition:master/mochawesome.html
=> Cypress/E2E: Fix CI run of Cypress and add flag to sort specs to test first

e2e/cypress/integration/signin_authentication/forgot_password_spec.js
Fix test for forgot password based on new email template
https://mattermost.atlassian.net/browse/MM-34782
=> MM-34782 Cypress/E2E: Fix test for forgot password based on new email template

components/suggestion/menu_action_provider.jsx
Cherry pick of #7769 on cloud.
=> Automated cherry pick of #7769

e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js, e2e/cypress/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_add_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_popover_ui_spec.js, e2e/cypress/integration/enterprise/oauth/oauth_spec.js, e2e/cypress/integration/files_and_attachments/file_preview_audio_spec.js, e2e/cypress/integration/files_and_attachments/file_preview_generic_spec.js, e2e/cypress/integration/files_and_attachments/file_preview_image_spec.js, e2e/cypress/integration/files_and_attachments/file_preview_video_spec.js, e2e/cypress/integration/integrations/incoming_webhook/webhook_posts_when_creator_not_in_channel_spec.js, e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
Upgrading consistently passing tests in the last five builds to prod.
Unstable nightly builds checked: 4520, 4491, 4447, 4412, 4372.
=> Upgrading tests to prod

components/purchase_modal/icon_message.scss, components/purchase_modal/index.ts, components/purchase_modal/process_payment_setup.tsx, components/purchase_modal/purchase.scss, components/purchase_modal/purchase_modal.tsx
fix contact support link in the error payment screen
https://mattermost.atlassian.net/browse/MM-34978
=> MM-34978 - fix contact support link in the error payment screen

components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap, components/admin_console/license_settings/license_settings.jsx, components/admin_console/license_settings/license_settings.test.jsx, components/admin_console/license_settings/renew_license_card/renew_license_card.tsx, components/announcement_bar/renewal_link/renewal_link.tsx
Cherry pick of #7904 on cloud.
/cc  @hahmadia
=> Automated cherry pick of #7904

components/admin_console/admin_definition.jsx
Hide payment information for trialing customers
https://mattermost.atlassian.net/browse/MM-34975
=> MM-34975 - hide payment information to free trial customers

components/admin_console/admin_definition.jsx
Cherry pick of #7950 on cloud.
=> Automated cherry pick of #7950

components/admin_console/billing/payment_info_edit.tsx, i18n/en.json
Update payment screen info banner to remove references of free tier. 
https://mattermost.atlassian.net/browse/MM-35016
=> MM-35016 - Update payment screen info text

components/admin_console/billing/payment_info_edit.tsx, i18n/en.json
Cherry pick of #7953 on cloud.
=> Automated cherry pick of #7953

e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js, e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js, e2e/cypress/integration/messaging/local_date_time_spec.js
- Fixed tests so that they are reported properly to zephyr
- Updated MM-T713 to match cypress code
NA
=> Cypress/E2E: Fix clock, timezone, local date time specs

sass/components/_popover.scss, sass/layout/_headers.scss, sass/layout/_sidebar-left.scss
This PR addresses UI issues related to hard coded variables and misalignment of the channel header with the 'has guests' text. 
https://mattermost.atlassian.net/browse/MM-34763
https://mattermost.atlassian.net/browse/MM-34767
https://mattermost.atlassian.net/browse/MM-34744
=> [MM-34763][MM-34744][MM-34767] - Fix UX issues with channel navigator and navbar

components/file_search_results/__snapshots__/file_search_result_item.test.tsx.snap, components/file_search_results/file_search_result_item.scss, components/file_search_results/file_search_result_item.tsx, components/search/search.tsx, components/search_hint/__snapshots__/search_hint.test.tsx.snap, components/search_hint/search_hint.tsx, components/search_results/__snapshots__/messages_or_files_selector.test.tsx.snap, components/search_results/messages_or_files_selector.scss, components/search_results/messages_or_files_selector.tsx, sass/components/_search.scss
Cherry pick of #7925 on cloud.
/cc  @jespino
=> Automated cherry pick of #7925

components/admin_console/system_roles/system_role/system_role.tsx, packages/mattermost-redux/src/client/client4.ts
Cherry pick of #7959 on release-5.35.
/cc  @hahmadia
=> Automated cherry pick of #7959

components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx, components/admin_console/billing/billing_subscriptions/index.tsx, selectors/cloud.ts
Cherry pick of #7937 on cloud.
=> Automated cherry pick of #7937

components/main_menu/index.jsx, components/main_menu/main_menu.jsx, components/main_menu/main_menu.test.jsx, components/purchase_modal/index.ts, components/widgets/links/link.scss, components/widgets/links/upgrade_link.tsx, components/widgets/menu/menu.tsx, components/widgets/menu/menu_items/menu_item.scss, components/widgets/menu/menu_items/menu_top_notification.tsx, i18n/en.json
Cherry pick of #7894 on cloud.
=> Automated cherry pick of #7894

components/admin_console/billing/billing_summary/billing_summary.tsx, components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx, components/purchase_modal/purchase_modal.tsx
Cherry pick of #7939 on cloud.
=> Automated cherry pick of #7939

NOTICE.txt
Cherry pick of #7978 on release-5.35.
/cc  @amyblais
=> Automated cherry pick of #7978

i18n/en.json, sass/components/_announcement-bar.scss
Cherry pick of #7971 on cloud-2021-04-26.
=> Automated cherry pick of #7971

components/announcement_bar/configuration_bar/configuration_bar.tsx, utils/license_utils.jsx
Cherry pick of #7917 on cloud.
=> Automated cherry pick of #7917

components/suggestion/switch_channel_provider.jsx
Cherry pick of #8016 on release-5.35.
=> Automated cherry pick of #8016

packages/mattermost-redux/src/actions/apps.ts, packages/mattermost-redux/src/client/client4.ts
Cherry pick of #7902 on release-5.35.
=> Automated cherry pick of #7902

components/search_results/search_results.tsx
Fixing the initial plus sign in the search result counters
[MM-34999](https://mattermost.atlassian.net/browse/MM-34999)
```release-note
NONE
```
=> Fixing the initial plus sign in the search result counters

components/search_results/search_results.tsx
Cherry pick of #8005 on cloud.
/cc  @jespino
=> Automated cherry pick of #8005

components/search_results/search_results.tsx
Cherry pick of #8000 on cloud.
/cc  @jespino
=> Automated cherry pick of #8000

components/search_results/messages_or_files_selector.scss
Cherry pick of #7999 on release-5.35.
/cc  @jespino
=> Automated cherry pick of #7999

actions/integration_actions.jsx, components/integrations/bots/bot.test.tsx, components/integrations/bots/bot.tsx, components/integrations/bots/bots.test.tsx, components/integrations/bots/bots.tsx, components/integrations/bots/index.ts, components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.tsx.snap, components/integrations/installed_oauth_app/installed_oauth_app.test.tsx, components/integrations/installed_oauth_app/installed_oauth_app.tsx, components/integrations/installed_oauth_apps/__snapshots__/installed_oauth_apps.test.tsx.snap, components/integrations/installed_oauth_apps/index.ts, components/integrations/installed_oauth_apps/installed_oauth_apps.test.tsx, components/integrations/installed_oauth_apps/installed_oauth_apps.tsx, i18n/en.json, packages/mattermost-redux/src/action_types/integrations.ts, packages/mattermost-redux/src/actions/integrations.ts, packages/mattermost-redux/src/client/client4.ts, packages/mattermost-redux/src/reducers/entities/integrations.ts, packages/mattermost-redux/src/selectors/entities/integrations.ts, packages/mattermost-redux/src/store/initial_state.ts, packages/mattermost-redux/src/types/integrations.ts
Cherry pick of #7850 on cloud.
/cc  @larkox
=> Automated cherry pick of #7850

actions/apps.ts, actions/command.test.js, actions/command.ts, actions/global_actions.tsx, actions/post_actions.jsx, components/apps_form/__snapshots__/apps_form_container.test.jsx.snap, components/apps_form/apps_form.test.jsx, components/apps_form/apps_form.tsx, components/apps_form/apps_form_container.test.jsx, components/apps_form/apps_form_container.tsx, components/apps_form/index.ts, components/dot_menu/dot_menu.test.tsx, components/dot_menu/dot_menu.tsx, components/dot_menu/dot_menu_empty.test.tsx, components/dot_menu/dot_menu_mobile.test.tsx, components/dot_menu/index.ts, components/post_view/embedded_bindings/button_binding/button_binding.test.tsx, components/post_view/embedded_bindings/button_binding/button_binding.tsx, components/post_view/embedded_bindings/button_binding/index.ts, components/post_view/embedded_bindings/select_binding/index.ts, components/post_view/embedded_bindings/select_binding/select_binding.test.tsx, components/post_view/embedded_bindings/select_binding/select_binding.tsx, components/suggestion/command_provider/app_command_parser/app_command_parser.ts, components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts, i18n/en.json, plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap, plugins/channel_header_plug/channel_header_plug.test.tsx, plugins/channel_header_plug/channel_header_plug.tsx, plugins/channel_header_plug/index.ts, types/apps.ts
Cherry pick of #7827 on cloud.
=> Automated cherry pick of #7827

actions/apps.ts, actions/command.test.js, actions/command.ts, actions/global_actions.tsx, actions/post_actions.jsx, components/apps_form/__snapshots__/apps_form_container.test.jsx.snap, components/apps_form/apps_form.test.jsx, components/apps_form/apps_form.tsx, components/apps_form/apps_form_container.test.jsx, components/apps_form/apps_form_container.tsx, components/apps_form/index.ts, components/dot_menu/dot_menu.test.jsx, components/dot_menu/dot_menu.tsx, components/dot_menu/dot_menu_empty.test.tsx, components/dot_menu/dot_menu_mobile.test.tsx, components/dot_menu/index.ts, components/post_view/embedded_bindings/button_binding/button_binding.test.tsx, components/post_view/embedded_bindings/button_binding/button_binding.tsx, components/post_view/embedded_bindings/button_binding/index.ts, components/post_view/embedded_bindings/select_binding/index.ts, components/post_view/embedded_bindings/select_binding/select_binding.test.tsx, components/post_view/embedded_bindings/select_binding/select_binding.tsx, components/suggestion/command_provider/app_command_parser/app_command_parser.ts, components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts, i18n/en.json, plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap, plugins/channel_header_plug/channel_header_plug.test.tsx, plugins/channel_header_plug/channel_header_plug.tsx, plugins/channel_header_plug/index.ts, types/apps.ts
#7827
```release-note
NONE
```
=> Cherrypick "Use ActionResult error field for CallResponse errors (#7827)"

sass/routes/_admin-console.scss
Error message displayed next to Save & Cancel buttons in System Console is not responsive. This PR aims to fix it by increasing max height
https://mattermost.atlassian.net/browse/MM-25824
**BEFORE**
**AFTER**
```release-note
NONE
```
=> [MM-25824] Fix Error message displayed next to Save & Cancel buttons in System Console is not responsive

components/apps_form/apps_form.tsx
Cherry pick of #7982 on release-5.35.
```release-note-none
```
=> Automated cherry pick of #7982

components/suggestion/command_provider/app_command_parser/app_command_parser.ts, components/suggestion/command_provider/command_provider.test.tsx, components/suggestion/command_provider/command_provider.tsx, components/suggestion/suggestion_box.test.jsx, components/textbox/textbox.tsx
Cherry pick of #7922 on release-5.35.
=> Automated cherry pick of #7922

components/main_menu/main_menu.jsx, components/main_menu/main_menu.test.jsx, plugins/test/__snapshots__/main_menu_action.test.jsx.snap
This PR displays the 'Marketplace' button in the main menu if the user has the `sysconsole_write_plugins` permission.
https://mattermost.atlassian.net/browse/MM-30815
```release-note
NONE
```
=> [MM-30815] add link to Plugins Marketplace

packages/mattermost-redux/src/constants/permissions.ts
Cherry pick of #8060 on cloud.
/cc  @hahmadia
=> Automated cherry pick of #8060

components/widgets/menu/menu_wrapper.test.tsx, components/widgets/menu/menu_wrapper.tsx
Adding class to indicate if the menu is open on the menu wrapper
https://mattermost.atlassian.net/browse/MM-35458
=> Adding class to indicate if the menu is open on the menu wrapper

actions/marketplace.ts
Changes per https://github.com/mattermost/mattermost-plugin-apps/pull/166
https://mattermost.atlassian.net/browse/MM-35184
- Has Apps plugin changes: https://github.com/mattermost/mattermost-plugin-apps/pull/166
```release-note
NONE
```
=> [MM-35184] Update apps install command for Marketplace

actions/marketplace.ts
Cherry pick of #8009 on release-5.35.
/cc  @hanzei
=> Automated cherry pick of #8009

actions/marketplace.ts
Reverts mattermost/mattermost-webapp#8067
=> Revert "Automated cherry pick of #8009"

e2e/cypress/integration/accessibility/accessibility_buttons_spec.js, e2e/cypress/integration/accessibility/accessibility_keyboard_usability_spec.js
Fixed two `accessibility button` and `accessibility keyboard` test cases
=> Cypress/E2E: Fixed accessibility test cases

e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js, e2e/cypress/integration/accessibility/accessibility_post_spec.js
Fixed emoji and keyboard accessibility test cases
=> Cyperss/E2E:fixed emoji preview  and keyboard accessibility 

e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js, e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js, e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js, e2e/cypress/integration/enterprise/group_mentions/helpers.js, e2e/cypress/integration/integrations/outgoing_webhook/regenerate_token_spec.js, e2e/cypress/integration/messaging/message_draft_then_switch_channel_spec.js, e2e/cypress/support/ui/system.js
none, failed on Cypress Cloud May 5
```release-note
NONE
```
=> Cypress/E2E: Fix flaky prod tests

components/emoji_picker/emoji_picker_overlay.jsx
Cherry pick of #8092 on release-5.33.
```release-note
NONE
```
=> Automated cherry pick of #8092

.gitlab-ci.yml, package.json
ci/gitlab: fix test running on gitlab ci
```release-note
NONE
```
=> ci/gitlab: fix test running on gitlab ci

.gitlab-ci.yml, package.json
Cherry pick of #8102 on cloud.
/cc  @cpanato
=> Automated cherry pick of #8102

e2e/cypress/fixtures/console-example-inputs.json, e2e/cypress/fixtures/system-roles-console-access.json
MM-T3388 - Verify the Admin Role - System Read Only Admin
=> Cypress/E2E: Fixed compliance compliance data retention

components/post_view/post_info/index.ts, components/post_view/post_info/post_info.test.tsx, components/post_view/post_info/post_info.tsx, components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap, components/rhs_comment/index.js, components/rhs_comment/rhs_comment.jsx, components/rhs_comment/rhs_comment.test.jsx, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/index.js, components/rhs_root_post/rhs_root_post.jsx, components/rhs_root_post/rhs_root_post.test.jsx
- rearranges center post menu items, (dot menu becomes the last item)
- rearranges RHS post menu items, (dot menu becomes the last item)
https://mattermost.atlassian.net/browse/MM-35270
https://mattermost.atlassian.net/browse/MM-35271
```release-note
NONE
```
=> MM-35270, MM-35271: CRT dotmenu changes

e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js, e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js, e2e/cypress/integration/mark_as_unread/toast_appears_unread_spec.js, e2e/cypress/integration/menus/status_dropdown_spec.js, e2e/cypress/integration/messaging/permalink_message_edit_spec.js, e2e/cypress/integration/plugins/marketplace/not_render_in_main_menu_spec.js, e2e/cypress/integration/plugins/marketplace/render_in_main_menu_spec.js, e2e/cypress/support/ui/menu.d.ts, e2e/cypress/support/ui/menu.js
=> Cypress/E2E: Fix several tests from the recent cloud test run

e2e/cypress/integration/custom_status/custom_status_5_spec.js
Fix test of custom status and match with the test case - MM-T3850
none, failed on daily Cypress run
```release-note
NONE
```
=> Cypress/E2E: Fix test of custom status and match with the test case

e2e/cypress/fixtures/account_setting_sections.json
- Fixed `accessibility_account_setting_spec`
NA
```release-note
NONE
```
=> Cypress/E2E: Fix account setting sections json

components/post_view/post/__snapshots__/post.test.js.snap, components/post_view/post/post.jsx, components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap, components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/rhs_root_post.jsx
- Fixed MM-35924 Custom status emoji is undersized and misaligned in the RHS
- Fixed MM-36026 "Update your status" is showing an all users posts instead of just the current user
- https://mattermost.atlassian.net/browse/MM-35924
- https://mattermost.atlassian.net/browse/MM-36026
```release-note
Fixed MM-35924 and MM-36026 issues
```
=> Fixed custom status issues

e2e/cypress/integration/scroll/deleting_scroll_spec.js, e2e/cypress/integration/signin_authentication/login_logout_smoke_spec.js
Summary
Cypress test: MM-T2372 Deleting
Ticket Link
https://automation-test-cases.vercel.app/test/MM-T2372
=> MM-T2372 Deleting: Thread does not move when deleting post

e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
https://automation-test-cases.vercel.app/test/MM-T947
```release-note
NONE
```
=> tests/MM-T947 : When deactivating users in the System Console, email address should not disappear

e2e/cypress/integration/messaging/message_bullets_spec.js
https://automation-test-cases.vercel.app/test/MM-T1321
```release-note
NONE
```
=> tests/MM-T1321 : WebApp: Truncated Numbered List on Chat History Panel

e2e/cypress/integration/channel_sidebar/category_sorting_spec.js
Fixed two test cases of "category sorting"
NONE
=> Cypress/E2E : Fixed Category sortingTest Case

components/profile_popover/profile_popover.jsx
Cherry pick of #8182 on release-5.36.
=> Automated cherry pick of #8182

e2e/cypress/integration/scroll/channel_scroll_spec.js
https://automation-test-cases.vercel.app/test/MM-T2374
```release-note
NONE
```
=> tests/MM-T2374 : System Messages

e2e/cypress/integration/system_console/user_management/users_spec.js
https://automation-test-cases.vercel.app/test/MM-T925
N/A
N/A
```release-note
NONE
```
=> tests/MM-T925 : Users - Profile image on User Configuration page is round

components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx, i18n/en.json, utils/constants.jsx
This PR makes sure that the cloud pricing information link is open in a new tab once the multiple sku's feature is enabled.
https://mattermost.atlassian.net/browse/MM-36066
```release-note
NONE
```
=> Mm 36066 open cloud pricing link in new tab

components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx, components/admin_console/billing/billing_subscriptions/index.tsx
Cherry pick of #8201 on cloud.
=> Automated cherry pick of #8201

NOTICE.txt
Cherry pick of #8199 on release-5.36.
/cc  @amyblais
=> Automated cherry pick of #8199

components/emoji_picker/emoji_picker_overlay.jsx
Cherry pick of #8208 on release-5.36.
```release-note
Fix emoji picker sometimes opening in the wrong position
```
=> Automated cherry pick of #8208

components/sidebar/__snapshots__/sidebar.test.tsx.snap, components/sidebar/sidebar.tsx
Cherry pick of #8198 on release-5.34.
/cc  @larkox
=> Automated cherry pick of #8198

components/suggestion/at_mention_provider/at_mention_suggestion.jsx
Cherry pick of #8235 on cloud.
=> Automated cherry pick of #8235

components/legacy_sidebar/header/dropdown/index.js, components/legacy_sidebar/header/dropdown/sidebar_header_dropdown.jsx
Cherry pick of #8207 on cloud.
/cc  @catalintomai
=> Automated cherry pick of #8207

packages/mattermost-redux/src/actions/posts.test.js, packages/mattermost-redux/src/reducers/entities/posts.ts, packages/mattermost-redux/src/reducers/entities/threads.ts
Update avatars and reply count correctly for unfollowed threads.
https://mattermost.atlassian.net/browse/MM-36068
```release-note
NONE
```
=> MM-36068 Update avatars and reply count correctly for unfollowed threads

e2e/cypress/integration/onboarding/tutorial_navigation_and_links_spec.js, e2e/cypress/integration/plugins/demo_plugin/webhook_spec.js
Fixed Webhook and Tutorial navigation test cases
NONE
=> Cypress/e2e: Fixed Webhook and Tutorial navigation test cases

e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js
Fixed link customization test case
NONE
=> Cypress/E2E : Fixed link customization Test case

e2e/cypress/integration/channel_settings/channel_header_spec.js, e2e/cypress/support/api/channel.d.ts
https://automation-test-cases.vercel.app/test/MM-T1808
```release-note
NONE
```
=> tests/MM-T1808 : Hover effect exists to add a channel description / header (when not already present)

components/threading/thread_viewer/__snapshots__/thread_viewer.test.tsx.snap, components/threading/thread_viewer/thread_viewer.test.tsx
Fixes tests in thread viewer
```release-note
NONE
```
=> Fixes tests in thread viewer

actions/marketplace.ts
Update slash command used in the Marketplace to install apps.
https://mattermost.atlassian.net/browse/MM-36294
- Has Apps Plugin changes: https://github.com/mattermost/mattermost-plugin-apps/pull/194
```release-note
NONE
```
=> [MM-36294] Update marketplace install command

.gitlab-ci.yml
Related MR: https://git.internal.mattermost.com/mattermost/ci/mattermost-webapp/-/merge_requests/8/diffs
```release-note
```
=> Set build image version as variable

actions/marketplace.ts
Cherry pick of #8244 on cloud.
/cc  @hanzei
=> Automated cherry pick of #8244

actions/views/create_comment.jsx
Changes selector's name for tracking to the correct one.
```release-note
NONE
```
=> Fixes selector's name for tracking

actions/new_post.test.js, actions/new_post.ts, actions/post_actions.test.js, packages/mattermost-redux/src/actions/channels.ts
5.36 version of https://github.com/mattermost/mattermost-webapp/pull/8222
https://mattermost.atlassian.net/browse/MM-35837
https://github.com/mattermost/mattermost-webapp/pull/8222
```release-note
NONE
```
=> MM-35837 Improve batching of channel-related actions on post receipt (release-5.36)

e2e/cypress/integration/channel_sidebar/category_sorting_spec.js
- Promote  MM-T3834 and MM-T3916
NA
```release-note
NONE
```
=> Cypress/E2E: Promote category sorting

selectors/views/custom_status.ts
Fix linting errors from master
```release-note
NONE
```
=> fix import errors

selectors/views/custom_status.ts
Cherry pick of #8298 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #8298

components/purchase_modal/purchase_modal.tsx
This PR orders the new products from lowest to highest price. 
https://mattermost.atlassian.net/browse/MM-36341
```release-note
NONE
```
=> MM-36341 - order plan lists

components/sidebar_right/sidebar_right.jsx, selectors/views/threads.test.ts, selectors/views/threads.ts
Cherry pick of #8279 on cloud.
/cc  @koox00
=> Automated cherry pick of #8279

components/emoji_picker/emoji_picker_tabs.jsx, sass/components/_emoji-picker-tabs.scss, sass/components/_emoticons.scss
Some colors were not following the theme guidelines.
[MM-36626](https://mattermost.atlassian.net/browse/MM-36626)
```release-note
NONE
```
=> [MM-36626] fix emoji picker colors

components/emoji_picker/emoji_picker_tabs.jsx, sass/components/_emoji-picker-tabs.scss, sass/components/_emoticons.scss
Cherry pick of #8303 on cloud.
=> Automated cherry pick of #8303

components/admin_console/billing/billing_subscriptions/index.tsx, components/admin_console/billing/billing_summary/billing_summary.tsx, components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx, components/announcement_bar/cloud_trial_announcement_bar/index.ts, components/main_menu/index.jsx, utils/constants.jsx
This PR adds a condition that assures we always will display in the UI the maximum remaining days correctly.
https://mattermost.atlassian.net/browse/MM-35897
```release-note
NONE
```
=> MM-35897 - make sure to show max 14 days in the UI of remaining trial

i18n/en.json, utils/emoticons.test.tsx, utils/emoticons.tsx
Cherry pick of #8318 on cloud.
=> Automated cherry pick of #8318

components/rhs_comment/rhs_comment.jsx, components/threading/thread_viewer/thread_viewer.tsx
Cherry pick of #8323 on cloud.
/cc  @koox00
=> Automated cherry pick of #8323

actions/emoji_actions.js, actions/local_storage.jsx, components/emoji_picker/components/emoji_picker_skin.jsx, components/emoji_picker/emoji_picker.jsx, components/emoji_picker/emoji_picker.test.jsx, components/emoji_picker/index.js, reducers/views/emoji.js, selectors/emojis.js, stores/local_storage_store.jsx, utils/constants.jsx
Cherry pick of #8322 on cloud.
=> Automated cherry pick of #8322

components/suggestion/switch_channel_provider.jsx
Cherry pick of #8324 on cloud.
/cc  @koox00
=> Automated cherry pick of #8324

sass/components/_announcement-bar.scss
Manual cherry-pick of https://github.com/mattermost/mattermost-webapp/pull/8321
```release-note
NONE
```
=> Manual cherry pick of #8321

packages/reselect/src/index.js
`trackedSelectors` previously stored old copies of selectors which in turn store their previous results. This caused it to leak memory over time as we created and stopped using per-component selectors created by factories.
The new version is still technically unbounded in its memory usage, but it grows at a much slower rate since it's only storing a few values for each selector instead of the potentially large data structures pulled from the redux store or computed by the selector.
More information here: https://community-daily.mattermost.com/core/pl/nctf7qwuqjgwjxegaiw1uobpnw
```release-note
NONE
```
=> Prevent trackedSelectors from holding a reference to old selectors

packages/reselect/src/index.js
Cherry pick of #8336 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #8336

e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js, e2e/cypress/integration/accessibility/accessibility_popovers_spec.js, e2e/cypress/integration/accessibility/accessibility_post_spec.js, e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js, e2e/cypress/integration/archived_channel/post_menu_spec.js, e2e/cypress/integration/emoji/custom_emoji_1_spec.js, e2e/cypress/integration/emoji/sorted_emojis_spec.js, e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_not_cloud_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_more_spec.js, e2e/cypress/integration/enterprise/guest_accounts/helpers.js, e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_not_cloud_spec.js, e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js, e2e/cypress/integration/interactive_dialog/full_dialog_spec.js, e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js, e2e/cypress/integration/messaging/dm_list_of_users_spec.js, e2e/cypress/integration/messaging/emoji_keyboard_entry_spec.js, e2e/cypress/integration/messaging/emoji_picker_keyboard_usability_spec.js, e2e/cypress/integration/messaging/emoji_size_spec.js, e2e/cypress/integration/notifications/desktop_notifications_spec.js, e2e/cypress/integration/system_console/reporting/site_statistics_spec.js, e2e/cypress/integration/system_console/user_management/users_deactivation_not_cloud_spec.js, e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js, e2e/cypress/integration/system_console/user_management_not_cloud_spec.js, e2e/cypress/integration/system_console/user_management_spec.js, e2e/cypress/support/api/user.d.ts, e2e/cypress/support/api/user.js
- Move several tests as "not cloud"
- Updated tests based on recent changes
none, failed on Cloud run
```release-note
NONE
```
=> Cypress/E2E: Fix failed tests

components/suggestion/command_provider/app_command_parser/app_command_parser.ts
Commands with forms with no fields where not handled correctly by the parser.
None
https://github.com/mattermost/mattermost-webapp/pull/8171
None
```release-note
NONE
```
=> Fix Command parser

actions/views/threads.ts, components/sidebar/sidebar_channel_list/index.ts, components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx, components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx, components/threading/global_threads/global_threads.tsx, components/threading/global_threads_link/global_threads_link.tsx
Cherry pick of #8278 on release-5.37.
/cc  @koox00
=> Automated cherry pick of #8278

components/threading/global_threads/global_threads.tsx
Cherry pick of #8333 on release-5.37.
/cc  @koox00
=> Automated cherry pick of #8333

NOTICE.txt
Cherry pick of #8357 on release-5.37.
/cc  @amyblais
=> Automated cherry pick of #8357

components/apps_form/apps_form.test.jsx, components/apps_form/apps_form.tsx, components/apps_form/apps_form_field/apps_form_field.test.tsx, components/apps_form/apps_form_field/apps_form_field.tsx, components/suggestion/command_provider/command_provider.test.tsx
Cherry pick of #8219 on cloud.
/cc  @larkox
=> Automated cherry pick of #8219

components/user_settings/general/user_settings_general.tsx, i18n/en.json
Cherry pick of #8360 on release-5.37.
=> Automated cherry pick of #8360

components/suggestion/emoticon_provider.jsx, packages/mattermost-redux/src/types/emojis.ts, utils/emoticons.tsx
Cherry pick of #8339 on cloud.
=> Automated cherry pick of #8339

components/user_settings/display/user_settings_display.tsx
Cherry pick of #8335 on cloud.
/cc  @koox00
=> Automated cherry pick of #8335

package-lock.json, sass/components/_channel-switcher.scss, sass/layout/_sidebar-left.scss
fixes styles (color) for modal-header close button by increasing class specificity
Fixes [MM-36740](https://mattermost.atlassian.net/browse/MM-36740)
| before | after |
|-------|-------|
|<img width="610" alt="Screenshot 2021-07-07 at 16 15 17" src="https://user-images.githubusercontent.com/32863416/124774994-8b1f9000-df3e-11eb-9b1e-976976072bdf.png">|<img width="610" alt="Screenshot 2021-07-07 at 16 14 43" src="https://user-images.githubusercontent.com/32863416/124775024-907cda80-df3e-11eb-89eb-06832a4f2106.png">|
```release-note
NONE
```
=> MM-36740 - fix close button styling

sass/routes/_about-modal.scss
This PR fixes a hardcoded value for the about modal border colour so that the colour can update when we are using different themes. 
https://mattermost.atlassian.net/browse/MM-36313
-->
```release-note: NONE
```
=> [MM-36313] - Fix hardcoded value for about modal border

e2e/generate_test_cycle.js, e2e/run_test_cycle.js, e2e/save_report.js
Fix e2e scripts instruction
```release-note
NONE
```
=> (chore) Cypress/E2E: fix e2e scripts instruction

e2e/cypress/integration/emoji/recently_used_emoji_spec.js
Attempt to fix timeout error when running cypress against recently_used_emoji_spec. Also demoted the specs for observation.
none, frequently happening on daily Cloud run
```release-note
NONE
```
=> Cypress/E2E: Fix timeout error when running cypress against recently_used_emoji_spec

packages/mattermost-redux/src/client/client4.ts
Cherry pick of #8381 on cloud.
=> Automated cherry pick of #8381

components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts, components/suggestion/command_provider/app_command_parser/app_command_parser.ts, i18n/en.json
Improve some texts, handled some weird cases and fixed some suggestions.
The case handled is when we try to execute a non leaf command, or when that command has a form included.
None
None
```release-note
NONE
```
=> Minor error fixes on command parser

components/suggestion/command_provider/app_command_parser/app_command_parser.ts
Cherry pick of #8348 on cloud.
/cc  @larkox
=> Automated cherry pick of #8348

e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js, e2e/cypress/integration/messaging/header_spec.js, e2e/cypress/integration/messaging/receive_message_on_socket_reconnect_spec.js, e2e/cypress/integration/team_settings/teams_spec.js, e2e/cypress/integration/toast/permalink_post_with_new_message_spec.js
Fix failed tests from cloud run
```release-note
NONE
```
=> Cypress/E2E: Fix failed tests from cloud run

components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.jsx.snap, components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap, components/admin_console/team_channel_settings/team/list/team_list.scss, e2e/utils/artifacts.js
=> Fix master lint issue.

actions/storage.js, actions/views/create_comment.jsx, components/create_comment/create_comment.jsx, components/create_post/create_post.jsx, components/create_post/index.js
Cherry pick of #8411 on cloud.
=> Automated cherry pick of #8411

actions/views/create_comment.jsx, components/create_post/create_post.jsx
Cherry pick of #8428 on cloud.
=> Automated cherry pick of #8428

components/collapsed_reply_threads_modal/collapsed_reply_threads_modal.tsx, i18n/en.json
cc// @cwarnermm as an example of an in product "text" change
```release-note
NONE
```
=> Update CRT docs link in notice

components/collapsed_reply_threads_modal/collapsed_reply_threads_modal.tsx, i18n/en.json
Cherry pick of #8359 on cloud.
/cc  @esethna
=> Automated cherry pick of #8359

components/needs_team/needs_team.test.tsx, components/post_view/post/post.jsx, components/post_view/post_header/post_header_custom_status.tsx, components/post_view/post_info/post_info.tsx, components/root/root.test.jsx, components/threading/channel_threads/thread_footer/thread_footer.tsx, sass/components/_post.scss, sass/layout/_webhooks.scss, utils/utils.jsx
Cherry pick of #8342 on cloud.
/cc  @koox00
=> Automated cherry pick of #8342

e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js, e2e/cypress/integration/account_settings/display/code_theme_colors_spec.js, e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/with_ldap_login_spec.js, e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js, e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js, e2e/cypress/integration/messaging/channel_menu_spec.js, e2e/cypress/support/api/preference.d.ts, e2e/cypress/support/api/preference.js, e2e/cypress/support/api/user.d.ts, e2e/cypress/support/api/user.js, e2e/cypress/support/index.js
- Updated tests to new behavior.
- Renamed onboarding function.
NA
```release-note
NONE
```
=> Cypress/E2E Maintenance: Fix failing tests

components/generic_modal.scss, components/product_notices_modal/product_notices_modal.scss
Cherry pick of #8425 on cloud.
=> Automated cherry pick of #8425

packages/mattermost-redux/src/actions/threads.ts
Cherry pick of #8450 on cloud.
=> Automated cherry pick of #8450

components/threading/global_threads/thread_pane/thread_pane.scss
Cherry pick of #8448 on cloud.
/cc  @koox00
=> Automated cherry pick of #8448

actions/storage.js, actions/views/create_comment.jsx, actions/views/create_comment.test.jsx, components/create_comment/create_comment.jsx, components/create_comment/create_comment.test.jsx, components/create_comment/index.js, components/create_post/create_post.jsx, components/create_post/index.js, components/threading/thread_viewer/thread_viewer.tsx
Cherry picks the following fixes for slow typing performance issue related to drafts:
* https://github.com/mattermost/mattermost-webapp/pull/8396
* https://github.com/mattermost/mattermost-webapp/pull/8411
* https://github.com/mattermost/mattermost-webapp/pull/8428
```release-note
Improve typing performance in affected environments by reducing the frequency at which drafts are saved
```
=> Cherry pick slow typing draft fixes to release-5.37

components/needs_team/index.ts, components/needs_team/needs_team.test.tsx, components/needs_team/needs_team.tsx, components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx, components/team_members_dropdown/index.ts, components/team_members_dropdown/team_members_dropdown.test.tsx, components/team_members_dropdown/team_members_dropdown.tsx, packages/mattermost-redux/src/actions/channels.test.js, packages/mattermost-redux/src/actions/posts.test.js, packages/mattermost-redux/src/actions/preferences.test.js, packages/mattermost-redux/src/actions/teams.test.js, packages/mattermost-redux/src/actions/teams.ts, packages/mattermost-redux/src/actions/users.test.js, packages/mattermost-redux/src/actions/users.ts, packages/mattermost-redux/src/client/client4.ts, packages/mattermost-redux/src/reducers/entities/threads.ts, packages/mattermost-redux/src/types/teams.ts, packages/mattermost-redux/test/test_helper.js
This is a subset of @calebroseland's PR #8290  with some minor updates. I'll be submitting further PRs to handle the other tickets related to team thread unreads.
https://mattermost.atlassian.net/browse/MM-35392
```release-note
NONE
```
=> MM-35392 Load thread unreads for other teams on app load

components/needs_team/index.ts, components/needs_team/needs_team.test.tsx, components/needs_team/needs_team.tsx, components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx, components/team_members_dropdown/index.ts, components/team_members_dropdown/team_members_dropdown.test.tsx, components/team_members_dropdown/team_members_dropdown.tsx, packages/mattermost-redux/src/actions/channels.test.js, packages/mattermost-redux/src/actions/posts.test.js, packages/mattermost-redux/src/actions/preferences.test.js, packages/mattermost-redux/src/actions/teams.test.js, packages/mattermost-redux/src/actions/teams.ts, packages/mattermost-redux/src/actions/users.test.js, packages/mattermost-redux/src/actions/users.ts, packages/mattermost-redux/src/client/client4.ts, packages/mattermost-redux/src/reducers/entities/threads.ts, packages/mattermost-redux/src/types/teams.ts, packages/mattermost-redux/test/test_helper.js
Cherry pick of #8413 on cloud.
=> Automated cherry pick of #8413

components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap, components/channel_invite_modal/channel_invite_modal.tsx, components/multiselect/multiselect.tsx, e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js, e2e/cypress/integration/messaging/focus_move_spec.js, e2e/cypress/integration/notifications/browser_tab_notification_spec.js, sass/components/_channel-invite-modal.scss, sass/components/_channel-switcher.scss, sass/components/_module.scss
Cherry pick of #8449 on cloud.
/cc  @hmhealey
=> Automated cherry pick of #8449

components/channel_layout/center_channel/center_channel.test.tsx, components/channel_layout/center_channel/center_channel.tsx, components/channel_layout/center_channel/index.ts, components/channel_view/__snapshots__/channel_view.test.tsx.snap, components/channel_view/channel_view.tsx, components/channel_view/index.ts
Cherry pick of #8437 on cloud.
/cc  @AGMETEOR
=> Automated cherry pick of #8437

components/next_steps_view/steps.ts, components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx, components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx, i18n/en.json, i18n/en_AU.json
Cherry pick of #8442 on cloud.
/cc  @AGMETEOR
=> Automated cherry pick of #8442

components/threading/global_threads/global_threads.tsx
Cherry pick of #8438 on cloud.
/cc  @AGMETEOR
=> Automated cherry pick of #8438

components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap, components/threading/global_threads/thread_item/thread_item.tsx
Cherry pick of #8434 on cloud.
=> Automated cherry pick of #8434

components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap, components/threading/global_threads/thread_item/thread_item.tsx
Cherry pick of #8447 on cloud.
/cc  @koox00
=> Automated cherry pick of #8447

components/admin_console/license_settings/license_settings.jsx
Cherry pick of #8406 on cloud.
=> Automated cherry pick of #8406

components/sidebar_right/sidebar_right.jsx, components/threading/thread_viewer/thread_viewer.tsx
Cherry pick of #8471 on cloud.
```release-note
Fix Safari overflow scroll glitch
```
=> Automated cherry pick of #8471

components/rhs_header_post/index.ts, components/threading/thread_viewer/thread_viewer.tsx, packages/mattermost-redux/src/reducers/entities/threads.test.js, packages/mattermost-redux/src/reducers/entities/threads.ts
Cherry pick of #8441 on cloud.
/cc  @koox00
=> Automated cherry pick of #8441

utils/constants.jsx
Add "playbooks" and "boards" to restricted team URLs list.
https://mattermost.atlassian.net/browse/MM-37042
- https://github.com/mattermost/mattermost-server/pull/18014
```release-note
NONE
```
=> MM-37042 Add "playbooks" and "boards" to restricted team URLs list

components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/admin_sidebar.test.jsx, e2e/cypress/integration/enterprise/system_console/compliance/data_retention_policies_spec.js
Cherry pick of #8454 on release-5.38.
=> Automated cherry pick of #8454

components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap, components/threading/global_threads/thread_list/thread_list.tsx
Cherry pick of #8493 on release-5.38.
/cc  @koox00
=> Automated cherry pick of #8493

actions/new_post.ts
Cherry pick of #8489 on release-5.38.
/cc  @ashishbhate
=> Automated cherry pick of #8489

NOTICE.txt
Cherry pick of #8502 on release-5.38.
/cc  @amyblais
=> Automated cherry pick of #8502

components/next_steps_view/steps.test.tsx, components/next_steps_view/steps.ts, components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx, e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js, i18n/en.json, i18n/en_AU.json
Cherry pick of #8478 on release-5.38.
/cc  @AGMETEOR
=> Automated cherry pick of #8478

e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js, e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Fixed Guest and Member invitation test cases
```release-note
NONE
```
=> Cypress E2E: fixed Guest and Member invitation test cases

components/global/at_mentions_button/at_mentions_button.tsx, components/global/at_mentions_button/index.ts, components/global/global_header.scss, components/global/global_header.tsx, components/global/global_search_nav/global_search_nav.tsx, components/global/history_buttons/history_buttons.tsx, components/global/history_buttons/index.ts, components/global/product_switcher/index.ts, components/global/product_switcher/product_switcher.tsx, components/global/product_switcher_menu/index.ts, components/global/saved_posts_button/index.ts, components/global/saved_posts_button/saved_posts_button.tsx, components/global/settings_button/index.ts, components/global/settings_button/settings_button.tsx, components/global/user_guide_dropdown/user_guide_dropdown.tsx, components/root/root.jsx, package.json
@nevyangelova, proposed ui updates for Global Header.
You'll notice:
- segmenting header into left, center and right components
- using semantic elements (still need to work on this)
- broke buttons out into separate components to keep functionality segregated
- didn't have time to port the functionality for all of these yet, so there are just place holders in some cases
- added spacing between elements per designs (still a bit of work to do here)
I didn't get a chance to do everything I was hoping (so I'm not 100% happy with where things are), but as I have a holiday today (Monday) with family coming over, I won't be able to finish and don't want to leave you hanging.
What needs to be done:
- add in missing functionality for some of the buttons
- add in tool tips
- finish menu structure, …
=> WIP: Global Header UI updates/additions

components/next_steps_view/next_steps_view.scss
This fixes a known overflow-y on iOS. See https://stackoverflow.com/questions/35469227/overflow-y-not-working-in-safari-inside-a-modal
[MM-37065](https://mattermost.atlassian.net/browse/MM-37065?atlOrigin=eyJpIjoiMDEwZWQ4NTMxMDg4NGY2NGFjZjM2ZGVmM2Q3YzJmZWIiLCJwIjoiaiJ9)
```release-note
NONE
```
=> [MM-37065] - No way to complete onboarding in mobile view

components/next_steps_view/next_steps_view.scss
Cherry pick of #8525 on cloud.
/cc  @AGMETEOR
=> Automated cherry pick of #8525

components/admin_console/data_retention_settings/custom_policy_form/custom_policy_form.scss, components/admin_console/data_retention_settings/data_retention_settings.scss, components/admin_console/data_retention_settings/global_policy_form/global_policy_form.scss, components/admin_console/jobs/table.scss, components/card/card.scss, components/payment_form/payment_form.scss, sass/routes/_admin-console.scss, sass/routes/_backstage.scss
Cherry pick of #8435 on cloud.
=> Automated cherry pick of #8435

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
* Upgrading German to official language
* Upgrading German to offical language
* ran update snaphot
Co-authored-by: Tom De Moor <tom@controlaltdieliet.be>
```release-note
```
=> Upgrading german to official language (#8517)

e2e/cypress/integration/accessibility/accessibility_image_spec.js, e2e/cypress/integration/account_settings/general/nickname_spec.js, e2e/cypress/integration/enterprise/ldap/ldap_guest_spec.js, e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js, e2e/cypress/integration/enterprise/visual_regression/system_console/authentication_section_spec.js, e2e/cypress/integration/enterprise/visual_regression/system_console/compliance_section_spec.js, e2e/cypress/integration/interactive_dialog/full_dialog_spec.js, e2e/cypress/integration/messaging/message_reaction_spec.js, e2e/cypress/integration/messaging/strikethrough_spec.js, e2e/cypress/integration/team_settings/invite_members_spec.js
- Fix failing e2e
NA
```release-note
NONE
```
=> Cypress/E2E Maintenance: Fix broken tests

components/root/root.jsx
Cherry pick of #8311 on release-5.38.
/cc  @jespino
=> Automated cherry pick of #8311

components/sidebar/__snapshots__/sidebar.test.tsx.snap, components/sidebar/add_channel_dropdown.tsx, components/sidebar/channel_navigator/channel_navigator.tsx, components/sidebar/sidebar.tsx, components/widgets/menu/menu_items/menu_item.scss, i18n/en.json
This PR adds a new invite people button to sidebar channel dropdown
https://mattermost.atlassian.net/browse/MM-37504
```release-note
NONE
```
=> Mm 37504 - add new invite people button to sidebar channel dropdown

components/global/global_header.scss, components/sidebar/channel_navigator/channel_navigator.tsx, components/sidebar/sidebar_header/dropdown/sidebar_header_dropdown_button.tsx
this PR aims at unifying the channel navigator between web and desktop app when the global header is enabled.
there is also a small fix included that aligns the header info burger button.
[MM-37834](https://mattermost.atlassian.net/browse/MM-37834)
```release-note
test
```
=> feature: unify channel navigator in web and desktop app

e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js, e2e/cypress/integration/onboarding/use_team_invite_link_to_sign_up_spec.js, e2e/cypress/integration/team_settings/closed_team_invite_with_non_mattermost_domain_spec.js, e2e/cypress/integration/team_settings/closed_team_invite_with_specific_domain_spec.js, e2e/cypress/integration/team_settings/helpers.js, e2e/cypress/support/api/cloud_default_config.json, e2e/cypress/support/api/on_prem_default_config.json
Disable onboarding flow by default in Cypress
Cypress report - https://community.mattermost.com/core/pl/dnp666h1ejrhu8eo739yzei8fc
```release-note
NONE
```
=> Cypress/E2E: Disable onboarding flow by default in Cypress

sass/components/_tutorial.scss
Fix placement of tips 3 (add channels tip) and 4 (menu tip)
https://mattermost.atlassian.net/browse/MM-37956
none
No release note: this is for a bug fix to new UI that has not yet been released.
```release-note
NONE
```
=> update tip placement

components/channel_layout/center_channel/index.ts
This PR fixes a regression that was caused by this PR https://github.com/mattermost/mattermost-webapp/pull/8528
[MM-37932](https://mattermost.atlassian.net/browse/MM-37932)
```release-note
none
```
=> [MM-37932] - Onboarding flow in center channel comes back for existing users

components/admin_console/admin_definition.jsx, packages/mattermost-redux/src/types/general.ts
Cherry pick of #8554 on cloud.
```release-notes
NONE
```
=> Automated cherry pick of #8554

components/channel_layout/center_channel/index.ts
Cherry pick of #8599 on cloud.
/cc  @AGMETEOR
```release-notes	
NONE
```
=> Automated cherry pick of #8599

components/user_settings/display/index.ts, components/user_settings/display/manage_timezones/index.ts, components/user_settings/display/manage_timezones/manage_timezones.test.tsx, components/user_settings/display/manage_timezones/manage_timezones.tsx, components/user_settings/display/user_settings_display.test.tsx, components/user_settings/display/user_settings_display.tsx, package-lock.json, package.json, packages/mattermost-redux/src/actions/general.test.js, packages/mattermost-redux/src/actions/general.ts, packages/mattermost-redux/src/actions/timezone.ts, packages/mattermost-redux/src/client/client4.ts, packages/mattermost-redux/src/reducers/entities/general.ts, packages/mattermost-redux/src/selectors/entities/general.ts, packages/mattermost-redux/src/selectors/entities/timezone.ts, packages/mattermost-redux/src/store/initial_state.ts, packages/mattermost-redux/src/types/general.ts, packages/mattermost-redux/src/utils/timezone_utils.ts, utils/timezone.jsx
Cherry pick of #8532 on cloud.
```release-note
Updating Account Settings > Display > Timezone to be more user friendly
```
=> Automated cherry pick of #8532

sass/components/_tutorial.scss
Cherry pick of #8602 on cloud.
/cc  @neallred
=> Automated cherry pick of #8602

components/sidebar/add_channel_dropdown.tsx, components/widgets/menu/menu_items/menu_item.scss, i18n/en.json, sass/layout/_sidebar-left.scss
Cherry pick of #8577 on cloud.
=> Automated cherry pick of #8577

components/channel_header/channel_header.js
Cherry pick of #8593 on cloud.
=> Automated cherry pick of #8593

components/global/product_switcher.tsx, components/global/product_switcher_menu/product_switcher_menu.tsx, components/widgets/menu/menu_items/menu_item.tsx, components/widgets/menu/menu_items/menu_item_action.test.tsx, components/widgets/menu/menu_items/menu_item_action.tsx
Cherry pick of #8594 on cloud.
=> Automated cherry pick of #8594

components/global/global_header.tsx, components/global/history_buttons/history_buttons.tsx
Cherry pick of #8571 on cloud.
=> Automated cherry pick of #8571

sass/routes/_about-modal.scss
Cherry pick of #8586 on cloud.
=> Automated cherry pick of #8586

sass/routes/_admin-console.scss
Cherry pick of #8587 on cloud.
=> Automated cherry pick of #8587

components/admin_console/data_retention_settings/data_retention_settings.scss, sass/routes/_admin-console.scss
Cherry pick of #8588 on cloud.
=> Automated cherry pick of #8588

components/global/global_header.scss
Cherry pick of #8595 on cloud.
=> Automated cherry pick of #8595

components/global/global_header.scss, components/global/global_header.tsx, components/global/product_switcher_tip/product_switcher_tip.test.tsx, plugins/registry.js, types/store/plugins.ts
Cherry pick of #8581 on cloud.
=> Automated cherry pick of #8581

components/root/root.jsx
This PR adds the websockets client to the products, and wraps their components in a `LoggedIn` component so the client is correctly initialised.
```release-note
Added websocket client to products
```
=> Adds websockets to products

components/root/root.jsx
Cherry pick of #8608 on cloud.
=> Automated cherry pick of #8608

plugins/registry.js
Cherry pick of #8617 on cloud.
=> Automated cherry pick of #8617

package-lock.json
Cherry pick of #8609 on cloud.
/cc  @hmhealey
=> Automated cherry pick of #8609

components/global/product_switcher.tsx, components/global/product_switcher_menu/product_switcher_menu.tsx
Cherry pick of #8575 on cloud.
=> Automated cherry pick of #8575

components/channel_layout/channel_controller.jsx, components/root/root.jsx
Cherry pick of #8621 on cloud.
/cc  @jespino
=> Automated cherry pick of #8621

components/global/global_header.scss, components/user_settings/display/index.ts, selectors/global_header.ts
Cherry pick of #8561 on cloud.
=> Automated cherry pick of #8561

sass/layout/_webhooks.scss
Cherry pick of #8534 on cloud.
/cc  @larkox
=> Automated cherry pick of #8534

components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap, components/rhs_comment/rhs_comment.jsx, components/threading/global_threads_link/global_threads_link.tsx, e2e/cypress/integration/collapsed_reply_threads/crt_settings_spec.js, e2e/cypress/integration/collapsed_reply_threads/following_spec.js, e2e/cypress/integration/collapsed_reply_threads/replies_spec.js, e2e/cypress/integration/collapsed_reply_threads/unread_spec.js, e2e/cypress/support/api/cloud_default_config.json, e2e/cypress/support/api/on_prem_default_config.json, e2e/cypress/support/api/preference.d.ts, e2e/cypress/support/api/preference.js, e2e/cypress/support/ui/account_settings_modal.d.ts, e2e/cypress/support/ui/account_settings_modal.js, e2e/cypress/support/ui/sidebar_left.d.ts, e2e/cypress/support/ui/sidebar_left.js, e2e/cypress/support/ui_commands.js, selectors/views/threads.ts
Cherry pick of #8494 on cloud.
/cc  @koox00
=> Automated cherry pick of #8494

components/threading/global_threads/thread_list/thread_list.scss
Cherry pick of #8649 on cloud.
=> Automated cherry pick of #8649

e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js, e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js, e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js, e2e/cypress/utils/timezone.js, e2e/package-lock.json, e2e/package.json
Fixed failed tests on timezone, theme sidebar and navigation
none, failed on daily due to recent changes.
```release-note
NONE
```
=> Cypress/E2E: Fixed failed tests on timezone, theme sidebar and navigation

components/status_dropdown/status_dropdown.tsx
Cherry pick of #8682 on cloud.
=> Automated cherry pick of #8682

utils/utils.jsx
fixes text coloring in RHS for highlighted hashtags
Fixes [MM-36926](https://mattermost.atlassian.net/browse/MM-36926)
```release-note
NONE
```
=> fixes color inheritance on highlighted hashtags in RHS

utils/utils.jsx
Cherry pick of #8679 on cloud.
=> Automated cherry pick of #8679

components/sidebar/sidebar_header/sidebar_header.tsx, selectors/global_header.ts
Cherry pick of #8651 on cloud.
=> Automated cherry pick of #8651

components/custom_status/custom_status_suggestion.tsx
Cherry pick of #8687 on cloud.
=> Automated cherry pick of #8687

components/markdown_image_expand/markdown_image_expand.tsx, components/post_view/embedded_bindings/embedded_binding/__snapshots__/embedded_binding.test.tsx.snap, components/post_view/embedded_bindings/embedded_binding/embedded_binding.tsx, components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap, components/post_view/message_attachments/message_attachment/message_attachment.tsx
Cherry pick of #8630 on cloud.
/cc  @larkox
=> Automated cherry pick of #8630

components/global/product_switcher.tsx, components/global/product_switcher_menu/product_switcher_menu.tsx, components/widgets/menu/menu_items/menu_item.tsx, components/widgets/menu/menu_items/menu_item_action.test.tsx, components/widgets/menu/menu_items/menu_item_action.tsx
Cherry pick of #8677 on cloud.
=> Automated cherry pick of #8677

components/suggestion/switch_channel_provider.jsx
Fix quick channel switcher mention counts not following collapsed threads logic.
https://mattermost.atlassian.net/browse/MM-38118
```release-note
Fix quick channel switcher mention counts not following collapsed threads logic
```
=> MM-38118 Ensure quick channel switcher mentions obey collapsed threads

.gobom.json
Add the dependency track config that will be used inside the internal GitLab to generate the dependencies and send to the dep track system
JIRA: https://mattermost.atlassian.net/browse/DOPS-582
```release-note
NONE
```
=> security: add dependency track configuration

components/global/product_switcher_menu/product_switcher_menu.tsx, components/widgets/menu/menu_items/menu_item_external_link.test.tsx, components/widgets/menu/menu_items/menu_item_external_link.tsx
Cherry pick of #8695 on release-6.0.
=> Automated cherry pick of #8695

actions/websocket_actions.jsx, packages/mattermost-redux/src/actions/teams.ts
Cherry pick of #8702 on release-5.39.
=> Automated cherry pick of #8702

components/global/global_header.scss, components/search/search.tsx, selectors/global_header.ts
Cherry pick of #8671 on release-6.0.
=> Automated cherry pick of #8671

components/global/product_switcher.tsx, i18n/en.json
Cherry pick of #8742 on release-6.0.
=> Automated cherry pick of #8742

components/threading/channel_threads/thread_footer/thread_footer.scss
Cherry pick of #8680 on release-5.39.
=> Automated cherry pick of #8680

packages/mattermost-redux/src/actions/threads.ts, packages/mattermost-redux/src/client/client4.ts
- Be consistent with query parameter names
- https://mattermost.atlassian.net/browse/MM-36792
- Has server changes: https://github.com/mattermost/mattermost-server/pull/18260
- Has mobile changes: https://github.com/mattermost/mattermost-mobile/pull/5643
```release-note
NONE
```
=> [MM-36792] Consistent query param names

components/global/global_header.scss
Cherry pick of #8730 on release-6.0.
=> Automated cherry pick of #8730

package-lock.json, package.json
Cherry pick of #8736 on release-6.0.
=> Automated cherry pick of #8736

sass/components/_post-right.scss
Cherry pick of #8705 on release-6.0.
=> Automated cherry pick of #8705

actions/post_actions.test.js, utils/browser_history.jsx, utils/server_version.test.tsx, utils/server_version.tsx, utils/user_agent.tsx
Cherry pick of #8522 on release-6.0.
=> Automated cherry pick of #8522

e2e/cypress/integration/messaging/post_html_table_spec.js, utils/paste.tsx
Cherry pick of #8760 on release-6.0.
=> Automated cherry pick of #8760

components/post_view/post/post.jsx, sass/layout/_markdown.scss
Cherry pick of #8754 on release-6.0.
/cc  @koox00
=> Automated cherry pick of #8754

components/global/global_header.tsx, components/global/product_switcher.tsx
Cherry pick of #8648 on release-6.0.
=> Automated cherry pick of #8648

components/post_view/post/post.jsx
Cherry pick of #8759 on release-6.0.
=> Automated cherry pick of #8759

components/global/product_switcher.tsx, components/global/product_switcher_menu/product_switcher_menu.tsx, components/widgets/menu/menu_group.tsx
Cherry pick of #8678 on release-6.0.
=> Automated cherry pick of #8678

.gobom.json
cherry pick of https://github.com/mattermost/mattermost-webapp/pull/8741
n/a
```release-note
NONE
```
=> security: add dependency track configuration (#8741)

package.json
Cherry pick of #8774 on release-6.0.
=> Automated cherry pick of #8774

components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap, components/threading/channel_threads/thread_footer/thread_footer.test.tsx, components/threading/channel_threads/thread_footer/thread_footer.tsx, components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap, components/threading/global_threads/thread_item/thread_item.tsx
Cherry pick of #8664 on release-6.0.
/cc  @koox00
=> Automated cherry pick of #8664

.editorconfig
Updates .editorconfig to handle typescript files
```release-note
NONE
```
=> Updates .editorconfig to handle typescript files

components/next_steps_view/steps.ts, sass/layout/_sidebar-left.scss
Cherry pick of #8781 on release-6.0.
=> Automated cherry pick of #8781

components/threading/global_threads/thread_item/thread_item.test.tsx, components/threading/global_threads/thread_item/thread_item.tsx
Thread Root Post
fixes [https://mattermost.atlassian.net/browse/MM-36789](https://mattermost.atlassian.net/browse/MM-36789)
NONE
```release-note
* Show ('message deleted') in global thread on root post message delete
```
=> [MM-36789] Thread Root Post

components/compass_theme_provider/compass_theme_provider.tsx, components/global/global_header.scss, components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap, components/status_dropdown/status_dropdown.tsx, components/widgets/menu/menu_items/menu_item_action.tsx, components/widgets/menu/menu_items/submenu_item.test.tsx, components/widgets/menu/menu_items/submenu_item.tsx, package-lock.json, package.json, sass/components/_status-icon.scss
Design fixes for the status dropdown that were outstanding in https://github.com/mattermost/mattermost-webapp/pull/8585
https://mattermost.atlassian.net/browse/MM-37976
```release-note
NONE
```
=> [MM-37814] - Adjust status dropdown according to design

sass/components/_post-right.scss
Cherry pick of #8755 on release-6.0.
/cc  @koox00
=> Automated cherry pick of #8755

components/threading/global_threads/thread_item/thread_item.test.tsx, components/threading/global_threads/thread_item/thread_item.tsx
Cherry pick of #8708 on release-6.0.
=> Automated cherry pick of #8708

components/global/global_header.tsx, components/global/hooks.tsx, components/next_steps_view/steps.ts
Cherry pick of #8796 on release-6.0.
=> Automated cherry pick of #8796

components/admin_console/admin_definition.jsx, i18n/en.json, i18n/en_AU.json
Cherry pick of #8817 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8817

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
```
Italian and Polish are degraded to Alpha
```
```release-note
```
=> downgrading Italian and Polish to Alpha

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
Cherry pick of #8818 on release-6.0.
/cc  @ctlaltdieliet
=> Automated cherry pick of #8818

components/sidebar/invite_members_button.tsx, components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap, components/sidebar/sidebar_category/sidebar_category.tsx, sass/layout/_sidebar-left.scss
Cherry pick of #8832 on release-6.0.
/cc  @neallred
=> Automated cherry pick of #8832

components/widgets/menu/menu_items/menu_start_trial.test.tsx, components/widgets/menu/menu_items/menu_start_trial.tsx
Cherry pick of #8827 on release-6.0.
/cc  @AGMETEOR
=> Automated cherry pick of #8827

components/more_channels/more_channels.tsx, components/more_direct_channels/more_direct_channels.tsx
Fixes https://github.com/mattermost/mattermost-server/issues/18360
=> remove bodyOnly prop

components/sidebar/sidebar_next_steps/sidebar_next_steps.scss
Cherry pick of #8805 on release-6.0.
=> Automated cherry pick of #8805

actions/notification_actions.jsx, actions/notification_actions.test.js, i18n/en.json
Cherry pick of #8778 on release-6.0.
/cc  @koox00
=> Automated cherry pick of #8778

sass/components/_post.scss, utils/utils.jsx
Cherry pick of #8797 on release-6.0.
=> Automated cherry pick of #8797

components/channel_layout/channel_identifier_router/actions.ts
Cherry pick of #8739 on release-6.0.
=> Automated cherry pick of #8739

components/threading/global_threads/thread_item/thread_item.tsx
Cherry pick of #8815 on release-6.0.
=> Automated cherry pick of #8815

components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap, components/post_view/post_message_preview/post_message_preview.tsx, sass/components/_post.scss
Cherry pick of #8776 on release-6.0.
=> Automated cherry pick of #8776

components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
Looks like some [prior work](https://github.com/mattermost/mattermost-webapp/pull/8776) missed updating some of the snapshots.
https://mattermost.atlassian.net/browse/MM-38158
None
N/A
```release-note
NONE
```
=> fix snapshots

components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap, components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.jsx.snap, components/admin_console/team_channel_settings/team/details/__snapshots__/team_modes.test.jsx.snap, components/admin_console/team_channel_settings/team/details/index.js, components/admin_console/team_channel_settings/team/details/team_details.jsx, components/admin_console/team_channel_settings/team/details/team_modes.jsx, components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.tsx.snap, components/admin_console/team_channel_settings/team/list/index.ts, components/admin_console/team_channel_settings/team/list/team_list.tsx
Cherry pick of #8873 on release-6.0.
/cc  @mkraft
=> Automated cherry pick of #8873

utils/browser_history.jsx
Cherry pick of #8878 on release-6.0.
=> Automated cherry pick of #8878

e2e/cypress/integration/archived_channel/archive_channel_operations_spec.js, e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js, e2e/cypress/integration/channel/user_to_channel_admin_member_updates_manage_channel_members_modal_spec.js, e2e/cypress/integration/channel_sidebar/drag_and_drop_spec.js, e2e/cypress/integration/integrations/builtin_commands/groupmsg_command_spec.js, e2e/cypress/integration/integrations/builtin_commands/helper.js, e2e/cypress/integration/integrations/builtin_commands/invalid_commands_spec.js, e2e/cypress/integration/integrations/builtin_commands/invite_command_spec.js, e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js, e2e/cypress/integration/integrations/builtin_commands/user_status_spec.js, e2e/cypress/integration/integrations/slash_commands_spec.js, e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js, e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/not_open_emoji_picker_spec.js, e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_center_spec.js, e2e/cypress/integration/markdown/markdown_image_spec.js, e2e/cypress/integration/markdown/markdown_text_spec.js, e2e/cypress/integration/menus/status_dropdown_spec.js, e2e/cypress/integration/messaging/at_mentions_user_spec.js, e2e/cypress/integration/messaging/autocomplete_shown_each_channel_spec.js, e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js, e2e/cypress/integration/messaging/channel_and_posts_links_spec.js, e2e/cypress/integration/messaging/collapse_link_spec.js, e2e/cypress/integration/messaging/collapsed_message_spec.js, e2e/cypress/integration/messaging/ctrl_cmd_k_find_gm_by_matching_name_spec.js, e2e/cypress/integration/messaging/ctrl_cmd_k_open_dm_with_mouse_spec.js, e2e/cypress/integration/messaging/edit_message_spec.js, e2e/cypress/integration/notifications/at_mentions_spec.js, e2e/cypress/support/api/user.d.ts, e2e/cypress/support/api/user.js, e2e/cypress/support/ui/global_header.d.ts
Fix failed tests for v6.0
Test report - https://automation-dashboard.vercel.app/cycles/5e26dc79-bc96-4665-8d4e-c7491e7e8542
```release-note
NONE
```
=> Cypress/E2E: fix for failed tests

e2e/cypress/integration/messaging/message_reaction_spec.js, e2e/cypress/integration/messaging/message_spec.js, e2e/cypress/integration/messaging/post_options_menu_spec.js, e2e/cypress/integration/messaging/post_pre_header_spec.js, e2e/cypress/integration/messaging/post_textbox_height_spec.js, e2e/cypress/integration/messaging/private_channel_open_spec.js, e2e/cypress/integration/messaging/quick_send_spec.js, e2e/cypress/integration/messaging/typing_on_middle_spec.js, e2e/cypress/integration/search/results_post_spec.js
Fixed messaging test cases
```release-note
NONE
```
=> fixed messageing test cases

components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap, components/new_channel_modal/index.js, components/new_channel_modal/new_channel_modal.jsx, components/new_channel_modal/new_channel_modal.test.jsx
Cherry pick of #8844 on release-6.0.
/cc  @hmhealey
=> Automated cherry pick of #8844

sass/components/_post.scss
Cherry pick of #8867 on cloud.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #8867

components/admin_console/admin_definition.jsx, e2e/cypress/integration/system_console/ui_and_api/customization_spec.js, i18n/en.json
Cherry pick of #8892 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
=> Automated cherry pick of #8892

components/actions_menu/actions_menu.tsx, components/actions_menu/index.ts, components/post_view/post_info/index.ts, components/post_view/post_info/post_info.tsx, packages/mattermost-redux/src/actions/preferences.ts, packages/mattermost-redux/src/constants/preferences.ts, selectors/actions_menu.ts
=> WIP do not merge

e2e/cypress/integration/auth_sso/authentication_4_spec.js, e2e/cypress/integration/messaging/message_edit_post_clear_text_spec.js, e2e/cypress/integration/messaging/message_edit_post_with_attachment_spec.js, e2e/cypress/integration/messaging/message_emoji_jumbo_spec.js, e2e/cypress/integration/messaging/message_ephemeral_spec.js, e2e/cypress/integration/messaging/message_in_another_language_spec.js, e2e/cypress/integration/messaging/message_parse_spec.js, e2e/cypress/integration/messaging/message_pinning_unpinning_spec.js, e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js, e2e/cypress/integration/messaging/message_reply_scrollable_spec.js, e2e/cypress/integration/messaging/message_reply_too_long_spec.js, e2e/cypress/integration/messaging/message_shortlinking_spec.js, e2e/cypress/integration/messaging/message_with_gif_spec.js, e2e/cypress/integration/messaging/mobile_message_deletion_spec.js, e2e/cypress/integration/messaging/mobile_profile_popover_spec.js, e2e/cypress/integration/messaging/strikethrough_spec.js, e2e/cypress/integration/messaging/typing_should_show_up_when_editing_spec.js
=> fixed messaging test case

e2e/cypress/integration/auth_sso/authentication_4_spec.js, e2e/cypress/integration/messaging/message_edit_post_clear_text_spec.js, e2e/cypress/integration/messaging/message_edit_post_with_attachment_spec.js, e2e/cypress/integration/messaging/message_emoji_jumbo_spec.js, e2e/cypress/integration/messaging/message_ephemeral_spec.js, e2e/cypress/integration/messaging/message_in_another_language_spec.js, e2e/cypress/integration/messaging/message_parse_spec.js, e2e/cypress/integration/messaging/message_pinning_unpinning_spec.js, e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js, e2e/cypress/integration/messaging/message_reply_scrollable_spec.js, e2e/cypress/integration/messaging/message_reply_too_long_spec.js, e2e/cypress/integration/messaging/message_shortlinking_spec.js, e2e/cypress/integration/messaging/message_with_gif_spec.js, e2e/cypress/integration/messaging/mobile_message_deletion_spec.js, e2e/cypress/integration/messaging/mobile_profile_popover_spec.js, e2e/cypress/integration/messaging/strikethrough_spec.js, e2e/cypress/integration/messaging/typing_should_show_up_when_editing_spec.js
Cherry pick of #8914 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8914

NOTICE.txt
Cherry pick of #8906 on release-6.0.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #8906

components/custom_status/custom_status_modal.tsx
Cherry pick of #8918 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8918

e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js, e2e/cypress/integration/account_settings/general/nickname_spec.js, e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js, e2e/cypress/integration/enterprise/ldap_group/invite_bot_spec.js, e2e/cypress/integration/integrations/incoming_webhook/delete_incoming_webhook_spec.js, e2e/cypress/integration/integrations/incoming_webhook/incoming_webhook_is_image_only_spec.js, e2e/cypress/integration/integrations/incoming_webhook/setup_incoming_webhook_spec.js, e2e/cypress/integration/integrations/integrations_spec.js, e2e/cypress/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js, e2e/cypress/integration/notifications/deselect_username_mention_trigger_spec.js, e2e/cypress/integration/notifications/notification_preferences_do_not_save_spec.js, e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js, e2e/cypress/integration/signin_authentication/desktop_session_expire_spec.js, e2e/cypress/integration/system_console/lock_teammate_name_display_spec.js, e2e/cypress/integration/system_console/sidebar_link_navigation_not_cloud_spec.js, e2e/cypress/integration/system_console/sidebar_link_navigation_spec.js, e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js, e2e/cypress/integration/team_settings/teams_spec.js, e2e/cypress/support/ui/common.d.ts, e2e/cypress/support/ui/extend_testing_library.d.ts, e2e/cypress/support/ui/menu.d.ts, e2e/cypress/support/ui/menu.js, e2e/cypress/support/ui/post.d.ts, e2e/cypress/support/ui/post.js
Test report - https://automation-dashboard.vercel.app/cycles/773a3100-3239-40be-8f71-6dbf5404eb66
Other than fixes includes clean up of comments and removal of unused UI commands.
```release-note
NONE
```
=> Cypress/E2E: Fix tests for v6.0

e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js, e2e/cypress/integration/account_settings/general/nickname_spec.js, e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js, e2e/cypress/integration/enterprise/ldap_group/invite_bot_spec.js, e2e/cypress/integration/integrations/incoming_webhook/delete_incoming_webhook_spec.js, e2e/cypress/integration/integrations/incoming_webhook/incoming_webhook_is_image_only_spec.js, e2e/cypress/integration/integrations/incoming_webhook/setup_incoming_webhook_spec.js, e2e/cypress/integration/integrations/integrations_spec.js, e2e/cypress/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js, e2e/cypress/integration/notifications/deselect_username_mention_trigger_spec.js, e2e/cypress/integration/notifications/notification_preferences_do_not_save_spec.js, e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js, e2e/cypress/integration/signin_authentication/desktop_session_expire_spec.js, e2e/cypress/integration/system_console/lock_teammate_name_display_spec.js, e2e/cypress/integration/system_console/sidebar_link_navigation_not_cloud_spec.js, e2e/cypress/integration/system_console/sidebar_link_navigation_spec.js, e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js, e2e/cypress/integration/team_settings/teams_spec.js, e2e/cypress/support/ui/common.d.ts, e2e/cypress/support/ui/extend_testing_library.d.ts, e2e/cypress/support/ui/menu.d.ts, e2e/cypress/support/ui/menu.js, e2e/cypress/support/ui/post.d.ts, e2e/cypress/support/ui/post.js
Cherry pick of #8916 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8916

e2e/cypress/integration/bot_accounts/in_teams_and_channels_spec.js, e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js, e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_rhs_spec.js, e2e/cypress/support/ui/team.js
Cherry pick of #8930 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8930
