mattermost/mattermost-webapp

- components/announcement_bar/version_bar/__snapshots__/version_bar.test.tsx.snap
- components/announcement_bar/version_bar/version_bar.tsx
Change whitespace in refresh bar to be an `&nbsp;` instead of a `' '`.
https://mattermost.atlassian.net/browse/MM-37426
before:
after:
```release-note
Change whitespace in refresh bar so that it always displays to user.
```
> fix whitespace in refresh bar

- components/next_steps_view/steps.test.tsx
- components/next_steps_view/steps.ts
- components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx
- e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
- i18n/en.json
- i18n/en_AU.json
- Makes sure that when Getting Started steps are finished, the sidebar updates to "Next Steps and Tips"
- Fixes Modal text when closing Getting Started and Next Steps and Tips
[MM-37377](https://mattermost.atlassian.net/browse/MM-37377?atlOrigin=eyJpIjoiNzA4Y2VjNTQwODFiNGExMzkwYTRjMGJmNjRkNDI5NjkiLCJwIjoiaiJ9)
```release-note
NONE
```
> [MM-37377] - LHS does not update after Getting Started steps are complete

- .circleci/config.yml
- .gitlab-ci.yml
This is a reversion of a change that wasn't supposed to make it into master, which was causing builds to utilize an older version of mattermost-server than it should have.
n/a
n/a
```release-note
none
```
> Fix builds pointing at the wrong version

- components/rhs_thread/index.ts
- components/textbox/index.ts
- components/textbox/textbox.tsx
- components/threading/global_threads/thread_item/index.ts
- components/threading/global_threads/thread_pane/thread_pane.tsx
- components/threading/thread_viewer/index.ts
- packages/mattermost-redux/src/selectors/entities/posts.test.js
- packages/mattermost-redux/src/selectors/entities/posts.ts
Something definitely got messed up here, probably by me.
To make it optional, I had to fix the type of the arguments to a couple selectors to avoid making everything weird. I think this makes everything look nicer overall anyway.
```release-note
NONE
```
> Make rootId prop optional for Textbox

- .eslintrc.json
- components/channel_header_mobile/channel_info_button/channel_info_button.test.js
- components/overlay_trigger.test.tsx
- components/overlay_trigger.tsx
Eslint error when trying to use OverlayTrigger directly from react-bootstrap, which doesn't forward `Intl.Context` to overlay content.
```release-note
NONE
```
> ESLint overlay trigger error help message

- components/channel_layout/center_channel/center_channel.tsx
- sass/components/_post.scss
When turning on the collapsed replies there's a big gap between the
first and second consecutive post from the same person.
This commit removes that gap.
https://mattermost.atlassian.net/browse/MM-36646
_before_:
_after_:
```release-note
NONE
```
> MM-36646: reverts post paddings when CRT enabled

- e2e/cypress/integration/emoji/recently_used_emoji_spec.js
- e2e/cypress/integration/plugins/plugin_install_spec.js
- e2e/cypress/integration/plugins/plugin_startup_fail_spec.js
- e2e/cypress/plugins/index.js
This PR attempts to isolate and debug further the timeout error happening on the following specs:
1. recently_used_emoji_spec.js
2. plugin_install_spec.js
3. plugin_startup_fail_spec.js
- The `--disable-dev-shm-usage` for launching Chrome removes the limitation to Docker resource where Cypress is running. Such might solve the issue of hang up if the timeout error is due to some CPU/memory limitation.
- `@timeout_error` test metadata will be used to isolate the said plugins for further investigation in CI.
- The other one related to plugin is to only remove a specific plugin as much as possible.
```release-note
NONE
```
> Cypress/E2E: Add flag disabling limit to Docker resource when launching chrome, add "@timeout_error" metadata and only remove plugin by ID

- components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
- components/next_steps_view/download_section.tsx
- components/next_steps_view/next_steps_tips.tsx
- components/next_steps_view/next_steps_view.tsx
This PR refactors out the code to create a new component "DownloadSection" that contains a tip for users to download desktop or mobile apps. The component is then added to both the Getting Started and NextSteps and Tips pages
[MM-37460](https://mattermost.atlassian.net/browse/MM-37460?atlOrigin=eyJpIjoiNDc3YTU0NzA4ZjBiNDMxM2I5NTVmNmVmODljMGIzZjYiLCJwIjoiaiJ9)
----
```release-note
NONE
```
> [MM-37460] - Add tip for downloading desktop app to the Getting Started page

- components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- i18n/i18n.jsx
German translations are back at 100% and no need to keep German in Beta. We have multiple new maintainers for German now
None
```
```
```release-note
Reinstate German as official language. 
```
> Upgrading german to official language

- components/alert_banner.scss
This PR fixes a regression where the alert banners css style class name was changed from --sys to --system.
https://mattermost.atlassian.net/browse/MM-37333
Before:
After:
```release-note
NONE
```
> MM-37333 - fix info banner colors

- actions/websocket_actions.jsx
When the websocket reconnects we need to pull the thread unreads for other teams if CRT is enabled.
https://mattermost.atlassian.net/browse/MM-35972
```release-note
For collapsed reply threads fix a bug where thread unread state would not be updated on reconnect of the websocket
```
> MM-35972 Pull unread thread counts for other teams on websocket reconnect

- packages/mattermost-redux/src/reducers/entities/emojis.test.js
- packages/mattermost-redux/src/reducers/entities/emojis.ts
- packages/mattermost-redux/src/selectors/entities/emojis.ts
When using the emoji autocomplete, we'll end up frequently either receiving autocomplete results for emojis we've already received and sometimes we'll receive empty autocomplete results. Both of these caused `state.entities.emojis.emojis` to be modified even though they wouldn't have any actual changes on the app, so a bunch of components (mostly instances of the `Markdown` component) would re-render a lot more than they should. 
https://mattermost.atlassian.net/browse/MM-36977
https://github.com/mattermost/mattermost-webapp/pull/8480
```release-note
NONE
```
> MM-36977 Prevent unnecessary changes to emoji state

- components/global/product_switcher.tsx
improved and simplified the product icon rendering to a simple string or `none`
Skipping QA and UX reviews, since this currently has no impact on it.
```
NONE
```
```release-note
NONE
```
> improve `ProductSwitcher` product icon rendering

- components/channel_header/__snapshots__/channel_header.test.jsx.snap
- components/channel_header/channel_header.js
- components/no_results_indicator/no_results_indicator.tsx
- components/search_hint/__snapshots__/search_hint.test.tsx.snap
- components/search_hint/search_hint.tsx
The icon `icon-file-document-outline` was recently renamed in [Compass Icons](https://github.com/mattermost/compass-icons/commit/4b5b9f2d55fe2b1dd4c45b7ecf71fc0aff627e4b) to `icon-file-text-outline`, this PR reflects that change in the Webapp now that the Webapp is using the Compass Icons package directly.
```release-note
NONE
```
> Update compass-icon `icon-file-document-outline` to match icon font rename

- components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
- components/suggestion/command_provider/app_command_parser/app_command_parser.ts
- components/suggestion/command_provider/app_command_parser/tests/app_command_parser_test_data.ts
If we set the autocomplete position of a text field, it becomes the "rest" argument.
https://mattermost.atlassian.net/browse/MM-30460
```release-note
Add "rest field" to app command parser.
```
> Add rest field support

- components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
- e2e/cypress/integration/enterprise/cloud/onboarding/invite_member_by_email_spec.js
In the onboarding step for sending email invites, when "Finish" is clicked:
- If input has invalid emails they'll be validated and emails won't be sent. The step will also not complete
- If input has valid emails, they'll be sent, just like if the send button was pressed and step will complete
- if no emails are present in the input, clicking the finish step will simply finish the step
[MM-36842](https://mattermost.atlassian.net/browse/MM-36842?atlOrigin=eyJpIjoiMDRiZWZiOTgwNzA3NGVjNGIzNTI2MDA1MDIzNWY1OWIiLCJwIjoiaiJ9)
```release-note
NONE
```
> [MM-36842] - Send email invites when clicking Next button in Onboarding

- components/convert_channel_modal/convert_channel_modal.jsx
- components/convert_channel_modal/index.js
- packages/mattermost-redux/src/actions/channels.test.js
- packages/mattermost-redux/src/actions/channels.ts
- packages/mattermost-redux/src/client/client4.ts
Removing the convert channel endpoint and using `/channels/{channel_id}/privacy` instead
https://mattermost.atlassian.net/browse/MM-18391
https://github.com/mattermost/mattermost-server/pull/18015
https://github.com/mattermost/mattermost-api-reference/pull/650
```release-note
Removing the convert channel endpoint and using /channels/{channel_id}/privacy instead
```
> [MM-18391] Removing convert channel endpoint

- components/main_menu/main_menu.jsx
- components/sidebar/add_channel_dropdown.tsx
- components/widgets/menu/menu_items/menu_item.scss
- i18n/en.json
- plugins/test/__snapshots__/main_menu_action.test.jsx.snap
- sass/layout/_sidebar-left.scss
While working on https://github.com/mattermost/mattermost-webapp/pull/8569, we discovered that the "Add channel dropdown" menu with the same menu item as the channel sidebar header menu needed wording and sizing adjustments for consistency. This PR makes the necessary changes.
```release-note
NONE
```
> Matching text to channel sidebar header menu

- components/channel_header/channel_header.js
conditionally adds the global header height value to the channel header info `topOffset` value (if global header is enabled)
[MM-37455](https://mattermost.atlassian.net/browse/MM-37455)
| before | after |
|---|---|
|<img width="748" alt="Screenshot 2021-08-16 at 12 22 55" src="https://user-images.githubusercontent.com/32863416/129550245-a3229f6a-ba32-4a04-a072-7c03f47a405d.png">|<img width="748" alt="Screenshot 2021-08-16 at 12 23 20" src="https://user-images.githubusercontent.com/32863416/129550263-06c5b59f-f26c-4d68-ad18-93b7f11666c4.png">|
```release-note
NONE
```
> MM-37455: fix misplaced channel header info popover

- components/admin_console/admin_definition.jsx
- packages/mattermost-redux/src/types/general.ts
Certificate-based authentication under Experimental Features in System Console was shown/hidden checking the SAML license feature flag. In the upcoming product repackaging, SAML has been moved from highest level tier (Enterprise - former E20) to mid-level (Professional) while Certificate-based authentication feature had no change and should stay in the highest sku.
This PR changes the check to rely on the `ShortSkuName` of the license and will show the setting for high level skus only: Enterprise/E20.
https://mattermost.atlassian.net/browse/MM-36084
- Has server changes https://github.com/mattermost/mattermost-server/pull/18113
```release-note
NONE
```
> MM-36084 - Certificate Auth: Remove SAML dependency in license check

- components/convert_channel_modal/convert_channel_modal.jsx
- components/convert_channel_modal/index.js
- packages/mattermost-redux/src/actions/channels.test.js
- packages/mattermost-redux/src/actions/channels.ts
- packages/mattermost-redux/src/client/client4.ts
Cherry pick of #8484 on cloud.
```release-note
Removing the convert channel endpoint and using /channels/{channel_id}/privacy instead
```
> Automated cherry pick of #8484

- components/global/global_header.scss
added a few CSS rules to make the `.backstage` class to take up the entire viewport and be layered on top of the global header.
[MM-37784](https://mattermost.atlassian.net/browse/MM-37784)
| before | after |
|----|----|
|<img width="1306" alt="Screenshot 2021-08-16 at 14 00 18" src="https://user-images.githubusercontent.com/32863416/129560454-9b20aa95-2aa9-4a6e-8a67-5d949b411aad.png">|<img width="1306" alt="Screenshot 2021-08-16 at 14 00 25" src="https://user-images.githubusercontent.com/32863416/129560488-6ed71f61-6722-4067-a9e2-26f6e3306f9d.png">|
```release-note
NONE
```
> MM-37784: make integrations (backstage) take up the entire viewport

- components/admin_console/data_retention_settings/data_retention_settings.scss
- sass/routes/_admin-console.scss
This PR fixes dropdown menus theming in the System Console. The dropdown menus now use the System theme instead of the user's theme, which may make the menus difficult to see if the user is using a Dark theme.
This PR also deletes the now-duplicate code from `/components/admin_console/data_retention_settings/data_retention_settings.scss`, which was added as a part of https://github.com/mattermost/mattermost-webapp/pull/8435.
https://mattermost.atlassian.net/browse/MM-37561
None
Before fix:
After fix:
```release-note
Fixed dropdown menu theming in System Console
```
> [MM 37561] Fix dropdown menu theming in System Console

- sass/routes/_admin-console.scss
Fixes an issue where the system console's hamburger menu was improperly themed with the user's theming instead of the system console's theming.
Fixes https://mattermost.atlassian.net/browse/MM-37669
None
Before fix:
After fix:
```release-note
Fixed system console's hamburger menu theming
```
> [MM-37669] System console hamburger menu theming issue

- sass/routes/_about-modal.scss
Fixes an issue where the header border in the System Console's About Mattermost modal was faded and difficult to see.
https://mattermost.atlassian.net/browse/MM-37670
None
Before fix:
After fix:
```release-note
Fixes About Mattermost modal styling
```
> [MM-37670] System console about modal missing header border

- plugins/registry.js
To facilitate changing the tooltip text on playbooks depending on the context, support a React component when registering the tooltip text. This was actually already supported downstream, but wasn't correctly supported in the registration api.
Relates-to: https://mattermost.atlassian.net/browse/MM-37542
```release-note
Support React component in channel header tooltips registered by plugins.
```
> MM-37542: support tooltip react components

- package-lock.json
This was missing from the package-lock.json in the previous PR, so it gets added automatically by `npm install` all the time
```release-note
NONE
```
> Add timezones.json to the package-lock

- e2e/generate_test_cycle.js
- e2e/run_tests.js
- e2e/utils/file.js
Add ability to include or exclude test files by filename (thru `find` command) and metadata (thru `grep` or file content, already existing in excluding group).
This gives more flexibility to select files to test, like when:
- testing a PR which introduce new spec files that are not yet included in prod specs
- wanting to test specific spec files which require granular filter
```release-note
NONE
```
> Cypress/E2E: Add ability to include or exclude test files

- e2e/generate_test_cycle.js
- e2e/run_tests.js
- e2e/utils/file.js
This is minor correction to https://github.com/mattermost/mattermost-webapp/pull/8628
```release-note
NONE
```
> Cypress/E2E: Follow up fix to finding spec files

- sass/layout/_webhooks.scss
Fix message attachment fields alignment.
Fix https://github.com/mattermost/mattermost-plugin-aws-SNS/issues/66
Fix https://github.com/matterpoll/matterpoll/issues/391
Fix https://github.com/mattermost/mattermost-server/issues/17859
Fix https://mattermost.atlassian.net/browse/MM-36943
https://mattermost.atlassian.net/browse/MM-36943
None
Before:
```release-note
Fix bug that kept message attachment fields unaligned.
```
> [MM-36943] Fix message attachment fields alignment

- components/threading/global_threads/thread_list/thread_list.scss
CRT:fix two scrollbar issue in threads view. After increasing browser zoom to 175% or above double scrollbar starts appearing. 
[https://mattermost.atlassian.net/browse/MM-37233](https://mattermost.atlassian.net/browse/MM-37233)
NONE
```release-note
NONE
```
> [MM-37233] CRT:fix two scrollbar issue in threads view

- e2e/cypress/integration/channel_sidebar/helpers.js
- e2e/cypress/support/ui/channel_sidebar.js
Fixed failed test case on category muting 
N/A
> Cypress:e2e/fixed category muting test case

- components/markdown_image_expand/markdown_image_expand.tsx
- components/post_view/embedded_bindings/embedded_binding/__snapshots__/embedded_binding.test.tsx.snap
- components/post_view/embedded_bindings/embedded_binding/embedded_binding.tsx
- components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap
- components/post_view/message_attachments/message_attachment/message_attachment.tsx
- utils/message_html_to_component.jsx
There were some errors in markdown and attachment images (and related, in embedded bindings).
1. Attachment images were not handling the "onToggle" action. This made the "Show More" "Show Less" to still be visible and not properly working when we collapse the image.
2. Attachments (and many other markdown location) did not provide a "onImageHeightChanged" property. This would, in the end, not set the "onToggle" action, which make the attachment break.
In the Jira link you can see test steps to reproduce these issues consistently.
https://mattermost.atlassian.net/browse/MM-38003
```release-note
Fix crash when markdown images are present on the message attachments and embedded bindings.
```
> Fix attachment images

- components/status_dropdown/status_dropdown.tsx
this PR aims to potentially fix the "white screen of death" issue appearing in spinwick instances.
The issue first appeared after the global header got introduced in all instances.
PRs in which the error occurs (list might not be complete):
- #8645 
- #8648 
- #8651 
- #8677 
- #8678 
- #8679 
cc// @spirosoik @jgilliam17 @andrewbrown00 
```
NONE
```
```release-note
NONE
```
> added a guard to check for the currentUser in `status_dropdown.tsx`

- components/sidebar/sidebar_header/sidebar_header.tsx
- selectors/global_header.ts
changed the `toggle` appearance to `active` when the menus are open.
components that are changed:
1. `ProductSwitcher`
2. `UserGuideDropdown`
3. `SidebarHeader`
The `Avatar` active styling already got handled by @nevyangelova in #8585 
[MM-37799](https://mattermost.atlassian.net/browse/MM-37799)
|  component  |  before  |  after  |
|-----|-----|-----|
|  `ProductSwitcher`  |<img width="281" alt="Screenshot 2021-08-19 at 15 51 38" src="https://user-images.githubusercontent.com/32863416/130080997-32a0d796-aa36-4309-8d2c-18a7753f3479.png">|<img width="281" alt="Screenshot 2021-08-19 at 15 47 16" src="https://user-images.githubusercontent.com/32863416/130081019-a3b3edde-9f7d-4446-8bdb-24502fa39c9a.png">|
|  `UserGuideDropdown`  |<img width="231" alt="Screenshot 2021-08-19 at 15 52 43" …
> active state for iconbuttons in global header

- components/global/product_switcher.tsx
- components/global/product_switcher_menu/product_switcher_menu.tsx
- components/widgets/menu/menu_items/menu_item.tsx
- components/widgets/menu/menu_items/menu_item_action.test.tsx
- components/widgets/menu/menu_items/menu_item_action.tsx
This reverts #8594 since it added a bug to the existing webapp.
Adding UX and QA to check for correct restoration of previous behaviour.
[MM-37916](https://mattermost.atlassian.net/browse/MM-37916)
Tickets reporting this bug:
[MM-38019](https://mattermost.atlassian.net/browse/MM-38019)
[MM-38056](https://mattermost.atlassian.net/browse/MM-38056)
[MM-38057](https://mattermost.atlassian.net/browse/MM-38057)
#8594 
```release-note
NONE
```
> Revert "MM-37916: close product switcher on item click (#8594)"

- components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
- components/status_dropdown/status_dropdown.tsx
- sass/layout/_headers.scss
Small fix: DND submenu is too far from parent menu to mouse over to (submenu disappears before getting to it) as a result of margins not being overridden as intended due to a classname typo. This PR fixes that typo and corrects the DND submenu issue.
Update: Turns out the conditional for TimedDND feature flag was reversed, so the submenu was only showing when it's feature flag was disabled. Added a commit to this review to fix the conditional.
https://mattermost.atlassian.net/browse/MM-38119
Before:
After:
```release-note
NONE
```
> [MM-38119] Fix class name typo

- components/interactive_dialog/interactive_dialog.jsx
Disables browser autofill for Interactive Dialogs.
Fixes https://github.com/mattermost/mattermost-server/issues/18030
JIRA: https://mattermost.atlassian.net/browse/MM-37510
```release-note
NONE
```
> [MM-37510]: Disable autofill on interactive dialogs 

- actions/command.test.js
- actions/command.ts
- components/global/settings_button/settings_button.tsx
- components/main_menu/main_menu.jsx
- components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.tsx
- components/profile_popover/profile_popover.tsx
- components/sidebar/legacy_sidebar_header/dropdown/sidebar_header_dropdown.tsx
- components/sidebar/sidebar_header/dropdown/sidebar_header_dropdown.jsx
- components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
- components/status_dropdown/status_dropdown.tsx
- components/user_settings/modal/user_settings_modal.tsx
- i18n/en.json
- plugins/test/__snapshots__/main_menu_action.test.jsx.snap
This PR changes the tooltip text of the gear icon button and resulting modal from "Channel Preferences" to "Settings" to help avoid confusion between the button being used for settings for the Channel product or settings for the currently active channel ... includes translation id and string. The resulting Modal's title is also changing to "Settings".
Also, updated a variable name from `isContentChannelPreference` to `isContentProductSettings` for consistency.
https://mattermost.atlassian.net/browse/MM-38130
```release-note
NONE
```
> [MM-38130] Rename channel preferences tooltip and modal to settings

- actions/websocket_actions.jsx
- packages/mattermost-redux/src/actions/teams.ts
Do not overwrite current team's thread mention count on websocket reconnect and fetch threads again.
https://mattermost.atlassian.net/browse/MM-38121
```release-note
Fix re-connecting to the websocket causing thread mentions to be cleared in the UI with collapsed reply threads enabled.
```
> MM-38121 Do not overwrite current team's thread mention count on websocket reconnect

- components/global/product_switcher_menu/product_switcher_menu.tsx
- components/widgets/menu/menu_items/menu_item_external_link.test.tsx
- components/widgets/menu/menu_items/menu_item_external_link.tsx
The 'Download' and 'About' menu items were inadvertently added to the `Permissions.SYSCONSOLE_WRITE_PLUGINS` permissions gate when added during the Global Header push. This PR moves them back out so that they are accessible by all users and not just select admins.
https://mattermost.atlassian.net/browse/MM-37859
```release-note
NONE
```
> [MM-37859] Fix product switcher menu items

- components/global/product_switcher.tsx
- i18n/en.json
remove the first "headline" entry from the product switcher: `Open ...` since it did create some misunderstanding among users.
[MM-38189](https://mattermost.atlassian.net/browse/MM-38189)
```release-note
NONE
```
> [MM-38189] - removed `Open...` from the product switcher menu

- components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
- i18n/i18n.jsx
The maintainers for English-Australian and Hungarian reached for more than 3 months a full translation. These languages don't need a beta tag anymore #### Related Pull Requests
None
```
```
```release-note
Hungarian and English-Australian are now official languages. 
```
> Promoting hungarian and english australian

- components/global/global_header.scss
fixes focussed searchbar background color.
It was using the `--sidebar-text` variable, which led to an unreadable search field.
It now uses `--center-channel-bg` as mentioned in [this thread](https://community-daily.mattermost.com/core/pl/1148ypnr33nzzfj3dwxrbwuaue).
[MM-38085](https://mattermost.atlassian.net/browse/MM-38085)
|-----|-----|
|<img width="439" alt="Screenshot 2021-08-27 at 16 13 37" src="https://user-images.githubusercontent.com/32863416/131141502-ed612a17-146c-44a5-953c-47673a5c54a4.png">|<img width="439" alt="Screenshot 2021-08-27 at 16 12 29" src="https://user-images.githubusercontent.com/32863416/131141584-32ceca0b-97a7-4f81-8353-74335f0c6108.png">|
|-----|-----|
|<img width="439" alt="Screenshot 2021-08-27 at 16 13 21" …
> [MM-38085] - fixing focussed search field background color

- package-lock.json
- package.json
This PR updates the `@mattermost/compass-icons` package to get the updated product icons.
```release-note
NONE
```
> Update compass-icons to v0.1.8 for new product icons

- sass/components/_post-right.scss
This PR fixes a spacing issue where the username in permalink previews is misaligned in the RHS.
https://mattermost.atlassian.net/browse/MM-38049
None
Before fix:
After fix:
```release-note
Fixed permalink preview misalignment when viewed in RHS
```
> [MM-38049] Fix permalink preview username spacing

- components/post_view/post/post.jsx
- sass/layout/_markdown.scss
Removes the click to open thread functionality when clicking or
trying to select text in a code block or in-line code.
https://mattermost.atlassian.net/browse/MM-37603
```release-note
NONE
```
> MM-37603: click on code should not open the thread

- e2e/cypress/integration/messaging/post_html_table_spec.js
- utils/paste.tsx
We start making use of [`DOMParser`](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) to parse html tables from clipboard.  
I am assuming creating a parser is an efficient operation. Let me know if we should cache it or something like that.
https://mattermost.atlassian.net/browse/MM-38241
```release-note
NONE
```
> [MM-38241] Use DOMParser to parse tables from clipboard

- components/post_view/post/post.jsx
dotmenu on post is now closing correctly when clicking `Reply`.
@koox00 , @deanwhillier and @jgilliam17 please be extra thorough when checking for other menu items, since I had to remove a event propagation and I cannot tell if that might have side-effects.
[MM-38209](https://mattermost.atlassian.net/browse/MM-38209)
```release-note
NONE
```
> [MM-38209] - removed propagation stop on handler function

- sass/components/_popover.scss
change the user-profile popover username font-family from `Metropolis` to `Open Sans`
[MM-37708](https://mattermost.atlassian.net/browse/MM-37708)
|------|------|
|<img width="134" alt="Screenshot 2021-08-31 at 12 39 45" src="https://user-images.githubusercontent.com/32863416/131488545-3964764e-a17b-4e49-8334-fe4d54eaa03f.png">|<img width="157" alt="Screenshot 2021-08-31 at 12 39 22" src="https://user-images.githubusercontent.com/32863416/131488569-43f54578-33c6-4b8e-8dd0-f22762b63670.png">|
```release-note
NONE
```
> [MM-37708] - changed font-family to Open Sans on popover title

- sass/components/_post-right.scss
Timestamps and or new messages line was overlapping the text message
making it impossible to read, this commit fixes that.
https://mattermost.atlassian.net/browse/MM-37957
```release-note
NONE
```
> MM-37957: fixes overlapping separators in thread

- components/global/user_guide_dropdown/index.ts
A logged out user with global header enabled would crash for the root
URL. This was happening because we assumed current user exists when
querying on whether to show or not the tutorials or getting started
page.
This commit fixes that by defaulting those values to false and
guarding on current user.
```release-note
NONE
```
> Fixes "property.roles" of undefined

- components/admin_console/admin_definition.jsx
- components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
- components/admin_console/admin_sidebar/admin_sidebar.test.jsx
Features below were only checking for the existence of a license in System Console (assuming it would be available for both E10/E20). However, in Cloud Starter, there is a license present but these features should not be available:
- Announcement Banner
- Compliance Monitoring
This PR changes it so it checks for the actual Feature Flags in the license.
https://mattermost.atlassian.net/browse/MM-38159
```release-note
NONE
```
> MM-38159 - Fix license checks in System Console for Starter License

- packages/mattermost-redux/src/reducers/entities/channels/message_counts.test.js
- packages/mattermost-redux/src/reducers/entities/channels/message_counts.ts
fixes count of root posts should not be equal to the total posts if there are threads. See [discussion](https://community-daily.mattermost.com/core/pl/ynhi4n6w6pyztec8qrnzjdqpwr)
[MM-38420](https://mattermost.atlassian.net/browse/MM-38420)
```release-note
NONE
```
> [MM-38420] Fix root message being equal

- components/global/global_header.tsx
- components/global/hooks.tsx
- components/global/user_guide_dropdown/index.ts
- components/next_steps_view/steps.ts
in the last days we had some problems with our test-servers not showing a login screen because of a javascript error. In the global header we were accessing the currently logged in user (although there was none) and that resulted in breaking the application.
The root cause for this is that the global header is rendering regardless if a user is logged in pr not. Re-arranging the components in `root.jsx` did not really work out due to our current routing structure. 
the solution for now is to prevent rendering of the global header inside the global header component, by utilizing a new hook `useIsLoggedIn`.
this PR also reverts changes made in #8781 and #8791 
```
NONE
```
```release-note
NONE
```
> Bugfix - roles error with global header enabled

- build/emoji/emoji_gen.mjs
In some cases we have customers wishing to remove certain emoji from our built-in set.  This script accepts a file with emoji `shortname`s and excludes them from the source files that are used to build the final `mattermost-webapp` bundle.
No specific ticket link.
Examples:
From the `mattermost-webapp` directory, create a file with emoji shortnames, each on an individual line.  Like so:
```
flag-eg
flag-eh
flag-ta
flag-tw
```
Prior to building the whole `mattermost-webapp` project, run the following npm script, passing the file of excluded emojis:
```
mattermost-webapp$npm run make-emojis -- --excluded-emoji-file ./excluded-emoji.txt
```
Once this is complete, the whole `mattermost-webapp` build can be run, and the resulting client files will no longer have reference in the UI to the …
> Added support to exclude specific emoji by short name

- components/channel_layout/channel_identifier_router/actions.ts
PR fixes a `Cannot read property 'type' of undefined` error that could happen if the channel couldn't be found when joining as sysadmin.
https://mattermost.atlassian.net/browse/MM-38198
```release-note
Fixed an issue on joining a missing channel as sysadmin.
```
https://github.com/mattermost/mattermost-server/issues/18284
> Fix JS error on joining missing channel as sysadmin

- components/admin_console/admin_definition.jsx
- i18n/en.json
- i18n/en_AU.json
Fixing link for docs
https://mattermost.atlassian.net/browse/MM-38280
```release-note
NONE
```
> [MM-38280] Fixing doc link for permalinks

- .github/PULL_REQUEST_TEMPLATE.md
I am using comparison tables a lot in my PRs and therefore I am constantly typing them out by hand. 
This PR aims to provide a template to copy/paste in the `Screenshots` section of our current PR template for convenience. 
no ticket has been filed for this.
```release-note
NONE
```
> extends the `Screenshots` section in the PR template

- components/sidebar/sidebar_next_steps/sidebar_next_steps.scss
this fixes the colors for the getting started indicator element in the bottom of the left sidebar.
[MM-37694](https://mattermost.atlassian.net/browse/MM-37694)
|  |  before  |  after  |
|-----|-----|-----|
|  hover  |<img width="255" alt="Screenshot 2021-09-08 at 14 34 08" src="https://user-images.githubusercontent.com/32863416/132510010-6ca19cd2-f230-4eb1-a776-8e59fcbf38d0.png">|<img width="255" alt="Screenshot 2021-09-08 at 14 29 29" src="https://user-images.githubusercontent.com/32863416/132509769-60284f07-4a05-4058-af67-4ff363b9fbdc.png">
|  active  |<img width="255" alt="Screenshot 2021-09-08 at 14 34 13" src="https://user-images.githubusercontent.com/32863416/132510045-db3d90f9-7568-482e-b7d2-26e9f6cee42b.png">|<img width="255" alt="Screenshot 2021-09-08 at 14 29 39" …
> [MM-37694] - fixing getting started colors

- components/sidebar/invite_members_button.tsx
- components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
- components/sidebar/sidebar_category/sidebar_category.tsx
- sass/layout/_sidebar-left.scss
Fix whitespace of left hand side invite members button to match other left hand side items.
https://mattermost.atlassian.net/browse/MM-38466
none
before:
after:
```release-note
Fix whitespace of left hand side invite members button to match other left hand side items.
```
> match invite members button space with other lhs spacing

- components/widgets/menu/menu_items/menu_start_trial.test.tsx
- components/widgets/menu/menu_items/menu_start_trial.tsx
This PR takes care of an edge case where if the instance has never had a trial license used and currently has a non trial license loaded, the CTA shows up. This PR ensures that the CTA doesn't show in such a scenario.
[MM-38427](https://mattermost.atlassian.net/browse/MM-38427)
```release-note
NONE
```
> [MM-38427] - Start Trial option showing in Daily

- components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
- components/post_view/post_message_preview/post_message_preview.tsx
- sass/components/_post.scss
The show more indicator was showing when it wasn't needed.
https://mattermost.atlassian.net/browse/MM-38158
```release-note
NONE
```
> fixing show more button for message previews

- actions/command.ts
Add initial whitespace character in /code rendering which was not happening earlier.
Fixes https://github.com/mattermost/mattermost-server/issues/15538
```
NONE
```
Current Output:
```release-note
Changes the way /code is rendered in the web app
```
> [MM-22950] Add initial whitespace characters in /code rendering

- components/admin_console/admin_definition.jsx
- components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
- components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.jsx.snap
- components/admin_console/team_channel_settings/team/details/__snapshots__/team_modes.test.jsx.snap
- components/admin_console/team_channel_settings/team/details/index.js
- components/admin_console/team_channel_settings/team/details/team_details.jsx
- components/admin_console/team_channel_settings/team/details/team_modes.jsx
- components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.tsx.snap
- components/admin_console/team_channel_settings/team/list/index.ts
- components/admin_console/team_channel_settings/team/list/team_list.tsx
- components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
Enabled the team list and team details system console pages in team edition build.
https://mattermost.atlassian.net/browse/MM-38260
```release-note
Enabled the team list and team details system console pages in team edition build.
```
> MM-38260: Enabled the team list and team details system console pages in team edition build.

- utils/browser_history.jsx
desktop is sending an event back to the webapp and sometimes is not defined properly, while it gets fixed this should prevent errors from happening.
[MM-38630](https://mattermost.atlassian.net/browse/MM-38630), [community report](https://community-daily.mattermost.com/core/pl/z6g57troxbyitgsdee5jsoster)
https://github.com/mattermost/mattermost-webapp/pull/8522
```release-note
NONE
```
> [MM-38630] Don't error if there is no pathName defined on the message

- packages/mattermost-redux/src/types/cloud.ts
Represent last four digits of credit card as a string. The private code backing this has similar changes. It will make credit card numbers with leading digits of 0 in the last 4 digits show properly in the System Console, including invoices downloaded from the console.
Supporting PRs:
https://github.com/mattermost/customer-web-server/pull/529
https://github.com/mattermost/mattermost-server/pull/17996
https://mattermost.atlassian.net/browse/MM-31950
- There is also an accompanying server change: https://github.com/mattermost/mattermost-server/pull/17996
```release-note
Fixed display of last 4 credit card digits
```
> Last 4 credit card digits as a string

- components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
- components/new_channel_modal/index.js
- components/new_channel_modal/new_channel_modal.jsx
- components/new_channel_modal/new_channel_modal.test.jsx
Looking back at the diffs, we might have had some logic in this modal to manually control focus, but it was mostly removed a while back with only this `onBlur` left over. Without it, react-bootstrap's automatic focus trapping seems to work fine to keep the keyboard focus within the modal when tabbing around.
https://mattermost.atlassian.net/browse/MM-24370
```release-note
Fixed keyboard focus within New Channel modal
```
> MM-24370 Remove manual focus change from cancel button 

- sass/components/_post.scss
Fix compose message textbox background to match center channel background color when the around_input treatment is given, instead of taking on the highlight color.
https://mattermost.atlassian.net/browse/MM-38361
None
before:
after:
```release-note
NONE
```
> fix input background

- packages/mattermost-redux/src/utils/post_list.test.js
- packages/mattermost-redux/src/utils/post_list.ts
A small performance improvement I came across while working on https://mattermost.atlassian.net/browse/MM-28338. `makeGetPostsForIds` has some extra memoization that lets us work with a subset of posts a bit easier.
https://mattermost.atlassian.net/browse/MM-28338
```release-note
Slightly improved performance around rendering of system messages
```
> Improve memoization of makeCombineUserActivityPosts

- components/admin_console/admin_definition.jsx
- e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
- i18n/en.json
- i18n/en_AU.json
This PR updates text on the support email description in the console
[MM-38468](https://mattermost.atlassian.net/browse/MM-38468)
```release-note
NONE
```
> [MM-38468] - Webapp/System Console: Check if help text about customized Support Email is still accurate with the removal of tutorial screen

- components/custom_status/custom_status_modal.tsx
fixes Unable to set custom status with Don't clear option
Fixes [https://mattermost.atlassian.net/browse/MM-38414](https://mattermost.atlassian.net/browse/MM-38414)
NONE
|  before  |
|----|
| ![custom-status-issue-small](https://user-images.githubusercontent.com/16203333/134318517-b707d3b7-dd05-46dc-9802-cc9c7578c10e.gif) | 
| after |
| ![custom-status-issue](https://user-images.githubusercontent.com/16203333/134319671-30148d71-1208-4004-ad41-8d26b5e797f8.gif) |
```release-note
* Bug fix: set custom status with don't clear option
```
> [MM-38414] fixes Unable to set custom status with Don't clear option

- components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
- components/next_steps_view/next_steps_tips.tsx
- components/next_steps_view/next_steps_view.tsx
- i18n/en.json
Always display playbooks card.
https://mattermost.atlassian.net/browse/MM-38064
before:
after:
```release-note
Always show Tips & Next Steps Playabooks card.
```
> always show playbooks card

- sass/components/_modal.scss
This PR fixes a bug where a css selector with higher specificity was directly applying white to the channel name in the notification preferences modal for that channel. The overriding colour has been removed to allow the channel name to inherit the themed colour from it's parent.
https://mattermost.atlassian.net/browse/MM-38678
|----|----|
| ![image](https://user-images.githubusercontent.com/3245614/134390491-246a3753-4166-4c83-b11e-fdab682a07f2.png) | ![image](https://user-images.githubusercontent.com/3245614/134390364-acbdb567-4cfe-428b-ab72-448f6ea4879e.png) |
```release-note
NONE
```
> MM-38678 - fix theme colour bug

- sass/components/_post-right.scss
this PR fixes a spacing issue that occured in community daily (in the desktopapp) when opening a thread-view in the RHS.
The "Add comment" button was hidden in the overflow.
[MM-38578](https://mattermost.atlassian.net/browse/MM-38578)
```release-note
NONE
```
> [MM-38578] - fix for rhs bottom spacing issue

- components/markdown/__snapshots__/markdown.test.tsx.snap
- components/markdown/markdown.tsx
- components/post_markdown/__snapshots__/post_markdown.test.tsx.snap
- components/post_markdown/post_markdown.tsx
- components/post_view/post_edited_indicator/post_edited_indicator.tsx
- components/post_view/post_message_view/__snapshots__/post_message_view.test.tsx.snap
- components/post_view/post_message_view/post_message_view.test.tsx
- components/post_view/post_message_view/post_message_view.tsx
- i18n/en.json
- sass/components/_post.scss
- utils/datetime.ts
- utils/message_html_to_component.jsx
- utils/text_formatting.tsx
According to the [designs](https://www.figma.com/file/fVLSLjGls2d2LUvCqk2JMS/MM-29137-Message-Editing?node-id=630%3A240624) this PR moves the edit-indicator on posts inline and adds some more functionality in the form of a popover which holds information on when the post was last edited.
For this purpose I had to extend 2 functions that are responsible for rendering: `formatText` and `messageHtmlToComponent`, since the rendering of posts differs quite a bit depending on the content. Those are being called from the `Markdown` component (first `formatText` and afterwards `messageHtmlToComponent`).
**changes to `formatText`:**
I essentially remove a wrapping `<p>` tag if it exists and append an empty `<span>` with an id. The format of the id is `postEdited_${postId}`. This makes the span id …
> [MM-36551] - improvements to post edit indicator

- components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
- components/sidebar/invite_members_button.test.tsx
- components/sidebar/invite_members_button.tsx
- components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
- components/sidebar/sidebar_category/index.ts
- components/sidebar/sidebar_category/sidebar_category.test.tsx
- components/sidebar/sidebar_category/sidebar_category.tsx
- sass/layout/_sidebar-left.scss
- utils/constants.jsx
Invite members button is highlighted until the user interacts with it.
https://mattermost.atlassian.net/browse/MM-38803 , but first intended to be included with
https://mattermost.atlassian.net/browse/MM-38258
No release note; this has not been released and was intended to be part of the invite members button when we established that as the A/B test winner.
```release-note
NONE
```
> Highlight invite_members_button until user interacts with it

- components/sidebar/add_channel_dropdown.tsx
this PR adds the necessary changes to move the invite users button to the bottom of the menu of the plus menu button channels.
https://mattermost.atlassian.net/browse/MM-38311
Before:
After:
```release-note
NONE
```
> MM-38311 - invite people button to bottom of menu

- components/global/global_header.scss
Fix some lhs sidebar & team sidebar height issues when both the global header and the announcement bar are enabled. In the CWS linked spinwick, users should see the announcement bar from the free trial, enabling testing.
https://mattermost.atlassian.net/browse/MM-38326
before:
after:
```release-note
NONE
```
> Mm 38326 getting started position

- components/multiselect/multiselect.tsx
`utils.jsx` isn't typed, so `localizeMessage` returning the wrong type for that prop wasn't caught by the type checker.
https://mattermost.atlassian.net/browse/MM-38747
```release-note
NONE
```
> MM-38747 Fixed crash caused by incorrect prop

- components/purchase_modal/purchase_modal.tsx
When a customer is upgrading to Enterprise from professional, we want to only show the Enterprise option.
https://mattermost.atlassian.net/browse/MM-38140
none
|----|----|
| 
| 
|
```release-note
NONE
```
> MM-38140 - show only enterprise for professional upgrade

- components/emoji_picker/components/emoji_picker_preview.jsx
- components/emoji_picker/index.js
This allows the emoji picker to be shown outside the context of a team. This is needed for example to show the emoji picker when you are in boards, where the team is not part of the context (for now).
mattermost/focalboard#1286
```release-note
NONE
```
> This allows the emoji picker to be shown outside the context of a team

- components/needs_team/index.ts
- components/needs_team/needs_team.test.tsx
- components/needs_team/needs_team.tsx
- components/root/root.jsx
- components/root/root.test.jsx
When using a single theme for all teams that isn't the default team (Denim), logging out and in again incorrectly applies the default theme (Denim) until the browser is refreshed, at which point the correct theme is applied. This does not happen when using per-team themes.
For some reason, the `NeedsTeam` component that handles applying the users selected theme when it changes, is not updated following initialization to trigger applying the users theme when sharing a single theme across all teams but it is updated if using per-team themes. In both cases, the users selected theme is correctly passed as a prop to the `NeedsTeam` component.
I spent a fair amount of time trying to track down why this is happening, but didn't get very far so left the exploration to another day. Since we now …
> [MM 38105] Bug fix: apply theme in root component instead of needs team component

- utils/message_html_to_component.jsx
- utils/text_formatting.tsx
this PR removes an extra whitespace from messages, when no edit indicator is being rendered. This led to several failing cypress tests.
[MM-38854](https://mattermost.atlassian.net/browse/MM-38854)
```release-note
NONE
```
> [MM-38854] - remove extra space from message when no edit indicator is present

- components/global/product_switcher.tsx
Given the prominence of the product switcher button and challenges with rendering the 9 square grid icon at such a small size, we are increasing the icon size for this single use case. This corrects a rendering challenge of the icon on non-retina screens and especially on Linux.
See conversation here for context and details: https://community-daily.mattermost.com/core/pl/yk3u6xqoqbddjnz79qjieqcwfw
|----|----|
| ![image](https://user-images.githubusercontent.com/3245614/134529333-cef42c9a-28ee-4ed9-aaf3-e4e813ae285a.png) ![image](https://user-images.githubusercontent.com/3245614/134530124-e77b4b59-2b37-4948-92fd-a43c8872f3be.png)| ![image](https://user-images.githubusercontent.com/3245614/134529398-fbb3f800-4dba-440b-918b-7f4eecc960ed.png) …
> Bug fix: Product Switcher button icon size increase

- actions/hooks.js
- actions/hooks.test.js
- components/edit_post_modal/edit_post_modal.test.tsx
- components/edit_post_modal/edit_post_modal.tsx
- components/edit_post_modal/index.js
- plugins/registry.js
PR adds a new `registerMessageWillBeUpdatedHook(newPost, oldPost)` to intercept edited messages before sending them to the server.
This was surprisingly missing given we offer similar functionality server-side and it was posing certain limitations: for example, this was brought up by a user that is currently implementing an e2e encryption plugin which needs a way to manipulate messages before they hit the server, whether they are new or updated.
https://mattermost.atlassian.net/browse/MM-38274
```release-note
Added new registerMessageWillBeUpdatedHook(newPost, oldPost) client-side plugin hook to intercept edited messages.
```
> [MM-38274] Implement registerMessageWillBeUpdatedHook

- components/suggestion/suggestion_list.jsx
due to some misunderstanding and a regression coming in by another PR the `SuggestionList` inside the quick switch modal was rendering type-dividers for the returned results.
I had a PR open for fixing it (#8963), but since I did not have all information on channel request/sorting logic within it and the number of commits that were already in that PR it was easier to provide a new PR for a fix.
[MM-38850](https://mattermost.atlassian.net/browse/MM-38850)
**showing recent channels with divider**
**after typing the results have no divider**
```release-note
NONE
```
> [MM-38850] - only render "recent" divider in quick switch modal

- actions/websocket_actions.jsx
When a websocket reconnect occurs and the `reconnectCallback` gets called,
we should only fetch user threads if CRT is enabled for the user.
```release-note
NONE
```
> Fixes fetching threads upon ws reconnection

- actions/storage.js
- store/index.js
Companion PR to #8978. Draft rehydration was occurring on any change to localforage when it was only required on first load. This had a side effect for multiple tabs on the same desktop app or browser causing a lot of unnecessary hydration resulting in high CPU usage.
@jgilliam17 for testing can you make sure drafts still persist correctly after refresh and channel switch? Particularly when typing quickly and immediately reloading the page.
https://mattermost.atlassian.net/browse/MM-38539
```release-note
Performance improvements for draft storage with multiple tabs open
```
> MM-38539 Only rehydrate drafts from localStorage on first load

- client/websocket_client.tsx
Upon websocket reconnect we are missing messages, this commit attempts
to fix that by always calling reconnectCallback regardless on whether
reliableWebSockets is enabled or not.
Some more info:
We keep track of websocket connection status on redux,
which is getting set to false onerror, and set true upon reconnect,
with reliable websockets enabled it didn't got set to true upon reconnection,
since `reconnectCallback` was responsible for that.
https://mattermost.atlassian.net/browse/MM-36932
```release-note
NONE
```
> MM-36932: always call reconnect callback

- sass/layout/_sidebar-left.scss
This PR adds the css changes to make the LHS invite members button to behave consistently on the hover event with the chat members DM links.
https://mattermost.atlassian.net/browse/MM-38540
Before:
After:
```release-note
NONE
```
>  MM-38540 - set consistent hover state for invite members button

- components/widgets/menu/menu_items/menu_item.scss
Makes the Try Enterprise CTA responsive
[MM-38836](https://mattermost.atlassian.net/browse/MM-38836)
Before
---
After
---
```release-note
NONE
```
> [MM-38836] - Try Enterprise for free option missing spacing in mobile webview

- components/payment_form/card_input.tsx
This PR updates the font in the CC field on the purchase modal to Open Sans
[MM-38833](https://mattermost.atlassian.net/browse/MM-38833)
https://github.com/mattermost/customer-web-server/pull/569
Before
---
After
---
```release-note
NONE
```
> [MM-38833] - Font within CC field is not consistent with other fields in payment form

- e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
- e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_2_spec.js
- e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js
- e2e/cypress/integration/messaging/direct_message_spec.js
- e2e/cypress/integration/messaging/permalink_message_edit_spec.js
- e2e/cypress/integration/messaging/strikethrough_spec.js
- e2e/cypress/integration/messaging/typing_should_show_up_when_editing_spec.js
Failed tests introduced by https://github.com/mattermost/mattermost-webapp/pull/8851
Test report - https://automation-dashboard.vercel.app/cycles/726450d3-2515-48ec-bae7-ceb55a246d35
Note: MM-T1239 is known product bug - https://mattermost.atlassian.net/browse/MM-38971
```release-note
NONE
```
> Cypress/E2E: Update tests related to edit indicator

- components/channel_layout/center_channel/center_channel.tsx
- components/channel_layout/playbook_runner.tsx
Navigating to `/:team/_playbooks/:playbookId/run` will switch to the last viewed channel in the team, defaulting to Town Square, and then will execute the `/playbook run-playbook` command, effectively rendering an interactive dialog to run the playbook.
This is needed to support the Run button in the Playbooks product, fixing a bug in the desktop where the app successfully changes the tab to Channels but still renders the interactive dialog in the Playbooks tab.
The video below shows the use-case: the user is in team `eligendi`, then goes to the Playbooks tab and opens a Playbook in team `minus`, when clicking on the Run button, the desktop app focuses the Channels tab, where the user is redirected to the last channel viewed in the playbook team (in this case `neque` in the team `minus`) …
> MM-38908: Handle /:team/_playbooks/:playbookId/run

- components/needs_team/needs_team.tsx
This PR stops the `needs_team` component from trying to go to a team with a reserved name. This is a workaround for the issue seen on the Desktop App when the server enables/disables/upgrades a plugin like Boards or Playbooks where it uses the base route instead of the `/plugins` route.
https://mattermost.atlassian.net/browse/MM-38536
```release-note
NONE
```
> [MM-38536] Stop needs_team from trying to join a team with a reserved name

- components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
- components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
This PR updates the invitation card subtitle in the onboarding to show correct text depending on whether the cloud subscription is paid or not. It also makes sure there's a default text for other instances (non-cloud)
It is an update of this PR https://github.com/mattermost/mattermost-webapp/pull/8944
[MM-38430](https://mattermost.atlassian.net/browse/MM-38430)
```release-note
NONE
```
> [MM-38430] - Onboarding invite shows limits that no longer apply-2

- components/admin_console/admin_definition.jsx
Fix to not show Oauth for Cloud Starter license as this feature is not available in Starter or E0. 
https://mattermost.atlassian.net/browse/MM-38780
```release-note
NONE
```
> MM-38780 - Do not show Oauth 2.0 for Starter

- components/status_dropdown/status_dropdown.scss
Do not disturb submenu item not taking full width
(Note: we need to enable TimeDND feature flag)
Fixes [https://mattermost.atlassian.net/browse/MM-38868](https://mattermost.atlassian.net/browse/MM-38868)
NONE
|----|----|
| ![image-20210927-235911](https://user-images.githubusercontent.com/16203333/135425382-ec7885a0-e627-43e0-9e89-1764c643dd2c.png) | <img width="572" alt="Screenshot 2021-09-30 at 2 47 44 PM" src="https://user-images.githubusercontent.com/16203333/135425275-a188f481-ccae-443a-8295-c4c9dfde1687.png"> |
```release-note
* UI: Fixes Do not disturb submenu item not taking full width
```
> [MM-38868] Fixes do not disturb submenu item not taking full width

- e2e/cypress/integration/messaging/channel_and_posts_links_spec.js
- e2e/cypress/integration/messaging/permalink_message_edit_spec.js
- Fix some failing prod messaging e2e
Test report - https://automation-dashboard.vercel.app/cycles/bd3f7721-690f-4385-9966-58753174c377
NA
```release-note
NONE
```
> Cypress/E2E: Fix some prod messaging tests

- e2e/cypress/integration/messaging/permalink_click_spec.js
- e2e/cypress/integration/messaging/single_image_thumbnail_spec.js
- Fix some failing unstable messaging e2e
Test report - N/A (currently broken)
NA
```release-note
NONE
```
> Cypress/E2E: Fix some unstable messaging tests

- components/file_preview_modal/file_preview_modal.jsx
- components/post_view/post_image/post_image.jsx
Cherry pick of #8971 on release-6.0.
```release-note
NONE
```
> Automated cherry pick of #8971

- .circleci/config.yml
This is the initial work to cleanup the docker repositories and push images tot he official repositories (`mattermost/mattermost-enterprise-edition` / `mattermost/mattermost-team-edition`) only official releases and not testing/prs images
the testing/prs images will be pushed to `mattermost/mm-te-test` and `mattermost/mm-ee-test`
to avoid any breaks for now we will push to both places, after we make sure everything is clean and correct we will do a follow up to remove the push to `mattermost/mattermost-enterprise-edition`
JIRA: https://mattermost.atlassian.net/browse/DOPS-632
Server: https://github.com/mattermost/mattermost-server/pull/18488
enterprise: https://github.com/mattermost/enterprise/pull/1073
Matterwick: https://github.com/mattermost/matterwick/pull/30
```release-note
NONE
``` …
> docker/build: push image to the testing repository and refactor the fetches of the dockerfile

- components/more_direct_channels/list/index.test.js
- components/more_direct_channels/list/index.ts
I accidentally made it so that new users would see an empty DM modal instead of a list of all users alphabetically before they had any DMs opened. This fixes that.
https://mattermost.atlassian.net/browse/MM-39033
Before:
After:
```release-note
NONE
```
> MM-39033 Revert change to More DMs modal for new users

- components/multiselect/__snapshots__/multiselect.test.tsx.snap
- components/multiselect/multiselect.tsx
When a related modal was updated in #7172 and we changed the message from "No items found" to "No results found for **whatever**", we forgot to pass in the search query, so it just displayed "No results found for ****"
https://mattermost.atlassian.net/browse/MM-39034
```release-note
Fixed "No results found" string in Direct Messages modal
```
> MM-39034 Fix 'no results found' string in More DMs modal

- actions/storage.js
- actions/storage.test.js
- actions/views/create_comment.tsx
- components/create_post/create_post.tsx
- components/create_post/index.ts
- reducers/storage.js
- reducers/storage.test.js
- utils/constants.jsx
I think this logic is also related to the performance issues we've been fighting. Every time a `CreatePost` or `CreateComment` is mounted, we go through and clear up all in-progress file uploads (which is another bug for the RHS since it means you have to leave the RHS open while a file uploads or else it'll be cleared), and when we do that, we mutate all the drafts. That, in turn, caused all the other tabs to rehydrate which caused other performance-affecting stuff to happen.
Now, we'll only mutate them if there were actually changes to be made.
https://mattermost.atlassian.net/browse/MM-39046
```release-note
Reduce storage-related slow downs on page load
```
> MM-39046 Don't modify all drafts on page load

- packages/mattermost-redux/src/reducers/entities/posts.ts
When CRT is enabled ephemeral message were rendering only in RHS without any indication on centre post, this change will add ephemeral message in centre channel as well
[https://mattermost.atlassian.net/browse/MM-36883](https://mattermost.atlassian.net/browse/MM-36883)
|----|----|
| <img width="1792" alt="Screenshot 2021-10-04 at 2 03 27 PM" src="https://user-images.githubusercontent.com/16203333/135819270-940724f1-acd1-4a5c-985c-813a59ce671e.png"> | <img width="1792" alt="Screenshot 2021-10-04 at 2 02 29 PM" src="https://user-images.githubusercontent.com/16203333/135819345-ce8bef4f-4f46-4f42-8678-ae90e753d519.png"> |
```release-note
* Show ephemeral message as centre post even if CRT is enabled
```
> [MM-36883] Show ephemeral message as centre post even if CRT is enabled

- packages/mattermost-redux/src/selectors/entities/channels.ts
- packages/mattermost-redux/src/selectors/entities/users.ts
- packages/mattermost-redux/src/types/users.ts
- packages/mattermost-redux/src/types/utilities.ts
- packages/mattermost-redux/src/utils/channel_utils.ts
Modify UserState profilesInChannel and profilesNotInChannel attributes to both be typed Record<string, Set>
Introduce a RelationOneToManyUnique type that mimics RelationOneToMany but use a Set instead of an Array
Fixes mattermost/mattermost-server#18112
JIRA: https://mattermost.atlassian.net/browse/MM-37631
NONE
> Fix type definition for state.entities.users.profilesInChannel

- components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.tsx.snap
- components/add_groups_to_channel_modal/add_groups_to_channel_modal.test.tsx
- components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
- components/admin_console/system_roles/system_role/add_users_to_role_modal/add_users_to_role_modal.test.tsx
- components/admin_console/system_roles/system_role/add_users_to_role_modal/add_users_to_role_modal.tsx
- components/admin_console/team_channel_settings/group/group_members_modal.test.tsx
- components/admin_console/team_channel_settings/group/group_members_modal.tsx
- components/admin_console/team_channel_settings/users_to_be_removed_modal.jsx
- components/commercial_support_modal/__snapshots__/commercial_support_modal.test.tsx.snap
- components/commercial_support_modal/commercial_support_modal.test.tsx
- components/commercial_support_modal/commercial_support_modal.tsx
- components/commercial_support_modal/index.ts
- components/delete_post_modal/delete_post_modal.test.tsx
- components/delete_post_modal/delete_post_modal.tsx
- components/join_private_channel_modal.tsx
I'm renaming onHide to onExited so that it mirrors how it's supposed to be used with React-Bootstrap. GenericModal is one of those modals.
There shouldn't be any functional changes from this PR.
https://mattermost.atlassian.net/browse/MM-39580
https://github.com/mattermost/mattermost-webapp/pull/9280
https://github.com/mattermost/mattermost-webapp/pull/9281
https://github.com/mattermost/mattermost-webapp/pull/9282
https://github.com/mattermost/mattermost-webapp/pull/9283
https://github.com/mattermost/mattermost-webapp/pull/9291
https://github.com/mattermost/mattermost-webapp/pull/9292
```release-note
NONE
```
> MM-39580 Switch admin-related modals to onExited

- components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
- components/post_view/post_message_preview/post_message_preview.tsx
- i18n/en.json
Addressing concern about users seeing messages they shouldn't by making the text more clear.
We want to communicate that only users of the originating channel can see the preview.
> Update permalink preview subtext

- components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
- components/post_view/post_message_preview/post_message_preview.tsx
- i18n/en.json
Cherry pick of #9174 on release-6.1.
/cc  @esethna
```release-note
NONE
```
> Automated cherry pick of #9174

- packages/mattermost-redux/src/selectors/entities/channels.test.js
- packages/mattermost-redux/src/selectors/entities/channels.ts
Fixes a regression in #9261 that causes the web app to crash when opening the DMs modal because it's displaying a GM channel which has no members loaded for it yet.
https://mattermost.atlassian.net/browse/MM-39773
https://github.com/mattermost/mattermost-webapp/pull/9261
```release-note
NONE
```
> MM-39773 Re-add default value in getChannelsWithUserProfiles

- components/markdown/markdown.tsx
added a new condition in `Markdown` component to check for the message to be a string and have a length of 0 (empty string)
[MM-39429](https://mattermost.atlassian.net/browse/MM-39429)
```release-note
edited indicator now shows on edited messages with attachments, where message is empty or deleted
```
> [MM-39429]: show edited indicator on empty/deleted messages with attachment

- components/markdown/markdown.tsx
Cherry pick of #9264 on release-6.1.
```release-note
NONE
```
> Automated cherry pick of #9264

- components/channel_info_modal/channel_info_modal.test.tsx
- components/channel_info_modal/channel_info_modal.tsx
- components/channel_invite_modal/channel_invite_modal.test.tsx
- components/channel_invite_modal/channel_invite_modal.tsx
- components/channel_members_modal/__snapshots__/channel_members_modal.test.tsx.snap
- components/channel_members_modal/channel_members_modal.test.tsx
- components/channel_members_modal/channel_members_modal.tsx
- components/channel_notifications_modal/channel_notifications_modal.jsx
- components/channel_notifications_modal/channel_notifications_modal.test.jsx
- components/delete_channel_modal/delete_channel_modal.test.tsx
- components/delete_channel_modal/delete_channel_modal.tsx
- components/edit_channel_purpose_modal/edit_channel_purpose_modal.test.tsx
- components/edit_channel_purpose_modal/edit_channel_purpose_modal.tsx
- components/rename_channel_modal/rename_channel_modal.test.tsx
- components/rename_channel_modal/rename_channel_modal.tsx
- components/unarchive_channel_modal/unarchive_channel_modal.test.tsx
- components/unarchive_channel_modal/unarchive_channel_modal.tsx
I'm renaming onHide to onExited so that it mirrors how it's supposed to be used with React-Bootstrap. GenericModal is one of those modals.
The only functional change here is that the Channel Info and Channel Members modals will now fade out nicely before unmounting instead of just disappearing.
https://mattermost.atlassian.net/browse/MM-39580
https://github.com/mattermost/mattermost-webapp/pull/9280
https://github.com/mattermost/mattermost-webapp/pull/9281
https://github.com/mattermost/mattermost-webapp/pull/9282
https://github.com/mattermost/mattermost-webapp/pull/9283
```release-note
NONE
```
> MM-39680 Switch Channel modals to onExited

- components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
- components/edit_channel_header_modal/edit_channel_header_modal.test.tsx
- components/edit_channel_header_modal/edit_channel_header_modal.tsx
- components/edit_channel_header_modal/index.ts
I'm renaming onHide to onExited so that it mirrors how it's supposed to be used with React-Bootstrap. GenericModal is one of those modals.
The only functional change here is that this modal will now fade out nicely before unmounting instead of just disappearing.
https://mattermost.atlassian.net/browse/MM-39580
https://github.com/mattermost/mattermost-webapp/pull/9280
https://github.com/mattermost/mattermost-webapp/pull/9281
https://github.com/mattermost/mattermost-webapp/pull/9282
```release-note
NONE
```
> MM-39580 Switch EditChannelHeaderModal to onExited

- components/admin_console/feature_discovery/feature_discovery.tsx
- components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
- components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
- components/announcement_bar/renewal_link/renewal_link.tsx
- components/dot_menu/dot_menu.tsx
- components/dot_menu/index.ts
- components/edit_post_modal/edit_post_modal.tsx
- components/global_header/right_controls/settings_button/settings_button.tsx
- components/invitation_modal/index.js
- components/main_menu/main_menu.tsx
- components/sidebar/index.ts
- components/sidebar/legacy_sidebar_header/dropdown/sidebar_header_dropdown.tsx
- components/sidebar/legacy_sidebar_header/dropdown/sidebar_header_dropdown_button.tsx
- components/sidebar/legacy_sidebar_header/legacy_sidebar_header.tsx
- components/sidebar/sidebar.tsx
- components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
- components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
- components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
- components/status_dropdown/status_dropdown.tsx
- components/user_limit_modal/index.ts
- components/user_limit_modal/user_limit_modal.tsx
This cleans up all the uses of `openModal` that didn't cause the type checker to report errors when I submitted #9181.
https://mattermost.atlassian.net/browse/MM-39581
https://github.com/mattermost/mattermost-webapp/pull/9181
```release-note
NONE
```
> MM-39581 Update openModal type definitions

- e2e/cypress/integration/account_settings/security/password_spec.js
- e2e/cypress/integration/enterprise/system_console/compliance/data_retention_policies_2_spec.js
- e2e/cypress/integration/enterprise/system_console/compliance/data_retention_policies_3_spec.js
- e2e/cypress/integration/enterprise/system_console/compliance/data_retention_policies_4_spec.js
- e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_up_down_in_rhs_spec.js
Moved following `spec` to Prod
`cypress/integration/account_settings/security/password_spec.js`
`cypress/integration/enterprise/system_console/compliance/data_retention_policies_2_spec.js`
`cypress/integration/enterprise/system_console/compliance/data_retention_policies_3_spec.js`
`cypress/integration/enterprise/system_console/compliance/data_retention_policies_4_spec.js`
`cypress/integration/keyboard_shortcuts/ctrl_cmd_up_down_in_rhs_spec.js`
Using following Cycles results,
1. https://automation-dashboard.vercel.app/cycles/c06a2697-866d-41b4-94c0-9c030b113dae
2. https://automation-dashboard.vercel.app/cycles/ea217de2-8cc7-449c-9cd0-a5d94174b667
3. https://automation-dashboard.vercel.app/cycles/0b80019b-4e4f-4692-b375-7a66da757ce9
4. …
> Cypress E2E: Moved from unstable to prod

- components/threading/global_threads/thread_item/thread_item.scss
Mention badge in thread wasn't visible in some themes.
[MM-39770](https://mattermost.atlassian.net/browse/MM-39770)
```release-note
Made thread mention badge visible in all themes
```
> [MM-39770] Make thread mention badge visible in all themes

- components/threading/common/follow_button/follow_button.tsx
Since https://github.com/mattermost/mattermost-server/pull/18740 the API can return `null` for `isFollowing` property,
this caused the thread footer's follow button to appear disabled.
This commit fixes that issue.
https://mattermost.atlassian.net/browse/MM-39850
```release-note
NONE
```
> MM-39850: fixes follow in thread footer

- components/widgets/menu/menu_items/menu_item.scss
Fix menu width highlighting when hovering
[MM-39596](https://mattermost.atlassian.net/browse/MM-39596)
```release-note
Fix menu width highlighting when hovering
```
> [MM-39596] Fix menu width

- components/user_settings/display/user_settings_theme/user_settings_theme.jsx
- sass/routes/_settings.scss
I've removed string-refs usage for that one as it doesn't correspond to anything in the app.
The code dates back from 2016 and I wasn't able to blame before that to understand why it was added (and with which corresponding code)
Fixes https://github.com/mattermost/mattermost-server/issues/15843
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29404
NONE
> Remove string-refs usage in ThemeSetting component as it isn't needed anymore

- build/emoji/emoji_gen.mjs
- sass/components/_emojisprite.scss
- sass/components/_emoticons.scss
Fix premature truncation of names in emoji picker. Generally simplify style now that aliases are shown on the same line as the primary name.
https://github.com/mattermost/mattermost-server/issues/18430  
https://mattermost.atlassian.net/browse/MM-37746
|----|----|
| ![Screenshot_20211029_110846](https://user-images.githubusercontent.com/28617290/139354663-407d08a9-fcbc-4b29-a12f-fbb0717cb490.png) | ![Screenshot_20211028_115539](https://user-images.githubusercontent.com/28617290/139354543-98fb2a7b-2257-44c2-b9bd-439cfec6ed7f.png) |
```release-note
NONE
```
> MM-37746 Fix premature truncation of names in emoji picker

- components/emoji_picker/emoji_picker.jsx
- components/emoji_picker/emoji_picker.test.jsx
Recent emojis now change (when applicable) based on the default selected
skin tone.
If more than one skin tone was available in the recent section, this
feature will trim all duplicates, displaying only the emoji matching
the default selected skin tone.
Jira ticket: https://mattermost.atlassian.net/browse/MM-37990
Fixes https://github.com/mattermost/mattermost-server/issues/18847
|----|----|
| ![image](https://user-images.githubusercontent.com/14358537/139396327-66ab69e1-5cf7-48d6-8ae9-90353246e3b5.png) | ![perf-after](https://user-images.githubusercontent.com/14358537/139396331-687b6f87-32ca-4410-a08d-06bd83c3d8a0.PNG) |
```release-note
Recent emojis get updated based on default …
```
> [MM-37990] Update recent emojis based on default selected skin tone

- e2e/cypress/support/api/on_prem_default_config.json
- packages/mattermost-redux/src/types/config.ts
Removing references to `DesktopMinVersion` and `DesktopLatestVersion` since we aren't using them.
https://mattermost.atlassian.net/browse/MM-39374
- Has server changes (https://github.com/mattermost/mattermost-server/pull/18979)
```release-note
NONE
```
> [MM-39374] Remove references to DesktopMinVersion and DesktopLatestVersion

- e2e/cypress/integration/keyboard_shortcuts/shift_up_focuses_on_rhs_spec.js
This pull request creates a spec to tests shift+up keyboard shortcut focus on RHS.
Fixes https://github.com/mattermost/mattermost-server/issues/18808
-->
```release-note
NONE
```
> MM-T1277 Create Spec for SHIFT+UP Shortcut

- components/create_post/create_post.test.jsx
- components/create_post/create_post.tsx
- components/sidebar/sidebar.test.tsx
- components/sidebar/sidebar.tsx
CRT: Shortcut (Command-/) for the keyboard shortcuts Modal doesn't work in global threads
Fixes https://mattermost.atlassian.net/browse/MM-36009
``None``
-->
```release-note
* fixes keyboard shortcut not working with global threads
```
> [MM-36009] fixes keyboard shortcut with global threads

- e2e/cypress/integration/custom_status/custom_status_5_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
- e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
- e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
- e2e/cypress/support/ui/sidebar_left.d.ts
- e2e/cypress/support/ui/sidebar_left.js
- Based on @furqanmlk's original changes in PR https://github.com/mattermost/mattermost-webapp/pull/9275, applied additional changes so that it's consistent, i.e. change `uiGetChannelSwitcher` to `uiGetFindChannels` and use `uiOpenFindChannels`
NA
```release-note
NONE
```
> Cypress/E2E: Cleanup find channels

- e2e/cypress/integration/autocomplete/common_test.js
- e2e/cypress/integration/channel/channel_mention_autocomplete_spec.js
- e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
- e2e/cypress/integration/settings/sidebar/fullname_spec.js
- e2e/cypress/support/ui/suggestion_list.d.ts
- e2e/cypress/support/ui/suggestion_list.js
- Since suggestion list section divider name has been recently removed from autocomplete, I'm disabling the check for that one for now. I'm going to keep the logic in the function in case we decide to put it back in.
NA
```release-note
NONE
```
> Cypress/E2E: Fix unstable autocomplete

- components/threading/global_threads/global_threads.tsx
- i18n/en.json
Missing i18 variable for unread threads.
Note: we need to add translations for the new key added for missing text.
Fixes https://mattermost.atlassian.net/browse/MM-38673
``None``
```release-note
* Added missing i18 variable for unread threads
```
> add missing i18 variable for unread threads

- components/delete_post_modal/delete_post_modal.tsx
- components/delete_post_modal/index.ts
- components/threading/global_threads/thread_item/index.ts
- reducers/views/rhs.js
- reducers/views/threads.ts
Webapp crashes when the root post is deleted from Threads RHS
Note: All other scenarios of post delete, as well as global threads RHS, require testing.
Fixes https://mattermost.atlassian.net/browse/MM-38376
``None``
|----|----|
| [https://www.loom.com/share/2c626dd0418444999390b2ed932cd719](https://www.loom.com/share/2c626dd0418444999390b2ed932cd719) | [https://www.loom.com/share/ff354c7621cd46a1a1fcc58c02c7fa32](https://www.loom.com/share/ff354c7621cd46a1a1fcc58c02c7fa32) |
```release-note
* Bug fixes app crash on root post delete from global threads
```
> [MM-38376]fix-app-crash-on-root-post-delete-from-global-threads

- e2e/cypress/integration/collapsed_reply_threads/channel_notifications_spec.js
Adds E2E tests to test notification in CRT threads when changing the
notification preference on channel level.
https://mattermost.atlassian.net/browse/MM-39619
```release-note
NONE
```
> MM-39619: E2E CRT channel channel notification override

- utils/utils.jsx
CRT: Thread viewer long post Show More/Less background is broken
Fixes https://mattermost.atlassian.net/browse/MM-35926
``None``
|----|----|
| <img width="992" alt="Screenshot 2021-11-18 at 1 56 05 PM" src="https://user-images.githubusercontent.com/16203333/142378961-54fccd68-cc75-40c3-97a3-43313eaf1822.png"> | <img width="1012" alt="Screenshot 2021-11-18 at 1 54 31 PM" src="https://user-images.githubusercontent.com/16203333/142378892-4edd967b-3e31-4573-b644-4000a0beb504.png"> |
```release-note
NONE
```
> [MM-35926] CRT: Thread viewer long post Show More/Less background is broken

- components/activity_log_modal/activity_log_modal.tsx
- components/admin_console/brand_image_setting/brand_image_setting.tsx
- components/admin_console/file_upload_setting.jsx
- components/admin_console/remove_file_setting.jsx
- components/audio_video_preview.jsx
- components/code_preview.jsx
- components/post_view/scroll_to_bottom_arrows.jsx
- components/searchable_channel_list.jsx
- components/searchable_user_list/searchable_user_list.jsx
- components/settings_sidebar.tsx
- components/team_general_tab/team_general_tab.jsx
- components/team_settings_modal/team_settings_modal.tsx
- package-lock.json
- package.json
- tests/helpers/client-test-helper.jsx
This leave the jquery dependency in the package.json because it is required by
bootstrap. We need to eventually remove bootstrap to be able to definitively
get rid of jquery.
Removing remaining jquery imports
https://mattermost.atlassian.net/browse/MM-27444
https://mattermost.atlassian.net/browse/MM-27445
https://mattermost.atlassian.net/browse/MM-29031
https://mattermost.atlassian.net/browse/MM-29032
```release-note
NONE
```
> Removing remaining jquery imports

- components/search/search.tsx
Command Shift F search in global threads without prefilled term
Fixes https://mattermost.atlassian.net/browse/MM-36641
``None``
|----|----|
| <img width="815" alt="Screenshot 2021-11-22 at 3 17 53 PM" src="https://user-images.githubusercontent.com/16203333/142839304-9727d0fe-2d5a-4384-b508-f33e591ffa91.png"> | <img width="816" alt="Screenshot 2021-11-22 at 3 19 03 PM" src="https://user-images.githubusercontent.com/16203333/142839491-0ba5a8ff-f7eb-40cc-9d42-ebe3f4752e72.png"> |
```release-note
* On Cmd/Ctrl + Shift + F in global threads will not add a search term automatically
```
> Command Shift F search in global threads without prefilled term

- e2e/cypress/integration/enterprise/auth_sso/mfa_authentication_spec.js
- e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
- e2e/cypress/integration/signin_authentication/mfa_authentication_spec.js
- e2e/cypress/support/ui/index.js
- e2e/cypress/support/ui/mfa.d.ts
- e2e/cypress/support/ui/mfa.js
- Fixed flaky tests on MFA
- Moved common UI command as `cy.uiGetMFASecret`
none, failed on daily Cypress run
```release-note
NONE
```
> Cypress/E2E: Fix flaky tests on MFA

- components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
- components/status_dropdown/status_dropdown.tsx
- e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
- e2e/cypress/integration/accessibility/accessibility_post_spec.js
- e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
- Fixed failed tests on user profile focus introduced by https://github.com/mattermost/mattermost-webapp/pull/9383
- Fixed aria-label of "Profile" menu item and include test on it
- Removed the use of implementation specific detail (CSS class) in favor of accessible attribute (`be.focused`)
none, failed on daily run
```release-note
NONE
```
> Cypress/E2E: Fix user profile focus and menu option aria-label

- e2e/package-lock.json
- e2e/package.json
Cypress install recently encountered error when installing deprecated "har-validator". 
```
npm ERR! Error: Cannot find module 'har-validator'
```
Workaround is to set @cypress/request to 2.88.7 until "har-validator" is totally removed from the said package (PR to track `https://github.com/cypress-io/request/pull/15`).
```release-note
NONE
```
> Cypress/E2E: Set @cypress/request to 2.88.7 to avoid error when installing deprecated "har-validator"

- plugins/index.js
The `uninitialize` method is used to revert any changes a plugin may have made to the environment that the plugin framework doesn't keep track of. It is called when plugin is disabled or removed from the system, but not when the plugin is re-deployed while during the user's browser session.
This PR makes it so `uninitialize` is called in this case, so the plugin has a chance to clean up before the next version starts up.
https://mattermost.atlassian.net/browse/MM-40340
> [MM-40340] Uninitialize webapp plugin when a new version gets deployed

- components/trial_benefits_modal/trial_benefits_modal.scss
- components/trial_benefits_modal/trial_benefits_modal.tsx
During the initial implementation of the benefits trial modal, the hands svg image had an scaling problem related to the way figma was exporting the image. In order to make it fit in the space and be compliant with the design, we had to set a bigger size to the image. Now that the hands svg image was fixed and replaced as part of the changes for the license page https://github.com/mattermost/mattermost-webapp/pull/9372/files#diff-c9a0cfc007c0ec6684e230f4bf09f32c1a853fd174be5a6c1a226eb9d72b21e9R19 we can set the correct size to the image in the trial modal.
https://mattermost.atlassian.net/browse/MM-40176
Before:
After:
```release-note
NONE
```
> MM-40176 - adjust hands svg size for trial benefits modal

- components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
There was a defect related to the licensing page not showing the accurate name for the starter license. This PR adds the starter option to the sku name generation so when a starter license is upload, the information shown in the license section is accurate.
https://mattermost.atlassian.net/browse/MM-40417
Both images were taken from an env using a starter license.
Before:
After:
```release-note
NONE
```
> MM-40417 - fix the wording for the starter plan

- components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
- components/dot_menu/dot_menu.tsx
- components/file_attachment/file_attachment.tsx
- components/rhs_search_nav/rhs_search_nav.tsx
- components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
- components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
- components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
- components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
- components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
- components/sidebar/sidebar_menu/sidebar_menu.test.tsx
- components/sidebar/sidebar_menu/sidebar_menu.tsx
- utils/utils.jsx
Similar to the related PRs, we're trying to improve some performance issues that a customer was reporting where the JS thread would frequently get blocked on style recalculations. As part of an effort to combat that, I've been removing stuff that we think blocks on the UI based on [this list](https://gist.github.com/paulirish/5d52fb081b3570c81e3a).
There's technically two sets of changes, but I'm trying to save some work because of how much cherry-picking is required for these. For the two commits:
1. The first one is avoiding accessing dimensions of stuff during render. I have a theory this is the worst culprit for those issues.
2. The second one is avoiding accessing that when its doing ref callbacks since I assume that's similarly bad. All of the cases I saw where we were doing that …
> MM-40071 Attempt to improve performance by reducing direct DOM usage

- components/about_build_modal/__snapshots__/about_build_modal.test.tsx.snap
- components/about_build_modal/about_build_modal.tsx
Updated the About Mattermost Team Edition modal community URL to point to https://mattermost.com/community/ since the .org domain is being retired.
Updated the About Mattermost Team Edition modal to change the community link from `mattermost.org` to `mattermost.com/community/`.
```release-note
Updated the About Mattermost Team Edition modal to change the community link from `mattermost.org` to `mattermost.com/community/`.
```
> Updated About Mattermost TE modal's community URL

- plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
- plugins/channel_header_plug/channel_header_plug.test.tsx
- plugins/channel_header_plug/channel_header_plug.tsx
- plugins/channel_header_plug/index.ts
With the current channel header icon placement in relation to the RHS, users have been accidentally starting zoom meetings because the zoom icon is placed at the same spot as the close-x of the RHS thread view. If the user clicks to close the RHS twice, the zoom button gets clicked.
The channel header icons will be moved to the App Bar in the near future, which will make it so this is no longer a problem, but this PR is a solution to avoid this issue in the meantime. This PR makes it so when user closes the RHS, the channel header icons are disabled for a short period of time, to avoid the double-click issue.
https://mattermost.atlassian.net/browse/MM-39745
> [MM-39745] Disable channel header buttons temporarily when the RHS closes

- components/suggestion/suggestion_box/suggestion_box.jsx
In my other PR to forward the ref through the QuickInput to the inner input, I missed a place that was still trying to access the ref as a field of the QuickInput
https://mattermost.atlassian.net/browse/MM-40528
https://github.com/mattermost/mattermost-webapp/pull/9452
```release-note
NONE
```
> MM-40528 Fix error caused by changes to QuickInput

- components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.scss
- components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
Previously, the DND modal had some internal state for tracking its show/hide, and it also implemented its own confirm button for whatever reason. Both of those didn't work together (the modal didn't close properly), so I removed the extra state and changed it so that the actual footer from the GenericModal is used. This results in some minor appearance changes, but I think consistency between modals is more important here.
https://mattermost.atlassian.net/browse/MM-40493
|----|----|
| ![Screen Shot 2021-12-07 at 2 55 25 PM](https://user-images.githubusercontent.com/3277310/145099176-93a5b51f-3ee8-4178-afe8-bb8b1b2f6fab.png) | ![Screen Shot 2021-12-07 at 2 55 29 PM](https://user-images.githubusercontent.com/3277310/145099208-66897430-9192-4865-9a8a-c5b44a86e97d.png) …
> MM-40493 Switch DND modal to rely more on GenericModal

- components/emoji_picker/emoji_picker.jsx
When a default emoji (yellow skin) is added as a reaction to a post it appears correctly in the recent emoji section, but would not change its skin when we select a different skin. The same is not the case for emoji with non default skin; when they are added, they change the skin correctly in recent emoji section
N/A
N/A
before
https://user-images.githubusercontent.com/17708702/145613667-3c8c8f2c-2c75-4f98-9f2c-0353c593f550.mov
after
https://user-images.githubusercontent.com/17708702/145613827-3aa49411-7ee5-4636-a3b6-9c4e87dc367f.mov
```release-note
NONE
```
> fix : Emojis with default skin not changing color in recent when skin is changed

- components/rhs_card/index.js
- components/rhs_card/rhs_card.jsx
- components/rhs_card/rhs_card.test.jsx
- components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
- components/rhs_comment/index.ts
- components/rhs_comment/rhs_comment.jsx
- components/rhs_comment/rhs_comment.test.jsx
- components/rhs_header_post/index.ts
- components/rhs_header_post/rhs_header_post.tsx
- components/rhs_root_post/index.ts
- components/rhs_root_post/rhs_root_post.jsx
- components/rhs_root_post/rhs_root_post.test.jsx
- components/search/index.tsx
- components/search/search.tsx
- components/search/types.ts
- components/search_results_item/index.test.js
- components/search_results_item/index.ts
- components/search_results_item/search_results_item.jsx
- components/search_results_item/search_results_item.test.jsx
`getIsMobileView` is the more redux-friendly, more self-explanatory, and hopefully more performant version of `Utils.isMobile` that we're wanting to be using everywhere now. 
https://mattermost.atlassian.net/browse/MM-40114
https://github.com/mattermost/mattermost-webapp/pull/9507
https://github.com/mattermost/mattermost-webapp/pull/9508
https://github.com/mattermost/mattermost-webapp/pull/9509
```release-note
NONE
```
> MM-40114 Migrate RHS and search components to use getIsMobileView

- components/rhs_header_post/rhs_header_post.spec.tsx
We deprecated `Utils.isMobile` and replaced with `getIsMobileView`
selector.
Some tests failed to be updated and now fail on master.
This commit fixes that.
```release-note
NONE
```
> Fixes tests on master

- NOTICE.txt
- components/root/root.jsx
- components/root/root.test.jsx
- package-lock.json
- package.json
https://mattermost.atlassian.net/browse/MM-40271
None
```release-note
NONE
```
> chore/MM-40271 : Remove fastclick library

- components/root/root.jsx
- packages/mattermost-redux/src/client/client4.ts
Fixes: https://github.com/mattermost/mattermost-redux/issues/1359
Currently the token isn't set on login, so using login actually does nothing and any following request that requires permission fails with 401 `'api.context.session_expired.app_error'`
> fix: set token if not already set

- components/emoji_picker/emoji_picker.jsx
Fixed the bug in emoji picker when custom emoji was deleted and the state of emoji picker was stuck to search one.
None
None
```release-note
```
> fix : Fix custom emoji deleted puts emoji picker in search state

- components/widgets/users/avatars/avatars.tsx
- i18n/en.json
- package-lock.json
- package.json
`make i18n-extract` used to have issues with TypeScript files. It turns out that that was because it was trying to parse all files as if they used Flow, not TypeScript, and it would silently fail as soon as it hit any TS code that wasn't also valid Flow.
https://mattermost.atlassian.net/browse/MM-40630
https://github.com/mattermost/mattermost-utilities/pull/56
```release-note
NONE
```
> MM-40630 Update mmjstools so i18n-extract supports TypeScript

- components/invitation_modal/invite_view.tsx
- components/widgets/inputs/users_emails_input.tsx
- e2e/cypress/integration/team_settings/invite_members_spec.js
Focus input by default in invitation modal.
https://mattermost.atlassian.net/browse/MM-40487
This one:
https://user-images.githubusercontent.com/13738432/146068884-7b8d0f69-b229-4166-9666-aabd1b655c0b.mp4
```release-note
Invite to team modal auto focuses its email search input.
```
> focus user email input by default for invitation modal

- .circleci/config.yml
As far as I know, no one actually uses the web app's Storybook stuff since the widgets components aren't in active development any more, so this'll speed up CI a bit. We have another ticket to fully remove the Storybook code from the web app repo, but that'll be done separately since it'll require actual code changes.
This won't affect any of the Storybook in other repos or used by other teams, and we can definitely reintroduce it later on, but we don't need it in this repo for the time being.
https://mattermost.atlassian.net/browse/MM-40633
```release-note
NONE
```
> MM-40633 Remove Storybook-related CI steps

- components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
This PR fixes a typo in the licensing pages, replacing a `?` character for the correct one `/` in the first feature list item in the right column, just before it reads `LDAP Group Sync`
https://mattermost.atlassian.net/browse/MM-40599
Before:
After:
```release-note
NONE
```
> MM-40599 - fix typo in features list

- components/invitation_modal/index.tsx
- components/invitation_modal/invitation_modal.test.tsx
- components/invitation_modal/invitation_modal.tsx
use onExited & track state.show for a smoother exit transition in invitation modal
https://mattermost.atlassian.net/browse/MM-40315
```release-note
Fix exit animation on invitation modal.
```
> use state.show & top level onExited for invitation modal

- components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
- components/admin_console/license_settings/index.ts
- components/admin_console/license_settings/license_settings.tsx
This PR fixes a regression added during the migration from .js to .ts as part of the License page UX changes. The fix consist of setting a custom type instead of using the ActionResult common one. This is due since the signature of the response doesn't match with the ActionResult type.
https://mattermost.atlassian.net/browse/MM-40600
https://user-images.githubusercontent.com/10082627/146703651-ae42bb44-4114-4f13-a5fb-0f7bf19b159b.mp4
```release-note
Problem description: As part of the UX redesign for the licensing pages a regression was added that prevented the upgrade button to show the progress and hence was not showing the restart button once the progress reached the 100%. This led to users not being able to restart the server directly from the UI so they can not see the upgraded …
```
> MM-40600 - use custom type and set correct value to api response

- components/timestamp/index.test.tsx
- components/timestamp/index.ts
Cherry pick of #9427 on release-6.3.
```release-note
NONE
```
> Automated cherry pick of #9427

- components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
Cherry pick of #9535 on release-6.3.
```release-note
NONE
```
> Automated cherry pick of #9535

- components/file_preview_modal/file_preview_modal_info/__snapshots__/file_preview_modal_info.test.tsx.snap
- components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.tsx
File preview modal info bar has channel id instead of channel name for DM's 
Fixes https://mattermost.atlassian.net/browse/MM-40460
``NONE``
|----|----|
| ![Image Pasted at 2021-12-2 21-04](https://user-images.githubusercontent.com/16203333/146725999-b397aa2a-bec9-47be-be3b-0e5e888a808d.png) | <img width="1792" alt="Screenshot 2021-12-20 at 12 26 34 PM" src="https://user-images.githubusercontent.com/16203333/146725955-bf809953-4620-4208-9205-65dfa0985c83.png"> |
```release-note
* File preview modal info bar has channel id instead of channel name for DM's
```
> fix Dm name in file preview modal info bar

- sass/components/_post-menu.scss
Fix: Post hover menu overlapping long post in the center channel and RHS
Fixes: https://mattermost.atlassian.net/browse/MM-40481
``NONE``
|----|----|
| <img width="1792" alt="Screenshot 2021-12-22 at 1 07 09 PM" src="https://user-images.githubusercontent.com/16203333/147054731-2e0f50f9-892b-49a4-a869-cc6165551d94.png">|<img width="1790" alt="Screenshot 2021-12-22 at 1 10 52 PM" src="https://user-images.githubusercontent.com/16203333/147054747-7df989d2-ebe7-4ef1-ab24-8e25a6cd8820.png">|
|<img width="1478" alt="Screenshot 2021-12-22 at 1 09 10 PM" src="https://user-images.githubusercontent.com/16203333/147054768-0e67865b-0077-467b-b779-cfc0e49be4a5.png">|<img width="974" alt="Screenshot 2021-12-22 at 1 10 25 PM" …
> [MM-40481] fix post hover menu overlap

- components/sidebar/sidebar_category/sidebar_category.tsx
This PR adds a check to hide invitation button when DMs are collapsed from the sidebar
[MM-39279](https://mattermost.atlassian.net/browse/MM-39279)
```release-note
NONE
```
> [MM-39279] - Hide the Invite Members button when the DM category is collapsed

- components/admin_console/license_settings/license_settings.scss
- components/admin_console/license_settings/starter_edition/starter_edition.scss
- components/admin_console/license_settings/starter_edition/starter_right_panel.tsx
- components/announcement_bar/contact_sales/contact_us.tsx
Buttons on the licensing page were not responsive so when resizing the screen, the buttons were showing a different padding. This PR makes those buttons responsive so in smaller screens they are displayed as block elements occupying all the available space.
https://mattermost.atlassian.net/browse/MM-40746
https://user-images.githubusercontent.com/10082627/147148025-bb749630-a80f-436c-a7b2-6aa77e48a8bb.mp4
```release-note
NONE
```
> MM-40746 - make licensing page purchase buttons responsive

- packages/mattermost-redux/src/client/client4.ts
Turns out all API requests we make to the server from the client are made with `Content-Type: plain/text` even though we're always passing JSON through `Client4`. I looked through every Client4 call that passes a body, and every one of them calls `JSON.stringify` on an object before passing it as the `body` option
https://mattermost.atlassian.net/browse/MM-40751
Closes https://mattermost.atlassian.net/browse/MM-40751
```release-note
Changed Client4 to properly set Content-Type as application/json on API calls
```
> MM-40751 Properly set Content-Type on API requests

- components/sidebar/sidebar.tsx
- e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_a_account_settings_spec.js
This is what I get for copying code without realizing it didn't check for shift when handling this hotkey
https://mattermost.atlassian.net/browse/MM-40767
```release-note
NONE
```
> MM-40545 Prevent ctrl+a from opening account settings modal without shift

- components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
- components/announcement_bar/configuration_bar/configuration_bar.test.tsx
- utils/license_utils.jsx
- utils/license_utils.test.jsx
The license check and invalidation was removed server side for Cloud installations in https://github.com/mattermost/mattermost-server/pull/18921 and https://github.com/mattermost/mattermost-webapp/pull/9318 . However, it was not removed in the banner checks for already expired licenses. This PR will not show the license expired banner for any cloud installation. 
https://mattermost.atlassian.net/browse/MM-40790
```release-note
NONE
```
> MM-40790 - Do not show license expired banner for Cloud

- reducers/plugins/index.ts
- types/store/plugins.ts
If a component's id is associated with multiple locations (such as `ChannelHeaderButton` and `MobileChannelHeaderButton`), it will only be removed from one of those places, since we short-circuit the removal process once we find one component:
https://github.com/mattermost/mattermost-webapp/blob/53868e12c770d6da4195955cf94a5b53b82a7c86/reducers/plugins/index.ts#L122-L136
In the app bar PR https://github.com/mattermost/mattermost-webapp/pull/9273, we changed the initialization of the plugin component store to start with empty arrays for the different component types, mainly to make the stored more strongly typed. Since `MobileChannelHeaderButton` happens to be initialized first, it exists first in order of keys in the `plugins.components` object. When we iterate over this object later to …
> MM-40766 unregisterComponent now removes plugin components from all associated locations

- components/file_preview_modal/file_preview_modal_main_actions/__snapshots__/file_preview_modal_main_actions.test.tsx.snap
- components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.test.tsx
- components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
This PR stops the "Get a Public link" button from showing in the file preview modal if the file being observed is an external image. 
There was an existing prop I noticed while testing this called `showPublicLink` which appears to be set to true if the `fileInfo.link` property exists, otherwise false. External images don't set this link property, and as a result `showPublicLink` gets set to false. So I'm adding an extra check here to make sure the public link button only shows up if `showPublicLink` is true
https://mattermost.atlassian.net/browse/MM-38501
|  uploaded image  |  externally linked |
|----|----|
| ![mattermost-filemodal-attached](https://user-images.githubusercontent.com/26177230/145492133-8bfe9e93-7ad9-4bcf-9100-22f48cb00399.png) | …
> [MM-38501] - observe showPublicLink prop when rendering file preview modal

- e2e/cypress/integration/files_and_attachments/image_link_preview_new_window_spec.js
- e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
- e2e/cypress/support/ui/file_preview.d.ts
- e2e/cypress/support/ui/file_preview.js
4 test cases fixed. one test needs to be verified. [MM-T332](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T332) . it's failing due to Bit links image is not rendering.
```release-note
NONE
```
> Cypress/E2E:fixed image preview test case

- components/suggestion/switch_channel_provider.jsx
- sass/components/_suggestion-list.scss
Channel switcher flashes no results if the search does not match the search term now it will show loading spinner instead.
Fixes https://mattermost.atlassian.net/browse/MM-38758
``None``
|----|----|
| https://www.loom.com/share/b5a0d09dad374d85a62601578a430c4f | https://www.loom.com/share/e683b728c6b14fcab386ae2903120ad6 |
```release-note
* add loader when fetching data from backend in channel switcher if there are no results matching local data
```
> [MM-38758] loading spinner in channel switcher if no local data matches

- components/channel_layout/center_channel/center_channel.test.tsx
- components/channel_layout/center_channel/center_channel.tsx
- components/channel_layout/center_channel/index.ts
- components/channel_view/__snapshots__/channel_view.test.tsx.snap
- components/channel_view/channel_view.test.tsx
- components/channel_view/channel_view.tsx
- components/channel_view/index.ts
- components/global_header/center_controls/user_guide_dropdown/index.ts
- components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.test.tsx
- components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
- components/main_menu/index.tsx
- components/main_menu/main_menu.test.tsx
- components/main_menu/main_menu.tsx
- components/next_steps_view/index.ts
- components/next_steps_view/next_steps_view.test.tsx
- components/next_steps_view/next_steps_view.tsx
- components/sidebar/__snapshots__/sidebar.test.tsx.snap
- components/sidebar/sidebar_next_steps/index.ts
- components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
- components/threading/global_threads/global_threads.tsx
- e2e/cypress/integration/enterprise/cloud/onboarding/cloud_legacy_invite_member_by_email_spec.js
- e2e/cypress/integration/onboarding/cloud_sysadmin_onboarding_spec.js
- e2e/cypress/integration/onboarding/invite_member_by_email_spec.js
- e2e/cypress/integration/onboarding/set_profile_and_team_spec.js
- plugins/test/__snapshots__/main_menu_action.test.jsx.snap
- plugins/test/main_menu_action.test.jsx
This PR makes the next steps view component accessible on it's own route `/:team/tips`
[MM-38154](https://mattermost.atlassian.net/browse/MM-38154)
```release-note
NONE
```
> [MM-38154] - Webapp: Change Getting Started/Tips & Next Steps to be it's own view rather than overlay on active channel

- packages/mattermost-redux/src/client/client4.ts
there was a recent improvement to set the correct ContentType to requests to be application/json, but it was generating an error response while uploading a license file. The solution is not add this header when the body is type of FormData since it will need a boundary and the fetch api is smart enough to add the ContentType header with a correct boundary.
https://github.com/mattermost/mattermost-webapp/pull/9615
Before (by setting the contentType to app/json):
After:
```release-note
NONE
```
> Let fetch api set the correct content-type to FormData requests

- components/suggestion/channel_mention_provider.jsx
Fixes: Archived channels are showing the globe channel icon in channel autocomplete
Fixes https://mattermost.atlassian.net/browse/MM-40484
``NONE``
|----|----|
|  ![image-2021-12-03-10-30-44-268](https://user-images.githubusercontent.com/16203333/148263744-911b73d6-14cc-42e0-ac6c-9356260bd523.png) | <img width="606" alt="Screenshot 2022-01-05 at 11 10 12 PM" src="https://user-images.githubusercontent.com/16203333/148263873-6aa11b11-137b-47d8-97f4-c3dcb69993f8.png"> |
```release-note
* UI: show archived channel icon for archived channels in channel autocomplete
```
> [MM-40484]Archived channels are showing the globe channel icon in channel autocomplete

- components/searchable_channel_list.jsx
Fixed the code which call [`scrollTo`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo) on next button of browse channels modal with only single parameters instead of two.
https://mattermost.atlassian.net/browse/MM-40552
~Has server changes (please link here)~
~Has mobile changes (please link here)~
https://user-images.githubusercontent.com/17708702/148368842-4c19ef58-ee2b-4da5-948d-bc4766e20742.mov
```release-note
NONE
```
> fix:MM-405552 : JavaScript error when browsing channels and clicking Next

- Makefile
- package-lock.json
- package.json
- skip_integrity_check.js
Copies a workaround for the integrity check issue that we've had people reporting since we upgraded mmjstool
See https://github.com/mattermost/mattermost-plugin-playbooks/pull/868 for more details
```release-note
NONE
```
> Add workaround for mmjstool integrity check failing

- components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
- components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
Fixed the callback from the function of `getCloseHandler`
Jira ticket: https://mattermost.atlassian.net/browse/MM-40681
Fix https://github.com/mattermost/mattermost-server/issues/19209
Fixes https://github.com/mattermost/mattermost-server/issues/40681
```
NONE
```
> [MM-40681] : The "Leave Channel" button doesn't work from the 3-dot menu when clicking on it second time

- components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
- components/status_dropdown/status_dropdown.tsx
- i18n/en.json
This PR fixes an issue where a menu header with text 'Status' appeared when custom status was disabled. The menu header would not appear if custom status was enabled (as expected).
Fixes [MM-40750](https://mattermost.atlassian.net/browse/MM-40750)
|  Before  |  After  |
|----|----|
| <img width="289" alt="MM-40750 Before" src="https://user-images.githubusercontent.com/23694620/149233961-ca5bb75d-0d74-477f-9057-2cd5bfee5127.png"> |<img width="289" alt="MM-40750 After" src="https://user-images.githubusercontent.com/23694620/149233994-7e76e467-130c-4b8c-9310-d151d333e1e1.png"> |
```release-note
NONE
```
> [MM-40750] Remove 'Status' Menu Header on Status Dropdown

- components/admin_console/admin_definition.jsx
- components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
- components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_modes.test.tsx.snap
- components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx
- components/admin_console/team_channel_settings/channel/details/channel_details.tsx
- components/admin_console/team_channel_settings/channel/details/channel_modes.tsx
- components/admin_console/team_channel_settings/channel/details/index.ts
- packages/mattermost-redux/src/types/general.ts
The new sku of Professional license now includes support for Channel Moderation which was moved from the higher sku. However, in previous versions of v6.0, channel moderation was still checking for the `LADPGroup` feature which is not available in the mid-tier license of Professional. 
This PR adds a license check for Professional to allow to unlock the `Channels` section of the System Console. The license check function added was introduced in v6.0 here https://github.com/mattermost/mattermost-webapp/pull/8554 and was included here to backport to a 5.37 release. 
This PR also adds the restriction to `Synch Group Members` and `Groups` within channel details if only on high sku license and not in Professional. This restrictions were the changes made in …
> MM-40824 - Backport support of Professional sku for channel moderation

- components/global_header/left_controls/history_buttons/history_buttons.tsx
This PR allows the history_buttons component to talk to the desktop app directly and determine whether the Back/Forward buttons should be enabled.
https://mattermost.atlassian.net/browse/MM-32371
Desktop: https://github.com/mattermost/desktop/pull/1941
```release-note
NONE
```
> [MM-32371] Enable desktop app to tell webapp when Back/Forward should be enabled

- components/admin_console/billing/billing_history.tsx
- components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
- components/admin_console/billing/billing_summary/billing_summary.tsx
- components/admin_console/billing/payment_info_edit.tsx
- components/admin_console/billing/plan_details/plan_details.tsx
- components/purchase_modal/purchase_modal.tsx
This PR replaces several occurrences of the anchor property target from _new, which is an incorrect value to the property  to _blank that is the correct way of calling it. Also, replaces the _new from _self for the download invoice link that was not working on the desktop app.
https://mattermost.atlassian.net/browse/MM-40894
https://user-images.githubusercontent.com/10082627/149197201-fef845fb-557b-4304-bead-44d0b24d1636.mp4
```release-note
NONE
```
> MM-40894 - not able to download license in desktop app

- utils/products.ts
Fixed a bug causing team sidebar to always show up in products when running in subpath.
[#19343](https://github.com/mattermost/mattermost-server/issues/19343)
Fixes a bug caused by #9262
```release-note
NONE
```
> Fixed a bug causing team sidebar to always show up in products when running in subpath

- components/channel_header/channel_header.js
- components/channel_header/channel_header.test.jsx
- components/channel_header/index.js
- components/search_hint/search_hint.test.tsx
- components/search_hint/search_hint.tsx
- components/search_results/__snapshots__/messages_or_files_selector.test.tsx.snap
- components/search_results/messages_or_files_selector.test.tsx
- components/search_results/messages_or_files_selector.tsx
- components/search_results/search_results.tsx
- utils/file_utils.jsx
Remove the channel file-related buttons if file attachments are disabled on the server.
Fixes https://mattermost.atlassian.net/browse/MM-38054
``None``
|----|----|
| <img width="1018" alt="Screenshot 2022-01-14 at 7 56 24 PM" src="https://user-images.githubusercontent.com/16203333/149531234-f36466c7-9a0c-406e-9332-39bfb98d6ccd.png"> | <img width="1792" alt="Screenshot 2022-01-14 at 7 52 34 PM" src="https://user-images.githubusercontent.com/16203333/149531305-39b1500f-af4a-41c3-9de9-e32562abc602.png"> |
```release-note
* UI: Remove the channel file related buttons if file attachments are disabled on the server
```
> [MM-38054] Remove the channel file related buttons if file attachments are disabled on the server

- actions/emoji_actions.js
- actions/emoji_actions.test.js
- actions/local_storage.jsx
- selectors/emojis.ts
- stores/local_storage_store.jsx
- stores/local_storage_store.test.jsx
Added memoized selector for `getOneClickReactionEmojis` redux selector
https://mattermost.atlassian.net/browse/MM-40559
None
None
```release-note
NONE
```
> chore/MM-40559 : Add memoization to getOneClickReactionEmojis

- e2e/cypress/integration/emoji/custom_emoji_2_spec.js
- e2e/cypress/integration/emoji/custom_emoji_3_spec.js
- e2e/cypress/integration/emoji/recently_used_emoji_spec.js
- e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/helpers.js
Adds end to end tests for following scenarious
https://mattermost.atlassian.net/browse/MM-40609
None
None
```release-note
NONE
```
> tests/MM-40609 : E2Es for recent custom emoji fixes 

- components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.test.tsx
- components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
- components/admin_console/license_settings/modals/upload_license_modal.test.tsx
- components/admin_console/license_settings/modals/upload_license_modal.tsx
- i18n/de.json
- i18n/en.json
- i18n/en_AU.json
- i18n/pl.json
Format the number of users attached to a license in "System Console > About > Edition and License".
Also applied formatting in the Upload license Modal confirmation message.
**Note:** A comment in the code reminds us that the labels must not be translated (because the labels are linked to the license that must stay in English) - that's why in the screenshot below, the French locale still has English labels.
https://mattermost.atlassian.net/browse/MM-37245
N/A
Locale = US (separator is `,`)
Locale = FR (separator is a space)
```release-note
NONE
```
> [MM-37245] Format the number of users in enterprise license details

- components/invitation_modal/no_permissions_view.tsx
- i18n/en.json
```release-note
Clarified in-product error string "Oops!" as "Unable to continue" for both translators and target audiences in cases where a user doesn't have sufficient permissions to add users or guests.
```
> Clarified in-product string

- e2e/cypress/integration/websocket/handle_new_post_spec.js
As far as I can tell, the assertions in these tests didn't match the
expected behavior. The first test asserted that the test user will see
a channel they were just added to as read, when they actually see
both the unread highlight and mention badge from the join system message.
There was also a problem with an implicit dependency between the first and second
tests. The second test again expected that the test channel starts as read from
the test user's point of view, but it reuses the same channel from the first test,
which ends on unread.
Certainly possible that I'm missing something obvious here, please correct me if I'm wrong.
```
NONE
```
> e2e: fix 'handle new post' spec read/unread assertions

- components/sidebar/add_channel_dropdown.tsx
- components/sidebar/add_channel_tutorial_tip.tsx
- components/sidebar/channel_navigator/channel_navigator.test.tsx
- components/sidebar/channel_navigator/channel_navigator.tsx
- components/sidebar/channel_navigator/index.ts
- components/sidebar/sidebar_header/sidebar_header.test.tsx
- components/sidebar/sidebar_header/sidebar_header.tsx
- packages/mattermost-redux/src/constants/config.ts
- packages/mattermost-redux/src/selectors/entities/preferences.ts
- packages/mattermost-redux/src/types/config.ts
- sass/layout/_sidebar-left.scss
The result of the AB testing led us to pick the "by_team_name" variant. This PR applies this change and removes the other ones.
https://mattermost.atlassian.net/browse/MM-41188
- Has server changes https://github.com/mattermost/mattermost-server/pull/19414
|----|----|
| ![image](https://user-images.githubusercontent.com/785518/151090699-21e6ed96-a87d-418f-8df1-712a630bfca2.png) | ![image](https://user-images.githubusercontent.com/785518/151090663-898a80cc-1263-4bf2-8806-95686eb58e0e.png) |
```release-note
NONE
```
> [MM-41188] Remove "Add Channel Button" feature flag

- components/admin_console/admin_definition.jsx
Follow-on work for https://github.com/mattermost/mattermost-webapp/pull/9717
```release-note
Removed incorrect in-product string text from the **Send full message contents** email notification option description displayed via **System Console > Site Configuration > Notifications**. 
```
> Remove incorrect string text

- components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
Tooltip in the DM category displays the wrong text.
This commit fixes that.
https://mattermost.atlassian.net/browse/MM-38332
```release-note
NONE
```
> MM-38332: fixes dm category menu

- e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
- e2e/cypress/integration/files_and_attachments/upload_files_spec.js
- e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_center_spec.js
- e2e/cypress/integration/multi_team_and_dm/close_current_dm_redirects_spec.js
- Fixed react_to_center_spec
- Fixed closed_current_dm_redirect spec
- Added `KNOWN ISSUE` to title of failing test cases with known issues that are currently unresolved
NA
```release-note
NONE
```
> Cypress/E2E: Fix react_to_center and close_current_dm_redirect specs

- components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
Cherry pick of #9646 on release-6.3.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #9646

- e2e/cypress/integration/emoji/recently_used_emoji_1_spec.js
- e2e/cypress/integration/emoji/recently_used_emoji_2_spec.js
- e2e/cypress/integration/emoji/recently_used_emoji_spec.js
- e2e/cypress/integration/mark_as_unread/mark_as_unread_spec.js
- recently_used_emoji_spec is passing for me locally but noticed the issue on cypress run might have something to do with calling beforeEach on every test. Modified the test so that setup is only once, hopefully fixing the finicky test on cypress run
- Added `KNOWN ISSUE: MM-41538`
NA
```release-note
NONE
```
> Cypress/E2E: Potential fix for recently used emoji spec

- actions/telemetry_actions.jsx
- components/channel_view/channel_view.tsx
- components/post_view/post_list/post_list.jsx
- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
I noticed two things in the telemetry data we were receiving:
1. The `channel_switch` events were no longer being reported.
2. The old `channel_switch` and existing `team_switch` data was reporting seemed low at around 200ms.
It was easy to spot that 1) was broken because of a mismatched name when marking the `channel_switch` event.
For 2) we were measuring when ChannelView updated which didn't mean that posts had been loaded and rendered. I moved that measuring to PostList and ensured that the posts had been loaded/mounted before marking the switch as complete. I also introduced the idea of `fresh` switches into the telemetry which indicates whether the posts for that channel had been loaded previously or not. This still isn't a perfect measurement but it will be more accurate to what …
> Fix and update channel switch performance telemetry tracking

- components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
- components/tutorial/tutorial_tip/index.ts
- selectors/onboarding.ts
The main change here is to make it so that we're not calling `makeGetCategory` in the `mapStateToProps` since that creates a new instance of the selector each time which prevents it from doing any memoization. Normally, I would've moved just it out into the outer `makeMapStateToProps` to memoize it on a per-component basis, but I figured I'd pull it out into its own selector at the same time so that we only have a single instance of that selector instead of one-per-component.
This is also an effort to improve some performance issues we're seeing on community. The profiles we've collected on community contain a large number of calls which appear to be to the `clearChannelSelection` action passed to `SidebarChannelLink`, but I think there's something wrong with the source mapping there …
> MM-41511 Fix repeated calls to makeGetCategory

- components/admin_console/billing/__snapshots__/billing_history.test.tsx.snap
- components/admin_console/billing/billing_history.test.tsx
- components/admin_console/billing/billing_history.tsx
This PR removes the value _new from anchor target property. _new is not a valid value, it just works to open a new tab window because it tries to open an existing tab named _new, since it fails to find it, it results in opening a new empty tab. Also, replacing it to _self so it works fine for downloading invoices from the desktop app which is the place where originally the problem was found.
https://mattermost.atlassian.net/browse/MM-40894
https://github.com/mattermost/mattermost-webapp/pull/9645
https://user-images.githubusercontent.com/10082627/152431906-80358f2c-9f7e-4fd5-927d-f4a274fa035e.mp4
```release-note
NONE
```
> Mm 40894 not able to download license from download history

- components/root/root.jsx
- sass/base/_structure.scss
- sass/layout/_sidebar-left.scss
- sass/layout/_team-sidebar.scss
- sass/routes/_backstage.scss
As discussed in https://community-daily.mattermost.com/core/pl/7rqqd1g1pig4xb1pp4j7ybnmqo, we're reverting these changes since the root CSS for the page is fragile, and those changes ended up breaking the position of some elements (notably the centre pane in Playbooks/Boards and the announcement bar/sidebar in Channels)
https://mattermost.atlassian.net/browse/MM-41342
https://github.com/mattermost/focalboard/pull/2263
||Before|After|
|-|-|-|
|Desktop View*|![Screen Shot 2022-02-04 at 1 40 40 PM](https://user-images.githubusercontent.com/3277310/152585003-1b85d1c7-ea1c-428b-92b4-1b6be9c80cb5.png)|![Screen Shot 2022-02-04 at 1 40 52 PM](https://user-images.githubusercontent.com/3277310/152585019-c26bc7f3-149d-4684-93e7-0eaf60dbe8dd.png)|
|Mobile View|![Screen Shot 2022-02-04 at 1 40 24 …
> MM-41342 Revert fixes related to using team sidebar in products

- sass/layout/_team-sidebar.scss
Based on https://github.com/mattermost/mattermost-webapp/pull/9755. Changes exclusive to it are in the latest commit
https://mattermost.atlassian.net/browse/MM-40887
https://github.com/mattermost/mattermost-webapp/pull/9755
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/3277310/152589775-5fa18eff-a478-4158-869f-0209071eeaf8.png)|![Screen Shot 2022-02-04 at 2 15 28 PM](https://user-images.githubusercontent.com/3277310/152589821-c42b5811-b4ff-4b91-8407-315fa1c466ba.png)|
||![Screen Shot 2022-02-04 at 2 13 47 PM](https://user-images.githubusercontent.com/3277310/152589853-c9f2f7cd-7a0c-4966-9461-262c94c38a4f.png)|
||![Screen Shot 2022-02-04 at 2 15 55 PM](https://user-images.githubusercontent.com/3277310/152590008-483d3b4b-13f0-45b5-9fc1-8c6f89c4c355.png)| …
> MM-40887 Fix team sidebar covered by global header with announcement bar visible

- components/root/root.jsx
When mattermost is installed on a subdomain (e.g. mattermost.example.com), rudder parses the top-level domain and sets their cookies using a general `.example.com` making the cookie available in every subdomain. This PR ensures the cookie is set to the actual subdomain by parsing SiteURL from the config
(you'll find this part as a comment bellow also)
After further investigation, it appears that focalboard are doing their own telemetry on the side (enabled with their own config.json), so while this fixes the problem with the webapp, having focalboard enabled will make the issue reappear. I'm working on implementing the same code on focalboard.
https://mattermost.atlassian.net/browse/MM-36643
N/A
N/A
```release-note
Fixed a bug causing rudder to create their cookies on the top-level domain …
```
> [MM-36643] Have rudder use the domain given on SiteURL for its cookies.

- components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
- components/global_header/center_controls/user_guide_dropdown/index.ts
- components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.test.tsx
- components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
- plugins/registry.js
- reducers/plugins/index.ts
- selectors/plugins.ts
- types/store/plugins.ts
As part of MM-29724, I have to give the `nps` plugin the ability the register a new menu item in the user guide dropdown.
**TODO:**
https://mattermost.atlassian.net/browse/MM-29724
- nps plugin PR: https://github.com/mattermost/mattermost-plugin-nps/pull/87
<details>
<summary>Give feedback has been added by a plugin</summary>
</details>
```release-note
Added a new plugin registry entry to append menu items to the user guide dropdown
```
> [MM-29724] Allow plugin to add menu items to the user guide dropdown

- components/create_comment/__snapshots__/create_comment.test.jsx.snap
- components/create_comment/create_comment.tsx
- components/create_post/__snapshots__/create_post.test.jsx.snap
- components/create_post/create_post.tsx
- components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
- components/edit_channel_header_modal/edit_channel_header_modal.tsx
- components/edit_post_modal/__snapshots__/edit_post_modal.test.tsx.snap
- components/edit_post_modal/edit_post_modal.tsx
- components/textbox/textbox_links/textbox_links.tsx
https://mattermost.atlassian.net/browse/MM-41327
https://github.com/mattermost/mattermost-webapp/pull/9697
```release-note
NONE
```
> MM-41327 : Avoid re-rendering of TextboxLinks component on typing (#9697) (6.3)

- components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
- components/quick_switch_modal/quick_switch_modal.tsx
- components/suggestion/suggestion_box/suggestion_box.jsx
Added a new prop `shouldSearchCompleteText` to suggestion box. When this is true suggestion box component will treat whole word as search input text.
https://mattermost.atlassian.net/browse/MM-40755
N/A
Before
https://user-images.githubusercontent.com/17708702/153572530-0e92ce31-c556-45dd-b05a-f1b6e8fb82e8.mov
After 
https://user-images.githubusercontent.com/17708702/153572627-edd33c4e-555d-490c-82b7-40afe2016cc3.mov
```release-note
Bug fix in channel switcher not searching when few starting characters are removed. 
```
> MM-40755 : Editing the text in the channel switcher does not work as expected

- packages/mattermost-redux/src/selectors/entities/channels.ts
`getMyFirstChannelForTeams` is a heavy selector that recomputes often. It's only needed in rare cases but it was getting called all the time due to poor placement inside the function. Super simple fix.
```release-note
NONE
```
> Only call getMyFirstChannelForTeams if needed

- components/purchase_modal/icon_message.scss
- components/purchase_modal/purchase.scss
This PR adds the code to refactor the payment page layout so the content fits well  no matter the language.
https://mattermost.atlassian.net/browse/MM-41280
```release-note
NONE
```
> MM-41280 - refactor the payment page layout so the content fits well

- components/popover_list_members/popover_list_members.jsx
- components/popover_list_members/popover_list_members.test.jsx
This PR adds a conditional logic based on the manage_private_channel_members permission to the `Add +` members to channel button that appears in the channel pop-up.
https://mattermost.atlassian.net/browse/MM-41369
Before:
*without the manage_private_channel_members permissions it was still showing the button.
After:
With the permission enabled:
With the permission disabled:
```release-note
NONE
```
> MM-42369 - restrict add members btn to roles with permissions

- components/__snapshots__/textbox.test.tsx.snap
- components/suggestion/at_mention_provider/at_mention_provider.jsx
- components/suggestion/at_mention_provider/at_mention_provider.test.jsx
- components/suggestion/suggestion_box/suggestion_box.test.jsx
- components/textbox/index.ts
- components/textbox/textbox.tsx
- packages/mattermost-redux/src/selectors/entities/channels.ts
- packages/mattermost-redux/src/selectors/entities/utils.ts
#9831
```release-note
Fix a major web and desktop app performance problem for users with large accumulated numbers of DMs and GMs.
```
> Cherry-pick  to 6.4 of "Improving selectors of Textbox component (#9831)"

- components/sidebar/sidebar_category/sidebar_category.tsx
Thanks to Jesús for pointing this out. Everywhere else that we use the accessibility events uses a state change to attach any additional listeners, so they can't be affected by this same issue.
```release-note
Fix potential memory leak in sidebar when using accessibility hotkeys
```
> Fix possible leak in SidebarChannel

- components/tutorial/tutorial_tip_legacy/index.ts
- packages/mattermost-redux/src/constants/config.ts
- packages/mattermost-redux/src/selectors/entities/preferences.ts
- packages/mattermost-redux/src/types/config.ts
Removes the AutoTour Feature flag.
As commented on the Jira ticket, while the tasks required to remove the Autotour feature because it lost the AB test, it's been used heavily in the Usecase Onboarding Growth Spike, so I did not touch the feature.
@stevemudie : the main changes applies to a component that is not really used anymore, So I think just making sure that the tutorials still works is the best way to QA this.
https://mattermost.atlassian.net/browse/MM-41408
- Has server changes https://github.com/mattermost/mattermost-server/pull/19495
N/A
```release-note
NONE
```
> [MM-41408] Remove FF for auto tour

- components/onboarding_tasks/onboarding_tasks_manager.tsx
Modify tasklist plugins show condition based on user preference in onboarding flow
https://community-daily.mattermost.com/boards/workspace/fpbb7orqpiyfxqgg6fcu91y5xo/b6ropkdiowj8eugbt8kifrew79h/v49mkf7kyxbd9zg9xhqaerzi1hy/cqewn8qhznbrc8jzhhud87qe68y
``NONE``
```release-note
UI: Modify tasklist plugins show condition based on user preference in onboarding flow
```
> Modify tasklist plugins show condition based on user preference in onboarding flow

- components/preparing_workspace/preparing_workspace.tsx
For instances created from cloud portal,  read from `myTeams` as a back up as `currentTeam` does not yet have data. This was causing separate errors for both the paths that:
* tried to create channels
* tried to redirect user to the main channels view
Opting to defer QA until this is running from instances created from test portal, as this is where the issue was observed.
https://mattermost.atlassian.net/browse/MM-42019
Was able to find this out on an instance created from test portal:
```release-note
NONE
```
> Read from myTeams if there is no currentTeam

- components/global_header/global_header.tsx
Change global header z-index causing issue with profile menu if RHS if is open.
Fixes https://mattermost.atlassian.net/browse/MM-41817
``NONE``
|----|----|
| ![image-20220222-182638](https://user-images.githubusercontent.com/16203333/155511938-7803bf44-5b63-4df4-9cec-ee6bcc326c71.png) | <img width="1043" alt="Screenshot 2022-02-24 at 4 25 36 PM" src="https://user-images.githubusercontent.com/16203333/155511891-bf631106-1e8f-4ed6-91d4-897439676a52.png"> |
```release-note
NONE
```
> [MM-41817] : Change global header z-index causing issue with profile menu if RHS if is open

- components/global_header/center_controls/global_search_nav/global_search_nav.tsx
- components/global_header/left_controls/history_buttons/history_buttons.tsx
This memory leaks are specially low priority because they happens on unmount,
and this 2 components only get unmounted when you stop seeing the global header
(than means, when you switch to the admin console, or when you switch to the
backstage.
Probably would be useful to talk about this other way of leaking memory in the
Developers Meeting.
Thanks to @hmhealey for bringing up this kind of issues.
NOT YET
```release-note
NONE
```
> Fixing possible (low priority) memory leaks

- actions/websocket_actions.jsx
On server restart web socket event, client config are fetched again.
https://mattermost.atlassian.net/browse/MM-40415
N/A
N/A
```release-note
Feature flags are automatically refreshed when server undergoes restart
```
> MM-40415 : Feature flags are not reloaded client-side when server restarts

- e2e/cypress/integration/mark_as_unread/mark_as_unread_spec.js
The listeners for the pointer cursor have moved to the individual posts, so I updated the E2E tests to simulate those events on the posts themselves.
I noticed one of the other tests in this file is failing for me locally (MM-T250), but that's not something that would affected by the change that broke the test I did fix.
https://mattermost.atlassian.net/browse/MM-41538
```release-note
NONE
```
> MM-41538 Fix E2E test broken by changes to listeners

- components/preparing_workspace/index.tsx
- components/preparing_workspace/preparing_workspace.tsx
- components/root/index.js
- components/root/root.jsx
- components/root/root.test.jsx
- components/root/root_redirect/index.ts
- components/root/root_redirect/root_redirect.tsx
- packages/mattermost-redux/src/selectors/entities/users.ts
Second admin should not see use case onboarding.
https://mattermost.atlassian.net/browse/MM-42103 , but only the `First admin vs second admin scenario:` scenario listed in the QA description.
Not related in the code sense, but there is a separate server PR that addresses the `>= 10` posts part of the bug:
* https://github.com/mattermost/mattermost-server/pull/19642
https://user-images.githubusercontent.com/13738432/155773390-6c3f863e-dab5-4549-9689-a076534c113c.mp4
```release-note
NONE
```
> only first admin sees preparing-workspace screen

- components/preparing_workspace/index.tsx
- components/preparing_workspace/preparing_workspace.tsx
- components/root/index.js
- components/root/root.jsx
- components/root/root.test.jsx
- components/root/root_redirect/index.ts
- components/root/root_redirect/root_redirect.tsx
- packages/mattermost-redux/src/selectors/entities/users.ts
Cherry pick of #9897 on cloud.
/cc  @neallred
```release-note
NONE
```
> Automated cherry pick of #9897

- plugins/registry.js
Fixing a documentation problem in the registerProduct plugin api
Not needed
```release-note
NONE
```
> Fixing a documentation problem in the registerProduct plugin api

- components/threading/global_threads/thread_list/thread_list.tsx
- e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_open_channel_from_global_threads_spec.js
Moving up/down doesn’t work as expected in find channels (ctrl/cmd + k) if global threads is in background, adding more specific conditions in threads list keyboard event listener to avoid this.
Fixes https://mattermost.atlassian.net/browse/MM-40444
``NONE``
|----|----|
| https://user-images.githubusercontent.com/16203333/155275448-2d681acc-2eca-4822-95d9-a0c163fee270.mp4 | https://user-images.githubusercontent.com/16203333/155275473-407afcec-7249-4d47-b2f9-b1066938a271.mp4 |
```release-note
*UI: up/down key in find channel when global threads are in background
```
> Keyboard up/down key issue in Channel switcher due to global thread list

- packages/mattermost-redux/src/actions/groups.ts
- packages/mattermost-redux/src/client/client4.ts
- packages/mattermost-redux/src/selectors/entities/groups.test.js
- packages/mattermost-redux/src/selectors/entities/groups.ts
Adding `group_source` to the query parameters in order to filter out custom groups
https://mattermost.atlassian.net/browse/MM-42068
https://mattermost.atlassian.net/browse/MM-42070
```release-note
Fixes a bug where custom groups were appearing in the UI when linking groups to channels/teams
```
> [MM-42068] Adding source query param to team and channel group endpoints

- .github/workflows/scorecards-analysis.yml
Github Action for Scorecard
https://github.com/ossf/scorecard
The Scorecard provides a (somewhat opinionated) view on the security posture of the repository -- we (the product security team) would like to adopt this on our key repositories to identify possible security improvements
> Add scorecard analysis

- sass/layout/_sidebar-left.scss
Removed `animation-fill-mode` css property on sidebar links for them to not overflow over to side bar menus
https://mattermost.atlassian.net/browse/MM-41952
N/A
|----|----|
| <img width="521" alt="image" src="https://user-images.githubusercontent.com/17708702/156352786-2db8dbd9-4d22-494a-aeb2-86bc40ff2dae.png"> | <img width="521" alt="image" src="https://user-images.githubusercontent.com/17708702/156352474-ecac9dab-da38-450d-8090-3572a0c69d75.png"> |
```release-note
Channel links on hover overlapping channels menus fixed
```
> MM-41952 : Unread channels names and sidebar item render on top of channel options menu

- components/post_view/post_list_virtualized/post_list_virtualized.jsx
This is a fix for a typo I introduced here: https://github.com/mattermost/mattermost-webapp/commit/286fb6dad8f7bb848d817ddbee30af915a388469#diff-ec9be19b2c781da350707675e6fe6a8483f55db7deaee8737edb55cc8ba79637L283
https://mattermost.atlassian.net/browse/MM-42131
https://github.com/mattermost/mattermost-webapp/pull/9508
```release-note
Fixed positioning of the post menu in mobile web view
```
> MM-42131 Fix accidental change to PostList positioning

- components/admin_console/data_grid/data_grid.tsx
Removed resize js event listener on unmount of data grid component which is used in admin console's channels, teams pages.
https://mattermost.atlassian.net/browse/MM-42274
N/A
https://community-daily.mattermost.com/core/pl/4y8qph3g87nm7kfx4bf9556zua
```release-note
Minute memory leak in admin console fixed.
```
> MM-42274 : Remove event listener "resize" on unmount of DataGrid component

- components/announcement_bar/default_announcement_bar/announcement_bar.tsx
- packages/mattermost-redux/src/actions/errors.ts
- packages/mattermost-redux/src/actions/general.ts
- packages/mattermost-redux/src/client/client4.ts
- packages/mattermost-redux/src/types/client4.ts
- root.jsx
This PR reworks how the webapp handles uncaught JS errors.
Firstly, it removes the unnecessary request in the `onerror` handlers, which causes an 401 anyway, as it doesn't contain a CSRF token.
Secondly, all JS errors now get logged - on `debug` level. This should help support with debugging issues.
If developers mode is enabled, the announcement banner shows the error information. The error message was added back. The background color is back to red.
Example log message on the server:
```
debug [2022-02-25 11:25:13.147 +01:00] Client Logs API Endpoint Message: {"type":"developer","message":"A JavaScript error has occurred. Please use the JavaScript console to capture and report the error (msg: Uncaught foo, row: 37, col: 159561).","stack":"foo","url":"http://localhost:8065/static/plugins/ …
```
> MM-42094 Rework handling of uncaught JS errors

- components/needs_team/needs_team.tsx
Whenever the app goes inactive, after 5 minutes of inactivity the app will set the users status to Away. A short time after the websocket will disconnect. We have an interval check that tries to fetch missing data after the computer wakes up from sleep, which we amended to also reconnect the websocket in order to get more missing data.
Unfortunately this causes an issue where the interval still runs if the user is Away, but the computer is still on and the app is inactive (but still running), thus the websocket keeps reconnecting and users are automatically set back to Online when this happens, meaning they might miss mobile notifications since the server still thinks they're Online.
This PR reverts that fix for the time being, and we'll need to come up with something else to address the …
> [MM-42207] Revert changes to wake up code where websocket is automatically reconnected

- components/admin_console/schema_admin_settings.jsx
- components/admin_console/schema_admin_settings.test.jsx
- The console would crash when trying to validate a page containing an item that is not a real 'setting' (=that does not contain the `key` attribute, example: the banner in the `Web Server`)
- The warning message next to the save button was wrongfully erased.
https://mattermost.atlassian.net/browse/MM-42298
N/A
The warning message works as expected (next to the save button at the bottom left):
The Web Server page (which contains a banner) now doesn't crash when changing values (previously, it would turn into a blank page).
https://user-images.githubusercontent.com/785518/156672159-aeb8773f-cb9a-422a-9f7d-e9e8ed5a1649.mp4
It does **not impact** the fields marked as required, they still display their own error message and block the save button:
```release-note
- Fixed a bug causing the …
```
> [MM-42298] Fix bugs introduced with console validation

- components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.scss
- components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.tsx
- components/collapsed_reply_threads_beta_modal/index.ts
- components/user_settings/modal/index.ts
- components/user_settings/modal/user_settings_modal.tsx
- i18n/en.json
- utils/constants.jsx
Adding CRT beta modal which was removed as part of https://github.com/mattermost/mattermost-webapp/pull/9289 (needs to be removed as soon CRT is ready for GA).
Fixes : CRT modal not showing the "Got It" Button in the Modal Footer.
Fixes https://mattermost.atlassian.net/browse/MM-40486
NONE
```release-note
UI: CRT Beta warning modal 
```
> [MM-40486] CRT beta warning modal

- components/onboarding_tasks/onboarding_tasks_manager.tsx
- components/onboarding_tour/onboarding_tour_manager.tsx
Opting out of the Channels tour doesn't check off the onboarding step as complete
Fixes https://mattermost.atlassian.net/browse/MM-42126
``NONE``
|----|----|
| ![Screen Shot 2022-02-28 at 11 36 04 AM](https://user-images.githubusercontent.com/16203333/156974220-3b319e34-d6ec-4d37-90c9-e0eb58de0977.png) |  <img width="399" alt="Screenshot 2022-03-07 at 11 06 26 AM" src="https://user-images.githubusercontent.com/16203333/156974263-d912deb9-1104-4baf-acc5-7ad71df4d5aa.png"> |
```release-note
UI: Fixes opting out of the Channels tour doesn't check off the onboarding step as complete
```
> [MM-42126] Fixes: opting out not marking channels tour complete in tasklist

- components/threading/global_threads/thread_list/thread_list.tsx
Fixes: Channel keyboard navigation breaks when in the Threads view
Note: Repro on Desktop app only
Fixes https://mattermost.atlassian.net/browse/MM-40267
``NONE``
|----|----|
| https://user-images.githubusercontent.com/16203333/156151927-51d8940f-07f1-427e-98d6-15f4854cc133.mp4 | https://user-images.githubusercontent.com/16203333/156151683-3c63bdca-b5b0-4890-a5ab-71c814af441c.mp4 | 
```release-note
Fixes: Channel keyboard navigation breaks when in the Threads view
```
> [MM-40267] Fixes: Channel keyboard navigation breaks when in the Threads view

- components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
- components/threading/global_threads/thread_list/thread_list.tsx
- components/threading/global_threads/thread_list/virtualized_thread_list.test.tsx
- components/threading/global_threads/thread_list/virtualized_thread_list.tsx
- e2e/cypress/integration/collapsed_reply_threads/following_spec.js
CRT: Ensure the Search Guidance row only appears on the “All your threads” tab
https://mattermost.atlassian.net/browse/MM-42127
```release-note
NONE
```
> MM-42127_Search row should not appear in the unreads tab

- components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
- components/admin_console/license_settings/license_settings.tsx
- components/admin_console/license_settings/modals/__snapshots__/upload_license_modal.test.tsx.snap
- components/admin_console/license_settings/modals/upload_license_modal.test.tsx
- components/admin_console/license_settings/modals/upload_license_modal.tsx
- components/admin_console/license_settings/starter_edition/starter_left_panel.tsx
- utils/constants.jsx
Change the UI flow for the upload license process. This PR removes a step from the UI flow for uploading a license. With these changes when you click the upload button, the OS file selector window is shown and when you select the file THEN the upload modal is shown with the file information.
https://mattermost.atlassian.net/browse/MM-41745
https://user-images.githubusercontent.com/10082627/156860041-010a3be3-3e4c-44e6-85d5-75d2d066e617.mp4
```release-note
NONE
```
> MM-41745 refactor upload license flow

- e2e/cypress/integration/account_settings/security/password_spec.js
Cypress test for MM-T2086:
Check that password setting _(in profile settings)_ shows password was updated at current time.
Additionally, check that an email notification about the password update is received.
Fixes https://github.com/mattermost/mattermost-server/issues/18818
> [MM-T2086] Cypress test for changing password and checking email and timestamp

- actions/telemetry_actions.jsx
- plugins/index.js
With this, we'll be tracking:
1. How many plugins are loaded
2. How much JS is transferred while loading them
3. How long it takes to load the plugins, both in real time and the total time taken to load them all
I think having both real time and total duration is interesting since it could let us compare how long each takes to load on average while also being able to see how long the overall load takes if we're finding that the app is getting bottlenecked while loading a dozen plugins at once
https://mattermost.atlassian.net/browse/MM-41830
```release-note
Added performance metrics related to plugin loading on page load
```
> MM-41830 Add metrics for plugin loading

- components/preparing_workspace/use_case.tsx
Missed adjusting svg positioning for cloud workspaces. For cloud workspaces, there is no previous button on the use case screen because it is the first step for the cloud admin.
https://mattermost.atlassian.net/browse/MM-42291
```release-note
Fix svg positioning in admin onboarding when screen does not have a previous button.
```
> adjust svg positioning for cloud case with no previous button

- components/admin_console/license_settings/trial_banner/trial_banner.tsx
- i18n/en.json
The button's text is "Upgrade Server And Start trial", and not "Upgrade
And Start trial"
I just found this error, there are no ticket exists.
Here it shows, that the button text is not matching with the help text.
```
NONE
```
> [FIX] admin_console/licence_settings: fix of referencing to a button

- actions/websocket_actions.jsx
On websocker reconnect moved the reloading of the plugins after getting user, post etc.
https://mattermost.atlassian.net/browse/MM-30805
N/A
N/A
```release-note
NONE
```
> MM-30805 : On websocket reconnect, plugins are reloaded before the rest of the app

- components/emoji_picker/utils/index.ts
Added safety checks in `getCursorProperties` function to return early in case of undefined or nulls. Currently the emoji picker and gif picker both renders on either tab is selected since they supposedly share the same search text.
https://mattermost.atlassian.net/browse/MM-42321
N/A
https://user-images.githubusercontent.com/17708702/158060417-87b60e77-6446-4909-a509-1e8fe4939082.mov
```release-note
Fixed client app crash when typing into search of Gif picker.
```
> MM-42321 : Client crashed on typing text in the Gif picker search

- .gitignore
- Makefile
- config.mk
This is a dev QOL PR, no new feature.
This PR changes the Makefile to add a `RUN_CLIENT_IN_BACKGROUND` variable defaulting to `true` (current behavior), allowing devs to decide if they wanna run the client in foreground or background.
To make sure we have a smooth experience between projects: 
- I copied the configuration model of `mattermost-server` (`config.mk` + optional and ignored  `config.override.mk`).
- The way to deal with the new variable has been copied from `mattermost-server`
https://github.com/mattermost/mattermost-server/blob/dd100a3a697b39a83ca7c62b00ed9aaedc9bed10/Makefile#L161-L164
N/A
N/A
N/A
```release-note
NONE
```
> Makefile: run the client in the foreground

- components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
- components/dot_menu/dot_menu.test.tsx
- components/dot_menu/dot_menu.tsx
- e2e/cypress/integration/messaging/copy_post_text_spec.js
- i18n/en.json
- utils/constants.jsx
Adds a post menu item with the keyboard shortcut "C" that will copy the post's raw message.
https://mattermost.atlassian.net/browse/MM-35594
```release-note
Add post menu item to copy raw text
```
> MM-35594 Add post menu item to copy text

- components/__snapshots__/generic_modal.test.tsx.snap
- components/custom_status/custom_status_modal.tsx
- components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
- components/edit_category_modal/edit_category_modal.tsx
- components/generic_modal.scss
- components/generic_modal.tsx
- components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap
- components/product_notices_modal/product_notices_modal.tsx
- components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx
As part of [PR9862](https://github.com/mattermost/mattermost-webapp/pull/9862) a `<form>` wrapping tag was removed and with that unintentionally was removed the functionality of submit forms that were using the generic modal component when pressing the Enter key. This PR enhances the GenericModal component by providing a handler event for the Enter key press, that way we add back that functionality without the extra problems that was giving the wrapper form tag by default given that now every component using the generic modal will be able to define if want to perform a particular action by the enter key press.
https://mattermost.atlassian.net/browse/MM-42614
```release-note
NONE
```
> MM 42614 fix e2e broken tests

- components/main_menu/__snapshots__/main_menu.test.tsx.snap
- components/main_menu/main_menu.tsx
- plugins/test/__snapshots__/main_menu_action.test.jsx.snap
- plugins/test/main_menu_action.test.jsx
Render main menu items added by plugins.
https://mattermost.atlassian.net/browse/MM-41273
```release-note
Restored rendering of main menu items from plugins in non-mobile view
```
> MM-41273 : Restore main menu items added by plugins

- components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
- components/dot_menu/dot_menu.tsx
- components/rhs_root_post/rhs_root_post.jsx
- components/widgets/menu/menu_items/menu_item_action.test.tsx
- components/widgets/menu/menu_items/menu_item_action.tsx
This PR fixes a misalignment issue caused by https://github.com/mattermost/mattermost-webapp/pull/8853. In that PR, I created more problems than necessary with updates to the `menu_item_action` component. In this PR, I create the `rightDecorator` as a component and pass it in to `menuItem`
I would like to merge this PR in to https://github.com/mattermost/mattermost-webapp/pull/10028. 
https://mattermost.atlassian.net/browse/MM-42604
```release-note
NONE
```
<details>
<summary>Details</summary>
</details>
> [MM-42604] - Status menu items are misaligned

- components/admin_console/system_users/system_users.tsx
- i18n/en.json
- utils/constants.jsx
- utils/filter_users.ts
Mattermost system console user list should allow to filter out inactive users, or in other words to only show active users and admins.
Right now you only have following options:
"All users"
"System Admins"
"Guests"
"Inactive"
This PR adds new option "Active" to the list.
The API on the server side is already present:
This URL returns inactive  users:
/api/v4/users?page=0&per_page=100&inactive=true
This URL returns active users:
/api/v4/users?page=0&per_page=100&inactive=false
https://mattermost.uservoice.com/forums/306457-general/suggestions/44133915-filter-out-inactive-users-in-mattermost-system-con
and partially https://github.com/mattermost/mattermost-server/issues/12319
```release-note
Adds another …
```
> Adds another 'Active' filter users and admins in AdminConsole/UserManagement/Users

- components/admin_console/group_settings/groups_list/groups_list.test.tsx
- components/admin_console/group_settings/groups_list/groups_list.tsx
Fixes an issue with pagination for groups in system console.
Fixes [MM-40072](https://mattermost.atlassian.net/browse/MM-40072)
https://user-images.githubusercontent.com/23694620/156460326-e86a1a83-6fb2-4d53-a73c-4035258e235e.mov
```release-note
NONE
```
> [MM-40072] Fix Groups Pagination in System Console

- actions/telemetry_actions.jsx
- components/root/root.jsx
- components/root/root.test.jsx
- packages/reselect/src/index.js
Hopefully this is something we can work with on Looker. I'd like to report the 3 least effective selectors so that we can see how they change over time to watch out for either:
1. A new selector suddenly becoming the worst or
2. An existing selector getting better as we make improvements to it
I also included some numeric data since that might be helpful if we start to focus more on individual selectors, but I could remove that in case we're worried about the data getting bloated.
https://mattermost.atlassian.net/browse/MM-41820
```release-note
Added telemetry for selector performance
```
> MM-41820 Report least effective selectors as telemetry

- components/dot_menu/dot_menu.test.tsx
- components/dot_menu/dot_menu.tsx
- components/dot_menu/utils.tsx
This PR fixes an issue where the shortcut additions in the post dot menu had disabled the ability to click the menu item with the mouse.
QA should verify that both the shortcut and clicking activate the desired response.
```release-note
```
> [MM-42636] fix disabled dot menu clicking 

- packages/mattermost-redux/src/client/client4.test.js
- packages/mattermost-redux/src/client/client4.ts
Add graphql client to existing client4 client. 
Example usage
```typescript
const {data} = await Client4.fetchWithGraphQL<MyDataQueryResponseType>(myDataQuery);
```
https://mattermost.atlassian.net/browse/MM-42390
N/A
N/A
```release-note
NONE
```
> MM-42390 : Make a minimal GraphQL web client

- packages/mattermost-redux/src/reducers/entities/threads/counts.ts
Upon reconnecting the websocket we are fetching unread threads,
but we don't update unread counts when we do that.
This PR adds those updates on the counts reducer.
This is done to fix the negative counts that can happen when:
While disconnected you might receive a new thread.
If you view the new thread before reconnecting,
and then view an old thread,
that would set the count to a negative value.
Showing "you have -1 unread threads".
https://mattermost.atlassian.net/browse/MM-41808
```release-note
NONE
```
> MM-41808: fixes negative unread counts for threads

- components/actions_menu/actions_menu_tutorial_tip.tsx
This PR solves an issue where scrolling up and down the posts in a channel (when the pulsating tooltip is showing) would produce the following error. This is introduced by using the required `overlayPunchOut` prop of the `TourTip` component. 
The solution I chose was to pass `null` into this prop, as suggested inside the tour tip component.
Testing: 
Before:
scrolling up and down post list would show warning once and only once. To see it again, user must refresh the page.
After: 
scrolling up and down the post list never displays the error in the console.
**None related change: **
convert `nextBtn` from callable function to a const that returns the value of function.
https://mattermost.atlassian.net/browse/MM-42778
```release-note
```
> [MM-42778] Fix console warning introduced by Actions Menu

- selectors/actions_menu.ts
When a user is in the mobile view, the actions menu should not wait for the user to view the tooltip.
* do not show pulsating dot on Action menu
* clicking the Actions Menu will always open the menu
* side effect is that they can use the new Actions Menu feature on mobile, but will see the pulsating dot if viewing on web view.
I added the logic to the selector which is used by post_info, rhs_comment, and rhs_root components.
https://mattermost.atlassian.net/browse/MM-42603
|----|----|
| ![image](https://user-images.githubusercontent.com/7575921/160440485-5c870b2b-5021-4d47-9604-60c6b657ff5a.png)| <img width="572" alt="image" src="https://user-images.githubusercontent.com/7575921/160441049-0c5b6f42-4d91-40c6-9385-8fb3a733e91d.png"> |
```release-note
```
> [MM-42603] if mobile view, don't show pulsating dot. Always open the actions menu

- components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
- components/admin_console/admin_sidebar/admin_sidebar.jsx
- components/admin_console/admin_sidebar/index.js
- sass/routes/_admin-console.scss
The task list icon button was covering the bottom items options in the system console. This PR checks if the task list button is shown and if so, it adds a css class which adds more padding to the bottom so the options can be seen.
https://mattermost.atlassian.net/browse/MM-42353
n/a
Before:
After:
```release-note
NONe
```
> MM-42353 - add more padding bottom if task list is shown

- packages/mattermost-redux/src/actions/admin.ts
- packages/mattermost-redux/src/actions/channel_categories.ts
- packages/mattermost-redux/src/actions/channels.ts
- packages/mattermost-redux/src/actions/files.ts
- packages/mattermost-redux/src/actions/general.ts
- packages/mattermost-redux/src/actions/groups.ts
- packages/mattermost-redux/src/actions/helpers.ts
- packages/mattermost-redux/src/actions/integrations.ts
- packages/mattermost-redux/src/actions/posts.ts
- packages/mattermost-redux/src/actions/search.ts
- packages/mattermost-redux/src/actions/teams.ts
- packages/mattermost-redux/src/actions/threads.ts
- packages/mattermost-redux/src/actions/users.ts
- packages/mattermost-redux/src/actions/websocket.ts
- packages/mattermost-redux/src/types/actions.ts
We declared our own version of redux-batched-actions when we migrated mattermost-redux to TypeScript. I wasn't sure why we did that originally, but I now think that's because TypeScript threw a bunch of errors, mostly about how we used `logError`. It turns out that redux-batched-actions doesn't work with redux-thunk (https://github.com/tshelburne/redux-batched-actions/issues/3), so that code didn't actually work to begin with.
I don't know if we actually need `logError` at this point, and we could probably implement it in a way that's batching-friendly, but I just went with removing them from batches for the time being.
https://mattermost.atlassian.net/browse/MM-41607
```release-note
NONE
```
> MM-41607 Don't redeclare redux-batched-actions

- packages/mattermost-redux/src/actions/errors.ts
There's more context in this thread https://community-daily.mattermost.com/core/pl/xirywgxsw3rit815umggaoaz9y, but essentially the [error.stack](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack) property is non-standard and can take on different shapes, including a nested structure like the following:
This causes an exception on the `.includes` line in the diff of this PR, which makes it so the browser never sends the error to the server.
Fixes https://mattermost.atlassian.net/browse/MM-42884
> [MM-42884] Guard against malformed error when logging

- components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.tsx.snap
- components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.tsx
- components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
- components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
- components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
- components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.test.tsx
- components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
- components/admin_console/permission_schemes_settings/permissions_tree/types.ts
- components/admin_console/permission_schemes_settings/permissions_tree_playbooks.test.tsx
- components/admin_console/permission_schemes_settings/permissions_tree_playbooks.tsx
- packages/mattermost-redux/src/types/general.ts
Cherry pick of #10084 on release-6.6.
```release-note
NONE
```
> Automated cherry pick of #10084

- components/admin_console/team_channel_settings/channel/details/channel_members/index.ts
- components/channel_header/index.js
- components/popover_list_members/index.ts
- packages/mattermost-redux/src/selectors/entities/users.test.js
- packages/mattermost-redux/src/selectors/entities/users.ts
`makeGetProfilesInChannel` takes in an optional `filters` object that does further filtering on the array of users returned, but because of the way we pass it into the result function, it has the potential to cause the selector to recompute constantly if we pass in new object literals each time the selector is called. Usually, I'd get rid of the filters object and pass individual fields to fix that, but since `filters` has 5 or 6 different optional fields, I decided to just memoize `filters` where it was used.
`makeGetProfilesNotInChannel` is also at risk of the same problem, but we never actually passed `filters` to it, so I just removed that option.
https://mattermost.atlassian.net/browse/MM-42654
```release-note
NONE
```
> MM-42654 Improve memoization of makeGetProfilesInChannel

- components/common/hooks/useCopyText.ts
The track callback was being fired every time the hook fired (bad). We should only trigger it when the copy text element is actually clicked.
https://mattermost.atlassian.net/browse/MM-43003
```release-note
Fix copy links to not fire track callback until copy link is actually clicked.
```
> fix placement of track callback

- components/integrations/__snapshots__/abstract_command.test.jsx.snap
- components/integrations/abstract_command.jsx
Cherry pick of #10118 on cloud.
```release-note
NONE
```
> Automated cherry pick of #10118

- components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.test.tsx
- components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
fixes: public links are being generated by the server even if public links are disabled in the config.
Note: we might need to check the server error log's 
Fixes https://mattermost.atlassian.net/browse/MM-42928
n/a
|----|----|
| https://user-images.githubusercontent.com/16203333/161056571-0d2c013e-4017-4149-87a8-142e94b6ac2e.mov | https://user-images.githubusercontent.com/16203333/161056763-30f2f04b-9e6f-40f5-854f-bebea56c82e4.mov |
```release-note
Bug fixes: public link generate API was getting called even if public links are disabled
```
> [MM-42928]: fixes public links are being generated by the server even if public links are disabled in the config

- components/dot_menu/dot_menu.tsx
This PR solves an issue where `Save/Unsave` `Pin/Unpin` shortcuts (`S`), (`P`)require pressing twice to execute the action. 
http://localhost:8065/testing-org/pl/od3kp6m1hjbhmxmz61mec6rqec
```release-note
```
> [MM-48892] fix shortcut key double press to activate action

- components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- i18n/i18n.jsx
Cherry pick of #10134 on release-6.6.
```release-note
NONE
```
> Automated cherry pick of #10134

- actions/websocket_actions.jsx
- actions/websocket_actions.test.jsx
In https://github.com/mattermost/mattermost-webapp/pull/8545, a change to dispatch `RECEIVED_WEBAPP_PLUGIN` was introduced on receipt of a websocket event for enabling a plugin. Unfortunately, this had the unexpected effect of changing the semantics of plugin reloading.
In particular, for Playbooks, if that version of the plugin was already installed, instead of replacing it, it would appear to be removed altogether. The plugin registration and management is, unfortunately, very brittle.
No test is included with this PR at this time.
Fixes: https://mattermost.atlassian.net/browse/MM-43194
```release-note
NONE
```
> MM-43194: remove plugin-related dispatch on enable

- actions/websocket_actions.jsx
- actions/websocket_actions.test.jsx
Cherry pick of #10152 on release-6.6.
```release-note
NONE
```
> Automated cherry pick of #10152

- components/code_block/__snapshots__/code_block.test.jsx.snap
- components/code_block/code_block.tsx
Removed the ability to hold on the CodeBlock in order to show the context menu. Now it will only show on right click.
Fixes [MM-42916](https://mattermost.atlassian.net/browse/MM-42916)
```release-note
Fixes a bug where the context menu would get in the way when highlighting text
```
> [MM-42916] Fixes context menu gets in the way when highlighting text

- components/code_block/__snapshots__/code_block.test.jsx.snap
- components/code_block/code_block.tsx
Cherry pick of #10136 on release-6.6.
/cc  @cleferman
```release-note
NONE
```
> Automated cherry pick of #10136

- sass/routes/_backstage.scss
Adjusts the backstage body element height to accommodate the banner
https://mattermost.atlassian.net/browse/MM-41791
N/A
N/A
```release-note
NONE
```
> MM-41791 : Custom emoji "Next" button out of view when banner is present

- e2e/cypress/tests/integration/onboarding/cloud_user_onboarding_spec.js
It's been reported that the e2e test `MM-T3326 - Sysadmin onboarding` was broken because the page tested (`/tips`) is not presented anymore to sysadmins. Turns out all the tests in this file depend on sysadmins accessing `/tips` so no tests in this file were valid.
That being said, regular users still have access to this page, so I decided to convert the tests to a `User onboarding` rather than dropping the file. If this is not desired let me know and I'll drop the file.
https://mattermost.atlassian.net/browse/MM-42795
N/A
N/A
```release-note
NONE
```
> [MM-42795]  Cypress test MM-T3326 is broken

- README.md
Updated Docker instructions to point to new instructions after [PR#5517](https://github.com/mattermost/docs/pull/5517) is merged.
See also: [PR#19924](https://github.com/mattermost/mattermost-server/pull/19924)
```release-note
NONE
```
> Update link to Docker instructions

- package.json
Implicitly we assume developers have node 16 to build mattermost, but this is not enforced. Adding this to `package.json` will issue a warning.
See [this discussion on community](https://community.mattermost.com/core/pl/gwp64h5yhtf48g3sojoin91e9o)
```release-note
NONE
```
> Added minimum node and npm version requirement

- .gitpod.yml
This PR makes it so when this repository is used to create a Gitpod workspace, the configuration used will be delegated to the [mattermost-gitpod-config](https://github.com/mattermost/mattermost-gitpod-config) repo through its [.gitpod.yml](https://github.com/mattermost/mattermost-gitpod-config/blob/master/.gitpod.yml) file.
This allows multiple repos to share the same Gitpod config, as well as keeping the commit history minimal in regards to the individual repos.
https://www.gitpod.io/docs/references/gitpod-yml
https://www.gitpod.io/docs/multi-repo-workspaces
https://mattermost.atlassian.net/browse/MM-43384
```
NONE
```
> Add .gitpod.yml to use mattermost-gitpod-config repo for Gitpod configuration

- selectors/plugins.ts
The focalboard link on the channel intro does not appear if the AppBarEnabled feature flag is turned on. 
The intro link shouldn't work differently for this. 
Fixes https://github.com/mattermost/focalboard/issues/2709
- focalboard changes - https://github.com/mattermost/focalboard/pull/2766
```release-note
NONE
```
> fix channel intro components with app filter on

- package-lock.json
- skip_integrity_check.js
Checksum for `mattermost/marked` was failing in the same way as `mmjstool` was, so I've removed the integrity check for it as well.
```release-note
NONE
```
> Skip integrity check for mattermost/marked

- actions/views/rhs.test.ts
- actions/views/rhs.ts
- components/channel_members_rhs/channel_members_rhs.tsx
- components/channel_members_rhs/index.ts
- packages/mattermost-redux/src/actions/channels.ts
I was looking at the `channel_admin` role on the membership to determine if a user was a channel admin, turns out this was not working on the community server because it has a Team Override Schemes.
If you want to reproduce the bug (fixed in the spinwick):
- Create a new team.
- Create a Team Override Schemes (add a name, description and add your team)
- Make someone a channel admin
- Go back to the channel member RHS
Without the fix: the user is not listed as a channel admin
With the fix: the user is listed as a channel admin
Also:
- The Channel member RHS would crash when coming back from the Admin console because the channel was not loaded.
- Sometimes the member (as in user of the channel) role was not loaded despite the fact that the member was. I now load the member role. …
> [MM-43328] Fix Channel admin not listed in their groups

- actions/views/rhs.test.ts
- actions/views/rhs.ts
- components/channel_members_rhs/channel_members_rhs.tsx
- components/channel_members_rhs/index.ts
- packages/mattermost-redux/src/actions/channels.ts
Cherry pick of #10176 on cloud.
```release-note
NONE
```
> Automated cherry pick of #10176

- components/team_sidebar/components/team_button.tsx
- components/team_sidebar/team_sidebar.tsx
The team sidebar in products shows channel's, unread message count. This is incorrect. This PR adds the feature of hiding the unread msg count badge when being rendered in a product.
https://github.com/mattermost/focalboard/issues/2802
```release-note
none
```
> Made unread msg badge in team sidebar hidden in products

- components/admin_console/workspace-optimization/dashboard.tsx
There was an issue with the subpaths because the initial implementation was not using the general function to get the base route and was just relying on fetch api to get the relative url path. This PR uses the `Client4.getBaseRoute()` function call to avoid any problem with url subpaths.
https://mattermost.atlassian.net/browse/MM-42885
n/a
n/a
```release-note
NONE
```
> MM-42885 - fix relative path url problem with subpath

- actions/telemetry_actions.jsx
I think these metrics aren't being sent because we're checking if performance metrics are enabled before we have that config setting loaded
https://mattermost.atlassian.net/browse/MM-43302
```release-note
Fix timing of selector performance metrics
```
> MM-43302 Check if performance metrics are enabled closer to when we send selector metrics

- components/admin_console/schema_admin_settings.jsx
- i18n/en.json
Fixes https://github.com/mattermost/mattermost-server/issues/19691
```release-note
NONE
```
> MM-42316: Error message when clicking on test connection button without saving

- components/threading/global_threads/global_threads.tsx
Since we don't have a ThreadCreated WS event, we can't know the total
number of threads currently in global threads with certainty.
So when you follow new threads by replying you won't see the end of the
list component in the global threads, since the total count you have is
less than the actual count, also you might miss some threads in the end
of the list when paginating.
This commit fixes this issue by fetching thread counts once, each time you
enter global threads.
```release-note
NONE
```
> MM-41565: fixes total thread count

- e2e/cypress/tests/integration/messaging/message_with_gif_spec.js
- Replaced tenor gif url and width to fix message with gif spec
NA
```release-note
NONE
```
> Cypress/E2E: Fix message with gif spec

- packages/types/src/admin.ts
PluginAnalytics name type changed to React.ReactNode. 
This is needed to match the type that will be used from the plugins which are using `<FormattedMessage.../>` to translate the names of the stats. [Example at playbooks](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1128/files#diff-47ddfada7835e6c591120fc4ca2bde4e83ba9834df8550cddb48349d7040b36eR140)
This type did not fail before because pluginRegistry is not typed yet.
https://mattermost.atlassian.net/browse/MM-42971
https://github.com/mattermost/mattermost-webapp/pull/10180
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1128
```
NONE
```
> set plugin stat title type to reactnode to enable translations

- components/channel_layout/playbook_runner.tsx
- packages/mattermost-redux/src/selectors/entities/channels.test.js
- packages/mattermost-redux/src/selectors/entities/channels.ts
The route handler for `:team/_playbooks/:playbookId/run` was incorrectly sensitive to the currently selected team, and would inadvertently switch teams if it found a channel matching the "current channel name" (i.e. the commonly shared, `town-square`), preventing the handler from ultimately finding the playbook since it wasn't on that team.
Introduce a new Redux selector and use it to constrain the search for channels by name in the given team. In addition to the unit tests in this PR, see linked PR for E2E tests in Playbooks itself.
Fixes: https://mattermost.atlassian.net/browse/MM-42755
- https://github.com/mattermost/mattermost-plugin-playbooks/pull/1146
```release-note
NONE
```
> MM-42755: consistently run playbook

- sass/components/_post.scss
This is a fix for a long running, but easy to fix bug where the "New Messages Below" banner in the mobile web view wasn't able to be clicked on because it was covered by the invisible div that holds the floating timestamp.
https://mattermost.atlassian.net/browse/MM-28269
```release-note
Fixed the New Messages toast in mobile web view not being fully clickable
```
> MM-28269 Allow clicking through mobile web view timestamp

- components/root/root.jsx
- components/root/root.test.jsx
So we've had a feature for a while that logs a user in and out on multiple tabs if they have multiple tabs open at once. That was broken for a while, and then it was re-added in https://github.com/mattermost/mattermost-webapp/pull/6319, but when it was re-added, it was changed to only actually log the user in when the window became visible. I thought this was broken a while back, but it turns out that it just didn't work if the tab was already visible because you had multiple windows open at once instead of two tabs in a single window.
This changes it so that the login reload is triggered when the window gains focus to allow it to work when you have two tabs in separate windows open.
https://mattermost.atlassian.net/browse/MM-29798
```release-note
NONE
```
> MM-29798 Log in background tabs on focus

- packages/mattermost-redux/src/actions/users.ts
We are asking for CRT preference state in redux before we actually fetch
the user's preferences, resulting in always being false.
This commit fixes that by moving the selector after the dispatches have
finished and the state has been updated.
```release-note
NONE
```
> Fixes: invalid CRT preference state

- components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
- components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
- components/sidebar_right/sidebar_right.jsx
Cherry pick of #10261 on cloud.
```release-note
NONE
```
> Automated cherry pick of #10261

- components/new_channel_modal/new_channel_modal.tsx
- e2e/cypress/tests/integration/multi_team_and_dm/existing_channel_name_spec.js
Cherry pick of #10264 on cloud.
```release-note
NONE
```
> Automated cherry pick of #10264

- components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
- components/link_tooltip/link_tooltip.scss
- components/link_tooltip/link_tooltip.tsx
- e2e/cypress/tests/integration/plugins/link_tooltip_spec.js
The PR #10004 for "Eliminate unnecessary tooltip divs added for links" introduced a few issues when hovering over a  plugin `LinkTooltip` link:
- In certain mouse and screen positions, the tooltip be placed right at the pointer of the mouse, causing sporadic `mouseon` and `mouseleave` events to fire. This makes the tooltip flicker continuously.
- The protocol for this plugin feature has changed. Before the PR, the `LinkTooltip` component was mounted on initial render of the post containing the link. The component receives a `show` prop when it needs to react to being hovered. After the PR, the component is mounted on hover, making it so the component cannot do any local state caching.
- The popover does not fade into appearance anymore. It just instantly shows instead.
The first two …
> Fix plugin link tooltip flickering

- components/actions_menu/__snapshots__/actions_menu.test.tsx.snap
- components/actions_menu/actions_menu.test.tsx
This PR adds more unit tests for the actions menu
https://mattermost.atlassian.net/browse/MM-43345
```release-note
NONE
```
> add more unit tests for sysadmin vs end user

- i18n/en.json
This PR fixes the shortcut info modal which was showing the wrong shortcut for the show channel info on mac.
https://mattermost.atlassian.net/browse/MM-44172
N/A
```release-note
NONE
```
> [MM-44172] Fix hotkey for channel info shows alt instead of shift in the shortcut [mac only]

- e2e/cypress/tests/integration/channel_settings/add_users_to_channel_spec.js
Fixed add_user_to_channel_spec test case
```release-note
NONE
```
**E2E**
> E2E/Cypress:fixed add user to channel test case

- sass/components/_post.scss
Post hover state was adding incorrect padding to the post-header for the compact message display.
[MM-44228](https://mattermost.atlassian.net/browse/MM-44228)
n/a
n/a
```release-note
NONE
```
> [MM-44228]: fixed post hover-state on compact message display

- components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
- i18n/en.json
Advanced Text Editor: fix show preview tooltip text for windows/linux
Fixes https://mattermost.atlassian.net/browse/MM-44389
Epic: https://mattermost.atlassian.net/browse/MM-41347
NONE
NONE
```release-note
Advanced Text Editor: fix show preview tooltip text for windows/linux
```
> [MM-44389] : fix show preview tooltip text for windows/linux

- components/channel_view/index.ts
- components/threading/virtualized_thread_viewer/create_comment.tsx
- components/user_settings/advanced/index.js
- components/user_settings/advanced/user_settings_advanced.jsx
- packages/mattermost-redux/src/selectors/entities/preferences.ts
Add a condition to hide legacy Enable post formatting setting if Advanced Text editor is enabled
Fixes https://mattermost.atlassian.net/browse/MM-41296
Epic: https://mattermost.atlassian.net/browse/MM-41347
NONE
|----|----|
| <img width="851" alt="Screenshot 2022-05-20 at 3 34 31 PM" src="https://user-images.githubusercontent.com/16203333/169505460-be9ab26e-afb4-4305-af6b-6b8b92727088.png"> | <img width="856" alt="Screenshot 2022-05-20 at 3 32 27 PM" src="https://user-images.githubusercontent.com/16203333/169505482-c4a2e08e-a818-4b5a-98bf-3074506d5293.png"> |
```release-note
* Add a condition to hide legacy Enable post formatting setting if Advanced Text editor is enabled
```
> [MM-41296] : Add a condition to hide legacy Enable post formatting setting if Advanced Text editor is enabled

- components/admin_console/feature_discovery/feature_discovery.tsx
- components/cloud_start_trial/cloud_start_trial_btn.tsx
- components/onboarding_tasklist/onboarding_tasklist_completed.tsx
This PR adds code to ensure that  the disclaimer is only shown when the trial button is available.
https://mattermost.atlassian.net/browse/MM-44460
n/a
For end users will look like this. For Admins must close the onboarding task list.
```release-note
NONE
```
> MM-44460 - hide trial disclosure after start

- components/header_footer_route/footer.scss
- components/header_footer_route/footer.tsx
- components/header_footer_route/header.scss
- components/header_footer_route/header.tsx
- e2e/cypress/tests/integration/signin_authentication/login_spec.js
- e2e/cypress/tests/integration/signin_authentication/signup_spec.js
- e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_1_spec.js
- e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_2_spec.js
Apply new designs for the Signup screen - Rename new footer and header containers' classnames to avoid affecting other components.
https://mattermost.atlassian.net/browse/MM-42490
https://github.com/mattermost/mattermost-webapp/pull/10324
```release-note
NONE
```
> MM-42490_Rename new footer and header containers' classnames

- components/root/root.jsx
- selectors/onboarding.ts
This PR makes sure of starting the initial preferences for always showing the onboarding task list opened.
https://mattermost.atlassian.net/browse/MM-44545
n/a
```release-note
NONE
```
> MM-44545 - show onboarding task list opened by default

- e2e/cypress/tests/integration/accessibility/accessibility_sidebar_dm_spec.js
- e2e/cypress/tests/integration/accessibility/accessibility_sidebar_spec.js
- e2e/cypress/tests/integration/channel_sidebar/dm_category_spec.js
- e2e/cypress/tests/integration/channel_sidebar/dm_gm_behaviour_spec.js
- e2e/cypress/tests/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js
- e2e/cypress/tests/integration/collapsed_reply_threads/channel_notifications_spec.js
- e2e/cypress/tests/integration/collapsed_reply_threads/crt_tour_spec.js
- e2e/cypress/tests/integration/collapsed_reply_threads/files_spec.js
- e2e/cypress/tests/integration/collapsed_reply_threads/following_spec.js
- e2e/cypress/tests/integration/collapsed_reply_threads/global_threads_spec.js
- e2e/cypress/tests/integration/collapsed_reply_threads/replies_spec.js
- e2e/cypress/tests/integration/collapsed_reply_threads/unread_spec.js
- e2e/cypress/tests/support/api/preference.d.ts
- e2e/cypress/tests/support/api/preference.js
- e2e/cypress/tests/support/api/setup.d.ts
- e2e/cypress/tests/support/api/setup.js
- e2e/cypress/tests/support/api/user.d.ts
- e2e/cypress/tests/support/api/user.js
- e2e/cypress/tests/support/index.js
Hide trial modal for first admin, then only enable as required by test.
```release-note
NONE
```
> Cypress/E2E: Hide trial modal for first admin

- components/global_header/right_controls/cloud_upgrade_button/cloud_upgrade_button.test.tsx
- components/global_header/right_controls/cloud_upgrade_button/index.tsx
In the cloud_upgrade_button component, only make calls to the cloud endpoints when on cloud workspaces
[MM-44566](https://mattermost.atlassian.net/browse/MM-44566)
```release-note
NONE
```
> [MM-44566] - 501 errors for non-cloud environment getting subscription info

- actions/team_actions.jsx
- actions/team_actions.test.js
- components/post_view/post_list/index.js
- components/post_view/post_list/post_list.jsx
- components/post_view/post_list/post_list.test.jsx
- packages/mattermost-redux/src/actions/teams.test.js
- packages/mattermost-redux/src/actions/teams.ts
TL;DR:
- I got rid of the call to viewChannel when unmounting PostList and switching away from a channel
- I got rid of the extra call to viewChannel when switching teams
---
The viewChannel API is called to update the lastViewedAt for a channel as well as keeping track of the channel that the user is active in. This is currently called:
1. When the PostList is mounted, the current channel changes in it, or it's unmounted. This works out to:
- (mount) When opening the app or switching to a channel
- (channel change) This doesn't actually occur since we remount the component when this happens
- (unmount) When switching away from a channel or away from Channels in general
2. When switching teams from the TeamSidebar
3. When focusing the window
4. When blurring the window
- This is called …
> MM-43889 Reduce unnecessary calls to viewChannel API

- components/root/index.js
This PR adds the code to check the EnableOnboardingFlow config option to hide/show the new onboarding tasklist
https://mattermost.atlassian.net/browse/MM-44631
n/a
https://user-images.githubusercontent.com/10082627/170373448-948ad3a6-3ad1-49e0-949d-289bb102496d.mp4
```release-note
NONE
```
> MM-44631 - use the enable onboarding config to show/hide the  onboarding

- .gitignore
- package.json
I noticed stylelint had a cache option, similar to eslint. On my machine, this speeds up a "no work to do" run from 43 seconds to 37 seconds. Not as much as I hoped, but still felt worth doing.
N/A
```release-note
NONE
```
> cache stylelint

- components/advanced_create_post/advanced_create_post.tsx
fixes: Keyboard focus not put back to post textbox after hitting ctrl+shift+p twice
Fixes https://mattermost.atlassian.net/browse/MM-44588
NONE
NONE
```release-note
Bugfix: Keyboard focus not put back to post textbox after hitting ctrl+shift+p twice
```
> [MM 44588] fixes: Keyboard focus not put back to post textbox after hitting ctrl+shift+p twice

- components/advanced_text_editor/advanced_text_editor.scss
Advanced text editor: alignment to centre when channel display is set to fixed width
Fixes https://mattermost.atlassian.net/browse/MM-44437
EPIC https://mattermost.atlassian.net/browse/MM-44437
NONE
|----|----|
| <img width="2032" alt="image-20220519-194747" src="https://user-images.githubusercontent.com/16203333/169540135-ce43b183-d9f5-4c40-95d1-781b7148627b.png"> | <img width="1462" alt="Screenshot 2022-05-20 at 7 07 49 PM" src="https://user-images.githubusercontent.com/16203333/169540192-44ddede3-279c-4a8b-a393-1301450c9815.png"> |
```release-note
Advanced text editor: alignment to centre when channel display is set to fixed width
```
> [MM-44437]: Advanced text editor: alignment to center when channel display is set to fixed width

- components/advanced_text_editor/formatting_bar/hooks.tsx
Cherry pick of #10374 on release-7.0.
```release-note
NONE
```
> Automated cherry pick of #10374

- components/widgets/menu/menu_items/menu_cloud_trial.tsx
This PR adds the logic to open the view plans modal from the See Plans link shown on the main menu. This one is shown once the trial have passed and there is no subscription.
https://mattermost.atlassian.net/browse/MM-44419
n/a
https://user-images.githubusercontent.com/10082627/171473554-b9a7d8be-c823-41cb-8527-0f0499c64d84.mp4
```release-note
NONE
```
> MM-44429 - open view plans modal

- actions/cloud.tsx
Per bug bash, we want to show 0 file storage usage instead of fake file storage until real usage is available.
https://mattermost.atlassian.net/browse/MM-44742
```release-note
NONE
```
> default to 0 storage used until real storage data is available

- components/admin_console/billing/billing_subscriptions/limits.test.tsx
- components/admin_console/billing/billing_subscriptions/limits.tsx
- components/admin_console/billing/plan_details/feature_list.tsx
- components/admin_console/billing/plan_details/plan_details.tsx
- utils/constants.tsx
- utils/limits.tsx
Previous PRs added/used cloud-starter-legacy; it overcomplicates licensing and releasing of cloud freemium, and the UI checks based on it can all be achieved by looking at whether the plan is `cloud-starter` sku and if there are any applied limits (if there are no limits, then it must by legacy/paid cloud-starter).
https://mattermost.atlassian.net/browse/MM-44440
No UI changes
```release-note
NONE
```
> Remove cloud-starter-legacy; we do not need it

- packages/mattermost-redux/src/selectors/entities/preferences.ts
While the A/B test to hide the Use Case Based Onboarding is running on Cloud the experience should be hidden by default for Self-Managed workspaces.
https://mattermost.atlassian.net/browse/MM-44650
```release-note
NONE
```
> MM-44650_Turn off Use Case Based Onboarding for Self-Managed while A/B Test runs on Cloud

- components/cloud_start_trial/request_business_email_modal.tsx
the changes on this file are related to fix a defect that happens when starting the trial after the user had to enter a valid business email, that in the initial implementation the request business modal was not being closed.
This is the original feature ticket:
https://mattermost.atlassian.net/browse/MM-43666
n/a
```release-note
NONE
```
> close request business email modal after trial success request

- components/announcement_bar/cloud_trial_ended_announcement_bar/index.tsx
This was left at May 15 for testing purposes. We'll need it in June for the release.
https://mattermost.atlassian.net/browse/MM-44701
```release-note
None
```
> [MM-44701] Adjust trial end check in banner to June 15

- plugins/export.js
Plugins shouldn't have to import a duplicate copy of the styled components library. This will help avoid this warning:
Fixes: https://mattermost.atlassian.net/browse/MM-44334
```release-note
NONE
```
> MM-44334: export styled components

- components/app_bar/app_bar.scss
- sass/layout/_sidebar-right.scss
When the RHS is open and expanded, it renders a `position: absolute` div that covers the whole screen. This div handles any click on it to collapse the RHS again. The end result is that the user can click anywhere outside of the RHS to collapse it.
When the App Bar was implemented, this was not taken into account, so such RHS background renders also on top of the App Bar icons, making it impossible to click on them when the RHS is expanded.
There are two simple solutions for this:
1. Make the App Bar icons to render on top of the background as it is today (this very PR).
2. Shift the RHS background to the left, so that it does not cover the App Bar. This can be accomplished by aligning it to the right of the RHS with the following change:
```diff
--- a/sass/layout/_sidebar-right.scss
+++ …
```
> MM-44685: Render app bar icons on top of RHS background

- components/app_bar/__snapshots__/app_bar.test.tsx.snap
- components/app_bar/app_bar.scss
- components/app_bar/app_bar.tsx
This PR adds a divider between the core products section (i.e., Playbooks and Boards) and the rest of the icons in the App Bar. It is shown only when both sections are visible.
Another one for v7.0 :nerd_face: cc/ @amyblais 
https://mattermost.atlassian.net/browse/MM-44687
--
https://user-images.githubusercontent.com/3924815/171902141-095c5af4-984c-4aa7-afb1-a1713324ebcb.mp4
```release-note
NONE
```
> MM44687: Add divider between the core products and the rest of icons

- components/app_bar/app_bar.scss
Another fix for v7.0 cc/@amyblais.
The interaction of outline and border-radius is not always as one would expect, and the version of Electron used in Desktop 5.0.x seems not to apply the 50% border-radius to the outline of the App Bar icons (Desktop 5.1.x works fine).
As a workaround, we use box-shadow, which does fix the issue in Desktop 5.0.x while keeping the same behavior elsewhere.
https://mattermost.atlassian.net/browse/MM-44686
--
```release-note
NONE
```
> MM-44686: Fix squared outline using box-shadow

- components/advanced_text_editor/advanced_text_editor.tsx
Advanced Text Editor Don't show the preview button if the input is empty
Fixes https://mattermost.atlassian.net/browse/MM-44896
NONE
```release-note
UI: Advanced Text Editor Don't show the preview button if the input is empty
```
> [MM-44896] Advanced Text Editor Don't show the preview button if the input is empty

- components/advanced_create_comment/advanced_create_comment.tsx
- components/advanced_create_comment/index.ts
- components/advanced_create_post/advanced_create_post.tsx
- components/advanced_create_post/index.ts
- components/edit_channel_header_modal/index.ts
- components/user_settings/advanced/user_settings_advanced.jsx
Hide Markdown settings from pre-release preview settings in the user settings modal ( Advanced settings)
Fixes https://mattermost.atlassian.net/browse/MM-44898
NONE
|----|----|
| ![Image Pasted at 2022-6-3 11-12](https://user-images.githubusercontent.com/16203333/172374156-8a831c92-4fa0-4d3f-a5fa-83de4d7e1a56.png) | <img width="836" alt="Screenshot 2022-06-07 at 5 28 18 PM" src="https://user-images.githubusercontent.com/16203333/172374194-6c7d554f-25a5-4d11-8766-de3da050ff13.png"> |
```release-note
UI: Advanced Text editor Hide Markdown settings from pre-release preview settings in the user settings modal ( Advanced settings)
```
> [MM-44898] Hide Markdown settings from pre release preview settings in user settings modal ( Advanced settings)

- components/advanced_create_comment/advanced_create_comment.tsx
- components/advanced_create_comment/index.ts
- components/advanced_create_post/advanced_create_post.tsx
- components/advanced_create_post/index.ts
- components/edit_channel_header_modal/index.ts
- components/user_settings/advanced/user_settings_advanced.jsx
Hide Markdown settings from pre-release preview settings in the user settings modal (Advanced settings)
original PR https://github.com/mattermost/mattermost-webapp/pull/10497
Fixes https://mattermost.atlassian.net/browse/MM-44898
NONE
NONE
```release-note
Hide Markdown settings from pre-release preview settings in the user settings modal (Advanced settings)
```
> [MM-44898] Hide Markdown settings from pre-release preview settings in the user settings modal (Advanced settings)

- utils/url.tsx
We have some links to these pages in the UI (under the old textbox), and while those normally open in a new tab, if you copy and pasted that link into a post, you could get it to open within the Desktop App. When you were there, there was no back button, so you could get stuck.
This fixes that by just making it so that they always open in a new tab.
https://mattermost.atlassian.net/browse/MM-44100
```release-note
Always open links to internal help pages in a new browser tab
```
> MM-44100 Always open internal help pages in a new tab

- components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- i18n/i18n.jsx
Romanian product translations haven't been actively maintained, and with this reduction in translation quality, this language is being downgraded to Beta.
```release-note
Downgraded Romanian language support to Beta.
```
> Downgrade Romanian translations to Beta

- components/admin_console/billing/payment_info_edit.tsx
- components/payment_form/card_input.tsx
- components/payment_form/payment_form.scss
- components/payment_form/payment_form.tsx
- components/pricing_modal/content.tsx
- components/purchase_modal/index.ts
- components/purchase_modal/purchase.scss
- components/purchase_modal/purchase_modal.tsx
- i18n/en.json
- utils/utils.tsx
This PR fixes a couple of theming issues (especially in darker modes) for the stripe card element and generally on the purchase modal
[MM-44648](https://mattermost.atlassian.net/browse/MM-44648)
onyx
----
indigo
----
```release-note
NONE
```
> [MM-44648] - Card input not visible in darker modes

- components/dot_menu/dot_menu.tsx
Show Unfollow button in dot menu of root post if the post has mentions
Fixes https://mattermost.atlassian.net/browse/MM-42629
NONE
```release-note
Bugfix: Show Unfollow button in dot menu of root post if the  post has mentions
```
> [MM-42629] Show Unfollow button in dot menu of root post if the post has mentions

- components/dot_menu/dot_menu.tsx
Cherry pick of #10494 on cloud.
```release-note
NONE
```
> Automated cherry pick of #10494

- components/main_menu/__snapshots__/main_menu.test.tsx.snap
- components/main_menu/main_menu.tsx
- i18n/en.json
Create Team tooltip to inform that their trial ending will archive any new teams.
https://mattermost.atlassian.net/browse/MM-44883
```release-note
NONE
```
> MM-44883_Update the Create Team in trial tooltip text

- components/login/__snapshots__/login.test.tsx.snap
- components/login/login.tsx
- e2e/cypress/tests/integration/signin_authentication/login_spec.js
- e2e/cypress/tests/support/common_login_commands.js
Log in button is now always enabled. Validations for filled inputs before submit are in place.
https://mattermost.atlassian.net/browse/MM-44634
https://user-images.githubusercontent.com/79058848/172435804-3d8a58b9-d3c5-4a27-8f88-85d31c79b446.mp4
```release-note
- In the login page, the Log in button is now always enabled.
```
> MM-44634_When login credentials are auto-filled, log in button shows as disabled on hover

- actions/notification_actions.jsx
- actions/notification_actions.test.js
- packages/mattermost-redux/src/utils/post_utils.ts
Currently when we send desktop notifications we ignore all system
messages.
This commit changes that so when the current user is added in a channel
they are going to receive a desktop notification about that system
message.
https://mattermost.atlassian.net/browse/MM-42581
- Has server changes (https://github.com/mattermost/mattermost-server/pull/20181)
```release-note
NONE
```
> MM-42581: desktop notification when user added to channel

- actions/cloud.tsx
- packages/client/src/client4.ts
- packages/types/src/posts.ts
- utils/limits.tsx
Fill in file storage with real data. Note that the usage is cached for 30 mintues, so you'll need to wait that long to see an update in usage numbers after adding files. And you'll need to add at least 100MB files so see it make a difference, because we round to the nearest 0.1GB in the UI.
https://mattermost.atlassian.net/browse/MM-44555
```release-note
NONE
```
> add file storage usage

- actions/notification_actions.jsx
- actions/notification_actions.test.js
- packages/mattermost-redux/src/utils/post_utils.ts
Cherry pick of #10521 on release-7.0.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #10521

- components/linking_landing_page/linking_landing_page.tsx
- components/root/root.jsx
This PR adds the functionality to preview the desktop app download screen on a first visit to a new server.
Steps: 
- log out from all servers
- clear site data so that your login isn't remembered
- navigate to server home page
https://mattermost.atlassian.net/browse/MM-36439
```release-note
NONE
```
> Show desktop app download prompt on first visit to a new server

- components/linking_landing_page/linking_landing_page.tsx
- components/root/root.jsx
Reverts mattermost/mattermost-webapp#10573 because e2e tests need to be updated .
```release-note
NONE
```
> Revert "Show desktop app download prompt on first visit to a new server"

- components/admin_console/feature_discovery/feature_discovery.tsx
- components/admin_console/feature_discovery/index.tsx
This PR adds the logic for opening the upgrade modal once the trial have completed showing a call to action to upgrade from the feature discovery pages in the system console
https://mattermost.atlassian.net/browse/MM-44849
n/a
https://user-images.githubusercontent.com/10082627/172846978-b7f6dc9e-9bee-46b6-b6eb-f4da62c94313.mp4
```release-note
NONE
```
> MM-44849 - feature discovery pages show start trial button after trial completed

- components/logged_in/logged_in.test.tsx
- components/logged_in/logged_in.tsx
If you attempt to visit a page with query parameters and you're unauthenticated, you will be redirected to the login page with a `redirect_to` value, however the query parameters for the initial page will not be preserved. This passes along the query parameters to the redirect_to value 
https://mattermost.atlassian.net/browse/MM-45051
```release-note
None
```
> Fix redirect_to dropping query parameters

- components/app_bar/app_bar.tsx
The product switcher contains: Channels, Boards, Playbooks.
The App Bar, however, had Playbooks before Boards. This PR fixes that.
https://mattermost.atlassian.net/browse/MM-45067
--
|----|----|
| ![image](https://user-images.githubusercontent.com/3924815/173566348-1a324915-34ab-45a9-b0b9-b975c42b1b5f.png)| ![image](https://user-images.githubusercontent.com/3924815/173566525-6d9fbdf0-e30a-4fad-b6e1-77580451e6f2.png) |
```release-note
NONE
```
> MM-45067: Reorder core products in the App Bar

- packages/mattermost-redux/src/selectors/entities/preferences.ts
- packages/types/src/config.ts
Adds license and guest check to the Insights front-end feature fence.
https://mattermost.atlassian.net/browse/MM-44642
```release-note
NONE
```
* https://github.com/mattermost/mattermost-server/pull/20490
> MM-44642: Hide insights if not Professional or Enterprise SKU or if guest

- actions/websocket_actions.jsx
- package-lock.json
- package.json
This adds new debug logging for the `DynamicSizedList` component and new post events triggered by setting `logDSLEvents` and `logPostEvents` respectively to true. It's opt-in since it's fairly noisy (especially DynamicSizedList), and we'll hopefully remove it once we figure out what this long-running bug with the keep-at-bottom logic is caused by.
I linked the changes to the dynamic-virtualized-list library below
https://mattermost.atlassian.net/browse/MM-44131
https://github.com/mattermost/dynamic-virtualized-list/pull/26
```release-note
NONE
```
> MM-44131 Add debug logging for DynamicSizedList and for post-related websocket events

- components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.tsx
- components/post_view/post_attachment_opengraph/post_attachment_opengraph.tsx
Handle image metadata being undefined in posts with opengraph attachments. This was causing some channels or threads to crash the app.
Context in these threads:
* https://community.mattermost.com/core/pl/b45bs7x35j868g1n4e36qj38fo
* https://community.mattermost.com/core/pl/zqdbxqnjxtrmtkukqxy33hfgjc
```release-note
NONE
```
> Handle image metadata being undefined in posts with opengraph attachments

- stores/redux_store.jsx
Having access to the store when debugging is incredibly helpful, and since we seem to have a lot of issues that we can only reproduce on community, it seems like it makes sense to expose there.
I could see an argument for doing it whenever developer mode is turned on, but that requires watching the current value in the client config which is more complicated, and I don't think we need to add that unless we find a specific need for it.
This is part of https://github.com/mattermost/mattermost-webapp/pull/10617
```release-note
NONE
```
> Make window.store always available on community

- components/pricing_modal/content.tsx
- components/pricing_modal/downgrade_team_removal_modal/downgrade_team_removal_modal.scss
- components/pricing_modal/downgrade_team_removal_modal/downgrade_team_removal_modal.test.tsx
- components/pricing_modal/downgrade_team_removal_modal/index.tsx
`modal-backdrop` wasn't specific enough, so this z-index was leaking into other places of the webapp. This makes it so that the rule only applies to the downgrade modal. 
I also snuck in a fix for the starter button not being disabled.
```release-note
None
```
> Fix z index downgrade modal

- components/pricing_modal/content.tsx
This should be disabled when on starter, and enabled otherwise. Got my conditions crossed.
```release-note
None
```
> Remove negation on condition for disabling downgrade button

- components/channel_layout/center_channel/index.ts
- e2e/cypress/tests/integration/collapsed_reply_threads/last_viewed_spec.js
- selectors/local_storage.ts
Cherry pick of #10477 on cloud.
/cc  @kyeongsoosoo
```release-note
NONE
```
> Automated cherry pick of #10477

- components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
- components/global_header/left_controls/product_menu/product_menu_list/index.ts
- components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.test.tsx
- components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
Regression: Only starter free should show User Groups as restricted.
https://mattermost.atlassian.net/browse/MM-45298
```release-note
NONE
```
> MM-45298_User Groups not available in Cloud Enterprise

- components/async_load.tsx
- components/deferComponentRender.tsx
- components/file_search_results/file_search_result_item.tsx
- components/invitation_modal/index.tsx
- components/post_view/message_attachments/message_attachment/message_attachment.tsx
- components/single_image_view/single_image_view.tsx
- components/threading/thread_viewer/__snapshots__/thread_viewer.test.tsx.snap
- components/threading/thread_viewer/thread_viewer.tsx
- components/threading/virtualized_thread_viewer/index.ts
Something with the newer version of TS I tried using required me to migrate these to TS. The rest of the changes are to satisfy the type checker now that it properly knows the props of deferred and async components.
This is part of https://github.com/mattermost/mattermost-webapp/pull/10617
```release-note
NONE
```
> Migrate makeAsyncComponent and deferComponentRender to TS

- package-lock.json
- package.json
- packages/client/package.json
- packages/types/package.json
I'll probably automate this eventually, but the release process for the subpackages is pretty simple since they're locked to the version of the web app. There's a more detailed version in `packages/README.md` in this repo, but for now, I'm just updating these version numbers, and then once this is merged, I'll tag the commit for future reference.
Also, for my own future reference, the published packages are available here:
- https://www.npmjs.com/package/@mattermost/client
- https://www.npmjs.com/package/@mattermost/types
https://mattermost.atlassian.net/browse/MM-44326
```release-note
NONE
```
> Update subpackage versions to 7.0.0

- components/post_view/post_list/post_list.jsx
This PR fixes broken logic of loading more posts. Counter variable is not initialized, therefore it is `undefined`, therefore when adding `+1` to it, it becomes `NaN`, therefore guard `if (this.extraPagesLoaded > MAX_EXTRA_PAGES_LOADED) {` never works.
Probably this only affects channels with lots of System Message (which can be hidden by user but loaded anyway). 
If user opens such channel with system messages hidden then _all_ messages in the channel are being loaded. Which results in heavy load on API.
Also, I added a counter reset after a user clicks on `Load more` button for better UX.
```release-note
NONE
```
> fix: initialize load more posts counter

- components/activity_and_insights/insights/time_frame_dropdown/__snapshots__/time_frame_dropdown.test.tsx.snap
- components/activity_and_insights/insights/time_frame_dropdown/time_frame_dropdown.tsx
Remove typing from insights time dropdown
https://mattermost.atlassian.net/browse/MM-45277
```release-note
NONE
```
> [MM-45269] Remove typing from insights time dropdown

- package-lock.json
- package.json
Bump `@mattermost/compass-icons` version to v0.1.24. Needed by Playbooks for https://mattermost.atlassian.net/browse/MM-45475 (I may fix that using the SVG icons from the version we explicitly added to our dependencies, but in any case it does not hurt updating the compass-icons version here :) )
--
--
--
```release-note
NONE
```
> Bump @mattermost/compass-icons version to v0.1.24

- components/channel_info_rhs/channel_info_rhs.test.tsx
- components/channel_info_rhs/channel_info_rhs.tsx
Users should not be allowed to edit archived channel header/purpose.
For QA, visit the admin console and ensure `SITE CONFIGURATION > Users and Teams | Allow users to view archived channels` is set to true or you won't be able to visit an archived channel
https://mattermost.atlassian.net/browse/MM-45227
N/A
N/A
```release-note
NONE
```
> [MM-45227] Disable edition of archived channel purpose and header in RHS

- components/announcement_bar/cloud_trial_ended_announcement_bar/cloud_trial_ended_announcement_bar.test.tsx
- components/announcement_bar/cloud_trial_ended_announcement_bar/index.tsx
This banner, while dismissable, didn't have an explicit point at which it would go away. This resulted in people being downgraded to freemium, upgrading to professional, and still seeing the banner. 
This PR makes it so that the banner is only displayed to Starter instances
https://mattermost.atlassian.net/browse/MM-45335
```release-note
None
```
> don't show trial ended banner to non-starter worksapces

- components/advanced_create_comment/advanced_create_comment.tsx
- components/advanced_create_post/advanced_create_post.tsx
- components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
- i18n/en.json
Advanced text editor preview resetting issue on the message sent in preview mode and tooltip issue on windows
Fixes https://mattermost.atlassian.net/browse/MM-45397
NONE
```release-note
* Advanced text editor preview resetting issue on the message sent in preview mode and tooltip issue on windows
```
> [MM-45397]:Advanced text editor preview resetting issue on message sent in preview mode

- components/header_footer_route/content_layouts/alternate_link.scss
- components/header_footer_route/content_layouts/alternate_link.test.tsx
- components/header_footer_route/content_layouts/alternate_link.tsx
- components/header_footer_route/footer.scss
- components/header_footer_route/header.scss
- components/header_footer_route/header.tsx
- components/login/login.scss
- components/login/login.test.tsx
- components/login/login.tsx
- components/signup/__snapshots__/signup.test.tsx.snap
- components/signup/signup.scss
- components/signup/signup.test.tsx
- components/signup/signup.tsx
- e2e/cypress/tests/integration/signin_authentication/signup_spec.js
Move Login/Signup alternate links closer to the main content of the page.
https://mattermost.atlassian.net/browse/MM-44979
https://www.figma.com/file/PZuUUM5KPZtGS4YiJYvgSg/MM-44979-Move-Create-Account-Button?node-id=0%3A1
```release-note
NONE
```
> MM-44979_Move Create Account link closer to login container

- components/advanced_create_comment/advanced_create_comment.tsx
- components/advanced_create_post/advanced_create_post.tsx
- components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
- i18n/en.json
Cherry pick of #10685 on cloud.
```release-note
NONE
```
> Automated cherry pick of #10685

- components/activity_and_insights/insights/top_threads/top_threads.scss
The heading will no longer get cut off for insights
https://mattermost.atlassian.net/browse/MM-45261
```release-note
NONE
```
> [MM-45239] Fixing font size of markdown headings

- components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
- components/edit_channel_header_modal/edit_channel_header_modal.tsx
- i18n/en.json
In the context of editing a channel header, this PR removes the 2nd instance of the word "channel" from the text line "Edit the text appearing next to the channel name in the channel header" both to reduce redundancy, and to ensure the text applies equally to direct messages, group messages, and channels. In its original form, it only applied to channels.
(The first instance of "channels" works well as-is since direct messages and group messages are all types of channels.)
```release-note
Updated the Edit Header modal text description to be applicable to channels, direct messages, and group messages.
```
> Removed "channel" from "channel header"

- actions/cloud.tsx
- components/cloud_start_trial/cloud_start_trial_btn.tsx
- packages/client/src/client4.ts
This PR splits the logic to validate business email by creating a new endpoint where only the installation/user admin emails are validated and keep the other endpoint to validate an email that is sent as a parameter to be validated as a valid business email.
https://mattermost.atlassian.net/browse/MM-45174
https://github.com/mattermost/mattermost-server/pull/20581
n/a
```release-note
NONE
```
> MM-45174 - split validate business email logic

- components/announcement_bar/default_announcement_bar/announcement_bar.tsx
* LCH = life cycle hook
This PR makes sure to validate if the component updates and there is at least one bar to add the css class to the body element so the content is pushed down and no controls are hidden by the banner.
The main problem was that there is a sort of race conditions between the componentWillUnmount and ComponentDidMount, so if the webhook updates the redux information informing that the trial ended, the componentDidMount LCH is called first with the new trial-ended information and just after that, the componentWillUnmount (with the previous trial started banner information) is called removing the `announcement-bar--fixed` css class from body hence placing all the content at the top and getting main menu covered by banner.
The proposed solution on this PR is the less …
> MM-45146 - trial end banner hides product switcher

- components/post_view/post_attachment_opengraph/post_attachment_opengraph.scss
figure tag in opengraph attachment was missing max-width/-height properties
[MM-45505](https://mattermost.atlassian.net/browse/MM-45505)
n/a
|----|----|
|![Screenshot 2022-07-05 at 08 46 04](https://user-images.githubusercontent.com/32863416/177267002-a4dcb2ad-6f51-45ba-8e73-b3951b7c1aea.png)|![Screenshot 2022-07-05 at 08 46 51](https://user-images.githubusercontent.com/32863416/177267025-56fddafc-9005-4915-ad36-32b62029bb8e.png)|
```release-note
NONE
```
> [MM45505]: fixed overflowing image in link preview

- components/rhs_header_post/rhs_header_post.tsx
- components/rhs_thread/rhs_thread.tsx
- components/sidebar_right/index.ts
- components/sidebar_right/sidebar_right.tsx
This PR migrates 'components/sidebar_right' module and associated tests to TypeScript
Fixes https://github.com/mattermost/mattermost-server/issues/16719
JIRA: https://mattermost.atlassian.net/browse/MM-20387
```release-note
NONE
```
> MM-20387: Migrate 'components/sidebar_right' module and associated tests to TypeScript

- components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
- components/channel_header_dropdown/channel_header_dropdown_items.js
- components/channel_header_dropdown/menu_items/leave_channel/__snapshots__/leave_channel.test.tsx.snap
- components/channel_header_dropdown/menu_items/leave_channel/leave_channel.tsx
This PR applies the destructive action color to `Archive Channel` and `Leave Channel` menu actions. 
Issue: [Web app - Leave channel & archive channel actions should display as destructive](https://github.com/mattermost/mattermost-server/issues/19791)
Jira Link: [MM-36402](https://mattermost.atlassian.net/browse/MM-36402)
|----|----|
|<img width="1786" alt="168078853-2afdd4d7-c178-421f-95f6-e3495be489eb" src="https://user-images.githubusercontent.com/36856709/178643764-3a54d345-7006-44a9-8cc3-119512162ac3.png">|<img width="1512" alt="Screen Shot 2022-07-12 at 10 11 08 PM" src="https://user-images.githubusercontent.com/36856709/178643576-5e9ee113-5398-4e71-b442-1c6429d61d3a.png">
```release-note
Added the destructive action color to `Archive Channel` and `Leave …
```
> Mm 36402: Display leave,archive channel action as destructure

- e2e/cypress/tests/integration/mark_as_unread/mark_gm_as_unread_spec.js
- e2e/cypress/tests/integration/messaging/center_channel_rhs_overlap_spec.js
- e2e/cypress/tests/integration/messaging/private_channel_open_spec.js
- e2e/cypress/tests/integration/multi_team_and_dm/close_current_dm_redirects_spec.js
Misc maintenance fixes:
- Fixed `MM-T2140 Edited message displays edits and "Edited" in center and RHS`
- Fixed `MM-T1225 CTRL/CMD+K - Open private channel using arrow keys and Enter`
- Fixed `MM-T249 Mark GM post as unread`
- Fixed `MM-T453_2 Closing a different direct message should not affect active direct message`
N/A
```release-note
NONE
```
> Cypress/E2E: Fix mark as read, messaging, multi team and dm tests

- components/integrations/bots/add_bot/add_bot.test.tsx
- components/integrations/bots/add_bot/add_bot.tsx
- components/integrations/bots/add_bot/index.js
- components/integrations/bots/add_bot/index.ts
This PR migrates 'components/integrations/bots/add_bot' module and associated tests to TypeScript
Fixes https://github.com/mattermost/mattermost-server/issues/16129
JIRA: https://mattermost.atlassian.net/browse/MM-20445
```release-note
NONE
```
> MM-20445: Migrate 'components/integrations/bots/add_bot' module and associated tests to TypeScript

- e2e/cypress/tests/integration/messaging/long_post_attachments_spec.js
- e2e/cypress/tests/integration/messaging/mention_autocomplete_overlap_spec.js
Misc maintenance fixes:
- Fixed `MM-T105 Long post with multiple attachments`
- Add `KNOWN ISSUE: MM-45597` to failing autocomplete test
N/A
```release-note
NONE
```
> Cypress/E2E: Fix long post attachments spec

- components/admin_console/admin_definition.jsx
- components/login/login.scss
- components/login/login.tsx
- components/signup/signup.scss
- i18n/en.json
- utils/admin_console_index.test.tsx
Some updates to the Customization options for Login/Signup pages.
- Custom Brand Text:
- Shows centered
- Site Description:
- Help text updated to: "Displays as a title above the login form. When not specified, the phrase "Log in" is displayed."
- Placeholder removed.
https://mattermost.atlassian.net/browse/MM-44637
```release-note
- Custom Brand Text now shows centered.
- Site Description configuration does not show placeholder and help text now reads "Displays as a title above the login form. When not specified, the phrase "Log in" is displayed."
```
> MM-44637_Site description removes "Log in" text from login screen

- components/common/hooks/useOpenPricingModal.ts
- components/global_header/right_controls/plan_upgrade_button/index.tsx
- components/widgets/menu/menu_items/useWords.test.tsx
- i18n/en.json
- packages/types/src/config.ts
Cherry pick of #10798 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #10798

- components/search/search.tsx
- components/search_hint/__snapshots__/search_hint.test.tsx.snap
- components/search_hint/search_hint.tsx
- e2e/cypress/tests/integration/search/search_bar_popup_focus_spec.js
This PR modifies the search box to not hide the dropdown (with messages/files buttons) when the focus is set from the search box to one element inside the dropdown
Fixes https://github.com/mattermost/mattermost-server/issues/17734
Jira: https://mattermost.atlassian.net/browse/MM-34969
This pull request has no related prs
```release-note
NONE
```
> [MM-34969] search dropdown options should allow focusing with tab

- components/admin_console/workspace-optimization/dashboard.data.tsx
- packages/client/src/index.ts
- packages/client/tsconfig.json
- packages/components/tsconfig.json
- packages/types/tsconfig.json
- tsconfig.json
Added `"isolatedModules": true` to the main tsconfig.json and the package folders as well.
Fixed the few warnings that appeared.
We couldn't update mattermost-webapp ref at playbooks codebase because our tsconfig had it already enabled. Apparently we should have it enabled since we compile through babel (tsc is used more for type-checks).
[Doc reference](https://www.typescriptlang.org/tsconfig#isolatedModules)
[More context at community](https://community.mattermost.com/core/pl/abnr7d4a378gtq3obqfutc5k4y)
https://mattermost.atlassian.net/browse/MM-46040
Not yet
No UI changes
```release-note
NONE
```
> MM-46040 enable forced isolatedModules in tsconfig(s)

- components/team_sidebar/team_sidebar.tsx
Removes the pluggable in the team sidebar when switching to products (boards and playbooks)
This will prevent issues like the GitHub plugin appearing on the LHS for playbooks (and eventually boards) and being inoperative. 
https://mattermost.atlassian.net/browse/MM-45859
```release-note
NONE
```
> MM-45859 Disable team sidebar pluggable for products.

- actions/cloud.tsx
- packages/client/src/client4.ts
- packages/types/src/cloud.ts
This PR changes the response from being a plain 500 to be a json object containing the key is_valid which its values could be either true or false. This in order to prevent raising alarms and increasing the SLOs to SRE team for server errors.
https://mattermost.atlassian.net/browse/MM-45713
https://github.com/mattermost/mattermost-server/pull/20682
n/a
```release-note
NONE
```
> MM-45713 - change 500 error to json object during validate business email request

- components/team_sidebar/components/team_button.test.tsx
- components/team_sidebar/components/team_button.tsx
Avoid spuriously marking Playbooks (and the whole desktop app) as unread:
While we were correctly suppressing the mention and unread badge on the team button, we were still setting the class used by desktop to "detect" unreads.
Fixes: https://mattermost.atlassian.net/browse/MM-46041
```release-note
NONE
```
> MM-46041: only set team unread class in channels

- sass/components/_post.scss
Channels autocomplete was being hidden behind the RHS. Removing the restrictive z-index on the parent, which wasn't necessary as the parent isn't positioned absolutely, allows the Autocomplete popover to rely on its own z-indexing and is now a top level component
https://mattermost.atlassian.net/browse/MM-39394
```release-note
NONE
```
> [MM-39394] - Fix Autocomplete z-indexing issues when RHS is open

- components/channel_layout/center_channel/center_channel.test.tsx
- components/channel_layout/center_channel/center_channel.tsx
- components/channel_layout/center_channel/index.ts
Doesnt renders the mobile's channel header in non mobile mode
https://mattermost.atlassian.net/browse/MM-42718
N/A
```release-note
NONE
```
> MM-42718 : Do not render ChannelHeaderMobile when not in mobile view

- components/dot_menu/index.ts
- components/rhs_header_post/index.ts
- components/threading/channel_threads/thread_footer/thread_footer.tsx
- packages/mattermost-redux/src/selectors/entities/threads.ts
Created a factory selector for `getThreadOrSynthetic` which is then memoized for postId in footer component.
https://mattermost.atlassian.net/browse/MM-41861
N/A
```release-note
NONE
```
> MM-41861 : Avoid rendering of ThreadFooter component in Center when typing in center post

- .eslintrc.json
- packages/client/src/index.ts
- packages/components/tsconfig.json
- packages/mattermost-redux/src/selectors/entities/search.ts
- utils/route.test.tsx
Two small cleanup things:
1. Changes tabs to spaces in the one tsconfig for consistency (which I'm surprised none of the tooling complained about)
2. Swapping the built-in no-duplicate-imports ESLint rule which isn't aware of TS-specific `import type` and `export type` statements to the no-duplicates rule from eslint-plugin-import which handles those as well as having better support for when a file is imported via two different paths
https://mattermost.atlassian.net/browse/MM-46040
https://github.com/mattermost/mattermost-webapp/pull/10848
```release-note
NONE
```
> MM-46060 Followup to enabling isolatedModules

- components/threading/global_threads/thread_list/thread_list.tsx
fixes a very rare bug where opening the thread view results in an error
[MM-45798](https://mattermost.atlassian.net/browse/MM-45798)
n/a
n/a
```release-note
NONE
```
> [MM-45798]: fixed null error

- components/file_upload/file_upload.jsx
- components/file_upload/file_upload.test.jsx
previously we constructed a `name` property everytime we uploaded a file (or raw image data) via pasting (`CTRL`/`CMD` + `V`). With this we now use the filename if it exists and only construct the name string `Image pasted at xxx` when there is no filename property in the event object.
n/a
n/a
n/a
```release-note
NONE
```
> bugfix: use filename, if present, when pasting files

- sass/components/_post.scss
removed a white-space property that introduced a strange bug with permalink previews
n/a
n/a
|----|----|
|![Screenshot 2022-07-29 at 07 26 38](https://user-images.githubusercontent.com/32863416/181688799-465611c6-7868-4d2c-b62e-e31159e218f8.png)|![Screenshot 2022-07-29 at 07 26 57](https://user-images.githubusercontent.com/32863416/181688822-eedb8980-28c2-4df4-a092-cc0d1a35cec8.png)|
```release-note
NONE
```
> bugfix: removed white-space: nowrap

- components/team_sidebar/team_sidebar.tsx
Cherry pick of #10842 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #10842

- .circleci/config.yml
- .gitlab-ci.yml
This updates the build-images used for CI to:
- node: 16.2.0 -> 16.10.0
- npm: 7.13.0 -> 7.24.0
Internal consumed images: 
```
> docker run --platform linux/amd64 -it ${CI_REGISTRY}/mattermost/ci/devops-images/mattermost-build-webapp:20220802_node-16.10.0@sha256:3272aa759f10c2ef1719ed08cc82ddb07224bec5be86f09800c72f5e2a623c3d node -v
v16.10.0
> docker run --platform linux/amd64 -it ${$CI_REGISTRY}/mattermost/ci/devops-images/mattermost-build-webapp:20220802_node-16.10.0@sha256:3272aa759f10c2ef1719ed08cc82ddb07224bec5be86f09800c72f5e2a623c3d npm -v
7.24.0
```
Public consumed images: 
```
> docker run --platform linux/amd64 mattermost/mattermost-build-webapp:20220802_node-16.10.0@sha256:3272aa759f10c2ef1719ed08cc82ddb07224bec5be86f09800c72f5e2a623c3d  node -v
v16.10.0
> docker run …
```
> [chore] Update Node to 16.10.0

- components/team_sidebar/components/team_button.test.tsx
- components/team_sidebar/components/team_button.tsx
Cherry pick of #10849 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #10849

- components/user_groups_modal/__snapshots__/user_groups_modal.test.tsx.snap
- components/user_groups_modal/user_groups_modal.scss
- components/user_groups_modal/user_groups_modal.tsx
- components/view_user_group_modal/__snapshots__/view_user_group_modal.test.tsx.snap
- components/view_user_group_modal/view_user_group_modal.tsx
Input header was being cut off by the modal header, I also updated the search icon to use compass icons
https://mattermost.atlassian.net/browse/MM-44224
**Before:**
**After:**
```release-note
NONE
```
> [MM-44224] Fixing input header and search icon

- components/user_settings/advanced/user_settings_advanced.tsx
Show disable post formatting option in user settings modal (advanced)
Fixes https://mattermost.atlassian.net/browse/MM-45722
NONE
|----|----|
| <img width="812" alt="Screenshot 2022-08-03 at 2 12 29 PM" src="https://user-images.githubusercontent.com/16203333/182564815-33cec68e-08b5-4b81-9738-2953aca1d07f.png"> | <img width="813" alt="Screenshot 2022-08-03 at 2 11 41 PM" src="https://user-images.githubusercontent.com/16203333/182564627-37dc93d2-6593-4c60-96d3-bb26d5601463.png"> |
```release-note
* Show disable post formatting option in user settings modal (advanced)
```
> Show disable post formatting option in user settings modal (advanced)

- components/login/login.scss
Since the redesign of the login page with Mattermost 7.0, the custom branding image has been stretched with the latest version of Safari on both macOS 12.4 and 12.5. The attached screenshots illustrate the issue for our test cloud instance [1] on Safari 15.6 and macOS 12.5 and has been cross-validated on >10 different Apple Mac devices.
Upon further investigation, the issue seems to be especially easy to notice for images used that are much wider than high, e.g. the horizontal Mattermost logo from the official press kit (as png).
The display issue itself can be fixed in a variety of ways. This PR removes a property `flex: 1` that other browsers (like e.g. Firefox) already ignore (grayed out within the investigator) - and that seems to only cause issues in Safari on macOS. Our change has …
> Fix stretch for custom branding image in Safari

- components/suggestion/at_mention_provider/__snapshots__/at_mention_suggestion.test.tsx.snap
- components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
- components/widgets/users/avatar/__snapshots__/avatar.test.tsx.snap
- components/widgets/users/avatar/avatar.tsx
- components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
If user's profile picture fails to load, replace src with default profile src(I used the regex).
`Client4.getUsersRoute() + '/' + userId + '/image?_=' + lastPictureUpdate` 
-> 
`Client4.getUsersRoute() + '/' + userId + '/image/default'` 
https://github.com/mattermost/mattermost-server/issues/19815
```release-note
add fallback src to an avatar
```
> [MM-42526] When a profile picture fails to load,  fall back to the user's default picture

- components/root/root.jsx
Fix Denim theme issue
Undefined error in `onConfigLoaded` in `root.jsx` was causing to exit early and due to which theme wasn’t getting set.
Fixes https://mattermost.atlassian.net/browse/MM-46249
NONE
|----|----|
| <img width="1792" alt="Screenshot 2022-08-08 at 8 02 39 PM" src="https://user-images.githubusercontent.com/16203333/183442837-bee4f641-2676-4640-bc1b-23c286544f62.png"> | <img width="1792" alt="Screenshot 2022-08-08 at 7 48 22 PM" src="https://user-images.githubusercontent.com/16203333/183442883-f263aaec-d088-463e-ae13-b4c16783c8a0.png"> |
```release-note
* fix the theming issue due to early exit of code(undefined error).
```
> Fix Denim theme issue

- components/signup/__snapshots__/signup.test.tsx.snap
- components/signup/signup.tsx
Since at least 6.x, the sign up page (where invitation links take new users) does not include an OIDC button despite other openid providers like Google or Gitlab are present. In practice, this will lead to an error page stating "This server doesn’t have any sign-in methods enabled" in case only OIDC is active on a MM server. Since the invitation link generated within the UI leads new users to the sign up page, they will be very confused and contact the administrator (like stated on that page). On the other hand, the login page always displays OIDC correctly as an authentication method.
To restore expected behavior, code is added as part of this PR to make the necessary button available within the `signup.tsx` (based upon similar behavior in `login.tsx`). Test were adapted and all test …
> Add OIDC to the sign up page

- components/advanced_text_editor/advanced_text_editor.tsx
Adds missing `rootId` prop to `Textbox` component. Without that prop the `priorityProfiles` prop downstream is always empty:
https://github.com/mattermost/mattermost-webapp/blob/3b0e6a07308ef9e0f6d0a7fd9fef2636f706bd05/components/textbox/index.ts#L57
... and then the `AtMentionProvider` isn't able to include those users in the "priority" results:
https://github.com/mattermost/mattermost-webapp/blob/412b09d3547cdee05dbb84bc5d2345ccea824e87/components/suggestion/at_mention_provider/at_mention_provider.jsx#L217-L257
https://mattermost.atlassian.net/browse/MM-45042
```release-note
NONE
```
> MM-45042: Add missing prop.

- packages/mattermost-redux/src/utils/gfycat_sdk.ts
- types/external/gfycat-sdk.d.ts
https://mattermost.atlassian.net/browse/MM-46242
N/A
N/A
```release-note
NONE
```
> MM-46242 : Move "gfycat-sdk" type defination to webapp

- .eslintrc.json
- actions/views/rhs.ts
- actions/websocket_actions.jsx
- components/admin_console/admin_definition.jsx
- components/admin_console/license_settings/license_settings.tsx
- components/common/svg_images_components/laptop_alert_svg.tsx
- components/common/svg_images_components/man_with_laptop_svg.tsx
- components/common/svg_images_components/man_with_mailbox_svg.tsx
- components/create_post/create_post.tsx
- components/integrations/bots/add_bot/add_bot.tsx
- components/login/login.tsx
- components/main_menu/main_menu.tsx
- components/post_view/post_list_virtualized/post_list_virtualized.tsx
- components/purchase_modal/purchase_modal.tsx
- components/root/root.jsx
- components/signup/signup.tsx
- components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
- components/suggestion/switch_channel_provider.jsx
- components/threading/thread_viewer/thread_viewer.tsx
- components/user_settings/advanced/user_settings_advanced.tsx
- components/user_settings/notifications/user_settings_notifications.tsx
- package-lock.json
- packages/mattermost-redux/src/selectors/entities/posts.ts
- packages/mattermost-redux/src/selectors/entities/users.ts
- plugins/registry.js
- utils/post_utils.test.jsx
Added the rule for increasing the default file lines limit to 800. Removed the disable eslint rule for file lines in few files after the new rule. Conversation here https://community.mattermost.com/core/pl/7fbbyid14fr9xdgbwirakjc4cy
https://mattermost.atlassian.net/browse/MM-46293
N/A
N/A
```release-note
NONE
```
> MM-46293 : Increase eslint file lines limit warning to 800

- packages/mattermost-redux/src/utils/file_utils.test.js
- packages/mattermost-redux/src/utils/file_utils.ts
Remove `mime-db` usage webapp. This function was not used internally; the only mattermost related code I could find using it, was 100% duplicated code in mattermost-mobile that doesn't reference *this* code; its a full on copy of the code here. Because we don't currently export the mattermost-redux package, and the exported version is older and not tied to *this* code, it shouldn't affect any plugins, either. In the unlikely event some plugin uses the function in the old mattermost-redux package, and we do start exporting our newer version of mattermost redux as an npm package, and they need an upgrade path, we could either make a single purpose library, or point them to the code and tell them how to make their own. This saves 19.61KB, gzipped, from a bundle that we always load.
None/OSF …
> remove mime-db import and unused code

- components/onboarding_tasks/onboarding_tasks_manager.tsx
- components/preparing_workspace/preparing_workspace.tsx
- utils/constants.tsx
The preparing_workspace module defined its own const which was being imported, breaking its laziness. Fixed by defining the const in `utils/constants.tsx` and importing from there. Saves everyone not loading that page 216KB, gzipped (which is everyone except admins on their very first app load).
OSF effort, no ticket
before (notice it in one of the main bundles, in the top left):
after (notice it is now in its own bundle, on the right):
```release-note
NONE
```
> separate out preparing_workspace

- components/announcement_bar/version_bar/__snapshots__/version_bar.test.tsx.snap
- components/announcement_bar/version_bar/index.ts
- components/announcement_bar/version_bar/version_bar.test.tsx
- components/announcement_bar/version_bar/version_bar.tsx
- utils/server_version.test.tsx
- utils/server_version.tsx
This pull requests switches displaying the "new version available" announcement when the config's `BuildHash` changes instead of the server version.
This change is needed for community the current check of server version takes into account MAJOR.MINOR.PATCH.BUILDNUMBER parts of the server version, and BUILDNUMBER for community is always master, so the announcement bar is not displayed as it should.
https://mattermost.atlassian.net/browse/MM-45934
```
NONE
```
> Show new version bar when build hash changes

- CODEOWNERS
We've talked about adding this for a while, and using it to make sure Web Platform knows what's up with dependency changes seems like a good use for it.
```release-note
NONE
```
> Finally create CODEOWNERS

- components/file_preview_modal/index.ts
- package-lock.json
Modals mounted by the ModalController (ie by using `openModal`) have an `onExited` prop added automatically that removes them from the DOM. Since we overrode this one's in the `mapStateToProps`, it caused the modal to be hidden but not actually unmounted. Since the first FilePreviewModal that wasn't unmounted (it was just invisible), a new one couldn't be added when you try to view another file.
Also, I don't know why that line in package-lock.json keeps changing, but I'm going to keep changing it back because NPM keeps changing it back.
https://mattermost.atlassian.net/browse/MM-46432
https://github.com/mattermost/mattermost-webapp/pull/10904
```release-note
NONE
```
> MM-46432 Fix file attachment modal not closing properly

- packages/client/src/websocket.ts
On large installations, sometimes a proxy server can restart
or a network blip can happen which can disconnect a large
number of websocket connections. When this happens,
all of those clients will simultaneously try to reconnect,
putting the server under immense pressure.
This is fondly termed as thundering herd. And the solution
is to add a random time interval to spread out the reconnects.
We observed this happening on community, where a large number
of websocket reconnects causes the webapp to freeze due to
spikes in CPU and goroutines on the server side.
> Prevent thundering herd on websocket reconnect

- e2e/cypress/tests/integration/settings/display/message_display_mode_colorize_username_spec.js
This PR includes E2Es for colorized usernames in compact view based on [suggested steps](https://automation-test-cases.vercel.app/test/MM-T4984)
Fixes https://github.com/mattermost/mattermost-server/issues/20813
JIRA: https://mattermost.atlassian.net/browse/MM-46343
```release-note
NONE
```
> MM-46343: Include E2Es for colorized usernames in compact view

- components/pricing_modal/content.tsx
- e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js
Cherry pick of #10964 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #10964

- actions/command.ts
- e2e/cypress/tests/integration/integrations/builtin_commands/common_commands_1_spec.js
This PR introduces the new /marketplace command and changes the tests of the /help command which has a new behavior
https://mattermost.atlassian.net/browse/MM-46468
- [Has server changes](https://github.com/mattermost/mattermost-server/pull/20850)
QA done in the server PR
<details>
<summary>New <code>/help</code> command</summary>
</details>
```release-note
NONE
```
> [MM-46468] Change /help and add /marketplace

- components/signup/signup.scss
This PR applies the fix known from https://github.com/mattermost/mattermost-webapp/pull/10862 (login page) now also for the sign up page.
https://mattermost.atlassian.net/browse/MM-46522
|----|----|
| <img width="1428" alt="before" src="https://user-images.githubusercontent.com/15683974/182043213-588dc1e7-fbd3-4aa6-a6dd-bdf0a1e0d546.png"> | <img width="1428" alt="after" src="https://user-images.githubusercontent.com/15683974/182043211-8d65c170-f3a0-4f00-9ea7-020c0af449f7.png"> |
```release-note
NONE
```
> Fix stretch for custom branding image in Safari on sign up page

- components/root/index.js
- components/root/root.jsx
The desktop app prompt was breaking the cloud workspace flow for new users. This PR disables it.
https://mattermost.atlassian.net/browse/MM-46490
```release-note
NONE
```
> Disable desktop promp in cloud context

- package-lock.json
- package.json
- webpack.config.js
This adds `webpack-bundle-analyzer` to webpack after build. Plugin only creates static `bundlestats.json` in build folder without the interactive bundle chart web site. 
https://mattermost.atlassian.net/browse/MM-46499
This needs to be merged before https://github.com/mattermost/mattermost-webapp/pull/10969
n/a
```release-note
NONE
```
> MM-46499 : Add webpack-bundle-analyzer for bundle size

- components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
- components/admin_console/permission_schemes_settings/permissions_scheme_summary/index.tsx
- components/global_header/hooks.tsx
- components/logged_in/logged_in.tsx
- components/password_reset_send_link/password_reset_send_link.test.tsx
- components/permalink_view/permalink_view.test.tsx
- components/permalink_view/permalink_view.tsx
We shouldn't need to access react-router directly since everything is re-exported by react-router-dom. I found this while working on module federation because I managed somehow to have different versions of react-router and react-router-dom loaded at once so everything broke.
CC @mgdelacroix on this too. I think you mentioned something about Focalboard having issues importing React Router from the web app, so perhaps this was the issue? The error I got was around a call to `getContext` returning undefined in `useLocation` and other React Router hooks.
```release-note
NONE
```
> Correctly import React Router elements

- components/channel_layout/center_channel/center_channel.test.tsx
- components/channel_layout/center_channel/center_channel.tsx
- components/channel_layout/center_channel/index.ts
- Lazy loaded ActivityAndInsights (since it depends if it is enabled on the server)
- Lazy loaded ChannelHeaderMobile (since it depends if its open in mobile view
- Prop rearrangement for components/channel_layout/center_channel/center_channel.tsx
https://mattermost.atlassian.net/browse/MM-46496
n/a
n/a
```release-note
NONE
```
> MM-46496 : Seperate bundle for ActivityAndInsights and ChannelHeaderMobile

- actions/telemetry_actions.jsx
- components/post_view/post_list/post_list.tsx
More specifically, it's supposed to count all HTTP requests made using fetch or XMLHttpRequest during that period that go to the API. Unfortunately, it seems to only count requests completed by the time `markAndMeasureChannelSwitchEnd` occurs which happens as soon as any posts in the channel have been loaded. That matches with the time period captured by channel_switch and team_switch events though, so it might still be reasonable.
https://mattermost.atlassian.net/browse/MM-41823
https://mattermost.atlassian.net/browse/MM-41824
```release-note
Add telemetry for counting network requests made while switching channels or teams
```
> MM-41823/MM-41824 Count requests made during channel_switch and team_switch

- packages/mattermost-redux/src/actions/threads.ts
Adding a user to the channel on RHS causes an error
Fixes https://mattermost.atlassian.net/browse/MM-46557
NONE
```release-note
* Adding user to channel on RHS causes an error
```
> [MM-46557] Adding user to channel on RHS causes an error

- components/dot_menu/dot_menu.test.tsx
- components/dot_menu/dot_menu.tsx
- components/dot_menu/index.ts
- packages/mattermost-redux/src/selectors/entities/preferences.ts
Cherry pick of #10838 on cloud.
```release-note
NONE
```
> Automated cherry pick of #10838

- .github/workflows/bundle-size-analysis.yml
- components/actions_menu/actions_menu.tsx
As per [permissions of github actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) forked prs cannot have write permissions. Hence adding this skipping this CI
https://mattermost.atlassian.net/browse/MM-46642
n/a
n/a
```release-note
NONE
```
> MM-46642 : Skip bundlesize CI for forked repositories PR

- components/channel_header/__snapshots__/channel_header.test.tsx.snap
- components/channel_header/channel_header.test.tsx
- components/channel_header/channel_header.tsx
- components/channel_header/index.ts
- components/user_settings/notifications/user_settings_notifications.tsx
- plugins/channel_header_plug/channel_header_plug.tsx
This PR migrates 'components/channel_header' module and associated tests to TypeScript
Fixes https://github.com/mattermost/mattermost-server/issues/16713
JIRA: https://mattermost.atlassian.net/browse/MM-20393
```release-note
NONE
```
> MM-20393: Migrate 'components/channel_header' module and associated tests to TypeScript

- components/onboarding_tasklist/onboarding_tasklist.tsx
- components/onboarding_tasks/constants.ts
this PR adds a telemetry event for initial show of the onboarding tasklist and and also add event when the tasklist dismissed
https://mattermost.atlassian.net/browse/MM-46526
n/a
```release-note
NONE
```
> MM-46526 - add telemetry event for initial show of tasklist and add event to dismiss

- utils/text_formatting.test.jsx
- utils/text_formatting.tsx
When a post has a markdown image in it and a code block, all new lines in the code block are converted into `<br/>` and are visible in the code block.
This pull request excludes code blocks from conversion of newlines into `<br/>`.
Relevant unit tests have been added in the text formatting util, too.
Fixes https://mattermost.atlassian.net/browse/MM-45349
```release-note
NONE
```
> [MM-45349] Fix for visible html line breaks in code blocks

- actions/websocket_actions.jsx
- components/create_comment/create_comment.jsx
- components/create_post/create_post.jsx
This query is causing issues in a customer's large scale environment and is not required unless the `TeamSettings. EnableConfirmNotificationsToChannel` config setting is enabled. With this PR the query should be disabled when that setting is off.
```release-note
Prevent request for counting channel members in a group when feature configured off to prevent performance problems at scale
```
> [Backport to 5.37] Only query channel member counts by group when the related config is enabled

- components/activity_and_insights/activity_and_insights.scss
Hiding the Top Playbooks widget, temporarily for the Cloud release. This merge into master will be used for a `cloud` branch cherry-pick and then will be undone on `master`.
n/a
```release-note
NONE
```
> Hide Top Playbooks Insights widget (temporarily for cloud).

- package-lock.json
- package.json
update the compass-icon package version to the latest release
n/a
https://github.com/mattermost/compass-icons/pull/46
n/a
```release-note
NONE
```
> updated version for compass-icons package

- components/user_settings/security/user_access_token_section/user_access_token_section.tsx
- i18n/en.json
There's some typos in these strings as discussed here: https://community.mattermost.com/core/pl/unwdybmhy3baiygmrfbshydp8o
```release-note
Fixed typos in some translations that caused links to be broken
```
> Fix URLs in translations string for personal access tokens

- actions/websocket_actions.jsx
- components/create_comment/create_comment.tsx
- components/create_post/create_post.tsx
We gate the API calls behind the EnableConfirmNotificationsToChannel
config knob. This was probably the right thing to do in the
first place.
And also fixes a performance issue for a large customer.
https://mattermost.atlassian.net/browse/MM-46842
```release-note
If EnableConfirmNotificationsToChannel is disabled, channel member counts by group API won't be called.
```
> MM-46842: Do not query channelMemberCounts without config knob

- actions/websocket_actions.jsx
- components/create_comment/create_comment.tsx
- components/create_post/create_post.tsx
We gate the API calls behind the EnableConfirmNotificationsToChannel
config knob. This was probably the right thing to do in the
first place.
And also fixes a performance issue for a large customer.
https://mattermost.atlassian.net/browse/MM-46842
> MM-46842: Do not query channelMemberCounts without config knob (#11049)

- packages/mattermost-redux/src/actions/errors.ts
- packages/types/src/errors.ts
- root.tsx
This typo was introduced in #9891 and attemptedly fixed in #10095. The first PR confused the type of the 5th parameter to `window.onerror` which caused us to pass an `Error` instead of the `stack` string. The second PR stopped the error that the first PR caused, but we thought that it happened because of inconsistent behaviour between browsers when it was actually just our own code that was a bit messed up.
#9891
#10095
```release-note
NONE
```
> Fix error in error handling

- actions/command.test.js
- actions/command.ts
- components/global_header/left_controls/product_menu/product_menu_list/index.ts
- i18n/en.json
- packages/mattermost-redux/src/selectors/entities/general.ts
Add checks on the `/marketplace` command to only allow its execution when: 
- the user has the appropriate permission (`sysconsole_read_plugins` - [got it from the server side permission](https://github.com/mattermost/mattermost-server/blob/a5ea445bf9b173515f09a4b71a15c911cf9f35cb/api4/plugin.go#L291))
- the server config has plugins and marketplace enabled
https://mattermost.atlassian.net/browse/MM-46663
- [Has server changes](https://github.com/mattermost/mattermost-server/pull/20919)
As a user without permission:
When marketplace is disabled in the config:
```release-note
NONE
```
> [MM-46663] Only enable marketplace command execution when config allows it and user has permission

- components/commercial_support_modal/__snapshots__/commercial_support_modal.test.tsx.snap
- components/commercial_support_modal/commercial_support_modal.tsx
In the Desktop App, the support was unable to be downloaded because the app expected the link to be opened in a new window, which is only handled by the Desktop App for certain links.
It didn't really seem to make sense to make an exception for the support packet, so I've removed the `target=_blank` from the link since it doesn't really need to open in a new window as far I can tell anyways.
https://mattermost.atlassian.net/browse/MM-46239
```release-note
NONE
```
> [MM-46239] Remove target=_blank from support packet link

- components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- i18n/i18n.jsx
Bulgarian product translations haven't been actively maintained, and with this reduction in translation quality, this language is being downgraded to Beta.
```release-note
Downgraded Bulgarian language support to Beta.
```
> Downgrade Bulgarian/Български to Beta

- packages/client/src/client4.ts
- packages/mattermost-redux/src/actions/groups.ts
- packages/mattermost-redux/src/actions/teams.ts
- packages/mattermost-redux/src/types/actions.ts
Adds support to specify Return data and error type of an action using 'ActionFunc' as its return type by use of generics and conditional typing.
🔗 This is part of effort for adding graphQL to channels
https://mattermost.atlassian.net/browse/MM-46865
```release-note
NONE
```
> MM-46865 : Improve return type of 'ActionFunc' of 'mattermost-redux/types/actions'

- selectors/plugins.ts
This PR adds a check to ensure the `shouldRender` argument is a function before attempting to call it. More info is in the linked ticket.
https://mattermost.atlassian.net/browse/MM-46695
- https://github.com/mattermost/mattermost-webapp/pull/10400
```release-note
NONE
```
> Fix plugin ChannelHeaderMenu component shouldRender function check

- components/invitation_modal/invitation_modal.scss
The PR fixes the squashed invite member modal which happens on smaller screens.
https://mattermost.atlassian.net/browse/MM-44799
|----|----|
| ![Screenshot 2022-09-05 at 10 58 12](https://user-images.githubusercontent.com/841955/188398427-1038e256-a7a6-4840-a3a5-26c1130fca6c.png) | ![Screenshot 2022-09-05 at 10 54 34](https://user-images.githubusercontent.com/841955/188397799-c2aae89e-b86b-4c15-9984-5b47d013fbc4.png) |
```release-note
NONE
```
> invite member modal fits on screen for small screen

- components/advanced_text_editor/advanced_text_editor.tsx
the `RhsSuggestionList` component measures the correct position for itself and therefor is being used as the default suggestionList component for the ATE now.
[MM-45597](https://mattermost.atlassian.net/browse/MM-45597)
n/a
n/a
```release-note
NONE
```
> [MM-45597]: made RhsSuggestionList default in ATE

- components/signup/signup.tsx
In a brand new server with no users, after the signup completes and before redirecting to the create team screen, there should not be a brief flash of an error of “No signups allowed”.
https://mattermost.atlassian.net/browse/MM-44921
https://user-images.githubusercontent.com/79058848/188735314-bc9f51cb-d76f-479e-874e-d3f285a1b983.mp4
https://user-images.githubusercontent.com/79058848/188728681-c5cd1de0-69f0-46cf-a55b-0ed6405ae9bf.mp4
```release-note
NONE
```
> MM-44921_First admin signup in new server briefly flashes error screen

- sass/layout/_headers.scss
Intro-link button fix
The buttons don't force the icon to be inline (if it isn't already). The compassIcon component has certain styles that make it take display flex styling instead of inline, so the button forcing a display flex layout would be a much better way of fixing this.
```release-note
NONE
```
> Intro-link button fix

- components/post_priority/post_priority_picker_item.tsx
Boards is adding inline styles that change the `.Menu` class, 
which have the effect of not showing the "post priority" picker items.
This PR negates those changes, by styles in the styled-component used as the Menu in the picker.
https://mattermost.atlassian.net/browse/MM-46977
```release-note
NONE
```
> MM-46977: fixes post priority menu

- actions/channel_actions.test.ts
- actions/channel_actions.ts
- actions/views/channel.ts
- actions/views/create_comment.test.jsx
- actions/websocket_actions.jsx
- components/advanced_create_post/advanced_create_post.test.jsx
- components/create_post/create_post.test.jsx
- components/more_channels/index.ts
- components/permalink_view/actions.ts
- components/permalink_view/permalink_view.test.tsx
- components/post_view/message_attachments/action_menu/action_menu.test.tsx
- components/post_view/message_attachments/action_menu/action_menu.tsx
- components/post_view/message_attachments/action_menu/index.ts
- components/profile_popover/index.ts
- packages/mattermost-redux/src/actions/channels.ts
This is where the new graphql actions related to channels are , so it was important it to be converted to ts.
https://mattermost.atlassian.net/browse/MM-46992
n/a
n/a
```release-note
```
> MM-46992 : Migrate "actions/channel_actions" to ts

- components/activity_and_insights/activity_and_insights.scss
- sass/responsive/_desktop.scss
Fixing responsive of insights when threads are open. On larger screens the large cards were being pushed to the side
https://mattermost.atlassian.net/browse/MM-46886
```release-note
NONE
```
> [MM-46886] Fix responsive issue for insights

- components/login/__snapshots__/login.test.tsx.snap
- components/login/login.scss
- components/login/login.tsx
- components/signup/__snapshots__/signup.test.tsx.snap
- components/signup/signup.scss
- components/signup/signup.tsx
Currently, the alternate link anchors away from the login and signup form if the brand description or brand image occupies alot of space. This PR fixes it so the alternate link remains in its place
https://mattermost.atlassian.net/browse/MM-45803
|----|----|
| ![login-before](https://user-images.githubusercontent.com/841955/188657549-876cc31b-de76-40e3-a269-2cd5144ff2d0.png) | ![login-after](https://user-images.githubusercontent.com/841955/188657593-fd9b54b6-d030-4faf-b9e4-6e95faa2eb87.png) |
```release-note
NONE
```
> improved alternate link placement on login and signup page

- packages/client/src/client4.ts
- packages/mattermost-redux/src/action_types/posts.ts
- packages/mattermost-redux/src/actions/posts.ts
Adds `client4.moveThread` method to call the thread move endpoint,
and a redux action (`moveThread`) to dispatch.
```release-note
NONE
```
> Adds redux action to move a thread

- components/user_settings/advanced/index.ts
- components/user_settings/advanced/user_settings_advanced.tsx
- components/user_settings/advanced/wysiwyg_section/index.tsx
- components/user_settings/advanced/wysiwyg_section/wysiwyg_section.tsx
- packages/mattermost-redux/src/selectors/entities/preferences.ts
This PR adds the feature flag check for WYSIWYG Editor.
Unless the Feature Flag is set to true, the user cannot enable the feature through `Settings` > `Advanced` > `WYSIWYG Message Editor`.  The feature will not show in the settings. 
Once the feature flag is enabled, the user preference to turn the feature `on` or `off` is shown.
N/A
- Adds the Feature Flag - https://github.com/mattermost/mattermost-server/pull/21120
```release-note
```
> [contributor / wysiwyg] Add Feature Flag

- components/activity_and_insights/insights/top_reactions/top_reactions.tsx
- components/activity_and_insights/insights/top_reactions/top_reactions_table/top_reactions_table.test.tsx
- components/activity_and_insights/insights/top_reactions/top_reactions_table/top_reactions_table.tsx
Load custom emojis in the top reactions table and top reactions chart components, so that they are shown.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-46884)
Steps to reproduce bug:
- Switch to insights, make sure top reactions chart and/or top reactions table contains some custom emojis 
- Switch to a channel that doesn't have custom emojis in use
- Log out of user then log back in
- Switch to insights 
- You should see that the custom emojis in the top reactions chart/table do not render
The bug may also occur in other cases but the above is the easiest way for me to reproduce it.
```release-note
NONE
```
> [MM-46884] Load custom emojis in top reactions components

- webpack.config.js
ESLint doesn't support the async webpack config that we need for the web app to automatically configure the multi-product stuff, so we need to bypass that stuff there. The check I'd previously added for ESLint didn't work while running VS Code.
This fixes how the VS Code version of ESLint was having issues sorting imports while CI and `npm run check` weren't complaining.
```release-note
NONE
```
> Fix ESLint in VS Code

- actions/views/channel.ts
- components/suggestion/switch_channel_provider.jsx
- components/suggestion/switch_channel_provider.test.jsx
- utils/constants.tsx
Adding insights to the channel switcher with `cmd+k`. It follows the same procedure as threads
https://mattermost.atlassian.net/browse/MM-45488
```release-note
Adding insights to the channel switcher
```
> [MM-45488] Adding insights to the channel switcher

- components/activity_and_insights/insights/insights.tsx
- components/sidebar_right/sidebar_right.tsx
Close the RHS when opening insights and reopen when navigating away. Also fix a JS error if you try use the channel info shortcut on the insights page
https://mattermost.atlassian.net/browse/MM-46988
```release-note
NONE
```
> [MM-46988] Fixing channel info shortcut and closing rhs when opening insights

- components/channel_notifications_modal/components/expand_view.test.jsx
- components/channel_notifications_modal/components/expand_view.tsx
- components/channel_notifications_modal/components/notification_section.jsx
Migrate expand view to typescript
Fixes https://github.com/mattermost/mattermost-server/issues/21070
Fixes https://mattermost.atlassian.net/browse/MM-47099
NA
NA
```release-note
NONE
```
> MM-47099 :  Migrate "components/channel_notifications_modal/components/expand_view.jsx" to Typescript

- components/create_team/create_team.tsx
- components/create_team/index.ts
This PR migrates components/create_team/index.js to TypeScript. I have checked tests, check-style, and check-types locally and didn't find any issues with the new changes.
Fixes https://github.com/mattermost/mattermost-server/issues/21041
Fixes https://mattermost.atlassian.net/browse/MM-47120
N/A
N/A
NONE
> MM-47120 : Migrate "components/create_team/index.js" to Typescript

- components/channel_view/index.ts
While checking permission for channel posting we iterate through roles but break on first iteration.
It seems that it works in most situations as "channel_user" role is first in a roles array. But if that is not the case a user would not be able to write to the channel.
I move break statement to an if where we really find the role so that we iterate through all the available roles.
```release-note
NONE
```
> fix: break only when role match is found

- components/post_markdown/index.test.ts
Migrate post_markdown index.test.js to typescript
Fixes https://github.com/mattermost/mattermost-server/issues/21052
Fixes https://mattermost.atlassian.net/browse/MM-47118
NA
NA
```release-note
NONE
```
> MM-47118 : Migrate "components/post_markdown/index.test.js" to Typescript

- components/at_mention/at_mention.tsx
We added an extra e.preventDefault during fixing react 17 bugs for other popovers. This one was redundant and was causing issues with closing the popovers. 
https://mattermost.atlassian.net/browse/MM-47153
```release-note
NONE
```
> Fix profile popovers closing action due to react update

- i18n/en.json
- plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
- plugins/pluggable/error_boundary.tsx
- plugins/pluggable/pluggable.test.jsx
- plugins/pluggable/pluggable.tsx
While we can't guarantee plugins won't crash, we can at least guarantee that they won't crash the whole web app by using error boundaries. An error boundary stops a React error from crashing the web app with the sort of crash that makes the whole page go blank. Since we use this `Pluggable` component to wrap everywhere that a plugin injects content into the web app, this'll protect most of the app from errors.
Some of these examples are faked, but the one with clicking "unfollow run" is a real one.
https://user-images.githubusercontent.com/3277310/190820848-42c8dbdf-38fe-4374-b1e8-ffb24691dab8.mp4
https://user-images.githubusercontent.com/3277310/190820883-a834e9ab-4cc1-48f2-8f7f-d8903daf6add.mp4
https://mattermost.atlassian.net/browse/MM-47044
```release-note
Prevent plugin components …
```
> MM-47044 Wrap Pluggable component in an error boundary

- components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- i18n/i18n.jsx
Brazilian Portuguese and Romanian product translations haven't been actively maintained, and with this reduction in translation quality, these two languages are being downgraded to Alpha.
```release-note
Downgraded Brazilian Portuguese and Romanian language support to Alpha.
```
> Downgraded Brazilian Portuguese and Romanian language support to Alpha

- Makefile
The current commands to delete those files fail when the file doesn't exist
```release-note
NONE
```
> Prevent clean from failing because of missing files

- components/admin_console/admin_definition.jsx
- components/admin_console/group_settings/__snapshots__/group_settings.test.tsx.snap
- components/admin_console/group_settings/group_settings.tsx
- components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.tsx.snap
- components/widgets/admin_console/admin_panel.test.tsx
- components/widgets/admin_console/admin_panel.tsx
- components/widgets/admin_console/admin_panel_with_link.tsx
- i18n/en.json
- sass/routes/_admin-console.scss
1. There were some broken links in places that used the `AdminPanel` component because it still used a `FormattedMessage`. Since it only used Markdown in one place, I just changed that case to not use Markdown instead of adding an option to switch between Markdown and non-Markdown.
2. In the comments of the ticket, there was also an issue reported where links in the OpenID/OAuth settings were broken, so I fixed those as well. Since we no longer generate a proper list in those elements, I changed the CSS so that the newlines we added to that help text were visible. Ideally, we'd break that down into a proper list, but the System Console schema doesn't support arbitrary elements in help text.
https://mattermost.atlassian.net/browse/MM-46316
```release-note
Fixed a few broken links in the …
```
> MM-46316 Fix a few broken links in the System Console

- components/threading/global_threads_link/global_threads_link.tsx
Added "Threads" to the unread filter view even if there aren't unread threads.
Note this only applies when the following conditions are fulfilled:
- The "Collapsed Reply Threads" setting is enabled.
- The “group unreads separately” setting is not enabled.
Fixes [https://github.com/mattermost/mattermost-server/issues/21186](https://github.com/mattermost/mattermost-server/issues/21186)
Jira [https://mattermost.atlassian.net/browse/MM-46953](https://mattermost.atlassian.net/browse/MM-46953)
|  before  |
|----|
|  after  |
|----|
```release-note
Added "Threads" to the unread filter view even if there aren't unread threads.
```
> MM-46953 : Add "Threads" to the unread filter view even if there aren't unread threads

- components/integrations/integration_option.tsx
- components/integrations/integrations.jsx
MM-47089:Migrate "components/integrations/integration_option.jsx" to Typescript
Fixes https://github.com/mattermost/mattermost-server/issues/21080
Fixes  https://mattermost.atlassian.net/browse/MM-47089
None 
None
```release-note
NONE
```
> MM-47089 : Migrate "components/integrations/integration_option.jsx" to Typescript 

- components/size_aware_image.jsx
React complains when this value is set to a boolean and recommends setting it to undefined in this case. I can't remember if this warning is exclusive to dev mode or if it only happens when there's no image proxy enabled, but it doesn't trigger on community from what I can tell
```release-note
NONE
```
> Fix warning printed by SizeAwareImage

- components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
- components/channel_header_dropdown/channel_header_dropdown_items.js
Temporary fix to reorder the "leave channel" menu option above the plugin menu entries so users on smaller monitors still have the ability to leave a channel. The full fix will be addressed with https://mattermost.atlassian.net/browse/MM-40156 and the web platform teams Q4 OKRs for menus
Root cause is this bug: https://mattermost.atlassian.net/browse/MM-47217
```release-note
NONE
```
> MM-47217 Reorder the leave channel menu item

- components/post_view/post_list_virtualized/post_list_virtualized.tsx
- components/toast_wrapper/index.ts
- components/toast_wrapper/toast_wrapper.test.tsx
- components/toast_wrapper/toast_wrapper.tsx
- packages/mattermost-redux/src/utils/post_list.ts
This PR migrates 'components/toast_wrapper' and associated tests to TypeScript
Fixes https://github.com/mattermost/mattermost-server/issues/17276
JIRA: https://mattermost.atlassian.net/browse/MM-34347
```release-note
NONE
```
> MM-34347: Migrate 'components/toast_wrapper' and associated tests to TypeScript

- package.json
This PR will upgrade `@mattermost/compass-icons` to 0.1.28. A new `icon-shuffle-variant` which is added in compass-icons wasn't rendering in plugin mode. This will fix that. Linking related PR below.
https://github.com/mattermost/focalboard/pull/3924
```release-note
Bump compass-icons to "0.1.28"
```
> Bump @mattermost/compass-icons to 0.1.28

- components/purchase_modal/process_payment_setup.tsx
When you enter the System Console, `currentTeamId` and therefore `currentTeam` are cleared (this is core mattermost functionality, and has been this way always), so we are unable to display `Return to {team}` as we don't know which team to return to. Since `currentTeam` was undefined, it was causing a javascript error `cannot read display_name of undefined`, triggering a white screen instead of the success page. This PR makes it so that if the `currentTeam` is undefined (ie, if the upgrade flow is accessed from the system console) the button label will read `Return to System Console`
https://mattermost.atlassian.net/browse/MM-47054
```release-note
None
```
> [MM-47054] Change button label if upgrade is executed from System Console

- e2e/cypress/package-lock.json
- e2e/cypress/package.json
- e2e/cypress/tests/integration/custom_status/custom_status_1_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_2_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_3_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_4_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_5_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_6_spec.ts
- e2e/cypress/tests/support/api/system.d.ts
- e2e/cypress/tests/support/extended_commands.d.ts
- e2e/cypress/tests/support/extended_commands.js
- e2e/cypress/tests/support/ui/global_header.d.ts
migrated following files to typescript:
- e2e/cypress/tests/integration/custom_status/custom_status_1_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_2_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_3_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_4_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_5_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_6_spec.ts
also added a type-definition for the custom `typeWithForce` command and changed the definition for `uiOpenUserMenu` since the existing definition was incorrect
https://github.com/mattermost/mattermost-server/issues/21315
n/a
n/a
```release-note
NONE
```
> [#21315]: migrated custom status tests to typescript

- components/multiselect/multiselect_list.tsx
- i18n/en.json
Screen reader fails in announcing No result found in dm modal.
https://mattermost.atlassian.net/browse/MM-44858
Fixes https://mattermost.atlassian.net/browse/MM-44858
Fixes https://github.com/mattermost/mattermost-server/issues/21260
None
|  before  |
https://user-images.githubusercontent.com/102028591/190338880-68cbabea-76e2-48f8-8a1c-8dc63dd5e91e.mp4
|  after  |
https://user-images.githubusercontent.com/102028591/190334214-97253e31-12e9-4e83-941b-37908a4e186a.mp4
```release-note
In the Direct Messages modal (+ next to Direct Messages) when we try to search anything which is not present, a message ( No results found matching)  is visible and not accessible by the screenreaders. 
```
> [MM-44858] Screen reader fails in announcing no result found in dm modal

- components/password_reset_form/password_reset_form.tsx
- i18n/en.json
Remove the error message that displays when the inputted password is less than 5 characters so it only relies on the backend error message.
[MM-42341
](https://mattermost.atlassian.net/browse/MM-42341)
|----|----|
| ![image](https://user-images.githubusercontent.com/44761757/189185127-1af0e675-054a-4c32-ae8f-2ce7ee43cdfd.png) |![image](https://user-images.githubusercontent.com/44761757/189210401-205f44b2-2570-452d-99b0-1372b5aabc63.png)|
```release-note
Remove the error message on the Reset Password page that appears when the inputted password is fewer than 5 characters .
```
> [MM-42341] Reset password error message

- entry.tsx
- root.tsx
- webpack.config.js
So there's two issues that prevent subpaths from working currently:
1. The server's subpath rewriting logic silently fails (with an error message in the logs) when it can't find the CSP meta tag in the HTML. While that isn't needed for most cases, it's probably needed if people deploy MM using a CDN since that wouldn't load static files through the MM server which is responsible for adding the CSP HTML header. This PR fixes that by re-adding the CSP meta tag.
2. Since we're using module federation to load web app files now, we need to set the `__webpack_public_path__` sooner in the process before module federation is initialized. That's fixed by moving that stuff to happen in `root.tsx` before `entry.tsx` is loaded.
https://mattermost.atlassian.net/browse/MM-47400 …
> MM-47400/MM-47410 Fix subpaths with module federation

- e2e/cypress/tests/integration/autocomplete/common_test.ts
- e2e/cypress/tests/integration/autocomplete/helpers.ts
- e2e/cypress/tests/support/api/team.d.ts
- e2e/cypress/tests/support/api/user.d.ts
- e2e/cypress/tests/support/ui/common.d.ts
- e2e/cypress/tests/support/ui/suggestion_list.d.ts
Following files under /integration/autocomplete are converted to Typescript
helpers.js
common_test.js
Fixes https://github.com/mattermost/mattermost-server/issues/21291
JIRA: https://mattermost.atlassian.net/browse/MM-47284
```release-note
NONE
```
> MM-47284: Migrate /autocomplete/ tests to TypeScript

- packages/mattermost-redux/src/reducers/entities/channels.test.js
- packages/mattermost-redux/src/reducers/entities/channels.ts
On a websocket reconnect, under certain circumstances, a DM was marked as unread, but mention badges were not appearing. 
This appears to be a result of the change introduced in [#10589](https://github.com/mattermost/mattermost-webapp/pull/10589/files?diff=split&w=0#diff-7e2d5cd0fc248e2dd23906616bad90b0c819b2070ef84e8fc5138760b7d56d90R480). 
If the DM is read, then the mention count is 0. The count in the newly fetched membership is ignored because `math.min(0, updated_count)` is 0.
- https://mattermost.atlassian.net/browse/MM-45848
```release-note
Fix display of mention counts in unread channels
```
> MM-45848: fix mention badge update

- components/root/root.tsx
Add UTM tracking on the webapp.
The PR reads the params from the URL, fires a trackEvent, and then removes the params from the URL to prevent re-triggering the event upon refresh.
https://mattermost.atlassian.net/browse/MM-47499
N/A
N/A
```release-note
NONE
```
> [MM-47499] Add UTM Tracking

- components/admin_console/billing/billing_history_modal.tsx
- components/cloud_invoice_preview/index.tsx
- components/start_trial_modal/index.tsx
Add missing a11y__modal dialogClassName to <Modal> components.
This is the only references to `<Model>` without a11y__modal I found using `<Modal( |\n)((?:(?!a11y__modal).)*\n)+\s*>` regex
For a11y__popup I will need a little more background to see if I can found them. I did see `<Popover>` component, but no one use a11y__popup classname so I did not touch that.
Fixes https://github.com/mattermost/mattermost-server/issues/13865
```release-note
NONE
```
> GH-13865 : Add missing a11y__modal dialogClassName to <Modal> components

- utils/policy_roles_adapter.test.jsx
- utils/policy_roles_adapter.ts
Migrate utils/policy_roles_adapter.js to typescript
Fixes https://github.com/mattermost/mattermost-server/issues/21167
JIRA: https://mattermost.atlassian.net/browse/MM-47192
None
None
```release-note
NONE
```
> MM-47192 : Migrate "utils/policy_roles_adapter.js" to typescript

- e2e/cypress/tests/integration/enterprise/channel/channel_groups_spec.ts
- e2e/cypress/tests/support/api/channel.d.ts
- e2e/cypress/tests/support/api/system.d.ts
- e2e/cypress/tests/support/api/team.d.ts
- e2e/cypress/tests/support/index.d.ts
Converted the following spec files under /integration/enterprise/channel to Typescript
1. channel_groups_spec.js
Fixes https://github.com/mattermost/mattermost-server/issues/21309
```release-note
NONE
```
> [MM-47299] Migrated enterprise/permissions tests to Typescript

- utils/markdown/apply_markdown.ts
Fixes the behavior of applying styles to the selected text.
When there is a space selected at the start or end of the string it gets stripped and instead added to the pre-/suffix.
[MM-45385](https://mattermost.atlassian.net/browse/MM-45385)
n/a
n/a
```release-note
NONE
```
> [MM-45385]: fixing selection after applying styles

- e2e/cypress/tests/integration/profile_settings/profile_settings_spec.js
This tests the profile settings feature in our app. On navigating to profile settings (User menu > Profile > Profile Settings), when we edit the full name, we click on cancel instead of saving since we had not saved it, so it should reflect the full name which was there initially(before we clicked on edit). 
Addresses https://github.com/mattermost/mattermost-server/issues/18819
Added a new e2e cypress test for testing editing of full name in profile settings
> MM-T2044 added profile-settings test spec

- components/channel_view/__snapshots__/channel_view.test.tsx.snap
- components/channel_view/channel_view.test.tsx
- components/channel_view/channel_view.tsx
- components/channel_view/index.ts
The situation was that the create post will be briefly in [disabled state](https://mattermost.atlassian.net/browse/MM-22801) until the permissions are resolved from the network  . To counter this flash a fix https://github.com/mattermost/mattermost-webapp/pull/5337 was to keeping checking the permission state until the relevant permission for the channel is found. It worked as a kind of [loading mechanism](https://github.com/mattermost/mattermost-webapp/pull/5417/files#r417472909). Fortunately things have changed [after that](https://github.com/mattermost/mattermost-redux/blob/3d1028034d7677adfda58e91b9a5dcaf1bc0ff99/src/selectors/entities/roles.ts#L187) and we have improved the IPermission selector https://github.com/mattermost/mattermost-webapp/pull/10058 and brought the permission …
> MM-47534 : Remove the 'channelRolesLoading' check in "channel_view"

- e2e/cypress/package-lock.json
- e2e/cypress/package.json
- e2e/cypress/tests/integration/custom_status/custom_status_1_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_2_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_3_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_4_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_5_spec.ts
- e2e/cypress/tests/integration/custom_status/custom_status_6_spec.ts
- e2e/cypress/tests/integration/enterprise/oauth/oauth_spec.ts
- e2e/cypress/tests/support/api/setup.ts
- Revert changes using lodash.set
- Use Mattermost [types under `Cypress` namespace](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/tests/support/index.d.ts#L7-L35) to keep imports in one place only.
```release-note
NONE
```
> Cypress/E2E: Revert changes using lodash.set and mattermost types imports

- components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
- components/user_settings/display/manage_languages/manage_languages.test.tsx
- components/user_settings/display/manage_languages/manage_languages.tsx
- i18n/en.json
Announcing of Settings > Display > Language > Change interface language field dropdown correctly 
Fixes https://mattermost.atlassian.net/browse/MM-44114
Fixes https://github.com/mattermost/mattermost-server/issues/21159
none
|  before | 
https://user-images.githubusercontent.com/102028591/189839616-ae976aa3-87eb-4d5b-8750-166a67e1af0b.mp4
|  after  |
https://user-images.githubusercontent.com/102028591/189838983-b1e9fb1a-0917-45eb-bf0f-776a95b64a02.mp4
```release-note
Channel interface language dropdown in  Settings > Display > Language > Change interface language field not announcing that it was a dropdown by ScreenReader. Now by giving Aria-label to it makes it announcing properly by ScreenReader.
```
> MM-44114 : Announcing of channel interface language dropdown correctly

- tsconfig.json
The purpose of this change is to incorporate ts check support for `import.meta`. Currently [webpack already handles ](https://github.com/webpack/webpack/issues/6719)it without any configuration change https://webpack.js.org/api/module-variables/#importmetaurl. But the ts compiler throws error `The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'esnext', or 'system'.`. We cannot directly go to `esnext` as ts 4.7+ is needed for that change. For context "import.meta" is required to add WASM support in the app.
https://mattermost.atlassian.net/browse/MM-47611
n/a
n/a
```release-note
NONE
```
> MM-47611 : Change tsconfig value of module to 'es2020'

- components/onboarding_tasks/onboarding_tasks_manager.test.tsx
- components/onboarding_tasks/onboarding_tasks_manager.tsx
- packages/mattermost-redux/src/selectors/entities/users.ts
This PR adds code to hide the invite team members onboarding task list item to guest users.
https://mattermost.atlassian.net/browse/MM-47497
n/a
Before:
After:
```release-note
NONE
```
> MM-47497 - remove invite task from guest users

- components/admin_console/feature_discovery/__snapshots__/feature_discovery.test.tsx.snap
- components/admin_console/feature_discovery/feature_discovery.tsx
This PR attaches the id of the feature guarded by the feature discovery page to the telemetry id used to know where cloud trial starts from.
https://mattermost.atlassian.net/browse/MM-47679
n/a
```release-note
NONE
```
> MM-47679 - add id to feature discovery cloud trial start telemetry id

- actions/invite_actions.test.ts
- actions/invite_actions.ts
- components/invitation_modal/result_table.scss
- components/invitation_modal/result_table.tsx
- i18n/en.json
- utils/constants.tsx
Add system console SMPT config link to the invitation error.
https://mattermost.atlassian.net/browse/MM-44031
|----|----|
| ![Screenshot 2022-10-08 at 16 45 15](https://user-images.githubusercontent.com/841955/194710648-d77ec1a0-6931-4e13-a7f0-6cef4e67c370.png) | ![Screenshot 2022-10-08 at 16 22 29](https://user-images.githubusercontent.com/841955/194709762-6654aede-ec28-4aeb-8662-fc475ba5065a.png) |
```release-note
NONE
```
> [MM-44031] add system console SMTP link to invitation error

- components/search_results_item/index.ts
Fixes Channel name is not shown for recent mentions or search results.
Fixes https://mattermost.atlassian.net/browse/MM-47584
NONE
|----|----|
| <img width="387" alt="Screenshot at Oct 14 09-25-12" src="https://user-images.githubusercontent.com/16203333/196959391-089e3e28-7beb-41b7-816c-9fa54862d608.png"> | <img width="507" alt="Screenshot 2022-10-20 at 6 46 14 PM" src="https://user-images.githubusercontent.com/16203333/196959417-21afbbb3-7884-4279-b3b7-c75bdb6502af.png"> |
```release-note
* Fixes Channel name is not shown for recent mentions or search results.
```
> [MM-475584]: fix channel name not showing up in search results

- packages/mattermost-redux/src/selectors/entities/roles.test.ts
- packages/mattermost-redux/src/selectors/entities/roles.ts
`haveIGroupPermission` was returning `undefined` when permission didn't exist. Now it returns false
https://mattermost.atlassian.net/browse/MM-45909
```release-note
Fixing issue where custom group actions were appearing in the UI when you didn't have the permissions for them
```
> [MM-45909] Fixing group permissions issue

- components/multiselect/multiselect_list.tsx
- i18n/en.json
Cherry pick of #11140 on release-7.1.
/cc  @babinderrathi
```release-note
NONE
```
> Automated cherry pick of #11140

- utils/test_helper.ts
We had 2 PRs that went in around the same time that conflicted without actually conflicting because one used a type in a new place and another added a field to that type.
```release-note
NONE
```
> Fix missing field from master

- webpack.config.js
This PR is based on https://github.com/mattermost/mattermost-webapp/pull/11355. Changes specific to it are here: https://github.com/mattermost/mattermost-webapp/compare/MM-46981_production-mpa...MM-47238_boards-dev-server-url
This makes it so that people who develop MM on a URL other than `http://localhost` can redefine the URL, port, and protocol that the Boards Webpack dev server runs on for MPA development. Without it sets, it still defaults to running the dev server on `http://localhost:9006`
https://mattermost.atlassian.net/browse/MM-47238
https://github.com/mattermost/mattermost-webapp/pull/11355
https://github.com/mattermost/focalboard/pull/4026
https://github.com/mattermost/mattermost-server/pull/21435
```release-note
NONE
```
> MM-47238 Add MM_BOARDS_DEV_SERVER_URL environment variable for MPA

- components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
- components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
- components/widgets/users/avatars/avatars.tsx
Fixes a bug where the profile popover, when activated from the avatars widget, would not dismiss when a link inside the popover was clicked. Uses the same strategy to dismiss the popover as the post component. 
[Jira ticket](https://mattermost.atlassian.net/browse/MM-46933)
Steps to reproduce:
View the video through the link to see how to reproduce it. 
```release-note
NONE
```
> [MM-46933] Force profile popover to dismiss from avatars widget

- components/single_image_view/single_image_view.tsx
- components/size_aware_image.jsx
- components/size_aware_image.test.jsx
- packages/mattermost-redux/src/utils/file_utils.test.js
- packages/mattermost-redux/src/utils/file_utils.ts
Implement Progressive Image Loading
I didn't use any transition animation as there wasn't any for placeholder to image one.
Fixes  https://github.com/mattermost/mattermost-server/issues/15641
Fixes https://mattermost.atlassian.net/browse/MM-28362
https://user-images.githubusercontent.com/60970/194752364-64704b8a-8296-4148-a6d7-2ce82b1f4ee8.mov
```release-note
Implemented Progressive Image Loading in Webapp
```
> MM-28362 : Implement Progressive Image Loading in Webapp

- components/onboarding_tasks/onboarding_tasks_manager.tsx
- i18n/en.json
In a previous PR done for adding icons to the onboarding task list items, there was a scenario that was missing for the "explore other tools item task" that is only shown to non-admin end users. This small PR adds the icon to that onboarding task list.
https://mattermost.atlassian.net/browse/MM-47242
Original PR: https://github.com/mattermost/mattermost-webapp/pull/11335
Before: (no icon)
After:
```release-note
NONE
```
> MM47242 - add icon to explore other tools in the platform task list item

- components/admin_console/billing/company_info_edit.scss
Fixing a z-index issue with dropdown selector and modal with z-index. Ideally we should use this property at input level, instead of form, but the fix it's much bigger and require more investigation, as the z index levels are complex to follow. 
https://mattermost.atlassian.net/browse/MM-47802
before
After
```release-note
NONE
```
> Z index for dropdown selector collide with modals

- components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
- components/status_dropdown/status_dropdown.scss
- components/status_dropdown/status_dropdown.tsx
- components/widgets/users/avatar/avatar.tsx
Combine the avatar and status icon in global header into one button that can be focused.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-45719)
```release-note
NONE
```
> [MM-45719] Combine focus on avatar and status icon in global header

- components/advanced_create_post/advanced_create_post.tsx
When the `AdvancedCreatePost` component first loads the `currentChannel.id` is undefined, so an errant request with this undefined `currentChannel.id` is sent to `/api/v4/channels/{channel_id}/member_counts_by_group` resulting in the `400` error. 
This PR simply adds a guard to prevent that request if `currentChannel.id` is undefined. The `currentChannel.id` is defined afterwards and the existing logic in the `componentDidUpdate` function handles the same request as expected.
[MM-47995](https://mattermost.atlassian.net/browse/MM-47995)
```release-note
NONE
```
> [MM-47995] Undefined ChannelId Logs 400 Error on Page Load

- package-lock.json
- package.json
As part of regular dependency upgrades, this PR upgrades emoji-regex from version 10.1.0 to 10.2.1.
| From version | To version | Changelog | Notes|
|--------------|------------|------------|------|
| 10.1.0             | 10.2.1          | https://github.com/mathiasbynens/emoji-regex/commits/main | There are no release notes just tags added. The changes introduced from 10.1.0 to 10.2.1 are support for js modules and some style code changes |
I've tested emojis locally and work properly.
https://mattermost.atlassian.net/browse/MM-47622
```release-note
NONE
```
> [MM-47622] minor upgrade of emoji-regex from 10.1.0 to 10.2.1

- package-lock.json
- package.json
In the context of regularly upgrading dependencies in web app, this PR upgrades p-queue to latest version.
| From version | To version | changelog | Notes |
|--------------|-----------|------------|-------|
| 7.1.0               | 7.3.0          | [releases](https://github.com/sindresorhus/p-queue/releases) | Only some new functionality added without breaking changes. Namely, new "empty" queue event emitted in v7.3.0, as well as an abort task signal and controller added in v7.2.0.|
https://mattermost.atlassian.net/browse/MM-47890
```release-note
NONE
```
> [MM-47890] Upgrade p-queue from 7.1.0 to 7.3.0

- webpack.config.js
I have no idea why Node requires two separate packages for making http and https requests since most people wouldn't care about that
https://mattermost.atlassian.net/browse/MM-47793
```release-note
NONE
```
> MM-47793 Let products be developed using https

- components/login/login.tsx
- components/signup/signup.tsx
[UX] When leaving "Custom Brand Text" blank with Custom Branding enabled, we should remove the text altogether.
https://mattermost.atlassian.net/browse/MM-47042
|----|----|
| ![Screen Shot 2022-11-01 at 3 54 24 PM](https://user-images.githubusercontent.com/79058848/199339160-2d1b0558-de77-47c9-94b0-6948a4aff681.png) | ![Screen Shot 2022-11-01 at 3 50 12 PM](https://user-images.githubusercontent.com/79058848/199338692-9b9959ab-1470-4ffc-bf3d-769678dbfccc.png) |
| ![Screen Shot 2022-11-01 at 3 54 10 PM](https://user-images.githubusercontent.com/79058848/199339225-064bf512-6d65-4213-a644-3d70fd4c0450.png) | ![Screen Shot 2022-11-01 at 3 50 26 PM](https://user-images.githubusercontent.com/79058848/199338736-66638b1d-6d33-479a-ba1e-e84976724f49.png) |
```release-note …
```
> MM-47042_Remove default text for "Custom Brand Text" in login-signup

- components/new_channel_modal/new_channel_modal.scss
This PR addressed some styles for the text shown in the add channels modal to create a new board. Modifies the color so it looks well in light and dark themes and adds the hand cursor when hovering over the text.
https://mattermost.atlassian.net/browse/MM-47959
https://mattermost.atlassian.net/browse/MM-47960
n/a
```release-note
NONE
```
> MM-47959, MM-47960 - fix text in dark theme; show cursor as hand in text

- e2e/cypress/tests/integration/auth_sso/authentication_3_spec.ts
- e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_spec.ts
- e2e/cypress/tests/support/api/user.d.ts
Fix the `apiAdminLogin()` function signature, in the Typescript declaration.
None
This is a small improvement over an already merged MR, where the `apiAdminLogin()` function signature issue was observed https://github.com/mattermost/mattermost-webapp/pull/11365
```release-note
NONE
```
> Fix apiadminlogin ts spec

- components/header_footer_route/header_footer_route.scss
In Safari for iPhone, the Signup page now allows to scroll, so the Create Account button can be accessed.
https://mattermost.atlassian.net/browse/MM-45313
https://github.com/mattermost/mattermost-server/issues/20536
https://user-images.githubusercontent.com/79058848/199356814-2882ab5f-35ca-4c2f-88fa-21e415ad4fe5.mp4
```release-note
NONE
```
> MM-45313_Cannot access the create account button on safari for iOS

- package-lock.json
- package.json
Upgrade react-popper to latest version as part of dependency upgrades. The library is used in the onboarding task list component. Apart from checking the changelog of the library (from 2.2.5 to 2.3.0 only support for React 18 has been added, no breaking changes), I checked manually and the onboarding task popover continues to work as previously.
| From version | To version | Changelog | Notes |
|-------------|---------|-----------|---------|
| 2.2.5 | 2.3.0 | [changelog](https://github.com/floating-ui/react-popper/releases) | Add support for React 18 |
https://mattermost.atlassian.net/browse/MM-48046
```release-note
NONE
```
> [MM-48046] upgrade react-popper

- packages/mattermost-redux/src/reducers/entities/users.test.js
- packages/mattermost-redux/src/reducers/entities/users.ts
Users who were removed from a group couldn't be added back in through the UI
https://mattermost.atlassian.net/browse/MM-48049
```release-note
NONE
```
> [MM-48049] Including users who were removed from group in not_in_group response

- sass/components/_channel-invite-modal.scss
Multiselect height will no longer increase indefinitely. After 3 rows it will turn into a scrollable area
https://mattermost.atlassian.net/browse/MM-41906
Before:
After:
```release-note
NONE
```
> [MM-41906] Add max height and overflow to Multiselect

- Makefile
This is another case where running `npm install` or `npm ci` with NODE_ENV=production doesn't install the dev dependencies which was causing the GitLab builds of the web app to fail
```release-note
NONE
```
> Fix `make node_modules` when running in production mode

- components/logged_in/index.ts
- components/logged_in/logged_in.test.tsx
- components/logged_in/logged_in.tsx
Included `viewChannel` in `mapDispatchToProps` so that we don't have to call it with `state` and `dispatch` inside the component
fixes https://github.com/mattermost/mattermost-server/issues/21248
~- Has server changes (please link here)~
~- Has mobile changes (please link here)~
```release-note
NONE
```
> MM-47361 : Remove global state & dispatch from logged_in.tsx

- packages/README.md
With the recent change to isolate jest config into [its own file](https://github.com/mattermost/mattermost-webapp/pull/11372), this pr updates document references in package readme. It also fixes indents in few paragraphs.
https://mattermost.atlassian.net/browse/MM-47715
n/a
n/a
```release-note
NONE
```
> MM-47715 : Update "package/readme" to reflect new jest config file

- components/admin_console/admin_definition.jsx
In March, we hid file sharing and download options in Cloud ([link to PR](https://github.com/mattermost/mattermost-webapp/pull/9953)), including the following settings:
- EnableFileAttachments
- EnableMobileUpload
- EnableMobileDownload
File sharing and Download options in Cloud **_should_** be available, so we must reveal them in the system console now.
**Note**: In the ticket, it's mentioned that we should `Fix mobile upload and download settings, so that they honoured in Cloud when set to 'true'`. This has already been completed, and the settings are honoured.
[MM-45471](https://mattermost.atlassian.net/browse/MM-45471)
|----|----|
| <img width="1186" alt="Screen Shot 2022-11-02 at 4 51 50 PM" src="https://user-images.githubusercontent.com/116016004/199602039-ad8a …
> MM-45471 - Reveal "File Sharing and Download" System Console settings in Cloud.

- components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- i18n/i18n.jsx
Bulgarian, Persian, and Simplified Chinese product translations haven't been actively maintained, and with this reduction in translation quality, these languages are being downgraded to Alpha.
```release-note
Downgraded Bulgarian, Persian, and Simplified Chinese language support to Alpha.
```
> Downgrade languages to Alpha

- components/code_block/__snapshots__/code_block.test.tsx.snap
- components/code_block/code_block.test.tsx
- components/code_block/code_block.tsx
- components/code_preview.tsx
- utils/syntax_highlighting.test.ts
- utils/syntax_highlighting.tsx
Load language libraries of highlight.js on demands to reduce bundle size.
Fixes https://github.com/mattermost/mattermost-server/issues/14029
Jira: https://mattermost.atlassian.net/browse/MM-22249
No related PRs.
No UI changes.
```release-note
NONE
```
> MM-22249 : Add automatic lazy loading of syntax highlighting libraries

- components/onboarding_tasklist/onboarding_tasklist_task.tsx
With the intro of emojis in the tasklist, we want to remove the play/check icon so it's not so cluttered at the start. This is a request from UX. 
https://mattermost.atlassian.net/browse/MM-48361
|----|----|
|  <img width="381" alt="Screen Shot 2022-11-11 at 12 10 50 PM" src="https://user-images.githubusercontent.com/936315/201397278-22ccf82d-55ec-4eae-8da0-0194ccc648eb.png"> | <img width="362" alt="Screen Shot 2022-11-11 at 12 35 32 PM" src="https://user-images.githubusercontent.com/936315/201397302-ce2be287-f9be-428a-a89f-8a80cb6baca3.png">|
```release-note
NONE
```
> Remove the play/check icon in onboarding task list

- components/at_mention/at_mention.tsx
- components/create_user_groups_modal/create_user_groups_modal.test.tsx
- components/create_user_groups_modal/create_user_groups_modal.tsx
- components/update_user_group_modal/update_user_group_modal.tsx
- utils/post_utils.ts
Allowing the same special characters as a user's username
https://mattermost.atlassian.net/browse/MM-46112
```release-note
Allowing the same special characters in a group mention name as a user's username
```
> [MM-46112] Allowing special characters in group name

- components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
- components/admin_console/system_roles/system_role/system_role_permissions.test.tsx
- components/admin_console/system_roles/system_role/system_role_permissions.tsx
Within the console, under `User Management > System Roles`, there exists options to grant/remove access to License and Environment. These options should not be shown for cloud servers.
[MM-30941](https://mattermost.atlassian.net/browse/MM-30941)
|----|----|
| <img width="1186" alt="Screen Shot 2022-11-02 at 2 49 28 PM" src="https://user-images.githubusercontent.com/116016004/199576690-7b3d0e98-d7ba-41c2-9ef0-07cfbb1f405e.png"> | <img width="1186" alt="Screen Shot 2022-11-02 at 2 50 40 PM" src="https://user-images.githubusercontent.com/116016004/199576757-60e58e29-d939-4b60-be0f-ce2bd58b34eb.png"> |
1. Sign onto the server under a role that can access the `System Console`.
2. Upload any cloud license
3. Navigate to `User Management > System Roles`, and click edit on …
> Mm 30941 system roles shows license and environment should be hidden in cloud

- components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
The link to `System Scheme` in the team scheme system console page was broken:
It was linking to `https://docs.mattermost.com/onboard/advanced-permissions.htm` instead of `https://docs.mattermost.com/onboard/advanced-permissions.html`. This fixes it, but perhaps we also want to find a way to permalink the "broken link" for existing systems? 0/5
None.
```release-note
NONE
```
> Fix docs link to advanced permissions

- components/admin_console/license_settings/__snapshots__/license_settings.test.tsx.snap
- components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
- components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.test.tsx
- components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
- components/admin_console/license_settings/license_settings.tsx
- sass/base/_css_variables.scss
- utils/constants.tsx
Display the number of active users on License Panel Detail and dynamically style based on some limits.
https://mattermost.atlassian.net/browse/MM-47645
- Has server changes https://github.com/mattermost/mattermost-server/pull/21666
|----|----|
| ![image](https://user-images.githubusercontent.com/713534/198987671-77e37730-91ea-4650-b747-a7ea84ffeda5.png) | ![image](https://user-images.githubusercontent.com/713534/198987727-0927434d-3f17-46fa-aae0-ed4f6d47c07c.png) |
Between 5% - 10% Overage.
Over 10% Overage
```release-note
Self hosted license detail display the active users.
```
> Mm 47645 show license count activated users

- e2e/cypress/tests/integration/team/archive_team_spec.ts
- e2e/cypress/tests/integration/team_settings/archive_team_spec.ts
- packages/mattermost-redux/src/actions/users_queries.ts
Back when delete_at was not part of gQL query, we hardcoded it with `delete_at = 0`, after the support was added, we never changed that. This pr adds that and other fields to team object. Also adds an e2e test.
https://mattermost.atlassian.net/browse/MM-48423
n/a
n/a
```release-note
Fixed bug in webapp in graphQL environment where it became possible to for user to visit archived team.
```
> MM-48423 : Landing on "Team not found" page on clean slate browser

- components/advanced_create_post/advanced_create_post.test.jsx
- components/advanced_create_post/advanced_create_post.tsx
This ticket fixes a bug in which drafts are not saved after a paste that goes through the pasteHandler in the post textbox is processed (tables and hyperlinks, currently).
https://mattermost.atlassian.net/browse/MM-47681
```release-note
NONE
```
> Fixed post pasteHandler not saving drafts

- packages/mattermost-redux/src/reducers/entities/threads/threads.test.js
- packages/mattermost-redux/src/reducers/entities/threads/threadsInTeam.ts
Upon leaving a channel we collect all threads that belong to that channel and then we remove them from the `threadsInTeam` lists. BUT if a thread is in `threads`, but not in `threadsInTeam` then it will duplicate the list.
This is happening because we didn't check thread's index against -1. So the slice would be 
```js
// list1 == [1,2,3,4]
list2 = [...list.slice(0, -1), ...list.slice(1 - 1)]
// list2 == [1,2,3,1,2,3,4]
// after sorting [1,1,2,2,3,3,4]
```
This commit fixes that issue by checking each thread's index in `threadsInTeam` list, and if it doesn't exist it does nothing.
https://mattermost.atlassian.net/browse/MM-48348
```release-note
Fixed a bug where threads would appear duplicated in the threads list after leaving channels.
```
> Fixes duplicated threads in thread list

- components/threading/global_threads/thread_pane/thread_pane.test.tsx
- packages/mattermost-redux/src/selectors/entities/posts.test.ts
- packages/mattermost-redux/src/selectors/entities/posts.ts
- packages/mattermost-redux/src/utils/post_list.ts
Blank message in threads if send leave/join message preference is off.
Fixes https://mattermost.atlassian.net/jira/software/c/projects/MM/boards/91?modal=detail&selectedIssue=MM-47606
NA
|----|----|
| <img width="477" alt="image-20221014-195045" src="https://user-images.githubusercontent.com/16203333/201605637-3f663fac-f6c9-4e99-9a79-03f2d8bc3c50.png"> | <img width="501" alt="Screenshot 2022-11-14 at 1 27 44 PM" src="https://user-images.githubusercontent.com/16203333/201605693-0fb544d6-6a4a-429f-a5aa-f19a4deb34bc.png">
```release-note
* Blank message in threads if send leave/join message preference is off
```
> [MM-47606]: Blank message in threads if send leave/join message preference is off

- packages/mattermost-redux/src/reducers/entities/channels.ts
We are currently unable to open the profile popover from the Channel member RHS list because opening the popover triggers a request to fetch channel member information which causes the RHS list to re-render and close the popover immediately.
I tried to refactor the RHS list like Caleb suggested in the ticket and I moved the selector for the member information into the child component (`Member`). This solved the render issue but it meant that we couldn't order/sort the list correctly and I was unable to work around that without having the channel member info present in the parent components. From what I can tell, the selectors are functioning correctly and memoizing the components didn't impact the outcome.
I decided to make this change in the reducer, this means that when we open the …
> [MM-45789] Don't update redux state unless something has actually changed

- components/admin_console/feature_discovery/__snapshots__/feature_discovery.test.tsx.snap
- components/admin_console/feature_discovery/feature_discovery.tsx
fix telemetry id for self-hosted trial started from feature discovery pages
https://mattermost.atlassian.net/browse/MM-47759
n/a
```release-note
NONE
```
> MM-47759 - fix telemetry id for self-hosted trial started from feature discovery pages

- .circleci/config.yml
Currently, master CircleCI builds are failing because they're pulling an outdated version of the server bundle which doesn't include products when trying to generate a Docker image containing the latest version of the web app. While I still don't know why that happens (there's some more info available in the Jira ticket though), I don't think we even actually need that Docker image because, as far as I know, those images are only needed for generating Spinwick servers which isn't possible outside of a PR.
Because the Docker image is seemingly never used, I decided to just not even build it when CircleCI is running a build for a non-PR branch.
https://mattermost.atlassian.net/browse/MM-48531
```release-note
NONE
```
> MM-48531 Skip building Docker images in CircleCI for master/release builds

- e2e/playwright/support/server/default_config.ts
- packages/mattermost-redux/src/selectors/entities/preferences.ts
Cherry pick of #11644 on cloud.
/cc  @mkraft
```release-note
NONE
```
> Automated cherry pick of #11644

- components/cloud_subscribe_result_modal/error.tsx
- components/pricing_modal/content.tsx
The full screen modal's z index is less than that of the non-full-screen modal, so it would appear behind. 
This change makes it so the pricing modal closes. The error modal now accepts a back action prop that, and it's passing the openPricingModal hook, so it re opens when you go back. Finally, clicking the X button in the top right will now completely abort you out of the process (ie, does not reopen the pricing modal)
https://mattermost.atlassian.net/browse/MM-48111
https://www.loom.com/share/ab62fd34d65d4fe09a6cc381976b3d54
```release-note
None
```
> [MM-48111] Downgrade error modal z-index incorrect with single team

- components/advanced_create_comment/advanced_create_comment.tsx
- components/advanced_create_post/advanced_create_post.tsx
- components/drafts/drafts.tsx
- i18n/en.json
- Fixes an issue where sending a message in a comment reply by pressing `Enter` would result in the text box failing to clear. When a message is sent the text box unfocused which automatically triggered a draft save, and so this "new" draft would appear in the text box. This PR adds a flag to only save drafts when not in a submitting state.
- Also fixes an issue where drafts would not update for a thread until you closed and reopened the RHS.
- Changes text on drafts page to use "Any" instead of "All".
- https://mattermost.atlassian.net/browse/MM-48618
- https://mattermost.atlassian.net/browse/MM-48639
```release-note
NONE
```
> [MM-48618, MM-48639] Fix thread replies not clearing text box and not syncing across sessions

- components/permalink_view/permalink_view.tsx
Fixes: Clicking on a reply post time stamp in the global threads inbox opens two RHS
Fixes https://mattermost.atlassian.net/browse/MM-45907
Fixes https://mattermost.atlassian.net/browse/MM-48226
NA
https://user-images.githubusercontent.com/16203333/204783581-2e000149-d94f-4654-b11d-91b3cfb8c688.mov
https://user-images.githubusercontent.com/16203333/204783603-e4f2650f-f844-4c0e-a7b6-3cd013cf2bf0.mov
https://user-images.githubusercontent.com/16203333/204783663-16aa2df9-bd2b-4d9e-839b-b8caa934baed.mov
```release-note
* Fixes: Clicking on a reply post time stamp in the global threads inbox opens two RHS
```
> [MM-45907] Fixes: Clicking on a reply post time stamp in global threads inbox opens two RHS

- components/permalink_view/permalink_view.tsx
Cherry pick of #11679 on cloud.
```release-note
NONE
```
> Automated cherry pick of #11679

- components/sidebar_right/sidebar_right.tsx
Cherry pick of #11689 on release-7.6.
```release-note
NONE
```
> Automated cherry pick of #11689

- components/advanced_create_post/advanced_create_post.test.jsx
- components/advanced_create_post/advanced_create_post.tsx
- components/advanced_create_post/index.ts
Fixes an issue where drafts would save to the wrong channel when switching teams or channels.
- https://mattermost.atlassian.net/browse/MM-48781
- https://mattermost.atlassian.net/browse/MM-48780
- https://mattermost.atlassian.net/browse/MM-48772
```release-note
NONE
```
> [MM-48772] Fix Drafts Save to Wrong Channel

- .github/workflows/performance-benchmarks.yml
When the previous version of this downloaded the web app and server for running benchmarks, it tried downloading a server+webapp bundle from pr-builds.mattermost.com, but that's only available for PR builds and not for the master/release branches. pr-builds does still have the web app code for those branches though (uploaded by the upload-s3 step of the CircleCI flow), so we can use that plus a server build from releases.mattermost.com combined together to run these benchmarks on.
This PR obviously uses the PR flow so it won't exercise the master/release flow, but an earlier version of this pretended to be on master, and you can see that run [here](https://github.com/mattermost/mattermost-webapp/actions/runs/3603560912/jobs/6071906015) where the download step runs through the …
> MM-48688 Add separate benchmark flow for master/release branches

- components/create_team/components/team_url/index.ts
- components/create_team/components/team_url/team_url.test.tsx
- components/create_team/components/team_url/team_url.tsx
Check the right data when checking if team exists to avoid trying to create a team with the same URL.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-42008)
This error message already existed, with translations, so I didn't change it. 
```release-note
NONE
```
> [MM-42008] Fix getting data when checking if team exists

- components/code_block/code_block.tsx
Fixes a bug where pressing "copy" in the context (right-click) menu of a code block always copies the entire block.
https://mattermost.atlassian.net/browse/MM-46415
```release-note
Fixed a bug where selections within a code block were not properly copied to clipboard.
```
> [MM-46415] Code block copy bugfix

- packages/mattermost-redux/src/selectors/entities/threads.ts
Filters out threads with last_reply_at being 0, which is set on threads where all replies have been deleted. This stops them from showing up in all threads (with an awkward date of 1970).
https://mattermost.atlassian.net/browse/MM-47760
A related server change is incoming to address this behaviour when fetching threads as well. This ticket is for cached grabbed threads.
- Has server changes
https://github.com/mattermost/mattermost-server/pull/21702
```release-note
Fixed a bug where threads with 0 replies would show in all threads
```
> [MM-47760] Bugfix: filter out threads with deleted replies

- components/category_menu_items/category_menu_items.tsx
- components/category_menu_items/index.ts
- components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
- components/channel_header_dropdown/channel_header_dropdown_items.tsx
- components/channel_move_to_sub_menu/index.tsx
- components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
Sub menu items of channel move to of channel menu improved for following cases
- when a sub menu is under channel header dropdown, its shows correct categories i.e For DM/GM category "Channel" is not shown and vice versa
- when multiple same dms/gms are selected, Other categories along with "Direct Messages" is shown and not "Channel" category
- when multiple channels non dm/gm are selected, other categories along with "Channel" is shown and "Direct Messages" is not shown.
- when multiple any types of channels which included mix of DM/GM and other are selected, we show other categories but not show either of "Direct messages" nor "Channels"
Reviewing the PR
- [actual code change commit](https://github.com/mattermost/mattermost-webapp/pull/11694/commits/971dd6ea17f52971f064d4f409b4da1d693c0 …
> MM-48609 : channels/DM/GMs  moveTo sub menu options revise

- package-lock.json
- package.json
- webpack.config.js
I added the components package to the package.json to silence the warnings printed by Webpack when we tried to share it via module federation, but because it doesn't exist as a package on NPM, this caused `npm install` to error out for anyone using `mattermost-webapp` as a git dependency.
Since we currently use the web app as a git dependency and we don't use the components package in any products, this seems like the easiest way to fix everyone's issues until we're ready to support the package properly.
```release-note
NONE
```
> Stop exposing components package as a shared module for now

- components/post_view/acknowledgements/post_acknowledgements.tsx
The fallback position for the post acknowledgements users popover should be `bottom-start`, 
so if the popover doesn't fit at `top-start`, it would be placed at bottom`-start`, 
and if it doesn't fit there, or in `right`, it will use the `best-fit` position.
Fixes both RHS, and Center Channel.
https://mattermost.atlassian.net/browse/MM-48773
|----|----|
|![Screenshot 2022-12-03 at 3 20 34 PM](https://user-images.githubusercontent.com/3829551/205442868-1f12056d-086b-44bb-a817-b8cf37d4fa77.png)|![Screenshot 2022-12-03 at 3 20 06 PM](https://user-images.githubusercontent.com/3829551/205442856-48ba06e2-2ee9-46eb-9660-b239aed57289.png)|
```release-note
NONE
```
> MM-48773: fixes position of ACK users popover

- actions/websocket_actions.jsx
When we mark a channel as unread through a post which has mentions in urgent posts, we show briefly the normal badge, and then we show the "urgent" badge, instead of immediately.
It seems that we didn't pass the urgent mention counts upon the websocket event handling for post_unread_event.
This commit fixes that so it shows the urgent badge immediately.
https://mattermost.atlassian.net/browse/MM-48565
```release-note
NONE
```
> MM-48565: fixes delay in channel urgent mention

- packages/mattermost-redux/src/reducers/entities/posts.ts
Currently if a post exists which requested acknowledgements, but no-one has yet to acknowledge, when the first ACK happens it won't display to other users because of a bug.
This commit fixes that bug by returning the correct state shape upon the first ACK.
https://mattermost.atlassian.net/browse/MM-48831
```release-note
NONE
```
> MM-48831: fixes displaying of first acknowledgement

- sass/components/_mentions.scss
Fix to render the strikethrough on at-mentions in posts.
https://mattermost.atlassian.net/browse/MM-48778
Before fix:
After fix (non-hover and hover):
```release-note
Fixed the strikethrough display on at-mentions in posts.
```
> MM-48778: Render strikethrough on at-mentions in posts.

- components/activity_and_insights/insights/top_dms_and_new_members/new_members_item/new_members_item.tsx
Use last_picture_update to get the latest user's picture in insights.
Fixes https://mattermost.atlassian.net/browse/MM-46463
Server: https://github.com/mattermost/mattermost-server/pull/21758
N/A
```release-note
Fixes fetching the latest user's picture in insights.
```
> [MM-46463] Use last_picture_update in insights

- components/post_view/post_time/post_time.tsx
- components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
- components/timestamp/__snapshots__/semantic_time.test.tsx.snap
- components/timestamp/semantic_time.test.tsx
- components/timestamp/semantic_time.tsx
- components/timestamp/timestamp.test.tsx
- components/timestamp/timestamp.tsx
Time stamp announcement shortened (when focused on post time)
fixes https://mattermost.atlassian.net/browse/MM-44864
None
BEFORE -:
https://user-images.githubusercontent.com/89139362/190311992-f4e3101f-54dc-4470-ba34-8ed3d4946b3e.mp4
AFTER -:
https://user-images.githubusercontent.com/89139362/190312031-bb253432-e45f-4d2e-b3cf-fb0cf39e74a0.mp4
NA
```release-note
Time stamp announcement shortened (when focused on post time)
```
> [Mm 44864] Too long time stamp announcement

- components/drafts/drafts.tsx
Cherry pick of #11750 on release-7.6.
```release-note
NONE
```
> Automated cherry pick of #11750

- webpack.config.js
Currently, we assume all production builds of the web app have the available code for Boards included. This will make that optional for people who want to produce production builds without Boards for whatever reason.
https://mattermost.atlassian.net/browse/MM-48905
This'll also have a server component at some point
```release-note
NONE
```
> MM-48905 Add MM_DONT_INCLUDE_PRODUCTS to build web app for production without products included

- components/pricing_modal/content.tsx
- components/purchase_modal/purchase_modal.tsx
- e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js
- i18n/en.json
Fix a few bugs related to the yearly subscriptions.
1. Disable the "Downgrade" button when the user is on a yearly plan. 
|----|----|
| <img width="1438" alt="image" src="https://user-images.githubusercontent.com/44761757/205382606-5c5a16e0-4471-455a-91c2-0bf3145aee73.png"> |<img width="1437" alt="image" src="https://user-images.githubusercontent.com/44761757/205383588-941dad67-3958-46df-9ad4-7c325d052c8b.png"> |
2. When a user is subscribed to the monthly professional plan and opens the purchase modal, hide the yearly/monthly toggle. This ensures that they can't try to subscribe to the monthly professional plan when they are already on that plan.
|----|----|
|<img width="2040" alt="image" …
> [MM-48818]: Fix bugs related to yearly subscriptions

- components/analytics/activated_users_card/index.tsx
- e2e/cypress/tests/integration/enterprise/system_console/reporting/site_statistics_spec.js
- e2e/cypress/tests/integration/system_console/reporting/site_statistics_te_spec.js
- e2e/cypress/tests/integration/system_console/reporting/team_statistics_spec.js
- i18n/en.json
- i18n/en_AU.json
Reverting a text pending legal approval.
Original PR: https://github.com/mattermost/mattermost-webapp/pull/11490
https://mattermost.atlassian.net/browse/MM-48897
Previous change:
This PR reverts back to:
```release-note
NONE
```
> MM-48897: Reverts text change.

- components/logged_in/index.ts
- components/logged_in/logged_in.test.tsx
- components/logged_in/logged_in.tsx
- components/root/root.tsx
This PR moves the OnboardingTaskList component from the root component to the LoggedIn component to make sure that all the requests made from this component are only made once the user has logged in which is where actually makes sense.
https://mattermost.atlassian.net/browse/MM-48824
```release-note
NONE
```
> MM-48824 - move onboarding tasklist to logged in component

- .github/workflows/performance-benchmarks.yml
This is to prevent these tests accidentally timing out on CircleCI. Since we're checking the amount of time taken to run these tests as part of the test, it's okay for us to more or less disable the built-in timeout and instead check for it ourselves.
https://mattermost.atlassian.net/browse/MM-48819
```release-note
NONE
```
> MM-48819 Increase timeout for benchmark tests

- components/activity_and_insights/insights/hooks.ts
- components/activity_and_insights/insights/insights.tsx
- components/activity_and_insights/insights/insights_header/insights_header.scss
- components/activity_and_insights/insights/insights_title/insights_title.tsx
There are instances where no enterprise build is available (Team edition) so we want to hide the team insights dropdown and default to "my insights". To recreate this locally you will need to remove your enterprise repo
https://mattermost.atlassian.net/browse/MM-48987
```release-note
Fixing a bug where the team insights dropdown was available in non-enterprise builds
```
> [MM-48987] Removing team insights if no enterprise build available

- components/sidebar/channel_filter/__snapshots__/channel_filter.test.tsx.snap
- components/sidebar/channel_filter/channel_filter.tsx
- i18n/en.json
Cherry pick of #11641 on release-7.6.
/cc  @babinderrathi
```release-note
NONE
```
> Automated cherry pick of #11641

- components/emoji_picker/emoji_picker_overlay.tsx
- components/emoji_picker/emoji_picker_tabs.tsx
Migrates components/emoji_picker/emoji_picker_tabs to Typescript.
Fixes https://github.com/mattermost/mattermost-server/issues/21059
Jira: https://mattermost.atlassian.net/browse/MM-47111
```release-note
```
> MM-47111 : Migrate "components/emoji_picker/emoji_picker_tabs" to typescript

- components/logged_in/index.ts
- components/logged_in/logged_in.test.tsx
- components/logged_in/logged_in.tsx
This PR removes an unnecessary theme prop from the LoggedIn component that was a leftover from initial changes made on this PR https://github.com/mattermost/mattermost-webapp/pull/11737
https://mattermost.atlassian.net/browse/MM-48824
https://github.com/mattermost/mattermost-webapp/pull/11737
n/a
```release-note
NONE
```
> MM-48824 - remove unnecessary theme prop from LoggedIn Component

- components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
- e2e/cypress/tests/integration/system_console/main_menu_spec.js
Corrected in-product System Console legacy link to point to the current Cloud Administrator's Guide.
```release-note
Corrected in-product System Console legacy link to the Cloud Administrator's Guide.
```
> Updated Cloud admin docs links in-product

- components/app_bar/app_bar.tsx
- utils/constants.tsx
This is another issue with the Boards product. The product ID for Boards changed when it became a product, and because we were looking for the old ID when determining if something should come above or below the divider, it ended up below it.
https://mattermost.atlassian.net/browse/MM-48567
https://github.com/mattermost/mattermost-webapp/pull/11800
```release-note
Fixed position of Boards icon in app bar when Boards is running without a plugin
```
> MM-48567 Fix Boards button in app bar appearing below divider

- components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.test.tsx
- components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
- components/new_channel_modal/new_channel_modal.tsx
- components/new_channel_modal/selectors.ts
- e2e/cypress/tests/integration/channel/new_channel_with_board_spec.js
- packages/client/src/client4.ts
- plugins/products.test.ts
- plugins/products.ts
The feature to make a board for a new channel is currently broken in MPA because:
1. The code that checks if Boards is enabled and is the correct version doesn't work with the Boards product
2. That code calls the Boards API directly, and that didn't support the fact that Boards routes are different in MPA
This fixes those, and it also fixes the accompanying E2E test (MM-T5141)
https://mattermost.atlassian.net/browse/MM-48567
https://mattermost.atlassian.net/browse/MM-47938
```release-note
Fixed ability to create a board when Boards is running without a plugin
```
> MM-48567 Fix Client4 and ability to create a board with a channel in MPA

- components/suggestion/at_mention_provider/at_mention_suggestion.tsx
- i18n/en.json
- sass/components/_suggestion-list.scss
Added a badge with group members count. Also fixed the spacing between username and name.
https://mattermost.atlassian.net/browse/MM-44348
|----|----|
| <img width="600" alt="image" src="https://user-images.githubusercontent.com/684680/205632121-13175b9a-956a-489c-862b-bf7db0baeae6.png"> | <img width="591" alt="image" src="https://user-images.githubusercontent.com/684680/205631721-f873396c-d6c6-4f4e-ab30-cb9ba2e11e87.png"> |
```release-note
Added group members count in autocomplete
```
> [MM-44348] Show number of group members in group autocomplete

- components/integrations/__snapshots__/abstract_command.test.jsx.snap
- components/integrations/abstract_command.jsx
- i18n/en.json
- i18n/en_AU.json
Changed slash command description help text
https://mattermost.atlassian.net/browse/MM-47634
The description text has been changed from "Describe your incoming webhook." to "Describe your slash command."
```release-note
Fixed the slash command description help text
```
> [MM-47634] Changed slash command description text

- components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_base_channel/__snapshots__/sidebar_base_channel.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
- components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
- components/sidebar/sidebar_channel/sidebar_channel.tsx
- components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
- components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
- components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
- components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
- components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
- components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap
- components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx
- components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
- components/sidebar/sidebar_channel/sidebar_group_channel/sidebar_group_channel.tsx
`isCollapsed` prop was passed down in sidebarChannelLink for the sole reason of checking tabIndex on the collapsed channel link. But with https://github.com/mattermost/mattermost-webapp/pull/9732 pr we dont render the collapsed channels anymore, making this check redundant.
https://mattermost.atlassian.net/browse/MM-48895
n/a
n/a
```release-note
NONE
```
> MM-48895 : Remove tab index on collapsed channel link in sidebar

- components/threading/common/button/button.scss
- components/threading/common/button/button.tsx
- components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
- components/threading/global_threads/thread_item/thread_item.tsx
- components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
- components/threading/global_threads/thread_list/thread_list.tsx
- components/threading/global_threads/thread_pane/__snapshots__/thread_pane.test.tsx.snap
- components/threading/global_threads/thread_pane/thread_pane.tsx
fix icons alignment in global threads
Fixes: https://github.com/mattermost/mattermost-server/issues/21402
JIRA: https://mattermost.atlassian.net/browse/MM-47561
None
None
```release-note
NONE
```
> MM-47561 : fix icons alignment in global threads

- components/user_group_popover/group_member_list/group_member_list.tsx
- components/user_group_popover/group_member_list/index.ts
- packages/client/src/client4.ts
- packages/mattermost-redux/src/actions/users.ts
- packages/mattermost-redux/src/selectors/entities/users.ts
Use new display name parameter to fetch users in group, so that they are loaded in order of display name.
Intended to be used for this feature: [Jira ticket](https://mattermost.atlassian.net/browse/MM-44347)
Requires https://github.com/mattermost/mattermost-server/pull/21775
```release-note
NONE
```
> [MM-44347] Use new display name parameter to fetch users in group

- components/self_hosted_purchase_modal/index.test.tsx
- components/self_hosted_purchase_modal/index.tsx
While tweaking the self-hosted purchase flow, I discovered that if CWS sends license successfully but mattermost-server fails to apply it (I originally was creating a license with no seats on accident), we would show both the success screen and the failure screen at the same time because of how. We are unlikely to see this happen in production, but should cover the case nonetheless.
https://mattermost.atlassian.net/browse/MM-47423
N/A
N/A
```release-note
NONE
```
> do not show two screens at once

- components/admin_console/billing/billing_subscriptions/cloud_trial_banner.tsx
- components/pricing_modal/contact_sales_cta.tsx
- components/pricing_modal/content.tsx
Pre-fill the contact us form when the admin click `Contact Sales` on upgrade enterprise.
https://mattermost.atlassian.net/jira/software/c/projects/MM/boards/106?modal=detail&selectedIssue=MM-41722&assignee=62ed333d48e310e672967cc8
Pre-trial pricing modal clicking contact sales
Post-trial pricing modal clicking contact sales
```release-note
Bug fix where clicking contact sales hasn't prefilled the reason of contact to sales.
```
> [MM-41722] Add the upgrade enterprise sales reason

- components/apps_form/apps_form_component.scss
This PR fixes an issue with the background color of the loading spinner when an Apps form is refreshing. The color was hardcoded to white, which didn't look right on dark mode. Light mode themes are essentially unchanged. More context here https://mattermost.atlassian.net/browse/MM-49184
Fixes https://mattermost.atlassian.net/browse/MM-49184
Before
After
```release-note
NONE
```
> Fix Apps form loading background color

- components/announcement_bar/announcement_bar_controller.tsx
- components/announcement_bar/show_start_trial_modal/show_start_trial_modal.tsx
- components/system_notice/system_notice.tsx
This PR makes sure that the show start trial modal only calls the analytics endpoint when the user is an admin user.
https://mattermost.atlassian.net/browse/MM-48456
```release-note
NONE
```
> MM-48456 - restrict analytics call to only admins

- components/common/hooks/useControlSelfHostedPurchaseModal.ts
- components/pricing_modal/self_hosted_content.tsx
We should wait to close the pricing modal until the purchase modal is ready to open. When using a local license generator, getting the bootstrap license was very quick. Using a real license generator, its a little longer, on the order of 1.5 seconds, which is too long to close the modal and wait to open the other one. This should be cherry-picked to release-7.7 so that admins trying to purchase in-app have a less distracting experience.
https://mattermost.atlassian.net/browse/MM-49258
```release-note
NONE
```
> close pricing modal when purchase modal is ready to open

- components/notify_confirm_modal.tsx
- i18n/en.json
Updated in-product confirmation modal for `@here` mentions to clarify that people & timezone counts don't include the current user.  
Fixes https://mattermost.atlassian.net/browse/MM-48777
```release-note
Updated in-product confirmation modal for `@here` mentions to clarify that people & timezone counts don't include the current user.  
```
@fmartingr @mkraft - There's a second product string (id: `notify_here.question`) that's identical to this string (id: `notify_here.question_timezone`) that's missing the timezone count. Is this second string calculated the same way such that it would also benefit from the addition of the word "other"?
> Clarified string impact for the user

- components/global_header/right_controls/plan_upgrade_button/index.tsx
- e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js
Previously, when a user clicks on the "View Plans" button in the header followed by the "Upgrade" button in the Pricing modal, the tooltip from the "View Plans" button shows up on the Purchases modal. 
The new change stops this behaviour. The tooltip will only show up when a user hovers over the "View Plans" button in the header and it will not show up in the Purchases modal. 
https://mattermost.atlassian.net/browse/MM-49232
|----|----|
| ![image](https://user-images.githubusercontent.com/44761757/208747656-72b7362e-5e8d-4de4-a54e-85dc05f6d1f1.png)| <img alt="image" src="https://user-images.githubusercontent.com/44761757/208747739-760d6d95-e00e-4b0b-a938-f99bde3c843a.png">| …
> [MM-49232]: Prevent the "view Plans" tooltip from showing on the Purchases modal

- components/advanced_create_comment/advanced_create_comment.test.jsx
- components/advanced_create_comment/advanced_create_comment.tsx
Fixed thread drafts not syncing to server when RHS is unmounted
https://mattermost.atlassian.net/browse/MM-49061
- This should be merged after https://github.com/mattermost/mattermost-webapp/pull/11733.
```release-note
NONE
```
> [MM-49061] Fix Thread Drafts not Updating on Team Switch

- actions/notification_actions.jsx
Increased the max text notification length on Windows to 120. This value was chosen because Chrome on Windows supports 128 max length, and other browsers support higher. I opted to keep it a bit under the lowest value to accommodate all potential browsers with lower complexity.
fixes https://mattermost.atlassian.net/browse/MM-48799
```release-note
Increased notification length on Windows to 120 from 50.
```
> [MM-48799] - Adjusted windows text notification length

- e2e/cypress/tests/integration/accessibility/accessibility_account_settings_spec.js
- e2e/cypress/tests/integration/enterprise/accessibility/accessibility_input_fields_spec.js
- e2e/cypress/tests/integration/notifications/channel_links_show_as_links_spec.js
- e2e/cypress/tests/support/ui/account_settings_modal.js
- e2e/cypress/tests/support/ui/global_header.js
Conversation here https://community.mattermost.com/core/pl/9s4rk93kkbfb7dr54u3utsxp8h
https://mattermost.atlassian.net/browse/MM-49414
n/a
n/a
```release-note
NONE
```
> MM-49414 : Fix failing e2e due to recent a11y changes

- components/air_gapped_self_hosted_purchase_modal/content.scss
CSS leaking from another file was causing the misalignment. Make the selector a bit more targeted to fix that.
https://mattermost.atlassian.net/browse/MM-49358
N/A
|----|----|
| ![before](https://user-images.githubusercontent.com/684680/209840120-70f8ddc4-1b17-4a1b-816c-23954d9cd479.png) | ![after](https://user-images.githubusercontent.com/684680/209840073-8084dad6-a805-4f42-a23a-2232b988a2f4.png) |
```release-note
NONE
```
> [MM-49358] Fix alignment HFT routes

- components/onboarding_tasklist/onboarding_tasklist.tsx
When you try to setup Multi Factor Authentication for a user the page gets stuck in an infinite loop of network requests to the `savePreferences` endpoint. Since technically you aren't fully logged in until MFA is setup, that endpoint repeatedly returns a 403. 
The problem is that when `savePreferences` fails, it calls a reducer (PreferenceTypes.DELETED_PREFERENCES) that updates state  and that cascades back down to the onboarding tasklist component causing the `firstTimeOnboarding` selector to recalculate which in turn causes the `savePreferences` endpoint to be called again, and again, and again...
Removing `firstTimeOnboarding` as a dependency in the useEffect fixes the issue. I'm under the opinion that network call should only run on page load?
I've done some testing and I don't see …
> [MM-49483] Failing preferences request causes infinite loop in onboarding tasklist

- e2e/cypress/tests/integration/integrations/incoming_webhook/invalid_attachment_URL_webhook_spec.ts
This test verifies that viewing an attachment with an invalid URL does not cause the application to crash. However, the steps in the test are a bit different from the ones outlined in: https://github.com/mattermost/mattermost-server/issues/18181.  For one, there was no need to "edit a webhook already created", and the test data is slightly different.
Web-app E2E test with Cypress for: https://github.com/mattermost/mattermost-server/issues/18181
N/A as of now.
N/A
```release-note
NONE
```
> MM-T624 Viewing attachments with invalid URL

- components/post_priority/post_priority_picker_item.tsx
For some reason when Boards Product is enabled, and the .Menu CSS class is overwritten by it, the ordering of classes in Safari is reversed than in Firefox which makes the post priority picker not to be visible.
This commit fixes that by bumping the styled components rule's specificity.
See https://styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity
https://mattermost.atlassian.net/browse/MM-49487
```release-note
NONE
```
> MM-49487: fixes post priority picker in safari

- webpack.config.js
Since we accidentally cached these files previously, a few people on community have incorrectly cached versions of those files still in their browser cache which causes them to see outdated parts of the web app or get errors because their browser tried to load the now-missing versions of those files. Adding a query parameter to give each version of those files a unique URL should be enough to fix that without requiring us to give them unique file names like other JS files because that would make it difficult for the web app to know where to find Boards's remote entrypoint
https://mattermost.atlassian.net/browse/MM-47938
```release-note
Ensured that remote_entry.js files aren't cached
```
> MM-49563 Append query parameter to remote_entry.js files to fix bad caching on community

- e2e/cypress/tests/integration/channel/new_channel_with_board_spec.js
- e2e/playwright/support/server/default_config.ts
This test is still failing on nightly builds, and I think it might be because the feature flag is missing for this. Since the feature flag is now on-by-default on master, that should be fixed for us, but I wanted to be extra sure so I changed the test to fail if it's not enabled.
https://mattermost.atlassian.net/browse/MM-47938
```release-note
NONE
```
> MM-47938 Ensure feature flag is set before running E2E test

- components/forward_post_modal/forward_post_modal.scss
- components/move_thread_modal/move_thread_modal.tsx
Fixes the move thread modal-body scroll bar appearing when opening the picklist. All options of picklist are now visible
https://mattermost.atlassian.net/browse/MM-48394
```release-note
NONE
```
> [MM-48394] Wrangler UI/UX tweaks 

- e2e/cypress/cypress.config.ts
This environment variable is normally for setting the Site URL on the server, but we also use it in a few places like the web app's webpack.config.js when setting up some subpath stuff
```release-note
NONE
```
> Have Cypress use custom site URL if set

- components/threading/global_threads/thread_item/index.ts
When the user is a guest and removed, while being on that page there weren't any post information until the redirect so it would throw an error.
https://mattermost.atlassian.net/browse/MM-48290
N/A
N/A
```release-note
NONE
```
[MM-48290]: https://mattermost.atlassian.net/browse/MM-48290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-48290] Fix white screen when guest is removed from last channel while on Threads

- components/purchase_modal/icon_message.scss
Some text on the downgrade success and failure screens was not aligned properly.
I mentioned I have this fixed in another PR, but this change alone will get in faster and the ticket will be closed out sooner if the change is in it's own PR.
A really basi change, this just removes the `max-width` style on the `IconMessage-sub` styling. This screen is the only place it's used.
[MM-49615](https://mattermost.atlassian.net/browse/MM-49615)
|----|----|
| ![Screen Shot 2023-01-17 at 2 15 35 PM](https://user-images.githubusercontent.com/116016004/212992318-9ebdb39f-094b-4b07-88e8-26aba085ee71.png) | ![Screen Shot 2023-01-17 at 2 15 47 PM](https://user-images.githubusercontent.com/116016004/212992527-6dfa1d71-f290-4676-b4a3-1f600fe1f476.png) |
| ![Screen Shot 2023-01-17 at 2 …
> MM-49615 - Fix Downgrade Success/Failure Text Alignment

- components/pricing_modal/self_hosted_content.tsx
Self-hosted purchase (for v7.8) when purchase not available, direcly open the customer portal purchase experience. QA deferred to post-merge because we don't yet have a good way to to test this from spinwicks.
https://mattermost.atlassian.net/browse/MM-49771
This is now the experience if CWS reports signup is not available;
https://user-images.githubusercontent.com/13738432/213553508-50608a99-0450-4218-845e-c96d21d28e4e.mp4
```release-note
If self-hosted purchase is not available, go to cws purchase portal experience directly instead of showing air-gapped modal.
```
> Self-hosted purchase not available case (for v7.8)

- actions/telemetry_actions.jsx
The request count for `team_switch` and `channel_switch` events isn't the most accurate, but it currently ignores GraphQL API requests since those are under `/api/v5`, so there's no chance of us seeing any effects of those in Looker
https://mattermost.atlassian.net/browse/MM-49632
```release-note
Correctly count GraphQL APIs when measuring performance telemetry
```
> MM-49632 Correctly count GraphQL requests during performance events

- scripts/dev-server.js
- scripts/run.js
- scripts/utils.js
With the feature flag for this being on-by-default now, it doesn't make sense to require the feature flag be set while developing on the frontend, so now we just start the Focalboard product as long as its found.
I also realized when doing this that Focalboard wasn't run by `make dev` so that's also the case now as well.
https://mattermost.atlassian.net/browse/MM-49714
```release-note
NONE
```
> MM-49714 Start Boards product as long as Focalboard is found

- components/root/root.tsx
This PR fixes an issue causing UTM params to not being sent to rudder.
@stevemudie we might have to defer QA, I don't know how to set rudder in spinwicks (locally I have to  change the code directly)
https://mattermost.atlassian.net/browse/MM-49810
N/A
Visiting http://localhost:8065/login/?utm_source=nurture&utm_medium=email&utm_campaign=cloud-starter-v2
```release-note
NONE
```
> [MM-49810] Fix UTM params not sent to rudder

- components/pricing_modal/content.tsx
- e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.ts
- i18n/en.json
Currently, the downgrade button is grayed out for Cloud Annual Subscriptions as this is not available yet for self-serve. 
We need to update this CTA to Contact Support and open to support form in the portal. 
For monthly subscriptions, it should still have the downgrade option as it does
Issue created from a [message in Mattermost](https://community.mattermost.com/private-core/pl/wgochxkd7jnetxzy9sskz8swnw).
[MM-49617](https://mattermost.atlassian.net/browse/MM-49617)
|----|----|
| ![Screen Shot 2023-01-17 at 3 30 41 PM](https://user-images.githubusercontent.com/116016004/213006857-008c37fc-f109-44b6-aa16-fd0e6a73ef7d.png) | ![Screen Shot 2023-01-17 at 3 29 10 PM](https://user-images.githubusercontent.com/116016004/213006896-24fbbd7d-a2b6-463c-a99f-ba9bc5db08c8.png) …
> MM-49617 - Add Contact Support CTA for Downgrade to Starter if the Current Subscription is Yearly

- .github/workflows/performance-benchmarks.yml
I've made it so that we're also uploading the MM server logs, screenshots from Cypress of failures, and videos of all Cypress runs to the build artifacts to help debugging performance issues that cause the CircleCI job to fail
```release-note
NONE
```
> Add additional debugging information to benchmark tests

- .github/workflows/performance-benchmarks.yml
- e2e/cypress/tests/integration/performance/team_switch_spec.js
Temporarily increase the team switch performance benchmark test until we figure out the reason for the failures or issues with github actions
```release-note
NONE
```
> Temporarily increase team switch benchmark

- actions/marketplace.ts
- components/work_templates/index.tsx
- packages/client/src/client4.ts
This PR uses the marketplace listing new flag `?remote_only=true` to allow users to get public plugin info. Without this being on, non admins would not be able to see public plugins info at all.
QA @ server side PR
https://mattermost.atlassian.net/browse/MM-49929
- Has server changes https://github.com/mattermost/mattermost-server/pull/22151
N/A
```release-note
NONE
```
> [MM-49929] Work templates: allow simple users to list marketplace plugins

- components/work_templates/components/customize.tsx
- components/work_templates/index.tsx
- i18n/en.json
Block the "Private" button if the template contains a playbook and the server license is not E20 or Enterprise.
Also, the design has this selector showing the buttons side-by-side (they were on top of each other so far), so I changed the UI to match what is on figma.
- On a new server with no license
- Open work templates
- Go to the last page of the first template
- the private button is disabled and has a tooltip explaining that you need an enterprise license
- Upload an enterprise license (or start a trial)
- Open work templates
- Go to the last page of the first template
- the private button is available.
https://mattermost.atlassian.net/browse/MM-50007
```release-note
NONE
```
> [MM-50007] WorkTemplate: disable "private" button when a template contains a playbook without an enterprise license

- components/analytics/true_up_review.tsx
- i18n/en.json
- utils/constants.tsx
The True Up Review panel in the system console had no information or instruction on how to perform a quarterly true-up review.
Figma: https://www.figma.com/file/1qWr4RtBjwQZyGQMT7z9Jp/True-Up-Review?node-id=503%3A38649&t=DdEYP8hX03OTYhdy-0
[MM-50030](https://mattermost.atlassian.net/browse/MM-50030)
[True-Up Review Docs](https://github.com/mattermost/docs/pull/6191)
|----|----|
| ![before](https://user-images.githubusercontent.com/116016004/215187061-c655cfe9-244b-4846-b70f-d73e0fbdec23.png) | ![after](https://user-images.githubusercontent.com/116016004/215186892-286567cd-b798-49c3-b041-2cb4eb024d9e.png) |
```release-note
NONE
```
[MM-50030]: https://mattermost.atlassian.net/browse/MM-50030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
> Add link to true-up review documentation

- components/add_user_to_channel_modal/add_user_to_channel_modal.tsx
- components/admin_console/file_upload_setting.jsx
- components/admin_console/license_settings/license_settings.tsx
- components/admin_console/manage_roles_modal/manage_roles_modal.tsx
- components/admin_console/password_settings.jsx
- components/admin_console/plugin_management/plugin_management.tsx
- components/admin_console/push_settings.jsx
- components/admin_console/schema_admin_settings.jsx
- components/admin_console/system_user_detail/system_user_detail.tsx
- components/analytics/doughnut_chart.tsx
- components/analytics/line_chart.tsx
- components/channel_notifications_modal/channel_notifications_modal.tsx
- components/create_team/components/display_name.tsx
- components/create_team/components/team_url/team_url.tsx
- components/file_preview/file_preview.tsx
- components/file_preview_modal/popover_bar/popover_bar.tsx
- components/multiselect/multiselect_list.tsx
- components/post_view/embedded_bindings/embedded_binding/embedded_binding.tsx
- components/post_view/message_attachments/message_attachment/message_attachment.tsx
- components/post_view/reaction_list/reaction_list.tsx
- components/post_view/show_more/show_more.tsx
- components/searchable_channel_list.jsx
- components/team_general_tab/team_general_tab.tsx
- components/user_settings/advanced/user_settings_advanced.tsx
- components/user_settings/display/user_settings_display.tsx
- components/user_settings/general/user_settings_general.tsx
- components/user_settings/security/user_access_token_section/user_access_token_section.tsx
We had an old campaign to remove all usage of string refs from the app. That was almost entirely done, but we never went back and removed the exceptions from files that would stop ESLint from erroring out on files that hadn't been cleaned up yet. This does that
https://mattermost.atlassian.net/browse/MM-26304
```release-note
NONE
```
> Removed unused eslint-disables for no-string-refs

- components/drafts/panel/panel_header.scss
Adds spacing between the timestamp and draft tag on the drafts page.
https://mattermost.atlassian.net/browse/MM-49974
```release-note
NONE
```
> [MM-49974] Fix Spacing Between Timestamp and Draft Tag

- packages/client/src/client4.ts
- packages/mattermost-redux/src/action_types/apps.ts
- packages/mattermost-redux/src/actions/apps.ts
- packages/mattermost-redux/src/constants/apps.ts
- packages/mattermost-redux/src/reducers/entities/apps.ts
- packages/mattermost-redux/src/selectors/entities/apps.ts
- packages/mattermost-redux/src/utils/marketplace.ts
- packages/types/src/apps.ts
- packages/types/src/marketplace.ts
Apps are no longer marked as experimental. The codebase should reflect that.
https://mattermost.atlassian.net/browse/MM-50059
```release-note
NONE
```
> [MM-50059] Remove experimental warning about apps

- actions/views/channel.test.js
- actions/views/channel.ts
- components/work_templates/index.tsx
Sometimes we try to redirect the user to a newly created channel before the webapp is aware of it (websocket not processed yet). To fix this I added a method that will load the channel using the API if it's not already loaded before switching to the channel.
I did not change the existing method for BC reasons.
For QA it might get difficult, knowing that it was happening fairly rarely and there was not way to reproduce 100%. So I can try to create a bunch and make sure you are redirect to a new channel every time? 😓
https://mattermost.atlassian.net/browse/MM-50077
N/A
N/A
```release-note
NONE
```
> [MM-50077] Race condition on work template execution

- components/common/hooks/useCanSelfHostedSignup.ts
Cherry-pick of https://mattermost.atlassian.net/browse/MM-50049
```release-note
Team edition workspaces should not try to check if CWS is available.
```
> cherry-pick MM-50049

- components/activity_and_insights/insights/hooks.ts
- components/activity_and_insights/insights/insights.tsx
When you are on free tier the initial load for insights will request from team insights before fixing itself and getting my insights on second render. This fix just pins the filter type to `My insights` in order to avoid the failed requests
https://mattermost.atlassian.net/browse/MM-49943
```release-note
NONE
```
> [MM-49943 ] Fixing initial load for insights types on free tier

- components/product_notices_modal/product_notices_modal.tsx
`currentTeamId` was undefined. I checked the behaviour on previous MM versions and this network request was only supposed to go out on page load (not every team switch)
https://mattermost.atlassian.net/browse/MM-49863
```release-note
Fixing product notices 404
```
> [MM-49863] Check for team Id in product notices

- sass/components/_modal.scss
The modal header was overridden maybe for the early stages of modals but is now unnecessary for maintaining consistency.
https://mattermost.atlassian.net/browse/MM-33593
N/A
|----|----|
| <img width="678" alt="image" src="https://user-images.githubusercontent.com/684680/215471074-a09fd6f1-1805-4931-b9c6-16ae1f656e31.png"> | <img width="678" alt="image" src="https://user-images.githubusercontent.com/684680/215470573-5a6fdd15-8dec-480c-aa54-8ba1085dc925.png"> |
```release-note
NONE
```
> [MM-33593] Inconsistent styling of modal headers in the system console

- actions/command.ts
- i18n/en.json
Adds a `/templates` command to open the modal.
N/A: OSF 
- Has server changes https://github.com/mattermost/mattermost-server/pull/22246
```release-note
NONE
```
> [OSF] Allows opening the work template modal from a slash command

- components/admin_console/billing/company_info_edit.tsx
When editing company information, the standard discard modal is not presented when navigating to another page.
This change ensures the modal appears when any field is modified.
https://mattermost.atlassian.net/browse/MM-38465
1. Go to System Console ➜ Billing & Account ➜ Company Information
2. Add a new address without clicking the Save Info button
3. Click the back arrow to exit
**Expected**: The standard System Console Discard Changes modal prevents me from leaving (see screenshot) 
```release-note
NONE
```
> MM-38465 Add Discard Modal for Company Information Edit

- components/post/post_options.tsx
Bugfix: Don't show the message count for all posts in a thread if CRT is disabled.
Fixes https://mattermost.atlassian.net/browse/MM-50280
NA
|----|----|
| <img width="1060" alt="Screenshot at Feb 02 10-26-02" src="https://user-images.githubusercontent.com/16203333/216920266-33a9e31d-1a2d-4471-80ed-68bf4f7b2339.png"> | <img width="1481" alt="Screenshot 2023-02-06 at 1 50 02 PM" src="https://user-images.githubusercontent.com/16203333/216920233-ea660798-5f45-4e2b-be29-d7b2125a1747.png"> |
```release-note
* Don't show the message count for all posts in a thread if CRT is disabled.
```
> MM-58280: Don't show the message count for all posts in a thread if CRT is disabled.

- utils/message_html_to_component.jsx
A few different Markdown elements such as tables and code blocks sometimes caused React to print warnings about components in an array having duplicated keys. I don't know exactly why these specific elements caused those warnings, but this fixes them at least
```release-note
NONE
```
> Fix React warnings about missing keys for Markdown elements

- components/work_templates/index.tsx
It clears the error message to unblock the create button.
https://mattermost.atlassian.net/browse/MM-50078
```release-note
NONE
```
> MM-50078-unable-to-click-the-create-button-after-fixing-the-name-of-the-work-template

- .circleci/config.yml
I can't remember why I decided in https://github.com/mattermost/mattermost-webapp/pull/11626 to treat all branches named `cloud-*` as release branches for this when the server only treats `cloud` itself that way.
This should fix test servers and performance benchmarks for PRs from branches named starting with `cloud-`
https://github.com/mattermost/mattermost-webapp/pull/11626
```release-note
NONE
```
> Fix Docker images not being built for cloud-* branches

- components/custom_status/custom_status_modal.tsx
- components/forward_post_modal/forward_post_modal.tsx
- components/tours/crt_tour/collapsed_reply_threads_modal/collapsed_reply_threads_modal.tsx
- Added autofocus on custom stautus modal
- Added focustrap in thread intro modal and forward modal
https://mattermost.atlassian.net/browse/MM-50323
n/a
n/a
```release-note
NONE
```
> MM-50323 : Autofocus on custom status modal on open

- components/work_templates/components/customize.tsx
Limit max length for the name field
QA: the name field will prevent your from typing more than 64 characters.
https://mattermost.atlassian.net/browse/MM-50080
- [Has server changes](https://github.com/mattermost/mattermost-server/pull/22282)
N/A
```release-note
NONE
```
> [MM-50080] Limit max length for the name field

- e2e/cypress/tests/integration/system_console/workspace_deletion_spec.js
Disabling tests for time being until few more changes get merged.
PR: https://github.com/mattermost/mattermost-webapp/pull/12077
pending code changes in CWS and enterprise repo need to be merged for the tests to pass. 
[pr-customer-web-server-1083](https://github.com/mattermost/customer-web-server/pull/1083)
[pr-mattermost-server-22200](https://github.com/mattermost/mattermost-server/pull/22200)
[pr-enterprise-1377](https://github.com/mattermost/enterprise/pull/1377)
```release-note
NONE
```
> chore(cypress): demote workspace_deletion_spec test

- utils/constants.tsx
The internal name that highlight.js uses for C# is `csharp`, not `cs`, so while we recognized C# in the code block, we weren't telling highlight.js what it needed to do syntax highlighting
Before | After
-|-
```release-note
Fixed C# syntax highlighting not working
```
> Fix C# syntax highlighting

- sass/components/_post.scss
https://caniuse.com/?search=mask-image is very noncommittal about whether or not a prefix is needed for this property in Chrome
https://mattermost.atlassian.net/browse/MM-50506
https://github.com/mattermost/mattermost-webapp/pull/12086
```release-note
Fixed new collapsed post fade out being broken on Chrome and Desktop
```
> MM-50506 Add -webkit-mask-image to support Chrome and Electron

- components/analytics/true_up_review.tsx
- i18n/en.json
We need to add links to true-up documentation in other areas that mention true-up. This has already been done, but the wording has changed _slightly_ from:
`Learn more about true-up here.` to `Learn more about true-up.`
[MM-50226](https://mattermost.atlassian.net/browse/MM-50226)
|----|----|
| ![Screen Shot 2023-02-14 at 3 24 51 PM](https://user-images.githubusercontent.com/116016004/218853910-ec0d332f-e9ac-4d8d-8174-51bce4dbb06d.png) | ![Screen Shot 2023-02-14 at 3 25 37 PM](https://user-images.githubusercontent.com/116016004/218854029-1b4c5b1f-a719-46af-9b2c-0541665986fe.png) |
```release-note
NONE
```
[MM-50226]: https://mattermost.atlassian.net/browse/MM-50226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM-50226 Remove 'here' from the true-up docs link.

- .github/workflows/performance-benchmarks.yml
We may fail to hit performance targets when running Performance benchmarks under the default GitHub runners with 2 CPU Cores.
Example:
https://github.com/mattermost/mattermost-webapp/actions/runs/4191515787/jobs/7266161637
We bump-up the GhRunners for this step to align with requirements
Ticket: https://mattermost.atlassian.net/browse/CLD-5125
> [CLD-5125] CI Bump-Up runners for Performance Testing

- components/file_preview_modal/__snapshots__/file_preview_modal.test.tsx.snap
- components/file_preview_modal/file_preview_modal.tsx
- types/store/plugins.ts
In order for plugins to have the freedom to close the file preview modal, we need to provide a prop to call that does this. https://github.com/mattermost/mattermost-webapp/pull/5430 added this prop but it seems it was removed in a refactor. The file was not typescript'd back then so it makes sense.
This PR adds this prop back into the component.
This can be tested with https://github.com/mattermost/mattermost-plugin-demo/pull/105
Fixes https://mattermost.atlassian.net/browse/MM-24763 again. I've reopened the issue but can create another if necessary.
- https://github.com/mattermost/mattermost-webapp/pull/5430
- https://github.com/mattermost/mattermost-plugin-demo/pull/105
```release-note
NONE
```
> Add onModalDismissed to plugin file preview

- .github/workflows/performance-benchmarks.yml
We better size the performance benchmarks instances used for CI, downsizing from 8-core to 4-core.
Builds on: https://github.com/mattermost/mattermost-webapp/pull/12215
Commit: c4c992a2cd309e1f3c3a21e23ffa041732b59e28
https://mattermost.atlassian.net/browse/CLD-5125
> [CLD-5125] CI Revisit performance benchs sizing

- components/admin_console/billing/billing_subscriptions/index.tsx
- e2e/cypress/tests/integration/system_console/workspace_deletion_spec.js
I noticed today that for the Delete Workspace flow, if you're on an enterprise monthly subscription, the CTA to contact support (rather than the CTA to delete the workspace) was no longer present when it should be.
This PR updates the condition for displaying either CTA to take into account that enterprise should never see the delete workspace CTA and should always see the contact support CTA (with the cancel subscription title) regardless of it's recurring interval being monthly or yearly.
[MM-50572](https://mattermost.atlassian.net/browse/MM-50572)
https://github.com/mattermost/mattermost-webapp/pull/12077
|----|----|
| ![Screen Shot 2023-02-16 at 11 56 33 AM](https://user-images.githubusercontent.com/116016004/219434524-a50ce088-0766-43c0-b873-19caf23fdc52.png) | …
> MM-50572 - Allow Enterprise-Monthly to See Contact Support CTA Rather Than a Blank Section

- actions/cloud.tsx
- components/purchase_modal/index.ts
Cloud export compliance introduced a [better return type](https://github.com/mattermost/mattermost-webapp/pull/12102/files#diff-e7ad3697a6a81325213114b2cb24bbb12e5c71b9a489b1191fdd067f12d19e86R92-R105) for `subscribeCloudSubscription` but the corresponding callers needed updating. Reverting the return type to a simple `true` until we fix this all the way.
https://mattermost.atlassian.net/browse/MM-50723
Issue this fixes is not yet released to prod, so no release note.
```release-note
NONE
```
> MM-50723 quick fix for subscribing to a cloud product so that successes display as successes.

- packages/mattermost-redux/src/selectors/entities/channels.test.ts
- packages/mattermost-redux/src/selectors/entities/channels.ts
Remove mention counts of muted channels on the browser and desktop tabs
Fixes https://github.com/mattermost/mattermost-server/issues/21229
Fixes https://mattermost.atlassian.net/browse/MM-47369
NA
https://user-images.githubusercontent.com/16203333/195066884-84e7382a-7545-4452-a36e-82abc958c8b9.mov
```release-note
NONE
```
> [MM-47369] Remove mention counts of muted channels on the browser and desktop tabs

- actions/websocket_actions.jsx
- actions/websocket_actions.test.jsx
- components/team_controller/team_controller.tsx
- packages/client/src/websocket.ts
We're currently adding duplicated `reconnect` handlers every single time the WebSocket is re-initialized because we don't clean up the listeners we use when the WebSocket connection is closed. This hasn't been noticeable with other WebSocket event listeners because we're always registering the same listener and the `WebSocketClient` uses a Set which de-dupes that automatically, but because the `reconnect` handler used an arrow function previously, that'd lead us to register multiple copies of the same handler.
Because of that, we'd sometimes fire off multiple copies of the `reconnect` handler when the websocket reconnects which is a very heavy operation.
This fixes that issue by:
1. Not using an arrow function so that the underlying Set would de-duplicate that listener for us
2. Cleaning …
> MM-50573 Clean up WebSocket listeners when connection is closed

- components/common/hooks/useGetLimits.ts
- packages/mattermost-redux/src/reducers/entities/cloud.test.ts
- packages/mattermost-redux/src/reducers/entities/cloud.ts
Couldn't think of how else to meet all the concerns in the original MM-50233 PR until I tried to fix it myself. Conerns I see:
* We don't want every inital use of the hook to trigger a request, because this is used in so many places.
* The subscription update process should already transparently update the limits, but it seems this isn't occurring in some scenarios. We keep trying to ensure the limits get proactively updated, but it we keep running into cases where it doesn't, hence this ticket.
By clearing the reducer and resetting the state within the hook, existing hook usages will retrigger the request. By keeping the existing "data already requested" and "data already received checks, we prevent overrequesting of this data for first time renders of the hook. …
> clear limits on subscription change

- components/common/hooks/useGetLimits.ts
- packages/mattermost-redux/src/reducers/entities/cloud.test.ts
- packages/mattermost-redux/src/reducers/entities/cloud.ts
cc @amyblais , @AGMETEOR 
```release-note
Limits are cleared and reloaded on subscription change.
```
> clear limits on subscription change (#12244)

- components/purchase_modal/process_payment_setup.tsx
- components/purchase_modal/purchase_modal.tsx
- i18n/en.json
When changing from a monthly-based payment interval to an annual-based, upon success, users would see the following success screen:
This change updates the wording on this success screen, specifically for subscription changes which involve updating the payment interval from monthly to annual.
[MM-50238](https://mattermost.atlassian.net/browse/MM-50238)
|----|----|
| ![image](https://user-images.githubusercontent.com/116016004/219779553-cfdb1472-b1de-44d8-87dc-9a6f5cbf8864.png) | ![Screen Shot 2023-02-17 at 4 47 38 PM](https://user-images.githubusercontent.com/116016004/219800102-27e81a22-18a4-4827-825f-87871134c99a.png) |
```release-note
NONE
```
[MM-50238]: https://mattermost.atlassian.net/browse/MM-50238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> MM-50238 - Add a Success Page for Changes to Annual Subscriptions.

- scripts/runner.js
I left `make run` running for a few days straight with the fancy runner enabled, and it managed to start lagging because of how much output it had saved up
```release-note
NONE
```
> Add a limit of 5000 lines to the web app runner

- .github/workflows/ci.yml
We noticed that Spinwick environments were failing to start due to some change on the way we build docker images . 
Spinwick is using an old registry client and it had some strange errors with the manifests generated by buildx 
```
OCI index found, but accept header does not support OCI indexe
```
By disabling provenance we resolve this issue as we do not need it since we do not build for multi platform . 
https://github.com/mattermost/mattermost-webapp/pull/12007
https://github.com/mattermost/mattermost-webapp/pull/12261
> hotfix(ci): Fix docker image build for Spinwick environments

- webpack.config.js
I also added `styled-components` to the shared packages since it was missing previously
https://mattermost.atlassian.net/browse/MM-50818
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1826
https://github.com/mattermost/focalboard/pull/4605
```release-note
NONE
```
> MM-50818 Add more comments to explain how shared modules are configured

- package-lock.json
- package.json
- packages/client/package.json
- packages/types/package.json
I keep forgetting to update these on master before a release branch is cut. They don't really matter until I go to cut the release (like I just did for 7.8), but it saves me from having to push the release branch directly
```release-note
NONE
```
> Update subpackage versions to 7.9.0

- components/widgets/inputs/users_emails_input.test.tsx
- components/widgets/inputs/users_emails_input.tsx
The input was so tiny that you could not right-click into it. It's not perfect, as it's not expanded vertically, but it's better now.
https://mattermost.atlassian.net/browse/MM-50229
N/A
**Before**
https://user-images.githubusercontent.com/684680/217881062-390a52af-bcf5-45fb-b319-e185fdbcce5a.mp4
**After**
https://user-images.githubusercontent.com/684680/217881093-08c9f307-e76b-4f54-9af2-5476b83503bc.mp4
```release-note
NONE
```
> [MM-50229] Fix right-click paste for user invites

- components/common/hooks/useGetUsageDeltas.test.ts
- components/common/hooks/useGetUsageDeltas.ts
Fix selector. Because limits were getting loaded more than once, when they got cleared, the usage existed, but the limits did not, and the backup value getting picked was 0, when it should have been max number (assumed no limit if we have not yet loaded a limit).
https://mattermost.atlassian.net/browse/MM-51000
https://user-images.githubusercontent.com/13738432/222208409-4070fdf0-6266-41b9-98b6-f481ab2d6cbd.mp4
```release-note
Fix issue where cloud limits would briefly flash in system console before disappearing.
```
> MM-51000 fix withBackupValue

- components/dot_menu/post_reminder_submenu.tsx
- components/post_markdown/index.ts
- components/post_markdown/post_markdown.tsx
- components/post_markdown/system_message_helpers.tsx
- components/status_dropdown/status_dropdown.tsx
fix post reminder timezone, DND submenu and post reminder ephemeral message not to respecting user set timezone
Fixes https://mattermost.atlassian.net/browse/MM-51032
NA
```release-note
* fix post reminder timezone, DND submenu and post reminder ephemeral message not to respecting user set timezone
```
> [MM-51032]: fix post reminder timezone, DND submenu and post reminder ephemeral message not to respecting user set timezone

- sass/components/_post.scss
The styling for a new modal introduced in https://github.com/mattermost/mattermost-webapp/pull/11069 were actually applying to a bunch of other modals
Before: 
After: 
https://mattermost.atlassian.net/browse/MM-50803
```release-note
NONE
```
> MM-50803 Fix restore post modal styles applying to other modals

- sass/components/_post.scss
After we've [unified the post components](https://github.com/mattermost/mattermost-webapp/pull/11127), the `.post--hovered` is now being attached. This triggers overflow to be visible, which looks like isn't needed. @nevyangelova Maybe you have a better context if this is required somewhere?
https://mattermost.atlassian.net/browse/MM-51008
N/A
N/A
```release-note
NONE
```
> [MM-51008] Fix RHS search result hover for larger text

- actions/channel_queries.ts
Increase members count per page in gql from 60 to 200
https://mattermost.atlassian.net/browse/MM-51242
n/a
n/a
```release-note
NONE
```
> MM-51242 : Increase member per page count to 200 in gQL

- e2e/playwright/support/server/client.ts
Currently the helper function available for Playwright tests `uploadPluginX` is appending the file contents using the form data name `license` instead of `plugin`. This PR makes it so it uses the correct name.
```release-note
```
> Fix typo in e2e test helper function uploadPluginX

- actions/global_actions.tsx
- actions/views/rhs.ts
- components/channel_info_rhs/channel_info_rhs.test.tsx
- components/channel_info_rhs/channel_info_rhs.tsx
- components/channel_info_rhs/index.ts
- components/channel_info_rhs/menu.test.tsx
- components/channel_info_rhs/menu.tsx
- packages/client/src/client4.ts
- packages/mattermost-redux/src/actions/channels.ts
Exclude file count on channel stats API call on from channel header.
cherry-pick for https://github.com/mattermost/mattermost-webapp/pull/12245
Fixes https://mattermost.atlassian.net/browse/MM-49090
- Has server changes (Merged) https://github.com/mattermost/mattermost-server/pull/22096
```release-note
* Exclude file count on channel stats api call on from channel header.
```
>  [MM-49090]: Exclude file count on channel stats api call on from channel header
