mattermost/mattermost-webapp

components/create_post/prewritten_chips.tsx, components/next_steps_view/next_steps_view.test.tsx, components/next_steps_view/next_steps_view.tsx, components/next_steps_view/steps.ts, i18n/en.json
Fix translation strings for onboarding.
https://mattermost.atlassian.net/browse/MM-38659
```release-note
Fix onboarding translation strings.
```
=> fix notifications translations

components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap, components/next_steps_view/next_steps_tips.tsx, components/next_steps_view/next_steps_view.tsx, i18n/en.json
Cherry pick of #8903 on release-6.0.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #8903

components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap, components/widgets/menu/menu_items/menu_item.test.tsx, components/widgets/menu/menu_items/menu_item.tsx, components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx, components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx, selectors/views/modals.js
this PR fixes several console errors that came up due to a false setting of props within the `Menu.ItemToggleModalRedux` component
[MM-38469](https://mattermost.atlassian.net/browse/MM-38469)
```release-note
NONE
```
=> [MM-38469] - fixed several console errors regarding propTypes

sass/components/_modal.scss
Cherry pick of #8928 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8928

components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap, components/widgets/menu/menu_items/menu_item.test.tsx, components/widgets/menu/menu_items/menu_item.tsx, components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx, components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx, selectors/views/modals.js
Cherry pick of #8921 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8921

sass/components/_post-right.scss
Cherry pick of #8917 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8917

actions/websocket_actions.jsx
Cherry pick of #8828 on release-6.0.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #8828

components/next_steps_view/images/documents.svg.tsx, components/next_steps_view/images/incidents.svg.tsx, components/next_steps_view/images/plugins.svg.tsx
Cherry pick of #8932 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8932

components/sidebar/add_channel_dropdown.tsx
Cherry pick of #8927 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8927

components/global/global_header.scss
Cherry pick of #8900 on release-6.0.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #8900

components/multiselect/multiselect.tsx
Cherry pick of #8967 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #8967

components/emoji_picker/components/emoji_picker_preview.jsx, components/emoji_picker/index.js
Cherry pick of #8901 on release-6.0.
/cc  @jespino
```release-note
NONE
```
=> Automated cherry pick of #8901

components/needs_team/index.ts, components/needs_team/needs_team.test.tsx, components/needs_team/needs_team.tsx, components/root/root.jsx, components/root/root.test.jsx
Cherry pick of #8926 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8926

components/global/product_switcher.tsx
Cherry pick of #8934 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8934

components/suggestion/suggestion_list.jsx
Cherry pick of #8976 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8976

actions/storage.js, store/index.js
Cherry pick of #8980 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8980

client/websocket_client.tsx
Cherry pick of #8956 on release-6.0.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #8956

actions/websocket_actions.jsx
Cherry pick of #8985 on release-6.0.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #8985

actions/storage.js, package-lock.json, package.json
Cherry pick of #8978 on release-6.0.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #8978

e2e/cypress/integration/accessibility/accessibility_sidebar_spec.js, e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
Fixed Sidebar and Display mode test cases
```
NONE
```
=> CypressE2E: Fixed Test Cases

e2e/cypress/integration/accessibility/accessibility_sidebar_spec.js, e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
Cherry pick of #9007 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #9007

e2e/cypress/integration/account_settings/display/message_display_mode_spec.js, e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_2_spec.js, e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js, e2e/cypress/integration/messaging/direct_message_spec.js, e2e/cypress/integration/messaging/permalink_message_edit_spec.js, e2e/cypress/integration/messaging/strikethrough_spec.js, e2e/cypress/integration/messaging/typing_should_show_up_when_editing_spec.js
Cherry pick of #9006 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #9006

sass/layout/_sidebar-left.scss
Cherry pick of #9005 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #9005

components/channel_layout/center_channel/center_channel.tsx, components/channel_layout/playbook_runner.tsx
Cherry pick of #9012 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #9012

components/needs_team/needs_team.tsx
Cherry pick of #8981 on release-6.0.
```release-note
NONE
```
=> Automated cherry pick of #8981

components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx, components/next_steps_view/steps/invite_members_step/invite_members_step.tsx, i18n/en.json
Cherry pick of https://github.com/mattermost/mattermost-webapp/pull/8944 and https://github.com/mattermost/mattermost-webapp/pull/8990
```release-note
NONE
```
=> [MM-38430] Cherrypick

components/admin_console/admin_definition.jsx
Cherry pick of #8972 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #8972

components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx, components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
Cherry pick of #8990 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
=> Automated cherry pick of #8990

actions/global_actions.tsx, components/threading/global_threads/global_threads.tsx
Cherry pick of #8829 on cloud.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #8829

components/file_preview_modal/file_preview_modal.jsx, components/post_view/post_image/post_image.jsx
Cherry pick of #8971 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #8971

actions/websocket_actions.jsx
Cherry pick of #8985 on release-5.39.
=> Fixes fetching threads upon ws reconnection (#8985)

e2e/cypress/integration/system_console/environment_spec.js
E2E test around the Purge Caches functionality
Addressing https://github.com/mattermost/mattermost-server/issues/18185
```
NONE
```
=> test: MM-T963 Test for Purge Caches

components/more_direct_channels/list/index.test.js, components/more_direct_channels/list/index.ts
Cherry pick of #9029 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9029

e2e/cypress/integration/custom_status/custom_status_expiry/custom_status_expiry_3_spec.js
- Minor fix for custom status expiry e2e
NA
```release-note
NONE
```
=> Cypress/E2E: Update date filter format

packages/mattermost-redux/src/constants/general.ts, packages/mattermost-redux/src/selectors/entities/channels.ts
Cherry pick of #9211 on release-6.1.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #9211

NOTICE.txt
Cherry pick of #9304 on release-6.1.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #9304

components/dot_menu/dot_menu.tsx, components/dot_menu/index.ts, components/rhs_header_post/index.ts, components/rhs_header_post/rhs_header_post.tsx, packages/mattermost-redux/src/selectors/entities/threads.ts, utils/post_utils.ts
Cherry pick of #8779 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #8779

packages/mattermost-redux/src/selectors/entities/channels.test.js, packages/mattermost-redux/src/selectors/entities/channels.ts
Cherry pick of #9313 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9313

components/markdown/markdown.tsx
Cherry pick of #9264 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9264

components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap, components/admin_console/license_settings/license_settings.test.jsx, utils/license_utils.jsx
Cherry pick of #9318 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9318

components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.scss, components/status_dropdown/status_dropdown.scss, components/widgets/menu/menu_items/menu_item.scss
Fixes https://github.com/mattermost/mattermost-server/issues/18532
JIRA https://mattermost.atlassian.net/browse/MM-38937
|----|----|
| ![before](https://user-images.githubusercontent.com/60970/138778966-97164ccd-b778-45a8-b64e-06418c07861f.png) | ![after](https://user-images.githubusercontent.com/60970/138778962-ecfff554-7845-42f0-9885-3232b2f22387.png) |
```release-note
NONE
```
=> [MM-38937] Remove the cursor pointer when hovering at "Disable notifications until:"

e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_center_spec.js, e2e/cypress/integration/messaging/header_spec.js, e2e/cypress/integration/messaging/system_message_spec.js, e2e/cypress/integration/system_console/lock_teammate_name_display_spec.js
Fixed cypress test cases
`NONE`
=> Cypress/E2E: Fixed cypress tests

components/threading/global_threads/thread_item/thread_item.scss
Cherry pick of #9330 on release-6.1.
```release-note
NONE
```
=> Automated cherry pick of #9330

e2e/cypress/integration/bot_accounts/post_message_spec.js, e2e/cypress/integration/emoji/custom_emoji_1_spec.js
=> Cypress/E2E: fixed flaky tests as verified for Cloud release

components/widgets/menu/menu_items/menu_item.scss
Cherry pick of #9324 on release-6.1.
```release-note
NONE
```
=> Automated cherry pick of #9324

components/dot_menu/__snapshots__/dot_menu.test.tsx.snap, components/dot_menu/dot_menu.test.tsx, components/dot_menu/dot_menu.tsx, components/dot_menu/dot_menu_empty.test.tsx, components/dot_menu/dot_menu_mobile.test.tsx, components/dot_menu/index.ts, components/post_view/post_time/index.ts, components/search_results/search_results.tsx, components/search_results_item/__snapshots__/search_results_item.test.jsx.snap, components/search_results_item/index.test.js, components/search_results_item/index.ts, components/search_results_item/search_results_item.jsx, components/search_results_item/search_results_item.test.jsx, packages/mattermost-redux/src/actions/search.ts
* Fix several bugs on saved posts
* Fix tests and fix teamID references in dot menu
* Fix lint
* Unify teamId and currentTeamId
* Fix lint
* Fix test
Co-authored-by: Mattermod <mattermod@users.noreply.github.com>
```release-note
```
=> Fix several bugs on saved posts and mentions (#9310)

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
Cherry pick of #9347 on release-6.1.
```release-note
NONE
```
=> Automated cherry pick of #9347

components/signup/signup_email/signup_email.tsx
This PR is a part of the work done here https://github.com/mattermost/mattermost-server/pull/18894 in order to track successful signups from the email reminders we send to users that're initially invited but join imediately
[MM-39060](https://mattermost.atlassian.net/browse/MM-39060)
- Has server changes (https://github.com/mattermost/mattermost-server/pull/18894)
```release-note
NONE
```
=> [MM-39060] - A/B Test: Reminder to Join Workspace email

components/create_post/create_post.test.jsx, components/create_post/create_post.tsx, components/sidebar/sidebar.test.tsx, components/sidebar/sidebar.tsx
Cherry pick of #9374 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9374

e2e/cypress/integration/account_settings/account_settings_spec.js, e2e/cypress/integration/account_settings/profile/help_text_link_spec.js
- Fixed unstable profile related e2e
- Also updated corresponding terms on zephyr tickets
NA
```release-note
NONE
```
=> Cypress/E2E: Fix unstable profile e2e

components/threading/global_threads/global_threads.tsx, i18n/en.json
Cherry pick of #9393 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9393

components/delete_post_modal/delete_post_modal.tsx, components/delete_post_modal/index.ts, components/threading/global_threads/thread_item/index.ts, reducers/views/rhs.js, reducers/views/threads.ts
Cherry pick of #9381 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9381

components/admin_console/license_settings/ee_license_modal/ee_license_modal.tsx
=> fix : Typscript failing prop for GenericModal in EE_Licence_Modal, changed from onHide to onExited

components/common/radio_group.tsx, components/invitation_modal/add_to_channels.test.tsx, components/invitation_modal/add_to_channels.tsx, components/invitation_modal/index.tsx, components/invitation_modal/invitation_modal.test.tsx, components/invitation_modal/invitation_modal.tsx, components/invitation_modal/invite_as.tsx, components/invitation_modal/invite_view.test.tsx, components/invitation_modal/invite_view.tsx, components/invitation_modal/result_view.tsx, components/toggle.tsx, e2e/cypress/integration/auth_sso/authentication_4_spec.js, e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js, e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js, e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js, e2e/cypress/integration/enterprise/guest_accounts/helpers.js, e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js, e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js, e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_l_does_not_change_focus_to_msgbox_spec.js, e2e/cypress/integration/team_settings/closed_team_invite_by_email_spec.js, e2e/cypress/integration/team_settings/join_closed_team_with_not_allowed_email_spec.js, e2e/cypress/integration/team_settings/teams_spec.js, e2e/cypress/support/common_login_commands.js, e2e/cypress/support/saml_commands.js, e2e/cypress/support/ui/team.js
Cherry pick of #9396 on cloud.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #9396

components/dot_menu/index.ts
Fix mentions permalink not showing the correct team.
https://mattermost.atlassian.net/browse/MM-39816
None
None
```release-note
NONE
```
=> [MM-39816] Fix mentions permalink

components/dot_menu/index.ts
Cherry pick of #9389 on cloud.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #9389

components/admin_console/admin_definition.jsx, i18n/en.json
Cherry pick of #9384 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9384

e2e/cypress/integration/files_and_attachments/channel_files_spec.js, e2e/cypress/integration/system_console/unsaved_changes_spec.js, e2e/cypress/support/ui/sidebar_right.d.ts, e2e/cypress/support/ui/sidebar_right.js
- Fixed channel files search and default max file size
- Added new test case [MM-T4418](https://automation-test-cases.vercel.app/test/MM-T4418)
none, failed on daily run
```release-note
NONE
```
=> Cypress/E2E: Fix channel files search and default max file size

actions/integration_actions.jsx
Remove unused getYoutubeVideoInfo function
No ticket needed
```release-note
NONE
```
=> Remove unused getYoutubeVideoInfo function

.circleci/config.yml, .gitlab-ci.yml
=> Lock CI from /release-6.2

components/code_preview.jsx
Fixing attachments code preview
[MM-40359](https://mattermost.atlassian.net/browse/MM-40359)
```release-note
NONE
```
=> Fixing attachments code preview

components/code_preview.jsx
Cherry pick of #9439 on cloud.
/cc  @jespino
```release-note
NONE
```
=> Automated cherry pick of #9439

actions/views/rhs.ts, components/file_preview_modal/file_preview_modal_info/__snapshots__/file_preview_modal_info.test.tsx.snap, components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.test.tsx, components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.tsx, packages/mattermost-redux/src/actions/posts.ts, packages/mattermost-redux/src/client/client4.ts
Cherry pick of #9323 on release-6.2.
```release-note
NONE
```
=> Automated cherry pick of #9323

components/sidebar_right_menu/index.js, utils/post_utils.ts, utils/utils.jsx
https://mattermost.atlassian.net/browse/MM-40071
#9365
```release-note
NONE
```
=> Fix for isMobile hitting window.innerWidth (#9365) (6.1)

components/sidebar_right_menu/index.js, utils/post_utils.ts, utils/utils.jsx
Cherry pick of #9462 on master.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9462

components/__snapshots__/autosize_textarea.test.jsx.snap, components/__snapshots__/textbox.test.tsx.snap, components/autosize_textarea.test.jsx, components/autosize_textarea.tsx, components/edit_post_modal/edit_post_modal.jsx, components/edit_post_modal/edit_post_modal.test.jsx, components/suggestion/rhs_suggestion_list.tsx, components/suggestion/suggestion_box.jsx, components/suggestion/suggestion_list.jsx, components/textbox/textbox.tsx, components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap, components/user_settings/notifications/manage_auto_responder.jsx, components/user_settings/notifications/manage_auto_responder.test.jsx, utils/utils.jsx
A 5.39 version of https://github.com/mattermost/mattermost-webapp/pull/9451
https://github.com/mattermost/mattermost-webapp/pull/9451
```release-note
NONE
```
=> MM-40071 Only calculate suggestion list max height when first opened (5.39)

components/__snapshots__/autosize_textarea.test.jsx.snap, components/__snapshots__/textbox.test.tsx.snap, components/autosize_textarea.test.jsx, components/autosize_textarea.tsx, components/edit_post_modal/edit_post_modal.test.tsx, components/edit_post_modal/edit_post_modal.tsx, components/quick_input/quick_input.tsx, components/suggestion/rhs_suggestion_list.tsx, components/suggestion/suggestion_box/suggestion_box.jsx, components/suggestion/suggestion_list.jsx, components/textbox/textbox.tsx, components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap, components/user_settings/notifications/manage_auto_responder.jsx, components/user_settings/notifications/manage_auto_responder.test.jsx
Cherry pick of #9451 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9451

components/trial_benefits_modal/trial_benefits_modal.scss, components/trial_benefits_modal/trial_benefits_modal.tsx
Cherry pick of #9469 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9469

client/websocket_client.tsx
The server side configuration will be removed
and the feature will always be enabled now.
Hence removing the if conditions, and updating
the code to assume that reliable websockets is always
true.
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4/7m95frqbk9o8zxin6xo9c7iusoh
=> Remove reliable websockets configuration

components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
Cherry pick of #9476 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9476

plugins/export.js
Bot Badge being used in Focalboard. Bot Badge is required to be exported here.
Required for https://github.com/mattermost/focalboard/pull/1906
```release-note
NONE
```
=> GH-1878: Display Bot Badge in Auto Complete For Focalboard

e2e/cypress/integration/account_settings/profile/profile_picture_change_spec.js
Test that user can remove profile picture then choose different picture without saving in between
https://github.com/mattermost/mattermost-server/issues/18815
```
NONE
```
=> MM-T2079 Can remove profile pic then choose different pic without saving in between

components/dot_menu/__snapshots__/dot_menu.test.tsx.snap, components/dot_menu/dot_menu.tsx, components/file_attachment/file_attachment.tsx, components/rhs_search_nav/rhs_search_nav.tsx, components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap, components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx, components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx, components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap, components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx, components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx, components/sidebar/sidebar_menu/sidebar_menu.test.tsx, components/sidebar/sidebar_menu/sidebar_menu.tsx, utils/utils.jsx
Cherry pick of #9466 on release-6.2.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9466

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx, e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_not_cloud_spec.js
Cherry pick of #9426 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9426

e2e/cypress/integration/mark_as_unread/helpers.js, e2e/cypress/integration/mark_as_unread/mark_dm_post_as_unread_spec.js
Add the tests for marking DM post as Unread in central panel and RHS.
https://github.com/mattermost/mattermost-server/issues/18166
```release-note
NONE
```
=> MM-T248 Mark DM post as Unread

e2e/cypress/integration/account_settings/profile/profile_picture_change_spec.js
- Added missing meta data to recently merged test
NA
NA
```release-note
NONE
```
=> Cypress/E2E: Add missing meta data

e2e/cypress/integration/account_settings/profile/profile_picture_change_spec.js
Verify profile picture does not update when we cancel out of adding/changing profile picture
https://github.com/mattermost/mattermost-server/issues/18814
```release-note
NONE
```
=> MM-T2075 Profile Picture: Cancel out of adding/changing profile picture

sass/components/_day-picker.scss, sass/components/_suggestion-list.scss, utils/utils.jsx
Cherry pick of #9496 on release-6.2.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #9496

actions/views/channel.js, actions/views/channel.test.js, actions/websocket_actions.jsx, components/delete_channel_modal/index.ts, components/rhs_header_post/index.ts, components/rhs_header_post/rhs_header_post.spec.tsx, components/rhs_header_post/rhs_header_post.tsx, e2e/cypress/integration/archived_channel/archive_channel_post_spec.js, e2e/cypress/integration/channel/leave_channel_spec.js, packages/mattermost-redux/src/reducers/entities/threads/counts.ts, packages/mattermost-redux/src/reducers/entities/threads/index.ts, packages/mattermost-redux/src/reducers/entities/threads/threadsInTeam.ts
Cherry pick of #9495 on release-6.2.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #9495

plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap, plugins/channel_header_plug/channel_header_plug.test.tsx, plugins/channel_header_plug/channel_header_plug.tsx, plugins/channel_header_plug/index.ts
Cherry pick of #9424 on release-6.2.
```release-note
NONE
```
=> Automated cherry pick of #9424

components/emoji_picker/components/emoji_picker_preview.tsx, components/emoji_picker/emoji_picker.jsx, components/post_view/reaction_list/index.ts, selectors/emojis.js, utils/emoticons.tsx, utils/post_utils.ts
Cherry pick of #9500 on release-6.2.
```release-note
NONE
```
=> Automated cherry pick of #9500

components/emoji_picker/emoji_picker.jsx
Cherry pick of #9519 on release-6.2.
```release-note
NONE
```
=> Automated cherry pick of #9519

components/emoji_picker/emoji_picker.jsx
Cherry pick of #9531 on release-6.2.
```release-note
NONE
```
=> Automated cherry pick of #9531

components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx, i18n/en.json
Based on PMM proposal, adjust `Need to increase your headcount?` to `Need to increase user count?`
- "headcount" is not a preferred term over seats or users
- shortening text slightly to fit within one line
```release-note
NONE
```
cc @annelieseklein for your review, plus if we'd need to reflect it in our design file
=> Proposed changes to "Contact sales" area title

.circleci/config.yml, .gitlab-ci.yml
=> Lock CI from /release-6.3

client/websocket_client.tsx
Cherry pick of #9430 on release-6.3.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #9430

NOTICE.txt, components/root/root.jsx, components/root/root.test.jsx, package-lock.json, package.json
Cherry pick of #9527 on release-6.3.
```release-note
NONE
```
=> Automated cherry pick of #9527

plugins/export.js
Cherry pick of #9472 on release-6.3.
/cc  @hahmadia
```release-note
NONE
```
=> Automated cherry pick of #9472

components/rhs_card/index.js, components/rhs_card/rhs_card.jsx, components/rhs_card/rhs_card.test.jsx, components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap, components/rhs_comment/index.ts, components/rhs_comment/rhs_comment.jsx, components/rhs_comment/rhs_comment.test.jsx, components/rhs_header_post/index.ts, components/rhs_header_post/rhs_header_post.tsx, components/rhs_root_post/index.ts, components/rhs_root_post/rhs_root_post.jsx, components/rhs_root_post/rhs_root_post.test.jsx, components/search/index.tsx, components/search/search.tsx, components/search/types.ts, components/search_results_item/index.test.js, components/search_results_item/index.ts, components/search_results_item/search_results_item.jsx, components/search_results_item/search_results_item.test.jsx
Cherry pick of #9510 on release-6.3.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9510

i18n/en.json, package-lock.json, package.json
Cherry pick of #9542 on release-6.3.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9542

components/invitation_modal/invite_view.tsx, components/widgets/inputs/users_emails_input.tsx, e2e/cypress/integration/team_settings/invite_members_spec.js
Cherry pick of #9537 on release-6.3.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #9537

components/team_general_tab/__snapshots__/open_invite.test.tsx.snap, components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap, components/team_general_tab/open_invite.test.tsx, components/team_general_tab/open_invite.tsx, components/team_general_tab/team_general_tab.jsx, components/team_general_tab/team_general_tab.test.jsx
Cherry pick of #9494 on release-6.3.
/cc  @jespino
```release-note
NONE
```
=> Automated cherry pick of #9494

components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx, i18n/en.json
Cherry pick of #9533 on release-6.3.
```release-note
NONE
```
=> Automated cherry pick of #9533

actions/team_actions.jsx, components/channel_layout/channel_controller.tsx, components/global_header/global_header.tsx, components/global_header/hooks.tsx, components/root/root.jsx, components/team_sidebar/index.ts, components/team_sidebar/team_sidebar.tsx, plugins/registry.js, sass/layout/_team-sidebar.scss, sass/routes/_backstage.scss, selectors/products.ts, types/store/plugins.ts, utils/products.ts, utils/test_helper.ts
Cherry pick of #9262 on release-6.3.
/cc  @harshilsharma63
```release-note
NONE
```
=> Automated cherry pick of #9262

components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.scss, components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
Cherry pick of #9504 on release-6.3.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9504

components/suggestion/suggestion_box/suggestion_box.jsx
Cherry pick of #9505 on release-6.3.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9505

components/admin_console/license_settings/renew_license_card/renew_license_card.test.tsx, components/admin_console/license_settings/renew_license_card/renew_license_card.tsx, components/announcement_bar/contact_sales/contact_us.tsx, components/announcement_bar/renewal_link/renewal_link.test.tsx, components/announcement_bar/renewal_link/renewal_link.tsx, i18n/en.json
Cherry pick of #9544 on release-6.3.
/cc  @AGMETEOR
```release-note
NONE
```
=> Automated cherry pick of #9544

components/root/root.jsx, packages/mattermost-redux/src/client/client4.ts
Cherry pick of #9333 on release-6.3.
/cc  @SebastianSpeitel
```release-note
NONE
```
=> Automated cherry pick of #9333

components/admin_console/license_settings/starter_edition/starter_left_panel.tsx, i18n/en.json
Cherry pick of #9493 on release-6.3.
/cc  @nathanaelhoun
```release-note
NONE
```
=> Automated cherry pick of #9493

components/__snapshots__/searchable_channel_list.test.jsx.snap, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap, components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap, components/plugin_marketplace/marketplace_modal.tsx, components/quick_input/quick_input.test.tsx, components/quick_input/quick_input.tsx, components/suggestion/modal_suggestion_list.jsx, components/suggestion/rhs_suggestion_list.tsx, components/suggestion/suggestion_box/suggestion_box.jsx, components/suggestion/suggestion_list.jsx
Cherry pick of #9452 on release-6.3.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9452

components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap, components/admin_console/license_settings/index.ts, components/admin_console/license_settings/license_settings.tsx
Cherry pick of #9546 on release-6.3.
```release-note
NONE
```
=> Automated cherry pick of #9546

components/tutorial/tutorial_tip/tutorial_tip.tsx, e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
This PR adds the ability to navigate tutorial tips by pressing the ENTER key
[MM-39488](https://mattermost.atlassian.net/browse/MM-39488)
```release-note
NONE
```
=> [MM-39488] - ENTER does not select the CTA on tutorial tips

components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap, components/announcement_bar/configuration_bar/configuration_bar.test.tsx, utils/license_utils.jsx, utils/license_utils.test.jsx
Cherry pick of #9607 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9607

sass/components/_post-menu.scss
Cherry pick of #9592 on release-6.3.
```release-note
NONE
```
=> Automated cherry pick of #9592

components/admin_console/license_settings/license_settings.scss, components/admin_console/license_settings/starter_edition/starter_edition.scss, components/admin_console/license_settings/starter_edition/starter_right_panel.tsx, components/announcement_bar/contact_sales/contact_us.tsx
Cherry pick of #9594 on release-6.3.
```release-note
NONE
```
=> Automated cherry pick of #9594

.circleci/config.yml
Cherry pick of #9543 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9543

e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_channel_switch_spec.js, e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_up_down_no_action_spec.js, e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_1_spec.js, e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_3_spec.js, e2e/cypress/support/ui/global_header.d.ts, e2e/cypress/support/ui/global_header.js
Fix tests on keyboard shortcuts
```release-note
NONE
```
=> Cypress/E2E: Fix tests on keyboard shortcuts

packages/mattermost-redux/src/client/client4.ts
Cherry pick of #9632 on release-6.3.
```release-note
NONE
```
=> Automated cherry pick of #9632

components/suggestion/channel_mention_provider.jsx
Cherry pick of #9620 on release-6.3.
```release-note
NONE
```
=> Automated cherry pick of #9620

components/searchable_channel_list.jsx
Cherry pick of #9622 on release-6.3.
```release-note
NONE
```
=> Automated cherry pick of #9622

components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Admin console team override scheme page going into an infinite loading state
Fixes https://mattermost.atlassian.net/browse/MM-40591
``None``
|----|----|
| https://www.loom.com/share/691fe8bf460143cea5de25d94290bda6 | https://www.loom.com/share/73f53038beb24ea59558064a73f2f496 |
```release-note
* Bugfix: Admin console team override scheme page going into an infinite loading state
```
=> [MM-40591]Admin console team override scheme page going into an infinite loading state

components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Cherry pick of #9638 on release-6.3.
```release-note
NONE
```
=> Automated cherry pick of #9638

components/admin_console/admin_definition.jsx, components/admin_console/server-health-dashboard/dashboard.tsx, components/admin_console/workspace-optimization/dashboard.tsx, i18n/en.json
adds a working dashboard page to the feature
```release-note
NONE
```
=> working dashboard page

utils/products.ts
Cherry pick of #9658 on release-6.3.
/cc  @harshilsharma63
```release-note
NONE
```
=> Automated cherry pick of #9658

components/channel_header/channel_header.js, components/channel_header/channel_header.test.jsx, components/channel_header/index.js, components/search_hint/search_hint.test.tsx, components/search_hint/search_hint.tsx, components/search_results/__snapshots__/messages_or_files_selector.test.tsx.snap, components/search_results/messages_or_files_selector.test.tsx, components/search_results/messages_or_files_selector.tsx, components/search_results/search_results.tsx, utils/file_utils.jsx
Cherry pick of #9651 on release-6.3.
```release-note
NONE
```
=> Automated cherry pick of #9651

e2e/cypress/integration/keyboard_shortcuts/alt_option_plus_up_down_spec.js, e2e/cypress/integration/keyboard_shortcuts/esc_close_modal_spec.js, e2e/cypress/integration/team_settings/closed_team_invite_by_email_spec.js, e2e/cypress/support/api/preference.d.ts, e2e/cypress/support/api/preference.js, e2e/cypress/support/index.js
Update tests
```release-note
NONE
```
=> Cypress/E2E: Update tests

components/admin_console/workspace-optimization/dashboard.scss, components/admin_console/workspace-optimization/dashboard.tsx, components/common/accordion/accordion.tsx, components/common/accordion/accordion_item.tsx, components/common/chip/chip.tsx, components/create_post/prewritten_chips.tsx, sass/admin_console_base/_sys_css_variables.scss
This PR adds the information chips to the header of the  accordion items.
N/A
N/A
```release-note
NONE
```
=> Growth spike/add information chips

build/emoji/emoji_gen.mjs
N/A
None
N/A
```release-note
NONE
```
=> docs : Removed comment note related to deleting emojis from emoji_gen file

plugins/index.js
Cherry pick of #9541 on cloud.
/cc  @jespino
```release-note
NONE
```
=> Automated cherry pick of #9541

components/threading/global_threads_link/global_threads_link.tsx, components/tutorial/tutorial_tip/index.ts, components/tutorial/tutorial_tip/tutorial_tip.test.tsx, components/tutorial/tutorial_tip/tutorial_tip.tsx, utils/constants.jsx
Cherry pick of #9700 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9700

components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap, components/channel_members_dropdown/channel_members_dropdown.jsx, components/channel_members_dropdown/channel_members_dropdown.test.jsx, components/channel_members_dropdown/index.js
Cherry pick of #9695 on release-6.4.
/cc  @ThiefMaster
```release-note
NONE
```
=> Automated cherry pick of #9695

.circleci/config.yml, .gitlab-ci.yml
=> Lock CI from /release-6.4

components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
Cherry pick of #9646 on release-6.4.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #9646

components/sidebar/__snapshots__/channel_tutorial_tip.test.tsx.snap, components/sidebar/channel_tutorial_tip.tsx, sass/components/_tutorial.scss
Cherry pick of #9723 on release-6.4.
```release-note
NONE
```
=> Automated cherry pick of #9723

NOTICE.txt
Cherry pick of #9746 on release-6.4.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #9746

components/tutorial/tutorial_tip/tutorial_tip.tsx
Moving next on dismiss on causing issue with onBoarding Tour
Fixes https://mattermost.atlassian.net/browse/MM-41570
``NONE``
|----|----|
| https://user-images.githubusercontent.com/16203333/152521050-2a5e9cf5-2d1a-4ef4-b62e-8118c74b731a.mov | https://user-images.githubusercontent.com/16203333/152521160-3b7a5347-8a17-4428-8b94-4e21fa744da2.mov |
```release-note
UI: Moving next on dismiss on causing issue with onBoarding Tour
```
=> [MM-41570] Moving next on dismiss on boarding tour and finished value

components/tutorial/tutorial_tip/tutorial_tip.tsx
=> [MM-41570]Moving next on dismiss on boarding tour and finished value

components/root/root.jsx, sass/base/_structure.scss, sass/layout/_sidebar-left.scss, sass/layout/_team-sidebar.scss, sass/routes/_backstage.scss
Cherry pick of #9755 on release-6.4.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9755

components/admin_console/workspace-optimization/dashboard.data.tsx, components/admin_console/workspace-optimization/dashboard.tsx
aligned the severity levels (`'error'`, `'warning'` or `'info'`) of each item to the figma design file
n/a
n/a
n/a
```release-note
NONE
```
=> added correct severity levels to the accordion items

sass/layout/_team-sidebar.scss
Cherry pick of #9756 on release-6.4.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9756

components/widgets/menu/menu_wrapper.tsx
Cherry pick of #9707 on release-6.3.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9707

components/post_view/post/post.jsx, components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/rhs_root_post.jsx
Cherry pick of #9708 on release-6.3.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9708

components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap, components/sidebar/sidebar_channel/sidebar_channel.tsx, e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js, e2e/cypress/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js, sass/layout/_sidebar-left.scss
Cherry pick of #9732 on release-6.3.
```release-note
NONE
```
=> Automated cherry pick of #9732

e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_user_from_other_team_spec.js
CTRL/CMD+K - Open DM with user: not on the current team
https://github.com/mattermost/mattermost-server/issues/18523
```
NONE
```
=> tests : MM-T1228 CTRL/CMD+K - Open DM with user not on the current team

actions/emoji_actions.js, actions/emoji_actions.test.js, actions/local_storage.jsx, selectors/emojis.js, stores/local_storage_store.jsx, stores/local_storage_store.test.jsx
https://mattermost.atlassian.net/browse/MM-40559
https://github.com/mattermost/mattermost-webapp/pull/9653
```release-note
NONE
```
=> chore/MM-40559 : Add memoization to getOneClickReactionEmojis (#9653) (6.3)

components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/rhs_root_post.jsx, components/rhs_root_post/rhs_root_post.test.jsx, e2e/cypress/integration/messaging/reactions_spec.js
https://mattermost.atlassian.net/browse/MM-41331
https://github.com/mattermost/mattermost-webapp/pull/9718
```release-note
NONE
```
=> MM-41331 : Remove post dot menu from RHS post when not hovered upon (#9718) (6.3)

components/channel_header/__snapshots__/channel_header.test.jsx.snap, components/custom_status/__snapshots__/custom_status_emoji.test.tsx.snap, components/custom_status/custom_status_emoji.tsx, components/profile_popover/__snapshots__/profile_popover.test.tsx.snap, components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
https://mattermost.atlassian.net/browse/MM-41329
https://github.com/mattermost/mattermost-webapp/pull/9698
```release-note
NONE
```
=> MM-41329 : Avoid re-rendering of CustomStatusEmoji component on post hovering (#9698) (6.3)

components/root/index.js
Change Tasklist show condition
Otherwise, link the JIRA ticket.
https://community-daily.mattermost.com/boards/workspace/fpbb7orqpiyfxqgg6fcu91y5xo/b6ropkdiowj8eugbt8kifrew79h/vsha9cczxb3bofripyh3o549s6r/c73y498ooftd65f7uczqbxouuhh
https://github.com/mattermost/mattermost-webapp/pull/9774
https://github.com/mattermost/mattermost-webapp/pull/9774
NONE
```release-note
NONE
```
=> Change Tasklist show condition

components/__snapshots__/textbox.test.tsx.snap, components/suggestion/at_mention_provider/at_mention_provider.jsx, components/suggestion/at_mention_provider/at_mention_provider.test.jsx, components/suggestion/suggestion_box/suggestion_box.test.jsx, components/textbox/index.ts, components/textbox/textbox.tsx, packages/mattermost-redux/src/selectors/entities/channels.ts, packages/mattermost-redux/src/selectors/entities/utils.ts
#9831
```release-note
Fix a major web and desktop app performance problem for users with large accumulated numbers of DMs and GMs.
```
=> Cherry-pick to 6.2 of "Improving selectors of Textbox component (#9831)"

components/__snapshots__/textbox.test.tsx.snap, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/suggestion/at_mention_provider/at_mention_provider.jsx, components/suggestion/at_mention_provider/at_mention_provider.test.jsx, components/suggestion/suggestion_box/suggestion_box.test.jsx, components/textbox/index.ts, components/textbox/textbox.tsx, packages/mattermost-redux/src/selectors/entities/channels.ts, packages/mattermost-redux/src/selectors/entities/utils.ts
#9831
```release-note
Fix a major web and desktop app performance problem for users with large accumulated numbers of DMs and GMs.
```
=> Cherry-pick to 6.3 of "Improving selectors of Textbox component (#9831)"

components/create_post/create_post.tsx
*\*sigh\**
https://mattermost.atlassian.net/browse/MM-41812
```release-note
Fixed a memory leak caused by the post textbox
```
=> MM-41812 Fix instances of CreatePost being leaked

components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap, components/sidebar/sidebar_channel/sidebar_channel.tsx, e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js, e2e/cypress/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js, sass/layout/_sidebar-left.scss
Reverts mattermost/mattermost-webapp#9799
See thread at https://community-daily.mattermost.com/core/pl/iiog3h91ptfjuqc3nos77mxzac.
I thought it would be good to revert, unless this PR is necessary to add to the 6.3.4 dot release. Let me know.
=> Revert "Automated cherry pick of #9732"

components/onboarding_tasklist/onboarding_tasklist.tsx, components/onboarding_tasks/constants.ts, components/onboarding_tasks/onboarding_tasks_manager.tsx, components/root/root.jsx, i18n/en.json, utils/constants.jsx
Cherry pick of #9829 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
=> Automated cherry pick of #9829

components/suggestion/at_mention_provider/at_mention_suggestion.jsx
Cherry pick of #9835 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9835

components/user_groups_modal/user_groups_list/index.ts, packages/mattermost-redux/src/selectors/entities/roles.test.js, packages/mattermost-redux/src/selectors/entities/roles.ts, packages/mattermost-redux/test/test_helper.js
Cherry pick of #9849 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9849

components/onboarding_tasks/onboarding_tasks_manager.tsx
Cherry pick of #9866 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9866

components/preparing_workspace/preparing_workspace.tsx
Cherry pick of #9885 on cloud.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #9885

components/global_header/global_header.tsx
Cherry pick of #9879 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9879

components/plugin_marketplace/marketplace_modal.scss, sass/components/_emoticons.scss
Cherry pick of #9877 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9877

e2e/cypress/integration/account_settings/profile/username_spec.js, e2e/cypress/integration/enterprise/oauth/oauth_spec.js, e2e/cypress/integration/enterprise/system_console/system_scheme_permission_spec.js, e2e/cypress/integration/enterprise/system_console/team_scheme_permission_spec.js, e2e/cypress/integration/integrations/custom_slash_commands/custom_slash_commands_spec.js
Known issues have been added in
```
oauth_spec
username_spec
system_scheme_permission_spec
team_scheme_permission_spec
custom_slash_commands_spec
```
```release-note
NONE
```
=> Cypress/E2E:Added Known Issues

components/sidebar/sidebar_channel/sidebar_channel_link/index.ts, e2e/cypress/integration/onboarding/finish_tutorial_spec.js, e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
Fixed tutorial guided tour test case and finish tutorial tour e2e.
Fixes https://mattermost.atlassian.net/browse/MM-42058
``NONE``
``NONE``
```release-note
E2E: Fixed tutorial guided tour test case and finish tutorial tour e2e
```
=> [MM-42058] : fix onboarding tour e2e

.circleci/config.yml, .gitlab-ci.yml
=> Lock CI from /release-6.5

sass/layout/_sidebar-left.scss
Cherry pick of #9918 on release-6.5.
```release-note
NONE
```
=> Automated cherry pick of #9918

packages/mattermost-redux/src/selectors/entities/roles.test.js, packages/mattermost-redux/src/selectors/entities/roles.ts, packages/mattermost-redux/test/test_helper.js
Cherry pick of #9873 on release-6.5.
```release-note
NONE
```
=> Automated cherry pick of #9873

packages/mattermost-redux/src/actions/groups.ts, packages/mattermost-redux/src/client/client4.ts, packages/mattermost-redux/src/selectors/entities/groups.test.js, packages/mattermost-redux/src/selectors/entities/groups.ts
Cherry pick of #9883 on release-6.5.
```release-note
NONE
```
=> Automated cherry pick of #9883

components/onboarding_tour/onboarding_tour_manager.tsx
Cherry pick of #9912 on release-6.5.
```release-note
NONE
```
=> Automated cherry pick of #9912

components/sidebar/sidebar_channel/sidebar_channel_link/index.ts, e2e/cypress/integration/onboarding/finish_tutorial_spec.js, e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
Cherry pick of #9904 on release-6.5.
```release-note
NONE
```
=> Automated cherry pick of #9904

components/admin_console/admin_definition.jsx, components/sidebar/sidebar_header/sidebar_header.tsx, components/user_groups_modal/user_groups_modal.scss, i18n/en.json
Cherry pick of #9881 on release-6.5.
```release-note
NONE
```
=> Automated cherry pick of #9881

components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap, components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.test.tsx, components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
Cherry pick of #9890 on release-6.5.
```release-note
NONE
```
=> Automated cherry pick of #9890

e2e/cypress/integration/channel_sidebar/group_unreads_separately_spec.js, packages/mattermost-redux/src/selectors/entities/channels.test.js, packages/mattermost-redux/src/selectors/entities/channels.ts, reducers/views/channel.test.js, reducers/views/channel.ts
Cherry pick of #9847 on release-6.5.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #9847

components/needs_team/needs_team.tsx
Cherry pick of #9931 on release-6.5.
```release-note
NONE
```
=> Automated cherry pick of #9931

components/create_post/create_post.tsx
Cherry pick of #9846 on release-6.3.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #9846

components/root/root.jsx, components/root/root.test.jsx, packages/mattermost-redux/src/action_types/users.ts, packages/mattermost-redux/src/actions/users.test.js, packages/mattermost-redux/src/actions/users.ts, packages/mattermost-redux/src/reducers/entities/users.ts, utils/utils.d.ts, utils/utils.jsx, utils/utils.test.jsx
https://mattermost.atlassian.net/browse/MM-41955
#9833
```release-note
NONE
```
=> MM-41955 Reduce useless changes to user state (#9833) (release-6.3)

components/create_user_groups_modal/create_user_groups_modal.test.tsx, components/create_user_groups_modal/create_user_groups_modal.tsx, components/update_user_group_modal/update_user_group_modal.tsx, i18n/en.json
Cherry pick of #9919 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9919

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
Cherry pick of #9854 on release-6.5.
/cc  @ctlaltdieliet
```release-note
NONE
```
=> Automated cherry pick of #9854

components/user_settings/general/user_settings_general.test.tsx, components/user_settings/general/user_settings_general.tsx, i18n/en.json
Cherry pick of #9923 on release-6.5.
/cc  @mkraft
```release-note
NONE
```
=> Automated cherry pick of #9923

components/create_user_groups_modal/create_user_groups_modal.test.tsx, components/create_user_groups_modal/create_user_groups_modal.tsx, components/update_user_group_modal/update_user_group_modal.tsx, i18n/en.json
Cherry pick of #9920 on release-6.5.
```release-note
NONE
```
=> Automated cherry pick of #9920

components/admin_console/password_settings.jsx, e2e/cypress/integration/system_console/authentication/password_settings_spec.js
Fixed MM-31752
[MM-31752](https://mattermost.atlassian.net/browse/MM-31752)
```release-note
NONE
```
=> [MM-31752] - Fixed MM-31752

components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap, components/admin_console/admin_sidebar/admin_sidebar.test.jsx, components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/edit_post_time_limit_modal.jsx
removes the previously needed feature flag guard for the workspace optimization dashboard
[MM-42236](https://mattermost.atlassian.net/browse/MM-42236)
- Has server changes: https://github.com/mattermost/mattermost-server/pull/19754
```release-note
NONE
```
=> Growth spike/remove feature flag guard

components/preparing_workspace/preparing_workspace.tsx
Cherry pick of #9997 on release-6.5.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #9997

components/global_header/global_header.tsx, components/global_header/right_controls/right_controls.tsx, components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap, components/status_dropdown/status_dropdown.tsx
cleaning up intermittent code after global header reached GA.
[MM-37838](https://mattermost.atlassian.net/browse/MM-37838)
- Has server changes: https://github.com/mattermost/mattermost-server/pull/19763
```release-note
NONE
```
=> [MM-37838]: global header clean up

components/edit_post/index.ts
Cherry pick of #10009 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10009

components/emoji_picker/utils/index.ts
Cherry pick of #10003 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10003

actions/global_actions.tsx, actions/telemetry_actions.jsx, actions/websocket_actions.jsx, components/user_settings/advanced/performance_debugging_section/index.ts, components/user_settings/advanced/performance_debugging_section/performance_debugging_section.tsx, i18n/en.json, packages/mattermost-redux/src/constants/preferences.ts
These are based on a couple theories we had about past performance issues. I ended up submitting these together since the PRs would've conflicted if I didn't.
https://mattermost.atlassian.net/browse/MM-41870
https://mattermost.atlassian.net/browse/MM-41872
```release-note
Added additional performance debugging settings
```
=> MM-41870/MM-41872 Add debug settings to disable "User is typing..." and telemetry events

components/edit_post/edit_post.tsx, components/textbox/textbox.tsx
Cherry pick of #10034 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10034

components/dot_menu/dot_menu.test.tsx, components/dot_menu/dot_menu.tsx, components/dot_menu/utils.tsx
Cherry pick of #10053 on cloud.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #10053

components/edit_post/edit_post.tsx, e2e/cypress/tests/integration/messaging/center_channel_rhs_overlap_spec.js, utils/utils.jsx
Cherry pick of #10035 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10035

i18n/en.json
Fixing a small typo in i18n/en.json
Was mentioned by a translator
```release-note
NONE
```
=> Changed spelling from looukp to lookup in translation

components/actions_menu/actions_menu_tutorial_tip.tsx
Cherry pick of #10069 on cloud.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #10069

components/dot_menu/__snapshots__/dot_menu.test.tsx.snap, components/dot_menu/dot_menu.tsx, components/widgets/menu/menu_items/menu_item.scss, components/widgets/menu/menu_items/menu_item_action.test.tsx, components/widgets/menu/menu_items/menu_item_action.tsx
Cherry pick of #10056 on cloud.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #10056

components/actions_menu/actions_menu.tsx, components/rhs_comment/rhs_comment.jsx, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/rhs_root_post.jsx, e2e/cypress/tests/integration/accessibility/accessibility_post_spec.js, e2e/cypress/tests/integration/messaging/tooltip_visual_verification_spec.js, i18n/en.json
Cherry pick of #10028 on cloud.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #10028

actions/command.test.js, actions/websocket_actions.jsx, actions/websocket_actions.test.jsx, components/admin_console/custom_plugin_settings/index.js, components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap, components/admin_console/plugin_management/index.ts, components/admin_console/plugin_management/plugin_management.test.tsx, components/admin_console/plugin_management/plugin_management.tsx, components/app_bar/app_bar.test.tsx, components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts, packages/mattermost-redux/src/action_types/apps.ts, packages/mattermost-redux/src/actions/apps.ts, packages/mattermost-redux/src/reducers/entities/apps.test.ts, packages/mattermost-redux/src/reducers/entities/apps.ts, packages/mattermost-redux/src/selectors/entities/apps.test.ts, packages/mattermost-redux/src/selectors/entities/apps.ts, packages/mattermost-redux/src/store/initial_state.ts, packages/mattermost-redux/src/types/apps.ts, utils/constants.jsx
Cherry pick of #8545 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #8545

components/threading/thread_viewer/index.ts, components/threading/thread_viewer/thread_viewer.test.tsx, components/threading/thread_viewer/thread_viewer.tsx
Cherry pick of #9913 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #9913

selectors/actions_menu.ts
Cherry pick of #10080 on cloud.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #10080

e2e/cypress/tests/integration/accessibility/accessibility_buttons_spec.js, e2e/cypress/tests/integration/accessibility/accessibility_dropdowns_spec.js
fixes for failures I was able to dupe locally from https://automation-dashboard.vercel.app/cycles/49e35a20-a7d1-4b23-a7ae-ebd1fb504047
```release-note
NONE
```
=> e2e: fix accessiblity test issues

e2e/cypress/tests/integration/accessibility/accessibility_buttons_spec.js, e2e/cypress/tests/integration/accessibility/accessibility_dropdowns_spec.js
Cherry pick of #10085 on cloud.
/cc  @Phrynobatrachus
```release-note
NONE
```
=> Automated cherry pick of #10085

packages/mattermost-redux/src/types/config.ts
https://mattermost.atlassian.net/browse/MM-41260
```release-note
NONE
```
=> MM-41260: Add new Elasticsearch config settings

.circleci/config.yml, .gitlab-ci.yml
=> Lock CI from /release-6.6

components/dot_menu/__snapshots__/dot_menu.test.tsx.snap, components/dot_menu/dot_menu.tsx, utils/constants.jsx
Cherry pick of #10063 on release-6.6.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #10063

components/integrations/__snapshots__/abstract_command.test.jsx.snap, components/integrations/abstract_command.jsx
Updated legacy link identified while testing https://mattermost.atlassian.net/browse/MM-42675
```release-note
NONE
```
=> Updated legacy link

sass/layout/_markdown.scss
The code blocks with a specified language would wrap instead of
showing a horizontal scroll.
Fixes [MM-42777](https://mattermost.atlassian.net/browse/MM-42777)
```release-note
Fixes a bug where code blocks that had a language specified would wrap instead of showing a horizontal scrollbar. This made code blocks harder to read.
```
=> [MM-42777] Fixes a bug where code blocks would not longer be scrollable

sass/layout/_markdown.scss
Cherry pick of #10120 on cloud.
/cc  @cleferman
```release-note
NONE
```
=> Automated cherry pick of #10120

components/post_view/post_info/post_info.tsx, components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap, components/rhs_root_post/rhs_root_post.jsx
Cherry pick of #10068 on cloud.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #10068

components/post_view/post_info/post_info.tsx
Cherry pick of #10114 on release-6.6.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #10114

components/dot_menu/__snapshots__/dot_menu.test.tsx.snap, components/dot_menu/dot_menu.scss, components/dot_menu/dot_menu.tsx
Cherry pick of #10111 on release-6.6.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #10111

components/dot_menu/dot_menu.tsx
Cherry pick of #10116 on cloud.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #10116

components/actions_menu/actions_menu_tutorial_tip.tsx, components/post_view/post_info/post_info.tsx, components/widgets/tour_tip/tour_tip.tsx
Cherry pick of #10127 on cloud.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #10127

components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.tsx.snap, components/post_view/post_body_additional_content/post_body_additional_content.test.tsx, components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap, components/post_view/post_message_preview/index.ts, components/post_view/post_message_preview/post_message_preview.test.tsx, components/post_view/post_message_preview/post_message_preview.tsx, packages/mattermost-redux/src/types/posts.ts
Adds permalink previews for DMs and GMs.
Fixes [MM-38615](https://mattermost.atlassian.net/browse/MM-38615)
- Has server changes https://github.com/mattermost/mattermost-server/pull/19765
```release-note
Adds permalink previews for DMs/GMs
```
=> [MM-38615] Permalink Previews for DMs/GMs

actions/websocket_actions.jsx, actions/websocket_actions.test.jsx
Cherry pick of #10152 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10152

e2e/cypress/tests/integration/integrations/incoming_webhook/incoming_webhook_creates_dm_spec.js, package-lock.json
This PR adds an E2E test case, to verify that an Incoming Webhook can successfully create a DM to another user.
Fixes https://github.com/mattermost/mattermost-server/issues/18183
NONE
No UI change
```release-note
NONE
```
=> MM-T639 Webhook DM test

utils/route.tsx
Cherry pick of #10161 on release-6.6.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #10161

package-lock.json, webpack.config.js
This is required in order to have the images accessible publicly.
```release-note
None
```
=> [MM-43339] [MM-43337] Add email asset images to webpack copy so they're exposed publicly

e2e/cypress/tests/integration/accessibility/accessibility_dropdowns_spec.js, e2e/cypress/tests/integration/account_settings/profile/nickname_spec.js, e2e/cypress/tests/integration/channel_settings/add_users_to_channel_spec.js, e2e/cypress/tests/integration/enterprise/guest_accounts/guest_experience_ui_spec.js, e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_ui_spec.js, e2e/cypress/tests/integration/enterprise/ldap/ldap_group_sync_spec.js, e2e/cypress/tests/integration/enterprise/permissions/team_permissions_spec.js, e2e/cypress/tests/integration/enterprise/system_console/channel_moderation/helpers.js, e2e/cypress/tests/integration/enterprise/system_console/channel_moderation/manage_members_spec.js, e2e/cypress/tests/integration/messaging/center_channel_rhs_overlap_spec.js, e2e/cypress/tests/integration/multi_team_and_dm/gm_add_user_spec.js, e2e/cypress/tests/integration/system_console/user_management_not_cloud_spec.js
Fix e2e tests that broke after.
A lot of them depended on a removed modal, and the features have not all been ported.
https://mattermost.atlassian.net/browse/MM-43336
N/A
```release-note
NONE
```
=> [MM-43336] Fix some e2e tests

package.json
Fixes minor coding style
```release-note
NONE
```
=> Fixes minor code style

components/command_palette/command_palette.tsx, components/command_palette/command_palette_modal/command_palette_modal.scss, components/command_palette/command_palette_modal/command_palette_modal.tsx, components/command_palette/command_palette_modal/index.ts, components/command_palette/index.ts, components/command_palette/types/index.ts, components/root/root.jsx, components/sidebar/channel_navigator/channel_navigator.test.tsx, components/sidebar/channel_navigator/channel_navigator.tsx, components/sidebar/channel_navigator/index.ts, i18n/en.json, packages/mattermost-redux/src/selectors/entities/preferences.ts, utils/constants.jsx
=> Make command palette available with shortcuts and from other places

e2e/cypress/tests/integration/collapsed_reply_threads/following_1_spec.js, e2e/cypress/tests/integration/collapsed_reply_threads/following_spec.js, e2e/cypress/tests/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
Fixed Accessibility_modals_dialogs_spec test case
```release-note
NONE
```
=> E2E/Cypress:test case fixed

components/team_sidebar/components/team_button.tsx, components/team_sidebar/team_sidebar.tsx
Cherry pick of #10203 on cloud.
/cc  @harshilsharma63
```release-note
NONE
```
=> Automated cherry pick of #10203

components/command_palette/command_palette.tsx, components/command_palette/command_palette_list/command_palette_list.scss, components/command_palette/command_palette_list/command_palette_list.tsx, components/command_palette/command_palette_list_item/command_palette_list_item.scss, components/command_palette/command_palette_list_item/command_palette_list_item.tsx, components/command_palette/command_palette_list_item/command_palette_list_item_pictograph.tsx, components/command_palette/command_palette_manager/command_palette_manager.ts, components/command_palette/command_palette_modal/command_palette_modal.scss, components/command_palette/command_palette_modal/command_palette_modal.tsx, components/command_palette/command_palette_modal/filters/filters.scss, components/command_palette/demo.json, components/command_palette/index.ts, components/command_palette/types/index.ts, components/command_palette/utils.ts
=> Command palette : Add command palette list, item and channel to command palette transformer

Makefile
Change-Id: I5c664cdc5616d9a6f9eac5c420bdc0c5c090a4d1
All make targets are the same in `make help` output.  So specify the makefile path for the `grep` command.
NA
|----|----|
| ![image](https://user-images.githubusercontent.com/8930775/163726098-47a0bbe8-0880-4afa-9c13-c11f554139bd.png)|![image](https://user-images.githubusercontent.com/8930775/163726091-f2eaef8a-63bc-4892-b9c4-9e525bb902ff.png) |
```release-note
NONE
```
=> fix the same target in make help output

components/admin_console/license_settings/__snapshots__/license_settings.test.tsx.snap, components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss, components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.test.tsx, components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx, components/admin_console/license_settings/license_settings.tsx, components/admin_console/license_settings/modals/__snapshots__/upload_license_modal.test.tsx.snap, components/admin_console/license_settings/modals/upload_license_modal.test.tsx, components/admin_console/license_settings/modals/upload_license_modal.tsx, i18n/en.json
Cherry pick of #10204 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
=> Automated cherry pick of #10204

plugins/registry.js
=> Update LinkTooltip docs

e2e/cypress/tests/integration/onboarding/use_team_invite_link_to_sign_up_spec.js
- Replaced query for town square
NA
```release-note
NONE
```
=> Cypress/E2E: Fix user team invite link to sign up spec

e2e/cypress/tests/integration/system_console/environment_spec.js
- Added saving of s3 connection settings and updated error message
NA
```release-note
NONE
```
=> Cypress/E2E: Fix environment spec

components/channel_members_rhs/search.tsx, components/widgets/inputs/input/input.tsx, i18n/en.json
This PR adds a placeholder to channel members search
https://mattermost.atlassian.net/browse/MM-43638
N/A
```release-note
NONE
```
=> [MM-43638] Add placeholder to channel members search

components/channel_members_rhs/search.tsx, components/widgets/inputs/input/input.tsx, i18n/en.json
Cherry pick of #10236 on release-6.7.
```release-note
NONE
```
=> Automated cherry pick of #10236

components/channel_members_rhs/index.ts
Improve channel member RHS perf by creating a selector to memoize retrieving members 
https://mattermost.atlassian.net/browse/MM-43602
N/A
N/A
```release-note
NONE
```
=> [MM-43602] Channel Members RHS: improve perf

NOTICE.txt
Cherry pick of #10251 on release-6.7.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #10251

components/new_channel_modal/__snapshots__/new_channel_modal.test.tsx.snap, components/new_channel_modal/new_channel_modal.tsx, e2e/cypress/tests/integration/multi_team_and_dm/existing_channel_name_spec.js
New channel modal: enabling enter key to submit channel creation
https://mattermost.atlassian.net/browse/MM-43816
```release-note
NONE
```
=> MM-43816_Unable to hit enter to create channel in new Create Channel modal

components/edit_post/edit_post.tsx
fixes posting the edited message with `enter` when editing messages that contain code-blocks
[MM-43349](https://mattermost.atlassian.net/browse/MM-43349)
n/a
n/a
```release-note
NONE
```
=> [MM-43349]: fixes posting edited code-blocks

components/edit_post/edit_post.tsx
Cherry pick of #10288 on release-6.7.
```release-note
NONE
```
=> Automated cherry pick of #10288

components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap, components/link_tooltip/link_tooltip.scss, components/link_tooltip/link_tooltip.tsx, e2e/cypress/tests/integration/plugins/link_tooltip_spec.js
Cherry pick of #10265 on release-6.7.
```release-note
NONE
```
=> Automated cherry pick of #10265

components/channel_members_rhs/index.ts, e2e/cypress/tests/integration/channel/channel_members_rhs_spec.js, packages/mattermost-redux/src/selectors/entities/users.ts
(cherry picked from commit 2e29e54)
Co-authored-by: Julien Tant <785518+JulienTant@users.noreply.github.com>
```release-note
none
```
=> Cherry pick for MM-43328

components/rhs_header_post/rhs_header_post.spec.tsx, components/widgets/tour_tip/index.ts, components/widgets/tour_tip/tour_tip.tsx, components/widgets/tour_tip/tour_tip_backdrop.tsx, tests/react-tippy_mock.js
Fix issue with tippy mock test and TourTipOverlayPunchOut export warning
Fixes https://mattermost.atlassian.net/browse/MM-44047
Blocking https://github.com/mattermost/mattermost-webapp/pull/10099
NONE
```release-note
* Bugfix: Fixes issue with tippy mock, import warning for TourTipOverlayPunchOut
```
=> [MM-44047] fix issue with tippy mock test and TourTipOverlayPunchOut export warning

components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap, components/threading/global_threads/thread_list/thread_list.tsx, components/tutorial/tutorial_tip_legacy/__snapshots__/tutorial_tip.test.tsx.snap, components/tutorial/tutorial_tip_legacy/tutorial_tip.tsx, components/widgets/pulsating_dot/index.tsx, e2e/cypress/tests/integration/collapsed_reply_threads/crt_tour_spec.js
Add 3 e2e tests for CRT tour:
https://automation-test-cases.vercel.app/test/MM-T4684 CRT full tour
https://automation-test-cases.vercel.app/test/MM-T4694 CRT skip tour
https://automation-test-cases.vercel.app/test/MM-T4695 CRT cancel any point by using x
Add data-testid and update snapshots
Fix https://github.com/mattermost/mattermost-server/issues/19824
```release-note
NONE
```
=> MM-42031 : Add e2e tests for CRT tour

components/actions_menu/__snapshots__/actions_menu.test.tsx.snap
Fixes snapshot tests
```release-note
NONE
```
=> Fixes snapshot tests

i18n/en.json
Cherry pick of #10306 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10306

components/edit_post/edit_post.tsx
Cherry pick of #10312 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10312

components/threading/thread_viewer/thread_viewer.scss, components/threading/virtualized_thread_viewer/create_comment.tsx, e2e/cypress/tests/integration/channel/archived_channels_1_spec.js, i18n/en.json, i18n/en_AU.json, sass/layout/_sidebar-right.scss
Cherry pick of #10222 on cloud.
/cc  @kyeongsoosoo
```release-note
NONE
```
=> Automated cherry pick of #10222

components/post_view/reaction_list/reaction_list.tsx, components/post_view/reaction_list/reactions_list.test.tsx
Cherry pick of #10214 on cloud.
/cc  @jtdspiria
```release-note
NONE
```
=> Automated cherry pick of #10214

components/invitation_modal/result_table.scss
Cherry pick of #10293 on cloud.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #10293

sass/components/_post.scss
Cherry pick of #10326 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10326

components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts, i18n/en.json
Cherry pick of #10344 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10344

components/advanced_text_editor/advanced_text_editor.tsx, components/advanced_text_editor/formatting_bar/formatting_bar.tsx, components/advanced_text_editor/toggle_formatting_bar/toggle_formatting_bar.tsx, packages/mattermost-redux/src/selectors/entities/preferences.ts
Fixes: Advanced text editor image pasting and drag drop issue
Fixes https://mattermost.atlassian.net/browse/MM-44428
NONE
```release-note
* Advanced text editor bugs
```
=> [MM-44428]: Advanced text editor image pasting and drag drop issue

components/advanced_text_editor/advanced_text_editor.tsx, components/advanced_text_editor/formatting_bar/formatting_bar.tsx, components/advanced_text_editor/toggle_formatting_bar/toggle_formatting_bar.tsx
Cherry pick of #10336 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10336

components/channel_view/index.ts, components/threading/virtualized_thread_viewer/create_comment.tsx, components/user_settings/advanced/index.js, components/user_settings/advanced/user_settings_advanced.jsx, packages/mattermost-redux/src/selectors/entities/preferences.ts
Cherry pick of #10343 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10343

components/threading/thread_viewer/index.ts, components/threading/thread_viewer/thread_viewer.test.tsx, components/threading/thread_viewer/thread_viewer.tsx, packages/mattermost-redux/src/reducers/entities/posts.test.js, packages/mattermost-redux/src/reducers/entities/posts.ts
Cherry pick of #10345 on cloud.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #10345

components/cloud_start_trial/cloud_start_trial_btn.tsx, components/onboarding_tasklist/onboarding_tasklist_completed.tsx
Cherry pick of #10350 on cloud.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #10350

components/app_bar/app_bar.scss
Cherry pick of #9680 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #9680

components/root/index.js
Cherry pick of #10388 on release-7.0.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #10388

actions/admin_actions.jsx, packages/client/src/client4.ts, packages/types/src/config.ts
Cherry pick of #10295 on release-7.0.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #10295

components/header_footer_route/footer.scss, components/header_footer_route/footer.tsx, components/header_footer_route/header.scss, components/header_footer_route/header.tsx, e2e/cypress/tests/integration/signin_authentication/login_spec.js, e2e/cypress/tests/integration/signin_authentication/signup_spec.js, e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_1_spec.js, e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_2_spec.js
Cherry pick of #10377 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10377

components/admin_console/billing/billing_subscriptions/index.tsx, components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx, components/announcement_bar/cloud_trial_announcement_bar/index.ts, components/widgets/menu/menu_items/menu_cloud_trial.tsx, e2e/cypress/tests/support/api/preference.d.ts, e2e/cypress/tests/support/index.js, utils/constants.tsx
This PR removes the 14 days hardcoded value and uses the feature flag isCloudFreeEnabled to determine if the max value is 14 days trial period or 30 days trial period.
https://mattermost.atlassian.net/browse/MM-44420
n/a
https://user-images.githubusercontent.com/10082627/170384033-9c460519-bdb3-443f-9ebe-f6ce13646c99.mp4
```release-note
NONE
```
=> MM-44420 - remove 14 days hardcoded values

components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.tsx, components/crt_tour/collapsed_reply_threads_modal/collapsed_reply_threads_modal.tsx
Update in-product GIF for CRT tutorial
Fixes https://mattermost.atlassian.net/browse/MM-44450
NONE
|----|----|
| <img width="716" alt="Screenshot 2022-05-27 at 4 43 43 PM" src="https://user-images.githubusercontent.com/16203333/170689220-ee7ee55d-82ac-49f9-b2e3-18cda1dee69f.png"> | <img width="689" alt="Screenshot 2022-05-27 at 4 41 57 PM" src="https://user-images.githubusercontent.com/16203333/170689205-544b1a3f-a38b-48c2-9df6-0b648bbe9d65.png"> |
```release-note
UI: Update in-product GIF for CRT tutorial
```
=> [MM-44450] Update in-product GIF for CRT tutorial

components/advanced_create_post/advanced_create_post.tsx
Cherry pick of #10415 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10415

components/widgets/menu/menu_items/menu_cloud_trial.test.tsx, components/widgets/menu/menu_items/menu_item_cloud_limit.test.tsx
Fix master tests
```release-note
NONE
```
=> Fix master pipeline

components/widgets/menu/menu_items/menu_cloud_trial.test.tsx, components/widgets/menu/menu_items/menu_item_cloud_limit.test.tsx
Cherry pick of #10427 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10427

components/advanced_create_comment/__snapshots__/advanced_create_comment.test.jsx.snap, components/advanced_create_comment/advanced_create_comment.tsx, components/advanced_create_post/__snapshots__/advanced_create_post.test.jsx.snap, components/advanced_create_post/advanced_create_post.tsx, components/advanced_text_editor/advanced_text_editor.scss, components/advanced_text_editor/advanced_text_editor.tsx, components/advanced_text_editor/formatting_bar/formatting_bar.tsx, components/file_upload/__snapshots__/file_upload.test.jsx.snap, components/file_upload/file_upload.jsx, components/file_upload/index.js, sass/components/_post.scss
Cherry pick of #10384 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10384

components/channel_info_rhs/index.ts, e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js
Cherry pick of #10438 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10438

components/admin_console/billing/billing_subscriptions/index.tsx, components/purchase_modal/purchase_modal.tsx
This PR adds ability to open pricing modal using query param on the admin billing route
[MM-44643](https://mattermost.atlassian.net/browse/MM-44643)
```release-note
NONE
```
=> [MM-44643] - Support the ability to link directly into the pricing modal

actions/global_actions.tsx, actions/views/channel.js, components/channel_layout/center_channel/index.ts, components/threading/global_threads/global_threads.tsx, e2e/cypress/tests/integration/collapsed_reply_threads/last_viewed_spec.js, e2e/cypress/tests/support/ui/sidebar_left.js, selectors/local_storage.ts, stores/local_storage_store.jsx, utils/constants.tsx
Cherry pick of #10255 on release-7.0.
/cc  @kyeongsoosoo
```release-note
NONE
```
=> Automated cherry pick of #10255

actions/views/rhs.ts, components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap, components/channel_header_dropdown/channel_header_dropdown_items.js, components/channel_header_dropdown/menu_items/open_members_rhs/index.ts, components/channel_header_dropdown/menu_items/open_members_rhs/open_members_rhs.tsx, components/channel_members_rhs/channel_members_rhs.tsx, components/channel_members_rhs/index.ts, components/channel_members_rhs/member.tsx, components/channel_members_rhs/member_list.tsx, e2e/cypress/tests/integration/archived_channel/archive_channel_member_spec.js, e2e/cypress/tests/integration/channel/channel_members_rhs_spec.js, e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_ui_spec.js, e2e/cypress/tests/integration/enterprise/permissions/team_permissions_spec.js, reducers/views/rhs.test.js, reducers/views/rhs.ts, selectors/rhs.ts, types/store/rhs.ts, utils/constants.tsx
Cherry pick of #10446 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10446

e2e/cypress/tests/integration/emoji/custom_emoji_1_1_spec.js, e2e/cypress/tests/integration/emoji/custom_emoji_1_spec.js, e2e/cypress/tests/integration/emoji/custom_emoji_2_1_spec.js, e2e/cypress/tests/integration/emoji/custom_emoji_2_spec.js
demoted `custom_emoji_1_1_spec.js`
demoted `custom_emoji_2_1_spec.js`
```release-note
NONE
```
=> E2E/Cypress:test cases demoted

packages/mattermost-redux/src/selectors/entities/preferences.ts
Cherry pick of #10445 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10445

components/__snapshots__/alert_banner.test.tsx.snap, components/alert_banner.tsx, components/signup/signup.tsx, e2e/cypress/tests/integration/team_settings/closed_team_invite_by_email_spec.js
When enabled email invitations, the email invite link should allow to signup.
https://mattermost.atlassian.net/browse/MM-44746
https://user-images.githubusercontent.com/79058848/171731545-498088c3-1f8e-40a0-9350-89b6e1f98bc1.mp4
```release-note
NONE
```
=> MM-44746_Not Open Server error when signing up with email invite

e2e/cypress/tests/integration/auth_sso/authentication_4_spec.js, e2e/cypress/tests/integration/system_console/main_menu_spec.js, e2e/cypress/tests/integration/system_console/site_configuration/link_customization_cloud_spec.js, e2e/cypress/tests/utils/admin_console.js
Fixed Cloud test cases
```release-note
NONE
```
=> E2E/Cypress:fixed cloud test cases

e2e/cypress/cypress.json, e2e/cypress/tests/integration/markdown/markdown_image_spec.js, e2e/cypress/tests/integration/markdown/markdown_text_spec.js, e2e/cypress/tests/support/api/cloud_default_config.json
Removed cloud_restrictable config settings updated by https://github.com/mattermost/mattermost-server/pull/20297
```release-note
NONE
```
=> removed cloud_restrictable config

components/advanced_text_editor/formatting_bar/formatting_icon.tsx
Cherry pick of #10474 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10474

packages/client/src/client4.ts, packages/mattermost-redux/src/actions/channels.ts
Cherry pick of #10363 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10363

components/app_bar/app_bar.scss, sass/layout/_sidebar-right.scss
Cherry pick of #10454 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10454

components/header_footer_route/header_footer_route.tsx, components/login/login.tsx
Cherry pick of #10492 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10492

components/app_bar/__snapshots__/app_bar.test.tsx.snap, components/app_bar/app_bar.scss, components/app_bar/app_bar.tsx
Cherry pick of #10471 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10471

components/cloud_start_trial/request_business_email_modal.tsx, components/onboarding_tasklist/onboarding_tasklist.tsx, components/root/index.js, components/root/root.jsx
Cherry pick of #10479 on cloud.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #10479

components/app_bar/app_bar.scss
Cherry pick of #10467 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10467

components/advanced_text_editor/advanced_text_editor.scss
fix Advanced Text editor Padding issue in RHS and Thread view
Fixes https://mattermost.atlassian.net/browse/MM-44438
Fixes https://mattermost.atlassian.net/browse/MM-44609
NONE
```release-note
fix Advanced Text editor Padding issue in RHS and Thread view
```
=> [MM-44438]: fix Advanced Text editor Padding issue in RHS and Thread view

components/advanced_text_editor/advanced_text_editor.scss
Cherry pick of #10466 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10466

components/advanced_create_comment/advanced_create_comment.tsx, components/advanced_create_comment/index.ts, components/advanced_create_post/advanced_create_post.tsx, components/advanced_create_post/index.ts, components/edit_channel_header_modal/index.ts, components/user_settings/advanced/user_settings_advanced.jsx
Cherry pick of #10497 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10497

components/advanced_text_editor/advanced_text_editor.tsx
Cherry pick of #10495 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10495

components/file_upload/file_upload.jsx
Cherry pick of #10503 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10503

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
Cherry pick of #10513 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10513

components/advanced_text_editor/send_button/send_button.tsx
Advanced Text Editor: forced refresh on message submit via send button if message has special mentions all, channel etc
Fixes https://mattermost.atlassian.net/browse/MM-44933
NONE
NONE
```release-note
Advanced Text Editor: fixes forced refresh on message submit via button if message have special mentions all, channel etc
```
=> [MM-44933] Advanced Text Editor: fixes forced refresh on message submit via button if message have special mentions all, channel etc

components/login/__snapshots__/login.test.tsx.snap, components/login/login.tsx, e2e/cypress/tests/integration/signin_authentication/login_spec.js, e2e/cypress/tests/support/common_login_commands.js
Cherry pick of #10506 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10506

components/advanced_text_editor/send_button/send_button.tsx
Cherry pick of #10531 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10531

actions/notification_actions.jsx, actions/notification_actions.test.js, packages/mattermost-redux/src/utils/post_utils.ts
Cherry pick of #10521 on cloud.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #10521

components/suggestion/suggestion_box/suggestion_box.jsx
Cherry pick of #10480 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10480

actions/cloud.tsx, packages/client/src/client4.ts, packages/types/src/posts.ts, utils/limits.tsx
Cherry pick of #10530 on cloud.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #10530

components/markdown_image_expand/markdown_image_expand.scss
Fixes the collapsed markdown image preview
https://mattermost.atlassian.net/browse/MM-38305
```release-note
NONE
```
=> Fix markdown image collapsed preview

e2e/cypress/tests/integration/messaging/file_upload_in_center_channel_spec.js
Adding correct test case id MM-T4861
```release-note
NONE
```
=> Update test case id for file_upload_in_center_channel_spec.js

components/admin_console/billing/billing_summary/upsell_card.scss, components/cloud_usage_modal/index.scss
Fixes some theming issues found when on admin_console -> subscriptions 
[MM-44923](https://mattermost.atlassian.net/browse/MM-44923)
Before
-----
See ticket description
After
-----
```release-note
NONE
```
=> [MM-44923] - Fix theming issues when in subscriptions under the admin console

components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.tsx, components/post_view/post_attachment_opengraph/post_attachment_opengraph.tsx
Cherry pick of #10606 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10606

packages/README.md, packages/client/README.md, packages/types/README.md
This contains some minor docs cleanup now that I've actually done this process once and the removal of some warnings from the READMEs of the subpackage that should've been done before this.
```release-note
NONE
```
=> Update subpackage docs

components/advanced_text_editor/formatting_bar/formatting_bar.tsx, components/file_upload/__snapshots__/file_upload.test.jsx.snap, components/file_upload/file_upload.jsx
Cherry pick of #10592 on release-7.0.
```release-note
NONE
```
=> Automated cherry pick of #10592

components/activity_and_insights/activity_and_insights.scss, components/activity_and_insights/insights/card/card.scss, components/activity_and_insights/insights/insights_header/insights_header.scss, sass/responsive/_desktop.scss
Merge into master of https://github.com/mattermost/mattermost-webapp/pull/10473.
```release-note
NONE
```
=> [MM-44657] Insights responsive (#10473)

components/activity_and_insights/activity_and_insights_link/activity_and_insights_link.tsx, components/activity_and_insights/insights/card/__snapshots__/card.test.tsx.snap, components/activity_and_insights/insights/card/card.tsx, components/activity_and_insights/insights/insights.tsx, components/activity_and_insights/insights/time_frame_dropdown/time_frame_dropdown.tsx, components/activity_and_insights/insights/top_boards/top_boards.tsx, components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx, components/activity_and_insights/insights/top_channels/top_channels.tsx, components/activity_and_insights/insights/top_channels/top_channels_table/top_channels_table.tsx, components/activity_and_insights/insights/top_threads/top_threads.tsx, components/activity_and_insights/insights/top_threads/top_threads_table/top_threads_table.tsx, components/activity_and_insights/insights/widget_hoc/widget_hoc.tsx
Merges https://github.com/mattermost/mattermost-webapp/pull/10518 into master.
```release-note
NONE
```
=> [MM-44657] Insights telemetry (#10518)

components/pricing_modal/content.tsx, components/pricing_modal/downgrade_team_removal_modal/downgrade_team_removal_modal.scss, components/pricing_modal/downgrade_team_removal_modal/index.tsx
See #10634 
```release-note
None
```
=> Cherry pick #10634 into cloud

components/pricing_modal/content.tsx
Cherry pick of #10641 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10641

components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap, components/global_header/left_controls/product_menu/product_menu_list/index.ts, components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.test.tsx, components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
Cherry pick of #10640 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10640

components/emoji/add_emoji/__snapshots__/add_emoji.test.tsx.snap, components/emoji/add_emoji/add_emoji.tsx, i18n/en.json
Cherry pick of #10668 on release-7.1.
```release-note
NONE
```
=> Automated cherry pick of #10668

components/advanced_create_comment/advanced_create_comment.tsx, components/advanced_create_post/advanced_create_post.tsx, components/advanced_text_editor/advanced_text_editor.scss
Cherry pick of #10628 on release-7.1.
```release-note
NONE
```
=> Automated cherry pick of #10628

package-lock.json, package.json, packages/client/package.json, packages/types/package.json
Cherry-pick of #10600 from release-7.0
https://github.com/mattermost/mattermost-webapp/pull/10600
```release-note
NONE
```
=> Update subpackage versions to 7.0.0 (#10600)

components/post_view/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.tsx.snap, components/post_view/post_attachment_opengraph/post_attachment_opengraph.tsx
Cherry pick of #10664 on release-7.1.
```release-note
NONE
```
=> Automated cherry pick of #10664

actions/views/rhs.ts, components/channel_members_rhs/channel_members_rhs.tsx, components/channel_members_rhs/index.ts, components/channel_members_rhs/member.tsx, components/channel_members_rhs/member_list.tsx, e2e/cypress/tests/integration/channel/channel_members_rhs_spec.js, packages/mattermost-redux/src/selectors/entities/users.ts
Cherry pick of #10577 on release-7.1.
```release-note
NONE
```
=> Automated cherry pick of #10577

components/channel_members_rhs/channel_members_rhs.tsx, components/channel_members_rhs/member_list.tsx, packages/mattermost-redux/src/actions/users.ts
Improves the code quality of the channel members RHS list by address nits detected by @julmondragon on my previous PR
@stevemudie there's no changes in features here or bugfix just code improvement, so I guess QA is making sure it works as before
N/A
N/A
N/A
```release-note
NONE
```
=> Improve code quality on members list RHS

components/purchase_modal/process_payment_setup.tsx
Makes changes to remove the telemetry calls from the render function
[MM-45100](https://mattermost.atlassian.net/browse/MM-45100)
```release-note
NONE
```
=> [MM-45100] - Remove telemetry calls from render function

components/activity_and_insights/insights/card/card.scss, components/activity_and_insights/insights/insights_header/insights_header.scss
The header shrinks when you navigate to Threads
https://mattermost.atlassian.net/browse/MM-45222
```release-note
NONE
```
=> [MM-45222] Fixing insights header

components/activity_and_insights/insights/card/card.scss, components/activity_and_insights/insights/insights_header/insights_header.scss
Cherry pick of #10655 on release-7.1.
```release-note
NONE
```
=> Automated cherry pick of #10655

components/announcement_bar/cloud_trial_ended_announcement_bar/cloud_trial_ended_announcement_bar.test.tsx, components/announcement_bar/cloud_trial_ended_announcement_bar/index.tsx
Cherry pick of #10692 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10692

components/activity_and_insights/activity_and_insights.scss, components/activity_and_insights/insights/insights_modal/insights_modal.scss
Cherry pick of #10666 on release-7.1.
```release-note
NONE
```
=> Automated cherry pick of #10666

components/activity_and_insights/activity_and_insights.scss, components/activity_and_insights/insights/insights_modal/insights_modal.scss, components/activity_and_insights/insights/top_threads/top_threads.scss
Adding ellipsis for channel name when it is too long
https://mattermost.atlassian.net/browse/MM-45261
```release-note
NONE
```
=> [MM-45261] Fixing channel name wrap for top threads

components/activity_and_insights/activity_and_insights.scss, components/activity_and_insights/insights/insights_modal/insights_modal.scss, components/activity_and_insights/insights/top_threads/top_threads.scss
Cherry pick of #10670 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10670

components/activity_and_insights/insights/top_threads/top_threads.scss
Cherry pick of #10677 on release-7.1.
```release-note
NONE
```
=> Automated cherry pick of #10677

e2e/playwright/playwright.config.ts, e2e/playwright/support/server/channel.ts, e2e/playwright/support/server/default_config.ts, e2e/playwright/support/server/index.ts, e2e/playwright/support/server/init.ts, e2e/playwright/support/server/team.ts, e2e/playwright/support/server/user.ts, e2e/playwright/support/ui/component/index.ts, e2e/playwright/support/ui/component/post_textbox.ts, e2e/playwright/support/ui/page/channel.ts, e2e/playwright/support/ui/page/index.ts, e2e/playwright/support/ui/page/landing_login.ts, e2e/playwright/support/ui/page/login.ts, e2e/playwright/support/ui/page/signup.ts, e2e/playwright/support/visual/applitools.ts, e2e/playwright/support/visual/percy.ts, e2e/playwright/tests/visual/intro_channel.spec.ts, e2e/playwright/tests/visual/landing_page.spec.ts, e2e/playwright/tests/visual/login.spec.ts, e2e/playwright/tests/visual/signup_email.spec.ts, e2e/playwright/tsconfig.json
Introduce paths and update initSetup to include uploading of profile image
none
```release-note
NONE
```
=> Playwright/E2E: Introduce paths and update initSetup to include uploading of profile image

e2e/cypress/tests/integration/auth_sso/authentication_4_spec.js, e2e/cypress/tests/integration/enterprise/guest_accounts/member_invitation_ui_spec.js, e2e/cypress/tests/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/not_open_emoji_picker_spec.js
Fixes the few remaining issues from cloud run review the other day.
```release-note-none
```
=> e2e: fix some test issues

components/admin_console/push_settings.jsx
Fix the HPNS link found in the admin console under Push Notification Server settings
N/A
N/A
```release-note
NONE
```
=> push_settings: fix broken link for linkHPNS

components/dot_menu/dot_menu.test.tsx, components/dot_menu/dot_menu.tsx, components/dot_menu/index.ts, packages/mattermost-redux/src/selectors/entities/preferences.ts
Cherry pick of #10816 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10816

components/admin_console/system_roles/system_role/system_role_users/index.tsx, components/admin_console/system_roles/system_role/system_role_users/system_role_users.tsx
Cherry pick of #10781 on cloud.
/cc  @mkraft
```release-note
NONE
```
=> Automated cherry pick of #10781

components/forward_post_modal/forward_post_modal.tsx
Fixes a merge conflict with https://github.com/mattermost/mattermost-webapp/pull/10569
```release-note
NONE
```
=> Fix merge conflict with compoennts.

components/pricing_modal/card.tsx, components/pricing_modal/content.tsx, components/pricing_modal/pricing_modal.scss, components/pricing_modal/starter_disclaimer_cta.tsx, e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js
Cherry-pick of https://github.com/mattermost/mattermost-webapp/pull/10815
```release-note
NONE
```
=> Cherry pick of #10815 to cloud

packages/components/rollup.config.js
Move the `globals` option to the output.
```release-note
NONE
```
=> Move globals option to output.

components/forward_post_modal/forward_post_modal.scss
fixes the missing scrollbars in the comment input for the forward post modal
[MM-45941](https://mattermost.atlassian.net/browse/MM-45941)
n/a
n/a
```release-note
NONE
```
=> [MM-45941]: fix for long comment in textbox

components/channel_header_mobile/channel_header_mobile.tsx
fixes unresponsive RHS and LHS making the app in mobile view hard to use.
[MM-46006](https://mattermost.atlassian.net/browse/MM-46006)
n/a
n/a
```release-note
NONE
```
=> [MM-46006]: fix for unresponsive RHS and LHS in mobile view

components/channel_header_mobile/channel_header_mobile.tsx
Cherry pick of #10844 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10844

package-lock.json, packages/client/package.json, packages/types/package.json
https://mattermost.atlassian.net/browse/MM-45825
```release-note
NONE
```
=> Update client and types packages to 7.1.0

components/search_bar/search_bar.tsx, sass/components/_popover.scss, sass/components/_search.scss
fixes some UI inconsistencies with the search bar in the global header
deferring QA since this only affects styles on the global header search bar and the changes are very minimal
[MM-43839](https://mattermost.atlassian.net/browse/MM-43839)
n/a
n/a
```release-note
NONE
```
=> [MM-43839]: style adjustments to the search bar

e2e/cypress/utils/report.js
This fixes the duration in the report in community channel and also add info about the env overrides of the test server (in support to running daily run with some feature flags enabled like in the case of GraphQL)
```release-note
NONE
```
=> Cypress/E2E: Update cypress report

components/forward_post_modal/forward_post_modal.scss
Cherry pick of #10845 on release-7.2.
```release-note
NONE
```
=> Automated cherry pick of #10845

sass/components/_post.scss
Cherry pick of #10856 on release-7.2.
```release-note
NONE
```
=> Automated cherry pick of #10856

e2e/cypress/tests/integration/messaging/mention_autocomplete_overlap_spec.js, e2e/cypress/tests/integration/plugins/plugin_startup_fail_spec.js
Demote mention_autocomplete_overlap_spec test case
Fixed plugin_startup_fail_spec test case
```release-note
NONE
```
=> Cypress/e2e:Fixed test case

components/admin_console/admin_definition.jsx, components/login/login.scss, components/signup/signup.scss, i18n/en.json, utils/admin_console_index.test.tsx
Cherry pick of #10762 on release-7.2.
```release-note
NONE
```
=> Automated cherry pick of #10762

.gitlab-ci.yml
PR contains changes to include shared components in the gitlab pipelines.
```release-note
NONE
```
=> Fix gitlab pipelines for shared components

components/global_header/right_controls/plan_upgrade_button/index.tsx
Fixes the splitio feature flag treatment
https://mattermost.atlassian.net/browse/MM-45666
```release-note
NONE
```
=> Fix the feature flag treatment

components/global_header/right_controls/plan_upgrade_button/index.tsx
Cherry pick of #10876 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
=> Automated cherry pick of #10876

components/file_upload/file_upload.jsx, components/file_upload/file_upload.test.jsx
Cherry pick of #10839 on release-7.2.
```release-note
NONE
```
=> Automated cherry pick of #10839

NOTICE.txt
Cherry pick of #10827 on release-7.2.
/cc  @mattermod
```release-note
NONE
```
=> Automated cherry pick of #10827

components/threading/global_threads/thread_list/thread_list.tsx
Cherry pick of #10801 on release-7.2.
```release-note
NONE
```
=> Automated cherry pick of #10801

i18n/en.json
Changes the header text for the autocomplete list of group mentions.
https://mattermost.atlassian.net/browse/MM-45854
```release-note
NONE
```
=> MM-45854: Updates translation.

components/root/root.jsx
https://github.com/mattermost/mattermost-webapp/pull/10891
```release-note
```
=> Cherry pick 

i18n/en.json
Cherry pick of #10885 on release-7.2.
/cc  @mkraft
```release-note
NONE
```
=> Automated cherry pick of #10885

components/root/root.jsx
Cherry pick of #10900 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10900

components/signup/__snapshots__/signup.test.tsx.snap, components/signup/signup.tsx
Cherry pick of #10882 on release-7.2.
/cc  @phpfs
```release-note
NONE
```
=> Automated cherry pick of #10882

components/advanced_text_editor/advanced_text_editor.tsx
Cherry pick of #10889 on release-7.2.
/cc  @mkraft
```release-note
NONE
```
=> Automated cherry pick of #10889

components/login/login.scss
Cherry pick of #10862 on release-7.2.
/cc  @phpfs
```release-note
NONE
```
=> Automated cherry pick of #10862

components/root/root.jsx
Fix condition checking if the hostname is test.mattermost.com
We don’t want to show the landing page on rainforest test servers but the check to make that happen wasn’t working as intended this will fix that.
Fixes https://mattermost.atlassian.net/browse/MM-46232
NONE
| Before |
|----|
https://user-images.githubusercontent.com/16203333/184130776-3b5e8914-42ff-47a1-ba5b-45ec21ee3d17.mov 
| After |
|----|
https://user-images.githubusercontent.com/16203333/184129844-6a475957-c323-4db8-addd-a63dfc9ad146.mov
```release-note
* Fix condition checking if the hostname is test.mattermost.com
```
=> Fix condition checking if the hostname is test.mattermost.com

components/root/root.jsx
Cherry pick of #10921 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10921

components/admin_console/license_settings/starter_edition/starter_edition.scss, components/admin_console/license_settings/starter_edition/starter_left_panel.tsx, e2e/cypress/tests/integration/enterprise/system_console/about/starter_edition_spec.js
Add View plan button that opens the pricing modal when on self-hosted starter
https://mattermost.atlassian.net/browse/MM-46060
```release-note
NONE
```
=> [MM-46060] - Self-Managed: Add 'View Plan' button in plan card

packages/client/src/client4.ts
Cherry pick of #10741 on cloud.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #10741

e2e/cypress/tests/integration/accessibility/accessibility_account_settings_spec.js, e2e/cypress/tests/support/api/cloud_default_config.json, e2e/cypress/tests/utils/constants.js
=> e2e: Fix cloud failures

e2e/cypress/tests/integration/account_settings/profile/fullname_edit_spec.js
This PR adds Webapp E2E test with Cypress for "MM-T2042 Full Name starting blank stays blank"
Fixes https://github.com/mattermost/mattermost-server/issues/18824
```release-note
NONE
```
=> Write Webapp E2E with Cypress: "MM-T2042 Full Name starting blank stays blank"

components/file_preview_modal/index.ts, package-lock.json
Cherry pick of #10952 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #10952

CODEOWNERS
n/a
n/a
n/a
```release-note
NONE
```
=> Add QA Platform in Codeowners for "e2e" folder

components/pricing_modal/content.tsx, e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js
When on enterprise trial, enable professional upgrade button
https://mattermost.atlassian.net/browse/MM-46448
```release-note
NONE
```
=> [MM-46448] - Subscribe button for Professional is disabled during Enterprise trial

e2e/cypress/tests/integration/accessibility/accessibility_account_settings_spec.js, e2e/cypress/tests/support/api/cloud_default_config.json, e2e/cypress/tests/utils/constants.js
Cherry pick of #10929 on cloud.
/cc  @Phrynobatrachus
```release-note
NONE
```
=> Automated cherry pick of #10929

webpack.config.js
Clears the dist between build
https://mattermost.atlassian.net/browse/MM-46497
n/a
n/a
```release-note
NONE
```
=> MM-46497 : Clear dist folder before running webpack build

components/advanced_create_post/advanced_create_post.tsx
Cherry pick of #10979 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10979

components/admin_console/cluster_table.jsx, i18n/en.json
We show a warning text if mixed versions are found
in a cluster.
https://mattermost.atlassian.net/browse/MM-29908
```release-note
NONE
```
=> MM-29908: Show warning text if mixed versions

packages/mattermost-redux/src/actions/threads.ts
Cherry pick of #10998 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #10998

components/onboarding_tasklist/onboarding_tasklist.tsx, components/onboarding_tasks/constants.ts
Cherry pick of #10999 on cloud.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #10999

components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx, components/user_settings/display/user_settings_theme/user_settings_theme.tsx
fix import issue causing type check failure caused by https://github.com/mattermost/mattermost-webapp/pull/10822
NONE
```release-note
- fix import issue causing type check failure
```
=> Fix import issue causing type check failure

components/activity_and_insights/activity_and_insights.scss
Cherry pick of #11034 on cloud.
/cc  @mkraft
```release-note
NONE
```
=> Automated cherry pick of #11034

components/activity_and_insights/insights/top_boards/top_boards.tsx, components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx, packages/types/src/insights.ts
Fixing the link to top boards
https://mattermost.atlassian.net/browse/MM-46523
```release-note
NONE
```
=> [MM-46523] Removing workspaceID and fixing link

components/activity_and_insights/insights/top_boards/top_boards.tsx, components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx, packages/types/src/insights.ts
Cherry pick of #10983 on release-7.3.
```release-note
NONE
```
=> Automated cherry pick of #10983

components/suggestion/switch_channel_provider.jsx
Cherry pick of #10971 on release-7.3.
/cc  @sinansonmez
```release-note
NONE
```
=> Automated cherry pick of #10971

components/pdf_preview.jsx, package-lock.json, package.json
This PR upgrades PDFJS-dist to the latest version. Includes minor breaking changes.
Note for QA: uploading and previewing a pdf file should work the same as on master.
https://mattermost.atlassian.net/browse/MM-32929
```release-note
NONE
```
=> Upgrade pdfjs-dist to latest version

components/admin_console/feature_discovery/feature_discovery.test.tsx, components/admin_console/feature_discovery/feature_discovery.tsx, components/admin_console/feature_discovery/features/announcement_banner.tsx, components/admin_console/feature_discovery/features/compliance_export.tsx, components/admin_console/feature_discovery/features/custom_terms_of_service.tsx, components/admin_console/feature_discovery/features/data_retention.tsx, components/admin_console/feature_discovery/features/groups.tsx, components/admin_console/feature_discovery/features/guest_access.tsx, components/admin_console/feature_discovery/features/ldap.tsx, components/admin_console/feature_discovery/features/openid.tsx, components/admin_console/feature_discovery/features/saml.tsx, components/admin_console/feature_discovery/features/system_roles.tsx, components/admin_console/feature_discovery/index.tsx, components/announcement_bar/purchase_link/purchase_link.tsx, e2e/cypress/tests/integration/system_console/feature_discovery_cloud_spec.js, e2e/cypress/tests/integration/system_console/feature_discovery_not_cloud_spec.js, i18n/en.json, utils/constants.tsx, utils/utils.tsx
For feature discovery of an enterprise feature, show `Contact sales`
https://mattermost.atlassian.net/browse/MM-46678
```release-note
NONE
```
=> [MM-46678] - Feature Discovery shows Upgrade to Enterprise plan

actions/command.test.js, actions/command.ts, components/global_header/left_controls/product_menu/product_menu_list/index.ts, i18n/en.json, packages/mattermost-redux/src/selectors/entities/general.ts
Cherry pick of #11024 on release-7.3.
```release-note
NONE
```
=> Automated cherry pick of #11024

components/user_settings/security/user_access_token_section/user_access_token_section.tsx, i18n/en.json
Cherry pick of #10995 on release-7.3.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #10995

components/activity_and_insights/activity_and_insights.scss
Display Top Playbooks widget.
https://mattermost.atlassian.net/browse/MM-46805
```release-note
NONE
```
=> MM-46805: Show Top Playbooks widget.

components/activity_and_insights/activity_and_insights.scss
Cherry pick of #11073 on release-7.3.
/cc  @mkraft
```release-note
NONE
```
=> Automated cherry pick of #11073

e2e/cypress/tests/integration/accessibility/accessibility_popovers_spec.js, e2e/cypress/tests/integration/autocomplete/database/users_in_channel_switcher_spec.js, e2e/cypress/tests/integration/autocomplete/database/users_in_message_input_box_spec.js, e2e/cypress/tests/integration/autocomplete/database/users_spec.js, e2e/cypress/tests/integration/messaging/message_spec.js, e2e/cypress/tests/integration/search_autocomplete/channels_spec.js, e2e/cypress/tests/integration/search_autocomplete/renaming_spec.js
Fixed Cloud test cases 
```release-note
NONE
```
=> Cypress/e2e:fixed Cloud

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
Cherry pick of #11091 on release-7.3.
```release-note
NONE
```
=> Automated cherry pick of #11091

selectors/plugins.ts
Cherry pick of #11076 on release-7.3.
```release-note
NONE
```
=> Automated cherry pick of #11076

components/activity_and_insights/activity_and_insights.scss, components/activity_and_insights/insights/insights_modal/insights_modal.scss, components/activity_and_insights/insights/least_active_channels/least_active_channels_table/least_active_channels_table.tsx, components/activity_and_insights/insights/top_dms_and_new_members/new_members_table/new_members_table.tsx, sass/responsive/_desktop.scss
Cherry pick of #11084 on release-7.3.
```release-note
NONE
```
=> Automated cherry pick of #11084

components/activity_and_insights/activity_and_insights.scss, components/activity_and_insights/insights/least_active_channels/least_active_channels.test.tsx, components/activity_and_insights/insights/least_active_channels/least_active_channels_item/least_active_channels_item.tsx, components/activity_and_insights/insights/least_active_channels/least_active_channels_table/least_active_channels_table.tsx, i18n/en.json
Cherry pick of #11122 on cloud.
/cc  @plant99
```release-note
NONE
```
=> Automated cherry pick of #11122

actions/channel_actions.jsx, actions/channel_actions.test.js, actions/global_actions.tsx, components/channel_layout/channel_identifier_router/actions.ts, components/needs_team/index.ts, components/needs_team/needs_team.test.tsx, components/needs_team/needs_team.tsx, components/suggestion/switch_channel_provider.jsx, packages/mattermost-redux/src/actions/channels.test.js, packages/mattermost-redux/src/actions/channels.ts, packages/mattermost-redux/src/actions/teams.ts
In ahead preparation to convert both of them will be converted to separate GQL action
https://mattermost.atlassian.net/browse/MM-46994
n/a
n/a
```release-note
NONE
```
=> MM-46994 : Suffix REST to "fetchAllMyTeamsChannelsAndChannelMembers" & "fetchMyChannelsAndMembers"

components/people/directory/directory.scss, components/people/directory/directory.tsx, i18n/en.json
Adding top menu with search bar and title. Probably won't support all the filters from the start
```release-note
NONE
```
=> Adding basic top menu

components/activity_and_insights/insights/insights.tsx, components/sidebar_right/sidebar_right.tsx
Cherry pick of #11144 on release-7.4.
```release-note
NONE
```
=> Automated cherry pick of #11144

components/channel_notifications_modal/components/expand_view.jsx, components/channel_notifications_modal/components/expand_view.test.jsx, components/channel_notifications_modal/components/notification_section.jsx
By mistake merged.
Reverts mattermost/mattermost-webapp#11159
=> Revert "MM-47099 :  Migrate "components/channel_notifications_modal/components/expand_view.jsx" to Typescript"

components/channel_notifications_modal/components/expand_view.jsx, components/channel_notifications_modal/components/expand_view.test.jsx, components/channel_notifications_modal/components/notification_section.jsx
Cherry pick of #11215 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11215

components/suggestion/suggestion_box/suggestion_box.jsx
Cherry pick of #11155 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11155

components/sidebar_right_menu/index.ts
Migration of index.js to index.ts in components/sidebar_right_menu
Fixes https://github.com/mattermost/mattermost-server/issues/21051
Fixes https://mattermost.atlassian.net/browse/MM-47119
None
None
```release-note
NONE
```
=> MM-47119 : Migrate "components/sidebar_right_menu/index.js" to Typescript

package-lock.json, package.json
```release-note
@mattermost/compass-icons updated to v0.1.27
```
=> Update compass-icons to 0.1.27

webpack.config.js
Cherry pick of #11067 on release-7.3.
```release-note
NONE
```
=> Automated cherry pick of #11067

utils/youtube.ts
Migrate utils/youtube.js to typescript
Fixes https://github.com/mattermost/mattermost-server/issues/21166
JIRA: https://mattermost.atlassian.net/browse/MM-47193
None
None
```release-note
```
=> MM-47193 : Migrate "utils/youtube.js" to typescript

i18n/en.json, plugins/pluggable/__snapshots__/pluggable.test.jsx.snap, plugins/pluggable/error_boundary.tsx, plugins/pluggable/pluggable.test.jsx, plugins/pluggable/pluggable.tsx
Cherry pick of #11148 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #11148

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
Cherry pick of #11263 on release-7.4.
```release-note
NONE
```
=> Automated cherry pick of #11263

utils/storage_utils.ts
Migrate utils/storage_utils.js to typescript
Fixes https://github.com/mattermost/mattermost-server/issues/21165
JIRA: https://mattermost.atlassian.net/browse/MM-47194
None
None
```release-note
NONE
```
=> MM-47194 : Migrate "utils/storage_utils.js" to typescript

package-lock.json, package.json, packages/client/package.json, packages/types/package.json
https://mattermost.atlassian.net/browse/MM-47038
```release-note
NONE
```
=> Update subpackage versions to 7.3.0

components/needs_team/needs_team.tsx, components/search_results/index.tsx, components/search_results/search_results.tsx, packages/mattermost-redux/src/selectors/entities/teams.ts
Cherry pick of #11279 on release-7.4.
```release-note
NONE
```
=> Automated cherry pick of #11279

components/advanced_create_comment/__snapshots__/advanced_create_comment.test.jsx.snap, components/advanced_create_comment/advanced_create_comment.tsx, components/advanced_create_post/__snapshots__/advanced_create_post.test.jsx.snap, components/advanced_create_post/advanced_create_post.tsx, components/advanced_text_editor/advanced_text_editor.tsx, components/custom_status/custom_status_modal.tsx, components/emoji_picker/emoji_picker_overlay.tsx, components/post_view/post_reaction/__snapshots__/post_reaction.test.tsx.snap, components/post_view/post_reaction/post_reaction.tsx, components/post_view/reaction_list/__snapshots__/reactions_list.test.tsx.snap, components/post_view/reaction_list/reaction_list.tsx
This PR migrates 'components/emoji_picker/emoji_picker_overlay.jsx' module and associated tests to TypeScript
Fixes [https://github.com/mattermost/mattermost-server/issues/21155](https://github.com/mattermost/mattermost-server/issues/21155)
JIRA [https://mattermost.atlassian.net/browse/MM-20519](https://mattermost.atlassian.net/browse/MM-20519)
```release-note
```
=> MM-20519 : Migrate 'components/emoji_picker/emoji_picker_overlay.jsx' module to TypeScript

components/forward_post_modal/forward_post_channel_select.tsx, components/forward_post_modal/forward_post_modal.tsx
fixes bug on cloud instances with forwarding to new DMs (no options showing due to wrong filtering)
[MM-45688](https://mattermost.atlassian.net/browse/MM-45688)
n/a
n/a
```release-note
NONE
```
=> [MM-45688]: fixed missing options due to wrong filtering

components/announcement_bar/announcement_bar_controller.tsx, components/announcement_bar/legacy_mattermost_cloud_bar/index.test.tsx, components/announcement_bar/legacy_mattermost_cloud_bar/index.tsx, i18n/en.json, utils/test_helper.ts
Show banner to legacy mattermost cloud admins that they need to change workspace soon.
https://mattermost.atlassian.net/browse/MM-45013
https://user-images.githubusercontent.com/13738432/194353683-19502477-a002-4102-b61e-bc0bac5b3ed4.mp4
```release-note
Show banner to legacy mattermost cloud admins that they need to change workspace soon.
```
=> legacy mattermost cloud bar

components/announcement_bar/announcement_bar_controller.tsx, components/announcement_bar/legacy_mattermost_cloud_bar/index.test.tsx, components/announcement_bar/legacy_mattermost_cloud_bar/index.tsx, i18n/en.json, utils/test_helper.ts
Cherry pick of #11290 on cloud.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #11290

components/delinquency_modal/delinquency_modal_controller.test.tsx, components/delinquency_modal/useDelinquencyModalController.tsx
Cherry pick of #11324 on cloud.
/cc  @Afsoon
```release-note
NONE
```
=> Automated cherry pick of #11324

entry.tsx, root.tsx, webpack.config.js
Cherry pick of #11337 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #11337

components/center_message_lock/index.tsx, components/feature_restricted_modal/feature_restricted_modal.tsx, components/notify_admin_cta/notify_admin_cta.tsx, e2e/cypress/tests/integration/enterprise/cloud/billing/notify_admin_spec.js
When the non admin user has already notified the admin, disable the CTA
https://mattermost.atlassian.net/browse/MM-46645
```release-note
NONE
```
=> [MM-46645] - UI Enhancement | Web App | To Disable notify button when we see 'Already Notified' text

e2e/cypress/tests/integration/integrations/incoming_webhook/attachment_does_not_collapse_spec.js, e2e/cypress/tests/integration/integrations/incoming_webhook/attachment_does_not_collapse_spec.ts
I'm working on creating a video for Hacktoberfest 2022, that shows contributors how to write their first E2E test for Mattermost. This PR is a part of this process 🙂 
[Write Webapp E2E with Cypress: "MM-T642 Attachment does not collapse" #18184 ](https://github.com/mattermost/mattermost-server/issues/18184)
N/A
N/A
```release-note
NONE
```
=> MM-T642: Attachment does not collapse - Cypress Webapp E2E Test

components/root/root.tsx
Cherry pick of #11339 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11339

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml
Updated CodeQL to use the latest version and reduced few false positive alerts
https://mattermost.atlassian.net/browse/SEC-1282
```
NONE
```
=> Updated CodeQL to use latest version 

components/search_results_item/index.ts
Cherry pick of #11406 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11406

package-lock.json, package.json, packages/mattermost-redux/src/store/configureStore.ts
Upgrade redux version from v4.1.0 to v.4.2.0 in the context of regular dependency upgrades.
| From version | To Version | Change log | Notes |
| ------------- | ------------- | ------------- | ------------- |
| 4.1.0  | 4.2.0  | [changelog](https://github.com/reduxjs/redux/releases) | Mostly some small fixes in 4.1.1 and 4.1.2 and deprecation of createStore in 4.2.0 (see changelogs) |
https://mattermost.atlassian.net/browse/MM-47619
```release-note
NONE
```
=> [MM-47619] Upgrade redux to version 4.2.0

package-lock.json, package.json
In the context of regular dependency upgrades, this is the upgrade of highlight.js to version 11.6.0 (minor version upgrade).
| From version | To Version | Change log | Notes |
| ------------- | ------------- | ------------- | ------------- |
| 11.5.1  | 11.6.0  | [changelog](https://github.com/highlightjs/highlight.js/releases/tag/11.6.0) | Changes are dropped support for node 12.x and fixes or enhancements of grammars |
https://mattermost.atlassian.net/browse/MM-47621
```release-note
NONE
```
=> [MM-47621] Upgrade highlight.js to 11.6.0

components/admin_console/billing/billing_subscriptions/limit_reached_banner.test.tsx, components/pricing_modal/downgrade_team_removal_modal/downgrade_team_removal_modal.test.tsx, packages/types/src/cloud.ts
[MM-47560](https://mattermost.atlassian.net/browse/MM-47560)
- Has server changes (https://github.com/mattermost/mattermost-server/pull/21429)
```release-note
NONE
```
=> [MM-47560]: Add support for new fields (back-end and front-end)

components/search/search.tsx, components/search_hint/__snapshots__/search_hint.test.tsx.snap, components/search_hint/search_hint.tsx, e2e/cypress/tests/integration/search/search_bar_popup_focus_spec.js
Cherry pick of #10792 on release-7.1.
/cc  @tiagodll
```release-note
NONE
```
=> Automated cherry pick of #10792

actions/status_actions.ts
Removed global state from "status_actions.ts" in mattermost webapp.
Fixes [https://github.com/mattermost/mattermost-server/issues/21354](https://github.com/mattermost/mattermost-server/issues/21354)
Jira [https://mattermost.atlassian.net/browse/MM-47443](https://mattermost.atlassian.net/browse/MM-47443)
```release-note
NONE
```
=> MM-47443 : Removed gobal state from 'status_actions.ts'

components/file_upload/file_upload.tsx, components/root/root.tsx, utils/dragster.ts, utils/utils.tsx
Bubble DragEvent to drag and drop text into input/textarea.
Fixes https://github.com/mattermost/mattermost-server/issues/18074
No related PRs.
https://user-images.githubusercontent.com/25968819/192328143-3f703dc7-d776-4157-a097-914342a8f299.mov
https://user-images.githubusercontent.com/25968819/192328184-cf37e2b5-9935-45bf-88eb-4b10dd0ee8e6.mov
```release-note
Text can be dragged and droppped into input-fields.
```
=> [MM-37712] Bubble DragEvent to drag and drop text into input/textarea

package-lock.json, package.json, packages/client/package.json, packages/types/package.json
https://mattermost.atlassian.net/browse/MM-47316
https://github.com/mattermost/mattermost-webapp/pull/11430
```release-note
NONE
```
=> MM-74316 Update client and types packages to 7.4.0 (master)

components/channel_layout/channel_identifier_router/channel_identifier_router.test.tsx, utils/browser_history.tsx
Migrate utils/browser_history.jsx To Typescript
Fixes https://github.com/mattermost/mattermost-server/issues/21161
JIRA: https://mattermost.atlassian.net/browse/MM-47190
None
None
```release-note
NONE
```
=> MM-47190: Migrate utils/browser_history.jsx To Typescript

components/suggestion/generic_user_provider.tsx, components/suggestion/menu_action_provider.tsx
Migration of components/suggestion/menu_action_provider.jsx to Typescript
Fixes: https://mattermost.atlassian.net/browse/MM-47070
Fixes: https://github.com/mattermost/mattermost-server/issues/21129
NONE
NONE
```release-note
NONE
```
=> Migrate "components/suggestion/menu_action_provider.jsx" to Typescript

components/channel_groups_manage_modal/channel_groups_manage_modal.tsx, components/list_modal.tsx, components/team_groups_manage_modal/team_groups_manage_modal.tsx
Migrate components/list_modal.jsx to Typescript
Fixes https://github.com/mattermost/mattermost-server/issues/21061
JIRA: https://mattermost.atlassian.net/browse/MM-47109
None
None
```release-note
```
=> MM-47109 : Migrate components/list_modal.jsx to Typescript

components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap, components/user_settings/display/manage_languages/manage_languages.test.tsx, components/user_settings/display/manage_languages/manage_languages.tsx, i18n/en.json
Cherry-pick of #11121 to the 7.1 ESR
https://mattermost.atlassian.net/browse/MM-44114
https://mattermost.atlassian.net/browse/MM-47881
#11121
```release-note
NONE
```
=> MM-44114 : Announcing of channel interface language dropdown correctly (#11121)

components/advanced_text_editor/advanced_text_editor.tsx, components/channel_view/channel_view.tsx, i18n/en.json
Cherry-pick of https://github.com/mattermost/mattermost-webapp/pull/11083 to the 7.1 ESR
https://mattermost.atlassian.net/browse/MM-46596
https://github.com/mattermost/mattermost-webapp/pull/11083
```release-note
NONE
```
=> [MM-46596] Screen Reader Announces Login Successful - cherry-pick

.circleci/config.yml, Makefile, e2e/cypress/tests/support/api/cloud_default_config.json, e2e/cypress/tests/support/api/on_prem_default_config.json, e2e/playwright/support/server/default_config.ts, package-lock.json, package.json, packages/types/src/config.ts, plugins/products.ts, types/products.d.ts, webpack.config.js
Cherry-pick of #11355
https://mattermost.atlassian.net/browse/MM-46275
https://mattermost.atlassian.net/browse/MM-46979
https://mattermost.atlassian.net/browse/MM-46981
https://mattermost.atlassian.net/browse/MM-47588
https://github.com/mattermost/mattermost-server/pull/21537
https://github.com/mattermost/enterprise/pull/1285
```release-note
NONE
```
=> MM-46275/MM-46979/MM-46981/MM-47588 Production MPA for web app (#11355)

components/admin_console/team_channel_settings/team/details/team_details.tsx
Cherry pick of #11412 on cloud.
/cc  @plant99
```release-note
NONE
```
=> Automated cherry pick of #11412

components/global_header/right_controls/plan_upgrade_button/index.tsx, e2e/cypress/tests/integration/enterprise/cloud/billing/self_hosted_pricing_modal_spec.js, e2e/playwright/support/server/default_config.ts, packages/types/src/config.ts
Cherry pick of #11442 on release-7.5.
/cc  @ConorMacpherson
```release-note
NONE
```
=> Automated cherry pick of #11442

components/advanced_create_post/advanced_create_post.tsx
Cherry pick of #11492 on release-7.5.
```release-note
NONE
```
=> Automated cherry pick of #11492

components/app_bar/__snapshots__/app_bar.test.tsx.snap, components/app_bar/app_bar.test.tsx, package-lock.json, package.json
Manual cherry pick of #11486 
```release-note
```
=> MM-45869-fix-ci: manual cherry pick for release-7.5

e2e/cypress/tests/integration/account_settings/profile/fullname_edit_spec.ts, e2e/cypress/tests/integration/integrations/custom_slash_commands/slash_commands_spec.js, e2e/cypress/tests/integration/integrations/incoming_webhook/attachment_does_not_collapse_spec.ts, e2e/cypress/tests/integration/messaging/mention_autocomplete_overlap_spec.js, e2e/cypress/tests/integration/profile_settings/profile_settings_spec.js
fullname_edit_spec.ts `Promoted`
slash_commands_spec.js `Promoted`
attachment_does_not_collapse_spec.ts `Promoted`
mention_autocomplete_overlap_spec.js `Promoted`
profile_settings_spec.js `Promoted`
```release-note
NONE
```
=> e2e/cypress:test cases promoted

e2e/cypress/tests/integration/account_settings/profile/email_spec.ts, e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js, e2e/cypress/tests/integration/channel/channel_members_rhs_spec.js, e2e/cypress/tests/integration/channel_settings/add_users_to_channel_spec.js, e2e/cypress/tests/integration/files_and_attachments/upload_files_spec.js
fixed profile/email_spec.ts
fixed channel_info_rhs_spec.js
fixed upload_files_spec.js
```release-note
NONE
```
=> e2e/cypress:fixed

components/suggestion/suggestion_list.jsx
Cherry pick of #11212 on release-7.1.
/cc  @AbhinavVihan
```release-note
NONE
```
=> Automated cherry pick of #11212

package-lock.json, package.json
In the context of regular dependency upgrades, this PR upgrades `redux-thunk` to its latest version 2.4.1
| From version | To version | Changelog | Notes |
|--------------|-----------|------------|--------|
| 2.3.0              | 2.4.1          | [changelog](https://github.com/reduxjs/redux-thunk/releases) | The library has been converted to typescript and in general there are typescript improvements. |
https://mattermost.atlassian.net/browse/MM-48045
```release-note
NONE
```
=> [MM-48045] Upgrade redux-thunk to 2.4.1

components/new_channel_modal/new_channel_modal.scss
Cherry pick of #11455 on release-7.5.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #11455

components/at_sum_members_mention/notification_from_members_modal.tsx, components/custom_open_pricing_modal_post_renderer/index.tsx
Cherry pick of #11501 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
=> Automated cherry pick of #11501

components/common/svg_images_components/access_problem_svg.tsx
fixing master build for a [lint error](https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/62280/workflows/d000ab6e-ff75-4b10-8d93-16a528d383c8/jobs/424474) 
```release-note
NONE
```
=> [MM-47222] lint fix

packages/mattermost-redux/src/reducers/entities/users.test.js, packages/mattermost-redux/src/reducers/entities/users.ts
Cherry pick of #11487 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11487

Makefile
Cherry pick of #11544 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #11544

package-lock.json, package.json
Upgrade core-js to its latest version (minor updates):
| From version | To version | Changelog | Notes |
|----------|----------|---------|---------|
| 3.23.3    | 3.26.0 | [changelog](https://github.com/zloirock/core-js/releases) | - |
https://mattermost.atlassian.net/browse/MM-48104
```release-note
NONE
```
=> [MM-48104] upgrade core-js

components/payment_form/gather_intent/gather_intent.test.tsx, components/payment_form/gather_intent/gather_intent_modal.test.tsx, components/payment_form/gather_intent/gather_intent_modal.tsx, components/payment_form/gather_intent/gather_intent_submitted_modal.tsx, package-lock.json
Remove eslint disable added by mistake. 
https://mattermost.atlassian.net/browse/MM-48172
```release-note
NONE
```
=> Remove Eslint Disable Lines

e2e/cypress/tests/integration/accessibility/accessibility_dropdowns_spec.js, e2e/cypress/tests/integration/auth_sso/authentication_1_spec.ts, e2e/cypress/tests/integration/auth_sso/authentication_4_spec.ts, e2e/cypress/tests/integration/auth_sso/hide_create_account_spec.ts, e2e/cypress/tests/integration/channel_sidebar/dm_gm_behaviour_spec.ts, e2e/cypress/tests/integration/channel_sidebar/hotkeys_spec.ts, e2e/cypress/tests/integration/channel_sidebar/sidebar_channel_menu_spec.ts, e2e/cypress/tests/integration/collapsed_reply_threads/following_spec.js, e2e/cypress/tests/integration/enterprise/auth_sso/authentication_spec.js, e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_spec.ts, e2e/cypress/tests/integration/keyboard_shortcuts/ctrl_cmd_k_open_channel_from_global_threads_spec.js, e2e/cypress/tests/integration/keyboard_shortcuts/keyboard_shortcuts_2_spec.js, e2e/cypress/tests/integration/onboarding/existing_email_adress_spec.js, e2e/cypress/tests/integration/onboarding/login_page_link_account_creation_spec.js, e2e/cypress/tests/integration/system_console/site_configuration/link_customization_cloud_spec.js, e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_1_spec.js, e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_2_spec.js, e2e/cypress/tests/support/ui/global_header.js
authentication_1_spec.ts ```fixed```
authentication_4_spec.ts ```fixed```
hide_create_account_spec.ts ```fixed```
auth_sso/authentication_spec.js ```fixed```
existing_email_adress_spec.js ```fixed```
login_page_link_account_creation_spec.js 
link_customization_cloud_spec.js ```fixed```
ink_customization_e20_1_spec.js ```fixed```
link_customization_e20_2_spec.js ```fixed```
```release-note
NONE
```
=> e2e/cypress:fixed authenticaton test cases

components/search/types.ts, components/suggestion/search_user_provider.tsx
Migrate of search_user_provider.jsx" to Typescript
Fixes https://github.com/mattermost/mattermost-server/issues/21090
Fixes https://mattermost.atlassian.net/browse/MM-47079
None
none
```release-note
NONE
```
=> MM-47079: Migrate "components/suggestion/search_user_provider.jsx" to Typescript

e2e/playwright/support/server/default_config.ts
remove deprecated guided channel creation ff
https://mattermost.atlassian.net/browse/MM-47865
https://github.com/mattermost/mattermost-server/pull/21599
n/a
```release-note
NONE
```
=> MM-47865 - remove deprecated guided channel creation ff

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
Cherry pick of #11568 on release-7.5.
```release-note
NONE
```
=> Automated cherry pick of #11568

package-lock.json, package.json
In the context of regular dependency upgrades, this PR is upgrading memoize-one to its latest version:
| From version | To Version | Changelog | Notes |
|-----------|-----------|---------|-----------|
| 5.2.1      | 6.0.0 | [changelog](https://github.com/alexreardon/memoize-one/releases/tag/v6.0.0) | Despite being a major version upgrade, there are no changes in the API, only improvements in types and also a new feature: the clear method for clearing memoize function's cache |
https://mattermost.atlassian.net/browse/MM-48202
```release-note
NONE
```
=> [MM-48202] Upgrade memoize-one to v6.0.0

e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js, e2e/cypress/tests/integration/channel/channel_members_rhs_spec.js, e2e/cypress/tests/integration/enterprise/guest_accounts/guest_popover_ui_spec.ts, e2e/cypress/tests/integration/files_and_attachments/image_link_preview_spec.js, e2e/cypress/tests/integration/integrations/outgoing_webhook/disable_outgoing_webhook_spec.js, e2e/cypress/tests/integration/mark_as_unread/mark_as_unread_spec.js, e2e/cypress/tests/integration/messaging/image_attachment_spec.js, e2e/cypress/tests/integration/messaging/send_message_via_profile_popover_spec.js, e2e/cypress/tests/integration/system_console/session_length_spec.js, e2e/cypress/tests/integration/toast/unread_with_bottom_start_toast_spec.js
channel_info_rhs_spec.js ```fixed```
channel_members_rhs_spec.js ```fixed```
guest_popover_ui_spec.ts ```demoted```
image_link_preview_spec.js ```fixed```
mage_attachment_spec.js ```fixed```
```release-note
NONE
```
=> e2e/Cypress:fixed spec files

components/onboarding_tasks/onboarding_tasks_manager.test.tsx, components/onboarding_tasks/onboarding_tasks_manager.tsx, packages/mattermost-redux/src/selectors/entities/preferences.ts, packages/types/src/config.ts
This PR allows A/B testing for reducing onboarding task list item. With feature flag ON the following three items are not displayed in the onboarding task list
- Download the Desktop and Mobile Apps
- Complete your Profile
- Visit the System Console to configure your workspace
For testing, I have created the following users having different roles in the spinwick server.
| role | user id | password |
|----|----|----|
| admin | admin@admintest.com | admin@admintest.com |
| user | user-1 | User-1@123 |
| guest | muhammad.salman+reduceonboardingguestuser@mattermost.com | muhammad.salman+reduceonboardingguestuser@mattermost.com |
https://mattermost.atlassian.net/browse/MM-47931
- Has server changes (https://github.com/mattermost/mattermost-server/pull/21571)
|  before/feature flag: off | …
=> [MM-47931] a/b test for reduced onboarding task list item

components/onboarding_tasks/onboarding_tasks_manager.test.tsx, components/onboarding_tasks/onboarding_tasks_manager.tsx, packages/mattermost-redux/src/selectors/entities/preferences.ts, packages/types/src/config.ts
Cherry pick of #11526 on cloud.
/cc  @mhd-sln
```release-note
NONE
```
=> Automated cherry pick of #11526

actions/views/onboarding_tasks.ts, components/advanced_create_post/index.ts, components/global_header/right_controls/right_controls.tsx, components/onboarding_tasks/onboarding_tasks_manager.tsx, components/tours/constant.ts, components/tours/hooks.ts, packages/components/src/tour_tip/tour_tip.tsx
Cherry pick of #11561 on cloud.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #11561

components/purchase_modal/index.ts, components/purchase_modal/purchase_modal.tsx
Cherry pick of #11571 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11571

components/common/accordion/accordion.tsx, components/worktemplates/components/menu/use_case.tsx
For a high level understanding of the feature. Please view the parent PR. This PR improves the styling of use-case window based on https://www.figma.com/proto/xS2v61Rlq2DiLG8QF3fIPU/MMO-MVP?node-id=200%3A159143&scaling=min-zoom&page-id=193%3A104002&starting-point-node-id=243%3A163187
https://mattermost.atlassian.net/browse/MM-48027
https://www.loom.com/share/f762eadbcc7641bea820be8c631d42db
```release-note
NONE
```
=> [MM-48027] improve use case window style

packages/mattermost-redux/src/actions/roles.ts, packages/mattermost-redux/src/actions/users.test.js, packages/mattermost-redux/src/actions/users.ts, packages/mattermost-redux/src/actions/users_queries.ts
Cherry pick of #11550 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11550

components/admin_console/billing/billing_subscriptions/index.tsx
Remove all global store's usages from billing_subscriptions/index.tsx
Fixes https://github.com/mattermost/mattermost-server/issues/21367
=> MM-47469: Remove global store usage in billing_subscriptions/index.tsx

components/widgets/menu/menu_items/menu_item.scss, e2e/cypress/tests/integration/channel/leave_and_archive_channel_destructive_spec.ts
e2e for leave and archive channel destructive
Fixes: https://github.com/mattermost/mattermost-server/issues/20951
JIRA: https://mattermost.atlassian.net/browse/MM-46893
None
None
None
```release-note
NONE
```
=> MM-46893 :  e2e for leave and archive channel destructive

components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap, components/admin_console/admin_sidebar/admin_sidebar.tsx
Make OpenID Connect a free feature
https://mattermost.atlassian.net/browse/MM-47384
- Has server changes ([please link here](https://github.com/mattermost/mattermost-server/pull/21556))
```release-note
NONE
```
=> [MM-47384] Make OpenID Connect free for all

components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
Looks like we had two PRs merged that changed the same thing around the same time
```release-note
NONE
```
=> Fix snapshot

components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.tsx.snap, components/add_user_to_channel_modal/add_user_to_channel_modal.test.tsx, components/add_user_to_channel_modal/add_user_to_channel_modal.tsx, components/at_mention/__snapshots__/at_mention.test.tsx.snap, components/at_mention/at_mention.test.tsx, components/at_mention/at_mention.tsx, components/profile_picture/__snapshots__/profile_picture.test.tsx.snap, components/profile_picture/profile_picture.tsx, components/profile_popover/__snapshots__/profile_popover.test.tsx.snap, components/profile_popover/index.ts, components/profile_popover/profile_popover.scss, components/profile_popover/profile_popover.test.tsx, components/profile_popover/profile_popover.tsx, components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap, components/widgets/users/avatar/avatar.tsx, components/widgets/users/avatar/index.ts, components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap, components/widgets/users/avatars/avatars.tsx, sass/components/_links.scss, sass/components/_mentions.scss, sass/components/_popover.scss, sass/components/_post.scss, sass/components/_status-icon.scss, utils/a11y_controller.js, utils/constants.tsx, utils/post_utils.ts, utils/utils.tsx
Cherry pick of #11530 on cloud.
/cc  @cyrilzhang-mm
```release-note
NONE
```
=> Automated cherry pick of #11530

components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
Cherry pick of #11647 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #11647

.circleci/config.yml
Cherry pick of #11626 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #11626

components/admin_console/permission_schemes_settings/permission_schemes_settings.test.tsx, components/admin_console/permission_schemes_settings/permission_schemes_settings.tsx
Cherry pick of #11597 on cloud.
/cc  @mkraft
```release-note
NONE
```
=> Automated cherry pick of #11597

actions/storage.js, actions/storage.test.js, store/index.js
Cherry pick of #11640 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #11640

actions/views/drafts.ts, actions/websocket_actions.jsx, components/advanced_create_post/advanced_create_post.tsx, components/advanced_create_post/index.ts, components/advanced_text_editor/advanced_text_editor.tsx, components/channel_header/index.ts, components/drafts/channel_draft/channel_draft.tsx, components/drafts/drafts_link.tsx, components/drafts/panel/__snapshots__/panel_body.test.tsx.snap, components/drafts/panel/panel_body.scss, components/drafts/panel/panel_body.test.tsx, components/drafts/panel/panel_body.tsx, components/post_priority/post_priority_picker.scss, components/post_priority/post_priority_picker.tsx, components/post_priority/post_priority_picker_item.tsx, components/post_priority/post_priority_picker_overlay.tsx, components/post_view/acknowledgements/post_acknowledgements.tsx, components/search_bar/__snapshots__/search_bar.test.tsx.snap, components/suggestion/suggestion_box/suggestion_box.jsx, components/textbox/textbox.tsx, components/toggle.tsx, packages/mattermost-redux/src/actions/drafts.ts, packages/mattermost-redux/src/selectors/entities/channels.ts, packages/mattermost-redux/src/selectors/entities/posts.ts, packages/types/src/drafts.ts, sass/components/_toggle.scss, sass/responsive/_tablet.scss, selectors/rhs.ts, selectors/storage.ts
Cherry pick of https://github.com/mattermost/mattermost-webapp/pull/11662 on cloud.
/cc @amyblais 
```release-note
NONE
```
=> Manual cherry pick of #11662

components/advanced_create_comment/advanced_create_comment.tsx, components/advanced_create_post/advanced_create_post.tsx, components/drafts/drafts.tsx, i18n/en.json
Cherry pick of #11654 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11654

components/advanced_create_post/advanced_create_post.test.jsx, components/advanced_create_post/advanced_create_post.tsx, components/advanced_create_post/index.ts
Cherry pick of #11704 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11704

components/pricing_modal/content.tsx, i18n/en.json, i18n/en_AU.json
Fix typo in pricing modal from `Dedicated encryption keys 99%` to `Dedicated encryption keys`
https://mattermost.atlassian.net/browse/MM-48798
```release-note
NONE
```
=> [MM-48798] - Typo in pricing modal

package-lock.json, package.json
In the context of regular dependency upgrades, this PR upgrades `concurrently` to its latest version (from 7.3.0 -> 7.6.0). Only fixes and minor changes are in the releases after 7.3.0, no breaking changes.
The library is used in a few scripts like `scripts/build.js` etc. I've ran those scripts locally, to make sure everything works as before.
https://mattermost.atlassian.net/browse/MM-48207
```release-note
NONE
```
=> [MM-48207] Upgrade concurrently - minor version upgrade

.github/workflows/performance-benchmarks.yml
Cherry pick of #11712 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #11712

packages/mattermost-redux/src/reducers/entities/posts.ts
Cherry pick of #11720 on cloud.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #11720

components/admin_console/admin_definition.jsx, e2e/playwright/support/server/default_config.ts, i18n/en.json, packages/types/src/config.ts
See the corresponding server PR for more information on what this setting actually does
https://mattermost.atlassian.net/browse/MM-48120
https://mattermost.atlassian.net/browse/MM-48623
https://github.com/mattermost/mattermost-server/pull/21171
```release-note
NONE
```
=> MM-48120/MM-48623 Add ExperimentalSettings.PatchPluginsReactDOM to the System Console

components/admin_console/admin_definition.jsx, e2e/playwright/support/server/default_config.ts, i18n/en.json, packages/types/src/config.ts
Cherry pick of #11672 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #11672

components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx, i18n/en.json
Cherry pick of #11701 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11701

actions/websocket_actions.jsx
Cherry pick of #11719 on release-7.6.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #11719

sass/components/_mentions.scss
Cherry pick of #11713 on cloud.
/cc  @mkraft
```release-note
NONE
```
=> Automated cherry pick of #11713

components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
Please see description in [JIRA ticket](https://mattermost.atlassian.net/browse/MM-48727).
[JIRA ticket](https://mattermost.atlassian.net/browse/MM-48727)
- Has server changes ([please link here](https://github.com/mattermost/mattermost-server/pull/21781))
```release-note
NONE
```
**QA Steps**
Please see QA steps in [JIRA ticket](https://mattermost.atlassian.net/browse/MM-48727),
=> [MM-48727] Restore license checks for SSO in self-hosted deployments - admin console

components/admin_console/admin_definition.jsx, components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
Cherry pick of #11692 on cloud.
/cc  @plant99
```release-note
NONE
```
=> Automated cherry pick of #11692

components/drafts/drafts.tsx
Cherry pick of #11750 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11750

components/at_mention/at_mention.test.tsx, components/at_mention/at_mention.tsx, sass/components/_mentions.scss
Cherry pick of #11749 on cloud.
/cc  @cyrilzhang-mm
```release-note
NONE
```
=> Automated cherry pick of #11749

actions/views/drafts.ts
Catches errors when deleting drafts. Currently we delete a draft when sending a post, so it will return an error if there does not exist a draft in the server to delete. 
Follow-up ticket created here to limit the number of `deleteDraft` calls being made: [MM-48893](https://mattermost.atlassian.net/browse/MM-48893)
[MM-48889](https://mattermost.atlassian.net/browse/MM-48889)
```release-note
NONE
```
=> [MM-48889] Catch error when attempting to delete draft

actions/views/drafts.ts
Cherry pick of #11738 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11738

webpack.config.js
Cherry pick of #11754 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #11754

components/at_mention/at_mention_group.tsx, components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap, components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap, components/user_group_popover/group_member_list/group_member_list.tsx, components/user_group_popover/user_group_popover.test.tsx, components/user_group_popover/user_group_popover.tsx, sass/components/_mentions.scss
Cherry pick of #11652 on cloud.
/cc  @cyrilzhang-mm
```release-note
NONE
```
=> Automated cherry pick of #11652

components/pricing_modal/content.tsx, components/purchase_modal/purchase_modal.tsx, e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js, i18n/en.json
Cherry pick of #11715 on cloud.
/cc  @emmyni
```release-note
NONE
```
=> Automated cherry pick of #11715

.github/workflows/performance-benchmarks.yml, e2e/cypress/tests/integration/auth_sso/authentication_1_spec.ts, e2e/cypress/tests/integration/auth_sso/authentication_4_spec.ts, e2e/cypress/tests/integration/enterprise/auth_sso/authentication_spec.js, e2e/cypress/tests/integration/onboarding/existing_email_adress_spec.js, e2e/cypress/tests/integration/signin_authentication/login_open_server_spec.js
Enable open server explicitly and remove unnecessary config change
none
```release-note
NONE
```
=> Cypress/E2E: Enable open server explicitly and remove unnecessary config change

components/analytics/activated_users_card/index.tsx, e2e/cypress/tests/integration/enterprise/system_console/reporting/site_statistics_spec.js, e2e/cypress/tests/integration/system_console/reporting/site_statistics_te_spec.js, e2e/cypress/tests/integration/system_console/reporting/team_statistics_spec.js, i18n/en.json, i18n/en_AU.json
Cherry pick of #11770 on release-7.6.
/cc  @mkraft
```release-note
NONE
```
=> Automated cherry pick of #11770

components/activity_and_insights/insights/hooks.ts, components/activity_and_insights/insights/insights.tsx, components/activity_and_insights/insights/insights_header/insights_header.scss, components/activity_and_insights/insights/insights_title/insights_title.tsx
Cherry pick of #11778 on release-7.6.
```release-note
NONE
```
=> Automated cherry pick of #11778

components/pricing_modal/content.tsx, components/pricing_modal/self_hosted_content.tsx, i18n/en.json
Remove duplicate "Advanced compliance management" text in self hosted pricing modal.
https://mattermost.atlassian.net/browse/MM-48823
before:
after:
```release-note
Remove duplicate text in self-hosted pricing modal
```
=> remove duplicate text

webpack.config.js
I'd complain about people missing this during review, but I'm the dummy who basically wrote
```js
if (DONT_DO_THING) {
doThing();
}
```
here, so it's 100% my fault 😛 
https://mattermost.atlassian.net/browse/MM-49053
https://github.com/mattermost/mattermost-webapp/pull/11754
```release-note
NONE
```
=> MM-49053 Fix backwards if statement around MPA initialization

components/admin_console/permission_schemes_settings/permission_schemes_settings.tsx, components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap, components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx, i18n/en.json, packages/mattermost-redux/src/constants/permissions.ts, utils/constants.tsx
A new custom user groups related permission is to be added to server, this PR adds `restore group` permission to admin console.
https://mattermost.atlassian.net/browse/MM-44842
- Has server changes ([please link here](https://github.com/mattermost/mattermost-server/pull/21806/files))
**before**
**after**
```release-note
NONE
```
=> MM-44842: Add restore groups permission to admin console

components/self_hosted_purchase_modal/index.test.tsx, components/self_hosted_purchase_modal/index.tsx
Cherry pick of #11817 on release-7.7.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #11817

components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap, components/post_view/message_attachments/message_attachment/message_attachment.test.tsx, components/post_view/message_attachments/message_attachment/message_attachment.tsx
Cherry pick of #11825 on release-7.7.
/cc  @harshilsharma63
```release-note
NONE
```
=> Automated cherry pick of #11825

components/common/hooks/useControlSelfHostedPurchaseModal.ts, components/pricing_modal/self_hosted_content.tsx
Cherry pick of #11845 on release-7.7.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #11845

components/apps_form/apps_form_component.scss, components/apps_form/apps_form_field/apps_form_field.test.tsx, components/apps_form/apps_form_field/apps_form_field.tsx, components/apps_form/apps_form_field/apps_form_select_field.tsx, components/apps_form/apps_form_field/select_channel_option.tsx, components/apps_form/apps_form_field/select_user_option.tsx, sass/components/_forms.scss
Make channel and user fields support multiselect property, to allow the user to select multiple values in the form
https://github.com/mattermost/mattermost-server/issues/21484
```release-note
App Framework - Make channel and user fields support multiselect property, to allow the user to select multiple values in the form.
```
=> feat: add support for multiselect in users form field

components/apps_form/apps_form_field/select_channel_option.tsx, components/purchase_modal/purchase.scss, components/purchase_modal/purchase_modal.tsx
A few spacing changes for the purchases modal: 
- Change the padding at the top from 20px to 40px
- Move the middle section down so that the "Alternate Payment Options" header starts below "provide your payment details"
- Fix the spacing underneath the "Seats" input box so that when the value 0 is entered, the spacing is still consistent
- Change the font size of "Total" to 14px
https://mattermost.atlassian.net/browse/MM-49263
|----|----|
| <img width="1766" alt="image" src="https://user-images.githubusercontent.com/44761757/208989010-f7b7876c-56f8-46ee-ba93-f12e47ed27c2.png"> | <img width="1768" alt="image" src="https://user-images.githubusercontent.com/44761757/208988939-c7a32db0-ed00-4 …
=> [MM-49263]: Spacing Changes for the Purchases Modal

components/self_hosted_purchase_modal/consequences.tsx, components/self_hosted_purchase_modal/index.test.tsx, components/self_hosted_purchase_modal/self_hosted_purchase_modal.scss, i18n/en.json, utils/constants.tsx, utils/utils.tsx
Cherry pick of #11856 on cloud.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #11856

components/delinquency_modal/delinquency_modal_controller.test.tsx, components/delinquency_modal/useDelinquencyModalController.tsx
Prevent fetch of cloud products in deliquency modal when on self-hosted
https://mattermost.atlassian.net/browse/MM-48963
```release-note
NONE
```
=> [MM-48963] - /cloud/products fails on Self-Hosted (Community)

e2e/cypress/tests/integration/accessibility/accessibility_account_settings_spec.js, e2e/cypress/tests/integration/settings/display/clock_display_mode_spec.js, e2e/cypress/tests/integration/system_console/reporting/team_statistics_spec.js
Failing test on master: https://mattermost-cypress-report.s3.amazonaws.com/282972-onprem-ent-ha-master-mm-ee-test:test/mochawesome.html
**before**:
**after**:
```release-note
NONE
```
=> fix(cypress): a11y account settings test case

components/pricing_modal/starter_disclaimer_cta.tsx, e2e/cypress/tests/integration/enterprise/cloud/billing/after_subscription_spec.js, e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.ts, e2e/cypress/tests/integration/enterprise/cloud/billing/company_information_free_trial_spec.ts, e2e/cypress/tests/integration/enterprise/cloud/billing/notify_admin_spec.ts, e2e/cypress/tests/integration/enterprise/cloud/billing/payment_free_trial_spec.ts, e2e/cypress/tests/integration/enterprise/cloud/billing/subscriptions_free_trial_spec.ts, e2e/cypress/tests/integration/enterprise/cloud/billing/yearly_subscription_spec.js, e2e/cypress/tests/integration/enterprise/self-hosted/self_hosted_pricing_modal_spec.js
Cherry pick of #11391 on cloud.
/cc  @yasserfaraazkhan
```release-note
NONE
```
=> Automated cherry pick of #11391

components/advanced_create_comment/advanced_create_comment.tsx
Cherry pick of #11803 on release-7.7.
```release-note
NONE
```
=> Automated cherry pick of #11803

components/activity_log_modal/components/activity_log.tsx
Manual cherry-pick as the automated one picked up only the tests for this change.
https://mattermost.atlassian.net/browse/MM-49198
https://github.com/mattermost/mattermost-webapp/pull/11854
```release-note
NONE
```
[MM-49198]: https://mattermost.atlassian.net/browse/MM-49198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MM-49198] Fix reported device as desktop when coming from mobile app

components/common/hooks/useControlSelfHostedPurchaseModal.ts, components/purchase_in_progress_modal/index.test.tsx, components/purchase_in_progress_modal/index.tsx, components/self_hosted_purchase_modal/constants.ts, components/self_hosted_purchase_modal/index.tsx
Cherry pick of #11895 on release-7.7.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #11895

packages/client/src/client4.ts
Cherry pick of #11873 on release-7.7.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #11873

actions/notification_actions.test.js, components/admin_console/admin_definition.jsx, components/permalink_view/permalink_view.test.tsx, components/suggestion/switch_channel_provider.test.jsx, packages/mattermost-redux/src/actions/channels.test.js, packages/mattermost-redux/src/actions/posts.test.js, packages/mattermost-redux/src/actions/preferences.test.js, packages/mattermost-redux/src/actions/teams.test.js, packages/mattermost-redux/src/actions/users.test.js, packages/mattermost-redux/src/selectors/entities/channel_categories.test.ts, packages/mattermost-redux/src/selectors/entities/channels.test.ts, packages/mattermost-redux/src/selectors/entities/preferences.ts, utils/post_utils.test.jsx
Cherry pick of #11706 on release-7.7.
/cc  @vish9812
```release-note
NONE
```
=> Automated cherry pick of #11706

components/admin_console/admin_definition.jsx, components/admin_console/billing/plan_details/feature_list.tsx
Cherry pick of #11799 on release-7.7.
```release-note
NONE
```
=> Automated cherry pick of #11799

components/air_gapped_self_hosted_purchase_modal/content.scss
Cherry pick of #11869 on cloud.
/cc  @kostaspt
```release-note
NONE
```
=> Automated cherry pick of #11869

components/new_channel_modal/new_channel_modal.tsx
Cherry pick of #11876 on cloud.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #11876

e2e/cypress/save_report.js
Removed Chai assertion which causing Cypress Pipeline failure
```release-note
NONE
```
=> Removed chai assert from Save Report

components/onboarding_tasklist/onboarding_tasklist.tsx
Cherry pick of #11901 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11901

e2e/cypress/tests/integration/interactive_dialog/demo_boolean_spec.ts
This test completes the steps outlined in https://github.com/mattermost/mattermost-server/issues/18176, except for checking in the iOS and Android apps.
@saturninoabril _How do I go about writing a test for the iOS/Android apps (for example, do I need to add them to the webapp repository)?_
Web-app E2E test with Cypress for: https://github.com/mattermost/mattermost-server/issues/18176
N/A as of now.
N/A
```release-note
NONE
```
=> MM-T2503 Boolean value check

e2e/cypress/tests/integration/channel_sidebar/unread_filter_spec.ts
This test goes over the steps outlined in https://automation-test-cases.vercel.app/test/MM-T5208. 
Web-app E2E test with Cypress for: https://github.com/mattermost/mattermost-server/issues/21387
N/A as of now.
N/A
```release-note
NONE
```
=> MM-T5208 - Continue to show global Threads item when unread filter is enabled

components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap, i18n/i18n.jsx
Cherry pick of #11911 on cloud.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #11911

components/admin_console/team_channel_settings/line_switch.tsx, sass/components/_line-switch.scss
Cherry pick of #11933 on cloud.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #11933

components/post_priority/post_priority_picker_item.tsx
Cherry pick of #11940 on cloud.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #11940

components/preparing_workspace/preparing_workspace.scss, components/root/root.tsx
Cherry pick of #11947 on cloud.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #11947

components/advanced_create_comment/advanced_create_comment.tsx, components/advanced_create_post/advanced_create_post.tsx
Cherry pick of #11849 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11849

components/activity_and_insights/insights/insights.tsx, components/activity_and_insights/insights/top_boards/top_boards.tsx, components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx
Cherrypick of https://github.com/mattermost/mattermost-webapp/pull/11922
https://mattermost.atlassian.net/browse/MM-49515
```release-note
NONE
```
=> [MM-49515] Show board insights for boards 'product' 

components/activity_and_insights/insights/insights.tsx, components/activity_and_insights/insights/top_boards/top_boards.tsx, components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx
Cherrypick of https://github.com/mattermost/mattermost-webapp/pull/11922
https://mattermost.atlassian.net/browse/MM-49515
```release-note
NONE
```
=> [MM-49515] Show board insights for boards 'product'

e2e/cypress/tests/integration/accessibility/accessibility_account_settings_spec.js, e2e/cypress/tests/integration/enterprise/accessibility/accessibility_input_fields_spec.js, e2e/cypress/tests/integration/notifications/channel_links_show_as_links_spec.js, e2e/cypress/tests/support/ui/account_settings_modal.js, e2e/cypress/tests/support/ui/global_header.js
Cherry pick of #11877 on release-7.7.
```release-note
NONE
```
=> Automated cherry pick of #11877

webpack.config.js
Cherry pick of #11960 on cloud.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #11960

components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap, components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx, components/global_header/left_controls/product_menu/__snapshots__/product_menu.test.tsx.snap, components/global_header/left_controls/product_menu/product_menu.tsx, components/global_header/right_controls/at_mentions_button/__snapshots__/at_mentions_button.test.tsx.snap, components/global_header/right_controls/at_mentions_button/at_mentions_button.tsx, components/global_header/right_controls/plan_upgrade_button/index.tsx, components/global_header/right_controls/saved_posts_button/__snapshots__/saved_posts_button.test.tsx.snap, components/global_header/right_controls/saved_posts_button/saved_posts_button.tsx, components/global_header/right_controls/settings_button/settings_button.tsx, components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap, components/status_dropdown/status_dropdown.tsx, i18n/en.json
Cherry pick of #11812 on release-7.7.
/cc  @cyrilzhang-mm
```release-note
NONE
```
=> Automated cherry pick of #11812

components/drafts/drafts_link/drafts_tour_tip/drafts_tour_tip.tsx, components/post_priority/post_priority_badge.tsx
fixes broken build due to merged code-quality branch: #11100 
n/a
- broken branch: https://github.com/mattermost/mattermost-webapp/pull/11100
- related pipieline: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/66228/workflows/7d78e04b-9b18-4b7f-81b9-44a50f8d1d35
webapp build on local succeeds
```release-note
NONE
```
=> fixes build due to merged tag feature

webpack.config.js
In my dev env, one second wasn't sufficient.
=> Bump product wait timeout to 5 seconds

components/admin_console/feature_discovery/__snapshots__/feature_discovery.test.tsx.snap, components/admin_console/feature_discovery/feature_discovery.tsx, components/admin_console/license_settings/trial_banner/trial_banner.tsx, components/cloud_start_trial/request_business_email_modal.tsx, components/feature_restricted_modal/feature_restricted_modal.tsx, components/learn_more_trial_modal/learn_more_trial_modal_step.tsx, components/onboarding_tasklist/onboarding_tasklist_completed.tsx, components/pricing_modal/start_trial_caution.tsx, components/start_trial_modal/index.tsx, i18n/bg.json, i18n/de.json, i18n/en.json, i18n/en_AU.json, i18n/es.json, i18n/fa.json, i18n/fr.json, i18n/hu.json, i18n/it.json, i18n/ja.json, i18n/ko.json, i18n/nl.json, i18n/pl.json, i18n/pt-BR.json, i18n/ro.json, i18n/ru.json, i18n/sv.json, i18n/tr.json, i18n/zh-CN.json, i18n/zh-TW.json, utils/constants.tsx
Updates links referencing the Software License Agreement, found in:
- Pricing modal
- System console
- Professional / Enterprise features in System Console
- Features inside the product that lead to trial activation
- Trial modals
From the old link: https://mattermost.com/software-evaluation-agreement to the new link: https://mattermost.com/pl/software-and-services-license-agreement
[MM-49645](https://mattermost.atlassian.net/browse/MM-49645) / [MM-49646](https://mattermost.atlassian.net/browse/MM-49646)
```release-note
NONE
```
[MM-49645]: https://mattermost.atlassian.net/browse/MM-49645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MM-49646]: https://mattermost.atlassian.net/browse/MM-49646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
=> MM-49645 - Update Software Evaluation Links to use the new Software And Services License Agreement Link

components/pricing_modal/self_hosted_content.tsx
Cherry pick of #12032 on cloud.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #12032

components/team_sidebar/components/team_button.tsx
Cherry pick of #11967 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11967

components/admin_console/admin_console.test.tsx, components/admin_console/admin_console.tsx, components/admin_console/index.ts, components/header_footer_route/header_footer_route.scss, sass/base/_structure.scss
Cherry pick of #11867 on cloud.
/cc  @kostaspt
```release-note
NONE
```
=> Automated cherry pick of #11867

components/pricing_modal/pricing_modal.scss
Cherry pick of #11937 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
=> Automated cherry pick of #11937

components/root/root.tsx
Cherry pick of #12045 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #12045

sass/base/_structure.scss
Cherry pick of #11920 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11920

components/size_aware_image.jsx, components/size_aware_image.test.jsx, e2e/cypress/tests/integration/files_and_attachments/image_link_preview_spec.js, e2e/cypress/tests/integration/messaging/image_attachment_spec.js, sass/components/_files.scss, sass/layout/_markdown.scss
Cherry pick of #11804 on cloud.
/cc  @Roy-Orbison
```release-note
NONE
```
=> Automated cherry pick of #11804

sass/components/_suggestion-list.scss
Cherry pick of #12030 on cloud.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #12030

components/user_groups_modal/__snapshots__/user_groups_modal.test.tsx.snap, components/user_groups_modal/user_groups_list/__snapshots__/user_groups_list.test.tsx.snap, components/user_groups_modal/user_groups_list/user_groups_list.tsx, components/user_groups_modal/user_groups_modal.scss, components/user_groups_modal/user_groups_modal.tsx
Cherry pick of #11884 on cloud.
/cc  @Afsoon
```release-note
NONE
```
=> Automated cherry pick of #11884

components/work_templates/components/customize.tsx, components/work_templates/components/menu.tsx, components/work_templates/components/preview.tsx, components/work_templates/index.tsx, utils/constants.tsx
Add telemetry except for all the ones in "After creation" of this document: https://www.figma.com/file/xS2v61Rlq2DiLG8QF3fIPU/MMO-MVP?node-id=668%3A174151&t=jggkxeunzSTKNin3-0
https://mattermost.atlassian.net/browse/MM-48003
N/A
N/A
```release-note
NONE
```
=> [MM-48003] Work Templates: add telemetry

components/team_controller/team_controller.tsx
Cherry pick of #12022 on release-7.8.
```release-note
NONE
```
=> Automated cherry pick of #12022

components/file_preview_modal/file_preview_modal.scss, components/pdf_preview.jsx
Cherry pick of #11934 on release-7.8.
```release-note
NONE
```
=> Automated cherry pick of #11934

components/widgets/inputs/dropdown_input_hybrid.scss
Fixing style for data retention time selector
https://mattermost.atlassian.net/browse/MM-48788
```release-note
NONE
```
[MM-48788]: https://mattermost.atlassian.net/browse/MM-48788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MM-48788] Fixing style for data retention form selectors

components/drafts/panel/panel_header.scss
Cherry pick of #12111 on release-7.8.
```release-note
NONE
```
=> Automated cherry pick of #12111

components/common/hooks/useCanSelfHostedSignup.ts
This reverts commit 2002c1e6361985cceb34b35f46c55ff1acd37d18. Plan is to revert the manually cherry-picked commit with this pr, and then do another PR that re-applies the needed cherry-pick.
https://mattermost.atlassian.net/browse/MM-50049
```release-note
NONE
```
=> Revert "merge in fix to not contact portal if on team edition"

components/common/hooks/useCanSelfHostedSignup.ts, components/pricing_modal/self_hosted_content.tsx, components/self_hosted_purchase_modal/index.tsx
Cherry pick of #12046 on release-7.8.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #12046

components/product_notices_modal/product_notices_modal.tsx
Cherry pick of #12076 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #12076

components/activity_and_insights/insights/hooks.ts, components/activity_and_insights/insights/insights.tsx
Cherry pick of #12105 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #12105

components/post/user_profile.tsx
Fix e2e tests related to clicking username on message posted by bot
Fixes https://github.com/mattermost/mattermost-server/issues/22237
Fixes https://mattermost.atlassian.net/browse/MM-50295
To be provided
```release-note
NONE
```
=> MM-50295: Fix e2e tests related to clicking username on message posted by bot

sass/components/_suggestion-list.scss
Cherry pick of #12096 on cloud.
/cc  @kostaspt
```release-note
NONE
```
=> Automated cherry pick of #12096

components/post/index.tsx, components/post/post_component.tsx, components/post/user_profile.tsx, e2e/cypress/tests/support/ui/post.ts, sass/components/_post.scss
This PR fixes some UI bugs and e2e test failures that got introduced after merging the post component refactor. 
https://mattermost.atlassian.net/browse/MM-50169
https://mattermost.atlassian.net/browse/MM-50196
https://mattermost.atlassian.net/browse/MM-50205
https://mattermost.atlassian.net/browse/MM-50319
```release-note
Fix post component related errors
```
=> Fix post component merge errors and bugs

components/post_priority/post_priority_badge.tsx, components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap, components/threading/global_threads/thread_item/thread_item.scss, components/threading/global_threads/thread_item/thread_item.tsx
fixes overlapping username and tags section in threads view
[MM-49854](https://mattermost.atlassian.net/browse/MM-49854)
[MM-49867](https://mattermost.atlassian.net/browse/MM-49867) (dupe)
n/a
n/a
```release-note
NONE
```
[MM-49854]: https://mattermost.atlassian.net/browse/MM-49854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MM-49867]: https://mattermost.atlassian.net/browse/MM-49867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bugfix: MM-49854

components/post_priority/post_priority_badge.tsx, components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap, components/threading/global_threads/thread_item/thread_item.scss, components/threading/global_threads/thread_item/thread_item.tsx
Cherry pick of #12124 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #12124

components/suggestion/switch_channel_provider.jsx, sass/components/_suggestion-list.scss
Fix tag, custom status position in channel switcher
Fixes https://mattermost.atlassian.net/browse/MM-49976
NA
|----|----|
| <img width="630" alt="image-20230125-195438" src="https://user-images.githubusercontent.com/16203333/216259489-58df01f4-e804-4b1b-b354-38f633717b93.png"> | <img width="633" alt="Screenshot 2023-02-02 at 2 20 05 PM" src="https://user-images.githubusercontent.com/16203333/216275939-9e48cdbf-4036-482b-833c-fd2783727a6b.png"> |
```release-note
* Fix tag, custom status position in channel switcher
```
=> MM-49976: Fix tag, custom status position in channel switcher

components/advanced_create_comment/advanced_create_comment.tsx, components/advanced_create_post/advanced_create_post.tsx
Cherry pick of #12107 on release-7.8.
/cc  @koox00
```release-note
NONE
```
=> Automated cherry pick of #12107

components/post/post_options.tsx
Cherry pick of #12155 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #12155

components/suggestion/switch_channel_provider.jsx
Cherry pick of #11930 on release-7.8.
```release-note
NONE
```
=> Automated cherry pick of #11930

components/suggestion/switch_channel_provider.jsx, sass/components/_suggestion-list.scss
Cherry pick of #12120 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #12120

components/__snapshots__/generic_modal.test.tsx.snap, components/delete_category_modal/delete_category_modal.tsx, components/edit_category_modal/edit_category_modal.tsx, components/menu/menu.tsx, components/more_direct_channels/__snapshots__/more_direct_channels.test.tsx.snap, components/more_direct_channels/more_direct_channels.tsx, packages/components/src/generic_modal/generic_modal.tsx
Cherry pick of #12128 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #12128

components/post/index.tsx, components/post/post_component.tsx, components/post/post_options.tsx, components/rhs_header_post/index.ts, packages/mattermost-redux/src/selectors/entities/preferences.ts, selectors/drafts.ts
Adds a feature flag to disable tour tips for Rainforest testing.
- **Drafts Tour Tip**
- **RHS Viewing a Thread Tour Tip**
- **Post Actions Tour Tip**
*See https://community.mattermost.com/core/pl/b4pwu6jeb3n7pkejqcci5uy7fh for further context.*
https://mattermost.atlassian.net/browse/MM-50349
- Has server changes https://github.com/mattermost/mattermost-server/pull/22263
```release-note
NONE
```
=> [MM-50349] Add Feature Flag to Disable Tour Tips

components/post/index.tsx, components/post/post_component.tsx, components/post/post_options.tsx, components/rhs_header_post/index.ts, packages/mattermost-redux/src/selectors/entities/preferences.ts, selectors/drafts.ts
Cherry pick of #12167 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #12167

components/rhs_header_post/index.ts, packages/mattermost-redux/src/selectors/entities/preferences.ts, selectors/drafts.ts
Cherry-pick https://github.com/mattermost/mattermost-webapp/pull/12167
```release-note
```
=> Feature flag to disable the drafts tour tip

actions/channel_actions.ts, components/interactive_dialog/dialog_element/dialog_element.tsx, components/post_view/message_attachments/action_menu/action_menu.tsx, components/suggestion/generic_channel_provider.tsx
Migrate components/suggestion/generic_channel_provider.jsx to typescript
Fixes https://github.com/mattermost/mattermost-server/issues/21095
Fixes https://mattermost.atlassian.net/browse/MM-47074
NONE
NONE
NONE
```release-note
NONE
```
=> [MM-47074] : Migrate "components/suggestion/generic_channel_provider.jsx" to Typescript

.github/workflows/ci.yml
- Fix docker build tag
```release-note
NONE
```
=> fix: docker build tag

scripts/utils.js
Change webpack output for Boards from red to blue so it looks less like errors.
NONE
```release-note
NONE
```
=> Change webpack output for Boards from red to blue

.github/workflows/performance-benchmarks.yml
Cherry pick of #12215 on cloud.
/cc  @phoinixgrr
```release-note
NONE
```
=> Automated cherry pick of #12215

components/apps_form/apps_form_container.tsx
Cherry pick of #11707 on cloud.
```release-note
NONE
```
=> Automated cherry pick of #11707

components/admin_console/billing/plan_details/plan_details.tsx, i18n/en.json
Cherry pick of #12209 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
=> Automated cherry pick of #12209

e2e/cypress/tests/integration/channel_sidebar/dm_gm_filtering_sorting_spec.ts, e2e/cypress/tests/integration/enterprise/cloud/billing/company_information_free_trial_spec.ts, e2e/cypress/tests/integration/enterprise/cloud/billing/notify_admin_spec.ts, e2e/cypress/tests/integration/enterprise/profile_popover/profile_popover_spec.js
=> chore(cypress): fix cloud tests

components/admin_console/billing/billing_subscriptions/index.tsx, e2e/cypress/tests/integration/system_console/workspace_deletion_spec.js
Cherry pick of #12217 on cloud.
/cc  @ConorMacpherson
```release-note
NONE
```
=> Automated cherry pick of #12217

components/common/hooks/useControlSelfHostedPurchaseModal.ts
Cherry pick of #12218 on cloud.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #12218

e2e/cypress/tests/integration/channel_sidebar/dm_gm_filtering_sorting_spec.ts, e2e/cypress/tests/integration/enterprise/cloud/billing/company_information_free_trial_spec.ts, e2e/cypress/tests/integration/enterprise/cloud/billing/notify_admin_spec.ts, e2e/cypress/tests/integration/enterprise/profile_popover/profile_popover_spec.js
Cherry pick of #12226 on cloud.
/cc  @yasserfaraazkhan
```release-note
NONE
```
=> Automated cherry pick of #12226

.github/workflows/performance-benchmarks.yml
Cherry pick of #12235 on cloud.
/cc  @phoinixgrr
```release-note
NONE
```
=> Automated cherry pick of #12235

actions/cloud.tsx, components/purchase_modal/index.ts
Cherry pick of #12242 on cloud.
/cc  @neallred
```release-note
NONE
```
=> Automated cherry pick of #12242

components/menu/sub_menu.tsx
=> Fix type check for 'sub_menu' file

components/post/post_component.tsx, package-lock.json
This PR addresses bug fixes related to the post component refactor. One is a class mismatch on post threads in compact message view, and the other is adding back the channel header name for all RHS screens.
https://mattermost.atlassian.net/browse/MM-50775
https://mattermost.atlassian.net/browse/MM-50475
```release-note
Post component bug fixes
```
=> [MM-50475][MM-50775] - Post component fixes

components/profile_popover/profile_popover.scss, components/profile_popover/profile_popover.tsx
Automatic Merge
Cherry-pick https://github.com/mattermost/mattermost-webapp/pull/12254
Fixes https://mattermost.atlassian.net/browse/MM-50561
```release-note
* Add email in profile popover
```
=> Add email in profile popover

components/post/post_component.tsx, package-lock.json
Reverts mattermost/mattermost-webapp#12272
=> Revert "[MM-50475][MM-50775] - Post component fixes (#12265)"

components/custom_status/custom_status_modal.tsx, components/post/user_profile.tsx, components/post_view/post_header_custom_status/post_header_custom_status.tsx
=> Cherry pick MM-50798 and MM-50321

components/post/post_component.tsx, package-lock.json
Cherry pick https://github.com/mattermost/mattermost-webapp/pull/12265
```release-note
NONE
```
cc/ @amyblais
=> Cherry pick [MM-50475][MM-50775] - Post component fixes 

package-lock.json, package.json, packages/client/package.json, packages/types/package.json
Cherry-pick of https://github.com/mattermost/mattermost-webapp/pull/12283
https://github.com/mattermost/mattermost-webapp/pull/12283
```release-note
NONE
```
=> Update subpackage versions to 7.9.0 (#12283)

sass/components/_post.scss
Cherry pick of https://github.com/mattermost/mattermost-webapp/pull/12291
```release-note
NONE
```
=> Cherry pick of #12291

NOTICE.txt
Cherry-pick of https://github.com/mattermost/mattermost-webapp/pull/12294
```release-note
NONE
```
=> Update NOTICE.txt (7.9)

e2e/playwright/support/server/default_config.ts, packages/types/src/config.ts
Adds a feature flag configuration value `SelfHostedExpansion`.
[MM-51019](https://mattermost.atlassian.net/browse/MM-51019)
```release-note
NONE
```
[MM-51019]: https://mattermost.atlassian.net/browse/MM-51019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MM-51019 - Add a Feature Flag for In-Product Expansion

components/dot_menu/post_reminder_submenu.tsx, components/post_markdown/index.ts, components/post_markdown/post_markdown.tsx, components/post_markdown/system_message_helpers.tsx, components/status_dropdown/status_dropdown.tsx
cherry pick (#12306)
```release-note
NONE
```
=> cherry-pick-MM-51032

components/profile_popover/__snapshots__/profile_popover.test.tsx.snap, components/profile_popover/index.ts, components/profile_popover/profile_popover.test.tsx, components/profile_popover/profile_popover.tsx, components/profile_popover_call_button/index.tsx, components/profile_popover_call_button/profile_popover_call_button.tsx, plugins/call_button/call_button.scss, plugins/call_button/call_button.tsx
Cherry-pick of #12080 on `release-7.9`
```release-note
NONE
```
=> MM-49808 Cherry-pick 

sass/components/_post.scss
Cherry-pick of https://github.com/mattermost/mattermost-webapp/pull/12286 to release-7.9
https://mattermost.atlassian.net/browse/MM-50803
https://github.com/mattermost/mattermost-webapp/pull/12286
```release-note
NONE
```
=> MM-50803 Fix restore post modal styles applying to other modals

sass/components/_post.scss
Cherry pick of #12303 on release-7.9.
```release-note
NONE
```
=> Cherry pick of #12303

components/post/post_component.tsx, i18n/en.json
Change the text
https://mattermost.atlassian.net/browse/MM-51031
N/A
N/A
```release-note
NONE
```
=> [MM-51031] Fix header text

components/post/post_component.tsx, i18n/en.json
Cherry pick of #12309 on release-7.9.
```release-note
NONE
```
=> Cherry pick of 12309

components/channel_move_to_sub_menu/index.tsx, components/menu/menu.tsx, components/menu/menu_item.tsx, components/menu/sub_menu.tsx, components/sidebar/sidebar_category/sidebar_category.tsx, components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx, components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx, components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
Cherry pick of 
https://mattermost.atlassian.net/browse/MM-50281
https://mattermost.atlassian.net/browse/MM-50286
https://mattermost.atlassian.net/browse/MM-50322
- https://github.com/mattermost/mattermost-webapp/pull/12126
- https://github.com/mattermost/mattermost-webapp/pull/12269
none
```release-note
NONE
```
=> Cherry pick of MM-50281,  PR-12269

sass/responsive/_tablet.scss
Automatic Merge
cherry-pick https://github.com/mattermost/mattermost-webapp/pull/12331
```release-note
NONE
```
=> [MM-51009] - Remove redundant CSS rule for timestamps in compact mode (#12331)

e2e/playwright/support/browser_context.ts
Fixed storage state path
```release-note
NONE
```
=> Playwright/E2E: fix storage state path
